### ISSUE TITLE
Add Magnesium Extras to Known compatability issues

### ISSUE THREAD

**Issue by Niketats** [nonamecrackers2/crackers-wither-storm-mod#1]
To play with Magnesium Extras you need to disable "Entity Distance", cuz this setting cause same issues as:
![image](https://user-images.githubusercontent.com/68917520/167470174-12f26ee4-2059-4fee-b102-ce65b3c05d56.png)

**Comment by nonamecrackers2** [comment]
It appears to only affect the top issue, however I've added it to the list

**Comment by NinjaSam5399** [comment]
First issue

**Comment by myron-obsolete-account** [comment]
> First issue

ok and
