### ISSUE TITLE
Optifine compatibility

### ISSUE THREAD

**Issue by ColdNSs** [nonamecrackers2/crackers-wither-storm-mod#100]
1.18.2 Optifine
Looking slightly above the wither storm will cause it to disappear (stop rendering)
This issue only exists when optifine is loaded

**Comment by ColdNSs** [comment]
If you are on the ground then it is not a big problem
but if you are too close to its head when being picked up by the tracktor beam then you can't see its head

**Comment by ColdNSs** [comment]
nvm I just found out that it is a already known issue
But still, please fix this

**Comment by Loverxzc** [comment]
It is impossible for the author to fix this trouble. Optifine changes the "construction" of the entity renderer, so the author cannot fix it.

**Comment by nonamecrackers2** [comment]
I'm not able to as this is something optifine internally changes with how the game renders entities. You should try bugging optifine about this.
