### ISSUE TITLE
Issue 1000!

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1000]
Woo how cool, 1000 issues are here now! Congratulations I guess?

_What am I even doing_

**Comment by Pandaboi25x** [comment]
Atleast recomend smth lol

**Comment by nonamecrackers2** [comment]
I like the enthusiasm but please don’t open blank issues

**Comment by myron-obsolete-account** [comment]
> I like the enthusiasm but please don’t open blank issues

:(
