### ISSUE TITLE
1.19.3 craftable cmd block support?

### ISSUE THREAD

**Issue by KeshaGvozd** [nonamecrackers2/crackers-wither-storm-mod#1001]
when

**Comment by myron-obsolete-account** [comment]
There is a mod that makes the command block craftable: https://modrinth.com/mod/craftcmdblock (as the guy who made this mod I can say that it might not work in 1.19.3)
alternatively just use a withered beacon and 3 wither skeleton skulls

**Comment by nonamecrackers2** [comment]
Command blocks will not be made craftable in the mod, especially since they cannot be broken by default in survival, etc.

**Comment by myron-obsolete-account** [comment]
> Command blocks will not be made craftable in the mod, especially since they cannot be broken by default in survival, etc.

Just copy my method duh
![image](https://user-images.githubusercontent.com/53058491/223496913-0cc23dd3-fcef-432f-8b91-8944b5f2904d.png)
I don't think it should be too performance impacting when checking for a modded command block every tick, eh?

**Comment by nonamecrackers2** [comment]
Regardless, I don’t really want to mess with the vanilla mechanics of the command block.
