### ISSUE TITLE
Possibly a cracker food item as a gag?

### ISSUE THREAD

**Issue by Bloxxify1520** [nonamecrackers2/crackers-wither-storm-mod#1003]
**Description of feature**
i thought of this while eating saltine crackers, dont ask. 

So my suggestion is about your entire brand, added into your mod for a funny, a cracker food item. The way to craft it would be to have 2 wheat, 1 placed in the middle left, one on the middle right, and then 1 thing of sugar in the middle middle. Not the most accurate craft (but bread recipe isnt all that accurate either.) The texture would be the image used in your YT profile picture, maybe a bit more pixelated to fit minecraft texture. this is something i thought of randomly this is really something i randomly thought of and dont really care if its rejected or not.

**Comment by myron-obsolete-account** [comment]
That'd be cool.

**Comment by nonamecrackers2** [comment]
Would be a funny gag lmao but I don’t really want to add items with no purpose. Maybe april fools?

**Comment by myron-obsolete-account** [comment]
> Would be a funny gag lmao but I don’t really want to add items with no purpose. Maybe april fools?

How about you change all (or almost all) of the sounds into meme sound effects? Roaring could be the man screaming meme and the WS ambience could be elevator waiting music

And last but not least: the debris rings could also rotate around the x and z axis, for the ultimate chaos! :D

**Comment by Bloxxify1520** [comment]
> Would be a funny gag lmao but I don’t really want to add items with no purpose. Maybe april fools?

I think that it would be a funny thing to add just to keep, many mods i play random things in it (Alexs mobs has a Smitty Werben Jager Man Jensen #1 hat, Spongebob reference, it has a chance of 0.1 to spawn from a skelewag. When i was making this i thought it would be a nice inside joke for people that know about your icon, if its not added thats fine with me.

**Comment by Bloxxify1520** [comment]
Didnt mean to link issue number 1

**Comment by NinjaSam5399** [comment]
Cracker's Cracker Mod
