### ISSUE TITLE
Withered Sickened Iron Golem

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#1004]
I don't know if you're gonna add this. But, can you add a sickened golem as well, it'd be cool and also it should be summoned by a symbiont as well.

**Comment by NinjaSam5399** [comment]
Cool Suggestion

**Comment by Resuster** [comment]
Thanks @NinjaSam5399

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
