### ISSUE TITLE
[Question] What is the witherstorms ID?

### ISSUE THREAD

**Issue by Ultrover** [nonamecrackers2/crackers-wither-storm-mod#1005]
Using the "/witherstormmod phase set [BLANK] 4" I'm not sure what to put for the witherstorms ID so I can change its phase with a command.

**Comment by Globalfirestorm10** [comment]
the full command is this:
/witherstormmod phase set @e[type=witherstormmod:wither_storm,limit=1] 4
If you want to change it to other phases, change the 4 to the number you want, it can be 0-7
hope this helps!
