### ISSUE TITLE
SEVERE LAG IN 7th stage

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#1006]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3

**Mod version**
3.2

when the WS reaches the final stage, THERE IS SEVERE LAG!!!!!

**To Reproduce**
1. Wait for WS to reach phase7
2. Experience the lag

**Crash Reports / Logs**
No crashes

**Is OptiFine installed?**
No OptiFine

**Screenshots**

https://user-images.githubusercontent.com/125754458/224134581-5edcaa03-85e4-4cde-845a-9b5433b892e6.mp4

**Comment by Globalfirestorm10** [comment]
Can I see your mod list? it might be other mods. Perhaps also consider testing your wifi speed?

**Comment by humzahre** [comment]
worldedit and cwsm.

**Comment by Globalfirestorm10** [comment]
also, are you sure that the "lag" you are talking about is your fps? Perhaps that could be it? Consider lowering down your render distance as well

**Comment by watersofnazareth** [comment]
What are your specs @humzahre?

**Comment by myron-obsolete-account** [comment]
> also, are you sure that the "lag" you are talking about is your fps? Perhaps that could be it? Consider lowering down your render distance as well

I have a way larger render distance set (24 chunks) and it runs fine at 50-60 FPS, and my guess is that humzahres render distance is around 8 chunks. Only possible reason I can think of is that they either have way to many other things running open in the background or they just have a not-made-for-gaming-PC.

**Comment by nonamecrackers2** [comment]
What kind of lag are you experiencing? Server side or client side?

**Comment by humzahre** [comment]
client

**Comment by nonamecrackers2** [comment]
Is this the case when you look away from the wither storm?

**Comment by humzahre** [comment]
looking away OR at it

**Comment by nonamecrackers2** [comment]
Considering that they're now banned from this repo, I will be closing this issue

**Comment by Globalfirestorm10** [comment]
Wait you banned them? Damn.

**Comment by myron-obsolete-account** [comment]
> Considering that they're now banned from this repo, I will be closing this issue

They might just have a bad computer and thats why it's lagging so much, considering that the WS in 3.2 is heavily optimized.

**Comment by nonamecrackers2** [comment]
Probably, there could also be some mod compatibility issue here at play, however can't request any more information

**Comment by ScreamingMC** [comment]
Yet still, the mod was running on a touchscreen dell laptop with integrated intel graphics at 40-60 fps
