### ISSUE TITLE
How do I craft the amulet (for all the possible variants)

### ISSUE THREAD

**Issue by anonymoususer923847** [nonamecrackers2/crackers-wither-storm-mod#1007]
Title.

**Comment by Globalfirestorm10** [comment]
hey, mind joining the discord for asking questions? trust me, you'll probably get a much faster response there than here. That aside,   I, unfortunately, don't know the recipe. Consider using JEI, as it's one of the most useful mods out there. Once you've installed JEI and loaded into a world,  press e, search amulet, then scroll to the amulet, and press r to view the recipe. Assuming you have no conflicting keybindings, the recipe should pop up. 

here's the link:https://www.curseforge.com/minecraft/mc-mods/jei

hope this helps
