### ISSUE TITLE
More devastating to creatures other than the player

### ISSUE THREAD

**Issue by Composer-Hu** [nonamecrackers2/crackers-wither-storm-mod#1008]
Until now, I have found that the degree of topographic damage and biological destruction caused by wither storm has been loss of balance. For the destruction of creatures, custom AI behavior causes the wither skull shot by the wither storm to fail to hit the target at all before the head can fire a tractor beam.

In the phase 4 and beyond, wither storm will cause increasing damage to the terrain and can be further enhanced by settings. But at this time there will be an embarrassing situation:
In the case of its oppressive theme song and various strong effect sound effects,in the event of constant and severe damage to the terrain,the creatures being dragged will only slowly approach the wither storm,it is not aimed at the target and falls out of the light as the head moves, even with the storm constantly moving the targeted target will also be abandoned because it cannot reach the mouth of the wither storm for a long time.

Cite the example of MCSM:The flight speed of the sucked in in the Jesse scenario is very slow,just like the towing speed now.Any other entity is quickly inhaled, this is the difference between a protagonist and a supporting character. In theory, watch for devastating effectsand fairness are compatible, the player acts as the protagonist in the game, being targeted will only slowly rise, entities other than the player should be quickly swept into the storm and destroyed.

At the same time, the cooldown time of the wither storm shoot flaming wither skull is a little too long. with custom AI behavior turned on, most creatures can quickly escape, at this time, it is necessary to launch the skull more frequently for large-scale destruction of distant targets, as in the case of a bridge being blown up in MCSM (pre-blocking of roads).

By The Way：English is not my native language, please forgive me for grammatical errors！

**Comment by myron-obsolete-account** [comment]
I don't think mobs should be sucked in faster than players, because in the end everyone's the same: a living organism that tries to escape. I mean, what priorities should other mobs have? To die faster? Poor little creatures! It would look weird to see mobs getting beamed up faster than now too anyways so eh. Let's see what Crackers opinion is.

**Comment by Composer-Hu** [comment]
> 

All right,  just wait for Cracker's opinion

**Comment by Globalfirestorm10** [comment]
I dislike this idea heavily,as moron said, all mobs are technically living organisms, so why should the storm be more a of a threat to some over others? It honestly makes no sense imo

**Comment by BluePineappleGuy** [comment]
I think though it may not make sense it really adds to the atmosphere of the wither storm, just watching countless mobs get flung into the storm while running for your life, but doesn't make the tractor beams impossible to counter. Another cool effect for atmosphere is mobs in tractor beams are spinning as they go.
