### ISSUE TITLE
Crash after summoning?

### ISSUE THREAD

**Issue by PillowQueso** [nonamecrackers2/crackers-wither-storm-mod#1009]
**Minecraft version**
1.19.2

**Mod version**
1.19.2

**Describe the bug**
When I Summon the wither storm and after then explosion, little after the wither goes up it crashes

**To Reproduce**
1. summon wither storm
2. wait a little when jus summon
3. after it explosion it goes up
4. crashes

**Crash Reports / Logs**
https://pastebin.com/aLrBv3zx

**Is OptiFine installed?**
Yes, Same version

**Comment by myron-obsolete-account** [comment]
Turn off block cluster coloring to make OptiFine shaders work. Alternatively I suggest the combination of Rubidium and Oculus both for 1.19.2 to use shaders while 1. not having the known optifine rendering issues and 2. to be able to keep block cluster coloring on

**Comment by PillowQueso** [comment]
> Turn off block cluster coloring to make OptiFine shaders work. Alternatively I suggest the combination of Rubidium and Oculus both for 1.19.2 to use shaders while 1. not having the known optifine rendering issues and 2. to be able to keep block cluster coloring on

does block cluster color work if i remove optifine?

**Comment by myron-obsolete-account** [comment]
> does block cluster color work if i remove optifine?

You don't need optifine when using Rubidium and Oculus

**Comment by myron-obsolete-account** [comment]
And yes it does work if you remove it.

**Comment by humzahre** [comment]
I agree with Mo Ro N. Try usting the mods Rubidium and oculus to make shaders work PROPERLY.

**Comment by nonamecrackers2** [comment]
As MoRoN already stated, you'll need to disable Block Cluster Coloring if you want to use shaders in the version you're playing.

**Comment by myron-obsolete-account** [comment]
> As MoRoN already stated, you'll need to disable Block Cluster Coloring if you want to use shaders in the version you're playing.

or use Rubidium and Oculus

**Comment by nonamecrackers2** [comment]
You will still need to disable block cluster coloring with rubidium/oculus, this bug occurs with any mod that adds shader support

**Comment by myron-obsolete-account** [comment]
> You will still need to disable block cluster coloring with rubidium/oculus, this bug occurs with any mod that adds shader support

For me it worked fine while having block cluster coloring on.

**Comment by humzahre** [comment]
oh ok nonamecrackers2.. instead of fixing optifine bugs, you MADE THEM WORSE
