### ISSUE TITLE
Hero of the village effect after killing the ws 

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1010]
I know that some villagers might be dead already after killing the storm.. unless you keep them in your basement  but uh "words spread fast" right? *if possible make the hero of the village effect make the villagers trade require less emeralds or any other stuff they wanna trade  when trading plus make the effect longer*

:jess:

**Comment by Globalfirestorm10** [comment]
I like the idea of getting a buffed version of the "hero of the village" effect when you kill the storm

**Comment by BluePineappleGuy** [comment]
maybe a new effect called something like 'world hero' or 'global hero'? hostile mobs in the overworld could become neutral for you because you saved them from being eaten by the WS, but would not apply to end or nether mobs, as they had no idea of the wither storms existence. also includes effects of hero of the village

**Comment by Globalfirestorm10** [comment]
> maybe a new effect called something like 'world hero' or 'global hero'? hostile mobs in the overworld could become neutral for you because you saved them from being eaten by the WS, but would not apply to end or nether mobs, as they had no idea of the wither storms existence. also includes effects of hero of the village

That might be a little too OP, if this were to happen, it would be for a certain amount of time

**Comment by BluePineappleGuy** [comment]
> > maybe a new effect called something like 'world hero' or 'global hero'? hostile mobs in the overworld could become neutral for you because you saved them from being eaten by the WS, but would not apply to end or nether mobs, as they had no idea of the wither storms existence. also includes effects of hero of the village
> 
> That might be a little too OP, if this were to happen, it would be for a certain amount of time

i guess it could last for about 20 MC days, or the effect could only be obtained through the 4-tier (and 4 support beacon)  withered beacon and only in a 10 block radius
Edit: actually 10 blocks is pretty much useless anyway so i guess maybe 100 blocks so it actually is a reward

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
