### ISSUE TITLE
Amulet In Abandoned House

### ISSUE THREAD

**Issue by SFusion** [nonamecrackers2/crackers-wither-storm-mod#1012]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**
You could make the amulet be placed inside one of the barrels in the Abandoned House

**Comment by myron-obsolete-account** [comment]
Could be a good idea for a config option.

**Comment by nonamecrackers2** [comment]
I won't be making it spawn in the house since that's giving a fairly powerful item to players for free at the beginning of the game. Feel free to modify the structure file and make a datapack that adds it though.
