### ISSUE TITLE
Make Tentacles Attack mobs/players

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#1013]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Can you make the tentacles attack mobs and players? Almost like MCSM?

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by TheEyeOfGaming** [comment]
#12

**Comment by myron-obsolete-account** [comment]
#12

**Comment by myron-obsolete-account** [comment]
Also as far as my common sense has evolved I don't think you can code something like that without being like the best programmer in the world or something.
