### ISSUE TITLE
Wither Storm disappears during death animation

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1014]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2

**Mod version**
2.2

**Describe the bug**
Wither Storm disappears during death only showing heads and tentacles

**Comment by myron-obsolete-account** [comment]
This is a known issue and already has been reported (#939) please close this as this is a duplicate
