### ISSUE TITLE
Game crashes a little after spawning the storm with Server Performance - Smooth Chunk Save

### ISSUE THREAD

**Issue by SmoothWolf20** [nonamecrackers2/crackers-wither-storm-mod#1015]
**Minecraft version**
1.19.3

**Mod version**
3.2

**Describe the bug**
After spawning the storm with SP installed, the game freezes, then crashes maybe 10 seconds after. These mods together worked on the version before. I would just play without it but it helps my FPS drastically.

**To Reproduce**
Simply install Server Performance with the WS Mod, then start a world and summon the storm, wait a little bit and the game will freeze then crash.

Not using Optifine

**Comment by GrandmaPork** [comment]
This is because the game needs to create the bowels

**Comment by myron-obsolete-account** [comment]
Dude you need to decide for one. Does the game crash or does the world freeze?

**Comment by Globalfirestorm10** [comment]
> **Minecraft version**
> 
> 1.19.3
> 
> 
> 
> **Mod version**
> 
> 3.2
> 
> 
> 
> **Describe the bug**
> 
> After spawning the storm with SP installed, the game freezes, then crashes maybe 10 seconds after. These mods together worked on the version before. I would just play without it but it helps my FPS drastically.
> 
> 
> 
> **To Reproduce**
> 
> Simply install Server Performance with the WS Mod, then start a world and summon the storm, wait a little bit and the game will freeze then crash.
> 
> 
> 
> Not using Optifine

Two things
1. Mind sending the crash report? That would be very useful, as it's hard to determine what the issue could be when it's not available
2. Mind sending the link to the mod?

**Comment by SmoothWolf20** [comment]
> > **Minecraft version**
> > 1.19.3
> > **Mod version**
> > 3.2
> > **Describe the bug**
> > After spawning the storm with SP installed, the game freezes, then crashes maybe 10 seconds after. These mods together worked on the version before. I would just play without it but it helps my FPS drastically.
> > **To Reproduce**
> > Simply install Server Performance with the WS Mod, then start a world and summon the storm, wait a little bit and the game will freeze then crash.
> > Not using Optifine
> 
> Two things
> 
> 1. Mind sending the crash report? That would be very useful, as it's hard to determine what the issue could be when it's not available
> 2. Mind sending the link to the mod?

Now I'm not so sure, I tested one last time on a new world to see if it would work and it did, I guess it doesn't matter now...
