### ISSUE TITLE
Bigger late phase 5

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1017]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Bigger phase 5.5/late 5 so it matches with MCSM.

**ONLY ONE FEATURE REQUEST PER ISSUE**

Images: 

![CrackerPhase5 5](https://user-images.githubusercontent.com/109185503/224528094-f08523c9-bbe8-498f-a9ed-9a5911271fa5.svg)
![Witherbody3](https://user-images.githubusercontent.com/109185503/224528105-fdc9ce8e-4e49-43dd-8c22-6f549d9c8448.svg)

**Comment by Honey-Programming** [comment]
The images might not load correctly so follow these steps:

1. Click on the area below “images:” to see the current texture.
2. Click on the bottom of the textbox/info area to see the texture suggested.



Credit to @happykid48 for textures

**Comment by Composer-Hu** [comment]
Do you mean to modify the model?

**Comment by myron-obsolete-account** [comment]
Cracker said he wont make new models/make changes to models so this has an extremely low chance of being accepted. Also not everything has to be the same as in MCSM. Infact I think the "bigbrain" from MCSM looks way more ugly than the one Crackers made. It's what makes his mod so unique.

**Comment by WitherBean** [comment]
> Cracker said he wont make new models/make changes to models so this has an extremely low chance of being accepted. Also not everything has to be the same as in MCSM. Infact I think the "bigbrain" from MCSM looks way more ugly than the one Crackers made. It's what makes his mod so unique.

Why do you think that the model is more ugly?

**Comment by myron-obsolete-account** [comment]
> Why do you think that the model is more ugly?

![image](https://user-images.githubusercontent.com/53058491/224557877-36503c14-86d2-4b49-bbe8-90b389a5d0ff.png)

**Comment by WitherBean** [comment]
I just think that the MCSM one is more flat.

**Comment by Composer-Hu** [comment]
> 我只是认为MCSM更平坦。

That's right, the MCSM is more oppressive.

**Comment by myron-obsolete-account** [comment]
Okay whatever lets wait for Crackers opinion

**Comment by TheEyeOfGaming** [comment]
i like this suggestion, but i doubt crackers gonna accept it.

**Comment by Honey-Programming** [comment]
The MCSM model is more jagged

**Comment by Honey-Programming** [comment]
> > Why do you think that the model is more ugly?
> 
> ![image](https://user-images.githubusercontent.com/53058491/224557877-36503c14-86d2-4b49-bbe8-90b389a5d0ff.png)

You’re kinda right

**Comment by Honey-Programming** [comment]
But still even if the MCSM model is not added I suggest make the current one bigger

**Comment by Honey-Programming** [comment]
> Cracker said he wont make new models/make changes to models so this has an extremely low chance of being accepted. Also not everything has to be the same as in MCSM. Infact I think the "bigbrain" from MCSM looks way more ugly than the one Crackers made. It's what makes his mod so unique.

The “bigbrain” that you are talking about is just a subphase and looks like this:

![Witherbody2](https://user-images.githubusercontent.com/109185503/224608775-3f555407-7c24-4966-b9e2-b18e561068af.svg)

**Comment by Composer-Hu** [comment]
> > Cracker表示，他不会制作新模型/更改模型，因此被接受的可能性极低。也不是所有的东西都必须与MCSM相同。事实上，我认为MCSM的“大脑袋”看起来比饼干做的更丑。这就是他的模组如此独特的原因。
> 
> 你说的“大脑袋”只是一个子阶段，看起来像这样：
> 
> ![Witherbody2](https://user-images.githubusercontent.com/109185503/224608775-3f555407-7c24-4966-b9e2-b18e561068af.svg)

I think the width of the top is the most important source of oppression, changing it like this I feel more like the redstonenia form in MCSM.

**Comment by Honey-Programming** [comment]
The reason I suggest this is because the MCSM model looks like the whole body is extending up and outwards while the CWSM looks like a big fat blob

**Comment by Honey-Programming** [comment]
Cracker's late 5 is almost the same as this subphase from MCSM:

![Subphase bigbrain2](https://user-images.githubusercontent.com/109185503/224864630-1b38897a-b2e2-40f3-babd-09d04ef54e54.svg)

**Comment by nonamecrackers2** [comment]
Model changes to make the mod more accurate to MCSM are against the guidelines and won’t be happening
