### ISSUE TITLE
Phase 4 - 7 more often explosive skulls [Higher use of explosive skulls]

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1018]
I have noticed that the Wither Storm Phase 4 - 7 doesn't shoot skulls as often as it feels like it should. I am not talking about the black and blue skulls, because I don't think it would fit phase 4-7, but allowing it to shoot flaming skulls more often (NOT PHASE 0 - 3). It would allow the wither storm to have an alternative attack other than the standard tractor beam. This would also be more accurate to MC: Story Mode, but as a feature it would add to the intensity. You could also add a configuration for it as well.

**Comment by Composer-Hu** [comment]
I'm very much in favor of this idea, maybe like this #1008?

**Comment by Globalfirestorm10** [comment]
I like this idea, as it shows that the storm has overall gotten more powerful.

**Comment by nonamecrackers2** [comment]
Closing since a config option has been added that makes this possible

**Comment by IndigoAmethyst** [comment]
Looking back it's probably fine as it is but at atleast I can create total havoc with the config
