### ISSUE TITLE
WS music stops being intense when wither storm doesn't attack.

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1019]
So when the wither storm is focused on something else, or it just revives from the formidibomb, play less intense music like G, H-B, H-C and H-D in this playlist I put together. 
https://downloads.khinsider.com/playlist/2482kafi

**Comment by myron-obsolete-account** [comment]
What is that website you linked

**Comment by IndigoAmethyst** [comment]
its a site that has video game soundtracks

**Comment by BluePineappleGuy** [comment]
personally i think it should still be intense when it revives but when you are safer from the wither storm it should be less intense

**Comment by nonamecrackers2** [comment]
I think how the music system is currently is fine and does not need changing
