### ISSUE TITLE
The nether portal

### ISSUE THREAD

**Issue by lugamerbox** [nonamecrackers2/crackers-wither-storm-mod#1020]
Can you add that if the wither storm is in (said radius) he will do that breaking portal animation just like in story mode!

**Comment by myron-obsolete-account** [comment]
#993

**Comment by FrozenDragon0** [comment]
Already been suggested and has been denied.

**Comment by Globalfirestorm10** [comment]
Tbh, I feel like me, moron, and frozendragon should all be able admins (or whatever role is close to this) for this github, as we're kinda the most active on these issues.

**Comment by Asteroid4** [comment]
> Tbh, I feel like me, moron, and frozendragon should all be able admins (or whatever role is close to this) for this github, as we're kinda the most active on these issues.

that does feel correct.

**Comment by nonamecrackers2** [comment]
#49
