### ISSUE TITLE
Optifine with a simple shader

### ISSUE THREAD

**Issue by lugamerbox** [nonamecrackers2/crackers-wither-storm-mod#1021]
when i ry to play the mod with optifine and a simple shader called Vplus or any other shader is crashes and says something abou "void"

**Comment by myron-obsolete-account** [comment]
Known issue, deactivate block cluster rendering or use Rubidium and Oculus for shaders if you are playing on 1.19.2

**Comment by V0calgiant12** [comment]
Correction to what MoRon said, turn off block cluster coloring in the client config of CWSM, found in the options menu as the purple W

**Comment by nonamecrackers2** [comment]
> Correction to what MoRon said, turn off block cluster coloring in the client config of CWSM, found in the options menu as the purple W
