### ISSUE TITLE
Shootable Flaming Wither Skulls

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1022]
Make the flaming wither skulls breakable.

For example if the player shoots one, it would have a chance blow up without hitting the floor and there could be particles when it blows up. If it makes any sounds when it is broken, it should make a shattering sound.

**Comment by myron-obsolete-account** [comment]
I don't quite understand this. Do you want to be able to shoot a flaming wither skull or do you want to be able to destroy them?

**Comment by WitherBean** [comment]
Destroy them with an arrow.
