### ISSUE TITLE
Better pulsing/enderman ripping

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1023]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
When the WS is in the final stage, blocks will pulse white. The suggestion is when blocks pulse white they will reveal some hidden flesh inside.

Images of flesh:

![Pulses](https://user-images.githubusercontent.com/109185503/224598928-cd3b31af-a299-4c96-ab46-fb13dce53e0c.svg)

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Honey-Programming** [comment]
Note that this is a little hard to see on PC

**Comment by Aimyx** [comment]
good idea, don't know about how they would pull of the remembering where it pulses, so they could switch the texture out though.

**Comment by Honey-Programming** [comment]
This is how I think it would work. As the blocks rip, there is a texture for each ripped phase like lightly ripped, ripped, and heavily ripped.

**Comment by Honey-Programming** [comment]
Texture of "heavily ripped":

![Witherstorm EnderTorn (2)](https://user-images.githubusercontent.com/109185503/229417246-d6205d95-699d-4754-8ff2-f98d35dc3444.svg)

Note that this is from my MCSM Wither Storm game and the hole should be in the middle instead of the bottom.

**Comment by myron-obsolete-account** [comment]
> Texture of "heavily ripped":
> 
> ![Witherstorm EnderTorn (2)](https://user-images.githubusercontent.com/109185503/229417246-d6205d95-699d-4754-8ff2-f98d35dc3444.svg)
> 
> Note that this is from my MCSM Wither Storm game and the hole should be in the middle instead of the bottom.

why are you calling those things textures

**Comment by Honey-Programming** [comment]
because they are

**Comment by nonamecrackers2** [comment]
With how the current system works this wouldn't be possible, and rewriting it is not in my best interests
