### ISSUE TITLE
Endermen spawn with tainted blocks on final stage

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#1025]
To give the illusion of endermen stealing blocks off of the wither storm, I think it’d be very cool if *only* when then hole is open, endermen spawn with tainted flesh blocks. Another option would be for endermen to be enraged, and then teleport somewhere random but now holding a tainted block and passive but that’s probably difficult

**Comment by bensonb3** [comment]
hm that its a good idea

**Comment by myron-obsolete-account** [comment]
I have a feeling that this has been suggested or atleast mentioned somewhere else before but I forgot where and who...

**Comment by GrandmaPork** [comment]
Yeah probably so but it’s been a while so I thought I’d bring it up again. I checked guidelines and didn’t find anything

**Comment by Asteroid4** [comment]
dont just check guidlines, search all of the issues.

**Comment by GrandmaPork** [comment]
There are 1000+ issues my dude

**Comment by V0calgiant12** [comment]
That's what the search bar is for my guy. Search for key words that would be relevant to the feature. Then make sure you check both opened and closed issues

**Comment by GrandmaPork** [comment]
Ah I see now, thanks #235

**Comment by nonamecrackers2** [comment]
There is a lot of issues so it's understandable
