### ISSUE TITLE
Low priority: sub-phases

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#1026]
I think it’s a good sign when the only suggestions you get are those that are small nitpicks. Great mod

somewhere down the line, I’d like to see extra phases or “sub-phases” between phases up until phase 5. The jump from phase four to five is just a little much in my opinion. If I were to make the phases, this is how’d I’d have it:
0
0.3 (very little covering)
0.6 (some covering)
1
2
3
4
4.5 (not much on top)
5 (and so on)

If/when you do this, I’d like to see extra phases passed normal ones but in an addon if lag becomes an issue. Also, if you were to adjust phase 3 at all, I’d just make it so the bottom tentacle is on the side and facing down like it is in phase 4. These of course are all nitpicks because your mod is basically perfect

**Comment by Jackmo2207** [comment]
Might be too much but I think there should be a phase 2.3 where the command block is covered, 2.6 where it adds a single tentacle, 2.9 where it has 2 tentacles, and phase 3 adds the last one

**Comment by Asteroid4** [comment]
This has already been suggested

**Comment by GrandmaPork** [comment]
Most likely but I couldn’t find one

**Comment by Asteroid4** [comment]
#316
