### ISSUE TITLE
Enderman torn stage

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1027]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Instead of a hole appearing when the evolution is complete, create a texture that is a little smaller than the seventh stage and then add the hole.

Texture:

![WitherStorm EnderTorn](https://user-images.githubusercontent.com/109185503/224863886-1ff4f9b5-a677-4e59-a6ac-97cfe8bfa70c.svg)

compared to this from the current textures:

![CrackerPhase7](https://user-images.githubusercontent.com/109185503/224864055-456b6df2-2258-4628-8bd8-e8e393999450.svg)

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
I think the current texture/system is fine as is and doesn't need changing
