### ISSUE TITLE
changeable color night glare color thing

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1028]
pretty much like the tractor beam color changer but night glare version
*do i need to tell more? its pretty self explaining in the title*

if this was already suggested tell me :waa:

:jess:

**Comment by myron-obsolete-account** [comment]
The night glare texture is white as I could see in the files, if that even was the nightglare texture. Could/should be possible to add a coloring kind of thing like for foilage textures of grass leaves etc. (theyre grayscale too)

**Comment by myron-obsolete-account** [comment]
Let me actually just quickly smash a list of things that should be colorable here:

- tractor beams (already colorable but still in the list duh)
- night glare thing
- the tractor beam overl- okay nvm you can change it by texture
- the little overlay thing thats in the body hole which makes its inside kinda look like magenta-ish, indicating that the bowels are in there
- the uhhhhhhhhhhhh the ummmm sky darkening effect
- something else idk

**Comment by NinjaSam5399** [comment]
Cool idea

**Comment by Pandaboi25x** [comment]
> Let me actually just quickly smash a list of things that should be colorable here:
> 
> * tractor beams (already colorable but still in the list duh)
> * night glare thing
> * the tractor beam overl- okay nvm you can change it by texture
> * the little overlay thing thats in the body hole which makes its inside kinda look like magenta-ish, indicating that the bowels are in there
> * the uhhhhhhhhhhhh the ummmm sky darkening effect
> * something else idk

im not sure what to say but the only thing that comes in mind is *ok*

**Comment by Pandaboi25x** [comment]
*stressfuly watching crackers close and add misc to other suggestions*

**Comment by Pandaboi25x** [comment]
Cool a misc

**Comment by NinjaSam5399** [comment]
Like This: 
![image](https://user-images.githubusercontent.com/111523734/227059971-84d29e81-9328-40eb-8f2b-cbd888a85584.png)

**Comment by NinjaSam5399** [comment]
Ignore the leftovers of purple glare.

**Comment by NinjaSam5399** [comment]
Accepted ✅

**Comment by LocalWaterCreeper911911** [comment]
Looks like a new update is coming.

**Comment by Pandaboi25x** [comment]
https://media.discordapp.net/attachments/1068133497623023626/1096806702172614656/20230402_232258.gif

**Comment by Pandaboi25x** [comment]
![20230402_232258](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/be12ec04-19d0-42f2-9e67-57e723dd4534)

**Comment by Steve982950** [comment]
This may add a Dramatic effect at night

**Comment by nonamecrackers2** [comment]
Forgot to close this lol, has been implemented

**Comment by Pandaboi25x** [comment]
> Forgot to close this lol, has been implemented

lol

**Comment by Steve982950** [comment]
> ![20230402_232258](https://user-images.githubusercontent.com/121638798/238692704-be12ec04-19d0-42f2-9e67-57e723dd4534.gif) [ ![20230402_232258](https://user-images.githubusercontent.com/121638798/238692704-be12ec04-19d0-42f2-9e67-57e723dd4534.gif) ](https://user-images.githubusercontent.com/121638798/238692704-be12ec04-19d0-42f2-9e67-57e723dd4534.gif) [ ](https://user-images.githubusercontent.com/121638798/238692704-be12ec04-19d0-42f2-9e67-57e723dd4534.gif)

wot? XDDDD
