### ISSUE TITLE
1.19.4 version..?

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#1029]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Maybe port to 1.19.4? i havent thought of any extra tings yet but i will**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
1.19.4 was just released, and Forge for 1.19.4 is not even released. It will come.

**Comment by humzahre** [comment]
when forge 1.19.4 is released, do it plz

**Comment by humzahre** [comment]
btw It already released in beta
