### ISSUE TITLE
Optifine shaders unload the WS torso in general as well as tractorbeam disappearing

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#1030]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3

**Mod version**
3.2

**When I use Optifine Complementary shaders, the torso unloads**

**To Reproduce**
1. Install Optifine
2.Get Compimentary shaders (not sure about other shaders)
3. The torso will unload

**Crash Reports / Logs**
No crashes

**Is OptiFine installed?**
OptiFine Is installed

**Screenshots**
![2023-03-14_19 33 45](https://user-images.githubusercontent.com/125754458/225117300-b9cec4a1-f929-485f-9377-932b896a19c8.png)

**Comment by humzahre** [comment]
fix in new 1.19.4 update (if possible)

**Comment by nonamecrackers2** [comment]
#972

**Comment by humzahre** [comment]
NOT KILLING THE WS! with OF shaders, the body unloads EVEN When its alive

**Comment by humzahre** [comment]
look at the heads CAREFULLY

**Comment by humzahre** [comment]
they arent looking up and there is NO DEBRIS falling

**Comment by TeaCupsTeaPots** [comment]
yeah i think this is a separate issue not a duplicate because i've only gotten this when the ws was dying and that was with and without optifine

**Comment by humzahre** [comment]
at least teacups understands.

**Comment by myron-obsolete-account** [comment]
@nonamecrackers2 thats a different issue...
