### ISSUE TITLE
Wither Storm Improved Attacks 

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1031]
Every time the Wither Storm starts attacking an entity, a hidden value is rolled that determines what attack it uses. Let's call this the Attack Value (AV). Every phase is coded to have a max AV listed here:

Phase 0 - 50
Phase 1 - 80
Phase 2 - 100
Phase 3 - 110
Phase 4 - 250
Phase 5A - 250
Phase 5B - 270
Phase 6 - 270
Phase 7A - 280
Phase 7B - 280

Each Phase also has a minimum value (This is so there isn't a Phase 4 Wither Storm shooting regular wither skulls):

Phase 0 - 0
Phase 1 - 0
Phase 2 - 35
Phase 3 - 35
Phase 4 - 111
Phase 5A - 111
Phase 5B - 111
Phase 6 - 111
Phase 7A - 141
Phase 7B - 141

- Standard Skulls: WS flies to random spot within 10 blocks of the target, flies 7 blocks above the ground, stops moving until attack is over, and rapidly fires black wither skulls (10% of which are blue wither skulls.), and stops after 20 seconds or the target gets 25 blocks away from it. (AV= 0 - 40)

- Hunchback Flaming Skulls: The Wither Storm turns off its tractor beam, moves directly 4 blocks in front of the target, and shoots 1-3 flaming skulls. (AV= 41 - 70)

- Body Charge: The wither storm charges at the entity with great force, temporally disabling their shield. (AV= 71- 80)

- Hunchback Tractor Beam: The WS uses its tractor beam, slowly pulling its target, if the target hits the head 1-3 times, the head is temporarily disabled. (AV= 81 - 100)

- Hunchback tentacle: A random one of the 3 tentacles (all with separate hitboxes that work similar to the tractor beams), attacks in the same way the tentacle entity used in the bowels does. (AV= 100 - 110) 

- Flaming Skulls: The Wither Storms tractor beams turn off, and the wither storm shoots 4-10 flaming skulls at its target with a 1 second cooldown. (AV= 111 - 140)

- Tractor Beam: A random wither storm head uses its tractor beam to pick up the target (This is already fine as it is in the mod) (AV= 141 - 210)

- Tentacle: The wither storm flies near to the ground and uses its tentacles in the same way as the hunchback Wither Storm, however much quicker and hard-hitting, as well as being able to lift the target much higher, with more hits needed to temporary disable. It can also be used to breakdown any block that isn't unbreakable. (AV= 211 - 250)

- Large Tentacle: The wither storm uses one of its large tentacles to attack the target. Deals much more damage and needs to take more hits to disable. (AV= 251 - 270)

- Flaming Skull Rapid Fire: The WS shoots 10-40 flaming skulls all over the place at the direction of the target with tiny cooldown between each shot. (AV= 271 - 280)

Thank you for reading and considering. I would be grateful if you consider adding anything listed.

**Comment by IndigoAmethyst** [comment]
I think this might be to much lol

**Comment by Asteroid4** [comment]
I think more varied attacks is a good idea, and the way attack value would work seems like a good idea.

**Comment by IndigoAmethyst** [comment]
Yar

**Comment by BluePineappleGuy** [comment]
also the block clusters should not be able to contain obsidian unless a large tentacle hits it, in which case it becomes a block cluster flung out of place into the storm.

**Comment by Asteroid4** [comment]
The more I think about it, the more i realize this being implemented turns the wither storm from a "make sure you're far away" to a "stay away at all costs". Also, what about the segments?

**Comment by IndigoAmethyst** [comment]
My original thought was the segments could attack separately from the main WS and the other segment. But I am not really sure.

**Comment by Asteroid4** [comment]
That makes sence.

**Comment by GoldSlimeling91** [comment]
This is cool but personally to make it not feel like a living hell to be near the WS, just add a cooldown between each attack roll the wither does and disable attacking at all for the fight with the Symbiont, otherwise this is a great idea and adds variety to the Storm.

**Comment by IndigoAmethyst** [comment]
Also, phases 2 and 3 need to have there hitboxes fixed

**Comment by nonamecrackers2** [comment]
Going to be closing this, reading over this again a lot of this wouldn't fit in very well and would being extremely game changing.
