### ISSUE TITLE
Storymode Accurate Bowels hole

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#1032]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Can you make minecraft storymode accurate witherstorm bowels hole??

**ONLY ONE FEATURE REQUEST PER ISSUE**

![witherstorm mod - Search and 2 more pages - Profile 1 - Microsoft​ Edge 14_03_2023 22_11_24](https://user-images.githubusercontent.com/125754458/225154125-e3deb1d8-d312-48ad-9bc8-976d45eae84b.png)

**Comment by humzahre** [comment]
pls do the best u can currently do! :)

**Comment by GrandmaPork** [comment]
He’s already said he wouldn’t because this isn’t meant to be a 1 to 1 recreation of the wither storm

**Comment by FrozenDragon0** [comment]
This isn't meant to be a 1:1 recreation of the Story mode Witherstorm.

**Comment by nonamecrackers2** [comment]
Please read the guidelines

**Comment by myron-obsolete-account** [comment]
Bro my brain hurts. Literally everywhere has been stated that the WS will not/is not supposed to be a 1:1 replica of the MCSMWS, yet you made this suggestion. Also why aren't you happy that the current models look good? They do look good. Actually better than in MCSM. This feels like you are not appreciating nonamecrackers2's work. What am I even mad at lmao

**Comment by humzahre** [comment]
ALSO THIS IS 1 FEATURE ONLY TO CHANGE THE MODELS OF WS TO LOOK ACCURATE

**Comment by humzahre** [comment]
😭😭😭😭😭😭😭😭😭PLEASEEE DO IT!

**Comment by humzahre** [comment]
it could make me happy!

**Comment by FrozenDragon0** [comment]
> WELL I WANT IT TO BE A 1:1 RECREATION

It's not going to happen.

**Comment by ThatB0i** [comment]
> WELL I WANT IT TO BE A 1:1 RECREATION

bro thinks modding eazy

**Comment by humzahre** [comment]
> Bro my brain hurts. Literally everywhere has been stated that the WS will not/is not supposed to be a 1:1 replica of the MCSMWS, yet you made this suggestion. Also why aren't you happy that the current models look good? They do look good. Actually better than in MCSM. This feels like you are not appreciating nonamecrackers2's work. What am I even mad at lmao

IM NOT HAPPY WITH THE CURRENT MODELS! IT'S GOTTA BE P̷̤̪̯̬̲͌̍̽͜È̴̡̡̹̬̻̼̳̘͉̬̰͇͇̥͗̈́ͅR̶̩̝̮̩̠̋̎̈́́́͗̕F̸̟͙̩̫̱̜̻̙̌̏̈̐̒̃̃̅̚͝͠E̴̫̻͐̌̕Ċ̶̘͓͙̪͈́̍̽͗͑̈́̈́͗̓̕͜͝T̸̢̢͈̞̘̳̼̩̰̼̄̿̒̎̉́̕͘͠!

**Comment by humzahre** [comment]
ok fine i understand.... can u at least make the bowels hole in the right place??

**Comment by myron-obsolete-account** [comment]
> ok fine i understand.... can u at least make the bowels hole in the right place??

it looks better where it is right now trust me

**Comment by humzahre** [comment]
ok i agree with u for once. i just wanted it to be a bit lower so i could reach it better

**Comment by FrozenDragon0** [comment]
> ok i agree with u for once. i just wanted it to be a bit lower so i could reach it better

The hole is easy enough to reach in it's current place, just load a crossbow with an enderpearl.

**Comment by myron-obsolete-account** [comment]
> ok i agree with u for once. i just wanted it to be a bit lower so i could reach it better

lower the flying height...

**Comment by humzahre** [comment]
ok...?

**Comment by GrandmaPork** [comment]
you can easily reach the hole after allowing yourself to be beamed up

**Comment by myron-obsolete-account** [comment]
true

**Comment by humzahre** [comment]
hmm.. a bit dangerous but ok!

**Comment by nonamecrackers2** [comment]
Forgot to link the duplicate issue: #268
