### ISSUE TITLE
how do you get the update?

### ISSUE THREAD

**Issue by bensonb3** [nonamecrackers2/crackers-wither-storm-mod#1033]
how do you get the  update?

**Comment by Pandaboi25x** [comment]
https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod/files/4407369 now close this issue thing lol

**Comment by myron-obsolete-account** [comment]
> how do you get the update?

seriously..?

**Comment by Bloxxify1520** [comment]
> how do you get the update?

Dude go on the curseforge page for it and download 3.2 or 2.2, 3.2 is for 1.19.3 and 2.2 is 1.18.2

**Comment by Bloxxify1520** [comment]
Also close this
