### ISSUE TITLE
Float on the amulet like Kirby with his star

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1034]
Very much like kirby with his star but you can only float for 2 seconds *or 1 second* by sprinting then jumping and pressing right click or just float in air and press right click (please im about to die in my world)

:jesssad:

**Comment by Pandaboi25x** [comment]
Im on phase 7 btw :waa:

**Comment by nonamecrackers2** [comment]
Funny idea, but wouldn't really fit in and would take a bit to implement for a funny gimmick.

**Comment by Pandaboi25x** [comment]
> Funny idea, but wouldn't really fit in and would take a bit to implement for a funny gimmick.

Pain :waa: tho it would be a great suggestion for april fools

**Comment by nonamecrackers2** [comment]
It could be, who knows what might happen

**Comment by Pandaboi25x** [comment]
> It could be, who knows what might happen

👀
