### ISSUE TITLE
More Sickened mobs

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#1038]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Add more sickened mobs (sickened wolf, witch, husk, slime etc)

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by myron-obsolete-account** [comment]
similar to #943 which basically suggest more sickened mobs but idk if its a duplicate or not

**Comment by myron-obsolete-account** [comment]
okay it is a duplicate ***pulls out gun***

**Comment by humzahre** [comment]
ayayayayay im kid so im innocent

**Comment by humzahre** [comment]
ure doing a haram action

**Comment by NinjaSam5399** [comment]
A kid suggesting stuff. Bruh

**Comment by humzahre** [comment]
bc i <3 THIS MOD! btw im a pre-teen so dont judge!

**Comment by NinjaSam5399** [comment]
ok

**Comment by nonamecrackers2** [comment]
#459

**Comment by NinjaSam5399** [comment]
> bc i <3 THIS MOD! btw im a pre-teen so dont judge!

ur 3 years old, bruh
