### ISSUE TITLE
Witherstorm does not show up on horizon after exiting nether portal

### ISSUE THREAD

**Issue by ShirakiShio** [nonamecrackers2/crackers-wither-storm-mod#104]
Witherstorm does not show up on the horizon after I exited a Netherportal approximately 4000 blocks away from another portal we entered, where the Storm is located. It does exist, as seen in the screenshot below, I am also facing the area where it **should** be located.
![image](https://user-images.githubusercontent.com/48332495/174071304-b1e050f1-50a9-484b-98c5-9b3c2ec26cfa.png)

**Comment by nonamecrackers2** [comment]
Interesting. Will have to investigate.

**Comment by nonamecrackers2** [comment]
In the mean time, relogging should fix this issue.

**Comment by ShirakiShio** [comment]
I already did twice, it's persisting

**Comment by nonamecrackers2** [comment]
Really? And it's still loaded?

**Comment by ShirakiShio** [comment]
Yup
![image](https://user-images.githubusercontent.com/48332495/174092641-c13f86af-3752-4e1d-8bfd-34aa00a3e0c8.png)

**Comment by nonamecrackers2** [comment]
Ok, I'll have to take a look and see if I can reproduce.

**Comment by ShirakiShio** [comment]
https://gyazo.com/63e6ec05d5bef251b53d779f0b86b214 Here's a gif for reference

**Comment by ShirakiShio** [comment]
I'm gonna see and look if it will fix itself if it gets in my chunk area, and then distance myself from it

**Comment by nonamecrackers2** [comment]
Sure

**Comment by ShirakiShio** [comment]
https://gyazo.com/f4e6f3b46b79b111bebf266e58538acc results, also the debris ring doesn't seem to be loading despite my client options having them enabled. Could this be because of the RAM issue?

**Comment by nonamecrackers2** [comment]
No the rings are clientside so they shouldn’t be affected by the server… Also this issue is very peculiar, never seen it before.

**Comment by ShirakiShio** [comment]
I'll let you know if these persist after I do a server stop/restart, right now I don't want to do that incase it'll begin lagging again afterwards.

**Comment by ShirakiShio** [comment]
Found the issue, apparently I can't have my graphics on _Fabulous!_

**Comment by nonamecrackers2** [comment]
Oh, that's interesting. Glad you figured it out, will have to say the fabulous graphics setting isn't compatible.
