### ISSUE TITLE
Having the Outer Tentacles have any role to damaging the player

### ISSUE THREAD

**Issue by Bloxxify1520** [nonamecrackers2/crackers-wither-storm-mod#1040]
**Description of feature**
Most github suggestions for things like “swinging tentacles!1!1” get rejected, this one im simply making to say that the outer tentacles should get any type of upgrade, i feel they have potential to be better and stronger.
Many common suggestions have been
1. Swinging tentacles
2. Grabbing tentacles
3. Cluster grabbing tentacles
What i made this for was just to state that the outer tentacles have good potential to make it harder to survive the storm.

**Comment by BluePineappleGuy** [comment]
The tentacle attacks were some of the storm's core abilities, the others being the tractor beams and block cluster pickups. They should be there for more than just decoration. so yes cracker pls add this

**Comment by Asteroid4** [comment]
At flying height, the tentacles can’t really do much on their own

**Comment by myron-obsolete-account** [comment]
1.: #47
2.: #12
3.: Why?

**Comment by nonamecrackers2** [comment]
#12
