### ISSUE TITLE
Wall tentacles

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1043]
When the command block has been hit for the first time, four tentacles come out of the walls.
IMAGE:
<img width="925" alt="Screen Shot 2023-03-17 at 5 28 55 PM" src="https://user-images.githubusercontent.com/114886300/226073393-01aeec2c-634f-4350-9a49-e48170be1d8d.png">

**Comment by GrandmaPork** [comment]
I think this would be cool

**Comment by FrozenDragon0** [comment]
I believe this has already been suggested.

**Comment by myron-obsolete-account** [comment]
#750
