### ISSUE TITLE
Block cluster rotations

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1044]
When block clusters fall, they will keep the rotation they hit the ground with.

**Comment by myron-obsolete-account** [comment]
if this was a feature, keep in mind that, with how clusters currently work, you would not be able to walk around on them and instead just fall or walk through them since they still would be entities

**Comment by WitherBean** [comment]
I meant that the blocks in the clusters have the same rotation as they fell.

**Comment by myron-obsolete-account** [comment]
yeah i know what you mean. or do i? are you saying that block clusters should stay rotated yes?
but in minecraft there are only 4 horicontal rotations, and a block can not take any steps between those rotations. only solution would be an entity.

**Comment by BluePineappleGuy** [comment]
i think it wouldn't _quite_ work out because blocks like torches and plants would break upon the cluster being placed

**Comment by GrandmaPork** [comment]
i personally like it how it is

**Comment by nonamecrackers2** [comment]
Gonna be keeping clusters entity to block system the same as of now. Trying to apply their rotation to their placement wouldn’t work very well
