### ISSUE TITLE
More lore/references for the wither storm/rundown house

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#1047]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**
I have an idea: within the rundown house, there could be documentation/journal-like entries of someone experimenting with the command block, if you want I could help with this. I'll try to come up with more lore related ideas later

**Comment by Globalfirestorm10** [comment]
Overall lore just makes this mod more interesting, and more fun for theorists

**Comment by darkheart78** [comment]
maybe have a lapis chest as a reference to minecraft story mode. Or like an unfinished iron golem. Something like that.

**Comment by myron-obsolete-account** [comment]
fred the villager wanted to destroy the world with the command block but someone could stop him, but that someone forgot to disassemble the command block from the rooftop so now here we are with one skull away of death

**Comment by myron-obsolete-account** [comment]
^ that's a so-called ✨ I D E A ✨

**Comment by Globalfirestorm10** [comment]
Should I close this GitHub suggestion?

**Comment by BluePineappleGuy** [comment]
> Should I close this GitHub suggestion?

dont its a great one

**Comment by GrandmaPork** [comment]
i think the lore would be better if it were community made

**Comment by Globalfirestorm10** [comment]
> > Should I close this GitHub suggestion?
> 
> 
> 
> dont its a great one

Thanks for that, it seems like a lot of people think my suggestion is cringe, so I might

**Comment by Globalfirestorm10** [comment]
> i think the lore would be better if it were community made

Fair enough. I also saw what you said about me and moron on the discord server, so I have a question for you:
Why were we pissing you off?
It wasn't your dispute, so I fail to see why. I do agree however that I and moron stepped out of line a bit

**Comment by nonamecrackers2** [comment]
The lore isn't really set in stone and feel free to come up with your own. I have some idea of what it could be, but I don't think I'll add anything to mod lore-wise.

**Comment by Globalfirestorm10** [comment]
fair enough
