### ISSUE TITLE
Spawn platform (Ruined house) variations

### ISSUE THREAD

**Issue by ThatB0i** [nonamecrackers2/crackers-wither-storm-mod#1048]
a suggestion that the house has more designs/variations than just the single one, this would make it more immersive. this could even fix the house spawning on a tiny island by having underwater variants. I just think this would be cooler than the same house in every world.

**Comment by GrandmaPork** [comment]
I think a house per biome would be very cool

**Comment by darkheart78** [comment]
there is already a small island when it spawns in an ocean

**Comment by ThatB0i** [comment]
> there is already a small island when it spawns in an ocean

yea but it looks really out of place

**Comment by GrandmaPork** [comment]
I think it could be imrpoved on. Honestly I'd settle for a larger, floating island-looking base base tho

**Comment by Globalfirestorm10** [comment]
> I think it could be imrpoved on. Honestly I'd settle for a larger, floating island-looking base base tho

I like this idea, but I'd personally prefer an abandoned underground bunker-like structure just for aesthetics. I do think the idea of a floating island does fit with minecraft though, crackers could even just take the current structure NBT and make it spawn at something like 0,120,0 instead of the current 0, 71, 0 coordinates.

**Comment by GrandmaPork** [comment]
I meant like, a base that is similar to a floating island base. Not an actual floating island

**Comment by Globalfirestorm10** [comment]
Oh I see, my bad. I still like the idea

**Comment by Aimyx** [comment]
> I like this idea, but I'd personally prefer an abandoned underground bunker-like structure just for aesthetics. I do think the idea of a floating island does fit with minecraft though, crackers could even just take the current structure NBT and make it spawn at something like 0,120,0 instead of the current 0, 71, 0 coordinates.
 
if it was underground, it could also give the break the blocks above it feature thing a chance to shine.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
