### ISSUE TITLE
Wither storm attribute modifier not working + Render shine ON not rendering (No Optifine)

### ISSUE THREAD

**Issue by goldennightcore** [nonamecrackers2/crackers-wither-storm-mod#1049]
**Minecraft version**
1.18.2

**Mod version**
1.18.2-2.2

**Describe the bug**
Wither storm is evolving while playing, but the evolution attribute modifier does not change speed of evolution. Render shine is not rendering regardless of restart/reload.

**Is OptiFine installed?**
No Optifine

**Comment by darkheart78** [comment]
how long did you wait

**Comment by goldennightcore** [comment]
I waited a long time, even setting the evolution attribute modifier to 0.1 and reloading.

**Comment by goldennightcore** [comment]
ok, tried waiting longer and it does evolve, just the attribute modifier doesnt apply even after a reload.

**Comment by nonamecrackers2** [comment]
You'll have to use the config to modify the evolution speed attribute, modifying it using commands won't do anything since the config will always adjust modifiers so the value reaches the one specified in the config. Please make a separate issue for the shine issue and provide screenshots.
