### ISSUE TITLE
New stage for the command block in the final boss battel arena 

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#105]
OK I know thus might be impossible but I don't know that much about mods the suggestion is when the player hit the command 3 timed its on hit away from getting destroyed I suggest it go upside down (I still think this is impossible) but maybe just maybe it's possible

**Comment by nonamecrackers2** [comment]
I really wanted to be able to do this, but it just won't be possible. Thanks though

**Comment by Asteroid4** [comment]
There is the gravity changer mod, you could use that.

**Comment by Krypton6167** [comment]
you can just use a gravity changer, and have the whole on top, when it reaches the next face it can rather instantly go down there or just have a rotate animation, in any case, just make everything flip instantly while you fly your face into the ceiling, might be hard anyway, but I think its a good chance.

**Comment by myron-obsolete-account** [comment]
@nonamecrackers2 I have a small idea to keep the mouths of those who want this shut:
If the user has the create mod installed alongside the witherstormmod, the bowels structure.nbt thats going to be generated is actually a different one, with a mechanical bearing and some redstone mechanics etc. if the health of the command block is 16, the entire bowels, glued to that mechanical bearing, could rotate upside down. however im not sure how it would work with the entities.
just a silly idea i had please ignore this if you are completely sick of that topic + im sorry

**Comment by myron-obsolete-account** [comment]
also its gonna lag a lot so uhh 🗿

**Comment by BluePineappleGuy** [comment]
or... instead of the battle arena rotating, which would require a few dependencies or a WHOLE HECKLOAD OF CODE, you could just make the command podium rotate after it moves up.
