### ISSUE TITLE
More accurate Tentacles

### ISSUE THREAD

**Issue by goldennightcore** [nonamecrackers2/crackers-wither-storm-mod#1050]
**Description of feature**
Maybe as a feature make the tentacles more long and droopy like in the original,
I always thought the current tentacles were more lifted up and shorter than how the original design of the witherstorm had looked.

**Other**
The tentacles could maybe also be more blocky, like in the original game the tentacles looked more like much more several blocks than singular blocks.

Also another feature could be it destroying the nether portal, maybe an animation or something like that.
![Screenshot (23)](https://user-images.githubusercontent.com/128508428/226720198-ddaea58c-3723-42f0-a561-11db852b1776.png)

Note: if this is insane coding I don't mind this idea being scrapped.

*ORIGINAL IMAGE OF WITHER STORM*
![image](https://user-images.githubusercontent.com/128508428/226718634-829cb27e-a55e-4131-b84c-64752e43e497.png)

**Comment by WitherBean** [comment]
I like this idea.

**Comment by FrozenDragon0** [comment]
This has already been suggested and denied: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/47

Tentacles breaking portals has also already been suggested and denied: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/49

**Comment by GrandmaPork** [comment]
this is a duplicate, the tentacles are already accurate to mcsm. you can close this

**Comment by Asteroid4** [comment]
this isnt a duplicate, its about tentacles being a bit closer to the ground, not about moving

**Comment by GrandmaPork** [comment]
Cracker has stated he will not be blockifying the tentacles, although I do like the idea of them being more droopy

**Comment by WitherBean** [comment]
Is this what you mean?
![new tentacles](https://user-images.githubusercontent.com/114886300/226779350-96950510-3932-46bb-931d-dbf2c251de0e.png)

**Comment by NinjaSam5399** [comment]
it looks like a tail in phase four, maybe turn the tail into long tentacles too.

I think this is better: 
![image](https://user-images.githubusercontent.com/111523734/227053498-275f975b-7bdc-4e2b-98a6-4a46cfdbdc1b.png)
