### ISSUE TITLE
Withered Symbiont will attack even if in creative mode

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1051]
**Minecraft version**
1.19.3

**Mod version**
1.19.3

**Describe the bug**
if you start flying around and push the withered symbiont he will get pissed and start preparing a spell for you

**To Reproduce**
1. spawn a withered symbiont
2. start flying
3. push him (pushing him near his stomach is better to see the bug)
4. wow he attacked you in creative.. hacks

**Is OptiFine installed?**
no

**Screenshots**
![image](https://user-images.githubusercontent.com/121638798/226890257-d58e5599-3c82-4f4a-bb50-286ba3c8be0f.png)
![image](https://user-images.githubusercontent.com/121638798/226890549-ed4089dc-bdc8-4d3c-81c4-664c31d4511f.png)

also a sickened mobs will attack you when symbiont summons mobs if in creative

**Comment by Pandaboi25x** [comment]
ive wanted to report this bug a long time ago but i forgor :skull:

**Comment by GrandmaPork** [comment]
💀

**Comment by NinjaSam5399** [comment]
💀

**Comment by Pandaboi25x** [comment]
:skull:

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
