### ISSUE TITLE
multishot dupe enderpearl glitch 

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1052]
**Minecraft version**
1.19.3

**Mod version**
1.19.3

**Describe the bug**
if you have multishot and 1 enderpearl it will shoot 3 

**To Reproduce**
1. get a crossbow with multishot
2. get the ender pearl on the crossbow
3. shoot
4. 3 ender pearls :shock:

**Is OptiFine installed?**
no

**Screenshots**
![image](https://user-images.githubusercontent.com/121638798/226901944-f451cc07-63cd-4e2e-8ad4-af664a9abfba.png)

![image](https://user-images.githubusercontent.com/121638798/226901871-9c3f414f-2852-45f4-bf59-5836e45183aa.png)

**Comment by myron-obsolete-account** [comment]
thats literally what multishot means 🙄

**Comment by Pandaboi25x** [comment]
> thats literally what multishot means 🙄

:moyai:

**Comment by Pandaboi25x** [comment]
dawg holy shit im dumb as fuck i havent played minecraft for so long i forgot it can do that :sob:

**Comment by Pandaboi25x** [comment]
im dissapointed in myself

**Comment by myron-obsolete-account** [comment]
lmao

**Comment by Pandaboi25x** [comment]
i havent played in a while sthu :sob:

**Comment by myron-obsolete-account** [comment]
:(

**Comment by Bloxxify1520** [comment]
> i havent played in a while sthu 😭

Multishot was added in 1.14

**Comment by Pandaboi25x** [comment]
> > i havent played in a while sthu 😭
> 
> Multishot was added in 1.14

Literally when i started playing :shock: appears i havent played minecraft for so long i forgor
