### ISSUE TITLE
Better smart bossbar (Tractor beam, ambient sounds and ambient loops of the WS are affected by smart bossbar setting)

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1053]
Tractor beams should not render or affect the player in any way when smart bossbar hides the bossbar. Also using similar logic, ambient loops and sounds will not play.
When the player has seen the WS and retreated into a cave, https://www.youtube.com/watch?v=WvZ3hwwRSkY&t=48s plays on loop and the bossbar doesn't dissapear 'till the player is far underground (maybe 75 block from the surface)
Extra idea: when the bossbar isnt there but the WS is in the area, the music would play, but on mute, and get unmuted when the bossbar turns on

**Comment by GrandmaPork** [comment]
I think the boss bar is perfect how it is. I’d like for the tractor beams to be not visible but idk how he’d do that. Maybe he can unload the wither storm whenever the boss bar disappears

**Comment by BluePineappleGuy** [comment]
> I think the boss bar is perfect how it is. I’d like for the tractor beams to be not visible but idk how he’d do that. Maybe he can unload the wither storm whenever the boss bar disappears

problem is, with how the WS works, it loads itself so it can do damage without the player being in the area.

**Comment by GrandmaPork** [comment]
well it can load itself onto the server side but not client side

**Comment by nonamecrackers2** [comment]
This could cause some unintended behavior where the tractor beams disappear when the boss bar is not visible but the Wither Storm clearly is. I think the system is fine as it is, and removing the loops will also make it seem like it disappeared entirely.

**Comment by BluePineappleGuy** [comment]
> This could cause some unintended behavior where the tractor beams disappear when the boss bar is not visible but the Wither Storm clearly is. I think the system is fine as it is, and removing the loops will also make it seem like it disappeared entirely.

true, could cause issues when not rendering the beam, but removing the loops and sounds would still be great because it tends to spoil the surprise when you go up to the surface, as when seeing the beams when mining or hearing the sounds of a close-by storm tell you that its above you, kind of ruining the point of smart bossbar. to fix the beams issue perhaps the bossbar also turns on if the storm is visible, even if other requirements for the bossbar are not met.

also when i said loops wont play i meant when underground, on the surface the distant ambient loops and sound loops of the storm still play

**Comment by nonamecrackers2** [comment]
The point of the smart bossbar isn’t to make the wither storm surprising, instead it’s meant to disable the bossbar when the wither storm isn’t a threat.
