### ISSUE TITLE
Wither Sickness Events Optimization

### ISSUE THREAD

**Issue by Kasualix** [nonamecrackers2/crackers-wither-storm-mod#1054]
Spark shows that the WitherSicknessEvents-onWorldTick lags a lot

![image](https://user-images.githubusercontent.com/110756250/227436196-01de9474-47de-4038-a4d8-e02956b7b48d.png)

> _things deleted and issue turns into a feature request_

**Comment by nonamecrackers2** [comment]
Some performance optimizations have been made in 2.2.1/3.2.1, let me know if they help with performance at all

**Comment by Kasualix** [comment]
Another question: Should the Wither Sickness Tracker keeps ticking when Wither Sickness Effect is disabled in serverconfig?
