### ISSUE TITLE
Bowels archeology for 1.20

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1056]
Basically, tainted gravel, suspicious tainted gravel, and suspicious tainted sand could be found in the bowels when the full 1.20 comes out and this mod updates. Inside could be found special withered items, such as new tainted armor trims and withered pottery shards. The pots from withered pottery shards would be purple and would form a purple-pinkish pot (Additionally, tainted bricks could be added for blank sides). The symbols and drawings on the shards would be of things related to the mod, such as the storm spawn totem, the abandoned house, the command block tools, the f-bomb, segments, stage 4 wither storm, symbiont, and bowels arena. Archeology sites could be found in the bowels, like a tainted desert well, the new trail ruins, or an updated tainted desert temple. These would be where you can find the tainted suspicious blocks.

Extra idea: the shards could also contain images of story mode references such as the elixir, or a shard of a pig called 'Reuben'

**Comment by GrandmaPork** [comment]
Sounds very cool and adds to the reward of beating the wither storm

**Comment by Globalfirestorm10** [comment]
Yeah, I like this idea.

**Comment by NinjaSam5399** [comment]
Best Idea Yet.

**Comment by Aimyx** [comment]
great idea.

**Comment by GrandmaPork** [comment]
I think this should only be possible inside the withered chunks that it drops on death

**Comment by NinjaSam5399** [comment]
I wanna see this confirmed

**Comment by BluePineappleGuy** [comment]
Kinda hope this will be in Evolution pt. 2
