### ISSUE TITLE
Ender pearl crossbows show arrow crossbow texture

### ISSUE THREAD

**Issue by CubeGamer647** [nonamecrackers2/crackers-wither-storm-mod#1057]
**Minecraft version**
1.19.3

**Mod version**
3.2

**Describe the bug**
When loading an ender pearl into a crossbow, it shows a crossbow with an arrow in it. It still functions like an ender pearl when shot. I've looked through the files and seen that there is an ender pearl texture there, but it's unused for some reason.

**To Reproduce**
1. Hold an ender pearl in your offhand
2. Load the crossbow
3. The crossbow shows an arrow texture instead of an ender pearl texture

**Is OptiFine installed?**
No

**Screenshots**
![image](https://user-images.githubusercontent.com/100244632/227738836-f4abd5fc-5e45-4f18-b646-089e0b4184c6.png)

**Comment by WitherBean** [comment]
For me, it shows the ender pearl texture.

**Comment by nonamecrackers2** [comment]
What other mods/resource packs do you have installed?

**Comment by CubeGamer647** [comment]
Nothing besides jei, but I tried without it and it still gave me the problem.

**Comment by nonamecrackers2** [comment]
Interesting

**Comment by CubeGamer647** [comment]
Okay so I completely wiped my minecraft folder and updated to 1.19.4 and it fixed the crossbow bug and the death animation that I didn't even know was messed up. Before, the body would disappear and only the the heads and tentacles would slowly disintegrate. I have no idea why either of these would have been a problem.

**Comment by nonamecrackers2** [comment]
You may have had the mod resources resource pack below the default minecraft resources, which has been known to cause the body unloading issue when the WS is dying and the Ender pearl crossbow texture bug
