### ISSUE TITLE
A smaller split storm

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1058]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Make the Wither Storm's body smaller during phase 6. This way, it looks more weakened, but when it reaches phase 7 it will look WAY more intimidating. Also, make the pink/purple flesh parts brighter or glow. It will look scarier at night when everything is dark.

Texture I suggest:

![Witherbody4](https://user-images.githubusercontent.com/109185503/227744815-a09c81e0-13d9-4114-ac85-01ce8882bccb.svg)

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Honey-Programming** [comment]
I hope this gets added for the next update.

**Comment by Globalfirestorm10** [comment]
IIRC, crackers said he wouldn't be editing any of the phase models, so idk if this issue should be open or not

**Comment by nonamecrackers2** [comment]
Read the guidelines please. Model changes are not in the mods best interest.
