### ISSUE TITLE
Sickened Sniffer

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#1060]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**
With the new archeology update coming out, if this mod ever gets ported to 1.20 in the future, I think there should be a sickened sniffer.

Essentially, this mob would hatch out of a sickened version of a sniffer egg,and start sniffing around for the player. If it detects the player, it would alert nearby sickened mobs in the bowels, and those mobs would start coming to the location of the player.

I'm not exactly sure how and if this would work for the bossfight, I guess since sickened mobs spawn in the non-command block area of the bowels, perhaps it could be there? Idk

**Comment by Pandaboi25x** [comment]
Poor sniffer tho cool idea

**Comment by ThatB0i** [comment]
this is truly evil

**Comment by Globalfirestorm10** [comment]
> Poor sniffer tho cool idea

thanks!

**Comment by Globalfirestorm10** [comment]
> this is truly evil

how so?

**Comment by Aimyx** [comment]
why do that to that poor thing. its not even hostile

**Comment by Globalfirestorm10** [comment]
Just because.

**Comment by darthvader45** [comment]
Maybe you can cure it with golden apple stew and it becomes a regular sniffer?

**Comment by nonamecrackers2** [comment]
Closing since the new guidelines do not permit sickened mob suggestions

**Comment by darthvader45** [comment]
Huh, doesn't seem like it's mentioned.  Might you point that one out to me?

**Comment by nonamecrackers2** [comment]
Sure thing: https://github.com/nonamecrackers2/crackers-wither-storm-mod/blob/1.16.5/docs/CONTRIBUTING.md#:~:text=what%27s%20already%20coming-,More%20sickened%20mobs,-(they%20will%20be

**Comment by darthvader45** [comment]
Thanks.  Btw, love the mod, puts me right in the atmosphere of season 1 of story mode.

**Comment by nonamecrackers2** [comment]
Glad you like it!

**Comment by darthvader45** [comment]
No problem.  I even paired it with another mod that adds some of the unique armor sets found in Story Mode, alongside Fresh Animations, which surprisingly makes mobs animated just like Story Mode, check it out.

**Comment by myron-obsolete-account** [comment]
> No problem. I even paired it with another mod that adds some of the unique armor sets found in Story Mode, alongside Fresh Animations, which surprisingly makes mobs animated just like Story Mode, check it out.

fresh animations does not animate sickened mobs from the WS mod like the normal ones though. I am going to open an issue on that in a minute or two

**Comment by darthvader45** [comment]
Sounds cool, I'd love to see animated sickened mobs.

**Comment by ThatB0i** [comment]
> Sure thing: https://github.com/nonamecrackers2/crackers-wither-storm-mod/blob/1.16.5/docs/CONTRIBUTING.md#:~:text=what%27s%20already%20coming-,More%20sickened%20mobs,-(they%20will%20be

i kinda wish i could help make textures for the other mobs.........
