### ISSUE TITLE
Disable ruined house config

### ISSUE THREAD

**Issue by ThatB0i** [nonamecrackers2/crackers-wither-storm-mod#1064]
A small suggestion to add a config that lets the player disable or enable the wither storm spawn platform for modpacks.

**Comment by V0calgiant12** [comment]
This can be done by making a datapack that removes the structure

**Comment by NinjaSam5399** [comment]
There is a setting that removes the rundown house.

**Comment by nonamecrackers2** [comment]
As already mentioned, there is a setting to disable the house but only in 1.16.5. You'll need a datapack to remove it #206
