### ISSUE TITLE
Tentacles on the witherstorm, not inside of it.

### ISSUE THREAD

**Issue by ConnirH** [nonamecrackers2/crackers-wither-storm-mod#1065]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

This would be a cool but difficult idea but, what if the tentacles on the witherstorm were able to grab people if they were to close or underneath it and had like 3 to 5 seconds to break free or would be put into the mouth of the wither storm and had to free them selves from there. Just like the real story mode game, again this would be very cool and would love it.

**Comment by ConnirH** [comment]
Or when put into the mouth they would be instantly killed.

**Comment by ConnirH** [comment]
Another way would they would just be strangled by the tentacle.

**Comment by Globalfirestorm10** [comment]
this has been suggested numerous times, please close this

**Comment by myron-obsolete-account** [comment]
#12 please close this duplicate
