### ISSUE TITLE
Rotation Speed slider outside of its slider box

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1066]
**Minecraft version**
1.19.3

**Mod version**
3.2.1

**Describe the bug**
The slider of the Rotation Speed config is too far on the left, see screenshot on the bottom.

**To Reproduce**
Steps to reproduce the behavior (really?):
1. Download CWSM V3.2.1 for 1.19.3 and install it to your mods folder
2. Start Minecraft
3. Go to options
4. Go to W
5. Go to World Options
6. Scroll down to Rotation Speed
7. See slider not respecting its enviorment

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
No.

**Screenshots**
![image](https://user-images.githubusercontent.com/53058491/228260575-79afdd9c-2bf7-48cd-914f-24951440331b.png)

**Comment by Globalfirestorm10** [comment]
Huh? I thought this bug was fixed last version, I guess not. Test it on other versions if possible

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
