### ISSUE TITLE
Tractor Beam Distant Render Disable Option

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#1067]
When The Wither Storm Is Far Away The Tractor Beam Is Still Visible

It Would Be Great If There Could Be A Option To Disable Distant Tractor Beam Render

**Comment by GrandmaPork** [comment]
while it definitely looks awkward to see the tractor beams just end, i think a better solution would be to make them fade out about halfway

**Comment by Aimyx** [comment]
> while it definitely looks awkward to see the tractor beams just end, i think a better solution would be to make them fade out about halfway

that would be a good idea

**Comment by nonamecrackers2** [comment]
Will be remedied with tractor beam fade in the next update
