### ISSUE TITLE
WS body unloading (not shader related)

### ISSUE THREAD

**Issue by TeaCupsTeaPots** [nonamecrackers2/crackers-wither-storm-mod#1068]
WS body unloads upon death.
This is not shader related and happens without optifine (the only thing in the mods folder is WS mod).
Forge is 44.1.23
Minecraft versions is 1.19.3
This happens with the most recent update, 3.2.1, but also happens with 3.2 (not sure about any previous versions but I do remember playing this mod a while before I played it again and saw this issue).
This only happens with the real death, not the fake one.
Screenshot from latest version:
![2023-03-28_15 55 32](https://user-images.githubusercontent.com/102552124/228282732-8cd8d6ae-0e4d-44bc-a638-b9bf628b7b4b.png)

**Comment by myron-obsolete-account** [comment]
#939 this issue is known and has already been reported

**Comment by myron-obsolete-account** [comment]
or not idk

**Comment by TeaCupsTeaPots** [comment]
> or not idk

There was a separate issue that Crackers fixed about the WS body unloading with shaders
He told me to make a separate issue for this, which occurs without shaders or any optifine

**Comment by myron-obsolete-account** [comment]
it is known that this happens without shaders either way so technically a duplicate but i dont think they made a sperate issue for it so idk honestly

**Comment by TeaCupsTeaPots** [comment]
I don't think there are any issues specifically about this issue happening only on the death animation AND with no involvement with other mods like Optifine either
separating this from the already fixed issue is also less confusing

**Comment by nonamecrackers2** [comment]
What's your mod list?

**Comment by TeaCupsTeaPots** [comment]
> What's your mod list?

empty right now but when i was testing this there was nothing in there except for CWSM

**Comment by nonamecrackers2** [comment]
Any resource packs?

**Comment by TeaCupsTeaPots** [comment]
> Any resource packs?

cannot remember if i had any at the time, i'll go quickly check without resource packs

**Comment by TeaCupsTeaPots** [comment]
> Any resource packs?

this reminded me about the mod resources file, and noticed that it was below the vanilla resource pack
putting mod resources above vanilla fixes the issue
didn't expect this to be so simply fixed lol

**Comment by nonamecrackers2** [comment]
Glad that worked! I'll have to add that to the known incompatibilities then
