### ISSUE TITLE
witherstorm loses its 2 big tentacles

### ISSUE THREAD

**Issue by hodgettsalf1** [nonamecrackers2/crackers-wither-storm-mod#1069]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by hodgettsalf1** [comment]
the witherstorm should lose its 2 massive tentacles after it gets exploded by the f bomb bc its weird how the segments got 4 tentacles so each big tentacles on the main witherstorm should be put on for each segment

**Comment by myron-obsolete-account** [comment]
already suggested #923 please check for suggestions if they already exist before making one
and please close this
