### ISSUE TITLE
Wither storm morph

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#107]
I know this might be hard so let it be an update in the future when the players destroys the command he gets a withered nether star or something to morph to the wither storm from its 1 phase to the final and if its not possible to get from phase 1 to the last phase separate the morph items (oh I almost forgot maybe not the withered nether star cuz there is a suggestion says for a bacon for it so if you can make an item or a menu or just make some changes to the mod so we can add a morph mod)

**Comment by Loverxzc** [comment]
#57
