### ISSUE TITLE
Doesn't s summon

### ISSUE THREAD

**Issue by badgermedic76** [nonamecrackers2/crackers-wither-storm-mod#1071]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
Specify if you're using OptiFine

**Screenshots**

**Comment by nonamecrackers2** [comment]
Please fill out the template

**Comment by Globalfirestorm10** [comment]
> _**Please check the guidelines before submitting:**_ #217
> 
> **Minecraft version** The version of Minecraft the mod is running on
> 
> **Mod version** The version of the mod you are using
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Crash Reports / Logs** Crash reports / logs hosted on pastebin, gist, etc.
> 
> **Is OptiFine installed?** Specify if you're using OptiFine
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
You need to do two things:
1. Fill out the template
2. tell us what doesn't summon, as I have no idea what "s" is

**Comment by Globalfirestorm10** [comment]
@badgermedic76 Look, ill try to help you even though you have given zero info on your issue. The symbiont (if you are referring to that, which I think you may be) takes a while to spawn, so you'll need to be patient. You can also try checking if you have mobGriefing disabled, as you'll need that for the withered symbiont to spawn. If not, you may have conflicting mods, otherwise idrk tbh

**Comment by myron-obsolete-account** [comment]
- makes new issue
- fills title with 2 words
- leaves template unfilled
- publishes issue
- refuses to elaborate
- leaves

sounds like a normal day
