### ISSUE TITLE
Formidibomb for all phases

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1072]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
If you try to explode the formidibomb on the early ones it doesnt do much so please add it 

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Globalfirestorm10** [comment]
> _**Please read the guidelines before submitting:**_ #217
> 
> **Description of feature** If you try to explode the formidibomb on the early ones it doesnt do much so please add it
> 
> **ONLY ONE FEATURE REQUEST PER ISSUE**

Do you mind expanding on what you mean by "it doesn't do much"?

**Comment by WitherBean** [comment]
How early are the "early ones"?

**Comment by BluePineappleGuy** [comment]
> How early are the "early ones"?

i'm guessing stage 4

**Comment by Globalfirestorm10** [comment]
> > How early are the "early ones"?
> 
> 
> 
> i'm guessing stage 4

i'd probably take a shot in the dark and say this guy is referring to phases 0-3

**Comment by nonamecrackers2** [comment]
This is intended
