### ISSUE TITLE
fabric versiyon

### ISSUE THREAD

**Issue by Rogenar** [nonamecrackers2/crackers-wither-storm-mod#1073]
Will Cracker's Wither Storm Mod come in fabric version?

**Comment by darkheart78** [comment]
it uses forge only features so not possible

**Comment by Rogenar** [comment]
It would be more descriptive if the person who made this mod answers it herself.

**Comment by Bloxxify1520** [comment]
> It would be more descriptive if the person who made this mod answers it herself.

Its literally confirmed he wont port it to other moddinng API’s or Bedrock
