### ISSUE TITLE
1.19.4, 3, and 2 are not working.

### ISSUE THREAD

**Issue by EvanFarwolder** [nonamecrackers2/crackers-wither-storm-mod#1074]
Using Fabric, it loads perfectly fine. But as you can see in gameplay + modmenu it doesn't show up. (I'm not using OptiFine)

**Comment by Bloxxify1520** [comment]
Its not for fabric…? The mod is forge only

**Comment by nonamecrackers2** [comment]
Cracker's Wither Storm Mod is a Forge only mod
