### ISSUE TITLE
Global sky darkening effect

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#1075]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

I think that it looks rather weird how when the storm is near you, the sky suddenly darkens as the storm loads in. So I propose that the sky darkening effect should be in effect no matter how far away you are from the storm. Feel free to make this low priority or something, as it's kinda a nitpick

**Comment by FrozenDragon0** [comment]
I don't think this would be a good idea to have on non-stop, some people might hate having their world darkened nonstop if the storm exists, I think this is more better suited as a config option.

**Comment by GrandmaPork** [comment]
The reason is because when it’s up close, it is blocking out the sun. Pretty realistic for it to suddenly go dark. Think of it like it’s a solar eclipse

**Comment by Globalfirestorm10** [comment]
Fair enough. However, as dragon suggested, cracker could just slap a config on it.

**Comment by Globalfirestorm10** [comment]
> The reason is because when it’s up close, it is blocking out the sun. Pretty realistic for it to suddenly go dark. Think of it like it’s a solar eclipse 

Yeah I forgot about that

**Comment by Globalfirestorm10** [comment]
Im gonna close this for now, as this feature I don't really see fit for the mod for now. If @nonamecrackers2 wants to open it again, then that's fine.
