### ISSUE TITLE
Withered beacon can use some of the wither storm's powers

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1076]
Basically you can use the withered beacon to do things like turn a block into its tainted variant and vice versa, or allow it to create a sort of beam that can repel or pull in entities based on their movement pattern (basically flight within the beam but only 1 entity at a time), create block clusters and assemble them how you wish, sicken mobs, cure mobs, perhaps summoning of certain entities, etc.
Perhaps this could require the beacon to have a 'charging' mechanic: while charging up power it stops its effects and beam and once its charged it glows, ready for use.

EXTRA IDEA: maybe it could also be charged up to physically darken the sky (basically eternal night). can be toggled in the GUI, and uses up some of the beacons charge as it goes on.

**Comment by Aimyx** [comment]
good idea, terribly hard to implement probably

**Comment by nonamecrackers2** [comment]
It can now be used to craft blocks/items and summon sickened mobs. The other ideas are cool but would take a lot of work to implement.

**Comment by BluePineappleGuy** [comment]
> It can now be used to craft blocks/items and summon sickened mobs. The other ideas are cool but would take a lot of work to implement.

well, the other ideas didn't really fit with the mod anyway lol
