### ISSUE TITLE
Add a setting to disable the spawning of the starter house

### ISSUE THREAD

**Issue by MyBedIsInAWall** [nonamecrackers2/crackers-wither-storm-mod#1077]
This might already be a thing, but after checking all config files multiple times, I can't seem to find a setting to do this, although I can remember it.

**Comment by nonamecrackers2** [comment]
#1064

**Comment by myron-obsolete-account** [comment]
Why the hell does everyone want the starter house not to spawn?

**Comment by nonamecrackers2** [comment]
Modpack makers, they want to use a different method to spawn the storm
