### ISSUE TITLE
Smart Withered Symbiont Bossbar

### ISSUE THREAD

**Issue by GoldSlimeling91** [nonamecrackers2/crackers-wither-storm-mod#1078]
Since the Wither Storm itself now has a smart bossbar that vanishes when it's not visible, why not make it's miniboss's bossbar smart aswell? The Symbiont's bossbar could be hidden while not engaged with it and the Storm's bossbar  could be hidden while fighting the empowered zombie, it would make more sense this way as seeing multiple bossbars at once (especially an extra one for an entity you cant even damage normally) is a little jarring.

As for the Withered Symbiont in the Command Block's fight, you could just make it's bossbar hidden during the fight as it's not too important there and is simply a minion. Up to you really when it comes to that one as I don't have any other ideas.

**Comment by GrandmaPork** [comment]
I actually disagree. It is very helpful to have the bossbar so at least you know you're near it

**Comment by nonamecrackers2** [comment]
> I actually disagree. It is very helpful to have the bossbar so at least you know you're near it

For that reason I think the symbiont bossbar shouldn't have the smart bossbar feature.
