### ISSUE TITLE
cracker's wither storm mod not working on server

### ISSUE THREAD

**Issue by 26emeraldking** [nonamecrackers2/crackers-wither-storm-mod#1079]
I am trying to make a survival server for me and my friends, but the server won't start and it keeps giving me an error. I have tried several versions of the mod and even forge, but it just won't work. plz help I am a noob.

**Comment by Globalfirestorm10** [comment]
Mind telling us exactly what happened? It's hard to tell, as theres little info. If it crashed, send the crash report and latest.log files (latest.log is found in .minecraft-> logs, and crash reports are found in .minecraft-> crash-reports)



Next time could you fill out the template? That would help us a lot

**Comment by Globalfirestorm10** [comment]
Also, send a screenshot of your mods folder and tell us what version of mc forge your using CWSM on

**Comment by 26emeraldking** [comment]
ok, sorry I didn't do that earlier. I forgot to say that whenever I added the wither storm mod, it would crash and not work, but if I had all the other mods and removed the wither storm mod it would work. anyway, here are the mods list and log. also I didn't know there was a template, could you show me where that is? [mods list](https://drive.google.com/file/d/1Em7yImfq2nbW4-ZOTHPot8MrYHuMFWo3/view?usp=share_link)
[server log](https://drive.google.com/file/d/1g9A3ERcHaKH0PcXlr6cq-GGgHEf960e5/view?usp=share_link)
By the way, this is a **_ Minecraft server_** I'm having trouble with. If you need anything else, let me know.
thanks.

**Comment by GrandmaPork** [comment]
Take this to discord and close this issue. If it ends up being a mod compatibility issue, open an issue here

**Comment by nonamecrackers2** [comment]
Looks like you're trying to run the server with Java 19, you'll need to use Java 17

**Comment by 26emeraldking** [comment]
Thank you so much, it worked!

**Comment by nonamecrackers2** [comment]
Np
