### ISSUE TITLE
Wither storm can get stuck after evolving to phase 4 (bug i guess)

### ISSUE THREAD

**Issue by NEFFLEAFF** [nonamecrackers2/crackers-wither-storm-mod#108]
Sometimes if the wither storm evolves to phase 4 at the wrong moment it can get stuck with the terrain and basically never move from it.

A easy solution is to make wither storm phase 4 able to break the blocks that are touching it's hitbox, at least to make it able to get to the sky.

**Comment by nonamecrackers2** [comment]
The wither storm will now (in the next update) explode blocks when colliding with them. The only thing is that this doesn't work with water, however I don't think there will be much cases of this happening/
