### ISSUE TITLE
1.19.4 Broken ?

### ISSUE THREAD

**Issue by Theoyeah** [nonamecrackers2/crackers-wither-storm-mod#1080]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4 with rubinium, oculus and cwsm (lastest) and same for forge

**Mod version**
witherstormmod-1.19.4-3.2.1.2.jar

**Describe the bug**
The WS seems to be in max lightning ? idk how to quite say it
![image](https://user-images.githubusercontent.com/97792861/229274821-939dc230-f809-4d47-93dd-3790e60a9668.png)

**To Reproduce**
Just make the ws phase 7 and you would see this

**Crash Reports / Logs**
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/11128819/latest.log)

**Is OptiFine installed?**
Optifine has no bitches so never
**Screenshots**
....

**Comment by FrozenDragon0** [comment]
This ain't a bug lol, it's an April fools joke.

**Comment by nonamecrackers2** [comment]
Yep lol. If you want to disable it, disable "April Fools" in the client config

**Comment by Theoyeah** [comment]
> 

Bruh
