### ISSUE TITLE
3.2 Issue

### ISSUE THREAD

**Issue by AstralVR** [nonamecrackers2/crackers-wither-storm-mod#1081]
I'm using your mod's version 3.2 but whenever i summon a witherstorm through withered beacons, it's pink.

**Comment by myron-obsolete-account** [comment]
thats an april fools feature and will be over tomorrow, its not because of the beacons. if you want it gone today already go to configs and disable april fools rendering at the bottom

**Comment by ThatB0i** [comment]
WAIT THERES AN APRIL FOOLS JOKE!!!!!!!!!!
