### ISSUE TITLE
Wither Storm's body unload even in version 2.2.1

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1082]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2

**Mod version**
2.2.1 (A Block and a Hard Place "Fixes")

**Describe the bug**
The Wither Storm's Body unloads even when Crackers said he would fix it in 2.2.1 (1.18.2).
I couldn't even find a a fixed version on modrinth.

NOTE: This issue is not related to 1.19.4 as this was already fixed

**Is OptiFine installed?**
No

**Comment by nonamecrackers2** [comment]
Make sure mod resources is at the top of the list  in the resource pack menu

**Comment by Honey-Programming** [comment]
![2023-04-02_10 24 03](https://user-images.githubusercontent.com/109185503/229369118-d10df675-cb1d-4665-b48d-1857362815c4.png)

This is a screenshot of me killing the Wither Storm using Forge 1.18.2 (40.2.1) with CWSM 2.2.1


![Screenshot 2023-04-02 102755](https://user-images.githubusercontent.com/109185503/229369127-21de5afd-afe2-4edc-926c-f4e094159edb.png)

The mod is at the top of the list.
When I hover over the mod file it says "Made for an older version of Minecraft".

**Comment by Honey-Programming** [comment]
It probably wasn't implemented correctly.
This also happened with 3.2.1 (1.19.4).

**Comment by Honey-Programming** [comment]
Never mind it was fixed because the mod resources in the resource packs were not at the top.

**Comment by nonamecrackers2** [comment]
Glad that worked. Yeah the pack.mcmeta will need to be updated

**Comment by Steve982950** [comment]
I can CONFIRM This bug was supposed to be fixed, but wasn't. Even in NewEST Patch 3.2.1.3

**Comment by Steve982950** [comment]
Screenshot:
![BUGGED STORM](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128298281/a4d39459-872c-41e8-bf1a-6f11360757cb)
BTW Sorry for f3 menu.

**Comment by BluePineappleGuy** [comment]
is mod resouces at the top?

**Comment by Steve982950** [comment]
> is mod resouces at the top?

idk. Anywhay here's my mod list:
Witherstormmod 3.2.1.3,

Worldedit 1.19.4,

Aether 1.19.4 BETA2

**Comment by nonamecrackers2** [comment]
> > is mod resouces at the top?
> 
> idk. Anywhay here's my mod list: Witherstormmod 3.2.1.3,
> 
> Worldedit 1.19.4,
> 
> Aether 1.19.4 BETA2

Please check if it is, could be the cause of the issue if it isnt

**Comment by Steve982950** [comment]
it wasnt before but NOW it is.

**Comment by Steve982950** [comment]
and it worked
