### ISSUE TITLE
Wither Storm behavior when it notices a player.

### ISSUE THREAD

**Issue by 1-Mythical** [nonamecrackers2/crackers-wither-storm-mod#1083]
**Description of feature**
I don't think this doesn't count as trying to mimic story mode's mechanics.

The Wither Storm focuses too much on the player when it spots one and doesn't give up at times it should.
If you throw an ender pearl out of sight from the wither storm, it will still start levitating the player towards it. You can literally throw a few ender pearls outside of one of the wither storm's beam range and you will still keep flying.

The Wither Storm also will not leave the player alone even after 5 minutes of going after a player.
If you go in an obsidian cage and the Wither Storm is trying to pick you up, it will sit there attempting that for 5 minutes.

What you should do is make the Wither Storm not be so focused on the player. (I know there is a config for favoring players, but it is just too much even with changing other options for player behavior.)

The Wither Storm looks very busy focusing on evolving in its early stages, but it shouldn't be that focused on the player when it has better to do.
(Just a story mode similarity.) The Wither Storm never really focused on anyone until it was in phase 4 in Story Mode.

**Comment by Globalfirestorm10** [comment]
There is an option to toggle favourability of players off

**Comment by BluePineappleGuy** [comment]
also the WS keeps pulling the player in about a second before the beam locks on, prob bug, and it also will not stop beaming the player no matter what 'till the head gets injured.

**Comment by 1-Mythical** [comment]
> There is an option to toggle favourability of players off

The favorability doesn't actually stop it from bothering you for 5 minutes. It will just go after something else if it sees something else, but if there is nothing else, then it still won't leave you alone.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
