### ISSUE TITLE
Severe lag is caused after installing the Ice and Fire mod together with this mod

### ISSUE THREAD

**Issue by JerryHan3** [nonamecrackers2/crackers-wither-storm-mod#1084]
**Minecraft version**
1.18.2

**Mod version**
2.2

**Describe the bug**
This mod causes severe lag on the server, making TPS drops to less than 10. The Spark profiler shows that the `WitherSicknessEvent` is the main cause of lag. However, the lag only appears after installing the Ice and Fire mod, and can't be removed by uninstalling the Ice and Fire mod. 

**To Reproduce**
1. Run a server with this mod and the Ice and Fire mod installed
2. Join this server
3. The server starts to experience severe lag

**Crash Reports / Logs**
- Spark profile: https://spark.lucko.me/780ea82Jdg
- Crash report when the watchdog forcibly stops the server: https://pastebin.com/Ff7cJJNc

**Is OptiFine installed?**
No

**Screenshots**
N/A

**Comment by nonamecrackers2** [comment]
Performance improvements involving the wither sickness have been made in 1.19.3+ and will just need to be backported to the 1.18 version
