### ISSUE TITLE
Game crashes when Wither Storm awokens

### ISSUE THREAD

**Issue by NiklasAmogus** [nonamecrackers2/crackers-wither-storm-mod#1085]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
          1.19.2

**Mod version**
    witherstormmod-1.19.2-3.1.1.1

**Describe the bug**
    I activate the witherstorm, then after a while when he becomes active, the game crashes. I cant join the server again after that

**To Reproduce**
1. Start Minecraft
2. Create a server (singleplayer)
3. Activate the witherstorm
4. When he starts moving the game crashes

**Crash Reports / Logs**
   Error: java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4

**Is OptiFine installed?**
           yes

**Screenshots**
![image](https://user-images.githubusercontent.com/129692699/229377326-90dfa6dd-9f3d-4d5b-ae07-55a1c1c1875b.png)
[crash-2023-04-03_17.29.37-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/11139884/crash-2023-04-03_17.29.37-client.txt)

**Comment by Globalfirestorm10** [comment]
For the reproduction, tell us what you did to crash the game. Please send the crash report as well

**Comment by NiklasAmogus** [comment]
OK, new thing, the game crashes only when im near the wither

**Comment by Globalfirestorm10** [comment]
Alright, mind showing me your mod list? It also might be caused by resourcepacks or shaders, as the crash report is reporting a failure to render a model. Alternatively, try forge 1.19.3 or 1.18.2, as 1.19.2 is kinda outdated

**Comment by NiklasAmogus** [comment]
OK I GOT IT, it was probably cuz of optifine. When my friends combined those two mods, the same thing happend to them. I disabled something in client options or how its called, then it worked fine even with optifine.

**Comment by Globalfirestorm10** [comment]
Mind telling us what you disabled?

**Comment by NiklasAmogus** [comment]
I changed the preset to low, then i the game stopped crashing, i tried to turn on some more things to see what caused the crash. It was Block cluster rendering

**Comment by Globalfirestorm10** [comment]
Makes sense

**Comment by nonamecrackers2** [comment]
If you want to keep block cluster rendering, you can disable block cluster coloring which will also fix the issue
