### ISSUE TITLE
Minor: Typo in client config

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1087]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2/1.19.4

**Mod version**
2.2.1/3.2.1

**Describe the bug**
In "Purple W Button → Client → Play Wither Storm Boss Music" when you hover over the button the tooltip says "NONE:" instead of "NOTE:"

**Is OptiFine installed?**
No

**Comment by Honey-Programming** [comment]
![Screenshot 2023-04-22 142824](https://user-images.githubusercontent.com/109185503/233807459-2879495c-2379-43b1-b935-113c333edd85.png)

**Comment by BluePineappleGuy** [comment]
> ![Screenshot 2023-04-22 142824](https://user-images.githubusercontent.com/109185503/233807459-2879495c-2379-43b1-b935-113c333edd85.png)

it also says "playerWitherStormTheme" instead of "playWitherStormTheme", guessing thats another typo

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
