### ISSUE TITLE
Block Cluster Issue

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1088]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2/1.19.4

**Mod version**
2.2.1/3.2.1

**Describe the bug**
When the Wither Storm dies, some block clusters from the bowels remain as an entity when they hit the ground allowing you to walk through them but not break any blocks.

**Is OptiFine installed?**
No

**Comment by Globalfirestorm10** [comment]
Mind sending some screenshots or a video of this?

**Comment by nonamecrackers2** [comment]
That would be helpful yes

**Comment by nonamecrackers2** [comment]
Closing until more information is given
