### ISSUE TITLE
Compatibility with Xaero's Minimap/World Map

### ISSUE THREAD

**Issue by StupidUserNameThin** [nonamecrackers2/crackers-wither-storm-mod#1089]
Possibly code in something ( Or make it a separate thing on CurseForge / Modrinth ) that would make the Wither Storm appear on the World Map, or Minimap, probably just the face of the wither storm, and maybe the three heads when its in the final two stages.

**Comment by GrandmaPork** [comment]
#778

**Comment by Globalfirestorm10** [comment]
As pork said, this is a duplicate, please close this
