### ISSUE TITLE
WS Beam block clusters are aligned in a way of where they don't grab what they're look at but in front of it 

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#109]
I've noticed that the tractor beams from the WS grab in front of the target instead of at the target causing it to be stuck on trying to grab something with the beam but being unable to it could be the way the beam is visually but is strange

**Comment by SSgamingYT** [comment]
I thought i noticed something strange about that

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update
