### ISSUE TITLE
Witherstorm pulses when in late stage 5

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1090]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2/1.19.4

**Mod version**
2.2.1/3.2.1.3

**Describe the bug**
When the Wither Storm reaches late phase 5, it appears that enderman ripping/pulsing occurs even though not completed in it's evolution.

**Is OptiFine installed?**
No

**Comment by Globalfirestorm10** [comment]
Mind including some screenshots or a video of this?

**Comment by BluePineappleGuy** [comment]
i thought that was intended. kinda makes sense tho, this is its max stage without the formidibomb

**Comment by Honey-Programming** [comment]
But it isn't being torn by enderman in the late 5 phase

**Comment by Globalfirestorm10** [comment]
I am very confused here. The hole to the storms bowels appears at phase 7 (you may have to wait about 20 min, idk the exact time), and enderman do not make the hole. This feature was suggested many times, but turned down

**Comment by myron-obsolete-account** [comment]
you are confusing me even more

**Comment by Globalfirestorm10** [comment]
> you are confusing me even more

Sorry I wrote this at 1am, polished it up a bit just to make it less confusing

**Comment by Steve982950** [comment]
i think i know what he means.... in the end of stage 5, certain areas/blocks of the mass pulse brighter. same thing happens in Final stage. this isn't a bug.

**Comment by nonamecrackers2** [comment]
If you let the phase 5 wither storm alone for long enough it would eventually get to the point where it ate enough to have the pulse effect render. Technically not intended

**Comment by Honey-Programming** [comment]
> i think i know what he means.... in the end of stage 5, certain areas/blocks of the mass pulse brighter. same thing happens in Final stage. this isn't a bug.

The pulsing represents enderman tearing the storm apart

**Comment by Honey-Programming** [comment]
> Mind including some screenshots or a video of this?

SOON

**Comment by Honey-Programming** [comment]
> I am very confused here. The hole to the storms bowels appears at phase 7 (you may have to wait about 20 min, idk the exact time), and enderman do not make the hole. This feature was suggested many times, but turned down

But in the mod config it says: "Render pulsing to visualize the effect of enderman tearing the Wither Storm apart".

**Comment by Honey-Programming** [comment]
Pictures:

![2023-04-04_22 12 09](https://user-images.githubusercontent.com/109185503/229987124-8ec82c32-c0c5-45c7-9570-b63166f34f87.png)

**Comment by Honey-Programming** [comment]
Look at the white spots. Those are the pulses.

**Comment by Steve982950** [comment]
> If you let the phase 5 wither storm alone for long enough it would eventually get to the point where it ate enough to have the pulse effect render. Technically not intended

ohh silly me

**Comment by Globalfirestorm10** [comment]
> > I am very confused here. The hole to the storms bowels appears at phase 7 (you may have to wait about 20 min, idk the exact time), and enderman do not make the hole. This feature was suggested many times, but turned down
> 
> 
> 
> But in the mod config it says: "Render pulsing to visualize the effect of enderman tearing the Wither Storm apart".

You said "enderman tearing", and I thought that meant the hole to the bowels opening, so mb

**Comment by honey-java** [comment]
Anyone want to fix it

**Comment by Globalfirestorm10** [comment]
The bug still needs to be confirmed, and the code is closed source, so crackers will fix it eventually, just have patience

**Comment by myron-obsolete-account** [comment]
> Anyone want to fix it

this guy

**Comment by Demonmaster-MD** [comment]
> 

Oh I thought it was 😅

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release

**Comment by Honey-Programming** [comment]
When a project is on it's last beta why does it take forever to release
