### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by VeryKitty03** [nonamecrackers2/crackers-wither-storm-mod#1091]
Will there EVER be a fabric version of this mod?  I'm asking because on the curseforge page it says that is is not currently.  My question is about the currently.

**Comment by Globalfirestorm10** [comment]
no, this has been asked before, and crackers has said no (same thing goes for bedrock), as fabric doesn't have an advanced enough API for modding, and bedrocks modding API does not exist

**Comment by myron-obsolete-account** [comment]
#1073 
#439 
#887 
this

and so many times on crackers youtube comments site and on his mod page comments
on the mod page, both curseforge and modrinth, its stated with a big fat marker that fabric will not happen.

**Comment by nonamecrackers2** [comment]
The current is still currently no, sorry
