### ISSUE TITLE
Tamed/Name tagged pets would come back after wither storms death

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1092]
when the funni storm eats your pets you will have a depresso but when the storm dies your very cool pets that have been tamed or name tagged will fall on the ground (wont die) and your depresso will be cured and every1 would be living happily ever after (until sum idiot resummons him)

jokes aside a cool feature if your beloved animal gets eaten by the storm he would come back after storms death

:jess:

**Comment by myron-obsolete-account** [comment]
would technically make sense as the wither storm does not actually destroy consumed objects but instead just creates a massive pile of trash of them, one stacked above another, thats why it keeps growing etc. bla bla bla lore stuff idk idc

so pets should be able to return, but maybe with a 50/50 chance, as they might get crushed by falling block clusters or common-sensely die of height or something else. or maybe you can find them as sickened mobs in the bowels, and you need to unsicken them with a golden apple soup or something idk thats just an idea yeahhh

**Comment by darkheart78** [comment]
i agree because my dog sammy the sdog was murdered

**Comment by Pandaboi25x** [comment]
> i agree because my dog sammy the sdog was murdered

rip

**Comment by Pandaboi25x** [comment]
> 

i was thinking bout the bowels part but your friends could just kill your pet

**Comment by Pandaboi25x** [comment]
> would technically make sense as the wither storm does not actually destroy consumed objects but instead just creates a massive pile of trash of them, one stacked above another, thats why it keeps growing etc. bla bla bla lore stuff idk idc
> 
> so pets should be able to return, but maybe with a 50/50 chance, as they might get crushed by falling block clusters or common-sensely die of height or something else. or maybe you can find them as sickened mobs in the bowels, and you need to unsicken them with a golden apple soup or something idk thats just an idea yeahhh

i was thinking bout the bowels part but your friends could just kill your pet

**Comment by BluePineappleGuy** [comment]
they should also respawn when the WS gets blown up by the f-bomb

**Comment by Composer-Hu** [comment]
Maybe you can use this mod for a while
https://www.curseforge.com/minecraft/mc-mods/domestication-innovation

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
