### ISSUE TITLE
Faint White line at the bottom left of screen

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#1093]
This is presumably the part where the music names are displayed

**Comment by Globalfirestorm10** [comment]
Mind sending a screenshot of this?

**Comment by myron-obsolete-account** [comment]
what kinda prank is this? wheres the filled out bug template?

**Comment by Globalfirestorm10** [comment]
Yeah, please fill out the template  next time, inonedn

**Comment by nonamecrackers2** [comment]
Please fill out the bug report template

**Comment by myron-obsolete-account** [comment]
@Inonedn hello we want to help but please provide information. open a new issue with actually stating information this time ._.

**Comment by Inonedn** [comment]
Its difficult to take a screenshot due to how Minecraft automatically pauses

**Comment by myron-obsolete-account** [comment]
what

**Comment by Globalfirestorm10** [comment]
> Its difficult to take a screenshot due to how Minecraft automatically pauses

Pressing f2 pauses Minecraft? Perhaps check your keybinds

**Comment by myron-obsolete-account** [comment]
> > Its difficult to take a screenshot due to how Minecraft automatically pauses
> 
> Pressing f2 pauses Minecraft? Perhaps check your keybinds

yeah im confused
