### ISSUE TITLE
Sickened zombies texture breaks when symbionts spawns mobs

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1094]
i belive this also happens in the bowels
here
![image](https://user-images.githubusercontent.com/121638798/230427280-9371cd3c-5e9f-4541-b7a1-adf05a747a6d.png)

:jess:

**Comment by Pandaboi25x** [comment]
i put it as a suggestion omg

**Comment by Pandaboi25x** [comment]
im so stupid
:waa:

**Comment by Globalfirestorm10** [comment]
Hey, mind just sending your mod list? It might be a mod confliction

**Comment by Pandaboi25x** [comment]
> Hey, mind just sending your mod list? It might be a mod confliction

its only cwsm with zero resuource packs

**Comment by Globalfirestorm10** [comment]
Oh, that's odd, mind editing your first message with the template filled out? Or you can state the info that the template asks in a comment

**Comment by nonamecrackers2** [comment]
Probably something on my end, will have to investigate

**Comment by Inonedn** [comment]
Can confirm, it happens to me too

**Comment by IndigoAmethyst** [comment]
In pretty sure it's a issue when rendering armor. @nonamecrackers2

**Comment by BluePineappleGuy** [comment]
looks like a model issue of some sort. probably the game doesn't recognize the head correctly?

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
