### ISSUE TITLE
Faint White line at bottom left of screen

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#1095]
NOTE: This may be a graphical error, as I cannot seem to replicate it via screenshot, or could be a starlight/rubidium issue
**Minecraft version**
1.19.4

**Mod version**
Latest

**Describe the bug**
At the bottom left of the screen, a small white line can be seen. It briefly disappears when announcing the Withered Symbiote's boss theme.

**To Reproduce**
1. Enter a world
2. See faint white line on bottom left
3. Line disappears when announcing Wither Symbiote theme

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
No

**Screenshots**

![2023-04-06_15 07 42](https://user-images.githubusercontent.com/36087299/230472510-cc3c52c3-99ed-4388-9fac-48b96547283b.png)

**Comment by Inonedn** [comment]
![error](https://user-images.githubusercontent.com/36087299/230473032-feec2bc9-e680-4e43-8cb7-2384d713cad0.jpg)

**Comment by myron-obsolete-account** [comment]
do you mean this very small line that brightens up the pixels just a bit?

**Comment by myron-obsolete-account** [comment]
it seems like an issue with your monitor, try other games or just do some other activities and if this issue is present outside of minecraft then its not an issue with this mod

**Comment by myron-obsolete-account** [comment]
@Inonedn are you still alive?

**Comment by myron-obsolete-account** [comment]
@Inonedn hello? we need information please

**Comment by myron-obsolete-account** [comment]
I feel ignored.

**Comment by LocalWaterCreeper911911** [comment]
> I feel ignored.

F

**Comment by nonamecrackers2** [comment]
Going to be closing this since it only appears on your monitor, appears to be an issue on your end.
