### ISSUE TITLE
Amulet Crafting Recipe

### ISSUE THREAD

**Issue by AffyTaffy5** [nonamecrackers2/crackers-wither-storm-mod#1096]
We need an amulet crafting recipe. If there is one, please let me know about it. Best regards, AffyTaffy5.

**Comment by BATIMBendyTheDemon** [comment]
> 

There is one

**Comment by Globalfirestorm10** [comment]
@AffyTaffy5 there is one, please close this

**Comment by GrandmaPork** [comment]
Download JEI to your mod list. This would be a question for the discord

**Comment by Composer-Hu** [comment]
The synthesis above is a creature that can be bound to the same kind.
![K9G@PDD72V}HQLVMWCILEJ5](https://user-images.githubusercontent.com/127498588/230573949-cece9319-0b0c-40c6-99dd-7bf6efcb591c.png)
