### ISSUE TITLE
Improve phases from 0 to 4

### ISSUE THREAD

**Issue by Asaredapvp2** [nonamecrackers2/crackers-wither-storm-mod#1097]
Improve phases from 0 to 4. Phase 0, 1, 2 and third are okay but the jump from phase 3 to 4 is too big, make it look like in mcsm, it slowly builds up to phase 4, it doesn't just jump up in size. To me, the difference between these two is not balanced.

**Comment by Globalfirestorm10** [comment]
Already suggested, please close this

**Comment by myron-obsolete-account** [comment]
#90 #316 #788 close this please ._.
