### ISSUE TITLE
Compatibility with Biomes o' Plenty

### ISSUE THREAD

**Issue by 3u9en** [nonamecrackers2/crackers-wither-storm-mod#1098]
Hello

I have 2 mods installed, The witherstorm and Biomes o' plenty.

When i go into the game, i don't see anywhere the house spawn of the witherstorm. 
Is it even compatible with the Biomes o' plenty mod?

Thank you in advance.

**Comment by WitherBean** [comment]
Do you not see it at 0,0?

**Comment by WitherBean** [comment]
If not, where did you spawn? (the coordinates)

**Comment by Globalfirestorm10** [comment]
Perhaps fill out the bug report template with this? If it's an actual incompatibility with BOP, it is technically a bug

**Comment by 3u9en** [comment]
I think it is also a bug, I spawned in Mystic Grove biome. When I looked around, i didn't see the structure, and i typed in to locate the structure, it said it wasn't found. 
When I made a new world generation, I spawned in Meadows and then I saw the structure

**Comment by nonamecrackers2** [comment]
Please open a new issue and fill out the template. CWSM should be compatible, so if the house is not generating then it’s probably a bug
