### ISSUE TITLE
Bowels with other modded things inside

### ISSUE THREAD

**Issue by ThatB0i** [nonamecrackers2/crackers-wither-storm-mod#1099]
what if the Wither storm bowels had stuff like create contraptions or furniture inside from other mods? just to add more bowel parts that are relevant to the other mods in a mod pack?

also saying this because of the event for the bowels.

**Comment by GrandmaPork** [comment]
“You could probably do this with datapacks”
-Nazaru

**Comment by nonamecrackers2** [comment]
Yeah, datapacks that modify the structure nbt files could do this.

**Comment by ThatB0i** [comment]
ok then

sorry about that
