### ISSUE TITLE
"Crashing"

### ISSUE THREAD

**Issue by Fazbea** [nonamecrackers2/crackers-wither-storm-mod#11]
I don't know if this is where they report bugs but anyway. When I summon Wither Storm it remains blue, the particles move and so do I, but the proof that when I summon it the game crashes monstrously, is that when I moved away, the rendered area remained and did not continue to render, another proof is that when I went to use the Crafting Table, It just didn't open the crafting menu. I ask for your help

**Comment by ScriptleGIT** [comment]
What's your PC Parts Are? On low-end PC it(mod) will crash

**Comment by nonamecrackers2** [comment]
What are your hardware specs?

**Comment by Fazbea** [comment]
Oh, is that ta reason. Thx


Em sáb, 14 de mai de 2022 00:52, MythixOfficialGIT ***@***.***>
escreveu:

**Comment by nonamecrackers2** [comment]
Well it can be or not
