### ISSUE TITLE
(1.18.2) Dynamic Surroundings Resurrected incompat

### ISSUE THREAD

**Issue by Swagboi7** [nonamecrackers2/crackers-wither-storm-mod#110]
When the Wither Storm goes into its distant render mode, it has these cool ambient sound effects, right? Well, with DSR, when the Wither Storm’s distant renderer is obstructed, say, you can’t see it because there’s a tree in front of you, the ambient sounds just cut off. Maybe all I need to do is change some settings up, but I just need to make sure this bug is known.

**Comment by nonamecrackers2** [comment]
Found the issue. You'll need to disable "Enable Sound Occlusion Calculations" in "sndctrl-client.toml"
