### ISSUE TITLE
Holding amulet in-hand doesnt allow me to break blocks

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1100]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
When I hold an amulet in my hand, it wont allow me to break blocks

**To Reproduce**
1. Hold amulet
2. try to break blocks

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
N/A

**Screenshots**

https://user-images.githubusercontent.com/128298281/230788151-2325fdef-c645-482c-b896-94b0377ca03b.mp4

**Comment by Pandaboi25x** [comment]
also experienced it
(whatis that xp :skull:

**Comment by myron-obsolete-account** [comment]
if your amulet doesn't like you, swap it with a new one, if you still have the receipt

**Comment by Steve982950** [comment]
ok

Edit: i tried swapping the amulet and still WONT allow me

**Comment by myron-obsolete-account** [comment]
> ok
> 
> Edit: i tried swapping the amulet and still WONT allow me

that was a joke 💀

**Comment by Steve982950** [comment]
bruh

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
