### ISSUE TITLE
"Smarter" Sky darkening effect

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#1101]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

Something I would like to see in this mod (particularly for the sky darkening effect when near the wither storm) is a feature where the closer you are to the storm, the more visible the effect becomes. So you could start at the sky becoming a little tinted/dimmed, and then end at the actual effect being fully present when near the storm (in other words, the closer the storm is to you, the more darker/tinted the sky is).

**Comment by nonamecrackers2** [comment]
It already does this? Or do you mean you'd prefer for the effect fade to be more dramatic?

**Comment by Globalfirestorm10** [comment]
> It already does this? Or do you mean you'd prefer for the effect fade to be more dramatic?

it does? huh, never really noticed that. In that case, I'd say it should be a little more dramatic, apologies for the confusion 😄

**Comment by myron-obsolete-account** [comment]
in early phases up to phase 3 the darkening is default boss entity darkening and only occurs when the WS is inside of your render distance. same probably with phase 4 and 5. at phase 5+ the sky darkens when you are near the ws but it can already darken even if its still outside of your render radius. thats what i think, havent played the mod in a long time so idk if i said something wrong now

**Comment by Globalfirestorm10** [comment]
I'm morso talking about later phase like 6 and 7, but ok

**Comment by myron-obsolete-account** [comment]
a.

**Comment by IndigoAmethyst** [comment]
Phase 0-5 darkens the sky exactly the same as the normal Wither does by slightly darkening the sky and turning the horizon grey (When in render distance).

Phase 5.5 adds an effect to the sky that makes it look darker the closer it is. When the WS is in render distance it's the just like evening.

Phase 6 - 7.5 have the same effect but much more intense with the sky being pure purple when the WS is in render distance.

**Comment by nonamecrackers2** [comment]
I think the current fade distance it has is fine, making this distance too large would result in the sky to start darkening when the Wither Storm is still pretty far away.
