### ISSUE TITLE
Wither Storm wont spawn when placing last skull

### ISSUE THREAD

**Issue by LvnaTheWorst** [nonamecrackers2/crackers-wither-storm-mod#1102]
**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
I was really excited to play this but then when I place the last wither skull, it aint working. The wither isn't spawning. I tried remaking it, nothing. Can anyone help or I will be crying for days cause I cant play this lol

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
Specify if you're using OptiFine

**Screenshots**

**Comment by Globalfirestorm10** [comment]
Check if you have the game rule Mobgriefing to true, and check if you have peaceful mode on

**Comment by Globalfirestorm10** [comment]
Also please fill out the template next time

**Comment by myron-obsolete-account** [comment]
@LvnaTheWorst update?

**Comment by nonamecrackers2** [comment]
What mods do have installed?

**Comment by nonamecrackers2** [comment]
Closing until more information is provided

**Comment by MoRoN222** [comment]
@LvnaTheWorst hey did you know that opening an issue and not providing more information when getting asked is absolutely unprofessional? If you want your issue to be resolved cooperate with us now or stay silent forever
