### ISSUE TITLE
Amulet item not working correctly

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1104]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.1

**Describe the bug**
the amulet doesn't glow when i hold it in my hand and point to the storm, nor does it visually swap when i shift-rightclick. its only really usable in the tooltip

**To Reproduce**
1. Get an amulet
2. look at the WS or shift-rightclick
3. See error

**Crash Reports / Logs**
none

**Is OptiFine installed?**
No, but mod 'rubidium' is in use instead

**Screenshots**
none

**Comment by GrandmaPork** [comment]
Screenshot pls

**Comment by Globalfirestorm10** [comment]
Perhaps you have conflicting keybinds? Check you keybinds and swap them out for non-conflicting ones if they are conflicting

**Comment by BluePineappleGuy** [comment]
> Perhaps you have conflicting keybinds? Check you keybinds and swap them out for non-conflicting ones if they are conflicting

i can tell its swapping, the sound plays and it binds correctly. but no animations play (it doesnt visually rotate or glow)

**Comment by nonamecrackers2** [comment]
This has been fixed, use the latest 1.19.4 version

**Comment by myron-obsolete-account** [comment]
> This has been fixed, use the latest 1.19.4 version

is 1.19.3 still supported (updates etc.) or do I need to switch versions again?

**Comment by nonamecrackers2** [comment]
1.19.3 is no longer supported except for critical bug fixes

**Comment by myron-obsolete-account** [comment]
> 1.19.3 is no longer supported except for critical bug fixes

you've gotta be kidding me

**Comment by Globalfirestorm10** [comment]
> 1.19.3 is no longer supported except for critical bug fixes

Well, that's extremely disappointing

**Comment by nonamecrackers2** [comment]
Sorry to disappoint. I’d love to support all those versions but the amount of work to make content updates for several different versions is not worth my time. Hope you can understand
