### ISSUE TITLE
Withered symbiont tentacle use

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1105]
The withered symbiont should be able to use its tentacles in certain cases, such as:
1. When the player hits the back, instead of turning around and attacking the player, the tentacles should swat the player away with a force half the amount of the bowels' tentacles (enough to knock the player back but not to send them flying).
2. The symbiont can grab the player between spells and attack the player. Hitting the symbiont 3-4 times will cause it to drop you but you don't hurt the symbiont;
3. The symbiont can grab nearby blocks and hurl them at you. Damage it does on collision with the player depends on either the blocks harvest level or time it takes to break the block.

**Comment by nonamecrackers2** [comment]
The withered symbionts tentacles are merely for cosmetic purposes, and they're not really long enough to do anything meaningful. As said with the making the Wither Storm's tentacles interactable multiple times before, doing something like this is extremely difficult and not worth my time.
