### ISSUE TITLE
Wither does not seems to be tracking ultimate target properly

### ISSUE THREAD

**Issue by fulRicardosun1** [nonamecrackers2/crackers-wither-storm-mod#1107]
**Minecraft version**
1.18.2

**Mod version**
witherstormmod-1.18.2-2.2.1

**Describe the bug**
Not sure but I would like to confirm. After spawning Wither storm and teleporting 2000+ (also tested with 1M) blocks away. Wither seems to not be tracking and flying towards the ultimate target (If I understand it correctly, it tracks a player [Btw I also had the amulet] and tries to seek it accelerating itself). 

**To Reproduce**
1. Spawn wither Storm (you can wait for phase 5 if you want or just go to step 2 if you don't want to wait or run a command to skip´phases)
2. Teleports or run away (Can be in creative or survival)
3. Grab an amulet (I did this through JEI cheat mode so I didn't have to change to creative)
4. Stay stationary and just keep looking at the amulet for the distance in between you and the wither storm (you'll notive that even after 1 hour nothing will happen and at least he might be a little bit close due his random walks)

**Crash Reports / Logs**
Not sure where to grab it, let me know how I can help

**Is OptiFine installed?**
No, only rubidium

**Screenshots**
Not aplicable, let me know if you have any ideas for screenshot if needed

Pos post:
Looks like it is now tracking on last phase (Before having to use the Fbomb). It is going towards me, I teleported myself over 1Milion blocks away again and let's see if it tracks me correctly until it reaches me (as I tested before and it stopped tracking me at some point but I'll test it again). I'll keep it posted and probably delete this post if working correctly

**Comment by GrandmaPork** [comment]
There’s a limit to the distance. Also it get distracted after a certain time

**Comment by fulRicardosun1** [comment]
@GrandmaPork, and after a while this happens. does it goes back to track the player? Or there is a way to recover this tracking module without having to get close to the Wither again? 

The idea is to make kind of a "Apocalypse" that one day will reach out the player if they stay where the player is for a while.

**Comment by Globalfirestorm10** [comment]
Depending on how far you are. After a certain distraction period, assuming you are 10000 or less blocks away from it, it will begin to track you again, albeit it may not be noticeable depending on how far you are from it, and how fast your flying speed is, along with other config settings

**Comment by GrandmaPork** [comment]
I believe the limit is 80,000 blocks, which should be plenty for your idea. Also, I cannot remember exactly how it works but when it's in between two distances (i.e. minimum of 800, maximum of 2,000), it has a chance to get distracted for a configurable amount of time. Then it returns to tracking the player. I'd look into the world configs. Also, for the amulet not glowing when looking at wither storm, can you send a screenshot? If I'm not mistaken, it also only glows when the wither storm is a certain amount of blocks away

**Comment by nonamecrackers2** [comment]
Just noticed your edit there, did you manage to get all the phases tracking you or?

**Comment by fulRicardosun1** [comment]
Hi guys,

Sorry for keep you waiting. No, for extreme distances there is a big chance
he will stop tracking you after a very long time.

Just found a way for doing what I was trying to do (The imminent apocalypse
stuff) but through the FTB Quests mod, just spawning the WS after certain
conditions (you can configure it, in my case, I put a timer after the
player sees the ender portal opened and wait for 3 days). So in normal
gameplays, the player will not likely be so many blocks away from X:Z = 0
(Where by default the WS will be spawned), which makes the WS able to track
it without any problems.

Just for safe measures, I added a repeatable quest to force spawn a
symbiont so you can kill it on demand in case it does not spawns and WS
eats your world.

So technically you can close this bug and put this FTB Quest mod workaround
as a solution

Regards,

Em sáb., 15 de abr. de 2023 13:25, nonamecrackers2 ***@***.***>
escreveu:

**Comment by nonamecrackers2** [comment]
Alright if that works then, if you figure out a specific mod that’s causing the issue, let me know
