### ISSUE TITLE
i dont have music

### ISSUE THREAD

**Issue by VANA1122** [nonamecrackers2/crackers-wither-storm-mod#1108]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on
1.19.4

**Mod version**
The version of the mod you are using
new

**Describe the bug**
i dont have music

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
Specify if you're using OptiFine

**Screenshots**

**Comment by myron-obsolete-account** [comment]
enable it in the config

**Comment by Globalfirestorm10** [comment]
Also next time please fill out the template. With that aside, go to options, click the purple w, go to client settings, then enable all config options that correspond to playing themes.

**Comment by myron-obsolete-account** [comment]
funny how they put "new" to the mod version like bro in atleast 1 month "new" isn't valid anymore

**Comment by Steve982950** [comment]
for ''Mod Version'' put
3.2.1.3 of if different mc version check the file. for instance, for 1.19.2, check what it says after 1.19.2. it may say
''witherstormmod_1.19.2_3.1.1.''

**Comment by nonamecrackers2** [comment]
> for ''Mod Version'' put 3.2.1.3 of if different mc version check the file. for instance, for 1.19.2, check what it says after 1.19.2. it may say ''witherstormmod_1.19.2_3.1.1.''

I don't think they're going to reply to you considering this is a two month old issue.

**Comment by Steve982950** [comment]
ok i guess.
