### ISSUE TITLE
the game will crash whenever i try to launch it i was going to make a small seris on this mod as a surviavl challange its not a very big modpack considting of less than 50 mods

### ISSUE THREAD

**Issue by gamingcactus486** [nonamecrackers2/crackers-wither-storm-mod#1109]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2

**Mod version**
witherstormmod-1.18.2-2.2.1.jar

**Describe the bug**
crashes when ever i try to lauch a moppack with this mod

**To Reproduce**
1. Go tothe launcher
2. Click on play

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.
[crash-2023-04-13_02.43.33-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/11233231/crash-2023-04-13_02.43.33-server.txt)

**Is OptiFine installed?**
nope i tried it with adn without and it didnt make a differnce

**Comment by myron-obsolete-account** [comment]
fill the template with information and send your mod list so we can try to identify conflicting mods

**Comment by gamingcactus486** [comment]
> fill the template with information and send your mod list so we can try to identify conflicting mods

there was nothing conflicting
its doing
 this if its just on its own

**Comment by GrandmaPork** [comment]
What’s your modlist

**Comment by Globalfirestorm10** [comment]
Make sure you have the latest optifine 1.18.2 version with it's corresponding forge version (if you use optifine, which I'm pretty sure of)

**Comment by nonamecrackers2** [comment]
> Make sure you have the latest optifine 1.18.2 version with it's corresponding forge version (if you use optifine, which I'm pretty sure of)

Yep, this looks exactly like this issue

**Comment by darkheart78** [comment]
i farted and it smells really bad
