### ISSUE TITLE
Block update glitch caused by Symbiont's "Jump" spell

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1110]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on
1.19.3
**Mod version**
The version of the mod you are using
All versions related to "A Block and a Hard Place" update, tested in 3.2 and 3.2.1.1 so far
**Describe the bug**
When symbiont jumps, it leaves "glitched area" behind.
**To Reproduce**
1. Summon symbiont
2. hurt him

**Is OptiFine installed?**
No other mods instaled.

**Screenshots**
![2023-04-10_22 31 45](https://user-images.githubusercontent.com/129298645/232105926-5e51571d-ca10-442f-a382-4988922a3a3d.png)
![2023-04-10_22 30 53](https://user-images.githubusercontent.com/129298645/232105990-b2aa9878-9cab-400e-b85f-bad7918d5dc3.png)

**Comment by myron-obsolete-account** [comment]
i dont see a glitched area there. are you sure there is an issue?

**Comment by LocalWaterCreeper911911** [comment]
I'll reply when ill have time. Just dont close this now OK?

**Comment by LocalWaterCreeper911911** [comment]
How should i record a video in MC 1 19 3? My brain is about to explode

**Comment by nonamecrackers2** [comment]
What is the behavior of this "glitched area?" Are you possibly getting "stuck" in imaginary blocks or?

**Comment by LocalWaterCreeper911911** [comment]
@nonamecrackers2  YES i am getting stuck

**Comment by nonamecrackers2** [comment]
It probably is some desync then. I'll have to investigate

**Comment by LocalWaterCreeper911911** [comment]
I've seen someone on Youtube replicate this bug

**Comment by nonamecrackers2** [comment]
> I've seen someone on Youtube replicate this bug

Mind sending the video?

**Comment by LocalWaterCreeper911911** [comment]
Yes i do, give me time

**Comment by LocalWaterCreeper911911** [comment]
https://www.youtube.com/watch?v=6baAowCUzBs

7:30-8:00

**Comment by LocalWaterCreeper911911** [comment]
Wrong timestamp, 11:20-12:00 (He fought second symbiont)

**Comment by LocalWaterCreeper911911** [comment]
@nonamecrackers2

**Comment by myron-obsolete-account** [comment]
> @ nonamecrackers2

no need to do that, he'll see it at one point anyways

**Comment by LocalWaterCreeper911911** [comment]
> no need to do that, he'll see it at one point anyways

Alright, i get it. By the way, what are "imaginary blocks"? I've never heard of these.

**Comment by nonamecrackers2** [comment]
Interesting, will have to see what’s causing this then. The “imaginary blocks” are blocks that actually exist, but to the player they don’t exist

**Comment by LocalWaterCreeper911911** [comment]
Six days passed. How is the "investigation" process going?

?

Also why is that "needs confirming" tag everywhere?

**Comment by LocalWaterCreeper911911** [comment]
@nonamecrackers2 didnt want to live in the same world as Wither Storm

**Comment by myron-obsolete-account** [comment]
> @nonamecrackers2 fell out of the world

what

**Comment by myron-obsolete-account** [comment]
> Also why is that "needs confirming" tag everywhere?

![image](https://user-images.githubusercontent.com/53058491/233374611-3403e8f7-a3e7-4989-921d-1d12f833eb0c.png)

**Comment by LocalWaterCreeper911911** [comment]
> Also why is that "needs confirming" tag everywhere?


> ![](https://user-images.githubusercontent.com/53058491/233374611-3403e8f7-a3e7-4989-921d-1d12f833eb0c.png)

Yeah i saw this thingo too, but if bug happens to at least two people, then its confirmed right?

Oh god there are already 20 comments. What have i done...

> How should i record a video in MC 1 19 3? My brain is about to explode

What about this?

**Comment by myron-obsolete-account** [comment]
> > How should i record a video in MC 1 19 3? My brain is about to explode
> 
> What about this?

Back then I used a program called oCam but now since I have a new PC I'm just using the integrated NVIDIA GeForce Experience Screen Recording since I have a GTX Graphic Card

**Comment by LocalWaterCreeper911911** [comment]
> @nonamecrackers2 didnt want to live in the same world as Wither Storm

> what

@MoRoN222 , its a death message that appears when you /kill yourself when inside the tractor beam;
to put that simple, cracker is dead

**Comment by myron-obsolete-account** [comment]
yeah please stop being cringe and put minecraft death messages here thanks

**Comment by LocalWaterCreeper911911** [comment]
Alright, lets be quiet until cracker pops in.

**Comment by LocalWaterCreeper911911** [comment]
Cracker is still inactive, which (probably) means that he is working on something big that he wants to implement in the next update, which makes me happy happy happy happy happy happy happy

**Comment by LocalWaterCreeper911911** [comment]
My nickname is the opposite of @globalfirestorm10(and yes i s u k at nicknames)

global - local

fire - water

storm - creeper

10(small number) - 911911(big number)

**Comment by Globalfirestorm10** [comment]
> My nickname is the opposite of @globalfirestorm10(and yes i s u k at nicknames)
> 
> 
> 
> global - local
> 
> 
> 
> fire - water
> 
> 
> 
> storm - creeper
> 
> 
> 
> 10(small number) - 911911(big number)

Ok?

**Comment by myron-obsolete-account** [comment]
> My nickname is the opposite of @Globalfirestorm10(and yes i s u k at nicknames)
> 
> global - local
> 
> fire - water
> 
> storm - creeper
> 
> 10(small number) - 911911(big number)

bro sorry but that's just cringe 💀

**Comment by LocalWaterCreeper911911** [comment]
I know, nobody cares, but i cant stop being cringe for two reasons:

1. I'm russian:)

2.#whereiscracker

**Comment by nonamecrackers2** [comment]
Let's try to stay on topic for the issue at hand. If you want to chat feel free to join the [discord server](https://discord.gg/W2f3DxR9pV)

**Comment by LocalWaterCreeper911911** [comment]
> Let's try to stay on topic for the issue at hand. If you want to chat feel free to join the [discord server](https://discord.gg/W2f3DxR9pV)

thanks, didnt know about it

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
