### ISSUE TITLE
add the tainted sapling

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1111]
a very cool yet small feature for builders dunno what to say anymore like pretty self explainable title

:jess:

**Comment by BATIMBendyTheDemon** [comment]
:jess:

**Comment by LocalWaterCreeper911911** [comment]
:jess:

**Comment by myron-obsolete-account** [comment]
:jess:

**Comment by Pandaboi25x** [comment]
a misc very coooll

**Comment by Pandaboi25x** [comment]
coming back to this and great heavens what chain have i created 💀

**Comment by LocalWaterCreeper911911** [comment]
> coming back to this and great heavens what chain have i created 💀

:jess:

**Comment by watersofnazareth** [comment]
As of now I'm not going to add a tainted sapling, the plants in the bowels are all meant to be dead/dying and shriveled up, making a sapling doesn't make much sense in that regard
