### ISSUE TITLE
If right conditions are met, block clusters can go through portals

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1112]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on
1.19.3
**Mod version**
The version of the mod you are using
3.2
**Describe the bug**
Title, i dont know the"conditions" tho
**To Reproduce**
1. Create a Nether Portal under the WS and hope for the best
2. See error

**Is OptiFine installed?**
As always, no other mods installed

**Screenshots**
![2023-03-03_21 03 19](https://user-images.githubusercontent.com/129298645/232230884-0e28e681-eabb-4389-a8b0-59f7232a0ffe.png)

**Comment by myron-obsolete-account** [comment]
block clusters are entities and entities can go through portals so this is technically normal but probably unintended for common sense etc. so I think crackers will look into it but idk its kinda cool though

**Comment by LocalWaterCreeper911911** [comment]
@MoRoN222  I know that BC are entities etc. but IMAGINE if BC that contains water goes through portal like THIS

illegal water in the nether CONFIRMED

**Comment by LocalWaterCreeper911911** [comment]
I reloaded my world a couple times before this happened, so it might be caused by #690

**Comment by LocalWaterCreeper911911** [comment]
Please add 1.16.5; 1.18.2; 1.19.2 labels because BC always were entities.

**Comment by LocalWaterCreeper911911** [comment]
Or not idk

**Comment by nonamecrackers2** [comment]
1.16.5 and 1.18.2 are no longer supported and won’t be receiving this bug fix since it isn’t critical

**Comment by LocalWaterCreeper911911** [comment]
Really? I didn't know(i'm about 1.18.2).
Why did you remove 1.19.3 tag?

**Comment by nonamecrackers2** [comment]
1.19.3 is also no longer supported. It doesn’t make sense to be supporting two minor MC versions

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
