### ISSUE TITLE
Can't see the storm when you get out of render distance with speed on and you go high enough in the air

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1114]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
1.19.4
**Describe the bug**
Title is pretty self explanatory. You can't see the storm anymore if you go about 200-300 blocks in the air  with high speed effects on. (Though I realize this isn't too consistent but is still there.

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
no

**Screenshots**

**Comment by Globalfirestorm10** [comment]
Provide screenshots of this problem and your mod list

**Comment by nonamecrackers2** [comment]
Please state the version of the mod you are using. It should be stated in the file name of the witherstormmod jar

**Comment by Pandaboi25x** [comment]
> Please state the version of the mod you are using. It should be stated in the file name of the witherstormmod jar

its this one ![image](https://user-images.githubusercontent.com/121638798/232558504-0782bed9-b3b6-4b75-936f-a6dd7edf8309.png) (played with him at that time)

**Comment by nonamecrackers2** [comment]
Unable to reproduce. Can see the storm just fine 
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/105086648/0be797ea-2472-4ee2-b6bc-7e844e7bc1b9)
