### ISSUE TITLE
The Strong Grow Weak... and ...The Weaken Arise Stronger advancements are skippable

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#1117]
**Minecraft version**
1.19.4

**Mod version**
Latest

**Describe the bug**
Presumably in a chunk the player isn't loaded in. Upon blowing up the Storm or having it revive automatically will skip the 2 advancements entirely

**To Reproduce**
1. Kill the Storm via a Formidibomb or let it Auto-Revive while not loaded in its chunk
2. See error

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
N/A

**Screenshots**
N/A

**Comment by LocalWaterCreeper911911** [comment]
I was about to open the same issue

**Comment by nonamecrackers2** [comment]
This is technically intended however I can make the advancement global. I’d make a new issue to suggest this change.
