### ISSUE TITLE
Small Suggestion: Option that applies vanilla fog to nearby WStorms

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1118]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
An option in client config that applies vanilla fog to nearby Storms would be scary and intimidating for those players who 
want an actual challenge
**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by LocalWaterCreeper911911** [comment]
English is not my native language, sorry.

**Comment by nonamecrackers2** [comment]
The vanilla fog is applied to the the wither storm?

**Comment by LocalWaterCreeper911911** [comment]
@nonamecrackers2 
I'm dumb.
So i just realised that turning off distant renderer adds EXACTLY what i suggested (a.k.a. Invisible WS when its far away)
And it doubles the scary vibe of this mod!
So, i'm closing this issue

**Comment by LocalWaterCreeper911911** [comment]
#830

**Comment by LocalWaterCreeper911911** [comment]
@nonamecrackers2 please add a duplicate label

**Comment by LocalWaterCreeper911911** [comment]
> @nonamecrackers2 please add a duplicate label

Where is my well deserved duplicate label?

**Comment by BluePineappleGuy** [comment]
do you mean an option that allows you to turn off/on vanilla fog rendering?

**Comment by LocalWaterCreeper911911** [comment]
> do you mean an option that allows you to turn off/on vanilla fog rendering?

Yes(almost), and its a duplicate of #830
