### ISSUE TITLE
Wither Storm isn't as aggressive towards players without amulet

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1119]
If you have the amulet it makes sense for the storm to go thousands of blocks away to get you. But how does it track you if you have an empty inventory. I think it can only track you if you are close enough. If there is a reason it's able to track you without the amulet please tell.

**Comment by myron-obsolete-account** [comment]
makes sense because in story mode the command block is linked to the amulet too so yeah actually kinda true

**Comment by nonamecrackers2** [comment]
The storms ability to track you from wherever is kind of the core of the mod and removing this makes no sense.
