### ISSUE TITLE
Rotating End Battle? And other suggestions. Plus a bug with shaders.

### ISSUE THREAD

**Issue by TaterKing** [nonamecrackers2/crackers-wither-storm-mod#112]
I was thinking if you could have the battle inside the witherstorm rotate like in the end of episode 4 plus if you implement this, the hole in the witherstorm needs to be above the command block. The clouds of blocks or circle things of blocks on the first destroyer phase (phase 4 i believe) should not be there or at least dimmed down because it would look a lot more like the beginning of episode 1. And another thing is it would be cool if you could add the potion from beginning of episode 1. Also there is a bug where if I look at the witherstorm around 30 seconds after its been spawned with shaders on it will crash my game. I don't think its a pc problem cause I have a high end pc. Sorry for saying so much in this post I just haven't had a chance to get on the computer today. Also here's the video of the end battle so you can see what I mean: https://youtu.be/MAREvo6I7H4?t=345 
And the beginning of season 1 what I was talking about: https://youtu.be/7fYG2vcZlfY?t=129

**Comment by Loverxzc** [comment]
#65 - potion. Crash with shaders - You may experience a crash when using shaders when trying to render block clusters. Turning "Block Cluster Colouring" to OFF in the mods client config menu should fix this crash, or you can just disable block cluster rendering entirely.

**Comment by nonamecrackers2** [comment]
Rotating battle: #105, Potion: (what Loverxzc said) #65, and the shader crash: #22.

For the debris rings, I personally think they're fine as they are, and my mod is designed with some little differences from the base game. Thanks for suggestion though
