### ISSUE TITLE
some of the bowels builds should fall down when storm killed

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1120]
a very cool thing if the storm gets killed the bowels builds would drop down (half of it) so that you can explore more and check out some villagers that were stuck and other mobs

:jess:

**Comment by darkheart78** [comment]
they would have to be modified because normally they are just cubes

**Comment by GrandmaPork** [comment]
This sounds cool but I feel like some would be laggy. It’d be cool if chunks of the builds fell tho

**Comment by Pandaboi25x** [comment]
> they would have to be modified because normally they are just cubes

yea but would be cool in the end

**Comment by Pandaboi25x** [comment]
i mean hey i can make some of the structures to look like they fell from the bowels and then give you em :trollface:

**Comment by nonamecrackers2** [comment]
Since the builds are designed to be surrounded by blocks, using the structures directly would just create a bunch of large cubes on the ground everywhere. Well someone could modify them to be open, I'd personally prefer to do them myself, if this was something I wanted in the mod. Thanks for your suggestion though.

**Comment by Pandaboi25x** [comment]
> Since the builds are designed to be surrounded by blocks, using the structures directly would just create a bunch of large cubes on the ground everywhere. Well someone could modify them to be open, I'd personally prefer to do them myself, if this was something I wanted in the mod. Thanks for your suggestion though.

darn 😔 oh well atleast it was worth a shot
