### ISSUE TITLE
Withered Rundown House

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#1121]
Withered Rundown House would be a good idea for being in the bowels. But it will feature new blocks including Tainted Bricks, etc. Otherwise, it will not make any sense if it gets sucked by the wither storm and completely disappears. So hopefully this will be added.

**Comment by darkheart78** [comment]
lots of things are sucked in by the wither storm but just turned into flesh

**Comment by NinjaSam5399** [comment]
But still a good idea to add to the bowels.

**Comment by GrandmaPork** [comment]
This was an event submission that didn't make it in

**Comment by NinjaSam5399** [comment]
I wish it made it.

**Comment by Pandaboi25x** [comment]
> This was an event submission that didn't make it in

very sad it didnt 😔 (i made it)

**Comment by Pandaboi25x** [comment]
https://cdn.discordapp.com/attachments/1094298502076567582/1094329221473644595/image.png heres how it looked like

**Comment by Pandaboi25x** [comment]
![image](https://user-images.githubusercontent.com/121638798/232583286-c4645d88-782f-426f-be12-d066848117f8.png)
heres how it looked like(very old)

**Comment by Tordx12881** [comment]
Could be but to late

**Comment by NinjaSam5399** [comment]
But it is still really needed to be added.

**Comment by Pandaboi25x** [comment]
*cuh???_cat_gif*

**Comment by nonamecrackers2** [comment]
As already mentioned, this was made in our bowels caves contest in our Discord but was turned down. In a future event, if someone does the same concept again and we like it, we could put it into the mod. Otherwise this wouldn't be something I'd do myself, sorry.
