### ISSUE TITLE
Improved symbiont death animation

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1122]
now now i think we all are getting bored of the symbionts animation of him(?) swinging his arms around but it would be very cool if the symbiont had a new improved death animation in the withered symbiont settings where you can change his animation there to either let him swing his arms or a new animation heres an example of the new animation: 

https://user-images.githubusercontent.com/121638798/232752851-d93f48b9-7b2a-467f-a9f9-0bdf833c24cc.mp4

sorry it looks bad but it was rushed and sadly didnt have perms to get the blockbench one 😔

**Comment by Pandaboi25x** [comment]
https://user-images.githubusercontent.com/121638798/232754901-71c28c68-9f83-4fd4-b99c-5fefb97e6379.mp4

bruh it didnt show it

**Comment by LocalWaterCreeper911911** [comment]
I agree, WSymbiont needs a new death animation, but i would prefer an animation where the WSymbiont "slowly disintegrates"
with a CB book inside of it, instead of your rushed animations

It's my opinion, feel free to ignore it.

**Comment by Pandaboi25x** [comment]
> I agree, WSymbiont needs a new death animation, but i would prefer an animation where the WSymbiont "slowly disintegrates" with a CB book inside of it, instead of your rushed animations
> 
> It's my opinion, feel free to ignore it.

its fine gotta respecc the opinions tho i think the rushed animation would be a bit cooler... possibly crackers can add more animations in the symbiont settings :eyes:

**Comment by nonamecrackers2** [comment]
I personally like the current death animation and don't feel it needs much of a revamp. Thanks for your suggestion though.

**Comment by Pandaboi25x** [comment]
> I personally like the current death animation and don't feel it needs much of a revamp. Thanks for your suggestion though.

ah darn 😔
