### ISSUE TITLE
Add night glare to hunchback phases

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1123]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Title,for the SAME reason as you added NG to all other phases.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by darkheart78** [comment]
what is hunchback

**Comment by LocalWaterCreeper911911** [comment]
> what is hunchback

hunchback is phases 0-3 (thats how theyre called in World Settings)

**Comment by nonamecrackers2** [comment]
It is intentionally not supposed to be invisible during those phases, and I don’t plan on making it appear at this time

**Comment by LocalWaterCreeper911911** [comment]
I'm suFFering

**Comment by myron-obsolete-account** [comment]
> I'm suffering

ok

**Comment by LocalWaterCreeper911911** [comment]
Not ok




![2023-04-21_21 40 05](https://user-images.githubusercontent.com/129298645/233690544-1cdf9f28-1154-4ad9-b610-1a950605fbb8.png)

guess if its stage 2 or 3

**Comment by myron-obsolete-account** [comment]
> Not ok
>
> ![2023-04-21_21 40 05](https://user-images.githubusercontent.com/129298645/233690544-1cdf9f28-1154-4ad9-b610-1a950605fbb8.png)
> 
> guess if its stage 2 or 3

stage 2, no tentacles visible, stop posting this here, this is not discord

**Comment by LocalWaterCreeper911911** [comment]
> stage 2, no tentacles visible

H-H-How did you know?

**Comment by LocalWaterCreeper911911** [comment]
> stop posting this here, this is not discord

I'm eating my house because of depression +still suFFering

**Comment by LocalWaterCreeper911911** [comment]
@MoRoN222 please tell me if im blind

**Comment by LocalWaterCreeper911911** [comment]
@MoRoN222  are you still alive?

**Comment by myron-obsolete-account** [comment]
> @MoRoN222 are you still alive?

yes i am

**Comment by myron-obsolete-account** [comment]
> @MoRoN222 please tell me if im blind

why

**Comment by LocalWaterCreeper911911** [comment]
> > @MoRoN222 please tell me if im blind
> 
> why

Because i cant see any sh***t
![2023-04-21_21 40 05](https://user-images.githubusercontent.com/129298645/236515367-17487eaa-efdf-4fc3-b378-ee1130fccfe7.png)

and yes, its phase 2

**Comment by myron-obsolete-account** [comment]
> Because i cant see any sh***t ![2023-04-21_21 40 05](https://user-images.githubusercontent.com/129298645/236515367-17487eaa-efdf-4fc3-b378-ee1130fccfe7.png)
> 
> and yes, its phase 2

the storm is darker than the night sky background, there wouldve been tentacles if it was phase 3

**Comment by LocalWaterCreeper911911** [comment]
> the storm is darker than the night sky background, there wouldve been tentacles if it was phase 3

The Night Glare would've been useful for players like me, but ok

@nonamecrackers2 , you are welcome!
