### ISSUE TITLE
Wither Storm tracks amulet in storage

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1124]
Basically, whenever you put an amulet in a chest or barrel or idk furnace the wither storm will go there and suck it up. This would be a cool idea if possible

**Comment by BluePineappleGuy** [comment]
cool idea

**Comment by GrandmaPork** [comment]
I can’t find where it’s said but Cracker doesn’t want to make the amulet trackable like that cuz it will be too difficult to implement

**Comment by nonamecrackers2** [comment]
This wouldn't be possible/very feasible since it'd require scanning all containers in the world which would be very taxing performance wise. The amount of people that would use this feature wouldn't justify the work to implement this, sorry. Thanks for your suggestion though.
