### ISSUE TITLE
Phase 5.5.5

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1126]
in mcsm there is a bigger 5.5 phase with a side head thing like i have a picture. 
(https://user-images.githubusercontent.com/128404590/233102132-a8949532-2e41-4f3e-8f4f-c03d436f831d.png)
this would be if you took too long and it eats really fast.

**Comment by GrandmaPork** [comment]
A phase recommendation that wasn’t struck down??? Nice

**Comment by darkheart78** [comment]
lets go it is alive

**Comment by Honey-Programming** [comment]
bro I actually posted one similar to this and it got rejected

**Comment by GrandmaPork** [comment]
L

**Comment by myron-obsolete-account** [comment]
Jesus christ please read your yt notifications
![image](https://user-images.githubusercontent.com/53058491/233374190-13810fcf-4843-4250-a753-28bf0a5df853.png)

**Comment by darkheart78** [comment]
> Jesus christ please read your yt notifications ![image](https://user-images.githubusercontent.com/53058491/233374190-13810fcf-4843-4250-a753-28bf0a5df853.png)

i sub to too many channels

**Comment by Steve982950** [comment]
Did you know that this is NOT supposed to be a 1:1 recreation?

**Comment by Resuster** [comment]
wdym it is suppose to be, he just didnt know the structure of the storm cuz telltale literally didnt even care and just made some ups and downs on the actual game

**Comment by Steve982950** [comment]
Compare the models of the mod to the Actual MCSM.

**Comment by WitherBean** [comment]
> Compare the models of the mod to the Actual MCSM.

The CWSM models are thicker in the back.

**Comment by Steve982950** [comment]
k.

**Comment by nonamecrackers2** [comment]
I don't see where this would fit well, seems to just be a phase 6 for me.
