### ISSUE TITLE
Some ways to boost the Wither Storm's Phases

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#1127]
I'm tired of waiting a long time for the wither storm to complete its phases. Because sometimes the "evolutionAttributeModifier" does not work with multiplayer, people will end up changing the speed of the wither storm, like too fast, or too slow. Instead, there should be something that boosts the wither storm's phases or growth. It is good for speedrunners who try to beat the record of defeating the wither storm in a short amount of time. Instead of just making a record of 2 hours to defeat the wither storm. Or you could add a new block called "Tainted Mold Block" or "Tainted Mold". This might be suggested in #1116, But it might do good for speedrunners to craft Tainted Flesh surrounding the Tainted block as a crafting recipe. But hopefully, you add some ways to cause the wither storm to grow faster.

**Comment by nonamecrackers2** [comment]
Closing in favour of #1116.

**Comment by NinjaSam5399** [comment]
ok
