### ISSUE TITLE
DONT SLEEP (or else)

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1129]
When you sleep the storm goes towards you at slow speed but however long the night is so if you sleep it comes towards you. Cool idea but might be too game changing.

**Comment by GrandmaPork** [comment]
Sounds cool

**Comment by BluePineappleGuy** [comment]
pretty sure something similar was suggested (storm gets a boost when skipping the night)

**Comment by Globalfirestorm10** [comment]
Yeah this was already suggested, please close this

**Comment by nonamecrackers2** [comment]
#243
