### ISSUE TITLE
A Crap Ton of Suggestions

### ISSUE THREAD

**Issue by TaterKing** [nonamecrackers2/crackers-wither-storm-mod#113]
I was wondering if you could make it so that you could craft the formidi-bomb in the tractor beam like the game. Of course if you did this you would have to make it so that the bomb would go off depending on how close it is too the witherstorm (if its in the tractor beam). This will probably be really hard for a small addon and could be impossible but it would just be cool. Another thing would be that you could make enderman attack the witherstorm and maybe they could visibly take pieces off the  witherstorm. Maybe if you killed them it would give you a witherstorm block or something. Also maybe adding the ability to craft command blocks not for like actually using command blocks but a special one for summoning in the wither storm in survival mode. The ingredients for the command block are at redstonia in Minecraft story mode. To make it harder you could make it block versions of those ores. The last one is probably my favorite idea and I would want to terrorize my friends with the witherstorm. I know I have made many suggestions so i sound like a broken record at this point.
Here is what I mean about crafting in the tractor beam: https://youtu.be/ZFbt_J0P3_I?t=73 
Here is what I mean about enderman attacking the witherstorm: https://youtu.be/PMD9DMB8s0U?t=2258
Here is what I mean about the command block crafting: https://youtu.be/GJqShuGOzbE?t=81 (this exact frame shows all the ingredients. [some are repeated])

P.S. you dont have to do any of them (obviously) but the crafting command block would be best if you would make one.

**Comment by nonamecrackers2** [comment]
Crafting in the tractor beam would require a custom entity and lot of extra work, and there is also the fact that the formidibomb will blow up extremely close to the player, killing them. I would love to do the endermen thing, but it would be extremely hard to match up endermen positions with the wither storm model, due to how rendering and entity models are done. I may not make a copy of the command block to be craftable, as I'll have another way to resummon the Wither Storm in survival mode only. Thanks for the suggestions though.

**Comment by TaterKing** [comment]
thanks for responding on the command block thing

**Comment by Frask0** [comment]
It wouldn't be natural, but you could have the players survive the F-Bomb if it's blown up while they are in the Tractor Beam with the F-Bomb like the Suggestion said, by giving them a lot of resistance, which could give the effect of the player being "Blown away" by the F-Bomb, like Jesse did in Story Mode.
