### ISSUE TITLE
Phase 7 bowels not opening

### ISSUE THREAD

**Issue by CrazyMax111** [nonamecrackers2/crackers-wither-storm-mod#1131]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on is 1.19.2

**Mod version**
The version of the mod i am using is 3.1.1.1

**Describe the bug**
I went to test the mod in Creative, got to Phase 6, but the bowels are not opening at all.
**To Reproduce**
1. Summon the wither storm the normal way
3. Wait for it to grow to Phase 5
4. F-bomb the storm for it to go into Phase 6
5. The bowels are not opening after, like, 30 minutes

**Is OptiFine installed?**
No, i am using Rubidium and Flywheel instead.

**Comment by myron-obsolete-account** [comment]
the hole only appears at phase 7 and it takes a while

**Comment by CrazyMax111** [comment]
yeah, but it didn't appear for 30 mins despite the setting for "Open Hole" set at 1 minute

**Comment by CrazyMax111** [comment]
i will try it again tomorrow with all phase speeds set to fastest. if it works, i'll close

**Comment by nonamecrackers2** [comment]
If it’s at phase 6 that config value is not considered. It can take a bit for the storm to evolve to phase 7 before the hole actually opens
