### ISSUE TITLE
Endermen around the wither storm at phase 7

### ISSUE THREAD

**Issue by InevitableRob** [nonamecrackers2/crackers-wither-storm-mod#1132]
During phase 7 Endermen should start spawning around the Wither Storm. Through out phase 7 more and more Endermen should spawn so when the hole appears it makes a bit more sense of what caused it then the hole just randomly showing up out of nowhere.

**Comment by myron-obsolete-account** [comment]
#656 please close this

**Comment by nonamecrackers2** [comment]
#235

**Comment by myron-obsolete-account** [comment]
> #235

oh
