### ISSUE TITLE
Re-Summoning Wither Storm/ Beacon change 

### ISSUE THREAD

**Issue by Midstas** [nonamecrackers2/crackers-wither-storm-mod#1135]
When I first saw and played the newest version of the mod with the withered beacon. I noticed that it went from nothing to stage four. I was a little disappointed about that. Not about animations etc. But about that I can’t relive phases 1-3 and that it destroyed the whole beacon with the amulet (That as far as I know isn’t craftable). My solution about this was to not let the beacon summon the storm itself but a command block that the player can mine with a command tool. So the player can place it wherever it wants and so that is spawns at phase 1. 

This also could fit with the lore that you tried to craft a command block in the series itself in ellegaards lab. But this is not the main thought about the idea.

I really would like to see this feature so I can create another new storm that restarts from the beginning.

**Comment by myron-obsolete-account** [comment]
> with the amulet (That as far as I know isn’t craftable)

the amulet is craftable

**Comment by Midstas** [comment]
> > with the amulet (That as far as I know isn’t craftable)
> 
> the amulet is craftable

Really, never knew that I could do that. What is the recipe tho

**Comment by FrozenDragon0** [comment]
> When I first saw and played the newest version of the mod with the withered beacon. I noticed that it went from nothing to stage four. I was a little disappointed about that. Not about animations etc. But about that I can’t relive phases 1-3 and that it destroyed the whole beacon with the amulet (That as far as I know isn’t craftable). My solution about this was to not let the beacon summon the storm itself but a command block that the player can mine with a command tool. So the player can place it wherever it wants and so that is spawns at phase 1.
> 
> This also could fit with the lore that you tried to craft a command block in the series itself in ellegaards lab. But this is not the main thought about the idea.
> 
> I really would like to see this feature so I can create another new storm that restarts from the beginning.

I remember Cracker's mentioning that he doesn't want to touch the code with command blocks by making them breakable + placable in Survival mode or something like that.

**Comment by myron-obsolete-account** [comment]
> I remember Cracker's mentioning that he doesn't want to touch the code with command blocks by making them breakable + placable in Survival mode or something like that.

yeah but I've found like the easiest solution for that

**Comment by nonamecrackers2** [comment]
Yes, I don't want to mess with adding craftable command blocks, hence the way the storm is resummoned using the beacon.

**Comment by BluePineappleGuy** [comment]
> Yes, I don't want to mess with adding craftable command blocks, hence the way the storm is resummoned using the beacon.

makes sense, adding things like loot tables so it drops the block or making it placeable and mineable would be quite a hassle, but maybe add a config for resummoning the storm (such as phase it gets summoned in).
