### ISSUE TITLE
Overgrowth Phases

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1136]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Add an overgrowth phase that goes after phase 7.
The first overgrowth phase is phase 7 but a little bigger and more blocks on it. The second overgrowth phase is when really things start to "overgrow".

Overgrowth phase 1:

![WitherbodyOvergrow1 (2)](https://user-images.githubusercontent.com/109185503/233806590-5a4b24df-3e01-4ce4-9cde-4eb17272baaa.svg)

Overgrowth phase 2:

![WitherbodyOvergrow2 (2)](https://user-images.githubusercontent.com/109185503/233806610-50345eb3-0091-494d-9444-c6bb06edd91e.svg)

Note: When standing on the ground the player will only see the bottom part of overgrowth phase 2

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by TheEyeOfGaming** [comment]
I like it as it is a new idea for a Phase 7, but there should be a OverGrowth phase for the Witherstorm before the Formidibomb

**Comment by TaintedBlock** [comment]
As cool as this could be, I don't think Cracker plans on making more models. (though if this somehow does become a thing it definitely should be a config thing)

**Comment by myron-obsolete-account** [comment]
Yeah he said no to more models as for now. and this overgrown phase just seems like a phase 8 because the wither storm cant really overgrow. it's evil, after all

**Comment by TaintedBlock** [comment]
It wouldn't be called a overgrowth though. It would just be the phases where it continues to grow beyond 7. Would be terrifying but wouldn't change anything and probably just start causing unnecessary lag.

**Comment by GrandmaPork** [comment]
I think if this were to be implemented, it should be a config. Cool twist tho

**Comment by nonamecrackers2** [comment]
Technically #10 #106

**Comment by myron-obsolete-account** [comment]
> Technically #10 #106

that's what I'm sayin'

**Comment by WitherBean** [comment]
Maybe more that 2 segments...

**Comment by BluePineappleGuy** [comment]
this about to get closed as a duplicate or smth
