### ISSUE TITLE
1.20 Smithing Compatibility

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1139]
Alright, so I was playing this mod 1.19.4, and I enabled the 
1.20 experiment which reworks the smithing table so that 3 things are needed instead of 2 (The base equipment, the Template, the material.). In the case of Netherite: 1 Diamond Equipment, 1 Netherite Ingot and 1 (Netherite Upgrade) Smithing Template. When I got to the stage when a Command Block tool needs to be made, I couldn't because of the Smithing Rework (So I had to cheat in one). Here are 2 simple ideas for compatibility.

1. *Command Upgrade* Smithing Template: 

(The vanilla templates can only be obtained via loot, however they can be made into more copies although expensive). Just like the Ancient Cities main template is the Ward Trim; but also contain the MUCH more rare Silence Trim, I think the End Cities which already contain the Spire Trim should hold the Command Upgrade which will be alot more rare. What this means is that the player has a reason to be traveling throughout the Overworld instead of letting the Wither Storm camp the surface that their portal is under and only coming up to confront it. But if you disagree then I think it could also be in a Nether Fort, or else. One alternative is that it can be found in the bowls, however this would mean the Bowls Countdown timer would have to start if the UT has a Command Block book instead of a tool.

2. "Withered Anvil" 

Simply an anvil that can make a Command Block Tool just like the Pre-1.20 Smithing Table does. It could made with an anvil with a Wither Skeleton Skull next to it, but it could also use something like Withered Bones if that idea is to "expensive".

**Comment by NinjaSam5399** [comment]
Cool Idea

**Comment by IndigoAmethyst** [comment]
Oh I came up with another idea
3. Use an regular anvil

**Comment by nonamecrackers2** [comment]
Yeah it is most likely I will just use the regular anvil when 1.20 comes.

**Comment by IndigoAmethyst** [comment]
Alright, although there is still the experiments already in the game so I think some notice should be given so people know the experiments are not compatible.

**Comment by BluePineappleGuy** [comment]
> Yeah it is most likely I will just use the regular anvil when 1.20 comes.

maybe might not be possible. as far as i know, i dont think anvils can change an item to another, they change the item NBT. thats why it works for enchantments, but not for item conversions such as diamond to netherite.

**Comment by Steve982950** [comment]
when will 1.20 CWSM Mod release?

**Comment by IndigoAmethyst** [comment]
You should probably ask Cracker directly

**Comment by Steve982950** [comment]
ok. @nonamecrackers2 when will 1.20 CWSM Mod 
release? (Pls reply if possible)
