### ISSUE TITLE
fire blocks

### ISSUE THREAD

**Issue by ygyuvctuhgvfcurmnjkjknknjnjnknjkjnkjnko** [nonamecrackers2/crackers-wither-storm-mod#114]
the blocks are on fire plz fix this

**Comment by nonamecrackers2** [comment]
You'll need to provide more context.

**Comment by watersofnazareth** [comment]
I think they mean that Block Clusters can be set on fire

**Comment by nonamecrackers2** [comment]
Maybe, will have to see what they say. I'll need to fix the block cluster thing though as well :/
