### ISSUE TITLE
next april fools petting feature 

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1141]
basically on april fools there should be an option to pet any tainted mobs,blocks or items pettable and after petting them for a very long time they will fall asleep for the length you did the petting (if thats not an interest with the asleep make them friendly for 5/3 seconds then after the 5/3 seconds they get a buff and beat the living hell out of you) (hostile mobs can still hit you while petting) a very funny april fools feature plus very cool

:jess:

**Comment by Pandaboi25x** [comment]
Basically based on the discord emojis zombpet and plankspet

**Comment by nonamecrackers2** [comment]
Top ten funny idea, however april fools stuff will be added at our discretion.

**Comment by Pandaboi25x** [comment]
Darn 😔
