### ISSUE TITLE
it is shal not tick bug

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1142]
do not visible wither storm when go more to the render distance

mod name is it is shall not tick

**Comment by Globalfirestorm10** [comment]
> do not visible wither storm when go more to the render distance
> 
> 
> 
> mod name is it is shall not tick
> 
> 

Mind filling out the template? Your description is useless without more info

**Comment by myron-obsolete-account** [comment]
> do not visible wither storm when go more to the render distance
> 
> mod name is it is shall not tick

you are speaking a language nobody understands

**Comment by LocalWaterCreeper911911** [comment]
> you are speaking a language nobody understands

he is saying something about mod incompatibility

**Comment by Globalfirestorm10** [comment]
> do not visible wither storm when go more to the render distance
> 
> 
> 
> mod name is it is shall not tick
> 
> 

you sound underage

**Comment by BluePineappleGuy** [comment]
try adding the WS to the mob ignore list

**Comment by nonamecrackers2** [comment]
Please fill out the template
