### ISSUE TITLE
Amulet not glowing 

### ISSUE THREAD

**Issue by Midstas** [nonamecrackers2/crackers-wither-storm-mod#1143]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
Specify if you're using OptiFine

**Screenshots**

When I played today I noticed that the amulet I am using and all other amulets in the world aren’t working properly anymore. I can still see the distance in the inventory but it isn’t glowing anymore even not when looking at the wither storm.

Version 1.19.3
Optifine installed 
Mod version: Witherstormmod-1.19.3-3.2.1.1.jar

**Comment by Demonmaster-MD** [comment]
Fill in the info

**Comment by IndigoAmethyst** [comment]
The amulet only glows when you are less than 1000 blocks away. Is this the issue?

**Comment by myron-obsolete-account** [comment]
fill out the template

**Comment by Midstas** [comment]
> The amulet only glows when you are less than 1000 blocks away. Is this the issue?

That could be it

**Comment by BluePineappleGuy** [comment]
i had this issue before, the amulet would not visually rotate or glow, its fixed in latest CWSM version

**Comment by nonamecrackers2** [comment]
Can you still rotate the amulet?

**Comment by watersofnazareth** [comment]
Closing till issue has more info
