### ISSUE TITLE
WSsegments stop following main WS, if chunk loading radius is set below 100

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1144]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3

**Mod version**
3.2

**Describe the bug**
TITLE

**To Reproduce**
1. Set chunk loading radius in World Settings below 200
2. Summon stage 7 WS
3. Go far away from it

**Is OptiFine installed?**
NO other mods installed.

**Screenshots**
SOON

**Comment by LocalWaterCreeper911911** [comment]
I did some MATHS and appears that chunk loading distance is too small to the point of WS not loading its own segments

**Comment by LocalWaterCreeper911911** [comment]
HELLO

**Comment by nonamecrackers2** [comment]
Please be patient, it takes time for bug reports to be processed, especially considering this was recently open

**Comment by LocalWaterCreeper911911** [comment]
> Please be patient, it takes time for bug reports to be processed, especially considering this was recently open

OK, sorry for that.

MATHS:

√196 : 2 *16=112 blocks

**Comment by myron-obsolete-account** [comment]
> HELLO

just... why

**Comment by LocalWaterCreeper911911** [comment]
@MoRoN222 i said SORRY

**Comment by LocalWaterCreeper911911** [comment]
SCREENSHOTS:

![2023-04-27_21 28 04](https://user-images.githubusercontent.com/129298645/234931232-de8607f2-96ce-4678-8e41-ec0e6bd85c6b.png)

![2023-04-27_21 25 43](https://user-images.githubusercontent.com/129298645/234931294-bf38c42c-b706-470a-a53d-d9442a9f144b.png)
Glitched?

**Comment by LocalWaterCreeper911911** [comment]
MORE SCREENSHOTS:

![2023-04-27_21 25 50](https://user-images.githubusercontent.com/129298645/234934452-c468c7d0-c5fc-4684-acaa-279dfb875364.png)

![2023-04-27_21 28 46](https://user-images.githubusercontent.com/129298645/234934947-da0a0d75-d3a9-42bf-9f95-c7cf4f5079ae.png)

![2023-04-27_21 29 13](https://user-images.githubusercontent.com/129298645/234935088-1adb6ebb-12da-49b3-9c9e-fcd8f7d65c18.png)

**Comment by LocalWaterCreeper911911** [comment]
Strange things are starting to happen...

**Comment by Globalfirestorm10** [comment]
> Strange things are starting to happen...

I'll be honest, you sound like someone else that was banned from here once

**Comment by LocalWaterCreeper911911** [comment]
This should be a separate issue/bug report?
![2023-04-27_21 29 13](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/207f7f2b-a0c4-4081-9325-c678d34b2dfc)

**Comment by nonamecrackers2** [comment]
Yes, if it’s not related to the original issue

**Comment by LocalWaterCreeper911911** [comment]
> Yes, if it’s not related to the original issue

thanks

**Comment by LocalWaterCreeper911911** [comment]
> > Yes, if it’s not related to the original issue
> 
> thanks

#1176

**Comment by nonamecrackers2** [comment]
Should be fixed in the upcoming 1.20.1 version, since the chunk loading system has been revamped

**Comment by gamerscruffy** [comment]
It also happens if you set the flight speed of the wither storm too high

**Comment by ScreamingMC** [comment]
https://github.com/user-attachments/assets/b693fd28-0dad-4a48-a6f9-1e48af599ab1

did you know?

screaming segments

lol up to version of witherstorm to the newest for 1.19.4, if u made witherstorm very fast, and run away, u will notice the segment disappear. come back, and notice they will keep roaring whole time, with no cooldown, and if the ws is rotating fast, then the segment have no cooldown of waiting. if the ws gets exploded, they teleport high in the sky, and after it revives then they will keep roaring. also snap back. you need to rejoin or kill them to fix this. doesnt happen beyond the 1.19.4. now they always follow. also the gamelogs will be filled of witherstorm segment it's uuid repeating.
