### ISSUE TITLE
Crash While Generating New World

### ISSUE THREAD

**Issue by Darkosto** [nonamecrackers2/crackers-wither-storm-mod#1145]
**Minecraft version**
1.18.2

**Mod version**
2.2.1

**Forge Version**
40.2.0

**Describe the bug**
Starting up a new world in the modpack I am currently developing while frequently crash to desktop during the generation phase.

**To Reproduce**
1. Start MC instance
2. Create a new world
3. Crash before entering the world

**Crash Reports / Logs**
https://gist.github.com/Darkosto/ac55470931c6c916f3538a13ec781789

**Is OptiFine installed?**
No

**Comment by nonamecrackers2** [comment]
Looks like some structure mod may be interfering. Try removing some to see if that fixes the issue.

**Comment by watersofnazareth** [comment]
Closing till issue has more info given
