### ISSUE TITLE
What if, instead of the hole in the storm just "Magically appearing", it went into a sort of "enderman phase"?

### ISSUE THREAD

**Issue by FireCode125** [nonamecrackers2/crackers-wither-storm-mod#1146]
What I think would be cool to see, is this:

When the storm reaches phase 7, endermen begin to rapidly spawn around the storm, and enderman spawn rates everywhere else would be drastically decreased.
The storm will be much more likely to target endermen in this phase than any other entity, and endermen that get "pulled" by the storm will become aggravated at it.
Aggravated endermen will teleport onto the storm, at least, visually, they wouldn't actually have to be there. They would then strip a block off the storm and teleport away (despawn)
This will form a hole, and the hole will gradually become larger and more apparent, until it's big enough to teleport through.

What do you think?

**Comment by GrandmaPork** [comment]
Honestly the endermen don’t even need to teleport on the wither storm. I like the idea of adjusting spawn mechanics tho

**Comment by darkheart78** [comment]
i cant think of any good way to do this. In mcsm it was because soren had tons of endermen.

**Comment by BluePineappleGuy** [comment]
> i cant think of any good way to do this. In mcsm it was because soren had tons of endermen.

when the storm was revived in episode 4, endermen could be seen walking towards the storm slowly.

**Comment by BluePineappleGuy** [comment]
pretty sure similar things were suggested before, like endermen spawning near the storm. crackers said endermen directly interacting with the WS will not happen (and probably visually being seen on it), but he might make endermen attracted to the storm, and i think he said he might also have some endermen near the storm hold flesh blocks.

**Comment by nonamecrackers2** [comment]
#235 #790
