### ISSUE TITLE
Configurable sky color

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#1147]
Add a option in the config to change the sky darkening colour.

**Comment by WitherBean** [comment]
I like this idea.

**Comment by MFNmodding** [comment]
i remember seeing a preview of that on the discord.

**Comment by NinjaSam5399** [comment]
Accepted✅

**Comment by LocalWaterCreeper911911** [comment]
> Accepted✅

wdym?

**Comment by Resuster** [comment]
les goooo

**Comment by Steve982950** [comment]
i mean this is cool

**Comment by nonamecrackers2** [comment]
Will be possible in the next update via resource packs
