### ISSUE TITLE
More Detailed Block Clusters

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1148]
In MCSM, the Wither Storm's later phases have a boom sound effect before the clusters get swept away into the debris ring. Also when the block clusters get ripped out of the ground, they are very fast.

**Comment by darkheart78** [comment]
this is not mcsm this is cwsm his own thing it doesnt have to be 100% accurate

**Comment by NinjaSam5399** [comment]
But fast block clusters are better.

**Comment by NinjaSam5399** [comment]
Maybe you could add it in the config.

**Comment by nonamecrackers2** [comment]
There are suggestions for config options to increase the cluster speed already. Also I’m not really sure what you mean by a boom sound, but regardless I think the sounds that are already present are pretty good by themselves.
