### ISSUE TITLE
Better sickened mobs

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1149]
Currently, sickened mobs kind of just act like retextured regular mobs (i.e sickened zombie has same AI and abilities as regular zombie). I think they should have some kind of wither ability, such as skeleton arrows are tipped with the wither effect, zombies grant wither when attacking, creepers leave a wither cloud, and spiders grant wither 2. Maybe upon being attacked they give a few seconds of wither to the attacker, or they can infect mobs with wither sickness. To prevent mod compatibility issues, there could be a config option in "common" to turn it off.

**Comment by WitherBean** [comment]
Maybe wither sickness or that would be too powerful.

**Comment by IndigoAmethyst** [comment]
Yea Wither Sickness would be to strong.

**Comment by BluePineappleGuy** [comment]
> Yea Wither Sickness would be to strong.

eh, could be only on hard difficulty or smth

**Comment by IndigoAmethyst** [comment]
They already do more damage

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release

**Comment by BluePineappleGuy** [comment]
after playing survival i regret this
but other people may hate it too so please keep the feature
