### ISSUE TITLE
Tainted glass panes cannot be destroyed via explosions(dont fix this today, take a break)

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1151]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3

**Mod version**
3.2

**Describe the bug**
T I T L E

**To Reproduce**
1. Place down some tainted glass panes
2. Run `/summon ~ ~ ~ witherstormmod:super_tnt`
3. See error

**Is OptiFine installed?**
NO other mods installed

**Screenshots**
I cant provide screenshots right now, sorry.

**Comment by Pandaboi25x** [comment]
crackers said its its not a bug and intended

**Comment by LocalWaterCreeper911911** [comment]
WHERE did he say that

**Comment by Pandaboi25x** [comment]
> WHERE did he say that

discord server

**Comment by Pandaboi25x** [comment]
![image](https://user-images.githubusercontent.com/121638798/234901636-073ce7c5-92af-4ae4-9e8b-9e1dcbee4054.png)

**Comment by myron-obsolete-account** [comment]
> ![image](https://user-images.githubusercontent.com/121638798/234901636-073ce7c5-92af-4ae4-9e8b-9e1dcbee4054.png)

he believes so yeah

**Comment by LocalWaterCreeper911911** [comment]
> > ![image](https://user-images.githubusercontent.com/121638798/234901636-073ce7c5-92af-4ae4-9e8b-9e1dcbee4054.png)
> 
> he believes so yeah

he believes so yeah

**Comment by nonamecrackers2** [comment]
This is intended as already mentioned
