### ISSUE TITLE
  -

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1153]

**Comment by NinjaSam5399** [comment]
You need to describe it.

**Comment by LocalWaterCreeper911911** [comment]
> You need to describe it.

![2023-04-27_21 32 00](https://user-images.githubusercontent.com/129298645/234932004-7d06315d-99a0-426d-b41d-a887e4a4589c.png)

**Comment by Globalfirestorm10** [comment]
Correct me if i'm wrong @nonamecrackers2, but isn't it up to the community to make translations for your mod?

**Comment by nonamecrackers2** [comment]
The community translates the mod, and there hasn't been an update from our Russian translator yet.

**Comment by LocalWaterCreeper911911** [comment]
Well, i hope your "russian translator" is alive OwO

**Comment by Globalfirestorm10** [comment]
> Well, i hope your "russian translator" is alive OwO

you sound underage

**Comment by Globalfirestorm10** [comment]
> > > Well, i hope your "russian translator" is alive OwO
> 
> > 
> 
> > you sound underage
> 
> 
> 
> Знаю, и что? Из-за одного человека страдает целая страна, и всем по*иг на это. Эх, ладно, пойду сделаю ресурспак, 
> 
> благодаря которому Withered Beacon станет Иссушённым Маяком, и можно будет нормально играть в
> 
> Шахтёрское Ремесло, а не в Minecraft.
> 
> 
> 
> I'm sorry, @Everyone.


Мужик, я говорю о юридическом возрасте для github. Мне жаль, что Россия страдает от санкций, но это не оправдание. Если вам 12 лет или меньше, вам нельзя здесь находиться.

Я не пытаюсь начать спор, изначально это была шутка, но ты вроде как призналась, что была несовершеннолетней

Translation:

Dude, I'm talking about the legal age for github. I'm sorry Russia is suffering from sanctions, but that's no excuse. If you're 12 years old or younger, you're not allowed to be here.

Im not trying to start an argument here, it was originally a joke, but you kinda confessed to being underage

**Comment by Globalfirestorm10** [comment]
Also, im pretty sure you're not allowed to bring politics into this, as this isn't the place for it either @LocalWaterCreeper911911

**Comment by nonamecrackers2** [comment]
Yes please, politics is not the place for this.

**Comment by Globalfirestorm10** [comment]
> Yes please, politics is not the place for this. 

Sorry if I came off as trying to start an argument, I really wasn't .

**Comment by LocalWaterCreeper911911** [comment]
You know what? Im deleting this issue forever.
