### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by gamingcactus486** [nonamecrackers2/crackers-wither-storm-mod#1154]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version** 1.18.2
The version of Minecraft the mod is running on

**Mod version**witherstormmod-1.18.2-2.2.1.jar
The version of the mod you are using

**Describe the bug** the game grashes when ever i try to make a world

**To Reproduce**
1. Go to '...' play the modpack with  with the mod crackers witherstorm mod 
2. Click on '....' play in the launcher 

3. See error

**Crash Reports / Logs**
Crash reports / logs hoste
[crash-2023-04-27_17.59.01-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/11346234/crash-2023-04-27_17.59.01-server.txt)
d on pastebin, gist, etc.

**Is OptiFine installed?**
Specify if you're using optiFine yes i am

**Screenshots**

**Comment by myron-obsolete-account** [comment]
fill out the template please

**Comment by Globalfirestorm10** [comment]
Make sure that you have the right version of 1.18.2 forge and optifine 1.18.2

**Comment by nonamecrackers2** [comment]
> Make sure that you have the right version of 1.18.2 forge and optifine 1.18.2

^ This

You will have to use one of the preview versions 
![image](https://user-images.githubusercontent.com/105086648/235269827-0698caf7-d758-43d5-aa83-c0adcbb82194.png)
