### ISSUE TITLE
I built a Symbiont abusing machine (aka sickened mob farm)

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1155]
SORRY for blank issue, but i am happy to announce that i built a TITLE, that uses a Symbiont, a lot of cobblestone and 
two **** ****** in order to get infinite:

1. withered flesh
2. string
3. gunpowder
4. withered bones
5. bows
6. enchanted bows
7. iron swords and shovels
8. all kinds of armor
9. DiAmOnD ArMoR

screenshots and more information COMING SOON

**Comment by myron-obsolete-account** [comment]
this is not an issue report nor a suggestion so please close this. why even did you open this?

**Comment by LocalWaterCreeper911911** [comment]
> this is not an issue report nor a suggestion so please close this. why even did you open this?

because its a bug report 


(probably)

**Comment by myron-obsolete-account** [comment]
> > this is not an issue report nor a suggestion so please close this. why even did you open this?
> 
> because its a bug report
> 
> (probably)

If it is a bug report then PLEASE for the sake of being able to solve this properly, fill out the TEMPLATE and explain what to do to make this happen so Cracker can possibly fix this issue.

**Comment by LocalWaterCreeper911911** [comment]
![2023-04-29_21 58 15](https://user-images.githubusercontent.com/129298645/235314711-2f81bdb8-9ebc-4cb4-825b-9e4fbb0d4413.png)

**Comment by myron-obsolete-account** [comment]
Not a valid answer.

**Comment by nonamecrackers2** [comment]
I mean if you can rally up a symbiont and make a farm out of it, go ahead. I don't really think this is a bug.

**Comment by LocalWaterCreeper911911** [comment]
> I mean if you can rally up a symbiont and make a farm out of it, go ahead. I don't really think this is a bug.

Yeah? I thought Symbiont isnt supposed to be abused in anyway, but OK

**** ****** = Snow Golems

**Comment by myron-obsolete-account** [comment]
> > I mean if you can rally up a symbiont and make a farm out of it, go ahead. I don't really think this is a bug.
> 
> Yeah? I thought Symbiont isnt supposed to be abused in anyway, but OK
> 
> **** ****** = Snow Golems

you are acting weird

**Comment by LocalWaterCreeper911911** [comment]
> > > I mean if you can rally up a symbiont and make a farm out of it, go ahead. I don't really think this is a bug.
> > 
> > 
> > Yeah? I thought Symbiont isnt supposed to be abused in anyway, but OK
> > **** ****** = Snow Golems
> 
> you are acting weird

What do you mean?

Also a side-question: i have recently noticed, that Symbiont doesnt drop a Book when killed in any dimension besides
Overworld. Is that intended?

**Comment by nonamecrackers2** [comment]
No, make a new a new issue for that then
