### ISSUE TITLE
Symbiont doesnt drop a Book when killed in any dimension besides Overworld

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1157]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3 (i cant switch to 1.19.4 right now,sorry)

**Mod version**
3.2.1.1

**Describe the bug**
Symbiont doesnt drop a Book when killed in any dimension besides Overworld

**To Reproduce**
1. Summon a Symbiont in the Nether
2. kill him
3. See error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
No other mods installed

**Screenshots**
SOON

**Comment by Pandaboi25x** [comment]
are you sure it didnt fell in the lava? using 1.19.4 and it seems like it dropped

**Comment by LocalWaterCreeper911911** [comment]
> are you sure it didnt fell in the lava? using 1.19.4 and it seems like it dropped

It happened on top of Nether Roof, so idk

**Comment by LocalWaterCreeper911911** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Pandaboi25x** [comment]
I did it on the nether roof too and it still dropped
