### ISSUE TITLE
WitherStorm shoots blue skulls in destroyer/devourer phases (Not a bug)

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1158]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4, finally

**Mod version**
3.2.1.3

**Describe the bug**
WitherStorm shoots blue skulls in destroyer/devourer phases

**To Reproduce**
1. Summon a WS
2. See error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
NO, and no other mods installed

**Screenshots**
![2023-05-01_21 09 26](https://user-images.githubusercontent.com/129298645/235490076-d26009bb-0a48-4666-b3ea-18dce8ae9352.png)

**Comment by Globalfirestorm10** [comment]
This is intended, please close the issue

**Comment by BluePineappleGuy** [comment]
> This is intended, please close the issue

but why? it looks so weird and off

**Comment by darkheart78** [comment]
> > This is intended, please close the issue
> 
> but why? it looks so weird and off

CLOSE IT

**Comment by LocalWaterCreeper911911** [comment]
> > This is intended, please close the issue
> 
> but why? it looks so weird and off

AGREED! This cant be intended!

**Comment by Globalfirestorm10** [comment]
> > This is intended, please close the issue
> 
> 
> 
> but why? it looks so weird and off

the wither shoots the blue wither skulls along with regular ones, and so does the storm. IIRC, they do more damage and have a longer decay effect. If you want them removed, then open a new issue, mark it as a suggestion, and say what you want

**Comment by LocalWaterCreeper911911** [comment]
> > > This is intended, please close the issue
> > 
> > 
> > but why? it looks so weird and off
> 
> the wither shoots the blue wither skulls along with regular ones, and so does the storm. IIRC, they do more damage and have a longer decay effect. If you want them removed, then open a new issue, mark it as a suggestion, and say what you want

I mean, its normal that WS shoots blue skulls when in phases 0-3, but when its in phases 4-7, especially 7...
they have ***ZERO*** impact on the situation around!

sorry for bad language

**Comment by Globalfirestorm10** [comment]
> > > > This is intended, please close the issue
> 
> > > 
> 
> > > 
> 
> > > but why? it looks so weird and off
> 
> > 
> 
> > the wither shoots the blue wither skulls along with regular ones, and so does the storm. IIRC, they do more damage and have a longer decay effect. If you want them removed, then open a new issue, mark it as a suggestion, and say what you want
> 
> 
> 
> I mean, its normal that WS shoots blue skulls when in phases 0-3, but when its in phases 4-7, especially 7...
> 
> they have **ZERO** impact on the situation around!
> 
> 
> 
> sorry for bad language

You know what? Ill just wait for cracker to show up, im not getting into an argument of whether this is intentional or not.

**Comment by nonamecrackers2** [comment]
This is intended

**Comment by LocalWaterCreeper911911** [comment]
bruh

**Comment by FrozenDragon0** [comment]
> bruh

I literally don't see an issue with it firing blue skulls, yes it's a mutated Wither but even still that's no reason as to why it shouldn't beable to fire blue skulls.

**Comment by Globalfirestorm10** [comment]
> bruh

Told you

**Comment by LocalWaterCreeper911911** [comment]
> > bruh
> 
> Told you

OK
