### ISSUE TITLE
Visual bug about block clusters ( ? )

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1159]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
IDK

**To Reproduce**
1. Summon WS
2. See error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
NO, and no other mods installed.

**Screenshots**
![2023-05-01_21 08 57](https://user-images.githubusercontent.com/129298645/235490995-74a1a537-7aa3-4a1e-9024-99df43d641cb.png)

![2023-05-01_21 10 16](https://user-images.githubusercontent.com/129298645/235491024-735a32cb-12ea-4439-a0ae-3470ecc8fb9e.png)

**Comment by Globalfirestorm10** [comment]
I see no visual bugs here

**Comment by BluePineappleGuy** [comment]
> I see no visual bugs here

seems to be incorrect lighting issue?

**Comment by BluePineappleGuy** [comment]
do you have any resource packs on (other than mod resources)? they might be messing with the clusters

**Comment by LocalWaterCreeper911911** [comment]
> do you have any resource packs on (other than mod resources)? they might be messing with the clusters

No, and this happens in phases 4+

**Comment by nonamecrackers2** [comment]
In the F3 menu on the right, does it say if the vertex buffer renderer is active or not?

**Comment by LocalWaterCreeper911911** [comment]
Wait a minute. Why did the night glare disappear? (second screenshot)

**Comment by LocalWaterCreeper911911** [comment]
![2023-05-04_21 01 02](https://user-images.githubusercontent.com/129298645/236265558-96c2ef53-33e7-434e-b655-9fd6da48bf6a.png)

**Comment by BluePineappleGuy** [comment]
> Wait a minute. Why did the night glare disappear? (second screenshot)

it didnt, you can see the faint outer edges , the rest is blocked by the storms mass

**Comment by LocalWaterCreeper911911** [comment]
@nonamecrackers2 , i provided the information, please remove the "question" tag.

**Comment by Globalfirestorm10** [comment]
> @nonamecrackers2 , i provided the information, please remove the "question" tag.

It's not about the template, look at his comment, it'll make sense then

**Comment by LocalWaterCreeper911911** [comment]
> > @nonamecrackers2 , i provided the information, please remove the "question" tag.
> 
> It's not about the template, look at his comment, it'll make sense then

I mean, i screenshotted the entire F3 menu. Is that what @nonamecrackers2  needs?

**Comment by Globalfirestorm10** [comment]
> > > @nonamecrackers2 , i provided the information, please remove the "question" tag.
> 
> > 
> 
> > It's not about the template, look at his comment, it'll make sense then
> 
> 
> 
> I mean, i screenshotted the entire F3 menu. Is that what @nonamecrackers2  needs?

yeah

**Comment by Globalfirestorm10** [comment]
> In the F3 menu on the right, does it say if the vertex buffer renderer is active or not?

According to their screenshot, it's not

**Comment by LocalWaterCreeper911911** [comment]
> > In the F3 menu on the right, does it say if the vertex buffer renderer is active or not?
> 
> According to their screenshot, it's not

So, how do i turn it on?

**Comment by Globalfirestorm10** [comment]
> > > In the F3 menu on the right, does it say if the vertex buffer renderer is active or not?
> 
> > 
> 
> > According to their screenshot, it's not
> 
> 
> 
> So, how do i turn it on?

idk if you need to turn it on or not

**Comment by LocalWaterCreeper911911** [comment]
> > > > In the F3 menu on the right, does it say if the vertex buffer renderer is active or not?
> > 
> > 
> > > 
> > 
> > 
> > > According to their screenshot, it's not
> > 
> > 
> > So, how do i turn it on?
> 
> idk if you need to turn it on or not

Yes, i need to turn it on.

**Comment by LocalWaterCreeper911911** [comment]
You know, the things are NOT GOOD when issue gets labeled as a bug that doesnt need confirming
OwO
