### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by TitanHammer** [nonamecrackers2/crackers-wither-storm-mod#116]
Hello!
I have been enjoying the mod, is there a discord or something in which I can find servers running the mod and stuff? The modpack is epic, it'd be nice if I could find some cool server to play with other people. I looked all over youtube and forge and just wasnt able to find a discord, if there is one please tell me!

**Comment by Gaboamau** [comment]
The creator said he will consider it in the future, but right now he doesn't have enough resources to run a discord server.

**Comment by nonamecrackers2** [comment]
I don't have one, but there is an unofficial one with a minecraft server in the works: https://discord.gg/zD6X53XDdc
