### ISSUE TITLE
Mineshaft zombie miss put

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1160]
**Minecraft version**
just when the new bowels came out

**Describe the bug**
a very annoying mineshaft zombie thing

**To Reproduce**
1. Go to the mineshaft bowels
2. look around 
3. see that the zombie is miss putted

**Screenshots**
![image](https://user-images.githubusercontent.com/121638798/235520734-6f61f5f9-f0d5-458e-9c87-96be5a79a308.png)
You had one job naza 😔

**Comment by Pandaboi25x** [comment]
i was tired so do ignore my spelling or yea

**Comment by LegendaryGodzilla** [comment]
Mineshaft Zombie thing using hacks

**Comment by BluePineappleGuy** [comment]
bro's in creative mode

**Comment by Pandaboi25x** [comment]
> bro's in creative mode

Fr

**Comment by Pandaboi25x** [comment]
> Mineshaft Zombie thing using hacks

Ikr

**Comment by LocalWaterCreeper911911** [comment]
This cant be low priority!
![2023-05-04_20 45 25](https://user-images.githubusercontent.com/129298645/236265839-c27cc4f0-d486-4cc8-b1f3-cb2a1f39d587.png)

**Comment by BluePineappleGuy** [comment]
> This cant be low priority! ![2023-05-04_20 45 25](https://user-images.githubusercontent.com/129298645/236265839-c27cc4f0-d486-4cc8-b1f3-cb2a1f39d587.png)

it kinda is, its not gamebreaking or a serious issue, he's just misplaced. also we can enjoy hacker zombie while we can before it gets fixed

**Comment by nonamecrackers2** [comment]
This wouldn't be overly worth fixing... Besides, think of it has a little easter egg lol

**Comment by Pandaboi25x** [comment]
> This wouldn't be overly worth fixing... Besides, think of it has a little easter egg lol

alright then
