### ISSUE TITLE
Wither Storm theme doesn't play (fixed)

### ISSUE THREAD

**Issue by DarthArnettJr** [nonamecrackers2/crackers-wither-storm-mod#1161]
I was trying out the new version when i noticed that the theme wasn't playing. It was the normal Minecraft tunes.

**Comment by Bloxxify1520** [comment]
Go to the client config and turn on “play boss themes”

**Comment by DarthArnettJr** [comment]
Ok thx!

**Comment by Bloxxify1520** [comment]
You can close it
