### ISSUE TITLE
Add a Config to change the Withered Symbiont Theme to an Old Theme.

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#1162]
People have been asking for Old Withered Symbiont Theme, and other people rather want the new Withered Symbiont theme. So can you add settings that change the theme to an old version? I would name it "Withered Symbiont Archived Theme". It would be a good name.

**Comment by NinjaSam5399** [comment]
Also, people want the old withered symbiont theme with the new version.

**Comment by V0calgiant12** [comment]
Just make a resource pack lol

**Comment by darkheart78** [comment]
> Just make a resource pack lol

yeah but it would be easier to just have a config option you dont have to use it

**Comment by darkheart78** [comment]
> > Just make a resource pack lol
> 
> yeah but it would be easier to just have a config option you dont have to use it 

anyways i created a resource pack check #creations on discord server

**Comment by NinjaSam5399** [comment]
> Just make a resource pack lol

But the config version is easier than just doing all the steps. Ok fine! then remove the config of enabling the wither storm music. Make configs resource packs. And now see what it feels like! >:(

**Comment by NinjaSam5399** [comment]
People say almost every suggestion "Do it with resource pack".

**Comment by BluePineappleGuy** [comment]
I did like the old theme

**Comment by nonamecrackers2** [comment]
This is something that can be done with a resource pack.

**Comment by darkheart78** [comment]
> This is something that can be done with a resource pack.

bruh

**Comment by nonamecrackers2** [comment]
Besides, the new themes were made specifically for the mod to replace the existing ones.

**Comment by V0calgiant12** [comment]
> Ok fine! then remove the config of enabling the wither storm music. Make configs resource packs. And now see what it feels like! >:(

Realistically, that is something that cannot be done as resource packs only change sounds, textures, models, and words. Thats the limit, it's just simply not possible to make a resource pack that would change the internal code of a mod or just vanilla Minecraft in anything that isn't visual, even if a custom sound is added via resource packs, they cannot be coded to play naturally without a datapack which init of itself is very limiting. I can understand the frustration of being told to just use a resource pack/datapack, but in all truth, small things that can already be done with resource packs and datapacks would not be worth any developer's time, whether it be a mod dev or a Mojang dev as that time can be spent making bigger, better, and cooler things for the game. (Or it could be spent throwing random things at the code to try to fix a bug until it eventually works.)

**Comment by NinjaSam5399** [comment]
oh ok

**Comment by BluePineappleGuy** [comment]
> > Ok fine! then remove the config of enabling the wither storm music. Make configs resource packs. And now see what it feels like! >:(
> 
> Realistically, that is something that cannot be done as resource packs only change sounds, textures, models, and words. Thats the limit, it's just simply not possible to make a resource pack that would change the internal code of a mod or just vanilla Minecraft in anything that isn't visual, even if a custom sound is added via resource packs, they cannot be coded to play naturally without a datapack which init of itself is very limiting. I can understand the frustration of being told to just use a resource pack/datapack, but in all truth, small things that can already be done with resource packs and datapacks would not be worth any developer's time, whether it be a mod dev or a Mojang dev as that time can be spent making bigger, better, and cooler things for the game. (Or it could be spent throwing random things at the code to try to fix a bug until it eventually works.)

you could just set the theme to silence and change it with resource packs
