### ISSUE TITLE
Please make the wither storm mod on spigot

### ISSUE THREAD

**Issue by Vocosmical** [nonamecrackers2/crackers-wither-storm-mod#1163]
I was trying to make a server on aternos with the wither storm mod, but the problem is that I wan't my server to be accessible to vanilla players, and my server is Java and bedrock friendly, so I am asking kindly to put it on spigot so it won't be identified as a mod and a plugin, thank you.

**Comment by darkheart78** [comment]
what this isnt possible please close this

**Comment by Globalfirestorm10** [comment]
Lmao that isn't even possible, not gonna happen kid

**Comment by FireCode125** [comment]
I can’t even begin to explain everything wrong with this…

**Comment by Bloxxify1520** [comment]
Me when the impossible:

**Comment by BluePineappleGuy** [comment]
Sadly, this mod depends on internal forge API's and modding tools. With a plugin, you cannot add entities, blocks, or dimensions. Only things like functions or procedures. If you want to make an aternos server with it, it'll have to be java only and on forge, not spigot or paper.

**Comment by FrozenDragon0** [comment]
Please close this, this is not even possible to do, plugins cannot replicate what this mod does.

**Comment by Globalfirestorm10** [comment]
bro summoned the whole CWSM github community 💀

**Comment by nonamecrackers2** [comment]
This is not possible. The mod requires blocks and entities to be registered on the client, which vanilla does not have, which means nothing would appear for players.

**Comment by myron-obsolete-account** [comment]
oh my god I think I just lost a few thousand brain cells...

**Comment by LocalWaterCreeper911911** [comment]
> oh my god I think I just lost a few thousand brain cells...

what

**Comment by myron-obsolete-account** [comment]
> > oh my god I think I just lost a few thousand brain cells...
> 
> what

what

**Comment by nonamecrackers2** [comment]
> oh my god I think I just lost a few thousand brain cells...

@MoRoN222 if we could be a little bit more respectful, this is your last warning

**Comment by myron-obsolete-account** [comment]
> @MoRoN222 if we could be a little bit more respectful, this is your last warning

last?

**Comment by Globalfirestorm10** [comment]
> > @MoRoN222 if we could be a little bit more respectful, this is your last warning
> 
> 
> 
> last?

We already got a warning after the whole humzahre incident, ig this is your last one

**Comment by myron-obsolete-account** [comment]
> > > @MoRoN222 if we could be a little bit more respectful, this is your last warning
> > 
> > 
> > last?
> 
> We already got a warning after the whole humzahre incident, ig this is your last one

wasnt that the guy that got banned then?

**Comment by LocalWaterCreeper911911** [comment]
> > > oh my god I think I just lost a few thousand brain cells...
> > 
> > 
> > what
> 
> what

what

**Comment by Globalfirestorm10** [comment]
> > > > @MoRoN222 if we could be a little bit more respectful, this is your last warning
> > > 
> > > 
> > > last?
> > 
> > 
> > We already got a warning after the whole humzahre incident, ig this is your last one
> 
> wasnt that the guy that got banned then?

yeah, but we both got a warning from crackers for being too toxic

**Comment by Vocosmical** [comment]
Didn't mean to be so rude, I just wanted to make a vanilla minecraft server. 😭

**Comment by Vocosmical** [comment]
I just wanted to know if it was possible but it isn't, I didn't want to be called a idiot because I didn't know anything about curseforge  
I am a freaking MCPE player and it isn't possible to install any mods on mobile so I never knew about this kind of stuff, I'll just watch Minecraft Story Mode on Netflix xince Telltale shut down from now on.

**Comment by myron-obsolete-account** [comment]
> I am a freaking MCPE player

yeah sorry but CWSM is not even a mod for bedrock/pocket editon so yeah sorry

**Comment by Judoboy2019** [comment]
There was a guy on youtube who used commandblocks to do it in vanilla. He has a world download. he used datapacks for the model. _
