### ISSUE TITLE
Compatibility Issue: Pehkui

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1164]
When close it works but the distant renderer broken.

**Comment by nonamecrackers2** [comment]
Please fill out the bug report template

**Comment by darkheart78** [comment]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.1

**Describe the bug**
incompatibility issue with pehkui. the distant renderer doesnt work

**To Reproduce**
Steps to reproduce the behavior:

1. use pehkui to change the size of the wither storm
2. go outside the chunk distance. 
3. it smol again

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
no

**Screenshots**
![2023-05-03_21 06 53](https://user-images.githubusercontent.com/128404590/236095726-2adebbdf-ac06-4f04-abcf-ffbf214c3dfd.png)

**Comment by darkheart78** [comment]
![2023-05-03_21 06 55](https://user-images.githubusercontent.com/128404590/236095994-123880af-d2e3-4c58-92a1-7b444a013b73.png)
when close

**Comment by darkheart78** [comment]
> Please fill out the bug report template

i did

**Comment by darkheart78** [comment]
also the positioning is a bit wrong

**Comment by darkheart78** [comment]
![image](https://user-images.githubusercontent.com/128404590/236096286-bfe562e4-4c6e-47d8-881d-a2748f3c813c.png)

**Comment by darkheart78** [comment]
please reopen
