### ISSUE TITLE
Wither Storm sucks blocks behind primary layers of a wall

### ISSUE THREAD

**Issue by C182MC** [nonamecrackers2/crackers-wither-storm-mod#1166]
Please check the guidelines before submitting

Minecraft version
All versions the mod has support for

Mod version
Version 2.2.1.2/affects all versions

Describe the bug
When the Wither Storm is subject or adjacent enough to any walls (can be any), it sucks blocks through the first layer of the wall.

To Reproduce
1. Summon wither storm close to wall
2. Go into spectator mode and wait a while 
3. Notice you see random holes in the wall, right near or at the Wither Storm's flying height.

Crash Reports / Logs
There is no logs nor crash reports I could rip from this issue.

Is OptiFine installed?
No, I don't use OptiFine with the Wither Storm mod.

Screenshots
This issue is very easy to perform with the mod, so screenshot evidence is optional.

**Comment by LocalWaterCreeper911911** [comment]
> This issue is very easy to perform with the mod, so screenshot evidence is optional.

Still, we need a screenshot or something like that. Because you know, its very helpful.

**Comment by nonamecrackers2** [comment]
Please provide a screenshot. Also please don’t say “affects all versions” as over time new versions of the mod will be released. State specifically which ones you’ve seen it occur in.

**Comment by watersofnazareth** [comment]
Closing till issue has more info given
