### ISSUE TITLE
WS skulls sometimes teleport to bowels, causing an explosion on the otherside

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1167]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4, that doesnt matter

**Mod version**
3.2.1.3, that doesnt matter too

**Describe the bug**
WS skulls sometimes teleport to bowels, causing an explosion on the otherside

**To Reproduce**
1. Summon phase 7.5 WS
2. Give yourself Resistance V and go into Survival Mode, also give yourself a crossbow and an arrow
3. Shoot the central head
4. You are stuck!
5. Wait
6. Wait
7. WAIT
8. Go back into Creative Mode and enter the Bowels
9. see error
10. this doesnt happen all the time tho

**Is OptiFine installed?**
NO other mods installed

**Screenshots**
![2023-05-09_21 33 25](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/5b591ace-53c2-4230-be23-b84dc525010f)

**Comment by myron-obsolete-account** [comment]
What the hell is phase 7.5

**Comment by LocalWaterCreeper911911** [comment]
> What the hell is phase 7.5

a Storm with a hole in its mass

**Comment by myron-obsolete-account** [comment]
> > What the hell is phase 7.5
> 
> a Storm with a hole in its mass

still phase 7 but ok

**Comment by darkheart78** [comment]
> > > What the hell is phase 7.5
> > 
> > 
> > a Storm with a hole in its mass
> 
> still phase 7 but ok

there is a difference between phase 7 and phase 7.5

phase 7 is big brain storm
phase 7.5 is big brain storm but with a hole

**Comment by LocalWaterCreeper911911** [comment]
> > > > What the hell is phase 7.5
> > > 
> > > 
> > > a Storm with a hole in its mass
> > 
> > 
> > still phase 7 but ok
> 
> there is a difference between phase 7 and phase 7.5
> 
> phase 7 is big brain storm phase 7.5 is big brain storm but with a hole

EXACTLY

**Comment by LocalWaterCreeper911911** [comment]
@MoRoN222 mind replying to me? #1123

**Comment by NinjaSam5399** [comment]
This is supposed to be intended.

**Comment by LocalWaterCreeper911911** [comment]
So, this bug is fixable?

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
