### ISSUE TITLE
Minecraft keeps crashing

### ISSUE THREAD

**Issue by Minecraftplayer20** [nonamecrackers2/crackers-wither-storm-mod#1169]
The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file witherstormmod-client.toml of type CLIENT for modid witherstormmod

**Comment by darkheart78** [comment]
the config file is missing i think

**Comment by darkheart78** [comment]
check you config folder

**Comment by darkheart78** [comment]
what is your discord?

**Comment by Minecraftplayer20** [comment]
> check you config folder

Where is the config folder located?

**Comment by darkheart78** [comment]
what is ur discord

**Comment by Minecraftplayer20** [comment]
> what is ur discord

like my discord username?

**Comment by darkheart78** [comment]
yeah mine is BenBen#6100
add me

**Comment by Minecraftplayer20** [comment]
> BenBen#6100

ok

**Comment by Steve982950** [comment]
can u actually fill out the templates rather than just throwing in the crash log?

**Comment by nonamecrackers2** [comment]
Please fill out the template.

**Comment by Steve982950** [comment]
> Please fill out the template.

I agree
