### ISSUE TITLE
[Suggestion] When the WS is staring at something and pulling it have everything in a small radius of it also pulled in

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#117]
This way things like Cow/General Animal Farms aren't big distractions to it and it'd be able to grab clusters of mobs and it'd probably make things like items/armor stands things that aren't really considered targets get pulled in just by being close to the target,

*I hope I made sense with that if I didn't I'll try to elaborate more*

**Comment by nonamecrackers2** [comment]
#67. I do really like this idea though!

**Comment by watersofnazareth** [comment]
Didn't realize it was already suggested mb!

**Comment by nonamecrackers2** [comment]
No worries!
