### ISSUE TITLE
Wither Storm destroying nether portal.

### ISSUE THREAD

**Issue by Macisialek** [nonamecrackers2/crackers-wither-storm-mod#1170]
Its not rare that people run from wither storm to the nether to stay there very long. I think that it should destroy the portal same way that was shown in MC:SM.  (Sorry for bad english, im Polish).

**Comment by FrozenDragon0** [comment]
This has been suggested many times and has been denied: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/49

**Comment by Macisialek** [comment]
> This has been suggested many times and has been denied: #49
Kinda sad

**Comment by Globalfirestorm10** [comment]
please close this issue, as it's a duplicate
