### ISSUE TITLE
Command Block Bowels Sound Change

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1171]
As of the current version (2.2/3.2), I feel like the Command Block within the Wither Storm Bowels can be heard from to far away as it can be heard when you are in another part of the Bowels, which seems off. 
I suggest that the radius of the Command Block sound gets reduced to about 5-15 blocks.

Also, you should make it so that the Command Block can be heard everywhere in the Bowels once the boss fight has started.
I hope you consider this change.

**Comment by darkheart78** [comment]
agree it is annoying

**Comment by Globalfirestorm10** [comment]
Couldn't you just change this with a resource pack?

**Comment by BluePineappleGuy** [comment]
> Couldn't you just change this with a resource pack?

resource packs change sound files, not sound volumes. you can change what sound plays but not how loud or how far it can be heard.

**Comment by WitherBean** [comment]
You could use a resource pack to lower the sound volume with an audio editor.

**Comment by nonamecrackers2** [comment]
You can use a resource pack to edit the sounds.json to decrease the attenuation distance (the distance the sound can be heard), however I do partially agree that the distance is a little bit too big.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
