### ISSUE TITLE
Phase 2/3 Head Hitbox is difficult to hit.

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1172]
The Phase 2/3's head hitbox is very difficult to hit as most attacks register as a hit to the whole Wither Storm, not the head. 
1. Summon a Wither Storm in Phase 3 or 2.
2. Activate Hitboxes.
3. Go into survival with early-game gear and see if you can survive it picking you up.

I really hope you fix this, as it makes the Wither Storm at this phase more dangerous than the later phases

**Comment by darkheart78** [comment]
yeah early phase op

**Comment by nonamecrackers2** [comment]
This is technically intended however I’ll keep this as a suggestion

**Comment by BluePineappleGuy** [comment]
it is super annoying, i think hitting the main WS could work for disabling the head to even out how incredibly hard the head is to hit.

**Comment by IndigoAmethyst** [comment]
Yeah the later phases are not as dangerous compared to phase 2 an 3, which doesn't really make sense considering the wither storm is supposed to be more dangerous as it grows.

**Comment by nonamecrackers2** [comment]
I don't really want to expand the hitbox since you could then miss the head visually but still technically hit it. I'll instead be lowering the amount of times it requires to fully injure the head which should work better.
