### ISSUE TITLE
[Junk items teleport to bowels] The entire bowels is filled with kelp

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1173]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
T I T L E

**To Reproduce**
1. Set Flying Height to 30
2. Go to any Ocean biome nearby
3. summon phase 7,5 WS
4. see Storm sucking up tons of kelp
5. Let the WS alone for long enough
6. Enter bowels
7. see error

**Is OptiFine installed?**
No other mods installed

**Screenshots**
![2023-05-09_21 38 18](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/ec573ac1-6b97-498e-bda2-5f9990f4f063)

**Comment by darkheart78** [comment]
kelp

**Comment by LocalWaterCreeper911911** [comment]
> kelp

kelp?

**Comment by WitherBean** [comment]
Why kelp?

**Comment by Globalfirestorm10** [comment]
Please reproduce this issue, and fill out the template with the info needed

**Comment by watersofnazareth** [comment]
Uh, we need more information

**Comment by Globalfirestorm10** [comment]
> Uh, we need more information

I literally just said that, also nice seeing you here again

**Comment by LocalWaterCreeper911911** [comment]
> > Uh, we need more information
> 
> I literally just said that, also nice seeing you here again

Sorry for inconvenience.

The problem was caused by WS sucking up ***TONS*** of kelp, and some of they teleporting to random place in Bowels.

Steps to Reproduce are filled now!

**Comment by myron-obsolete-account** [comment]
I'm gonna take a stupid guess; I think it's intentional that items that get sucked up spawn everywhere inside the bowels instead of just at the player spawnpoint(-s)

**Comment by MoRoN222** [comment]
I'm gonna take a stupid guess; I think it's intentional that items that get sucked up spawn everywhere inside the bowels instead of just at the player spawnpoint(-s)

**Comment by LocalWaterCreeper911911** [comment]
> I'm gonna take a stupid guess; I think it's intentional and items that get sucked up spawn everywhere inside the bowels instead of just at the player spawnpoint(-s)

I just had the SAME thought

**Comment by WitherBean** [comment]
Now you have a lot of food.

**Comment by nonamecrackers2** [comment]
What’s probably happening is the low flying height is causing items to reach the wither storm’s hole and enter the bowels

**Comment by LocalWaterCreeper911911** [comment]
> What’s probably happening is the low flying height is causing items to reach the wither storm’s hole and enter the bowels

You're right.

**Comment by Globalfirestorm10** [comment]
> What’s probably happening is the low flying height is causing items to reach the wither storm’s hole and enter the bowels

Perhaps you could just implement a feature that deletes items when they get sucked up by the storm?

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
