### ISSUE TITLE
Missing blocks?

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1174]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
Missing blocks?

**To Reproduce**
1. Go to bowels

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
No other mods installed

**Screenshots**
![2023-05-09_21 38 49](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/0d3af363-dd08-4931-85cd-af99464dfff7)
there are lots of these

**Comment by WitherBean** [comment]
I have seen this happen too.

**Comment by Steve982950** [comment]
same lol

**Comment by Globalfirestorm10** [comment]
please fill out the template in order to make sure your issue does not get closed and marked as invalid

**Comment by Globalfirestorm10** [comment]
Also, im pretty sure that you this is an unfixable bug/intentional

**Comment by watersofnazareth** [comment]
It's just a unfilled air block, bit nitpicky as it doesn't affect the game

**Comment by LocalWaterCreeper911911** [comment]
@Thefuzz1234555 

I only screenshotted ONE of these "unfilled air blocks".

I managed to find about 30 of these!

**Comment by LocalWaterCreeper911911** [comment]
> same lol

same lol

**Comment by LocalWaterCreeper911911** [comment]
> @nonamecrackers2 closed this as not planned

umm WHAT

**Comment by Pandaboi25x** [comment]
> > @nonamecrackers2 closed this as not planned
> 
> umm WHAT

well its not exactly much of an issue.. plus its not exactly what players could see so

**Comment by LocalWaterCreeper911911** [comment]
> > > @nonamecrackers2 closed this as not planned
> > 
> > 
> > umm WHAT
> 
> well its not exactly much of an issue.. plus its not exactly what players could see so

yeah, but why is it INVALID?
