### ISSUE TITLE
Command Block Power Up

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#1175]
When killing the storm, you get a special power up which gives the power of the command block. You can break blocks, instantly and other cool stuff. Pick up blocks from the ground... and throwing them against mobs and also a flying ability. You can also turn off your power or on as well.

**Comment by Resuster** [comment]
Feel free to ignore this idea.

**Comment by Pandaboi25x** [comment]
Kinda op

**Comment by darkheart78** [comment]
i think if this exists it should only be given when the withered beacon is fully powered up at level 4 along with the support beacons

**Comment by Globalfirestorm10** [comment]
> i think if this exists it should only be given when the withered beacon is fully powered up at level 4 along with the support beacons

even with that, it's way too op. It's basically creative mode

**Comment by watersofnazareth** [comment]
The mod is suppose to retain a Vanilla+ esc feel at the very least, this completely overthrows balance

**Comment by Resuster** [comment]
I understand

**Comment by Tordx12881** [comment]
The command block tools exists, they can't break so you can use it infinite times
