### ISSUE TITLE
Skeleton AI does not stop, again... (WS Segments-related, not a duplicate of #551)

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1176]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3

**Mod version**
3.2.1.1

**Describe the bug**
T I T L E

**To Reproduce**
1. Summon WSS itself
2. kill it
3. See error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
NO other mods installed, except for JEI

**Screenshots**
![2023-04-27_21 29 13](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/093dfe91-cb4f-4c64-bab4-6ffee144a054)

Once again, its NOT a duplicate of #551 !!!

**Comment by LocalWaterCreeper911911** [comment]
3.2 is the most bug-free update the world has seen.

**Comment by Globalfirestorm10** [comment]
> 3.2 is the most bug-free update the world has seen.

Doubt that. While yes, 3.2 may have less bugs than the current versions, bugs are inevitable during development with all the new features.

**Comment by LocalWaterCreeper911911** [comment]
***sarcasmsacras***

**Comment by nonamecrackers2** [comment]
Should be fixed in the next 1.19.4/1.20.1 release
