### ISSUE TITLE
WS shoots a BUNCH of WSSkulls when evolves into phase 7

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1177]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**

WS shoots a BUNCH of WSSkulls when evolves into phase 7, causing in weird sound
effect and a lot of destruction
They all face the SAME direction btw

**To Reproduce**
1. SummonWS
2. Cause it to evolve into phase 7
3. See error

**Is OptiFine installed?**
Once again, NO OTHER MODS INSTALLED

**Screenshots**
![2023-05-13_20 06 23](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/6b373c60-f173-4dd7-8600-9e94b1f877e3)

![2023-05-13_20 05 16](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/a62acb3e-b5e9-4afb-8dfd-d9ac156ce18b)

**Comment by nonamecrackers2** [comment]
Could you send a video of what it looks like?

**Comment by BluePineappleGuy** [comment]
i think it could be a really cool thing if the heads only shot them in order and not at the same time.

**Comment by Steve982950** [comment]
> Could you send a video of what it looks like?

Yeah... we need a video to understand better

**Comment by LocalWaterCreeper911911** [comment]
> > Could you send a video of what it looks like?
> 
> Yeah... we need a video to understand better

I'm working on it :)

**Comment by LocalWaterCreeper911911** [comment]
It says: "This video is too big. Try again with a file size less than 10MB."

I should record everything over AGAIN!?

**Comment by MFNmodding** [comment]
are you able to upload it to youtube and put a link to it here?

**Comment by LocalWaterCreeper911911** [comment]
> are you able to upload it to youtube and put a link to it here?

Sadly, no. I dont even have a Youtube channel.

I'm still working on it though. :)

Was unable to reproduce the bug itself, however i found a bit of evidence :)

**Comment by LocalWaterCreeper911911** [comment]
I'll close it for now since i'm collecting more info.

**Comment by nonamecrackers2** [comment]
Don’t. It can remain open, it’ll only be closed if it’s invalid, can’t be reproduced, or fixed.

**Comment by LocalWaterCreeper911911** [comment]
Since i am unable to upload a video right now, ill use something else...

You see, there are lots of bugs that do only appear when your PC is lagging (when such things happen, 
WS is unable to beam me up properly, etc etc etc...), and my PC specs are PURE PAIN, which makes the game unplayable in Survival,but allows me to break the Game(including CWSM) as much as i want.

Considering of that i personally believe that this bug is related to my PC and etc.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
Update 4.3 when?

**Comment by nonamecrackers2** [comment]
This is technically intended, when it evolves it makes a bunch of the heads roar.
