### ISSUE TITLE
Nothing changed.

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1178]
I tried my best. PLEASE HELP ME

Here's the explaination:
![2023-05-13_20 56 35](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/8f22bac4-4a3f-499a-bc36-6db0757db929)

Full command:
`/data modify entity @e[type=witherstormmod:command_block,limit=1] BossfightManager:{PhaseTicks:0} set value 20`

It says:"Nothing changed. These attributes alreade have such values."

**Comment by LocalWaterCreeper911911** [comment]
Closing this since its neither a bug report nor a feature request.

**Comment by LocalWaterCreeper911911** [comment]
Nah, ill reopen it just to let the one & the only @nonamecrackers2 know about it.

**Comment by nonamecrackers2** [comment]
I’m not sure, try removing the “:0” from “PhaseTicks”. This isn’t a help forum though however so I will be closing this

**Comment by LocalWaterCreeper911911** [comment]
ok
