### ISSUE TITLE
The mod crashes when fighting the command block when I hit it for the third time, makes the world unusable. (I couldn't figure out how to put a label, it's an issue in 1.18)

### ISSUE THREAD

**Issue by ItsZed01** [nonamecrackers2/crackers-wither-storm-mod#118]
Here is the report you asked me to send: 
[report.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/8934359/report.txt)

**Comment by watersofnazareth** [comment]
It's a ticking entity crash caused from a Wither Skull at -2.75, 112.71, 26.97, seems to be also related to wither sickness?

**Comment by nonamecrackers2** [comment]
If you update to the latest version, it should be fixed
