### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xelotex** [nonamecrackers2/crackers-wither-storm-mod#1180]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.2

**Mod version**
3.1.1.1

**Describe the bug**
The first time the wither start chasing me and got close enough, the game crashed.

**To Reproduce**
Don't really know...

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
no-
**Screenshots**
[crash-2023-05-14_10.37.59-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/11472635/crash-2023-05-14_10.37.59-client.txt)

**Comment by Pandaboi25x** [comment]
are you sure optifine isnt installed? did you have any shaders on?

**Comment by xelotex** [comment]
> are you sure optifine isnt installed? did you have any shaders on?
no optifine, no shaders.

**Comment by xelotex** [comment]
> are you sure optifine isnt installed? did you have any shaders on?
seems like it is a MetaSpace error, how much ram this mod needs? i have allocated 8gs, should i double it to 16gs?

**Comment by nonamecrackers2** [comment]
Looks like atlas combat and corail tombstone are having some incompatibility issues. Doesn’t seem related to CWSM

**Comment by BluePineappleGuy** [comment]
have had similar issues with previous versions of the mod (i think before "a block and a hard place" update came out), only this time no mods
