### ISSUE TITLE
Spawning a Sickened Villager crashes the game

### ISSUE THREAD

**Issue by PandaMan69420** [nonamecrackers2/crackers-wither-storm-mod#1181]
**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
Upon spawning the sickened villager, the game freezes and shortly crashes after.

**To Reproduce**
1. Go to the creative tab & find the sickened villager spawn egg (or use commands to spawn it).
2. Spawn in the mob.
3. Game = ded

**Crash Reports / Logs**

[crash-2023-05-11_10.40.27-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/11498973/crash-2023-05-11_10.40.27-server.txt)

**Is OptiFine installed?**
No.

**Comment by nonamecrackers2** [comment]
What other mods do you have?

**Comment by PandaMan69420** [comment]
I, uh, have 140 mods loaded in, including the Wither Storm Mod.

**Comment by Globalfirestorm10** [comment]
Can you try reproducing this with just CWSM?

**Comment by PandaMan69420** [comment]
The game ended up not crashing, so there might be something wrong with one or more of the mods I installed.

**Comment by Globalfirestorm10** [comment]
The only method I could think of off the top of my head to find the problem is to break down the mod into chunks, load your world and spawn a sickened villager with that mod chunk, and see if it crashes. If it does crash, then chunk the mods down further, and so on until you find the incompatibility. The only problem is that this method takes a lot of time and is tedious, especially with your mod count

**Comment by nonamecrackers2** [comment]
You could try removing biomemakeover, sapience, and multiverse

**Comment by MFNmodding** [comment]
i wonder why sapience messes with it. as far as i can tell, it only affects piglins.

**Comment by nonamecrackers2** [comment]
I’m not sure if it would, I’m just looking at the crash report and seeing which mods may be potentially interfering.

**Comment by MFNmodding** [comment]
i had the same problem, and disabling sapience seemed to make things work.

**Comment by nonamecrackers2** [comment]
Oh, glad to know. Will just wait for a response from the OP to see if that fixes it for them then.

**Comment by watersofnazareth** [comment]
This does seem to be a compatibility issue with Sapience

**Comment by PandaMan69420** [comment]
I did take out Sapience when I first saw the first few comments, I just completely forgot to close the issue because I have horrible memory. Thanks for the help, though!

**Comment by nonamecrackers2** [comment]
No worries!
