### ISSUE TITLE
Fog is not applied to Tractor Beams when its nighttime

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1182]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
T. I. T. L. E.

**To Reproduce**
1. Customize your Tractor Beams
2. Summon WS
3. Go far away from it

**Is OptiFine installed?**
N/A

**Screenshots**
TOMORROW, im busy

**Comment by Pandaboi25x** [comment]
STOP

**Comment by LocalWaterCreeper911911** [comment]
WHY AM I the most controversial person on GH, DS? I TOLD YOU, im just lucky

**Comment by BluePineappleGuy** [comment]
> STOP

wdym

**Comment by LocalWaterCreeper911911** [comment]
> > STOP
> 
> wdym

I joined crackers DS, and blew up

**Comment by nonamecrackers2** [comment]
The tractor beams intentionally become white when from a distance as the color was deemed to look too out of place during the daytime in my opinion.

**Comment by LocalWaterCreeper911911** [comment]
> The tractor beams intentionally become white when from a distance as the color was deemed to look too out of place during the daytime in my opinion.

MISREAD! IM not about that.

**Comment by LocalWaterCreeper911911** [comment]
@nonamecrackers2  and please reopen this.

**Comment by nonamecrackers2** [comment]
Could you please provide a screenshot to better explain your issue then? I’m having trouble understanding exactly what you mean if I misread it

**Comment by LocalWaterCreeper911911** [comment]
> Could you please provide a screenshot to better explain your issue then? I’m having trouble understanding exactly what you mean if I misread it

Oh ok then, ill have to work on it.

**Comment by LocalWaterCreeper911911** [comment]
I figured it out.
![2023-05-20_20 48 54](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/03e78e25-2324-4e8b-8b43-e35fc4709b80)
![2023-05-20_21 11 18](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/073bce0d-6624-404f-b2e1-9f8bbcbd4051)

Is that intended?
@nonamecrackers2

**Comment by BluePineappleGuy** [comment]
pretty sure it is intended, looks like it at least

**Comment by nonamecrackers2** [comment]
Yes that is intended. The colors fade white from a distance during the daytime as the normal colors looked awkward during the day, but looked great during the night.
