### ISSUE TITLE
Custom tractor beam's color's doesnt affect the tractor beam outline

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1183]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
the version where you can have custom tractor beams

**Mod version**
it doesnt matter it still will do the thing

**Describe the bug**
basically if you change the tractor beam color *example* blue it wont affect the 

**To Reproduce**
1. change the tractor beam color
2. go in to the beams
3. wait
4. there is no custom tractor beam outline

**Is OptiFine installed?**
it doesnt matter if its installed both will have the same issue

**Screenshots**
as crackers already know i cant really check it :pain:
didnt know what to put it as so i put it as a bug

**Comment by LocalWaterCreeper911911** [comment]
ITS INTENDED

**Comment by Pandaboi25x** [comment]
why th is it intended

**Comment by Pandaboi25x** [comment]
how th is it intended

**Comment by LegendaryGodzilla** [comment]
e

**Comment by NinjaSam5399** [comment]
Please, I don't even want to do it with Datapack.

**Comment by nonamecrackers2** [comment]
The outline is a texture that can’t be coloured in code like the night shine. You’ll need to make a texture pack to change it.

**Comment by LocalWaterCreeper911911** [comment]
@Pandaboi25x 

told you

**Comment by Pandaboi25x** [comment]
Ah darn it

**Comment by Pandaboi25x** [comment]
> @Pandaboi25x
> 
> told you

Bro okay i know no need for that
