### ISSUE TITLE
Have the Wither Storm Evolve sound play in all dimensions

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1185]
Simple, the early game is a rush to get to the nether for the most part. However, you might need to go back and get something from the overworld, only to be met with a Phase 4 storm just arriving at your location and stealing your portal. By having the sound play in all dimensions, it makes it a lot easier to tell if the overworld is safe or not. Even if that isn't of concern, it raises the tension by telling you how much time you had before it came for you.

**Comment by Globalfirestorm10** [comment]
Ill be honest, this wouldn't make much sense, as whatever's in the overworld, including the storm can't bleed into the nether. Plus, IIRC, crackers said that this was intended and altering this or giving a "warning" would spoil the surprise of the storm being there.

**Comment by BluePineappleGuy** [comment]
> Ill be honest, this wouldn't make much sense, as whatever's in the overworld, including the storm can't bleed into the nether. Plus, IIRC, crackers said that this was intended and altering this or giving a "warning" would spoil the surprise of the storm being there.

still, would prefer to know when its become a giant monster when in the nether. it doesn't really spoil the surprise of it being there, it just tells you its huge now.

**Comment by BluePineappleGuy** [comment]
wait where is the suggestion label

**Comment by Globalfirestorm10** [comment]
> wait where is the suggestion label

Did you perhaps list this as a bug report instead of a feature suggestion?

**Comment by nonamecrackers2** [comment]
I like having the element of surprise, but could consider this as a config option defaulted to off

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
