### ISSUE TITLE
Phase 5 can be F-Bombed.

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1187]
The Phase 5 Wither Storm can be F-Bombed. I have known about this since release, but back then it could only be done with cheats. As of version 2.2/3.2, this can be done through normal survival by getting a Super TNT/Command Block Book before the Wither Storm is killed, then using it on the Phase 5 Wither Storm when resummoned, completely skipping Phase 5.5, and making the Wither Storm gets bigger which doesn't make sense logically.
This effects all versions regardless of if other mods are installed.

**Comment by IndigoAmethyst** [comment]
I believe this effects all versions, not just 1.19.4. @nonamecrackers2

**Comment by nonamecrackers2** [comment]
Support is going for the latest MC version, if this was a game-breaking bug I'd all the other version labels.

**Comment by nonamecrackers2** [comment]
This works as intended. There is no way to bomb the storm at phase 5 in a normal survival playthrough since the symbiont only spawns at phase 5.5

**Comment by IndigoAmethyst** [comment]
> This works as intended. There is no way to bomb the storm at phase 5 in a normal survival playthrough since the symbiont only spawns at phase 5.5

It is possible in Survival tho because if you get the Enchanted Command Block Book needed for an F-Bomb, then kill the Wither Storm, you will be able to make an F-Bomb before it gets to 5.5 when respawning the Storm @nonamecrackers2

**Comment by IndigoAmethyst** [comment]
In a more organised list
1. Get a Enchanted Command Block Book from a Phase 5.5+ Wither Storm, and store it somewhere safe like in the Nether or Underground.
2. Kill the Wither Storm and make a working Withered Beacon.
3. Resummon the Wither Storm (As you know it will be Phase 4).
4. Use the deposited ECBB to make an F-Bomb.
5. Use it on a Phsde 5 Wither Storm.

**Comment by IndigoAmethyst** [comment]
*Phase

**Comment by BluePineappleGuy** [comment]
you might also be able to use the f-bomb on other stages as well using that method

**Comment by IndigoAmethyst** [comment]
> you might also be able to use the f-bomb on other stages as well using that method

True, but only Phase 5 goes to Phase 6, which is odd as it makes it grow bigger.

**Comment by IndigoAmethyst** [comment]
The Phase 4 drops down and doesnt change

**Comment by nonamecrackers2** [comment]
I guess that’s true, however I doubt most players would ever do that. Disabling the formidibomb for those phases will confuse creative mode players, which happened in older versions of the mod when formidibombing the incorrect phase wasn’t possible.

**Comment by IndigoAmethyst** [comment]
> I guess that’s true, however I doubt most players would ever do that. Disabling the formidibomb for those phases will confuse creative mode players, which happened in older versions of the mod when formidibombing the incorrect phase wasn’t possible.

You could add a config setting.

**Comment by nonamecrackers2** [comment]
I could, but that would require another issue to be opened
