### ISSUE TITLE
sub phases in /witherstormmod phase set

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1189]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
make the phase command accept decimals and it would adjust the consumed entities and phase accordingly to apply the sub phase

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Globalfirestorm10** [comment]
Sub phases haven't really been made yet, but this would probably be added if they are to be added.

**Comment by darkheart78** [comment]
> Sub phases haven't really been made yet, but this would probably be added if they are to be added.

they are kinda made

**Comment by Globalfirestorm10** [comment]
not really. With the exception of phase 5.5, there aren't anymore

**Comment by Krypton6167** [comment]
actually there is a phase 7.5 when the whole opens but rather than that you are correct.

**Comment by myron-obsolete-account** [comment]
another phase in the recent evolution pt1 trailer has been found, probably phase 4.5 as far as I can tell

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
