### ISSUE TITLE
[Bug?] Inside the WS there are a lot of debris particles the player is never able to see

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#119]
Image: (https://user-images.githubusercontent.com/28667280/174461699-363a7e46-85f9-4249-bacc-7d93aa0a018c.png)
Don't know if this is known but they do cause a quite hefty FPS drop even with 2D Debris

**Comment by nonamecrackers2** [comment]
Will be partially fixed. There will always be some inside due to how the system works.
