### ISSUE TITLE
small additions to /witherstormmod

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1190]
1. /witherstormmod phase get
    this would be helpful as its easier to detect the current phase of the storm than doing '/data get entity (ws) phase'
2. /witherstormmod consumedEntities get
   same as /witherstormmod phase get, but for its consumed entity count.

and maybe other small QOL additions that i may think of in the future

**Comment by darkheart78** [comment]
agree

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
