### ISSUE TITLE
SIckened mobs have cursed heads.....?

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1191]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
When the Withered Symbiont spawns sickened mobs, their heads are cursed!

**To Reproduce**
1. Spawn Symbiont
2. Wait for him to spawn mobs
3. See Error

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
N/A

**Screenshots**
![2023-05-20_09 22 37](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128298281/959eb91c-563c-41ec-9fed-f4aec73515a4)

**Comment by IndigoAmethyst** [comment]
I believe this is a texture issue when sickened mobs wear armor.

**Comment by Steve982950** [comment]
ok

**Comment by Steve982950** [comment]
if this is DUPLICATE, please let me know and i will close

**Comment by LocalWaterCreeper911911** [comment]
> if this is DUPLICATE, please let me know and i will close

#1094, now close this.
@Steve982950
