### ISSUE TITLE
Have the Wither Storm Evolve sound play in the whole world when re-summoned

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1192]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
IIRC, the WS doesnt generate any sounds when re-summoned, thats why im suggesting that.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
It should. The sound won’t play if you’re too close to it though.
