### ISSUE TITLE
Add Target Stationary and Target Not Stationary sounds

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1193]
Currently, there is no way of conveying to the player that the Wither Storm gets faster when the player stays still too long. The problem as of now is the config settings are too confusing to know what counts as Stationary, so adding noises would alleviate this issue. By knowing of the settings, one could piece together what counts as stationary. For good measure, it could also apply when leaving nether portals to convey you need to run.

**Comment by nonamecrackers2** [comment]
You're not supposed to know when it's going to chase you and it is meant to be a surprise.
