### ISSUE TITLE
Particles when Hunchback Wither Storm Evolves.

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1194]
Particles appear around the Wither Storm when it goes into the next Phase, so that it doesn't just seem as if mass just blips into existence. (Sorry idk how to describe it better)

**Comment by watersofnazareth** [comment]
What do you mean exactly? it already has particles around it, but we have plans to make that less obvious currently

**Comment by nonamecrackers2** [comment]
Probably new particles that spawn upon evolving.

**Comment by IndigoAmethyst** [comment]
Ye

**Comment by IndigoAmethyst** [comment]
What I mean is that the Wither Storm is covered in particles when transforming into the next phase.

**Comment by IndigoAmethyst** [comment]
For a smoother transition

**Comment by nonamecrackers2** [comment]
I don't think the particles existence would make much sense. Besides, we have some stuff coming that will help with the transition a bit.
