### ISSUE TITLE
Blocks exposed to air automatically get sucked up by Wither Storm

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1195]
If there are blocks that are floating in the air, then they will be sucked up by the Wither Storm. This would make a Wither Storm-wrecked area look alot more realistic and less random and ugly.

**Comment by GearsawStudios** [comment]
Doesn't quite address the more than 1 block pieces, but otherwise a reasonable solution to this issue.

**Comment by watersofnazareth** [comment]
This would require too many checks to be practical, and would be very laggy in doing so
