### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ScriptleGIT** [nonamecrackers2/crackers-wither-storm-mod#12]
Wither Storm at Phase from 4 to 7 can grab you with tentacles and: Eat, or Launch you in stratosphere

Why? IDK, I was Bored

**Comment by nonamecrackers2** [comment]
It would be quite hard to implement this with how the mod is written, and to make it even viable I would have to write a lot of code (and it may not even turn out solid). Thanks for the suggestion, though!

**Comment by nonamecrackers2** [comment]
I also won’t be doing this as I don’t feel the tentacles reaching from the default flying height it uses is unrealistic

**Comment by Joshowa5** [comment]
> I also won’t be doing this as I don’t feel the tentacles reaching from the default flying height it uses is unrealistic

maybe there should be different attack modes where the witherstorm starts to get closer to the ground and the tentacles could be like upside down and larger versions of the tentecles you find in the bowels

**Comment by User198263321** [comment]
Could make sense if Witherstorm is configured to fly lower to the ground. It can also grab flying entities at default height or multitask by grabbing mob from the tractor beam then while it aims tractor beam at a new mob it eats the held mob with lower jaw while beam relatively stays on the next mob (upper head moves slightly to add realism to animation but still staying on next mob while most movement is from lower part of the head).

**Comment by humzahre** [comment]
I agree with Joshowa. Make the height of WS lower to start tentacle attacks

**Comment by Asteroid4** [comment]
y so many duplicates of this

**Comment by humzahre** [comment]
bruh nonamecrackers2, EVEN IF this is hard, Never give up. It may soon be possible! :)
