### ISSUE TITLE
distraction only drops players

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#120]
for some reason when I distract the wither storm it only drops me, while the other mobs that are being picked up keep floating away. (and yes, those heads are distracted too, so dont bug me about them not being distracted) also, it sometimes doesnt even drop players at all. can you fix this please?

**Comment by nonamecrackers2** [comment]
Do you mean while they are distracted mobs are still being pulled in? That would be unintended.
