### ISSUE TITLE
Tainted Warden decoration block

### ISSUE THREAD

**Issue by WitherInSuit** [nonamecrackers2/crackers-wither-storm-mod#1200]
Add a tainted warden block similar to that of tainted zombies and skeletons that would act as a decoration block appearing in the ancient city sectors of the bowels. Perhaps it could drop skulk and withered bones when broken.

**Comment by Globalfirestorm10** [comment]
we already have one of those

**Comment by watersofnazareth** [comment]
I'd rather not work on this, it's unnecessary as it doesn't make too much sense
