### ISSUE TITLE
WS turning into blocks when entering bowels (big text warning)

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1203]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
You see , i just figured out that you can generate a structure inside of another structure using zigsaw blocks. Which means:

1. you can simply make the bowels dimensions made out of fresh AIR and put a WS-looking (big) structure made out of withered flesh and sickened flesh (which would reduce lag a little bit)

2. this structure should generate smaller structures (including Bossfight Room) inside of it using these zigsaw blocks

3. bowels biome should be inside of this structure
 
4. Bowels Storm is like a WS, but without its torso. Should be protected from being digged out using hardened flesh.Used to 
simulate tentacles, debris cloud and even three WS heads.

5. to be announced...

6. If you get too far away from the Storm(OR if you fall down in the void), you get teleported to Overworld using "Aether" thingo

7. Some places should contain "WitherStorm food" from #1116 

8. The deeper you are in the Bowels, the more silent the Bowels Storm becomes(sorry i cant explain better)

**ONLY ONE FEATURE REQUEST PER ISSUE**

IK, and?

@nonamecrackers2

**Comment by LocalWaterCreeper911911** [comment]
I edited this six times already...       BRUH

**Comment by LocalWaterCreeper911911** [comment]
#crackcrackcrack

@nonamecrackers2

**Comment by Globalfirestorm10** [comment]
1. Dude, have some patience, he's gonna see it, just wait
2. Jesus christ that was a lot to read
3. The only problem with this is that Idk if it fits the mod well, and if proper collision is possible.

**Comment by LocalWaterCreeper911911** [comment]
> 1. Dude, have some patience, he's gonna see it, just wait
> 2. Jesus christ that was a lot to read
> 3. The only problem with this is that Idk if it fits the mod well, and if proper collision is possible.

1. OK
2. I told you, big text warning
3. #crackcrackcrack

**Comment by nonamecrackers2** [comment]
Are you suggesting that the bowels structure generates a shell of the Wither Storm in void in the bowels dimension?

**Comment by LocalWaterCreeper911911** [comment]
> Are you suggesting that the bowels structure generates a shell of the Wither Storm in void in the bowels dimension?

Idk what exactly you mean by "shell" , but YES!

**Comment by nonamecrackers2** [comment]
Doing that wouldn't really make much sense. In the bowels dimension, you never leave the bowels structure, so you wouldn't ever see this "shell" structure of the Wither Storm making it pointless. Also, lag wise, this would probably make it worse, as more blocks are exposed than just having the whole dimension filled with blocks since all the faces that are exposed would not be rendered.

**Comment by LocalWaterCreeper911911** [comment]
someone ban me from GH please

**Comment by Globalfirestorm10** [comment]
Why?

**Comment by LocalWaterCreeper911911** [comment]
> Why?

because
![16](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/3db42575-ea21-4083-b4f4-45566e123a07)

**Comment by LocalWaterCreeper911911** [comment]
> Doing that wouldn't really make much sense. In the bowels dimension, you never leave the bowels structure, so you wouldn't ever see this "shell" structure of the Wither Storm making it pointless. Also, lag wise, this would probably make it worse, as more blocks are exposed than just having the whole dimension filled with blocks since all the faces that are exposed would not be rendered.

1. as i believe, this would add more of "guys look, im inside the storm" feeling instead of current "yeah look, he teleported me to this indestructible maze" feeling, especially considering that current bowels are MUCH bigger then phase 7.5 storm.

2. also this could be used to turn the bowels looting process from "exploring caves" to "hunting treasures".
For example, if you see a big patch of sickened flesh on storms body, this should mean that some structure via loot is hidden here.

3. since this "torso" wouldnt be as big as current bowels, i dont think this would cause much lag.

@nonamecrackers2

**Comment by nonamecrackers2** [comment]
You never see the outside of the bowels so technically players don't know it's technically an indestructible maze... the idea is that you're inside the storm and I don't think players would really realize fully that they technically aren't/wouldn't really care. They also wouldn't know there was a replica torso of it outside of the bowels either.

If you're suggesting that players start from the outside of this torso structure and go inside, there are a few problems:
1. The pink fog would be everywhere and it wouldn't make very much sense
2. The torso would look weird, as it wouldn't look like an actual wither storm. The tentacles and heads would be missing, among us other problems.
3. There would just be void, so how would player travel to this torso structure and get inside?

Regardless, this feature simply wouldn't be worth the effort to try to implement when the current system is perfectly fine, I don't see any problems with it.

**Comment by GearsawStudios** [comment]
> You never see the outside of the bowels so technically players don't know it's technically an indestructible maze... the idea is that you're inside the storm and I don't think players would really realize fully that they technically aren't/wouldn't really care. They also wouldn't know there was a replica torso of it outside of the bowels either.
> 
> If you're suggesting that players start from the outside of this torso structure and go inside, there are a few problems:
> 
> 1. The pink fog would be everywhere and it wouldn't make very much sense
> 2. The torso would look weird, as it wouldn't look like an actual wither storm. The tentacles and heads would be missing, among us other problems.
> 3. There would just be void, so how would player travel to this torso structure and get inside?
> 
> Regardless, this feature simply wouldn't be worth the effort to try to implement when the current system is perfectly fine, I don't see any problems with it.

Exploring the mineshafts often reveals that it's an indestructible maze but your point stands.

**Comment by LocalWaterCreeper911911** [comment]
> You never see the outside of the bowels so technically players don't know it's technically an indestructible maze... the idea is that you're inside the storm and I don't think players would really realize fully that they technically aren't/wouldn't really care. They also wouldn't know there was a replica torso of it outside of the bowels either.
> 
> If you're suggesting that players start from the outside of this torso structure and go inside, there are a few problems:
> 
> 1. The pink fog would be everywhere and it wouldn't make very much sense
> 2. The torso would look weird, as it wouldn't look like an actual wither storm. The tentacles and heads would be missing, among us other problems.
> 3. There would just be void, so how would player travel to this torso structure and get inside?
> 
> Regardless, this feature simply wouldn't be worth the effort to try to implement when the current system is perfectly fine, I don't see any problems with it.

1. Isnt the pink fog generated by "bowels" biome?

2. I talked about this already, what i think would fit well is an entity that looks like WS without torso and etc.

3. IDK what exactly you mean, but doesnt the player always spawn inside the bowels?

@nonamecrackers2 

#crackcrackcrackcrackcrackcrack

**Comment by nonamecrackers2** [comment]
> > You never see the outside of the bowels so technically players don't know it's technically an indestructible maze... the idea is that you're inside the storm and I don't think players would really realize fully that they technically aren't/wouldn't really care. They also wouldn't know there was a replica torso of it outside of the bowels either.
> > If you're suggesting that players start from the outside of this torso structure and go inside, there are a few problems:
> > 
> > 1. The pink fog would be everywhere and it wouldn't make very much sense
> > 2. The torso would look weird, as it wouldn't look like an actual wither storm. The tentacles and heads would be missing, among us other problems.
> > 3. There would just be void, so how would player travel to this torso structure and get inside?
> > 
> > Regardless, this feature simply wouldn't be worth the effort to try to implement when the current system is perfectly fine, I don't see any problems with it.
> 
> Exploring the mineshafts often reveals that it's an indestructible maze but your point stands.

That is true, I guess I’m more trying to say that isn’t supposed to be the players first impression.
