### ISSUE TITLE
Super TNT duplication glitch (easy-to-fix)

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1204]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
Basically, at this moment, every single man who plays minecraft is aware of TNT duplication machine. However, after some testing appears that this machine works with Super TNT as well! The only fix for that is to disallow players to move Super TNT with 
pistons, just like cracker already did with the Fbomb.

**To Reproduce**
1. Build a TNT duplication machine
2. Replace TNT with Super TNT
3. See your machine causing MUCH MUCH  more destruction

**Is OptiFine installed?**
N/A

**Screenshots**
The path of destruction (made in under 5 mins)

![2023-05-19_19 51 11](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/79e75364-3625-44e5-9751-0b3b53b7af09)

**Comment by NinjaSam5399** [comment]
Report it to the official Minecraft, not this mod.

**Comment by LocalWaterCreeper911911** [comment]
> Report it to the official Minecraft, not this mod.

I mean, im suggesting for cracker to disallow us to move Super TNT with pistons, just like he did with F-bomb.

**Comment by BluePineappleGuy** [comment]
this is actually really cool

**Comment by LocalWaterCreeper911911** [comment]
> this is actually really cool

![15](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/edd88b67-98a9-4242-b525-0b41b314fab3)

**Comment by BluePineappleGuy** [comment]
> > this is actually really cool
> 
> ![15](https://user-images.githubusercontent.com/129298645/241403005-edd88b67-98a9-4242-b525-0b41b314fab3.PNG)

thats exactly why its cool, gonna commit genocide on a village before this gets fixed >:)

**Comment by LocalWaterCreeper911911** [comment]
> > > this is actually really cool
> > 
> > 
> > ![15](https://user-images.githubusercontent.com/129298645/241403005-edd88b67-98a9-4242-b525-0b41b314fab3.PNG)
> 
> thats exactly why its cool, gonna commit genocide on a village before this gets fixed >:)

bruh why are you all so evil :(

**Comment by Theoyeah** [comment]
> > > this is actually really cool
> > 
> > 
> > ![15](https://user-images.githubusercontent.com/129298645/241403005-edd88b67-98a9-4242-b525-0b41b314fab3.PNG)
> 
> thats exactly why its cool, gonna commit genocide on a village before this gets fixed >:)

I love genocide

**Comment by LocalWaterCreeper911911** [comment]
> > > > this is actually really cool
> > > 
> > > 
> > > ![15](https://user-images.githubusercontent.com/129298645/241403005-edd88b67-98a9-4242-b525-0b41b314fab3.PNG)
> > 
> > 
> > thats exactly why its cool, gonna commit genocide on a village before this gets fixed >:)
> 
> I love genocide

I shouldnt have reported that bug ( '_' )

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release

**Comment by Luke7381** [comment]
> Will be fixed in the next 1.19.4/1.20.1 release

bro can you consider making it a option to make fbombs or super tnt dupeable?
my man needs his genocide.

**Comment by nonamecrackers2** [comment]
Lol I mean think of the lag it would cause

**Comment by Theoyeah** [comment]
> Lol I mean think of the lag it would cause

Well i don't care i got a fucking nvidia rtx and a ryzen to burn this is the best way to commit genocide 😈

**Comment by BluePineappleGuy** [comment]
> Lol I mean think of the lag it would cause

more lag means less time for the villagers to escape hehehehe
