### ISSUE TITLE
Flashing Storm Heads...

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1205]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4/1.19.3/1.19.2, Probably previous versions..

**Mod version**
3.2.1.3 and maybe older

**Describe the bug**
When I fall out of the bowels, I notisced the WS heads flashing..

**To Reproduce**
1. Go to Bowels
2. Deal a hit to the Commandblock
3. Fall out of bowels
4.  See Error

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
N/A

**Screenshots**

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128298281/58001aa4-27d7-4173-b37c-d75273377b68

**Comment by LocalWaterCreeper911911** [comment]
Thats intended, its because you damaged Command Block.

**Comment by Steve982950** [comment]
ok
