### ISSUE TITLE
Flipping Bowels (Feel Free to Ignore this Issue if it isn't Possible)

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1206]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
In Bowels Fight Phase 3, Can you make it so that the Command block Platform flips upside down? The Screenshot is an idea/example
![Minecraft_ 1 19 4 27_05_2023 18_01_50](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128298281/d5d5c7e3-b58f-4005-a482-d16e76d77b80)
 (Once Again, feel free to ignore if not possible.)
**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
Please read the guidelines.

**Comment by Steve982950** [comment]
> Please read the guidelines.

''***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**''
