### ISSUE TITLE
Visual Glitches with shaders

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1207]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
when i kill the WS, Visual glitches happen

**To Reproduce**
1. Install mods Oculus & Rubidium
2. Enable Shaders
3. Kill WS

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
No, only Oculus & Rubidium

**Screenshots**
![Minecraft_ 1 19 4 27_05_2023 22_30_31](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128298281/f0083992-8010-41b1-b405-16976000d116)

**Comment by Steve982950** [comment]
Also btw this happens in 1.19.4/1.19.3

**Comment by Steve982950** [comment]
OK WHY IS THIS UN-NOTICED?

**Comment by nonamecrackers2** [comment]
What versions of rubidium and oculus are you using?

**Comment by Steve982950** [comment]
OCULUS: 1.5.2, whereas RUBIDIUM: 0.6.4

**Comment by nonamecrackers2** [comment]
Any other mods?

**Comment by Steve982950** [comment]
well i have

Worldedit,
CWSM,
Aether,
Oculus,
Rubidium.
mob battle

**Comment by Steve982950** [comment]
Im Kinda worried about the issue, is this to be resolved in CWSM EVOLUTION Part 2/3?

**Comment by nonamecrackers2** [comment]
> Im Kinda worried about the issue, is this to be resolved in CWSM EVOLUTION Part 2/3?

Probably not, this seems to be a shader mod issue

**Comment by Steve982950** [comment]
hmm ok

**Comment by nonamecrackers2** [comment]
For whatever reason I cannot reproduce this issue. I recommend trying to replicate this with Embeddium instead of Rubidium to see if the issue persists.

**Comment by Herobrine982950291** [comment]
I replicated it with embeddium and same results

**Comment by Herobrine982950291** [comment]
sorry i took too long XD

**Comment by Herobrine982950291** [comment]
btw this my alt, my real account i cant access

**Comment by nonamecrackers2** [comment]
I'll see if I can replicate it then further.

**Comment by TaintedBlock** [comment]
This glitch only depends on the kind of shaders you use. Seeing that you're using BSL (I think), that's probably why. I don't think crackers can fix this himself.

**Comment by nonamecrackers2** [comment]
Is that BSL? I guess that would probably impact results lol, I think I used Complementary when testing this out

**Comment by Herobrine982950291** [comment]
I also used complementary just now IoI

**Comment by Herobrine982950291** [comment]
Complementary also has same results.

**Comment by Herobrine982950291** [comment]
In fact, I tested ALL shaders I have, same results

**Comment by nonamecrackers2** [comment]
Still cannot replicate. Can you send a screenshot of your F3 menu as the bug is happening?

**Comment by Herobrine982950291** [comment]
alright
just wait a bit, i will have it ready.

**Comment by Herobrine982950291** [comment]
![2024-04-24_21 09 45](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/85f81d9f-ce11-4fea-b5a0-faf951d72e29)

**Comment by TaintedBlock** [comment]
final issue before 1.5 moment

**Comment by Herobrine982950291** [comment]
Got the info you needed?

**Comment by LucasDotje** [comment]
I've Tried It Also And It Seems To Be Working Fine On 1.20.1, It Could Be That Oculus And Rubidium Have Some Issues, Maybe Try Oculus Version 1.6.9? And Embeddium 0.2.13

**Comment by Luke7381** [comment]
> Got the info you needed?

Have you tried doing a fresh installation and only having CWSM, oculus, Embeddium and whatever shader you were using? Also for good measure make sure your using the latest version of each mod and try not to edit any settings.

**Comment by nonamecrackers2** [comment]
Found the issue, it's because of Complementary Unbound 4.7.2. Using an updated version of the shaders fixed the issue for me.
