### ISSUE TITLE
Wither storm doesnt suck up the f bomb

### ISSUE THREAD

**Issue by SculkWizard** [nonamecrackers2/crackers-wither-storm-mod#1208]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2 

**Mod version**
I dont know sorry
**Describe the bug**
When i want to kill the wither storm with the formidi bomb, he does not suck it up. It just explodes on the ground and doesnt kill him.

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
No

**Screenshots**

**Comment by Steve982950** [comment]
I think you are using an old version of CWSM. try version 2.2/2.2.1/

**Comment by LocalWaterCreeper911911** [comment]
> I think you are using an old version of CWSM. try version 2.2

yeah, old version had the SAME bug, it was fixed in 2.2

**Comment by Globalfirestorm10** [comment]
Please fill out the template, and is it at phase 5?

**Comment by IndigoAmethyst** [comment]
Are you using version 2.2

**Comment by IndigoAmethyst** [comment]
Can you send a video?

**Comment by SculkWizard** [comment]
Okay i will try it again

Steve982950 ***@***.***> schrieb am So., 28. Mai 2023, 16:02:

**Comment by Steve982950** [comment]
ok..

**Comment by nonamecrackers2** [comment]
Please fully fill out the template and provide your mod version.
