### ISSUE TITLE
Make WS able to keep mobs in its tracker beam when it moves its head if it choices to.

### ISSUE THREAD

**Issue by LunchTingz56** [nonamecrackers2/crackers-wither-storm-mod#1209]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by IndigoAmethyst** [comment]
That may be hard to code, but we will have to see Cracker's opinion before anything.

**Comment by nonamecrackers2** [comment]
#590
