### ISSUE TITLE
[Shake block clusters before being picked up] Better block absorbtion

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#121]
Can you try making the wither storm pull in blocks with it's tractor beam? maybe you could make it pick up the blocks behind/below it's target and they could be in smaller quantities than the stage it is in. also, you could make it just pick up one block every now and then with the tractor beam, just for a bit of immersion. another thing you could do is make blocks vibrate a little bit before they are picked up, that could make it even more immersive and like story mode. One last thing you could do is make it so when a block cluster detects a village house within 2 blocks outside of the cluster itself, it jumps to it. it then turns into multiple pieces that slowly move apart and then get pulled into the wither storm. to simplify it, the wither storm picks up village houses that are near block clusters, which then fall apart into a few pieces while being pulled into the wither storm. I recommend doing this with the tractor beam too, as it also adds a bit of immersion.

**Comment by nonamecrackers2** [comment]
The tractor beams already pick up block clusters. The clusters shaking before being picked up could be interesting,

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
