### ISSUE TITLE
Resummoned Wither Storm Phase Config

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1210]
A useful config option and a easy one to implement would be to be able to change the Phase the Wither Storm starts at when resummoned with the Withered Beacon.

If this is implemented, then I think you should make it accept decimals so that Phase 5.5 and 7.5 work.

**Comment by IndigoAmethyst** [comment]
I am just asking because I would like to use it on my CWSM server as I don't feel the early phases get experienced enough

**Comment by BluePineappleGuy** [comment]
i like this, crackers pls make

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
