### ISSUE TITLE
you can heal the command block and make the ws immortal

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1211]
**Minecraft version**
1.19.4

**Mod version**
why is this a double question 1.19.4

**Describe the bug**
hitting the command block and healing it with the healing potion makes the storm invincible

**To Reproduce**
1. Go to the bowels
2. attack the cmdb
3. heal it
4.repeat till you see the error

**Crash Reports / Logs**
no crash

**Is OptiFine installed?**
no

**Screenshots**
if github would be better and let me send a vid i would

**Comment by LocalWaterCreeper911911** [comment]
Minecraft version and CWSM version are not the same thing.

**Comment by Pandaboi25x** [comment]
> Minecraft version and CWSM version are not the same thing.

what

**Comment by nonamecrackers2** [comment]
Mod version is on the jar file of the mod, e.x. 3.2.1.2

**Comment by Pandaboi25x** [comment]
> Mod version is on the jar file of the mod, e.x. 3.2.1.2

oooooooh thats what it meant 💀 
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/31e10637-3515-4f5b-b35d-07805d14966a)

**Comment by LocalWaterCreeper911911** [comment]
I can confirm this, on top of that, the ENTIRE CB battle process is affected by this. If you heal it back to full health, its pulse goes back to normal, tentacles become passive while still dancing, bossfight music stops playing, witherstorm stops screaming and shaking, and etc etc...

**Comment by LocalWaterCreeper911911** [comment]
also this
![2023-05-30_21 19 06](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/51b9419b-ed90-4069-a93a-50afd4cd1f6b)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 update
