### ISSUE TITLE
CWSM explosives cannot be ignited by flaming arrows / fire spread

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1212]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
Up here, user.

**To Reproduce**
1. place down fbomb or super tnt
2. try to ignite them via flaming arrow or fire spread

**Is OptiFine installed?**
N/A

**Screenshots**
SOON

**Comment by LocalWaterCreeper911911** [comment]
btw all versions are affected by this

**Comment by LocalWaterCreeper911911** [comment]
btw 1212 is a LUCKy number

**Comment by nonamecrackers2** [comment]
Unable to reproduce the flaming arrows issue, seems to be working perfectly fine. Fire spread appears to not be working but I personally don't mind that and see it more as a feature.
