### ISSUE TITLE
Wither Storm mass turns red after FormidiBomb

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1213]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
Wither Storm mass and segments mass turn red.

**To Reproduce**
1. Have a good amount of fire under the wither storm
2. blow up the wither storm
3. wait for it to play dead

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
no

**Screenshots**
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/8d4e15a9-165a-4517-9b5c-96355dada761)

**Comment by LocalWaterCreeper911911** [comment]
i see nothing wrong here

**Comment by nonamecrackers2** [comment]
That screenshot is very hard to see, could you send a better one?

**Comment by TaintedBlock** [comment]
> That screenshot is very hard to see, could you send a better one?

I only took a few that look about the same. I can try an recreate this in the same world
![2023-05-31_09 18 38](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/59ef8104-dfb0-4cd4-9f5b-b46c8e451cd0)
if you look at the tentacle then the mass I think you could see the difference (This is the first time screenshot)

**Comment by TaintedBlock** [comment]
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/bf03a72e-d2fc-4859-804f-eaab91c5a306)
here is another
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/545e3bb6-8733-491f-a89d-7345e4e89f0c)

**Comment by TaintedBlock** [comment]
it did turn back normal when it woke up

**Comment by TaintedBlock** [comment]
ok after multiple test I couldn't seem to get it again

**Comment by TaintedBlock** [comment]
nvm i got it to work again. The wither storm has to land in fire and probably lava too for it to turn red

**Comment by nonamecrackers2** [comment]
Ah alright then.
