### ISSUE TITLE
Prevent the Wither Storm from taking blocks away near the player if the Symbiont is attacking

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1214]
When fighting the Symbiont (Very prevalent during the 2nd fight if you wait until phase 7) the Storm often ruins the battle field for the fight, leading to a variety of issues. Such issues include but aren't limited to:

Cheap hits from the blocks you're standing on being taken
Turning the arena into a cave battle (This issue has deleted my book before by hiding it, long story)
Trapping its minions in pits
Trapping the Symbiont into a pit, or worse, a cave it might outright not be found in if it doesn't ground slam

Adding would likely be simple, add a function that detects if the player is within Symbiote theme range. If so, do not pull blocks within ~30 blocks of said player.

**Comment by LocalWaterCreeper911911** [comment]
I dont really like this idea for at least two reasons:

1. This feature could be easily abused.

2. this makes the storm less dangerous when fightihg symbiont soooo

**Comment by BluePineappleGuy** [comment]
crackers said on a video showcasing the symbiont fight that he liked fighting a boss as the world around you gets eaten by the storm (paraphrasing, cant find the video but i watched it)

**Comment by GearsawStudios** [comment]
> crackers said on a video showcasing the symbiont fight that he liked fighting a boss as the world around you gets eaten by the storm (paraphrasing, cant find the video but i watched it)

The world does get eaten around you, just not *on* you so the fight isn't interrupted.

**Comment by GearsawStudios** [comment]
> I dont really like this idea for at least two reasons:
> 
> 1. This feature could be easily abused.
> 2. this makes the storm less dangerous when fightihg symbiont soooo

You're still able to be inflicted with Wither Sickness, not to mention potential accidental tractor beam. You can't abuse it because of that and the threat of the Symbiote. Multiplayer could be an issue in that sense but the Sickness is still prevalent.

That's the whole idea, you're fighting the Symbiote, not the Wither Storm.

**Comment by GearsawStudios** [comment]
On second thought, this would be better if it was around the symbiote to encourage not running away.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
