### ISSUE TITLE
WS defeat poem

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1215]
same as the end poem, but for the WS and a different poem or perhaps quotes.

**Comment by TaintedBlock** [comment]
No.

**Comment by Bloxxify1520** [comment]
> No.

Why not? I think it may fit kind of.

**Comment by TaintedBlock** [comment]
> > No.
> 
> Why not? I think it may fit kind of.

Well 1, you enter the end portal to even get the text. 2, the Wither Storm isn't a giant growing portal. Its a boss fight. Just like the Wither

**Comment by V0calgiant12** [comment]
While it is an interesting idea, it wouldn't really be the best idea, even if incorporated in a way like Terraria's credits are, it still would get in the way.

**Comment by LocalWaterCreeper911911** [comment]
> same as the end poem, but for the WS and a different poem or perhaps quotes.

bruh i was about to open same issue :(

**Comment by nonamecrackers2** [comment]
I’m not sure what this poem would even consist of. An interesting idea however I don’t really feel it would fit in that much.
