### ISSUE TITLE
Command Block knocking players into pit with no ways to escape when dying

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1216]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
I guess, it would be neat if when CB is dying, it would knock nearby players into the hole which would automatically lead them out of the bowels, instead of instant teleportation.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
I prefer the instant teleportation and making it knock you into the hole reliably would be difficult.

**Comment by LocalWaterCreeper911911** [comment]
> I prefer the instant teleportation and making it knock you into the hole reliably would be difficult.

No, i meant just a simple knockback when the player hits CB for final time. Considering that CB is already capable of knockbacking players, this should be possible.
