### ISSUE TITLE
Abandoned WSSegments should act like normal WS

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1218]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
This Segment have lost his father because of #1144 , and now hes feeling lonely. He doesnt move, his heads are glitched, he simply cant do anything. Press F to pay respect to him.
![2023-04-27_21 28 04](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/6be9b18c-6115-4df2-aec9-41bd0ba662f6)

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by LocalWaterCreeper911911** [comment]
I pressed F

**Comment by IndigoAmethyst** [comment]
This doesn't happen via normal gameplay, so I don't think this will be added but idk

**Comment by LocalWaterCreeper911911** [comment]
> This doesn't happen via normal gameplay, so I don't think this will be added but idk

It does, if you set chunk loading radius below 100 (#1144 ) so idk

**Comment by IndigoAmethyst** [comment]
_well it's not **supposed** to happen_

**Comment by LocalWaterCreeper911911** [comment]
> _well it's not **supposed** to happen_

OK, ill wait for cracker to appear

**Comment by nonamecrackers2** [comment]
The segments should never be left behind. I believe this behaviour is a bug and has already been reported.

**Comment by LocalWaterCreeper911911** [comment]
> The segments should never be left behind. I believe this behaviour is a bug and has already been reported.

I mean, this should also include Segments that were spawned in via /summon

**Comment by watersofnazareth** [comment]
My guy, that's only someone with cheats can do, this mod is intended for Survival play, doing this would make no sense

**Comment by nonamecrackers2** [comment]
If a segment doesn’t have a parent wither storm, they will maintain some default wither storm behaviour. They aren’t meant to be on their own and so this default behaviour wont be enhanced.
