### ISSUE TITLE
crackers wither storm mod crashes minecraft

### ISSUE THREAD

**Issue by Minecraftplayer20** [nonamecrackers2/crackers-wither-storm-mod#1219]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.1.6.5

**Mod version**
witherstormmod-1.16.5-1.0.3.jar

**Describe the bug**
Everytime I launch my modded version of minecraft with the witherstorm mod it gives me an error code that saysThe game crashed whilst rendering overlay
Error: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file witherstormmod-client.toml of type CLIENT for modid witherstormmod

**To Reproduce**
1. Go to 'curseforge and then go to minecraft'
2. Click on 'the minecraft installation that has the witherstorm mod'
3. Scroll down to 'play button and launch minecraft'

**Crash Reports / Logs**
https://gist.githubusercontent.com/Minecraftplayer20/c366a39272215420a812144b521f4f31/raw/86fa594e7855e1538e51b3d6f439a8bdfaeb49f9/latest.txt

**Is OptiFine installed?**
no

**Screenshots**
![error](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/106546611/a400c7ee-5116-4afe-9fdf-e41e4b9d7c79)

**Comment by TaintedBlock** [comment]
bro playing in the future

**Comment by BluePineappleGuy** [comment]
try checking your config folder in '.minecraft' (or the forge save directory if its a different folder) for the CWSM client config file

**Comment by nonamecrackers2** [comment]
The client config file may be corrupted, try deleting it and restarting the game

**Comment by Minecraftplayer20** [comment]
> The client config file may be corrupted, try deleting it and restarting the game

where is the client config file do you mean the witherstorm mod client file?

**Comment by Minecraftplayer20** [comment]
> The client config file may be corrupted, try deleting it and restarting the game

which config file I have so many config files in my config folder from other mods

**Comment by BluePineappleGuy** [comment]
> > The client config file may be corrupted, try deleting it and restarting the game
> 
> which config file I have so many config files in my config folder from other mods

it should be called 'witherstormmod-client.toml'

**Comment by Minecraftplayer20** [comment]
> The client config file may be corrupted, try deleting it and restarting the game
I tried deleting witherstormmod-client.toml it gave me the same error

**Comment by Minecraftplayer20** [comment]
> > > The client config file may be corrupted, try deleting it and restarting the game
> > 
> > 
> > which config file I have so many config files in my config folder from other mods
> 
> it should be called 'witherstormmod-client.toml'

I tried deleting witherstormmod-client.toml it gave me the same error

**Comment by Minecraftplayer20** [comment]
> The client config file may be corrupted, try deleting it and restarting the game

nonamecrackers2 can you close this issue im not gonna try to fix my installation anymore I think its just corrupted because I downgraded to an older version of crackers wither storm mod it didn't say the config file of crackers wither storm mod was broken but now my other config files from other mods keep having the same problem just like crackers wither storm mod config file im just gonna have to delete my installation

**Comment by nonamecrackers2** [comment]
Alright then
