### ISSUE TITLE
cluster create command revamp

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#122]
just a follow up to a comment I made a few weeks ago
One thing you could do for the cluster create command is make it have a specifier like this:
/witherstormmod cluster create (position and radius/pos 1-pos2) @e[type=witherstormmod:wither_storm,limit=1] 

The specifier makes the cluster float and disappear at the specified entity, with it being able to go to any entity (just to make it a bit more simple, you can decide to add this part or not)

**Comment by Guidealorean** [comment]
sounds better than having to manually edit the motion tag so it flies towards the wither storm

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
