### ISSUE TITLE
WS doesnt follow you if your more then 1000 blocks away 1.19.4

### ISSUE THREAD

**Issue by TheMictick** [nonamecrackers2/crackers-wither-storm-mod#1221]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
1.19.4-3.2.1.3

**Describe the bug**
Starting from phase 3 and up the WS wont follow you if are more then 1000 blocks away.

1. Summon wither storm
2. Get it to phase 3 or higher.
3. Move a 1000 blocks away or more.

**Is OptiFine installed?**
I tryed using without it and it still doesnt work.

**Comment by watersofnazareth** [comment]
Can you give us more details? perhaps a screenshot?

**Comment by TheMictick** [comment]
Nvm I fixed it. However I am experiences serious lag when i move away from it. Are there any perfomance mods that can increase my FPS with this mod?

**Comment by watersofnazareth** [comment]
> Nvm I fixed it. However I am experiences serious lag when i move away from it. Are there any perfomance mods that can increase my FPS with this mod?

https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance119.md
