### ISSUE TITLE
Floating items travel at speed of light when pulled via fishing rod

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1223]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.1.9.4

**Mod version**
3.2.1.3

**Describe the bug**
Up here, user.

**To Reproduce**
1. summon symbiont
2. kill him
3. pull the floating book via fishing rod (same with WS star)

**Is OptiFine installed?**
N/A

**Screenshots**
SOON, but i dont really think the screenshots are needed here

**Comment by nonamecrackers2** [comment]
Appears to just be basic vanilla behavior. Nothing I can/should really fix here. Just don't use a fishing rod on the command block book I guess?
