### ISSUE TITLE
Distant wither storm sounds

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1225]
basically if you are far away and the storm is spawned you would hear some ws sounds and the bigger it gets the further you can hear it
something that tainted did >:/ i even wanted to ask crackers if this is normal and if i didnt install a illegal version or sum shit however good suggestion to scare people

**Comment by TaintedBlock** [comment]
:0

**Comment by BluePineappleGuy** [comment]
distant ambient sounds already exist in the mod tho

also pls dont swear, there may be kids on here

**Comment by Pandaboi25x** [comment]
> distant ambient sounds already exist in the mod tho
> 
> also pls dont swear, there may be kids on here

Like i mean from around 1000 or 500 blocks away

**Comment by Pandaboi25x** [comment]
When its in phase 0-3 it makes the roars echo

**Comment by LegendaryGodzilla** [comment]
> > distant ambient sounds already exist in the mod tho
> > also pls dont swear, there may be kids on here
> 
> Like i mean from around 1000 or 500 blocks away

we need disssssssssss

**Comment by Steve982950** [comment]
This i believe already exists. When the WS is approaching, a sound called ''Witherstorm Ambience'' plays & repeats

**Comment by Steve982950** [comment]
btw..... #1224 !

**Comment by Pandaboi25x** [comment]
We did it at the same time

**Comment by Pandaboi25x** [comment]
> This i believe already exists. When the WS is approaching, a sound called ''Witherstorm Ambience'' plays & repeats

And its not thatwhen you are far from the ws that is phase 0 like around 500 blocks it would make an echo roar just like it has in the bowels

**Comment by Steve982950** [comment]
so the issues seem similar but are actually different?

**Comment by Pandaboi25x** [comment]
> so the issues seem similar but are actually different?

no they are both the same and suggested at the same time

**Comment by Steve982950** [comment]
ok so technically a Duplicate

**Comment by nonamecrackers2** [comment]
Yeah technically is

**Comment by Pandaboi25x** [comment]
> ok so technically a Duplicate

Same time bud *same time* how can it be a duplicate if we did it at the same time by accident

**Comment by Steve982950** [comment]
duplicate means more than 1. lol

**Comment by Pandaboi25x** [comment]
> duplicate means more than 1. lol

well duh i know

**Comment by Pandaboi25x** [comment]
but why is it a duplicate anyways if it was reported at the SAME time, doesnt that mean both are

**Comment by Pandaboi25x** [comment]
oh well even if its closed as a ***duplicate***- we might get it anyways

**Comment by nonamecrackers2** [comment]
Yeah it’s not intentional but we don’t need two for the same idea if that makes sense

**Comment by Pandaboi25x** [comment]
> Yeah it’s not intentional but we don’t need two for the same idea if that makes sense

yeaaa i kinda overreacted there- sorry

**Comment by nonamecrackers2** [comment]
It's okay
