### ISSUE TITLE
Storymode Armours

### ISSUE THREAD

**Issue by TeutonicGrandMaster** [nonamecrackers2/crackers-wither-storm-mod#1227]
I would like to have the original storymode armours added to the mod to like add more immersion into the game they could be either craftable or found but the armours could make you a bit more immune to wither attacks (sorry i didnt explain well)

**Comment by TaintedBlock** [comment]
There are mods for this already

**Comment by GrandmaPork** [comment]
This is out of scope for this mod #191
Please close

**Comment by GearsawStudios** [comment]
> I would like to have the original storymode armours added to the mod to like add more immersion into the game they could be either craftable or found but the armours could make you a bit more immune to wither attacks (sorry i didnt explain well)

https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/91 Please read the Guidelines before posting

**Comment by Steve982950** [comment]
A: u can install a mod of this,
B: Duplicate #91
C: Not supposed to be 1:1 accurate to MCSM

**Comment by Steve982950** [comment]
not 910
