### ISSUE TITLE
Issues with AtrributeModifier

### ISSUE THREAD

**Issue by goldennightcore** [nonamecrackers2/crackers-wither-storm-mod#1228]
**Minecraft  #version**
1.19.4

**Mod version**
1.19.4.3.2.1.2
April 1 2023

**Describe the bug**
AttributeModifier doesn't apply after reloading a world.

Applies to all versions *1.19.4,1.18.2,1.16.5* unsure if this is a issue on my side

**Is OptiFine installed?**
No

**Video**

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128508428/f43963fc-150d-4e68-a0fb-da506b7067af

**Comment by nonamecrackers2** [comment]
Your video didn’t really show anything, I was expecting you to go back to the config menu to show that it wasn’t saved.

**Comment by goldennightcore** [comment]
Sorry, I will redo the video when I have time.

**Comment by goldennightcore** [comment]
[New video.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/11737160/New.video.zip)
Sorry about the strange way this was uploaded, video was too long to be able to be put onto github normally.

To explain it simply, when I use the config menu on world settings and set the attribute modifier, but after saving and exiting, the settings arent applied properly.

**Comment by nonamecrackers2** [comment]
Sorry for the late response, I meant to get back to you but since I was on mobile I couldn't watch the video.

Your video still doesn't show you going back into the config menu to show that the value wasn't saved/applied correctly.

**Comment by goldennightcore** [comment]
The video was meant to show how when the config is set, but when reloading to apply the config, the config doesnt seem to apply while the menu says otherwise, 

This may be an issue on my end, but I'm not sure.
*Also its completely fine.*

**Comment by BluePineappleGuy** [comment]
> This may be an issue on my end, but I'm not sure. _Also its completely fine._

its not just an issue on your end. i also have the same issue.

**Comment by nonamecrackers2** [comment]
If you try summoning a new wither storm with the config value set to what you want, does it appear to work then?

**Comment by goldennightcore** [comment]
I have actually tried this before, it didn't seem to work.

**Comment by nonamecrackers2** [comment]
Alright I will investigate then
