### ISSUE TITLE
Wither storm not evolving past destroyer

### ISSUE THREAD

**Issue by goldennightcore** [nonamecrackers2/crackers-wither-storm-mod#1229]
Minecraft #version
1.19.4

Mod version
1.19.4.3.2.1.2
April 1 2023

Describe the bug
Wither storm doesnt evolve after destroyer

Is OptiFine installed?
No

**Screenshots**
Unable to replicate

**Comment by LocalWaterCreeper911911** [comment]
it could take a long time for the storm to evolve into phase 5, its not a bug

**Comment by goldennightcore** [comment]
By this, I mean like around 2 hours of game time.

**Comment by IndigoAmethyst** [comment]
It takes a while for it to go past Phase 4

**Comment by goldennightcore** [comment]
I'm currently busy right now but when I get the chance I will run a test to see how long it takes from phase 4 to phase 5.

let it run for 3 hours, still no result

**Comment by goldennightcore** [comment]
still no result after 8 hours

**Comment by nonamecrackers2** [comment]
Is mob griefing disabled? What phase is it at now?

**Comment by goldennightcore** [comment]
No progress has been shown, but the storm is remaining at destroyer with mob griefing active.

**Comment by nonamecrackers2** [comment]
Oh yeah I misread, thought you were saying it wasn’t evolving to destroyer, which is my bad. I’ll try to investigate further.

Oh and do you have any other mods enabled?

**Comment by goldennightcore** [comment]
Sorry for late comment, only mods active were rubidium and oculus

**Comment by nonamecrackers2** [comment]
Alright, I’ll see what I can do then (and no worries)

**Comment by goldennightcore** [comment]
Issue seemed to have fixed itself after redownloading some of the files from the mod, so the issue is now fixed.
