### ISSUE TITLE
[Spawn consumed mobs on death and when playing dead] mob consumption revamp

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#123]
instead of the wither storm killing the mob that gets pulled in, i recommend making the mob fade as it gets pulled into the wither storm, which then makes them go inside the wither storm, but they dont die. What i recommend doing is teleporting the mobs into either the bowels or a pocket dimension, and then 75% of them are dropped out when the wither storm is "killed" by the formidibomb, while the rest being freed when the wither storm actually dies. also make this with stage 4 and up, instead of stage 2 or 3, as it wouldnt make much sense

**Comment by nonamecrackers2** [comment]
This could be interesting. I think the ones picked up with tractor beams should be eaten, but if all the heads have targets then other mobs could be picked up like block clusters, then when the wither storm plays dead is could respawn a random amount near itself.

**Comment by GrandmaPork** [comment]
those mobs could also be given slowness and weakness effect for a configurable amount of time

**Comment by Asteroid4** [comment]
> those mobs could also be given slowness and weakness effect for a configurable amount of time

Or...
What if the mobs forgot their normal AI? they would become neutral mobs until they die or the wither storm dies.

**Comment by nonamecrackers2** [comment]
Mobs will fade when being consumed, and pets will revive after the Wither Storm has been formidibombed/killed in the next major release.
