### ISSUE TITLE
Custom Amulet Combinations 

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1231]
What if you could use different minerals when crafting a Amulet to make different colour and glow combinations, similar to how the Decorated Pot currently works in 1.20. You could customise a Amulet even more that way, so they can be more unique. This could also include more materials being used such as Copper, Coal, Echo Shards, Quartz, Netherite, Gold, Amethyst, End Stone, Magma, ect

Also if you want to go further, the Wither Storm will only be tracked by (and tracking) the holder of an Amulet if it is in the current combination (the Order of the Stone's colors).

**Comment by TaintedBlock** [comment]
This should more likely be a config option to change the colors. Not a crafting recipe.

**Comment by IndigoAmethyst** [comment]
But then Amulets can't be unique

**Comment by nonamecrackers2** [comment]
This kind of goes out of scope for the mod, but is an interesting idea.
