### ISSUE TITLE
remove mod from world

### ISSUE THREAD

**Issue by strikoe** [nonamecrackers2/crackers-wither-storm-mod#1232]
edit resolved
**_used NBTExplorer to remove every file made by cracker wither storm from world, sorry im stupid._**

{i accidentally opened my survival world with this mod on forge,
and now i can't open this world on vanilla minecraft, it says:
Errors in currently selected datapacks prevented the world from loading
you can either try to load it with only the vanilla data pack ("safe mode"), or go
back to the title screen and fix it manually,}**_**

**Comment by Bloxxify1520** [comment]
? This doesent make much sense, can you explain in more detail?

**Comment by Steve982950** [comment]
Please fill out the template
