### ISSUE TITLE
[Just a question, not a suggestion/bug report..] @nonamecrackers2, when will 1.20 mod version release? 

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1233]
@nonamecrackers2 when will 1.20 mod version release? (again no one else comment but crackers.)

**Comment by Steve982950** [comment]
if not confirmed yet, then tell me

**Comment by goldennightcore** [comment]
He usually says he has no planned dates for versions, they just come when they come

**Comment by nonamecrackers2** [comment]
Please do not open issues to ask questions, this is not the place.

1.20 will come when it comes.

**Comment by Steve982950** [comment]
oh sorry

**Comment by Steve982950** [comment]
sorry im just very eager for updates lol

**Comment by nonamecrackers2** [comment]
It’s alright. Mod developers get a lot of “when are you updating to <version>”, and because they usually only make mods as a hobby, they don’t usually have a date for when updates come. Just something to keep that in mind.

**Comment by Steve982950** [comment]
ok
