### ISSUE TITLE
Newer mod version for 1.16

### ISSUE THREAD

**Issue by stupiditzz** [nonamecrackers2/crackers-wither-storm-mod#1235]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Is it possible that the newer mod version with a lot of new stuff, be made for 1.16? The main reason I'm suggesting it is because I like this mod and my pc is trash af and lags a lot in 1.19/1.18

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Bloxxify1520** [comment]
1.16.5 and anything below has already been confirmed Numerous times That it will Not be getting a port.

**Comment by ROBOY6321** [comment]
> 1.16.5 and anything below has already been confirmed Numerous times That it will Not be getting a port.

yeah

**Comment by FrozenDragon0** [comment]
1.16.5 is no longer supported apart from bug fixes.

**Comment by stupiditzz** [comment]
ok how do i unopen this

**Comment by nonamecrackers2** [comment]
Yeah as others said 1.16.5 is no longer supported. It would be awesome to have all the features but it would take a lot of time to port them to a version with major code differences.
