### ISSUE TITLE
Bowels Config

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1236]
A config that enables and disables the bowels. If disabled, players won't be able to enter the bowels.

The reason I am suggesting this is that on one of my servers, we have agreed that it will open when the majority of us can play it, however there is no way to properly close it. So I would appreciate it if you add a config to disable it.

**Comment by LocalWaterCreeper911911** [comment]
> A config that enables and disables the bowels. If disabled, players won't be able to enter the bowels.
> 
> The reason I am suggesting this is that on one of my servers, we have agreed that it will open when the majority of us can play it, however there is no way to properly close it. So I would appreciate it if you add a config to disable it.

`/witherstormmod ConsumedEntities set @e[type:witherstormmod:wither_storm,limit=1] 0`

This command automatically closes bowels hole iirc.

**Comment by nonamecrackers2** [comment]
> > A config that enables and disables the bowels. If disabled, players won't be able to enter the bowels.
> > The reason I am suggesting this is that on one of my servers, we have agreed that it will open when the majority of us can play it, however there is no way to properly close it. So I would appreciate it if you add a config to disable it.
> 
> `/witherstormmod ConsumedEntities set @e[type:witherstormmod:wither_storm,limit=1] 0`
> 
> This command automatically closes bowels hole iirc.

I believe that won’t worked in all cases, as in some instances it is forced open (such as when you have a command block took the hole with automatically open after a specific period of time)

**Comment by IndigoAmethyst** [comment]
Yea I was thinking that

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
