### ISSUE TITLE
Game crash after summoning wither storm

### ISSUE THREAD

**Issue by mirekfajny** [nonamecrackers2/crackers-wither-storm-mod#1237]
**Minecraft version** 1.19.4

**Mod version** 1.19.4

**Describe the bug** so everytime i try to summon the wither storm its normal but when it loads after 50 sec game crashes

**To Reproduce**
open wither storm mod 
summon wither storm
wait for it to load
crash

**Crash Reports / Logs**
yes

**Is OptiFine installed?**
yes

**Screenshots**
no

**Comment by TaintedBlock** [comment]
it may be because of optifine. CWSM and Optifine do not work well with eachother.

**Comment by nonamecrackers2** [comment]
Mind sending the crash report? Btw it’s not a yes or no question lol

**Comment by mirekfajny** [comment]
Thanks for trying to help but somone already told me what was the problem
it was optifine

wt., 20 cze 2023, 18:38 użytkownik nonamecrackers2 ***@***.***>
napisał:
