### ISSUE TITLE
No Chromatic Aberration

### ISSUE THREAD

**Issue by TheRealVortex** [nonamecrackers2/crackers-wither-storm-mod#1238]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
No chromatic Aberration when Detonating or Placing Formidi-Bomb

**To Reproduce**
Sadly, but no idea

**Crash Reports / Logs**
None

**Is OptiFine installed?**
Yes

**Screenshots**
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/137203754/1b1f3458-78fe-4e59-a961-8e64f8bc31ce)
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/137203754/fef962f5-b2af-4fa4-93ed-e24089926068)
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/137203754/2db9d4bb-0500-4a58-8d46-cc196288343c)

**Comment by TheRealVortex** [comment]
There is no CA effect on hand on both screenshots, Im playing on server

**Comment by watersofnazareth** [comment]
This is likely due to Optifine

**Comment by nonamecrackers2** [comment]
Try removing optifine and see if the problem persists

**Comment by nonamecrackers2** [comment]
Closing until more information is given
