### ISSUE TITLE
Turning Command Block Weapon to Netherite

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#1239]
Small request but can you add the ability to turn the command block weapon into netherite so that it can be more OP and can fit with out netherite drip? It makes sense since the weapon is already made of diamond just has the power of the command block.

**Comment by watersofnazareth** [comment]
Please read the duplicates before you make a suggestion

**Comment by TaintedBlock** [comment]
You could also install the mod that allows this. More command block tools I think its called.

**Comment by Resuster** [comment]
Oh alr, thx
