### ISSUE TITLE
playing dead/stage 6 model doesnt make sense

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#124]
I noticed the 2 massive chunks that come off the wither storm(the segments) are really high up, instead of at the real head locations. is there any way you can fix this by putting those holes in the correct spot?

**Comment by nonamecrackers2** [comment]
It’s not really realistic (I noticed that as well) however I personally like the dismantled phase 6 model and remaking it would take some time, especially for something I don’t think the majority of the playerbase would notice.
