### ISSUE TITLE
Heads & Beams Move “Smoother”

### ISSUE THREAD

**Issue by Bloxxify1520** [nonamecrackers2/crackers-wither-storm-mod#1241]
**Description of feature**
The heads and tractor beams that currently are in this mod are “snappy” when they move. As in, when the beam finds a player, it immediately snaps onto the player, or a mob as another example. Possibly would be better visually to make the storms heads move smoother.

**Comment by GrandmaPork** [comment]
Already been suggested

**Comment by BluePineappleGuy** [comment]
> Already been suggested

where tho

**Comment by nonamecrackers2** [comment]
Yeah #285
