### ISSUE TITLE
1.18.2 Pick Block not working as intended

### ISSUE THREAD

**Issue by Sam2451** [nonamecrackers2/crackers-wither-storm-mod#1242]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**: 1.18.2 Forge 40.2.9

**Mod version**: 2.2.1

**Describe the bug**:
When you use the pick block button in creative, the item you use it on gets duplicated instead of bringing the one you have in your inventory, in survivual doesn't work. The bug only occurs when this mod is installed, even by itself

**To Reproduce**:
Enter/Create a world where this mod is installed use the pick block key on a block , if you do it twice or more on the same block, the previous one is not selected, but a new one is created in the inventory (creative). In survival you do the same thing but with a block you already have in your inventory.

**Crash Reports / Logs**: Not provided

**Is OptiFine installed?**: No

**Screenshots**: Not provided

**Comment by Bloxxify1520** [comment]
What other mods are installed?

**Comment by Sam2451** [comment]
none

**Comment by Bloxxify1520** [comment]
Odd, usually other kinds of mods are responsible for this.

**Comment by Sam2451** [comment]
I specially tested it without mods

**Comment by Sam2451** [comment]
could be because of new version of forge?

**Comment by Bloxxify1520** [comment]
Ill check the changelog of forge.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release.
