### ISSUE TITLE
How do I craft the species locked Amulet?

### ISSUE THREAD

**Issue by AffyTaffy5** [nonamecrackers2/crackers-wither-storm-mod#1243]
just how???

**Comment by Bloxxify1520** [comment]
Use JEI. Its a mod that shows every block/item and the crafting recipe to it.
https://www.curseforge.com/minecraft/mc-mods/jei

**Comment by nonamecrackers2** [comment]
I can’t remember it off the top of my head but as blox said you can install JEI to show all the recipes. Also GitHub is for suggestions/bug reports, if you have any more questions I recommend join the discord server: https://discord.gg/W2f3DxR9pV
