### ISSUE TITLE
Tentacle starts dancing when its target is standing in specific proximity( AI bug )

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1244]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
T I T L E, tentacle constantly tries to attack player but fails cuz player isnt close enough

**To Reproduce**
1. summon tentacle
2. slowly sneak to him (shift + shield)
3. stop when you see error

**Is OptiFine installed?**
N/A

**Screenshots**
soon, work in progress

**Comment by LocalWaterCreeper911911** [comment]
IG this should be added to the guidelines

"Make sure to stay active and check comments under your issue, as mod creator may ask you some questions to get more information" or smth like that

many issues are closed because of that

**Comment by nonamecrackers2** [comment]
Could you send a video of the issue? Also could you please post the screenshots along with the issue instead of adding them in later that would be helpful

**Comment by nonamecrackers2** [comment]
Was unable to reproduce. Since creeper is banned they won't be able to reply with footage anyway
