### ISSUE TITLE
maybe add neck to witherstorm heads? (both ws and ws head entity)

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1245]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Currently, you can literally see everything through head mouth, which is strange                                                                                    
          (also, heads in mcsm have necks so thats the second reason)
![10](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129298645/287f081d-739d-4650-bff9-2c30e04cb83d)

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Steve982950** [comment]
I agree, this makes sense but idk if possible

**Comment by Tordx12881** [comment]
> I agree, this makes sense but idk if possible

everything is possible

**Comment by Steve982950** [comment]
> > I agree, this makes sense but idk if possible
> 
> everything is possible

OK! I never knew standing on CLOUDS was possible

**Comment by Tordx12881** [comment]
> > > I agree, this makes sense but idk if possible
> > 
> > 
> > everything is possible
> 
> OK! I never knew standing on CLOUDS was possible

You can stand in a cloud. Everything is possible dude

**Comment by LocalWaterCreeper911911** [comment]
> > > > I agree, this makes sense but idk if possible
> > > 
> > > 
> > > everything is possible
> > 
> > 
> > OK! I never knew standing on CLOUDS was possible
> 
> You can stand in a cloud. Everything is possible dude

Tordx using 0,00001% of his power:

**Comment by Steve982950** [comment]
..

**Comment by watersofnazareth** [comment]
As I said in Discord, the necks would look bad and would require us changing the models, which really isn't worth it especially since most Minecraft mods don't have necks it just looks wrong

**Comment by Pandaboi25x** [comment]
W

**Comment by LocalWaterCreeper911911** [comment]
> W

# W

**Comment by LocalWaterCreeper911911** [comment]
> As I said in Discord, the necks would look bad and would require us changing the models, which really isn't worth it especially since most Minecraft mods don't have necks it just looks wrong

# A

**Comment by Steve982950** [comment]
> > W
> 
> WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

bruh whats with the W's?
