### ISSUE TITLE
Make the withered beacon connections depend on the amulet inside the main beacon

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1246]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Basically, Wbeacon should only connect to Support beacon if its placed on the correct side
Red amulet color - redstone beacon
White amulet color - iron beacon
Green amulet color - emerald beacon
Cyan amulet color - diamond beacon,

otherwise it wouldnt connect to support beacons.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by watersofnazareth** [comment]
I believe this may confuse some if we did this, currently you can make wacky looking beacons if you want to

**Comment by LocalWaterCreeper911911** [comment]
> I believe this may confuse some if we did this, currently you can make wacky looking beacons if you want to

Forgot to mention this should be stated in the beacon gui

**Comment by MFNmodding** [comment]
maybe also have toggleable icons that have the color of the correct beacon in the correct direction. possibly an arrow. i know there's already a toggle for the thing that shows you the directions of the special effects (couldn't think of a way to describe it, just got over being sick and my brain isn't working right yet), so i know that it's an option.

**Comment by nonamecrackers2** [comment]
The connection may not be entirely obvious to players, and I think players should have the freedom to orient their support beacons how they choose (this would prevent setting them up in the same quadrant, at an angle, etc)
