### ISSUE TITLE
Command Block can be moved around with pistons

### ISSUE THREAD

**Issue by CubeGamer647** [nonamecrackers2/crackers-wither-storm-mod#1248]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
Applies to all versions it seems, but I'm using 3.2.1.3

**Describe the bug**
The command block inside the bowels can be pushed around with a piston, and when pushed into the pit, it will get teleported outside like any entity. This makes for some interesting behavior such as moving blocks it isn't supposed to and being able to kill the wither from long distances or outside. The boss fight behaves normally, as it will spawn mobs. It will skip phase 3's heads however because it can't detect any.

I should also mention the command block can be pushed while it's playing dead, but after a certain distance it just wakes back up.
Edit/Update: If the command block dies while outside, and there is a player in the bowels, the player can remain in the bowels until they fall in the pit, at which point they will be sent to their spawn. I tested it with /kill but I would expect a player destroying it would have the same effect.

**To Reproduce**
1. Go into the bowels
2. Using pistons, push the command block and see result
3. For further results, push the command block into the pit and outside
4. Destroy command block and see result

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
No

**Screenshots**
![2023-06-26_09 01 48](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/100244632/ab6d05da-10e2-489a-a423-9280ada1166f)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
