### ISSUE TITLE
New type of Table for 1.20.1 Version (when it releases)

### ISSUE THREAD

**Issue by Bloxxify1520** [nonamecrackers2/crackers-wither-storm-mod#1249]
**Description of feature**
For whenever the 1.20.1 version of this mod comes out, the usual way the command tool is crafted would have to be changed, to correspond with the new smithing table GUI. I think a new type of table to upgrade them into command tools could be made, maybe replacing the iron used to make a smithing table with diamonds.

Another thing i came up with is for some sickened mobs to have a (low) chance of dropping some type of “Tainted Diamond” or “Tainted Iron” that replaces the usual iron to make one.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by IndigoAmethyst** [comment]
#1139

**Comment by nonamecrackers2** [comment]
> #1139

This is not the same suggestion.

I kind of like the idea though, I have yet to figure out what would be the best replacement however.

**Comment by MFNmodding** [comment]
perhaps it could be crafted by surrounding a smithing table in withered/sickened items (the same tag as what you use to make golden apple stew) in a crafting table.

**Comment by BluePineappleGuy** [comment]
> perhaps it could be crafted by surrounding a smithing table in withered/sickened items (the same tag as what you use to make golden apple stew) in a crafting table.

or perhaps just a new smithing template.
could maybe have a 1% chance to drop when killing a sickened mob, or found in a new structure.

**Comment by MFNmodding** [comment]
or perhaps use the command block book AS the smithing template and use a sickened item as the upgrade item.

**Comment by zChenX1** [comment]
> > #1139
> 
> This is not the same suggestion.
> 
> I kind of like the idea though, I have yet to figure out what would be the best replacement however.

The Order Block Enchantment Book is the Forge template
Diamond or lapis lazuli as material?
I think the material should be easy to obtain, either in other dimensions or underground, and the speed of the Erstorm chase makes it difficult to collect the material when it is on the surface of the Overworld

**Comment by MFNmodding** [comment]
> 

perhaps redstone. kind of fits with the whole command block thing.

**Comment by nonamecrackers2** [comment]
Closing since command block tools are now crafted with the anvil
