### ISSUE TITLE
Witherstorm Boss Bar goes down to zero when Killed

### ISSUE THREAD

**Issue by TheEyeOfGaming** [nonamecrackers2/crackers-wither-storm-mod#1250]
**Description of feature**
The Witherstorms boss bar should get slowly drained to zero when death animation plays.
As it feels weird that the Boss Bar doesnt go down when the WitherStorm is dying.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
