### ISSUE TITLE
When WITHERSTORM is charging up, the bossbar should fill up, like a normal wither, but slower

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1251]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
When a regular wither is summoned, the bossbar fills up. can you make that happen to the storm when summoned?

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Steve982950** [comment]
If duplicate, Tell me

**Comment by nonamecrackers2** [comment]
#425

**Comment by Steve982950** [comment]
oh
