### ISSUE TITLE
Cannot Locate Wither Storm Spawn Platform

### ISSUE THREAD

**Issue by alexpatney** [nonamecrackers2/crackers-wither-storm-mod#1252]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.2

**Mod version**
3.1.1
**Describe the bug**
I had loaded in a modded world with a modpack, then later on added the Wither Storm Mod. And At X:0 Z:0 There was already a preexisting structure from the mod When Dungeons Arise. (Image Below Is at X:0 Z:0). And now the wither storm spawn platform cannot be found anywhere near

**To Reproduce**
idk

**Crash Reports / Logs**
None

**Is OptiFine installed?**
No

**Screenshots**
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/70240335/f2e64998-2f23-4850-9af4-43cc571e5290)

**Comment by Bloxxify1520** [comment]
The structure ONLY generates if the world is made with the mod, because the only place the structure will ever spawn is at 0, 0

**Comment by Bloxxify1520** [comment]
Probably should close this now that you know

**Comment by alexpatney** [comment]
ok thx
