### ISSUE TITLE
Have a command block constantly teleporting to original position just like shulkers

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1253]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
As i know of minecraft, thats the only way to make command block completely unmovable. Its self explanatory though.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
This could cause some lag and isn't a really good fix. A more proper one would be to prevent methods that could move it from working entirely.
