### ISSUE TITLE
witherstorms growth is inconsistent (before it explodes)

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1254]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4(all versions affected)

**Mod version**
3.2.1.3(all versions affected)

**Describe the bug**
looks like WS's growth code is stolen from normal wither cause it quickly grows for 10 seconds, but then stops growing.

**To Reproduce**
1. summon WS
2. see it growing for 10 seconds but then stop
3. See error

**Is OptiFine installed?**
No

**Screenshots**
yeah i know but soon

**Comment by LocalWaterCreeper911911** [comment]
GROWTH AHD EVOLUTION ARE NOT THE SAME THING

**Comment by LocalWaterCreeper911911** [comment]
also 10 seconds is spawn cooldown of normal wither so something aint right here

**Comment by nonamecrackers2** [comment]
Do you mean how the model scales when it's first summoned?

**Comment by LocalWaterCreeper911911** [comment]
> Do you mean how the model scales when it's first summoned?

yeah

**Comment by bruhicantlogin** [comment]
but the wither storm is supposed to be a normal wither that literally just changes as it grows, i don't see what do you mean

**Comment by BluePineappleGuy** [comment]
> but the wither storm is supposed to be a normal wither that literally just changes as it grows, i don't see what do you mean

he's saying that it stops 10 seconds in no matter the invulnerability time, where it should grow at a speed that matches the invulnerability time

**Comment by LocalWaterCreeper911911** [comment]
> > but the wither storm is supposed to be a normal wither that literally just changes as it grows, i don't see what do you mean
> 
> he's saying that it stops 10 seconds in no matter the invulnerability time, where it should grow at a speed that matches the invulnerability time

Yeah, exactly

**Comment by nonamecrackers2** [comment]
I don't really mind this and will be leaving it as is.
