### ISSUE TITLE
Cured sickened Villagers have special trades

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1255]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

Once you cure a Sickened Villager with a golden apple stew, the Villager should potentially have special trades added depending on its profession. for example a Mason could sell tainted stone, and the cleric could sell sickened mob drops like tainted rotten flesh or bones. I believe this would be a good way to add a way to get non-renewable or unobtainable items after the wither storm is defeated

**Comment by TaintedBlock** [comment]
not a bad idea..

**Comment by Aimyx** [comment]
gives a actually good reason for curing things

**Comment by BluePineappleGuy** [comment]
why is everything getting closed as completed

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
