### ISSUE TITLE
Wither Immune Armor

### ISSUE THREAD

**Issue by ISLANDBANE** [nonamecrackers2/crackers-wither-storm-mod#1259]
ok this may sound stupid, LIKE REALLLYY STUPID, but what about in mineshafts theres a chance you can find wither resistant armors that will make the witherstorm weaker to you (this armor could be turned off in world configs, but on by default) the armor will do the following:

* (Full Set Needed): Less damage from Withered Symbiont, Sickened mobs, and The Wither Storm heads.

* (Needs 2 pieces of armor): Slower tractor beam pulling, it pulls you up slower so you have a better shot of getting out

* (Needs 1 piece of armor): Higher wither sickness immunity.

I feel like this would be a way to help the people that are new to cwsm, and dont know how to play it yet, but the armor spawns would be rare, like finding diamonds close to the surface, I know this is stupid but its a concept i came up with, however, for it to be fair, it would give you no defense buffs, and when wearing with other sets, the wither immune effects will not apply, so you choose whether to be safe from the witherstorms army, or general mobs and other players. No inbetween. anyway just some silly idea I had for the mod, ill leave a concept sketch I made, but im bad at drawing so...
![witherarmor](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/116474402/1ccad56e-3d24-4049-a472-04ba340b527e)

**Comment by TaintedBlock** [comment]
No. This just makes things TOO easy imo

**Comment by ISLANDBANE** [comment]
> No. This just makes things TOO easy imo

understand, this would make the witherstorm too easy tho, unless you had to go through a whole cycle, like maybe you get this from combining bowels blocks into armor, which means you have to enter the bowels and resummon the storm all in 1 go for the armor to mean anything.

**Comment by nonamecrackers2** [comment]
I don't really want to add new armors/tools to the mod, and I don't feel there are players that especially need the extra help this set would provide. It is meant to be a challenge mod after all.

**Comment by ISLANDBANE** [comment]
> I don't really want to add new armors/tools to the mod, and I don't feel there are players that especially need the extra help this set would provide. It is meant to be a challenge mod after all.

yep, makes sense, figured it would be like that, mainly for removing most challenges in the mod (im still gonna try modding it in it with a seperate private mod im gonna make, if you allow private copys of stuff that changes stuff)

**Comment by nonamecrackers2** [comment]
Definitely if you want to please do!
