### ISSUE TITLE
Minecraft crashed after joining catcraft green realm

### ISSUE THREAD

**Issue by Minecraftplayer20** [nonamecrackers2/crackers-wither-storm-mod#1260]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.16.5

**Mod version**
1.0.3

**Describe the bug** 
I joined catcraft server and went to green realm and it crashed giving me an exit code -1 and this is the error 
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Tag 
witherstormmod:command_block_tools used before it was bound

**To Reproduce**
1. Go to 'multiplayer'
2. Click on 'catcraft'
3. Go to green realm

**Crash Reports / Logs**
latest.log: https://gist.github.com/Minecraftplayer20/fa601b7ae35faee903188287d5404fae

**Is OptiFine installed?**
Yes

**Screenshots**
![Screenshot (7)](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/106546611/8d08ce3a-2687-4aeb-8c3d-c6609926a956)

**Comment by nonamecrackers2** [comment]
You need Cracker's Wither Storm Mod on both the client and the server. You're trying to join a vanilla server with Cracker's Wither Storm Mod installed, which does not work.

**Comment by Minecraftplayer20** [comment]
> You need Cracker's Wither Storm Mod on both the client and the server. You're trying to join a vanilla server with Cracker's Wither Storm Mod installed, which does not work.

I have a question what if I disable the mod and dont load into my world that has crackers wither storm mod loaded I wont lose any data right?

**Comment by nonamecrackers2** [comment]
No as long as you don't load the world without it installed
