### ISSUE TITLE
Amulet painting texture inaccuracy

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1261]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on
1.19.4
**Mod version**
The version of the mod you are using
3.2.1.3
**Describe the bug**
The amulet painting's amulet is sideways and the red and green parts are swapped with eachother
**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
Specify if you're using OptiFine
no
**Screenshots**
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/106888663/0dbf0583-de0d-46b6-9450-c69431df59f7)
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/106888663/a4382338-2f3d-44a6-bc79-36096672e6b7)

**Comment by IndigoAmethyst** [comment]
I am pretty sure this is also a problem in Story Mode as well

**Comment by BluePineappleGuy** [comment]
this is actually an issue with the amulet texture, not the painting. the painting shows how the amulet was in MCSM, green on top, light blue on the right, red on bottom, white on the left, and blue in the middle.

**Comment by Nov1st2k10** [comment]
> this is actually an issue with the amulet texture, not the painting. the painting shows how the amulet was in MCSM, green on top, light blue on the right, red on bottom, white on the left, and blue in the middle. 

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/106888663/bacfa0c7-a6f1-4d79-ac90-44532fdd52fe)

even if it may be tilted the banner still has colors in wrong places

**Comment by BluePineappleGuy** [comment]
> even if it may be tilted the banner still has colors in wrong places

actually, the mods amulet is the one that has wrong colors. if you look at the amulet in the inventory in MCSM you'll notice it matches the painting

**Comment by Nov1st2k10** [comment]
> > even if it may be tilted the banner still has colors in wrong places
> 
> 
> 
> actually, the mods amulet is the one that has wrong colors. if you look at the amulet in the inventory in MCSM you'll notice it matches the painting

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/106888663/b417c56c-8e4f-46d1-b236-6fe2737331e1)
well yes but the texture was inaccurate to the model in the first place, mcsm is full of these kinds of inconsistencies 
(also the model i sent was from mcsm, not cwsm)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release, to match the CWSM item texture
