### ISSUE TITLE
Wither Skeletons

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#1262]
Since Wither Skeletons are the OG "withered" mobs, they should behave like other sickened mobs and shouldn't run away from the storm/shouldn't be targeted. Maybe they could also spawn in the bowels or could be summoned by the symbiont. I think it would be fitting, especially because in bedrock edition, the regular Wither spawns wither skeletons already.

**Comment by FrozenDragon0** [comment]
I guess it kinda makes sense, given the storm is literally summoned by using Wither skeleton heads.

**Comment by BluePineappleGuy** [comment]
same with the wither, it should be treated as a sickened mob and should not attack sickend mobs/wither storm and vice versa

**Comment by NinjaSam5399** [comment]
Yeah, it makes sense. And also a good idea to add.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
