### ISSUE TITLE
A fandom wiki

### ISSUE THREAD

**Issue by Zoande** [nonamecrackers2/crackers-wither-storm-mod#1263]
Description of feature
A wiki would be useful to be able to find out things
I think there wasn’t a point in making a wiki before but with the addition of the beacon I think it would be useful to for example have a fandom wiki.

**Comment by IndigoAmethyst** [comment]
I think I started working on one a while back but I can't find it

**Comment by Zoande** [comment]
If you can find it I would be happy helping you finish it!

**Comment by nonamecrackers2** [comment]
#622
