### ISSUE TITLE
Feature Request: Nether Interaction

### ISSUE THREAD

**Issue by ThatBigDerp** [nonamecrackers2/crackers-wither-storm-mod#1264]
Addition to https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/13
The wither storm doesn't simply break the portal [Even if he breaks it on the overworld side it would still stay active in the nether side], he grabs the different sides of the portal frame and expands it for his size when reach specific phase and players are in the nether. He enters the nether and chases the players while destroying everything in his way just as in the overworld. Also maybe he can break the nether roof because if some players are there and he is on the bottom side of the roof he wouldnt be able to reach them. When he kills the players he creates portal from  himself and returns to the overworld landing from the sky.

**Comment by FrozenDragon0** [comment]
This really isn't a good idea, the Nether is meant to be the one safe place you can go to without worrying about the storm, and having it following you through the nether would just make it extremely difficult to get anything done.

**Comment by TaintedBlock** [comment]
As well as annoying because all you hear is explosions

**Comment by nonamecrackers2** [comment]
Would be a lot of work to make it work properly, would also have a significant negative impact on progression since the nether is considered a "safe haven" when running from the storm and the location where get the ingredients to advance your playthrough.
