### ISSUE TITLE
Feature request: Spawner Interaction

### ISSUE THREAD

**Issue by ThatBigDerp** [nonamecrackers2/crackers-wither-storm-mod#1265]
If the Wither Storm grabs chunk with spawner, it will not get destroyed, the spawner will get corrupted and will start spawning corrupt monsters which he can use to attack you. After defeat the spawner will stay corrupted.

**Comment by nonamecrackers2** [comment]
This doesn't really make sense considering that the spawner would be the only block that would remain and not be picked up, and blocks around it would just phase through it when becoming a block cluster. Would also require a bit of work to create a new block for a feature that most players wouldn't really notice.

**Comment by ThatBigDerp** [comment]
I mean that the wither storm is grabbing the spawner and places it near the player he targeted and the spawner is spawning some corrupt monsters until you don't break it. It uses the spawner like some sort of attack to the player.
