### ISSUE TITLE
glitchy wither storm beam

### ISSUE THREAD

**Issue by Nandor21** [nonamecrackers2/crackers-wither-storm-mod#1268]
I encountered a bug in the 'Crackers Wither Storm' mod where the wither storm's beam or ray shifts away from its eye at 12,550,000 blocks in Minecraft version 1.19.4.

I created 2 screenshot for this bug:
![2023-07-06_20 18 40](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/107921437/5a5f32b5-96aa-4eda-b3da-add8fea9428e)
![2023-07-06_20 20 55](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/107921437/b0e62dd0-1dc1-4772-a00a-d28c3d53b72e)

**Comment by Steve982950** [comment]
Please fill out the template.

**Comment by BluePineappleGuy** [comment]
yea glitchy things happen in minecraft when that far away

**Comment by FrozenDragon0** [comment]
That's to be expected when your that far out, the game in general will start to glitch, this issue really isn't worth fixing anyway.

**Comment by nonamecrackers2** [comment]
Was able to reproduce but not sure how I can fix this. Found that this also applies to the debris rings as well. I doubt most players would encounter this issue though since getting that far out with the storm isn't something that'll be very common.

**Comment by CubeGamer647** [comment]
Not that this is important since it's creative only, but I've had this same issue when the wither storm is mounted on another mob.

**Comment by nonamecrackers2** [comment]
That could probably be fixed, I'd make another bug report for that
