### ISSUE TITLE
Improve Super TNT

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1269]
Currently, the Super TNT acts as a crafting ingredient only for the most part. There is no real reason to play around with it in creative as it acts as a TNT with max explosion radius from vanilla. To be honest, that's really boring for the mythical Formidibomb's main ingredient. It already has cool sounds and a nice texture, might as well give it a use to play around with in creative. No need for it to have a legitimate survival use outside of SMPs, just something simple.

Ideas for Improvements:

Give it a unique explosion shape, perhaps making tunnels on all sides of the block.

Add something unique to its crater, maybe even loot if need be. (Side effect of giving it a niche use in survival)

Disable the Wither Storm's head within a certain radius if it eats it, possibly setting off a distraction.

Adding an advancement for using it against the storm that taunts you for using the wrong item.

Adding a screen shader before it explodes, maybe a command block themed one similar to that of getting frozen in powder snow.

Naturally, some of these might be too much work or plain bad, but it could be looked into if changes are desired.

**Comment by BluePineappleGuy** [comment]
i also think the texture should be tweaked to match story mode a bit better, with the command-block colored fuse and text. it would make it look a bit more intimidating and a ton more epic

**Comment by GearsawStudios** [comment]
True, it's the build up to **The Formidibomb** which is kinda a big deal. Making it more intimidating would help the build up.

**Comment by BluePineappleGuy** [comment]
for the second idea, what if some blocks near the explosion (but the ones that didn't get broken) had a chance to randomize into another? of course, some blocks wouldn't appear (such as explosives, tainted blocks, and the new beacons).

**Comment by GearsawStudios** [comment]
> for the second idea, what if some blocks near the explosion (but the ones that didn't get broken) had a chance to randomize into another? of course, some blocks wouldn't appear (such as explosives, tainted blocks, and the new beacons).

Fantastic idea, gives it a use in late game survival by incentivizing blowing them up for rare blocks like gold or similar.

**Comment by nonamecrackers2** [comment]
Some of these ideas are neat but are quite niche. I don’t see the majority of the player base utilizing these features and the work to implement these would be tremendous. Thanks for your suggestions though.
