### ISSUE TITLE
[1.18] Blocks with over Obsidian hardness aren't grabbable by the Witherstorm or destroyed by the F-Bomb

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#127]
Things like Obsidian and Crying Obsidian aren't grabbable making it possible to make Obsidian bases or nether portal blocks end up being grabbed without the portal frame

**Comment by nonamecrackers2** [comment]
> nether portal blocks end up being grabbed without the portal frame

I'd recommend separating this into another issue so I can track both better

**Comment by watersofnazareth** [comment]
I was givin a example more than a second issue but I will make sure to do so!

**Comment by nonamecrackers2** [comment]
Oh I see now. My bad. You won’t need to

**Comment by nonamecrackers2** [comment]
Will be implemented in the next update.
