### ISSUE TITLE
wither storm shoots skulls at portals

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1270]
simple, instead of breaking it using a tentacle and also on the nether side, it should attempt to target nether portal blocks and break the frame to prevent players from escaping.

**Comment by nonamecrackers2** [comment]
This would be hard to pull off since it would require scanning a large are of blocks, which in my experience would be very impactful on the performance. It would also be difficult to get the heads to line up with the trajectory of a skull to a portal. Thanks for your suggestion though.

**Comment by BluePineappleGuy** [comment]
Maybe not so hard to get it to detect the portal, considering its a POI so piglins can avoid it, but scanning it in a large area constantly _would_ impact performance, so i understand why this isn't very feasible.

**Comment by BluePineappleGuy** [comment]
actually, what if it scanned the area near the player rather than near the storm, so it would only shoot if a player was attempting to enter and would require less scanning.

**Comment by nonamecrackers2** [comment]
That could work, but it’d still be fairly performant intensive
