### ISSUE TITLE
When tracking all players with an amulet it will only track the player that has the amulet

### ISSUE THREAD

**Issue by StellaBiscuit** [nonamecrackers2/crackers-wither-storm-mod#1271]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
When an amulet (the special version that makes the amulet track any entity of a certain type), if a player is tracked, it will always track the player holding the amulet since it is the closest

I feel like this is unintended and it would anyway be better to instead track the nearest player that isn't the owner of the amulet

**To Reproduce**
Craft an ender eye + chorus amulet
Track a player on multiplayer
The amulet will track the owner since it is the closest to the amulet

**Crash Reports / Logs**
None needed

**Is OptiFine installed?**
No

**Screenshots**
Can't make a screenshot right now

**Comment by watersofnazareth** [comment]
H-huh? What do you mean,

If all players have an amulet: It tracks the closest player
If one person has a amulet: It tracks that player
If no one has a amulet it defaults to closest player

Unless you mean using a upgraded amulet on a player, in which case it doesn't follow the people tracked it just tracks the player with the amulet

**Comment by nonamecrackers2** [comment]
Ah I see what they mean, when using the entity type tracking amulet and they make it track players it tracks themselves since they're the closest player technically.

Yeah this would be unintended and would need fixing.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
