### ISSUE TITLE
Wither Storm Segments Drop Remains when Dying

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1274]
It would be cool if the Segments dropped clusters of tainted blocks when dying, before falling down and evaporating. Simple as.

**Comment by nonamecrackers2** [comment]
I feel this should remain exclusive to the main Wither Storm since currently the segments don't have much mass to them, so dropping a bunch of clusters wouldn't make much sense.

**Comment by BluePineappleGuy** [comment]
maybe they could spawn 1 or 2 each?
