### ISSUE TITLE
Setting to turn off withered symbionte

### ISSUE THREAD

**Issue by HammedBurngur** [nonamecrackers2/crackers-wither-storm-mod#1276]
There should be a setting for turning off symbiote for creative worlds or rp

**Comment by Bloxxify1520** [comment]
Then how would people get the book/formidibomb/command tool?

**Comment by GearsawStudios** [comment]
> There should be a setting for turning off symbiote for creative worlds or rp

That already exists, check your settings when in world.

**Comment by CubeGamer647** [comment]
> Then how would people get the book/formidibomb/command tool?

That kind of gamerule isn't as much about progression as it is just debugging or restrictions. If I recall correctly, there's a setting that disables the bowels/hole completely. How do you suppose it be slayed then?
That aside, it could be a useful config for modpacks with other means of progression.

Edit: Okay, that gamerule doesn't actually exist except for when you disable structure generation entirely, but my point still stands.

**Comment by nonamecrackers2** [comment]
This option already exists in the server config
