### ISSUE TITLE
An option to change the position of the Phase 7 opening

### ISSUE THREAD

**Issue by Terraver** [nonamecrackers2/crackers-wither-storm-mod#1277]
This may be complicated to make, but I think what would be ideal is having an option for changing the position of the opening during Phase 7.

The default mode (CWSM) is the default position of the opening, and the MCSM mode changes it to be below the center Wither Storm's heads, as seen in EP4 of Season 1.

**Comment by TaintedBlock** [comment]
This wouldn't happen as there is no point.

**Comment by BluePineappleGuy** [comment]
while crackers has said no model changes (unless to fix issues), this would mean that the enderpearl crossbow isn't necessary and you can throw a regular pearl when you're close enough.

**Comment by nonamecrackers2** [comment]
#144
