### ISSUE TITLE
1.16.5 crash report

### ISSUE THREAD

**Issue by LocalWaterCreeper911911** [nonamecrackers2/crackers-wither-storm-mod#1278]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.16.5

**Mod version**
1.0.3

**Describe the bug**
ive set the debris cloud rendering to false, then created a new world, summoned the storm, realized that i turned off debris cloud, tried turning them on, but it didnt work. then i escaped to nether, died here, respawned and...
the storms debris rings turned into a bunch of missing textures overlapping each other.
i got closer, tried hitting his head and game crashed.

**To Reproduce**
1. read the text up here 
2. i was unable to reproduce this sh*t again, so
3. try to replicate this (might work in versions higher then 1.16.5)

**Crash Reports / Logs**
[crash-2023-07-14_14.05.04-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12048393/crash-2023-07-14_14.05.04-client.txt)

**Is OptiFine installed?**
No other mods installed

**Screenshots**
As i said, i was unable to replicate this again, sadly (for now)

**Comment by LocalWaterCreeper911911** [comment]
yay local is back with bug reports

**Comment by Nov1st2k10** [comment]
We don't help with pirated clients.

**Comment by LocalWaterCreeper911911** [comment]
> We don't help with pirated clients.

ok

**Comment by LocalWaterCreeper911911** [comment]
> We don't help with pirated clients.

wdym by help its a bug report

**Comment by Nov1st2k10** [comment]
You do use a pirated version of minecraft, which is illegal, plus 1.16.5 won't be receiving updates in the future, so it's likely this bug won't be patched

**Comment by nonamecrackers2** [comment]
Closing since local water creeper has now been blocked
