### ISSUE TITLE
Slight vanity request

### ISSUE THREAD

**Issue by Terraver** [nonamecrackers2/crackers-wither-storm-mod#1279]
It would be nice having the glow behind the Wither Storm have customizable colors instead of being a default dark purple.

**Comment by TaintedBlock** [comment]
Maybe you should look in the announcements

**Comment by Steve982950** [comment]
why are all ''confirmed'' labelled issues always customization options?

**Comment by Steve982950** [comment]
dont mean to be rude

**Comment by BluePineappleGuy** [comment]
> why are all ''confirmed'' labelled issues always customization options?

im guessing its because they're very easy to code most of the time

**Comment by BluePineappleGuy** [comment]
wait isnt this just #1028 or is this suggestion different

**Comment by Steve982950** [comment]
ok

**Comment by nonamecrackers2** [comment]
> wait isnt this just #1028 or is this suggestion different

Didn't notice that, thank you

**Comment by Steve982950** [comment]
'_'
