### ISSUE TITLE
Witherstorm segment unloads sometimes if the Witherstorm is speedy

### ISSUE THREAD

**Issue by ShirakiShio** [nonamecrackers2/crackers-wither-storm-mod#128]
![image](https://user-images.githubusercontent.com/48332495/175290339-bd669902-91d5-4e63-ac63-0280bfffb460.png)
![image](https://user-images.githubusercontent.com/48332495/175290353-a6a852e9-164b-4247-81ff-8730f38d0adc.png)
It does not re-appear until you reload the world.

**Comment by nonamecrackers2** [comment]
It may have gotten stuck behind a cliff or something. There is code that would teleport them back but it appears to not work properly.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update
