### ISSUE TITLE
temporary cure to wither sickness

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1280]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

One of the biggest issues i've had in a playthrough is not being able to get the resources for the golden apple stew, and i quickly succumb to wither sickness long before i craft the stew. I'm suggesting that a cheaper version of the golden apple stew is added, however this stew only regains a couple hearts and pushes back the symptoms of wither sickness for about 15-30 minutes, the recipe for this shouldn't require any tainted items, as it is a cheaper alternative to use while you gather the resources for the actual golden apple stew

**Comment by MFNmodding** [comment]
doesn't eating golden apples already do that? i remember that you can gain back hearts like that.

**Comment by BluePineappleGuy** [comment]
> doesn't eating golden apples already do that? i remember that you can gain back hearts like that.

no, it just gives you absorption hearts like normal. it doesn't really help to delay or prevent wither sickness as the sickness bypasses the absorption effect

**Comment by AlexLikeFoxes** [comment]
Golden apple stew does cure you, it just takes some time and cancels if you get exposed to the Wither's beam

**Comment by nonamecrackers2** [comment]
Closing in favor of #1346, will use this as a reference.
