### ISSUE TITLE
Make the wither storm slowly grow in pixels as it consumes more blocks

### ISSUE THREAD

**Issue by Bruce6131** [nonamecrackers2/crackers-wither-storm-mod#1281]
What if when the wither storm consumes a block of dirt of example it grows 16 pixels on the side it ate the dirt for smaller objects it could gain less pixels and for larger ones more pixels so in between stages there would be a seamless transition as it's pixels grow
I would love if you added this feature as it would be like a dream to have such a good wither storm

**Comment by MatthewMegapixel** [comment]
i wouldn't add pixel by pixel development of the wither storm, but i would add more subphases, for example between 3 and 4 there would be a subphase that would make it a bit bigger

**Comment by GearsawStudios** [comment]
Suggested often, already a side-mod WIP for this. Unfortunately, there is no feasible way to add this to the mod.

**Comment by Laikagor** [comment]
this would be too hard, since it would need like a 1000 models.

**Comment by Nov1st2k10** [comment]
this is a duplicate issue, this would take far too long to implement and wouldn't be worth the time

**Comment by Bruce6131** [comment]
> this would be too hard, since it would need like a 1000 models.

I was thinking it would be dynamic so no pre defined models it would generate them so every wither storm would look different

**Comment by Bruce6131** [comment]
> Suggested often, already a side-mod WIP for this. Unfortunately, there is no feasible way to add this to the mod.

What is the side mod called?

**Comment by GearsawStudios** [comment]
> > Suggested often, already a side-mod WIP for this. Unfortunately, there is no feasible way to add this to the mod.
> 
> What is the side mod called?

Sorry for late reply, it's not out yet. I don't know the name either but it's likely to be announced by Crackers when it releases.

**Comment by nonamecrackers2** [comment]
#1267
