### ISSUE TITLE
Make `/witherstormmod config server get` compatible with `/execute store`

### ISSUE THREAD

**Issue by sm644me** [nonamecrackers2/crackers-wither-storm-mod#1282]
Many commands give usable results with `/execute store`, such as `/scoreboard players get` or `/data get`. However, `/witherstormmod config server get` is only useful for the player to see what the config is set to, which can usually be done just by opening the config menu. Making this return a result would make it much more useful in datapacks, and it'd also be consistent with other commands. For clarity, `/execute store success` also doesn't work when trying to change config values, as it returns a 1 (meaning, success) even if the config command fails to change anything.

Of course, not all config settings are numbers, and numbers are all that `/execute store result` looks for. For settings like whether or not the Amulet target override should work (true or false) or what targeting mode the Wither Storm uses (a list of options), this would probably be more difficult to implement. Still, even just getting the config values that are just numbers compatible with `/execute store` would be very powerful and useful for making datapacks respond to the player's preferred config settings.

**Comment by Steve982950** [comment]
wow a suggestion INSTANTLY confirmed

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
