### ISSUE TITLE
Configurable Wither Storm colour

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1283]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
I think it would be nice to change colours of the Wither Storm

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by CubeGamer647** [comment]
You can make a resource pack.

**Comment by Nov1st2k10** [comment]
Texture packs can change the color very easily, i don't see why they should implement a config for this

**Comment by BluePineappleGuy** [comment]
what exactly do you mean by wither storm color? do you mean the mass, glow, or eyes?

**Comment by Steve982950** [comment]
> what exactly do you mean by wither storm color? do you mean the mass, glow, or eyes?

just mass

**Comment by nonamecrackers2** [comment]
That can be done with resource packs as others have already mentioned.

**Comment by Steve982950** [comment]
oh ok.
