### ISSUE TITLE
Chance of Wither Storm Picking the Player Up Slider Doesn't Work

### ISSUE THREAD

**Issue by Onemario1234** [nonamecrackers2/crackers-wither-storm-mod#1284]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
The slider that should adjust the chances of the Wither Storm picking me up isn't working. I set the chance to 0, and he still grabs me every time I try to leave my cave and enter its field of view. A Wither Symbiont spawned and I can't even fight it because I keep getting picked up and dying from the Wither Storm. (I'm aware I could be misunderstanding how it works, and if that's the case, please let me know)

**To Reproduce**
Let the Wither Storm progress in Phases
Set pickup chance to 0
Live in a cave like I do
Try to lave
Get picked up by Wither Storm every single time.

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
Nope

**Screenshots**
Not Needed.

**Comment by Steve982950** [comment]
I think 0 means he will pick you up A LOT more. maybe set the slider to 1.

**Comment by nonamecrackers2** [comment]
As sm644me said in the Discord:

> I can explain that one. The player pickup chance is actually the Wither Storm's chance to pick up the player compared to other available mobs. If nothing else is around for it to pick up, it'll always instantly target the player even if the chance is as low as possible.
