### ISSUE TITLE
Is the Wither Storm, Withered Symbiont, and the Sickened Mobs considered undead in-game and thus are damaged by the Instant Healing, healed by Instant Harming, unaffected by Poison and Regeneration, and ignored by the Wither?

### ISSUE THREAD

**Issue by anonymoususer923847** [nonamecrackers2/crackers-wither-storm-mod#1285]
Title.

**Comment by CubeGamer647** [comment]
You can test this yourself in-game, this isn't the place to post questions, but yes they are undead.

**Comment by GrandmaPork** [comment]
Join the discord for questions

**Comment by nonamecrackers2** [comment]
I replied to your question in the Discord:
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/105086648/b63d5e4b-d3c1-40d3-88eb-a58469a5e697)
