### ISSUE TITLE
Does not attack flying mobs from other mods (1.16.5 - 1.18.2)

### ISSUE THREAD

**Issue by Gaboamau** [nonamecrackers2/crackers-wither-storm-mod#129]
I've noticed that the Wither Storm doesn't attack flying mobs from other mods, like when I used the ice and fire mod for version 1.16.5, while the Wither Storm was in phase 4, one of the mobs called Amphithere was close to him and he wasn't absorbing him, what's more, the mob was attacking him and the Wither Storm didn't do anything. Another example is the Advent of Ascension mod for version 1.18.2, where the Wither Storm only attacks non-flying mobs. In short I would improve the hostility of the Wither Storm for flying mobs if possible.

**Comment by nonamecrackers2** [comment]
I've already attempted this, but their flying ability resists the tractor beam pull so they never get killed by the heads, and just results in weird behavior that I can't really control.
