### ISSUE TITLE
Wither Storm Death Improvements

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1290]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Version**
1.20/1.20.1

**Description of feature**
So when you kill the Wither Storm, tentacles and "dead" heads (heads with no tractor beam) should drop out of the body because it doesn't really make sense where the tentacles and heads go after the storm breaks up.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by TaintedBlock** [comment]
The heads and tentacles all get incinerated with the rest of the wither storm. The chunks are just the lucky parts that made it out

**Comment by Honey-Programming** [comment]
The chunks that come out are actually bowels flesh so it makes sense that bowels tentacles fall out

**Comment by Honey-Programming** [comment]
> The chunks that come out are actually bowels flesh so it makes sense that bowels tentacles fall out

also the heads

**Comment by TaintedBlock** [comment]
Like I said, they get destroyed wither the rest of the wither

**Comment by Honey-Programming** [comment]
> Like I said, they get destroyed wither the rest of the wither

Then how did so many tainted zombies and skeletons get out

**Comment by TaintedBlock** [comment]
Luck. Some didn't make it out.

**Comment by TaintedBlock** [comment]
most actually

**Comment by nonamecrackers2** [comment]
Actually, what much of use would they give? Deactivated heads can't be killed and so they'd just stay there forever. Even if they could be killed, what would they drop? Regardless I feel that they don't have a very good reason for them to drop from the Wither Storm besides it doesn't make sense for them to disappear.
