### ISSUE TITLE
Invulnerable Wither Storm

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1291]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
In phase 3 it looks like it already covered up the command block and I know this is a little like Minecraft Story Mode but healing potions still damage the command block and it makes no sense because the potion is just hitting obsidian but it still damages the Wither Storm.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by TaintedBlock** [comment]
Technically you'd be dead if you're close enough to do this so I wouldn't see why this would be fixed.

**Comment by Honey-Programming** [comment]
> Technically you'd be dead if you're close enough to do this so I wouldn't see why this would be fixed.

You could throw it when the head is sucking you up

**Comment by TaintedBlock** [comment]
Then there really wouldn't be a point in playing the mod in survival don't you think?

**Comment by TaintedBlock** [comment]
maybe it can be a creative item but not one you can find in survival. Tho I doubt it would be added either way

**Comment by TaintedBlock** [comment]
oops

wrong suggestion

**Comment by TaintedBlock** [comment]
lmao

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release
