### ISSUE TITLE
Some sort of way to defeat the Wither Storm in it's early stages

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1292]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
So in phase 0, 1 and 2 the command block is exposed so there should be a potion hidden around 50 blocks underground with a 0.0125% chance of spawning called the eraser potion and when you throw it DIRECTLY at the command block (hitting the head or back will do nothing) then the command block will crack fully and the Wither Storm will remain just floating there for about 1 second without the command block and then it will disappear with some death particles.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by TaintedBlock** [comment]
Should probably be a creative item. And if someone were to find it in survival it would ruin the whole point in playing the mod.

**Comment by FrozenDragon0** [comment]
If this was a thing then what would be the point of playing the mod in general?

**Comment by nonamecrackers2** [comment]
You're not supposed to kill the Wither Storm in it's early stages. You skip all the other phases and don't fully experience the mod. While it could be something for second playthroughs, I don't think it would see much use and wouldn't be worth adding in.
