### ISSUE TITLE
Wither Storm in it's first stage should be slightly bigger than the normal wither

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1293]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
So when you first summon wither storm it will appear like a normal wither but with a command block in it's rib cage but it should be slightly bigger.
**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
I think the size should remain as it is since there isn't much of a reason for it to be slightly larger. It'll also require repositioning the other head positions and main hitbox since the size increase would off-center them. Thanks for the suggestion as always though.
