### ISSUE TITLE
Ender Dragon breaks Hardened Flesh Blocks

### ISSUE THREAD

**Issue by YeetMaster6942** [nonamecrackers2/crackers-wither-storm-mod#1294]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2

**Mod version**
2.2.1

**Describe the bug**
The Ender Dragon is able to destroy Hardened Flesh Blocks by running into them. I am not sure if this is intentional or not but I think it is caused because the block is missing the "Dragon_Immune" attribute, allowing the dragon to break it.

**To Reproduce**
1. Go anywhere with Hardened Flesh Blocks (or spawn them in)
2. Summon a dragon near the Flesh Blocks
3. The Ender Dragon will break the blocks if it runs into them

**Is OptiFine installed?**
No

**Screenshots**
![2023-07-19_16 51 18](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/140018689/4e05d7fb-421e-498d-b804-f2043ffcf1d7)
![2023-07-19_16 51 35](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/140018689/23a47388-13ff-412b-afa0-da3ab9792b0c)
![2023-07-19_16 51 41](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/140018689/e65ae3ae-a84d-4f68-a6b8-cdd3998ace3c)

**Comment by TheEyeOfGaming** [comment]
Well this doesnt really matter, since the Enderdragon cant interact with the Hardened Flesh Blocks, since the WitherStorm is Overworld Exclusive (unless you spawn it in creative in the End).

**Comment by CubeGamer647** [comment]
Are we all ignoring the fact that you can bring the beacon to the end?

**Comment by nonamecrackers2** [comment]
Will be fixed in the upcoming 1.19.4/1.20.1 release.
