### ISSUE TITLE
[Warning to] enable flying on servers when installed

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1295]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

A big problem that has occurred throughout all of the ws servers that i'd played on, was being kicked from the game for flying when being picked up by the wither storm, it's always a hassle for the owners to go to the server management area or the console and enable the setting and restart the server just so we don't get kicked off the server all of the time. Having cwsm enable flying by default would greatly help these problems, if you're worried that some servers might want flying disabled, the mod could send all Operators a message about cwsm enabling flying the first time they log on. (also a lot of servers i play on are 1.18.2 so i would appreciate if this made it into 1.18)

**Comment by GrandmaPork** [comment]
Personally, I have never had an issue with going in and enabling flying. Also I believe support for 1.18 has been dropped

**Comment by Nov1st2k10** [comment]
> Personally, I have never had an issue with going in and enabling flying. Also I believe support for 1.18 has been dropped 

yeah, most of the cwsm servers i play on use 1.18.2 due to the vast variety of mods compared to 1.19.4, but i understand if it isn't added to 1.18.2, the main issue with flying i have is that most server owners completely forget about it and then they have to go enable it and restart while we're in the server

**Comment by nonamecrackers2** [comment]
I don't really want to mess with defaulting it to on since that could mess with things, however a warning that flying is not enabled could be added.

**Comment by Steve982950** [comment]
Pls hurry for 1.20.1 before 1.20.2 comes out!!!

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
