### ISSUE TITLE
WITHER STORM DESPAWNS?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1298]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4 forge

**Mod version**
3.2.1.3

**Describe the bug**
When i accidentally closed Minecraft in my Wither Storm survival world, I rejoin and the storm DESPAWNS?

**To Reproduce**
1. load up world with Wither Storm
2. Close minecraft whilst in the world
3. Reload the world
4. See ERROR

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
No

**Screenshots**
Unable to replicate

**Comment by IndigoAmethyst** [comment]
1. What other mods are you using?
2. How did you check if it was despawned? 
@Steve982950

**Comment by Steve982950** [comment]
@Demonmaster-MD  to answer question 1,
Witherstormmod
aether beta 5.1
worldedit 7.2.14
mob battle
to answer question 2,

I checked the distance, it wasnt there
i checked my amulet, ''Could not find nearby''

**Comment by IndigoAmethyst** [comment]
> @Demonmaster-MD to answer question 1, Witherstormmod aether beta 5.1 worldedit 7.2.14 mob battle to answer question 2,
> 
> I checked the distance, it wasnt there i checked my amulet, ''Could not find nearby''

Were you in the same dimension as the Wither Storm when you checked?

**Comment by Steve982950** [comment]
yes!

**Comment by ZiHerng** [comment]
The wither storm shook its head when I placed a formidibomb and lit it up.

**Comment by Steve982950** [comment]
so..?

**Comment by IndigoAmethyst** [comment]
> The wither storm shook its head when I placed a formidibomb and lit it up.

I don't understand how that is in any way relevant

**Comment by nonamecrackers2** [comment]
@Steve982950 Is this still reproducible? And if so, when the Wither Storm despawns, check `/witherstormmod chunks get` and send the results here.

**Comment by Steve982950** [comment]
Wither Storm Mod has 0 chunks out of 0 forced chunks loaded. Thats the result

**Comment by nonamecrackers2** [comment]
How do you close Minecraft by the way? Alt+F4? Exit to the main menu?

**Comment by Steve982950** [comment]
ALT+F4

**Comment by nonamecrackers2** [comment]
Does this still happen if you close the game by pausing it then saving and exiting?

**Comment by Steve982950** [comment]
no
Exiting the world manually does not despawn the WitherStorm. Only if you Alt+f4 whilst in the world

**Comment by nonamecrackers2** [comment]
I feel the world isn’t being saved properly then. This would either be a bug with vanilla or your operating system, since alt+f4-ing for me saves the world properly.

**Comment by Steve982950** [comment]
Mod List:
oculus
rubidium
worldedit
mobbattle
ferritecore
starlight

**Comment by Steve982950291** [comment]
also, IMPOSSIBLE! 


(this my alt)

**Comment by BluePineappleGuy** [comment]
> Mod List: oculus rubidium worldedit mobbattle ferritecore starlight

think u got the wrong issue

**Comment by Herobrine982950291** [comment]
i was just saying that mod list so Crackers can see what mod is causing the issue
