### ISSUE TITLE
Forge fails to launch minecraft with mod enabled

### ISSUE THREAD

**Issue by 4nademe** [nonamecrackers2/crackers-wither-storm-mod#1299]
When I launch minecraft from forge with the mod installed and only the mod installed, minecraft does not open and a crash report appears with the following: 
[hs_err_pid17420.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12142862/hs_err_pid17420.log)

I'm just about ready to toss in the towel and give up, but if anyone has suggestions to try I'll give it a go.

**Comment by Steve982950** [comment]
Please fill out the template.

that aside, what mods do you have?

**Comment by 4nademe** [comment]
Thank you for your help Steve982950, I've found the issue to my problem. It appears I had an incorrect version of forge alongside where my mods were meant to be placed.

**Comment by Steve982950** [comment]
no problem!
