### ISSUE TITLE
Feature Suggestion: Wither Storm breaking nether portals

### ISSUE THREAD

**Issue by GameDokter51** [nonamecrackers2/crackers-wither-storm-mod#13]
Suggestion: the wither storm should continue moving towards the nether portal once the player goes through it. Then, when it reaches the portal, it will send it's tentacle through and break the portal like in Minecraft: Story Mode. This means that players need to be careful to (a) bring obsidian with them when they enter the nether, and (b) make the portal as far from the wither storm as possible. Also, players *could* escape the nether if they get trapped there thanks to ruined portals.
Here is an example from Minecraft: Story Mode
https://m.youtube.com/watch?3980&v=4EG2up-jcKMt%3D&feature=youtu.be

**Comment by nonamecrackers2** [comment]
While this would be interesting there are multiple issues. Players would need to locate a ruined portal (which may take a lot of their time) and in my opinion would be a nuisance to them. It's also possible players could've entered the nether without a diamond pickaxe, or it could break while they're in the nether, etc. which would result in trying to get back to the nether almost impossible. Thanks for the suggestion though.

**Comment by TheSrBig** [comment]
You can make an option for this function
