### ISSUE TITLE
Make so wither storm don't grab grass blocks and blocks beneath it.

### ISSUE THREAD

**Issue by AlexLikeFoxes** [nonamecrackers2/crackers-wither-storm-mod#1300]
you could add a gamerule or config file to enable/disable the fact that the storm can pick up grass block(and water sources,too). it will still be able to destroy them with skulls.
In Minecraft Story mod, the wither never actually picked up grass blocks (I think...) Only destroyimg them with skulls.

**Comment by CubeGamer647** [comment]
1. Suggestions making the mod more accurate to mcsm will be ignored
2. Where would it get blocks then? It would evolve so much slower than it already does
3. There are tags in the datapack that modify what blocks can be moved by the wither storm.

**Comment by BluePineappleGuy** [comment]
it actually did, if you notice in the forest chase scene

**Comment by myron-obsolete-account** [comment]
> it actually did, if you notice in the forest chase scene

and it does a lot off camera because logically almost all spots are covered in grass right?
