### ISSUE TITLE
Killing the command block only kills the main part of the witherstorm

### ISSUE THREAD

**Issue by oulajuusola** [nonamecrackers2/crackers-wither-storm-mod#1301]
Minecraft version:1.18.2
mod version:witherstormmod-1.18.2-2.2.1.jar
so i killed the command block inside the WS with a command block tool and when i was teleported to the ground the 2 other parts stayed alive and continued consuming the world ALSO i didn't get the withered nether star
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/140114563/a9de661e-690d-4bed-a3e9-14fc3bcf5816)

**Comment by nonamecrackers2** [comment]
What other mods do you have installed?

**Comment by oulajuusola** [comment]
It started working. I have already sent a mod list in the discord server👍

la 29. heinäk. 2023 klo 1.31 nonamecrackers2 ***@***.***>
kirjoitti:

**Comment by nonamecrackers2** [comment]
Could you send it here though? And what was your fix?

**Comment by nonamecrackers2** [comment]
Closing until more information is given
