### ISSUE TITLE
Withered Sky

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1304]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
When the Wither storm reaches Evolution Phase 7, the sky should turn to a more Purple-ish colour.

Heres an example:
![Minecraft_ (version hidden from driver) 28_07_2023 12_11_57](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128298281/20612fce-a64f-4784-bf65-3a2405bcece4)

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Pandaboi25x** [comment]
darkened storm moment

**Comment by BluePineappleGuy** [comment]
i think something similar was suggested before, idk tho.
this would also fit more for a stage 8 of some sort, that if you didn't defeat the storm it would grow more and do this.

**Comment by Steve982950** [comment]
> i think something similar was suggested before, idk tho. this would also fit more for a stage 8 of some sort, that if you didn't defeat the storm it would grow more and do this.

and what issue might that be?

**Comment by NinjaSam5399** [comment]
Actually, the config for the sky is coming next update.

**Comment by Steve982950** [comment]
ok

**Comment by nonamecrackers2** [comment]
I've changed my mind, since a config is coming to modify the sky colors you'll be able to do this yourself.

**Comment by Steve982950** [comment]
c...
