### ISSUE TITLE
Health bar increases to be consistent with original wither

### ISSUE THREAD

**Issue by theemeraldsword85** [nonamecrackers2/crackers-wither-storm-mod#1306]
I think this might be what #1254 was trying to get after.

When a regular Wither is created, you have some time to get away/ prepare before it actually starts moving. The time you have left is shown by the health bar slowly increasing from zero. When the wither has full health, it explodes the surrounding area and starts attacking you.

When the Wither storm is created, you still have some time to get away, but the health bar doesn't show how much time you have left by increasing.

I thought it would be neat and also helpful to know how much time you have left before the Wither Storm starts its rampage.

Look at the health bar and notice how the wither spawns once it's fully increased.
https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114451543/ca0a20c6-d27b-4690-a4c1-1400e445a1b6

Look at how the wither storm's health bar is full but the wither storm not doing anything.
![2023-07-31_14 39 28](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114451543/e253f4a7-b109-417f-88ec-63e509da763c)

**Comment by theemeraldsword85** [comment]
For some reason it didn't like the video I took of the wither storm so I had to use a screenshot

**Comment by GoldSlimeling91** [comment]
pretty sure this was just confirmed in the teaser for Evolution, very nice

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
