### ISSUE TITLE
The bowels being an expansive dimension

### ISSUE THREAD

**Issue by WitherStormEnjoyer** [nonamecrackers2/crackers-wither-storm-mod#1307]
What if the bowels were an expansive dimension? maybe there could be living mobs in there, living in organs? like a stomach biome, filled with acid but with chunks of pristine blocks in there? or a nerve, with electric shocks and electron ore which can be used to craft wither electric armor? Or other biomes, like a heart with wither fluid, like a turbulent ocean? imagine the amount of stuff that would be possible in a expanive bowels dimension? it would even be livable?

**Comment by CubeGamer647** [comment]
I really do like this idea, but there can only be so much hammerspace. Where would all this extra space come from?

**Comment by WitherStormEnjoyer** [comment]
If hammerspace is storage space, then maybe from optimization, if its inside space, the bowels are bigger on the inside

**Comment by CubeGamer647** [comment]
The bowels are already larger on the inside, but what you're proposing would be thousands of blocks wide, if not even larger, and that just doesn't seem realistic.

**Comment by WitherStormEnjoyer** [comment]
Just load it like you would the overworld. random chunks. like the nether. its a dimension.

**Comment by Steve982950** [comment]
Geez you dont have to shout

**Comment by nonamecrackers2** [comment]
This kind of expands beyond the scope of the mod. Besides if it was an expansive dimension that'd make less sense since it'd be theoretically infinite. Interesting idea though.

**Comment by Luke7381** [comment]
> This kind of expands beyond the scope of the mod. Besides if it was an expansive dimension that'd make less sense since it'd be theoretically infinite. Interesting idea though.

Actually since the wither storm could theoretically have a unlimited size this isn't to out of the question but yeah this probably wouldn't fit.

**Comment by BluePineappleGuy** [comment]
some sort of addon that would add this would be awesome, and bonus points if there's a new stage that allows you to access it
