### ISSUE TITLE
Toggle Patreon cosmetic in the "Player Customization" menu

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1309]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**
Be able to enable/disable the patreon cosmetic in settings

**Comment by IndigoAmethyst** [comment]
Would be handy for cinematics and lore

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
