### ISSUE TITLE
Auto-Disable of Spawn House

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1314]
If the mod 'Command Block Ascension' is installed in a modpack, the witherstormmod should Auto-Disable the House, cuz you can craft the Command Block anyways.

**Comment by CubeGamer647** [comment]
That would be the responsibility of the CBA developer. You can install the mod that disables the house spawn in the meantime.

**Comment by FalconinVoid** [comment]
I always installed all the mods on the server first and the Wither Storm Mod after loading X-0 Z-0. But how is the mod called so I can install it on later projects?

**Comment by CubeGamer647** [comment]
[No Rundown House](https://www.curseforge.com/minecraft/customization/no-rundown-house)

**Comment by nonamecrackers2** [comment]
As CubeGamer647 said, this would be something Command Block Ascension would have to do. You can also the no rundown house datapack Cube linked above to disable it as well.
