### ISSUE TITLE
Music isn't playing.

### ISSUE THREAD

**Issue by BlueCrayFish21** [nonamecrackers2/crackers-wither-storm-mod#1315]
Hello. For some reason, Wither Storm music wasn't playing. I had my master volume and music to 100%, but it still didn't play music. What happened?

**Comment by Steve982950** [comment]
Please fill out the template.

Btw check the Client Config.
Are options 'Play Wither Storm theme' and 'Play Symbiont theme enabled?

**Comment by nonamecrackers2** [comment]
In the client config (Options > Purple "W" > Client) enable "Play Wither Storm Theme" or "Play Boss Themes" (depends on the version of the mod, which you didn't specify by not filling out the template)
