### ISSUE TITLE
Formidibomb will sometimes crash the game when exploding.

### ISSUE THREAD

**Issue by MagmaSlime123** [nonamecrackers2/crackers-wither-storm-mod#1316]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.2.

**Mod version**
3.1.1.1.

**Describe the bug**
Formidibombs will crash the game upon exploding sometimes.

**To Reproduce**
Light a Formodibomb and wait for it to explode. The game should crash randomly.

**Crash Reports / Logs**
https://pastebin.com/8eqh54hv
This mod is mentioned all over the report.
If I'm blind and somehow some other mod is being stupid, please let me know.

**Is OptiFine installed?**
No.

**Screenshots**
N/A.

**Comment by Steve982950** [comment]
what is your mod list?

**Comment by MagmaSlime123** [comment]
Crash reports contain the current list of mods. Thank Forge for that.

**Comment by nonamecrackers2** [comment]
The crash report you sent isn't related to the formidibomb (possibly the wrong one?) but if it isn't, this is just a weird Minecraft bug with flat worlds and custom dimensions. All you'll need to do is reload your world and you should be fine.

**Comment by MagmaSlime123** [comment]
Well, your mod is mentioned all over the report. So I doubt its some other mod doing something.

**Comment by nonamecrackers2** [comment]
That's not what I'm saying. The formidibomb is not mentioned in the report, I didn't say anything about other mods causing the issue

What's being described in the crash report is a bug with vanilla flat worlds, it causes modded dimensions to not exist upon world creation (reloading the world fixes this issue). There's nothing I can really do to fix this.
