### ISSUE TITLE
Custom Bossbar (feel free to ignore..)

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1317]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
I think it would be nice to add a different bossbar rather than the bland one. Once again feel free to ignore lol

Example:
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128298281/86a0056c-4529-4014-a962-78a05626322b)

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by IndigoAmethyst** [comment]
https://www.curseforge.com/minecraft/texture-packs/enhanced-boss-bars


>

**Comment by IndigoAmethyst** [comment]
This already exists in that texture pack

**Comment by nonamecrackers2** [comment]
Considering a texture pack has already done this, I don't really feel the need to add a custom bossbar texture

**Comment by Steve982950** [comment]
GDI. ok
