### ISSUE TITLE
Been waiting for 2 hours, wither storm not evolving. Wither storm mod is the only mod i have and it's on max evolving speed

### ISSUE THREAD

**Issue by ReyTheDog** [nonamecrackers2/crackers-wither-storm-mod#1318]
Like I said, been waiting for 2 hours, and it's not evolving from the 4th phase
It's the only mod I have
Max evolving speed

**Comment by Steve982950** [comment]
Please fill out the template.
That aside, what option did u put the evolution speed to?

**Comment by ReyTheDog** [comment]
Maximum, he should be evolving fast

**Comment by CubeGamer647** [comment]
The higher the value, the slower it evolves. You'll want it on the lowest value.

**Comment by ReyTheDog** [comment]
I know that's what i did

**Comment by Steve982950** [comment]
try putting it to the lowest value - 0.1

**Comment by ReyTheDog** [comment]
> try putting it to the lowest value - 0.1

I already did that

**Comment by Composer-Hu** [comment]
If the configuration item is modified in purple W, you need to exit the game and re-enter the refresh to take effect.

**Comment by Steve982950** [comment]
this setting requires reload of WORLD

**Comment by watersofnazareth** [comment]
Can you give more info? Screenshots would help, but you can also do /data to get the ConsumedEntities or Phase value

**Comment by nonamecrackers2** [comment]
Yes, please fill out the entire report.

**Comment by Steve982950** [comment]
> Yes, please fill out the entire report.

Exactly what i said. ''Please fill out the template''

**Comment by nonamecrackers2** [comment]
Closing until more information is given

**Comment by Herobrine982950291** [comment]
Maybe tell us your RandomTickSpeed...

**Comment by nonamecrackers2** [comment]
Please don't necro old issues, they obviously aren't going to respond
