### ISSUE TITLE
Renaming Wither Skeleton Skull = renaming Wither Storm

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1319]
**Description of feature**
When you rename the wither skeleton skull before placing it on the command block, it would be cool if the Wither Storm would take the name from the skull, e.g. naming the skull Kevin results into the Wither Storm being named Kevin too.

**Comment by nonamecrackers2** [comment]
This would take some work to do for something most players probably wouldn't utilize. You can always make a name tag and immediately put it on the storm.
