### ISSUE TITLE
1. Wither Storm Phase 6/7 Giant Lag 2. Music not working sometimes

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#132]
1. So, when the wither storm reaches at Phase 6, it starts lagging a lot and sometimes crashes.
2. There is sometimes a giant lag spike when turns off the music of the wither storm for some reason.

**Comment by nonamecrackers2** [comment]
This looks like a hardware issue and is something I can't actually fix. I'd recommend turning on "Low Res Models" and disabling the debris cloud or turning on the setting that renders them 2D. You can refresh the sound loops that the mod uses by going to the client config and clicking "Refresh Sounds" in the top left corner.
