### ISSUE TITLE
More command weapon durability 

### ISSUE THREAD

**Issue by JaxHasHax** [nonamecrackers2/crackers-wither-storm-mod#1320]
Now think about this you spend all this time waiting for the wither storm to grow and then you have to wait for the mini boss to spawn then kill it for the book to drop as well as put it with a diamond weapon which is both time consuming and hard to do it wouldn’t hurt to add a few extra attack damage to the weapons maybe only like 7 or 8 more to the original to me it just makes the weapons feel only good for killing the wither storm like this thing can destroy a command block which is impossible without it.

**Comment by FrozenDragon0** [comment]
I disagree with this considering the fact the weapons are unbreakable and can be kept even after the storm is defeated, having them do more damage would just make them too overpowered as they also already have a damage boost.

**Comment by IndigoAmethyst** [comment]
This could be added, however considering how easy it is to get making it harder would probably change the progression too much in my opinion, so I am gonna have to agree with Frozen here. And besides, it is VERY OP especially when strength pots and enchants already exist.

**Comment by nonamecrackers2** [comment]
They already are unbreakable, I feel adding more attack damage would make them too overpowered.
