### ISSUE TITLE
Ivors house

### ISSUE THREAD

**Issue by JaxHasHax** [nonamecrackers2/crackers-wither-storm-mod#1321]
It would be cool to see ivors little house from the farlands. Now it would have a rare chance of spawning and it would include a few things like some tools and the possibles of the command book in a chest but the chances would be low and you would have to find it. And no there wouldn’t be a secret passage way since that’s to complicated to do. I just feel there should be more structures to explore and if you consider using my idea I would be honored to build the hut to save you trouble.

**Comment by TaintedBlock** [comment]
So basically make a structure that makes the symbiont and the grind for diamonds pointless. Great!

**Comment by GrandmaPork** [comment]
This would be better off in like a datapack

**Comment by nonamecrackers2** [comment]
I don't plan on adding other structures specifically from MCSM currently, and having the command block book in the structure has a small chance to mess up progression (such as a player could find it before the Wither Storm reaches the end of phase 5, make a formidibomb and blow it up on phase 4, which does nothing)
