### ISSUE TITLE
Have the ability to escape the tractor beam

### ISSUE THREAD

**Issue by JaxHasHax** [nonamecrackers2/crackers-wither-storm-mod#1322]
The tractor beams have a high chance to grab the player and I know there’s a setting for that but if you get grabbed with no bow and arrow your kinda screwed. So what if you could click shift or any button to slowly get out of the tractor beam or just use wasd and you don’t have to make it easy for the player either. P.s for those of you on discord spelling out stuff like kys or something just don’t you can just put thumbs down or say you don’t like it.

**Comment by TaintedBlockmObile** [comment]
Just.. don't get caught :trollface:

**Comment by JaxHasHax** [comment]
Just for clarification when you click shift or any button it will pull you a bit closer to ground but only if you have over 3 hunger bars. And if possible it would play the swimming animation for cooler effects

**Comment by nonamecrackers2** [comment]
I personally don't really like this, since it'd remove the threat of being caught by the tractor beams. As a side note, stuff is coming in the next update that'll make avoiding them a bit easier.
