### ISSUE TITLE
Can't manually spawn wither storm platform structure

### ISSUE THREAD

**Issue by RichPrune** [nonamecrackers2/crackers-wither-storm-mod#1323]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
forge 1.19.2
**Mod version**
latest

**Describe the bug**
So, when i try to spawn in the spawn platform structure, it says "failed to place structure". However, when I try to spawn in the bowels(the only other structure), it does work. This doesn't happen for any other structure from any other mod; so what gives?

**To Reproduce**
1. download witherstorm mod and (what i use to spawn in structures but you could also use a structure block) generation stages
2. Use a structure block or with gen stages type in /place structure witherstormmod:storm_spawn_platform
3. "failed to place structure"
4. nothing appears

**Crash Reports / Logs**
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12330177/latest.log)

**Is OptiFine installed?**
no

**Screenshots**
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103792572/797a4206-968e-4917-b93c-53f5fdfff6e2)

**Comment by RichPrune** [comment]
nvm thats the wrong crash report
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12330180/latest.log)

**Comment by RichPrune** [comment]
*i meant to say latest log

**Comment by nonamecrackers2** [comment]
This is intentional, the way the structure works makes it so it can only be spawned/placed at the 0, 0 chunk. There isn't a solid way to circumvent this currently, sorry.

**Comment by RichPrune** [comment]
is there a better way to summon the wither storm on my own terms? like lets say i give myself a command block in survival once i complete my modpacks progression; then how would i place it? do you have any ideas

**Comment by nonamecrackers2** [comment]
You should be able to place command blocks in survival, however you won't be able to break them.
