### ISSUE TITLE
Crash with ImprovedMobs

### ISSUE THREAD

**Issue by LMauc** [nonamecrackers2/crackers-wither-storm-mod#1324]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.2 - Forge 43.2.21 - (running java 17.0.8)

**Mod version**
3.1.1.1

**Describe the bug**
it crashes with a phantom or guardian as a mount

**To Reproduce**
I have a mod installed that alters the game, such as mobs riding on "Guardian" and "Phantom", among others, by the way, the mod is called "improvedmobs", however, disabling this sometimes fixes it completely, but the mod seems to have some bug, however the developers asked me to tell you the following  "check for phantom class and not phantom entity type"

**Crash Reports / Logs**
[crash-2023-08-14_18.06.05-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12339984/crash-2023-08-14_18.06.05-server.txt)

**Is OptiFine installed?**
No, Rubidium & Oculus

**Screenshots**
Nothing

**Comment by nonamecrackers2** [comment]
Will be fixed in future versions of the mod, since 1.19.2 is no longer supported.
