### ISSUE TITLE
Keep Inventory for CB tools

### ISSUE THREAD

**Issue by EarthKing339** [nonamecrackers2/crackers-wither-storm-mod#1327]
In my opinion, the command block tools are very special. I think, because of this, a feature should be implemented where in the event of the players death, they would still have the CB tool upon respawning. Ofc, if you add this, consider adding support for the gravestone type mods. It would be much appreciated.

**Comment by TaintedBlockmObile** [comment]
Idk how to feel about this one

**Comment by IndigoAmethyst** [comment]
I don't think KI is a good idea just as they are already unbreakable and it would be very bad in competitive multiplayer servers.
As it is, they are valuable which makes them something you have to try not to lose. Gonna have to see cracker's opinion on this though

**Comment by GearsawStudios** [comment]
This does solve a major issue in that if you lose it from dying, progression can be halted for a long time. Perhaps instead of keep inventory, it could never despawn and have the glowing effect so you can't lose it if you remember where you died.

**Comment by IndigoAmethyst** [comment]
Yeah I think that would be better

**Comment by nonamecrackers2** [comment]
Having them not despawn would be better. I do agree that they are special so you should protect them, having them stay with you forever kind of loses that determination to keep them safe. You’ll have to open a new suggestion for making them not despawn though.
