### ISSUE TITLE
Every time i try to launch the mod in curseforge it crashs with exit code 1 

### ISSUE THREAD

**Issue by Waspinator1999** [nonamecrackers2/crackers-wither-storm-mod#1328]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**
1. Go to 'curseforge'
2. Click on 'play on the mode'
3. Click play on the launch

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
Specify if you're using OptiFine

**Screenshots**

![Screenshot (27)](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/142454158/b25d93c1-a1a2-4e9f-a9f8-04ac4eeab050)

**Comment by watersofnazareth** [comment]
We need your crash log, Exit Code doesn't help

**Comment by nonamecrackers2** [comment]
Closing this issue, please fill out the bug report template

**Comment by IndigoAmethyst** [comment]
I have had this issue on a lower-spec computer before. Il try and replicate
