### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by ramacuw** [nonamecrackers2/crackers-wither-storm-mod#1329]
Are you going to port 3.2 to 1.19.2 because most mods do not support 1.19.4 or 1.19.3 that well please do if you can

**Comment by GearsawStudios** [comment]
> Are you going to port 3.2 to 1.19.2 because most mods do not support 1.19.4 or 1.19.3 that well please do if you can

He said no, also wrong place.

**Comment by ramacuw** [comment]
k
