### ISSUE TITLE
[Performance] Wither Storm Heads in Boss Fight tank FPS when you're around their mouth

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#133]
I dunno how to really write a description, it's a really weird issue causing a major performance drop in the fight when looking at the head near the mouth

**Comment by nonamecrackers2** [comment]
What version were you noticing this?

**Comment by nonamecrackers2** [comment]
Unable to reproduce. Closing this for now. Do you have any other mods installed?

**Comment by watersofnazareth** [comment]
It may be something with Radium
