### ISSUE TITLE
Command for the wither storm to go to specifics coordinates

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1330]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

Command for the WS to go to specific coordinates,
maybe something like
/witherstormmod goto (x) (z)

**Comment by TaintedBlockmObile** [comment]
This is already possible using the ultimate target command

**Comment by nonamecrackers2** [comment]
> This is already possible using the ultimate target command

Yep, “/witherstormmod ultimateTarget set <storm> <pos>”

**Comment by Nov1st2k10** [comment]
Do you mean like you can set make the Wither storm go to specific coordinates with the UltimateTarget command? or do you mean that it goes to the specific coordinates of that entity?

**Comment by nonamecrackers2** [comment]
You can make it to go to specific coordinates or an entity
