### ISSUE TITLE
CB tool idea

### ISSUE THREAD

**Issue by EarthKing339** [nonamecrackers2/crackers-wither-storm-mod#1331]
Add an enchantment called soulbound that can only be put on a CB tool. Whenever you die, you'll still have it on you. Same idea but different

**Comment by IndigoAmethyst** [comment]
That's a bit OP I reckon

**Comment by EarthKing339** [comment]
It'd be super hard to get. Maybe a secondary use for the corrupted nether star?

**Comment by nonamecrackers2** [comment]
I don't overly like the idea of adding new enchantments, especially since I'm pretty sure there is a mod out there that might already do this.
