### ISSUE TITLE
Amulet lights misplaced when held in left main hand

### ISSUE THREAD

**Issue by Laughingcat27** [nonamecrackers2/crackers-wither-storm-mod#1336]
**Minecraft Version**
1.19.4

**Mod Version**
3.2.1.3

**Bug Description**
If you have the left hand as the main hand, the amulet's lights will be misplaced

**To Reproduce**
1. Select the left hand as the main hand
2. Hold an amulet (either in main hand or offhand)

**Is OptiFine installed?**
No

**Screenshots**
https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/142660229/9ec8827e-00d9-4a00-a650-11def3ce4398

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 update

**Comment by Laughingcat27** [comment]
awesome, now us left handed people finally get equal rights
