### ISSUE TITLE
Music Change in later stages

### ISSUE THREAD

**Issue by TriniteTray** [nonamecrackers2/crackers-wither-storm-mod#1337]
so yea, i only suggested this for the atmosphere of the storm
Now what do i mean by music change?
look at this video. https://www.youtube.com/watch?v=WvZ3hwwRSkY
Example, when the wither storm has just spawned, he would play the theme from 0:00 to 4:01, 
in phase 5, he would play the theme from 2:24 to 4:01
In phase 6 and beyond he would play the theme from 4:01 to 8:05

and yes, this would be a togglable option in the settings, under "Music Theme Matches with phase" or something

i hope you were able to understand this and hope you consider this because i think it would go well with ambience of the increasing intensity of it slowly growing

**Comment by CubeGamer647** [comment]
I believe you're referring to dynamic music, which has already been confirmed for the next update.

**Comment by mythicplays** [comment]
I think at Phase 0-1 in the video link you sent, the theme will play from 0:00 - 0:48 then Phase 2, the theme will play from 0:48 - 1:36 then Phase 3, 1:36 - 2:24 then Phase 4, it will play the theme from 0:48 - 3:12 then Phase 5 will play the Theme from 2:24 - 4:01, Phase 6 will be 0:48 - 4:01 then Phase 7 2:24 - 8:05

**Comment by BluePineappleGuy** [comment]
> I think at Phase 0-1 in the video link you sent, the theme will play from 0:00 - 0:48 then Phase 2, the theme will play from 0:48 - 1:36 then Phase 3, 1:36 - 2:24 then Phase 4, it will play the theme from 0:48 - 3:12 then Phase 5 will play the Theme from 2:24 - 4:01, Phase 6 will be 0:48 - 4:01 then Phase 7 2:24 - 8:05

i think it woud be better if stage 6-7 both played from 2:00 to 8:05, as stage 7 starting out intense wouldnt fit well considering it starts at the end of your render distance. starting from 2:00 would include a less intense part to give that feeling of foreboding when the wither storm comes nearby

**Comment by nonamecrackers2** [comment]
More parts of the theme will be added in the next major release.
