### ISSUE TITLE
WS Model misalignment when mounted

### ISSUE THREAD

**Issue by CubeGamer647** [nonamecrackers2/crackers-wither-storm-mod#1338]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.4

**Mod version**
3.2.1.3

**Describe the bug**
Whenever the wither storm is mounted on another entity, its model is rotated incorrectly from its hitbox. This causes the tractor beams to float in the air, and the heads will eat you without appearing to be near you.

**To Reproduce**
Using /ride or /summon, have a wither storm mount an entity.
Example: /summon armor_stand ~ ~ ~ {Passengers:[{id:"witherstormmod:wither_storm"}]}

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
No

**Screenshots**
![2023-08-19_12 59 48](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/100244632/057d7c02-31ba-4f1f-b609-88cd2fda625b)
![2023-08-19_13 07 30](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/100244632/5c5b65ad-5215-4237-809f-c8165fdf26fd)

**Comment by nonamecrackers2** [comment]
Unfortunately, this is due to some weird vanilla logic, and since it's not really intended for the storm to mount any entity, that feature has been disabled. Will be fixed in the next 1.19.4/1.20.1 release
