### ISSUE TITLE
[Suggestion] Config to toggle Phase 5 F-Bombing 

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1339]
A config that toggles whether Phase 5 will turn into Phase 6 when F-Bombed. 

If false, then the Wither Storm will have to be Phase 5.5 for it to turn into Phase 6. 

If true, Phase 5 will also be able to change into 6. 

A 3rd option, "Dependent" automatically sets it as true as long as the Player is in creative mode or spectator, and false if in Survival or Adventure. For multiplayer, it uses the game mode that the server is set as. Dependent would be used as the default value.

**Comment by IndigoAmethyst** [comment]
For context: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1187#issuecomment-1684506618

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
