### ISSUE TITLE
Distant renderer tanks fps

### ISSUE THREAD

**Issue by ShirakiShio** [nonamecrackers2/crackers-wither-storm-mod#134]
**Minecraft version**
1.16.5

**Mod version**
Latest

**Describe the bug**
My fps drop down to 23-25 when I look in the Witherstorm's direction. This is fixed by turning off the distant renderer, but is unusual as this didn't happen before.

**To Reproduce**
You go back to the 1960s and help prevent everything that could've started a nuclear war, creating new problems to solve. Eventually you create the witherstorm and it lags the entire universe.

**Crash Reports / Logs**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/48332495/175721509-140f502f-8c8f-4bbf-b65c-42ea268df538.png)

**Comment by nonamecrackers2** [comment]
Also marking as 1.18.2 as I think this is a universal problem

**Comment by nonamecrackers2** [comment]
If you were to disable to the debris cloud, does the fps improve?

**Comment by nonamecrackers2** [comment]
Fixed in 2.2/3.2
