### ISSUE TITLE
[Suggestion]: Wither storm music continues playing if you get in range again

### ISSUE THREAD

**Issue by Laughingcat27** [nonamecrackers2/crackers-wither-storm-mod#1340]
### Desription of feature request

Currently, if the wither storm's boss bar dissapears then the music will fade away. If it is still fading away and the boss bar re-appears, a new audio track starts playing while the previous track still fades away.

When i'm near the wither storm the boss bar sometimes dissapears very momentarily, for example because i'm running in and out of a cave, or i ran far enough from the storm but it caught up with me. It just feels wrong to have the entire music track restart for those couple seconds i was out of sight.

I'd like to suggest that if a music track is fading away, and the boss bar re-appears, that that music track fades back in and continues playing, as opposed to ending and having all of the music restart again.
And for clarification, if a music track has COMPLETELY faded away then it should not come back.

**Comment by TaintedBlockmObile** [comment]
Good idea imo

**Comment by LegendaryGodzilla** [comment]
I like this idea

**Comment by Aimyx** [comment]
This may have been suggested already, but proximity based music tracks, instead if the storm is like 1000 blocks away, it would make the siren loop, and closer it gets, the more the music "evolves" for lack of a better term, to solve the cave issue, i guess would be just to have the music never stop, just set the volume down to 0 when you cant see the storm, therefore, the track would never have to restart?

**Comment by BluePineappleGuy** [comment]
> This may have been suggested already, but proximity based music tracks, instead if the storm is like 1000 blocks away, it would make the siren loop, and closer it gets, the more the music "evolves" for lack of a better term, to solve the cave issue, i guess would be just to have the music never stop, just set the volume down to 0 when you cant see the storm, therefore, the track would never have to restart?

unless you got really far away from the storm, then it would restart.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next update. Was a super simple thing to do, surprised I haven't done this already.
