### ISSUE TITLE
[Suggestion]: Hidden WS heads in bowels until they get called by Command Block

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1341]
### Desription of feature request

My idea is that the heads inside the bowels could be a bit more hidden until the command block calls them when it's at a quarter of it's health. And before you think I suggest this to be more accurate to story mode, no, forget it.
Lots of people already know how the bossfight goes, that the heads will appear at some point, so this is kinda pointless, but it is just creepier and better if the heads are not there before.

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/7f505144-5f2e-4154-b5fa-1e22723c1262)
I think it would fit if there was a small structure like this, which is the shape of the head (pointing down) and then when it's time, the structure gets removed and the heads spawn in.

**Comment by nonamecrackers2** [comment]
I personally like how they are, since you’ll notice them and feel a looming sensation that these things may do something at some point.

**Comment by myron-obsolete-account** [comment]
fair enough

**Comment by myron-obsolete-account** [comment]
yeah no one more question I cannot answer myself as I am currently playing on 1.20.1 (and am waiting for the update hooray) since the damage system is different than before IIRC, will MrCrayfish's gun mod harm the heads now, as I believe they did not before?

**Comment by myron-obsolete-account** [comment]
nevermind that mod is still stuck in 1.19.4
