### ISSUE TITLE
[Bug]: Formidibomb doesn't tick when in a container

### ISSUE THREAD

**Issue by CubeGamer647** [nonamecrackers2/crackers-wither-storm-mod#1342]
### Minecraft Version

1.19.4

### Mod Version

3.2.1.3

### Describe the bug

When the formidibomb is crafted and placed in a container such as a chest or shulker, its timer will not tick down, allowing the player to store the formidibomb until use rather than its ingredients.

(Optifine is not installed, but it was required to be ticked to submit)

### To Reproduce

1. Craft a formidibomb
2. Place it in a chest
3. Observe the timer tooltip does not update until you take it out

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] Optifine is installed

**Comment by nonamecrackers2** [comment]
This is intended. The formidibomb did tick in containers in older 1.16.5 versions, but it was removed due to several compatibility issues and a major feature that was removed in later versions that would require the system to be reworked. This led to the feature being removed entirely.
