### ISSUE TITLE
Formidibomb works in modded containers (it doesn't tick in backpacks and other things)

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1343]
Formidibomb should continue the explosion countdown even when in objects such as backpacks or shulkers in the inventory

(haven't actually tested the shulker thing yet but still gonna write it down)

**Comment by nonamecrackers2** [comment]
Why on earth is the suggestion label never applied to issues you open

**Comment by nonamecrackers2** [comment]
Also, the formidibomb did tick in containers in older 1.16.5 versions, but it was removed due to several compatibility issues and a major feature that was removed in later versions that would require the system to be reworked. This led to the feature being removed entirely.

**Comment by CubeGamer647** [comment]
I literally just made this post like a few hours before you lol. And yes, it does freeze in shulkers and chests.

**Comment by myron-obsolete-account** [comment]
> Why on earth is the suggestion label never applied to issues you open

because he probably always opens them as bugs

**Comment by nonamecrackers2** [comment]
No, because it would have the bug template info. I added a form style system, so that wouldn't be why
