### ISSUE TITLE
Updated de_de in closed pull request because I can't open a new one

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1347]
### Desription of feature request

Hello Cracker I know this isnt a suggestion but I just wanted to tell you this, you would have probably not seen it otherwise and I don't have discord to tell you that so

sorry

#786

**Comment by nonamecrackers2** [comment]
For some reason I missed this, I apologize (appears to be a few I missed). Has been acknowledged.
