### ISSUE TITLE
update1.19.2 please

### ISSUE THREAD

**Issue by Leonoric123** [nonamecrackers2/crackers-wither-storm-mod#1349]
### Desription of feature request

please update 1.19.2 to the latest available version of the mod if possible. the mod is great, but I have 1.19.2 and there is no updated version

**Comment by watersofnazareth** [comment]
There's no reason for us to update a version like 1.19.2 especially since 1.19.4 is in general better for the mod

**Comment by myron-obsolete-account** [comment]
let's turn the tables, check your mods if they have an updated version for .4 and update Forge from .2 to .4 so you can use CWSM again along with all your other mods
