### ISSUE TITLE
[Variations on cluster shape] Misc Entities, Water pulling, Cluster size & shape and Storm Remain.

### ISSUE THREAD

**Issue by WorldSpinAround** [nonamecrackers2/crackers-wither-storm-mod#135]
After experimenting on the Storm, I noticed a few things that would be great if added:

-Other entities, such as primed TNT, should be picked by the beam into the Wither.
Although not being able to kill it, I just think doing a trap TNT and let it suck it all is an entertaining strategy. But most important, it would be to the point with the fact that entities should be beamed up by the Storm, even if they are not alive.
That being said, it would work better if he could pick up multiple entities alongside blocks, but I searched this category and figured out you already knew about this specific suggestion.

-Water isn't devoured by the Storm. Ice do, but when you leave the Storm in an area long enough, you see a large pool of flowing water, there. I believe it should somehow being drained, not in chunks clusters, but like, a vacuum of many blocks. Doesn't even have to be 3d if it is too much performance. Sure, the issue is that water regenerate in the right configuration, but...
Oh yeah, lava too. Although it should be a bit easier to clear.

-Cluster being sucked up should have different size and shapes, not just spherical. It makes the terrain currently looking a bit odd, and I believe adding more variety to the destruction would be fitting. :)
That and singular blocks being sucked up too, but this specific one is already suggested by others around.

-When the Wither Storm is finally defeated, although the death sequence shouldn't be touched, it would be neat to see chunks of it fall onto the destroyed world under, and land as a cluster of Wither Storm Remains. That way, you as the player can have a source of new blocks to build with!

I believe that should be all. ^^ Great mod, really enjoyed it!

**Comment by nonamecrackers2** [comment]
1. TNT's fuse would need to be modified as it would explain midway to the head. I don't think this feature would be used very often and it doesn't currently have an affect against the WS besides distracting it
2. The WS does pull in water and other fluids however it doesn't render, if that is what you're requesting.

4 is already confirmed (#184) and I think 3 would be a good addition.

**Comment by BluePineappleGuy** [comment]
> 2. The WS does pull in water and other fluids however it doesn't render, if that is what you're requesting.

it should have some way of draining it quicker and more efficiently, it looks odd to see floating water everywhere.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
