### ISSUE TITLE
Music changes when hitting ocmmand block

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#1350]
### Desription of feature request

I feel like it just kinda goes BOOM the first time you hit a command block so proggresive music might be a cool change. Here, look at this:
https://www.youtube.com/watch?v=WvZ3hwwRSkY
Obviously at first normal music plays, but at around 11:16 this should play when approaching the command block in its room or when your about to hit it, then at 13:30 or something should be when you hit it the first time, then when you hit it a second time 14:29 should play and then the 3rd time it would start playing the classic music it now plays every time. Sure, this probably wont get added, but I thought it was a cool feature and maybe youd like diffrent music to select around it but yeah.

**Comment by LegendaryGodzilla** [comment]
It feels weird but I'll respect your suggestion

**Comment by nonamecrackers2** [comment]
I personally like how the music jumps in, and having the music be "progressive" with your distance to the command block will be difficult to properly pull off
