### ISSUE TITLE
[Suggestion]: Config option and/or command to toggle whether the phase 7 hole should naturally appear

### ISSUE THREAD

**Issue by sm644me** [nonamecrackers2/crackers-wither-storm-mod#1352]
### Desription of feature request

Currently, the phase 7 hole opens under two circumstances: Either when the Wither Storm reaches its evolution peak (2,125,000 ConsumedEntities by default), or a random-ish amount of time after a player obtains a Command Block weapon during phase 7 (uses ShouldShowHole). If a modpack/datapack developer wants to change how the hole appears, these random requirements can be annoying to work with.

For example, let's say that a developer wants the hole to appear on some arbitrary trigger, like defeating the Ender Dragon or a server operator deciding that a group of people is ready. In the current version, this would require two commands to constantly be run, one to prevent the Wither Storm from gaining more ConsumedEntities and another to toggle the ShouldShowHole tag to false even if a player has a Command Block weapon. Then, opening the hole on whatever that arbitrary trigger is would require a `/witherstormmod consumedEntities` command, which honestly works fine.

Instead, a config option and/or a command could be added. The config option would disable the natural methods that cause the hole to appear, and the command would toggle whether or not the hole has appeared on a given Wither Storm. For the sake of coding simplicity, I don't see a need for this command to work outside of phase 7; that'd probably be best as a separate suggestion.

Changing the config without a plan for what to replace it with is very much a progression-breaking option, but the config already includes an option to disable the Withered Symbiont, so the precedent is set. And yes, it's possible to control when the hole appears without this suggestion being implemented (so it shouldn't be high-priority), but again, it's also possible to deny Symbiont spawns with manual commands without the config. If the Symbiont can be disabled, I see no reason why this is so different.

**Comment by nonamecrackers2** [comment]
A config option to disable the bowels hole will be added in the next major release, should work for what you want to do :)
