### ISSUE TITLE
[Suggestion]: seperate config for final battle theme toggle

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1353]
### Desription of feature request

I personally might slowly but surely get annoyed when the Wither Storm theme plays on loop 24/7 when it's inside my rendering distance, but I might enjoy the final battle with the final fight theme (Wither Storm Destroyed), so a seperate config option for the final battle theme would be neat, so I can turn off the normal WS theme while the final battle theme stays activated.

Pausing and enabling it in the config for the final battle is also a way of doing it but nah

**Comment by NinjaSam5399** [comment]
I probably suggested this before.

**Comment by NinjaSam5399** [comment]
Its post #666 (Just ignore that, nothing is wrong with the number).

**Comment by NinjaSam5399** [comment]
Devil's Number.

**Comment by myron-obsolete-account** [comment]
oof
