### ISSUE TITLE
[Bug]: Inconsistent Amulet Rotation

### ISSUE THREAD

**Issue by Flaming-skeleton-guitar** [nonamecrackers2/crackers-wither-storm-mod#1354]
### Minecraft Version

1.19.4

### Mod Version

3.2.1.3

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Describe the bug

The amulet's glow is rotated differently from the item itself

### Steps to Reproduce

1. Play on world with mod
2. Hold Amulet
3. Look at Wither Storm with amulet in hand
4. Glow layer will be rotated away from amulet

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![amuletwrongrotate](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/141991899/feeb2509-ff23-47ee-be56-d99b2bd027f6)

### Mod List

Most of these are likely unrelated to the issue

All YUNG Structure mods
Twilight Forest
The Bumblezone
Queen Bee
Searchables
Mouse Tweaks
JEI
Journeymap
Geckolib
Cracker's WS Mod
Controlling
Configured
Cloth Config
Catalogue
BE Style Wither (Doesn't affect Cracker's as far as I know)
Bad Wither No Cookie

**Comment by nonamecrackers2** [comment]
This is intentional, it's extremely difficult to get the shine to line up properly due to how Minecraft orients the item.

**Comment by myron-obsolete-account** [comment]
> This is intentional, it's extremely difficult to get the shine to line up properly due to how Minecraft orients the item.

there is no way possibly making it a texture? even though I personally don't have a problem with that at all, didn't even notice it at first lmao

by the way are you ignoring my one issue on purpose or do you just not see it where I tell you I updated the german translations in the closed pull request because I can not open a new one?? #786 

I don't have discord and rather not use it before you tell me that alright

**Comment by nonamecrackers2** [comment]
I can't make it a texture, since the pulse flash cannot be controlled by having it baked in with it

Also, I am not trying to ignore you intentionally. I get a lot of things coming through, and while I try not to miss things, it happens sometimes.

**Comment by myron-obsolete-account** [comment]
> I can't make it a texture, since the pulse flash cannot be controlled by having it baked in with it
> 
> Also, I am not trying to ignore you intentionally. I get a lot of things coming through, and while I try not to miss things, it happens sometimes.

I'm sorry sometimes I do be like this
