### ISSUE TITLE
[Suggestion]: Bowels tentacle revamp?

### ISSUE THREAD

**Issue by mattdafilipino** [nonamecrackers2/crackers-wither-storm-mod#1355]
### Bowels tentacle revamp?

maybe inside the bowels instead of the tentacles grabbing you and putting you down the hole, it has a chance of yeeting you in a random directoon.

**Comment by TaintedBlock** [comment]
They already do this? They don't try and put you in the hole.

**Comment by myron-obsolete-account** [comment]
when exactly did tentacles try to throw you into the bowels exit

**Comment by nonamecrackers2** [comment]
They don't intentionally try to put you through the hole. They already throw you in a random direction however.

**Comment by Pandaboi25x** [comment]
> They don't intentionally try to put you through the hole. They already throw you in a random direction however.

I think by yeet he meant that the tentacles do near the commans block

**Comment by TaintedBlockmObile** [comment]
> > They don't intentionally try to put you through the hole. They already throw you in a random direction however.
> 
> I think by yeet he meant that the tentacles do near the commans block

I don't think the tentacles up there even can hit you in there

**Comment by Pandaboi25x** [comment]
> 

you bein serious rn?

**Comment by Pandaboi25x** [comment]
> > > They don't intentionally try to put you through the hole. They already throw you in a random direction however.
> > 
> > 
> > I think by yeet he meant that the tentacles do near the commans block
> 
> I don't think the tentacles up there even can hit you in there

you bein serious rn?
