### ISSUE TITLE
[Suggestion]: New command block hit sound (QoL)

### ISSUE THREAD

**Issue by mattdafilipino** [nonamecrackers2/crackers-wither-storm-mod#1358]
### Desription of feature request

When you hit the command block, it now has a crack sound when you hit it. Heres my own concept of the command block hit sounds.

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103057495/dd0d27e4-bfbf-4247-87f3-e017758605c9

**Comment by TaintedBlockmObile** [comment]
You should send the sound files as well if you want this to even be used.

**Comment by mattdafilipino** [comment]
You can't send audio files on github, only video and photos. I'll send them via discord if they want.

**Comment by LegendaryGodzilla** [comment]
I like this idea

**Comment by BluePineappleGuy** [comment]
> You should send the sound files as well if you want this to even be used.

using something like freeconvert.com you can change a video file to an audio file, including OGG files which are used for minecraft sounds.

**Comment by myron-obsolete-account** [comment]
> You can't send audio files on github, only video and photos. I'll send them via discord if they want.

you forgot about zip files

**Comment by mattdafilipino** [comment]
[Hit_sounds_for_command_block.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12485580/Hit_sounds_for_command_block.zip)
zip files for the 3 hit sounds in mp3 format

**Comment by nonamecrackers2** [comment]
Not exactly the same, but definitely took inspiration. Will be implemented in the next major release.
