### ISSUE TITLE
[Suggestion]: Wither Storm Head Improvements

### ISSUE THREAD

**Issue by dishonest-truth** [nonamecrackers2/crackers-wither-storm-mod#1359]
### Desription of feature request

When I say this, I mean in early phases. 
**Closed Eyes:** To make it more immersive instead of having it literally staring into the abyss as it's being summoned. It's also like how it is ingame and makes it look better (shouldn't be too hard to make I don't think?) in Phase 0 (Summoning phase)
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143570676/3e9ae35b-8cd2-4c98-9057-d908c41f5e3f)
**Independent Heads:** During Phase 1, 2, and 3 (The phases where it still has the 2 smaller wither heads) it should be able to move the secondary heads to look at mobs and maybe shoot regular wither skulls. You may think "The heads already move!" which is correct, but they only lock onto one target and they do it simultaneously. So if it's chasing you, it will be deadlocked onto you instead of the other heads wreaking havoc around just like in the later phases where it has the 3 large heads.
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143570676/75ec4e20-0a27-4fc7-8f42-67669a080ffe)
_Image isn't a great example but ya take what you can get_

**Comment by mattdafilipino** [comment]
a bit like decayed reality its a good idea

**Comment by CubeGamer647** [comment]
If the eye thing were to get added, I would make that a toggle. I do agree the head tracking needs improvement.

**Comment by nonamecrackers2** [comment]
I prefer how the heads track but the eyes could be interesting.

**Comment by MoRoN222** [comment]
nah. personal opinion here: I think without closed eyes is better like the normal wither, maybe it could be a config and in MCSM they probably made the closed eyes for "more realism" while in MCJE and the other ones it does not have closed eyes, but I don't really care honestly, we could still make a texture pack right?

**Comment by mattdafilipino** [comment]
> nah. personal opinion here: I think without closed eyes is better like the normal wither, maybe it could be a config and in MCSM they probably made the closed eyes for "more realism" while in MCJE and the other ones it does not have closed eyes, but I don't really care honestly, we could still make a texture pack right?

this isnt a wither we are talking about its a whole storm so giving it a bit of life might add to it being something different than just a wither

**Comment by MoRoN222** [comment]
> > nah. personal opinion here: I think without closed eyes is better like the normal wither, maybe it could be a config and in MCSM they probably made the closed eyes for "more realism" while in MCJE and the other ones it does not have closed eyes, but I don't really care honestly, we could still make a texture pack right?
> 
> this isnt a wither we are talking about its a whole storm so giving it a bit of life might add to it being something different than just a wither

the whole storm was a wither with a 1x1x1m magic cube in it's rip bones but alright

**Comment by CubeGamer647** [comment]
Can you guys stop arguing about a fictional block game powered by souls where you can resurrect the dead and transform it into a giant eldritch horror used to destroy worlds and power a beacon with infinite range

**Comment by mattdafilipino** [comment]
> Can you guys stop arguing about the realism of a fictional block game powered by souls where you can resurrect the dead and transform it into a giant eldritch horror used to destroy worlds and power a beacon with infinite range

no

**Comment by dishonest-truth** [comment]
> Can you guys stop arguing about the realism of a fictional block game powered by souls where you can resurrect the dead and transform it into a giant eldritch horror used to destroy worlds and power a beacon with infinite range

Literally impossible.

**Comment by dishonest-truth** [comment]
> I prefer how the heads track but the eyes could be interesting.

(I'm a necroposter but ya know.) Yeah, currently it just stares into space and even when the spawning animation is over, is stays for a few more seconds. I feel like it should raise up to the sky during the spawning animation (I'm talking about the blue flashes before it actually does anything)

**Comment by nonamecrackers2** [comment]
#1037
