### ISSUE TITLE
Making the wither storm more crazier.

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#136]
make the wither storm more chaotic (see the comment i made)

**Comment by Resuster** [comment]
So, I saw the difference between the engender wither storm and your one. The engender one was very chaotic and stuff, So I'd like you to do that and also make the tentacles crazy and pick mobs and slash them away

**Comment by nonamecrackers2** [comment]
I don't think it's very realistic for the tentacles to be able to reach to the ground and grab/slash mobs in a way that makes sense and I can't think of a reasonable way that I could implement this at the moment. I'm also not using the engender mod as the "standard" for my mod.
