### ISSUE TITLE
Super TNT creates the bowels hole.

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1364]
### Desription of feature request

In the evolution update teaser, it was shown that TNT can be beamed by the storm and will blow up close to the head. My idea is something similar using super TNT in the last phase, it would turn off all the heads of the segment/storm that picked it up, and for the storm it would create the hole in the process.

**Comment by mattdafilipino** [comment]
good idea but the waiting time for a symbiont is already long and if you gotta wait for another one to spawn, its just gonna be a bit long. just a flaw i saw.

**Comment by TaintedBlockmObile** [comment]
I don't really see this happening to be completely honest.

**Comment by BluePineappleGuy** [comment]
> good idea but the waiting time for a symbiont is already long and if you gotta wait for another one to spawn, its just gonna be a bit long. just a flaw i saw.

it _would_ slow down progression a little bit, so maybe this could be a config or smth

**Comment by nonamecrackers2** [comment]
I don’t think crafting super tnt just to do this would be a very effective use time/materials.
