### ISSUE TITLE
[Suggestion]: Make the Witherstorm be able to be stood on

### ISSUE THREAD

**Issue by BladeLightsteel** [nonamecrackers2/crackers-wither-storm-mod#1366]
### Desription of feature request

not sure how it would work, but I think it'd be cool to stand on the witherstorm like a boat lets you stand on it and possibly make it give you a debug like a more intense version of wither sickness (it would only stay while standing on the witherstorm, then just goes back to the normal sickness after stepping off), to discourage it but still allow for it to happen.

**Comment by TaintedBlockmObile** [comment]
Don't think this will happen nor do I think it's possible with the ws

**Comment by Steve982950** [comment]
Even if it was possible, It might cause a lot of bugs/problems/lag

**Comment by myron-obsolete-account** [comment]
while taking Create, Valkerien Skies and other mods as an example, idk if its really necessary too, I mean, it would be cool, flying up there with your elytra or something but uhh yea idk

**Comment by BluePineappleGuy** [comment]
it wouldn't really work out that well, because the heads would still attempt to target you and his head would go inside the mass.

**Comment by BladeLightsteel** [comment]
did you forget that the heads wont just snap onto your location anymore?

**Comment by BladeLightsteel** [comment]
also with the lag issue, you just just add a setting to turn it on/off

**Comment by TaintedBlockmObile** [comment]
> did you forget that the heads wont just snap onto your location anymore?

This doesn't change the fact that they will still try and get you. And if they can't that's just a really cheap way of surviving

**Comment by myron-obsolete-account** [comment]
imagine building a house on top of the storm 💀

**Comment by BladeLightsteel** [comment]
like i said, it would give you a huge wither sickness debuff if you stood on it, preventing you from  just cheesing the wither by standing on it.

**Comment by BluePineappleGuy** [comment]
it still wouldn't make sense as accurate collisions would be very difficult for crackers to make, due to how complex the model is. and unless you were playing this late game with an elytra, most players would never even notice this would exist.

**Comment by Steve982950** [comment]
> imagine building a house on top of the storm 💀

LOL 💀💀💀💀💀💀💀

**Comment by Midstas** [comment]
It would probably be too hard. Could probably be done if the mod is later developed and it is easier to be done but I don’t think we will see this anytime soon

**Comment by Steve982950** [comment]
Imagine a VILLAGE on the storm lol

**Comment by nonamecrackers2** [comment]
#494
