### ISSUE TITLE
[Suggestion]: The witherstorm just needs to shoot more wither skills

### ISSUE THREAD

**Issue by mattdafilipino** [nonamecrackers2/crackers-wither-storm-mod#1367]
### Desription of feature request

i feel like he could be more destructive if there was a config where you could customize when a witherskull is shot every what ever time you set it

**Comment by Luke7381** [comment]
i actually suggested something similar at one point

**Comment by Composer-Hu** [comment]
This has already been achieved and you can expect a new version to be released!

**Comment by nonamecrackers2** [comment]
#624

**Comment by nonamecrackers2** [comment]
Actually can’t find where this was suggested, will be implemented in the next update though
