### ISSUE TITLE
Disable wither storm healing (request)

### ISSUE THREAD

**Issue by NEFFLEAFF** [nonamecrackers2/crackers-wither-storm-mod#137]
This is two suggestions in one as both have the same purpose.
-Add a config option to disable the wither storm healing.
-Add a config option to make wither storm phase 4 and above damageable.

I'm crazy enough to challenge a destroyer phase in a normal fight.

**Comment by Parakeetgod** [comment]
agreed

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
