### ISSUE TITLE
[Suggestion]: Snow on top of the storm when it's snowing

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1370]
### Desription of feature request

stupid suggestion, unlikely to be accepted, difficult to implement I guess

what if the storms body gets snow layers on top of it when it's in a snowy enviorment and it's snowing?

**Comment by mattdafilipino** [comment]
Christmas update

**Comment by myron-obsolete-account** [comment]
no way christmas update

**Comment by TaintedBlockmObile** [comment]
It would probably absorb the snow but maybe for Christmas sure

**Comment by GrandmaPork** [comment]
Christmas 🎄

**Comment by FunkyPotao** [comment]
Itll probably consume the snow xp

**Comment by nonamecrackers2** [comment]
Would be difficult to implement texture wise due to how the model is set up, but interesting idea though

**Comment by Laughingcat27** [comment]
christmas storm
