### ISSUE TITLE
[Suggestion]: Add mass to the back of the wither storm over time

### ISSUE THREAD

**Issue by ItsMitlit** [nonamecrackers2/crackers-wither-storm-mod#1371]
### Desription of feature request

Personally, I think that it'd be pretty cool if the back of the wither storm got bigger and bigger once it has reached its final stage.  Something like this was done with the [Engender Mod](https://www.curseforge.com/minecraft/mc-mods/engender-mod) as it continued to suck up blocks.

**Comment by mattdafilipino** [comment]
> ### Desription of feature request
> 
> Personally, I think that it'd be pretty cool if the back of the wither storm got bigger and bigger once it has reached its final stage.  Something like this was done with the [Engender Mod](https://www.curseforge.com/minecraft/mc-mods/engender-mod) as it continued to suck up blocks.

Nah it woukd look goofy cause look at the engender at max consumed entities. It could go past that and get bigger![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103057495/1d8ea33a-9238-41ef-a3ee-0efea8a9be92)

**Comment by Composer-Hu** [comment]
You can look forward to the next new release, and it won't disappoint.

**Comment by WitherBean** [comment]
> You can look forward to the next new release, and it won't disappoint.

I agree.

**Comment by nonamecrackers2** [comment]
Something similar was suggested before. However, this wouldn't be possible since the models would need to be manually created, and having it randomly generated would require a complete model system rework which isn't worth the time to do so.
