### ISSUE TITLE
[Suggestion]: Phase Progresion (This issue is stupid and forget about

### ISSUE THREAD

**Issue by SimonGamingPl** [nonamecrackers2/crackers-wither-storm-mod#1373]
### Desription of feature request

So waiting fro The Wither storm is kinda boring, so i came with a idea if the wither storm suck up a block a small of his mass will appear

Somethig like that:
![wither storm sug](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/18397562-dddb-439f-9f9c-05e1ffb0ec4e)

**Comment by SimonGamingPl** [comment]
Yes i mad it in paint so plese no heat :(

**Comment by TaintedBlock** [comment]
So basically subphases. There is a possibility it will happen.

**Comment by TaintedBlock** [comment]
This does not mean every block picked up will add more mass. That's just too many models

**Comment by SimonGamingPl** [comment]
But when wither storm is on stage 4 the Stage Progresion will be turn off ( just no more mass will apper when WITHER STORM suck up a block ( it will work just like now) )

**Comment by TaintedBlock** [comment]
> Author

Again, subphases will probably be a thing, but there wont be a bunch of small subphases for no reason. That's just too many models to be adding for something people wont really pay too much attention to.

**Comment by SimonGamingPl** [comment]
You know what? im gonna delete this post cuss its stupid anyway.

**Comment by nonamecrackers2** [comment]
Definitely possible but would require a complete rework of the model system, which is not in my best interests right now

**Comment by BluePineappleGuy** [comment]
this kinda exists though (in the early stages
