### ISSUE TITLE
Update github feature request template to include a list of commonly declined features (tentacle attacks, update 1.19.2-1.18.2 suggestions and such)

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1374]
this would prevent more duplicate posts about things that would simply be declined

**Comment by myron-obsolete-account** [comment]
it does already

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/825d8eb4-e3c5-4e9d-a618-0f23e9b3561c)

**Comment by Nov1st2k10** [comment]
> it does already
> 
> 
> 
> ![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/825d8eb4-e3c5-4e9d-a618-0f23e9b3561c)
> 
> 

yeah but nobody takes their time to read it, so it should instead just have it in the template

**Comment by nonamecrackers2** [comment]
I might have another approach for this, but for now I think the link is fine
