### ISSUE TITLE
Witherstorm center model not being accurate to witherstorm segments in phase 6

### ISSUE THREAD

**Issue by mattdafilipino** [nonamecrackers2/crackers-wither-storm-mod#1376]
### Desription of feature request

Just like a model adjustment to be more accurate when the witherstorm segments fall off as shown in the picture its confusing 😱😱
![33F8C6BE-F721-4EC3-A16F-3A33B3D35114](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103057495/6013a11b-35dd-442c-845c-7aa0dd38751b)
![94D79756-78D6-493B-89FC-7F8065C42ADD](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103057495/72bc82bb-79df-4217-984d-9625f38cddc7)

**Comment by TaintedBlockmObile** [comment]
No point in changing this since the screen is fully white and no one can see this

**Comment by myron-obsolete-account** [comment]
> No point in changing this since the screen is fully white and no one can see this

you will literally see it the entire time the WS is at phase 6 that the holes are up there and not down there where they should be

**Comment by myron-obsolete-account** [comment]
by the way #823

**Comment by TaintedBlockmObile** [comment]
> 

Still won't end in the model being changed.
