### ISSUE TITLE
[Bug]: Bossbar Issue

### ISSUE THREAD

**Issue by Honey-Programming** [nonamecrackers2/crackers-wither-storm-mod#1377]
### Minecraft Version

1.19.4

### Mod Version

3.2.1.3

### Mod Loader

Forge

### Mod Loader Version

45.1.17 and below

### Describe the bug

When you kill the Wither Storm, the bossbar should be empty instead of filled up. It makes no sense that the bossbar says it's alive but it is actually dead.

This applies to all versions except for the older versions of 1.16.5

### Steps to Reproduce

1. Kill Wither Storm
2. See error

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

I will add screenshots when I have time. Just follow the reproduction steps until I can add a screenshot.

### Mod List

NONE

**Comment by TaintedBlockmObile** [comment]
I think this might be changed in the next update. This request has already been made btw

**Comment by Composer-Hu** [comment]
Yes, the next release update will take care of that detail.

**Comment by nonamecrackers2** [comment]
This is technically intended, but yes this will be changed in the next update
