### ISSUE TITLE
[Suggestion]: new way of obtaining command block book

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1378]
### Desription of feature request

If the withered symbiont dies it should release command block power wich should be collected with a book crause it could look cooler and it makes no sence that a creature like this has a random book inside of it

**Comment by TaintedBlockmObile** [comment]
The creature uses the book

**Comment by FunkyPotao** [comment]
> The creature uses the book

I cant see it using the book jknow

**Comment by Nov1st2k10** [comment]
You do know that the symbiont drops the command block book?

**Comment by FunkyPotao** [comment]
> You do know that the symbiont drops the command block book?

Makes no sence yknow + collecting little command block sparks with a book is a liztle more actionish

**Comment by nonamecrackers2** [comment]
I personally don't feel this needs changing and it may confuse players, going to leave it as it is for now. Thank you for your suggestion though

**Comment by Laughingcat27** [comment]
> > You do know that the symbiont drops the command block book?
> 
> Makes no sence yknow + collecting little command block sparks with a book is a liztle more actionish

i mean if ivor can make command block books with a command block, then the wither storm can do so too. it gives those to the symbionts, it does make sense they drop the whole books.
But it would be a cool feature to collect the sparks with a book yeah

**Comment by TaintedBlockmObile** [comment]
> > > You do know that the symbiont drops the command block book?
> > 
> > 
> > Makes no sence yknow + collecting little command block sparks with a book is a liztle more actionish
> 
> i mean if ivor can make command block books with a command block, then the wither storm can do so too. it gives those to the symbionts, it does make sense they drop the whole books. But it would be a cool feature to collect the sparks with a book yeah

This would just make the book overpowered as hell
