### ISSUE TITLE
[Suggestion]: symbiont phases

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1379]
### Desription of feature request

Okay, thiscould be hard to model new stuff but i would love if the withered symbiont would get phases like over time itll transform into a spider or some sorts wich could be a punishment for the player not killing the symbiont

**Comment by LegendaryGodzilla** [comment]
SpooderSymbiont

**Comment by Midstas** [comment]
What about it overtime sucks up block just like the storm. And grows stronger overtime. And after like maybe 30 minutes (could be a setting) it will get taken back by the storm and give the storm some extra consumed entity’s

**Comment by nonamecrackers2** [comment]
I'm going to be leaving the symbiont as it is, changing its behavior as of now is not in the best interests for the mod.
