### ISSUE TITLE
[Suggestion]: wither sickness weapons

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1380]
### Desription of feature request

Like arrows ir spash potion that emmit the effect, canbe annoying in hardcore :p

**Comment by TaintedBlockmObile** [comment]
Maybe for the normal wither effect? Wither sickness would just be a little much

**Comment by FunkyPotao** [comment]
> 

Doesnt have to be permanent  yknow

**Comment by TaintedBlockmObile** [comment]
> > 
> 
> Doesnt have to be permanent yknow

Then it would just be the normal wither effect. Which is much better to deal with

**Comment by nonamecrackers2** [comment]
Wither sickness potions, etc. have been suggested already and declined, since Wither Sickness is a long lasting effect having potions that only give it for a few minutes doesn't make any sense
