### ISSUE TITLE
[Suggestion]: Phase 4.5

### ISSUE THREAD

**Issue by SimonGamingPl** [nonamecrackers2/crackers-wither-storm-mod#1384]
### Desription of feature request

So phase 4.5 is  just phase 5 but witout the big brain (the mass) and that's it
Example: (this is bedrock edition btw)
![2023-09-03](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/30c4a167-adc2-4b37-8e03-546683866a3e)

**Comment by Pandaboi25x** [comment]
basically subphases, subphases are gonna get added and heres the 4.5 phase 
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/3282600f-31da-4d70-9865-bf9bd5d00f98)
you should watch the new cwsm evolution vid

**Comment by SimonGamingPl** [comment]
Oh... I watch it but i didn't noitec it LOL

**Comment by SimonGamingPl** [comment]
But Thank you :D

**Comment by Pandaboi25x** [comment]
> But Thank you :D

yw should prob remove this suggestion since you know its getting added btw

**Comment by SimonGamingPl** [comment]
You cant remove issues (i think)

**Comment by Pandaboi25x** [comment]
> You cant remove issues (i think)

well you cant remove but you can close em

**Comment by SimonGamingPl** [comment]
oh ok thx

**Comment by Pandaboi25x** [comment]
yw

**Comment by myron-obsolete-account** [comment]
well I mean the features the Evolution trailer reveals can be spoken about, even by patrons I hope? because yeah idk
