### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lazybum1487** [nonamecrackers2/crackers-wither-storm-mod#1386]
### Minecraft Version

1.19.4

### Mod Version

3.2.1.3

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Describe the bug

Right clicking on a sickened tamed wolf with a golden apple stew doesn't begin the curing process. It just keeps sitting them down as if you didn't have anything in your hand.

### Steps to Reproduce

1. Tame a wolf
2. Let it catch the wither sickness effect
3. Craft a Golden Apple Stew
4. Right click on your sickened wolf with the stew in your hands
5. See error

### Crash Reports/Logs

None

### Is OptiFine installed?

No

### Screenshots

None

### Mod List

Cracker's Wither Storm Mod
Dynamic Lights
Easy Magic [Forge & Fabric]
Easy Netherite Ingot [FORGE & FABRIC]
Enchanting Infuser [Forge & Fabric]
Enchantment Descriptions
Inventory HUD+
Legacy Smithing Table
Mouse Tweaks
Ok Zoomer Forge
Roughly Enough Items Fabric/Forge (REI)
Roughly Enough Resources
Simple Uncrafting Table (Fabric/Forge)
Tool Stats
Useful Backpacks
WTHIT Forge Edition
Xaero's Minimap
Xaero's World Map
FPS Monitor
Better Fps - Render Distance[Forge]
No Leg Indent

**Comment by TaintedBlockmObile** [comment]
Did you try shift right-clicking?

**Comment by lazybum1487** [comment]
Yes, that still didn't resolve the issue sadly

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release.
