### ISSUE TITLE
Using NORMAL tnt to open the witherstorms hole

### ISSUE THREAD

**Issue by mattdafilipino** [nonamecrackers2/crackers-wither-storm-mod#1388]
### Desription of feature request

Hear me out, using the new mechanics seen in the evolution teaser at phase 7 to open up the witherstorms hole you have to make the witherstorms heads suck up a certain number of tnt (10-12). The hole could progressively show it getting bigger until the final stage of the hole where it then can be entered. This mechanic could also be conpatible with creepers, making mobs have more use in this mod aswell. 
![E9262624-BEC9-4044-B47B-D1340BB9A082](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103057495/ae57b771-aaae-4f98-ad39-3a52e7ee6e84)
![B7D04E0B-CC6D-44C6-8699-BA1DEC82CDA7](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103057495/eccd1458-f9af-4fd2-992b-16ebd8a42e34)
![46C439F6-9C41-47DE-89BB-C16F4B432250](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103057495/caa2cafb-57f8-4cc9-aa6c-a0bb9448c7e6)

**Comment by Flaming-skeleton-guitar** [comment]
How would the tnt reach the part where the hole forms? Doesn't make sense physically

**Comment by TaintedBlockmObile** [comment]
Still a no.

**Comment by BluePineappleGuy** [comment]
this would work better than my suggestion, and it makes sense.

**Comment by TaintedBlockmObile** [comment]
> this would work better than my suggestion, and it makes sense.

Not really. It would be very weird for TNT to do any kind of damage but a f-bomb couldn't obliterate it

**Comment by BluePineappleGuy** [comment]
> > this would work better than my suggestion, and it makes sense.
> 
> Not really. It would be very weird for TNT to do any kind of damage but a f-bomb couldn't obliterate it

good point

**Comment by nonamecrackers2** [comment]
Putting this under #1364
