### ISSUE TITLE
Endermen holding Tainted flesh spawn nearby when the bowels hole opens

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1389]
In MCSM, Endermen would take blocks off the wither storm and form a hole, This would be quite hard to implement so i'm suggesting that they just spawn around the wither storm,so the player ender pearls to enter the storm, as well as giving the illusion that the endermen formed that hole by taking blocks

**Comment by TaintedBlockmObile** [comment]
Pretty sure this is suggested already. Idk which it is tho

**Comment by nonamecrackers2** [comment]
#235
