### ISSUE TITLE
[Suggestion] Block based entities such as item frames/paintings/armor stands should be pulled with Block Clusters

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#139]
Usually Item Frames and other tile based entities are popped off of where they used to be, not sure if this is possible without rewriting them but it would be cool to see them be picked up and rotated with block clusters, maybe turned into "fake" blocks to replace them but retain their visual appearance?

**Comment by onyxromero** [comment]
I second this, I've noticed the wither cannot pick up a lot of blocks.

**Comment by nonamecrackers2** [comment]
There aren't a lot of entity type blocks (item frames, paintings) and rewriting the block clusters to include these is currently not worth my time.
