### ISSUE TITLE
Please make it available for 1.20.1 [Suggestion]: 

### ISSUE THREAD

**Issue by Kskdo** [nonamecrackers2/crackers-wither-storm-mod#1391]
### Desription of feature request

i have a world for 1.20.1 and i wanna use this mod with it. Can you please upgrade?

**Comment by Pandaboi25x** [comment]
it will be available on the next update

**Comment by Laughingcat27** [comment]
he's gonna release it for this version once the new version of the mod comes out

**Comment by Kskdo** [comment]
ok but if possible can i use my 1.20.1 world on 1.19.4?

**Comment by Kskdo** [comment]
> [Pandaboi25x](/Pandaboi25x)

when will be the next update?

**Comment by Flaming-skeleton-guitar** [comment]
> ok but can i use my 1.20.1 world on 1.19.4? And if possible how?

Just wait a few days, or convert it with chunker if you are really that desperate

**Comment by Kskdo** [comment]
ok

**Comment by TaintedBlockmObile** [comment]
> ### Desription of feature request
> i have a world for 1.20.1 and i wanna use this mod with it. Can you please upgrade?

The update will release in 1.19.4 and 1.20 in due time. This month it will release and soon.

**Comment by BluePineappleGuy** [comment]
this is not really the place for questions, you can go to discussions to ask questions
