### ISSUE TITLE
[Suggestion]: Better Downed Wither storm

### ISSUE THREAD

**Issue by SimonGamingPl** [nonamecrackers2/crackers-wither-storm-mod#1393]
### Desription of feature request

Pretty much what my Suggestion is that when you use the F-Bomb on The storm this looks kinda boring.  So what i ment is that the Downed Wither storm shoud look like this:
![2023-09-05](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/6960e1fa-f6c4-4b6f-8039-74fab1b694ed)

It will look cooler and and more accruate to MCSM (yes i said it and now im gonna get bombbarded by people)
(P.S You dont have to move the wither storm other bodys)

**Comment by TaintedBlockmObile** [comment]
Most likely not gonna happen. And the dead wither storm in mcsm really doesn't make sense anyway.

**Comment by BluePineappleGuy** [comment]
i do like the idea of a tentacle maze of some sort,  instead of just climbing up one of the tentacles

**Comment by TaintedBlockmObile** [comment]
> i do like the idea of a tentacle maze of some sort, instead of just climbing up one of the tentacles

This wouldn't make much sense, especially how the wither is built.

**Comment by BluePineappleGuy** [comment]
> > i do like the idea of a tentacle maze of some sort, instead of just climbing up one of the tentacles
> 
> This wouldn't make much sense, especially how the wither is built.

good point, but it still would be kinda cool

**Comment by nonamecrackers2** [comment]
MC:SM accuracy suggestions are against the guidelines.
