### ISSUE TITLE
[Suggestion]: Command Block Armor + NEW Smithing Template

### ISSUE THREAD

**Issue by SimonGamingPl** [nonamecrackers2/crackers-wither-storm-mod#1394]
### Desription of feature request

Just Diamond Armor but Command Block Powered

To the Smithing Template. to get it you need to craft it. the crafting is very simple. Something like this:
![Suggestion](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/4031fea3-c33c-40bb-aa03-2e9ae91d9e7d)

(if crakers comments im doing a good looking Smithing Template texture)

**Comment by BluePineappleGuy** [comment]
i doubt it would require another command block book as that would slow down progression, and new armor is something that has been turned down before. i do like the idea of a smithing template instead of a new anvil, but it would be better if it was found in a structure rather than crafted.

**Comment by nonamecrackers2** [comment]
Please read the guidelines
