### ISSUE TITLE
[Suggestion]: Add a Shieker in the Sculk Section of the Bowel

### ISSUE THREAD

**Issue by WorldSpinAround** [nonamecrackers2/crackers-wither-storm-mod#1397]
### Desription of feature request

After briefly reviewing the latest update, I came to the discovery of the Sculk Maze in the Bowels. I was glad to see the Warden wasn't there!
However, I have read around that it used to have a shrieker.
I am unsure of what motivated their removal, but it seems it is due to the fact that said block could summon the Warden... Which you know, good!

But I tried a "can_summon=false" shrieker, and... With the ambiance, noises the Bowels gives, hearing a Shrieker does send a chill down my spine! One could expect the terrible Warden at any seconds!

I feel it is a missing opportunity. It's a quick fix to do, but I believe it could greatly add to the vibe of this one part of the Bowels.

**Comment by nonamecrackers2** [comment]
#958
