### ISSUE TITLE
Phasometer can be fused with the amulet (combine both to integrate the functionality into the amulet)

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1399]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

You can combine the amulet and phasometer in a smithing table or crafting table and after combining them, the amulet has the ability to show the precise phase of the nearest wither storm

**Comment by LegendaryGodzilla** [comment]
Amumeter

**Comment by nonamecrackers2** [comment]
I think I'll be leaving them separate since I don't overly like the idea of combining them
