### ISSUE TITLE
Feature Suggestion: option for more detailed wither tractor beams.

### ISSUE THREAD

**Issue by GameDokter51** [nonamecrackers2/crackers-wither-storm-mod#14]
I suggest an option for more detailed tractor beams that have the small particles in them like can be seen in Minecraft: Story Mode. 
https://youtu.be/NU4cPCBVL4o

**Comment by Abasthepro** [comment]
This will be cool of it got added

**Comment by nonamecrackers2** [comment]
Implemented as of pre release
