### ISSUE TITLE
Crash with shaders (I don't know if I did this weird shit right)

### ISSUE THREAD

**Issue by Imadehtisaccountjustsoicanreportissues** [nonamecrackers2/crackers-wither-storm-mod#140]
**Minecraft version**
The version of Minecraft the mod is running on
1.16.5
**Mod version**
The version of the mod you are using
Latest 1.16.5 version
**Describe the bug**
I get this crash every time I go into the wither storms stomach with shaders: 

The game crashed whilst tesselating block model with rgba
Error: java.lang.ArrayIndexOutOfBoundsException: 4
Exit Code: -1

**To Reproduce**
1. Go to 'The wither storms stomach with shaders using optifine'
2. Click on '..................................'
3. Scroll down to '.....................'

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**
{Insert boring crash image here}

**Comment by nonamecrackers2** [comment]
Disable block cluster coloring in the client config

**Comment by Imadehtisaccountjustsoicanreportissues** [comment]
> Disable block cluster coloring in the client config

i have

**Comment by Imadehtisaccountjustsoicanreportissues** [comment]
> Disable block cluster coloring in the client config

oh shit i meant that i have disabled block clusturing and im still getitng crashes
