### ISSUE TITLE
Cave rumble intensity toggle

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1400]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

Be able to configure cave rumble intensity so it can affect bigger areas and make more glow berries fall
(when i experienced the cave rumble it made 1-5 glow berries fall and i would like to configure it to be much stronger)

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
