### ISSUE TITLE
Using /witherstormmod phase set @w 4.6-4.9 reverts to the default phase 4 model rather then the phase 4.5 model

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1401]
**Minecraft version**
The version of Minecraft the mod is running 
1.20.1
**Describe the bug**

**To Reproduce**
Follow instructions in title

also works for all the variants from the other phases

**Comment by TaintedBlock** [comment]
This happens for every phase. And I think its because phase 4-7 are like the main models while the subphases aren't? I really don't know

**Comment by nonamecrackers2** [comment]
Will be fixed in the next release

**Comment by myron-obsolete-account** [comment]
it really feels like that the first release of the new version/update really is just a bughunter version so the next one will be the actual better release lol
