### ISSUE TITLE
You can put any item into a withered beacon (it can also hold unlimited of that item

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1402]
You can right click and put any item into the withered beacon, not just wither skeleton skulls!

[image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/106888663/5408df66-3a67-494d-9e4f-8bec98e9cfc5)

**Comment by Nov1st2k10** [comment]
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/106888663/52f403e6-3882-4187-9ea2-3d3784469832)

**Comment by nonamecrackers2** [comment]
This is intentional, there are new crafting recipes with the beacon (you can use JEI to view them all)
