### ISSUE TITLE
Inconsistent and illogical command block tool stats

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1404]
The tools stats are all over the place, the gold command block sword somehow does less damage then a regular gold sword

The iron command block sword is also somehow stronger then the diamond command block sword

**Comment by TSEG6** [comment]
This is intended

**Comment by TaintedBlock** [comment]
They all have abilities. And makes it so its worth using different ones

**Comment by Nov1st2k10** [comment]
They have different effects? is there a list of all the new effects or do i just have to test them all

**Comment by nonamecrackers2** [comment]
This is intended, each have their own unique abilities/drawbacks. They should be listed in the change log
