### ISSUE TITLE
Suggestions for Part 2

### ISSUE THREAD

**Issue by Nekimi** [nonamecrackers2/crackers-wither-storm-mod#1405]
1. (Personal Preference) I like the slider options for the Evolution Attribute Modifier (maybe do a poll in the server on which ones people like more? Sliders vs. Typing)
2. A sound for the Bowels opening, something that you can hear even in the caves and it sounds like Endermen ripping the Storm apart, like in MCSM
3. Maybe make it so that the game generates one wither storm spawn house once in each of its variant biomes (doesn't matter how far they are otherwise in order to see all of them you will have to generate a ton of worlds)  and place structure for it does not work.

**Comment by nonamecrackers2** [comment]
Only one suggestion per issue please
