### ISSUE TITLE
[Bug]:  just a tiny typo

### ISSUE THREAD

**Issue by VeryJordan** [nonamecrackers2/crackers-wither-storm-mod#1406]
EDIT: Yes i know this is super minor, but dont where where else to report it other than the "bug report" template. Also im not to concerned about this. Im just reporting it to crackers just in case.

### Minecraft Version

1.19.4

### Mod Version

3.3

### Mod Loader

Forge

### Mod Loader Version

45.1.19

### Describe the bug

its small little typo i found when hovering over "world settings" 
Its not important fix it but you know "Quality-of-life"

"unqiue" should be "unique"

### Crash Reports/Logs

of course there was no crashes.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/141176384/7e84a25a-48e2-4e72-8ea2-bf1d0ca04087)

### Mod List

dont think the mods really matters, unless i have a mod that messes with words for some reason.

**Comment by TaintedBlock** [comment]
Bro really made a whole github suggestion for a MINOR spelling mistake. Its so small barely anyone noticed it.

**Comment by VeryJordan** [comment]
> Bro really made a whole github suggestion for a MINOR spelling mistake. Its so small barely anyone noticed it.

dude where else could've ive done it?
If there was a template for simple mistakes like these i would gladly use it.

**Comment by TaintedBlockmObile** [comment]
If you have discord you could've asked there but to each their own I guess😭

**Comment by nonamecrackers2** [comment]
Dude this is the exact place for these kind of things... we don't need to be rude about it.

**Comment by myron-obsolete-account** [comment]
lmao

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update
