### ISSUE TITLE
Mobs turning sickened when in the tractor beam for to long

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#1407]
### Desription of feature request

When a mob gets pulled into a tractor beam it would turn sickened or when a mob gets killed it will come back to life as a sickened mob, EXAMPLE: a skeleton gets eaten by the wither storm, it will respawn below the wither storm as a sickened mob

**Comment by nonamecrackers2** [comment]
This would cause a lot of mobs to pile up and wouldn't make much sense in the context of the Wither Storm "eating" it.
