### ISSUE TITLE
Placing 3 wheat on a super beacon creates a secret "cracker" item

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1408]
Item recipe and the item itself should be hidden from JEI and creative mode

would be a nice little easter egg item

**Comment by Tordx12881** [comment]
Cracker pls make this a thing

**Comment by LegendaryGodzilla** [comment]
SIIIIIIII

**Comment by nonamecrackers2** [comment]
Please read the guidelines. We do not accept easter eggs, they will be added on our own discretion.
