### ISSUE TITLE
[Bug]: Gan

### ISSUE THREAD

**Issue by TriniteTray** [nonamecrackers2/crackers-wither-storm-mod#1409]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.44

### Describe the bug

Game randomly crashed out of nowhere 
Game was not lagging

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot 2023-09-09 225813](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/142684411/717ee1fa-5e31-466c-a424-47143d963ef0)

### Mod List

Cracker's Wither Storm Mod

**Comment by TaintedBlock** [comment]
A crash log would help

**Comment by nonamecrackers2** [comment]
Please provide the crash report

**Comment by TriniteTray** [comment]
Sorry, i wouldnt know how to view the crash report, all i can say is that the "Exit Code" was 1, And i accidentally stated Optifine was installed, that is not the case. i am only using cwsm at the moment, do i need a new forge thing? or is this a thing im gonna have to regularly deal with

**Comment by SimonGamingPl** [comment]
I have this error too 
![obraz_2023-09-10_100010676](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/792f6129-6d6b-4a21-978d-4de7ff59773d)
Mr. Crakers pls fix
(im from poland so it looks a littel difreand to evryone here)

**Comment by CubeGamer647** [comment]
There's nothing anyone can do without a crash log, as we wouldn't know what's happening. Go to %appdata%/.minecraft/logs and paste the one from the session it crashed.

**Comment by watersofnazareth** [comment]
We can't fix this issue without a crash log, until one is provided I'm marking this as invalid

**Comment by GoldSlimeling91** [comment]
i've been getting similar crashes (it sometimes crashes discord at the same time too)

i would post a crash log but it just refuses to grant one, i literally just had one of these and it didnt supply me with a report for some reason, i'll try to see if i can get the game output to show me anything but yeah this crash is really weird

Edit: it crashed google chrome too, crazy

**Comment by NinjaSam5399** [comment]
Thats mod compatibility issue.

**Comment by myron-obsolete-account** [comment]
> Thats mod compatibility issue.

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/93872888-0d98-4250-badc-72e14601a158)

**Comment by nonamecrackers2** [comment]
Closing until a crash report is provided.
