### ISSUE TITLE
Enderman Interaction

### ISSUE THREAD

**Issue by IntrovertedGamer** [nonamecrackers2/crackers-wither-storm-mod#141]
When The Witherstorm reaches phase 6, it starts becoming a little bit faster, to the point where a player who hasn't gotten a Horse will likely fall victim to it.

Fortunately, escape isn't hopeless for the player, Endermen will start to notice that flying monstrosity absorbing blocks in the sky, becoming hostile towards it from 32 blocks away, Like in MCSM, they attack by teleporting onto it and ripping apart the blocks it absorbed, it won't actually damage the Witherstorm but it will temporarily stop it from chasing the player.

**Comment by SSgamingYT** [comment]
oooooo I think this would go good I hope he adds it

**Comment by nonamecrackers2** [comment]
#113 [my response to the endermen thing](https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/113#:~:text=I%20would%20love%20to%20do%20the%20endermen%20thing%2C%20but%20it%20would%20be%20extremely%20hard%20to%20match%20up%20endermen%20positions%20with%20the%20wither%20storm%20model%2C%20due%20to%20how%20rendering%20and%20entity%20models%20are%20done.)
