### ISSUE TITLE
[Suggestion]: Evolution Update Part 2 Suggestions:

### ISSUE THREAD

**Issue by mythicplays** [nonamecrackers2/crackers-wither-storm-mod#1410]
### Desription of feature request

1. Phase 4 with big tentacles, another subphase between Phase 4 and 4.5
2. More subphases between Phase 0-3 not just the 1.1 and 2.1 which is a slightly bigger phase 1 & 2
3. Wither Storm infinitely growing if not formidibombed(Phase 5.5+) or command block not destroyed(Phase 7.5+)
4. Wither Storm theme for each Phases & Subphases(like wither_storm_phase4_theme) and the Phase 5.5 theme(wither_storm_formidibomb_theme) should get renamed to wither_storm_phase5.5_theme
Also the theme for phase 5.5 should be changed to the MCSM EP3 Wither Storm theme, the phase 7.5 wither storm theme music should be changed a bit.
5. More mcsm structures(not just the order temple spawn platform appearing at certain spawnpoint biome)

**Comment by myron-obsolete-account** [comment]
as said in #1405, please put only one suggestion per issue

**Comment by Tordx12881** [comment]
The mod will not have more rundown houses, maybe crackers adds 2 or 3 more but not MCSM ones

**Comment by nonamecrackers2** [comment]
Please read the guidelines. Only one suggestion per issue.

**Comment by mythicplays** [comment]
ok I didn't read properly
