### ISSUE TITLE
[Bug]: Wither Storm body dissolving animation does not play on death

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1411]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.44

### Describe the bug

When the WS dies, in the death animation the main storm's body won't play the dissolving animation and is just stuck on the last "frame".

### Steps to Reproduce

Kill the Wither Storm

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

https://www.youtube.com/watch?v=k-iYF_Alc_Y

### Mod List

Mob Battle Mod
Just Enough Items
Pehkui
Rubidium
Xaero's World Map
Citadel
MixinExtras
Panoramica
Additional Structures
Create: Steam 'n' Rails
3dSkinLayers
Cloth Config v10 API
Forge
Supplementaries
Konkrete
Minecraft
Moonlight Library
Blackwolf Library
Jade
Kotlin For Forge
NotEnoughAnimations Mod
Cataclysm Mod
Flywheel
Oculus Flywheel Compat
Create
Xaero's Minimap
Oculus
Create Stuff & Additions
Dramatic Doors
More Trapdoor
Cracker's Wither Storm Mod
WorldEdit
Item Pickup Particle Disable
MrCrayfish's Furniture Mod
Automobility
Valkyrien Skies 2
VS Eureka Mod

**Comment by Pandaboi25x** [comment]
did you do /kill?

**Comment by myron-obsolete-account** [comment]
> did you do /kill?

`/kill` just removes the entity (death animation won't play)

**Comment by Pandaboi25x** [comment]
> > did you do /kill?
> 
> `/kill` just removes the entity (death animation won't play)

ok so you didnt use that command uhh gonna let crackers do the thing :wswide:

**Comment by myron-obsolete-account** [comment]
> > > did you do /kill?
> > 
> > 
> > `/kill` just removes the entity (death animation won't play)
> 
> ok so you didnt use that command uhh gonna let crackers do the thing :wswide:

did you even watch the not-screenshot I attached to screenshots? the animation does play, but like, the texture animation of the body dissolving does not. idk

**Comment by Pandaboi25x** [comment]
> > > > did you do /kill?
> > > 
> > > 
> > > `/kill` just removes the entity (death animation won't play)
> > 
> > 
> > ok so you didnt use that command uhh gonna let crackers do the thing :wswide:
> 
> did you even watch the not-screenshot I attached to screenshots? the animation does play, but like, the texture animation of the body dissolving does not. idk

oh no i didnt see it sorry, but yea i really dont know what happend there

**Comment by Composer-Hu** [comment]
It's amazing, and the release feels like many change from the last beta.

**Comment by nonamecrackers2** [comment]
Is the mod resources in the resource pack menu at the top?

**Comment by myron-obsolete-account** [comment]
it was infact not at the top, it resolved the issue, thank you
also I wonder why the issue was not present when I had shaders enabled (as seen in the attached video in #1412), for some reason the animation played there just fine (the body duplication issue is still not solved though but that's to be discussed in #1412)

**Comment by nonamecrackers2** [comment]
That's is quite strange, but glad that was the cause
