### ISSUE TITLE
[Bug]: Wither Storm body duplicated in world when dying (with shaders enabled)

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1412]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.44

### Describe the bug

When killing the WS while having shaders enabled (in my case it's with rubidium and oculus, not optifine) the bodies of the WS somehow get duplicated and are stuck to my POV/facing rotation.

### Steps to Reproduce

1. enable shaders (I use Complementary)
2. kill WS
3. see

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

https://www.youtube.com/watch?v=bOv8J5wxEFw

### Mod List

Mob Battle Mod
Just Enough Items
Pehkui
Rubidium
Xaero's World Map
Citadel
MixinExtras
Panoramica
Additional Structures
Create: Steam 'n' Rails
3dSkinLayers
Cloth Config v10 API
Forge
Supplementaries
Konkrete
Minecraft
Moonlight Library
Blackwolf Library
Jade
Kotlin For Forge
NotEnoughAnimations Mod
Cataclysm Mod
Flywheel
Oculus Flywheel Compat
Create
Xaero's Minimap
Oculus
Create Stuff & Additions
Dramatic Doors
More Trapdoor
Cracker's Wither Storm Mod
WorldEdit
Item Pickup Particle Disable
MrCrayfish's Furniture Mod
Automobility
Valkyrien Skies 2
VS Eureka Mod

**Comment by Composer-Hu** [comment]
Yes, this issue has been around since the beta, but because it's sporadic I'm not sure if it's me personally so I don't have feedback. And I have this problem with shaders not enabled.

**Comment by nonamecrackers2** [comment]
#1207

**Comment by myron-obsolete-account** [comment]
HUH
