### ISSUE TITLE
Tractor Beam Color

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1414]
### Minecraft Version

1.19.4

### Mod Version

3.3

### Mod Loader

Forge

### Mod Loader Version

1.19.2, 45.1.0

### Describe the bug

When I look in the config, there is no place to change the Wither Storm's tractor beams' color. In other versions of the mod, there was an option to change the tractor beams' color. Was it removed or just renamed without "Beam", "Tractor", or "Color" in it?

### Steps to Reproduce

Look anywhere in the config.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Cracker's Wither Storm Mod

**Comment by TaintedBlock** [comment]
You now need a resource pack to change these kinds of things.

**Comment by WitherBean** [comment]
I looked in the assets, there are no textures for the sky color or the tractor beams. Are they in the mod shaders?

**Comment by myron-obsolete-account** [comment]
> I looked in the assets, there are no textures for the sky color or the tractor beams. Are they in the mod shaders?

textures are not the only thing you can change
there are also lines of code to change colors of tractor beam and sky darkening for this example

**Comment by WitherBean** [comment]
In the shaders?

**Comment by myron-obsolete-account** [comment]
idk

**Comment by WitherBean** [comment]
There are no files that can change the color of the tractor beams that I could find.

**Comment by WitherBean** [comment]
> > I looked in the assets, there are no textures for the sky color or the tractor beams. Are they in the mod shaders?
> 
> textures are not the only thing you can change there are also lines of code to change colors of tractor beam and sky darkening for this example

What file would that be in?

**Comment by Composer-Hu** [comment]
{
	"tractor_beams":
	{
		"red": 18,
		"green": 21,
		"blue": 105
	},
	"tractor_beams_night":
	{
		"red": 30,
		"green": 8,
		"blue": 90
	},
	"night_shine":
	{
		"red": 60,
		"green": 113,
		"blue": 174,
		"alpha": 140
	},
	"sky_colors": {
		"5": {
			"day":
			{
				"sky_darken_clouds":
				{
					"red": 65,
					"green": 47,
					"blue": 95
				},
				"sky_darken":
				{
					"red": 20,
					"green": 0,
					"blue": 24
				},
				"sky_darken_fog":
				{
					"red": 99,
					"green": 61,
					"blue": 96
				}
			},
			"night": 
			{
				"sky_darken_clouds":
				{
					"red": 28,
					"green": 32,
					"blue": 120
				},
				"sky_darken":
				{
					"red": 0,
					"green": 0,
					"blue": 36
				},
				"sky_darken_fog":
				{
					"red": 42,
					"green": 43,
					"blue": 158
				}
			}
		},
		"6": {
			"day":
			{
				"sky_darken_clouds":
				{
					"red": 156,
					"green": 98,
					"blue": 148
				},
				"sky_darken":
				{
					"red": 40,
					"green": 24,
					"blue": 56
				},
				"sky_darken_fog":
				{
					"red": 137,
					"green": 93,
					"blue": 148
				}
			},
			"night":
			{
				"sky_darken_clouds":
				{
					"red": 28,
					"green": 32,
					"blue": 120
				},
				"sky_darken":
				{
					"red": 8,
					"green": 10,
					"blue": 37
				},
				"sky_darken_fog":
				{
					"red": 13,
					"green": 7,
					"blue": 64
				}
			}
		},
		"7": {
			"day": 
			{
				"sky_darken":
				{
					"red": 14,
					"green": 5,
					"blue": 9
				},
				"sky_darken_clouds":
				{
					"red": 0,
					"green": 0,
					"blue": 0
				},
				"sky_darken_fog":
				{
					"red": 250,
					"green": 146,
					"blue": 86
				}
			},
			"night": 
			{
				"sky_darken":
				{
					"red": 14,
					"green": 5,
					"blue": 9
				},
				"sky_darken_clouds":
				{
					"red": 0,
					"green": 0,
					"blue": 0
				},
				"sky_darken_fog":
				{
					"red": 153,
					"green": 66,
					"blue": 53
				}
			}
		}
	}
}

**Comment by Composer-Hu** [comment]
I made one, how should I share it with you?

**Comment by WitherBean** [comment]
Upload it to github or share it as a zip file.

**Comment by Composer-Hu** [comment]
[config.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12569775/config.zip)
Unzip it and put it in the witherstormmod folder under resourcepacks

**Comment by WitherBean** [comment]
in assets?

**Comment by WitherBean** [comment]
Thank you!

**Comment by Composer-Hu** [comment]
I'm glad I was of help.

**Comment by BluePineappleGuy** [comment]
this should probably be reverted or have some hint in-game to tell you how to change them. its very confusing to players who played older versions.

**Comment by nonamecrackers2** [comment]
There's an entire page of documentation about it: https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Advanced-Modification

**Comment by BluePineappleGuy** [comment]
> There's an entire page of documentation about it: https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Advanced-Modification

just so it doesnt confuse players, you should add a link somewhere in-game for people to find it

**Comment by MakuTln** [comment]
> I'm glad I was of help.

yo it still doesnt work i tried everything even the documentation page and it doesnt change
