### ISSUE TITLE
[Suggestion]: provoked when beamed

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1416]
### Desription of feature request

When enemies get beamed by an head they should be provoked by the head that pulls them. 

By provoked I mean the behavior as if, for example, a skeleton is hit by another skeleton then it is also gets provoked and shoots back

**Comment by myron-obsolete-account** [comment]
creepers explode infront of heads already
so do skeletons shoot it with arrows, attempting to harm it

**Comment by nonamecrackers2** [comment]
Skeletons already do this in the latest release

**Comment by FunkyPotao** [comment]
Also make snowman attack THE head its getting sucked up by

**Comment by nonamecrackers2** [comment]
You should make a new suggestion for that then
