### ISSUE TITLE
Black Everything

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1417]
### Minecraft Version

1.19.4

### Mod Version

3.3

### Mod Loader

Forge

### Mod Loader Version

1.19.4, 45.1.0

### Describe the bug

A bug happened!

### Steps to Reproduce

Run /witherstormmod phase set @w 4.5
Run /reload

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots
![Screen Shot 2023-09-11 at 11 34 23 AM](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114886300/621f52eb-f444-47d2-9ea0-1007e49b610a)

### Mod List

Cracker's Wither Storm Mod

**Comment by nonamecrackers2** [comment]
Please provide some screenshots

**Comment by watersofnazareth** [comment]
Well the issue is you're using 1.19.4 on 1.19.2

**Comment by nonamecrackers2** [comment]
Oh yeah I didn't realize that

**Comment by nonamecrackers2** [comment]
Strange. It appears your using some sort of resourcepack, could you list the resource packs you are using?

**Comment by WitherBean** [comment]
Witherstormmod New Textures.

**Comment by nonamecrackers2** [comment]
Have you tried removing them to see if that solves the issue?

**Comment by nonamecrackers2** [comment]
Closing until more information is given
