### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jan88od** [nonamecrackers2/crackers-wither-storm-mod#1418]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

Unsure, must be 47.0.45?

### Describe the bug

So, i've launched game, this console appeared, it was saying: [19:57:02] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'witherstormmod', Expected range: '[47.1.0,)', Actual version: '47.0.45'
As I understood, you have config that is outdated. I tried everything to fix it, added optifine and removed it, reloaded mod, etc.
When I started first time I had problem with some configs, such as Terrablender and clouth api, i just changed them on older version and it worked.

### Steps to Reproduce

1. Go to 'front page'
2. Click on 'play'
3. Scroll down to 'Console panel appears, scrolling down to middle'

### Crash Reports/Logs

19:57:02] [main/ERROR]: Missing or unsupported mandatory dependencies: 	Mod ID: 'forge', Requested by: 'witherstormmod', Expected range: '[47.1.0,)', Actual version: '47.0.45'

### Is OptiFine installed?

- [X] OptiFine is installed

### Screenhots

https://drive.google.com/file/d/1QVvc2avnsu14OwcxXRZ9gnWuIjblxFw1/view?usp=sharing

### Mod List

![Знімок екрана (665)](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144617472/b3b9a871-870c-4d81-8c13-aee413a4c0d4)

**Comment by nonamecrackers2** [comment]
You need to update your forge version to 47.1.0
