### ISSUE TITLE
[Bug]: It crashes a lot

### ISSUE THREAD

**Issue by minecrafter354** [nonamecrackers2/crackers-wither-storm-mod#1419]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.46

### Describe the bug

After a little while it crashes, i've tried to close all of my programs and it still crashes after a while.
Basically i've tried everything and **it still crashes.** I don't know why it crashes other than it using all of my memory up.

### Steps to Reproduce

1. Set memory to 5 Gigabytes of ram
2. Get inside of the wither storm and go into spectator mode
3. Move around the inside/in the walls
4. See the crash report (If possible)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Just the wither storm mod 4.0
witherstormmod-1.20.1-4.0.jar

**Comment by nonamecrackers2** [comment]
Please provide the crash report, we can not assist you if don't do so.

**Comment by minecrafter354** [comment]
It was my computer, so i think it was because of my memory, only having 8 gigabytes was the problem.
Just bad memory

**Comment by minecrafter354** [comment]
I'm sorry for the inconvenience of no crash report.
