### ISSUE TITLE
Distant renderer only renders teeth and eyes 

### ISSUE THREAD

**Issue by ItsZed01** [nonamecrackers2/crackers-wither-storm-mod#142]
Basically, when I use Chocapic's Toaster Edition Shaders, only the teeth and eyes render.

I am using 1.16.5 1.0.2.1.

**Describe the bug**
Once the Wither Storm goes in the distant render, it almost completely disappears except the teeth and eyes.

How to reproduce the bug:

1. Download Optifine & Chocapic Toaster Edition.
2. Click on options.
3. Click on video settings.
4. Then, click on shaders, and select the shader.
5. Load it.

**Crash Reports / Logs**
There weren't any crashes.

Screenshot (Hilarious)
![unknsadasdown](https://user-images.githubusercontent.com/81433526/175824408-9894ab63-536a-4db4-947d-a96a7542dcaf.png)

**Comment by nonamecrackers2** [comment]
I can't really provide support for shaders.  Do you have the have fabulous graphics setting enabled?
