### ISSUE TITLE
[Bug]: Sickened mobs can be damaged by wither effect

### ISSUE THREAD

**Issue by CubeGamer647** [nonamecrackers2/crackers-wither-storm-mod#1420]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.46

### Describe the bug

All sickened mobs (not symbiont or tentacles) can be damaged by the wither effect (delivered via potion) despite giving wither themselves.

### Steps to Reproduce

1. Summon any sickened mob
2. Throw a splash potion of decay at them
3. Watch them take damage

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM
JEI

**Comment by nonamecrackers2** [comment]
Will be fixed in the next release
