### ISSUE TITLE
[Suggestion]: Removal of new command block tools

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1422]
### Desription of feature request

While I like the newer versions of command block tools (iron, wood, gold, etc.), I think they make the progression too easy and should probably stay as an addon. That too, the stats are improper making iron command block better than diamond command block. 
Getting the diamonds for the command block tool is one of the main parts of progression, and this kind of removes that by allowing you to use your iron sword instead, or even a stick and 2 planks. Overall it feels like it should stay as an addon mod and not part of the main one.

**Comment by nonamecrackers2** [comment]
We won't be removing them but we can consider balancing them. While iron may seem better, they do have higher cooldowns which should help make them a bit more balanced.

**Comment by BluePineappleGuy** [comment]
> While iron may seem better, they do have higher cooldowns which should help make them a bit more balanced.

the attack damage should still be a bit lower to match diamond.
