### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Hadryan505** [nonamecrackers2/crackers-wither-storm-mod#1423]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.37

### Describe the bug

i can't seem to spawn the wither in any form
When spawning him it just dissapears and nothing happens
Using the withered beacons makes the game crash, when i enter the world again the wither isn't there
And using the /summon command doesn't work too

### Steps to Reproduce

1. Go to any world
2. Spawn the wither in any form
3. See error

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot_4](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144624610/9e1dfebd-d319-46c0-be3c-f306ade3a348)
![imagen](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144624610/378f84bd-0f7b-418a-95e0-c24d9bfa88ca)

### Mod List

![imagen](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144624610/344e5e17-3149-49b5-9cac-8f4ae4e9ef4b)
![imagen](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144624610/ef07a593-42dd-4f64-8560-8cce47671280)
![imagen](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144624610/a687a497-55bf-40ae-bdef-0cbf5f2b8320)

**Comment by nonamecrackers2** [comment]
Please provide the crash report.

**Comment by nonamecrackers2** [comment]
Try using the recommended forge version, this appears to have been the fix for some.

**Comment by NinjaSam5399** [comment]
💀
