### ISSUE TITLE
[Suggestion]: Different music for F-bombing/entering the bowels

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1424]
### Desription of feature request

Currently, when the storm is ready to be formidibombed/the hole has appeared, it plays the track "WS rises". My idea is to instead play from 4:01 to 5:39 of the official theme (https://www.youtube.com/watch?v=WvZ3hwwRSkY), then cut back to 2:25 and play the rest of the default theme from there.

**Comment by LegendaryGodzilla** [comment]
you can use a texture pack to change them for example i made a texture pack that changes the storms themes into the netflix version

**Comment by BluePineappleGuy** [comment]
> you can use a texture pack to change them for example i made a texture pack that changes the storms themes into the netflix version

pls send me that pack i love the netflix theme

**Comment by nonamecrackers2** [comment]
Going to be keeping the current themes, as already stated you can use a resource pack to change them

**Comment by LegendaryGodzilla** [comment]
> > you can use a texture pack to change them for example i made a texture pack that changes the storms themes into the netflix version
> 
> pls send me that pack i love the netflix theme

What's your Discord idk how to send things here

**Comment by BluePineappleGuy** [comment]
> > > you can use a texture pack to change them for example i made a texture pack that changes the storms themes into the netflix version
> > 
> > 
> > pls send me that pack i love the netflix theme
> 
> What's your Discord idk how to send things here

i dont have one, but you can drag and drop the zip file while commenting to send it

**Comment by LegendaryGodzilla** [comment]
> 

Okay

**Comment by BluePineappleGuy** [comment]
i dont see it if you sent it
maybe we should continue this in the discussions page

**Comment by LegendaryGodzilla** [comment]
> 

I was doing something

**Comment by BluePineappleGuy** [comment]
oh ok

**Comment by LegendaryGodzilla** [comment]
> oh ok
[Netflix Wither Storm Theme.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12570169/Netflix.Wither.Storm.Theme.zip)

**Comment by BluePineappleGuy** [comment]
tysm

**Comment by LegendaryGodzilla** [comment]
> 

np

**Comment by mythicplays** [comment]
> > oh ok
> > [Netflix Wither Storm Theme.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12570169/Netflix.Wither.Storm.Theme.zip)

Can you add the "Bowels Exposed Netflix Theme",  This video: https://youtu.be/veFoUze5LAA?si=wYK_1isfzsyM-6dT

**Comment by LegendaryGodzilla** [comment]
> > > oh ok
> > > [Netflix Wither Storm Theme.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12570169/Netflix.Wither.Storm.Theme.zip)
> 
> Can you add the "Bowels Exposed Netflix Theme", This video: https://youtu.be/veFoUze5LAA?si=wYK_1isfzsyM-6dT

Sure

**Comment by LegendaryGodzilla** [comment]
> > > oh ok
> > > [Netflix Wither Storm Theme.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12570169/Netflix.Wither.Storm.Theme.zip)
> 
> Can you add the "Bowels Exposed Netflix Theme", This video: https://youtu.be/veFoUze5LAA?si=wYK_1isfzsyM-6dT
[Netflix_Wither_Storm_Theme.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12579729/Netflix_Wither_Storm_Theme.zip)

**Comment by BluePineappleGuy** [comment]
should we open a discussion for this instead of using the issue?
