### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by s171sonic** [nonamecrackers2/crackers-wither-storm-mod#1425]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.29

### Describe the bug

I cant spawn the wither storm and using the withered beacon to spawn it in crashes the game

### Steps to Reproduce

1.Get the withered beacon
2. Put the three wither skulls
3.watch the game crash

### Crash Reports/Logs

https://pastebin.com/LbDs141r

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

<img width="1125" alt="Screenshot 2023-09-10 032608" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144632832/3db2b7a8-5d2b-4214-b145-c4262df8a1df">
<img width="1207" alt="Screenshot 2023-09-10 032618" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144632832/300a2265-2ba0-4e67-8c88-085723995d0c">
<img width="882" alt="Screenshot 2023-09-10 032623" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144632832/34e30a12-1a18-446a-be03-cedd9ff1e141">
<img width="321" alt="Screenshot 2023-09-10 032639" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144632832/8f99fbf4-b3c3-48b9-b697-9ed2968d5933">
<img width="682" alt="Screenshot 2023-09-10 032643" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144632832/304eb9d6-03b4-4400-8e43-f8dabe407dc3">
<img width="937" alt="Screenshot 2023-09-10 032557" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144632832/907b4b29-99db-489a-88aa-f5a57a7a8ed5">

### Mod List

none

**Comment by TaintedBlock** [comment]
Are you on peaceful? If not, what mods do you have installed?

**Comment by s171sonic** [comment]
> Are you on peaceful? If not, what mods do you have installed?

I did not have peaceful mode on and I don't have any other mods installed

**Comment by nonamecrackers2** [comment]
Try using the recommended forge version
