### ISSUE TITLE
New command block tools - no use in the game - other materials better than diamond

### ISSUE THREAD

**Issue by Tant33** [nonamecrackers2/crackers-wither-storm-mod#1429]
### Desription of feature request

I was checking the new update and saw a lot of new tools. To be honest I don't like it really because it wasn't in mc storymode. I know the wither symbiont also isn't in that game, but it has a purpose. You need to kill it before getting the command book. Most people will probably already have at least 1 diamond tool at this stage of the game.

Next the tools are also pretty unbalanced. 
1. an iron command axe does more dps than a diamond command axe?
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/111907054/8eb78f1d-4ed6-4f37-950b-182282b23a9b)
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/111907054/65c12d80-1f40-4f87-959c-2f4b48053fd5)
2. noboy is going to waste those books on stone/wooden tools. If they can get golden ones with infinite durability.

**Comment by TaintedBlockmObile** [comment]
You do know that cwsm isn't following story mode right? Btw the tools do have abilities the others don't have. They are all different.

Not to mention sometimes people don't even get diamond in time and need to craft a command weapon. So diamond really isn't needed for a weapon. Also think about the memes people will make just because command block wooden hoes are funny lmao.

**Comment by CubeGamer647** [comment]
Suggestions regarding accuracy to mcsm will be ignored, and anyway, this issue has so many duplicates. Each set has different advantages and drawbacks, it's completely intentional. Iron has high damage but slow speed

**Comment by LegendaryGodzilla** [comment]
:WSBruh:

**Comment by nonamecrackers2** [comment]
> Suggestions regarding accuracy to mcsm will be ignored, and anyway, this issue has so many duplicates. Each set has different advantages and drawbacks, it's completely intentional. Iron has high damage but slow speed

This exactly. If you have some specific ideas on how we should rebalance them, please let us know in a new issue. Also you can check out what their advantages/drawbacks are in the [update changelog](https://github.com/nonamecrackers2/cwsm-update-info/blob/main/1.19.4-3.3-changelog.md)

**Comment by BluePineappleGuy** [comment]
its hard to tell what the advantages or powers are. some sort of ingame guide could help, otherwise it kinda confuses people why some seem bad and others good.

**Comment by nonamecrackers2** [comment]
That's true

**Comment by Tant33** [comment]
Maybe wooden tools can have a permanent speed effect while holding - wood is light.
Stone tools smelt everything they mine (iron ore, cobblestone, etc).
Iron tools slow but more damage (possibly also slowness).
Golden tools fast (also for mining) but weak in damage.
diamond tools balanced.
