### ISSUE TITLE
the two small wither storms completely disappear when far away  

### ISSUE THREAD

**Issue by bassbubble** [nonamecrackers2/crackers-wither-storm-mod#143]
**Minecraft version**
1.18.2

**Mod version**
latest

**Describe the bug**
the small ones are just gone, not even picking up blocks or mobs

**To Reproduce**
im not sure how to

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by nonamecrackers2** [comment]
I'm unable to reproduce after some changes were made. I may have fixed this issue without knowing it. I believe your problem is that they get stuck in terrain and that they aren't teleporting back to the main wither storm and get unloaded, which should be fixed.
