### ISSUE TITLE
[Suggestion]: Netherite Command Block Tools

### ISSUE THREAD

**Issue by Asaredapvp2** [nonamecrackers2/crackers-wither-storm-mod#1430]
### Desription of feature request

As said in title, Netherite Command Block Tools so we can upgrade every tool to Command Block Level.

**Comment by CubeGamer647** [comment]
If this was going to be added, I feel like it would already be in the update. It's probably too overpowered.

**Comment by TaintedBlockmObile** [comment]
These aren't getting added do to them being too overpowered.

**Comment by nonamecrackers2** [comment]
#261 (However we may consider them in a later release, as tainted stated they'd need special treatment since they would be very overpowered)
