### ISSUE TITLE
[Suggestion]: More color customizability

### ISSUE THREAD

**Issue by CubeGamer647** [nonamecrackers2/crackers-wither-storm-mod#1432]
### Desription of feature request

With the recent update, resource packs now have the ability to change sky and night backlight colors. I think there should also be some way to customize the fog in the bowels using a resource pack so people can change the entire color scheme.
If possible, it would also be nice to allow the the texture of the wither storm to change with the day/night cycle so that the eyes can match the color of dynamic tractor beams.

**Comment by TaintedBlock** [comment]
I like this idea

**Comment by sm644me** [comment]
This is already possible by using a data pack and changing the bowels biome fog color, but having all of the color customizations in a single resource pack could be nice for people who want to drastically overhaul the look of the Storm without changing anything else.

**Comment by CubeGamer647** [comment]
> This is already possible by using a data pack and changing the bowels biome fog color

I figured as much. I looked through and didn't see anything about fog color but to be fair I rarely mess with data packs. And having it all in a resource pack would make it more accessible to those who play multiplayer.

**Comment by nonamecrackers2** [comment]
The bowels fog config will be added in the next major release. Adding the ability for separate textures based on the day cycle is currently not on my agenda for implementing but it's an interesting idea.
