### ISSUE TITLE
[Suggestion]: Make it so smaller wither storms follow larger wither storms

### ISSUE THREAD

**Issue by BladeLightsteel** [nonamecrackers2/crackers-wither-storm-mod#1433]
### Desription of feature request

If there happens to be more than one wither storm (e.g. somebody in creative summons more) then the lesser wither should follow  the larger wither. Like phase 4 follows a phase 7.  There should be a config to disable it (it would be off by default), and config for following distance. Add different following types like follow like a severed storm bit, have it be in the ring, follow behind it, Infront, etc.

Not sure how hard this would be to add, but it doesn't seem too hard because you can probably reuse some of the code from a severed storm.

**Comment by BladeLightsteel** [comment]
forgot to mention, if they're the same phase they don't follow each other. And if theres two withers of the same phase and one thats lower then it would go to the one with the most phase progress (e.g. theres two phase 5 and one phase 4, the phase 4 will follow the phase 5 with 59% instead of 23%)

**Comment by TaintedBlock** [comment]
I don't understand why this would even be a thing. I would understand more then 2 segments but the Wither Storms have their own command block.

**Comment by BladeLightsteel** [comment]
i mean if the f bomb made more segments each time you used it then idk

**Comment by TaintedBlockmObile** [comment]
> 

That wouldn't be the best idea since 9 heads is already more then enough to be running from. And it would cause lag from the clusters

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release. There won't be any of the fancy ring formations as suggested, just the typical ultimate target logic.
