### ISSUE TITLE
[Bug]: The Wither Storm's `TrackedEntities` NBT can freeze the server/client sometimes

### ISSUE THREAD

**Issue by sm644me** [nonamecrackers2/crackers-wither-storm-mod#1434]
### Minecraft Version

1.19.4

### Mod Version

3.3

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Describe the bug

At least, I think that's the issue here. After using a bunch of commands to modify and read the Wither Storm's data, the server begins to lag. At this point, using `/data get entity @w` freezes the client, and so does `/data get entity @w TrackedEntities`. If this isn't done, the lag rapidly intensifies until the server entirely freezes. The client behaves as normal during this time, but no server ticks happen until the server is forcibly closed. When the server is reopened (from the last autosave, of course), the lag quickly resumes and seems unstoppable unless the Wither Storm is despawned or killed before the server freezes again.

My guess is that there's no failsafe in CWSM to prevent the `TrackedEntities` NBT from becoming unmanageably large. I really don't know what's happening to cause that NBT to have issues, but I do know that running `/kill @e[type=item]` every tick prevents the error from occurring. Block clusters contribute to lag, sometimes very significantly, but they don't seem to freeze the server on their own.

The only unusual element of my log files is as follows: "[Render thread/WARN] net.minecraft.client.multiplayer.ClientPacketListener/]: Received passengers for unknown entity", repeated several times before the server freezes and while it lags prior to freezing. This happens with both items and block clusters. Maybe `TrackedEntities` is actually just a symptom, and there's some passenger system with block clusters and items that makes the server so unhappy?

### Steps to Reproduce

I have no idea, but it happens in the development version I'm making of Explorer's Eve enough to make certain parts of the pack entirely unplayable. I don't think it's entirely my own functions, since no particular function seems to cause the error. Sometimes the game freezes, other times it doesn't lag at all. I assure you, if I could find a consistent way to make this happen, I'd put it here.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

The full modlist of Explorer's Eve. If needed, I could try and extract just the functions relevant to a part of the pack that causes this issue a lot. However, this issue never happened prior to updating CWSM to 3.3.

**Comment by nonamecrackers2** [comment]
I might have an idea why, I’ll have to investigate it further though

**Comment by nonamecrackers2** [comment]
Found the problem, will be fixed in the next release
