### ISSUE TITLE
Withered Iron Golems take fall damage.

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1435]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

4.0

### Describe the bug

Withered Iron Golems take fall damage.

### Steps to Reproduce

1. Summon Withered Iron Golem
2. Watch it die of fall damage because you summoned too high

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

NONE

**Comment by BluePineappleGuy** [comment]
they are also strangely immune to lava, unlike regular golems. not sure if this is intended but i'm pretty sure sickened mobs take fire damage.

guess they might not in the new update

**Comment by myron-obsolete-account** [comment]
don't normal iron golems also take fall damage?

**Comment by BluePineappleGuy** [comment]
> don't normal iron golems also take fall damage?

nope, try it yourself. they're immune to fall damage and drowning, hence why iron farms always make use of lava.

**Comment by BluePineappleGuy** [comment]
also just checked, they're immune to lava when other sickened mobs arent.

**Comment by GoldSlimeling91** [comment]
can confirm this bug, i witnessed one take fall damage while messing with them with some friends
its very cursed seeing an iron golem take fall damage

**Comment by nonamecrackers2** [comment]
Will be fixed in the next release
