### ISSUE TITLE
[Suggestion]: Sickened Mooshrooms should be shearable

### ISSUE THREAD

**Issue by CubeGamer647** [nonamecrackers2/crackers-wither-storm-mod#1436]
### Desription of feature request

Similarly to how vanilla mooshrooms can be sheared to provide a regular cow and the corresponding mushrooms, you should be able to shear a tainted mooshroom to turn it into a sickened cow and receive tainted mushrooms.

**Comment by NinjaSam5399** [comment]
good idea

**Comment by nonamecrackers2** [comment]
Will be implemented in the next release, alongside the ability to "milk" them with a bowl to get suspicious stew with the wither effect.
