### ISSUE TITLE
[Suggestion]: Color Config For The Wounds

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#1437]
### Desription of feature request

As the title says, the wounds of the wither storm (Including the purple glowing thing flying around the wither storm) should have color config. They should be a separate Color Configure.

**Comment by CubeGamer647** [comment]
I think those can be customized through actual texturing, so that wouldn't be necessary. I'm not completely sure if the hole to the bowels can be textured though.

**Comment by myron-obsolete-account** [comment]
at this point every actual texture with purple witherstorm-parts could just be grayscale so you can customize everything automatically

**Comment by BluePineappleGuy** [comment]
> at this point every actual texture with purple witherstorm-parts could just be grayscale so you can customize everything automatically

the eyes cant be, and the wounds might be difficult, as tinting the wounds might tint the whole mass due to them sharing a texture. the eyes share a texture with the teeth making it impossible to tint, as the teeth would get tinted too.

**Comment by NinjaSam5399** [comment]
ok

**Comment by NinjaSam5399** [comment]
but it is probably still a good idea.

**Comment by nonamecrackers2** [comment]
This can be done with texture packs

**Comment by NinjaSam5399** [comment]
ok
