### ISSUE TITLE
[Suggestion]: command block tools hurting early phases

### ISSUE THREAD

**Issue by HammedBurngur** [nonamecrackers2/crackers-wither-storm-mod#1438]
### Desription of feature request

the command block tools should deal massive to damage to the wither storm if the command block is exposed

**Comment by TaintedBlock** [comment]
Wouldn't make sense because the tools aren't supposed to be obtained so early and the hunchback phases are not meant to be killed.

**Comment by BluePineappleGuy** [comment]
ressummoned storm config lets it happen

**Comment by TaintedBlock** [comment]
Still doesn't mean they are meant to be killed so early. Especially since there isn't a reward for doing it.

**Comment by BluePineappleGuy** [comment]
good point

**Comment by nonamecrackers2** [comment]
Yeah as tainted said, you can’t obtain the command block tools that early, and while you could for the resummoned wither storm, it’s not intended to be killed.
