### ISSUE TITLE
[Suggestion]: New Wither Storm Head Spawning Animation

### ISSUE THREAD

**Issue by Asaredapvp2** [nonamecrackers2/crackers-wither-storm-mod#1440]
### Desription of feature request

It would be cool when the Wither Storm evolves to phase 4 or after exploded with F Bomb and new Wither Heads show up in MCSM style, like after the Endercon roof falls and the heads just appear coming out of the body and Roaring. Just like in this GIF https://tenor.com/bWWSX.gif

**Comment by TaintedBlockmObile** [comment]
This is quite unlikely to happen since the heads I believe are coded in and not made in a program like blockbench.

**Comment by BluePineappleGuy** [comment]
you could give the animation to have no beam, and be inside the mass, which should be possible to animate, then have them each do the animation shown.

**Comment by TaintedBlockmObile** [comment]
> you could give the animation to have no beam, and be inside the mass, which should be possible to animate, then have them each do the animation shown.

Well seeing that they are suggesting something like storymode, it would be darn near impossible since crackers would have to hand code the animation.

**Comment by nonamecrackers2** [comment]
#542
