### ISSUE TITLE
[Suggestion]: Extra loot/Bowels structures in WS death remains

### ISSUE THREAD

**Issue by Void866** [nonamecrackers2/crackers-wither-storm-mod#1441]
### Desription of feature request

In the remains of the Wither storm that are dropped to the floor upon its death, maybe there's a chance a few of the remains have chests from them with extra bowels loot? An extra reward for defeating the wither storm? 

Perhaps these remains with loot can be actually bigger than the normal ones and have a structure spawn within them, and the chests and loot inside. The structures could be from the same ones that are used in the bowels. 

(Just makes the remains more useful instead of being a large mess after the witherstorm death lol)

**Comment by TaintedBlock** [comment]
Well the chunks that fall off is supposed to be a grave for the eldritch beast you spent hours preparing for and finally killed. I don't see this happening since bowels loot is already over powered and there is a lot of it.

**Comment by nonamecrackers2** [comment]
I like the chests idea but I won't be including additional structures in the clusters. Will be implemented in the next major release.
