### ISSUE TITLE
[Suggestion]: late hero advancement

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1442]
### Desription of feature request

If you beat the ws in a village where there are no more villagers you would get the late hero advancement *and get nothing* but if there is a nearby village and if you kill the ws nearby with villagers innit you would just get hero of the village **or just make it not give you any advancements if theres a village with no more villagers left but i feel like an advancement would be cool** 

Description of the late hero advancement: Defeat the wither storm with no villagers in a village.

I might fix this if it made no sense at all lol

:jess:

**Comment by LegendaryGodzilla** [comment]
late hero effect when!1!1

**Comment by Pandaboi25x** [comment]
> late hero effect when!1!1

But why

**Comment by Laughingcat27** [comment]
thats pretty cool and creepy

**Comment by LegendaryGodzilla** [comment]
> > late hero effect when!1!1
> 
> But why

🔪

**Comment by GoldSlimeling91** [comment]
Far as i know you already get Hero of the Village when you defeat the storm near a village

**Comment by Pandaboi25x** [comment]
> Far as i know you already get Hero of the Village when you defeat the storm near a village

yea but theres a chance there wont be any villagers cuz they died cuz of the ws so you would get late hero advancement

**Comment by nonamecrackers2** [comment]
This would be most cases so you would rarely ever get hero of the village. I’m going to be leaving this suggestion out for now.

**Comment by Pandaboi25x** [comment]
> This would be most cases so you would rarely ever get hero of the village. I’m going to be leaving this suggestion out for now.

Darn
