### ISSUE TITLE
[Suggestion]: QOL features of the debris during phase 1-3

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#1443]
### Description of feature request

It would make sense if the debris around the wither storm are smaller and much closer to the wither storm, because it doesn't look good for phase 2-3 to have no near debris and it just looks less terrifying. You could still keep the outside debris if you want, or add a config setting for much closer block cluster. The title isn't a typo, I'm just saying to add much lesser debris during phase one and significantly adds a bit more when progressing the hunchback phases.

**Comment by TaintedBlock** [comment]
This probably wont happen since the debris is purposely for those phases. But maybe

**Comment by nonamecrackers2** [comment]
Yeah I personally prefer the debris as it is right now and don’t have plans to change it

**Comment by TaintedBlockmObile** [comment]
Also debris are closer then they used to be. And making them smaller wouldn't keep them consistent.

**Comment by NinjaSam5399** [comment]
ok
