### ISSUE TITLE
Z-Fighting on Phase 2 of the Wither Storm

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1444]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.46

### Describe the bug

As pictured, Z-Fighting can be seen on the Wither Storm's model.

### Steps to Reproduce

Summon a Wither Storm
Observe the sides of the model as it grows between phase 1 and 3

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot 2023-09-13 214354](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/122060314/598b6a7c-84fc-45c0-ba5e-0f817e892057)

### Mod List

No extra mods.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next release
