### ISSUE TITLE
[Suggestion]: Config for WS head bite damage

### ISSUE THREAD

**Issue by Void866** [nonamecrackers2/crackers-wither-storm-mod#1447]
### Description of feature request

Because y'know its a giant beast and with netherite enchanted gear you can tank multiple bites from its head. So why not allow its damage to be set so it just one shots you no matter what? 

Might make reaching the WS heads actually terrifying, and a whole new reason why you should carry a bow.

**Comment by myron-obsolete-account** [comment]
I mean netherite armor is very durable so it should make sense for it to take multiple bites, but alright

**Comment by BluePineappleGuy** [comment]
> I mean netherite armor is very durable so it should make sense for it to take multiple bites, but alright

this beast is literally powered by a block with the ability to warp reality, i think biting through netherite should be no problem for it

**Comment by nonamecrackers2** [comment]
This should be possible with attributes by modifying the mobs melee damage
