### ISSUE TITLE
[Bug] (CLOSED) : Sickened Mobs added from 4.0 cannot be cured by Golden Apple Stew

### ISSUE THREAD

**Issue by GoldSlimeling91** [nonamecrackers2/crackers-wither-storm-mod#1448]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.46

### Describe the bug

Sickened Pillagers, Phantoms, Cows, Mooshrooms, Chickens, and Iron Golems (not sure if iron golems are intended or not as they're a weird case) cannot be cured through usage of Golden Apple Stew, right clicking them with it simply does nothing.

Steps to Reproduce
1. Summon any Sickened Mob that isn't a Zombie, Villager, Skeleton, Spider, or Creeper
2. Attempt to cure them with the stew
3. ❌ Observe as nothing happens

Edit: summoning a sickened mob through /summon or through a spawn egg prevents them from being cured, this issue can be closed (this is weird as when i was initially testing this i spawned a skeleton with an egg and it got cured, but now it doesn't get cured)

**Comment by Pandaboi25x** [comment]
cant cure on 1.19.4 too

**Comment by Composer-Hu** [comment]
If you summon them directly, they cannot be healed. Only an infected creature that transforms can be cured, because the creatures summoned do not have their original form.

**Comment by nonamecrackers2** [comment]
> If you summon them directly, they cannot be healed. Only an infected creature that transforms can be cured, because the creatures summoned do not have their original form.

This. Did you summon the mobs then try to cure them?

**Comment by Pandaboi25x** [comment]
> > If you summon them directly, they cannot be healed. Only an infected creature that transforms can be cured, because the creatures summoned do not have their original form.
> 
> This. Did you summon the mobs then try to cure them?

I did yes but i still think this should be fixed on 1.19.4

**Comment by nonamecrackers2** [comment]
I'd make a separate suggestion then since it's technically intended

**Comment by GoldSlimeling91** [comment]
I summoned the mobs through spawn eggs and /summon as well too, and they refused to get cured, only the classic sickened mobs can be cured after spawning them with a spawn egg

Oh wait nevermind scratch that i cant cure mobs after spawning them with an egg now???? I did it before idk why it doesnt work now
I'll try to infect a pillager and cure it again real quick to see if i can close this issue
