### ISSUE TITLE
[Suggestion]: Concept idea for a cutscene to play when the witherstorm hole appears

### ISSUE THREAD

**Issue by mattdafilipino** [nonamecrackers2/crackers-wither-storm-mod#1449]
### Description of feature request

Using some of my editing and some sound effects from #1351 I cooked up a video concept idea on how a cutscene would play when the hole appears. It freezes the player and mobs around the player (this includes if the player is falling from a height) so the cutscene does not screw you over in any way. Credits to MoRoN222 for the sound effects (Even though I kinda yoinked it without permission srry dont deep it). 

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103057495/7dc6cc27-e6f8-43b2-8de3-160d796576ce

**Comment by TaintedBlockmObile** [comment]
I don't really see this happening. But a sound would make sense

**Comment by Yiyipthegruntmajor** [comment]
> I don't really see this happening. But a sound would make sense

A sound could work better than a cutscene, Minecraft doesn't ever take control away from the player and this mod should keep it that way. Its like adding cutscenes to half life, its wrong.

**Comment by mattdafilipino** [comment]
> > I don't really see this happening. But a sound would make sense
> 
> A sound could work better than a cutscene, Minecraft doesn't ever take control away from the player and this mod should keep it that way. Its like adding cutscenes to half life, its wrong.

Fair should I take this down den?

**Comment by Yiyipthegruntmajor** [comment]
> > > I don't really see this happening. But a sound would make sense
> > 
> > 
> > A sound could work better than a cutscene, Minecraft doesn't ever take control away from the player and this mod should keep it that way. Its like adding cutscenes to half life, its wrong.
> 
> Fair should I take this down den?

If you want to, otherwise let cracker choose what he wants to do with this.

**Comment by myron-obsolete-account** [comment]
> Credits to MoRoN222 for the sound effects (Even though I kinda yoinked it without permission srry dont deep it).

how ironic because I just got a strike on my YT channel today lmao

**Comment by nonamecrackers2** [comment]
This is a bit out of scope for the mod, and I don't overly like the idea of taking control of peoples cameras. Neat idea though.
