### ISSUE TITLE
Add a purpleish orange when gets to phase 6 and phases after phase 6

### ISSUE THREAD

**Issue by Python17900** [nonamecrackers2/crackers-wither-storm-mod#145]
I think it will be nice if there was a purpleish orange when hits phase 6 and phases after phase 6 
![image](https://user-images.githubusercontent.com/106478826/176046613-5f5e30d1-a998-4b8b-ba7e-aa53498415f5.png)

**Comment by nonamecrackers2** [comment]
After testing out the sky darkening effect, I don't feel this is entirely necessary. I've attempted adding a glow effect in the past and it didn't really work out.
