### ISSUE TITLE
[Bug]: When the WitherStorm is chasing you, it just goes PAST you......

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1452]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.46

### Describe the bug

When the witherstorm is chasing, it randomly just goes past me! PLS FIX AS SOON AS POSSIBLE

### Steps to Reproduce

1. wait until WS is chasing
2. Wait until it goes close to u
3. See error

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/128298281/130cc459-56e8-4116-933c-78e684d28055)

**Comment by TaintedBlock** [comment]
Did this happen more then once?

**Comment by GearsawStudios** [comment]
Were you in spectator mode? It can't track you in spectator and saves your last non-spectator position. Also, it may have gotten distracted and intentionally went past you. If you were underground, it'll move around above your location instead of directly above.

**Comment by NinjaSam5399** [comment]
This is probably intended.

**Comment by Steve982950** [comment]
> Did this happen more then once?
Yes

**Comment by Steve982950** [comment]
> Were you in spectator mode? It can't track you in spectator and saves your last non-spectator position. Also, it may have gotten distracted and intentionally went past you. If you were underground, it'll move around above your location instead of directly above.

I wasnt in Spec mode

**Comment by nonamecrackers2** [comment]
Were you out of sight from the Wither Storm when this happened?

**Comment by Steve982950** [comment]
Both INSIGHT AND out of sight

**Comment by nonamecrackers2** [comment]
Have modified the "Ultimate Targeting Type" server config value at all?

**Comment by Steve982950** [comment]
I don't think so. Why?

**Comment by nonamecrackers2** [comment]
Just checking. You could've set it to random stroll and it would just fly past you.

**Comment by Steve982950** [comment]
ok

**Comment by nonamecrackers2** [comment]
Unable to replicate. Have you modified any of the Wither Storm's speed configs?

**Comment by Herobrine982950291** [comment]
i have not

**Comment by Herobrine982950291** [comment]
sorry if i took a long time
btw this my alt

**Comment by Herobrine982950291** [comment]
I have not modified any WS speed configs. They are all in default

**Comment by nonamecrackers2** [comment]
Can't replicate. There could be a few reasons why this may have happened:
- You could have set an ultimate target pos accidentally
- You were temporarily out of sight and the Wither Storm started randomly strolling

If these possibilities aren't the case, then if you can send a video of your issue and possibly better steps to reproduce the issue, that would be most beneficial.

**Comment by Herobrine982950291** [comment]
> Can't replicate. There could be a few reasons why this may have happened:
> 
> * You could have set an ultimate target pos accidentally
> * You were temporarily out of sight and the Wither Storm started randomly strolling
> 
> If these possibilities aren't the case, then if you can send a video of your issue and possibly better steps to reproduce the issue, that would be most beneficial.

the 2nd reason could be the right one...
