### ISSUE TITLE
[Bug]: Segment of Phase 6 lagging behind

### ISSUE THREAD

**Issue by Onemario1234** [nonamecrackers2/crackers-wither-storm-mod#1456]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.0

### Describe the bug

I was playing on my Survival world, with the Wither Storm set to "Random Stroll Near Player." I had just crafted a Formidibomb, placed, and ignited it. The Wither Storm was insanely fast at this point for unknown reasons, so it zoomed right by. Formidibomb floats towards it and explodes, "killing" the Wither Storm. When it stops playing dead, one of the segments lags behind heavily before suddenly teleporting to the other segments. But at this point, it started lagging behind, teleporting with it instead of moving smoothly.

### Steps to Reproduce

1. Survival(?)
2. Destroy Wither Storm at Phase 5.5 with the Formidibomb
3. Make it stop playing dead
4. (Hopefully) see result

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/25996506/8a147637-6e75-415a-ae5a-85ebb08ff1dc

### Mod List

- AmbientSounds
- Appleskin
- Biggerstacks
- CreativeCore
- EMI
- Forge Config Screens
- InventoryHUD+
- LevelHearts
- Oculus
- Rubidium
- Sound Physics Remastered
- Wither Storm
- Xaero's Minimap
- Xaero's World Map

**Comment by nonamecrackers2** [comment]
Will be fixed in the next release
