### ISSUE TITLE
[Bug]: Modern Forge Builds Prevent Wither Storm from spawning

### ISSUE THREAD

**Issue by Onemario1234** [nonamecrackers2/crackers-wither-storm-mod#1457]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

Latest Builds (exact numbers unknown)

### Describe the bug

When playing with latest versions of Forge, the Wither Storm refuses to spawn, whether it's the spawn structure or summon command.

### Steps to Reproduce

1. Install the Wither Storm mod on a Latest build of Forge
2. Load into a world and try to summon the Wither Storm
3. Wither Storm doesn't spawn

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/25996506/27cb7bf8-aa56-4935-ac54-d39a9ddb556f

### Mod List

Tested with _only_ the Wither Storm mod installed.

**Comment by myron-obsolete-account** [comment]
for now it's best to use an earlier forge build until this is fixed, try 47.1.44 (1.20.1), it's what I use and it works just fine

**Comment by Void866** [comment]
Can confirm had the same issue, latest version of forge and 1.20.1 version of the mod.

Didn't test if it's fixed with early version of forge though.

**Comment by nonamecrackers2** [comment]
Found that it's a specific range of forge versions causing the issue (47.1.6 to 47.1.39). Will be fixed in the next update by preventing the mod from loading when one of those versions are installed.
