### ISSUE TITLE
[Small Bug] Common Options lists Players Are More Favorable twice

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#146]
1.18.2

witherstormmod-1.18.2-2.0-beta3.jar

Common Options lists Players Are More Favorable twice

**To Reproduce**
1. Go to options
2. Click on common options
3. See Players Are More Favorable twice

![image](https://user-images.githubusercontent.com/28667280/176107009-17cb84f8-5499-44b8-bba5-ae1ed37c4150.png)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update, apparently I overrode another config option that's supposed to be there.
