### ISSUE TITLE
[Suggestion]: Config to hide debris rings in earlier phases but show them after split

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1460]
### Description of feature request

I don't even know if I actually want this but since the F-Bomb explosion also pretty much throws around and rips off lots of debris off the storm's mass, I think it'd be a little bit more realistic if the debris rings started appearing at phase 6 and up, cus having that much of debris displayed in the storm's early destroyer phases sometimes feels wrong I guess.
It also looks like they have been disabled in the screenshot for the new panorama, it just looks better I guess
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/6efbd3b0-0cf2-40e0-8564-5d75f585a4cd)

**Comment by Composer-Hu** [comment]
I like this suggestion, even if it's just to add this configuration item as a command to modify it, that way I can also make a datapack and have it execute true/flase at different stages.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
