### ISSUE TITLE
[Bug]: WS randomly stopped rendering (no chunkloading)

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1462]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.44

### Describe the bug

I was spending my time deep in the caves craving for iron and diamonds, when I finally surfaced I was wondering why the WS didn't evolve yet, after using some spare blocks from the mining to build a tower to look in the distance the WS wasn't there, then I enabled the server to LAN with cheats to check for the chunkloading, results were zero chunks loaded out of zero (by the way I think commands like that one should be accessable without cheats)

### Steps to Reproduce

1. play the game
2. yeah

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

N/A

or, well...
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/d2566144-ff8f-430b-981f-7b90f2698f14)
that?

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/a885b592-7eb2-4056-91ec-5a1719bd2299)

**Comment by nonamecrackers2** [comment]
Seems like a mod compat issue, try to see if you can pin point the problematic mod (if there is one). Did you see the Wither Storm before during the same session?

**Comment by BluePineappleGuy** [comment]
i actually had a similar issue where the storm unloaded upon joining the world. i couldn't hear or see the storm, and it had stopped moving completely. when i got nearby to where it last was, it reloaded (presumably because it was in my simulation distance, and continued moving as if nothing happened. it seems to be an issue with the new chunkloader

**Comment by myron-obsolete-account** [comment]
> Seems like a mod compat issue, try to see if you can pin point the problematic mod (if there is one). Did you see the Wither Storm before during the same session?

well yeah cus I had to spawn it at some point, I then ran out of it's radius (or, well, MY render radius), possibly before it was released, could've possibly caused it but I don't actually know

theres an option in the MC launcher to load a log that runs along with the game when launching it, maybe I can identify the incompatible mod with that method, if there's even one that creates that issue. I actually had this issue twice (once with the patreon beta) but the first time I thought it was a random bug from minecraft itself or whatever, but I'll try to figure it out now

**Comment by myron-obsolete-account** [comment]
update: not figured out if it could be a mod problem yet because I didn't do enough test runs lmao

**Comment by NRH2007** [comment]
ive discovered a similar issue in one of my own modpacks. the witherstorm (due to my presence in the aether for the duration of its original starting time) did not progress as far as i expected, and upon reloading the world i discovered it has disapeared (probably because its chunkloader failed), upon going to its last known location it reappeared. So far, we share the witherstorm mod and its dependency citadel, Create, Create: Steam and Rails, JEI, Moonlight, Supplementaries, and farmers delight. Some of those are more likely to be responsible than others. Im on 1.20.1 forge version 47.1.46 if that helps.

**Comment by BluePineappleGuy** [comment]
> ive discovered a similar issue in one of my own modpacks. the witherstorm (due to my presence in the aether for the duration of its original starting time) did not progress as far as i expected, and upon reloading the world i discovered it has disapeared (probably because its chunkloader failed), upon going to its last known location it reappeared.

this issue and mine are probably related as the same result happened.

**Comment by nonamecrackers2** [comment]
Maybe try using the recommended forge version to see if that helps

**Comment by myron-obsolete-account** [comment]
It happened again (did not swap forge version though)

**Comment by Boo566ya8** [comment]
Same thing happened to me. A few days ago, me and a friend started a Minecraft server and decided to add this mod. Everything was going well for about the first 12ish Minecraft days on the server and then we started wondering where the Wither Storm had went. I decided to look up some commands to see if I could find its position just out of curiosity since we couldn't see it at all and whenever I tried to use any of the commands such as finding it's ultimate target or getting the amount of entities it consumed I would always get "Entity does not exist". In this case, the chunk loader failed and I even tried to summon a new Wither Storm, while killing the original one and after the chunk loader initially stopped working for the first time, it would always stop working everytime I closed and re-opened the server. This is a really cool mod and I hope you guys can get this issue resolved soon! I can also give you the entire server folder if it would help in solving this bug.

**Comment by Boo566ya8** [comment]
And I should also note that we did not go to another dimension.

**Comment by Boo566ya8** [comment]
Ok, so I messed around with my world for a bit and I tried clearing out the entire entities list in the world folder and re-summoned the Wither Storm and it seems to work now, so it has to be something to do with the mod itself.

**Comment by Boo566ya8** [comment]
Okay, so I tested this mod alone with default settings and found that if you go about 7000+ blocks away from the Wither Storm and then save and quit and rejoin the world, the chunk loader will break and you will have to always go near the Wither Storm to temporarily fix it every time you start the world.

**Comment by myron-obsolete-account** [comment]
> Okay, so I tested this mod alone with default settings and found that if you go about 7000+ blocks away from the Wither Storm and then save and quit and rejoin the world, the chunk loader will break and you will have to always go near the Wither Storm to temporarily fix it every time you start the world.

yeah thats pretty much it cus I noticed it go away again aswell when I left and rejoined the world.

**Comment by nonamecrackers2** [comment]
> It happened again (did not swap forge version though)

Could you actually try swapping the forge version though?

**Comment by nonamecrackers2** [comment]
> Same thing happened to me. A few days ago, me and a friend started a Minecraft server and decided to add this mod. Everything was going well for about the first 12ish Minecraft days on the server and then we started wondering where the Wither Storm had went. I decided to look up some commands to see if I could find its position just out of curiosity since we couldn't see it at all and whenever I tried to use any of the commands such as finding it's ultimate target or getting the amount of entities it consumed I would always get "Entity does not exist". In this case, the chunk loader failed and I even tried to summon a new Wither Storm, while killing the original one and after the chunk loader initially stopped working for the first time, it would always stop working everytime I closed and re-opened the server. This is a really cool mod and I hope you guys can get this issue resolved soon! I can also give you the entire server folder if it would help in solving this bug.

Thanks for the info! Mind telling me the forge version you're using?

**Comment by Boo566ya8** [comment]
> > Same thing happened to me. A few days ago, me and a friend started a Minecraft server and decided to add this mod. Everything was going well for about the first 12ish Minecraft days on the server and then we started wondering where the Wither Storm had went. I decided to look up some commands to see if I could find its position just out of curiosity since we couldn't see it at all and whenever I tried to use any of the commands such as finding it's ultimate target or getting the amount of entities it consumed I would always get "Entity does not exist". In this case, the chunk loader failed and I even tried to summon a new Wither Storm, while killing the original one and after the chunk loader initially stopped working for the first time, it would always stop working everytime I closed and re-opened the server. This is a really cool mod and I hope you guys can get this issue resolved soon! I can also give you the entire server folder if it would help in solving this bug.
> 
> Thanks for the info! Mind telling me the forge version you're using?

The latest (47.1.47)

**Comment by myron-obsolete-account** [comment]
so latest and 47.1.44 (I am using that) have the issue.

**Comment by myron-obsolete-account** [comment]
now we need someone with the recommended version to try that so cracker can invesitage much further or whatever

**Comment by Kskdo** [comment]
i dont have any other mods and it happens to me sometimes too.

**Comment by nonamecrackers2** [comment]
I may have an idea why but I'll have to investigate on it further

**Comment by soup587** [comment]
am having this issue in singleplayer, leaving and rejoining the world stops the wither storm from chunk loading and freezes it like regular mobs until i get within simulation distance of it again

**Comment by Aimyx** [comment]
> am having this issue in singleplayer, leaving and rejoining the world stops the wither storm from chunk loading and freezes it like regular mobs until i get within simulation distance of it again

This has been reported already. #1493

**Comment by soup587** [comment]
> I believe that's 1.20 exclusive due to the new chunk loading system, this issue is for 1.19.4

woulda commented there but i'm getting the issue on 1.20.1

**Comment by Aimyx** [comment]
> woulda commented there but i'm getting the issue on 1.20.1

This is an issue for both versions, however at it's core, this only happens because of mod incompatibility. this does not happen with just cwsm installed.

**Comment by soup587** [comment]
strangely it only happens if i close and save my world?
if the game crashes for whatever reason without being able to save then next time i load in the wither storm's chunks load just fine

**Comment by nosivaste** [comment]
can confirm this also happens to me on both server and singleplayer, am using the 1.20.1 version

**Comment by nonamecrackers2** [comment]
Should be fixed in the next major release
