### ISSUE TITLE
[Suggestion]: wither storm instantly absorbing blocks next to it

### ISSUE THREAD

**Issue by HammedBurngur** [nonamecrackers2/crackers-wither-storm-mod#1463]
### Description of feature request

blocks that are too close to the wither storm will be instantly pulled in in stage 4+, like in the scene where it left the main endercon building

**Comment by TaintedBlockmObile** [comment]
Doesn't it kinda do this already?

**Comment by BluePineappleGuy** [comment]
> Doesn't it kinda do this already?

it explodes them, but doesn't suck them in or somethin

**Comment by Composer-Hu** [comment]
Suggestion added: I think maybe after phase 4, near WS will still be like the end of phase 3, quickly inhale a large number of 1*1 blocks. Visually, it even looks like a particle of debris.

**Comment by nonamecrackers2** [comment]
This is actually a pretty good idea, would be better than the current explosions that are in place

**Comment by MFNmodding** [comment]
perhaps that blocks too close to it immediately turn into block clusters. it would look like that previously mentioned scene, and it would be cool as heck.

**Comment by SuperSharkGaming** [comment]
If it was in stage 4+ it would be neat if the block clusters were really big

**Comment by MFNmodding** [comment]
> If it was in stage 4+ it would be neat if the block clusters were really big

that's what i meant to say, you summarized it pretty well.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
