### ISSUE TITLE
[Suggestion]:Diffrent command block colors 

### ISSUE THREAD

**Issue by TNTPLAYZEXE318** [nonamecrackers2/crackers-wither-storm-mod#1464]
### Description of feature request

we all know the original command block color is but command blocks can be purple and cyan. it wont effect the wither storm but it would look cool... great idea?

for: 1.18.2, 1.19.4, 1.20.1

**Comment by Shadowwolf2010-void** [comment]
Can we have Ruben please I feel like he'd be important.

**Comment by Composer-Hu** [comment]
This may not be possible because there are texture issues involved, unlike something like a beam that can directly modify the render color.

**Comment by Composer-Hu** [comment]
> 我们可以请鲁本吗，我觉得他很重要。
Use the name tag for the pig named Reuben, you'll get it.

**Comment by myron-obsolete-account** [comment]
duplicate of #820

**Comment by TNTPLAYZEXE318** [comment]
reopened

**Comment by myron-obsolete-account** [comment]
> reopened

why?? this is a duplicate

**Comment by TNTPLAYZEXE318** [comment]
i did not think that anybody suggested this yet ):

**Comment by TNTPLAYZEXE318** [comment]
fine i will close it
