### ISSUE TITLE
[Bug]: Phasometer does not work

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1465]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.44

### Describe the bug

I use the phasometer all the time but it doesn't show me the information it should show, it keeps saying "searching..."

### Steps to Reproduce

use the phasometer

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2023-09-17_13 10 19](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/c393346b-d7b4-4620-96c3-b7adfbafde54)

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/d86a1cfb-8c57-4714-a6a8-69a8d7fba939)

**Comment by CubeGamer647** [comment]
You've gotta be looking at the hitbox of the wither storm, which is around the bottom, where the tentacles are. F3+B to see it, I think only the white one works.

**Comment by nonamecrackers2** [comment]
Do you have squash hitboxes enabled?

**Comment by myron-obsolete-account** [comment]
> Do you have squash hitboxes enabled?

nope

**Comment by myron-obsolete-account** [comment]
> You've gotta be looking at the hitbox of the wither storm, which is around the bottom, where the tentacles are. F3+B to see it, I think only the white one works.

did it multiple times now, even before too I guess, didn't work


cracker it worked for you as I could see in a few preview videos, but you did it in 1.19.4 right?

**Comment by nonamecrackers2** [comment]
It could be broken or could be a mod compat issue

**Comment by nonamecrackers2** [comment]
Unable to reproduce. Appears to be a mod compat issue, I'd remove any performance/library mods you may have to figure out the cause.
