### ISSUE TITLE
Fast Block Cluster Option

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#1467]
### Description of feature request

It Would Be Cool If There Was A Option To Change How Fast The Block Clusters Get Pulled To The Wither Storm

Like Instead Of Having Them Fly To The Wither Storm In Normal Speed, They Can Go Really Fast Or Slow

**Comment by Composer-Hu** [comment]
This feature may cause the game to lag, and it can be serious, that may not be so easy, Let's see what Crackers says, I'm also looking forward to this config.

**Comment by nonamecrackers2** [comment]
This already exists, it’s the block cluster pick up interval options.

**Comment by BluePineappleGuy** [comment]
> This already exists, it’s the block cluster pick up interval options.

i think he means the speed they fly into the storm, like some should slowly go up while others zoom into the storm.

**Comment by LucasDotje** [comment]
> This already exists, it’s the block cluster pick up interval options.

No I Don't Mean That One, I Mean A New One To Change How Fast They Fly Into The Wither Storm After Being Picked Up

**Comment by myron-obsolete-account** [comment]
> > This already exists, it’s the block cluster pick up interval options.
> 
> No I Don't Mean That One, I Mean A New One To Change How Fast They Fly Into The Wither Storm After Being Picked Up

question, why do you cap every new letter of every new word

**Comment by nonamecrackers2** [comment]
Ah I see, that’s my bad then

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
