### ISSUE TITLE
[Suggestion]: Lightning around the wither storm. (edited)

### ISSUE THREAD

**Issue by TNTPLAYZEXE318** [nonamecrackers2/crackers-wither-storm-mod#1468]
### Description of feature request

lightning will happen in phases 4-7, the lightning will get more intense in phases 6 and 7 and will get more powerful... (UPDATE!!!) there will be a setting in the world settings. you can set of how fast the lightning will happen, how far you could see it and hear it, and to turn it off or on! (off by default) great idea?

if somebody already suggested this let me know and i will close this suggestion if so.

for 1.18.2, 1.19.4, 1.20.1

**Comment by myron-obsolete-account** [comment]
idk if that's a good idea, it'll just reduce something I personally like about the storm... but lets see what cracker says

**Comment by CubeGamer647** [comment]
This would be better left as a visual feature with a config, but I think this could be interesting.

**Comment by TNTPLAYZEXE318** [comment]
i have updated the desc a little. just to give more detail

**Comment by nonamecrackers2** [comment]
#228 #552
