### ISSUE TITLE
[Suggestion]: Easy config for removing spawn structure

### ISSUE THREAD

**Issue by JustSomeGuy7** [nonamecrackers2/crackers-wither-storm-mod#1469]
### Description of feature request

Developing a modpack in 1.20.1, and I want to remove the spawn structure to force players to play through the pack before being able to fight the wither storm. However, I also want players to somewhat easily be able to re-enable the structure to be able to test concepts in creative mode. Any means to easily disable/enable the structure would be appreciated.

**Comment by nonamecrackers2** [comment]
There’s this [data pack](https://www.curseforge.com/minecraft/customization/no-rundown-house) I made that might do the trick. Unfortunately adding a button option (or something similar) wouldn’t be possible since structures are run with data packs, but players can always disable the data pack.
