### ISSUE TITLE
[Suggestion] Wither Storm storing certain blocks in a separate part of the bowels

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#147]
I've had this idea of what if the Witherstorm kept track of the player's most visited chunks and if a block cluster came from it it should store it inside of it in a part of the bowels like a empty cavity filled with blocks not accessible to the player and when it's defeated it should drop those block clusters so the player feels a sense of saving something they cared about structure wise or loot wise

**Comment by Asteroid4** [comment]
I like the idea of block clusters from the bowels falling out when the wither storm is destroyed, but the entire idea is good!
