### ISSUE TITLE
[Suggestion]: The far lands(nvm i dint know these kind of requests are not gonna get added)

### ISSUE THREAD

**Issue by charaster** [nonamecrackers2/crackers-wither-storm-mod#1470]
### Description of feature request

It would be cool to see the far lands back in this mod at around like 60k blocks out from spawn(far away enough that you can run into it while fighting against the storm but not close enough to casually find it) and in the far lands there would be all kinds of items and maybe even the maze to help you defeat the beast

**Comment by LegendaryGodzilla** [comment]
bruh

**Comment by TaintedBlockmObile** [comment]
Story mode request are not looked at. The mod is not trying to be like story mode fyi

**Comment by myron-obsolete-account** [comment]
hey just so you know the mod's name is wither storm mod not story mode mod

**Comment by nonamecrackers2** [comment]
> hey just so you know the mod's name is wither storm mod not story mode mod

Please be a bit more respectful. But yes, this is out of scope for the mod. Thank you for your suggestion however.

**Comment by myron-obsolete-account** [comment]
> > hey just so you know the mod's name is wither storm mod not story mode mod
> 
> Please be a bit more respectful. 

I'm sorry
