### ISSUE TITLE
[Suggestion]: Wither Storm Lock Command

### ISSUE THREAD

**Issue by TriniteTray** [nonamecrackers2/crackers-wither-storm-mod#1471]
### Description of feature request

![2023-09-17_12 18 57](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/142684411/c5304824-180f-4749-9e7d-f0518f7ac131)
So, ive been having fun with the Wither Storms "Black Hole" Phase. but the fun dims down when he evolves  and cant no longer suck in entire villages in seconds, so why not have the fun last forever? (or how ever as long as you want!)

I think there should be a Command and or World Option that Locks the Wither Storm in his current phase. For Example, say the witherstorm is in phase 5, Turning on this option would prevent the witherstorm from progressing in his evolution, and would stay in phase 5 forever, until the option is disabled

a command idea would be something like
/witherstormmod LockPhase @e[type=witherstormmod:wither_storm,limit=1]

**Comment by TaintedBlockmObile** [comment]
There is kinda already a way to do this. Gotta set it's consumed entities to 16000 with a repeating command block

**Comment by BluePineappleGuy** [comment]
it would look more like `/witherstormmod phase lock @w`

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
