### ISSUE TITLE
[Suggestion]: Data-driven potion + block crafting

### ISSUE THREAD

**Issue by CubeGamer647** [nonamecrackers2/crackers-wither-storm-mod#1473]
### Description of feature request

Hard to describe in the title, but basically, take how you throw a potion of decay onto a pumpkin to make a tainted pumpkin, and add datapack accessibility for custom recipes. i.e. 1 block input and 1 block output. If possible, this could use potions other than decay, such as throwing a potion of leaping onto a honey block to make it a slime block.

**Comment by Asteroid4** [comment]
This would probably make more sense as a seperate API.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
