### ISSUE TITLE
[Bug]: (updated) sickened phantoms dropping... chainmail pants??

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1474]
### Minecraft Version

1.19.4

### Mod Version

3.3

### Mod Loader

Forge

### Mod Loader Version

Not on pc but its the bug patch on 1.19.4

### Describe the bug

A really weird bug hapoend while i was watching tainted fight in the bowels, after tainted killed a sickened phantom the phantom dropped.. enchanted chainmail pants?? Idk how it happend but yea theres also a chance they drop more armor too (update the new mobs also drop em???)

### Steps to Reproduce

1. Go to cwsm
2. Kill a sickened phantom in the bowels (gl on getting chainmail pants lmao)
3. Truly a chainmail pants or any other armor maybe  drop

### Crash Reports/Logs

No crash 

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/6a8a62cf-3d3b-4df9-ad6f-77d57c845538)
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/e944f445-173d-4f63-bc25-527fcda655dc)

### Mod List

Not on pc but i can say that the sickened phantom dropped chainmail pants with deep pockets 1 (more inv space)

**Comment by TaintedBlock** [comment]
I think it was iron but yeah

**Comment by LegendaryGodzilla** [comment]
invisible legs

**Comment by BluePineappleGuy** [comment]
i think in the bowels bossfight, the game tries to equip it with armor, causing the armor to drop

**Comment by Pandaboi25x** [comment]
> i think in the bowels bossfight, the game tries to equip it with armor, causing the armor to drop

Possible

**Comment by GoldSlimeling91** [comment]
can confirm, this occurs with every sickened mob the command block summons (besides the symbiont) and even the ones the symbiont summons (creepers and spiders can drop armor sometimes)
probably due to the fact the game equips them with random armor when they're summoned

**Comment by nonamecrackers2** [comment]
> probably due to the fact the game equips them with random armor when they're summoned

Most likely. I think the symbiont has checks for this for the mobs it summons but not the final boss fight.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release

**Comment by Laughingcat27** [comment]
Truly a sickened phantom dropping chainmail pants moment
