### ISSUE TITLE
[Bug]: Order Temple Rundown House does not contain any loot

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1476]
### Minecraft Version

1.19.4

### Mod Version

3.3.1

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Describe the bug

The order temple variation of the rundown house does not contain any items in the chests or dispensers.

### Steps to Reproduce

1. Create a world with the Order Temple variation of the Rundown House
2. Check Chests/Dispensers

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

NONE

**Comment by nonamecrackers2** [comment]
This should’ve been up to the person that made the structure, however I’ll be willing to add loot myself

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
