### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ahmetenesay** [nonamecrackers2/crackers-wither-storm-mod#1478]
### Minecraft Version

1.16.5

### Mod Version

1.0.3

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### Describe the bug

I recommend the development of the AI AI of the Wither Storm and the Withered Symbiont. I coded a special mod to test your wither storm mod. Wither Storm's artificial intelligence is really bad. Wither Storm's hitbox has all its faces (n-s-w-e) deactivated. Okay, it makes sense that Wither Storm rejects physical attacks in this way, is invincible and therefore cannot be interacted with. As for the mode I coded, I added armor that allows the player to fly in survival mode. Once you start flying, both Wither Storm's pulling power and Withered Symbiont's gravity field attack decrease by almost 74%. Frankly, I don't want to talk too much. I can share a few AI codes that come to my mind.
This is the last one I tried on my old computer. 1.16.5

### Steps to Reproduce

You can understand what I mean by downloading a cheat software for Forge and opening "flight".

### Is OptiFine installed?

- [X] OptiFine is installed

### Screenhots

![2023-09-17_16 00 15](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/111576796/7e9b48bd-f474-4175-8950-129844884478)

### Mod List

NONE

**Comment by TaintedBlockmObile** [comment]
Mod list none yet what you're holding is modded bro. And I don't really get what's the problem here?

**Comment by nonamecrackers2** [comment]
It isn't really designed around pulling in flying players. Also 1.16.5 is no longer supported and won't be receiving bug fixes (unless if they are major, which this is not). Also next time please fill in your mod list since you clearly have more than CWSM installed.

**Comment by NinjaSam5399** [comment]
?
