### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by ahmetenesay** [nonamecrackers2/crackers-wither-storm-mod#1479]
### Description of feature request

This is unrelated but I have terrible news :{]
The mod is not open source, but someone who knows a little bit about programming can get everything from it after adapting Winrar to jar files with a simple installation. Personally, since I liked the boss themes, I extracted them and recorded them on my mp3 player :D I listen to them every time I have free time :D
Even without winrar, jd gui uses java decompiler.
Apart from all these, as a Java and C++ expert, I can make a few useful suggestions regarding the development of the mod. Currently, I am coding a side game for Minecraft in C++.

**Comment by LegendaryGodzilla** [comment]
wtf is this for

**Comment by BluePineappleGuy** [comment]
this is actually for the discussions page
https://github.com/nonamecrackers2/crackers-wither-storm-mod/discussions/1357

**Comment by LegendaryGodzilla** [comment]
okay

**Comment by nonamecrackers2** [comment]
Please use the discussions page for questions/concerns. Also the mod is currently intentionally closed source and there aren't plans to change that as of now. And yes I am aware of java decompilers and using WinRAR to view the source and I don't see them as a big issue (or something that I can mitigate).
