### ISSUE TITLE
[[BUG]] Duplicated Severed Witherstorms

### ISSUE THREAD

**Issue by Void866** [nonamecrackers2/crackers-wither-storm-mod#148]
Latest Version of 1.16.5

Pretty much was playing a normal survival game and went to hunt the witherstorm while it was in late Phase 6 and 7. From afar seemed like it was still in phase 5. When I reached it the 2 severed witherstorms (I'll call these A) loaded in, and then ANOTHER 2 spawned above the main witherstorm (I'll call these B), lowering themselves into same positions as severed A. 

Tried to run away, come back, tp far away, and tp back. Went to another dimension came back. Still had the issue. Im pretty sure at one point I had somehow duplicated it again meaning there was a Set C of severed witherstorms. Even after the duplications, from afar only the main witherstorm could be seen, set A, B and C severed parts could not be seen.

In terms of how I think I caused the bug.....
1 - Kill the witherstorm via formidabomb
2 - Ensure the auto revive is on.
3 - While the witherstorm "plays dead" head to the nether (or other dimension)
4 - Remain in the nether (or other dimension) while the witherstorm revives.
5 - Leave said dimension once it has revives.
6 - Severed witherstorms shouldn't be able to be seen from afar (looks like phase 5)
7 - Head over to the witherstorm and the severed will duplicate.

Note - This is only what I could think could of caused the issue, I may be wrong.

I didn't get any screenshots, but If I can find a way to cause the bug again, I'll upload them in a comment.

**Comment by nonamecrackers2** [comment]
I was unable to reproduce this issue. Do you happen to have optifine, and are you able to reproduce this issue multiple times? The only thing I can think that would be causing this is optifine's "Smooth World" performance feature.
