### ISSUE TITLE
[Suggestion]: mobs begging for help and mobs entering bases to keep them safe

### ISSUE THREAD

**Issue by TNTPLAYZEXE318** [nonamecrackers2/crackers-wither-storm-mod#1481]
### Description of feature request

(might be hard to code) so every mob that runs away from the wither storm will be affected. very few mobs will come up to the player, no mater if it is a hostile mob, a passive mob, or a friendly mob they will still come up to the player and follow him/her, mobs will no longer attack when the storm is present, even in the caves or the underground. and also when the mobs run away from the storm they will sweat. (what i mean is there will be water particles coming out of the mob like they are in major panic). if mobs are closest to caves or basses, they will not hesitate to go to them and hide.

for 1.18.2, 1.19.4, 1.20.1

if this is a duplicate let me know, as the other 2 that i posted were duplicates ):

**Comment by nonamecrackers2** [comment]
Adding the sweat and all that goes a bit out of scope for the mod. Also mobs aren't meant to not attack you underground, so that won't be changed. I don't think players will really get the message anyway that a mob is requiring help and will probably just kill the mob regardless.
