### ISSUE TITLE
[Bug]: Wither Storm body turns red when hitting it while having shaders on and entity hit effect diabled

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1482]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.44

### Describe the bug

Hitting the WS (hunchback phases) turns out to make it red for a second. now this is of course normal, but not if you realise that you use shaders, and disabled the entity hit effect. so it pretty much should not turn red
(the ws heads in destroyer phases do not turn red though and the issue with the hunchback phases is not that important to fix as it's just a visual little thing)

### Steps to Reproduce

get sum shaders
turn off entity hit effect
hit it
see? red! (TF2 reference intended)

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/c3c87775-c35b-409d-b611-0a42878f7c6d)
I made the shot the second I hit it so you can see it.

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/3b2eff98-c6e5-4e7a-ba57-f389c3e7c581)

**Comment by nonamecrackers2** [comment]
How did you disable the entity hit effect?

**Comment by BluePineappleGuy** [comment]
> How did you disable the entity hit effect?

i think its done in the settings of the shader (not sure been a while since i played with optifine)

**Comment by nonamecrackers2** [comment]
Closing until more information is given
