### ISSUE TITLE
[Bug]: Problem with CWSM's settings

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1483]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.1.47

### Describe the bug

Can't select sub-phases on CWSM's own settings.
I mean when resummoning Wither Storm via Withered Beacon, there is an option on CWSM's own options that specifies which phase Wither Storm will be upon Summoned. And I can only write numbers like 4, 5, 6 and not 4.5 or 5.5

### Steps to Reproduce

Nothing to tell.
Just can't write sub-phases on CWSM's own settings.

### Is OptiFine installed?

- [X] OptiFine is installed

### Mod List

CWSM

**Comment by myron-obsolete-account** [comment]
it's because subphases are not really by that numbering, when you do 4.5 it just sets it to 4 and then adds consumed entities until it makes the next submodel appear, that's how it works for the /witherstormmod phase set @w command, but not for anywhere else unfortunately

**Comment by nonamecrackers2** [comment]
This is intended, I'd make a new issue as a suggestion for this
