### ISSUE TITLE
[Suggestion]: Bowels collapse when storm killed

### ISSUE THREAD

**Issue by SuperSharkGaming** [nonamecrackers2/crackers-wither-storm-mod#1485]
### Description of feature request

I got an idea for a visual effect when the storm is killed

When the command block gets to the last hit, small chunks of the roof of the bowels shake and fall down like a block cluster

When the final hit is blown, giant chunks of the roof of the bowels fall down and the last thing the player sees is chunks of the floor shaking and falling before being teleported outside of the storm

**Comment by TaintedBlock** [comment]
Why is this something I was thinking about the other day

**Comment by LegendaryGodzilla** [comment]
oooooooo i would love seeing this

**Comment by Laughingcat27** [comment]
this is cool

**Comment by Asteroid4** [comment]
this sounds really cool

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
