### ISSUE TITLE
[Bug]: Setting the Wither Storm to phase 6.5 when it's already at phase 6.5 or higher causes all side heads to immediately shoot a skull

### ISSUE THREAD

**Issue by sm644me** [nonamecrackers2/crackers-wither-storm-mod#1486]
### Minecraft Version

1.19.4

### Mod Version

3.3.1

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Describe the bug

Title. Repeatedly setting the Wither Storm to phase 6.5 makes the side heads shoot. I believe this is because the `OtherHeadsDisabled` NBT gets confused and doesn't realize that it's already set to 0, so the side heads deactivate and reactivate in the same tick, causing their roaring interval to get reset to 0. Using something like `/data modify entity @w OtherHeadsDisabled set value 0` causes the exact same issue.

While it's possible to hold the Wither Storm at phase 6.5 by using `ConsumedEntities` instead, this doesn't work well if a player wants to adjust the Storm's evolution speed. Fixing this bug would allow for the Wither Storm to stick to this subphase regardless of what that config is set to.

### Steps to Reproduce

1. Summon a Wither Storm
2. Run `/witherstormmod phase set @w 6.5` repeatedly
3. Observe many, many skulls

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

NONE

**Comment by Steve982950** [comment]
OHHHH YOOOOOO THAT WOULD BE DANGEROUS!! 💀💀

**Comment by myron-obsolete-account** [comment]
> OHHHH YOOOOOO THAT WOULD BE DANGEROUS!! 💀💀

what?

**Comment by Steve982950** [comment]
TOO MANY SHOOTING SKULLS

**Comment by myron-obsolete-account** [comment]
> TOO MANY SHOOTING SKULLS

I'm sorry can you calm down please, also this is a bug report not a suggestion

**Comment by Steve982950** [comment]
ok ok. sorry

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
