### ISSUE TITLE
[Suggestion]: a fun tractor beam tool for creative mod 

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1488]
### Description of feature request

This tool will work like the tractor beam from the mod just pulling mobs and blocks

**Comment by Laughingcat27** [comment]
that would be amazing, i will finally have a motive to vaccuum clean my room for the first time in a few years

**Comment by ROBOY6321** [comment]
i agree

**Comment by SuperSharkGaming** [comment]
This would be neat, you could use the tool by clicking and holding,  it would act like a real tractor beam, block clusters and mobs could even orbit the player if they reach a configurable distance (default should be 3 blocks away from the player) and when the tool is unequipped it could drop the blocks and mobs (or there could be a config option to make you absorb the mobs and blocks for experience points)

**Comment by nonamecrackers2** [comment]
This wouldn't be something that I personally feel would fit in with the mod or Minecraft in that matter (since CWSM is meant to bring the Wither Storm in a more vanilla Minecraft-y style). Interesting idea though.
