### ISSUE TITLE
[Suggestion]: beeing able to change the witherstorm buildings at coordinates 0 0 with a recourcepack mabye

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1490]
### Description of feature request

It would be awesome for modpackcreators to mabye disable this building or make it into an diffrent structure or seal it with some kind of lategame breakable stone. Imsure its somehow possible with a recource pack or smth

**Comment by FunkyPotao** [comment]
You could also make it instantly spawn if you could change that building

**Comment by nonamecrackers2** [comment]
This is possible with datapacks. I have an [example](https://www.curseforge.com/minecraft/customization/no-rundown-house) that disables the house if you're interested.
