### ISSUE TITLE
[Suggestion]: witherstorm should drop all its block clusters and play an animation when the command block gets hit

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1491]
### Description of feature request

Well the command block kinda is the heart of thr creature so it would make sence that other players that arent in the bowels would see the witherstorm suffer if its "heart" gets attacked and mabye the witherstorm could pick up less clusters when the command block has little hp or it could drop certain clusters or mobs when its command block has low hp

**Comment by TaintedBlockmObile** [comment]
It already drops clusters when hit. And looses tractor beams sometimes.

**Comment by FunkyPotao** [comment]
> It already drops clusters when hit. And looses tractor beams sometimes.

It really does? Since wich update?

**Comment by TaintedBlockmObile** [comment]
> > It already drops clusters when hit. And looses tractor beams sometimes.
> 
> It really does? Since wich update?

Don't remember but it's been a thing for a while.

**Comment by nonamecrackers2** [comment]
It was a thing since the very first release I believe. Since the heads become injured and all that, I feel that is plenty and a special animation (especially considering the work to make one when most people wouldn't even see it) isn't needed. Thanks for your suggestion though
