### ISSUE TITLE
[Suggestion]: Add an option to toggle Tractor Beam Cluster Pick up.

### ISSUE THREAD

**Issue by TubbieEld** [nonamecrackers2/crackers-wither-storm-mod#1492]
### Description of feature request

Make an Option that toggles Tractor Beam Cluster Pick up.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release

**Comment by Aimyx** [comment]
oooh we in the "implemented in next major release" phase now? I sense evo
p2 trailer in early 2024
