### ISSUE TITLE
[Suggestion]: Witherstorm Purple sky flash

### ISSUE THREAD

**Issue by bludigity** [nonamecrackers2/crackers-wither-storm-mod#1494]
### Description of feature request

Hello cracker! I’ve got a suggestion from Minecraft story mode that you should add. So after the formidabomb incident, Jesse and Reuben are talking on that cliff thing, and the sky flashes purple when they are looking at the storm.
Please add this! It’d make the game feel more like story mode. Thanks! Bye!

**Comment by NinjaSam5399** [comment]
This is a good idea, but probably duplicate.

**Comment by bludigity** [comment]
> This is a good idea, but probably duplicate.

**Comment by bludigity** [comment]
> This is a good idea, but probably duplicate.

Uh, wdym duplicate?

**Comment by NinjaSam5399** [comment]
#463

**Comment by Laughingcat27** [comment]
cracker very likely wont add things that only make the mod more like story mode
