### ISSUE TITLE
(CRITICAL) [Bug]:  Exit Portal in End doesn't properly generate

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#1495]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.0.3

### Describe the bug

when the mod is installed, the Exit Portal in the End will fail to properly generate, generating at the bottom of the world, softlocking the game.

### Steps to Reproduce

1. Have mod installed
2. Teleport to End
3. See the portal broken

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

N/A

### Mod List

N/A

**Comment by myron-obsolete-account** [comment]
I don't really think CWSM is causing this issue. do you really not have any other mods installed?

**Comment by nonamecrackers2** [comment]
I talked with them before hand and they said it happened with only CWSM installed

**Comment by myron-obsolete-account** [comment]
> I talked with them before hand and they said it happened with only CWSM installed

alright

**Comment by nonamecrackers2** [comment]
I was unable to reproduce. Can you verify if your steps to reproduce the issue still work on your end?
