### ISSUE TITLE
[Suggestion]: Phase 2-3 Revamps

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#1496]
### Description of feature request

Since the Evolution Part 1 Update, phase 2-3 still feels like the wither storm is a black hole, and I thought it's going to be buffed, but instead, it was just tiny changes. So here are some changes to the game to make these two phases feel much easier.

**- Slower Head Movement:** 
The wither storm head speed is remained unchanged. Why not make the wither storm head moves as fast as the phase 4-7 head moves, instead of being like the old update where it would lock on player and there are no method to escape the tractor beam.

**- Better Tractor Beam Hitbox:**
The hitbox of the tractor beam feels like a black hole picking up players just randomly. So you should probably make the wither storm hitbox smaller than just a black hole sized hitbox.

**- Movement Changes:**
Instead of the Wither storm rushing towards the players when being in the Tractor Beam, the wither storm just stay in one spot and stare at players until the player dies or gets eaten. Another movement changes I want to suggest is the wither storm should move much slower than the phase 4-7. 

**Extra Note:**
Phase 0-1 will remain untouched and will not apply to any of these changes.

I hope this suggestion gets implemented to the game, because it was very stressful just for me to be suck in like a black hole.

**Comment by TaintedBlockmObile** [comment]
It's meant to be a black hole..??

**Comment by myron-obsolete-account** [comment]
I think the head speed on the hunchback WS is fine as it's still fast and the head is small enough to not fall apart when unrealisically moving fast like on the destroyer phases but lets see what cracker will say

**Comment by TaintedBlockmObile** [comment]
Not to mention the AI for the hunchback has been changed so you can escape

**Comment by NinjaSam5399** [comment]
But still.

**Comment by NinjaSam5399** [comment]
Any respond.

**Comment by myron-obsolete-account** [comment]
> Any respond.

not yet. patience is key.

**Comment by NinjaSam5399** [comment]
ok

**Comment by GoldSlimeling91** [comment]
The movement changes are already a thing in the update, but something i did notice is that its nigh impossible to properly hit the hunchback phase's head to make it drop you (you just end up hitting the wither itself instead)
I think just fixing that would make it work better, i dont see any reason to change it's head turn speed or it's hitbox though, they're fine as is

The WS in these phases is meant to be something that just destroys and kills everything around it because it's attention is way more focused on a smaller area until it enters the destroyer phases (and also its overall more mobile and faster), as you're basically almost equal in size to it still and thus, much more noticeable compared to being a small speck on the landscape

**Comment by TaintedBlockmObile** [comment]
> The movement changes are already a thing in the update, but something i did notice is that its nigh impossible to properly hit the hunchback phase's head to make it drop you (you just end up hitting the wither itself instead) I think just fixing that would make it work better, i dont see any reason to change it's head turn speed or it's hitbox though, they're fine as is
> 
> The WS in these phases is meant to be something that just destroys and kills everything around it because it's attention is way more focused on a smaller area until it enters the destroyer phases (and also its overall more mobile and faster), as you're basically almost equal in size to it still and thus, much more noticeable compared to being a small speck on the landscape

The head can be hit btw. Just have to aim a little more over the mass I think when aiming at the head

**Comment by GoldSlimeling91** [comment]
> The head can be hit btw. Just have to aim a little more over the mass I think when aiming at the head

yeah but its impossible to pull off (even once) and really annoying to land a hit on it when you're literally inside the ws and currently being consumed

**Comment by NinjaSam5399** [comment]
> The movement changes are already a thing in the update, but something i did notice is that its nigh impossible to properly hit the hunchback phase's head to make it drop you (you just end up hitting the wither itself instead) I think just fixing that would make it work better, i dont see any reason to change it's head turn speed or it's hitbox though, they're fine as is
> 
> The WS in these phases is meant to be something that just destroys and kills everything around it because it's attention is way more focused on a smaller area until it enters the destroyer phases (and also its overall more mobile and faster), as you're basically almost equal in size to it still and thus, much more noticeable compared to being a small speck on the landscape

The hunchback phase is much better when its slower rather than rushing towards players.

**Comment by nonamecrackers2** [comment]
I'd prefer to have the current head movement speed remain the same. I'm not sure what a "black hole sized" hitbox is so if you could elaborate more on what you mean that would be most appreciated. Changes should have been made to make it less likely to be constantly focused on players/staying near them, and I do not think it should be slower than the destroyer/devourer phases (4-7).

**Comment by NinjaSam5399** [comment]
I mean the wither storm acts like a black hole.

**Comment by NinjaSam5399** [comment]
Sorry for the mistake

**Comment by nonamecrackers2** [comment]
Im still not sure what that means but I don’t feel it needs changing personally

**Comment by NinjaSam5399** [comment]
ok

**Comment by myron-obsolete-account** [comment]
> Im still not sure what that means

didn't you mention in your patreon updates that it acts like a black hole, sucking up lots and lots of blocks before evolving to ph4?

**Comment by TaintedBlockmObile** [comment]
> > Im still not sure what that means
> 
> didn't you mention in your patreon updates that it acts like a black hole, sucking up lots and lots of blocks before evolving to ph4?

Yes. And it does that

**Comment by myron-obsolete-account** [comment]
> > > Im still not sure what that means
> > 
> > 
> > didn't you mention in your patreon updates that it acts like a black hole, sucking up lots and lots of blocks before evolving to ph4?
> 
> Yes. And it does that

yeah we know
