### ISSUE TITLE
[Suggestion]: Porting the mod to Fabric

### ISSUE THREAD

**Issue by NVGAT** [nonamecrackers2/crackers-wither-storm-mod#1498]
I'm not sure how viable this suggestion would be, but it would open a whole new world for content creators. As a creator myself, I find Replay Mod very useful, and the fact that it's not supported on newer versions of Forge makes content on this mod hard to produce. I'd completely understand if this wasn't possible or practical, after all we're talking about porting a very large mod to a whole another mod loader.

**Comment by TaintedBlockmObile** [comment]
Crackers has no plans to port the mod to fabric as that would mean basically re creating the whole mod. And there is already a mod out there that allows fabric and forge to work together.

**Comment by NVGAT** [comment]
> Crackers has no plans to port the mod to fabric as that would mean basically re creating the whole mod. And there is already a mod out there that allows fabric and forge to work together.

Interesting, could you please link that mod?

**Comment by myron-obsolete-account** [comment]
> And there is already a mod out there that allows fabric and forge to work together.

there was 2 times but both were then lies/WIP/discontinued/whatever

**Comment by TaintedBlockmObile** [comment]
> > Crackers has no plans to port the mod to fabric as that would mean basically re creating the whole mod. And there is already a mod out there that allows fabric and forge to work together.
> 
> Interesting, could you please link that mod?

https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

**Comment by myron-obsolete-account** [comment]
> > > Crackers has no plans to port the mod to fabric as that would mean basically re creating the whole mod. And there is already a mod out there that allows fabric and forge to work together.
> > 
> > 
> > Interesting, could you please link that mod?
> 
> https://www.curseforge.com/minecraft/mc-mods/sinytra-connector

lets see if replay mod will finally work again

**Comment by TaintedBlockmObile** [comment]
> > > > Crackers has no plans to port the mod to fabric as that would mean basically re creating the whole mod. And there is already a mod out there that allows fabric and forge to work together.
> > > 
> > > 
> > > Interesting, could you please link that mod?
> > 
> > 
> > https://www.curseforge.com/minecraft/mc-mods/sinytra-connector
> 
> lets see if replay mod will finally work again

It should since I saw someone using it with cwsm

**Comment by NVGAT** [comment]
> > > > > Crackers has no plans to port the mod to fabric as that would mean basically re creating the whole mod. And there is already a mod out there that allows fabric and forge to work together.
> > > > 
> > > > 
> > > > Interesting, could you please link that mod?
> > > 
> > > 
> > > [curseforge.com/minecraft/mc-mods/sinytra-connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector)
> > 
> > 
> > lets see if replay mod will finally work again
> 
> It should since I saw someone using it with cwsm
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12706440/latest.log)

Sadly, my game crashes. Could you be so kind and help me with my crash? I'd greatly appreciate it! (logs provided)

**Comment by TaintedBlock** [comment]
This is because of optifine. Don't use optifine with cwsm. It breaks rendering

**Comment by TaintedBlock** [comment]
oculus is unstable on 1.20 so don't use that either

**Comment by NVGAT** [comment]
> This is because of optifine. Don't use optifine with cwsm. It breaks rendering

I wasn't using OptiFine. I only have Replay Mod, Connector and the Forgified Fabric API.

**Comment by TaintedBlockmObile** [comment]
Hmm.. interesting. I'm not the best at it but maybe could ask someone in the discord server?

**Comment by nonamecrackers2** [comment]
Making a fabric port would take a lot of time that I’m not willing to invest. I’d like to make one but don’t want to spend the effort at the moment.

**Comment by Sansthegamer248** [comment]
Hey I see what you mean, tainted, why does it break rendering?

**Comment by Sansthegamer248** [comment]
I'm talking about cwsm and optifine?

**Comment by Sansthegamer248** [comment]
> Making a fabric port would take a lot of time that I’m not willing to invest. I’d like to make one but don’t want to spend the effort at the moment.

Honestly makes sense my friend. I'm a YouTuber also plus I try to use texture packs like fresh animations and the new models for cwsm and it just crashes, any ideas on how to fix that

**Comment by Theo65476** [comment]
então quando vc decidir quiser fazer nonamecrackers2 ficarei muito agradecido, ou pode portá-lo para 1.12.2.não se importe comigo é so uma sugestão de um fã ok?

**Comment by Theo65476** [comment]
> então quando você decidir querer fazer nonamecrackers2 ficarei muito agradecido, ou pode portá-lo para 1.12.2.não se importe comigo é então uma sugestão de um fã ok?

 translate this on google translator from portuguese to english

**Comment by Theo65476** [comment]
> então quando você decidir querer fazer nonamecrackers2 ficarei muito agradecido, ou pode portá-lo para 1.12.2.não se importe comigo é então uma sugestão de um fã ok?

translate this on google translator from brazilian portuguese to english

**Comment by erenbabaxpro47-ops** [comment]
Kilt You can use the mod! And also wither storm modunu fabric You can run it.
