### ISSUE TITLE
AI Suggestion : Scared mobs

### ISSUE THREAD

**Issue by MicrowaveTheDum** [nonamecrackers2/crackers-wither-storm-mod#15]
Like in Storymode, every small mob should run away from the Witherstorm when it gets big.

**Comment by GameDokter51** [comment]
That would be really cool. I agree with this suggestion.

**Comment by ScriptleGIT** [comment]
I agree with this suggestion, it sounds cool

**Comment by Loverxzc** [comment]
Very good idea!

**Comment by zChenX1** [comment]
good suggestion! I think all animals and monsters should try to stay away from the wither storm during phases 6-7 as well

**Comment by cardanawandra** [comment]
big yes, also we need enderman to angry at wither storm. and use it in phase 7 to feed wither storm and make hole

**Comment by Resuster** [comment]
same here

**Comment by GrandmaPork** [comment]
I think the endermen should just get mad and that's it. maybe they can teleport while suddenly holding a new wither storm "flesh" block to make it seem as if they just came back from attacking

**Comment by watersofnazareth** [comment]
Implemented as of the Prereleases
