### ISSUE TITLE
[Suggestion] Block Clusters should be physical towards entities and players like how boats and striders are

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#150]
It feels weird to suddenly fall into a pit and I feel like it would be more accurate to how MCSM shows the witherstorm if block clusters had a physical collision box, tho I don't know how that'd effect performance, I tried a thing using a command block to teleport entities within 2.5 blocks of a cluster up with it and it made it feel a lot more immersive

**Comment by SSgamingYT** [comment]
this looks interesting, I hope he adds it! maybe the mob could be absorbed with it!

**Comment by StellaBiscuit** [comment]
I think looking at the code of the Create mod would help since they have moving and spinning block contraption and stuff

**Comment by BluePineappleGuy** [comment]
this is also probably pretty easy as similar code seems to be used for the command block entity added by this mod

**Comment by myron-obsolete-account** [comment]
> this is also probably pretty easy as similar code seems to be used for the command block entity added by this mod

not exactly as the command block is like a normal block, same rotation, so the cuboid hitbox fits on it perfectly, on block clusters which are constantly rotating and moving it's a different thing.

**Comment by BluePineappleGuy** [comment]
> > this is also probably pretty easy as similar code seems to be used for the command block entity added by this mod
> 
> not exactly as the command block is like a normal block, same rotation, so the cuboid hitbox fits on it perfectly, on block clusters which are constantly rotating and moving it's a different thing.

yes, but the hitboxes don't need to necessarily be accurate, they just need to be somewhat solid

**Comment by watersofnazareth** [comment]
Closing this issue as it's not possible unless we rework how Clusters work

**Comment by BluePineappleGuy** [comment]
> Closing this issue as it's not possible unless we rework how Clusters work

NOOOOO
