### ISSUE TITLE
[Bug]: command block boss bar still shows even tho ws was changed to phase 4

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1500]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.1.0

### Describe the bug

title very much explains it 

### Steps to Reproduce

1. Go to cwsm
2. go to the bowels on phase 7
3. hit the cmd block 
4. go outside
5.change its phase to 4 
6.yea

### Crash Reports/Logs

no

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/8925db19-c783-4998-9bdd-fe732589a316)

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/87cc193d-7f80-4cb0-9771-ef7220a9f07a)

:jess:

**Comment by Pandaboi25x** [comment]
oh 1500 suggestion thing
epic

**Comment by TaintedBlockmObile** [comment]
I don't really see this needing a fix since the wither shouldn't be devolving lol

**Comment by Pandaboi25x** [comment]
> I don't really see this needing a fix since the wither shouldn't be devolving lol

idk man might be a bit annoying to see 2 boss bars at once, might get too distracting or smth

**Comment by myron-obsolete-account** [comment]
this is (in my view) intended as the WS is harmed in the inside either way, and the new feature that the bossbar is visible on the outside, disabling that again is uhh idk

**Comment by TaintedBlockmObile** [comment]
> this is (in my view) intended as the WS is harmed in the inside either way, and the new feature that the bossbar is visible on the outside, disabling that again is uhh idk

This is indeed intended

**Comment by Pandaboi25x** [comment]
> > this is (in my view) intended as the WS is harmed in the inside either way, and the new feature that the bossbar is visible on the outside, disabling that again is uhh idk
> 
> This is indeed intended

i still feel like this needs to be changed like i do not want 2 boss bars brothers :stare:

**Comment by floppydiskdrive6** [comment]
2 bossbars are normally visible in the commandblock fight anyways

**Comment by Pandaboi25x** [comment]
> 2 bossbars are normally visible in the commandblock fight anyways

shouldnt be when on phase 4 tho :stare:

**Comment by GoldSlimeling91** [comment]
the command block is damaged, thus the bossbar will display, simple as that
it tends to remain damaged permanently aswell (even when changing the WS's phase and "healing" the command block) so i see this as working as intended

**Comment by nonamecrackers2** [comment]
This is intended, it shows the bossbar at any phase if it’s not full
