### ISSUE TITLE
[Suggestion]: command block bow

### ISSUE THREAD

**Issue by floppydiskdrive6** [nonamecrackers2/crackers-wither-storm-mod#1501]
### Description of feature request

a weapon that can damage the command block but from a distance like a bow maybe even a crossbow

**Comment by Laughingcat27** [comment]
that would be very overpowered since you won't have to avoid getting smacked by the tentacles guarding the command block

**Comment by LegendaryGodzilla** [comment]
nah

**Comment by TaintedBlockmObile** [comment]
This kinda kills the whole boss battle tbh.

**Comment by floppydiskdrive6** [comment]
you could make so theres only a 25% chance it damages the command block

**Comment by floppydiskdrive6** [comment]
and if it doesn't work it wont work until the next phase

**Comment by floppydiskdrive6** [comment]
bc bows are weak

**Comment by floppydiskdrive6** [comment]
+ the boss keeps getting harder

**Comment by floppydiskdrive6** [comment]
every update

**Comment by TaintedBlockmObile** [comment]
> bc bows are weak

Then that just makes the bow useless

**Comment by myron-obsolete-account** [comment]
duplicate of #857

**Comment by floppydiskdrive6** [comment]
i didn't know this was a duplication💀
