### ISSUE TITLE
[Suggestion]: More tentacle movement.

### ISSUE THREAD

**Issue by EPICGUPPY44** [nonamecrackers2/crackers-wither-storm-mod#1504]
### Description of feature request

Simply put, just a bit more tentacle movement. Whenever I play with this mod, the wither storm in phase 4 on then on, the tentacles just look like they don’t move at all. In Minecraft story mode, the tentacles seem to have a larger range of movement, in here, this isn’t really so. So my suggestion is just adding more life into the tentacles.

**Comment by TaintedBlockmObile** [comment]
Already a thing in the most recent versions

**Comment by myron-obsolete-account** [comment]
Already was suggested, denied because it's unrealistic, however has been implemented for when the storm is chasing from a distance.

**Comment by TaintedBlockmObile** [comment]
> Already was suggested, denied because it's unrealistic, however has been implemented for when the storm is chasing from a distance.

Tentacles did gain a movement change. Even while not accelerating.

**Comment by BluePineappleGuy** [comment]
> > Already was suggested, denied because it's unrealistic, however has been implemented for when the storm is chasing from a distance.
> 
> Tentacles did gain a movement change. Even while not accelerating.

they still seem pretty static to me, they should look more like a squid

**Comment by nonamecrackers2** [comment]
Please read the guidelines. This extends more into the MC:SM parity section and is probably a duplicate.
