### ISSUE TITLE
[Suggestion]: Tentacles can be used by wither

### ISSUE THREAD

**Issue by Kskdo** [nonamecrackers2/crackers-wither-storm-mod#1505]
### Description of feature request

make the wither storm able to use his tentacles to grab and eat mobs. If it can be very laggy make it a toggle on the world options.

**Comment by TaintedBlockmObile** [comment]
Tentacles will not be changed

**Comment by BluePineappleGuy** [comment]
this has been suggested. it was turned down, but i like the idea because this would add difficulty to the storm.

**Comment by TaintedBlockmObile** [comment]
> this has been suggested. sadly turned down, because this would add difficulty to the storm

It would be impossible to do even if he wanted to and the wither is far too high in the sky

**Comment by BluePineappleGuy** [comment]
yeah, ig, but i still would love to see it.

**Comment by nonamecrackers2** [comment]
Please read the guidelines
