### ISSUE TITLE
[Suggestion]: Can stand on block clusters

### ISSUE THREAD

**Issue by Kskdo** [nonamecrackers2/crackers-wither-storm-mod#1506]
### Description of feature request

I know it will lag so much but make us able to stand on block clusters. It will be so good to see it in the game.

**Comment by TaintedBlockmObile** [comment]
Not possible with how clusters rotate

**Comment by Kskdo** [comment]
i was thinking u can make a special block cluster entity that u can stand on even if it rotates. like boats.

**Comment by TaintedBlockmObile** [comment]
I don't really see this happening since it would be extremely annoying and kinda unnecessary to make a whole new entity just for that

**Comment by BluePineappleGuy** [comment]
wasn't solid block clusters suggested before?
like the hitbox was solid and you could stand on it?

**Comment by nonamecrackers2** [comment]
#150
