### ISSUE TITLE
[Bug]:  Wither Storm drops fire

### ISSUE THREAD

**Issue by Kskdo** [nonamecrackers2/crackers-wither-storm-mod#1507]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

Wither storm sucks fire sometimes and when u explode it while it sucks fire in, it drops fire. Sometimes when it drops the fire while exploding, fire starts to float in the sky as a normal block, not a cluster.

### Steps to Reproduce

Summon the wither storm
Wait till it sucks some fire in
explode the storm

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Wither storm mod (obviously)
Rubidium for performance

**Comment by nonamecrackers2** [comment]
I was unable to reproduce, but I've made it so clusters will no longer place fire as blocks in the world so hopefully that will fix the issue

**Comment by Kskdo** [comment]
Ok thank you.
