### ISSUE TITLE
[Suggestion]: Segments can grow like the center storm

### ISSUE THREAD

**Issue by Kskdo** [nonamecrackers2/crackers-wither-storm-mod#1508]
### Description of feature request

u may think im spamming but im randomly getting ideas :D 
Anyways, make it so segments have phases and can grow like the center storm.

**Comment by HammedBurngur** [comment]
I always wondered why they didn't in mcsm

**Comment by BluePineappleGuy** [comment]
pretty sure this has been suggested before

**Comment by TNTPLAYZEXE318** [comment]
this is a duplicate. but i like the idea

**Comment by nonamecrackers2** [comment]
#389
