### ISSUE TITLE
[Possible Bug] Block Clusters trail behind the Wither Storm

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#151]
1.18.2 

 Beta 3

Behind the Wither Storm when it's moving at high speeds Block Clusters trail and can cause lag

Get the Wither Storm to move to a location while it's pulling in blocks

![2022-06-30_02 13 39](https://user-images.githubusercontent.com/28667280/176616122-4e286865-c142-4db2-9b1a-c4f89b0503ff.png)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update
