### ISSUE TITLE
[Suggestion]: More accurate bowels entrance/exit

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1510]
### Description of feature request

What I want to say is, there is only one hole on the WS body which is the one at the front above the heads, and the only hole that leads to an exit inside the bowels is the one below the command block's small floating island.

My idea is that there could be another hole on the body model of the storm, somewhere behind the tentables but at the bottom, so it looks more like that the hole from the bowels actually leads outside. and the other way around, that there's the entrance hole somewhere in the caves which leads outside through the top hole. ¯\_(ツ)_/¯

**Comment by mythicplays** [comment]
Good idea

**Comment by TaintedBlockmObile** [comment]
Are you talking about the fall into the front of the bowels?? I need an example of what you're talking about.

**Comment by IndigoAmethyst** [comment]
> Are you talking about the fall into the front of the bowels?? I need an example of what you're talking about.

I think he means to add a second hole which the Player comes out of if they fall out of the Bowels for Phase 7.5

**Comment by nonamecrackers2** [comment]
This would be a pretty drastic model change, I don’t think this would be worth my time and may not look very good. Thanks for your suggestion though!
