### ISSUE TITLE
[Suggestion]: New Color Config: Horizon Color Config

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#1511]
### Description of feature request

The difference between the fog config and horizon config are the fog config changes the fog while the horizon config changes the color of the horizon. Since the fog changes the horizon, the fog color config should only change the color of the fog.

**Comment by TaintedBlockmObile** [comment]
You can do all of this with resource packs

**Comment by NinjaSam5399** [comment]
Can this be a color config instead of resource pack?

**Comment by NinjaSam5399** [comment]
I mean kinda resource pack

**Comment by NinjaSam5399** [comment]
The new method.

**Comment by nonamecrackers2** [comment]
The horizon is the fog. There’s the sky then the fog, there’s not really a horizon.
