### ISSUE TITLE
[Suggestion]: Better Tentacles

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#1512]
### Description of feature request

The tentacles should be more immersive. Like, I saw how you made the tentacles faster at phase 4 but I think they should move randomly instead of it looping the same animation. The tentacles don't need to pick up stuff but should look more menacing and intimidating.

**Comment by TaintedBlockmObile** [comment]
Tentacles will not be changed

**Comment by myron-obsolete-account** [comment]
no offense (before someone tells me to be respectful) but this suggestion doesn't really make sense. while I did notice the tentacle animations were looped back and forth, they still look good, and randomizing the movement might be difficult or whatever. and in my opinion and probably so many other people's opinion aswell the tentacles already look intimidating and menacing enough. but I don't wanna shoot down your issue like I would shoot down the Wither Storm with my Tsar Bomba rocket ;)

**Comment by Resuster** [comment]
Oh alr its fine ig ill close down this suggestion

**Comment by Laughingcat27** [comment]
I agree, the tentacles could look more intimidating. it just looks like they are standing still and only move because the wither storm is breathing. It would be cool if they moved more like they are alive rather than being an addition to the storms body

**Comment by Resuster** [comment]
I already closed it so no point :/

**Comment by myron-obsolete-account** [comment]
> I already closed it so no point :/

you can still reopen it

**Comment by BluePineappleGuy** [comment]
> no offense (before someone tells me to be respectful) but this suggestion doesn't really make sense. while I did notice the tentacle animations were looped back and forth, they still look good, and randomizing the movement might be difficult or whatever. and in my opinion and probably so many other people's opinion aswell the tentacles already look intimidating and menacing enough. but I don't wanna shoot down your issue like I would shoot down the Wither Storm with my Tsar Bomba rocket ;)

even if looped, the tentacles should have a little more variation, they currently just point in the same direction with a video game idle animation. i think they would look way more menacing if they swung around in every direction as part of the loop (think the one in story mode, or think squid)

**Comment by GrandmaPork** [comment]
I think a small in animations would be cool cuz they’re nearly static but tbh it’s like a sub-phase request. Doesn’t effect anything and will barely be noticed

**Comment by BluePineappleGuy** [comment]
> I think a small in animations would be cool cuz they’re nearly static but tbh it’s like a sub-phase request. Doesn’t effect anything and will barely be noticed

if they moved more wildly, trust me, _it will be noticed._

**Comment by Resuster** [comment]
Alr i guess ill reopen lemme see what crackers response is

**Comment by floppydiskdrive6** [comment]
tbh i just want the tentecales to be blocky like mcsm

**Comment by nonamecrackers2** [comment]
There are no plans to update the tentacles as of now.

**Comment by Resuster** [comment]
Okay.
