### ISSUE TITLE
[Suggestion]: Player armor gets darker as they approach the wither storm

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#1513]
### Description of feature request

Currently only the player model gets darker. I think it could look cooler if the armor the player wears also gets darker

**Comment by BluePineappleGuy** [comment]
dunno whether this was meant to happen or not.

**Comment by GrandmaPork** [comment]
Good point. I think it’s very cool either way

**Comment by nonamecrackers2** [comment]
Looking at the code there doesn't appear to be a meaningful way I could implement this without some ugly code injection. Interesting idea though.
