### ISSUE TITLE
[Suggestion]: add the lolcat and pirate speak language to the mod

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#1514]
### Description of feature request

i would like to see the lolcat and pirate speak to the mod it might be funny

**Comment by IndigoAmethyst** [comment]
Interesting.

**Comment by myron-obsolete-account** [comment]
thats up to the translators. I might actually wanna do the lolcat one, but for the pirate language we need actual pirates :trollface:

**Comment by GrandmaPork** [comment]
Yeah I don’t think cracker himself will be implementing this but I bet you can make and submit them as translations

**Comment by NinjaSam5399** [comment]
You could make pull request.

**Comment by ComradeOctoling** [comment]
i would actually like this, because i always play with lolcat and i wish cwsm had lolcat translation @MoRoN222 lmk when your lolcat translation is done

**Comment by nonamecrackers2** [comment]
Yeah I won’t do this myself but if people want to do it go ahead

**Comment by BluePineappleGuy** [comment]
> thats up to the translators. I might actually wanna do the lolcat one, but for the pirate language we need actual pirates :trollface:

well, i mean, https://lingojam.com/PirateSpeak
we can use this >:)

edit: doesnt work for all of it but i can substitute the issues

**Comment by Aimyx** [comment]
Just get the pirates that use Tlauncher to Alr it.

**Comment by IndigoAmethyst** [comment]
Fr
