### ISSUE TITLE
[Bug]: Crashing when creating a new world

### ISSUE THREAD

**Issue by enderwitherstorm123** [nonamecrackers2/crackers-wither-storm-mod#1515]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.1

### Describe the bug

I was creating a new world with this mod and when it reached 100% the game crashed then i tried creating a flat world and the same thing happened
im on the ultra low preset and im using optifine.
Exit Code: -1

### Steps to Reproduce

Create a new world
Reach 100%
Game Crashed

### Is OptiFine installed?

- [X] OptiFine is installed

### Mod List

Optifine

**Comment by mythicplays** [comment]
You should probably try Rubidium, if you want shaders, you might not be able to use it as Oculus mod crashes the game too, or you should allocate more RAM to Minecraft(if you have 2048MB Allocated only)

**Comment by myron-obsolete-account** [comment]
> You should probably try Rubidium, if you want shaders, you might not be able to use it as Oculus mod crashes the game too, or you should allocate more RAM to Minecraft(if you have 2048MB Allocated only)

there are only crashes with specific versions. oculus/rubidium works just fine for me because I read the warnings and infos about it

**Comment by watersofnazareth** [comment]
Provide a crash log

**Comment by unithecutie** [comment]
[crash-2023-10-04_20.06.16-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12807264/crash-2023-10-04_20.06.16-client.txt)

**Comment by nonamecrackers2** [comment]
Try removing optifine, if that doesn't work it might be an issue with forge (you could then try using the recommended forge build to see if that fixes the issue)

**Comment by nonamecrackers2** [comment]
Closing until information about if potential solution worked is given
