### ISSUE TITLE
[Suggestion]: arrows affected by beams

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#1516]
### Description of feature request

I’ve noticed that when a block cluster is created already landed arrows aren’t included in the cluster and just fall. Also, when the beam travels over them, they aren’t affected. I think it’d be cool if arrows were slightly affected by the beam so it doesn’t mess up anyone’s shots but it also doesn’t leave them littered across the ground. And hey, maybe it would very very slightly improve performance to clear a few arrows off the terrain

**Comment by myron-obsolete-account** [comment]
arrows are entities that's why these kinda things didn't happen in the first place. never tried it yet but I believe arrows keep sticking on valkerin skies structures, maybe that or similar could be implemented for the mod, or whatever

**Comment by GrandmaPork** [comment]
Well aren’t they their own projectile entity? I am suggesting that cracker could code in some unique behavior with them to maybe fix one or two things

**Comment by floppydiskdrive6** [comment]
> arrows are entities that's why these kinda things didn't happen in the first place. never tried it yet but I believe arrows keep sticking on valkerin skies structures, maybe that or similar could be implemented for the mod, or whatever

mobs are entities and the storm can pick them up so

**Comment by nonamecrackers2** [comment]
Programming them to stay with the cluster would be difficult and not worth the endeavour, making the arrows be effected by tractor beams is possible. However you’ll have to open a new suggestion for that since only one suggestion per issue is allowed.

**Comment by GrandmaPork** [comment]
Oh okay I can do that then

**Comment by GrandmaPork** [comment]
Okay I will do that then
