### ISSUE TITLE
[Suggestion]: killing the WS should remove block clusters along with it

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1517]
### Description of feature request

When killing the Wither Storm using the regular `/kill` command, which now only removes the entity without playing the death animation, it could remove the block clusters it picks up along with it, because if you want to quickly get rid of the storm without having clusters flying around your trees after that, this could be useful. Maybe the mod could detect if the player runs the kill command and choses the WS as the or one of the target entities, and kill the block cluster entities aswell.

Or if that's too difficult, how about a new sub-command, `/witherstormmod remove @w` which acts like the same idea, instead of using `/witherstormmod kill @w` which plays the animation etc. or simply `/kill @w`, using `/witherstormmod remove @w` could remove it the same way as the `/kill` command along with removing all clusters.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
