### ISSUE TITLE
[Suggestion]: New Tainted Mobs: Withered Dogs, Withered Cats, and Withered Axolotls.

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#1519]
### Description of feature request

Since there are just not that much withered mobs, how about 3 more withered mobs. And they are all hostile, even the tamed ones.

**Comment by NinjaSam5399** [comment]
I'm evil

**Comment by TaintedBlockmObile** [comment]
Pretty sure more sickened mobs will come in part 2

**Comment by NinjaSam5399** [comment]
Including these mobs?

**Comment by TaintedBlockmObile** [comment]
Probably. I wouldn't say it's out of the question.

**Comment by LegendaryGodzilla** [comment]
wither sickened witer stom when??????

**Comment by NinjaSam5399** [comment]
today

**Comment by GrandmaPork** [comment]
Um read guidelines in pretty sure cracker said to not request new tainted mobs cuz they’ll get to them eventually

**Comment by nonamecrackers2** [comment]
Yes, please read the guidelines

**Comment by NinjaSam5399** [comment]
ok

**Comment by BluePineappleGuy** [comment]
> wither sickened witer stom when??????

bro, the storm _is_ the sickness.
