### ISSUE TITLE
Tractor beams should pull entities like tnt, boats, minecarts, etc.

### ISSUE THREAD

**Issue by NEFFLEAFF** [nonamecrackers2/crackers-wither-storm-mod#152]
Now that wither storm pulls anything that touches a tractor beam, i think it would be cool to make those entities also be attracted.

Edit by nonamecrackers2: Including items as well.

**Comment by ghost** [comment]
I do agree, it's supposed to pull in and destroy anything it gets near so that would be very logical.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
