### ISSUE TITLE
[Bug]: the wither storm has rendering issues with using pollution of the realms

### ISSUE THREAD

**Issue by ComradeOctoling** [nonamecrackers2/crackers-wither-storm-mod#1520]
### Minecraft Version

1.19.4

### Mod Version

3.3.1

### Mod Loader

Forge

### Mod Loader Version

45.1.19

### Describe the bug

the wither storm has rendering issues when far away with pollution of the realms

### Steps to Reproduce

1. add pollution of the realms and it's dependency to your mods folder with cwsm enabled
2. summon the wither storm and set it's phase to phase 4 or above 
3. go far from the wither storm
4. see that only the tracker beams render NOTE: the wither storm renders at night, but during the day only the tracker beams render 

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot 2023-09-29 041235](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144869444/480db001-d4bb-4199-b458-ed35dc89576d)

### Mod List

![leaked mods folder (new)](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144869444/b346f0bd-95b0-4494-9141-735567399eac)
![leaked mods folder (new) 2](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/144869444/ed34fe9b-b1ee-4304-8f3e-d8a8b2b84dfe)

**Comment by floppydiskdrive6** [comment]
weird

**Comment by nonamecrackers2** [comment]
Was able to reproduce, but this does not appear to be fixable on my end. You'll have to contact the developers of pollution of the realms to fix this one.
