### ISSUE TITLE
[Suggestion]: Mini Bowles Challenge When Eaten

### ISSUE THREAD

**Issue by Sol00er** [nonamecrackers2/crackers-wither-storm-mod#1521]
Description:

When a player gets pulled up to a head and gets a few bites taken out of them they eventually get swallowed and transported to a mini version of the Bowles where they will have accelerated wither sickness so they will have a limited time to escape, how may the player escape you may ask?Well when the player gets to the mini Bowles they have to win a challenge, they either have to fight a horde if infected mobs or win a parkour challenge when the player wins either one, the wither will spit them out with no fall damage and the bigger the phase the harder the challenge will get.Why should this be added?Well it would certainly be far more interesting than hitting a black screen once you get fully sucked up to a head and would be fairer to less skilled players also would just be cool.And maybe just maybe just maybe you could get a peek at the command block if you look for it.

**Comment by Laughingcat27** [comment]
That's actually a reall cool idea. Getting pulled up by a tractor beam without the proper equipment to break your fall is immediately a death sentence atm. With this suggestion you can still get a second chance but you shouldn't rely on it because everytime you get taken to the mini bowels you'll lose hp faster from the wither sickness. That gives a reason to still fear the storm while being able to do something back

**Comment by Sol00er** [comment]
Thanks maybe the chances of getting swallowed could be higher during the early phases or the player could have a choice of getting swallowed or the chances of getting swallowed could be higher if the player does very little damage to the head letting more prepared and geared players the chance of escape while less equipped players could have another chance of escape through the challenge.

**Comment by TaintedBlockmObile** [comment]
I feel this could get really annoying if you aren't prepared in time. And I think someone made a suggestion like this in discord and crackers said they wouldn't be altering the bowels but we'll see.

**Comment by nonamecrackers2** [comment]
This isn’t very Minecraft-y and wouldn’t fit in with the mod very well. Interesting idea though
