### ISSUE TITLE
[Suggestion]: Mobs fall from ceiling during command block fight

### ISSUE THREAD

**Issue by Sol00er** [nonamecrackers2/crackers-wither-storm-mod#1522]
### Description of feature request

When fighting the command block mobs just spawn in, and while it works, it would be much cooler if the withered mob blocks on the ceiling fell and turned into their respective mob its a small change but a cool one.

**Comment by nonamecrackers2** [comment]
I don’t think this would work very well or look good, but it’s an interesting idea
