### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by ahmetenesay** [nonamecrackers2/crackers-wither-storm-mod#1523]
### Description of feature request

I don't like to brag, but I won't use my modesty on this matter. I haven't looked too much into Wither Storm's main code file, WitherStormEntity.class. But I'm pretty sure that wither strom uses the "Invulnerable" tag, a built-in NBT data tag in Minecraft, to make him invincible. Namely, this invincibility can be caused by some scripts, data packages, etc. that invalidate the NBT data tag (Invulnerable). there is. All this means that your use of Minecraft's built-in tags for wither storm and withered symbiont may be the target of some sycophants or spoiled critics. Long story short, Wither Storm and his minions are literally invincible, uninteractable, and immune to everything. You'd better do a more advanced AI procedure yourself ;}

**Comment by GrandmaPork** [comment]
Isn’t being invincible to everything the point of it all??

**Comment by TaintedBlockmObile** [comment]
Yeah.. the wither and symbiont is supposed to be invincible to everything but it's weak point.

**Comment by nonamecrackers2** [comment]
The Wither Storm or symbiont does not use the “Invulernable” NBT tag, but instead checks if a given damage type can affect the entity. The Wither Storm is intentionally invulnerable (configurable) while the symbiont can only be attacked on its weak point when it’s bent over.
