### ISSUE TITLE
[Suggestion]: withered ores

### ISSUE THREAD

**Issue by floppydiskdrive6** [nonamecrackers2/crackers-wither-storm-mod#1527]
### Description of feature request

ores that are ores but withered

**Comment by Sol00er** [comment]
Why?

**Comment by NinjaSam5399** [comment]
I like this idea.

**Comment by NinjaSam5399** [comment]
But lets not add Withered Ancient Debris.

**Comment by floppydiskdrive6** [comment]
> Why?

why not?

**Comment by floppydiskdrive6** [comment]
maybe even withered tools or something

**Comment by TaintedBlockmObile** [comment]
Tainted wood and stone??

**Comment by BluePineappleGuy** [comment]
imagine if you can make withered armor with these, or further powerup a withered beacon

**Comment by floppydiskdrive6** [comment]
> Tainted wood and stone??

there already is tainted wood and stone

**Comment by floppydiskdrive6** [comment]
> imagine if you can make withered armor with these, or further powerup a withered beacon

that would be cool

**Comment by nonamecrackers2** [comment]
You'll have to elaborate; tainted ore blocks or withered items that come from the ore blocks?

**Comment by BluePineappleGuy** [comment]
> You'll have to elaborate; tainted ore blocks or withered items that come from the ore blocks?

i think he means things like tainted diamonds, iron, etc.

**Comment by floppydiskdrive6** [comment]
> You'll have to elaborate; tainted ore blocks or withered items that come from the ore blocks?

witch ever you decide

**Comment by floppydiskdrive6** [comment]
your the owner so you can do witch ever you want

**Comment by floppydiskdrive6** [comment]
you could just do raw ore ingots that you can smelt into normal ore ingots

**Comment by floppydiskdrive6** [comment]
items

**Comment by nonamecrackers2** [comment]
Personally, I'm not sure what tainted ore could even be used for (withered ore items would be a bit useless, since I'm not adding withered versions of tools, etc) besides decoration, so I think this is a bit pointless. Thanks for the suggestion though.
