### ISSUE TITLE
[Squash hitboxes issue] Witherstorm (Hunchback) does not pick up dropped items

### ISSUE THREAD

**Issue by ShirakiShio** [nonamecrackers2/crackers-wither-storm-mod#153]
**Minecraft version**
1.18.2

**Mod version**
Latest as of typing this

**Describe the bug**
Witherstorm does not pickup dropped items. Instead they jitter back and forth

**To Reproduce**
You go to mars and set up a base, grow plants and eventually a civilization. Eventually, one of the people will mutate and turn into a Witherstorm, consuming all except things people dropped.

**Crash Reports / Logs**
None

**Screenshots**
https://gyazo.com/6c86fac17c907cf52c2c84d11e94e744

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update
