### ISSUE TITLE
[Suggestion]: A use for super tnt other than crafting.

### ISSUE THREAD

**Issue by craft97804** [nonamecrackers2/crackers-wither-storm-mod#1530]
### Description of feature request

Maybe super tnt could be used to damage the wither storm in some way for like 10 minutes or something, but not cause it to fake die, and instead stun it.

**Comment by GrandmaPork** [comment]
Please make a new post for the second suggestion and edit #2 out

**Comment by GrandmaPork** [comment]
Also check guidelines before posting

**Comment by BluePineappleGuy** [comment]
so essentially leave the heads stunned for an extended period of time.

**Comment by craft97804** [comment]
> so essentially leave the heads stunned for an extended period of time.

also stop it from moving for some time and change its appearance until it recovers

**Comment by myron-obsolete-account** [comment]
we have TNT being able to "stun" the heads already, maybe super TNT could force the head to be damaged to disable the tractorbeam for like 2 minutes, idk

**Comment by nonamecrackers2** [comment]
This would require a lot of work to kill a Symbiont (you'd also deviate from progression a lot) just for something that would "stun" the Wither Storm, which is frankly not worth the effort. At this point you should just craft another formidibomb since it'll still work and you can have the Wither Storm down for an hour.

**Comment by myron-obsolete-account** [comment]
> This would require a lot of work to kill a Symbiont (you'd also deviate from progression a lot) just for something that would "stun" the Wither Storm, which is frankly not worth the effort. At this point you should just craft another formidibomb since it'll still work and you can have the Wither Storm down for an hour.

make that two, I've got villages to raid :trollface:

**Comment by BluePineappleGuy** [comment]
> > This would require a lot of work to kill a Symbiont (you'd also deviate from progression a lot) just for something that would "stun" the Wither Storm, which is frankly not worth the effort. At this point you should just craft another formidibomb since it'll still work and you can have the Wither Storm down for an hour.
> 
> make that two, I've got villages to raid :trollface:

one time i blew up 9 formidibombs on a village, then added super tnt dupers. 10/10 would recommend

**Comment by myron-obsolete-account** [comment]
> > > This would require a lot of work to kill a Symbiont (you'd also deviate from progression a lot) just for something that would "stun" the Wither Storm, which is frankly not worth the effort. At this point you should just craft another formidibomb since it'll still work and you can have the Wither Storm down for an hour.
> > 
> > 
> > make that two, I've got villages to raid :trollface:
> 
> one time i blew up 9 formidibombs on a village, then added super tnt dupers. 10/10 would recommend

I did it with like 40 F-Bombs but the game just bugged out, they flew where they unloaded and as soon as I went to different locations they kept exploding
