### ISSUE TITLE
[Suggestion]: Tractor Beam Block

### ISSUE THREAD

**Issue by craft97804** [nonamecrackers2/crackers-wither-storm-mod#1531]
### Description of feature request

After killing the wither storm for real some of the heads would fall to the ground in block form, alongside the flesh and tainted block structures, with the eyes being the tractor beam block, and you could also craft it with the withered beacon. It would be powered by redstone and when activated it would make a tractor beam facing whatever direction the block is facing in.

**Comment by TaintedBlockmObile** [comment]
I like this but it kinda goes out the scope of the mod imo

**Comment by BluePineappleGuy** [comment]
> I like this but it kinda goes out the scope of the mod imo

yeah, its unlikely, but there should be a side mod for this. its an extremely interesting concept and could do a lot of things

**Comment by nonamecrackers2** [comment]
Interesting idea but doesn't really fit in with the mod's vanilla-esc vision
