### ISSUE TITLE
[Suggestion]: Wither Storm Phase 0 Drop

### ISSUE THREAD

**Issue by SpringerPlayz29** [nonamecrackers2/crackers-wither-storm-mod#1532]
### Description of feature request

Make If you manage to kill the wither storm in phase 0 it drops a normal nether star, simple enough suggestion.

**Comment by Asteroid4** [comment]
i mean, people have defeated it easily when starting with netherite gear and a lot of potions, so this is feasible to happen.

**Comment by myron-obsolete-account** [comment]
the WS is not supposed to be defeated in hunchback phases. people who geared up to godmode before fighting it to death do not get the whole point of the mod, and as Cracker said somewhere else (yes this is a duplicate btw): it'll defeat the whole point, and the player will miss like 80 more percent of what this mod has to offer, not just the small pre-phases.

**Comment by BluePineappleGuy** [comment]
an idea: when killed in its hunchback stages, the storm falls down to the ground, then disappears and in its place is another incomplete spawn totem.

**Comment by nonamecrackers2** [comment]
#571
