### ISSUE TITLE
[Suggestion]: Gamerule to deactivate the spawn house or a config

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1533]
### Description of feature request

I think this feature request is pretty straight foreward.

**Comment by TaintedBlockmObile** [comment]
Can do this with a datapacks crackers created

**Comment by FalconinVoid** [comment]
> Can do this with a datapacks crackers created

Can you leave a link?

**Comment by myron-obsolete-account** [comment]
> > Can do this with a datapacks crackers created
> 
> Can you leave a link?

idk, can he? :D
https://www.curseforge.com/minecraft/customization/no-rundown-house

**Comment by FalconinVoid** [comment]
Thanks
