### ISSUE TITLE
[Suggestion]: More shaking effects

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1534]
### Description of feature request

I would love, if you get in a chase and when a wither head explodes next to you, then the camera shakes like crazy or if you get sucked up that beam the camera shakes more.

**Comment by myron-obsolete-account** [comment]
current camera shaking is only ocurring when touching the ground so that might need a new implementation of the camera shake effect

**Comment by Aimyx** [comment]
I personally think the shaking effect is underused
Maybe you could also have some screen shake when a large cluster is picked up nearby, or as this issue suggests, with wither head explosions.

**Comment by FalconinVoid** [comment]
Yes! More shaking babeh! ;)

**Comment by BluePineappleGuy** [comment]
bro closed it
