### ISSUE TITLE
[Suggestion]: More biome based spawn house variation

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1535]
### Description of feature request

I would like to have more biome-based spawn house differences, so something different in a jungle or desert than the normal version, which fits more with the plains.

**Comment by myron-obsolete-account** [comment]
it already does have a lot of new rundown houses I guess

**Comment by FrozenDragon0** [comment]
There's already biome based houses depending on what biome it spawns in.

**Comment by FalconinVoid** [comment]
lol

**Comment by nonamecrackers2** [comment]
This is a new feature in the latest update
