### ISSUE TITLE
[Suggestion]: Happy End

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1536]
### Description of feature request

Can the world somehow get fixed again after defeating the WS? So a happy end can be celebrated without those giant holes in the world?

**Comment by GrandmaPork** [comment]
That’d be incredibly laggy. Also the idea is the wither storm destroys terrain and you gotta stop it before it does too much damage but what’s done is done

**Comment by FalconinVoid** [comment]
You have a point

**Comment by myron-obsolete-account** [comment]
you can if you want to do the challenge on a world you already have and love too much to be destroyed, just, copy it and do it there 👍

**Comment by FalconinVoid** [comment]
That's the idea! Install a big map, thanks

**Comment by nonamecrackers2** [comment]
This has been suggested before (however I can't find it), doing this would take a monumental amount of work that wouldn't be worth it. Not to mention tons of issues that may arise from such a feature.
