### ISSUE TITLE
[Suggestion]: Smoother killing of mobs

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1537]
### Description of feature request

The dying animation in the mouth of the WS looks crappy. Plz make an absorbtion animation so it feels more like eating.

**Comment by TaintedBlockmObile** [comment]
Don't think this is needed. There is already mobs that will get absorbed into the mass if caught in the beam when not targeted. And the wither storm eats them not absorb it into its mouth.

**Comment by FalconinVoid** [comment]
I know, but a better dying animation or something that it feels more like eating, cuz it always falls out of the mouth.

**Comment by TaintedBlockmObile** [comment]
Because it dies? I don't think its possible to have a dead entity move anymore

**Comment by myron-obsolete-account** [comment]
I pretty much believe it more like chomps the victim up into pieces (cause of death, hence MC death animation, duh) instead of consuming it, which is already being done by other entities being generally sucked into the WS' mass

**Comment by FalconinVoid** [comment]
Yeah, but a like, the mob could be biten apart into pieces and then get consumed by the witherstorm like other blocks... idk.

**Comment by TaintedBlockmObile** [comment]
> Yeah, but a like, the mob could be biten apart into pieces and then get consumed by the witherstorm like other blocks... idk.

This would be a little too unnecessary to add. And it kinda  goes out the scope of the mod since even story mode didn't really do this

**Comment by FalconinVoid** [comment]
I know, but this triggers as fuck XD

**Comment by BluePineappleGuy** [comment]
> I know, but this triggers as fuck XD

maybe hold off on the swearing, remember kids are on this place too.

**Comment by nonamecrackers2** [comment]
> > I know, but this triggers as fuck XD
> 
> maybe hold off on the swearing, remember kids are on this place too.

Kids aren't technically allowed on GitHub, you have to be 13+ to have an account

**Comment by nonamecrackers2** [comment]
Also, instead of just calling the animation "crappy" you could perhaps include ways to improve it

**Comment by BluePineappleGuy** [comment]
> > > I know, but this triggers as fuck XD
> > 
> > 
> > maybe hold off on the swearing, remember kids are on this place too.
> 
> Kids aren't technically allowed on GitHub, you have to be 13+ to have an account

13 year olds still dont like swearing. i know from experience.

**Comment by myron-obsolete-account** [comment]
> > > > I know, but this triggers as fuck XD
> > > 
> > > 
> > > maybe hold off on the swearing, remember kids are on this place too.
> > 
> > 
> > Kids aren't technically allowed on GitHub, you have to be 13+ to have an account
> 
> 13 year olds still dont like swearing. i know from experience.

I once heard about a 10 year old, you don't wanna know what he said 💀

**Comment by FalconinVoid** [comment]
Just please think about improving the animation idk, do whatever you want.

**Comment by nonamecrackers2** [comment]
Looking back I don't think this is necessary. The mobs are being eaten when they get chomped, not exactly absorbed
