### ISSUE TITLE
[Suggestion]: Make the witherstorm music ON by default

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1538]
### Description of feature request

I am always extremely annoyed, when I have to activate the music again... ._.

**Comment by GrandmaPork** [comment]
Check config files

**Comment by TaintedBlockmObile** [comment]
This is for YouTubers and to stop copyright I think

**Comment by BluePineappleGuy** [comment]
> This is for YouTubers and to stop copyright I think

yes, i think crackers did say he changed it to be off by default to prevent the mod from being copyrighted.

**Comment by myron-obsolete-account** [comment]
> > This is for YouTubers and to stop copyright I think
> 
> yes, i think crackers did say he changed it to be off by default to prevent the mod from being copyrighted.

surely not the mod. antimo and welles told me cracker asked and got permission to use it and in his trailers aswell (they smashed a strike on my channel for uploading an extension of their WS destroyed track :(( thats how we got the smalltalk)

**Comment by FalconinVoid** [comment]
> This is for YouTubers and to stop copyright I think

I understand, but not everyone is a YTber and they can easily turn it off if they want

**Comment by TaintedBlockmObile** [comment]
Yes but most don't know this and turning the music on isn't hard at all. It'll stay on if you play on the same version. Just don't keep switching Minecraft versions

**Comment by FalconinVoid** [comment]
But I play with the witherstorm mod in like 2/3 of all my modpacks XD

**Comment by TaintedBlockmObile** [comment]
> > This is for YouTubers and to stop copyright I think
> 
> I understand, but not everyone is a YTber and they can easily turn it off if they want

It's already extremely easy to just turn it on. No need to add this

**Comment by TaintedBlockmObile** [comment]
> But I play with the witherstorm mod in like 2/3 of all my modpacks XD

Well this still won't be a thing. Just gonna have to deal with it as it is

**Comment by FalconinVoid** [comment]
I just hope it gets on by default, cuz who the fuq wants it to be off? (Exept Youtubers but they can deactivate it, if they want)

**Comment by TaintedBlockmObile** [comment]
> I just hope it gets on by default, cuz who the fuq wants it to be off? (Exept Youtubers but they can deactivate it, if they want)

Once again, some people don't know how to do this. So it's better if it stays off. It isn't hard to turn it on.

You should close this suggestion since it already has a reason for not existing

**Comment by FalconinVoid** [comment]
Just let Cracker decide, I think that would be a huge benifit. Okay? Don't take this too personal bro. Or he could make this setting the first setting, the big important one... idk.

**Comment by GrandmaPork** [comment]
I believe it was on by default but cracker switched. I personally turn it off because it’s very short and the loop gets annoying. If you’re getting annoyed, just copy and paste your config file into each new mod pack you create. Auto applies for each world within the mod pack.

**Comment by nonamecrackers2** [comment]
It's off by default to avoid potential copyright issues with content creators who make videos with the mod. There haven't been any issues with it that I'm aware of, but you never know (of course, this is not legal advice). So no, this will not be changed.

**Comment by FalconinVoid** [comment]
:(

**Comment by myron-obsolete-account** [comment]
> :(

the music config is in client option so it stays on for all worlds, I honestly don't even know what the issue with that is. if you turn it on it stays on until you turn it off.
