### ISSUE TITLE
[Suggestion]: Improved Withered Beacon Witherstorm Resummoning Animation

### ISSUE THREAD

**Issue by craft97804** [nonamecrackers2/crackers-wither-storm-mod#1540]
### Description of feature request

Instead of the command block just shaking and rotating, and sucking up blocks, instead the blocks could turn dark and start rotating around the command block, forming the basic shape of the wither storm eventually, depending on the selected resummoning phase, before resummoning the wither storm.

**Comment by TaintedBlockmObile** [comment]
Now making the shape would be difficult but having it spin into making the wither storm does sound cool

**Comment by craft97804** [comment]
An alternative would be for the command block to start having the flesh build up onto itself, like phase 1-3

**Comment by nonamecrackers2** [comment]
I think the animation is fine as is, this would be extremely difficult to do and not worth implementing, sorry
