### ISSUE TITLE
[Suggestion]: Cave Rumbles Disorientate Mobs

### ISSUE THREAD

**Issue by craft97804** [nonamecrackers2/crackers-wither-storm-mod#1541]
### Description of feature request

Cave rumbles would confuse mobs for some time, for example the mobs could stop moving, and start looking around in random directions until a few seconds have passed since the cave rumble.

**Comment by nonamecrackers2** [comment]
I don't think people would really notice this feature and it would require a decent amount of work to implement that I'm not willing to invest.
