### ISSUE TITLE
[Suggestion]: Severed Bowels

### ISSUE THREAD

**Issue by craft97804** [nonamecrackers2/crackers-wither-storm-mod#1542]
### Description of feature request

Before phase 7.5, the severed witherstorms would grow, and by phase 7.5 would be around phase 4 or phase 5 size. During phase 7.5, all 3 of the witherstorms would get a hole, with a severed wither storms having smaller bowels, and the main one having the current bowels. The severed wither storms bowels would be the same but smaller, and without the command block. The command block room in the severed bowels would be of a room similar to the normal command block room, but without the island or the command block in the center. The hole would function the same as the one in the main command block room.

**Comment by BluePineappleGuy** [comment]
but they're far too small to have a bowels worth exploring, it'd be one small room and thats it.

**Comment by craft97804** [comment]
Maybe the severed wither storms could also grow

**Comment by TaintedBlockmObile** [comment]
I don't see this happens since there would be no point in have 3 different bowels

**Comment by craft97804** [comment]
Just for more loot, or maybe there would be items you can only find inside severed wither storm bowels

**Comment by nonamecrackers2** [comment]
Having separate bowels for the segments is pointless since most people won't go to the lengths to explore them. Also growing segments has been suggested before.
