### ISSUE TITLE
[Suggestion]: Blocks Above Phase 4+ Wither Storms Fall Into It Them

### ISSUE THREAD

**Issue by craft97804** [nonamecrackers2/crackers-wither-storm-mod#1543]
### Description of feature request

Similar to the endercon scene, blocks above wither storms that are phase 4 or above would fall into the witherstorm.

**Comment by BluePineappleGuy** [comment]
this has been suggested at #1463

**Comment by craft97804** [comment]
#1463 is blocks in the same place as the wither storm are absorbed, and this is blocks above

**Comment by BluePineappleGuy** [comment]
> #1463 is blocks in the same place as the wither storm are absorbed, and this is blocks above

ah my bad, misunderstood.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
