### ISSUE TITLE
[Suggestion]: Dropped Blocks And Mobs Become Tainted

### ISSUE THREAD

**Issue by craft97804** [nonamecrackers2/crackers-wither-storm-mod#1544]
### Description of feature request

If mobs, blocks, and block clusters are dropped by the witherstorm, they would become tainted, get wither sickness, or become withered depending on how close to the wither storm they were. For example, if a creeper was about to get absorbed, but the witherstorm was defeated, and dropped it, it would become withered, but if a tree was halfway from the ground to the wither storm, the tree after falling down would be a third made of tainted blocks.

**Comment by GrandmaPork** [comment]
I feel like in order for this to happen the block cluster has to retroactively be changed onto tainted blocks based on the % of it that’s inside the witherstorm’s “aura” and since there’d be so few anyways I’d imagine this unfortunately wouldn’t be noticed in the mess of everything

**Comment by GrandmaPork** [comment]
Mob idea sounds cool tho but only in the pre-f bomb phases

**Comment by nonamecrackers2** [comment]
Interesting idea but this would rarely happen in the case of block clusters, since there are only a handful of scenarios where the Wither Storm will actually drop them. Also most mobs just die when they escape due to fall damage so this idea is a bit pointless. Thank you for your suggestion though.
