### ISSUE TITLE
[Suggestion]: Fishing Rods Work As One Time Grapple Hooks While In Tractor Beams

### ISSUE THREAD

**Issue by craft97804** [nonamecrackers2/crackers-wither-storm-mod#1546]
### Description of feature request

While in tractor beams if you have a fishing rod on you it would be used as a one time grapple hook, to escape the tractor beam, and would stop the witherstorm from picking you up for some time, but would break the fishing rod, and would only work while in a tractor beam.

**Comment by NinjaSam5399** [comment]
Ok, no more suggestions for the day, you made way to many. XD

**Comment by BluePineappleGuy** [comment]
> Ok, no more suggestions for the day, you made way to many. XD

i think everyones been there at some point

**Comment by GrandmaPork** [comment]
You can emulate this with a mod called “grapple” but tbh ender pearls are much safer cuz you get pretty far off the ground pretty quickly so fall damage is a big issue

**Comment by nonamecrackers2** [comment]
Interesting idea, but in my opinion a fishing rod line is probably too thin to counteract the force of a tractor beam. I don't think this is a very necessary feature that would be worth my time to implement, sorry.
