### ISSUE TITLE
[Suggestion]: some way to place costume tractor beams

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1547]
### Description of feature request

Crackers tractor beams are soo cool i really would like to place them down or smthn. They could be configurable how long, wichblocks it sucks or if it sucks blocks or entitys. Mabyemake a sepperate mod? Ijust wanna use those awesome tractor beams with the power in my hands. Probablygonna ends up as an creative item but thats fine too

**Comment by myron-obsolete-account** [comment]
I don't even know how it's supposed to work

**Comment by TaintedBlockmObile** [comment]
This most likely won't happen because it's doesn't make much sense but a separate mod would be better for this

**Comment by GrandmaPork** [comment]
#1531
