### ISSUE TITLE
[Suggestion]: witherstorm on map mods

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1548]
### Description of feature request

It would be really cool to see the witherstorm in a map mod, not really as a head as an icon but to see the whole body fromm upper sight on map mods like xaeros mini and world map would be so awesome, like to see a black blob on the map that approaches your destination, might need a special item to see it very far away tho like a well idk

**Comment by FunkyPotao** [comment]
![Project Capture (55)](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/108956899/542a0f0f-04c7-4565-93e7-bd162a936abe)
Something like this

**Comment by FunkyPotao** [comment]
> ![Project Capture (55)](https://user-images.githubusercontent.com/108956899/273154370-542a0f0f-04c7-4565-93e7-bd162a936abe.jpg) Something like this

Ik the arrow looks ugly

**Comment by GrandmaPork** [comment]
#778 you would have to reach out to map mod developers not here
