### ISSUE TITLE
[Suggestion]: extra mod for op suggestiona

### ISSUE THREAD

**Issue by FunkyPotao** [nonamecrackers2/crackers-wither-storm-mod#1549]
### Description of feature request

Title is self explenatory

**Comment by ERCEpic** [comment]
No, no it really isn’t self explanatory.

**Comment by TaintedBlockmObile** [comment]
Gonna uhh.. need to explain this a little better

**Comment by GrandmaPork** [comment]
So make an extra mod that adds in OP suggestions?

**Comment by BluePineappleGuy** [comment]
i think he means for the more overpowered suggestions in the mod (things that could break progression like the elixir, for instance), there should be a separate mod that adds them so people who want them can have them, but it doesn't come with the main mod.

**Comment by TaintedBlockmObile** [comment]
That's a mod  for someone or himself to make. Not crackers

**Comment by myron-obsolete-account** [comment]
well it shouldnt be here then. this is only for suggestions/issues towards this mod directly I guess

**Comment by nonamecrackers2** [comment]
If someone wants to do this, go ahead. I won't be doing this myself however.
