### ISSUE TITLE
Layering appears even though beam isnt turned on yet.

### ISSUE THREAD

**Issue by ShirakiShio** [nonamecrackers2/crackers-wither-storm-mod#155]
**Minecraft version**
1.18.2

**Mod version**
Latest as of typing this.

**Describe the bug**
The layering effect of the tractor beam appears in the bowels when standing infront of a head, even though the beam isnt active yet.

**To Reproduce**
Stay in the spotlight of everything. It revolves around you, afterall.

**Crash Reports / Logs**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/48332495/176789456-ac13df99-409e-448a-bca4-fab58860dd95.png)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update
