### ISSUE TITLE
[Suggestion]: Command Staff or staff of commanding or something

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#1550]
### Description of feature request

I know many command block weapons have been suggested and turned down, and tbh this one might not work in the mod. I just find the concept interesting. To get this staff, you first must craft an Empty Staff, which could be crafted with:
tainted glass in the top right, sticks in the center and the lower left. To charge the staff, put the empty staff plus X books into the beacon to add Y charges. After charging, the staff will now be filled with command block particles. The staff still doesn't do more damage than punching, but now by holding down right click before releasing it (like a bow), you can fire one of the charges out. This charge can:
- Cause a symbiont that is not currently casting a spell to immediately switch to summoning mobs,
- Break the lens of an external head (if it hits the lens directly,)
- Deal damage to an internal head,
- Freeze a withered mob in place for a few seconds,
- Force a tentacle to drop a player,
- And maybe some other things that I will add here as I come up with them.

**Comment by Gaming32** [comment]
There's currently a voting process for custom weapons in the Discord server. However, submissions are over. You could maybe join and have a chance at the next event, if it happens.

**Comment by nonamecrackers2** [comment]
I'm not sure if there will be a next event, but that could be an opportunity to see this come to life. Otherwise this extends a bit out of scope for the mod, but is an interesting idea.
