### ISSUE TITLE
[Suggestion]: Structures and loot fall upon the storm dying

### ISSUE THREAD

**Issue by Lambda761** [nonamecrackers2/crackers-wither-storm-mod#1552]
### Description of feature request

sometimes, people just go after the command block in the bowels and dont bother exploring the place, maybe when the storm dies a structure with chests falls, usually like a desert or jungle temple, maybe a pillager post, or hell, even a mansion or water temple chunk, but point is, wither storm should atleast a small chance for a structure (or part of it) to drop, because most of the drops are just for decoration.

**Comment by BluePineappleGuy** [comment]
it makes sense, but makes it less needed to go to the bowels for loot

**Comment by TaintedBlock** [comment]
^

**Comment by nonamecrackers2** [comment]
#1441 #1120
