### ISSUE TITLE
Tainted tools

### ISSUE THREAD

**Issue by juanelgamer456** [nonamecrackers2/crackers-wither-storm-mod#1553]
The tainted tools are the result of using tools made of diamond and below (netherite tools not included) against tainted blocks and mobs too much

- After losing a certain and configurable amount of durability, (like more than the half for example) the tool is now able to turn tainted, and the "tainting points count" of the tool start, to avoid this, you have to repair it keeping the tool over the minimun amount of durability stated

- The tainted points needed for each material to get corroded would be:
Wood= 10
Stone= 20
Iron= 50
Gold= 100
Diamond= 250

- and the points given by each action are:

hitting a tainted chiken, cow, mooshroom cow, or villager: 1
hitting a tainted spider, zombie, creeper, or skeleton: 2
hitting a tainted pillager, iron golem, or phantom: 5
hitting a wither sickened player: 5
hitting the withered symbiont: 10

mining tainted dust, dust blocks, or mushrooms: 1
mining tainted sand, pumpkins (and its variations), or leaves: 2
mining tainted planks, logs, cobblestone, or stone: 5
mining flesh skeletons or zombies blocks: 10
mining tainted flesh, infected flesh, or hardened flesh: 15

- when the tool receives enough "tainting points", it gets replaced by a tainted tool, wich have damage and durability stats even lower than wood, giving 5 seconds of wither effect the only advantage these weapons have

- the texture of tainted tools look like a dirty and corroded purple material
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/111206110/7345fd40-3468-4ffc-affa-2835074b8817)
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/111206110/391108a4-b480-40c4-93d1-1235e8ab7234)

- as almost any suggestion, this whole feature should be able to be enabled and disabled

once again, thanks for crackers or anyone in the dev team for taking the time to read this suggestion

**Comment by TaintedBlock** [comment]
Nice idea. Don't know if it'll get it but I do like this

**Comment by Draco1246** [comment]
I really like this idea. It could add some extra challenge for those who seek it. I think it would be best if this feature was able to be toggled though.

**Comment by juanelgamer456** [comment]
I forgot to add that you can obviously repair the tool to avoid this but seems like most people actually just figure it out (it's an obvious option as I just said)

**Comment by juanelgamer456** [comment]
> I really like this idea. It could add some extra challenge for those who seek it. I think it would be best if this feature was able to be toggled though.

yeah i added that at the end lol

**Comment by nonamecrackers2** [comment]
Super cool idea, however it extends a bit out of scope for the mod. Could be an interesting addon to CWSM though

**Comment by BluePineappleGuy** [comment]
i think someone should make an additions mod that has all the ideas that are cool but don't fit the vision for the mod. i'd do it but i dont know proper modding and can only make them through Mcreator, which wouldn't allow for all these.
