### ISSUE TITLE
Legacy Texture Mode

### ISSUE THREAD

**Issue by Draco1246** [nonamecrackers2/crackers-wither-storm-mod#1555]
### Description of feature request

Although the new texture for the Witherstorm's flesh is cool, I prefer the original version. So I suggest the ability to switch the Witherstorm, along with other newly textured items/mobs back to their original counterparts. This could come as a new drop-down section which would include a switch for every legacy texture.

**Comment by Gaming32** [comment]
Or just a builtin resourcepack, similar to Programmer Art.

**Comment by myron-obsolete-account** [comment]
I thought there was one already?

**Comment by BluePineappleGuy** [comment]
do you mean like a programmer art resource pack, or the original textures from the earlier versions of the mod?
if the second one, crackers has already made a resource pack for that. its not built in, but you can access it if you go to his account projects page.

**Comment by nonamecrackers2** [comment]
> I thought there was one already?

There's an original textures resource pack on CurseForge but it's not built into the mod. Could consider having it built in like Programmer Art.

**Comment by Draco1246** [comment]
Yeah, I meant a built-in thing, because I know nothing about files or texture stuff. I was thinking a switch in the Wither storm Mod Settings tab (if that's possible for you to code), but a built-in texture pack would also work.

**Comment by BluePineappleGuy** [comment]
something similar should be done for the "no rundown house" datapack

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
