### ISSUE TITLE
[Suggestion]: A configurable max phase

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#1556]
### Description of feature request

Basically, for servers where you aren't supposed to kill the wither storm, or they implement their own way to kill it. In the config, there would be a maximum phase slider, and once the wither storm reaches what would normally be the end of that phase, it would instead begin the "enderman stealing blocks" effect.

**Comment by TaintedBlock** [comment]
> ### Description of feature request
> Basically, for servers where you aren't supposed to kill the wither storm, or they implement their own way to kill it. In the config, there would be a maximum phase slider, and once the wither storm reaches what would normally be the end of that phase, it would instead begin the "enderman stealing blocks" effect.

uhh.. how would you kill it..?

**Comment by TaintedBlock** [comment]
Like what's the point if you can't kill it?? And you can technically do this by using repeating command blocks and setting its phase

**Comment by Asteroid4** [comment]
The point is that on those servers, it is supposed to exist forever. And yes, repeating command blocks setting the phase do technically work, it would be a nightmare for TPS.

**Comment by TaintedBlockmObile** [comment]
> The point is that on those servers, it is supposed to exist forever. And yes, repeating command blocks setting the phase do technically work, it would be a nightmare for TPS.

Well there is always redstone timers

**Comment by BluePineappleGuy** [comment]
for these servers, isn't there the option to disable the bowels in the world config?

**Comment by Asteroid4** [comment]
there is, but some servers may want the wither storm to stop growing sooner

**Comment by nonamecrackers2** [comment]
There is

**Comment by Aimyx** [comment]
> There is

Then shouldn’t this be closed?

**Comment by TaintedBlockmObile** [comment]
> > There is
> 
> Then shouldn’t this be closed?

He's probably think on it. Most request stay open if he's thinking about if he should add it

**Comment by myron-obsolete-account** [comment]
> > There is
> 
> Then shouldn’t this be closed?

cracker answered to that theres a config for no bowels in servers, but not that the OP's requested feature exists

**Comment by nonamecrackers2** [comment]
> > There is
> 
> Then shouldn’t this be closed?

No since that won't do for what OP is suggesting

**Comment by nonamecrackers2** [comment]
Gonna close since an upcoming update will include a "lock" command that will prevent the Wither Storm from advancing its phase progress. You should be able to detect what phase it is with commands and then use the lock command appropriately. There is also the config option to disable the bowels if that's what you're looking for.
