### ISSUE TITLE
[Suggestion]: Upgradeable Command weapons

### ISSUE THREAD

**Issue by Aimyx** [nonamecrackers2/crackers-wither-storm-mod#1558]
### Description of feature request

So basically, If you have a wood command sword, then you could upgrade it (or downgrade?) to a stone command sword with a anvil + stone. This is like take a gold command Pick + iron = Iron command Pick. this would probably use a buttload of xp to do thou, and maybe, like take a Iron command Sword + Iron Pick = iron command pick?

**Comment by TaintedBlockmObile** [comment]
I don't see this being needed since once you get a withered Beacon you can summon an unlimited amount of symbionts

**Comment by nonamecrackers2** [comment]
I don’t think this is very necessary, it kind of forces the player to choose a tool and stick with it
