### ISSUE TITLE
[Suggestion]: Add a means of decrafting command tools

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1559]
### Description of feature request

In case somebody crafts the wrong tool, it'd be a great feature to allow people to undo said mistake. It'd be an awful experience to accidently craft a command block iron pickaxe instead of a diamond sword for anybody trying to take down the storm for the first time. Implementation should be left to developers, but using an unenchanted command tool on a grindstone could be one, destroying the tool in the process to get the book. I'd propose that whatever means is used for decrafting doesn't give back the tool to prevent using one book to swap between an entire toolset (not to mention a free repair on the go.) However, any solution would work, preferably not using the withered beacon.

**Comment by nonamecrackers2** [comment]
I don’t think people would craft the wrong tool accidentally. Also, I said on another post wishing to add a similar idea that this would remove the thought and intentionality behind picking a specific tool.

**Comment by TaintedBlock** [comment]
> I don’t think people would craft the wrong tool accidentally. Also, I said on another post wishing to add a similar idea that this would remove the thought and intentionality behind picking a specific tool.

Couldn't you just have the ability to disenchant? Or is the cmnd book not like that?

**Comment by nonamecrackers2** [comment]
Wdym exactly?

**Comment by TaintedBlockmObile** [comment]
> Wdym exactly?

With that one grindstone thing that can also be found at villages. It can remove enchantments off of weapons

**Comment by nonamecrackers2** [comment]
That should work, I don't know how that's related to this suggestion though
