### ISSUE TITLE
[Suggestion] Add some purple particles after the Wither Storm revive maybe better

### ISSUE THREAD

**Issue by MaxIceFlame** [nonamecrackers2/crackers-wither-storm-mod#156]
I think you can add some purple particles around the Wither Storm after the it revive for a moment. Purple particles like thi
![QQ截图20220701085949](https://user-images.githubusercontent.com/38246896/176802609-97035d02-6639-43e4-b895-96bf7b08e03a.png)
s
And I think you can add some glowing purple blocks on the side of Wither Storm Segment, too
![QQ截图20220701090029](https://user-images.githubusercontent.com/38246896/176802740-6dcdd5dc-6b06-4eb2-9a2d-4ae4520f8c76.png)
.

**Comment by nonamecrackers2** [comment]
I'll use #63 to track the glowing areas. The particles I don't feel are totally necessary.
