### ISSUE TITLE
Withered Symbiont can deal area damage

### ISSUE THREAD

**Issue by ahmetenesay** [nonamecrackers2/crackers-wither-storm-mod#1560]
### Description of feature request

Withered Symbiont can deal area damage. This is exactly what I mean: When the Withered Symbiont hits an entity with its hand when its health is reduced to half or with another trigger (you decide), an invisible damage area can be created. Just like killaura. In this way, when it hits only one entity, other entities in a certain area can also be damaged. Sounds pretty cool, right?

**Comment by nonamecrackers2** [comment]
I don’t think this would make much sense for the melee attack, it doesn’t seem like something that would have an area of effect.
