### ISSUE TITLE
[Suggestion]: Withered Beacon destruction prevention

### ISSUE THREAD

**Issue by Nintadso** [nonamecrackers2/crackers-wither-storm-mod#1561]
### Description of feature request

I don't know it's a bug or if it's intended, but I think it's a shame the Withered Beacon gets destroyed when resummoning the Wither Storm... Defeating it is already enough of a hassle, but you're also forced to only have one beacon, because the beacon gets destroyed and there's no way to obtain another command block either...

**Comment by GrandmaPork** [comment]
If you’re resummoning the wither storm… something tells me it’s not gonna be there for long either way.
Also can’t you make another beacon by defeating it again? 
command block is unobtainable in survival so it makes sense that there is no way to get it back. Download a different mod if you want that to be a feature

**Comment by Nintadso** [comment]
Yeah here's the thing : you *can* make another beacon, but you'd lose the first one. Basically I think it'd be nice if those things could be stacked

**Comment by TaintedBlock** [comment]
> Yeah here's the thing : you _can_ make another beacon, but you'd lose the first one. Basically I think it'd be nice if those things could be stacked

I think you underestimate how op the withered beacon is

**Comment by BluePineappleGuy** [comment]
they are quite overpowered, but one thing that _is_ annoying is any  connected support beacons also get destroyed when the storm resummons, meaning you'd have to kill 4 withers again to craft more.

**Comment by TaintedBlockmObile** [comment]
> they are quite overpowered, but one thing that _is_ annoying is any connected support beacons also get destroyed when the storm resummons, meaning you'd have to kill 4 withers again to craft more.

It's the consequence of summoning another wither storm so 🤷🏾‍♂️

**Comment by Asteroid4** [comment]
Well, it is prob best to then take the withered beacon from the full setup, move it a few thousand blocks, then summon the wither storm. That way, you can keep everything

**Comment by nonamecrackers2** [comment]
You’re only ever intended to have one withered beacon and it’s destruction is intentional
