### ISSUE TITLE
[Suggestion]: Should we have an official Minecraft server?

### ISSUE THREAD

**Issue by FireCode125** [nonamecrackers2/crackers-wither-storm-mod#1562]
### Description of feature request

I think it would be cool to have an official Minecraft server for this mod, so that we can play together. It's kinda not hard to notice that the server advertisements channel has almost no participation, so if we just had an official main server we would actually be able to play the mod together. Plus, there's a lot of creative and talented people in the discord, and I think it would be cool to see what everyone can build. I'm not really sure who would actually host the server, but I'm sure it wouldn't be too hard to find someone who can host.

**Comment by TaintedBlock** [comment]
So an SMP? This is probably something you COULD ask in discord but I think here is a little better.

**Comment by Bloxxify2827** [comment]
If he does, he should totally add the Custom Player Models plugin so i can use my amazing models muhahaha

**Comment by Laughingcat27** [comment]
Cracker's Modded Community's Official Modded Minecraft Server

**Comment by TaintedBlock** [comment]
> If he does, he should totally add the Custom Player Models plugin so i can use my amazing models muhahaha

Bloxxify trying to go a day without promoting his models:

**Comment by Bloxxify2827** [comment]
> > If he does, he should totally add the Custom Player Models plugin so i can use my amazing models muhahaha
> 
> Bloxxify trying to go a day without promoting his models:

Hey man i make some of the most immaculate and amazing models

**Comment by Bloxxify2827** [comment]
> Cracker's Modded Community's Official Modded Minecraft Server

Hm, i dont know about a modded server, i think a vanilla one with some plugins would be good

But theres always the chance he adds CWSM and we can have that kind of chaos

**Comment by GrandmaPork** [comment]
I think it’d be best to suggest this in the discord. This is the GitHub for the wither storm mod

**Comment by Bloxxify2827** [comment]
Yeah, but on github it wont be flooded out by some random conversations

**Comment by myron-obsolete-account** [comment]
> > > If he does, he should totally add the Custom Player Models plugin so i can use my amazing models muhahaha
> > 
> > 
> > Bloxxify trying to go a day without promoting his models:
> 
> Hey man i make some of the most immaculate and amazing models

ok..?

**Comment by Bloxxify2827** [comment]
> > > > If he does, he should totally add the Custom Player Models plugin so i can use my amazing models muhahaha
> > > 
> > > 
> > > Bloxxify trying to go a day without promoting his models:
> > 
> > 
> > Hey man i make some of the most immaculate and amazing models
> 
> ok..?

If you couldn’t tell that was a (mostly) sarcastic comment

**Comment by BluePineappleGuy** [comment]
> > Cracker's Modded Community's Official Modded Minecraft Server
> 
> Hm, i dont know about a modded server, i think a vanilla one with some plugins would be good
> 
> But theres always the chance he adds CWSM and we can have that kind of chaos

its gotta be modded if its a server for a mod.

**Comment by Bloxxify2827** [comment]
> > > Cracker's Modded Community's Official Modded Minecraft Server
> > 
> > 
> > Hm, i dont know about a modded server, i think a vanilla one with some plugins would be good
> > But theres always the chance he adds CWSM and we can have that kind of chaos
> 
> its gotta be modded if its a server for a mod.

Sure, some light mods i suppose. But im not sure how a server will hold up with alot of people on AND a witherstorm at once. I say maybe a small modpack if they do make a server, 15 or less mods.

**Comment by nonamecrackers2** [comment]
This is not the place for these kind of suggestions, feel free to go to the discussions page here on GitHub or join our discord server which is linked on the mod page
