### ISSUE TITLE
[Suggestion]: Bowels load when Wither is released

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1563]
### Description of feature request

Currently, the bowels load when the last skull is being placed on the spawn structure, causing the game to tick-freeze for a few seconds, and the wither being inside the spawn structure for that time until the blocks disappear. I believe it would look better if the bowels would load when the Wither is being released (when the countdown/charge up is finished), so the spawning of the creature is finally smooth, and that little lag for later is not that bad, right?

(alternatively the bowels could load when the WS is at phase 7.5 but that's rather not so good of an idea I believe)

**Comment by TaintedBlock** [comment]
I think the way it is now is better because its the very beginning and you have more then enough time to run

**Comment by myron-obsolete-account** [comment]
> I think the way it is now is better because its the very beginning and you have more then enough time to run

yeah that's not the point of my suggestion though. time for running away will stay the same, I never mentioned that

**Comment by TaintedBlockmObile** [comment]
> > I think the way it is now is better because its the very beginning and you have more then enough time to run
> 
> yeah that's not the point of my suggestion though. time for running away will stay the same, I never mentioned that

I'm saying I don't see the point in the change.

**Comment by myron-obsolete-account** [comment]
> > > I think the way it is now is better because its the very beginning and you have more then enough time to run
> > 
> > 
> > yeah that's not the point of my suggestion though. time for running away will stay the same, I never mentioned that
> 
> I'm saying I don't see the point in the change.

I literally mentioned it above

> causing the game to tick-freeze for a few seconds, and the wither being inside the spawn structure for that time until the blocks disappear. I believe it would look better if the bowels would load when the Wither is being released [...], so the spawning of the creature is finally smooth

right there

**Comment by Aimyx** [comment]
Yeah, seeing the ws face the wrong direction, inside blocks ain’t cool. Big yes for this one.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
