### ISSUE TITLE
!idle Animations!

### ISSUE THREAD

**Issue by Sam-uel-Shiroko** [nonamecrackers2/crackers-wither-storm-mod#1565]
In this suggestion, the wither storm is going to have an idle animation or a floating animation. This animation is not gonna be that complex but fairly simple. The tractor beams might be a problem though. The animations is gonna be the wither storm slowly moving up, down, sideways and possibly some very little rotations too. These movements are gonna be very slow and only travel a very little distance. (1-3 blocks) These animations are gonna be greatly slowed down too when the player is currently in the tractor beams. For the severed, it's gonna be the same but a little faster and some little more rotations that are absolutely not 360°. I am greatly looking forward for these animations in future updates!

**Comment by nonamecrackers2** [comment]
I don't have plans to do any more animations and feel personally the look/feel of it is completed and does not need altering. Thanks for your suggestion though.
