### ISSUE TITLE
Symbiont fight change suggestion

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1567]
### Description of feature request

Please make it possible for the Wither Storm to grab the player with tracktor beams. The Wither Storm should ignore the player in the fight, but I got into the beam once in the fight and didn't got sucked up, what's kinda unrealistic.

**Comment by Laughingcat27** [comment]
i think it's more important that you can fight the symbiont undisturbed by the tractor beams, than that it feels wrong for the beams to not pick you up at all. If they did pick you up, then it would make the fight pretty annoying.
lore-wise you could say uhhhh the storm filtered the player out of its tractor beams' target list so the symbiont can do all the work for it.

**Comment by GrandmaPork** [comment]
This is a feature but I agree it needs to be adjusted cuz I was beamed up while running towards the symbiont 

I misread whoops I don’t want this feature

**Comment by nonamecrackers2** [comment]
This is intended, it would suck if you were fighting it and you got sucked up, dropped, and then died due to fall damage
