### ISSUE TITLE
[Suggestion]: Better progression for spawning 

### ISSUE THREAD

**Issue by EthanRStokes** [nonamecrackers2/crackers-wither-storm-mod#1569]
### Description of feature request

Basically,
The mod by default gives the resources necessary to spawn the wither storm at the very start of the game via the run down houses

I think it would make sense to have an option for the resources to not be given, only a command block or something
That way the player actually has progressed through the game before spawning

**Comment by TaintedBlockmObile** [comment]
I mean you could just like.. destroy the other materials completely and then come back. The point of the mod is to spawn the wither and then progress through the game. Tho it can be played by progressing then spawning.

**Comment by GrandmaPork** [comment]
I disagree with this for many reasons
1. Probably the biggest is you need to enter the nether to collect wither skulls. During that time all blaze powder and other resources needed for the f bomb can be collected so you will spend majority of time waiting for the wither storm to evolve
2. Being geared up to fight the wither storm right away is not nearly as fun as working for the gear while running from it

**Comment by nonamecrackers2** [comment]
This is something more geared towards a custom datapack/modpack.
