### ISSUE TITLE
[Bug] Clusters above 256 instantly disappear

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#157]
1.18.2 

1.18.2-2.0

As the title says, blocks above 256 aren't ever absorbed if the WS is too high up because they're immediately deleted

**Comment by watersofnazareth** [comment]
This might actually be related to the Witherstorm being above world height in general, the 256 blocks thing happens in the Twilight Forest

**Comment by nonamecrackers2** [comment]
Yeah, probably is just the twilight forest's 256 world height then. I'll change this to allow them to go above world height in case the wither storm happens to be.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update
