### ISSUE TITLE
[Suggestion]: Limit the "Randomized" UTT to just Random stroll, random stroll near player, none and nearest in singleplayer

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1572]
### Description of feature request

Im not sure this was implemented already as i haven't experienced this mod in multiplayer nor have i messed around with "randomized" but im suggesting just incase. I feel "randomized" shouldn't switch to "Farthest" and "Group" in  singleplayer worlds because you know, its singleplayer why would it have to switch to those?

"last suggestion from me, for now atleast"

**Comment by BluePineappleGuy** [comment]
those ones act the same as nearest in singleplayer

**Comment by nonamecrackers2** [comment]
Yeah and this would remove those functionalities for multiplayer

**Comment by Luke7381** [comment]
> Yeah and this would remove those functionalities for multiplayer

I was saying that "randomized" shouldn't be able to switch to farthest or group on singleplayer worlds as it wouldn't make sense.

**Comment by BluePineappleGuy** [comment]
> > Yeah and this would remove those functionalities for multiplayer
> 
> I was saying that "randomized" shouldn't be able to switch to farthest or group on singleplayer worlds as it wouldn't make sense.

So since those ones act the same as nearest, it essentially triples the chance of it targeting the nearest, when they should all have the same probability.

**Comment by nonamecrackers2** [comment]
> > Yeah and this would remove those functionalities for multiplayer
> 
> I was saying that "randomized" shouldn't be able to switch to farthest or group on singleplayer worlds as it wouldn't make sense.

Ah I see, that's my bad

**Comment by Luke7381** [comment]
> > > Yeah and this would remove those functionalities for multiplayer
> > 
> > 
> > I was saying that "randomized" shouldn't be able to switch to farthest or group on singleplayer worlds as it wouldn't make sense.
> 
> Ah I see, that's my bad


I updated it just incase you forget when checking back here or something.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
