### ISSUE TITLE
[Design Suggestion]: Consume Detail

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1573]
### Description of feature request

Let the block clusters explode into blocks when touching the witherstorm and then let it get consumed. (Would be a cool detail)

**Comment by TaintedBlockmObile** [comment]
Could you elaborate a little bit on what you mean here?

**Comment by myron-obsolete-account** [comment]
> Could you elaborate a little bit on what you mean here?

block clusters that blow up into single blocks.

**Comment by TaintedBlockmObile** [comment]
> > Could you elaborate a little bit on what you mean here?
> 
> block clusters that blow up into single blocks.

Technically they can already do this tho.

**Comment by FalconinVoid** [comment]
> > block clusters that blow up into single blocks.
> 
> Technically they can already do this tho.
Fr? Is this the "Block Clusters Drop Items" Setting?

**Comment by BluePineappleGuy** [comment]
> > > block clusters that blow up into single blocks.
> > 
> > 
> > Technically they can already do this tho.
>
>  Fr? Is this the "Block Clusters Drop Items" Setting?

that makes them drop items as if they were broken. causes a heavy increase in lag tho

**Comment by TaintedBlockmObile** [comment]
> > > block clusters that blow up into single blocks.
> > 
> > 
> > Technically they can already do this tho.
> > Fr? Is this the "Block Clusters Drop Items" Setting?

No. The block cluster can split apart and come in a few varieties. Even one blocks clusters. Sometimes they break apart into small pieces. Idk about into singular blocks tho.

**Comment by myron-obsolete-account** [comment]
> > > > block clusters that blow up into single blocks.
> > > 
> > > 
> > > Technically they can already do this tho.
> > > Fr? Is this the "Block Clusters Drop Items" Setting?
> 
> No. The block cluster can split apart and come in a few varieties. Even one blocks clusters. Sometimes they break apart into small pieces. Idk about into singular blocks tho.

I don't think they break apart into single blocks. never seen it at least

**Comment by GrandmaPork** [comment]
I would say there should be a config for this but I think clusters can contain over 27 blocks so multiply that by how many have been picked up and you got hella lag

**Comment by FalconinVoid** [comment]
My PC can withstand the lag with a gen 13 Intel Core and a 4070Ti Graphic Card! 😎

**Comment by GrandmaPork** [comment]
Okay but like nobody else can

**Comment by TaintedBlockmObile** [comment]
Not many people at least

**Comment by nonamecrackers2** [comment]
Don't feel this is necessary, especially considering that block clusters already split in half occasionally
