### ISSUE TITLE
[Suggestion]: Blocks Around Gets Withered

### ISSUE THREAD

**Issue by Sam-uel-Shiroko** [nonamecrackers2/crackers-wither-storm-mod#1576]
### Description of feature request

When the wither storm is in one place for a little too long time, some blocks that haven't turned into a cluster yet will or has a chance to turn into a withered version of that block. It should be configured however. One of the examples are obstructed blocks from the reach of the wither storm's vision. Like in the interiors of buildings

**Comment by NinjaSam5399** [comment]
This has been already suggested.

**Comment by GrandmaPork** [comment]
#441
