### ISSUE TITLE
Cracker's Witherstorm: Evolution Part 1 Or 2

### ISSUE THREAD

**Issue by Draco1246** [nonamecrackers2/crackers-wither-storm-mod#1577]
### Description of feature request

My suggestion is simple: Compatibility for Snapshot 23W13A_OR_B, aka the 2023 April Fools update. This would be where you could add all of your dumb ideas that couldn't make it into the main mod. I already have an idea for a feature that would be in this version:

The Witherstorm could fly up and follow you to the Moon if you go there. If the Moon is made of cheese and the witherstorm consumes a single block, it instantly dies as it is lactose intolerant.

**Comment by Pandaboi25x** [comment]
Crackers said its impossible on forge and he can only do it on fabric i did indeed ask 😔

**Comment by Draco1246** [comment]
Aw that sucks. Still would be hilarious though.

**Comment by Pandaboi25x** [comment]
> Aw that sucks. Still would be hilarious though.

Yeah

**Comment by BluePineappleGuy** [comment]
I mean, a joke version of the mod would be awesome.
