### ISSUE TITLE
[Suggestion]: Wither Storm Plays the ''Wither Storm Evolves'' Sound effect every time it changes Phases (And i dont mean subphases)

### ISSUE THREAD

**Issue by Steve982950** [nonamecrackers2/crackers-wither-storm-mod#1578]
### Description of feature request

I think it would be nice if you add the ''Wither Storm Evolves'' Sound Effect So you dont have to keep checking the phase.

**Comment by TaintedBlockmObile** [comment]
I don't think checking what phase its at is what you want to be doing with your time lol

**Comment by IndigoAmethyst** [comment]
I feel like it's fine as it is as it describes a discharge of power that doesn't happen again. Plus having it play 7 times per storm would quickly get old.

It also would mean players won't have to check the Storm for progress. Cracker could think differently tho

**Comment by myron-obsolete-account** [comment]
I don't think it'll be a good idea, actually it might be pretty annoying, hearing an evolution sound every time. the key moment is the evolution from hunchback to destroyer, everything else is for you to figure out and fight against

**Comment by Steve982950** [comment]
tbh i realise that.
