### ISSUE TITLE
[Contribute translation] zh_CN translation for mod latest version 1.18.2-2.0

### ISSUE THREAD

**Issue by MaxIceFlame** [nonamecrackers2/crackers-wither-storm-mod#158]
[zh_cn.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9024667/zh_cn.zip)

This is the zh_CN translation for mod latest version 1.18.2-2.0
I translated the new things and I corrected some mistranslations
Not support upload json file so I uploaded zip file and the json file is in it

**Comment by nonamecrackers2** [comment]
Could you make a pull request instead please?

**Comment by MaxIceFlame** [comment]
ok. I'll make one tomorrow

---Original---
From: ***@***.***&gt;
Date: Fri, Jul 1, 2022 23:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nonamecrackers2/crackers-wither-storm-mod] [Contributetranslation] zh_CN translation for mod latest version 1.18.2-2.0 (Issue #158)




 
Could you make a pull request instead please?

**Comment by nonamecrackers2** [comment]
Sounds good
