### ISSUE TITLE
[Suggestion]: Tainted Sapling

### ISSUE THREAD

**Issue by CappyKid** [nonamecrackers2/crackers-wither-storm-mod#1580]
### Description of feature request

Remember those Tainted Trees in the bowels? Well I was thinking that if you break the leaves off of it, there is a chance a Tainted Sapling will appear. Like the other respective saplings, it can grow a tainted tree. The sapling can also be obtained by placing 5 Oak Saplings on a Withered Beacon.

**Comment by GrandmaPork** [comment]
#1111 before making a suggestion, I recommend searching with “is:issue” and a keyword from your recommendation (in this case, sapling)

**Comment by CappyKid** [comment]
> #1111 before making a suggestion, I recommend searching with “is:issue” and a keyword from your recommendation (in this case, sapling)

Oh shoot you're right. Lol

**Comment by CappyKid** [comment]
Already requested
