### ISSUE TITLE
[Suggestion]: Bowels Update

### ISSUE THREAD

**Issue by GangMistrzuniu** [nonamecrackers2/crackers-wither-storm-mod#1581]
### Description of feature request

Maybe make it rotate i saw a guy who made data pack that made bowels rotate for your mod it was called BWSB but the datapack stopped working i think

**Comment by TaintedBlockmObile** [comment]
The bowels fight isn't supposed to be impossible bro 😭

Also, rotating the bowels isn't possible.

**Comment by GangMistrzuniu** [comment]
Ye I forgot that not everyone use armors mods 😭 I edited it but I saw data pack for rotating bowels
Here is link https://www.curseforge.com/minecraft/texture-packs/bwsb-better-wither-storm-bowels-and-more

**Comment by TaintedBlockmObile** [comment]
> Ye I forgot that not everyone use armors mods 😭 I edited it but I saw data pack for rotating bowels Here is link https://www.curseforge.com/minecraft/texture-packs/bwsb-better-wither-storm-bowels-and-more

I recommend using Explorer's Eve as a way to make cwsm harder

**Comment by GangMistrzuniu** [comment]
> > Ye I forgot that not everyone use armors mods 😭 I edited it but I saw data pack for rotating bowels Here is link https://www.curseforge.com/minecraft/texture-packs/bwsb-better-wither-storm-bowels-and-more
> 
> I recommend using Explorer's Eve as a way to make cwsm harder

But what about that data pack which makes bowels rotate

**Comment by TaintedBlockmObile** [comment]
> > > Ye I forgot that not everyone use armors mods 😭 I edited it but I saw data pack for rotating bowels Here is link https://www.curseforge.com/minecraft/texture-packs/bwsb-better-wither-storm-bowels-and-more
> > 
> > 
> > I recommend using Explorer's Eve as a way to make cwsm harder
> 
> But what about that data pack which makes bowels rotate

You said it was outdated. And bowels rotation most likely won't be added anyway.

**Comment by GangMistrzuniu** [comment]
> > > > Ye I forgot that not everyone use armors mods 😭 I edited it but I saw data pack for rotating bowels Here is link https://www.curseforge.com/minecraft/texture-packs/bwsb-better-wither-storm-bowels-and-more
> > > 
> > > 
> > > I recommend using Explorer's Eve as a way to make cwsm harder
> > 
> > 
> > But what about that data pack which makes bowels rotate
> 
> You said it was outdated. And bowels rotation most likely won't be added anyway.

Nothing is impossible the creator of data pack will possibly update or help me fix it (I'm creating Wither Storm modpack and it's possible that mods break the data pack) and there are mods that change gravity i remember using a mod that changed gravity to upside down with special boots but It was possible to do it without armor so instead of rotating the bowels cracker can change gravity,screen rotation and models to upside down for players and mobs in bowels after Command block have half HP left but I think its very hard to do but not impossible

**Comment by TaintedBlockmObile** [comment]
Again, crackers has addressed this kind of suggestion already saying he wouldn't be doing that. Also flipping all the mobs wouldn't work since I believe that would require reworking the whole bowels fight

**Comment by GangMistrzuniu** [comment]
> Again, crackers has addressed this kind of suggestion already saying he wouldn't be doing that. Also flipping all the mobs wouldn't work since I believe that would require reworking the whole bowels fight

He said he want to do this but it's clearly Impossible but I believe that to do it you need to change these things and change half of bowels fight but it would be amazing I'm gonna think about another way to do it

**Comment by nonamecrackers2** [comment]
Please read the guidelines
