### ISSUE TITLE
[Bug]: When i beat wither storm it tps me and then somehow 2 wither storms appeared.

### ISSUE THREAD

**Issue by kapycta123456** [nonamecrackers2/crackers-wither-storm-mod#1582]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Describe the bug

1 wither storm was basic one 2nd wither storm was really strange. It didn't had heads, tentacles. It also had segments that was dying too. 2nd one was also rotated a bit.

### Steps to Reproduce

I don't know how that happened

### Crash Reports/Logs

There was no crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

(https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/148063104/d4883b11-4dfa-4a9a-8c99-f926e199712d)
The image of 2nd wither storm

### Mod List

Rubidium, Oculus, CWSM

**Comment by kapycta123456** [comment]
That 2nd wither storm was also stuck in my upper screen

**Comment by TaintedBlockmObile** [comment]
This happens with any shaders. I don't think it's something crackers can fix

**Comment by kapycta123456** [comment]
> This happens with any shaders. I don't think it's something crackers can fix

That's sad. :(

**Comment by myron-obsolete-account** [comment]
#1412 
   #1207

**Comment by myron-obsolete-account** [comment]
@kapycta123456 can you please close this since its a duplicate you saw my comment because you reacted already

**Comment by nonamecrackers2** [comment]
What people have already said. This is a shader issue and I'm not aware of a fix for it. This is also a duplicate

**Comment by kapycta123456** [comment]
Very sad.. Very very sad..

**Comment by kapycta123456** [comment]
> What people have already said. This is a shader issue and I'm not aware of a fix for it. This is also a duplicate

Very sad..
