### ISSUE TITLE
[Suggestion]: Cluster coloring distance config

### ISSUE THREAD

**Issue by Aimyx** [nonamecrackers2/crackers-wither-storm-mod#1584]
### Description of feature request

Basically, you can change the amount of distance away the clusters turn black, in order to compensate for like, flying hight changes so the clusters don’t instantly turn black, 
or also have the clusters just not instantly turn black when spawned at all?

**Comment by TaintedBlock** [comment]
The clusters do compensate to flying height tho.

**Comment by Aimyx** [comment]
> The clusters do compensate to flying height tho.

Not from what I’ve seen, the distance the coloring starts never changes when on different heights.

**Comment by TaintedBlockmObile** [comment]
Well the clusters turn dark pretty quickly and you might not have set it high enough

**Comment by Aimyx** [comment]
> Well the clusters turn dark pretty quickly and you might not have set it high enough

I have tried with the max hight all the way to the min hight. Nothing changes with the clusters that much, except just generally being farther away

**Comment by nonamecrackers2** [comment]
I don't think a config is necessary, however better implementation for the cluster fade could be possible. I'd open a new issue for that however

**Comment by Aimyx** [comment]
I have opened a big report issue for this.
