### ISSUE TITLE
[Suggestion]: New death sound for the Wither Storm. 

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1585]
### Description of feature request

Yes, I did indeed make this myself. 
https://youtu.be/yb5jYSyq2Mk

**Comment by BluePineappleGuy** [comment]
hasn't a new sound/animation been suggested already?

**Comment by TaintedBlockmObile** [comment]
No idea but since I made my own version I think it's fine

**Comment by BluePineappleGuy** [comment]
> No idea but since I made my own version I think it's fine

i guess so

**Comment by Pandaboi25x** [comment]
ngl this would fit for my new ws death animation suggestion i really like that

**Comment by myron-obsolete-account** [comment]
there already has a new sound been suggested #840 you can make a resource pack which I did with mine

**Comment by TaintedBlockmObile** [comment]
> there already has a new sound been suggested #840 you can make a resource pack which I did with mine

This suggestion is for a completely remade death sound not to keep the one we have.

**Comment by myron-obsolete-account** [comment]
> > there already has a new sound been suggested #840 you can make a resource pack which I did with mine
> 
> This suggestion is for a completely remade death sound not to keep the one we have.

bro what did I just say 💀

**Comment by TaintedBlockmObile** [comment]
> > > there already has a new sound been suggested #840 you can make a resource pack which I did with mine
> > 
> > 
> > This suggestion is for a completely remade death sound not to keep the one we have.
> 
> bro what did I just say 💀

Dude I understand what you said, but I'm still keeping this here. Yes I already know I can make a resource pack but that isn't the point. If it gets closed as a duplicate then so be it.

**Comment by LegendaryGodzilla** [comment]
si

**Comment by nonamecrackers2** [comment]
I actually kind of like it, I might consider adding it in

**Comment by TaintedBlock** [comment]
Ayy :D

**Comment by myron-obsolete-account** [comment]
of course

**Comment by nonamecrackers2** [comment]
We're going to be sticking to the current sound as of now

**Comment by juanelgamer456** [comment]
well, it was better than never trying
