### ISSUE TITLE
[Bug]: Mod freezes and deletes Witherstorm on re-launch

### ISSUE THREAD

**Issue by Fs3077** [nonamecrackers2/crackers-wither-storm-mod#1586]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

Randomly while playing the game will freeze. The player can still move, break blocks, place blocks, etc, but no items will drop and no mobs will move. You also cannot take damage.

**When exiting the world, it gets stuck on "saving world". No crash log is found.**

When i rejoin, the witherstorm is gone.

### Steps to Reproduce

1. Launch the game
2. Join a world
3. Play for a while
4. Issue arises

### Crash Reports/Logs

https://pastebin.com/iUGUsKwr

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Mods in **_italic + bold_** are what i think could be problematic (Error occured most while using waystones, at least in my experience)

AppleSkin

bad packets

Balm (Forge Edition)

Better Brightness Slider

Clumps

Collective

_**Cracker's Wither Storm Mod**_

Cupboard

_**Embeddium**_

_**JourneyMap**_

Just Enough Items (JEI)

_**Mekanism**_

Mekanism Additions

Mekanism Generators

Mekanism Tools

Mouse Tweaks

_**Nether Portal Spread**_

Refined Storage

TexTrue's Embeddium Options

_**Waystones**_

WI Zoom

WorldEdit

WTHIT Forge Edition

WTHIT Harvestability

**Comment by nonamecrackers2** [comment]
Looks like you ran out of memory. 1.20.1 is known to have a memory leak issue which could be the cause. I'd try increasing your RAM, if that doesn't work try removing CWSM to see if the problem persists. If that fixes it, come back here and let me know and I'll reopen this issue.

**Comment by Fs3077** [comment]
I increased the allocated ram and everything is working fine. Thanks!

**Comment by nonamecrackers2** [comment]
You're welcome! Glad that was the fix
