### ISSUE TITLE
[Bug]: Cluster color snapping

### ISSUE THREAD

**Issue by Aimyx** [nonamecrackers2/crackers-wither-storm-mod#1587]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

Latest

### Describe the bug

When a block cluster is spawned, when it finishes shaking, if it is close enough to the storm, ex: with lowered flying height, it will instantaneously snap to the required darkness. 

### Steps to Reproduce

1. Go to a block cluster that is shaking
2. Watch it get released 
3. See error

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Cwsm 
Rubidium 
Oculus

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
