### ISSUE TITLE
[Suggestion]: Patron Cosmetic visible in 1st person

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1588]
### Description of feature request

okay I see no reason why this shouldn't annoy me in the first 5 minutes I would have this setting on but I think it would be kinda cool being able to see it in 1st person. a toggle (off by def.) would fit for this I believe.

**Comment by myron-obsolete-account** [comment]
> You can use the first person playermodel mod for this

I hate to see the playermodel though

**Comment by Aimyx** [comment]
> > You can use the first person playermodel mod for this
> 
> I hate to see the playermodel though

Then disable that part in the config bruv

**Comment by myron-obsolete-account** [comment]
> > > You can use the first person playermodel mod for this
> > 
> > 
> > I hate to see the playermodel though
> 
> Then disable that part in the config bruv

then tell me that there is an option to disable the visiblity of the playermodel on a mod that enables the visibility of the playermodel bruv
