### ISSUE TITLE
[Suggestion]: Fresh Animations support

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#1589]
### Description of feature request

Okay I see that the creator of that resource pack should rather add animations for the CWSM mobs, but I hardly believe they will, and I thought of a way that might be working, but idk coding so maybe scrap that right away.
only thing that would really be required is animations for the sickened mobs, so a sickened mob uses the same new animation from the resourcepack like the original one does (e.g. sickened zombie uses same animations from FA like the normal one does with that pack)
idk if that's complicated or if I should try and look into how it would work, and worst of it all, how would the symbiont be animated? it's technically a zombie but it also swings its arms like an evoker for summoning. maybe just use the zombie animations for that one? idk duh.

**Comment by Aimyx** [comment]
The mobs from fresh animations use custom models

**Comment by myron-obsolete-account** [comment]
> The mobs from fresh animations use custom models

crap

**Comment by Aimyx** [comment]
I do want this feature if cracker ever wanted to go through hell  and back to add it

**Comment by Gaming32** [comment]
I don't think it would be that hard to implement, though the feature would require the same mods as Fresh Animations does (so ETF and EMF).

**Comment by Aimyx** [comment]
Ya know, that might be possible, open this back up to see what cracker thinks

**Comment by myron-obsolete-account** [comment]
> I don't think it would be that hard to implement, though the feature would require the same mods as Fresh Animations does (so ETF and EMF).

the requirement of these mods or optifinesucks (much rather ETF and EMF then) is probably unavoidable but it is how it is. maybe there could be an additional sorta forked version which adds support for sickened mobs from this mod or whatever, idk

**Comment by Aimyx** [comment]
>which adds support for sickened mobs from this mod or whatever, idk

What if they just make auto support with anything with “zombie” in its name?

**Comment by juanelgamer456** [comment]
> > which adds support for sickened mobs from this mod or whatever, idk
> 
> What if they just make auto support with anything with “zombie” in its name?

i tried that, its not that easy

**Comment by juanelgamer456** [comment]
> > I don't think it would be that hard to implement, though the feature would require the same mods as Fresh Animations does (so ETF and EMF).
> 
> the requirement of these mods or optifinesucks (much rather ETF and EMF then) is probably unavoidable but it is how it is. maybe there could be an additional sorta forked version which adds support for sickened mobs from this mod or whatever, idk

also there is a mod that adds only the custom models features and is not optifine, but the mod cant be modified to "support for the pack" we have to make a new one that changes the models of modded mobs

**Comment by BluePineappleGuy** [comment]
only one problem, fresh animations uses optifine and cwsm has tons of compatibility issues with it.

**Comment by myron-obsolete-account** [comment]
> only one problem, fresh animations uses optifine and cwsm has tons of compatibility issues with it.

have you missed the talk? we are using ETF and EMF, optifine is OUT

**Comment by BluePineappleGuy** [comment]
> > only one problem, fresh animations uses optifine and cwsm has tons of compatibility issues with it.
> 
> have you missed the talk? we are using ETF and EMF, optifine is OUT

ah sorry, didn't notice
also what is ETF and EMF?

**Comment by myron-obsolete-account** [comment]
> > > only one problem, fresh animations uses optifine and cwsm has tons of compatibility issues with it.
> > 
> > 
> > have you missed the talk? we are using ETF and EMF, optifine is OUT
> 
> ah sorry, didn't notice also what is ETF and EMF?

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/d61e60e1-a2d3-4e4f-b599-28f41f41ad55)
basically optifine without the optical fining 
(Fresh Animation works well with these)

**Comment by MFNmodding** [comment]
those mods are actually made with fresh animations in mind.

**Comment by TaintedBlockmObile** [comment]
This suggestion aged well

**Comment by MFNmodding** [comment]
how so? did i miss an announcement?

**Comment by TaintedBlockmObile** [comment]
Nope. Someone is making a resource pack currently and it's going quite well

**Comment by nonamecrackers2** [comment]
Closing since this now exists: https://modrinth.com/resourcepack/vn4s-fresh-wither-storm
