### ISSUE TITLE
[Bug]: Command block iron hoes do 16.5 damage

### ISSUE THREAD

**Issue by PolarBearFace** [nonamecrackers2/crackers-wither-storm-mod#1591]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.1.43

### Describe the bug

The iron command block hoe does 16.5 damage. Is that a real bug? Because that is insanely overpowered.
![2023-10-18_19 21 18](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/148401073/a3b5404b-90d4-45ed-aa76-3dd7f2d94664)

### Steps to Reproduce

1. Go into creative
2. Look for iron command block hoe.
3. See stats

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

None

**Comment by TaintedBlock** [comment]
This is intended. Its a scythe. Its also the slowest weapon

**Comment by Laughingcat27** [comment]
all my homies spend our iron on hoes

**Comment by nonamecrackers2** [comment]
This is intended
