### ISSUE TITLE
[Bug]: The amulet won't turn

### ISSUE THREAD

**Issue by Soupyfrog** [nonamecrackers2/crackers-wither-storm-mod#1592]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

1.20.1

### Describe the bug

When I do Shift Right-Click to rotate the amulet and select a different color nothing happens, I'm not sure what to do.

### Steps to Reproduce

Shift right click with the amulet and hope it doesnt work 🙏

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

NONE

**Comment by kapycta123456** [comment]
Well.. try reinstalling mod

**Comment by myron-obsolete-account** [comment]
maybe you set sneaking on a different keybind. I set mine on Alt and it works with the sneaking key, not specifically shift.

**Comment by BluePineappleGuy** [comment]
i've had the same problem where the amulet has no visual indications, but that was in previous versions. is the witherstormmod resources (under resource packs) at the top? that might fix the issue.

**Comment by nonamecrackers2** [comment]
Does it make a click sound without rotating?

**Comment by nonamecrackers2** [comment]
Closing until more information is given

**Comment by myron-obsolete-account** [comment]
I love how some people just don't respond anymore and their issue is left out in the dark forever lmao
