### ISSUE TITLE
[Suggestion]: Animation when growing up to phase 4.

### ISSUE THREAD

**Issue by kapycta123456** [nonamecrackers2/crackers-wither-storm-mod#1593]
### Description of feature request

Demonstration: <iframe width="560" height="315" src="https://www.youtube.com/embed/qRYSQCg6QhI?si=w1Js4nchcKF183t8&amp;controls=0&amp;clip=UgkxNdx2TmAxlCG9aLdR2yCMiu2PFCJJWCNC&amp;clipt=EK2JDBjj1Qw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
I really would like to see that

**Comment by kapycta123456** [comment]
oops

**Comment by kapycta123456** [comment]
> oops

THAT WAS ACCIDENT SORRY

**Comment by MoRoN222** [comment]
please close it as not planned because its not completed
