### ISSUE TITLE
[Suggestion]: Phase 4 evolve animation.

### ISSUE THREAD

**Issue by kapycta123456** [nonamecrackers2/crackers-wither-storm-mod#1594]
### Description of feature request

Demostration: https://youtube.com/clip/Ugkx8Iua2dc5ePBNqZLFsaZ4hqSFc6VAb6-p?si=Cw8WdYaFAMQmystP
I really would like to be it in mod.

**Comment by myron-obsolete-account** [comment]
like #178 that heads come out of the body over a short period of time or more inbetweening phaes which has been suggested too many times because nobody checks if other already suggested it which makes this another duplicate to say it the nicest way?

**Comment by nonamecrackers2** [comment]
#178
