### ISSUE TITLE
[Suggestion]: beacon's cluster fall instead of floating

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1596]
### Description of feature request

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/7e83b9b3-1342-4a2a-af1c-23eca8962af0)
basically this happens and it would be better if it actually fell instead of floating *title self explaining*

**Comment by Aimyx** [comment]
I'm pretty sure this is not intended, and also possibly a bug, clusters
DON'T float on their own without a wither storm nearby,

**Comment by Pandaboi25x** [comment]
> I'm pretty sure this is not intended, and also possibly a bug, clusters DON'T float on their own without a wither storm nearby,

i know its not intended, and they do float on their own when breaking a beacon i even mentioned beacon's clusters smh

**Comment by BluePineappleGuy** [comment]
i can see the background, what map is that

**Comment by Aimyx** [comment]
wasn't aware this was after the beacon was broken, this should be a bug
report, however.

**Comment by Pandaboi25x** [comment]
I accidently out suggestion instead of bug alright

**Comment by Pandaboi25x** [comment]
> i can see the background, what map is that

Mcsm map of course

**Comment by BluePineappleGuy** [comment]
> > i can see the background, what map is that
> 
> Mcsm map of course

ofc its mcsm, which map, theres a lot of them

**Comment by Pandaboi25x** [comment]
> > > i can see the background, what map is that
> > 
> > 
> > Mcsm map of course
> 
> ofc its mcsm, which map, theres a lot of them

the 1:1 map smh

**Comment by myron-obsolete-account** [comment]
> > > > i can see the background, what map is that
> > > 
> > > 
> > > Mcsm map of course
> > 
> > 
> > ofc its mcsm, which map, theres a lot of them
> 
> the 1:1 map smh

just link it ffs I want it too :((

**Comment by Pandaboi25x** [comment]
https://www.planetminecraft.com/project/mcsm-rebuilt-in-minecraft/ heres the map bros

**Comment by myron-obsolete-account** [comment]
splendid, big thankening

**Comment by BluePineappleGuy** [comment]
> https://www.planetminecraft.com/project/mcsm-rebuilt-in-minecraft/ heres the map bros

thx, i've been looking for one for ages

**Comment by nonamecrackers2** [comment]
This is more of a bug so I'll mark it as such

**Comment by myron-obsolete-account** [comment]
> This is more of a bug so I'll mark it as such

literally
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/a16b932d-df80-4ded-878d-ad5013fa8528)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release.
