### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by Luke29811** [nonamecrackers2/crackers-wither-storm-mod#1597]
### Description of feature request

maybe you could like code it to where the patreon supporters minecraft skins can spawn in the bowels you could try to list them all off with one of those username checkers

**Comment by myron-obsolete-account** [comment]
what about the ghost title

**Comment by HammedBurngur** [comment]
I actually wanted more realistic looking bodies in the bowels

**Comment by GrandmaPork** [comment]
Honestly I like this idea a lot. Maybe those who’ve built sections of the bowels get their body in their section?

**Comment by TaintedBlock** [comment]
> Honestly I like this idea a lot. Maybe those who’ve built sections of the bowels get their body in their section?

yes

**Comment by BluePineappleGuy** [comment]
could also include the skins of players on the server in the larger tunnels or the arena.

**Comment by nonamecrackers2** [comment]
If you could add a title that would be most appreciated

**Comment by nonamecrackers2** [comment]
Closing until title is given

**Comment by juanelgamer456** [comment]
and bro never added a title

**Comment by juanelgamer456** [comment]
and bro never gave it a title

**Comment by BluePineappleGuy** [comment]
> and bro never gave it a title

and bro got lag

**Comment by juanelgamer456** [comment]
> > and bro never gave it a title
> 
> and bro got lag

i indeed did 😭

**Comment by HammedBurngur** [comment]
where title bro
