### ISSUE TITLE
[Suggestion]: Worst omen effect

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1598]
### Description of feature request

basically when you kill a sickened pillager with a banner on its head you get the worst omen that will look like this
![worst_omen](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/062c09b7-63b9-4a0d-9f19-71f002141dbd)
close up
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/34822295-fd36-4be0-b581-b482ff2e3c73)
and when you go to a village the ws will go where you are at light speed and once its 500 blocks away from the village it will start raining, then there would be command block particles in a random area that spawns the sickened pillagers near the village and the ws would be distracted while you fight the raid, when your almost done with the raid the command block would spawn a new mutant mob that only appears in raids (the only sickened mobs that can appear are: sickened pillagers, new mutant sickened mob, sickened zombies)

**Comment by CappyKid** [comment]
Classic W idea from Panda.

**Comment by BluePineappleGuy** [comment]
so a withered raid, and a storm to top it all off.

awesome but needs a symbiont involved as well

**Comment by CappyKid** [comment]
Yeah. Maybe the Symbiont found in the bowels could work?

**Comment by Pandaboi25x** [comment]
> so a withered raid, and a storm to top it all off.
> 
> awesome but needs a symbiont involved as well

nah a new sickened mutant mob would be cooler

**Comment by TheEyeOfGaming** [comment]
Sounds good.

**Comment by Steve982950** [comment]
light speed? you mean '' Is Chasing''? or EVEN FASTER than that?

**Comment by Pandaboi25x** [comment]
> light speed? you mean '' Is Chasing''? or EVEN FASTER than that?

even faster *well there could be an option for this that makes it chasing instead of goin faster for performance*

**Comment by Steve982950** [comment]
ok

**Comment by nonamecrackers2** [comment]
Interesting idea but this expands a bit out of scope for the mod, this would also be a very rare occurrence that wouldn't be seen by most people making the effort to implement it not worth it.

**Comment by Pandaboi25x** [comment]
was worth a shot
