### ISSUE TITLE
[Suggestion]: Revamped tentacle animations and models

### ISSUE THREAD

**Issue by just-a-thing** [nonamecrackers2/crackers-wither-storm-mod#1599]
### Description of feature request

First of all, this mod is amazing. However, the tentacles connected to the storm have very restricted movement, and have pretty simplistic models. 

I suggest improving the models of the tentacles, and have them move with more freedom. By doing this, I would imagine it would make the storms tentacles look more lively and visually appealing.

**Comment by TaintedBlock** [comment]
Crackers will not be changing the models or tentacles.

**Comment by Aimyx** [comment]
I'm gonna say the thing. Please read the Guidelines. #217
