### ISSUE TITLE
[Suggestion]: Wither storm segment AI revamp

### ISSUE THREAD

**Issue by TNTPLAYZEXE318** [nonamecrackers2/crackers-wither-storm-mod#1602]
*CLOSED*

welp i tired

i typed all of that for nothing

**Comment by CappyKid** [comment]
This is an interesting idea. Might be hard to program, but let's see what the man himself has to say. :D

**Comment by TaintedBlock** [comment]
Technically part of this is already a thing. The segments do move on their own now. They can turn and move a bit more freely around the wither storm.

**Comment by TNTPLAYZEXE318** [comment]
thanks for pointing that out TaintedBlock, but it will be like that but just a little more freely and they can move further away from the storm than normal just to search for the player

**Comment by Aimyx** [comment]
I think giving the segments more movement capability is possible, as they
are separate mobs, however, another idea could be that when in a situation
the main ws would get distracted, a segment would instead of the main
storm, another possibility is that when in the stage 6-7 symboint fight,
the segments would make a really big circle with the main ws around the
player. just some ideas idk.

**Comment by TaintedBlockmObile** [comment]
> thanks for pointing that out TaintedBlock, but it will be like that but just a little more freely and they can move further away from the storm than normal just to search for the player

Again, they can already do this. They just can't get too far for obvious reasons.

**Comment by BluePineappleGuy** [comment]
the reason they currently dont move far is because they dont chunkload, so they'll be left behind and get unloaded.

**Comment by TNTPLAYZEXE318** [comment]
thank you everyone for pointing these things out... so i will add another thing

wither storm segments get chunk loaders.
i can already see people telling me about wither storm segments not having chunk loaders and i will fix that right now.

once a wither storm segment gets left behind the wither storm segments will have their own chunk loader. that means that if one or 2 get left behind they wont just get deleted like many people said.

**Comment by TNTPLAYZEXE318** [comment]
and also i will get rid of one thing in the desc and add another thing because that is already in game (: thank you all for pointing out the issues and what is already in the mod.

**Comment by TNTPLAYZEXE318** [comment]
e

**Comment by TaintedBlock** [comment]
> thank you everyone for pointing these things out... so i will add another thing
> 
> wither storm segments get chunk loaders. i can already see people telling me about wither storm segments not having chunk loaders and i will fix that right now.
> 
> once a wither storm segment gets left behind the wither storm segments will have their own chunk loader. that means that if one or 2 get left behind they wont just get deleted like many people said.

This could cause performance to tank for some people. That's like spawning 3 different wither storms in your world, which is possible without crashing, but would be hell for some.

**Comment by TaintedBlock** [comment]
I can see them going a little farther than they do now withing the withers range but otherwise, Idk about this one, sorry.

**Comment by TNTPLAYZEXE318** [comment]
its ok taintedblock.

**Comment by Steve982950** [comment]
I like this idea, may take a bit of time to code AND bugs may occur

**Comment by nonamecrackers2** [comment]
The segments have their own chunk loaders (although with a very small radius) in the 1.20.1 version. Also I don’t overly like the distracted idea and would prefer to have the segments to stick by the main wither storm as much as possible

**Comment by TNTPLAYZEXE318** [comment]
welp i tried
