### ISSUE TITLE
[Suggestion]: Option to return the old Symbiont theme "Action Suspense"

### ISSUE THREAD

**Issue by anonymoususer923847** [nonamecrackers2/crackers-wither-storm-mod#1603]
### Description of feature request

So in The Sky Darkens update the old Symbiont theme was replaced with the current theme. The current theme is fire but there are some aspects that the old theme still does better. I believe that there should be an option in the mod to toggle between the old and the new theme for the Symbiont as some players may still like the old theme more. Thanks!

**Comment by TaintedBlockmObile** [comment]
You can do this with resource packs

**Comment by BluePineappleGuy** [comment]
what taintedblock said. you can download an older version that had the old theme, convert it to zip and extract, and then poke around for the needed sound files.

**Comment by nonamecrackers2** [comment]
#1162
