### ISSUE TITLE
[Suggestion]: Resource pack template?

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1604]
### Description of feature request

So not a feature for the mod iteself but a "guide" or "helper".
I think for those who want to replace textures and sounds there should be a resource pack file with the textures and sounds which would allow people to easily make there own resource packs for this mod.

**Comment by TaintedBlock** [comment]
You could just search this up on your own tho. It should work the same as doing it with any other mod. Or if you're in the discord you could ask people.

**Comment by BluePineappleGuy** [comment]
I mean, you _can_ just open up the .jar file as a .zip file, then copy the files under "assets", but this would be helpful to people with little to no expertise in pack-making. especially because there are few CWSM resource packs in the first place.

**Comment by FalconinVoid** [comment]
> ### Description of feature request
> So not a feature for the mod iteself but a "guide" or "helper". I think for those who want to replace textures and sounds there should be a resource pack file with the textures and sounds which would allow people to easily make there own resource packs for this mod.

If you would know how to make texturepacks in vanilla minecraft, you would know how to make it for mods: Just take the mod, rename the .jar file to .zip and then take the assets folder to look which files you can replace.

**Comment by nonamecrackers2** [comment]
I’d rather not bundle all of the mods assets into a single resource pack. Making them is fairly straightforward, there’s plenty of tutorials online. Also as others stated you can open the mods jar with something like winrar to view the format of the assets folders
