### ISSUE TITLE
[Bug]: Boats and minecarts aren't eaten by storm

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#1605]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.1.0

### Describe the bug

Boats and minecarts are pulled by the tractor beam but aren't actually destroyed unless hit by a skull 

### Steps to Reproduce

1. Summon boats within tractor beam. I used the /summon command to make it easier. 

### Crash Reports/Logs

N/a

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2023-10-23_20 57 19](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/109642282/baadc00e-ce8e-4616-acd4-ee99465482b8)
![2023-10-23_20 57 25](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/109642282/ac0dfb80-47ae-4d3b-a2dd-5716d85b2ee2)
![2023-10-23_20 55 59](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/109642282/cee904df-b83f-4a21-b2ca-bd1cddf9053d)

### Mod List

55 mods:
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[ParCool! (by alRex_U)](https://www.curseforge.com/minecraft/mc-mods/parcool)
[Falling Leaves (Forge) (by Cheaterpaul)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Eating Animation [Forge] (by matyrobbrt)](https://www.curseforge.com/minecraft/mc-mods/eating-animation-forge)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Trimmable Tools (by Apollo)](https://www.curseforge.com/minecraft/mc-mods/trimmable-tools)
[Drip Sounds (Forge) (by PieKing1215)](https://www.curseforge.com/minecraft/mc-mods/waterdripsound)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[Tidal Towns (by joshieman)](https://www.curseforge.com/minecraft/mc-mods/tidal-towns)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Grapple (by uhmbyee)](https://www.curseforge.com/minecraft/mc-mods/grapple)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Sky Villages [Forge] (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/sky-villages-forge)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Full Brightness Toggle (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/full-brightness-toggle)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[YDM's Weapon Master (by YourDailyModderx)](https://www.curseforge.com/minecraft/mc-mods/ydms-weapon-master)
[CraftTweaker (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Wall-Jump TXF (Forge) (by jahirtrap)](https://www.curseforge.com/minecraft/mc-mods/wall-jump-txf)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Not Enough Animations (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)
[Tectonic (by Apollo)](https://www.curseforge.com/minecraft/mc-mods/tectonic)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Panda's Falling Tree's (Forge/Fabric) (by ThePandaOliver)](https://www.curseforge.com/minecraft/mc-mods/pandas-falling-trees)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Grappling Hook Mod (by yyonne)](https://www.curseforge.com/minecraft/mc-mods/grappling-hook-mod)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[Immersive structures (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Cracker's Wither Storm Mod (by nonamecrackers2)](https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod)
[Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[GroovyModLoader (GML) (by matyrobbrt)](https://www.curseforge.com/minecraft/mc-mods/gml)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Horizon City - Advanced World (by Master777XY)](https://www.curseforge.com/minecraft/worlds/horizon-city-advanced-world)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)

**Comment by BluePineappleGuy** [comment]
do any of these mods affect boats or minecarts (or generally mountables) in any way?
if so, try removing them and see if it persists

**Comment by Steve982950** [comment]
TOO MANY MODS 💀

**Comment by GrandmaPork** [comment]
shouldn't be any mods that affect them. they're mostly world gen mods or mods that add things like a grapple hook. I haven't tested it without the mods but i doubt they're changing anything. added them for reference

**Comment by Theoyeah** [comment]
> TOO MANY MODS 💀

Too many cpus ☠️

**Comment by Asteroid4** [comment]
the boats don't get pulled up either, even when im doing vanilla cwsm

**Comment by GrandmaPork** [comment]
Boats were being pulled up for me 🤔

**Comment by Steve982950** [comment]
> Boats were being pulled up for me 🤔

this guy means that the boats weren't EATEN! they were picked up but just went in the head without dying

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
