### ISSUE TITLE
[Bug]: Sick villagers burn in the sun

### ISSUE THREAD

**Issue by BrunoGoldbergFerro** [nonamecrackers2/crackers-wither-storm-mod#1607]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.1

### Describe the bug

The cause of this is probably the fact that they reuse code from the zombie villager

### Steps to Reproduce

Place a sick villager on the day

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2023-10-24_19 55 41](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/86776985/3fe1919f-8747-451a-81c1-5909b57c9982)

### Mod List

Essential-forge_1-20-1
farsighted-mobs-forge-1.1-1.20.1
firstperson-forge-2.2.3-mc1.20
notenoughanimations-forge-1.6.4-mc1.20
PerfectAccuracy-1.2-1.19
witherstormmod-1.20.1-4.0.1

**Comment by TaintedBlock** [comment]
This is intended. They are zombies

**Comment by BrunoGoldbergFerro** [comment]
Sick spiders dont burn tho

**Comment by TaintedBlockmObile** [comment]
> Sick spiders dont burn tho

Because they aren't exactly zombies. The sickened mobs follow the same logic as their normal counter parts. Besides the villager who was once human turned sickened. Which in turn is basically just another sickened zombie

**Comment by BrunoGoldbergFerro** [comment]
They don't have ''zombie'' in their name

**Comment by TaintedBlock** [comment]
> They don't have ''zombie'' in their name

I just said they follow the same logic as their normal counter parts

**Comment by BluePineappleGuy** [comment]
What tainted means is that they act the same as their normal counterpart, apart from granting wither. this is for mod compatibility. so the sick villager is based off the zombie villager, hence why they burn in the sun.

**Comment by BrunoGoldbergFerro** [comment]
I just tested it, a sick villager turns into a normal villager when healed, not a zombie villager
![2023-10-25_13 14 17](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/86776985/691d67c3-0d8e-4e06-84f5-33a4d7d96c94)
![2023-10-25_13 19 30](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/86776985/7a494096-3081-48e6-aca8-54a54bc9f112)

**Comment by BluePineappleGuy** [comment]
> I just tested it, a sick villager turns into a normal villager when healed, not a zombie villager ![2023-10-25_13 14 17](https://user-images.githubusercontent.com/86776985/278080082-691d67c3-0d8e-4e06-84f5-33a4d7d96c94.png) ![2023-10-25_13 19 30](https://user-images.githubusercontent.com/86776985/278080103-7a494096-3081-48e6-aca8-54a54bc9f112.png)

the mob itself is based off a zombie villager, but its cured version is a regular villager.

**Comment by TaintedBlockmObile** [comment]
> I just tested it, a sick villager turns into a normal villager when healed, not a zombie villager ![2023-10-25_13 14 17](https://user-images.githubusercontent.com/86776985/278080082-691d67c3-0d8e-4e06-84f5-33a4d7d96c94.png) ![2023-10-25_13 19 30](https://user-images.githubusercontent.com/86776985/278080103-7a494096-3081-48e6-aca8-54a54bc9f112.png)

Bruh why would it turn into a zombie villager lol

**Comment by nonamecrackers2** [comment]
This is intended. The sickened villager can be converted from a normal villager or a zombie villager, and since it’s more zombie-like it burns in the sun.
