### ISSUE TITLE
[Bug]: Crash caused with Improved Mobs

### ISSUE THREAD

**Issue by TheHandwovenBox** [nonamecrackers2/crackers-wither-storm-mod#1608]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.1

### Describe the bug

When playing with the Wither Storm and Improved Mobs mod, a crash will eventually occur. According to the log, the wither storm mod attempts to pass a class from Improved Mobs to a Phantom which causes a ticking entity crash.

### Steps to Reproduce

1. Install both mods
2. Play normally, seems to happen faster with Phantoms present but may be confirmation bias
3. Experience ticking entity crash

### Crash Reports/Logs

https://paste.gg/p/anonymous/0163e50c33f947cd9425805fb6be6736

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot 2023-10-25 002803](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/110263350/bef57450-dc33-4ea7-b275-96a5343b0ee3)
![Screenshot 2023-10-25 002815](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/110263350/ddd0d8ab-c2a9-4dbf-8bea-357663049b4e)
![Screenshot 2023-10-25 002822](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/110263350/de51d3e4-2e8c-4f5b-9cad-fb110cb2f61a)

### Mod List

Above in the screenshots is my modlist. I tried using only Wither Storm and Improved mods to try and recreate the error but of course nothing happened.

**Comment by theodore-zd** [comment]
Just ran into the same issues attaching my logs here 
- Improved Mobs v1.11.6
- Wither-Storm 4.0.1.1
- forge v
[crash-2024-02-08_22.50.58-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/14217022/crash-2024-02-08_22.50.58-server.txt)
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/14217023/latest.log)
[debug.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/14217025/debug.log)

**Comment by nonamecrackers2** [comment]
Should be fixed in the next major release.
