### ISSUE TITLE
[Suggestion]: Withered beacon slightly cooler summoning animation

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1609]
### Description of feature request

what i mean here is that instead of how the summoning is rn, my idea would be that they start shaking slowly backing off and just slowly fusing or whatever cant find the word, it would be like this 
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/016d388b-204a-4d75-be55-1bd2c694492e)

this was rushed

:jess:

**Comment by BluePineappleGuy** [comment]
the redstone block looks a lil familiar :eyes:

**Comment by Pandaboi25x** [comment]
> the redstone block looks a lil familiar 👀

no story mod didnt add it yet

**Comment by BluePineappleGuy** [comment]
> > the redstone block looks a lil familiar 👀
> 
> no story mod didnt add it yet

i know, but still, i recognize it 👀 👀 👀

**Comment by nonamecrackers2** [comment]
Took inspiration from this, items will now speed up and will get pulled in towards the center of the Withered Beacon as it summons a mob.
