### ISSUE TITLE
I think the tractor beams are bugged

### ISSUE THREAD

**Issue by Gaboamau** [nonamecrackers2/crackers-wither-storm-mod#161]
**Minecraft version**
1.18.2

**Mod version**
2.0 (not beta)

**Describe the bug**
As seen in the image I saw a very strange line between the two beams of the Wither Storm, also this bug was not in the other versions of the mod.

**To Reproduce**
At that time I was testing the mod together with the twilight forest mod, since in the githud error list, I read that the blocks absorbed by the Wither Storm disappear when they reach the height of 256 blocks (and it's true), but suddenly when the beams of the Wither Storm come together, strange lines come out like in the picture, but I think this also happens without the twilight forest mod in normal worlds.

**Screenshots**
![image](https://user-images.githubusercontent.com/106891155/176981443-70caa1d2-9a43-4e16-b413-656556523007.png)
![image](https://user-images.githubusercontent.com/106891155/176982167-919ee204-b455-4e3a-9063-225eb2ba60fc.png)
![image](https://user-images.githubusercontent.com/106891155/176982359-52732d7e-d2c9-44d8-85dd-b82c0b771cb3.png)

**Comment by nonamecrackers2** [comment]
This just due to how rendering works. The latest version made the beams appear inside of the tractor beams which is why the lines may appear. I'm not an expert with how the rendering works, some weird sorting issue.

**Comment by BluePineappleGuy** [comment]
> This just due to how rendering works. The latest version made the beams appear inside of the tractor beams which is why the lines may appear. I'm not an expert with how the rendering works, some weird sorting issue.

seems to be a transparency effect, its trying to render both on top of each other, causing the overlap and a more opaque color that is the line.
