### ISSUE TITLE
[Suggestion]: Some more wither storm animations

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1613]
### Description of feature request

I think to make the wither storm more "alive" there should be movement of its "main body" aswell instead of just its heads and tentacles.

Maybe have the wither storm bob up and down a bit to truly have that floating feel. Maybe have it have a slight tilting/swaying motion aswell.

ok so uh nvm #1565 but no rotation and for phase 4 and higher but its still way to similar damn it.

**Comment by TaintedBlockmObile** [comment]
This has already been suggested. And has been denied

**Comment by Luke7381** [comment]
> This has already been suggested. And has been denied

Yeah while there are some tiny differences (such as it being strictly for phase 4 and higher) its still mostly similar.

I legit thought no one suggested it but oh well. Also i think crackers would also have to deal with tractor beam issues aswell.
