### ISSUE TITLE
[Bug]: Stuck Dead after getting caught in F Bomb 

### ISSUE THREAD

**Issue by ConnorCarmine** [nonamecrackers2/crackers-wither-storm-mod#1616]
### Minecraft Version

1.18.2

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

40.2.0

### Describe the bug

After I killed WS with the F Bomb, I was to close to the explosion that I was killed? I'm stuck shaking with no hearts, tired /kill but I won't go to the the respawn screen. I'm just stuck standing and shaking with 0 hearts 

### Steps to Reproduce

Kill WS with F bomb and be to close 

### Is OptiFine installed?

- [X] OptiFine is installed

### Screenhots

![16987199586237382065286318972944](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/8f232c72-f15c-4995-989e-16135a0d598e)

### Mod List

Witherstrm

**Comment by ghost** [comment]
Could it be an Optifine problem?
Try replicating it without Optifine and see if you get the same result.

Also, just to be sure, are there any other mods installed with CWSM?

**Comment by TaintedBlockmObile** [comment]
Can you tell us the full mod list? It's obvious you have more then just CWSM

**Comment by Aimyx** [comment]
It might just be a texture pack

**Comment by TaintedBlockmObile** [comment]
> It might just be a texture pack

They aren't. I've used those mods before and they don't require texture packs

**Comment by Aimyx** [comment]
Mm ok

**Comment by ConnorCarmine** [comment]
Yes sorry, I had to look and see all my mods. This is the complete folder, I have tried everything I can think of to solve it. Nothing works. If anyone can help I'd greatly appreciate 

![List p1](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/af05e1a6-266a-4dfd-93b2-e0439a24ad05)
![list p2](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/177dca46-5e35-4d5e-aa1d-1f55be826ece)
![list p3](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/f37d058c-626a-4299-ad5d-629b860ee31a)
![list p4](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/6a7df63c-9d59-4969-a682-4250ef2ed204)
![list p5](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/f397fa15-3699-4a00-9df6-9fb8d6a2c0e2)
![list p6](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/e11bc8bd-6b1a-4d6f-b13b-272edbaef773)
![List p7](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/32a63ae3-22c2-4fdc-8170-678060bb0208)
![List p8](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/3d9fc08a-32aa-48ab-80d0-a33deeeb2d71)
![list p9](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149451242/8b1e4c31-7ab4-4d95-8437-38ea47ff4415)

**Comment by nonamecrackers2** [comment]
Try removing OptiFine. If that doesn't work, I'm not sure what else could be causing it since of the large mod list. I'd remove mods bit by bit to determine the culprit. You could also try providing me with your latest.log file when this problem occurs to see if anything weird is happening there.

**Comment by nonamecrackers2** [comment]
Also, you're definitely not using 1.20.1. Ice and fire hasn't been updated past 1.18.2

**Comment by BluePineappleGuy** [comment]
> Also, you're definitely not using 1.20.1. Ice and fire hasn't been updated past 1.18.2

they did say in the bug report the version was 1.18.2

**Comment by myron-obsolete-account** [comment]
> > Also, you're definitely not using 1.20.1. Ice and fire hasn't been updated past 1.18.2
> 
> they did say in the bug report the version was 1.18.2

4.X is not for 1.18.2, I believe that was 2.X

**Comment by nonamecrackers2** [comment]
Closing until corrected.
