### ISSUE TITLE
[Suggestion]: Option to make teeth not glow

### ISSUE THREAD

**Issue by nosivaste** [nonamecrackers2/crackers-wither-storm-mod#1617]
### Description of feature request

hello, would be awesome if we got a config option to make the wither storm's teeth not glow, when using certain shaders they start glowing like crazy and turning bloom off or lowering it makes other things not look as good

**Comment by myron-obsolete-account** [comment]
#931

**Comment by Theoyeah** [comment]
ok crackers um maybe he doesn't like the concept of glowy storm
![Capture d'écran_20221226_160019](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/97792861/b45e89a5-b523-4767-aacd-dd7638b864f9)

**Comment by nosivaste** [comment]
ye ye thats exactly what happens, literally getting flashbanged lmao

**Comment by BluePineappleGuy** [comment]
Crackers should add this, it looks so weird with shaders

**Comment by nonamecrackers2** [comment]
I guess having a config option for that would make sense for the excessive bloom with shaders lol

**Comment by myron-obsolete-account** [comment]
heck finally

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
