### ISSUE TITLE
[Bug]: black screen of the formidi bomb

### ISSUE THREAD

**Issue by miran8381** [nonamecrackers2/crackers-wither-storm-mod#1618]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.4

### Describe the bug

When the Formidi bomb ignites, the screen turns blacks.

### Steps to Reproduce

1. Formidi bomb ignition
2. The screen turns black

### Crash Reports/Logs

None

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![20231105_120501](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149885897/2e4646d1-db3c-439a-bf6b-f702939ab28f)
![20231105_115735](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/149885897/7c3d799a-0485-4479-9e31-805adf6aede1)

### Mod List

Cracker's wither storm mod
None

**Comment by Aimyx** [comment]
thats a weird lookin cwsm you got there buddy. why would you need a touchpad?

**Comment by miran8381** [comment]
I use the pojavlauncher (mobile java)

**Comment by myron-obsolete-account** [comment]
> thats a weird lookin cwsm you got there buddy. why would you need a touchpad?

it's probably that one app that lets you play minecraft java on mobile devices. it's very instable however so bugs like there are to be expected. not to be mean or anything but @miran8381 please get a PC for the full bug-free and better experience. christmas is coming soon, you may have a chance

**Comment by nonamecrackers2** [comment]
I don't think this will be an issue I can easily replicate, I think the issue is caused by your hardware and I'm unable to test it since I don't have an android device like yours.

**Comment by Aimyx** [comment]
would be nice to have this as a config option, instead of white and eye
destruction a toggle for it to go black and still block visibility unlike
just turning flash off, win-win.
or lose by the way you look at it.
someone else should make an issue on that before everyone forgets, cant do
it myself rn
