### ISSUE TITLE
[suggestion] book info

### ISSUE THREAD

**Issue by kaboom24** [nonamecrackers2/crackers-wither-storm-mod#1619]
It would really improve the mod if the book in the storm spawn platform structure actually contained writing of the original creator who almost summoned the wither storm (preferably also include a reason why it was never finished)

**Comment by GearsawStudios** [comment]
> It would really improve the mod if the book in the storm spawn platform structure actually contained writing of the original creator who almost summoned the wither storm (preferably also include a reason why it was never finished)

Problem: It's meant to be open ended

**Comment by kaboom24** [comment]
okay

**Comment by BluePineappleGuy** [comment]
I mean, it _could_ have a book that mentions some of the mods mechanics, such as info on the storm tracking the amulet. If you didn't check settings you probably wouldn't've known and been confused as to why it targets you and not your buddy.

**Comment by kaboom24** [comment]
that would be helpful

**Comment by nonamecrackers2** [comment]
It's intentionally empty since A) I didn't know what really to put there, and B) as Gearsaw said it's open ended and you can interpret the lore as you wish.
