### ISSUE TITLE
[Permadeath with second formidibomb while playing dead] Wither storm not getting back up 

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#162]
**Minecraft version**
The version of Minecraft the mod is running on 1.18.2

**Mod version**
The version of the mod you are using [witherstormmod-1.18.2-2.0.jar]

**Describe the bug**
A clear and concise description of what the bug is. Blowing up the wither storm with a formidibomb during its "fake death" state causes a glitched wither storm where it remains In the "fake death" state but the boss bar reappears, and the wither storm will not get back up

**To Reproduce**
1: blow up wither storm with formidibomb
2: blow it up with another formidibomb while it is in the "fake death" state

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**
![2022-07-01_18 53 13](https://user-images.githubusercontent.com/106888663/176982484-1674548a-46e2-4c7a-8862-7e9e17d2f5e4.png)

**Comment by cardanawandra** [comment]
i think this is awesome, no need to fix this, so we can get what second formidibomb is capable of

**Comment by Asteroid4** [comment]
> i think this is awesome, no need to fix this, so we can get what second formidibomb is capable of

I agree, besides the boss bar, I think this should be kept!

**Comment by Asteroid4** [comment]
I tested this out in my own minecraft world, here's what happens:

1. When the second formidibomb explodes, it launches the command block at high speeds.
2. I think that it's being launched into unloaded chunks, causing the wither storm to become confused and never get back up.

I think that to fix it, simply make it such that the command block has infinite knockback resistance.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release
