### ISSUE TITLE
[Suggestion]: Custom presets or ability to save your "world options"?

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1621]
### Description of feature request

I know that you can do this with datapacks (explorer eve for example) and all but this can be really tedious and average players like me don't really want to take the time to learn that.

**Comment by Aimyx** [comment]
All my world settings are really specific so re putting them in is just annoying. I think there might be someone who already suggested this though I’d have to look and I’m too lazy to do that

**Comment by Luke7381** [comment]
> All my world settings are really specific so re putting them in is just annoying. I think there might be someone who already suggested this though I’d have to look and I’m too lazy to do that


I haven't found one that specifically talks about making presets or saving the world options however i did find this.
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/705
Im not sure if it counts though.

**Comment by BluePineappleGuy** [comment]
> > All my world settings are really specific so re putting them in is just annoying. I think there might be someone who already suggested this though I’d have to look and I’m too lazy to do that
> 
> I haven't found one that specifically talks about making presets or saving the world options however i did find this. #705 Im not sure if it counts though.

That one suggests the ability to set the world options before generating the world. As far as i understand, your suggestion states that there should be a way to save the current world settings as a preset and load it after creating a new world.

**Comment by nonamecrackers2** [comment]
You can copy and paste your "witherstormmod-server.toml" config file from your world folder and put it in the "defaultconfigs" folder to make your changes apply to all worlds (at least, I believe that's how it works). Let me know if that doesn't work.
