### ISSUE TITLE
[Suggestion]: Wither Sickness Variant

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1622]
### Description of feature request

In a way you can this is a "minecraft story mode suggestion" as the game also has 2 variants aswell however this variant mostly different.

Functionality: Instead of amnesia or making the infected forget things, the variant will instead slowly weaken the player.
This variant will still wither the player overtime, however it will be at a much slower rate compared to the normal variant. The main danger of this variant though is its slowly worsening "mining fatigue" effect, with slower attack and mining speed over time. Along with this the player may slowly start dealing less damage overtime (the diamond sword for example may be as weak as a iron sword after like maybe a hour of being infected). Walking and sprinting slowly get slower and hunger may start to drain a little faster. Players can use milk to improve there symptoms for short period of time.

If mobs get infected they will simply deal less damage and move slower. They still get converted to there sickened versions after some time.

Graphics: I think there would be a grayish/black texture over the player instead of purple.

This variant would give more incentive to try and gather golden apple stew.

I doubt this will be added (i'd be surprised if some features made it in), might even be a little unfair but its nice to share ideas.

**Comment by Luke7381** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1484
I noticed a few similaries with this, however mine still has its own stuff in it

**Comment by nonamecrackers2** [comment]
Adding a new effect variant would be a bit of scope right now, but it's an interesting idea nonetheless.
