### ISSUE TITLE
[Bug]: (multiplayer) Storm despawns every time I restart the server.

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1624]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.2.5

### Describe the bug

While playing on the server, I summoned Storm 26000 blocks away from the spawn point. Everything was fine, but after some time, the server lagged. I decided to restart it. And Wither's gone. (Even Amulet can't find it.)
Server is powered by Aternos.

### Steps to Reproduce

1. Make Aternos server with Forge and mod installed.
2. Turn the server on and join.
3. Spawn the Wither Storm.
4. Server gets laggy.
5. Restart the server.
6. Connect to the server again.
7. Wither Storm is despawned / gone.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

FallingTree 1.20.1 4.3.1

**Comment by BluePineappleGuy** [comment]
WS despawning is one of the bugs already. that might be the problem.

**Comment by DarthXJacob** [comment]
Short update,
There was one time, when Wither Storm stayed.

**Comment by nonamecrackers2** [comment]
This is a known issue #1462
