### ISSUE TITLE
[Suggestion]: CWSM x Command Block Ascension

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1626]
### Description of feature request

I'd like to make a mod to make CWSM compartible with Command Block Ascension, while CBA uses Public Domain, CWSM has all rights reserverved. **Can I use the source code of CWSM to make this mod? CWSM will be still needed as a library mod and will get linked in all descriptions.**

**Comment by TaintedBlockmObile** [comment]
The mods are already compatible tho

**Comment by nonamecrackers2** [comment]
You can't have access to the source code, but you can use it as a dependency for your mod and try to interpret the source code without actually being able to see it.

Also questions are better asked in the discussions tab here on GitHub or in our official Discord server, thanks :)

**Comment by FalconinVoid** [comment]
okay, thanks!
