### ISSUE TITLE
Weird lag and stutters 

### ISSUE THREAD

**Issue by E-daw** [nonamecrackers2/crackers-wither-storm-mod#163]
![image](https://user-images.githubusercontent.com/34014927/176990382-d68c1b90-7340-45fc-8ad7-e2ebaa0036fb.png)

The witherstorm lag seems to be causing some tick lag with the wither sickness event. I had it spawned in the world but set it to peaceful to remove the witherstorm. I'm currently running in 1.16.5 and 1.0.2.1 version of the mod

**Comment by nonamecrackers2** [comment]
With the wither storm removed does the world still lag?
