### ISSUE TITLE
[Suggestion]: Better German Translation

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#1630]
### Description of feature request

Please don't just put the translation into Google Translate (It's terrible)

**Comment by MoRoN222** [comment]
Excuse me I did translate all of this by hand can you please not be mean thanks

**Comment by FalconinVoid** [comment]
> Excuse me I did translate all of this by hand can you please not be mean thanks

Alright... Let me do the translation! I am German and can't see this! My favourite mod has to have the right translation! I'll send the lang file in a few days, so you can correct your fatal mistake!

**Comment by MoRoN222** [comment]
> > Excuse me I did translate all of this by hand can you please not be mean thanks
> 
> Alright... Let me do the translation! I am German and can't see this! My favourite mod has to have the right translation! I'll send the lang file in a few days, so you can correct your fatal mistake!
> 
> Edit: I will be sending this today, because it is so important.

Welchen "fatalen Fehler" ich hier gemacht habe ist mir momentan unklar. Wenn dir meine Übersetzungen nicht gefallen dann mach die doch selber, aber solange ich die Übersetzungen für die Mod hergebe ist das so und gut ist!

P.S.: wenn du die Übersetzung von einem echten und lebenden Menschen dessen Herkunft Deutschland heißt nicht gefällt, dann rate ich dir sie doch lieber in einen Übersetzer zu schleudern und das so dann hier reinzusenden, aber ein Tipp geb ich dir, das klappt so nich' ;)

**Comment by FalconinVoid** [comment]
Meine Güte! Ich hab mir jetzt alles mal angekuckt, es geht bei einer Übersetzung nämlich nicht immer nur um richtige Wörter, sondern auch um den Kontext. Hier ist die überarbeitete Übersetzung:
[de_de.json](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/13350495/de_de.json)

**Comment by FalconinVoid** [comment]
Here the better Translation: [de_de.json](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/13350495/de_de.json)

**Comment by MoRoN222** [comment]
> Meine Güte! Ich hab mir jetzt alles mal angekuckt, es geht bei einer Übersetzung nämlich nicht immer nur um richtige Wörter, sondern auch um den Kontext.

ich hab mir auch die beste Mühe bei dem Kontext gegeben, aber gut, ich guck mal kurz was anders bei dir ist

**Comment by MoRoN222** [comment]
- Strahlung macht kein Sinn da der Sturm im besten fall nicht Radioaktiv ist, sonst könntest du dich realistischerweise nicht mal in seiner Nähe aufhalten
- wer nutzt heutzutage noch "Brocken?" okay, Blockhaufen kann man zu was stabilerem noch ändern aber Brocken finde ich ist jetzt auch nicht ganz so prickelnd
- nicht alles was "withered" ist muss "infiziert" sein. ich habe mit Absicht infiziert nur bei Mobs und fleischenthaltenen Blöcken verwendet da dies organische Materien sind, welche sich biologisch gesehen auch infizieren können. da passt "verwelkt" doch viel besser bei nicht-organischen Blöcken wie Stein.
- kann sein dass ich das nicht mehr richtig im Kopf habe, aber hast du bei "gui.witherstormmod.button.preset.title" die Abkürzung (falls da eine war) ausgeschrieben zu Voreinstellungen? wenn du die Länge der Wörter mal vergleichst fällt dir sehr schnell auf dass das deutsche Wort um so einiges länger ist, und würde auf der Preset-Taste in-game nicht raufpassen und dort überlappen. falls ich mich da nicht richtig erinnere dann tut's mir jetzt leid!
- uff

**Comment by FalconinVoid** [comment]
-Strahlung hab ich reingemacht, weil verwelkt keinen Sinn macht, man könnte sich auch auf einen anderen Begriff 
 einigen.
-Es gibt halt auch keinen gescheiten Begriff für "withered" im Deutschen.
-Na gut, mit den Abkürtzungen hast du Recht, daran hatte ich nicht gedacht.

**Comment by BluePineappleGuy** [comment]
As a person who can only speak english i am very confused as to what everyone is saying

**Comment by FalconinVoid** [comment]
We are talking about what german words are good and what are not, because some sound just like u put it in google translate.

**Comment by Demonmaster-MD** [comment]
gut
