### ISSUE TITLE
[Suggestion]: Wither Storm visibility in the distance (hunchback phases)

### ISSUE THREAD

**Issue by MonKris** [nonamecrackers2/crackers-wither-storm-mod#1631]
### Description of feature request

Basically just seeing the storm from a little further as the Wither Storm evolves in its hunchback phases.

**Comment by Aimyx** [comment]
So basically what your saying is, when the ws reaches a new hunchback phase, the distance it can be seen from increases?

**Comment by MonKris** [comment]
yez

**Comment by nonamecrackers2** [comment]
I'd rather not have the distance the Wither Storm can be seen be variable, interesting idea however
