### ISSUE TITLE
Technoblade skin

### ISSUE THREAD

**Issue by Cuteplushbros** [nonamecrackers2/crackers-wither-storm-mod#1633]
Like how the Rueben skin was added I think a Technoblade skin for the pig would be amazing as well to pay respects to his passing

**Comment by Aimyx** [comment]
This isn’t exactly an idea for this mod, however there are several ways available to do this via reasource packs to pay respects to our fallen hero

**Comment by Cuteplushbros** [comment]
> This isn’t exactly an idea for this mod, however there are several ways available to do this via reasource packs to pay respects to our fallen hero

i know but i think it would fit well with the reuben skin

**Comment by GrandmaPork** [comment]
I’d imagine this would be out of scope for what this mod wants to accomplish, even if it would be an homage to techno blade. I would look into other mods/resource packs that accomplish this

**Comment by Aimyx** [comment]
but das what i said :why:

**Comment by nonamecrackers2** [comment]
I'd love to pay respects to Technoblade but unfortunately this wouldn't really make sense to be in the mod, sorry.
