### ISSUE TITLE
[Bug]: Mobs' Health Becomes NaN if a Wither Storm Head Fails to Kill it

### ISSUE THREAD

**Issue by TonyZhang4508** [nonamecrackers2/crackers-wither-storm-mod#1635]
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.46

### Describe the bug

If a Mob has a totem of undying in either of its hands when a Wither Storm Head tries to kill it, the totem will activate and the mob's health would be shown as (NaN) (according to the mod 'Neat' which shows mob hp), this bug occurred on the sheep I spawned, and when the sheep's hp became 'NaN', it lost its walking animation and became unkillable, commands can't even detect the existence of it, and other weird things happen too, such as the warden roaring at it over and over and over again but not moving or attacking once turned aggressive towards it.

### Steps to Reproduce

1. Summon any mob with a totem of undying in its hand using command, make sure that it is a mob the wither storm head attacks.
2. Summon a Wither Storm that has grown wither storm heads, or simply summon a wither storm head using command
3. Wait for the wither storm head to pick up the summoned mob with its tractor beam and tries to consume it
4. Kill the wither storm head after the totem the mob is holding has activated
5. Observe the abnormal behavior of the mob, such as losing animation and becoming unkillable, when you try to do something to it using commands the command simply says no entities found
6. If you have the 'Neat' mod installed, you can also see that the mob's hp is 'NaN', which stands for 'not a number'.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Cracker's Wither Storm Mod
Neat
Mob Battle Mod

**Comment by nonamecrackers2** [comment]
I'm unable to replicate this issue, appears to be a mod compatibility issue. I'd recommend removing Mob Battle Mod and seeing if that resolves the issue.
