### ISSUE TITLE
[Suggestion]: Arrows Shot by the Withered Symbiont Should Ignore Damage Immunity

### ISSUE THREAD

**Issue by TonyZhang4508** [nonamecrackers2/crackers-wither-storm-mod#1636]
### Description of feature request

Every time the withered symbiont uses the arrow attack, it shoot a ton of arrows, but only the first one actually damages the target, the others all falls to the ground due to damage immunity, the whole move just became a fancier skeleton attack. This made the withered symbiont feel very lame.

**Comment by TaintedBlockmObile** [comment]
I don't know if you just haven't taken the full attack but, those arrows combined do a lot of damage lol. And if it ignored immunity getting slightly hit by that attack would be almost 100% fatal which is probably what crackers doesn't want for the mod.

**Comment by TonyZhang4508** [comment]
You can always use a shield or build a wall, and currently the arrow attack only deals 3-4 damage on a player with no armor on normal difficulty, I don't think it'll be that dangerous if you get slightly hit.

**Comment by nonamecrackers2** [comment]
I'm not sure if I'll be able to easily bypass the immunity frames of the player, but even if I could it might make the arrows extra overpowered. I'll look into it though

**Comment by nonamecrackers2** [comment]
Yeah, I won't be able to easily bypass the cooldown unfortunately. I also worry this would make the attack especially unfair and extremely annoying, so I'll be closing this issue. Thanks for your suggestion though.
