### ISSUE TITLE
[Suggestion]: Config option for Instant death if player is eaten by the Wither Storm in Phase 4 and above.

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1637]
### One more reason to fear the Storm

I find it odd how the Wither Storm can instantly kill Iron Golems and Wardens in one bite, but the player can hang on for a while, given they have armor and such.

So I suggest that an optional config be made so the Wither Storm can one shot the player, regardless of what armor they have, as it would be a more realistic outcome if a player is eaten.

That said, I believe that instant death would only work if the Wither Storm was on phase 4, as Phases 2 and 3 seem too weak in comparison to instantly kill a player by eating them. So this config would only apply once the Wither Storm reaches Phase 4 and above.

**Comment by TaintedBlockmObile** [comment]
Ultra hardcore wither storm

**Comment by Aimyx** [comment]
If this would be added, it would best to be off by default so you don’t ragequit and never play the mod again

**Comment by GrandmaPork** [comment]
Wither storm should be quicker to disable if implemented

**Comment by ghost** [comment]
> Wither storm should be quicker to disable if implemented

If so, make it not that quicker, like 80%-90% of the health of each head. The Wither Storm is not something that spawns into existence. It is something that is you have to summon. By summoning the Wither Storm, you are ready to fight the Storm and what comes with it. By making too quick to disable the beams, it doesn't give the player enough time to consider if they are to die or not (AKA: the fear factor).

**Comment by BluePineappleGuy** [comment]
More difficulty config would be awesome. The storm on its own isn't too hard to survive, with some fireworks and a bit of shelter you can survive a lot longer than the hunchback stages or a regular wither.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
