### ISSUE TITLE
[Suggestion]: wither storm head

### ISSUE THREAD

**Issue by SealDeal100** [nonamecrackers2/crackers-wither-storm-mod#1639]
### Description of feature request

I'm not sure if this technically is considered a tool/armor, but a wither storm head with a controllable tractor beam to pull mobs toward you when wearing the head. Also it could be like the ender dragon head where the mouth moves as you use redstone or walk.

**Comment by TaintedBlock** [comment]
How would this even fit on a player head

**Comment by SealDeal100** [comment]
> How would this even fit on a player head

as a scaled down version of the head

**Comment by myron-obsolete-account** [comment]
> How would this even fit on a player head

the hunchback phases have a small WS head

**Comment by TaintedBlock** [comment]
> > How would this even fit on a player head
> 
> the hunchback phases have a small WS head

But hunchbacks aren't meant to be killed. And even if you did that would be one hell of an op drop for barely experiencing the mod

**Comment by nonamecrackers2** [comment]
This wouldn't really fit in with the mod, neat idea though
