### ISSUE TITLE
Heads wake back up in the bowels

### ISSUE THREAD

**Issue by Void866** [nonamecrackers2/crackers-wither-storm-mod#164]
If the 2 wither storm heads in the bowels are disabled, after around a minute or so, they should re-activate. (Assuming the command block is still intact). 

And if this is already a feature, the amount of time it takes for them to do so should be reduced slightly.
I just think the heads are pretty easy to deal with for a final battle.

**Comment by nonamecrackers2** [comment]
While that is the case, if the revival time is too low it'll become more a nuisance than anything, and if it's too high they'll never wake up in time before the player defeats the command block. Overall I think this feature would be more annoying than challenging,
