### ISSUE TITLE
New sub phase between phase 2.2 and 3

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#1640]
### Description of feature request

I'm not sure if anyone else was thinking this, but a new sub phase between sub phase 2.2 and phase 3 would be great, the reasons for these are is because the jump is way too big, in sub phase 2.2 the wither has a little back growth and a wither storm head, and then all the sudden in phase 3 the command block is completely covered and its grown 3 tentacles, so in phase 2.5, my idea, it grows one tentacle and the command block is partially covered, just an idea.

Jump of growth between the two phases:
![Screenshot 2023-11-18 232323](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/116845536/1f1c01ea-bbee-4417-b231-320208e85334)
![Screenshot 2023-11-18 232352](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/116845536/f3f5c8b4-d2e9-4153-841d-fefa9a9f9042)

**Comment by nonamecrackers2** [comment]
#1431
