### ISSUE TITLE
[Bug]: Popping Totem's of Undying with Wither Sickness cures the effect.

### ISSUE THREAD

**Issue by FrozenDragon0** [nonamecrackers2/crackers-wither-storm-mod#1641]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.1.3

### Describe the bug

When infected with Wither Sickness and you have a Totem of Undying in your off-hand/main hand, popping said totem cures the effect even though it's not meant to.

### Steps to Reproduce

1. Infect yourself with Wither Sickness.
2. Grab a Totem of Undying either in your off-hand or main hand and pop it.
3. Notice that Wither Sickness has cured itself.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Only CWSM on it's own.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
