### ISSUE TITLE
[Suggestion]: New and changed acivements

### ISSUE THREAD

**Issue by SickNick43** [nonamecrackers2/crackers-wither-storm-mod#1643]
### Description of feature request

Instead of "Brushing shoulders with death" the achievement should be "Eye of the storm" because when escaping the storm, you damage/break its eye. 
also there should be achievements for upgrading command block tools to netherite.

**Comment by TaintedBlock** [comment]
There are no netherite command block tools??

**Comment by GearsawStudios** [comment]
> ### Description of feature request
> Instead of "Brushing shoulders with death" the achievement should be "Eye of the storm" because when escaping the storm, you damage/break its eye. also there should be achievements for upgrading command block tools to netherite.

Netherite tools aren't coming to this mod due to how powerful they'd be, invalidating the other tools.

**Comment by nonamecrackers2** [comment]
I prefer the current advancement name. Also, please read the guidelines. Only one suggestion per issue

**Comment by BluePineappleGuy** [comment]
Eye of the storm is still a cool advancement name, perhaps it could be for something else related to the heads?
