### ISSUE TITLE
[Suggestion]: Broken Wither Storm head additions

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1644]
### Description of feature request

I notice how broken wither storm heads don't move smooth like when it has tractor beams. The idea is to have them have the same movement but a little faster than normal.

**Comment by myron-obsolete-account** [comment]
> For the bowels heads, they should have the smooth head movement as well.

#1461

**Comment by TaintedBlockmObile** [comment]
Oh! Alright I'll change this then.

**Comment by nonamecrackers2** [comment]
I prefer how they move currently as it makes them seem a bit confused and wondering what just happened to them
