### ISSUE TITLE
[Bug]: Withered Symbiont does not spawn

### ISSUE THREAD

**Issue by Subaru112** [nonamecrackers2/crackers-wither-storm-mod#1647]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

The Withered Symbiont wont spawn, ive waited hour and a half yet nothing, havent seen any withered mobs either, the wither storm is at the phase 5
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/68911687/cb258faf-bd5b-4566-9e99-d02b9c4ebab9)

also i dont know if this is an issue too but after forcefully evolving the wither storm into phase 6 then the hole meant to take the user to the commandblock room didnt open

### Steps to Reproduce

No idea but ive had to respawn the wither storm using commands once before because he despawned after a minecraft crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

JEI 1.20.1-forge-15.2.0.27

**Comment by GearsawStudios** [comment]
Phase 5 isn't the right phase. It needs to be phase 5.5 instead, rendering this intended.

**Comment by BluePineappleGuy** [comment]
try evolving it without force to get big brain, then wait. it may fix the problem.

**Comment by Subaru112** [comment]
> Phase 5 isn't the right phase. It needs to be phase 5.5 instead, rendering this intended.

How long do i have to wait for 5.5? On the wiki it described 5.5 that he starts approaching me at high speeds which happened

**Comment by BluePineappleGuy** [comment]
> > Phase 5 isn't the right phase. It needs to be phase 5.5 instead, rendering this intended.
> 
> How long do i have to wait for 5.5? On the wiki it described 5.5 that he starts approaching me at high speeds which happened

it often happens when he evolves, not neccesarily 5.5
try using the `/witherstorm evolve` command but not forcefully, it should put it in max stage 5.

**Comment by Subaru112** [comment]
> > > Phase 5 isn't the right phase. It needs to be phase 5.5 instead, rendering this intended.
> > 
> > 
> > How long do i have to wait for 5.5? On the wiki it described 5.5 that he starts approaching me at high speeds which happened
> 
> it often happens when he evolves, not neccesarily 5.5 try using the `/witherstorm evolve` command but not forcefully, it should put it in max stage 5.

Something didnt work when i was trying to evolve him without force, i will try again later

**Comment by nonamecrackers2** [comment]
As others stated the symbiont only spawns at and past phase 5.5. I’d also double check the guide.

Also the bowels hole only opens at the end of phase 7. I would take a look at the [commands](https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Commands-and-Technical) GitHub wiki page, it should help you figure out what you want to do.
