### ISSUE TITLE
Mod crashes before launch

### ISSUE THREAD

**Issue by CladCrowe** [nonamecrackers2/crackers-wither-storm-mod#165]
Minecraft version 1.19 (but I also tried it on the versions listed on the curseforge website for this particular mod)
First I used curseforge to download the mod.  After the minecraft launcher loads, it crashes before I can even get into the game. I went back and manually downloaded the mod and put it in the mod folder and the same thing happed.
I will include a picture of the message I receive when I click play.
![Crash](https://user-images.githubusercontent.com/32950186/177015654-e602e941-3dd7-4919-9686-0a71030747d7.PNG)

Log report will be included as well.

I also saw that the mod was currently for 1.16.5 as well so I tried that and the I made it past the launcher but then it gave me an error saying I needed to load on 1.18.2 or higher. 
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9033691/latest.log)

**Comment by nonamecrackers2** [comment]
There is no 1.19 version of the mod. From the error message, something is wrong with your java setup (probably arguments?). Check your instance and see if the arguments are invalid. Otherwise, you'll need to go somewhere else to get assistance.

**Comment by CladCrowe** [comment]
It's so weird, I tried it on the 1.18.2 as well and got the same result.  I will have to look into the java issue.

**Comment by CladCrowe** [comment]
Got it fixed. Java has to be 17 or better.

**Comment by nonamecrackers2** [comment]
Glad you got it fixed!

**Comment by CladCrowe** [comment]
Thanks for chatting with me. My kid is going insane right now 🤣🤣🤣🤣🤣🤣

**Comment by nonamecrackers2** [comment]
That's awesome!
