### ISSUE TITLE
Command block shield

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#1651]
### Description of feature request

The command block shield would be crafted with a shield and a command block book in an anvil, it has greater resistance over witherstorm related entities and blocks some knockback damage, slightly more useful than a normal shield.

**Comment by TaintedBlock** [comment]
Please read the guidelines

**Comment by MaagesticAF** [comment]
true

**Comment by nonamecrackers2** [comment]
Please read the guidelines.
