### ISSUE TITLE
[Suggestion]: Sculk Horde compatibility

### ISSUE THREAD

**Issue by JeeperCreeperIH** [nonamecrackers2/crackers-wither-storm-mod#1653]
### Description of feature request

I doubt that this would get added... but nonetheless, I'm just putting it out there.

Sculk Horde compatibility, where the Wither Storm could perhaps get infected by the sculk horde, changing generation of the Bowels... or maybe even it could specifically target the Sculk Horde, disliking competitors.

I don't have much else to say, other than I did this manually (with the bowels being filled with the Sculk Horde) and it was ten times harder (WITH cheats). so it could become nearly impossible.

you might have to communicate with the dev(s) of the other mod, idk, it just seems like a cool idea.

**Comment by BluePineappleGuy** [comment]
I dont like the sculk storm idea (it would fit better as a separate mod since it means an entire chunk of the mod depends on another mod), but it targeting the sculk horde sounds pretty cool. Perhaps its aggression would be heavily increased in an attempt to wipe any sculk mobs out.

**Comment by JeeperCreeperIH** [comment]
Makes sense, maybe not sculk storm but aggression increase would be cool XD

**Comment by nonamecrackers2** [comment]
This is a bit out of scope for the mod and is incredible niche, interesting idea though.

**Comment by JeeperCreeperIH** [comment]
alright. I wasn't expecting it to happen anyway XD

**Comment by BluePineappleGuy** [comment]
> This is a bit out of scope for the mod and is incredible niche, interesting idea though.

Actually, for aggression suggestions, could you add a tag of mobs that the storm would target more than others? It would probably be empty, but it would be cool for datapacks so people can add these themselves.

**Comment by nonamecrackers2** [comment]
That’s already implement, I forget the exact name of the tag but it’s something along the lines of “favourable mobs”

**Comment by BluePineappleGuy** [comment]
> That’s already implement, I forget the exact name of the tag but it’s something along the lines of “favourable mobs”

Ah thx, didn't know
