### ISSUE TITLE
[Suggestion]: Join the Wither Storm

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1658]
### Become one with the Storm

Why constantly have to struggle and fight against the Wither Storm when you can **join the Storm**?

I propose an optional config where that if a player dies by the Wither Sickness, the player will reincarnate as a pawn to the Wither Storm, that will infect the world with the Wither Sickness and destroy the world as well.

As a Withered Player, they gain a default texture that resembles that of the Withered Symbiont, and gain the ability to give Wither Sickness to any nearby mobs, and has the ability to apply the Wither effect upon inflicting damage to any mob.

The only way to break free from being part of the Wither Storm is for the corrupted player to eat a Golden Apple Stew, where after the stew takes full effect, the player dies, and reincarnates as a normal player again.

This would provide an interesting way to experience the mod and give new ways to play Minecraft in general.

**Comment by BluePineappleGuy** [comment]
so essentially, he withers the world around him. i assume anything he kills or "consumes" adds to the storms growth?

**Comment by ghost** [comment]
> I assume anything he kills or "consumes" adds to the storms growth?

Not what I intended, but would be a killer idea.

**Comment by IndigoAmethyst** [comment]
I absolutely love this idea but it is very game changing so we will have to wait for Cracker to arrive at the case

**Comment by nonamecrackers2** [comment]
Interesting idea but out of scope for the mod.
