### ISSUE TITLE
[Bug]: wither storm is not dead after defeating the command block

### ISSUE THREAD

**Issue by Mrkripl** [nonamecrackers2/crackers-wither-storm-mod#1659]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.4

### Describe the bug

when I defeated the command block it flashbanged me made a sound and that's all it did, didn't tp me out of it
the WS still acted as not defeated and the command block cannot be killed in any way not even commands
the WS can be killed by /kill

### Steps to Reproduce

1. defeat command block
2. flashbang + sound
3. don't get TPd from WS
4. leave WS
5. WS still alive

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2023-11-28_19 43 31](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/92227052/f20da22b-195c-4ff5-b89f-884bd5a3e4f4)
![2023-11-28_19 44 01](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/92227052/b8f2b221-ee67-45c9-81f7-b17f30809dec)

### Mod List

	- ae2 15.0.15
	- aether 1.20.1-1.0.0-beta.1.4-neoforge
	- alexscaves 1.0.6
	- alexsmobs 1.22.6
	- appleskin 2.5.1+mc1.20.1
	- ars_creo 4.0.1
	- ars_elemental 1.20.1-0.6.3.1
	- ars_nouveau 4.7.4
	- arseng 1.1.2
	- balm 7.1.4
	- betterdungeons 1.20-Forge-4.0.3
	- betterjungletemples 1.20-Forge-2.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- bhc 1.20.1-1.0.5
	- blockui 1.20.1-1.0.124-BETA
	- boatiview 0.0.5
	- bookshelf 20.1.6
	- botanypots 13.0.17
	- chunkloaders 1.2.8a
	- citadel 2.4.8
	- cleanswing 1.20-1.3
	- clumps 12.0.0.3
	- collective 7.7
	- constructionwand 1.20.1-2.11
	- corail_woodcutter 3.0.3
	- cosmeticarmorreworked 1.20.1-v1a
	- crafttweaker 14.0.17
	- create 0.5.1.f
	- creeperoverhaul 3.0.1
	- cristellib 1.1.5
	- cucumber 7.0.4
	- cumulus_menus 1.20.1-1.0.0-beta.1-neoforge
	- curios 5.4.2+1.20.1
	- darkutils 17.0.3
	- deeperdarker 1.2.1
	- domum_ornamentum 1.20-1.0.147-BETA
	- doubledoors 5.1
	- dungeoncrawl 2.3.14
	- enchantinginfuser 8.0.2
	- enchdesc 17.0.8
	- endermanoverhaul 1.0.1
	- endersdelight 1.0.3
	- farmersdelight 1.20.1-1.2.3
	- fastleafdecay 31
	- flywheel 0.6.10-7
	- forge 47.2.4
	- framework 0.6.16
	- fullbrightnesstoggle 3.1
	- geckolib 4.2.4
	- goblintraders 1.9.3
	- harvestwithease 7.1.0.0
	- highlighter 1.1.7
	- iceberg 1.1.16
	- immersive_aircraft 0.6.2+1.20.1
	- immersiveengineering 1.20.1-10.0.0-169
	- insanelib 1.12.1
	- inventorysorter 23.0.1
	- jade 11.6.3
	- jearchaeology 1.20.1-1.0.3
	- jei 15.2.0.27
	- kleeslabs 15.0.0
	- legendarytooltips 1.4.5
	- lootr 0.7.29.68
	- minecolonies 1.20.1-1.1.319-BETA
	- minecraft 1.20.1
	- mixinextras 0.2.0-beta.9
	- moonlight 1.20-2.8.60
	- moreoverlays 1.22.1-mc1.20
	- mousetweaks 2.25
	- multipiston 1.20-1.2.31-ALPHA
	- mysticalagradditions 7.0.1
	- mysticalagriculture 7.0.6
	- netherportalfix 13.0.0
	- nethersdelight 1.20.1-4.0
	- nitrogen_internals 1.20.1-0.1.3-neoforge
	- notreepunching 7.1.0
	- patchouli 1.20.1-81-FORGE
	- pigpen 15.0.2
	- prism 1.0.5
	- productivebees 1.20.1-12.2.7
	- progressivebosses 3.9.5-mc1.20.1
	- projecte 1.0.0B
	- puffish_skills 0.10.0
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.8
	- reliquary 1.20.1-2.0.36.1199
	- resourcefulconfig 2.1.0
	- resourcefullib 2.1.16
	- runelic 18.0.2
	- snowundertrees 1.4.2
	- snowyspirit 1.20-2.2.5
	- stackrefill 4.1
	- structurize 1.20.1-1.0.662-BETA
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.15
	- t_and_t 0.0NONE
	- terrablender 3.0.0.169
	- tmted 1.0.3
	- tombstone 8.5.5
	- underground_jungle 2.1-forge
	- usefulbackpacks 2.0.1.122
	- uteamcore 5.1.4.269
	- waystones 14.0.2
	- witherstormmod 4.0.1
	- xaerominimap 23.8.4
	- xaeroworldmap 1.36.0
	- yungsapi 1.20-Forge-4.0.2
	- yungsbridges 1.20-Forge-4.0.3
	- yungsextras 1.20-Forge-4.0.3

**Comment by Herobrine982950291** [comment]
WOAH THIS MODLIST IS QUITE BIG

**Comment by Herobrine982950291** [comment]
maybe some of these mods is causing the issue? try killing it with only the Witherstorm mod enabled.

**Comment by AnguineChip** [comment]
> maybe some of these mods is causing the issue? try killing it with only the Witherstorm mod enabled.

I have the same issues, so i m gonna do a test on this

**Comment by AnguineChip** [comment]
![2023-12-29_13 11 22](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/72217956/4e81bffd-2c25-43d4-8721-5fa39e88c83a)

i tested it, it is an incompatible mod that isn't working with the mod

**Comment by nonamecrackers2** [comment]
What was the mod?

**Comment by AnguineChip** [comment]
> What was the mod?

I still do not know, Trying to find it out, but takes in a lot of time

**Comment by AnguineChip** [comment]
Was playing it in my modpack that is downloadable on CurseForge, if you want you can add your mod and take a look at it, further than that bug, it worked fine.

**Comment by AnguineChip** [comment]
Pack is called: Divinia 4: Island Of Shadows

> Was playing it in my modpack that is downloadable on CurseForge, if you want you can add your mod and take a look at it, further than that bug, it worked fine.

**Comment by nonamecrackers2** [comment]
Well if you can find whatever mod is causing the issue, feel free to relay it here. Would be most appreciated.

**Comment by AnguineChip** [comment]
Oh, also forgot this, Alex's Caves Irradiation Effect and The Withers Storms Model are conflicting with each other, The Model gets all glitched when you got the Irradiated Effect on from the Toxic Caves.

**Comment by AnguineChip** [comment]
> Well if you can find whatever mod is causing the issue, feel free to relay it here. Would be most appreciated.

FOUND THE ISSUE, Its ALEX'S CAVES

**Comment by nonamecrackers2** [comment]
I will keep that noted, thank you. @Mrkripl try removing Alex's Caves and see if that fixes the issue

**Comment by witherstorm6** [comment]
There are more mods not compatible to this, even when I removed Alex's Cave, it still has this same bug. When I tried this mod with Apotheosis, it also get this same issue. I did not get this issue with only the Wither storm mod and Appleskin

**Comment by nonamecrackers2** [comment]
Yeah I can't seem to reproduce this bug with Alex's Caves. Considering the amount of mods, this might be hard to track down. I'm also wanting a log from OP, so I'll be closing this until I get more information from them.

**Comment by ShorterKing** [comment]
I think my workaround might resolve this issue:
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/2352#issuecomment-3173693228

**Comment by jackcrowley420** [comment]
it is an issue with the mod itself i think
