### ISSUE TITLE
[Suggestion]: Sick creeper create a cloud of wither effect after exploding

### ISSUE THREAD

**Issue by BrunoGoldbergFerro** [nonamecrackers2/crackers-wither-storm-mod#1660]
### Description of feature request

title

**Comment by BluePineappleGuy** [comment]
thought it already did this

**Comment by nonamecrackers2** [comment]
#1149

**Comment by BrunoGoldbergFerro** [comment]
> #1149

I just tested it, nothing happens when they explode

**Comment by nonamecrackers2** [comment]
The issue was closed for the other ideas being implemented. If I remember correctly having them explode with a wither effect cloud was not something I necessarily wanted in the mod at the time.
