### ISSUE TITLE
[Suggestion]: make tentacles look more alive

### ISSUE THREAD

**Issue by JeeperCreeperIH** [nonamecrackers2/crackers-wither-storm-mod#1661]
### Description of feature request

I know that many other suggestions have suggested this, but they all say that you should also make it so they are faster.

I don't want that.

I simply want a larger range of motion for the tentacles, specifically the Destroyer form tentacles, the Hunchback form tentacles, and the two large tentacles that it sprouts towards the end of its 'life cycle'. they just look static, and in the case of the Destroyer form look downright ridiculous.

**Comment by ghost** [comment]
Many suggestions for any changes to tenacles are going to be rejected, due to no plans of the tenacles being changed. 
(If I have misinterpreted the numerous closed suggestions on tenacles, crackers can correct me on this.)

**Comment by TaintedBlock** [comment]
#1512

**Comment by JeeperCreeperIH** [comment]
What I largely mean are these tentacles.
![Screenshot 2023-12-03 134509](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/87666060/b0daa202-22f5-436a-a0f3-1821a0e7edcd)
from a distance, they look ridiculous and goofy.

**Comment by JeeperCreeperIH** [comment]
it looks better in the latest versions than in the older versions, but it still looks quite bad.
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/87666060/2014eee4-7f1d-4b97-906e-6aaf1a4fec2f)

**Comment by TaintedBlockmObile** [comment]
> it looks better in the latest versions than in the older versions, but it still looks quite bad. ![image](https://private-user-images.githubusercontent.com/87666060/287542027-2014eee4-7f1d-4b97-906e-6aaf1a4fec2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MzIwOTksIm5iZiI6MTcwMTYzMTc5OSwicGF0aCI6Ii84NzY2NjA2MC8yODc1NDIwMjctMjAxNGVlZTQtN2YxZC00Yjk3LTkwNmUtNmFhZjFhNGZlYzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE5Mjk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyYjA0MzQ1MjRmYzg4OTY4YjUwYzRjMWQwMjk5YzQ0MWZlNmFiYTE4OTY5ODYwMTg2MDQwNDhhNDdkYzdmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BKoZ_eXvxR0ZsiRYRAvYyoO30jlKfwVgpJZCsWa9vjE)

This suggestion has already been suggested before. Please close this issue as crackers will not be adding this as of now.

**Comment by BluePineappleGuy** [comment]
i think it has been suggested before but a wider range of movement would be pretty cool

**Comment by nonamecrackers2** [comment]
This hasn't been suggested before from my quick search. Regardless I prefer the current tentacle animations and it's not in my best interests to change them as of now.
