### ISSUE TITLE
[Suggestion]: Tainted beacon (not withered one)

### ISSUE THREAD

**Issue by kapycta123456** [nonamecrackers2/crackers-wither-storm-mod#1665]
### Description of feature request

Crafting: 
![craft](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/148063104/75f37713-ac13-4946-853f-3a37647d2454)
It's basically beacon/withered beacon, but a bit more stronger
It takes some of amulet's power and powered spyglass's power
Tainted beacon abilities (when placed): See how much blocks far is wither storm. Right click to tp into mob that got his own color from amulet (15 sec cooldown, tp time: 5 seconds). Outline nearby mobs (25 blocks).
Tainted beacon abilities (when holding): Outline nearby mobs (15 blocks).
Design: similar to crafting recipe (I don't really know how to design yet 😢 )

**Comment by kapycta123456** [comment]
Don't really know if it's good suggestion or no

**Comment by leglessidiot** [comment]
It's a good idea!

**Comment by kapycta123456** [comment]
> It's a good idea!

Tysm

**Comment by TaintedBlockmObile** [comment]
This doesn't really make much sense imo since beacons in general are not crafted like this. Also, hardened flesh is not obtainable.

**Comment by nonamecrackers2** [comment]
I don’t see why another beacon would be worth it, these features would probably fit better in with the existing beacon than adding an entire new block, which takes effort and time.

**Comment by kapycta123456** [comment]
> This doesn't really make much sense imo since beacons in general are not crafted like this. Also, hardened flesh is not obtainable.

srry didn't knew that hardened flesh is not obtainable

**Comment by kapycta123456** [comment]
> I don’t see why another beacon would be worth it, these features would probably fit better in with the existing beacon than adding an entire new block, which takes effort and time.

maybe you can make those features on withered beacon?
