### ISSUE TITLE
[Bug]: Exploding the WS in small stages still causes the starfish structure to spawn

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1670]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.4

### Describe the bug

When i use /witherstormmod explode on a small wither storm, the structure with the dead witherstorms commandblock.

### Steps to Reproduce

1. summon WS in phase 1-3
2. make a /witherstormmod explode on WS
3. See error

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Minecraft Forge_ 1 20 1 08_12_2023 14_37_49](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/c344d0c5-3e3c-4f64-ad8e-1e875fb3c0ef)
![Minecraft Forge_ 1 20 1 08_12_2023 14_38_14](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/8c0745f0-88b0-4e22-a1fa-1c33ff36edf8)

### Mod List

![mods 08_12_2023 14_42_04](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/c4a9f328-7fdd-4d94-a3af-886a2b5d7853)

**Comment by Herobrine982950291** [comment]
this is another account. My Original is @Steve982950

**Comment by kapycta123456** [comment]
> this is another account. My Original is @Steve982950

You aren't supposed to explode wither storm below phase 4 😭😭
Beacuse some of ppl won't play with cheats and won't blow up ws early

**Comment by Herobrine982950291** [comment]
> You aren't supposed to explode wither storm below phase 4 😭😭

ik, just sayin
also why the cry emojis?

**Comment by kapycta123456** [comment]
> > You aren't supposed to explode wither storm below phase 4 😭😭
> 
> ik, just sayin also why the cry emojis?

Why would you post this if it's an useless bug that won't be fixed. Plus i think that's a copy of a bug

**Comment by TaintedBlockmObile** [comment]
I don't see this needing a fix tbh. You can't even blow up the wither storm till it reaches 5.5. and the only way to get this "bug" is if you use commands

**Comment by kapycta123456** [comment]
> I don't see this needing a fix tbh. You can't even blow up the wither storm till it reaches 5.5. and the only way to get this "bug" is if you use commands

True.

**Comment by BluePineappleGuy** [comment]
it used to do this when using a formidibomb in creative.
