### ISSUE TITLE
[Suggestion]: Add Tainted Pinch Beetles (JOKE)

### ISSUE THREAD

**Issue by Jouto55** [nonamecrackers2/crackers-wither-storm-mod#1675]
### Description of feature request

Add Tainted Pinch Beetles from Twilight Forest to the mod to make the game more challenging.

~~Also to traumatize Draco and Gearsaw~~

**NOTE: This is a joke from VC where Draco discussed his absolute hatred for Pinch Beetles, please don't ban me crackers-senpai**

**Comment by GearsawStudios** [comment]
> ### Description of feature request
> Add Tainted Pinch Beetles from Twilight Forest to the mod to make the game more challenging.
> 
> ~Also to traumatize Draco and Gearsaw~
> 
> **NOTE: This is a joke from VC where Draco discussed his absolute hatred for Pinch Beetles, please don't ban me crackers-senpai**

I simply repress hatred, I despise them as much as Draco most likely.
