### ISSUE TITLE
[Suggestion]: Suggestions for evolution part 2

### ISSUE THREAD

**Issue by Gubberball** [nonamecrackers2/crackers-wither-storm-mod#1677]
### Description of feature request

1. Phases 5-7 are changed to be more like in story mode
2. More subphases in between phases 3 and 4
3. Tentacles grabbing you, smacking you, and going through portals (if possible to code)
4. Tractor beams being able to suck up dropped items that come in contact with it instead of having to throw them close enough to the wither storm
5. Command block netherite tools, bows, and even tridents
6. The wither storm being able to turn on and off tractor beams on command
7. Phase 4 flies lower 
8. Elixir that can one shot phase 0-3 and has a small chance of spawning in the barrels in the spawn structure
9. Mobs being taken to the bowels IF they aren't chomped by the wither storm

**Comment by TaintedBlock** [comment]
all of these except the subphases between 3 and 4 have been denied. Also, please read the guidelines

**Comment by juanelgamer456** [comment]
we are making cracker go insane with this one 🗣️🗣️ :100: :100: ❗❗

**Comment by Laikagor** [comment]
holy moly
thats all denied features!

**Comment by nonamecrackers2** [comment]
1. Please read the guidelines.
2. #1431 
3. Please read the guidelines.
4. #509 
5. Please read the guidelines.
7. This is already doable with the config.
8. Please read the guidelines.

Please read the guidelines before posting something, and check for duplicates. **Also, only one suggestion per issue is allowed.** The numbers that I've not listed above are valid ideas and can be re-suggested in a new issue, but **separately** please, not in one single issue.
