### ISSUE TITLE
wither storm segments don't follow the main wither storm

### ISSUE THREAD

**Issue by xg787** [nonamecrackers2/crackers-wither-storm-mod#168]
**Minecraft version**
1.18.2

**Mod version**
2.0.1

**Describe the bug**
wither storm segments don't follow the main wither storm

**To Reproduce**
get any wither storm phase with the segments and move around a bit 

**Screenshots**
![2022-07-04_23 28 16](https://user-images.githubusercontent.com/59268579/177244993-7198c645-ea5d-45db-b08e-50420420bcf9.png)

![2022-07-04_23 26 10](https://user-images.githubusercontent.com/59268579/177244962-e838b76f-8106-4ab0-818b-caf83698a9d0.png)

**Comment by nonamecrackers2** [comment]
This issue will be fixed in the next update
