### ISSUE TITLE
[Bug]: cant punch a summoned flaming wither skull

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1684]
### Minecraft Version

1.19.4

### Mod Version

3.3.1

### Mod Loader

Forge

### Mod Loader Version

45.1.16

### Describe the bug

title explains it

### Steps to Reproduce

1. summon flaming wither skull
2. try punching it
3. See error

### Crash Reports/Logs

no

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

cwsm and other mods but i doubt other mods cause it

**Comment by nonamecrackers2** [comment]
This is intended, only swords can knock back flaming wither skulls.

**Comment by TaintedBlockmObile** [comment]
> This is intended, only swords can knock back flaming wither skulls.

I think he means you can't hit summoned flaming skulls with swords. You should probably try it out just in case this is what he meant

**Comment by Pandaboi25x** [comment]
oh wait nvm i forgot to use swords

**Comment by TaintedBlockmObile** [comment]
Oh

**Comment by Pandaboi25x** [comment]
> > This is intended, only swords can knock back flaming wither skulls.
> 
> I think he means you can't hit summoned flaming skulls with swords. You should probably try it out just in case this is what he meant

nah it works

**Comment by TaintedBlockmObile** [comment]
Nvm then
