### ISSUE TITLE
[Suggestion]: Sickened snow golems

### ISSUE THREAD

**Issue by Gubberball** [nonamecrackers2/crackers-wither-storm-mod#1685]
### Description of feature request

Basically, sickened snow golems will throw withered snowballs at you that give you wither II for 5 seconds and can be spawned with tainted pumpkins + withered snow blocks (crafted with 4 withered snowballs)

**Comment by Luke7381** [comment]
crackers stated that withered mobs will be coming at there discretion

**Comment by Gubberball** [comment]
Aight, someone must close this then

**Comment by Gubberball** [comment]
It's been closed
