### ISSUE TITLE
[Bug]: Witherstrom fog is extremely intense in the end

### ISSUE THREAD

**Issue by Danny999999999** [nonamecrackers2/crackers-wither-storm-mod#1688]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.21

### Describe the bug

If you are close to the witherstorm, the fog is intense. but, if you get a little farther away, the fog mostly vanishes.

### Steps to Reproduce

1. go to the end in creative
2. summon stage 4 witherstorn
3. fly around and observe weird effects.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

<img width="1280" alt="Screenshot 2023-12-18 111954" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129821008/06593b62-4077-49ae-affd-9697737a9853">
<img width="1280" alt="Screenshot 2023-12-18 112013" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129821008/399083bc-e893-4764-90ec-687cc69da126">

The first image is of the witherstorm from closer up. the second image is from farther away.

### Mod List

<img width="976" alt="Screenshot 2023-12-18 113333" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129821008/28f747ab-cac8-4a92-a2dc-add1cd30f24e">
<img width="947" alt="Screenshot 2023-12-18 113349" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129821008/d0248489-965e-47fc-890a-ec7f7ee1f2e6">

**Comment by FrozenDragon0** [comment]
This would likely be due to the Ender Dragon causing the fog in the first place, as the main island is surrounded in fog when she's alive.

**Comment by myron-obsolete-account** [comment]
the end (or also due to Jean as said by FrozenDragon0 above) has very dense fog, so this is "intentional". you can use mods like no-fog or use shaders to get rid of it.

**Comment by nonamecrackers2** [comment]
This is because of the Ender Dragon. You'll need to kill the dragon in order to remove the intense fog.
