### ISSUE TITLE
A question and also a suggestion: model of the tentacles

### ISSUE THREAD

**Issue by Gaboamau** [nonamecrackers2/crackers-wither-storm-mod#169]
If you've seen the shapes of the tentacles in MC:SM, you've thought about changing the tentacle model to look like in MC:SM, instead of being made of simple rectangles, it's made of several little squares placed randomly, like in the image:

![image](https://user-images.githubusercontent.com/106891155/177244515-e1047769-db47-4212-a1a2-743a526fa686.png)

**Comment by Globalfirestorm10** [comment]
Any updates on this?

**Comment by nonamecrackers2** [comment]
Models will most likely be staying the same, however still needs further reviewing.

**Comment by User198263321** [comment]
Should be a separate client option since this means more advanced models

**Comment by BluePineappleGuy** [comment]
i honestly like the idea of better tentacles

**Comment by nonamecrackers2** [comment]
Yeah, going to be keeping the models the same. The current ones are too recognizable to be changed.
