### ISSUE TITLE
[Suggestion]: Make arrows not bounce off block clusters.

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1691]
### Description of feature request

If you're being beamed up, the natural course of action would be to shoot the head that's beaming you up. However, the recent addition of block clusters being sucked up by the beams has resulted in that not being feasible at time. I fired several arrows at the WS, only for my shots to be deflected and me bit twice before slicing my way out of its head, nearly ending my hardcore run. To prevent cheap situations like this (since bows already are the intended way of getting away,) arrows should pierce through block clusters, as in no collision.

**Comment by nonamecrackers2** [comment]
Arrows can pierce block clusters. Are you sure it's not hitting something else?

**Comment by GearsawStudios** [comment]
I'm pretty sure it was the cluster.

**Comment by nonamecrackers2** [comment]
This is a bug then. What’s your mod list?

**Comment by GearsawStudios** [comment]
> This is a bug then. What’s your mod list?

Sorry for long wait, Github notifications on weird.
I have been unable to replicate this on either version, so this issue isn't useful anymore.
