### ISSUE TITLE
[Suggestion]: More Phase 3 Sub Phases

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1692]
### Description of feature request

I would like to see more stage 3 sub phases that get bigger and bigger until phase 4 occurs... or something like this!

**Comment by TaintedBlockmObile** [comment]
Already was confirmed to be added later.

**Comment by Herobrine982950291** [comment]
OK! :)

**Comment by nonamecrackers2** [comment]
#1431
