### ISSUE TITLE
[Suggestion]: Sickened Mobs naturally spawn in the Bowels.

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1694]
### Making the Bowels more "natural"

You know how in the Nether Piglins, Hoglins, and Skeletons naturally spawn there, in their respective biomes?

This suggestion makes Sickened Zombies, Spiders, Skeletons, and Creepers being able to naturally spawn in the Bowels, with the mob spawners being saved for stuff like structures in the Bowels. This would make the Bowels feel more like its own biome, and less  unnatural, with mob spawners being placed all over the bowels.

**Comment by nonamecrackers2** [comment]
I don't want mobs to spawn naturally, since I like having the main arena free from mobs to let the player get settled before their fight. The mob spawners are in the caves for when the player wants to go explore them, since it adds a challenge there.

**Comment by BrunoGoldbergFerro** [comment]
> I don't want mobs to spawn naturally, since I like having the main arena free from mobs to let the player get settled before their fight. The mob spawners are in the caves for when the player wants to go explore them, since it adds a challenge there.

make the arena and caves separate biomes

**Comment by nonamecrackers2** [comment]
That would be too hard to detect. The current method is much simpler and works well
