### ISSUE TITLE
[Suggestion]: Can you improve the Phase 6 model?

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1696]
### Description of feature request

In this image: 
![2023-12-27_13 01 43](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/331b56d3-f46e-4a2f-b203-439cf8066665)

the ripped parts are not in the accurate position.. like.. Imagine putting the segments in the holes!
![2023-12-27_13 01 43](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/4c81a500-dd7d-42db-8b00-8af0b1cc2d17)
(Sorry about goofy ahh drawing but you know what I mean)

**Comment by LegendaryGodzilla** [comment]
I alr know this been suggested for then once and CWSM is not supposed to be accurate

**Comment by TaintedBlockmObile** [comment]
Crackers won't be changing the models dude

**Comment by Isoknight** [comment]
> I alr know this been suggested for then once and CWSM is not supposed to be accurate

This seems less about accuracy and more about inconsistency to me.

**Comment by Herobrine982950291** [comment]
oh... alright...

**Comment by Gubberball** [comment]
Major model changes aren't going to happen

**Comment by nonamecrackers2** [comment]
Please read the guidelines

**Comment by myron-obsolete-account** [comment]
#823
