### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Th1rdo** [nonamecrackers2/crackers-wither-storm-mod#1697]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

I was lagging in my singleplayer world. I made a spark profile and I noticed this:

**Server thread57.81%**
- nonamecrackers2.witherstormmod.common.entity.goal.AvoidWitherStormGoal.canUse()57.15% 36870ms (witherstormmod)
        - net.minecraft.world.level.EntityGetter.getEntitiesOfClass()57.05% 36810ms
                   - net.minecraft.world.level.Level.getEntities()57.05% 36810ms

...

I'ts using too much and I don't know why, maybe there is something on the config file to prevent this, but I'm not aware of such configuration.

### Steps to Reproduce

1. Install the mod pack i have
2. Open the game
3. Create a world
4. Destroy any block and you will see the absurd amount of lag

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/67807009/3a02f9ce-caee-4a1b-b309-ef196729d9e6)

### Mod List

Ad-Astra-Giselle-Addon-forge-1.20.1-5.8.jar

ad_astra-forge-1.20.1-1.15.5.jar

AdvancementPlaques-1.20.1-forge-1.5.1.jar

AI-Improvements-1.20-0.5.2.jar

alexscaves-1.0.9.jar

alexsmobs-1.22.7.jar

alternate_current-mc1.20-1.7.0.jar

AmbientSounds_FORGE_v5.3.5_mc1.20.1.jar

Apotheosis-1.20.1-7.2.0.jar

ApothicAttributes-1.20.1-1.2.1.jar

aquacombat 1.2.jar

Aquaculture-1.20.1-2.5.1.jar

aquamirae-6.API15.jar

architectury-9.1.12-forge.jar

athena-forge-1.20.1-3.1.1.jar

balm-forge-1.20.1-7.2.1.jar

Better_Dogs_X_Doggy_Talents_Next_v1.2.1 [1.20-1.20.1].jar

BetterAdvancements-1.20.1-0.3.2.162.jar

bettercombat-forge-1.8.1+1.20.1.jar

Bookshelf-Forge-1.20.1-20.1.8.jar

botarium-forge-1.20.1-2.2.1.jar

caelus-forge-3.1.0+1.20.jar

canary-mc1.20.1-0.2.10.jar

carryon-forge-1.20.1-2.1.2.7.jar

cataclysmiccombat-1.2.jar

catalogue-forge-1.20.1-1.8.0.jar

charmofundying-forge-6.4.5+1.20.1.jar

chipped-forge-1.20.1-3.0.1.jar

Chunky-1.3.92.jar

citadel-2.4.9-1.20.1.jar

cloth-config-11.1.118-forge.jar

Clumps-forge-1.20.1-12.0.0.3.jar

comforts-forge-6.3.4+1.20.1.jar

Controlling-forge-1.20.1-12.0.2.jar

CorgiLib-forge-1.20.1-4.0.0.4.jar

cosmeticarmorreworked-1.20.1-v1a.jar

create-1.20.1-0.5.1.f.jar

create_central_kitchen-1.20.1-for-create-0.5.1.f-1.3.9.d.ja

create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.7h.j

create_wizardry-1.20.1-0.1.1.jar

createaddition-1.20.1-1.2.1.jar

createbigcannons-forge-1.20.1-0.5.3.a.jar

createchunkloading-1.6.0-forge.jar

creategoggles-1.20.1-0.5.5.e_hf-[FORGE].jar

createoreexcavation-1.20-1.4.2.jar

CreativeCore_FORGE_v2.11.16_mc1.20.1.jar

creeperoverhaul-3.0.1-forge.jar

cupboard-1.20.1-2.2.jar

curios-forge-5.4.7+1.20.1.jar

deeperdarker-forge-1.20.1-1.2.1.jar

Divine_Weaponry_v1.7_1.20.1.jar

DoggyTalentsNext-1.20.1-1.18.4.jar

embeddium-0.2.16+mc1.20.1.jar

EnchantmentDescriptions-Forge-1.20.1-17.0.11.jar

endermanoverhaul-forge-1.20.1-1.0.3.jar

Enhanced_Celestials-forge-1.20.1-5.0.0.2.jar

entityculling-forge-1.6.2-mc1.20.1.jar

exposure-1.20.1-1.2.1-forge.jar

FarmersDelight-1.20.1-1.2.3.jar

Fastload-Reforged-mc1.20.1-3.4.0.jar

ferritecore-6.0.1-forge.jar

framework-forge-1.20.1-0.6.16.jar

friendsandfoes-forge-mc1.20.1-2.0.6.jar

geckolib-forge-1.20.1-4.3.1.jar

getittogetherdrops-forge-1.20-1.3.jar

goblintraders-forge-1.20.1-1.9.3.jar

handcrafted-forge-1.20.1-3.0.5.jar

Iceberg-1.20.1-forge-1.1.18.jar

Incendium_1.20.4_v5.3.4.jar

interiors-0.5.2+mc1.20.1-FORGE.jar

irons_spellbooks-1.20.1-2.1.2.jar

kleeslabs-forge-1.20-15.0.0.jar

kotlinforforge-4.10.0-all.jar

KryptonReforged-0.2.3.jar

L_Enders_Cataclysm-1.85 -1.20.1.jar

labels-1.20-1.19.jar

letmedespawn-forge-1.20.x-1.2.0.jar

Log-Begone-Forge-1.20.1-1.0.8.jar

map_atlases-1.20-5.12.7-all.jar

mob_grinding_utils-1.20.1-1.0.3.jar

modernfix-forge-5.11.1+mc1.20.1.jar

moonlight-1.20-2.8.72-forge.jar

mutil-1.20.1-6.1.1.jar

mythicmounts-20.1-7.4.2-forge.jar

netherportalfix-forge-1.20-13.0.1.jar

nethersdelight-1.20.1-4.0.jar

nocube's_create_compact_exp_1.0.3_forge_1.20.1.jar

Nullscape_1.20.4_v1.2.4.jar

obscure_api-15.jar

octolib-0.1.jar

Patchouli-1.20.1-84-FORGE.jar

Placebo-1.20.1-8.6.0.jar

player-animation-lib-forge-1.0.2-rc1+1.20.jar

REIPluginCompatibilities-forge-12.0.93.jar

relics-1.20.1-0.5.2.1.jar

rer-2.9.0.jar

resourcefulconfig-forge-1.20.1-2.1.0.jar

resourcefullib-forge-1.20.1-2.1.20.jar

RoughlyEnoughItems-12.0.684-forge.jar

RoughlyEnoughProfessions-forge-1.20.1-2.0.2.jar

sculkhorde-1.20.1-0.8.0.jar

Searchables-forge-1.20.1-1.0.2.jar

SereneSeasons-1.20.1-9.0.0.46.jar

SharedAdvancements-1.20.1-1.0.5.jar

simplyswords-forge-1.51.5-1.20.1.jar

sliceanddice-forge-3.2.0.jar

smoothchunk-1.20.1-3.5.jar

solcarrot-1.20.1-1.15.1.jar

sound-physics-remastered-forge-1.20.1-1.3.1.jar

spelunkery-1.20.1-0.3.4-forge.jar

Steam_Rails-1.5.3+forge-mc1.20.1.jar

Structory_1.20.2_v1.3.4.jar

Structory_Towers_1.20.4_v1.0.6.jar

supplementaries-1.20-2.7.14.jar

suppsquared-1.20-1.1.11.jar

Terralith_1.20.4_v2.4.11.jar

tetra-1.20.1-6.1.0.jar

tetraextrassro-0.1.1-1.20.jar

tetranomicon-1.4.4-1.20.1.jar

ToastControl-1.20.1-8.0.3.jar

witherstormmod-1.20.1-4.0.1.jar

**Comment by BluePineappleGuy** [comment]
thats a lot of mods

**Comment by Herobrine982950291** [comment]
I aint reading dat mod list. BTW try only enabling Wither storm Mod and nothing else

**Comment by nonamecrackers2** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Known-Compatibility-Issues#lithium-forks-radium-canary-1182

I encountered this myself when setting up a server. Canary used to detect if CWSM was installed and automatically did what's in the link I sent but I guess it doesn't do that anymore.
