### ISSUE TITLE
[Suggestion]: Sickened mobs infect other normal mobs when killed by them

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1698]
### Description of feature request

Title explains itself. Like a zombie killing a villager

**Comment by Herobrine982950291** [comment]
Ooh I like this Idea (In my Opinion)

**Comment by NinjaSam5399** [comment]
Love this idea

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
