### ISSUE TITLE
[Suggestion]: Tainted wool

### ISSUE THREAD

**Issue by Cuteplushbros** [nonamecrackers2/crackers-wither-storm-mod#1699]
### Description of feature request

Its a dark purple wool gotten by shearing or killing a sickened sheep (if that's being added). it can make a tainted bed, banner, carpet, and a tainted painting (the vanilla paintings but Wither Storm-Ified)

**Comment by Krypton6167** [comment]
Wait, Didn't the guidelines say NOT to suggest tainted variants of blocks?

**Comment by Aimyx** [comment]
I think it is different for like, a loot standpoint. like here you get tainted wool as a drop

**Comment by nonamecrackers2** [comment]
> Wait, Didn't the guidelines say NOT to suggest tainted variants of blocks?

Yes, thank you for pointing that out

**Comment by BluePineappleGuy** [comment]
I mean technically this is to suggest a niche quality fulfilled by the block (withered paintings and beds), not just the addition of the block itself.
