### ISSUE TITLE
Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by Jetpack-Cat** [nonamecrackers2/crackers-wither-storm-mod#17]
Crashes on world creation, would have loved to put this mod in my upcoming modpack.

It looks like a compatibility issue with roadrunner mod, which is unfortunate because roadrunner is a necessity for any pack with it's amazing performance improvements. Hope it gets fixed.

[crash-2022-05-16_03.37.56-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/8699310/crash-2022-05-16_03.37.56-server.txt)

**Comment by nonamecrackers2** [comment]
Should be fixed in an upcoming update
