### ISSUE TITLE
[1.16.5] Add ability to disable x=0 z=0 structure

### ISSUE THREAD

**Issue by Subthy** [nonamecrackers2/crackers-wither-storm-mod#170]
Ability to disable the structure that spawns at x=0 z=0 in config, it would give more ability to customize the mod. As for example , I want to use zen summoning to summon wither storm, so I would like to get rid of any other ways that allows you to summon it.

xoxoxox
- Sub

**Comment by nonamecrackers2** [comment]
There is a config option to do this in the common config

**Comment by Subthy** [comment]
Well, I set it to false and the config doesn't work. The structure still spawns. I am running the latest build of your mod.

**Comment by nonamecrackers2** [comment]
Please make a bug report then, as that is unintended.
