### ISSUE TITLE
[Suggestion]: CITADEL compatibility?

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1700]
### Description of feature request

Will the issue with the wither storm not chasing players far away if you have the citadel mod be fixed?
This would allow CWSM to work properly alongside alex's other mods.

**Comment by BluePineappleGuy** [comment]
And cataclysm, which is a great boss mod. Would be amazing to be beating these bosses for tools to defeat the storm.

**Comment by nonamecrackers2** [comment]
If there's an issue, please make a bug report instead of a suggestion, thank you.
