### ISSUE TITLE
[Bug]: Texture duplication with Withered Beacon when using resource pack

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1703]
### Minecraft Version

1.19.4

### Mod Version

3.3.1

### Mod Loader

Forge

### Mod Loader Version

45.1.16

### Describe the bug

So for some reason, the Withered beacon breaks when I put edited models/textures onto the withered beacon.
I couldn't tell you why this is. But it may be because of the emissive textures added. 

### Steps to Reproduce

1. Go to cruseforge and install the latest version of CWSP then minecraft
2. Click on a world
3. Place withered beacon
4. right click the formidibomb or super tnt onto the beacon with the texture pack on
5. see error

### Is OptiFine installed?

- [X] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/3b8282b4-d76f-48fb-b049-344014fbd188)

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/155f4f3b-4240-4076-a7de-0b3e3061f6ad)

**Comment by TaintedBlock** [comment]
OK im realizing its just optifine being optifine lol. Gonna close this

**Comment by nonamecrackers2** [comment]
Was about to say lol
