### ISSUE TITLE
[Bug]: Storm Pickup Clusters Rendering as Normal Withers in Replay Mod (Read Desc)

### ISSUE THREAD

**Issue by AccurateGIT** [nonamecrackers2/crackers-wither-storm-mod#1705]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.1.3

### Describe the bug

When Using Replay Mod, (With Connective) The Chunks that the Witherstorm picks up are being rendered as normal (Phase 1) withers. PS - i did install a newer version of replay mod, due to high loading times. Specifically, from 2.6.13 to 2.6.14

### Steps to Reproduce

1. Enter a Replay with a Witherstorm
2. observe
3. noticing block clusters rendered as withers instead of blocks
4. tried troubleshooting configs and didnt work

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-01-02_19 16 35](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/122229446/8f552b1f-0227-4cc2-991f-8f8d8c628fc2)

### Mod List

architectury 9.1.12-forge
CameraOverhaul- 1.4.0 Fabric Universal
cloth-config 11.1.106-forge
collective-1.20.1-7.15
connectivity-1.20.1-4.8
Connector-1.0.0-beta.25 + 1.20.1
ConnectorExtras-1.8.0+1.20.1
CreativeCore_FORGE_v2.11.11_mc1.20.1
cupboard-1.20.1-2.1
embeddium-0.2.13+mc1.20.1
essential_1-2-3_forge_1-20-1
fabric-api-0.90.7+1.10.3+1.20.1
fakeplayers-0.7.6+1.20.1
GoProne-forge-1.20.1-3.1.1
hourglass-1.20-1.2.1.1
iris-mc1.20.1-1.6.11
notenoughanimations-forge-1.6.4-mc1.20 - Copy
oculus-mc1.20.1-1.6.9
physics-mod-pro-v164-forge-1.20.1
player-animation-lib-forge-1.0.2-rc1+1.20 - Copy
replaymod-1.20.1-2.6.14
sit-1.20.1-1.3.4
soundphysics-forge-1.20.1-1.1.2
voicechat-forge-1.20.1-2.4.30
worldedit-mod-7.2.15
witherstormmod-1.20.1-4.0.1.1

**Comment by Herobrine982950291** [comment]
I'm so confused. How did you even get a Replay mod in forge for 1.20.1?

**Comment by AccurateGIT** [comment]
@Steve982950291 
i used "Connector" to use fabric mods with forge

**Comment by Herobrine982950291** [comment]
OH COOL when I tried that it 
C_R_A_S_H_E_D

**Comment by nonamecrackers2** [comment]
Quite a peculiar bug. This may be hard to fix considering it's using the connector mod, but I'll leave this open for future reference.

**Comment by FrozenDragon0** [comment]
> OH COOL when I tried that it C_R_A_S_H_E_D

You need to be on Forge version 47.1.3 1.20.1 specifically to actually use it.

**Comment by Herobrine982950291** [comment]
ok.

**Comment by nonamecrackers2** [comment]
I got all your mods but can't seem to replicate the issue. Considering this uses connector and has a bunch of other mods I'm not sure what could be the cause or where you could even report this to. I'd try updating all your mods since this issue has been opened for a while and there are updates to most of them.
