### ISSUE TITLE
[Suggestion]: add a poem like the end poem for when you defeat the wither storm

### ISSUE THREAD

**Issue by BrunoGoldbergFerro** [nonamecrackers2/crackers-wither-storm-mod#1706]
### Description of feature request

and in the credits put the patreon supporters

**Comment by TaintedBlockmObile** [comment]
How would this be properly inserted into the mod tho

**Comment by BrunoGoldbergFerro** [comment]
before you are teleported to the overworld after destroying the command block

**Comment by GrandmaPork** [comment]
This should be optional because as cool as it is… some people just want to watch the wither storm die

**Comment by Pandaboi25x** [comment]
wasnt this suggested before?

**Comment by BrunoGoldbergFerro** [comment]
yeah

**Comment by BrunoGoldbergFerro** [comment]
> wasnt this suggested before?

i have no idea

**Comment by BrunoGoldbergFerro** [comment]
> This should be optional because as cool as it is… some people just want to watch the wither storm die

yeah

**Comment by GrandmaPork** [comment]
Nvm this was recommended #1215
