### ISSUE TITLE
[Bug]: broken down house world gen error

### ISSUE THREAD

**Issue by Danny999999999** [nonamecrackers2/crackers-wither-storm-mod#1707]
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.1

### Describe the bug

broken down house places grass blocks even when generating on a different block(like gravel)

### Steps to Reproduce

example seed:
217213653446610552

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-01-03_12 01 25](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129821008/e796014a-d6e4-45f5-b708-8eb10732b1ba)

### Mod List

<img width="944" alt="image" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/129821008/1b74afb3-042a-4f13-85e8-f9adbf0fbab4">

**Comment by TaintedBlockmObile** [comment]
This isn't a bug. That's just part of the structure.

**Comment by nonamecrackers2** [comment]
This is intended, the grass is apart of the structure
