### ISSUE TITLE
[Idea for Tractor Beam]

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#171]
I was thinking when the Witherstorm is being focused on a area for a long enough time instead of a huge chunk coming up a rumbling sound should play and the blocks being focused will rip up in 1x1s it would make structures or the WS burrowing into the ground with its beam much more menacing and effective

**Comment by nonamecrackers2** [comment]
My biggest concern is how performance will be impacted with block clusters splitting, however this does seem interesting. I'll close this for the meantime, I want to make block clusters more performant before this anyway.
