### ISSUE TITLE
[Suggestion]: The wither storm's boss bar, and the wither sky darkening effect, should be active regardless of distance.

### ISSUE THREAD

**Issue by Mellohi138** [nonamecrackers2/crackers-wither-storm-mod#1711]
The boss bar doesn't need to be active when in underground, but sky darkening would be a really nice detail that shows the storm's presence is felt on the entire world.

**Comment by GearsawStudios** [comment]
That’d make no sense in the long run since the WS could be super far away and still darken the sky and let mobs not burn. Also, the bossbar would clutter the screen unnecessarily.

**Comment by Mellohi138** [comment]
By the sky darkening effect I was talking about the one that occurs when a wither is around, not the hellish sky that occurs when its a post-stage-5 wither storm.

As for the boss bar, if it's a clutter when far away what makes it "not clutter" when it's near you? Unless it's phases 1-3 or the bowels you literally have no way of damaging the wither storm, am I missing something?

**Comment by GearsawStudios** [comment]
When the WS is close, the boss bar is an indicator of danger, especially with music disabled. Also, the wither sky effect would ruin all screenshots taken when the WS is in the world, the WS derives the anxiety it emanates from the fact that you never know when the world will be turned upside down from it, not from its global influence.

**Comment by Mellohi138** [comment]
Fair enough

**Comment by BluePineappleGuy** [comment]
could be config tho
