### ISSUE TITLE
[Suggestion]: Command blocks can be broken with any command block tool. (Duplicate)

### ISSUE THREAD

**Issue by ThatB0i** [nonamecrackers2/crackers-wither-storm-mod#1714]
### Description of feature request

I feel like Command blocks should be destructible with command block tools since I mean, it already can destroy the command block in the storm, also it's not like you can get one in Survival, but it just would be a neat little thing. It would not drop the command block since that would kinda be useless (as if this wasn't useless already...)

also it could have config to turn it on and off

**Comment by TaintedBlockmObile** [comment]
#1679

**Comment by ThatB0i** [comment]
Dammit, I swear I looked if this already was suggested and didint see any

Anyways I'll close this now due to it being a duplicate

**Comment by ThatB0i** [comment]
...oops, I missclicked "completed" ):

**Comment by ThatB0i** [comment]
I am very bad at using this site
