### ISSUE TITLE
[Bug]: withered beacon for 1.19.2

### ISSUE THREAD

**Issue by Fredbear01** [nonamecrackers2/crackers-wither-storm-mod#1715]
### Minecraft Version

1.19.2

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

Forge

### Describe the bug

I'm not entirely sure if this is a bug or not, but I could've sworn the withered beacon was in version 1.19.2, if it is, then it isn't appearing for me in JEI or anything, im not sure if it just wasn't implemented into 1.19.2 or if the recipe got removed

### Steps to Reproduce

I'm not sure

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

None

**Comment by ghost** [comment]
IIRC, the Wither Beacon is not in 1.19.2, The Beacon is only in versions 1.19.3 and upwards. 

You'll need to update your version of Minecraft if you want the Beacon.

**Comment by nonamecrackers2** [comment]
The withered beacon was not implemented into any 1.19.2 version of the mod
