### ISSUE TITLE
[Suggestion]: High CPU Usage by AvoidWitherStormGoal.canUse() in witherstormmod v2.2.1

### ISSUE THREAD

**Issue by Windrinn** [nonamecrackers2/crackers-wither-storm-mod#1716]
### Description of feature request

I've been profiling my server using Spark and I've encountered a performance bottleneck associated with the witherstormmod, specifically version 2.2.1. The method AvoidWitherStormGoal.canUse() appears to be consuming a significant amount of CPU resources, accounting for approximately 34.81% of server thread usage.

https://spark.lucko.me/K9ig1iRmNV

This performance issue is causing noticeable server lag, and I thought it would be important to bring it to your attention for potential optimization in future updates.

Thank you for your time and effort in creating and maintaining the witherstormmod. I appreciate any assistance you can provide in addressing this matter.

**Comment by ghost** [comment]
Highly doubt this suggestion will be accepted, as crackers is focused on the latest versions of MC, and version 2.2.1 is for MC 1.18.2.

You're better off updating CWSM to the latest version, as those performance issue may be fixed in the more recent versions.

**Comment by nonamecrackers2** [comment]
This is more of a bug so I'd reopen this as such. I'd also check if more modern versions of the mod still have the same issue, since iirc we've made improvements to that function overtime. We appreciate you bringing it up however of course.
