### ISSUE TITLE
[Bug]: wither not rendering

### ISSUE THREAD

**Issue by Davidx01** [nonamecrackers2/crackers-wither-storm-mod#1717]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.16

### Describe the bug

i'm in a server, when the player moves away the wither stops growing and rendering, its not a server capacity issue (2 cores 6gb ram). I'm using arclight 1.20.1 with the following forge version 47.2.16. No plugins

### Steps to Reproduce

1. summon the wither
2. move away
3. you won't see the wither and it'll stop growing

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

only this

**Comment by nonamecrackers2** [comment]
Does it reappear when you get close to it? And when it does disappear, can you still hear the ambient background sound loop it makes?

**Comment by Davidx01** [comment]
When I get close to it, the wither reappears, I'm not sure about the music
in background I'll check after

Il ven 12 gen 2024, 01:21 nonamecrackers2 ***@***.***> ha
scritto:

**Comment by Davidx01** [comment]
no the music stops

**Comment by nonamecrackers2** [comment]
It’s probably unloading then #1462 

I have an idea on what the cause could be, but I’ll have to investigate it further. Thank you for your report though!

**Comment by Davidx01** [comment]
Ok, thanks.

Il lun 15 gen 2024, 18:56 nonamecrackers2 ***@***.***> ha
scritto:
