### ISSUE TITLE
thread render bug pls fix

### ISSUE THREAD

**Issue by antivoid66** [nonamecrackers2/crackers-wither-storm-mod#172]
**1.18.2.0**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
when i try to create a new world it crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/108605668/177288455-60bc570e-9714-4b59-a0ad-fdc3b4a17011.png)

**Comment by antivoid66** [comment]
head something bug

**Comment by watersofnazareth** [comment]
You should upload your crashlog and fill out the bug report details because this doesn't tell Cracker anything at all

**Comment by nonamecrackers2** [comment]
Yes, please send the crash report. I need the entirety of it in order to properly diagnose the issue. Also, please fill in all the details of the bug report template you were given.
