### ISSUE TITLE
[Suggestion]: Wither Storm should exist in peaceful mode

### ISSUE THREAD

**Issue by Cuteplushbros** [nonamecrackers2/crackers-wither-storm-mod#1720]
### Description of feature request

This feature would just be for anyone who doesn't wanna go through the nether with hostile mobs but still wants to defeat the wither storm by turning it off and back on.

**Comment by GrandmaPork** [comment]
You need peaceful mode off to make the bomb..

**Comment by TaintedBlockmObile** [comment]
True. If the ender dragon can't be peaceful'd, the wither storm shouldn't be either

**Comment by TaintedBlockmObile** [comment]
> You need peaceful mode off to make the bomb..

I think he means traveling with peaceful off but only turning it on occasionally

**Comment by Cuteplushbros** [comment]
> > You need peaceful mode off to make the bomb..
> 
> I think he means traveling with peaceful off but only turning it on occasionally

yes thats what i mean

**Comment by sm644me** [comment]
I think this should be a feature just because the Withered Nether Star is a unique item like the Dragon Egg. If the Ender Dragon stays around on Peaceful so the player isn't locked out of End Gateways and the Dragon Egg, then the Wither Storm should ignore Peaceful as well. Maybe make it not target the player on Peaceful or something if needed.

**Comment by Cuteplushbros** [comment]
> I think this should be a feature just because the Withered Nether Star is a unique item like the Dragon Egg. If the Ender Dragon stays around on Peaceful so the player isn't locked out of End Gateways and the Dragon Egg, then the Wither Storm should ignore Peaceful as well. Maybe make it not target the player on Peaceful or something if needed.

Thats exactly what i was thinking

**Comment by GrandmaPork** [comment]
I mean ig but just go through in easy mode or download a mod that allows you to disable certain mobs

**Comment by Cuteplushbros** [comment]
> I mean ig but just go through in easy mode or download a mod that allows you to disable certain mobs

there are mods that do that?

**Comment by GrandmaPork** [comment]
> > I mean ig but just go through in easy mode or download a mod that allows you to disable certain mobs
> 
> there are mods that do that?

https://www.curseforge.com/minecraft/mc-mods/bad-mobs

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
