### ISSUE TITLE
[Bug]: Wither is invisible

### ISSUE THREAD

**Issue by Skellykenz** [nonamecrackers2/crackers-wither-storm-mod#1723]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

The wither storm appears invisible!

### Steps to Reproduce

Download Embeddium and every other performance mod possible
Summon the wither storm
Wait until his later phases
Get far enough from him
He dissapears!

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/140901354/2c8c428d-df3b-4ba3-acc9-98ae0306750c)

### Mod List

[Create : Teleporters! (by Chilllliii)](https://www.curseforge.com/minecraft/mc-mods/create-teleporters)
[Decorative Blocks (Fork) (by TheWinABagel)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks-fork)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Leaky - Farm leak detection[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/leaky)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Create Chromatic Return (by phicctv)](https://www.curseforge.com/minecraft/mc-mods/create-chromaticreturn)
[Konkrete [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete)
[FTB Backups 2 (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2)
[Fresh Animations (by Fresh__LX)](https://www.curseforge.com/minecraft/texture-packs/fresh-animations)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples)
[Rechiseled: Create (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled-create)
[Cracker's Wither Storm Mod (by nonamecrackers2)](https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Enchanting Infuser [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-forge)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Iron Jetpacks (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[FTB Ultimine (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[FTB Teams (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[ItemPhysic Lite (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/itemphysic-lite)
[MrCrayfish's Gun Mod [Unofficial] (by MikhailTapio)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod-unofficial)
[Memory Settings[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/memory-settings)
[Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[Lootr (Forge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[Recipe Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric)
[Asmalda - A British Modern Style BedWars Hub Spawn (by xdorguniverse)](https://www.curseforge.com/minecraft/worlds/asmalda-a-british-modern-style-bedwars-hub-spawn)
[Sleep Time (by noxgame1230)](https://www.curseforge.com/minecraft/mc-mods/sleep-time)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[Elytra Slot (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot)
[YUNG's Menu Tweaks (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-menu-tweaks)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Auudio [Forge] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/auudio-forge)
[Dynamic View[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Tom's Simple Storage Mod (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/toms-storage)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[InsaneLib (by Insane96)](https://www.curseforge.com/minecraft/mc-mods/insanelib)
[Alex's Caves (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-caves)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[TexTrue's Embeddium Options (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/textrues-embeddium-options)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[PolyLib (by Official_CreeperHost)](https://www.curseforge.com/minecraft/mc-mods/polylib)
[Chunk Sending[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)
[Limited Chunkloading - Chunk cleanup[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/limited-chunkloading)
[Universal Bone Meal [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/universal-bone-meal-forge)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Create Ore Excavation (by tom54541)](https://www.curseforge.com/minecraft/mc-mods/create-ore-excavation)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[ParCool! (by alRex_U)](https://www.curseforge.com/minecraft/mc-mods/parcool)
[Spelunkery (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/spelunkery)
[AL's Skeletons Revamped (by ALthegatorMC)](https://www.curseforge.com/minecraft/texture-packs/als-skeletons-revamped)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Repurposed Structures (Neoforge/Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
[The Lost Cities (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-lost-cities)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Lucky's Spelunker's Charm II (by LuckyOwl)](https://www.curseforge.com/minecraft/mc-mods/spelunkers-charm-ii)
[Create: Netherless (by DariusZeBaguette)](https://www.curseforge.com/minecraft/mc-mods/create-netherless)
[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Crafting Tweaks (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Embeddium++ (by SrRapero720)](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus)
[Client Crafting (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/client-crafting)
[YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Boss Refreshed + Fresh Animations (by lukidon)](https://www.curseforge.com/minecraft/texture-packs/boss-refreshed-fresh-animations)
[[EMF] Entity Model Features [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-model-features)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Athena (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/athena)
[[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[Ad Astra (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[Magnum Torch (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge)
[AL's Skeletons Revamped x Fresh Animations (by ALthegatorMC)](https://www.curseforge.com/minecraft/texture-packs/als-skeletons-revamped-x-fresh-animations)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[fix GPU memory leak[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[Marbled's Arsenal [MA] (by MarbledNull)](https://www.curseforge.com/minecraft/mc-mods/marbleds-arsenal)
[Enhanced Boss Bars (by Nakuring)](https://www.curseforge.com/minecraft/texture-packs/enhanced-boss-bars)
[Spice of Life: Carrot Edition (by lordcazsius)](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition)
[Tissou's Zombie Pack (by Tissou)](https://www.curseforge.com/minecraft/texture-packs/tissous-zombie-pack-optifine-1-7x-1-19)
[Rechiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[Tectonic (by Apollo)](https://www.curseforge.com/minecraft/mc-mods/tectonic)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[Magnesium/Rubidium Dynamic Lights (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[Fast Async World Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fast-async-world-save-forge-fabric)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Boss Refreshed (by lukidon)](https://www.curseforge.com/minecraft/texture-packs/boss-refreshed)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[bad packets (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/badpackets)
[FTB Chunks (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Nyf's Spiders (by Nyfaria)](https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders)
[WTHIT Harvestability (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit-harvestability)
[Colds: Easy Paxel (Lite) (FORGE) (by Coldspell_Games)](https://www.curseforge.com/minecraft/mc-mods/colds-easy-paxel-lite)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[No See, No Tick (by Askaban)](https://www.curseforge.com/minecraft/mc-mods/no-see-no-tick)
[Better chunk loading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
['Dustrial Decor (by BlueDuckYT)](https://www.curseforge.com/minecraft/mc-mods/dustrial-decor)
[Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[Wither Skeleton Tweaks (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/wither-skeleton-tweaks)
[Create Slice & Dice (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
[Enhanced AI (by Insane96)](https://www.curseforge.com/minecraft/mc-mods/enhanced-ai)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[WTHIT Forge Edition (by badasintended)](https://www.curseforge.com/minecraft/mc-mods/wthit-forge)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)

**Comment by ghost** [comment]
This is an issue when using Embeddium++, you'll need to turn off max entity distance iirc.

**Comment by nonamecrackers2** [comment]
> This is an issue when using Embeddium++, you'll need to turn off max entity distance iirc.

Try that. It’s referenced [here](https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Known-Compatibility-Issues)
