### ISSUE TITLE
[Suggestion]: New Potions

### ISSUE THREAD

**Issue by Rrylcrafter** [nonamecrackers2/crackers-wither-storm-mod#1724]
### Description of feature request

_I'd like to propose an idea for two new potions. A potion that will speed up the evolution process wither storm, and a potion of withering disease._

**Let's start with the potion to accelerate evolution wither storm:**
It will be created using an acceleration potion and... a wither skull, for example? Honestly, I don’t know how it can be created. But I know its use. Oddly enough, it will accelerate the evolution of wither storm. It can also be loaded into a crossbow, or pulled onto a bow to shoot wither storm from afar. The potion can be made in a minute, or with gunpowder for eight minutes (in general, it can be made like regular potions. I don’t remember their minimum and maximum time).
The potion is suitable for those who want to first develop, and then call wither storm.

**The following is a potion of withering ailment:**
It will be made from a poison potion and a block of dried flesh. Just like the potion of accelerating evolution wither storm, it can be pulled onto a bow or loaded into a crossbow. After the potion hits a mob/player, it begins to become infected with a withering disease.
This potion is suitable for those who want to prank friends or complete an achievement without calling wither storm again.

_That's all. If I wrote anything through a translator, please forgive me for any mistakes. Bye!_

**Comment by nonamecrackers2** [comment]
Wither potions already exist in the mod. Adding capability for them to pulled and shot using a crossbow is not in my agenda currently, but it is an interesting idea. If you’re not talking about wither potions but instead of wither sickness potions (which is probably due to the translation), those have already been suggested and denied.

While the option to accelerate the Wither Storm’s evolution is interesting, we have other plans to add items that will do the same thing, so I do not see the necessity.

Thank you for your suggestions however!

**Comment by TaintedBlock** [comment]
> Wither potions already exist in the mod. Adding capability for them to pulled and shot using a crossbow is not in my agenda currently, but it is an interesting idea. If you’re not talking about wither potions but instead of wither sickness potions (which is probably due to the translation), those have already been suggested and denied.
> 
> While the option to accelerate the Wither Storm’s evolution is interesting, we have other plans to add items that will do the same thing, so I do not se the necessity.
> 
> Thank you for your suggestions however!

spelling mistake!!!111

**Comment by Pandaboi25x** [comment]
> Wither potions already exist in the mod. Adding capability for them to pulled and shot using a crossbow is not in my agenda currently, but it is an interesting idea. If you’re not talking about wither potions but instead of wither sickness potions (which is probably due to the translation), those have already been suggested and denied.
> 
> While the option to accelerate the Wither Storm’s evolution is interesting, we have other plans to add items that will do the same thing, so I do not se the necessity.
> 
> Thank you for your suggestions however!

se
