### ISSUE TITLE
[Suggestion]: Wither Storm drops cluster when it dies in phases 4-5.5 as well

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1726]
### Description of feature request

The only thing that should be said is that depending on the phase, it lowers the amount of clusters that fall. So like phase 4 would be like 3-4 and something like phase 5.25 would be like 5-6. And 5.5 would be the same as 7.5 (Or a little lower I guess)

**Comment by juanelgamer456** [comment]
would not this also work as an infinite tainted blocks farm?

**Comment by TaintedBlockmObile** [comment]
> would not this also work as an infinite tainted blocks farm?

Eh. Maybe. But this is also so it keeps wither storm deaths consistent since only phase 6+ drops clusters

**Comment by nonamecrackers2** [comment]
I’ve disabled cluster drops in those phases since the Wither Storm is too small for it to make sense, and having small clusters would be too awkward imo. Thank you for your suggestion though.
