### ISSUE TITLE
[1.18.2]f-bomb light effects not working

### ISSUE THREAD

**Issue by aa3214** [nonamecrackers2/crackers-wither-storm-mod#173]
**Minecraft version** 
1.18.2

**Mod version**
2.0.1

**Describe the bug**
when you active the f-bomb, the other colorthings during the countdown doenst appear, only the white screen at the end

**To Reproduce**
1. pick a f-bomb
2. pick a flint and steel
3. use it on the f-bomb
4. during the activation it doenst have that "pulse" idk what is it called.

**Crash Reports / Logs**
i didnt found any crash report

**Screenshots**

![2022-07-05_14 09 40](https://user-images.githubusercontent.com/108589914/177372594-8e50ebb8-c4d4-4eec-bb90-3aac1b52c746.png)

![2022-07-05_14 09 14](https://user-images.githubusercontent.com/108589914/177372834-bdb03e01-2bbd-4f6c-becd-13b5b6d0b368.png)

 (should it work like this, like in your video?)
![image](https://user-images.githubusercontent.com/108589914/177384404-5507a3d8-ade5-4aa7-9075-c316d769abd2.png)

**Comment by aa3214** [comment]
When i try to explode the f-bomb, it doenst have the light effects before it explodes

**Comment by aa3214** [comment]
only the white effect appears at the end

**Comment by nonamecrackers2** [comment]
Please fill in the bug report template you were given

**Comment by aa3214** [comment]
> Please fill in the bug report template you were given

I finished, could you check please?

**Comment by nonamecrackers2** [comment]
Do you have optifine installed, and if so, is the fabulous graphics setting enabled?

**Comment by aa3214** [comment]
> Do you have optifine installed, and if so, is the fabulous graphics setting enabled?

yes, they are

**Comment by aa3214** [comment]
sorry for taking so long to answer you, and sorry for taking your time, I didn't want to bother you or anything, just to know what's going on with the f-bomb

**Comment by nonamecrackers2** [comment]
It's all good. Try disabling the fabulous graphics setting and see if that fixes it.

**Comment by aa3214** [comment]
> It's all good. Try disabling the fabulous graphics setting and see if that fixes it.

still not working :(

**Comment by nonamecrackers2** [comment]
Do you have any shaders enabled (even the "Internal" optifine ones?)

**Comment by aa3214** [comment]
Yes,I've tried with it on and off and it still doesn't work..

**Comment by nonamecrackers2** [comment]
Even with f1 disabled it still doesn't show? In the pictures provided it seems like you have f1 enabled

**Comment by aa3214** [comment]
i've been trying this for a long time, you have no idea..  I've tried everything, literally.. I even tried to redowload the mod but it's still the same, i'll send another screenshot, and can i suggest something here? or i need to open a new issue?

**Comment by aa3214** [comment]
![image](https://user-images.githubusercontent.com/108589914/178079695-94c4c7f9-d872-4738-ad5d-dcaa87310bb0.png)

**Comment by aa3214** [comment]
![2022-07-08_19 54 16](https://user-images.githubusercontent.com/108589914/178079727-70ce3259-159c-4e39-8878-000fbedffcae.png)

**Comment by aa3214** [comment]
I'm from another country..if it gets in the way I can change the language to English to make it easier for you to understand

**Comment by nonamecrackers2** [comment]
No it's all good. I'll have to take a look to see if I can reproduce this issue. Thanks for your cooperation!

**Comment by aa3214** [comment]
> No it's all good. I'll have to take a look to see if I can reproduce this issue. Thanks for your cooperation!

np

**Comment by nonamecrackers2** [comment]
Yeah I can't reproduce. I'm lost on what could be the cause. Do you have any other mods installed?
