### ISSUE TITLE
[Suggestion]: Ability to customize the Wither Storm depending on its phase

### ISSUE THREAD

**Issue by TaintedBlockmObile** [nonamecrackers2/crackers-wither-storm-mod#1730]
### Description of feature request

Title kinda explains itself but, to further explain, there should be a way to change how the wither storm looks depending on its phase. For example, something like the texture of the mass or teeth or eyes. Or maybe be able to change the color of the night glare depending on the phase?

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
