### ISSUE TITLE
[Suggestion]: Config or Gamerule to remove Config limits

### ISSUE THREAD

**Issue by ThatB0i** [nonamecrackers2/crackers-wither-storm-mod#1733]
### Description of feature request

What if instead of config being stuck with limits, instead, we could have a config or gamerule that disables the config limits? 

It can have a warning about how it could be unstable under it. If I'm messing around with the mod in creative I would not care if it corrupts my save, so it wouldn't be necessary to have a limit.

A warning can also stop new players from crashing their game by accident when using this. Could also be a gamerule instead since most of the config is in the world config.

_If this a duplicate please let me know, ill close this suggestion if so._

**Comment by GearsawStudios** [comment]
Some configs really don't need minimums or maximums or at least different ones for the most part.
WS speed could easily go to 0
Turn speed could be even higher, perhaps even lock on completely
Block cluster interval could be longer or potentially disabled

**Comment by Aimyx** [comment]
Or shorten block cluster interval :trollws:

**Comment by TaintedBlockmObile** [comment]
I think pandaboi made a similar suggest to this and it got denied

**Comment by Pandaboi25x** [comment]
> I think pandaboi made a similar suggest to this and it got denied

I didnt suggest that??

**Comment by BluePineappleGuy** [comment]
Petition to make it under the tab "Config^2"

**Comment by nonamecrackers2** [comment]
A config option to remove limits would not be possible with how the Forge config system works. Limits are in place so unintended behavior is avoided and you don't corrupt things. If you'd like certain config values to have their limits expanded, I could definitely considering doing that in another suggestion issue.
