### ISSUE TITLE
Better Formidibomb Explosion

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1734]
### Description of feature request

When the formidibomb explodes, it should blast pieces of the Wither Storm in the distance. When the Wither Storm rises again, it should have a smaller back due to the explosion.

**Comment by GearsawStudios** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/836

**Comment by nonamecrackers2** [comment]
This would require model changes which are against the guidelines
