### ISSUE TITLE
Head Amount Customization

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1735]
### Description of feature request

In the config, there could be something where you can customize the amount of heads the wither storm has at each phase.

**Comment by BluePineappleGuy** [comment]
wouldn't that be pretty difficult to do since you'd have to specify where the extra heads would go

**Comment by TaintedBlockk** [comment]
This would probably be better to be left as something you can do with datapacks

**Comment by WitherBean** [comment]
> This would probably be better to be left as something you can do with datapacks

You cannot do this with datapacks. If you could, I would have done it with BWSB.

**Comment by TaintedBlockmObile** [comment]
> > This would probably be better to be left as something you can do with datapacks
> 
> You cannot do this with datapacks. If you could, I would have done it with BWSB.

Sm644me did it. I can't spoil where and when he did it. But I saw it for myself. It was really cool actually

**Comment by WitherBean** [comment]
> > > This would probably be better to be left as something you can do with datapacks
> > 
> > 
> > You cannot do this with datapacks. If you could, I would have done it with BWSB.
> 
> Sm644me did it. I can't spoil where and when he did it. But I saw it for myself. It was really cool actually

I think I know exactly what he did.

**Comment by Herobrine982950291** [comment]
> > This would probably be better to be left as something you can do with datapacks
> 
> You cannot do this with datapacks. If you could, I would have done it with BWSB.

BWSB is broken

**Comment by WitherBean** [comment]
> > > This would probably be better to be left as something you can do with datapacks
> > 
> > 
> > You cannot do this with datapacks. If you could, I would have done it with BWSB.
> 
> BWSB is broken

Which part? When I use it, it is not. Maybe you set it up wrong?

**Comment by nonamecrackers2** [comment]
Unfortunately I made the amount of heads extremely hard coded, and expanding/decreasing the amount is not something I want to go through the trouble to implement.

**Comment by Herobrine982950291** [comment]
> > > > This would probably be better to be left as something you can do with datapacks
> > > 
> > > 
> > > You cannot do this with datapacks. If you could, I would have done it with BWSB.
> > 
> > 
> > BWSB is broken
> 
> Which part? When I use it, it is not. Maybe you set it up wrong?

i install it, yet Bowels havent changed 1 bit... or anything!

**Comment by WitherBean** [comment]
> > > > > This would probably be better to be left as something you can do with datapacks
> > > > 
> > > > 
> > > > You cannot do this with datapacks. If you could, I would have done it with BWSB.
> > > 
> > > 
> > > BWSB is broken
> > 
> > 
> > Which part? When I use it, it is not. Maybe you set it up wrong?
> 
> i install it, yet Bowels havent changed 1 bit... or anything!

It is not installed correctly then. You should put this in the issues tab for BWSB.
