### ISSUE TITLE
[Suggestion]: Wither Storm's reaction to the light

### ISSUE THREAD

**Issue by Rrylcrafter** [nonamecrackers2/crackers-wither-storm-mod#1737]
### Description of feature request

_I would like to suggest that Wither Storm react to light (at night). But only for torches, all types of lanterns (blocks and incomplete blocks), and other luminous BLOCKS.
Only lava should not be on the list of where Wither Storm can fly. With this function it will be possible to lure Wither Storm somewhere. 
Well, or it will just be an interesting innovation._

I wrote through a translator. Bye

**Comment by nonamecrackers2** [comment]
I don't understand why light would be an issue for it, why it would want to avoid it, and/or why it would react to it. Especially considering if it's a single light source which wouldn't be bothersome for such a humungous creature. Interesting idea though.
