### ISSUE TITLE
[Bug]: unable to launch the game

### ISSUE THREAD

**Issue by FulsomeFrog8789** [nonamecrackers2/crackers-wither-storm-mod#1738]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

Forge - 47.2.0

### Describe the bug

so Ive been trying to launch crackers witherstorm mod and every time I try to launch the game I get exit code 1. I downloaded the mod by installing it into curseforge which I think has the right version of forge to play it (47.2.0) but every time I try to run the game it just doesn't work.

### Steps to Reproduce

1. install the latest version of crackers witherstorm mod into cruseforge
2. try to run the game

### Crash Reports/Logs

[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/13999045/latest.log)
1

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![pain](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/72046482/7d547739-4c4b-462a-b362-6f769bb0d6a8)

### Mod List

none

**Comment by Bloxxify2827** [comment]
We can’t help you with this amount of info, please send over your latest.log file.

**Comment by FulsomeFrog8789** [comment]
> We can’t help you with this amount of info, please send over your latest.log file.
you mean this right? or is it something else
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/13999045/latest.log)

**Comment by nonamecrackers2** [comment]
Try updating your graphics drivers

**Comment by watersofnazareth** [comment]
Closing this as we never got a response
