### ISSUE TITLE
[Suggestion]: Wither Storm corrupting the terrain (world)

### ISSUE THREAD

**Issue by MarcoTulioFonsecaAlves** [nonamecrackers2/crackers-wither-storm-mod#1739]
### Description of feature request

Developers, hello, I came here to talk about a crazy idea and I wanted to know what you think about the Wither Storm mod. My idea is, since the Wither can corrupt all monsters or animals (well, the minority) would it be an interesting idea to have the Wither corrupt the world around it like a corruption or a sculk corruption for example? It's just an idea but it would be very impressive for the Wither to corrupt everything it comes close to, not just destroy it.

**Comment by GearsawStudios** [comment]
Seems very, very out of scope for the mod.

**Comment by BluePineappleGuy** [comment]
this has been suggested i think

**Comment by nonamecrackers2** [comment]
#1664
