### ISSUE TITLE
(Suggestion) A Beacon using the Withered Nether Star

### ISSUE THREAD

**Issue by Swagboi7** [nonamecrackers2/crackers-wither-storm-mod#174]
This suggestion is, quite simply, give the Withered Nether Star a use by giving it its own Beacon. What it does, you decide. Either that, or give it some interaction with the vanilla beacon like what happened in this scene in Episode 4.
![3538223C-8C46-4B8B-836C-28A14A5DC6EE](https://user-images.githubusercontent.com/106929218/177452982-f9d944cb-e50b-485d-9635-9d546582bb22.png)

**Comment by watersofnazareth** [comment]
#3

**Comment by nonamecrackers2** [comment]
This has already been suggested and will be implemented eventually #3
