### ISSUE TITLE
Delete this Issue, please

### ISSUE THREAD

**Issue by MarcoTulioFonsecaAlves** [nonamecrackers2/crackers-wither-storm-mod#1740]
It could be, but it would be something much more immersive or challenging for the mod, since it is very easy to avoid the Storm just by staying underground, I know that at one time or another a corrupted monster appears but it is very rare sometimes.

**Comment by GearsawStudios** [comment]
Why did you make another post using my comment as the title?

**Comment by MarcoTulioFonsecaAlves** [comment]
I did what I shouldn't have done, I don't even know how to delete it anymore :(

**Comment by TaintedBlockk** [comment]
just close the issue
