### ISSUE TITLE
[Suggestion]: Tentacles' movements and sizes must improve.

### ISSUE THREAD

**Issue by HzErsin** [nonamecrackers2/crackers-wither-storm-mod#1743]
### Description of feature request

The tenctacles are so small and look so unrealistic after phase 4. It needs 2  "bigger" tentacles and smaller tentacles for its down body. Also their movements are so unrealistic that it looks like an octopus trying to go down in ocean.

**Comment by Aimyx** [comment]
R e a d   t h e   G u i d e l i n e s.

**Comment by TaintedBlockmObile** [comment]
I hope you didn't just call tentacles on a _Wither Storm_ unrealistic 💀 The irony is absurd

**Comment by juanelgamer456** [comment]
"must improve" bro is not suggesting, bro is demanding this 💀😭😭

**Comment by juanelgamer456** [comment]
> I hope you didn't just call tentacles on a _Wither Storm_ unrealistic 💀 The irony is absurd

also fr, bro is calling the tentacles from an eldritch abomination result of merging an ancient spirit with a machine able to distort reality "unrealistic"

**Comment by Nov1st2k10** [comment]
if you don't like it
_make your own wither storm mod_

**Comment by nonamecrackers2** [comment]
Please read the guidelines
