### ISSUE TITLE
[Suggestion]: Block state influenced by cave shake thing

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1744]
### Description of feature request

Blocks nearby the player may update (similar to placing a block next to it.)
It may also toggle or trigger certain redstone components such as levers, buttons, or pressure plates, maybe even break tripwire.

This would be configurated to off by default, and it would be a chance to happen, not guaranteed.

**Comment by ghost** [comment]
My only concern with this suggestion is "Would it take a massive hit on performance?"

**Comment by nonamecrackers2** [comment]
Performance would probably be fine, but this may royally screw with existing contraptions in unintended ways. Interesting idea though.

**Comment by BluePineappleGuy** [comment]
considering the cave rumbles mess with redstone now (which is part of the suggestion) should this be marked as completed?

**Comment by nonamecrackers2** [comment]
Oh yeah I guess, good catch
