### ISSUE TITLE
[Bug]: Render Crash 1.18.2

### ISSUE THREAD

**Issue by MatthewFMMS** [nonamecrackers2/crackers-wither-storm-mod#1745]
### Minecraft Version

1.18.2

### Mod Version

2.2.1

### Mod Loader

Forge

### Mod Loader Version

40.2.9

### Describe the bug

The game crashes when I enter a specific area in my world. It'll continue crashing until I get away from the area.
I killed a Wither Storm with a Gorgon head from Ice and Fire. I then spawned another Wither Storm. 

I recreated this condition in another world and could not recreate the crash. The stone statue did get stuck inside the Wither Storm after getting sucked up in the test world.

### Steps to Reproduce

I wasn't able to recreate the crash in another world.

### Crash Reports/Logs

https://mclo.gs/Db51z7l

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

https://www.curseforge.com/minecraft/modpacks/antistorm

**Comment by nonamecrackers2** [comment]
Looks like a problem with Ice and Fire. Considering that 1.18.2 is no longer supported and this appears to be a problem on their end, I'll be closing this issue.
