### ISSUE TITLE
[Bug]: The Biome Title for the Bowels is displayed incorrectly on Xaero's World Map/ Mini Map

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1746]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.19

### Describe the bug

What the title says, when going into the Bowels and Xaero's Minimap/World Map is installed with the Biome Info turned on, the title for the Bowels is not properly displayed.

### Steps to Reproduce

Set the settings on Xaero's Minimap to show the biome the person's in the Information Display settings
Then go to the Bowels.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![javaw_1Cus0M1rr8](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/148708399/8caeb765-e155-4930-af59-dd31c0cfca7a)

### Mod List

additional_enchantments-1.20.1-0.3.5-all
do_a_barrel_roll-forge-3.5.0+1.20.1
EasyAnvils-v8.0.1-1.20.1-Forge
EasyMagic-v8.0.1-1.20.1-Forge
embeddium-0.2.18+mc1.20.1
embeddiumplus-1.20.1-v1.2.3-build
EnchantingInfuser-v8.0.2-1.20.1-Forge
oculus-mc1.20.1-1.6.13
PuzzlesLib-v8.1.14-1.20.1-Forge
textrues_embeddium_options-0.1.3+mc1.20.1
UniversalEnchants-v8.0.0-1.20.1-Forge
witherstormmod-1.20.1-4.0.1.1
Xaeros_Minimap_23.9.3_Forge_1.20
XaerosWorldMap_1.37.2_Forge_1.20

**Comment by nonamecrackers2** [comment]
Ah I probably forgot to add an entry into the mods lang file for the bowels

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
