### ISSUE TITLE
[Suggestion]: Progressive Boss Music 

### ISSUE THREAD

**Issue by MrRyanLion50** [nonamecrackers2/crackers-wither-storm-mod#1747]
### Description of feature request

I think that it would be really cool if there is an option in the music section called “Progressive Music” where certain portions of the boss theme would play depending on both the phase and the distance of the wither storm.

**Comment by TaintedBlockmObile** [comment]
This would be cool. This is also doable with datapacks btw

**Comment by MrRyanLion50** [comment]
> This would be cool. This is also doable with datapacks btw

Do you know if there are any datapacks out there that do that or not yet.

**Comment by Aimyx** [comment]
This has been suggested already right?

**Comment by nonamecrackers2** [comment]
This kind of already exists in the mod, and has been suggested before: #227
