### ISSUE TITLE
[Bug]: Runaway Attempts Till Chase description is incorrect.

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1748]
### Minecraft Version

1.19.4

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

Not needed for this issue

### Describe the bug

A bug happened!

Incorrect statement about how runaways work. It states that 5 runaways must be met to chase. Upon further inspection with /data, it starts a chase when it reaches 6 and resets the counter from there. The description states that said chase will happen at 5 runaways, not 6.

### Steps to Reproduce

See: Ultimate Target Logic § Runaway Attempts

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/122060314/673762c2-5e1c-4e81-9410-6aacd348611c)

### Mod List

Explorer's Eve modpack, said error is a typo and unlikely to be caused by other mods.

**Comment by Pandaboi25x** [comment]
4.0.1.1 is crazy,

**Comment by nonamecrackers2** [comment]
Probably something I messed up using greater than or greater than and equal to

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update. The Wither storm will now chase when ultimate target attempts have been met instead of exceeded.
