### ISSUE TITLE
Mass Separation - New Attacks - Elixir

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#175]
Was thinking when it reaches a certain point in mass, it can break off a chunk and be another floating head doing what the other single headed ones do but infinitely or a lot of them.  Another could be at phase 7 or 8, one or all of the heads can unlock another attack like a laser beam that strikes down like Ghidorah or have the skulls that it shoots be beefier per phase. I feel like the bigger it gets, the stronger it should become. 
The elixir can be the one from story mode of course but have to go to the end cities and nether to make it that way it can be a rare special potion. I was thinking the resources needed could be chorus fruit, blaze powder, and a spider eye so it can be brewed.

**Comment by watersofnazareth** [comment]
The elixir has already been said that it's not going to be added, there would be no point in it, also with it breaking off that'd cause a lot of lag over time, the lasers don't seem like a good idea but the beefier skulls could be with the last phases, the mod is supposed to be accurate partially to MCSM but playable and stylized like vanilla Minecraft

**Comment by nonamecrackers2** [comment]
I don't quite understand the breaking off thing, probably just your wording, and the laser idea doesn't really fit with the mod in my opinion. The elixir was already suggested and isn't going to be added (#65)
