### ISSUE TITLE
[Bug]: Certain bonuses from apotheosis/attributeslib break Command Block battle

### ISSUE THREAD

**Issue by NightmareRise** [nonamecrackers2/crackers-wither-storm-mod#1750]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.20

### Describe the bug

During the Command Block fight, it seems like any command block sword given attributes from attributeslib, a library mod most commonly known for its use on Apotheosis affix items, with break the standard flow of the fight. 

The initial hit on the Command Block will progress the health bar two full stages worth of damage. The second hit will kill it but sometimes you may still need to finish the fight "normally" by killing the symbiont and heads and hitting the block two more times, despite the block technically being dead and the music not playing.

When first discovered, I thought it was due to protection pierce/armor pierce (these do seem to break it in the same way if added to the player directly though). This seems to only occur while using swords for some reason. I'll continue testing this myself and update with any new info.

EDIT 2/6/24: I've compiled a list of what I think are all of the problematic attributes:
Cold damage
Fire damage
Current HP damage
Protection pierce
Armor pierce

### Steps to Reproduce

Download CWSM + apotheosis and its dependencies.

Give yourself a command block sword and enter the bowels

Use "/apoth lootify apotheosis:epic" while holding the command block sword in your hand to give it affixes

Strike the command block. Its health should go down by half instead of quarters. If it doesn't reroll the affixes and try again.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Apotheosis 7.2.2
Apothic Attributes 1.2.1
Placebo 8.6.0
Patchouli 84
Cracker's Wither Storm Mod 4.0.1.1

**Comment by NightmareRise** [comment]
Did testing again. Current HP% Also breaks it in unintended ways, though I pretty much expected that to be the case. I believe it's ANY damage modifier.

**Comment by NightmareRise** [comment]
Accidentally closed, oops.

Current HP% breaks it too which I expected. I think any damage modifiers do.
I noticed that bosses from the Cataclysm mod can somehow ignore these attribute effects and maintain whatever protection they have coded into their bosses (besides current hp%) but I'm not sure how

**Comment by nonamecrackers2** [comment]
Found the issue, should be fixed in the next major release
