### ISSUE TITLE
[Suggestion]: Tainted_dust_circuit color config , like tractor beam or something

### ISSUE THREAD

**Issue by Composer-Hu** [nonamecrackers2/crackers-wither-storm-mod#1751]
### Description of feature request

Modify the tainted_dust.png will not change the color of the circuit after it is placed, and particles coming out of the circuit. So I hope something to change its actual color. Thanks.

**Comment by nonamecrackers2** [comment]
You should be able to change the model JSON file to change the color. Overriding the color with the color config isn't entirely feasible.

**Comment by Composer-Hu** [comment]
> You should be able to change the model JSON file to change the color. Overriding the color with the color config isn't entirely feasible.

Got it. I'll try
