### ISSUE TITLE
[Suggestion]: Phase 4 Configurable sky, fog and other colors

### ISSUE THREAD

**Issue by Composer-Hu** [nonamecrackers2/crackers-wither-storm-mod#1753]
### Description of feature request

Just add one more phase of color configuration, just like the subsequent phase that already exist, this atmosphere will work better. Thanks.

**Comment by WitherBean** [comment]
This sounds like a pretty good idea!

**Comment by TaintedBlockmObile** [comment]
It doesn't really have fog tho. It's just the normal wither fog

**Comment by nonamecrackers2** [comment]
Phase 4 does not darken the sky and I do not believe it should.

**Comment by BluePineappleGuy** [comment]
> Phase 4 does not darken the sky and I do not believe it should.

i mean, it would be cool to do with resource packs/config (i like messing around with configs)
