### ISSUE TITLE
[Suggestion]: Add an option to remove the config from the main options screen.

### ISSUE THREAD

**Issue by Billnotic** [nonamecrackers2/crackers-wither-storm-mod#1756]
### Description of feature request

I'm including this in a modpack I'm going to run with friends. You don't spawn at 0,0 in the pack, and I'd like discovering the storm to be a surprise. Distant Horizons has a main option config that you can disable, I sincerely hope this mod adds that as well.

**Comment by Herobrine982950291** [comment]
wait- how will we get to the config if the button is disabled?- oh... go to the config via mod menu...

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release. When it does release, you'll have to go to your mods list, search for "CrackersLib", open the config for that mod, client, then add "witherstormmod" to the config menu button blacklist.

**Comment by Herobrine982950291** [comment]
The Mini update? you mean the update coming on 30 april?
