### ISSUE TITLE
[Suggestion]: A bot that auto rejects suggestions and bugs based on violating guidelines for the GitHub.

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1758]
### Ok, this isn't strictly about the mod, but hear me out. And yes, I'm doing this on the issue tracker, because I want more opinions on this and the #cwsm channel still doesn't give image permissions yet.

I can imagine it is annoying to open your GitHub notifications to find yet another suggestion that ask for more subphases or tenacles changes.

So instead of having to manually delete those invalid suggestions, you can have a bot that automatically deletes issues based on keywords like "tenacle" or "subphase" in the main post.

That way, it filters out the junk and let's you focus on any new suggestions for the mod.

And if you're unable to code a bot that can do something that, I'd be willing to take a crack at coding a bot that can filter out suggestions and bugs.

**Comment by NinjaSam5399** [comment]
Don't post it here.

**Comment by TaintedBlockmObile** [comment]
This is quite interesting. Idk if this is the right place to post though

**Comment by nonamecrackers2** [comment]
Interesting idea but there may be issues with it, like closing issues that aren't actually duplicates (someone could've mentioned the tentacles but not actually suggesting model changes for them). Also this would probably be more appropriate for the discussions page.

**Comment by BluePineappleGuy** [comment]
Yeah i can see this getting pretty annoying very quick
