### ISSUE TITLE
[Bug]: When using Distant horizon mod, the Wither Storm is visible EVEN BEHIND blocks when far away...

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1759]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.4

### Describe the bug

When I travel until the wither storm is in the distance, it renders behind blocks

### Steps to Reproduce

1. Install Distant Horizons
2. Summon WS any stage
3. go far away behind a mountain or wall

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-02-02_13 12 11](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/c52f3ffe-b6aa-4aa1-8a38-78ba8ac2a4d0)

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/0c98e955-d700-41e2-8870-3672b39389b3)

**Comment by Herobrine982950291** [comment]
and no the storm is not in front of the hill

**Comment by TaintedBlockmObile** [comment]
This has been a known bug for a while. I believe it is unfixable on cracker's end

**Comment by Herobrine982950291** [comment]
really? IG i will just report this issue on their github/discord

**Comment by Bloxxify2827** [comment]
I already did, they disregarded it

**Comment by Herobrine982950291** [comment]
boi

**Comment by nonamecrackers2** [comment]
Yeah this is a known issue and is unfixable at this moment in time.
