### ISSUE TITLE
When Something that can really damage the wither storm in phase 2 it will cover up the command block faster 

### ISSUE THREAD

**Issue by Python17900** [nonamecrackers2/crackers-wither-storm-mod#176]
When you hold up the elixir or something powerful that can destroy it the wither storm in phase 2 will cover the command block faster seeing your trying to destroy it
![image](https://user-images.githubusercontent.com/106478826/177454334-f8737e53-9b65-431f-ba32-ece2803ba70c.png)

**Comment by nonamecrackers2** [comment]
I don't think this feature would be very noticeable, and players in survival starting out with nothing won't even have something that could "damage" the WS.
