### ISSUE TITLE
[Suggestion]: Wiggly tentacles 

### ISSUE THREAD

**Issue by donutlord12** [nonamecrackers2/crackers-wither-storm-mod#1761]
### Description of feature request

Make tentacles wiggly to be more accurate to the game
![fmc4wqtxrl971](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/158791751/446fbf0a-d489-400b-9d64-25468525b971)

**Comment by GearsawStudios** [comment]
Please read suggestion guidelines before posting.

**Comment by TaintedBlockk** [comment]
damn gearsaw you beat me to it

**Comment by Composer-Hu** [comment]
Cracker must have been thinking when he saw this ：No, not again!!!!!!!!!!

**Comment by Gubberball** [comment]
Tentacles are wiggly enough anyways

**Comment by BluePineappleGuy** [comment]
> Tentacles are wiggly enough anyways

disagree, they just slowly wave around. storm don't look eldritch enough to me

**Comment by Gubberball** [comment]
> > Tentacles are wiggly enough anyways
> 
> disagree, they just slowly wave around. storm don't look eldritch enough to me

Besides, the tentacle-related feature requests are driving cracker insane

**Comment by nonamecrackers2** [comment]
As Gearsaw stated,

> Please read suggestion guidelines before posting.
