### ISSUE TITLE
[Suggestion]: Add a check box for suggestions that verifies that the person has read the guidelines

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1762]
### Description of feature request

Similar to how bug reports demand the player answer about Optifine, the same should be done for suggestions. A little checkbox that asks if it's about tentacles, making it more accurate to story mode or the other most commonly suggested things is all that's needed.

✔️ I can verify that I have read the suggestion guidelines (linked here) and this is not about making tentacles attack or more accurate, adding more phases or drastic model changes.

**Comment by ghost** [comment]
You know, this is a much better idea than I had for filtering out suggestions.

**Comment by nonamecrackers2** [comment]
Done
