### ISSUE TITLE
[Suggestion]: to wither storm add the library Lodestone that adds cool shaders and stuff so you can make formida bomb cooler

### ISSUE THREAD

**Issue by respear** [nonamecrackers2/crackers-wither-storm-mod#1764]
### Description of feature request

its very very cool and you can make cool explosions with it or something idk
https://www.curseforge.com/minecraft/mc-mods/lodestone

**Comment by GearsawStudios** [comment]
Grammar has left the chat.

**Comment by respear** [comment]
whar

**Comment by nonamecrackers2** [comment]
Looks cool but I'm not currently looking to enhance the graphics in that way currently

**Comment by BluePineappleGuy** [comment]
honestly this would expand the storms influence a lot, like it doesn't just eat the blocks in-game it eats my CPU and RAM now
