### ISSUE TITLE
[Suggestion]: Change the [Chase on Phase Change] setting to be off be default

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1765]
### Description of feature request

To a newcomer, understanding the Wither Storm's AI can be quite confusing. Figuring out how to not make it chase, when to run, etc is a ton to handle all at once. However, it's much worse when accounting for the chase on phase change. While the phase 4 chase is justified as the player's first challenge, there isn't anything to gain from leaving it enabled besides inflating the amount of chases when the player is likely to trigger them at one point or another. It mainly contributes to the general playstyle of hiding in the nether the whole time, which is something the mod would be better off trying to avoid. Assuming that phase 4-5.5 takes two hours and at minimum it takes 13 minutes to waste all the runaway attempts, the player is likely going to face a chase or two if playing normally. It'd be quite painful to escape from a 4.5 chase, barely survive, only to be met with a phase 5 chase a few minutes after the distraction ends.

**Comment by TaintedBlockmObile** [comment]
I'm gonna disagree on this one. Taking away what makes it dangerous is not a good move imo. That is why the config TO turn it off exist. You're supposed to learn the AI as you play. Not make it easy your whole run through.

**Comment by Herobrine982950291** [comment]
@TaintedBlockmObile Exactly. I would not do this if I had a mod like this! (sadly i dont)

**Comment by LegendaryGodzilla** [comment]
Yeah I don't like this idea

**Comment by BluePineappleGuy** [comment]
I agree that it may be difficult to understand what the storm is doing, but i don't think nerfing it is a good idea. We're talking about something that can end the world by existing, so i think it should be harder, not easier. Maybe some sort of official guide to its AI and how to counteract it could be there (probably in the survival guide linked on the mod page)

**Comment by Luke7381** [comment]
The wither storm is supposed to be a constant, world-ending threat. I don't think nerfing it by default is a good idea.

**Comment by nonamecrackers2** [comment]
The mod's been balanced around that feature being enabled by default. I could see how it may be difficult for a new player to grasp but I don't feel it needs to be disabled by default. I may contemplate doing a playthrough with the chases on phase changed disabled to see what I think of it but for now I'll close this issue. Thanks for your suggestion as always however.
