### ISSUE TITLE
[Suggestion]: Allow the structure to spawn in the Lost Cities

### ISSUE THREAD

**Issue by NighthowlerStudios** [nonamecrackers2/crackers-wither-storm-mod#1766]
### Description of feature request

I would really appreciate some support either on a datapack level or config level (datapacking for 1.16.5 doesn't work since structures cannot have their spawns specified in that version) that **allows the mod to generate the summoning house structure specifically in the Lost Cities dimension**, instead of in the Overworld.  This would help enforce progression in my modpack.

If this isn't done here I wouldn't mind making a patch for it myself or via a mod.  **Probably for 1.16, probably for all the newer versions, best case scenario all of the above**, I have no entire clue yet it depends on how complex implementation would be.

It shouldn't be too hard to implement, only a few lines of code really.

**Comment by TaintedBlockmObile** [comment]
Isn't this a thing already? There is already a modpack that has the rundown houses spawn in different dimensions 
Edit: nvm I read the other part of this. Strange. But crackers isn't supporting older versions sadly

**Comment by NighthowlerStudios** [comment]
> There is already a modpack that has the rundown houses spawn in different dimensions

Yeah I'm aware you already reread what I posted, but 1.16 is silly like that.  It would also be nice to have this in a config option instead of just using that datapack, really, for ease of use.

That being said, the Lost Cities dimension is an exact copy of the Overworld generator inside and out, with a different seed and a chunk replacer that puts the cities in.  So gameplay wise, it wouldn't affect the way Wither Storm generates its structure.

I could patch it in in a commit, if the developer is willing on releasing an update with my PR if it happens.

Or I could just suck it up and learn mixin to make a patch mod specifically for 1.16.5 myself.

**Comment by watersofnazareth** [comment]
1.16 isn't receiving support anymore and doesn't really have the best support for anything including datapacks, you can try making your own patch but with how drastically different the version 1.16.5 of the mod is compared to 1.18 onwards there's no real reason for us to go back and make this change since it's much more difficult to work with in all regards, for now I'm going to close this issue, apologies for any inconvenience

**Comment by NighthowlerStudios** [comment]
The patch mod for this change is ready to be published to CurseForge, and we were wondering, since your mod's code is ARR (we mixin a method, nothing more, though this does mean we use attribute names)...

though you did give us permission to make a patch mod, we wanted to make sure if you wanted ownership of the Curse points for this project.  Modrinth publishing would not go through me, but HypherionSA, if he decides to, but I will be doing CurseForge myself.

**Comment by nonamecrackers2** [comment]
Nah that's alright, we don't need the curse points
