### ISSUE TITLE
[Suggestion]: new ultimate target: coordinate (and some more AI QOL)

### ISSUE THREAD

**Issue by warlordish** [nonamecrackers2/crackers-wither-storm-mod#1768]
### Description of feature request

had some problems forcing the wither storm into one area for a modpack, changing the target to none makes any phase above 3 not target anyone (effectively making it not move at all). But any Phase below 4 and the wither storm will wander away chasing mobs from where it would eventually end up going from phase 3 to 4.

the ultimate target config would have 2 new configs, while the ultimate targeting type would have 1 new target: coordinate

if the coordinate target is chosen, the wither storm will travel to that position(defined by the "coordinateTarget" Config, default can be 0, 80, 0. or any Y Coordinate that would allow the wither storm to hover around 0.0) and stay still (further AI behaivor can be done by having the wither storm attack a player when seen and returning to the coordinate after loosing them, or after a period of time)

(Coordinate can be overridden by the amulet if "amuletOverride" is set to true)

the user can also choose to allow the wither storm to roam arround the coordinate by changing the "coordinateRoam" config (default is 0, which makes the wither storm completely stationary upon getting to the coordinate). this behavior could automatically be turned off after the wither storm reaches over phase 3, as the wither storm does not target and move towards an entity with no active and moving target

For some extra AI behavior for just the NONE target, having the wither storm be able to turn on its own while stationary would help in making every area around it dangerous, as during my testing with the NONE target the wither storm will stop turning itself, making the entire backside of the wither storm completely safe.

finally, if this can not be done I would love for someone to send me to a current mod or a place where i can find how to control certain mob AI, as I am quite new to making modpacks and mods.

thanks.

**Comment by TaintedBlockk** [comment]
This exists already in the newer versions of CWSM in 1.19.4 and 1.20.1

**Comment by warlordish** [comment]
> This exists already in the newer versions of CWSM in 1.19.4 and 1.20.1

Where can i find that? i see no coordinate target in any of the changelogs.

if you're talking about the NONE target, i have been using that but the wither storm still targets entities when under phase 4

**Comment by TaintedBlockmObile** [comment]
> > This exists already in the newer versions of CWSM in 1.19.4 and 1.20.1
> 
> Where can i find that? i see no coordinate target in any of the changelogs.
> 
> if you're talking about the NONE target, i have been using that but the wither storm still targets entities when under phase 4

If you set the ultimate target setting to none, it should stop targeting anything and just roam the area. Although I'm not sure if the wither storm will just try and target a player again after a bit. Although if you set it's target to a block position then it won't target a player and will roam around that block it's targeting. You can also set the ultimate target config to random stroll which will make the wither storm roam the world like any normal mob

**Comment by warlordish** [comment]
> > > This exists already in the newer versions of CWSM in 1.19.4 and 1.20.1
> > 
> > 
> > Where can i find that? i see no coordinate target in any of the changelogs.
> > if you're talking about the NONE target, i have been using that but the wither storm still targets entities when under phase 4
> 
> If you set the ultimate target setting to none, it should stop targeting anything and just roam the area. Although I'm not sure if the wither storm will just try and target a player again after a bit. Although if you set it's target to a block position then it won't target a player and will roam around that block it's targeting. You can also set the ultimate target config to random stroll which will make the wither storm roam the world like any normal mob

sadly i don't think the ultimate target allows coordinates to be the target as the only allowed values are NEAREST, FARTHEST, GROUP, NONE, RANDOM_STROLL, RANDOMIZED, RANDOM_STROLL_NEAR_PLAYER

**Comment by TaintedBlockmObile** [comment]
You have make it target a block with commands 
/witherstormmod: ultimatetarget etc

**Comment by warlordish** [comment]
> You have make it target a block with commands /witherstormmod: ultimatetarget etc

ah, i found it. should have looked further in the commands but thought ultimate target overrode everything.

thank you for the help both of you though!
