### ISSUE TITLE
[Bug] Severed WS can break bedrock

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#177]
1.18.2

2.0.1

Severed Wither Storms can break bedrock 

1. Go to a flat world
2. Bring the WS to Phase 5 and blow it up
3. When the Severed fall down they should break the bedrock

![2022-07-05_23 19 28](https://user-images.githubusercontent.com/28667280/177467407-8bbc8cf9-150a-4984-9bf9-fdcc817fde5b.png)

**Comment by nonamecrackers2** [comment]
Unable to reproduce. Did you maybe perhaps break the bedrock accidently?

**Comment by nonamecrackers2** [comment]
Still unable to reproduce. Were you using any other mods? If not the only thing that I could think would've caused this is a village somehow generating and replacing some of the bedrock with dirt, then when the segments land and "explode" it removes the dirt and gives the impression that they destroyed bedrock.
