### ISSUE TITLE
option to make the command block entity blend better as a block

### ISSUE THREAD

**Issue by juanelgamer456** [nonamecrackers2/crackers-wither-storm-mod#1772]
### Description of feature request

a simple client config to disable the pulse, bossbar, and particles of the command block entity, all together
this would make the entity less distinguible from normal command blocks

**Comment by TheChimcowMan** [comment]
Either they should do that, do that but make it configurable(toggle) or just add the effects and stuff to all command blocks(except the bossbar)

**Comment by nonamecrackers2** [comment]
I do not see the need for this. It's meant to be distinguishable from the normal command block.
