### ISSUE TITLE
[Suggestion]: Blocks Attract Wither Storm

### ISSUE THREAD

**Issue by ThatB0i** [nonamecrackers2/crackers-wither-storm-mod#1773]
### Description of feature request

Somewhat like MCSM, the storm will try to beam up some blocks more than others

So building stuff can somewhat distract the storm, it will also make it so that the storm picks up structures more than other things

the level could be a 1 - 3 or something idk

**Comment by ThatB0i** [comment]
this is very unlikely to be added, but might as well try

**Comment by Herobrine982950291** [comment]
> this is very unlikely to be added, but might as well try

bruh you just predicted the future XD

**Comment by ThatB0i** [comment]
> > this is very unlikely to be added, but might as well try
> 
> bruh you just predicted the future XD

Lmao

**Comment by watersofnazareth** [comment]
I plan on looking into this eventually

**Comment by Herobrine982950291** [comment]
uh-oh it's the fuzz! BUSTED!

**Comment by ThatB0i** [comment]
> uh-oh it's the fuzz! BUSTED!

what

**Comment by Herobrine982950291** [comment]
The "fuzz" is what i call the police.. -_- idk why, just want to call it that.

**Comment by Herobrine982950291** [comment]
Confirmed? looks like we get more MCSM physics!

**Comment by Cod1ngGamer** [comment]
An easy way to do this is just to make it attack playermade structures, similar to the raids from Sculk Horde.

**Comment by nonamecrackers2** [comment]
This has been implemented
