### ISSUE TITLE
A slider that effects how fast the wither storm digs downward.

### ISSUE THREAD

**Issue by HammedBurngur** [nonamecrackers2/crackers-wither-storm-mod#1775]
### Description of feature request

As of right now it can take way too long to reach deepslate which makes the mod a lot less scary imo. To solve this you can add a slider that effects how fast it digs downward

**Comment by Aimyx** [comment]
It digs down? Never noticed rlly prolly cuz im always moleing about underground

**Comment by FrozenDragon0** [comment]
> It digs down? Never noticed rlly prolly cuz im always moleing about underground

If you stay in one place and leave the storm there it'll eventually pick up enough clusters to the point that it reaches deepslate and then bedrock layer.

**Comment by Aimyx** [comment]
thats not the point. The point is that it takes too long, not that it
doesn't do it at all

**Comment by Cod1ngGamer** [comment]
It should be able to dig down faster. Then, the point of the mod is to defeat the WS before it "strips everything down to the bedrock layer" rather than "hide in a hole to win"

**Comment by BluePineappleGuy** [comment]
I managed to recreate the whole "eating to bedrock" thing by setting cluster pickup interval to 10 and enabling "constant black hole". Only issue was that it became a total slideshow

**Comment by Aimyx** [comment]
What if you redirect all block cluster takes to a 25 ish block area
directly above the player, and then just have the wither storm look at that
general location to dig even faster, if there aren't any mobs around

**Comment by nonamecrackers2** [comment]
Yeah I'm going to close this since you can do this now with the various config options as @BluePineappleGuy already showed
