### ISSUE TITLE
[Suggestion]: different music depending on how many mobs there are (first music mod suggestion lel)

### ISSUE THREAD

**Issue by TaintedBlockmObile** [nonamecrackers2/crackers-wither-storm-mod#1776]
### Description of feature request

The bigger the mob group, the music changes and becomes a more intense music.

**Comment by Pandaboi25x** [comment]
Theres a mob battle suggestion page tainted

**Comment by TaintedBlockmObile** [comment]
> Theres a mob battle suggestion page tainted

Where

**Comment by Pandaboi25x** [comment]
> > Theres a mob battle suggestion page tainted
> 
> Where

Just check the curseforge page and look for the documdntion link

**Comment by Pandaboi25x** [comment]
> > Theres a mob battle suggestion page tainted
> 
> Where

https://github.com/nonamecrackers2/mob-battle-music/issues

**Comment by TaintedBlockmObile** [comment]
Found it. Lemme just copy this rq then lol

**Comment by juanelgamer456** [comment]
bro suggested in the wrong github 😭
also you got the record of the suggestion that was closed the fastest

**Comment by TaintedBlockmObile** [comment]
> bro suggested in the wrong github 😭 also you got the record of the suggestion that was closed the fastest

Still the first..! Lol

**Comment by juanelgamer456** [comment]
> > bro suggested in the wrong github 😭 also you got the record of the suggestion that was closed the fastest
> 
> Still the first..! Lol

never said otherwise
in fact, this means you got two records
