### ISSUE TITLE
[Bug]: Wither storm stuck in air

### ISSUE THREAD

**Issue by L0nke** [nonamecrackers2/crackers-wither-storm-mod#1777]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

43.2.10

### Describe the bug

The wither is stuck in the air after exploding the bomb.

### Steps to Reproduce

Simply try to kill the boss. Following the regular steps it gets stuck in the air

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image (4)](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/160797974/6d544687-a1fb-4d62-a0d0-44666e65f41d)

### Mod List

UniversIO (Modpack)

**Comment by watersofnazareth** [comment]
Is it floating above the void?

**Comment by L0nke** [comment]
No it's floating over the end island. Should be enough space for it to "land".

**Comment by L0nke** [comment]
Is there a way to remove him through commands or something seeing as he's just stuck there and we can't kill him or anything of that sort

**Comment by WitherBean** [comment]
teleport it down

**Comment by L0nke** [comment]
Only way to fix it was to /kill everything. That way he went through the final death animation and became the massive pile of blocks

**Comment by Herobrine982950291** [comment]
I have never tried "UniversiO" but i think it has something to do with this. Try it without the mod

**Comment by L0nke** [comment]
UniversIO is a modpack on Curseforge
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/160797974/f8a6cb96-719d-44d2-9713-f4a8dd834cbf)

**Comment by Herobrine982950291** [comment]
show me the "mods" tab... it's probably 1 or 2 of those mods.


And tell me if the issue still occurs with only the Wither Storm mod

**Comment by nonamecrackers2** [comment]
Considering this is a modpack, they may be doing something to cause this, or a mod(s) in the mod list could be causing issues. Also, I'm marking this issue as invalid since the game version and mod version are incorrect; this is 1.19.2, not 1.20.1.
