### ISSUE TITLE
[Bug]: Multiplayer Server crashes

### ISSUE THREAD

**Issue by shootbult** [nonamecrackers2/crackers-wither-storm-mod#1778]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.19

### Describe the bug

[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/14382362/latest.log)
Server crashes everytime when I try with the mod, but it runs perfectly fine without it.

### Steps to Reproduce

1. Run server with mod
2. Server crashes, tries to restart but doesn't work.

### Is OptiFine installed?

- [X] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/123608261/dab46d9c-6a9c-4b13-8a3b-42f48b72788b)

### Mod List

A lot of mods but they didn't conflict probably

**Comment by nonamecrackers2** [comment]
You're trying to launch the server with OptiFine installed which doesn't work since it's a client-side only mod. You'll have to remove it from your server side mod list.
