### ISSUE TITLE
[Suggestion]: MSM stuff and wither storm variants

### ISSUE THREAD

**Issue by golredMaker** [nonamecrackers2/crackers-wither-storm-mod#1779]
### Description of feature request

You should add the armours that they used against the wither storm in Minecraft Story Mode.
I also request that you add different variants of the storm. like repeating wither storm and chain wither storm. 
![13245062](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/161092037/83b077a5-4c8b-4cf4-92bd-ddd03717c816)
![cahin wither storm phase 3 - Converted](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/161092037/92f54b90-f67b-49fa-a439-936ec9ac227b)

**Comment by GearsawStudios** [comment]
Please read the guidelines before posting.

**Comment by golredMaker** [comment]
okokok
sorry

**Comment by Herobrine982950291** [comment]
There is already a mod for the armours... not sure about the different variants of the storm tho.

**Comment by BluePineappleGuy** [comment]
I did have an idea for functionalities for different command blocks on the
wither storm, such as repeating being much more deadly and chain only going
to stage 3, but merging with other storms to enhance their abilities. then
i realized it was out of scope for the mod.
