### ISSUE TITLE
[Suggestion]: Make the Wither Storm instantly become phase 4 if it drops below a certain threshold as a Hunchback

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1782]
### Description of feature request

Some people try preparing for the Wither Storm by getting good gear and end up killing it far too early, leaving them with a bad experience due to breaking intended mechanics. Instead of simply giving super high regeneration or damage reduction, the Wither Storm should jumpscare them by evolving to phase 4 instantly to force them back into progression. This could be set to config if need be.

**Comment by WitherBean** [comment]
This is a great idea

**Comment by nonamecrackers2** [comment]
Kind of like this actually

**Comment by Herobrine982950291** [comment]
same

**Comment by AccursedBird1** [comment]
That would prevent someone from ruining their experience on accident thats awesome!

**Comment by Aimyx** [comment]
Or like, the body would cover itself entirely in the "decay" that normally
grows on the ws, and go docile and stay still and perfectly invincible
until fully healed, then would reemerge

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
