### ISSUE TITLE
[Suggestion]:  Option to render WS heads from faraway

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1783]
### Description of feature request

(Just for performance) It would be nice to have a switch to render/not render the heads in the distance.

**Comment by WitherBean** [comment]
or they could just be removed >:)

**Comment by Herobrine982950291** [comment]
@WitherBean NAH, MAN XD

**Comment by BluePineappleGuy** [comment]
just because, the mass should also be toggleable :)

**Comment by Herobrine982950291** [comment]
oh... so that only the heads show? i dont think seeing 3-9 heads floating in the distance would be a nice add-on...

**Comment by Aimyx** [comment]
I think they mean the other way around

**Comment by Herobrine982950291** [comment]
hmm

**Comment by BluePineappleGuy** [comment]
no actually i did mean the floating heads and tentacles. cuz it would look
stupid and funny

**Comment by nonamecrackers2** [comment]
I don't see the need for this personally since the heads are the least performance impacting

**Comment by Herobrine982950291** [comment]
i knew i should have closed this years ago.

**Comment by Herobrine982950291** [comment]
fine though.
