### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CabbageFan2** [nonamecrackers2/crackers-wither-storm-mod#1784]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

The tentacles that protect the command block gain ABSURD range making it literally impossible to approach

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/161760843/949caa79-59e9-44a4-a5af-b7a476696e84

### Steps to Reproduce

This started happening after I summoned 2 wither storms and they both reached their final phase. The footage is from a completely new world though and I don't know why this happens

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

ParCool
Sniffer+
friends forever
Yungs better jungle temples, better dessert temples, better nether fortresses, better jungle temples
illager invasion
illagers wear armor
dynamic lights
The man from the fog
guard villagers
sound physics 
immersive minecraft
zombie awareness
Enhanced AI
Enhanced visuals
choice theorem's overhauled villages

**Comment by watersofnazareth** [comment]
Mods that change mob awareness radius causes this so this is likely a conflict with Enhanced AI

**Comment by CabbageFan2** [comment]
i removed enhanced ai and zombie awareness and it helped a lot but the tentacles still sometimes hit me from afar, not as frequent as when I had those mods installed though. Edit: it's working as intended now, huge thanks!

**Comment by Herobrine982950291** [comment]
"Lalalala... just strolling in da bowels.... WOAHAAAAAHHHHHHOOHOHHHOOHHHHHHH!!!! ow."

**Comment by BluePineappleGuy** [comment]
it is definitely a compatibility issue, this shouldn't happen at all with
no other mods. try enabling and disabling mods (or moving them to a
separate folder) and seeing which mods cause the issue.
