### ISSUE TITLE
[Suggestion]: command to trigger screen shaking effects

### ISSUE THREAD

**Issue by xg787** [nonamecrackers2/crackers-wither-storm-mod#1785]
### Description of feature request

adding command (and if possible intensity modifier) for screen shaking effects would be very useful for data pack makers and other things

**Comment by WitherBean** [comment]
sounds very useful for datapacks! I hope this gets put into the mod.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release

**Comment by TaintedBlock** [comment]
LFGG

**Comment by Aimyx** [comment]
"/witherstormmod {whatever cracker calls the command here} {intensity i
guess} {duration}"
is how i imagine cracker formated the command
