### ISSUE TITLE
Tractor Beam unloading

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1786]
### Minecraft Version

1.19.4

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

1.19.4 newest

### Describe the bug

When I look away from the Wither Storm, sometimes the beam unloads.

### Steps to Reproduce

I don't know

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-03-01_08 47 10](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114886300/299736a6-59b8-4c43-b580-9f9e386116f5)
![2024-03-01_08 47 08](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114886300/8e11ee67-fe14-4400-98a9-0b2e36510f92)

### Mod List

Explorer's Eve modpack

**Comment by TaintedBlockmObile** [comment]
That might be the tractor beams cutting off since it recent versions, the beam doesn't go through the ground anymore

**Comment by WitherBean** [comment]
It only happens when I look away

**Comment by WitherBean** [comment]
> That might be the tractor beams cutting off since it recent versions, the beam doesn't go through the ground anymore

It also happens above ground too

**Comment by nonamecrackers2** [comment]
The Wither Storm is probably far enough away to trigger the distant renderer, which has culling enabled which makes the tractor beams disappear when you aren't looking at the Wither Storm's hitboxes. Technically intended but I'll look in to fixing this.

**Comment by nonamecrackers2** [comment]
This is intended. As I've already said the Wither Storm is probably in its distant renderer which causes it's tractor beams to be culled when you aren't looking directly at it.
