### ISSUE TITLE
[Suggestion]: Blowing a Goat Horn should make the WS instantly look at the entity who played it

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1787]
### Description of feature request

Considering music seems to calm the Wither Storm with Jukeboxes, it can hear sound. Wouldn't a loud goat horn alert it at all? While it might seem like a useless feature at first that only gets you killed, it could help save a player that's getting beamed with no countermeasures by getting a player with countermeasures take their place instead.

**Comment by Herobrine982950291** [comment]
ah i see what u mean. If someone/thing is getting pulled up and u want to save it, u blow the horn to distract it...

but there are already blocks/items that do this such as:

Fireworks
Firework Bundle etc.

**Comment by WitherBean** [comment]
If this is accepted, the Wither Storm should have huge ears.

**Comment by Herobrine982950291** [comment]
- ^
-_-

**Comment by BluePineappleGuy** [comment]
> If this is accepted, the Wither Storm should have huge ears.

dumbo the giant eldritch monstrosity

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release

**Comment by GearsawStudios** [comment]
It’s official; Wither Storm is team locusts.

**Comment by BluePineappleGuy** [comment]
> It’s official; Wither Storm is team locusts.

no he is just not a fan of the 22w17a bug
