### ISSUE TITLE
[Suggestion]: Different tabs for different blocks in inventory

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1789]
### Description of feature request

I want to see different tabs for different blocks such as - 

Wither Storm mod Building Blocks
Wither Storm mod Items
Wither storm mod Tools and Utillities
Wither Storm Mod Food
Wither Storm Mod Spawn Eggs etc.

**Comment by TaintedBlock** [comment]
This just seems like adding a bunch of useless tabs that will only clutter space

**Comment by nonamecrackers2** [comment]
I personally don't think there is enough items/blocks to necessitate this.

**Comment by Herobrine982950291** [comment]
I knew i  should have closed this years ago, but fine.
