### ISSUE TITLE
Add a item to destroy the wither storm or un-fuse it in earlier phases

### ISSUE THREAD

**Issue by SomeRabbitFan** [nonamecrackers2/crackers-wither-storm-mod#179]
Suggestion: add a means of destroying the wither storm ONLY in its lower phases (Eg, 1 2 3) maybe the command sword would be able to damage the wither storm more [when the command block is visible] or add the elixir from mcsm(Minecraft story mode) in order to kill it. [and get a command block] (while the command block is visible)

**Comment by nonamecrackers2** [comment]
While this isn't the same "item," the idea is the same and was closed for reasons explained here: #65

**Comment by SomeRabbitFan** [comment]
Okay
