### ISSUE TITLE
[Bug]: Right-clicking another player with Golden Apple Stew doesn't give them the effects the stew comes with

### ISSUE THREAD

**Issue by BeeTeeKay64** [nonamecrackers2/crackers-wither-storm-mod#1790]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

When I right-clicked my friend while holding a Golden Apple Stew, the stew didn't give him the statues effects you get when consuming the stew yourself.

The version I'm playing on is the Discord test build with the new chunk loading system.

### Steps to Reproduce

1. Go on a world/server with one other player
2. Get infected by Wither Sickness
3. Right-click the other player with Golden Apple Stew

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Appleskin
Architectury
Better F3
Better Third Person
Chat Heads
Cloth Confiig
Constant Music
Cupboard
Dynamic FPS
Embeddium
Embeddium ++
EMF
ETF
Essentials
Ferritecore
Memory Leak Fix
Modernfix
Smoothchunk
Starlight
Textrues Embeddium Options
[This mod]
Zaero's Minimap

**Comment by Herobrine982950291** [comment]
I don't think this was intended in the beginning. If it was, try it with only the witherstorm mod.

**Comment by nonamecrackers2** [comment]
This is because you can't cure other players by right clicking them, they need to eat the stews themselves. Works as intended.
