### ISSUE TITLE
[Suggestion]: please move the mod over to fabric

### ISSUE THREAD

**Issue by GrenFlem** [nonamecrackers2/crackers-wither-storm-mod#1792]
### Description of feature request

Forge is too unstable and incompatible with other actually good mods that benefit gameplay. Friends cant join my game because of incompatible mods though we have the same mods. Forge is actual dogwater, though we are lead to believe it is good because it used to be all we had, but now there are actually good mod loaders out there. Please move away from forge.

**Comment by TaintedBlockmObile** [comment]
I'm pretty sure this is in the guidelines. If so, please read them. 

Crackers is not planning to remake the entire mod in an entirely new code base

**Comment by GearsawStudios** [comment]
Please read #faq in the Discord before suggesting.

**Comment by Bloxxify2827** [comment]
Average forge denier coming up with the biggest gobbledegook statement

**Comment by LegendaryGodzilla** [comment]
Well this was a dumb suggestion

**Comment by BluePineappleGuy** [comment]
its not worth the effort for crackers to do so, as the mod is already very large. it would take years of work to do something like that, and i haven't seen fabric versions of any of his other mods so i doubt he'd even know how to do many of the things that this mod does.

**Comment by Resuster** [comment]
Forgified Fabric API exists but it doesn't support every fabric mod I believe.

**Comment by WitherBean** [comment]
> ### Description of feature request
> Forge is too unstable and incompatible with other actually good mods that benefit gameplay. Friends cant join my game because of incompatible mods though we have the same mods. Forge is actual dogwater, though we are lead to believe it is good because it used to be all we had, but now there are actually good mod loaders out there. Please move away from forge.

Either switch to Forge, or you can't play together with this mod.

**Comment by Luke7381** [comment]
Dude just use sinyra connector and forgeified fabric api or deal with it. Crackers isn't gonna port the mod over due to the extensive work needed. Also your definitely one of those average forge deniers.

**Comment by nonamecrackers2** [comment]
Forge is actually fairly stable, it's mostly just the mods themselves that do things that conflict with others, but I can understand the concern.

Regarding moving to Fabric, there are major codebase differences that would make migrating a pain and not worth the time investment. CWSM also utilizes Forge-specific features that aren't present (at least, to my knowledge,) on Fabric. For example, Forge adds an emissive property to model JSON files which lets certain quads glow. Recreating this on Fabric would take too much time and I'd rather not maintain multiple versions.
