### ISSUE TITLE
[Bug]: Nothing happens after breaking command block

### ISSUE THREAD

**Issue by Juanxd7777** [nonamecrackers2/crackers-wither-storm-mod#1794]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.17

### Describe the bug

When breaking the command block inside the wither, a white screen appears for like 15 seconds and then dissapoears and im still on the wither, and jumping to the overworld the wither storm is still alive.

### Steps to Reproduce

1. Break command block
2. Wait for white screen to dissappear
3. Nothing happens
4. In the overworld the wither is still alive

### Crash Reports/Logs

https://gist.github.com/Juanxd7777/a6a7f1f13f7d13611baa1f237f0068d7

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

- advancednetherite 2.0.2
	- aeroblender 1.20.1-1.0.1-neoforge
	- aether 1.20.1-1.2.0-neoforge
	- aether_enhanced_extinguishing 1.20.1-1.0.0-neoforge
	- aether_redux 1.20.1
	- aetherdelight 1.0.0
	- alexsmobs 1.22.7
	- alternate_current 1.7.0
	- amecsapi 1.5.3+mc1.20-pre1
	- another_furniture 1.20.1-3.0.1
	- architectury 9.1.13
	- ash_api 3.0.2+1.20.1
	- attackspeedenchantment 1.3.0.20
	- azurelib 2.0.20
	- backpacked 2.2.5
	- badoptimizations 1.6.3
	- ballistix 1.20.1-0.7.0-3
	- balm 7.2.1
	- barteringstation 8.0.0
	- bcc 4.0.8
	- bclib 3.0.14
	- betteradvancements 0.3.2.161
	- betterchunkloading 1.20.1-3.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterend 4.0.11
	- betterendisland 1.20-Forge-2.0.5
	- betterfortresses 1.20-Forge-2.0.5
	- betterfpsdist 1.20.1-4.3
	- betterjungletemples 1.20-Forge-2.0.4
	- bettermineshafts 1.20-Forge-4.0.4
	- bettermodsbutton 8.0.2
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- bhmenu 2.4.1
	- biggerstacks 1.20.1-1.0.0
	- biomemusic 1.20.1-2.3
	- biomesoplenty 18.0.0.598
	- blue_skies 1.3.31
	- boatbreakfix 1.0.2
	- boatiview 0.0.5
	- bonusxp 1.2.0-1.20-1.20.1
	- bookshelf 20.1.9
	- bossominium 18.2.0
	- bountiful 6.0.3+1.20.1
	- bygonenether 1.3.2
	- caelus 3.1.0+1.20
	- canary 0.3.3
	- carryon 2.1.2.7
	- cataclysm 1.0
	- charmofundying 6.4.5+1.20.1
	- chat_heads 0.10.31
	- chefsdelight 1.0.3-forge-1.20.1
	- cherishedworlds 6.1.4+1.20.1
	- chunksending 1.20.1-2.8
	- citadel 2.5.3
	- clientcrafting 1.20.1-1.8
	- cloth_config 11.1.118
	- collective 7.30
	- comforts 6.3.5+1.20.1
	- command_block_recipe 1.0.0-1.20.1
	- commongroovylibrary 0.3.3
	- conjurer_illager 1.1.6
	- connectedglass 1.1.11
	- connectivity 1.20.1-4.9
	- connectorextras 1.9.2+1.20.1
	- connectorextras_architectury_bridge 1.9.2+1.20.1
	- connectorextras_continuity_compat 1.9.2+1.20.1
	- connectorextras_emi_bridge 1.9.2+1.20.1
	- connectorextras_energy_bridge 1.9.2+1.20.1
	- connectorextras_geckolib_fabric_compat 1.9.2+1.20.1
	- connectorextras_jei_bridge 1.9.2+1.20.1
	- connectorextras_kubejs_bridge 1.9.2+1.20.1
	- connectorextras_modmenu_bridge 1.9.2+1.20.1
	- connectorextras_rei_bridge 1.9.2+1.20.1
	- connectorextras_terrablender_bridge 1.9.2+1.20.1
	- connectormod 1.0.0-beta.36+1.20.1
	- controllable 0.20.3
	- controlling 12.0.2
	- coroutil 1.20.1-1.3.7
	- corpse 1.20.1-1.0.9
	- crabbersdelight 1.1.4
	- create 0.5.1.f
	- create_upgraded_armor 1.0.0
	- cristellib 1.1.5
	- croptopia 3.0.4
	- cuisinedelight 1.1.12
	- culllessleaves 1.20.1-1.0.5
	- cumulus_menus 1.20.1-1.0.0-neoforge
	- cupboard 1.20.1-2.3
	- curios 5.7.0+1.20.1
	- cutthrough 8.0.1
	- cyclopscore 1.19.0
	- deathbackup 3.1
	- deathcounter 1.3.0
	- decorative_blocks 4.0.2
	- deep_aether 1.20.1-1.0.2
	- deeperdarker 1.2.1
	- delightful 3.4.2
	- despawn_tweaker 1.20.1-0.0.5
	- deuf 1.20.1-1.3
	- diagonalblocks 8.0.2
	- diagonalfences 8.1.3
	- dimensionalsycnfixes 1.20.1-0.0.1
	- dragonmounts 1.1.5.b3
	- drippyloadingscreen 2.2.4
	- dungeons_arise 2.1.58-1.20.x
	- dynamictrees 1.20.1-1.3.0-BETA2
	- easy_mob_farm 7.0.0
	- easyanvils 8.0.1
	- easyexperience 1.6.0
	- easymagic 8.0.1
	- eatinganimation 5.0.0
	- eldritch_end 0.2.31
	- electrodynamics 1.20.1-0.9.0-3
	- elevated_enchantment 1.0.0
	- elevatorid 1.20.1-lex-1.9
	- elytra_physics 2.0
	- elytraslot 6.3.0+1.20.1
	- embeddium 0.3.5+mc1.20.1
	- enchantment_reveal 1.0.0
	- enchantmenttransfer 0.0.6
	- enchdesc 17.0.14
	- endersdelight 1.0.3
	- endlessbiomes 1.0.0
	- entity_model_features 1.2.3
	- entity_texture_features 5.2.3
	- entityculling 1.6.2
	- epherolib 0.1.2
	- euphoria_patcher 0.3.0-forge
	- everycomp 1.20-2.6.29
	- evilcraft 1.2.37
	- evilcraftcompat 1.2.37
	- exoticbirds 1.0.0
	- expandedstorage 10.2.2
	- experienced_crops 1.20.1-1.1.0
	- explorations 1.20.1-1.5.2
	- explorify 1.3.0-mc1.20
	- extra_compat 1.4.1
	- fabric_api 0.91.0+1.10.8+1.20.1
	- fabric_api_base 0.4.30+ef105b4977
	- fabric_api_lookup_api_v1 1.6.35+67f9824077
	- fabric_biome_api_v1 13.0.12+dd0389a577
	- fabric_block_api_v1 1.0.10+0e6cb7f777
	- fabric_block_view_api_v2 1.0.0+0767707077
	- fabric_blockrenderlayer_v1 1.1.40+1d0da21e77
	- fabric_client_tags_api_v1 1.1.1+5d6761b877
	- fabric_command_api_v1 1.2.33+f71b366f77
	- fabric_command_api_v2 2.2.12+561530ec77
	- fabric_content_registries_v0 4.0.10+a670df1e77
	- fabric_convention_tags_v1 1.5.4+fa3d1c0177
	- fabric_data_generation_api_v1 12.3.3+369cb3a477
	- fabric_dimensions_v1 2.1.53+8005d10d77
	- fabric_entity_events_v1 1.5.22+b909fbe377
	- fabric_events_interaction_v0 0.6.1+0d0bd5a777
	- fabric_game_rule_api_v1 1.0.39+461110ab77
	- fabric_item_api_v1 2.1.27+2272fc7f77
	- fabric_item_group_api_v1 4.0.11+f687ac9377
	- fabric_key_binding_api_v1 1.0.36+561530ec77
	- fabric_lifecycle_events_v1 2.2.21+afab492177
	- fabric_loot_api_v2 1.2.0+eb28f93e77
	- fabric_message_api_v1 5.1.8+52cc178c77
	- fabric_mining_level_api_v1 2.1.49+561530ec77
	- fabric_model_loading_api_v1 1.0.2+3a78c72c77
	- fabric_models_v0 0.4.1+7c3892a477
	- fabric_networking_api_v1 1.3.10+503a202477
	- fabric_object_builder_api_v1 11.1.2+2174fc8477
	- fabric_particles_v1 1.1.1+78e1ecb877
	- fabric_recipe_api_v1 1.0.20+514a076577
	- fabric_registry_sync_v0 2.3.2+1c0ea72177
	- fabric_renderer_api_v1 3.2.0+1d29b44577
	- fabric_renderer_indigo 1.5.0+67f9824077
	- fabric_rendering_data_attachment_v1 0.3.36+a6081afc77
	- fabric_rendering_fluids_v1 3.0.27+4ac5e37a77
	- fabric_rendering_v1 3.0.7+1c0ea72177
	- fabric_resource_conditions_api_v1 2.3.7+9ad825cd77
	- fabric_resource_loader_v0 0.11.9+142e25ab77
	- fabric_screen_api_v1 2.0.7+45a670a577
	- fabric_screen_handler_api_v1 1.3.29+561530ec77
	- fabric_sound_api_v1 1.0.12+4f23bd8477
	- fabric_transfer_api_v1 3.3.3+b00938ec77
	- fabric_transitive_access_wideners_v1 4.3.0+1880499877
	- fallingleaves 2.1.0
	- fallingtree 4.3.4
	- fancymenu 2.14.13
	- farmersdelight 1.20.1-1.2.4
	- farsight_view 1.20.1-3.6
	- fastasyncworldsave 1.20.1-1.4
	- fastipping 1.0.1
	- fastpaintings 1.20-1.2.4
	- ferritecore 6.0.1
	- flib 0.0.11
	- flywheel 0.6.10-7
	- forge 47.2.17
	- forgeconfigapiport 8.0.0
	- forgeconfigscreens 8.0.2
	- formations 1.0.2
	- formationsnether 1.0.3
	- formationsoverworld 1.0.2
	- framework 0.6.16
	- friendsandfoes 2.0.9
	- ftblibrary 2001.1.5
	- ftbquests 2001.3.3
	- ftbteams 2001.1.4
	- ftbxmodcompat 2.1.0
	- fullstackwatchdog 1.0.1+1.19.2-forge
	- fusion 1.1.1
	- gardens_of_the_dead 4.0.1
	- geckoanimfix 1.0.0
	- geckolib 4.4.2
	- geophilic 2.1.0-mc1.20u1.20.2
	- geophilic_reforged 1.2.0
	- gml 4.0.9
	- goblintraders 1.9.3
	- golems 20.1.0.0
	- gpumemleakfix 1.20.1-1.8
	- grassoverhaul 23.10.10
	- grimoireofgaia 4.0.0-alpha.6
	- guardvillagers 1.20.1-1.6.3
	- handcrafted 3.0.5
	- hearth_and_home 1.20.1-2.0.1
	- hearths 1.0.0-mc1.20u1.20.1
	- highlighter 1.1.9
	- hmag 9.0.13
	- iceberg 1.1.18
	- illagerinvasion 8.0.4
	- immediatelyfast 1.2.10+1.20.4
	- inventoryhud 3.4.18
	- inventorymanagement 1.3.1
	- ironchest 1.20.1-14.4.4
	- itemfilters 2001.1.0-build.59
	- jade 11.8.0
	- jei 15.2.0.27
	- jeresources 1.4.0.247
	- justenoughbreeding 1.0.12
	- justenoughprofessions 3.0.1
	- justzoom 1.0.2
	- kambrik 6.1.1+1.20.1
	- kiwi 11.5.3
	- kleeslabs 15.0.0
	- konkrete 1.8.0
	- kotlinforforge 4.10.0
	- krypton 0.2.3
	- l2library 2.4.16
	- lazurite 1.0.3+mc1.20.1
	- leavesbegone 8.0.0
	- lmft 1.0.4+1.20.1
	- logbegone 1.0.8
	- lootintegrations 1.20.1-3.4
	- lost_aether_content 1.2.3
	- luna 1.0.0
	- magnumtorch 8.0.2
	- majruszlibrary 7.0.5
	- majruszsdifficulty 1.9.8
	- maxenchantx 1.3
	- memoryleakfix 1.1.1
	- memorysettings 1.20.1-5.4
	- merenc 3.1
	- mindfuldarkness 8.0.3
	- minecraft 1.20.1
	- mixinextras 0.2.0
	- mixinsquared 0.1.1
	- mjollir 1.0.0
	- modernfix 5.13.0+mc1.20.1
	- modmenu 7.2.2
	- modpackupdatechecker 0.11.3
	- moonlight 1.20-2.9.10
	- mousetweaks 2.25
	- mr_blossom_blade 1.0
	- mr_dungeons_andtaverns 3.0.3
	- naturalist 4.0.3
	- naturescompass 1.20.1-1.11.2-forge
	- necronomicon 1.4.2
	- neruina 1.3.0
	- netherchested 8.0.3
	- netherportalfix 13.0.1
	- nethersdelight 1.20.1-4.0
	- nightconfigfixes 8.0.0
	- nightvision 1.20.1-0.0.2
	- nitrogen_internals 1.20.1-1.0.2-neoforge
	- nochatreports 1.20.1-v2.2.2
	- notenoughanimations 1.7.1
	- ntgbb 1.20.1-1.1.1
	- oceansdelight 1.0.2-1.20
	- oculus 1.6.15a
	- onlyhammersandexcavators 1.20.1-0.2
	- openpartiesandclaims 0.20.4
	- overflowingbars 8.0.0
	- packetfixer 1.2.4
	- paintings 11.0.0.0
	- patchouli 1.20.1-84-FORGE
	- paxi 1.20-Forge-4.0
	- philipsruins 3.1
	- pickupnotifier 8.0.0
	- pingwheel 1.7.1
	- polymorph 0.49.2+1.20.1
	- puzzlesaccessapi 8.0.9
	- puzzlesapi 8.1.5
	- puzzleslib 8.1.16
	- quark 4.0-436
	- quarkdelight 1.0.0
	- raided 0.1.3
	- reach_entity_attributes 2.4.0
	- realmrpg_skeletons 1.0.3
	- rechiseled 1.1.5c
	- recipeessentials 1.20.1-3.2
	- replantingcrops 5.3
	- repurposed_structures 7.1.11+1.20.1-forge
	- resourcefullib 2.1.23
	- resourcepackoverrides 8.0.2
	- revampedwolf 1.20.1-5.0.0
	- rightclickharvest 3.2.3+1.20.1-forge
	- rubidium 0.7.1
	- ryoamiclights 0.1.7+1.20.1
	- saturn 0.1.3
	- sawmill 1.20-1.3.0
	- scalinghealth 8.0.2+9
	- scuba_gear 1.0.6
	- sdrp 4.0.3-build.40+mc1.20.1
	- searchables 1.0.2
	- sereneseasons 9.0.0.46
	- serverbrowser 1.0.0
	- servercountryflags 1.9.3
	- shieldexp 1.1.7a
	- silentlib 8.0.0
	- simpleplanes 1.20.1-5.2.7
	- skinlayers3d 1.6.2
	- sleep_tight 1.20-1.1.19
	- smallships 2.0.0-b1.0
	- smarterfarmers 1.20-1.8.1
	- smoothchunk 1.20.1-3.5
	- snowrealmagic 10.2.7
	- snowundertrees 1.4.3
	- solarcraft 1.0.1
	- sophisticatedbackpacks 3.20.1.1012
	- sophisticatedcore 0.6.3.553
	- sound_physics_remastered 1.20.1-1.1.2
	- spark 1.10.53
	- sparsestructuresreforged 1.20.1-1.0.0
	- spawners_plus 2.0.1-1.20.1
	- spectrelib 0.13.15+1.20.1
	- sprinklerz 0.5
	- spruceui 0.1.2+1.20.1
	- stackablepotions 1.0.0
	- stalwart_dungeons 1.2.8
	- stoneworks 8.0.0
	- stonycliffs 1.0.0
	- storagenetwork 1.10.0
	- structory 1.3.4
	- structorytowers 1.0.6
	- structure_gel 2.16.0
	- structureessentials 1.20.1-3.2
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.7.35
	- suppsquared 1.20-1.1.12
	- t_and_t 0.0NONE
	- taxfreelevels 1.3.9
	- terrablender 3.0.1.4
	- terralith 2.4.11
	- thornybushprotection 1.2
	- tipsmod 12.0.4
	- tombstone 8.6.1
	- toofast 0.4.3.5
	- toolleveling 1.20.1-2.0.0
	- totemic 1.20.1-0.12.10
	- tradingpost 8.0.2
	- transparent 8.0.1+1.20.1
	- twigs 1.20.1-3.1.1
	- twilightdelight 2.0.4
	- twilightforest 4.3.2145
	- ultris_mr 5.6.9c
	- umbral_skies 1.3
	- upgradedechests 1.0.3-1.20.1
	- uteamcore 5.1.4.269
	- veinmining 1.3.0+1.20.1
	- villagernames 7.3
	- villagersplus 3.1
	- villagesandpillages 1.0.0
	- visuality 2.0.2
	- visualworkbench 8.0.0
	- voidtotem 3.0.1
	- watut 1.20.1-1.0.13
	- waystones 14.1.3
	- weaponleveling 1.20.1-2.1.1
	- whatareyouvotingfor 1.2.3
	- wither_drops_netherite_templates 1.0.0
	- witherstormmod 4.0.1.1
	- wunderlib 1.1.5
	- xaerominimap 23.9.7
	- xaeroplus 1.20.1
	- xaeroworldmap 1.37.8
	- xenon 0.3.5+mc1.20.1
	- xpbook 2.2
	- xpfromharvest 1.2.3
	- yeetusexperimentus 2.3.1-build.6+mc1.20.1
	- ysns 1.0.2
	- yungsapi 1.20-Forge-4.0.3
	- yungsbridges 1.20-Forge-4.0.3
	- yungsmenutweaks 1.20.1-Forge-1.0.1
	- zeta 1.0-13

**Comment by GearsawStudios** [comment]
How does the game run with all those mods?

**Comment by TaintedBlockmObile** [comment]
Yeah with this amount of mods, no wonder something went wrong. How many is that anyway?

**Comment by BluePineappleGuy** [comment]
probably a mod compat issue, but it would be a pain to figure out which one

**Comment by WitherBean** [comment]
Too many mods. It's a lag issue though. I recommend restarting the modpack or deleting all of the extra mods.

**Comment by nonamecrackers2** [comment]
From what I can gather, it may be an issue with ``farsight``. Try removing it and see if that resolves it.

If not, I'm not sure what else it could be due to the size of your mod list. You may have to try removing mods until you come across the issue.
