### ISSUE TITLE
Make the wither storm player controllable.

### ISSUE THREAD

**Issue by GroxDots** [nonamecrackers2/crackers-wither-storm-mod#1798]
### Description of feature request

Instead of an AI doing it, make it so that a player can control it. If it is already implemented, please write how to do it. 

If the player is in a multiplayer world, there should be arrows pointing to the other players.

**Comment by watersofnazareth** [comment]
Given how complex the Wither Storm is and how heavily code driven it is I don't think this is going to be something we do, but if Crackers wants to reopen this in the future I'm sure he will

**Comment by GroxDots** [comment]
Sad but understandable.

**Comment by nonamecrackers2** [comment]
You can use commands to redirect where it's going: https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Commands-and-Technical

**Comment by GroxDots** [comment]
Was not expecting a reply. To be more precise, is there a way for to make the wither storm target only mobs (does not matter which ones) while ignoring players?

**Comment by nonamecrackers2** [comment]
No that is currently not possible, I'd make a new suggestion if you're wanting to have that in the mod
