### ISSUE TITLE
[Bug]: WitherStorm is leaving blank NBT tags in items, which is messing up item stacking

### ISSUE THREAD

**Issue by PakoJones88** [nonamecrackers2/crackers-wither-storm-mod#1799]
### Minecraft Version

1.18.2

### Mod Version

2.2.1

### Mod Loader

Forge

### Mod Loader Version

40.2.17

### Describe the bug

As the title says, items are getting added a blank NBT tag. The blank NBT tag is preventing items from properly stacking.

### Steps to Reproduce

1. In creative mode, get some item from the creative inventory (I did it with a grass block) and place it in your hotbar.
2. Select the item in your hotbar at least once (then you can unselect it, it doesn't matter).
3. Press E to open the inventory again.
4. Close the inventory and see that the blank NBT tag has been added. (`/data get entity @p Inventory`)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/110305970/5fb494ff-1a63-4569-8624-9dde8b5c0704)

### Mod List

witherstormmod-1.18.2-2.2.1

**Comment by BluePineappleGuy** [comment]
You're using 1.18.2 which i believe is no longer supported. Does this issue occur in the latest version of the mod?

**Comment by nonamecrackers2** [comment]
I believe I fixed this in the newer versions of the mod. But yes, 1.18.2 is no longer supported and this isn't a game breaking bug.
