### ISSUE TITLE
Piglins and storm wither 

### ISSUE THREAD

**Issue by SplendidSuperGithub** [nonamecrackers2/crackers-wither-storm-mod#180]
Piglin try  kill wither boss or wither skeletons, I think they have to try kill the wither storm or wither symbionts or withered mobs like withered zombie or spider, like those mobs.

**Comment by nonamecrackers2** [comment]
I'm a little bit confused on what you're requesting. You want piglins to fight the wither storm?

**Comment by SplendidSuperGithub** [comment]
> I'm a little bit confused on what you're requesting. You want piglins to fight the wither storm?
Sorry if my grammar is bad, I'm not very good at speaking English.  when a piglin or brute piglin sees a wither skeleton or a wither boss he tries to kill the wither i think when a piglin sees the wither storm his symbiotes or mobs infect him with the wither storm (similar to the spider or the zombies that when infected they do not die but become allies of the storm), it tries to kill these mobs.
