### ISSUE TITLE
Wither Storm Spawn Egg

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1800]
### Description of feature request

Just like the Wither, the Wither Storm should have a spawn egg. It should be found in commands only.

**Comment by Pandaboi25x** [comment]
#1800 sugestion.. also yeaahhh wither storm spawn egg!!!

**Comment by GearsawStudios** [comment]
Ender Dragon spawn egg exists, Wither Storm should be hidden but still existing.

**Comment by BluePineappleGuy** [comment]
think of the multiplayer servers...

**Comment by GearsawStudios** [comment]
> think of the multiplayer servers...

In repeating command block with no redstone requirement:
/summon witherstormmod:wither_storm ~ ~ ~

That's not a valid excuse.

**Comment by BluePineappleGuy** [comment]
> > think of the multiplayer servers...
> 
> In repeating command block with no redstone requirement: /summon witherstormmod:wither_storm ~ ~ ~
> 
> That's not a valid excuse.

ik but i can imagine the amount of lag this would cause for kids messing around lol

**Comment by GearsawStudios** [comment]
You can already do that though, this doesn't enable that. Someone can already place down a row of WS summons, use commands, use a command block or build a massive pile of Formidibombs.

**Comment by TaintedBlockmObile** [comment]
Just imagine throwing at least 70 wither storm spawn eggs in the air with story mod

**Comment by nonamecrackers2** [comment]
Thought this was already suggested, but I guess not. This is not a good idea in general since it'll be very easy for unsuspecting players to accidently spawn a lot of Wither Storms at once which could cause issues.
