### ISSUE TITLE
[Suggestion]: An Item to Devolve the Wither Storm

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1801]
### A little more calm before the Storm

If the player needs more time before Phase 4 kicks in and all that it brings with it, this item can regress the Wither Storm to earlier Phases so the player can have more time to gather resources or escape to the Nether, as the hunchback phases of the Storm don't chase as fast as the other Phases beyond that hunchback.

**"But isn't there an option in the config to change the evolution speed of the WS?"**

Yes, that is an alternative to this suggestion, but that has its own caveats, affecting the the growth of the storm will affect the length of the battle with the Wither Storm as a whole. If you make the evolution speed of the WS slower in the config, it can draw out the battle to be too long. This suggestion is more to give the player a little more time before the real battle begins.

 Concept:

I have two ideas for this item:

1. By combining a rotten flesh, bone, gunpowder, and spider eye, it will create the item. Then by throwing this item at the Wither Storm, it will devolve the Storm to Phase 2 or 3.

2. An Ender Pearl combined with some redstone and gold, which will create the item. Then by launching the new pearl with a cross bow or throwing it into the WS' face, it will devolve the Storm to a weaker Phase.
![devolerpearl](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/148708399/c3e6331f-4380-4515-835a-7f8da2f4de21)

**Comment by TaintedBlock** [comment]
I think if you can't escape the wither storm with its evolution speed at the slowest, it's a personal skill issue. But with that being said, this seems a bit unnecessary and way out of scope of the mod. It kinda kills the fear the Wither Storm is supposed to give you when you hear it evolve

**Comment by ghost** [comment]
> I think if you can't escape the wither storm with its evolution speed at the slowest, it's a personal skill issue. But with that being said, this seems a bit unnecessary and way out of scope of the mod. It kinda kills the fear the Wither Storm is supposed to give you when you hear it evolve

In a Pure Vanilla Game with the WS mod only, being able to escape the WS can be **luck based**.
- You may be unable to find the diamonds needed to mine obsidian and make a portal, because the player doesn't know the speedrun strat for portal making.
- You may be unable to gather the armor to tank hits from the WS eating you, and/or lack the skills to MLG bucket.
- There's the chance you die before you find a Nether Fortress for Blaze Powder because you cannot find a Fortress before either the Nether's inhabitants kill you or you die of Wither Sickness.
- There's the chance you're unable to obtain the gunpowder needed for a Formidibomb, due to Creepers being stingy, or they keep exploding before you kill them.

I can see that this item would be relatively useless for and break the pace for expert Minecraft players or those well familiar with the WS, but this item is mainly towards inexperienced Minecraft players who are unable to gather the resources in time for the Wither Storm.

Plus, while it does kill the fear of the Storm, it's not a **necessary** item like the Command Block tools or Formidibomb. You can completely ignore this item, and still beat the Storm through will and skill.

**Comment by GearsawStudios** [comment]
You can outrun the storm on foot too.

**Comment by WitherBean** [comment]
If you played BWSB, I would understand why this is needed. But by default, no.

**Comment by BluePineappleGuy** [comment]
good idea, but maybe it shouldn't be usable on a stage 4 but on a storm
thats close to it? stage 4 is the major surprise moment, where from this
mutant wither it turns to an eldritch beast suddenly. making it usable on
stage 4 ruins that.

**Comment by Herobrine982950291** [comment]
> If you played BWSB, I would understand why this is needed. But by default, no.

BWSB IS BROKEN!

**Comment by WitherBean** [comment]
> > If you played BWSB, I would understand why this is needed. But by default, no.
> 
> BWSB IS BROKEN!

It's not. You installed it wrong.

**Comment by nonamecrackers2** [comment]
Interesting idea, however it doesn't fit in with my vision for the mod. I want players to feel helpless to stop the Wither Storm's growth, this would go against this and I feel this item could easily be abused. Thanks for your suggestion though.

**Comment by Herobrine982950291** [comment]
When a player learns it always evolves belike: "there is no way to stop it from evolving! MY ENTIRE WORLD WILL BE GONE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
