### ISSUE TITLE
[Suggestion]: Minecraft on switch 

### ISSUE THREAD

**Issue by Shadowwolf2010-void** [nonamecrackers2/crackers-wither-storm-mod#1803]
### Description of feature request

Im a Minecraft switch player and on it there's a market place with add-ons that players can download for their world can you guys possibly learn how to add the wither storm mod to the market place for 20, or 40 mine coins please and thank you <3

![IMG_20240316_002236_HDR](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/145250101/ba6eea8f-3d90-4e34-b8e3-0096be62655e)

**Comment by nonamecrackers2** [comment]
Bedrock is not supported.
