### ISSUE TITLE
[Suggestion]: Chain Wither Storm

### ISSUE THREAD

**Issue by RepositoryLover** [nonamecrackers2/crackers-wither-storm-mod#1805]
### Description of feature request

Add a new type of wither storm: Chain Wither Storm. It has chain command block inside of it instead of the impulse one. Unlike the original impulse wither storm, this wither storm can’t evolve or suck up blocks without the impulse one around, and would rather act as a normal wither until an impulse one spawns. And no matter the phase, if the impulse one dies, then the chain one stops sucking up blocks and evolving while still living.

**Comment by Pandaboi25x** [comment]
Please read the guidelines.

**Comment by RepositoryLover** [comment]
I did!

**Comment by RepositoryLover** [comment]
> Please read the guidelines.

Alright. I did. What’s wrong with this suggestion?

**Comment by Pandaboi25x** [comment]
> > Please read the guidelines.
> 
> Alright. I did. What’s wrong with this suggestion?

there wont be any other "Chain Command block" or "Repeating command block" wither storms, crackers probably didnt add it to the guidelines yet i guess

**Comment by RepositoryLover** [comment]
> > > Please read the guidelines.
> > 
> > 
> > Alright. I did. What’s wrong with this suggestion?
> 
> there wont be any other "Chain Command block" or "Repeating command block" wither storms, crackers probably didnt add it to the guidelines yet i guess

Ok. It’s probably too big of a suggestion, I guess.

**Comment by Nov1st2k10** [comment]
> > > Please read the guidelines.
> > 
> > 
> > Alright. I did. What’s wrong with this suggestion?
> 
> there wont be any other "Chain Command block" or "Repeating command block" wither storms, crackers probably didnt add it to the guidelines yet i guess

panda you moron read the guidelines before telling other people to read the guidelines 😭

**Comment by TaintedBlockmObile** [comment]
#1779

**Comment by Pandaboi25x** [comment]
> > > > Please read the guidelines.
> > > 
> > > 
> > > Alright. I did. What’s wrong with this suggestion?
> > 
> > 
> > there wont be any other "Chain Command block" or "Repeating command block" wither storms, crackers probably didnt add it to the guidelines yet i guess
> 
> panda you moron read the guidelines before telling other people to read the guidelines 😭

yes i remember the whole fucking guidelines i dont check it that much man

**Comment by Aimyx** [comment]
The part of the guidelines in question is the part where 'has been
suggested before'.
Always check to see if your suggestion doesn't already exist before posting

**Comment by nonamecrackers2** [comment]
#1779
