### ISSUE TITLE
...

### ISSUE THREAD

**Issue by battleforce404** [nonamecrackers2/crackers-wither-storm-mod#1809]
....

**Comment by GearsawStudios** [comment]
Please read suggestion guidelines before posting.

**Comment by battleforce404** [comment]
How?

**Comment by GearsawStudios** [comment]
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/122060314/fe8ea14c-be73-4dfe-af5b-228b9d478324)

**Comment by Pandaboi25x** [comment]
atleast close it down 😭

**Comment by TaintedBlockmObile** [comment]
Please close this.

**Comment by Laikagor** [comment]
close this

**Comment by NinjaSam5399** [comment]
Close this. its pointless.
