### ISSUE TITLE
[Suggestion]: Make it so the world will  will slowly mutate, that is, for example, cobblestone, when it is in the tractor beam of the Wither Storm, becomes withered cobblestone.

### ISSUE THREAD

**Issue by respear** [nonamecrackers2/crackers-wither-storm-mod#1810]
### Description of feature request

totally not from taken from the mod that stole cwsm
https://www.curseforge.com/minecraft/mc-mods/manjacs-wither-storm

**Comment by TaintedBlockmObile** [comment]
You had the nerve to make this.💀

**Comment by Aimyx** [comment]
Womp womp

**Comment by FireCode125** [comment]
Can we rename :theripoff: emoji to :lowtaperfade;

**Comment by Herobrine982950291** [comment]
you had the nerve to make a suggestion from a thief's mod. 😒😒💀💀💀💀

**Comment by BluePineappleGuy** [comment]
anyway this is duplicate i believe so, like the thief mod, it'll get closed
due to duplicate

**Comment by nonamecrackers2** [comment]
#1739
