### ISSUE TITLE
Better Evolving

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1812]
### Description of feature request

When the Wither Storm is in phase 5.5, it can eventually split into phase 6 with enough consumed entities.

**Comment by RepositoryLover** [comment]
That’s not how this works.

**Comment by TaintedBlockmObile** [comment]
This doesn't really make any sense. Why would it blow itself up?

**Comment by BluePineappleGuy** [comment]
so cut out the f-bomb, it splits itself into three to accelerate its
destruction.

**Comment by Herobrine982950291** [comment]
this won't fit in. It does not even make sense even in MCSM!

**Comment by WitherBean** [comment]
I knew this suggestion was bad from when I made it.
