### ISSUE TITLE
[Suggestion]: Support Wither Storm

### ISSUE THREAD

**Issue by RepositoryLover** [nonamecrackers2/crackers-wither-storm-mod#1813]
### Description of feature request

I have an idea for the withered support beacons. You would put three wither skulls on that and a new type of Wither Storm segment spawns. This Wither Storm segment is like the original but it can follow you on its own. Its model will also be mirrored to look like the right segment because when you spawn the original segment by its self it always looks like the left one. It will also have the stuff flying around it like the original Wither Storm (phase 4-7.5). Its purpose is to aid the Wither Storm even before phase 6. It will be called a Support Wither Storm. They can be spawned after defeating and respawning the Wither Storm and will provide a much greater challenge. When summoned they will be many blocks away in the four directions: North, South, West, East. They’ll also act chunk loaders and still come for you. Be careful where you travel.

**Comment by RepositoryLover** [comment]
They won’t act exactly like the original segments, they stand alone.

**Comment by RepositoryLover** [comment]
They’ll spawn far away, too.

**Comment by WitherBean** [comment]
So just make wither storm segments follow the player and can be summoned.

**Comment by RepositoryLover** [comment]
> So just make wither storm segments follow the player and can be summoned.

You can do that?

**Comment by WitherBean** [comment]
> > So just make wither storm segments follow the player and can be summoned.
> 
> You can do that?

You can, they are different entities.

**Comment by RepositoryLover** [comment]
> > > So just make wither storm segments follow the player and can be summoned.
> > 
> > 
> > You can do that?
> 
> You can, they are different entities.

How do you do it, is there a config for it?

**Comment by WitherBean** [comment]
> > > > So just make wither storm segments follow the player and can be summoned.
> > > 
> > > 
> > > You can do that?
> > 
> > 
> > You can, they are different entities.
> 
> How do you do it, is there a config for it?

Datapacks

**Comment by WitherBean** [comment]
rename this to "Option to summon Wither Storm Segments from Super Beacons"

**Comment by RepositoryLover** [comment]
Do you make one yourself or do you get one? I didn’t see any available on CurseForge.

**Comment by WitherBean** [comment]
> Do you make one yourself or do you get one? I didn’t see any available on CurseForge.

You make them

**Comment by WitherBean** [comment]
The option is in recipes (inside the data folder of the mod). Look for mob names in there. You can copy the Wither Storm's file, and change the entity, add entities, and change items needed.

**Comment by RepositoryLover** [comment]
Ok. I’ll try.

**Comment by RepositoryLover** [comment]
> The option is in recipes (inside the data folder of the mod). Look for mob names in there. You can copy the Wither Storm's file, and change the entity, add entities, and change items needed.

And make duplicates and different versions of entities?

**Comment by WitherBean** [comment]
> > The option is in recipes (inside the data folder of the mod). Look for mob names in there. You can copy the Wither Storm's file, and change the entity, add entities, and change items needed.
> 
> And make duplicates and different versions of entities?

If you want

**Comment by RepositoryLover** [comment]
> The option is in recipes (inside the data folder of the mod). Look for mob names in there. You can copy the Wither Storm's file, and change the entity, add entities, and change items needed.

I don’t see it. I tried searching for it in File Explorer.

**Comment by BluePineappleGuy** [comment]
> I don’t see it. I tried searching for it in File Explorer.

rename the mod file extension from `.jar` to `.zip`. windows will give you a warning but ignore it. then open the zip (you may have to extract it) and find the data file inside.

**Comment by RepositoryLover** [comment]
> The option is in recipes (inside the data folder of the mod). Look for mob names in there. You can copy the Wither Storm's file, and change the entity, add entities, and change items needed.

Nonamecrackers2 said you can’t add new mobs with datapacks.

**Comment by WitherBean** [comment]
> > The option is in recipes (inside the data folder of the mod). Look for mob names in there. You can copy the Wither Storm's file, and change the entity, add entities, and change items needed.
> 
> Nonamecrackers2 said you can’t add new mobs with datapacks.

You technically can't.

**Comment by RepositoryLover** [comment]
> > > The option is in recipes (inside the data folder of the mod). Look for mob names in there. You can copy the Wither Storm's file, and change the entity, add entities, and change items needed.
> > 
> > 
> > Nonamecrackers2 said you can’t add new mobs with datapacks.
> 
> That's not a mob.

You mean the segment? Yeah, it is. wither_storm_segment. Try summoning it when playing the game.

**Comment by RepositoryLover** [comment]
> > > The option is in recipes (inside the data folder of the mod). Look for mob names in there. You can copy the Wither Storm's file, and change the entity, add entities, and change items needed.
> > 
> > 
> > Nonamecrackers2 said you can’t add new mobs with datapacks.
> 
> You technically can't.

So you can add entities, just not mobs?

**Comment by FireCode125** [comment]
What

**Comment by ghost** [comment]
So you want more Wither Storm Segments to be summoned from the support beacons?

**Comment by RepositoryLover** [comment]
> So you want more Wither Storm Segments to be summoned from the support beacons?

Yes. And they’ll be separate mobs from the original segment and they’ll look like the right one.

**Comment by RepositoryLover** [comment]
They’ll have the internal name: support_wither_storm

**Comment by WitherBean** [comment]
> > So you want more Wither Storm Segments to be summoned from the support beacons?
> 
> Yes. And they’ll be separate mobs from the original segment and they’ll look like the right one.

Why do they need to be separate entities?

**Comment by RepositoryLover** [comment]
> > > So you want more Wither Storm Segments to be summoned from the support beacons?
> > 
> > 
> > Yes. And they’ll be separate mobs from the original segment and they’ll look like the right one.
> 
> Why do thy need to be separate entities?

Because if they were the same mob, then they’ll be independent of the main Wither Storm.

**Comment by RepositoryLover** [comment]
> > > So you want more Wither Storm Segments to be summoned from the support beacons?
> > 
> > 
> > Yes. And they’ll be separate mobs from the original segment and they’ll look like the right one.
> 
> Why do they need to be separate entities?

Because they would be independent of the main Wither Storm unlike the original segments. If you summoned the original segment, it would be stationary.

**Comment by RepositoryLover** [comment]
The support Wither Storm will move on their own unlike the original Wither Storm segment.

**Comment by RepositoryLover** [comment]
We can also have an amulet that tracks them and the main Wither Storm. And the phasometer can check the type of Wither Storm if it’s the main or one of the support ones.

**Comment by RepositoryLover** [comment]
Hello? @WitherBean I just gave you the reason.

**Comment by WitherBean** [comment]
> The support Wither Storm will move on their own unlike the original Wither Storm segment.

This could all still be the same entity, just will different nbt.

**Comment by WitherBean** [comment]
> > > > So you want more Wither Storm Segments to be summoned from the support beacons?
> > > 
> > > 
> > > Yes. And they’ll be separate mobs from the original segment and they’ll look like the right one.
> > 
> > 
> > Why do they need to be separate entities?
> 
> Because they would be independent of the main Wither Storm unlike the original segments. If you summoned the original segment, it would be stationary.

The segments could still move freely in the future.

**Comment by RepositoryLover** [comment]
> > > > > So you want more Wither Storm Segments to be summoned from the support beacons?
> > > > 
> > > > 
> > > > Yes. And they’ll be separate mobs from the original segment and they’ll look like the right one.
> > > 
> > > 
> > > Why do they need to be separate entities?
> > 
> > 
> > Because they would be independent of the main Wither Storm unlike the original segments. If you summoned the original segment, it would be stationary.
> 
> The segments could still move freely in the future.

What do you mean? You mean as a future feature?

**Comment by RepositoryLover** [comment]
> > The support Wither Storm will move on their own unlike the original Wither Storm segment.
> 
> This could all still be the same entity, just will different nbt.

What would the NBT be?

**Comment by nonamecrackers2** [comment]
Interesting idea, but this is out of scope for the mod.
