### ISSUE TITLE
[Suggestion]: Wither Storm segment one head NBT tag

### ISSUE THREAD

**Issue by RepositoryLover** [nonamecrackers2/crackers-wither-storm-mod#1816]
### Description of feature request

There should be an NBT tag for the segment to spawn either with one head or three heads when you summon it. /summon witherstormmod:wither_storm_segment ~ ~ ~ {HeadAmount:X}. You can either put in 1 or 3.

**Comment by TaintedBlock** [comment]
technically you can choose the heads with datapacks but yeah having to be able to choose to have one or 2 heads would be cool

**Comment by RepositoryLover** [comment]
> technically you can choose the heads with datapacks but yeah having to be able to choose to have one or 2 heads would be cool

I don’t think you can. Nonamecrackers2 said you can’t add mobs, duplicate, or edit mobs with datapacks. I don’t think you can choose the heads with datapacks either.

**Comment by TaintedBlockmObile** [comment]
> > technically you can choose the heads with datapacks but yeah having to be able to choose to have one or 2 heads would be cool
> 
> I don’t think you can. Nonamecrackers2 said you can’t add mobs, duplicate, or edit mobs with datapacks. I don’t think you can choose the heads with datapacks either.

You can. Sm644me did it with his datapack. He made a phase 4 wither storm have only one head

**Comment by nonamecrackers2** [comment]
``/summon witherstormmod:wither_storm_segment ~ ~ ~ {OtherHeadsDisabled:1b}`` should do the trick
