### ISSUE TITLE
Removing the two large tentacles from Phase 6/6.5

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#1820]
### Description of feature request

The name is pretty self-explanatory. Since it was bombed, I thought maybe removing the 2 large tentacles would show some addition on how damaged it got. [They will re-grow at Phase 7]

**Comment by Pandaboi25x** [comment]
Pretty sure this was suggested already

**Comment by Herobrine982950291** [comment]
same

**Comment by BluePineappleGuy** [comment]
> Pretty sure this was suggested already

yep, it was suggested at #923

**Comment by WitherBean** [comment]
So go back to the 1.16.5 wither storm?

**Comment by Herobrine982950291** [comment]
> So go back to the 1.16.5 wither storm?

Can you stop posting random stuff?

**Comment by WitherBean** [comment]
> > So go back to the 1.16.5 wither storm?
> 
> Can you stop posting random stuff?

Since when did I post random stuff?
