### ISSUE TITLE
[Bug]: Flaming Skulls lag behind when deflected

### ISSUE THREAD

**Issue by TaintedBlockmObile** [nonamecrackers2/crackers-wither-storm-mod#1821]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

Any version that works with cwsm

### Describe the bug

This is for both 1.19.4 and 1.20.1. the wither skulls kinda lag behind and don't smoothly turn all the way around when deflected. It looks like they are teleporting a bit. Try and deflect a wither skull from a distance and you'll see what I mean.

### Steps to Reproduce

1. Let a wither storm shoot a wither skull
2. Attack the wither skull with any sword
3. See error

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM

**Comment by Herobrine982950291** [comment]
same happens to me

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
