### ISSUE TITLE
[Bug]: How to summon withered symbiont with withered beacon?

### ISSUE THREAD

**Issue by tvpv2** [nonamecrackers2/crackers-wither-storm-mod#1825]
### Minecraft Version

1.19.4

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

45.2.0

### Describe the bug

Bro i'm really don't know do this. What meaning Lvl 4 beacon?

### Crash Reports/Logs

Null

### Is OptiFine installed?

- [X] OptiFine is installed

### Screenhots

![SAVE_20240329_165652](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/151381538/f55c6c68-fe4b-488b-91cc-74a2241615f6)

### Mod List

Only cwsm

**Comment by Pandaboi25x** [comment]
2 withered fleshes 2 withered bones and 1 wither skull to resummon the withered symbiont and your beacon needs to look like this
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/efb5831f-68d3-48e9-9205-261f91871057)
next time you should join the official discord server or ask in the github discussion chat

**Comment by TaintedBlockmObile** [comment]
You should go to the discord to ask this. There is also a guide that shows you how to do this

**Comment by BluePineappleGuy** [comment]
if you need recipe help you can use JEI

**Comment by WitherBean** [comment]
How is this a bug?

**Comment by NinjaSam5399** [comment]
cool 10/10 bug report.
