### ISSUE TITLE
[Bug]: ItemPhysic Full Causes Immediate Crash 

### ISSUE THREAD

**Issue by NyxBornee** [nonamecrackers2/crackers-wither-storm-mod#1827]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

Immediate crash on startup

### Steps to Reproduce

Immediate crash on startup
Latest log line
[pool-4-thread-1/WARN]: @Redirect conflict. Skipping itemphysic.mixins.json:ItemEntityMixin->@Redirect::setDeltaMovementRedirect(Lnet/minecraft/world/entity/item/ItemEntity;Lnet/minecraft/world/phys/Vec3;)V with priority 1000, already redirected by witherstormmod.mixins.json:MixinItemEntity->@Redirect::tick_makeItemFloatInVoid(Lnet/minecraft/world/entity/item/ItemEntity;Lnet/minecraft/world/phys/Vec3;)V with priority 1000

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

[witherstormmod-1.20.1-4.0.1.1.jar]
[ItemPhysic_FORGE_v1.7.0_mc1.20.1.jar]
[CreativeCore_FORGE_v2.11.25_mc1.20.1.jar] (required for ItemPhysic)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
