### ISSUE TITLE
[Suggestion]: Config option to reuse the old battle music for the Withered Symbiont

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1828]
### Blast from the Past?

If I remember correctly, before we got Bound by Darkness as the theme for the Withered Symbiont, there was a previous theme for the Symbiont in the older versions of CWSM. This theme has been removed since Bound by Darkness became the new theme for the Symbiont.

While I do agree the new theme is better, I thinking having a config to re-enable the old Wither Symbiont theme would be a nice way to preserve CWSM history of what was once there. A nice nod to those who stuck with CWSM from the beginning.

**Comment by TSEG6** [comment]
You can do it with your own resource pack

**Comment by BluePineappleGuy** [comment]
you can do this with a resource pack by going into the file resources of the old versions of the mod.
also duplicate

**Comment by ghost** [comment]
> you can do this with a resource pack by going into the file resources of the old versions of the mod. also duplicate

Which issue?

**Comment by nonamecrackers2** [comment]
I'd like to keep as much music I don't technically have the rights to use out of the mod as possible, in case of issues. You can re-add if you'd like with a resource pack.

**Comment by BluePineappleGuy** [comment]
> > you can do this with a resource pack by going into the file resources of the old versions of the mod. also duplicate
> 
> Which issue?

sorry, forgor to respond earlier, the issue was #1162
