### ISSUE TITLE
[Bug]: Why doesn't Wither Storm's music play even though I enable the option to play the music?

### ISSUE THREAD

**Issue by eccentricbald** [nonamecrackers2/crackers-wither-storm-mod#1829]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Describe the bug

the music don´t play even i enable the option

### Steps to Reproduce

1.enable the WS music
2. spawn WS
3. the music don´t play

### Is OptiFine installed?

- [X] OptiFine is installed

### Mod List

none

**Comment by WitherBean** [comment]
Turn jukebox sounds on

**Comment by nonamecrackers2** [comment]
^ This
