### ISSUE TITLE
Dark sky in phase 4 and above

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#183]
Since the normal wither already makes the sky a bit darker, i think this should be a thing here, too.
Especially in phase 4 and above where this huge thing is around. 
In phase 7 it currently looks "boring" like this:
![Bright Sky](https://user-images.githubusercontent.com/106488797/177832108-14e47e31-c633-403d-bb9f-64e05ae401aa.png)
While it could look scary like this:
![Dark Sky](https://user-images.githubusercontent.com/106488797/177832214-5f40ff0e-8450-49b7-8503-ef2ba6d04bf9.png)

An optional (changeable in the config) thunderstorm at the very end of phase 7 would also be a nice idea.

**Comment by RandomGithubUser32** [comment]
The wither storm does not seem to darken the sky in phase 4.

**Comment by watersofnazareth** [comment]
Implemented as of the Prereleases
