### ISSUE TITLE
[Suggestion]: Add splashes to the title screen

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1830]
### Description of feature request

Considering how many things this mod adds, I'm surprised that splashes were never thought of. Perhaps wait until Evolution 2 to do this for the most ideas, but inside jokes from CMC and MCSM would fit perfectly. Ideas include:

Waga Baga Bobo!
You could say Juan has no rizz
Also try Explorer's Eve!
Also try WitherBean's WS Tweaks!
Also try CWSM Plus!
Also try CMC Tool Expansion!
Also try (Insert any decently popular addon to CWSM here!)
Jimmy!
Symbiote or Symbiont?
You can outrun it on foot!
Useless tentacles included!
Elixir not included!

Please suggest more ideas below.

**Comment by ghost** [comment]
Also try Manjac's Wither Storm :trollface:

**Comment by nonamecrackers2** [comment]
I actually really like these, don't mind if I add some of them

**Comment by FireCode125** [comment]
“Remember Thomas?”
And also,
“Is that the fucking wither’s bane”

**Comment by juanelgamer456** [comment]
"hue."

"@quandale_dingle do not send unsolicited-"

**Comment by Aimyx** [comment]
"Fresh Animations Pack Compatibility Jumpscare"

**Comment by ghost** [comment]
> “Remember Thomas?” And also, “Is that the fucking wither’s bane”

No swearing in Minecraft.

**Comment by juanelgamer456** [comment]
"animated/functional tentacles when"

"do not join D&C"

**Comment by Herobrine982950291** [comment]
confirmed? Looks like more of those weird splash text will come

**Comment by WitherBean** [comment]
> ### Description of feature request
> Considering how many things this mod adds, I'm surprised that splashes were never thought of. Perhaps wait until Evolution 2 to do this for the most ideas, but inside jokes from CMC and MCSM would fit perfectly. Ideas include:
> 
> Waga Baga Bobo! You could say Juan has no rizz Also try Explorer's Eve! Also try WitherBean's WS Tweaks! Also try CWSM Plus! Also try CMC Tool Expansion! Also try (Insert any decently popular addon to CWSM here!) Jimmy! Symbiote or Symbiont? You can outrun it on foot! Useless tentacles included! Elixir not included!
> 
> Please suggest more ideas below.

this sounds good!

**Comment by WitherBean** [comment]
In the meantime, I will add this to my datapack.

**Comment by BluePineappleGuy** [comment]
a good one would be "Read the guidelines"
as a reference to the amount of invalid issues

**Comment by GrandmaPork** [comment]
^ and "Invalid" in red

**Comment by Herobrine982950291** [comment]
> In the meantime, I will add this to my datapack.

Your datapack does not work

**Comment by WitherBean** [comment]
> > In the meantime, I will add this to my datapack.
> 
> Your datapack does not work

I don't want to keep saying this, but it does work.

**Comment by Herobrine982950291** [comment]
> > > In the meantime, I will add this to my datapack.
> > 
> > 
> > Your datapack does not work
> 
> I don't want to keep saying this, but it does work.

hahahah! good one!

**Comment by RepositoryLover** [comment]
I got one: Segments are Love! Segments are Life!

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release

**Comment by juanelgamer456** [comment]
cracker would we be able to suggest splash texts? if yes, where?

**Comment by nonamecrackers2** [comment]
Just here

**Comment by VillagerN4** [comment]
Splash suggestion:
Also try Fresh Wither Storm!

**Comment by Pandaboi25x** [comment]
Also Try Tainted's Accurate Wither Storm!

**Comment by pinkygrocket** [comment]
More splash suggestions:

* Also try FTB Inferno!
* Also try Chocolate Edition!
* King of the monsters! (in reference to Godzilla, since the Wither Storm is also a kaiju)
* Tractor beams stealing cows! (in reference to the cliche of aliens using ufo tractor beams to steal cows)
* Current Wither reports indicate incoming storms! (wither/weather report pun)
