### ISSUE TITLE
[Bug]: Help, i think wither storm turned gey, but seriously why is this happening?

### ISSUE THREAD

**Issue by Gintas2002** [nonamecrackers2/crackers-wither-storm-mod#1831]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.21

### Describe the bug

he is pink, and I see hearts for some reason, I'm playing on a huge mod pack made by me, and adding wither storm mod, withers storm is like this wth?

### Steps to Reproduce

Just summoned wither storm 

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

https://imgur.com/a/pHDBGfY

### Mod List

Too many to name, its 182 mods.

**Comment by GearsawStudios** [comment]
https://minecraft.wiki/w/Pink_Wither#Three_Heads

**Comment by C-4-N** [comment]
april fools

**Comment by TaintedBlock** [comment]
april fools LMAO

**Comment by Pandaboi25x** [comment]
LOL

**Comment by Gintas2002** [comment]
> april fools LMAO

oh, lol, that makes sense i guess

**Comment by FireCode125** [comment]
april foul

**Comment by BluePineappleGuy** [comment]
this is still too funny
