### ISSUE TITLE
[Suggestion]: Reuben picks up command block tools in his mouth similar to an allay

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1833]
### Description of feature request

This has a high chance of getting denied but as an easter egg, if you drop your command block weapon around a reuben he'll try and bring it back to you. *The irony* hehehhee

**Comment by GearsawStudios** [comment]
Should treat its pathfinding as immune to fall damage and ignore falling.

**Comment by WitherBean** [comment]
He could also be like a pet (following you around).

**Comment by nonamecrackers2** [comment]
Closing this since it’s against the guidelines, although I kinda like the idea

**Comment by TaintedBlock** [comment]
rip
