### ISSUE TITLE
[Suggestion]: add fire snake

### ISSUE THREAD

**Issue by respear** [nonamecrackers2/crackers-wither-storm-mod#1834]
### Description of feature request

add a fire snake that attacks you while fighting the withered symbiont

![fireimage](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/99116475/76af4270-c4c4-4b5a-a943-a131e30e19c7)

**Comment by FireCode125** [comment]
FIRE SNAKE 🗣🔥🐍

**Comment by WitherBean** [comment]
This makes no sense.

**Comment by WitherBean** [comment]
It's not even April Fools anymore either...

**Comment by TheEyeOfGaming** [comment]
I think he means like a path of fire particles that follow you? idk

**Comment by NinjaSam5399** [comment]
How about withered snake

**Comment by BluePineappleGuy** [comment]
please explain what the heck is a snake

**Comment by nonamecrackers2** [comment]
Personally doesn’t seem like a very good symbiont attack to me, interesting idea though

**Comment by FireCode125** [comment]
> Personally doesn’t seem like a very good symbiont attack to me, interesting idea though

Bro doesn’t know 😭

**Comment by nonamecrackers2** [comment]
Don’t worry I’m well aware of what mod it was from

**Comment by BluePineappleGuy** [comment]
> Don’t worry I’m well aware of what mod it was from

wait what mod

now i wanna find and check it out

**Comment by WitherBean** [comment]
> > Don’t worry I’m well aware of what mod it was from
> 
> wait what mod
> 
> now i wanna find and check it out

it's probably the cwsm ripoff, manjack's wither storm.
