### ISSUE TITLE
[Bug]: Wither Sickness Layer doesn't show up on third person view with 3D Skin Layers

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1838]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.19

### Describe the bug

The Wither Sickness Layer does not show up in third person when 3D Skin Layers is installed alongside CWSM.
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/148708399/9b14e3ff-80df-477b-b1d5-2cec799948b9)

Strangely however, the wither sickness layer is still visible in the menu:
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/148708399/88ff91ab-7145-4338-bda0-f6f034e5e84c)

### Steps to Reproduce

1. Have 3D Skin Layers and CWSM installed
2.  Obtain Wither Sickness
3. Wait for the sickness layer to appear (or not)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

	- additional_enchantments 1.1.2
	- additionaladditions 6.0.1
	- advancementplaques 1.4.10
	- alexsmobs 1.22.8
	- alternategunpowder 1.0.0-1.20.1
	- architectury 9.2.14
	- autohud 6.3.4+1.20.1
	- better_beacons 2.0.0
	- better_weaponry 1.0.0
	- betterendisland 1.20-Forge-2.0.6
	- betterf3 7.0.2
	- bettermineshafts 1.20-Forge-4.0.4
	- bulletsboats 0.0.6-1.20.1
	- cataclysm 1.0
	- cerbons_api 1.1.0
	- citadel 2.5.4
	- cloth_config 11.1.118
	- collective 7.40
	- curios 5.7.2+1.20.1
	- dimdungeons 191
	- do_a_barrel_roll 3.5.3+1.20.1
	- dynamiccrosshair 7.4.4+1.20
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- ebb 1.0.0
	- elytra_physics 2.0
	- embeddium 0.3.11+mc1.20.1
	- embeddiumplus 1.2.5
	- enchantinginfuser 8.0.2
	- entity_model_features 1.3
	- entity_texture_features 5.2.3
	- everycomp 1.20-2.6.40
	- experimentalsettingsdisabler 3.0
	- forge 47.2.19
	- forgeconfigscreens 8.0.2
	- geckolib 4.4.4
	- hearths 1.0.0-mc1.20u1.20.1
	- hole_filler_mod 1.2.8
	- iceberg 1.1.21
	- immersive_weathering 1.20.1-2.0.1
	- invtweaks 1.0.0
	- jei 15.3.0.4
	- leavesbegone 8.0.0
	- leawind_third_person 2.0.8-beta.5
	- minecraft 1.20.1
	- mixinextras 0.2.0-beta.8
	- mixinsquared 0.1.1
	- mobbattle 1.20.1-2.4.7
	- moonlight 1.20-2.11.9
	- mousetweaks 2.25
	- mr_dungeons_andtaverns 3.0.3
	- mr_limesplatus_ending 1-v1.1.0c
	- nckey 1.0.0
	- noisium 2.0.0+mc1.20.x
	- oculus 1.6.15a
	- paddedelytras 1.20-1.0
	- palladiumcore 1.20-2.0.0.0
	- playeranimator 1.0.2-rc1+1.20
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.18
	- reeses_sodium_options 1.0.4
	- rubidium 0.7.1
	- sculkhorde 1.20.1-0.9.0-Beta4
	- skinlayers3d 1.6.2
	- smallships 2.0.0-b1.1
	- spectrelib 0.13.15+1.20.1
	- spyglass_of_curios 1.7.2
	- stepitup 2.0.1-1.20.1
	- textrues_embeddium_options 0.1.5+mc1.20.1
	- treeharvester 8.7
	- universalenchants 8.0.0
	- vc_gliders 1.1.5
	- veinmining 1.4.0+1.20.1
	- witherstormmod 4.0.1.1
	- yaclx 1.10
	- yungsapi 1.20-Forge-4.0.4
	- yungsmenutweaks 1.20.1-Forge-1.0.2

**Comment by Santiagonosequeaserxd** [comment]
That Fire

**Comment by nonamecrackers2** [comment]
Appears to be working fine for me. Mind sending a zip file of your mod list for me to test?

**Comment by ghost** [comment]
I'll give you the mod list after a final I have to take.
Which is Wednesday, 1:30 PM.

**Comment by nonamecrackers2** [comment]
No rush at all

**Comment by ghost** [comment]
> No rush at all

https://drive.google.com/file/d/1ylkw_5ROCLWvLu4ew9PEQhevYYueGKCk/view?usp=sharing
[datapacks.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15101688/datapacks.zip)
[resourcepacks.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15101697/resourcepacks.zip)

Here's almost all the mods I used in the mod list, but it still should still give the same bug I've been having. I've also included the datapacks and resourcepacks for good measure in case those cause the bug somehow.

**Comment by Leawind** [comment]
Try disable player fade out in config of leawind's third person

**Comment by nonamecrackers2** [comment]
I investigated the issue. It appears this combination of these mods causes the problem:

Cracker's Wither Storm Mod (4.0.1.1)
Architectury API 9.2.14
Embeddium 0.3.28
Leawind's Third Person 2.0.9-beta
Oculus 1.7.0
Skin Layers 3D 1.6.6

Removing either Oculus or Skin Layers 3D fixes this issue from my testing. Weirdly enough, the wither sickness layer shows depending on what you have in your hand, but it's incredibly inconsistent (edit: sometimes it doesn't render at all): https://youtu.be/Mlb7AvUE0zA

Regardless, I'm not sure what is causing the issue exactly between any of these mods. It does not appear to be anything that CWSM is doing. You could try reporting this issue to Oculus, since they seem to be the biggest culprit. Otherwise this isn't a major issue, so I'll be closing this as resolved.
