### ISSUE TITLE
[Suggestion]: Weather Change

### ISSUE THREAD

**Issue by Kyleo3345** [nonamecrackers2/crackers-wither-storm-mod#1839]
### Description of feature request

I think it would be awesome to have the weather change from clear to rain and from rain to thunder due to how far the wither storm is.

Example: If the Wither storm is 3,000 blocks away, the weather will change from clear to rain and if the Wither Storm is 1,000 blocks away, the weather will change from rain to thunder.

**Comment by TaintedBlock** [comment]
For your 2nd suggestion, read the guidelines. Crackers doesn't plan to do anything with the tentacles

**Comment by Kyleo3345** [comment]
> For your 2nd suggestion, read the guidelines. Crackers doesn't plan to do anything with the tentacles

Oh.
I mean it is an suggestion though.
He may or may not do it in future updates. But I respect his choices.

**Comment by GrandmaPork** [comment]
It’s been suggested 100x before. I recommend reading guidelines and double checking in the search bar if it’s been suggested already

**Comment by BluePineappleGuy** [comment]
> It's been suggested 100x before.

no, it actually hasn't. he is asking that the weather change depending on
storm distance but the other weather related suggestions are about
withering it or other weather behavior modifications

**Comment by FrozenDragon0** [comment]
> It's been suggested 100x before.
> no, it actually hasn't. he is asking that the weather change depending on storm distance but the other weather related suggestions are about withering it or other weather behavior modifications



He was referring to the tentacles suggestion, that has been suggested non-stop.

**Comment by BluePineappleGuy** [comment]
> He was referring to the tentacles suggestion, that has been suggested non-stop.

ah sorry, was cleaning out my email when i saw that and email notifications don't show edits to posts.

**Comment by WitherBean** [comment]
> ### Description of feature request
> I think it would be awesome to have the weather change from clear to rain and from rain to thunder due to how far the wither storm is.
> 
> Example: If the Wither storm is 3,000 blocks away, the weather will change from clear to rain and if the Wither Storm is 1,000 blocks away, the weather will change from rail to thunder.
> 
> Also could the tentacles have more movement and interaction like in MCSM? If you are working on that in the Evolution Part 2 update, then awesome!

I am pretty sure that you are only allowed to do one suggestion per github suggestion.

**Comment by nonamecrackers2** [comment]
Weather is global, so this wouldn't really work. As one player got closer, it would start raining for everyone else.
