### ISSUE TITLE
Remains after final death

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#184]
After finally killing the Stage 7 witherstorm, add some remains (Bodyparts made of tainted (flesh) blocks) on the ground like the fake death of phase 5 has them. Could also be combined with the rib cage holding the withered nether star (except for the command block), so we can pick it up there instead of it floating somewhere like in the 1.16.5 version or being added to our inventory like in the 1.18.2 version.

**Comment by Asteroid4** [comment]
Maybe some of the blocks from the bowels could be some of the clusters too!

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
