### ISSUE TITLE
[Suggestion]: Wither Storm Resummoning Tweak

### ISSUE THREAD

**Issue by C-4-N** [nonamecrackers2/crackers-wither-storm-mod#1840]
### Description of feature request

Wither Storm's Resummoning should be Tweaked as: It should change phase according to how many Beacons we Placed. Like When Fully Completed Level 4 Beacon, It Should summon the Storm at Phase 4 and when we just placed Withered Beacon on the ground without any Lapis Block under, it should summon the Storm at Phase 0, etc.

**Comment by RepositoryLover** [comment]
You actually don’t need lapis blocks at all.

**Comment by C-4-N** [comment]
> You actually don’t need lapis blocks.

i know, that's not what i meant

**Comment by nonamecrackers2** [comment]
Interesting idea but this might be hard to communicate with players and may cause players to summon Wither Storm's at accidental phases.
