### ISSUE TITLE
[Bug]: formidibomb

### ISSUE THREAD

**Issue by rjdxxxxxccc** [nonamecrackers2/crackers-wither-storm-mod#1842]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.21

### Describe the bug

What's wrong with not being attracted to wither storm?

### Steps to Reproduce

Use flint and steel to light formidibomb on fire，and wait until it explodes without being sucked up.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

none

**Comment by TaintedBlock** [comment]
what phase is the storm in

**Comment by rjdxxxxxccc** [comment]
The fifth stage

**Comment by Herobrine982950291** [comment]
is it phase 5.5 or phase 5 or phase 5.3

**Comment by GearsawStudios** [comment]
Can confirm, Formidibomb behavior is still inconsistent and it might be missed if a block cluster drops in into a cave or water.

**Comment by nonamecrackers2** [comment]
Can you possibly share a video of the problem? Screenshots should work as well.

**Comment by rjdxxxxxccc** [comment]
already solved
