### ISSUE TITLE
Tradicion

### ISSUE THREAD

**Issue by Hawkmanres** [nonamecrackers2/crackers-wither-storm-mod#1843]
### Description of feature request

Agregar como bot ayudante a unos de los personajes de modo historia

**Comment by GearsawStudios** [comment]
Note: This is has no reasoning and isn’t in English. Please use a translator before posting.

**Comment by juanelgamer456** [comment]
to be fair there wasn't a rule about language but the suggestion is still invalid anyway
anyway, in case anyone wants to know, this guy is suggesting a helper bot named after, and with the personality of, a character from mcsm
not sure if he means for the mod or the discord server

**Comment by WitherBean** [comment]
This is the wrong mod for that.

**Comment by nonamecrackers2** [comment]
Sorry we only accept suggestions in English
