### ISSUE TITLE
[Suggestion]: Distant sounds/Muffed sounds

### ISSUE THREAD

**Issue by lelenski** [nonamecrackers2/crackers-wither-storm-mod#1847]
### Description of feature request

Make it so when your are far away from the wither storm you can sometimes hear the wither storm roars echoing in the distance

Also another suggestion i thought of is when you are in a cave the wither storm sounds are muffled.

**Comment by GearsawStudios** [comment]
The second suggestion would have to be its own post.

**Comment by TaintedBlock** [comment]
If you're looking for the first suggestion, you should play Cracker's Wither Storm Plus :trollface:

**Comment by Pandaboi25x** [comment]
Distant sounds were already suggested

**Comment by nonamecrackers2** [comment]
#1224. Also, only one suggestion per issue as per the contributing guidelines.
