### ISSUE TITLE
Falling through cmdblock platform

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#185]
Minecraft version: 1.18.2
Mod version: 2.0.1

When the command block's platform moves up, one doesn't get kicked away like before, but falls through the platform now.

1. Get into bowels of phase 7 wither storm.
2. Hit the command block and stay on the platform.

**Comment by nonamecrackers2** [comment]
This is as intended, adding physics to block clusters was not worth my time, which is why the tentacles will knock you off. They won't do so however if you're not in survival

**Comment by ghost** [comment]
"Not worth my time" this is literally one of the best and most detailed mods i've seen, i don't even want to know how long this took you! But yeah i realised that the problem was me being in creative. Thanks!

**Comment by nonamecrackers2** [comment]
Np!
