### ISSUE TITLE
Make the wither storm chase after mobs, instead of players

### ISSUE THREAD

**Issue by GroxDots** [nonamecrackers2/crackers-wither-storm-mod#1850]
### Description of feature request

Mobs should have much a higher priority than players. If a mob attacks and the attack lands on the wither storm, that mob should instantly be targeted by the wither storm.

**Comment by RepositoryLover** [comment]
> ### Description of feature request
> Mobs should have much a higher priority than players. If a mob attacks and the attack lands on the wither storm, that mob should instantly be targeted by the wither storm.

It can be feature, but not by default.

**Comment by BluePineappleGuy** [comment]
I think this would be a bad idea to do for the entire storm, but maybe give each head its own priority:
- Main head: heavily prioritizes the player
- Second head: prioritizes large groups of mobs to grow the storms mass
- Third head: current behavior

**Comment by nonamecrackers2** [comment]
Players will always have more priority since otherwise the Wither Storm will rarely be a threat to players. If it doesn’t chase them it removes one of the core fundamentals of the mod.
