### ISSUE TITLE
[Suggestion]:Withered pollution

### ISSUE THREAD

**Issue by CautiousBerry92** [nonamecrackers2/crackers-wither-storm-mod#1851]
### Description of feature request

When Wither Storm is in Phase 4 or any later phase, whenever he takes heavy damage from one or more TNT or Creeper explosions, there is a chance that he will lose his flesh (such as when he dies), and his flesh will disperse. , releasing a radiation wave of the "Withering Disease" effect.  This radiation wave would cause the blocks or Mobs within that wave to wither.  Furthermore, when the Wither Storm dies and all of its flesh is scattered, this flesh would release a large wave of radiation.

**Comment by TaintedBlockmObile** [comment]
This seems really out of scope. And more like nuclear wither sickness or something

**Comment by CautiousBerry92** [comment]
I have seen in some blocks or Mobs that you have a violet light resulting from Wither Sickness, practically a moderately nuclear disease or rather a rare and unique disease 

> Esto parece realmente fuera de alcance. Y más bien como enfermedad nuclear o algo así.

**Comment by BluePineappleGuy** [comment]
i think the heads should have different targets: one head will act as it
does now, attempting to target the player when possible. another head will
target mobs over the player, and the third will target whichever last hurt
the storm or a withered entity. with segments it would be storms rather
than heads

**Comment by nonamecrackers2** [comment]
Interesting idea but this out of scope for the mod
