### ISSUE TITLE
[Bug]: Wither Storm doesn't load chunks when no players are in different Dimensions

### ISSUE THREAD

**Issue by IndigoAmethyst** [nonamecrackers2/crackers-wither-storm-mod#1852]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

From memory I don't remember this being a thing in past versions. I only just noticed this since I don't Nether camp much, and I just decided to do /witherstormmod chunkloader get @w and thats when it hit me.

Note: This was done on a server

### Steps to Reproduce

1. On a server, summon the Wither Storm, and go into the nether
2. Run /witherstormmod chunkLoader get @w 
3. See results

### Crash Reports/Logs

https://mclo.gs/LhkZlr2

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

- Embeddium
- Ender Trigon
- Essential (WE WERE **NOT** USING THIS TO HOST THE SERVER)
- JEI
- Proximity Text Chat
- Simple Voice Chat
- CWSM

**Comment by BluePineappleGuy** [comment]
Do you mean some people were in the nether and some in the overworld, or everyone in same dimension?

**Comment by IndigoAmethyst** [comment]
All online were in the Nether 

As far as I am concerned this wasn't supposed to happen

**Comment by nonamecrackers2** [comment]
This is a known bug and will be fixed in the next update.
