### ISSUE TITLE
[Bug]: You can track players when their invis with the amulet

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1855]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

Not on pc :pensive:

### Describe the bug

Idk if this is really intentional but yeah

### Steps to Reproduce

Title explains itself

### Crash Reports/Logs

Nuh

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

Not on pc

### Mod List

Pretty sure cwsm does this alone

**Comment by Herobrine982950291** [comment]
Well DUH! The amulet is supposed to alarm the Storm of your prescence/Location.

**Comment by Pandaboi25x** [comment]
> Well DUH! The amulet is supposed to alarm the Storm of your prescence/Location.

what? im not talking about the wither storm im talking how the players can track you with the amulet even tho your on invis potion, like i said idk if this is intentional or not

**Comment by Herobrine982950291** [comment]
> > Well DUH! The amulet is supposed to alarm the Storm of your prescence/Location.
> 
> what? im not talking about the wither storm im talking how the players can track you with the amulet even tho your on invis potion, like i said idk if this is intentional or not

80% chance of being intentional

**Comment by nonamecrackers2** [comment]
This is intended

**Comment by Pandaboi25x** [comment]
👍
