### ISSUE TITLE
Regular Mobs spawn inside the Witherstorm

### ISSUE THREAD

**Issue by ShirakiShio** [nonamecrackers2/crackers-wither-storm-mod#186]
**Minecraft version**
1.18.2

**Mod version**
Initial (Full) Release version.

**Describe the bug**
Self explanatory. A bunch of mobs spawn inside

**To Reproduce**
Eat pant and player

**Crash Reports / Logs**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/48332495/177860586-57d0cb14-f30c-4536-9591-6f70efaa7baf.png)

**Comment by nonamecrackers2** [comment]
Yeah I'm unable to reproduce. Are you able to with different worlds / bowel structures?
