### ISSUE TITLE
[Suggestion]: Ability to change tractor beam colors depending on the day like halloween

### ISSUE THREAD

**Issue by TaintedBlockmObile** [nonamecrackers2/crackers-wither-storm-mod#1860]
### Description of feature request

Title says it all really. It would make sense

**Comment by nonamecrackers2** [comment]
A very specific feature that I don't feel would be worth the time to implement for only a handful of people to use. Also, I can only imagine you'd use this to add your own easter eggs which I'd prefer to let only us developers add.

**Comment by TaintedBlockmObile** [comment]
Ah well, fair enough. It was worth a shot
