### ISSUE TITLE
[Bug]: Holes in Phase 6 Model

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1865]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.20

### Describe the bug

A bug happened! The Wither Storm phase 6 model has holes in it! Below are 2 screenshots of the issue!

### Steps to Reproduce

1. Summon Phase 6 WS
2. Go to the right-hand side ripped area
3. See error

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-04-20_14 10 49](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/0c79d728-52d7-451e-8518-3fa25e7bb39d)
![2024-04-20_14 11 11](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/61c2ec78-8f1d-4de7-9c5d-e444b9e45b88)

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/eecda351-8295-4cc5-ae62-25c704fdf788)

**Comment by GearsawStudios** [comment]
Wither Storm gonna deflate 💀

**Comment by Herobrine982950291** [comment]
> Wither Storm gonna deflate 💀

XDDCC

**Comment by TaintedBlockmObile** [comment]
It's a fake! The wither storm wasn't as dangerous as we thought!

**Comment by watersofnazareth** [comment]
This is technically intended and not a bug #625

**Comment by Herobrine982950291** [comment]
> It's a fake! The wither storm wasn't as dangerous as we thought!

It was all a trick! Phew!

> This is technically intended and not a bug #625

Incorrect.... *swings Lightsaber at the fuzz*
