### ISSUE TITLE
[Suggestion]: Drowned and Storm behavior update

### ISSUE THREAD

**Issue by RepositoryLover** [nonamecrackers2/crackers-wither-storm-mod#1866]
### Description of feature request

Have the Drowned run away from the Wither Storm and the Wither Storm attack it (when the player is in creative or far away/at a certain distance).

**Comment by WitherBean** [comment]
This should already happen.

**Comment by RepositoryLover** [comment]
> This should already happen.

No, it doesn't. Try spawning a Drowned near a Wither Storm when there are no other mobs and see for yourself.

**Comment by WitherBean** [comment]
> > This should already happen.
> 
> No, it doesn't. Try spawning a Drowned near a Wither Storm when there are no other mobs and see for yourself.

It picks them up

**Comment by RepositoryLover** [comment]
> > > This should already happen.
> > 
> > 
> > No, it doesn't. Try spawning a Drowned near a Wither Storm when there are no other mobs and see for yourself.
> 
> It picks them up

It still doesn't shoot wither skulls at it when it's in Phase 0 or 1.

**Comment by nonamecrackers2** [comment]
Seems like this is a bug, should be able to target them. I'd make a new issue as such

**Comment by RepositoryLover** [comment]
> Seems like this is a bug, should be able to target them. I'd make a new issue as such

Yeah, but the Drowned doesn't run away.

**Comment by BluePineappleGuy** [comment]
> > Seems like this is a bug, should be able to target them. I'd make a new issue as such
> 
> Yeah, but the Drowned doesn't run away.

that is also a bug, you should open a bug report for that
