### ISSUE TITLE
[Bug]: Wither Storm Flashes in distance - even in V4.0.1.1

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1868]
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.30

### Describe the bug

A bug happened! The same bug seen in 1.19.3, when moving around, the storm flashes in distance. Don't count this as a duplicate as the original issue was assigned to 1.19.3.

### Steps to Reproduce

1. Summon WS
2. Tp faraway
3. move around

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/4a785954-5de1-4e94-9ea2-d32d15db664a

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/b9c1c0e8-d6c6-4a67-8cc4-4ec8f2fbb158)

**Comment by Resuster** [comment]
i have a feeling its because of optifine

**Comment by nonamecrackers2** [comment]
This is because of vivecraft. In the mean time, if you're not using VR you'll have to remove that mod

**Comment by Herobrine982950291** [comment]
OK fine...

**Comment by Luke7381** [comment]
I swear dude your like a magnet for bugs or something.

**Comment by Herobrine982950291** [comment]
> I swear dude your like a magnet for bugs or something.

XDDCC

**Comment by nonamecrackers2** [comment]
Should be fixed in the next major release

**Comment by Herobrine982950291** [comment]
yay!
