### ISSUE TITLE
Different fake death fall

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#187]
When bombing the phase 5 wither storm with the F Bomb, the small parts will fall while one is blinded and then the big one falls while the whitescreen fades away.
Because the way the big one falls down looks a bit awkward (just falls down and then tips over to the back), i think it would look better if that happened while one is still blinded and then let the small ones fall when the whitescreen fades away. And it might fix the timing for the tainted (flesh) blocks and the ribcage spawning, too.

**Comment by ghost** [comment]
Sorry for submitting so many issues, but i'm obsessed with this mod and trying so many things now

**Comment by nonamecrackers2** [comment]
I think it's fine as it is, and watching the main wither storm fall on it's back is quite fun to watch (in my opinion). Changing it wouldn't be very noticeable anyway as well
