### ISSUE TITLE
[Suggestion]: Iron Golem Transformation

### ISSUE THREAD

**Issue by rjdxxxxxccc** [nonamecrackers2/crackers-wither-storm-mod#1871]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Iron golems cannot be converted into sickened iron golems in the mod

**Comment by WitherBean** [comment]
why not?

**Comment by Aimyx** [comment]
I this might be a false suggestion and is prolly an attempt at a bug report

**Comment by watersofnazareth** [comment]
This is intended assuming you mean that Golems aren't converted by sickness

**Comment by rjdxxxxxccc** [comment]
Yes, there is only this module in version 1.20.1, and iron golems still cannot be transformed.

**Comment by nonamecrackers2** [comment]
This is intended. They're a fairly special mob, so they can only be summoned using a tainted pumpkin instead of normal one on the iron golem summoning structure.

**Comment by rjdxxxxxccc** [comment]
It cannot be cured into iron golems, like zombie villagers can be cured into villagers.
