### ISSUE TITLE
[Suggestion]: Elixir Concept

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1873]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I know the Elixir wasn't accepted, however i came up with a new idea that could work for the mod. Its not MCSM accurate but this mod isn't really aiming for accuracy.

During Phase 0-3 the elixir would have the ability to weaken the wither storm by slowing phase progression (weakening the wither storm's ability to absorb blocks), decrease the tractor beam pickup speed and making the wither storm move slower. The wither storm would also ignore the player that threw it for a few minutes. These effects would be temporary. This would allow players that are to slow with there resource gathering to have more time to gather things. But here is the catch, the wither storm will grow resistance to the elixir's effects each time its used on it, meaning that the time it takes for the wither storm to recover gets shorter, until the elixir no longer works.

Phase 4:
Since the command block is practically deep inside the WS body at this point, the elixir would not have any effect, no matter if the WS is resistant to it or not.

Other uses:
Since the elixir in MCSM was supposed to kill the wither storm and that the wither storm is a undead mob, its possible that the Elixir might've had some healing capabilities on other beings. So i think the elixir could also be a used as potion to give players and mobs health boost and high regeneration

CLOSED: Has quite a bit of flaws. Might open another one

**Comment by GearsawStudios** [comment]
Slowing phase progression in any form is rejected.

**Comment by TaintedBlock** [comment]
I'm curious as to how this would even benefit the player at all? I mean, ok, it slows progression (which already makes this suggestion not acceptable), but it can only be done in phase 0-3.. Those are the phases you are preparing so you can get to the nether, I don't see why anyone would use this if it wont even matter after phase 3. Especially since usually people are running at that point and no where near the wither storm. And, what is the benefit of slowing progression at all? That just kinda delays the inevitable and all around makes the waiting game to phase 5.5 longer.

**Comment by Luke7381** [comment]
> Slowing phase progression in any form is rejected.



> I'm curious as to how this would even benefit the player at all? I mean, ok, it slows progression (which already makes this suggestion not acceptable), but it can only be done in phase 0-3.. Those are the phases you are preparing so you can get to the nether, I don't see why anyone would use this if it wont even matter after phase 3. Especially since usually people are running at that point and no where near the wither storm.


I forgot that slowing progression is rejected. And i never really thought about this. 

I had a feeling there was gonna be many flaws but hey thats why we share ideas to see if its good or not. Im gonna leave it open just to see what crackers thinks but its probably gonna be rejected

**Comment by Luke7381** [comment]
I might try to think of another way to see if the "elixir" has any possible use in this mod, but it seems futile at this point.

**Comment by Luke7381** [comment]
Actually ima just close it. It seems pointless looking at it now.

**Comment by BluePineappleGuy** [comment]
Here's my concept: the elixir can work as a projectile command-block weapon during the bossfight. In stages 0-2, it could either transform the storm back into the spawn totem as a "I change my mind" kind of thing, or it could deal damage to the storm but not past half health and would "enrage" the storm, speeding up its world consumption and therefor its evolution to stage 4.
