### ISSUE TITLE
[Suggestion]: Pure forms or mobs similar to withered symbiont?

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1874]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

This might be a little out there so i understand if crackers don't agree with this one.

So basically with the fact that the wither storm can generate limbs, the command block being able to make parts of the wither storm come to life (fbomb phase) and the wither sickness getting bad to the point where infected can sprout tentacles and other appendages, i had a idea that the wither storm would be able to create pure forms with there own behavior and what not or just severely mutated mobs to the point of having there own abilities and not just a buffed skeleton or zombie.

EDIT: So im not trying to imply to turn this mod into a "infection mod" if you will. Basically I'm saying that there could be mobs similar to wither symbiont but "weaker" if you will, such as a symbiont creeper or a cow.

**Comment by TaintedBlockmObile** [comment]
Sounds like SRP but it starts with the wither storm lol

**Comment by GearsawStudios** [comment]
Out of scope.

**Comment by Luke7381** [comment]
> Sounds like SRP but it starts with the wither storm lol

atleast it won't be a unbalanced mess and don't have mobs constantly spawning everywhere (hopefully)

**Comment by GearsawStudios** [comment]
> > Sounds like SRP but it starts with the wither storm lol
> 
> atleast it won't be a unbalanced mess and don't have mobs constantly spawning everywhere (hopefully)

How do you expect this to be coded though?

**Comment by Luke7381** [comment]
> Sounds like SRP but it starts with the wither storm lol



> > > Sounds like SRP but it starts with the wither storm lol
> > 
> > 
> > atleast it won't be a unbalanced mess and don't have mobs constantly spawning everywhere (hopefully)
> 
> How do you expect this to be coded though?

I don't know?
Its just that i know that if crackers were to add this, more than likely hes gonna care about keeping the gameplay fun and balanced compared to the SRP developers.

**Comment by GearsawStudios** [comment]
That's a serious issue then, if you can't figure out how this system would work why would he add it due to its large scale? This would require a total rewrite of a mechanic and _many_ models. This isn't in the budget.

**Comment by BluePineappleGuy** [comment]
well, just pure witherstorm mobs would be kinda cool, maybe 2 of them as bossfight exclusives?

**Comment by TheChimcowMan** [comment]
eh, maybe a mob could have this but I'm not sure if a player having this would be accurate to well anything really. The command block cant exactly remote control you as the player just because you're calling in sick to stay home from school. Although I do like the idea of extra boss fights, ya gotta understand this is the wither disease we are talking about, it slowly kills you regardless of what mob you are. Which in itself can be a suggestion(sick mobs eventually dying) but its not exactly the point I'm trying to get at.  The player regardless of the gamemode or difficulty is the most powerful being in minecraft and just saying that the command block can mutate/control it doesn't really make a lota sense. And for the mobs, they'll just die before getting any kind of purity. I see what you were trying to do here though, so I recommend checking out the mods Skulk Horde and Fungal Infection:Spore (yes there isn't a space between the 2 dots and the letters)

**Comment by Luke7381** [comment]
> eh, maybe a mob could have this but I'm not sure if a player having this would be accurate to well anything really. The command block cant exactly remote control you as the player just because you're calling in sick to stay home from school. Although I do like the idea of extra boss fights, ya gotta understand this is the wither disease we are talking about, it slowly kills you regardless of what mob you are. Which in itself can be a suggestion(sick mobs eventually dying) but its not exactly the point I'm trying to get at. The player regardless of the gamemode or difficulty is the most powerful being in minecraft and just saying that the command block can mutate/control it doesn't really make a lota sense. And for the mobs, they'll just die before getting any kind of purity. I see what you were trying to do here though, so I recommend checking out the mods Skulk Horde and Fungal Infection:Spore (yes there isn't a space between the 2 dots and the letters)

I never stated that players can have this.



> That's a serious issue then, if you can't figure out how this system would work why would he add it due to its large scale? This would require a total rewrite of a mechanic and _many_ models. This isn't in the budget.

This doesn't have to be on the scale of SRP or any infection mod at all. However i will admit i never really thought about how this would work. I made this suggestion simply because of the appearance of the wither symbiont, which gave me a idea of how bad the wither sickness could be if the wither storm used it to its full potential for other mobs

**Comment by nonamecrackers2** [comment]
Interesting idea, but this is out of scope for the mod.
