### ISSUE TITLE
[Bug]: What happens if the command block still exists after it dies

### ISSUE THREAD

**Issue by rjdxxxxxccc** [nonamecrackers2/crackers-wither-storm-mod#1875]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.21

### Describe the bug

A bug happened!
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15127919/latest.log)

### Crash Reports/Logs

No crash report

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

	- ad_astra 1.15.18
	- ad_extendra 0.1.1
	- additionalentityattributes 1.4.0.5+1.20.1
	- ae2 15.1.1
	- aeroblender 1.20.1-1.0.1-neoforge
	- aether 1.20.1-1.4.0-neoforge
	- aether_redux 2.0.11
	- alexs_mobs_extra_music 1.0.0
	- alexscaves 1.1.4
	- alexscaves_torpedoes 1.0.2
	- alexsmobs 1.22.8
	- alexsmobsinteraction 2.3
	- amplifiednether 1.2.4
	- animal_feeding_trough 1.0.3+1.20.1-forge
	- apoli 1.20.1-2.9.0.6
	- appleskin 2.5.1+mc1.20.1
	- aquamirae 6.API15
	- aquamirae_mod_extra_music 1.0.0
	- architectury 9.2.14
	- ars_nouveau 4.10.0
	- athena 3.1.2
	- autotranslation 1.2.1
	- awesomedungeonend 3.1.1
	- balm 7.2.2
	- beekeeperhut 2.0.0
	- bendylib 4.0.0
	- betteradvancements 0.3.2.162
	- betterarcheology 1.1.8-1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.4
	- betterendisland 1.20-Forge-2.0.6
	- betterfortresses 1.20-Forge-2.0.6
	- betterjungletemples 1.20-Forge-2.0.4
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- bettersafebed 1.20-9
	- betterstrongholds 1.20-Forge-4.0.3
	- bettervillage 3.1.0
	- betterwitchhuts 1.20-Forge-3.0.3
	- biomesoplenty 18.0.0.598
	- blue_skies 1.3.31
	- bonfires 1.2.16
	- bookshelf 20.1.10
	- bosses_of_mass_destruction 1.1.2
	- botarium 2.3.3
	- bountiful 6.0.3+1.20.1
	- butterflies 3.4.0
	- bygonenether 1.3.2
	- caelus 3.2.0+1.20.1
	- calio 1.20.1-1.11.0.3
	- carryon 2.1.2.7
	- castle_dungeons 4.0.0
	- cataclysm 1.0
	- catalogue 1.8.0
	- cavedust 2.0.4
	- cerbons_api 1.1.0
	- chat_heads 0.10.32
	- chefsdelight 1.0.3-forge-1.20.1
	- chipped 3.0.6
	- chunkpregen 1.20-4.4.3
	- citadel 2.5.4
	- cloth_config 11.1.118
	- clumps 12.0.0.4
	- collective 7.50
	- configured 2.2.3
	- coroutil 1.20.1-1.3.7
	- corpse 1.20.1-1.0.12
	- cosmeticarmorreworked 1.20.1-v1a
	- create 0.5.1.f
	- cristellib 1.1.5
	- ctov 3.4.3
	- cumulus_menus 1.20.1-1.0.0-neoforge
	- cupboard 1.20.1-2.6
	- curios 5.8.1+1.20.1
	- cutthrough 8.0.2
	- deep_aether 1.20.1-1.0.3
	- deeperdarker 1.2.1
	- denseores 1.2.2
	- dimthread 1.0.4
	- divine_weaponry 1.6.0
	- dungeons_arise 2.1.58-1.20.x
	- dynamiclightsreforged 1.20.1_v1.6.0
	- easy_mob_farm 7.1.0
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- ecologics 2.2.0
	- embeddium 0.3.14+mc1.20.1
	- enchdesc 17.0.14
	- ender_dragon_loot_ 1.0.0
	- endersdelight 1.0.3
	- endrem 5.2.3-R-1.20.1
	- entityculling 1.6.2
	- fabric_api 0.92.1+1.11.8+1.20.1
	- fabric_api_base 0.4.31+ef105b4977
	- fabric_api_lookup_api_v1 1.6.36+67f9824077
	- fabric_biome_api_v1 13.0.13+dc36698e77
	- fabric_block_api_v1 1.0.11+0e6cb7f777
	- fabric_block_view_api_v2 1.0.1+0767707077
	- fabric_blockrenderlayer_v1 1.1.41+1d0da21e77
	- fabric_client_tags_api_v1 1.1.2+5d6761b877
	- fabric_command_api_v1 1.2.34+f71b366f77
	- fabric_command_api_v2 2.2.13+561530ec77
	- fabric_content_registries_v0 4.0.11+a670df1e77
	- fabric_convention_tags_v1 1.5.5+fa3d1c0177
	- fabric_data_attachment_api_v1 1.0.0+30ef839e77
	- fabric_data_generation_api_v1 12.3.4+369cb3a477
	- fabric_dimensions_v1 2.1.54+8005d10d77
	- fabric_entity_events_v1 1.6.0+6274ab9d77
	- fabric_events_interaction_v0 0.6.2+0d0bd5a777
	- fabric_game_rule_api_v1 1.0.40+683d4da877
	- fabric_item_api_v1 2.1.28+4d0bbcfa77
	- fabric_item_group_api_v1 4.0.12+c9161c2d77
	- fabric_key_binding_api_v1 1.0.37+561530ec77
	- fabric_lifecycle_events_v1 2.2.22+afab492177
	- fabric_loot_api_v2 1.2.1+eb28f93e77
	- fabric_message_api_v1 5.1.9+52cc178c77
	- fabric_mining_level_api_v1 2.1.50+561530ec77
	- fabric_model_loading_api_v1 1.0.3+6274ab9d77
	- fabric_models_v0 0.4.2+7c3892a477
	- fabric_networking_api_v1 1.3.11+503a202477
	- fabric_object_builder_api_v1 11.1.3+2174fc8477
	- fabric_particles_v1 1.1.2+78e1ecb877
	- fabric_recipe_api_v1 1.0.21+514a076577
	- fabric_registry_sync_v0 2.3.3+1c0ea72177
	- fabric_renderer_api_v1 3.2.1+1d29b44577
	- fabric_renderer_indigo 1.5.1+67f9824077
	- fabric_rendering_data_attachment_v1 0.3.37+a6081afc77
	- fabric_rendering_fluids_v1 3.0.28+4ac5e37a77
	- fabric_rendering_v1 3.0.8+66e9a48f77
	- fabric_resource_conditions_api_v1 2.3.8+9ad825cd77
	- fabric_resource_loader_v0 0.11.10+bcd08ed377
	- fabric_screen_api_v1 2.0.8+45a670a577
	- fabric_screen_handler_api_v1 1.3.30+561530ec77
	- fabric_sound_api_v1 1.0.13+4f23bd8477
	- fabric_transfer_api_v1 3.3.5+631c9cd677
	- fabric_transitive_access_wideners_v1 4.3.1+1880499877
	- farmersdelight 1.20.1-1.2.4
	- fastasyncworldsave 1.20.1-2.0
	- fastleafdecay 31
	- ferritecore 6.0.1
	- flywheel 0.6.10-7
	- foodeffecttooltips 1.0.0
	- forge 47.2.21
	- fps_increaser 1.0.0
	- framework 0.6.27
	- friendsandfoes 2.0.10
	- ftblibrary 2001.2.1
	- ftbqoptimizer 1.2.2-1.20.1
	- ftbquests 2001.4.1
	- ftbteams 2001.3.0
	- geckolib 4.4.4
	- goblintraders 1.9.3
	- good_nights_sleep 1.3.1
	- graveyard 3.1
	- guardvillagers 1.20.1-1.6.4
	- gunscraft 1.0-SNAPSHOT
	- hamsters 1.20.1-1.0.3
	- healingbed 1.20.1
	- hearth_and_home 1.20.1-2.0.1
	- hopour 1.1.4
	- iceandfire 2.1.13-1.20.1-beta-4
	- iceberg 1.1.21
	- illagerinvasion 8.0.5
	- immersive_weathering 1.20.1-2.0.2
	- inventoryhud 3.4.18
	- inventoryprofilesnext 1.10.10
	- inversia 1.0.2
	- invmove 0.8.4
	- ironchest 1.20.1-14.4.4
	- itemfilters 2001.1.0-build.59
	- itemzoom 2.9.0
	- jade 11.8.0
	- jei 15.3.0.4
	- journeymap 5.9.21
	- kambrik 6.1.1+1.20.1
	- kleeslabs 15.0.0
	- kotlinforforge 4.10.0
	- kubejs 2001.6.5-build.7
	- l2library 2.4.16
	- leawind_third_person 2.0.8-beta.5
	- legendarytooltips 1.4.5
	- libipn 4.0.2
	- libraryferret 4.0.0
	- liferegen 1.0.5
	- lithostitched 1.1.5
	- logprot 1.4
	- lost_aether_content 1.2.3
	- lucent 1.5.5
	- mcbtcws 1.0.3
	- mcwbridges 3.0.0
	- merchantmarkers 1.3.3
	- minecraft 1.20.1
	- mixinextras 0.2.0-beta.9
	- mobcompack 0.0.3.9-1.20.1
	- moonlight 1.20-2.11.12
	- mousetweaks 2.25
	- mr_cherry_villages 1.0.3
	- mr_dungeons_andtavernspillageroutpostrework 1.1
	- mr_edf_remastered 4.3
	- mr_tidal_towns 1.3
	- mutantmonsters 8.0.7
	- mysticrift_music 15.2.5
	- nitrogen_internals 1.20.1-1.0.7-neoforge
	- notenoughanimations 1.7.2
	- notenoughcrashes 4.4.7+1.20.1
	- obscure_api 15
	- origins 1.20.1-1.10.0.7
	- origins_classes 1.2.1
	- overloadedarmorbar 1.20.1-1
	- paperdoll 8.0.0
	- patchouli 1.20.1-84-FORGE
	- physicsmod 3.0.13
	- pickupnotifier 8.0.0
	- playeranimator 1.0.2-rc1+1.20
	- polymorph 0.49.3+1.20.1
	- prism 1.0.5
	- proxima_plus 0.2
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.18
	- quark 4.0-441
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.24
	- rhino 2001.2.2-build.18
	- rubidium 0.7.1
	- saros_fruit_trees_mod 1.0.0
	- seamless_loading_screen 2.0.3+1.20.1
	- sereneseasons 9.0.0.46
	- shulkerboxtooltip 4.0.4+1.20.1
	- skinlayers3d 1.6.3
	- skyvillages 1.0.3
	- slashblade 0.1.2
	- smartbrainlib 1.14
	- smarterfarmers 1.20-1.8.3
	- smoothboot 0.0.4
	- smoothchunk 1.20.1-3.6
	- sophisticatedbackpacks 3.20.5.1039
	- sophisticatedcore 0.6.18.597
	- sound_physics_remastered 1.20.1-1.3.1
	- spectrelib 0.13.15+1.20.1
	- stepitup 2.0.1-1.20.1
	- structorytowers 1.0.6
	- structure_gel 2.16.2
	- structurecredits 1.7
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- tectonic 2.3.4
	- terrablender 3.0.1.4
	- tia 1.20-1.1
	- torohealth 1.20.1-forge-1
	- totw_modded 1.0.5
	- toughasnails 0.0NONE
	- travelerstitles 1.20-Forge-4.0.2
	- treeharvester 8.7
	- tumbleweed 0.5.5
	- twilightdelight 2.0.11
	- twilightforest 4.3.2145
	- undergarden 0.8.14
	- underground_villages 2.1.0
	- uteamcore 5.1.4.289
	- various_world 3.4
	- villagernames 7.3
	- villagersplus 3.1
	- visualworkbench 8.0.0
	- watut 1.20.1-1.1.1
	- waystones 14.1.3
	- weaponmaster_ydm 4.2.3
	- weeping_angels 46.0.1
	- wi_zoom 1.5-MC1.20.1-Forge
	- witherstormmod 4.0.1.1
	- worldeditcui 1.20+01
	- xgsmi 1.1.0
	- yet_another_config_lib_v3 3.4.1+1.20.1-forge
	- ysns 1.0.2
	- yungsapi 1.20-Forge-4.0.4
	- yungsextras 1.20-Forge-4.0.3
	- zeta 1.0-16

**Comment by RepositoryLover** [comment]
Ask this question in the qna channel in the discord server please. Not here.

**Comment by rjdxxxxxccc** [comment]
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15136884/latest.log)
Now this problem occurs

**Comment by rjdxxxxxccc** [comment]
The wither fracture body still exists after the death of the wither storm

**Comment by nonamecrackers2** [comment]
Please fill out the bug report form fully in a new issue, thanks

**Comment by rjdxxxxxccc** [comment]
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15196338/latest.log)
Now the problem reappears
