### ISSUE TITLE
[Bug]: Mob Battle Music + Cwsm Options menu Overlayed

### ISSUE THREAD

**Issue by Aimyx** [nonamecrackers2/crackers-wither-storm-mod#1876]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

Most Recent

### Describe the bug

When Having both MobBattleMusic and Cwsm, the options icon gets overidden by MBM, clicking on it only opens The mob battle menu

### Steps to Reproduce

1. Open Escape menu while in world or Main Menu
2. Click on Overidden Icon,
3. See error.

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/116039665/042b857f-8d8a-48f9-9a39-7dc3e1150ea1)

### Mod List

essential
ferritecore
jade
jei
mob battle music 
cwsm
modernFix
soundphysicsremastered
physicsmodpro

**Comment by TaintedBlockmObile** [comment]
I believe crackers said this is going to be fixed next update

**Comment by Aimyx** [comment]
ah, never looked for it

**Comment by nonamecrackers2** [comment]
This will be fixed in the next major release
