### ISSUE TITLE
[Suggestion]: Unique Sickened Pillager Captain Banner

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#1877]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The sickened pillager captain, often spawned by the symbiont, should have a banner that's different than the one's normal captains where. I am no banner artist but I imagine someone could make a cool design

**Comment by watersofnazareth** [comment]
This was actually a bug and will be fixed as of Evo 1.5

**Comment by GrandmaPork** [comment]
Ah cool i never saw any mention of it in the github

**Comment by TaintedBlock** [comment]
> Ah cool i never saw any mention of it in the github

It wasn't really seen as a bug, just something really annoying to deal with lol.

**Comment by nonamecrackers2** [comment]
> Ah cool i never saw any mention of it in the github

It was something we noticed ourselves, nobody opened a GitHub issue for it
