### ISSUE TITLE
[Suggestion]: Symbiont ability

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#1878]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Didn't see anything on this so figured I would suggest it but a fun ability for the symbiont would be for it to eat a couple of blocks and heal some health. This would only be for those who make it so it can be attacked always instead of waiting for it's vulnerable phase. I feel like this would add extra urgency to use every opening you can get. Though, if you wanted to make it so you don't need the config turned on for this ability, you could make it so it is also vulnerable during this phase and it would slowly consume blocks until it heals like a reasonable amount of health, or someone strikes it in the back. Maybe like a total of 15%-20% because a iron axe critical hit takes 30% of its health.

**Comment by emrearas14** [comment]
Agreed the symbiont is hella easy

**Comment by GrandmaPork** [comment]
I play with pretty high world consumption settings so it can be difficult to get the axe crits through all of the broken terrain and water, but sometimes it does feel too easy. Also this could help it get unstuck

**Comment by Aimyx** [comment]
Yall think the symbiote is easy? I'm over here struggling every time with
my trashy pvp skills.
Think of the little guys who can't fight good lol.

**Comment by BluePineappleGuy** [comment]
imagine a symbiont just chomping down on some birch leaves lol

**Comment by GrandmaPork** [comment]
The easiness comes from being able to stay at its range of engagement which makes its slow attacks ineffective but just waiting out its phases is boring and I feel like just increasing its health is also boring. If cracker doesn’t think this will fit then I’ll just increase its health and make it always vulnerable but I figured this would be a fun addition. If there was some urgency to getting every hit in, before it might heal, then it could add excitement. 
before it’s mentioned, I think reducing its vulnerable time would not help add urgency

**Comment by GrandmaPork** [comment]
I’ve fought the symbiont maybe 21 times now and each time has just boiled down to waiting for its attack phase to end, then hitting it with a guaranteed 30% health crit. This is fine during the final command block fight but it’s not the same story for the normal fight. Though there is some urgency for the normal fight, since you gotta try and kill it before the wither storm eats too much of the area and makes it hard to move around

**Comment by GrandmaPork** [comment]
Thank you for coming to my TED talk

**Comment by BluePineappleGuy** [comment]
> Thank you for coming to my TED talk

It was my pleasure.

**Comment by nonamecrackers2** [comment]
I'm currently against having the Symbiont heal. It was something we tinkered around with but it caused the fight to be extra long and frustrating. This could perhaps be something someone could make in a datapack for example.

**Comment by GrandmaPork** [comment]
gotcha. i'll just increase its health
