### ISSUE TITLE
[Suggestion]: Epic new features read this!

### ISSUE THREAD

**Issue by emrearas14** [nonamecrackers2/crackers-wither-storm-mod#1879]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

In the options there should be a change wither storm difficulty which would go in the order of: Easy - no wither symbionts spawning, command block takes 2 hits to get destroyed, less mobs spawn, less wither storm hp, less chance of being sucked in, less tentacles inside the wither storm, Normal - the current one we have right now, Hard - it's normal but now command block takes 6 hits to detroy, more tentacles inside the wither storm, more mobs spawning, more chance of being sucked in, on the 4th hit of the command block the whole place flips upside down, 3 wither heads inside the wither storm, more evolution speed. Impossible - Hard but command block takes 8 hits to destroy and on the 4th hit it flips the place upside down, more mobs spawn, inside the wither storm has 4 heads, more tentacles inside the wither storm, more wither storm hp, faster evolution speed.

And another feature is when the command block takes one more hit to be destroyed, it protects itself with tentacles which you have to kill to hit the command block and also you have to mine obsidian to get to the command block.

And fix the boss theme so when your 500 blocks away from the wither storm the music then stops.

**Comment by TaintedBlock** [comment]
You did not read the guidelines

**Comment by Herobrine982950291** [comment]
CANNOT FLIP BOWELS! IT IS MENTIONED EVERYWHERE!

**Comment by Herobrine982950291** [comment]
Read this https://github.com/nonamecrackers2/crackers-wither-storm-mod/blob/1.16.5/docs/CONTRIBUTING.md

**Comment by emrearas14** [comment]
But can't you just change the players gravity or flip the camera?

**Comment by emrearas14** [comment]
Can you add the other stuff i mentioned though?

**Comment by Herobrine982950291** [comment]
Idk, I don't create the mod, nor do I work for any mod developers but I believe it maybe quite hard to code some of the other stuff... some things could be implemented though. Just next time, read those guidelines. Link to guidelines: https://github.com/nonamecrackers2/crackers-wither-storm-mod/blob/1.16.5/docs/CONTRIBUTING.md

**Comment by BluePineappleGuy** [comment]
only one suggestion per post, this is multiple. most of these have been
suggested before, such as storm difficulties and gravity flipping.

**Comment by nonamecrackers2** [comment]
Please read the guidelines.
