### ISSUE TITLE
[Health based heads] Wrong head hitbox

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#188]
**Minecraft version**
1.18.2

**Mod version**
2.0.1

**Describe the bug**
When being picked up by the beam and sucked towards the head, hitting it with a bow is pretty much luck-based as the arrows will fly through the head 90% of the time. The hitbox seems to be a lot deeper than the actual eye / head.

Sometimes hitting it with a sword seems impossible too, as it sucks and kills one somewhere below the head - i think this is because of the same reason.

**To Reproduce**
1. Create a phase 4 (or up) wither storm.
2. Go into survival mode.
(3. Use "/effect give @s minecraft:resistance 255 255 true" to become invincible but still attackable.)
4. Let wither storm suck you up using the beam.
5. Try hitting the head with a bow or a sword.

Try it a few times as it doesn't happen all the time, but a lot of the time.
**I attached a video that shows it.** Ignore the wither storm disappearing though, as that is caused by OptiFine.

https://user-images.githubusercontent.com/106488797/177879675-0e88494d-3c12-4c81-8797-4456cf49cb4d.mp4

**Comment by nonamecrackers2** [comment]
The head injury system is currently luck based, with the intent that player should try to avoid the Wither Storm picking themselves up. There is also a cooldown between injury attempts. The hitboxes are also in the right place, however I'll leave this issue open as a reminder to myself to see if I can come up with a better system to replace the current luck-based one.

**Comment by ghost** [comment]
I can give you some ideas:

- Making it hit back the arrow with one of the tentacles and shooting a fireball at the player in the beam.
- Turning the head away to prevent a hit in the eye, suddenly dropping the player. (so the player either dies of fall damage or another beam catches it)
- The arrow just being slowed down and eaten (which would make no sense if another arrow can just hit)

I'm pretty sure there's something possible using an enderman's behaviour of preventing a hit by an arrow or a shield's behaviour of sending back an arrow.

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
