### ISSUE TITLE
[Bug]: Tractor beam is kinda broken

### ISSUE THREAD

**Issue by emrearas14** [nonamecrackers2/crackers-wither-storm-mod#1880]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

43.2.0

### Describe the bug

Idk if its really a bug but the wither storm almost NEVER tries to take me in with the tractor beam its always just taking other blocks and its kinda boring it never really tries to kill you or eat you

### Steps to Reproduce

If you just keep playing

### Crash Reports/Logs

there isnt any

### Is OptiFine installed?

- [X] OptiFine is installed

### Mod List

Only crackers wither storm mod

**Comment by TaintedBlock** [comment]
Did you mess with the config? And you aren't in creative are you?

**Comment by emrearas14** [comment]
> Did you mess with the config? And you aren't in creative are you?
I didnt mess with the config and im in survival, its like after phase 4

**Comment by emrearas14** [comment]
I mean idk if its config but i was holding the amulet and the ultimateTarget was set to me

**Comment by emrearas14** [comment]
I mean idk if its config but i was holding the amulet and the ultimateTarget was set to me

**Comment by TaintedBlockmObile** [comment]
Please do not close this as completed. If you solved the issue, close it as not planned.
