### ISSUE TITLE
[Suggestion]: Add a link *within* the "By checking this box..." guidelines warning that links to the guidelines.

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1881]
### Guidelines

- [ ] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

It seems that people need an easier way to access the guidelines... somehow.

**Comment by BluePineappleGuy** [comment]
Maybe people are just too excited to get their idea out and dont bother checking for duplicates, or they think the guidelines are gonna say something like "just dont be racist ok" and won't check them because they think they know them.

**Comment by nonamecrackers2** [comment]
I think the link is clear enough. If you don't see it you're just completely blind.
