### ISSUE TITLE
[Bug]: The game crashes and commands the block to feign death and lock 0 health

### ISSUE THREAD

**Issue by assomed00011** [nonamecrackers2/crackers-wither-storm-mod#1884]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

Forge 47.2.30

### Describe the bug

Command block lock with 0 health invincibility and immortality. When jumping out of the storm abyss for the first time, the game crashes, and the wither storm is immortalized

### Steps to Reproduce

Firstly, as usual, I killed the command block, but after the white light, I was not teleported out of the wither storm body. The command block in front of me is to lock 0 health, not die, and continuously restore health, although the restored health has always been 0 health.

Afterwards, I took the initiative to jump out of the abyss of the storm and return to the main world, but at that moment the game crashed.

Finally, when I re-entered the game and returned to the save, I fell from the body of the storm and found that it had not died. I re-entered the storm again, but the command block still didn't die - it couldn't die, and the type selector couldn't lock it.

Perhaps it has compatibility issues with a certain mod, but I cannot find it.

### Crash Reports/Logs

In the mod list

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

[crash-2024-05-04_22.09.08-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15212039/crash-2024-05-04_22.09.08-server.txt)
This is a crash report, which also includes all the mods used.

**Comment by nonamecrackers2** [comment]
Try to see if this bug still occurs using the latest 1.20.1 update (4.1). If not, send me a zip file of your mod list so I can take a look in game

**Comment by nonamecrackers2** [comment]
Closing until a response is received
