### ISSUE TITLE
[Bug]: Transparent Teeth...

### ISSUE THREAD

**Issue by FatalERROR1234** [nonamecrackers2/crackers-wither-storm-mod#1885]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.30

### Describe the bug

When I look at the back of the WS heads, the teeth appear slightly transparent.

### Steps to Reproduce

1. Summon WS (phase 2-7)
2. Go to the back of the head
3. See error

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-05-05_14 33 58](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/93551889/a933c565-602a-4fbd-96d8-869732c39d16)

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/93551889/ab522fc6-8911-447e-8f08-17ca22c5c563)

**Comment by FatalERROR1234** [comment]
(btw this can be more obvious in *Fabulous!* Graphics.

**Comment by nonamecrackers2** [comment]
This is fixed in the latest release
