### ISSUE TITLE
[Suggestion]: Boss Variants (Rip Command Block Golem)

### ISSUE THREAD

**Issue by Aimyx** [nonamecrackers2/crackers-wither-storm-mod#1887]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Crackers mentioned a previously cut content (rip command golem) 
And It gave me an idea:
Instead of having different situations for different bosses, we have different bosses that will be picked at random to spawn in the withered symbiotes places,
These boss variants could be skeleton, creeper, spider, etc versions of the classic zombie, all with their unique abilities

this would also allow the bossbar to stay called a “withered symbiont” 

this would also bring a sense of uncertainty, because it’s not clear what kind of fight you need to prepare for until you spot the symbiont that spawns, and add uniqueness to every fight with the storm

of course this All should not be added in one update, it would be better to add maybe one new boss every 3-4 major updates to add to the stream of new features comin in to the mod

**Comment by Pandaboi25x** [comment]
This probably wont be accepted so ill just say theres a mod (made by me btwww) coming out and its sorta similar to your suggestion

**Comment by Aimyx** [comment]
Bros coping

**Comment by Herobrine982950291** [comment]
you mean Symbiont Variants?

**Comment by Aimyx** [comment]
> you mean Symbiont Variants?

Basically, yeah

**Comment by Luke7381** [comment]
I kinda mentioned something similar in my "pure forms" suggestion and it got declined so its not looking so high for this one either.

**Comment by Herobrine982950291** [comment]
> > you mean Symbiont Variants?
> 
> Basically, yeah

ah! I see! could be an nice touch!

**Comment by BluePineappleGuy** [comment]
symbiont variants have been suggested before IIRC, not sure where tho
but non-symbiont bosses would be cool.

**Comment by nonamecrackers2** [comment]
Interesting idea but this is unfortunately out of scope for the mod and what the symbiont is designed for
