### ISSUE TITLE
[Bug]: JVM crash with ModernFix

### ISSUE THREAD

**Issue by soup587** [nonamecrackers2/crackers-wither-storm-mod#1888]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

NeoForge

### Mod Loader Version

47.1.105

### Describe the bug

With ModernFix installed, the JVM will crash shortly after a phase 4 Wither Storm exists in the world. Should the game save, the crash will occur before the game can finish loading the world.

### Steps to Reproduce

1. Install ModernFix
2. Summon a Wither Storm
3. Evolve it to phase 4+

### Crash Reports/Logs

https://gist.github.com/soup587/1439cd584a9ccef4f20a5f7c86abcd27

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

AppleSkin
CWSM
Embeddium (+Extras, ++)
EntityCulling
Ferrite Core
Memory Leak Fix
**ModernFix**
Radium
Yung's Structure Mods (API, Better Desert Temples, Strongholds, etc)

**Comment by embeddedt** [comment]
I will add a feature flag to disable the buffer freeing if CWSM is detected. That said, the best way to fix this issue would be to set the `buffer` field in `BufferBuilder` to `null` after freeing it, that way ModernFix will not try to free it a second time.

**Comment by nonamecrackers2** [comment]
> I will add a feature flag to disable the buffer freeing if CWSM is detected. That said, the best way to fix this issue would be to set the `buffer` field in `BufferBuilder` to `null` after freeing it, that way ModernFix will not try to free it a second time.

Yeah that's what I'm planning on doing from looking at ModernFix

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
