### ISSUE TITLE
Formidi-Blade bugged or too overpowered

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#1889]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.1.46

### Describe the bug

Formidi-Blade doesn't stop with explosions after more than 10 hits, i don't know if it's a bug or not, but i just wanted to make sure

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121522736/a50c4913-a4a3-4ea7-a04f-24986f4a789f

### Steps to Reproduce

 just keep hitting the entity with the sword

### Crash Reports/Logs

(isn't necessary actually)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

embeddium-0.2.13+mc1.20.1
MouseTweaks-forge-mc1.20-2.25
oculus-mc1.20.1-1.6.9
worldedit-mod-7.2.15

**Comment by WitherBean** [comment]
what the

**Comment by Aimyx** [comment]
Well Lucas is already mucking around with the new update

**Comment by nonamecrackers2** [comment]
Yeah no that's not supposed to happen lol

**Comment by Herobrine982950291** [comment]
> Well Lucas is already mucking around with the new update

Ik right? My eyes were sore from watching that continuous explosion...

**Comment by watersofnazareth** [comment]
Fixed this
