### ISSUE TITLE
Very big hole at the back of the wither storm

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#189]
1.16.5
The version of Minecraft the mod is running on

Any
The version of the mod you are using

VERY BIG HOLE AT THE BACK

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

![2022-07-08_04 52 55](https://user-images.githubusercontent.com/108914903/177920624-a29f8113-8cd6-4c99-bb83-861876f0850b.jpeg)

**Comment by witherstormfan87** [comment]
Very Big hole at the back

**Comment by nonamecrackers2** [comment]
What's your setup specs?

**Comment by witherstormfan87** [comment]
I don't know.

**Comment by nonamecrackers2** [comment]
I'm not sure how I could reproduce this issue, as I've never experienced it. I've seen it happening with the pojav launcher, and I believe it may be down to the specs of whatever hardware you may have and/or how much ram you have allocated to the game. If the hole is still appearing, and if your system allows it, try increasing your ram and see if this gets solved.

**Comment by witherstormfan87** [comment]
Ok

**Comment by witherstormfan87** [comment]
Didn't work
