### ISSUE TITLE
[Bug]: Game crash in my modpack 1.20.1 Forge 47.2.31

### ISSUE THREAD

**Issue by damikdevil** [nonamecrackers2/crackers-wither-storm-mod#1890]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.31

### Describe the bug

Game crashes after some time i spawn a wither storm phase1

### Steps to Reproduce

[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15274044/latest.log)

### Crash Reports/Logs

no crash reports, log on write section

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

logs

**Comment by jackjackpdr** [comment]
i have the exact same issue here

**Comment by jackjackpdr** [comment]
i spawn it after 2 minutes it crashes

**Comment by nonamecrackers2** [comment]
This is a compatibility issue with ModernFix, you'll need to remove it for now to prevent the crash. The issue is being tracked here: #1888
