### ISSUE TITLE
[Bug]: cant summon a sickened parrot with the withered beacon

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1892]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.19.4

### Mod Version

3.4

### Mod Loader

Forge

### Mod Loader Version

47.1.0

### Describe the bug

title explains it

### Steps to Reproduce

1. title explains it 2x

### Crash Reports/Logs

no

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/aa38dd6d-4b1a-40e9-a565-c33d61cda75c)

### Mod List

cwsm, cwse, worldedit

**Comment by BluePineappleGuy** [comment]
there probably isn't a recipe for it

**Comment by nonamecrackers2** [comment]
Oh there might be too many items, and you can't actually fit them all in. Should've tested that I guess lol

**Comment by Pandaboi25x** [comment]
> Oh there might be too many items, and you can't actually fit them all in. Should've tested that I guess lol

yeah theres too many
