### ISSUE TITLE
[Bug]: Importa incompatibility with the origins mod

### ISSUE THREAD

**Issue by FuryJack07** [nonamecrackers2/crackers-wither-storm-mod#1893]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.30

### Describe the bug

Not exactly a bug, but it is something that sort of ruins the experience: 
the golden apple stew cannot be eaten by carnivore origins

### Steps to Reproduce

Enter a world.
Select a carnivore origin
grab a golden apple stew
Ops, you can't eat it

Extra steps:
Get the wither sickness effect in a normal playthrough.
Struggle to get the needed ingredients for the golden apple stew.
Finally get them all.
Craft it.
...
shit.

### Crash Reports/Logs

None

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/162727720/b5a2f2db-f9b0-463d-8cc2-542a68b1e905)

### Mod List

NONE

**Comment by FuryJack07** [comment]
Sorry if this isn't considered a bug, but i'd very much rather something being done about it... considering just how important the stew is.

**Comment by FireCode125** [comment]
Skill issue lmao

**Comment by FuryJack07** [comment]
> Skill issue lmao

Bruh.

**Comment by BluePineappleGuy** [comment]
This is because the stew isn't considered 'meat' in the mod code. So carnivores, which can only eat food that is labeled as meat in the item code, cannot eat the stew.

**Comment by nonamecrackers2** [comment]
Yeah, and its technically intended (not meat in the stew lol), but in the case of this mod there shouldn't be anything preventing you from eating it since it cures you from an otherwise uncurable disease

**Comment by Aimyx** [comment]
Just make a carnivore version with a golden mutton or something
idk

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release. Just had to add the golden apple stew to the "ignore_diet" item tag added by Origins
