### ISSUE TITLE
[Suggestion]: The future of CWSM Evolution Part 2

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#1894]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Ending CWSM with a bang

With the mini update for CWSM released, I figured I share a lingering thought I had regarding the mod as a whole. I'm posting this suggestion here because there's only a Q&A category on the Discussion page of the GitHub, and I feel like this will get lost in the Discord, regardless of what channel I post this in.

When the Caves and Cliffs update was split into 2 parts, they saved part 2 as the biggest part of the update- Bigger world terrain in the form of **bigger mountains and cliffs**, **deeper caves**, **new cave biomes**, and **extending the world height**. It was a game changer for builds and exploration in Minecraft. (Also tanked performance on Vanilla, but not the main point)

**What does that have to do with CWSM?** Given that the Evolution update is also split into two parts, Evolution Part 2 needs to come out with a big bang. This mod needs to live up to the update name: **Evolution**. The mod needs to evolve, and go beyond what we currently have in the mod.

Sure, we got new command block tools, new mobs, and optimizations for Evolution Part 1. And sure, we got a bunch of new optimizations, more new mobs, and more configs options to play around with in the Mini Update. But much like Cave and Cliffs Part 1, it is small potatoes to what I'm proposing for Evolution Part 2.

Issue https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/10 requests for a phase 8. Given that crackers has yet to close this issue seems to tell me that he does have plans for an even bigger phase in the works, or something that evolves past the current phases of the Wither Storm.

Issue https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1672 can give a harder challenge for veterans of the mod. It would give a much greater challenge and more replayability, while not creating drastic progression changes that you would find in modpacks like Explorer's Eve.

I really don't know how else to "evolve" the mod past that without drastically changing the mod's progression, but this what I'm suggesting: truly evolving the mod and living up to the name of Evolution.

So I'll leave this final statement. To crackers, Nazaru, and the other developers working on this brilliant and legendary mod, when you do release Evolution Part 2, hit the Minecraft modding community with your all. Truly evolve this mod to it's greatest.

**Comment by Aimyx** [comment]
Basically, just take your time in development :thumbsup:

**Comment by Luke7381** [comment]
Im still hoping for the possibility of the WS being able to use its tentacles, even though its unlikely.

Also i do think it would be good for the WS to have some endgame phases such as phase 8, if the player decides to let it evolve more. This would allow certain possibilities such as a harder command block fight

**Comment by BluePineappleGuy** [comment]
#790 would also be good because it would, in a sense, evolve how the bowels open without actually having endermen on the storm.


Ignore the fact that i'm promoting my own suggestion.

**Comment by ghost** [comment]
> #790 would also be good because it would, in a sense, evolve how the bowels open without actually having endermen on the storm.

I like it. I problem I see is how entity lag from too many endermen and having to spawn under the radius of a moving target.

**Comment by nonamecrackers2** [comment]
I'm not sure what to do with this issue, so I'm just going to close it but I'll keep your encouragement/ideas for future reference in the back of mind. We have rough ideas on what we're going to do but it isn't set in stone yet.

And thank you, I'm glad (and probably so is Naza) that we're able to make something that so many people can enjoy, and we do definitely hope to end off in a bang.
