### ISSUE TITLE
[Bug]: WS Killed Early Jumpscare malfunctions at high levels of strength

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1895]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

Unknown, likely not tied to that.

### Describe the bug

A bug happened!

The wither storm ends up dying as a phase 4 wither storm instead of evolving and living.

### Steps to Reproduce

Summon WS.
Get strength 30.
Kill it.
Watch as it dies (incorrect behavior.)

### Crash Reports/Logs

N/A (I checked the logs and they were clean.)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/122060314/86a7ebd7-76c4-4a43-8118-5b2aaf3d154f)

### Mod List

CWSM
JEI

**Comment by GearsawStudios** [comment]
Note: Error also happens when attribute is used to reduce the max health of it and is punched to death normally.

**Comment by Pandaboi25x** [comment]
idk if this is worth fixing since no survival player will be able to kill the ws that fast, just give yourself strength 15 and it does the trick smh smh

**Comment by GearsawStudios** [comment]
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/122060314/358c6faa-60e6-4ee0-b700-142b271916db)
This occurs regardless of summon method, whether it be manual or /summon.

**Comment by Pandaboi25x** [comment]
> ![image](https://private-user-images.githubusercontent.com/122060314/329698264-358c6faa-60e6-4ee0-b700-142b271916db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjk0OTUsIm5iZiI6MTcxNTM2OTE5NSwicGF0aCI6Ii8xMjIwNjAzMTQvMzI5Njk4MjY0LTM1OGM2ZmFhLTYwZTYtNGVlMC1iNzAwLTE0MmIyNzE5MTZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxOTI2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGY3NDg1ZDU1MzQyYmE2NDA2OTI2MWZkN2I1OTBiYWZhMGY4MDRjMTk3OTNkODkyNjkxNjVmZGEwY2UxNzJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aT5xyFcX7AQZaBw5WylG00j9AseHNjXIntdF2CiuPzk) This occurs regardless of summon method, whether it be manual or /summon.

why the heads like that

**Comment by GearsawStudios** [comment]
They died too.

**Comment by BluePineappleGuy** [comment]
so is the issue that it dies or that the death is weird

**Comment by GearsawStudios** [comment]
> so is the issue that it dies or that the death is weird

That it dies, the death being weird is a side effect that shouldn’t ever be seen either.

**Comment by BluePineappleGuy** [comment]
might be storm invulnerability setting, is it turned on?

**Comment by GearsawStudios** [comment]
No, this is with default config with black hole mode enabled.

**Comment by nonamecrackers2** [comment]
I guess I should add a health clamp so it doesn't go under when it evolves

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
