### ISSUE TITLE
[Suggestion]: Update 1.19.2 to the newest version

### ISSUE THREAD

**Issue by teo-tomato** [nonamecrackers2/crackers-wither-storm-mod#1896]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

So basically I saw some videos showing off a beacon in the mod, which is also in the Wiki. So once I downloaded the mod I looked for the beacon and I couldn't find it anywhere. Please add all the new features to 1.19.2, i'm sure many people would appreciate it. Thanks
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/154431174/66dfa5f2-ceb3-4dcc-8dca-2355f33ad2ef)

**Comment by Pandaboi25x** [comment]
There wont be any backports since the code base changes between 1.19.2, 1.19.3, and 1.19.4, why do you guys like 1.19.2 so much anyway

**Comment by teo-tomato** [comment]
> There wont be any backports since the code base changes between 1.19.2, 1.19.3, and 1.19.4, why do you guys like 1.19.2 so much anyway

Because there are some mods that don't support 1.20.1

**Comment by GearsawStudios** [comment]
This is already confirmed to not be happening.

**Comment by FrozenDragon0** [comment]
> > There wont be any backports since the code base changes between 1.19.2, 1.19.3, and 1.19.4, why do you guys like 1.19.2 so much anyway
> 
> Because there are some mods that don't support 1.20.1

1.19.2 support is discontinued.

**Comment by Luke7381** [comment]
There won't be any updates to the 1.19.2 version. Blame mojang for some reason deciding to majorly change the code base between version 1.19.2-4

**Comment by BluePineappleGuy** [comment]
there are now 4 essential versions of forge: 1.12.2, 1.16.5, 1.19.2, and latest

**Comment by nonamecrackers2** [comment]
Versions below 1.19.4 are discontinued and will be receiving no more future updates, besides any critical bug fixes
