### ISSUE TITLE
[Bug]: Crafting an F-Bomb using ImmersiveMC Does not have a 600 sec countdown...

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1898]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.30

### Describe the bug

A bug happened! When I craft a Formidibomb using ImmersionMC, there is no 600 second countdown before auto-detonation.

### Steps to Reproduce

1. Install ImmersionMC
2. Craft a Formidibomb (Physically placing down ingredients)
3. Collect it and look in Inventory

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/05819c2a-9d10-45c2-b714-fe185fff77a8

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/a92dbbc8-259d-43f3-83f7-bd0399b9929a)

**Comment by nonamecrackers2** [comment]
The method which adds the timer may not be called. I'll look into it but it could be an issue with ImmersiveMC

**Comment by Herobrine982950291** [comment]
Sorry I made a mistake it's called ImmersiveMC. But alright.

**Comment by nonamecrackers2** [comment]
This is an issue with ImmersiveMC. I've opened a bug report on their repo, you can track it here: https://github.com/hammy275/immersive-mc/issues/430
