### ISSUE TITLE
Launcher crashes while trying to load game (with mod installed) 

### ISSUE THREAD

**Issue by MonaLisaSlayer** [nonamecrackers2/crackers-wither-storm-mod#190]
**Minecraft version**
1.18.2 

**Mod version**
![image](https://user-images.githubusercontent.com/108924446/177946667-fb9de839-a1d2-4e48-9242-f80a625d4c75.png)
(most recent version) 

**Describe the bug**
Whenever I try to launch Minecraft (via curseforge) with mod installed, launcher always crashes due to "invalid Java Runtime configuration".

**To Reproduce**
1. Install wither storm mod onto curseforge.
2. Launch mod via curseforge. 

**Crash Reports / Logs**
- No crash report 
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9070203/latest.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/108924446/177947609-273439f7-d526-4132-b375-e21553e4082e.png)

**Comment by nonamecrackers2** [comment]
Try using an older version of forge or a potentially a newer one, start with the former first

**Comment by nonamecrackers2** [comment]
I'd also recommend trying to launch an instance with no mods and see if it crashes. If it does, it's probably a curse issue that I can't resolve.
