### ISSUE TITLE
[Bug]: Wither Storm in phase 0-3 isn't considered undead

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1900]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

Nothing to do with this issue

### Describe the bug

Healing potions should damage the wither storm like it does the normal wither.

### Steps to Reproduce

1. throw a healing potion on a normal wither
2. compare to a wither storm in phase 0-3
3. see error

### Crash Reports/Logs

No crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-05-11_11 04 36](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/7252323e-b249-4e94-93ed-a5e727b46af2)

### Mod List

CWSM and some other client mods that aren't important to this

**Comment by TaintedBlock** [comment]
whoops, wrong image lol

**Comment by TaintedBlock** [comment]
I can't send the video but the issue is there

**Comment by GearsawStudios** [comment]
#1900 moment.

**Comment by TaintedBlockmObile** [comment]
Oh cool

**Comment by nonamecrackers2** [comment]
This will be fixed in the next release. We're gonna make the Wither Storm immune to potion damage entirely

**Comment by BluePineappleGuy** [comment]
> This will be fixed in the next release. We're gonna make the Wither Storm immune to potion damage entirely

rip elixir addons
