### ISSUE TITLE
[Bug]: Game crashes and world loads wrong when using ModernFix

### ISSUE THREAD

**Issue by Cod1ngGamer** [nonamecrackers2/crackers-wither-storm-mod#1902]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

When using CWSM and [ModernFix](https://modrinth.com/mod/modernfix/version/4D2n0P0v) together, all worlds with the wither storm load really weird. Then, the game crashes after a few seconds. Now here's the really weird part: **The game closes as if the quit button was pressed.** No crash message, no crashlog, nothing. It's like it's executing a kill instruction or something. The closest thing I could find to this was arbitrary code execution.

Honestly, I find this really interesting, and would love to see someone explain why this happens.

### Steps to Reproduce

1. Install CWSM and ModernFix
2. Make a new world (or load up an existing one)
3. Spawn the wither storm
4. Game closes

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM
ModernFix

**Comment by GearsawStudios** [comment]
ModernFix is the one that causes the crash, already known. This is a JVM error where ModernFix tries freeing memory CWSM already freed, breaking the game.

**Comment by nonamecrackers2** [comment]
#1888
