### ISSUE TITLE
[Bug]: Head's nbt merge

### ISSUE THREAD

**Issue by Composer-Hu** [nonamecrackers2/crackers-wither-storm-mod#1904]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.30

### Describe the bug

When you do any heads nbt data modification, head0 always instantly returns to the front. This has been a problem for a long time, I remember that it had been proposed and resolved, but I came across the problem again today.

### Steps to Reproduce

1. use command data merge entity @w {Heads: {2: {IsRoaring: 1b}}}, (even if it's not modifying head0)
2. See head0 returns to the front

### Crash Reports/Logs

No Crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

No

### Mod List

CWSM

**Comment by nonamecrackers2** [comment]
This is unfortunately a bug with Minecraft itself. There isn't much I can do about this. I'd recommend reporting this to them if it hasn't already been

**Comment by Composer-Hu** [comment]
Anyway, thanks for your efforts, thank you.
