### ISSUE TITLE
[Bug]: Bowels structure appears in command block arena

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#1905]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

Unknown

### Describe the bug

Title explains. Found a tainted mineshaft overlapping in the final boss arena.

### Steps to Reproduce

1. Go to bowels
2. Enter command block arena
3. Hope you get lucky

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Minecraft Forge_ 1 20 1 - Singleplayer 2024-05-11 7_59_28 PM](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/119386923/7340aa67-6759-4348-8f00-545787f56f5c)
![Minecraft Forge_ 1 20 1 - Singleplayer 2024-05-11 8_02_23 PM](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/119386923/c31c8cfa-481e-49ae-abba-b3603f8b7acc)

### Mod List

CWSM
Mob Battle Music

**Comment by TaintedBlock** [comment]
This isn't a bug, it's a new arena lol

**Comment by FrozenDragon0** [comment]
This is intentional, it's part of the new arena variants.

**Comment by Cod1ngGamer** [comment]
"It's not a bug, it's a feature"
-Mojang

**Comment by BluePineappleGuy** [comment]
> This is intentional, it's part of the new arena variants.

Really?
It seemed very odd so i thought it was a bug. Will close now then.
