### ISSUE TITLE
[Bug]: reuben spawns as a normal pig

### ISSUE THREAD

**Issue by pigsbane** [nonamecrackers2/crackers-wither-storm-mod#1906]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

1.20.1-47.2.17

### Describe the bug

when i summoned reuben with the corrupted beacon, reuben was just a normal pig

### Steps to Reproduce

1. place a corrupted
2. place 16x pork in the beacon
3. spawn 'reuben' and find a normal pig

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/160582060/3530eefb-7271-4f62-9e65-e8ee6b1b2521

### Mod List

cloth config api
dynamic fps
cracker's wither storm mod
embeddium
jade
jei
memory leak fix

**Comment by Herobrine982950291** [comment]
?? How is reuben in the mod?

**Comment by Cod1ngGamer** [comment]
Apparently you can spawn a baby pig by putting 16 porkchops in the withered beacon. It's a nice little easter egg, and I think the issue here is it sometimes spawns as an adult pig.

**Comment by pigsbane** [comment]
no just a baby normal pig, no reuben tag

**Comment by pigsbane** [comment]
i edited the issue to have  a vid

**Comment by Herobrine982950291** [comment]
huh! Never knew that...

**Comment by Resuster** [comment]
I've had this issue as well and I thought it was because of the datapacks I was using.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release

**Comment by Herobrine982950291** [comment]
does that include 4.2 mini update? or Evo Pt2?
