### ISSUE TITLE
[Suggestion]: Wither Storm conversion resistance

### ISSUE THREAD

**Issue by tvpv2** [nonamecrackers2/crackers-wither-storm-mod#1907]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Creatures from some Minecraft mods that use different attack strategies can cause the wither storm to turn into a certain stat. For example, a creature called gorgon in the Ice and Fire Dragon mode turns all entities into stone. This is a stat and I think wither storm should be immune to such transformations. I fought the wither storm with this gorgon creature that I mentioned personally. And the huge wither storm was turned into stone... I think the only way to ignore these transformations is to examine all the mods containing the relevant content and similar ones one by one and find the codes that enable the conversion. But I'm not sure. There may also be a specific code to prevent a creature from assuming an unforeseen status.
or conversion override...

**Comment by tvpv2** [comment]
Additionally, creatures with different attack strategies can engage in close combat with a huge wither storm. How absurd isn't it?

**Comment by nonamecrackers2** [comment]
This is something those mods should add compatibility for. It would be easier for them to do it then for me to try.
