### ISSUE TITLE
[Suggestion]: Mob Battle Music: Music fading config

### ISSUE THREAD

**Issue by SpudFr** [nonamecrackers2/crackers-wither-storm-mod#1908]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

honestly, i think a fading in and out config for the music would be great, same with the non-aggro track and the player track

**Comment by TSEG6** [comment]
This should be on the mobbattlemusic GitHub, not on cwsm

**Comment by SpudFr** [comment]
My bad
