### ISSUE TITLE
[Suggestion]: WS-Themed pottery sherds and armor trims

### ISSUE THREAD

**Issue by SrSpud** [nonamecrackers2/crackers-wither-storm-mod#1909]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

it would be cool to see pottery sherds and armor trims related to the wither storm, as an example, i made a concept texture of two pottery sherds that would be called "storm pottery sherd" and the symbiont one you guys could choose the name, besides, all of these would be found  exclusively in the bowels
![symbiontpsherd](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/169533212/20992377-7577-426a-9443-c90486cb89f0)
![wspshard](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/169533212/635629ad-0d55-4563-bb44-ea90dfc03c45)

**Comment by Cod1ngGamer** [comment]
This is an amazing idea, and the artwork is great! I really hope this gets added.

**Comment by Herobrine982950291** [comment]
NOICE! Love it! ⭐⭐⭐⭐⭐

**Comment by SrSpud** [comment]
> This is an amazing idea, and the artwork is great! I really hope this gets added.

Thanks! :D

**Comment by nonamecrackers2** [comment]
I quite like this idea

**Comment by BluePineappleGuy** [comment]
I believe this was mentioned in other issues, such as #1056 which suggest withered artifacts to be found inside the bowels via archeology.

**Comment by Herobrine982950291** [comment]
Dark Decorations....

**Comment by nonamecrackers2** [comment]
I'll keep this one open since it has some unique designs we can take inspiration from

**Comment by SrSpud** [comment]
> I'll keep this one open since it has some unique designs we can take inspiration from

Mind if i try to make more designs and the trims concept?

**Comment by nonamecrackers2** [comment]
Yeah that's fine
