### ISSUE TITLE
[Suggestion]: Phase 3.2 at 50%

### ISSUE THREAD

**Issue by RepositoryLover** [nonamecrackers2/crackers-wither-storm-mod#1910]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Can you make Phase 3.2 start at 50%? Just so it's the same as the other half-phases (such as 1.2, 2.1, 4.5, 5.25, and 6.5).

**Comment by nonamecrackers2** [comment]
We're going to be adding more sub-phases, so this wouldn't work out

**Comment by RepositoryLover** [comment]
> We're going to be adding more sub-phases, so this wouldn't work out

Will one of them appear at 50% of Phase 3?

**Comment by nonamecrackers2** [comment]
Maybe, but regardless this would prevent us from adding any more. We'd have to adjust the command each time we add new ones, breaking backwards compatibility
