### ISSUE TITLE
[Suggestion]: Bigger bowels when a phase 8 is added

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1913]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

title

**Comment by Aimyx** [comment]
If*

**Comment by NinjaSam5399** [comment]
Explain it pls

**Comment by nonamecrackers2** [comment]
Who said it was going to be added? If it ever would be, it'd be to our discretion whether or not the bowels would be larger or not

**Comment by Luke7381** [comment]
> Who said it was going to be added? If it ever would be, it'd be to our discretion whether or not the bowels would be larger or not

I don't know, i was thinking it was very likely that a Phase 8 would be added since issue #10 is yet to close, I could've worded better but since this was closed i won't really bother (unless you reconsider). I also apologize for being quite vague as i thought it would've been straightforward as to what i was talking about, but basically if the player decides to wait a bit longer and let the wither storm evolve more, the bowels "dimension" would be bigger and command block boss fight would be changed up.
