### ISSUE TITLE
[Bug]: decreased damage on displayed eye of the storm weapon

### ISSUE THREAD

**Issue by kaboom24** [nonamecrackers2/crackers-wither-storm-mod#1914]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

when I put the eye of the storm sword in a glow item frame and take it out it gets a minus 5 damage debuff please fix I really want to have it on display and grab it when I need it.

### Steps to Reproduce

get eye of storm sword
go in survival
put it in glow item frame
take it out
hover over it in inventory screen

### Crash Reports/Logs

none (dont know how to get latest logs without crashing and I cant crash on command)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

all mods are up to date as of this post
alexs caves
alexs mobs
aquaculture 2
balm (forge edition)
biomes o plenty
bosses of mass destruction
cerbons API [forge I fabric I neoforge]
citadel
cloth config API (fabric/forge/neoforge)
clumps
cosmetic armor reworked
curios API (forge neoforge)
geckolib
godly vampirism
just enough items (JEI)
just enough resources (JER)
L_enders cataclysm
Lionfish API
mob battle mod (forge)
nethers exoticism
not enough crashes (forge)
pet your cat
rats (ratlantis experiment turned on)
terrablender (forge)
the bumblezone (neoforge/forge)
vampires need umbrellas
vampirism - become a vampire
waystones
werewolves become a beast

**Comment by GearsawStudios** [comment]
This is intended behavior; its damage is dependent on health. Try using it on low health, maybe make a Github asking for a description to explain it too.

**Comment by nonamecrackers2** [comment]
> This is intended behavior; its damage is dependent on health. Try using it on low health, maybe make a Github asking for a description to explain it too.

This. The damage reduction goes away with the less amount of health you have.
