### ISSUE TITLE
[Suggestion]: Withered Gunpowder

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1916]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Can you make it so that Withered Creepers drop Withered Gunpowder? (If possible, this can be exclusive to creepers found in Bowels.)

**Comment by GearsawStudios** [comment]
What use would it have though?

**Comment by TaintedBlockmObile** [comment]
1, I don't think gunpowder can even "wither" so to speak. It's powder. 
2. What use would it have besides be an extra item that's not needed?

**Comment by Aimyx** [comment]
Alternate source of gunpowder might work, help with making formidibomb as
long as you don't let em explode.

**Comment by Luke7381** [comment]
> What use would it have though?

Maybe for a withered tnt of some kind? For survival use im not sure, maybe the explosion would inflict severe wither on nearby mobs, making it useful for hordes and what not.

**Comment by nonamecrackers2** [comment]
I personally don't see the need for withered gunpowder. Yes, it could be used to craft the formidibomb, but then it'll just make it take even longer since now you'll need to find sickened creepers. It'll also be less useful than normal gunpowder since it wouldn't be able to be used in normal recipes.

**Comment by Herobrine982950291** [comment]
> I personally don't see the need for withered gunpowder. Yes, it could be used to craft the formidibomb, but then it'll just make it take even longer since now you'll need to find sickened creepers. It'll also be less useful than normal gunpowder since it wouldn't be able to be used in normal recipes.

Couldn't it be dropped by the creepers summoned by the Symbiont?

**Comment by GearsawStudios** [comment]
Crackers said there was no need and closed it, there’s not much more to discuss.

**Comment by Herobrine982950291** [comment]
alr alr.
