### ISSUE TITLE
[Bug]: Falling blocks destroy tile entities

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#1918]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.21

### Describe the bug

When a block falls from the ceiling and lands on a bed or chest, it destroys it. This is pretty inconvenient

### Steps to Reproduce

1. Place bed or chest in cave under wither storm
2. Wait for falling block to land on and destroy said tile entity

### Crash Reports/Logs

n/a

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

Edited to fit under 10 seconds. Watch as my bed and chest is destroyed in this clip
https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/109642282/193a6da9-986e-4d70-86ae-433146fe44b3

### Mod List

c2me was removed**
Modlist shouldn't be relevant.
![Screenshot 2024-05-13 141602](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/109642282/243005b4-00ec-44b5-9ffd-62d2f4e118b6)
![Screenshot 2024-05-13 141552](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/109642282/33795192-1498-4e5e-a276-ceb4a0ae2a86)

**Comment by TaintedBlock** [comment]
I think this exist to prevent clusters from being stuck on small things like that. I'm not too sure

**Comment by GrandmaPork** [comment]
blacklisting chests and beds would be optimal

**Comment by watersofnazareth** [comment]
Fixed
