### ISSUE TITLE
wither storm  turns upside down 

### ISSUE THREAD

**Issue by Faknocker** [nonamecrackers2/crackers-wither-storm-mod#192]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.
you can make the final mob boss harder by  makeing the wither storm will go upside down like in story mode it might be hard but you can do it

**Comment by nonamecrackers2** [comment]
This will be extremely difficult and honestly not worth the effort to make the final boss battle (which I assume is what you're referring to) flip in a smooth, seamless and compatible way.
