### ISSUE TITLE
[Bug]: Block particles spawn even if tractor beam isn't touching the ground

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1920]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.32

### Describe the bug

Title

### Steps to Reproduce

I think the picture should be a good enough example

### Crash Reports/Logs

No crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-05-13_23 17 32](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/9a516e4e-88f4-4cb8-98cb-1896554b518d)

### Mod List

CWSM and other mods that shouldn't affect the wither storm's beams

**Comment by TaintedBlock** [comment]
![Uploading 2024-05-13_23.13.23.png…]()

**Comment by TaintedBlock** [comment]
![2024-05-13_23 13 23](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/19d5960d-aa29-4a89-baf1-5d968e7d9dc8)

**Comment by TSEG6** [comment]
Literally unplayble

**Comment by TaintedBlockmObile** [comment]
Smh, can't believe he let this slide

**Comment by BluePineappleGuy** [comment]
How do you even manage to get the storm that high without amplified

**Comment by TaintedBlockmObile** [comment]
> How do you even manage to get the storm that high without amplified

It isn't high up. The beams cut off when hitting a mass amount of blocks so they don't go through the ground

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
