### ISSUE TITLE
[Bug]: Boss Music Not Playing despite the options being on. 

### ISSUE THREAD

**Issue by LordAkuma8** [nonamecrackers2/crackers-wither-storm-mod#1921]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.19.4

### Mod Version

3.4

### Mod Loader

Forge

### Mod Loader Version

45.0.57

### Describe the bug

When the Wither Storm or Withered Symbiont is summoned, neither are producing boss music. The options are on and always have been on but are only experiencing issues lately, and no new mods have been added that would be incompatible. (Reloaded the world, launcher, and mod and issue has still persisted). 

### Steps to Reproduce

Launch the game and spawn either a Wither Storm or Withered Symbiont and check if the boss music is playing. 

### Crash Reports/Logs

5 minutes ago 11:01 PM CDT (5/13/2024)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Advanced Xray (Forge Edition)
Always a Wither Skull
Collective
Craftable Enchanted Golden Apple
JEI
Xaero's Minimap
More Enchantments

**Comment by FrozenDragon0** [comment]
Seems to be related to the bosses directly, as if you play the music via the /playsound command it'll work as normal.

**Comment by LordAkuma8** [comment]
That's what I figured, but I assumed that since I didn't add any new mods and that the issues only started when the new update content downloaded that it was some kind of bug introduced in the mini update.

**Comment by nonamecrackers2** [comment]
You need to have your music slider up now. The boss music has been moved from the records to music slider for mod compatibility. You can disable the Minecraft music in the CWSM client config.

**Comment by sm644me** [comment]
No, there's definitely a bug here. I'm on 1.19.4 to develop Explorer's Eve, and I have this issue. I've double-checked all the options (config is on, all sound sliders are maxed out) and even removed my custom resource pack, and still, no music. I heard it fade out once when I spawned the Wither Storm (seriously, it started nice and loud and immediately faded out), and I've never heard anything since.

**Comment by nonamecrackers2** [comment]
I must've read this wrong then. I swear the music worked on 1.19.4? I'll take a look

**Comment by Pandaboi25x** [comment]
it works for me on 1.19.4

**Comment by FrozenDragon0** [comment]
> I must've read this wrong then. I swear the music worked on 1.19.4? I'll take a look

It's a problem on 1.20.1 aswell, music straight up refuses to play from the Wither Storm directly.

**Comment by BluePineappleGuy** [comment]
> > I must've read this wrong then. I swear the music worked on 1.19.4? I'll take a look
> 
> It's a problem on 1.20.1 aswell, music straight up refuses to play from the Wither Storm directly.

That's odd, music works fine for me on 1.20.1
Maybe some other mod is causing it? Any other mods that do anything with sounds or music?

**Comment by FrozenDragon0** [comment]
Ah now it wants to work.

**Comment by sm644me** [comment]
> No, there's definitely a bug here. I'm on 1.19.4 to develop Explorer's Eve, and I have this issue. I've double-checked all the options (config is on, all sound sliders are maxed out) and even removed my custom resource pack, and still, no music. I heard it fade out once when I spawned the Wither Storm (seriously, it started nice and loud and immediately faded out), and I've never heard anything since.

It looks like some other people here are having issues, but I've _finally_ figured out that the specific issue I was having was caused by a rogue command in Explorer's Eve (custom music effects were triggering when they shouldn't, technically been a bug for over a year but hasn't had any negative effects until now). Music now works on 1.19.4 for me as it should. There may still be a bug here, but my specific problem is resolved.

**Comment by nonamecrackers2** [comment]
Good to know, I'll still investigate other peoples issues however

**Comment by FalconinVoid** [comment]
Changing the Version from 4.1-all to 4.0.1.1 fixed the problem for me

**Comment by nonamecrackers2** [comment]
I found some issues that was causing boss music to not play, and hopefully them being fixed should fix this issue. In general make sure to have your music slider up in order to hear the boss music
