### ISSUE TITLE
[Bug]: Crashed when re-entering a superflat world with a Wither Storm present

### ISSUE THREAD

**Issue by Bloxxify2827** [nonamecrackers2/crackers-wither-storm-mod#1923]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

Forge-47.2.0

### Describe the bug

A bug happened!

When Re-Entering a superflat world with a live wither storm, I crashed upon entry.

[message.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/15313967/message.txt)

### Steps to Reproduce

1. Create Superflat and summon Wither Storm
2. Exit world
3. Re-Enter

### Crash Reports/Logs

https://pastebin.com/ufCbHKnF

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

![image_2024-05-14_163630499](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/110550077/9557f777-f2dd-4efd-8bea-7933ba465801)

**Comment by nonamecrackers2** [comment]
Did you kill any of the segments?

**Comment by Bloxxify2827** [comment]
No, both segments were alive before exiting.

**Comment by Herobrine982950291** [comment]
> Did you kill any of the segments?

how can you kill segments? They instantly respawn...

**Comment by nonamecrackers2** [comment]
This should hopefully be fixed. I added a null check to where the crash occurred, so hopefully this won't happen again
