### ISSUE TITLE
[Suggestion]: Clarifcation on issue #1913

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1924]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I do want to apologize for being very vague on what i was insisting. The reason why i made that issue in the first place was due to #1894 stating that a phase 8 or higher could be likely due to #10 not being closed. I wasn't saying a phase 8/nor a bigger bowels was guaranteed

Now as for the suggestion itself it my mistake for even not putting anything there and i didn't really think it through. So here is my idea: If the player decided to wait long enough after 7.5 the wither storm would evolve to phase 8 and a new bigger bowels "dimension" would be accessible. This new bowels would be bigger and more maze-like, at least taking the player a few minutes to even get close to the command block. The new bowels would also be filled with more traps, along with some more loot. This new bowels would be home to a harder command block fight aswell

Its highly likely that this will get closed since phase 8 and a bigger bowels isn't confirmed but atleast i have my idea out.

**Comment by TaintedBlock** [comment]
You uh.. know you could have just made a comment in you suggestion.. right?

**Comment by Luke7381** [comment]
> You uh.. know you could have just made a comment in you suggestion.. right?

I had but no one responded and i think it was better to make a new suggestion anyway, since it was written so bad initially that i don't think anyone would've bothered to check back on it.

**Comment by BluePineappleGuy** [comment]
anyone else find it funny that the storm's entire mass is just the intestines with its heart right by the butthole

**Comment by Aimyx** [comment]
Thanks, BluePine, Now I have to Suffer with this memory every time i think
about how the bowels fits into the storm.

**Comment by nonamecrackers2** [comment]
It's fine, I understand what you were trying to stay. But still, I'd rather not have suggestions, for well, suggestions. It'd be to our discretion whether or not the bowels would be larger or not.
