### ISSUE TITLE
Withered Mutant

### ISSUE THREAD

**Issue by kapycta123456** [nonamecrackers2/crackers-wither-storm-mod#1925]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

![4235,44](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/148063104/d30ee0d4-0267-49fd-93be-b7826609f602)
Withered mutant has a wither storm's head and some tentacles in the back
He has some of abilities:
1: Tentacle Teleport (Shown on picture)
Withered Mutant teleports his tentacle through his portal and stuns the player
Effects: Blindness lasts 5 seconds and Slow effect that lasts 5 seconds too
Cooldown: 15 seconds
Damage: 9.5 hearts
2: Tractor Beam
Withered mutant enables his Eye's tractor beam and pulls the player.
Cooldown: 25 seconds
Damage: none
3: Tentacle Attack
Withered Mutant attacks player with tentacles and pushes him 5 blocks away
Cooldown: 10 seconds
Damage: 7.5 hearts
4: Slash
Withered Mutant punches player
Cooldown: 2 seconds
Effects: Bleeding (lasts 3 seconds, damage per second: 3 hearts)
Damage: 3.5 hearts.
5: Bite
Withered Mutant Bites player
Cooldown: 25 seconds
Damage: 10 hearts

Size: 3 blocks
Speed: A little faster than player's sprint
Health: 15 hearts
Appearance: When Wither Storm died (max: 5), In the bowels (max: 2) or getting summoned by symbiont (max: 1)

Hope you'll add it :>
(You can change some things if you don't like them)

**Comment by kapycta123456** [comment]
You also can change his name too if you don't like it

**Comment by TaintedBlockmObile** [comment]
Way out of scope of the mod. Cool idea though

**Comment by kapycta123456** [comment]
> Way out of scope of the mod. Cool idea though

Wait how?

**Comment by kapycta123456** [comment]
> Way out of scope of the mod. Cool idea though

How is it out of scope of the mod?

**Comment by GearsawStudios** [comment]
This violates guidelines, no new mobs.

**Comment by BluePineappleGuy** [comment]
> This violates guidelines, no new mobs.

thats in the guidelines?
aw man, this would've been a great miniboss to go along with the symbiont

**Comment by nonamecrackers2** [comment]
> This violates guidelines, no new mobs.

No, it's no sickened mob variant suggestions. This isn't a sickened mob variant.

Regardless, this is out of scope for the mod. Interesting idea though

**Comment by BluePineappleGuy** [comment]
aw man, a new miniboss would've been awesome. but in any case it doesn't really have a clear place in progression so it makes sense that its out of scope.

**Comment by Cod1ngGamer** [comment]
If kapycta have coding skills, maybe they could just make this an addon or put it in a modpack.
