### ISSUE TITLE
Wither Storm Models Changeable With Resource Packs 

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#1926]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Hi There, It Would Be Good If You Make People Able To Change The Wither Storm Models With Resource Packs Since It Would Mean That The Mod Would Be More Customizable, Like For Example: Since The Formidi Bomb And Super TNT Models Are Replacable With Resource Packs 

How You Can Make It For Example Is Giving Every Phase A File, And With A Setting You Can Select So It Will Load These Files In The Mod

**Comment by WitherBean** [comment]
This is already possible. I have done it before.

**Comment by LucasDotje** [comment]
> This is already possible. I have done it before.

Wait How?

**Comment by WitherBean** [comment]
Entity model features and entity texture features.

**Comment by WitherBean** [comment]
You can export models and change them for any entity.

**Comment by LucasDotje** [comment]
> Entity model features and entity texture features.

Okay How Do I Access That?

**Comment by WitherBean** [comment]
https://github.com/Traben-0/Entity_Model_Features/blob/master/FEATURES.md

**Comment by LucasDotje** [comment]
> https://github.com/Traben-0/Entity_Model_Features/blob/master/FEATURES.md

Okay So I Can Use Blockbench For The Models Right?

**Comment by WitherBean** [comment]
idk

**Comment by LucasDotje** [comment]
> This is already possible. I have done it before.

Can You Maybe Share How You Were Able To Create The Models?

**Comment by BluePineappleGuy** [comment]
So this means that we can do the drastic model changes ourselves and just make a resource pack or send it to crackers so he doesn't have to do it himself.

Yeah if i can figure this out i'm fixing the stage 6 model

**Comment by Herobrine982950291** [comment]
> > This is already possible. I have done it before.
> 
> Can You Maybe Share How You Were Able To Create The Models?

Hi, Lucas! Love your content! (btw i suggested to change the models in your new pack)

**Comment by nonamecrackers2** [comment]
You can do this with Entity Model Features and other mods, as WitherBean has already mentioned

**Comment by LeonGamerPS1** [comment]
how would i get the models lol
