### ISSUE TITLE
[Bug]: Game Crash on Wither Storm Spawning

### ISSUE THREAD

**Issue by Onemario1234** [nonamecrackers2/crackers-wither-storm-mod#1927]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.32

### Describe the bug

Whenever the Wither Storm spawns in any capacity, or even if I join an existing world before the mini-update with the Wither Storm spawned, the game completely crashes.

### Steps to Reproduce

1. Start world
2. Summon Wither Storm
3. Crash

### Crash Reports/Logs

https://pastebin.com/hk0mqJ5Y

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/25996506/22c168c4-3d5d-4713-81c9-6ef9c83680da)

**Comment by FrozenDragon0** [comment]
Definitely sounds like a mod conflict, also use Embeddium instead of Rubidium.

**Comment by nonamecrackers2** [comment]
Seems like a bug with rubidium, try using Embeddium as FrozenDragon0 suggested

**Comment by Onemario1234** [comment]
Yep, it worked! Thanks!
