### ISSUE TITLE
[Suggestion]: Visible beam particles from afar

### ISSUE THREAD

**Issue by SrSpud** [nonamecrackers2/crackers-wither-storm-mod#1929]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

In the mod, the tractor beam particles only render when the storm is close to the player, but not from far away. So, i think that a config option to toggle far beam particle rendering would be nice

**Comment by CosmicOpswastaken** [comment]
I understand that but also seems weird ngl but great idea

**Comment by nonamecrackers2** [comment]
This is intended. They wouldn't be very visible from far away and would cause unnecessary lag
