### ISSUE TITLE
[Suggestion]: heads render from far

### ISSUE THREAD

**Issue by CosmicOpswastaken** [nonamecrackers2/crackers-wither-storm-mod#1930]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I think it would be a great idea to see the heads from far. To me it's weird how you can the tractor beans from far but not the heads from that far.

**Comment by Pandaboi25x** [comment]
The heads are there, they just arent that visable

**Comment by CosmicOpswastaken** [comment]
> The heads are there, they just arent that visable

I zoom in and see nothing

**Comment by TaintedBlockmObile** [comment]
> > The heads are there, they just arent that visable
> 
> I zoom in and see nothing

Well they blend in with the distant rendering mass. But the heads do indeed render. That's how the tractor beams move

**Comment by Herobrine982950291** [comment]
If the Storm goes sideways, you may be able to BARELY Spot the heads.

**Comment by BluePineappleGuy** [comment]
Since the heads are not very visible from afar, maybe basic shading or darkening should be applied to them (config)

**Comment by Magiciandseq3** [comment]
close distant fog

**Comment by nonamecrackers2** [comment]
They blend in with the mass which is intended. You can turn off distant fog as mentioned if you want to see them.
