### ISSUE TITLE
[Bug]: JVM crash with Immersive Portals

### ISSUE THREAD

**Issue by soup587** [nonamecrackers2/crackers-wither-storm-mod#1931]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

NeoForge

### Mod Loader Version

47.1.105

### Describe the bug

Having a Wither Storm nearby while having Immersive Portals installed will quickly cause a JVM crash. I believe the issue relates to block cluster rendering.
Note - I _am_ running Immersive Portals via Sinytra Connector, but it does an excellent job with rendering based mods so I don't believe the issue is because of Connector (though not like it could be tested otherwise)

### Steps to Reproduce

1. Install Immersive Portals (via Sinytra Connector)
2. Summon a Wither Storm
3. Vibe for a short while

### Crash Reports/Logs

https://gist.github.com/soup587/9b360cefb7c75654dd45786163afd94f

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

200+ - not reasonable to list

**Comment by GearsawStudios** [comment]
ModernFix is enabled, uninstall that first since that also causes a JVM error.

**Comment by GrandmaPork** [comment]
Doesn’t immersive portals have a forge version? This crash is likely one immersive portals would need to fix because it breaks everything

**Comment by soup587** [comment]
> ModernFix is enabled, uninstall that first since that also causes a JVM error.

I have the patch that causes the crash disabled, this one's a different crash

**Comment by soup587** [comment]
> Doesn’t immersive portals have a forge version? This crash is likely one immersive portals would need to fix because it breaks everything

It does, but it's not on 1.20

**Comment by Cod1ngGamer** [comment]
At the bottom of the Immersive Portals description, it says that it's not recommended to use Sinytra, so that might actually be the issue. It's also apparently only compatible with one version of sodium/iris, so that might be contributing if they're installed.

**Comment by GrandmaPork** [comment]
yeah i would screenshot your modlist, even if it is 200 mods. So people can point out if you have incompatible mods.

**Comment by soup587** [comment]
forgot which setting it was but disabling one of the block cluster optimizations fixed the issue

tried on a fresh instance and it occurs with just cwsm, sinytra and immersive portals

**Comment by nonamecrackers2** [comment]
I've tested this with the latest versions of Sinytra (1.0.0-beta.45+1.20.1), Forgified Fabric API, (0.92.2+1.11.8+1.20.1) CWSM (4.1), and Immersive Portals (3.3.9-mc1.20.1-fabric) and cannot replicate this issue. It may have gotten fix, but it's more likely that this is just such an obscure and hard-to-replicate bug using very experimental mods. I doubt I'll be able to fix this if you're still experiencing it,
