### ISSUE TITLE
[Bug]: Witherstorm Crashes when using Modern fix when in Render dist

### ISSUE THREAD

**Issue by TheRugIsGone** [nonamecrackers2/crackers-wither-storm-mod#1933]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.32

### Describe the bug

When the witherstorm renders (when it gets into your render range) it crashes after a short time

### Steps to Reproduce

Get into bossbar range of the witherstorm. Wait a bit. Tadaaaa

### Crash Reports/Logs

Exit Code:1

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

AppleSkin
Better chunk loading[Forge/Fabric]
Better Fps - Render Distance[Forge]
Better Third Person
BetterF3
Bookshelf
Chunk Sending[Forge/Fabric]
Clean Swing Through Grass
Cloth Config API (Fabric/Forge/NeoForge)
Connectivity[Forge/Fabric]
Controlling
Cracker's Wither Storm Mod
Cupboard
Dynamic View[Forge]
Embeddium
Embeddium (Rubidium) Extra
Embeddium/Rubidium Dynamic Lights
Embeddium++
Enchantment Descriptions
Farsight [Forge]
Fast Async World Save[Forge/Fabric]
FerriteCore ((Neo)Forge)
fix GPU memory leak[Forge/Fabric]
Jade 🔍
Just Enough Items (JEI)
Just Zoom [Forge]
Konkrete [Forge]
Memory Settings[Forge/Fabric]
ModernFix
Mouse Tweaks
Not Enough Animations
Not Enough Crashes (Forge)
Oculus
Radium Reforged
Saturn
Searchables
Server Performance - Smooth Chunk Save[Forge/Fabri
spark
starlight
Structure Essentials[Forge/Fabric]

**Comment by Cod1ngGamer** [comment]
The culprit here is ModernFix. When it's installed, it tries to free up memory already freed by CWSM, and the JVM crashes. I made a bug report on the ModernFix page at https://github.com/embeddedt/ModernFix/issues/405, one of the comments said that you can fix it by adding mixin.bugfix.buffer_builder_leak=false at the bottom of config/modernfix-mixins.properties.

**Comment by TheRugIsGone** [comment]
Ahhhh I see
Thanks for the help!

**Comment by BluePineappleGuy** [comment]
you can close this since the bug has happened and is being tracked on a different issue. this one is a duplicate
