### ISSUE TITLE
[Suggestion]: Block Clusters TPS upgrade thingy thing thing

### ISSUE THREAD

**Issue by TheRugIsGone** [nonamecrackers2/crackers-wither-storm-mod#1934]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

If block clusters are off/not being rendered. make the Clusters instantly add Consumed Entity's to the wither storm to prevent TPS lag

**Comment by BluePineappleGuy** [comment]
this should probably only apply in WS loaded chunks, should also be configurable so replay mod users can still see clusters

**Comment by nonamecrackers2** [comment]
This wouldn't be possible since whether they render or not is purely client side, while them being consumed is purely server side. This would also be very strange to witness, since clusters will just randomly disappear.
