### ISSUE TITLE
[Suggestion]: Entity command block

### ISSUE THREAD

**Issue by rjdxxxxxccc** [nonamecrackers2/crackers-wither-storm-mod#1935]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the player's hitbox touches the hitbox of the command block in this module, all the player's equipment will be absorbed, but attacking it will not be absorbed.

**Comment by BluePineappleGuy** [comment]
so the command block steals your stuff?

seems very annoying, frustrating, and unnecessary. losing items to the storm is why the phlegm block was added.

**Comment by Cod1ngGamer** [comment]
Yeah, this doesn't seem like a good idea, it's the kind of thing that would make you rage quit.

**Comment by LegendaryGodzilla** [comment]
Not a good idea

**Comment by nonamecrackers2** [comment]
This would be very unexpected if this was to happen to you, and would be very frustrating and infuriating for players.
