### ISSUE TITLE
[Suggestion]: infinite stages 

### ISSUE THREAD

**Issue by CosmicOpswastaken** [nonamecrackers2/crackers-wither-storm-mod#1936]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I think it would be great for a infinite amount of stages or more stages.

**Comment by Pandaboi25x** [comment]
More stages are coming soon but deff wont be an infinite amount

**Comment by NinjaSam5399** [comment]
after phase 100, game crash.

**Comment by NinjaSam5399** [comment]
So we wouldn't want infinite stages.

**Comment by CosmicOpswastaken** [comment]
Infinite stages would be impossible lol I just think their should be more

**Comment by Luke7381** [comment]
"infinite" phases technically could be possible as engender was able to do so. However that would require a huge rework and model changes, and according to crackers adding new phases is hard enough. So i don't think this will be accepted

**Comment by SSgamingYT** [comment]
Using a trained AI to place cubes, this could be possible. However, too many cubes=lag problems so idk

**Comment by WATERfang132** [comment]
crackers wither storm update: the infinite stage wither storm, never coming out because there is constantly a new model being made lol.

**Comment by pigsbane** [comment]
you could just constantly combine cubes into meshes to improve performance but too much meshes constantly getting larger would get laggy

**Comment by Aimyx** [comment]
"you could just" is one of the most wrong statements that could ever exist.
Mod development is NOT as easy as "just do it"

**Comment by pigsbane** [comment]
whoa sorry i meant it as a suggestion

**Comment by nonamecrackers2** [comment]
Infinite stages wouldn't be very feasible considering how the mod is built. Would be pretty cool though. If I could procedurally generate models that would be great, but that's just not possible right now.
