### ISSUE TITLE
[Suggestion]: every mob has a sickened variant 

### ISSUE THREAD

**Issue by CosmicOpswastaken** [nonamecrackers2/crackers-wither-storm-mod#1937]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Detail

**Comment by Pandaboi25x** [comment]
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/d9f39698-bc23-4e42-bd7a-d5f77484ef7f)
actually read the guide lines please

**Comment by GearsawStudios** [comment]
Please read guidelines before posting, you’ve made two invalid submissions in a row.

**Comment by NinjaSam5399** [comment]
Just read the guidelines.

**Comment by Luke7381** [comment]
Read the guidelines. Most mobs will have a sickened variant in the updates to follow.
