### ISSUE TITLE
[Bug]: Certain Sickened and Normal mobs not attacking each other.

### ISSUE THREAD

**Issue by RepositoryLover** [nonamecrackers2/crackers-wither-storm-mod#1941]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

Sickened Pillager and Normal Pillagers aren't attacking each other, nor are Sickened Vindicators attacking the normal Pillagers. Instead, they both attack Sickened Iron Golems.

### Steps to Reproduce

1. Spawn a Sickened Pillager
2. Spawn a Pillager
3. Spawn a Sickened Iron Golem
4. See that the normal Pillager and Sickened Pillager don’t attack each other and that they both attack the Sickened Iron Golem

### Crash Reports/Logs

None

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

None

**Comment by Herobrine982950291** [comment]
Fill in the Steps to Reproduce so we can try to replicate this.

**Comment by RepositoryLover** [comment]
> Fill in the Steps to Reproduce so we can try to replicate this.

There! I edited it.

**Comment by pigsbane** [comment]
i think this is caused by team tags in the wither storm fight itself

**Comment by RepositoryLover** [comment]
> i think this is caused by team tags in the wither storm fight itself

This bug actually happens all the time.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
