### ISSUE TITLE
[Bug]: Wither storm did not die when command block died.

### ISSUE THREAD

**Issue by LCVaccMan5** [nonamecrackers2/crackers-wither-storm-mod#1942]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

TLancher

### Describe the bug

When I killed the command block, and hit F1 during the command block death animation, I was still in the storm the block was gone but when I jump down the Wither storm was still alive. I well try to recrate the bug.

### Steps to Reproduce

1. Go to the bowels
2. Kill command block
3. Hit F1 mid animation

### Crash Reports/Logs

No crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Wither storm, Just enough items.

**Comment by GearsawStudios** [comment]
TL is a pirated version and is unlikely to receive support.

**Comment by LCVaccMan5** [comment]
Ok, I now have screenshots. :)

**Comment by nonamecrackers2** [comment]
We do not support TLauncher here. Please make a new issue using a legitimate launcher that doesn't allow bypassing the paywall to play the game.
