### ISSUE TITLE
[Suggestion]: Minor Special Effect for block clusters and debris

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1943]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Maybe block clusters that are small (1 block) have a 25% chance of orbiting into the debris field and adding a new block in the debris? 

This would obviously cause a lot of lag, so maybe after around 5 minutes the blocks in orbit would slowly close their orbits until eaten by the wither storm.

 This could also work for other small debris that are smaller than 5 blocks, as well as some bigger block clusters breaking down into that size to orbit the storm temporarily.

**Comment by Luke7381** [comment]
As cool is this would be im not sure if this would look good since there is debris rings moving around the wither storm.

**Comment by SSgamingYT** [comment]
It would be an addition to the already existing debris clouds

**Comment by TheRugIsGone** [comment]
Honestly I think it'd be cool if thats how the witherstorm got the debris rings around it

**Comment by nonamecrackers2** [comment]
This would be complicated and wouldn't be very noticeable in my opinion considering the amount of effort this would take to implement
