### ISSUE TITLE
[Bug]: A LOT OF LAG in one of the symbiont abilities

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1945]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.30

### Describe the bug

A bug happened! When the Symbiont throws Withered Balls (or whatever they are) at me, it emits a lot of Wither particles which causes a lot of lag!

### Steps to Reproduce

1. Summon Symbiont
2. Wait for it to shoot WitherBalls at you
3. See Error

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

NONE

**Comment by Luke7381** [comment]
Im pretty sure your referring to the fireball attacks right? the symbiont is able to use normal and dragon fire balls.

the exact same happens to me aswell.

**Comment by pigsbane** [comment]
just get a better computer or turn off particles

**Comment by watersofnazareth** [comment]
I'll probably tone their particles down, currently they use the same particle count as the normal Dragon Fireballs

**Comment by Herobrine982950291** [comment]
> just get a better computer or turn off particles

I don't have enough to buy a new one yet. I can't turn off particles either because it ruins the astonishing look of Minecraft.

**Comment by BluePineappleGuy** [comment]
withered what

**Comment by Herobrine982950291** [comment]
those withered Fireballs which he shoots at you? The ones that emit Wither Particles?

**Comment by Luke7381** [comment]
> those withered Fireballs which he shoots at you? The ones that emit Wither Particles?

Those are supposed to be dragon fire breath, its stated in the changelog.

**Comment by Herobrine982950291** [comment]
oh, really? ok. Just tone down the amount of particles.

**Comment by nonamecrackers2** [comment]
Particles were slightly readjusted (not necessarily toned down). If they cause too much lag, just turn them down (that's why the option exists), nothing much else we can do for you here.

**Comment by Herobrine982950291** [comment]
welp i guess we're stuck with laggy ahh wither balls.
