### ISSUE TITLE
[Bug]:  CWSM music doesn't work unless using a Resource Pack??

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#1947]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.32

### Describe the bug

So I didn't have my resource pack on and I realized the default CWSM music wasn't functioning (it has been very inconsistent). Then I realized the music ALWAYS works whenever I have my resource pack on (CWSPLUS, just incase I need to clarify). 

### Steps to Reproduce

1. Get a cwsm resource pack that changes the boss music
2. Compare vanilla cwsm with the resource pack
3. See error

### Crash Reports/Logs

No crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM and other mods (mostly client) that don't affect CWSM's music. Others seem to have had the music issue so I don't think they would do anything.

**Comment by LegendaryGodzilla** [comment]
Budget Cuts

**Comment by nonamecrackers2** [comment]
Other mods have the music issue? Are you sure it's just a CWSM thing then?

**Comment by TaintedBlock** [comment]
> Other mods have the music issue? Are you sure it's just a CWSM thing then?

No I meant other people experience hearing no music. While I haven't yet

**Comment by nonamecrackers2** [comment]
Oh I see I thought you were in reference to your mod list

**Comment by FalconinVoid** [comment]
Thank you very much! Now I can play the mod with music and found an amazing new resouce pack!

**Comment by nonamecrackers2** [comment]
Can't really replicate. I figured out an issue regarding loading resource packs that would cause the music to stop working, but that'll be fixed in the next major release. Hopefully that will prevent this from happening again.
