### ISSUE TITLE
[Bug]: The Ender Dragon bugs out when it flies to the ws

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#1948]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

not related

### Describe the bug

If the ws is on top the bedrock it holds the ender dragon when it goes to its defeated place

### Steps to Reproduce

1. Defeat the ender dragon
2. let the ws be on top the bedrock in the middle
3. wait for the ender dragon to go to its defeated place

### Crash Reports/Logs

no

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/074041ff-9f07-407e-a4b0-a118d71ba71a)

### Mod List

Pretty sure cwsm is the only one thats doing this

**Comment by Pandaboi25x** [comment]
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/121638798/b6401317-fe37-44cd-8350-2c1f2ed8384e)
i just learned tping the ws out of it MAKES THE DRAGON BE PULLED BY THE TRACTOR BEAMS??

**Comment by Herobrine982950291** [comment]
The ws sucking it in may be intentional (could be wrong tho).

**Comment by Amelintrus** [comment]
The "Mod List" part is meant to specify all of the mods installed, not the ones that may be causing the bug.

**Comment by BluePineappleGuy** [comment]
why does the WS look weird, are those accurate tentacles

**Comment by Herobrine982950291** [comment]
I can tell by the bossbar that he's using CWSP.

**Comment by RepositoryLover** [comment]
@Pandaboi25x , Please close this issue.

**Comment by BluePineappleGuy** [comment]
> @Pandaboi25x , Please close this issue.

Why?

**Comment by RepositoryLover** [comment]
> > @Pandaboi25x , Please close this issue.
> 
> Why?



> > @Pandaboi25x , Please close this issue.
> 
> Why?

Because this mod your showing us is not CWSM. It's a different Wither Storm mod.

**Comment by Pandaboi25x** [comment]
> > > @Pandaboi25x , Please close this issue.
> > 
> > 
> > Why?
> 
> > > @Pandaboi25x , Please close this issue.
> > 
> > 
> > Why?
> 
> Because this mod your showing us is not CWSM. It's a different Wither Storm mod.

what are you talking about its cwsm im using a resource pack buddy 😭

**Comment by Pandaboi25x** [comment]
> why does the WS look weird, are those accurate tentacles

im using Fresh animations wither storm

**Comment by Pandaboi25x** [comment]
> The "Mod List" part is meant to specify all of the mods installed, not the ones that may be causing the bug.

i dont think i have to specify every mod in my mod list when theres just a ws and an ender dragon, its pretty obvious its just the ws

**Comment by Pandaboi25x** [comment]
> The ws sucking it in may be intentional (could be wrong tho).

the ws sucking it shouldnt be cuz the dragon cant die now

**Comment by BluePineappleGuy** [comment]
> > The "Mod List" part is meant to specify all of the mods installed, not the ones that may be causing the bug.
> 
> i dont think i have to specify every mod in my mod list when theres just a ws and an ender dragon, its pretty obvious its just the ws

some mods may mess with WS ai or dragon behavior. best to share it just in case

**Comment by Herobrine982950291** [comment]
> > The ws sucking it in may be intentional (could be wrong tho).
> 
> the ws sucking it shouldnt be cuz the dragon cant die now

oh, right.

**Comment by nonamecrackers2** [comment]
It shouldn't be targeting the ender dragon in the first place, weird

**Comment by Pandaboi25x** [comment]
> It shouldn't be targeting the ender dragon in the first place, weird

it happens cuz the dragon flies to the ws which angers the storm so then it happens

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
