### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#195]
**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by nonamecrackers2** [comment]
This provides no context or explanation of what "didn't work." Please fill in the template you were given.
