### ISSUE TITLE
[Suggestion]: Wither Storm Highers/Lowers (READ DESC)

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#1950]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the storm is far away from the target and is going after it, make it so the storm slightly gets higher and when it's in render of the target, lower the storm. Can be set to config if need be.

**Comment by TaintedBlock** [comment]
Technically this can be done just like this via datapacks, or just use dynamic flying height

**Comment by Herobrine982950291** [comment]
Really? I never knew that!

**Comment by BluePineappleGuy** [comment]
i guess you could close this issue since you can do what @TaintedBlock said, unless you want crackers to add this specific functionality to dynamic flying height (if its not already a part of it)

**Comment by nonamecrackers2** [comment]
I probably won't, wouldn't be super useful for the work I'd put to implement it
