### ISSUE TITLE
[Bug]: Villagers not running away

### ISSUE THREAD

**Issue by RepositoryLover** [nonamecrackers2/crackers-wither-storm-mod#1951]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

Villagers eventually stop running away from the Wither Storm.

### Steps to Reproduce

1. Summon Wither Storm
2. See Villagers run away at first
3. They eventually stop running.

### Crash Reports/Logs

None

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

No other mods other than CWSM.

**Comment by WitherBean** [comment]
This is not a bug.

**Comment by BluePineappleGuy** [comment]
> This is not a bug.

i thought they were supposed to run away constantly?

**Comment by nonamecrackers2** [comment]
They eventually reach a far enough distance where they stop
