### ISSUE TITLE
[Suggestion]: can we change head models?

### ISSUE THREAD

**Issue by Magiciandseq3** [nonamecrackers2/crackers-wither-storm-mod#1953]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

hello there is a way to change head models?

**Comment by Herobrine982950291** [comment]
What changes would you like, exactly?

**Comment by BluePineappleGuy** [comment]
with a mod that adds the optifine entity model features (not optifine
itself its very buggy with this mod), yeah, you could.
also questions like this would be better to ask in the discussions tab

**Comment by nonamecrackers2** [comment]
> with a mod that adds the optifine entity model features (not optifine itself its very buggy with this mod), yeah, you could. also questions like this would be better to ask in the discussions tab

Second this
