### ISSUE TITLE
[Bug]: Invisible World

### ISSUE THREAD

**Issue by TeeJayMac** [nonamecrackers2/crackers-wither-storm-mod#1954]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.17

### Describe the bug

Whenever I create a new world, the entire world is invisible. I can see my inventory and hotbar, but the rest of the world, particles, and entities are invisible. This only happens when I add CWSM to my modpack, once I remove it, everything is fine again.

### Steps to Reproduce

1. Go to singleplayer
2. Create a new world
3. The entire world is invisible

### Crash Reports/Logs

https://drive.google.com/file/d/1Apmz2e9UfD0hSDXWIHDAH8y8nBdzQlf_/view?usp=sharing

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-05-25_15 32 11](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/127977563/2c64673a-8db7-4f8e-8357-99660a06e4a6)
![2024-05-25_15 32 16](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/127977563/526a9003-3ded-4eb9-9154-6b2b62f70461)
![2024-05-25_15 32 22](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/127977563/6a263ca5-2175-4aff-8c67-13b332718193)

### Mod List

All of the mods should be in these screenshots
![Screenshot 2024-05-25 153901](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/127977563/fabc644f-91af-4c86-bcfb-ddfd0e42ce1c)
![Screenshot 2024-05-25 153915](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/127977563/68fe9e44-3e42-4c04-b87e-9312875b27eb)

**Comment by Herobrine982950291** [comment]
Try it without those mods.

**Comment by watersofnazareth** [comment]
Try removing mods that affect game rendering, you have a lot of mods installed so it's hard for us to really say without installing all of your mods ourselves, it could also be an issue with shaders

**Comment by TeeJayMac** [comment]
I forgot to follow up on this yesterday, I went through the mods and it was being caused by the update for the man from the fog because of the new fog rendering stuff that was added. for now i'm just gonna downgrade TMFTF a version and make a bug report in their discord server

**Comment by watersofnazareth** [comment]
Ah yeah that would be an issue on their side, for now I'm going to close this issue
