### ISSUE TITLE
[Bug]: music isnt always playing when it should, tractor beams dont always work

### ISSUE THREAD

**Issue by BusinessBear99** [nonamecrackers2/crackers-wither-storm-mod#1955]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

forge 47.2.0

### Describe the bug

A bug happened!
music wont play when it should and tractor beams rarely pick up mobs
also here's some feature suggestions https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1952#issue-2317145730

### Steps to Reproduce

1. play the mod and 50% of the time the music wont play
2. most of the time tractor beams wont pick up mobs

### Crash Reports/Logs

bug

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

embedium and other mods
(none that should affect these issues)

**Comment by watersofnazareth** [comment]
Do you mind being more descriptive with the second part? also, if you have 2 issues please open a different issue instead of putting multiple in one

**Comment by nonamecrackers2** [comment]
Also, please include your full mod list, and you don't need to advertise other issues here. We see all of them eventually.

**Comment by watersofnazareth** [comment]
Until this is answered I'll close it
