### ISSUE TITLE
Making a fabric port would take a lot of time that I’m not willing to invest. I’d like to make one but don’t want to spend the effort at the moment.

### ISSUE THREAD

**Issue by Sansthegamer248** [nonamecrackers2/crackers-wither-storm-mod#1956]
The game crashes with optifine but not with oculus

**Comment by juanelgamer456** [comment]
most confusing github ever

**Comment by TaintedBlock** [comment]
What even is this?? Please close it

**Comment by FrozenDragon0** [comment]
> The game crashes with optifine but not with oculus

If you want Fabric then use Forgified Fabric API + Sinytra Connector to run both Forge and Fabric mods together, also please close this.

**Comment by Bloxxify2827** [comment]
Least confusing github issue post

**Comment by BluePineappleGuy** [comment]
i wake up in the morning and what the heck why is the title like that
