### ISSUE TITLE
[Bug]: Cave Rumble command not working

### ISSUE THREAD

**Issue by DonCinnamon** [nonamecrackers2/crackers-wither-storm-mod#1958]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

Whenever I run the command /witherstormmod config server server.caves.caveRumbles true/false the chat logs say that it changes server.caves.caveRumblesMessWithRedstone instead of server.caves.caveRumbles. 

### Steps to Reproduce

1. Join world with cwsm
2. run command /witherstormmod config server server.caves.caveRumbles false
3. See error

### Crash Reports/Logs

https://pastebin.com/ChEexrrn

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

AgeOfWeapons-Reforged-1.20.2-(v.1.3.2a)
create-1.20.1-0.5.1.f
createsifter-1.20.1-1.8.1.e-22
darkblades-forge-1.20.1-1.2.5
easy_villagers-1.20.1-1.0.17
endgameenhanced-1.1.5-forge-1.20.1
entity_model_features_forge_1.20.1-2.0.2
entity_texture_features_forge_1.20.1-6.0.1
geckolib-forge-1.20.1-4.4.4
immersive_weathering-1.20.1-2.0.1-forge
ironchest-1.20.1-14.4.4
ironfurnaces-1.20.1-4.1.6
jei-1.20.1-forge-15.3.0.4
Mekanism-1.20.1-10.4.6.20
MekanismGenerators-1.20.1-10.4.6.20
MekanismTools-1.20.1-10.4.6.20
moonlight-1.20-2.11.28-forge
Nullscape_1.20.x_v1.2.5
skinlayers3d-forge-1.6.4-mc1.20.1
voicechat-forge-1.20.1-2.5.15
weaponmaster_ydm-forge-1.20.1-4.2.3

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
