### ISSUE TITLE
[Suggestion]: Purple Wither Skulls and Violet Wither Skulls

### ISSUE THREAD

**Issue by RepositoryLover** [nonamecrackers2/crackers-wither-storm-mod#1959]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Like a wither skull but inflicts wither sickness. It has a rare chance of being shot by the wither storm. Phases 0-3 have a chance of shooting a normal one and all Phases have rarer chance of shooting a flaming one. The flaming one can also cover the impacted area with Wither Sickness so even without being damaged by the explosion, you still can get Wither Sickness by being in that area after the explosion. Also, there can be Violet Wither Skulls: a mixture of blue and purple wither skulls, both inflicting wither sickness and breaking obsidian. Violet Wither Skulls will have a flaming variant too and has a rare chance of being shot out when a Wither Storm's head gets damaged. These new purple and violet wither skulls will also have red eyes like the sickened mobs. I hope I explained all of this well.

**Comment by nonamecrackers2** [comment]
There are already flaming wither skulls. Besides that, I do not want to spread wither sickness through the skulls. Your suggestion implies that the spread of the effect should be instantaneous when the skull explodes. Instead it should probably add to a counter that starts wither sickness when it reaches a certain threshold, but again I don't really want the skulls spreading wither sickness. I also don't want to add more skull variants than needed (unless if Naza wanted to texture and add it, not sure).
