### ISSUE TITLE
Big hole

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#196]
1.16.5
The version of Minecraft the mod is running on

Any
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

![2022-07-08_04 52 55](https://user-images.githubusercontent.com/108914903/178105637-15dfcac2-a048-444f-9be8-e919a20eb5e2.jpeg)

**Comment by witherstormfan87** [comment]
Increasing the ram didn't work

**Comment by nonamecrackers2** [comment]
Not sure then. What are you using to run the mod?

**Comment by nonamecrackers2** [comment]
I don't think I could reproduce this issue, and I think it's down ultimately to your hardware or some other limitation that I am not aware of. I'm unsure of how to fix this, sorry.
