### ISSUE TITLE
[Bug]: Symbiont pull attack can behave strangely with snow layers

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1961]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.19.4

### Mod Version

3.3.1.1

### Mod Loader

Forge

### Mod Loader Version

45.2.0

### Describe the bug

A bug happened!

Symbiont pull attacks can layer snow layers on snow layers, creating floating snow layers. Might be a Won't Fix issue.

### Steps to Reproduce

Fight symbiont in a snowy area, wait for it to charge up the fling attack and watch as snow will float above snow.

### Crash Reports/Logs

Unlikely to matter since it's not a crash, will provide if needed.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/122060314/a28859dc-23b9-4962-adbf-6e74e93f0a67)

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/122060314/64ca4c36-8b1e-463e-8596-58b4ae9b10d4)

**Comment by GearsawStudios** [comment]
On the same subject (might need a different report) if you stand in one area too long during the attack's wind up it'll make a square area of snow get flung, showing the exact range and looking unnatural.

**Comment by TheRugIsGone** [comment]
I think the issue is caused by the fact (I am not a Modder take everything I say with couple grains of salt) that the explosion uses minecraft's tnt code. Where is just shoots out like a bajillion lines in a cube-ish pattern
(Same thing happens with like stupidly powerful TNT explosions)

**Comment by Cod1ngGamer** [comment]
It's not a bug, it's a feature.

**Comment by watersofnazareth** [comment]
> I think the issue is caused by the fact (I am not a Modder take everything I say with couple grains of salt) that the explosion uses minecraft's tnt code. Where is just shoots out like a bajillion lines in a cube-ish pattern (Same thing happens with like stupidly powerful TNT explosions)

Pulse doesn't use the explosion/tnt code, snow layers can be blacklisted but this is an intended behavior due to how it works
