### ISSUE TITLE
[Bug]: Pet Respawning is not run when killing the Wither Storm using /kill

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1967]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

A bug happened!

Tamed pets won't respawn unless the Wither Storm is killed normally.

### Steps to Reproduce

1. Summon and tame a wolf
2. Summon a Phase 7 Wither Storm
3. Kill it using /kill
4. Where doggo?

### Crash Reports/Logs

Logs weren't of use

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM
JEI

**Comment by GearsawStudios** [comment]
Nevermind, /kill being different than /witherstormmod kill means that part is WAI.

**Comment by BluePineappleGuy** [comment]
wai?

**Comment by nonamecrackers2** [comment]
Working as intended
