### ISSUE TITLE
[Bug]: Pet Respawning doesn't work on direct absorbing

### ISSUE THREAD

**Issue by GearsawStudios** [nonamecrackers2/crackers-wither-storm-mod#1968]
### Guidelines

- [ ] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

A bug happened!

When a wolf is killed by indirectly being absorbed (rather than being eaten) it will not respawn after the Wither Storm dies. This also applies to flaming skulls, but that may be illogical to apply the mechanic to.

### Steps to Reproduce

1. Summon a wolf and tame it.
2. Bring Wither Storm (Phase 7) to eat the wolf.
3. Have the wolf eaten through indirect absorbing (the thing that happens when a mob reaches a head and isn't the target so it goes right into the mass.
4. /witherstormmod kill at w
5. Where doggo :cry:

### Crash Reports/Logs

Not useful in this

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM
JEI

**Comment by Cod1ngGamer** [comment]
Wait just a minute. Since when can pets respawn?

**Comment by nonamecrackers2** [comment]
Since the "block and a hard place" update I believe

**Comment by Cod1ngGamer** [comment]
I am so far out of the loop...

**Comment by nonamecrackers2** [comment]
Indirect absorbing was working fine, it turns out that the ``/witherstormmod kill`` command just didn't respawn pets. This has been fixed and will be in the next major release.
