### ISSUE TITLE
[Suggestion]: A more parasitic wither sickness

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1969]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Over time, some blocks could be turned into their tainted variants when under the wither storm for long enough, and the taint could spread across other blocks as well. 

Perhaps tainted mobs could gather on tainted blocks and form tainted flesh mounds (clumps of tainted flesh blocks) that have tentacles that grab and pull in mobs that get too close, and send out the occasional sickened mob to attack players.

**Comment by GearsawStudios** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1739
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1810

**Comment by SSgamingYT** [comment]
a more detailed suggestion for the flesh mound has been posted

**Comment by watersofnazareth** [comment]
Well this is a good idea for something like say Sculk Horde this doesn't work with CWSM
