### ISSUE TITLE
Client Crashing when Joining Server. (1.16.5-1.0.2.3)

### ISSUE THREAD

**Issue by SimpleWolf** [nonamecrackers2/crackers-wither-storm-mod#197]
**Minecraft version**
1.16.5

**Mod version**
1.0.2.3

**Describe the bug**
Client crashing when joining server. This does not occur if the player joins a Singleplayer world before connecting to the server.

**To Reproduce**
1. Load up a Forge 1.16.5 server with the mod installed
2. Join the server
3. Crash

There is actually a workaround to this issue, which is to join a Singleplayer world before connecting to the Multiplayer Server. If the player does not join a singleplayer world beforehand, the game will crash.

**Crash Reports / Logs**
https://pastebin.com/UgiRVs6J

Note: There are multiple mods installed.

**Comment by nonamecrackers2** [comment]
Not sure what could be causing this. If you could pinpoint the exact mod that would be extremely helpful.

**Comment by nonamecrackers2** [comment]
This should hopefully be fixed in the next update.
