### ISSUE TITLE
[Suggestion]: Sickened mob flesh mounds and nests

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1970]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When 10 or more sickened mobs are close to each other, they find a random block on the surface to go to, and cluster up into one area. a 20 second animation plays where a bunch of tainted flesh particles appear, and at the end all of the mobs die and a flesh mound (a 5 block wide mound of tainted and infected flesh blocks) appears, with a few tentacles sticking out of it. 

These tentacles have the ability to grab mobs that get too close, and pull them into the mound, causing it to grow. The mound will also act as a giant phlegm block, pulling in nearby items and absorbing them for growth. These flesh mounds can form into pillars, that form into nests, and over time a similar miniature version of what is seen inside of the main bowels chamber is formed, with two heads and tentacles. However, there is no command block, it is only a pillar in the center.

When the wither storm dies, all sickened entities are cured (already implemented), and the tentacles and heads die and turn into bones and rotten flesh. the rest of the mound collapses, and slowly the blocks inside of it either disappear (flesh blocks will disappear, with a 20% chance to drop rotten flesh or other organic makeups such as bones) or return to their normal variants

If some of this is not possible or is simply too hard to make, feel free to leave those parts out or change them to something else.

**Comment by Infinitekaosv3** [comment]
Good idea, I'd want to be in the mod lol

**Comment by GearsawStudios** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1969#issuecomment-2141090824 Similar idea presented, was deemed out of scope.

**Comment by SSgamingYT** [comment]
> [#1969 (comment)](https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1969#issuecomment-2141090824) Similar idea presented, was deemed out of scope.

The flesh mound doesn't exactly have to have the spreading taint, this suggests it as something separate

**Comment by BluePineappleGuy** [comment]
this is really cool but i doubt it'll be added

**Comment by watersofnazareth** [comment]
Again this seems more of like a parasite/infection mod thing, not something that would fit or work well with CWSM
