### ISSUE TITLE
[Suggestion]: Blocks being grabbed by the tractor beam spin around the beam

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1971]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

There is a scene in MCSM where the wither storm grabs the player's enderman statue, and I noticed how the clusters spin around inside of the tractor beam. This could be a neat detail for clusters in CWSM, that have been grabbed by the tractor beam. 
(I am fully aware of the fact regular clusters spiral around the storm, this is about tractor beam clusters spinning around inside the beam)

**Comment by watersofnazareth** [comment]
Knowing how the Tractor Beam clusters work this would be nearly impossible to do

**Comment by SSgamingYT** [comment]
> Knowing how the Tractor Beam clusters work this would be nearly impossible to do

Maybe it could be included in the animation, like how the cluster spins?

**Comment by watersofnazareth** [comment]
Not logically possible

**Comment by SSgamingYT** [comment]
> Not logically possible

Rip
