### ISSUE TITLE
[Suggestion]: Make the wither storm only fire the big skulls

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1972]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The wither storm should fire flaming skulls that (ironically) don't have fire at the earliest stages, which can be seen inside of the main endercon building in MCSM.

Extra details: 
- The wither storm will fire big skulls at a much slower rate than the current small skulls.
- the big skulls are slightly slower and weaker than the ones fired from stage 4+

**Comment by GearsawStudios** [comment]
This would make it impossible to escape if it targets you early on as flaming skulls already get fired and often hit the player.

**Comment by SSgamingYT** [comment]
> This would make it impossible to escape if it targets you early on as flaming skulls already get fired and often hit the player.

Sorry, I was tired when I made this suggestion. I'll provide better details

**Comment by BluePineappleGuy** [comment]
> This would make it impossible to escape if it targets you early on as flaming skulls already get fired and often hit the player.

theres a reason you have 60 seconds to get the heck away from that monstrosity

**Comment by nonamecrackers2** [comment]
I don't feel this is necessary. The normal wither skulls are used during the hunchback phases, and then when it evolves it uses those occasionally along with the upgraded flaming variants.
