### ISSUE TITLE
[Suggestion]: Block clusters should navigate out of holes before spiraling into the storm 

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1973]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Blocks that are grabbed tend to phase straight through the floor right away while spiraling into the storm. Maybe the clusters could detect the edges of the holes they are in, and move up or down (or in other directions) to get out of the hole they are being grabbed from after shaking

**Comment by Cod1ngGamer** [comment]
lol this is gonna devour my frames

**Comment by SSgamingYT** [comment]
> lol this is gonna devour my frames

Maybe

**Comment by BluePineappleGuy** [comment]
> lol this is gonna devour my frames

Yeah, this is quite impractical. A better solution would be the blocks in the way join the cluster instantly.

**Comment by SSgamingYT** [comment]
> > lol this is gonna devour my frames
> 
> Yeah, this is quite impractical. A better solution would be the blocks in the way join the cluster instantly.

That would cause worse lag than simply just making it move around the blocks

**Comment by BluePineappleGuy** [comment]
> > > lol this is gonna devour my frames
> > 
> > 
> > Yeah, this is quite impractical. A better solution would be the blocks in the way join the cluster instantly.
> 
> That would cause worse lag than simply just making it move around the blocks

not exactly since it would just add them to 1 entity and make them poof into nothing. less lag probably

**Comment by SSgamingYT** [comment]
> > > > lol this is gonna devour my frames
> > > 
> > > 
> > > Yeah, this is quite impractical. A better solution would be the blocks in the way join the cluster instantly.
> > 
> > 
> > That would cause worse lag than simply just making it move around the blocks
> 
> not exactly since it would just add them to 1 entity and make them poof into nothing. less lag probably

Bigger clusters cause more lag, you can see this by simply making a big cluster/tweaking the clusterSizeModifier

**Comment by BluePineappleGuy** [comment]
> > > > > lol this is gonna devour my frames
> > > > 
> > > > 
> > > > Yeah, this is quite impractical. A better solution would be the blocks in the way join the cluster instantly.
> > > 
> > > 
> > > That would cause worse lag than simply just making it move around the blocks
> > 
> > 
> > not exactly since it would just add them to 1 entity and make them poof into nothing. less lag probably
> 
> Bigger clusters cause more lag, you can see this by simply making a big cluster/tweaking the clusterSizeModifier

yeah good point. maybe they just dissapear then, or dont get picked up if they dont have a direct line of sight to the storm

**Comment by SSgamingYT** [comment]
> > > > > > lol this is gonna devour my frames
> > > > > 
> > > > > 
> > > > > Yeah, this is quite impractical. A better solution would be the blocks in the way join the cluster instantly.
> > > > 
> > > > 
> > > > That would cause worse lag than simply just making it move around the blocks
> > > 
> > > 
> > > not exactly since it would just add them to 1 entity and make them poof into nothing. less lag probably
> > 
> > 
> > Bigger clusters cause more lag, you can see this by simply making a big cluster/tweaking the clusterSizeModifier
> 
> yeah good point. maybe they just dissapear then, or dont get picked up if they dont have a direct line of sight to the storm

For immersion, it's probably best if they navigate around obstacles, this can be seen in MCSM too

**Comment by nonamecrackers2** [comment]
It may not be good for immersion but its better for performance. There's already tons of clusters at any given moment and constantly checking the blocks around it to navigate out of them would be very performance heavy.
