### ISSUE TITLE
[Suggestion]: Mobs move to the center of tractor beams

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1974]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

There could be a config that makes grabbed entities always be pushed to the center of tractor beams, to avoid the wither storm dropping mobs when it looks away (similar to how block clusters are grabbed by the beams)

**Comment by TaintedBlock** [comment]
This is already a thing

**Comment by SSgamingYT** [comment]
> This is already a thing

No it isn't, mobs that get grabbed only move partially into the beam once, and there's barely any more force keeping them in

**Comment by TaintedBlock** [comment]
I can assure you, this is 100% a thing. It isn't the most noticable thing because it is a little slow, but it is definitely there.

**Comment by SSgamingYT** [comment]
> I can assure you, this is 100% a thing. It isn't the most noticable thing because it is a little slow, but it is definitely there.

At the very least there should be a config to make the mobs pulled towards the center even more

**Comment by watersofnazareth** [comment]
> This is already a thing

This

**Comment by nonamecrackers2** [comment]
It isn't very noticeable since the mobs would clump up into a very noticeable line, but it is there

**Comment by SSgamingYT** [comment]
> It isn't very noticeable since the mobs would clump up into a very noticeable line, but it is there

Could there be a config to make it pull the mobs into a line? I'm trying to make the storm eat structures and mobs in experiments but the storm eats like one mob then drops the rest because it tries to look at the mob it's targeting

**Comment by nonamecrackers2** [comment]
You should make a new issue for that then
