### ISSUE TITLE
[Suggestion]: Smaller block clusters move faster in tractor beams

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1975]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When blocks are grabbed by the tractor beams, smaller block clusters should move faster than big ones when being pulled up the beam

**Comment by watersofnazareth** [comment]
Don't really know if I'm going to be adjusting the movements of clusters in beams anymore, I like where they are now

**Comment by nonamecrackers2** [comment]
I personally agree
