### ISSUE TITLE
[Suggestion]: Storm heads should to occasional "mob sweeps"

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1976]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The wither storm heads should do occasional "sweeps" across the ground to grab entities (these entities stay inside of the tractor beam like block clusters, unless it is a player or named entity).

 A Sweep would be a head grabbing more block clusters, and keeping all entities inside of the beam without letting them go. Sweeps look like normal looking around at first, but they are slower and the beam has more block clusters in it.

**Comment by TaintedBlock** [comment]
They already do this technically

**Comment by SSgamingYT** [comment]
> They already do this technically

No they don't? By "head sweeps" I mean All Mobs that get caught in the beam while it's moving are grabbed up like block clusters

**Comment by SSgamingYT** [comment]
> > They already do this technically
> 
> No they don't? By "head sweeps" I mean All Mobs that get caught in the beam while it's moving are grabbed up like block clusters

During head sweeps*

**Comment by TaintedBlock** [comment]
> > They already do this technically
> 
> No they don't? By "head sweeps" I mean All Mobs that get caught in the beam while it's moving are grabbed up like block clusters

I understood what you mean, but the heads can technically already do this. Of course, in the way you're describing, it would look much different

**Comment by SSgamingYT** [comment]
> > > They already do this technically
> > 
> > 
> > No they don't? By "head sweeps" I mean All Mobs that get caught in the beam while it's moving are grabbed up like block clusters
> 
> I understood what you mean, but the heads can technically already do this. Of course, in the way you're describing, it would look much different

Head sweeps and head movements would be very different - I think I should add more details in the post

**Comment by nonamecrackers2** [comment]
#1883
