### ISSUE TITLE
[Suggestion]: Wither storm should occasionally tilt over a bit to attack things under it

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1978]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The title is self explanatory, but it would be pretty neat to see the storm flying at an angle. For extra details, the storm should gradually have a lower limit to how much it can tilt the bigger it gets

**Comment by TaintedBlock** [comment]
I don't see a point in this tbh. It kills things just fine

**Comment by SSgamingYT** [comment]
> I don't see a point in this tbh. It kills things just fine

It doesn't have to be super practical, it works as a neat little detail too.

**Comment by Cod1ngGamer** [comment]
Should probably be a config.

**Comment by Cod1ngGamer** [comment]
Should probably be a config option.

**Comment by SSgamingYT** [comment]
> Should probably be a config option.

True

**Comment by Luke7381** [comment]
Crackers doesn't plan on altering animations or the movement of the model so i don't think this will get accepted.

**Comment by watersofnazareth** [comment]
The idea of the model tilting feels really weird, especially since almost no Minecraft mobs do this to begin with, I'm not going to close this issue but Crackers might, for now I'm just going to mark it unlikely

**Comment by SSgamingYT** [comment]
> The idea of the model tilting feels really weird, especially since almost no Minecraft mobs do this to begin with, I'm not going to close this issue but Crackers might, for now I'm just going to mark it unlikely

That's fine, the model never seems to move elsewhere so I kinda expected it

**Comment by nonamecrackers2** [comment]
This would require adjusting the location of the head hitboxes which would be more complicated trig math that I don't want to mess with. Could be cool but not worth the time investment for me as of now.
