### ISSUE TITLE
[Suggestion]: New Automation/ fun blocks

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1979]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Here's a few machine ideas:

Seismic Machine - Upon given a Redstone signal, it causes cave rumbles and collapses nearby buildings. Crafted using a dispenser, a withered support beacon, 2 Redstone blocks, and 5 cobblestone. (Dispenser on the bottom, withered support beacon on the top, Redstone blocks on the left and right middle slots, and cobblestone in the rest)

Strong piston - grabs a player-specified area of blocks and pushes/pulls them. Crafted using 4 phlegm blocks and 4 slime blocks surrounding a sticky piston, and is powered like any normal piston

Tractor Beam Block - pulls in mobs in a specific direction. Right click to change directions, shift right click to select mode. Modes include: grab mobs only, grab blocks only, grab mobs and blocks, and disabled. Grabbed blocks and mobs will be dropped below the machine, if the bottom of the machine is obstructed then it will drop blocks above it. Crafted using a support beacon in the center, with 4 dispensers on the outer middle, and 4 phlegm blocks in the corners. If switching to disabled isn't fast enough, can be disabled through a Redstone signal

Cluster grabber - pulls in nearby block clusters and breaks them apart and converts them to items. Crafted using a tractor beam block surrounded by hoppers, and overrides every form of cluster grabbing.

Jumbler - Swaps random block locations in a 20 block radius every 2 seconds by selecting to blocks (an animation plays where the two blocks are turned into block clusters, dragged to the other's location, and dropped.) Activated by right clicking on it. Crafted by combining a diamond, a cluster grabber, and a support beacon.

Crop harvester - When given a Redstone signal, it harvests and pulls in nearby crops that are fully grown and stores them. Sends a weak Redstone signal through a comparator when it harvests a crop for 100 ticks. Crafted by surrounding a tainted phlegm blocks with composters (at the corners), two Redstone (left and right edges), and two cobblestone (top and bottom edges).

Wither Radar - a block interface that detects the wither storm's position (similar to how weather2's radar works, but with a much wider range) and gives data based on its evolution progress. Crafted using two iron ingots (left and right edges), two Redstone (top and bottom edges), 4 diamonds (corners) and a wither storm tracker (I forgot the name, it was the telescope that tracks data on the wither storm like the phase) Also detects withered symbionts, and regular withers as well. (If these are added, can detect flesh mounds as well)

Those are my suggestions, hope you like the ideas

**Comment by TaintedBlock** [comment]
This is just so far out of scope it isn't even funny lol

**Comment by Cod1ngGamer** [comment]
I love it, but it's probably not gonna be accepted. Maybe if you have some coding skills you can make this into an addon?

**Comment by SSgamingYT** [comment]
> I love it, but it's probably not gonna be accepted. Maybe if you have some coding skills you can make this into an addon?

Unfortunately I can't code

**Comment by BluePineappleGuy** [comment]
awesome but this might be considered multiple suggestions in one, some of which have been suggested in the past (tractor beam block and wither radar). someone who can code should make a mod containing all out-of-scope ideas anyway

**Comment by Cod1ngGamer** [comment]
If I learn how to add cross-mod compatibility with MCreator, I might be able to make this.

**Comment by nonamecrackers2** [comment]
Interesting ideas but this is out of scope for the mod. Could be a neat addon though

**Comment by BluePineappleGuy** [comment]
> If I learn how to add cross-mod compatibility with MCreator, I might be able to make this.

MCreator would be difficult to add most of the things, from experience with it i can safely say that tractor beams would be impossible and redstone itself is finnicky
