### ISSUE TITLE
[Bug] Tentacles picked up by Heads

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#198]
1.18.2 

2.0.1.1

Wither Storm Heads are able to pick up Tentacles because of the entity being mounted

1. Get a entity in the tentacles grip
2. Get a head to focus that entity
3. The head will grab the tentacle with the entity

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update.
