### ISSUE TITLE
[Suggestion]: Wither storm stealth mode

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1980]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A preset for the client options that removes the wither storm's ambient noises (unless it's within the render distance of the player), removes the glow, removes the emissive textures, and makes roars quiet. It also removes the debris cloud and rings.

  Also found inside of the world options, the wither storm always stays low, has mass destruction settings, and has a long roaring interval. Block clusters that are grabbed will move at 0.4 speed, and tractor grabbed clusters will move at 0.3 speed.

**Comment by TaintedBlock** [comment]
Resource packs can easily do this

**Comment by Luke7381** [comment]
> Resource packs can easily do this

I know they can but i think he wants to be a actual "mode" the wither storm can switch to.

**Comment by watersofnazareth** [comment]
Going back to this, this isn't worth our time of looking into and as Tainted said you can do this yourself with a resourcepack
