### ISSUE TITLE
[Suggestion]: Blueprints for "distraction structures"

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1981]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A blueprint item that allows the player to quickly build structures that peak the wither storm's interest, keeping it distracted until the structure is destroyed. Can be used 3 times, and builds the structures for free. Upgrading it can allow for bigger structures, distracting the wither storm for longer. However, the structures are made almost entirely out of tractorable blocks, meaning they will be destroyed pretty quickly.

**Comment by watersofnazareth** [comment]
We're not going to be adding items like this, you're always welcome to make addons but this is out of the scope of the mod

**Comment by BluePineappleGuy** [comment]
sick mod idea though, imagine a blueprint that functions as a survival mode structure block
