### ISSUE TITLE
[Suggestion]: Containers that have the formidibomb should drop it before being absorbed

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1983]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

If a container that has the formidibomb inside of it is grabbed by the wither storm, it should immediately drop the formidibomb when it gets within 20 blocks of the wither storm's body

**Comment by nonamecrackers2** [comment]
This was an existing feature in early 1.16.5 version but was removed due to compatibility issues and code changes in the game that prevented it from being feasible. I doubt we will reintroduce this, but thanks for your suggestion anyways.
