### ISSUE TITLE
[Suggestion]: New wither storm decal

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1984]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the wither storm dies, it should drop a head and a few tentacles in it's death animation and those should become entity decals inside of the storm's remains.

**Comment by nonamecrackers2** [comment]
The Wither Storm is supposed to be dead, I doubt feel remnants should remain considering the command block that powered it got destroyed. Thanks for your suggestion however.
