### ISSUE TITLE
[Suggestion]: Wither Storm Death Revamp

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1985]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Instead of the wither storm fading away and dying, the storm should explode, leaving a hole the size of the hole made by the formidibomb. There should still be debris from it, such as tentacles and a head or two, as well as chunks of it scattered around, just more spread out.

**Comment by Herobrine982950291** [comment]
NNC2 may not change the death sequence anytime soon.

**Comment by SSgamingYT** [comment]
> NNC2 may not change the death sequence anytime soon.

That's fair, but I'm hoping he at least makes the wither storm's clusters and chunks of flesh from the death more spread out

**Comment by Cod1ngGamer** [comment]
I think the current death animation works well, it's like the power of the command block was holding the wither storm together, and without that it just falls apart.

Also yes, the debris should be more spread out, that way we don't just get a tower of tainted blocks.

**Comment by SSgamingYT** [comment]
> I think the current death animation works well, it's like the power of the command block was holding the wither storm together, and without that it just falls apart.
> 
> Also yes, the debris should be more spread out, that way we don't just get a tower of tainted blocks.

It's death is so anticlimactic tho, it would look better if it faded white and exploded

**Comment by nonamecrackers2** [comment]
I think the death animation is currently fine as is
