### ISSUE TITLE
[Bug]: Game crashes when curing sickened mobs with no wither storm

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1986]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

Latest 1.20.1 forge version

### Describe the bug

When giving a sickened mob (a mob that's already turned) golden apple stew when there is no wither storm, the game immediately crashes.

### Steps to Reproduce

1. Spawn a Sickened mob
2. Try to give it golden apple stew
3. Despair at the crash screen

### Crash Reports/Logs

Unavailable 

### Is OptiFine installed?

- [X] OptiFine is installed

### Mod List

Cracker's wither storm mod

**Comment by watersofnazareth** [comment]
Please provide a crash log

**Comment by watersofnazareth** [comment]
Until a crash log is provided this will be closed
