### ISSUE TITLE
[Suggestion]: Eye of the storm(Drop)

### ISSUE THREAD

**Issue by MinecraftModderDailyDoseOfMods** [nonamecrackers2/crackers-wither-storm-mod#1987]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Creates a tractor beam like the storm. A dispenser when dispenses the eye becoms a heart of the storm, the block varient of the eye of the storm. The beam is weakend a bit so it cannot attract blocks

**Comment by Cod1ngGamer** [comment]
Good idea, but the Eye of the Storm is already a sword, so a name chance might be necessary.

**Comment by nonamecrackers2** [comment]
Interesting idea but this would be out of scope for the mod
