### ISSUE TITLE
[Bug]: Wither Storm disappeared

### ISSUE THREAD

**Issue by ItsTheAltron** [nonamecrackers2/crackers-wither-storm-mod#1988]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.20

### Describe the bug

Basically, im playing on a custom modpack with crackers wither storm mod.
I prepared a long time for this fight and was willing to take it on. I placed the skull and it summoned.
Everything went great so far... until the game crashed fatal.
I was like: "now thats odd, it never crashes."
I relog and I see myself on the podium with the skull... thats not there anymore, with the Wither Storm nowhere to be found.
Turns out the Wither storm despawned and i was teleported back to right before the Wither Storm was summoned and the wither storm ritual was just gone so i couldnt resummon it.
this time it was a hs_err_pid file and since im not sure if its safe to share im not doing it for now (just going safe)
Now you could say "Oooouuuh.. thats your fault because you play on a modpack. if you would just play it like this it would have been alright. nerd:emoji " But like how am i supposed to know

### Steps to Reproduce

One time crash so not reproduceable.

### Crash Reports/Logs

not sharing for now

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

[modcraft EX modlist.txt](https://github.com/user-attachments/files/15515061/modcraft.EX.modlist.txt)

**Comment by nonamecrackers2** [comment]
We'll need the crash report in order to see what's going on

**Comment by GearsawStudios** [comment]
https://github.com/embeddedt/ModernFix/issues/405 Reconfigure Modern Fix, then try again.

**Comment by watersofnazareth** [comment]
Until a crash log is provided this will be closed

**Comment by ItsTheAltron** [comment]
[hs_err_pid6364.log](https://github.com/user-attachments/files/15532933/hs_err_pid6364.log)
Imma trust you with this one.

**Comment by nonamecrackers2** [comment]
Looking at the crash log, it appears to be an issue with Journey Map. Try removing that mod. If the issue persists, notify me here
