### ISSUE TITLE
Craftable Amulet 

### ISSUE THREAD

**Issue by Faknocker** [nonamecrackers2/crackers-wither-storm-mod#199]
i have a idea you can make the Amulet craftable for Role Players

**Comment by watersofnazareth** [comment]
The amulet is a thing added for creative/server owners, you can make a datapack for the amulet if you wanted to but having multiple doesn't really do anything that the mod wouldn't do normally

**Comment by nonamecrackers2** [comment]
> The amulet is a thing added for creative/server owners, you can make a datapack for the amulet if you wanted to but having multiple doesn't really do anything that the mod wouldn't do normally

^
