### ISSUE TITLE
[Suggestion]: Tentacles displace/destroy blocks they touch

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1990]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Since not much else is going to be done with them, maybe tentacles could destroy or displace blocks when they touch them (like tentacles slamming into blocks and flinging a few and destroying the rest when it's close to the ground)

**Comment by GearsawStudios** [comment]
Tentacles are not going to do anything.

**Comment by SSgamingYT** [comment]
> Tentacles are not going to do anything.

Oh well. Maybe someone could make a data pack for it instead

**Comment by SSgamingYT** [comment]
> Tentacles are not going to do anything.

Oh well. Maybe someone could make a data pack for it instead

**Comment by Luke7381** [comment]
According to crackers, adding functionality to the tentacles would be a extremely hard thing to do due to client and server shenanigans and minecraft's hitboxes not being able to rotate.

**Comment by Cod1ngGamer** [comment]
I would say maybe you could kill the entity and spawn another with rotated hitboxes, but that is probably impractical and might have quite a few limitations.

**Comment by watersofnazareth** [comment]
Please read the guidelines when making a issue
