### ISSUE TITLE
[Suggestion]: A charge attack for the hunchback phases

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1991]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

To pair up with my other suggestion, (the one about early stages only shooting flaming skulls), there could be a charge attack where the storm tries to ram into the player (similar to the normal wither)

**Comment by TaintedBlock** [comment]
You're thinking of bedrock lol. Java wither doesn't do that

**Comment by SSgamingYT** [comment]
> You're thinking of bedrock lol. Java wither doesn't do that

Oh I didn't know that

**Comment by BluePineappleGuy** [comment]
> You're thinking of bedrock lol. Java wither doesn't do that

well who cares lets add it anyway

**Comment by Cod1ngGamer** [comment]
Let's just give it all the abilities of the bedrock wither, after all, it's supposed to be monstrous and deadly.
And while we're at it, what if it could use symbiont spells?

**Comment by SSgamingYT** [comment]
> Let's just give it all the abilities of the bedrock wither, after all, it's supposed to be monstrous and deadly. And while we're at it, what if it could use symbiont spells?

Hey now, bedrock wither is enough but symbiont spells are too much

**Comment by watersofnazareth** [comment]
We don't want to copy Bedrock's Wither, however it is possible the Wither Storm will receive upgrades with it's Hunchback AI, However I don't think having a charge is a very good idea (Plus I'm pretty sure this was recommended before)
