### ISSUE TITLE
[Suggestion]: Small details with banners

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1992]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When a tractor beam hovers over a banner, it would be cool if they started to flap like crazy

**Comment by watersofnazareth** [comment]
This probably isn't possible without overwriting the Banner Renderer which may cause issues

**Comment by watersofnazareth** [comment]
Yeah no this seems too minor to include
