### ISSUE TITLE
[Suggestion]: Items spiral into the wither storm

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#1999]
Items should spiral into the wither storm like block clusters

**Comment by Luke7381** [comment]
Items being attracted, i think had been suggested before.

**Comment by SSgamingYT** [comment]
> I suggested this before

You have? I've never seen it before, and I searched this before I suggested it

**Comment by Luke7381** [comment]
> > I suggested this before
> 
> You have? I've never seen it before, and I searched this before I suggested it


i apologize, i typed the wrong thing. But yeah iirc items being sucked up was suggested before at some point. However i don't think spiraling around the WS was.
