### ISSUE TITLE
Procedure to spawn the Wither Storm

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#200]
I think that just walking to certain coordinates, where you can find the blocks already placed down just waiting to be combined is a bit of a let down. To get to the Ender Dragon you must work hard for it, same goes for spawning a normal Wither, so to give a better challenge to players, it could be wise to have the command block as a craftable item (combining certain rare items for example, could be a way) and/or have the current structure present at 0, 0 give out the crafting receipt for it, as well as be the location where you can obtain an unique item necessary to craft the command block (i.e. could be the white square part of a command block), or it could even have an underground lab similar to the one in STORY MODE with a redstone engine that gives access to the altar of the Wither Storm, maybe just missing a skull or the command block itself. Obviously, there could be a settings that allow the spawning of the og structure with the current settings. A reason for this to be a thing is to enhance multiplayer gameplay, as a random could just walk to the structure and build the WS without the knowledge and permission of other players, etc.

**Comment by nonamecrackers2** [comment]
While this seems like an awesome idea, players are meant to summon the ws early as they're meant to progress as it evolves. This idea could totally be a cool custom modpack/server idea, and you can always disable the structure from spawning by going into the common config (1.16.5) or using a datapack to disable it's generation (1.18.2)
