### ISSUE TITLE
[Suggestion]: Tractor beams should grab items

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2000]
The tractor beams should be able to grab items, and they should move at the same speed as entities (once they are in range of the wither storm they move towards it)

**Comment by GearsawStudios** [comment]
This already exists.

**Comment by Pandaboi25x** [comment]
dont really see a point in adding this in since the ws just sucks the items in without using its tractor beams

**Comment by SSgamingYT** [comment]
> dont really see a point in adding this in since the ws just sucks the items in without using its tractor beams

Usually the storm is too high to pull in most items, so the tractor beams could bring those items into pulling range

**Comment by Pandaboi25x** [comment]
> > dont really see a point in adding this in since the ws just sucks the items in without using its tractor beams
> 
> Usually the storm is too high to pull in most items, so the tractor beams could bring those items into pulling range

i guess

**Comment by SSgamingYT** [comment]
> This already exists.

No it doesn't. I just tested it on the latest version

**Comment by BluePineappleGuy** [comment]
bro is speedrunning these suggestions

**Comment by watersofnazareth** [comment]
I'm going to close issues that have been opened that are already planned in the dev environment
