### ISSUE TITLE
Distant Renderer not working

### ISSUE THREAD

**Issue by Cod1ngGamer** [nonamecrackers2/crackers-wither-storm-mod#2002]
**Minecraft version**
1.20.1

**Mod version**
"Mini" Update

**Describe the bug**
The Distant Renderer for the wither storm doesn't work.

**Crash Reports / Logs**
Not necessary, probably

**Screenshots**
![2024-05-31_18 02 54](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/137913869/26077393-e3e4-4486-b183-4c206c6b99d2)
![2024-05-31_18 02 56](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/137913869/5e641d46-6515-4bef-946d-f06455f50ac0)

**Comment by watersofnazareth** [comment]
Are you using Embeddium Extra or Entity Culling

**Comment by Cod1ngGamer** [comment]
I am using Entity Culling.

**Comment by Cod1ngGamer** [comment]
I am using both.

**Comment by BluePineappleGuy** [comment]
> I am using both.

try removing them

**Comment by watersofnazareth** [comment]
The issue is the Max Entity Distance, this isn't a bug or issue with CWSM

**Comment by nonamecrackers2** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Known-Compatibility-Issues#magnesiumrubidium-extras
