### ISSUE TITLE
Ghast should fight back with the Wither storm

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2003]
The feature request is in the title already but ill explain it anyway, Ghast should start fighting back with the wither storm after the ghast either.
1. Notices the wither storm and notices the mobs running away
or
2. Ghast gets stuck in the tractor beam and fights back to escape.
I Tested it out before I made this feature request to see if they do fight back on the latest update and no they didn't fight back.
And if you think " But Ghast don't spawn in the overworld, and the wither storm cant go in the nether!!! " Spawning ghast in the overworld is a option to.

**Comment by watersofnazareth** [comment]
The Wither Storm doesn't target ghast

**Comment by nonamecrackers2** [comment]
The Wither Storm doesn't target ghasts and there wouldn't be really any scenarios where ghasts would encounter the Wither Storm to attack. Yes you could spawn them but I don't think this feature is entirely necessary, sorry.
