### ISSUE TITLE
Tenticals

### ISSUE THREAD

**Issue by maxepetermen9575** [nonamecrackers2/crackers-wither-storm-mod#2004]
Idk If this has already been suggested but can you make the tentacles actually do something? Like they just kinda sit there I wish they would at least move more. Maybe they can like destroy things or something, but i would like them to like move around. In Minecraft story mode they tenacles move around Here is a video with some things. https://www.youtube.com/watch?v=PMD9DMB8s0U
Note that you may have to skip ahead. So can you please make them move around?

**Comment by watersofnazareth** [comment]
Read the guidelines

**Comment by maxepetermen9575** [comment]
Oh i just realized that is already a thing nvm

**Comment by TaintedBlock** [comment]
You made this suggestion and didn't even spell tentacles right

**Comment by Infinitekaosv3** [comment]
Can i respectfully bash your head into bricks?
