### ISSUE TITLE
please make it compatible with AdyTech99's Farlands Reborn

### ISSUE THREAD

**Issue by BusinessBear99** [nonamecrackers2/crackers-wither-storm-mod#2005]
I think it would be really cool if the mod was compatible with the farlands mod and I know at least one more person wants that to by the name of DarknessMaked. Ill link the page of the mod here: https://www.curseforge.com/minecraft/mc-mods/farlands-reborn/comments

**Comment by FrozenDragon0** [comment]
How is it incompatible? I don't see how this mod would be incompatible with a mod that brings the Farlands back.

**Comment by Cod1ngGamer** [comment]
It could be that the farlands are trying to generate in the bowels, and it's messing up somehow.

**Comment by BusinessBear99** [comment]
Idk, I tried with just the two mods and the farmlands don’t generate and when I disable CWSM they generate. I have only tried it in the over world

**Comment by BluePineappleGuy** [comment]
> if the mod was compatible with the farlands mod and I know at least one more person wants that to by the name of DarknessMaked. Ill link the page

that would be a compat bug then, i'd make a bug report for it

**Comment by nonamecrackers2** [comment]
Yeah please make a bug report for this instead

**Comment by Gubberball** [comment]
I found a farlands mod that works with CWSM and 1.20.1: https://github.com/ThisTestUser/FarLandsModV2
