### ISSUE TITLE
Reuben no longer spawns when using withered beacon

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2008]
**Minecraft version**
1.20.1

**Mod version**
4.1

**Describe the bug**
When trying to spawn Reuben, the withered beacon only spawns a normal baby pig.

**To Reproduce**
1. Make a withered beacon
2. Input the porkchops
3. See error

**Crash Reports / Logs**
None

**Screenshots**
None

**Comment by Pandaboi25x** [comment]
This was already reported

**Comment by Pandaboi25x** [comment]
#1906

**Comment by watersofnazareth** [comment]
Duplicate issue please check before reporting
