### ISSUE TITLE
Suggestion: When a wither is near a command block, said command block should travel to the wither to make a wither storm stage 1

### ISSUE THREAD

**Issue by MFNmodding** [nonamecrackers2/crackers-wither-storm-mod#2009]
An idea that I had to change up the start of the mod for those who like to do things differently is that when a wither is near a block tagged with "witherstormmod:wither_storm_summon_command_blocks" tag, it will become a block cluster and attempt to go towards the wither, which upon contact it shall become a wither storm.
This would be of benefit to those who remove either the command block in the rundown house, or the rundown house itself, in favor of using other means to start the apocalypse by means of mods that allow you to create command blocks through various means.
This has been my suggestion. Thank you for listening.

**Comment by TaintedBlock** [comment]
Imo, this can't really happen logically and doesn't really make sense. The command block only is a part of the Wither due to it being built into it. It doesn't make sense to absorb a command block

**Comment by LegendaryGodzilla** [comment]
I agree with Tainted. the Command Block is built into the Wither.

**Comment by watersofnazareth** [comment]
This could cause pretty big issues on say a server

**Comment by nonamecrackers2** [comment]
Biggest issue is worlds with command blocks which are in use. This feature could destroy those command blocks which may be serving important purposes. While we could check to see if the command block has no commands in side of it, this isn't exactly how the Wither Storm is meant to be formed or created. It's kind of "infused" with the rest of the wither structure upon spawn.
