### ISSUE TITLE
if the right conditions are met, the wither storm can die after Formidibomb

### ISSUE THREAD

**Issue by Fingernailsss** [nonamecrackers2/crackers-wither-storm-mod#201]
**Minecraft version**
1.18.2

**Mod version**
2.0.1.1

**Describe the bug**
the wither storm will die after Formidibomb

**To Reproduce**
1. get to stage 5
2. use Formidibomb
3. once "dead" place another Formidibomb next to the command block
4. the wither storm will now have a permanent corpse that cannot be removed. (yay?)

**Crash Reports / Logs**
none

**Screenshots**
none

**Comment by nonamecrackers2** [comment]
Already reported: #162

**Comment by Fingernailsss** [comment]
oops,

> Already reported: #162

oops, sorry

**Comment by nonamecrackers2** [comment]
All good
