### ISSUE TITLE
Import Settings 

### ISSUE THREAD

**Issue by CosmicOpswastaken** [nonamecrackers2/crackers-wither-storm-mod#2010]
I love the config settings. But I think it would be amazing if we can import our settings so we don't have to scroll through everything

**Comment by TaintedBlock** [comment]
You can already.

**Comment by Composer-Hu** [comment]
It's in the saves folder, "witherstormmod-server.toml" in the serverconfig folder.

**Comment by BluePineappleGuy** [comment]
Suggested at #1621

**Comment by nonamecrackers2** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1621#issuecomment-1806870752
