### ISSUE TITLE
Evolution Modifier config not working as it should

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#2011]
**Minecraft version**
1.20.1

**Mod version**
4.1

**Describe the bug**
The Evolution Modifier seems to reset itself back to its default number, causing it to bug out the Wither Storm's evolution (It was in phase 5), and making it jump phases when it shouldn't. For example, I could set the Storm to phase 5 and all of a sudden it would jump back to 5.5. 

Secondly, I was playing with my datapack, and a part of the Wither Storm's ability is its ability to grow faster than in vanilla CWSM. Although, this is through the use of summoning clusters. Not altering the config in any way. I'm not sure if summoned clusters change how the Storm evolves (which I don't think they are intended to).

**To Reproduce**
1. Change Evolution Attributes to be higher so the Storm evolves slower
2. Save config
3. Check to see if the value resets (may have to do it more than once, it was inconsistent, but consistent enough to be an issue and eventually crashed. I had to lock consumed entities once joining back)

**Crash Reports / Logs**
[crash-2024-06-06_15.01.43-client.txt](https://github.com/user-attachments/files/15710579/crash-2024-06-06_15.01.43-client.txt)

Mod list:
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114537009/4241e3f1-188e-48d7-bcf6-31279e7cedf2)

**Comment by nonamecrackers2** [comment]
Have you tested this without using your data pack?

**Comment by TaintedBlock** [comment]
Tested without datapack, cannot reproduce. Although I cannot identify what actually caused it earlier. Nothing in my datapack alters the evolution modifier. As a sidenote: When resummoning the Wither Storm with a 10.0 Evolution Modifier, the Storm immediately skipped into phase 4.5 and then phase 5.

**Comment by BluePineappleGuy** [comment]
> Tested without datapack, cannot reproduce. Although I cannot identify what actually caused it earlier. Nothing in my datapack alters the evolution modifier. 

that would mean there is a bug with summoning clusters. maybe use the `/witherstormmod consumedEntities add` command for your datapack instead?

**Comment by TaintedBlock** [comment]
I'd prefer not to since the clusters are for the visual effect. I tested this with my datapack again and there was no issue. Unless summoned clusters have their own issues, this would be something that Crackers or Nazaru would have to fix.

**Comment by TaintedBlock** [comment]
Update: Same modlist btw. But I have a crash. I do not know how to reproduce this, but I did happen to be using my datapack at the time.
[message.txt](https://github.com/user-attachments/files/15872832/message.txt)

**Comment by TaintedBlock** [comment]
Once again, I will repeat that nothing touches the evolution modifier. The issue could be custom clusters, but i'm not sure. I've never had this problem before the full release of evo 1.5

**Comment by nonamecrackers2** [comment]
Yeah and I'm not sure why custom clusters would affect the evolution modifier

**Comment by nonamecrackers2** [comment]
For some reason the config isn't properly being loaded. Can you send a latest.log file from when this crash occured?

**Comment by TaintedBlock** [comment]
I don't think I have the instance anymore. But I did mention a while back in discord that it didn't happen again after trying to reproduce it

**Comment by nonamecrackers2** [comment]
I'll mark this as closed then. If you even encounter it again feel free to make a new issue
