### ISSUE TITLE
bowels lagging when i hit the command block

### ISSUE THREAD

**Issue by jamil702** [nonamecrackers2/crackers-wither-storm-mod#2013]
when i hit the command block in the bowels, it just freezes for a few seconds
**To Reproduce**
1. Summon wither storm
2. Turn him into phase 7.5
3. Go to the bowels
4. Hit the command block

**Comment by jamil702** [comment]
I dont know how im lagging despite the fact that im literally getting 300 fps and the random freezes are crazy

**Comment by Herobrine982950291** [comment]
Mod List?

**Comment by jamil702** [comment]
Cracker's wither storm
Just enough items
Ferritecore
Embeddium
those are my mod list

**Comment by BluePineappleGuy** [comment]
IIRC there were some compat issues with embeddium. also use the bug report template

**Comment by nonamecrackers2** [comment]
Please reopen this issue with the required information
