### ISSUE TITLE
Achievement for being killed by sickened pet

### ISSUE THREAD

**Issue by Cod1ngGamer** [nonamecrackers2/crackers-wither-storm-mod#2014]
**Description of feature**
When a pet is wither sickened, it's still owned by the player that tamed it, and if it kills a monster, it's owner still gets credit. So, if a player is killed by a pet that was wither sickened, it should give a hidden achievement, something like "Betrayal: Get killed by your own pet"

**Comment by GrandmaPork** [comment]
this would be funny

**Comment by BluePineappleGuy** [comment]
"Et tu, brutus?" would be another name candidate

**Comment by watersofnazareth** [comment]
Only is issue is this goes against Hardcore

**Comment by Cod1ngGamer** [comment]
Could still work if the player was using a totem.

**Comment by nonamecrackers2** [comment]
Interesting idea but as already brought up this advancement would lock out hardcore players which I don't want to do. I really like the idea otherwise!

**Comment by GrandmaPork** [comment]
No way to check if you’ve been damaged by a sickened pet? Or check to see if a pet was changed into its sickened variant?

**Comment by Cod1ngGamer** [comment]
I meant the advancement would still be given if the player used a totem to revive themselves, so hardcore players would still be able to get it.
