### ISSUE TITLE
Symbionts can hurt eachother with their own attacks. But sickened mobs can't hurt eachother

### ISSUE THREAD

**Issue by TaintedBlock** [nonamecrackers2/crackers-wither-storm-mod#2015]
**Minecraft version**
1.20.1

**Mod version**
4.1

**Describe the bug**
Title is enough

**To Reproduce**
1. Spawn 2 symbionts
2. Let one power down or be vulnerable
3. Get the symbiont to aim an attack at the other symbiont's back, preferably the arrow attack
4. See inconsistency

**Comment by LegendaryGodzilla** [comment]
bros fighting to be the only symbiont

**Comment by BluePineappleGuy** [comment]
"This town ain't big enough for the both of us" ahh symbiont

**Comment by watersofnazareth** [comment]
Fixed
