### ISSUE TITLE
Entity's carrying the amulet should be chased by the Wither Storm

### ISSUE THREAD

**Issue by BladeLightsteel** [nonamecrackers2/crackers-wither-storm-mod#2017]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The title is somewhat self-explanatory. For instance, foxes can pick up the amulet and are not chased by the storm. It would be a good distraction if you manage to give the amulet to a fox or a zombie while running from the wither.

**Comment by CosmicOpswastaken** [comment]
Makes sense

**Comment by nonamecrackers2** [comment]
The only thing is that the mob could easily become unloaded, causing the Wither Storm to just swap back to the player. While I could just make it so mobs with amulets could chunk load, that would be unnecessarily complex and performance intensive.
