### ISSUE TITLE
[Bug]: Being near the Wither Storm when it automatically summoned causes the player to have Wither Sickness.

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#2019]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Describe the bug

When setting the WS to spawn automatically and the player is nearby the WS, it causes the player to have wither sickness. I am unsure why that is.

### Steps to Reproduce

1.Set the config to spawn the WS automatically
2. Be near the WS when it summons
3. Player should be inflicted with wither sickness

### Crash Reports/Logs

No crash log applicable for this bug.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/148708399/e2aa0264-3189-41cf-a157-2346a46d2ff3)

### Mod List

  [✔] BadOptimizations-2.1.3-1.20.1
  [✔] cloth-config-11.1.118-forge
  [✔] collective-1.20.1-7.61
  [✔] embeddium-0.3.20+mc1.20.1
  [✔] embeddiumplus-1.20.1-v1.2.12
  [✔] oculus-mc1.20.1-1.7.0
  [✔] Paxi-1.20-Forge-4.0
  [✔] setworldspawnpoint-1.20.1-3.3
  [✔] stepitup-2.0.1-1.20.1-forge
  [✔] VanillaTweaks-forge-1.20.1-1.5.71
  [✔] witherstormmod-1.20.1-4.1-all
  [✔] YungsApi-1.20-Forge-4.0.5

**Comment by watersofnazareth** [comment]
This is a known bug, we're planning on addressing it with the next update since it ruins the experience

**Comment by ghost** [comment]
> This is a known bug, we're planning on addressing it with the next update since it ruins the experience

Should I close this as a duplicate then?

**Comment by nonamecrackers2** [comment]
#1922
