### ISSUE TITLE
Changes to make it more accurate, no pressure.

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#202]
My request is that the events in the mod will have music that plays during that time in the MCSM game.
Like when the wither storm comes back from playing dead it will rise slower and play the music of that time.
also after the wither storm dies make it available so that the player can receive the blocks/items after death.
and more smoother animations, as well as more blocky arms. a function to the wither storm star.
thanks for reading this is ChaoticRobot from the discord server.

**Comment by nonamecrackers2** [comment]
Different boss themes has been suggested multiple times; #27

Blocks after death: #184 

Tentacles: #169 

Function for the star: #3 

For accuracy: My goal is not to make the mod 100% accurate to the game.

Smoother animations: What do you mean exactly?

**Comment by ghost** [comment]
more slower movement instead of the heads moving around too fast.

**Comment by Parakeetgod** [comment]
> more slower movement instead of the heads moving around too fast.

I agree with this, right now if the wither storm wants to use its tractor it will instantly lock onto whatever it wants, i think it would be a lot better if it moved its heads around slowly, like searching for players and mobs, allowing you to run from the beams
