### ISSUE TITLE
[Suggestion]: Formidibomb placement time

### ISSUE THREAD

**Issue by hpndd13** [nonamecrackers2/crackers-wither-storm-mod#2020]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I've been playing the cracker wither storm mod. When I place and burn the Fbomb, stages 5 to 5.5 wither storm absorb the Fbomb. I want stage 5.5 wither storm to absorb the Fbomb, not stages 5.3 and below.

**Comment by TaintedBlock** [comment]
There's a config in the MISC that can limit it to 5.5

**Comment by nonamecrackers2** [comment]
^ This

**Comment by hpndd13** [comment]
Which mod helps increase performance?
