### ISSUE TITLE
[Suggestion]: An option to decide what witherstorm should not target

### ISSUE THREAD

**Issue by NarckMax** [nonamecrackers2/crackers-wither-storm-mod#2022]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I noticed that the wither storm will lock on to the dragon bone corpses from fire and ice because it counts as a targetable entity. This entity does not take damage, and the witherstorm will continue to attack it continuously. I suggest an option that lets you filter out mobs from the witherstorm's target AI.

**Comment by Cod1ngGamer** [comment]
This is actually a really good idea, and I think it should be added.

**Comment by WitherBean** [comment]
You can, you just have to edit a wither_storm_target_blacklist.json file. And put that file in a datapack.

**Comment by nonamecrackers2** [comment]
As WitherBean has already mentioned this is already possible using datapacks and modifying the blacklist tag.
