### ISSUE TITLE
[Suggestion]: Items should be absorbed in a spiral way

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2025]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the storm sucks up an Item, it should be absorbed in a spiral shape (as in it twirls around the storm as it gets closer and closer before dying).

**Comment by watersofnazareth** [comment]
I've already actually implemented this in the dev builds lol

**Comment by Herobrine982950291** [comment]
Already confirmed! Wow!

**Comment by Herobrine982950291** [comment]
> I've already actually implemented this in the dev builds lol

btw how are you able to add labels/add issues to milestones? Did you get perms from NNC2?

**Comment by SSgamingYT** [comment]
> > I've already actually implemented this in the dev builds lol
> 
> btw how are you able to add labels/add issues to milestones? Did you get perms from NNC2?

That's nazaru

**Comment by nonamecrackers2** [comment]
> > I've already actually implemented this in the dev builds lol
> 
> btw how are you able to add labels/add issues to milestones? Did you get perms from NNC2?

They're a developer

**Comment by Herobrine982950291** [comment]
Oh. Nice!
