### ISSUE TITLE
[Bug]: the beam won’t pick me up and the skulls it shoots out don’t damage me

### ISSUE THREAD

**Issue by MrMemepuff** [nonamecrackers2/crackers-wither-storm-mod#2026]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

1.0.1

### Mod Loader

Forge

### Mod Loader Version

1.16.5

### Describe the bug

When the laser beam points at me it doesn’t pick me up and when they shoot the skulls they don’t damage me

### Crash Reports/Logs

Sat June 23 2024 1:22 am 

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![5C360F06-131A-40DC-A939-B801D807D679](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/173590733/65539da9-0362-4c0a-bda6-92c795295968)

### Mod List

No extra mods

**Comment by TaintedBlock** [comment]
Uhh.. is this bedrock edition??

**Comment by WitherBean** [comment]
Please only make bug reports for Cracker's Wither Storm Mod.

**Comment by nonamecrackers2** [comment]
Bedrock edition is not supported.

**Comment by Luke7381** [comment]
Your on bedrock and there are no official CWSM ports on bedrock.

**Comment by BluePineappleGuy** [comment]
nobody gonna talk about how he was playing minecraft at 1:30 AM

**Comment by juanelgamer456** [comment]
> nobody gonna talk about how he was playing minecraft at 1:30 AM

what is so weird about it really??

**Comment by Luke7381** [comment]
> nobody gonna talk about how he was playing minecraft at 1:30 AM

nothing is weird about playing late alright. Loads of people stay up at night either by not realizing, choosing to or addicted to games or something.

**Comment by BluePineappleGuy** [comment]
if it aint weird to you guys, you really gotta work on that sleep schedule

**Comment by CosmicOpswastaken** [comment]
> if it aint weird to you guys, you really gotta work on that sleep schedule

Yeah they do
