### ISSUE TITLE
[Suggestion] Random Screen Shake

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#203]
Whenever the Wither Storm sits over you for a extended amount of time a timer will start for a random time of 2.5-5 minutes to randomly shake the screen, very small request

**Comment by MatthewMegapixel** [comment]
I think it would be nice to add some screen shake when the Wither Storm's fire skull explodes near the player.

**Comment by BluePineappleGuy** [comment]
maybe a loud wither storm roar sound could be heard when it shakes

**Comment by MatthewMegapixel** [comment]
hey, this is a really cool idea. I hope Cracker will add this)
