### ISSUE TITLE
[Bug]: normal zombie spawning in bowels

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#2031]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Describe the bug

A bug happened! A regular vanilla zombie spawned inside the bowels

### Steps to Reproduce

1. go in the bowels
2. start command block fight
3. normal zombie spawned

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot (18)](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/108914903/7d43b662-610a-498b-8dca-c181c72a88b0)

### Mod List

Entity Model Features forge
Entity Texture Features forge
CWSM
JEI

**Comment by TaintedBlock** [comment]
Why did you close this as completed?

**Comment by BluePineappleGuy** [comment]
> Why did you close this as completed?

probably an accident
