### ISSUE TITLE
[Suggestion]: Shortening/changing the "tag" (idk what it's called)

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2034]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I think it would be much easier to replace "witherstormmod:"  with "CWSM:" (or something else).

**Comment by TaintedBlock** [comment]
I don't think it's possible anymore. There would be so much they would have to change it wouldn't even be worth it

**Comment by Herobrine982950291** [comment]
fine. I just suggested this because the Current "tag" takes too long to type out.

**Comment by TaintedBlock** [comment]
Nah I get it. Sadly might never be changed tho

**Comment by Pandaboi25x** [comment]
> fine. I just suggested this because the Current "tag" takes too long to type out.

not if you get used to it :trollface:

**Comment by watersofnazareth** [comment]
While this would be nice, it's honestly just not possible at this point in development, maybe when the mod was first being made but as of now this would be way too complicated

**Comment by nonamecrackers2** [comment]
Yeah and everything including save files, mod compatibility, resource packs, and more would not work with this change and would require a substantial amount of effort to update

**Comment by Herobrine982950291** [comment]
> While this would be nice, it's honestly just not possible at this point in development, maybe when the mod was first being made but as of now this would be way too complicated

Wow! **Never** thought of that! **Gonna** think of that now! **Give** me more! **You** are the best! **Up** the difficulty! (read the 1st word of each sentence)

**Comment by BluePineappleGuy** [comment]
> > While this would be nice, it's honestly just not possible at this point in development, maybe when the mod was first being made but as of now this would be way too complicated
> 
> Wow! **Never** thought of that! **Gonna** think of that now! **Give** me more! **You** are the best! **Up** the difficulty! (read the 1st word of each sentence)

you pulled that one already be more creative

**Comment by Herobrine982950291** [comment]
i know haha
