### ISSUE TITLE
[Bug]: Eyes & Teeth disappear...?

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2035]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Describe the bug

A bug happened! When deactivating tractor beams, then exploding it, then killing it, the teeth & eyes on those heads disappear!

### Steps to Reproduce

1. Deactivate Tractor beams (any amount)
2. Explode WS
3. Kill WS Whilst it's falling

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Minecraft Forge_ 1 20 1 - Singleplayer 29_06_2024 15_39_11](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/d704a1ee-4546-48ba-84ba-0dec732ad246)

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/48f68b20-1c32-432d-922a-9bd46813a2bd)

**Comment by TaintedBlock** [comment]
Do you have a resource pack installed?

**Comment by Herobrine982950291** [comment]
Not at this time, no.

**Comment by BluePineappleGuy** [comment]
i wonder if this still happens with "render emissive decal" off.

**Comment by nonamecrackers2** [comment]
This is technically intended. The exploding texture makes them disappear as the rest of the body dissolves. This doesn't apply to the emissive pieces which is why it's kind of weird. This isn't a big issue and would take some time to fix so I'll just close this as working as intended.
