### ISSUE TITLE
Wither Storm not spawning

### ISSUE THREAD

**Issue by Jaroszek1310** [nonamecrackers2/crackers-wither-storm-mod#204]
**Minecraft version**
1.16.5

**Mod version**
1.0.2.3

**Describe the bug**
When I place the wither skull, the Storm won't spawn, I tried it on multiple worlds.

**To Reproduce**
1. Place the last head
2. Wait
3. ...
4. Nothing

**Screenshots**
![2022-07-12_00 30 27](https://user-images.githubusercontent.com/109113516/178370023-e4fd6f8d-ba14-40d5-b0f0-71a44e35f140.png)
![2022-07-12_00 23 18](https://user-images.githubusercontent.com/109113516/178370047-7ac693fd-cdbf-49e8-b175-e488741ada75.png)

**Comment by nonamecrackers2** [comment]
What mods do you have installed?
