### ISSUE TITLE
An incorrect model of a Wither Storm

### ISSUE THREAD

**Issue by Saifin87** [nonamecrackers2/crackers-wither-storm-mod#2041]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Describe the bug

Instead of the usual cubic model of a WIther Storm, it has been replaced by a simpler shape for some reason unknown to me.

### Steps to Reproduce

1. The latest version of the mod for the corresponding version of Minecraft
2. turn on Minecraft with the mod installed
3. Launching the world with the mod installed
4. We summon the Wither Storm and wait for it to reach the 4 phase. A simplified model is visible instead of the usual cubic one.

### Crash Reports/Logs

No crash reports

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-07-03_21 12 23](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/174506289/31bdaa63-bc1b-4f19-bad4-0d5178cc14e2)

### Mod List

No

**Comment by watersofnazareth** [comment]
Check your client settings

**Comment by Saifin87** [comment]
> Проверьте настройки клиента

Thank you! The problem is solved.
