### ISSUE TITLE
[Bug]: ImmersiveMC compat

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2042]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

Latest 1.20.1 forge version

### Describe the bug

Formidibomb does not have craftFuseTicks when made using ImmersiveMC crafting tables

### Steps to Reproduce

1. Craft formidibomb 
2. View in inventory 
3. ### **_d e s p a i r  a t  t h e  r u i n e d  i m m e r s i o n_**

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

ImmersiveMC
CWSM
Embeddium
Architectury API

**Comment by GrandmaPork** [comment]
this might be something that should be reported to the immersive mc mod. it must be how they deliver the crafted item to the player

**Comment by Herobrine982950291** [comment]
#1898 duplicate

**Comment by SSgamingYT** [comment]
> #1898 duplicate

Oop
