### ISSUE TITLE
[Suggestion]: wither storm's mouth should close instead of always being open all the time

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#2043]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

the title pretty much says it, the wither storm's mouth should also just be closed instead of being open like all the time

**Comment by nonamecrackers2** [comment]
I think the animation is fine and I find it quite weird with it having its teeth closed all the time
