### ISSUE TITLE
[Suggestion]: random purple flashes at night

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#2044]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

at night the wither storm will produce random purple flashes at night i mean why not i saw it in MCSM ep 4 while watching technoblades stream of it, there also should be an option to turn this off

**Comment by nonamecrackers2** [comment]
#463
