### ISSUE TITLE
[Suggestion]: If there's no WS in the world, the phasometer shouldn't say "Searching..."

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2046]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

IDK what to say other than "TITLE".

**Comment by TaintedBlock** [comment]
I don't really understand this. Why would it not say searching when a Wither Storm isn't in the world when its purpose is to search for if a Wither Storm is in the world?

**Comment by Herobrine982950291** [comment]
If there arent any storms in the World, it shall not say searching... but if there is a Wither Storm, it should say searching...

**Comment by nonamecrackers2** [comment]
It's searching what you're current looking at for a wither storm. It'll continue to display that until it finds one.
