### ISSUE TITLE
[Suggestion]: command to bring tractor beams back

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#2047]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

basically when a head is damaged there should be a command to heal it again. idk if dis is actually necessary tho

**Comment by TSEG6** [comment]
It heals on it's own so this isn't needed

**Comment by witherstormfan87** [comment]
waiting

**Comment by witherstormfan87** [comment]
nevermind

**Comment by Aimyx** [comment]
this is probably for datapacks and/or scripted shenanigans people want to
play around with
