### ISSUE TITLE
[Bug]: Command Block Pedestal Offset

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#2049]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

Command Block Pedestal and Wither Heads are offset to the fighting chamber and spawned in a wall.

### Steps to Reproduce

1. Create the Bowels in version 4.1 and have a Mineshaft Fight Chamber
2. Go outside the Bowels
3. Switch to version 4.0.1.1
4. Enter the Bowels
5. See error

### Crash Reports/Logs

https://drive.google.com/file/d/13w9QeI9GBkpiqgj6Au9aIX6l0XiHjK5E/view?usp=sharing

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

-Oculus
-Rubidium
-Entity Model Features
-Entity Texture Features
-AmbientSounds 6
-AmplifiedNether
-Better Combat
-Blur
-Bobby Reforged
-Cloth Config API
-Collective
-CreativeCore
-Do a Barrel Roll
-EnhancedVisuals
-Essential Mod
-First-person Model
-Immersive Weathering
-Incendium
-JEI
-JER
-Load My Resources
-Model Gap Fix
-Moonlight Lib
-Naturally Charged Creepers
-Not Enough Animations
-Not Enough Recipe Book
-Nullscape
-Nyf's Spiders
-playerAnimator
-Presence Footsteps
-Simple Voice Chat
-Sound Physics Remastered
-Terralith
-You Die You Lose a Heart
-YUNG's API
-YUNG's Better...
 -... End Island
 -... Nether Fortresses
 -... Ocean Monuments
 -... Strongholds

**Comment by watersofnazareth** [comment]
We need more information on this, it's not clear what you mean, also again report issues for the latest version of the mod not old ones

**Comment by FalconinVoid** [comment]
I actually don't know exactly what happened there, that's the only thing that I know. The bowels looked different than usual. It may be a new stage that has not been finished and shouldn't be seen.

**Comment by FalconinVoid** [comment]
Okay found the Mineshaft Command Block Room again, the error probably occured because I switched the version. Those Mineshafts were not part of 4.0.1.1, but 4.1.
