### ISSUE TITLE
Two Suggestions 

### ISSUE THREAD

**Issue by xxdylan02xx** [nonamecrackers2/crackers-wither-storm-mod#205]
I noticed at we can make the wither storm completely stationary using the config settings and I think it would be nice to make it not able to damage the environment in case we want to build around it, like if for some reason someone wanted to build a giant containment facility around the wither storm. (This also includes the ability to stop the wither storm from shooting its skulls too since they can damage the environment.)

I also think we should have the option to disable its ability to pull entities with its tractor beam, (You don't have to implement this if you want to)

In summery: 

1. The ability to disable the damage to the environment and the wither skulls.
2.  (Optional) Disable the tractor beams pull effect on entities.

**Comment by nonamecrackers2** [comment]
You can disable mobGriefing to disable it destroying the surroundings, and the mob cluster pick up feature can be disabled (unless if you meant pick up from the ws targeting you)
