### ISSUE TITLE
[Suggestion]: Purple glowing for the amulet.

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2050]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I think it would make more sense if the Blue bit of the Amulet is purple, along with the Glowing. Can be set to a Config if need be.

**Comment by TaintedBlock** [comment]
But the middle of the amulet is blue though, its supposed to replicate story mode. You could make a resource pack changing the texture color and middle amulet color

**Comment by Herobrine982950291** [comment]
> But the middle of the amulet is blue though, its supposed to replicate story mode. You could make a resource pack changing the texture color and middle amulet color

TBH i really dont know how to make my own textures, let alone Datapacks/mods

**Comment by watersofnazareth** [comment]
This won't be changed, as Tainted said you can make a resource pack
