### ISSUE TITLE
[Bug]: World lag when the Storm Chases

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2051]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Describe the bug

A bug happened! When the Storm chases the player, the world lags. The Entities freeze for certain seconds. and Fireworks are delayed. Maybe make a config for the WS Speed when chasing.

### Steps to Reproduce

1. Make WS Chase you
2. Go far away
3. See error

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/152856226/2dc5d6cd-902c-43e8-b31c-8f6085188240)

**Comment by TaintedBlock** [comment]
A config for chase speed already exist.

**Comment by Herobrine982950291** [comment]
> A config for chase speed already exist.

well at least try to decrease the (default) speed a li'l bit or find a way to fix it.

**Comment by Cod1ngGamer** [comment]
If you're using a modloader, I would allocate more memory. Usually fixes any lag-related issues.

**Comment by nonamecrackers2** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Preferences-and-Performance#recommended-settingsperformance-settings

If nothing in that link works, try removing your extra mods. If the lag persists, it's probably your hardware and there isn't much we can do about it.
