### ISSUE TITLE
[Quality of Life]: No Creative Mode Wither Sickness

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#2055]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I thought of the wither sickness counter being reset or paused while creative mode is active.

**Comment by TaintedBlock** [comment]
You don't get the effect in creative anymore. Unless you mean it should stop affecting you if you already have it while in creative

**Comment by FalconinVoid** [comment]
> You don't get the effect in creative anymore. Unless you mean it should stop affecting you if you already have it while in creative

Oh I'm sorry then, I am playing on 4.0.1.1, cuz the music is not working in 4.1 o.o

**Comment by TaintedBlock** [comment]
Ah, ok.
