### ISSUE TITLE
[Bug]: Broken Wither Sickness Layer

### ISSUE THREAD

**Issue by FalconinVoid** [nonamecrackers2/crackers-wither-storm-mod#2056]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

Skeletons have a UV error in their Wither Sickness Layer (No other mob has this error)

### Steps to Reproduce

1. Wait for the Wither Storm to inflict the Wither Sickness
2. Summon a Skeleton and wait for it getting the Layer
3. See error

### Crash Reports/Logs

No Crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/141413671/3e0e61ce-14e2-408f-a569-7d2d6db30ffb)

### Mod List

![2024-07-10 21_35_57-mods](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/141413671/7f001b41-d843-42af-b109-a12f6b8be583)
-YungsBetterEndIsland-1.20-Forge-2.0.6
-YungsBetterNetherFortresses-1.20-Forge-2.0.6
-YungsBetterOceanMonuments-1.20-Forge-3.0.4
-YungsBetterStrongholds-1.20-Forge-4.0.3

**Comment by FalconinVoid** [comment]
Note: Problem persists with Entity Texture Features disabled

**Comment by TaintedBlock** [comment]
This probably wont be fixed due to it being on an older version. It is fixed in the newer version

**Comment by watersofnazareth** [comment]
Please use the modern versions of the mod as this has already been fixed

**Comment by nonamecrackers2** [comment]
Pretty sure it was in 4.0.1.1, but the fix gets disabled if Embeddium or Sodium is installed due to compatibility issues. I'll probably look into if the problem still exists with newer versions of Embeddium and Sodium

**Comment by nonamecrackers2** [comment]
The fix works fine with Embeddium. Better UV support will now be active when Embeddium is installed.
