### ISSUE TITLE
[Suggestion]: More Sickened Mobs

### ISSUE THREAD

**Issue by EndoPrime** [nonamecrackers2/crackers-wither-storm-mod#2058]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I've been thinking about this idea for weeks since the "Mini" update came out
This one might be complex but I thought the symbiont should have an animation of it holding and using the command block book to cast spells

**Comment by GearsawStudios** [comment]
You did not read the guidelines; suggesting sickened mobs isn't allowed.

Two separate suggestions in one post isn't allowed.

**Comment by TaintedBlock** [comment]
please close this as not planned
