### ISSUE TITLE
Ability to disable abandoned house structure generation

### ISSUE THREAD

**Issue by yeahpng** [nonamecrackers2/crackers-wither-storm-mod#206]
I'm going to gate the wither storm with kubejs and spawn it that way, so a config option to disable the abandoned house would be helpful.

**Comment by watersofnazareth** [comment]
#41
#170

**Comment by nonamecrackers2** [comment]
In 1.16.5 you could disable it with the config option in the common config, or in 1.18.2 you could make a data pack to override it's generation (probably could override it's has_structure biome tag to include no biomes?)
