### ISSUE TITLE
[Bug]: Game crashing trying to look at the Witherstorm

### ISSUE THREAD

**Issue by MissiNBetsi** [nonamecrackers2/crackers-wither-storm-mod#2063]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.1.106

### Describe the bug

I spawned the Witherstorm on our Server on accident. Whilst fighting it i just flat out crashed with no warning or error logs/crash log etc. Now every time i log onto the server and start looking towards the witherstorm my game instantly crashes with error code: 1.

### Steps to Reproduce

1. Load into World
2. Look at Wither
3. Crash
4. No Logs whatso ever

### Crash Reports/Logs

No logs were created. it just flatout crashes

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

[list.txt](https://github.com/user-attachments/files/16203112/list.txt)

**Comment by GearsawStudios** [comment]
Disable Modern Fix, known.

**Comment by MissiNBetsi** [comment]
Meaning uninstall modernfix?

**Comment by TaintedBlock** [comment]
> Meaning uninstall modernfix?

yes

**Comment by FrozenDragon0** [comment]
> Meaning uninstall modernfix?

The newer versions of ModernFix do fix the problem, haven't received a crash so far.
