### ISSUE TITLE
Wither Storm doesn't spawn

### ISSUE THREAD

**Issue by Omni-Man1** [nonamecrackers2/crackers-wither-storm-mod#2065]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.1.30 (Sinytra Connector)

### Describe the bug

After placing the last skull on top of the command block, the T-structure just broke down in particles (I will provide screenshots) and there is no Wither Storm to be seen. However, after testing some spawn eggs and commands, I came to the conclusion that I'm able to spawn all type of Sickened and Tainted mobs, plus the Symbiont and Wither Storm Head. 

[latest.log](https://github.com/user-attachments/files/16234400/latest.log)

### Steps to Reproduce

1. Go to structure
2. Skull on command block
3. T-structure breaks down
4. No Wither Storm

### Crash Reports/Logs

See description

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

 
![image](https://github.com/user-attachments/assets/18610fde-8804-43ff-a561-3b69f278d3a5)
![image](https://github.com/user-attachments/assets/843b4207-3598-4f19-bf00-5074a07cac7e)
![image](https://github.com/user-attachments/assets/5c140c5e-ed20-477f-94c8-4c33da85fb5e)

### Mod List

![image](https://github.com/user-attachments/assets/3f5770d2-491a-478d-87c0-a870a3e3521f)
![image](https://github.com/user-attachments/assets/34507072-dcf2-435a-9551-9d818737a6fc)
![image](https://github.com/user-attachments/assets/d8a28394-f519-419b-9cb3-cb4520fcb3f0)
![image](https://github.com/user-attachments/assets/7226d1da-a757-4e4c-be3a-a74b70ed5b75)

**Comment by Omni-Man1** [comment]
Mod version is 4.0 instead 4.1

**Comment by GearsawStudios** [comment]
> Mod version is 4.0 instead 4.1

Switch to 4.1 then.

**Comment by Omni-Man1** [comment]
> > Mod version is 4.0 instead 4.1
> 
> Switch to 4.1 then.

I meant as in I accidentally gave in 4.1 and it went unnoticed.

**Comment by watersofnazareth** [comment]
Does the issue persist in newer versions of the mod

**Comment by Omni-Man1** [comment]
> Does the issue persist in newer versions of the mod

Unfortunately I can’t tell since the versions above 4.0 won’t load with Forge version 47.1.30, 4.0 seems to be the only one that works with 47.1.30 (which I rely on for the Sinytra Connector)

**Comment by nonamecrackers2** [comment]
The mod prevents you from using 47.1.30 because that version causes this bug (more specifically, any Forge version between 47.1.5 and 47.1.40). You'll have to use 47.1.40 or higher, if you can't then there is unfortunately not much we can do.
