### ISSUE TITLE
[Suggestion]: Add an option to make the wither storm act like the one from the engender mod.

### ISSUE THREAD

**Issue by Totallysurfaceman1** [nonamecrackers2/crackers-wither-storm-mod#2068]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

In the engender mod, the wither storm could be a pet. The thing is, the model's are ass. It would be cool If it there was an option for this.

**Comment by TaintedBlock** [comment]
There's a trick to get the Wither Storm to not attack you.





_creative mode_

**Comment by Totallysurfaceman1** [comment]
> There's a trick to get the Wither Storm to not attack you.
> 
> _creative mode_

Yes but It's not what I'm talking about.

**Comment by watersofnazareth** [comment]
That's not the point of the mod and changing everything just for something so minor would be pointless

**Comment by juanelgamer456** [comment]
guys please chill, at least he just suggested the pet thing, and not tentacles
