### ISSUE TITLE
[Suggestion]: New Wither Storm Theme

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2069]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Can you please replace the current WS theme (phase 1-5.3, phase6-7) to the soundtrack heard here (I think it sounds better than the current one)

https://antimo.bandcamp.com/track/wither-storm-theme-101

**Comment by TaintedBlock** [comment]
Resource pack

**Comment by Herobrine982950291** [comment]
> Resource pack

dont know how to make





L

**Comment by BluePineappleGuy** [comment]
#789 crackers has already rejected using that theme bro

**Comment by Herobrine982950291** [comment]
آپ کو کبھی نہیں چھوڑیں گے

**Comment by BluePineappleGuy** [comment]
> مجھے اس سے نفرت ہے ...

?

**Comment by Herobrine982950291** [comment]
uhh nevermind

**Comment by Herobrine982950291** [comment]
just dont translate it
