### ISSUE TITLE
[Question/Suggestion?] Is it possible to get the Wither Storm to stay still in singleplayer?

### ISSUE THREAD

**Issue by TheD0ct0r101** [nonamecrackers2/crackers-wither-storm-mod#207]
As far as I can tell, the slowest I can set the Wither Storm's speed to in the single player configs is '0.01', but there is no '0' speed. Just wondering if the 'NONE' targeting mode is doable in singleplayer, or if not, possible to implement.

**Comment by nonamecrackers2** [comment]
Yeah if you set the ultimate targeting type to "NONE," it'll stay still.

**Comment by TheD0ct0r101** [comment]
I should have clarified, I was not able to find this 'ultimate targeting type' in any of the configs.

**Comment by TheD0ct0r101** [comment]
Ok, nevermind. When I used 'ctrl+F' in the server config I didnt get anything for results the first time and assumed I was in the wrong place. Sorry for my ignorance lol

**Comment by nonamecrackers2** [comment]
All good!
