### ISSUE TITLE
[Bug]: Phlegm block in "bowels_cave_portal_end" template is missing its loot table

### ISSUE THREAD

**Issue by sm644me** [nonamecrackers2/crackers-wither-storm-mod#2071]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

This is self-explanatory, no? This one template is just missing a loot table. It affects both versions of the "Mini" Update.

### Steps to Reproduce

1. Run the following command: `/place template witherstormmod:bowels/bowels_cave_portal_end`
2. Check the Phlegm block and notice that it's empty.

### Crash Reports/Logs

...It's an empty loot table. It's not that complicated.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

NONE

**Comment by watersofnazareth** [comment]
Oh shoot, I'll fix this one rq
