### ISSUE TITLE
[Suggestion]: Upgraded itmes in the creative menu

### ISSUE THREAD

**Issue by FuryJack07** [nonamecrackers2/crackers-wither-storm-mod#2074]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I want to be able to grab already upgraded items (amulet and stormphaser) directly from the creative menu

**Comment by CubeGamer647** [comment]
I second this. It's annoying to have to grab all the materials from the menu and manually craft the second phasometer.

**Comment by Composer-Hu** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1939
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1862

**Comment by FuryJack07** [comment]
> https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1939
> https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1862

Ops.

**Comment by watersofnazareth** [comment]
Already been added and will be available in the next update
