### ISSUE TITLE
cant upgrade to commandblock tools

### ISSUE THREAD

**Issue by ihateexperimentalfeaturesbug** [nonamecrackers2/crackers-wither-storm-mod#2075]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.19.4

### Mod Version

3.4

### Mod Loader

Forge

### Mod Loader Version

45.3.3

### Describe the bug

i cant upgrade my tools to commandblock tools because of the experimental features

### Steps to Reproduce

1. create new world
2. turn on experimental features
3. try upgrade diamond tools to commandblock tools using anvil or smithing table

### Crash Reports/Logs

none

### Is OptiFine installed?

- [X] OptiFine is installed

### Screenhots

![2024-07-26_01 23 06](https://github.com/user-attachments/assets/351454b1-0d26-4b6b-94bc-e3f4116397f7)
![2024-07-26_01 23 21](https://github.com/user-attachments/assets/38a9cd1e-c8c8-4b85-a5ad-aeaa40e0c760)

### Mod List

mr crayfish gun mod

**Comment by GearsawStudios** [comment]
Wait, why are you using specifically 1.19.4 with experimental features instead of 1.20.1?

**Comment by TaintedBlock** [comment]
This issue was addressed in discord already. There is nothing you can do about this. 

Edit: I also don't think this should be fixed because 1.20 exist for a reason.

**Comment by ihateexperimentalfeaturesbug** [comment]
> Wait, why are you using specifically 1.19.4 with experimental features instead of 1.20.1?

well i was using mr crayfish's gun mod, but its only for 1.19.4

**Comment by watersofnazareth** [comment]
You can make a datapack, but this is a non issue, since you're not intended to be playing on Experimental versions
