### ISSUE TITLE
formidiblade not compatible with Epic Fight 

### ISSUE THREAD

**Issue by X-Master112** [nonamecrackers2/crackers-wither-storm-mod#2076]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Describe the bug

So, while holding right click with formidiblade, it'll keep on charging forever. I do believe Epic fight is the only reason for that since I removed it and it charged after that. I do not know if I'm doing something wrong or not.

### Steps to Reproduce

Get a formidiblade, try to charge it, and wait forever I suppose.

### Crash Reports/Logs

file:///C:/Users/Mihai/AppData/Roaming/.minecraft/logs/latest.log 

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-07-25_22 23 14](https://github.com/user-attachments/assets/0207c15d-7565-4f51-8bd0-a77a0ccc0518)
![2024-07-25_22 23 10](https://github.com/user-attachments/assets/23924751-1f31-4d0f-bcdf-324fabe3a89b)
![2024-07-25_22 22 58](https://github.com/user-attachments/assets/f9815bef-24a1-4543-80a9-990673ffa532)

### Mod List

![image](https://github.com/user-attachments/assets/92984629-fde7-426c-87c7-cc77f51f1b54)
![image](https://github.com/user-attachments/assets/b7f18f90-9349-4787-b754-0beb02917d28)

**Comment by watersofnazareth** [comment]
You should open this issue up with Epic Fight, not here
