### ISSUE TITLE
[Bug]:  Lowering the "LI Required Proximity Seconds" custom option, along with setting the "Required contacts" to '1' sometimes makes the Wither storm not attack any mobs

### ISSUE THREAD

**Issue by bugsarerules** [nonamecrackers2/crackers-wither-storm-mod#2078]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

Changing the numbers for the custom option "LI Required Proximity Seconds" along with setting the "Required contacts" to 1  in world settings makes it so the wither storm does not attack anything at some points, nor pick anything up with its beams even though they are directly in it.  Sometimes one of the heads work, while the other two doesn't  target entities while one of the three works.

### Steps to Reproduce

1. Go to World settings
2. Set "Required Contacts" to 1
3. Set "LI Required Proximity Seconds" to as low as 12
4. Restart game
5. After a few minutes of dragging the witherstorm around in phase 4, bring it to a village or a structure similar
6. Bug should occur

### Crash Reports/Logs

none 

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot (351)](https://github.com/user-attachments/assets/afe65d93-e33a-45c9-940a-645a2567db06)
![Screenshot (349)](https://github.com/user-attachments/assets/8692917c-f0fd-4265-acc4-73c11d100d5e)
![Screenshot (353)](https://github.com/user-attachments/assets/82274681-51af-45eb-b265-8c5557b79e41)

### Mod List

![Screenshot (352)](https://github.com/user-attachments/assets/c480522b-84ff-4e4c-bd6b-c36220ae0549)

**Comment by nonamecrackers2** [comment]
It's currently targeting structures with its beams. In the first image, it may be targeting a mineshaft since you're in a badlands and they can spawn relatively high up. In the second image, it's probably targeting the sandstone walls. Same idea with the third image. When it's distracted by structures like this, it doesn't target mobs and they don't get sucked in by the beams.
