### ISSUE TITLE
Slower Head Rotation

### ISSUE THREAD

**Issue by Parakeetgod** [nonamecrackers2/crackers-wither-storm-mod#208]
At the moment if the wither storm wants to use its tractor beam on players or mobs the head snaps to the location of the mob/player and instantly uses its tractor beam, i think it would look better and play better if the heads looked around slowly scanning the area allowing you to dodge the beams, it would also work better if the scared mobs addition is inplemented

**Comment by nonamecrackers2** [comment]
This would require pretty much a complete revamp of the targeting system. While this idea is interesting it probably isn't worth my time as of now.

**Comment by nonamecrackers2** [comment]
Instead of scanning I will probably make the head rotations slower, I'll be using #285 to track this instead
