### ISSUE TITLE
[Suggestion]: Withered Pets

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2080]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Basically consumed pets (post f-bomb) spawn as their tainted/withered variants inside of the bowels (third hit on the command block) and attack the player, and they'd have to either 1. Kill them and lose them or 2. Spare them and try not to be killed by them 

Consumed pets that the player didn't kill in the bowels should respawn as normal when the storm is killed

**Comment by nonamecrackers2** [comment]
The only thing is that players could easily mistake them for just any other sickened mob and kill them without realizing. I feel like the current feature with them respawning after the wither storm dies would conflict with this feature, so I'll be closing this for these reasons.
