### ISSUE TITLE
[Suggestion]: Make the Starfish structure look slightly more like tentacles

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2081]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I think it would be nicer (and a lot more "realistic") if you make the ends of the starfish structure look more like tentacles so it makes more sense.

**Comment by Herobrine982950291** [comment]
Here's a concept of the WS having the structure:
![2024-07-28_13 53 38](https://github.com/user-attachments/assets/ed607afd-20bc-4dfb-a3c9-6f4bc9e783c5)
(I worked hard on this so please dont be rude)

**Comment by TaintedBlock** [comment]
This seems to be more like a story mode suggestion which is against guidelines

**Comment by Herobrine982950291** [comment]
Again that's just a concept. It doesnt have to look like THAT.

**Comment by Herobrine982950291** [comment]
Just make it look more like "tentacles" rather than "a starfish". But that's NNC2's decision.

**Comment by watersofnazareth** [comment]
The reason for the current design is because of the different orientations the Wither Storm can land in

**Comment by Herobrine982950291** [comment]
> The reason for the current design is because of the different orientations the Withered Symbiont can land in

Wut? "Withered Symbiont"? You mean Wither "Storm" XDDCC and why not just rotate the structure depending on the orientation..?

**Comment by TaintedBlock** [comment]
> > The reason for the current design is because of the different orientations the Withered Symbiont can land in
> 
> Wut? "Withered Symbiont"? You mean Wither "Storm" XDDCC and why not just rotate the structure depending on the orientation..

The wither storm can land at an angle and the structure can't rotate like that. Making the "star fish" structure more appropriate. You could just suggest to make the structure look more like tentacles, but imo it's just not needed.

**Comment by watersofnazareth** [comment]
> > The reason for the current design is because of the different orientations the Withered Symbiont can land in
> 
> Wut? "Withered Symbiont"? You mean Wither "Storm" XDDCC and why not just rotate the structure depending on the orientation..?

?

**Comment by nonamecrackers2** [comment]
> > The reason for the current design is because of the different orientations the Withered Symbiont can land in
> 
> 
> 
> Wut? "Withered Symbiont"? You mean Wither "Storm" XDDCC and why not just rotate the structure depending on the orientation..?
> 
> 
> 
> 

Not that simple. Rotating blocks with non-90 degree angles don't play very well. It looks like a starfish so it doesn't have to be rotated.

Regardless I don't think the structure needs changing.

**Comment by Herobrine982950291** [comment]
Bitadi-Zangalewa-dye-snayahai.
