### ISSUE TITLE
[Suggestion]: Netherite command tools.

### ISSUE THREAD

**Issue by PchelkaJeludok** [nonamecrackers2/crackers-wither-storm-mod#2082]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I'd like see it in mod because why Command tools can be only Wood, Stone, Iron and Diamond, if even wood can be why Netherite can't?

**Comment by GearsawStudios** [comment]
You didn’t read the guidelines, no tools allowed in suggestions.

**Comment by watersofnazareth** [comment]
#1239 #1430 #261
