### ISSUE TITLE
[Suggestion]: Custom Armor.

### ISSUE THREAD

**Issue by Totallysurfaceman1** [nonamecrackers2/crackers-wither-storm-mod#2083]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

It would be cool If there was custom armor i.e. In the bowel's after you kill the symbiont, you could use the book for command block armor. After killing the wither storm, you could use the flesh block It drop's to make armor that would resemble the wither storm.

**Comment by GearsawStudios** [comment]
Please read the guidelines, no armor or tools.
