### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2086]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

Idk if this is intended or not but one of the heads really likes to go upside down lmao, all of the heads do

### Steps to Reproduce

1. summon wither storm
2. Go to phase 4
3.  Wait for one of the heads to go upside (happens randomly) 

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![image](https://github.com/user-attachments/assets/7611771b-9531-4556-9699-8dcd15abcb75)

### Mod List

EMF
ETF
CWSM
essential

**Comment by nonamecrackers2** [comment]
#2021
