### ISSUE TITLE
[Bug]: if the sybiont casts the area clear, it deletes some of the beacon's blocks

### ISSUE THREAD

**Issue by Cyfenn01** [nonamecrackers2/crackers-wither-storm-mod#2088]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

1.20.1

### Describe the bug

when the sybiont is spawned by the beacon, if it casts the area clear, it deletes some of the beacon's blocks

### Steps to Reproduce

1. summon the symbiont
2. have it cast the area clear spell
3. boom, you have to grind for more gold and other stuff

### Crash Reports/Logs

NOT A CRASH

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

NONE

**Comment by Cod1ngGamer** [comment]
The symbiont can use /clear now?

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
