### ISSUE TITLE
[Suggestion]: New Phases!

### ISSUE THREAD

**Issue by Cyfenn01** [nonamecrackers2/crackers-wither-storm-mod#2089]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

make it so the storm can evolve to bigger phases, like a phase 8 or 9, or maybe even a 10! it would grow horazontally since it reached the build limit, like it starts to do in MCSM! this would be really cool and make it so there's even more of an urge to destroy the storm

**Comment by C-4-N** [comment]
u just signed ur death warrant

**Comment by GearsawStudios** [comment]
You didn’t read the guidelines.

**Comment by C-4-N** [comment]
> You didn’t read the guidelines.

guideline is scared of this guy.

**Comment by TaintedBlock** [comment]
The Wither Storm does not grow horizontally due to a build limit in Story Mode. lol

**Comment by nonamecrackers2** [comment]
Please read the guidelines. Failure to do so will get you block from this repository.

**Comment by BluePineappleGuy** [comment]
blud checked the guidelines box and then went on to ask for new phases 💀

**Comment by Herobrine982950291** [comment]
> blud checked the guidelines box and then went on to ask for new phases 💀

I don't see a check-mark

**Comment by BluePineappleGuy** [comment]
> > blud checked the guidelines box and then went on to ask for new phases 💀
> 
> I don't see a check-mark

its right here:

> ### Guidelines
> * [x]  By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

**Comment by Herobrine982950291** [comment]
oh, the checkmark is almost invisible.. i see now
