### ISSUE TITLE
Wither Storm follows the amulet as in the original video game.

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#209]
In Minecraft Story Mode, the wither storm followed the amulet little by little, in an episode Ivor said that, and why not make that mechanic with the mod, if he doesn't bring the amulet, the wither storm will follow his way, but if someone has the amulet, the wither storm will follow the one who has the amulet little by little.

**Comment by watersofnazareth** [comment]
It does function this way you have to set it's ultimate target to: "NONE"

**Comment by TheSrBig** [comment]
> It does function this way you have to set it's ultimate target to: "NONE"

¿?

**Comment by nonamecrackers2** [comment]
This is what the mod does?
