### ISSUE TITLE
[Suggestion]: Advancements for encountering/killing a sickened wolf and cat.

### ISSUE THREAD

**Issue by Cuteplushbros** [nonamecrackers2/crackers-wither-storm-mod#2092]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The advancements would be called "Bad Dog!" and "Bad Kitty!" respectively.

**Comment by TaintedBlock** [comment]
How about you get that for killing a sickened cat or wolf that used to be your pet?

**Comment by Cod1ngGamer** [comment]
> How about you get that for killing a sickened cat or wolf that used to be your pet?

No. Just no.

**Comment by TaintedBlock** [comment]
> > How about you get that for killing a sickened cat or wolf that used to be your pet?
> 
> No. Just no.

I would like to know why

**Comment by nonamecrackers2** [comment]
I don't really feel this entirely necessary, sorry. Thanks for your suggestion though
