### ISSUE TITLE
[Bug]: Tamed entities eaten by WS Segments don't respawn.

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2093]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Describe the bug

A bug happened! When tamed pets such as wolves or cats are eaten by WS Segments, they don't respawn when the WS dies.

### Steps to Reproduce

1. Summon WS (Phase 6+)
2. make segments eat tamed wolves/cats
3. Kill WS (by killing the command block or using /witherstormmod kill @w)

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

![image](https://github.com/user-attachments/assets/866292d2-a3b9-4f6b-8760-604702ddcc4d)

**Comment by nonamecrackers2** [comment]
This will be fixed in the next major release
