### ISSUE TITLE
[Bug]: Wither Storm Revives despite no players being near it/Wither Sickness in the Nether

### ISSUE THREAD

**Issue by MinusCrofters** [nonamecrackers2/crackers-wither-storm-mod#2094]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

So me and one of my friends were playing the mod on a multiplayer Aternos server, preparing for Phase 6 when all of a sudden the Storm got back up all on its own despite the remains being several thousand blocks away (both me and my friend were at 0, 0)

Similarly, we both kept getting wither sickness while being in the nether, again, while the thing was dead

Is it getting up by itself a bug or actually part of the mod? Both of us checked everywhere and couldn't find much on it because everyone kept immediately hopping back into the fight.

### Steps to Reproduce

(We have ZERO clue how to reproduce the bug, it doesn't seem to do anything in singleplayer worlds)

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot (5627)](https://github.com/user-attachments/assets/74cbbce1-c2ec-4749-835d-274ad1b7d42b)

![whyisshebackup](https://github.com/user-attachments/assets/4dfb942c-1ec5-402f-b25f-616fbc32de5c)

### Mod List

Cracker's Wither Storm Performance (Modpack)
JustZoom (ver. 1.0.2)
Simple Voice Chat (ver. 2.5.19)

**Comment by MinusCrofters** [comment]
side note, second screenshot is from my friend and his lack of advancement for reviving it
the only reason that it says "set gamemode to survival" is because he was prepping us further bc we were VERY underprepared for phase 6

**Comment by GearsawStudios** [comment]
This is intended behavior, it'll get back up over time. How were you dealing with the Wither Sickness? It has an application delay but shouldn't be returning unless you get near the WS again.

**Comment by sm644me** [comment]
The Wither Storm automatically revives after an hour (configurable) even if no one disturbs the corpse, so that's intended. Not sure about the Wither Sickness, though. It takes a while to set in once you're infected, but if you're getting reinfected without being near it, that's a bug.

**Comment by BluePineappleGuy** [comment]
why is this closed, the storm reviving wasn't a bug but the sickness in the nether was a bug

**Comment by MinusCrofters** [comment]
> why is this closed, the storm reviving wasn't a bug but the sickness in the nether was a bug

the main thing we were worried about was the wither storm standing up, i just included the wither sickness part bc i was unsure about that but wasn't as worried

**Comment by nonamecrackers2** [comment]
You may have gotten infected before hand and it just took a long time to set in (unless if you cured yourself while in the nether, then got it again, that would be a bug). If you're still experiencing this issue I'd open a new bug report
