### ISSUE TITLE
[Bug]: Witherstorm Fragment texture shown on the Witherstorm itself on phase 3.2 and lod phase 5

### ISSUE THREAD

**Issue by MoistedPotatoes** [nonamecrackers2/crackers-wither-storm-mod#2095]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

45.1.0

### Describe the bug

the wither storm has the fragment texture on it when its at phase 3.2 and low poly phase 5

### Steps to Reproduce

1. Summon a wither storm
2. set it's phase to 3.2 or 5
3. See error

### Crash Reports/Logs

none, it's just a texture issue

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-08-04_12 05 59](https://github.com/user-attachments/assets/bef5e03e-c3e8-48b6-a8d7-2eb1baf67530)
![2024-08-04_12 05 35](https://github.com/user-attachments/assets/aacc2a25-0748-4d19-b0f4-5a2e6b328590)
![2024-08-04_12 05 33](https://github.com/user-attachments/assets/25f7dff5-8faa-4943-894e-c02275bb4c62)

### Mod List

Cracker's Wither Storm Mod

**Comment by nonamecrackers2** [comment]
This is just an unfortunate quirk with how the texture is laid out. Not easily fixable at this moment
