### ISSUE TITLE
WitherStorm Reward

### ISSUE THREAD

**Issue by IntrovertedGamer** [nonamecrackers2/crackers-wither-storm-mod#21]
I always thought that defeating a phase 7 witherstorm should be more rewarding, so i'm suggesting an item that could be dropped by it after finally killing it

Broken Command Block: 

It's a command block that can be used in survival, to make it not as overpowered as a regular command block it has it's own pros and cons.

Pros:
-Can't be burned

-Can't be blown up

-Mineable and can be placed wherever you like

-Allows for the use of a single command every in-game week

-Free [Stackable] Items!

Cons:

-Impulse only

-Can't use it to switch gamemodes

-A limit to how many items you can have

-You can't summon Mobs from your mod with this

-You can only use 1 command every week

An alternative could be making the current WitherStorm drop the same but the Star could be used to make something like this.

**Comment by nonamecrackers2** [comment]
There's already a withered nether star in the game that drops from the Wither Storm, and there is a planned use for it in the future. The command block idea is interesting although it can also be overpowered, players who don't use commands may struggle with it, and overall doesn't really fit in with the mod really well. Thanks for the suggestion, though!
