### ISSUE TITLE
[Set ultimate target block pos command] I have a new suggestion for the amulet and/or new command

### ISSUE THREAD

**Issue by Gaboamau** [nonamecrackers2/crackers-wither-storm-mod#210]
**Description of feature**
Since the amulet was added, I was wondering if you could send the WS to a specific place, so what you could add is that if the amulet does put on an item frame or an armor stand in a specific place, the WS would go to that place and stop following the player or players, the WS will stay there until the amulet is removed, and/or you could also put a command where we put the coordinates for where we want the WS to go and it stays there until we put another command where the fixing to that place is removed (example: /witherstormmod ultimateTarget <entity/location> <set/clear> <x, z>)

**Comment by nonamecrackers2** [comment]
While following the amulet outside of a player's inventory isn't feasible, I'll definitely add the ability to set a specific pos for it to go to, to go along with setting a specific player.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
