### ISSUE TITLE
[Suggestion]: When flying directly past the storm, it gets distracted for 1-2 minutes

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2100]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When you fly directly past the storm, I think it should get distracted (thinking you're still there) before tracking you again! This happens in Cracker's Wither Storm Bedrock Port 0.4.5 by Persom and Tazo!

**Comment by watersofnazareth** [comment]
This would make things way too easy

**Comment by Herobrine982950291** [comment]
> This would make things way too easy

or at least for like 30-40-50 seconds at least..

**Comment by nonamecrackers2** [comment]
Yeah and this wouldn't really be feasible to do as of now

**Comment by TaintedBlock** [comment]
> When you fly directly past the storm, I think it should get distracted (thinking you're still there) before tracking you again! This happens in Cracker's Wither Storm Bedrock Port 0.4.5 by Persom and Tazo!

This just seems like something that happens because of Bedrock being Bedrock. Not an actual intended feature.
Remember, CWSMBP is trying to replicate CWSM, not the other way around.
