### ISSUE TITLE
[Bug]: Incompatibility between latest version of CWSM and Sapience

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#2103]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.5

### Describe the bug

When the mod Sapience (https://www.curseforge.com/minecraft/mc-mods/sapience) is enabled and a Sickened Villager spawns, the game crashes, with a server crash for some reason. Sapience is mainly a better AI for Piglins mod, it only changes one thing about villagers which is the ability so shift-right click them to check the reputation the player has with the villager in question.

### Steps to Reproduce

Simply spawning a Sickened Villager when Sapience is present with CWSM causes a server crash (even when in single player)

### Crash Reports/Logs

https://drive.google.com/drive/folders/1Tt9zijgRpF9NXfq6FKxlaJr4_TznS39C?usp=sharing

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Mod list should be included in the crash report

**Comment by BluePineappleGuy** [comment]
yeah there are some compatibility issues between CWSM and sapience. IIRC this is a known issue.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release
