### ISSUE TITLE
[Suggestion]: Withered Symbiont Battle Area

### ISSUE THREAD

**Issue by RPM092210** [nonamecrackers2/crackers-wither-storm-mod#2105]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the Withered Symbiont spawns in, a circle filled with flesh blocks will spawn around it, and the Withered Symbiont will stay in that area. This will help prevent the Withered Symbiont from getting lost.

**Comment by nonamecrackers2** [comment]
I don't really like generating battle arenas, since I don't want to have to deal with remembering blocks that get replaced by the arena. In general, the terrain and the Wither Storm consuming it is meant to be the arena you fight the Symbiont in.
