### ISSUE TITLE
[Bug]: WS transitioning from distant render to in render causes fog to appear when using shaders

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2107]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Describe the bug

A bug happened! When the WS comes in render, a bit of fog appears behind the WS.

### Steps to Reproduce

1. Enable shaders
2. Wait for WS to transition from distant to in render
3. See error

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-08-08_20 34 51](https://github.com/user-attachments/assets/2c416bc9-83b4-40f3-8916-92a363fdaff3) Before in render
![2024-08-08_20 34 54](https://github.com/user-attachments/assets/70ef4d27-ec01-4e93-be9c-9960c546422d) After in render

### Mod List

![image](https://github.com/user-attachments/assets/78071d96-319b-4e78-8460-1a3a20d2066f)

**Comment by Herobrine982950291** [comment]
Heres a vid: 

https://github.com/user-attachments/assets/cfc2b39a-e0dc-4001-ba60-3c83a7504249

**Comment by nonamecrackers2** [comment]
This is a shader issue, not much I can do here.

**Comment by Herobrine982950291** [comment]
Never gonna give you up, never gonna let you down! Never gonna run around and desert you! Never gonna make you cry, never gonna SAY Goodbye! Never gonna tell a lie and hurt you!
