### ISSUE TITLE
[Bug]: Wither Storm don't move when far away and im sure one of mods does that 

### ISSUE THREAD

**Issue by Witherstormfan-helloneighbor** [nonamecrackers2/crackers-wither-storm-mod#2108]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.19.2

### Mod Version

3.1.1.1

### Mod Loader

Forge

### Mod Loader Version

43.4.0

### Describe the bug

tell me what mod may cause wither storm stays in place

### Steps to Reproduce

1.I Spawn Wither storm
2.when i go like bit far when his bar dissipear he just frozen in place

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

[Wither Storm + Alternative Reality.zip](https://github.com/user-attachments/files/16553229/Wither.Storm.%2B.Alternative.Reality.zip)
 

### Mod List

here i gave to download and see it

**Comment by Pandaboi25x** [comment]
This is a 1.19.2 bug and its been fixed in the newer versions

**Comment by nonamecrackers2** [comment]
Please use an updated version of the mod.
