### ISSUE TITLE
[Bug]: No bowels fog when using shaders

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2109]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.3.1

### Describe the bug

A bug happened! When using shaders, the purple fog in the bowels is gone!

### Steps to Reproduce

1. Enable shaders
2. enter WS bowels
3. See error

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

![image](https://github.com/user-attachments/assets/07e2117c-983c-43df-b3ac-40e293cc5cbd)

**Comment by TaintedBlock** [comment]
This is a shader issue.

**Comment by nonamecrackers2** [comment]
As Tainted said this is a shader issue
