### ISSUE TITLE
[Suggestion]: QOL Small Cluster Shapes

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2111]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The shape of smaller clusters (like the ones seen in hunchback/constant blackhole) could occasionally have more blocks in them (like the tractor beams)

TLDR Occasional Two/three blocks in a small cluster instead of just one

**Comment by watersofnazareth** [comment]
Not entirely sure about this one, but I do want to eventually make it so that normal clusters aren't all just one giant sphere

**Comment by watersofnazareth** [comment]
This will be addressed with the cluster rework I don't plan on changing small clusters to be bigger than 1x1s

**Comment by BluePineappleGuy** [comment]
> This will be addressed with the cluster rework I don't plan on changing small clusters to be bigger than 1x1s

yo we gettin a cluster rework?
