### ISSUE TITLE
[Bug]: witherstormmod.subtitle.flaming_skull_impact ?

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2113]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.5.0

### Describe the bug

A bug happened! When a WS Flaming skull hits the ground, the subtitles say witherstormmod.subtitle.flaming_skull_impact...

(btw the version of the Witherstormmod is actually 4.2.0.1

### Steps to Reproduce

1. Enable subtitles
2. Summon flaming Wither Skull (or summon WS and wait for it to shoot the skull)
3. See error

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

Uploading Minecraft Forge_ 1.20.1 - Singleplayer 2024-08-11 11-14-24.mp4…

### Mod List

![image](https://github.com/user-attachments/assets/dfeaffdb-0d4b-4932-9b3a-6a5c8fc708e1)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next release
