### ISSUE TITLE
[Bug]: Server fails to start with the mod.

### ISSUE THREAD

**Issue by JsinghG5** [nonamecrackers2/crackers-wither-storm-mod#2114]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.0.1

### Mod Loader

Forge

### Mod Loader Version

Forge 47.3.0, Java 17 (I tried it with Java 21 as well)

### Describe the bug

Server is unable to start because it "Failed to create a mod instance". I'm really not sure what to write here, let me know if you want more detail.

### Steps to Reproduce

Unsure, I ran the autogenerated start.sh with crackers witherstorm as the only mod in the mods folder. When I swapped it out for Aquamirae and Obscure API to see if it was a forge problem the server worked fine.  

### Crash Reports/Logs

Latest.log: https://pastebin.com/jb5VzMWh
Debug.log: https://pastebin.com/NTwak9PB
(I'm not sure if those are the same thing or not, might as well send both, I can also send the terminal output if needed)

### Is OptiFine installed?

No

### Screenhots

I don't think they're needed?

### Mod List

NONE

**Comment by nonamecrackers2** [comment]
Found the source of the problem, will be fixed in the next major release
