### ISSUE TITLE
[Bug]: Wither Storm is unable to chomp armor stands

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2115]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.0.1

### Mod Loader

Forge

### Mod Loader Version

Forge 47.3.0

### Describe the bug

This is kind of two bugs in one
1. The heads can directly target armor stands for some reason
2. When it does, it can't chomp the armor stand so it just looks up and spazzes out (However it can pull any non-directly targeted armor stands into the body like normal)

### Steps to Reproduce

1. Spawn the wither storm (Phase 2+)
2. Spawn armor stands
3. watch it suffer misfortune

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM
ETF
EMF
Physics mod pro
Embeddium
Embeddium Dynamic lights

**Comment by nonamecrackers2** [comment]
Will be fixed, the Wither Storm is not supposed to target armor stands
