### ISSUE TITLE
[Bug]: Wither Storm Making GUI Black

### ISSUE THREAD

**Issue by Contoro123** [nonamecrackers2/crackers-wither-storm-mod#2120]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

When you spawn the wither storm again with the beacon, then you change the evolution speed to 0.1; it turns the whole GUI and screen black. When you go back to the menu's it also changes the texts to black. the only way to fix it is to reset the whole game.

### Steps to Reproduce

1. summon the wither storm with the beacon
2. use the command "/witherstormmod evolutionspeed set @w 0.1"

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Entity Model Features, Entity Texture Features.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next release.

**Comment by TaintedBlock** [comment]
The darkness grew stronger
