### ISSUE TITLE
[Suggestion]: More small mobs being consumed

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2121]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Tiny mobs such as tiny magma slimes and certain baby mob variants (rabbits, bees) could be pulled in like small slimes

Other small mobs such as Rabbits, Frogs, Bees, Bats, Fish, Other Baby Mob variants, etc could be pulled in slightly (the further they are away and the bigger the wither storm is determines how much the storm pulls in them, i.e. phase 7 pulls in small mobs like tiny mobs when they are close enough, while phase 4 is only able to fully pull in mobs that are roughly 20 blocks away and the rest are just tugged a bit)

The strength that it pulls small mobs could be configurable in "World Consumption" settings, and also toggleable entirely

**Comment by watersofnazareth** [comment]
Already planned, the update came out before I could finish the system
