### ISSUE TITLE
[Suggestion]: Ability to do a server-side override of client settings for cwsm

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2126]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

On servers it would be neat to be able to override client settings, for events and such

**Comment by nonamecrackers2** [comment]
This would not be a good idea. This could be used maliciously to override accessibility and preference options. In general the client config should remain client-side only, and should not be able to be modified by the server.
