### ISSUE TITLE
[Suggestion]: Orbiting phantoms swoop around phase 5.5 and phase 7 (open bowels) wither storms

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2127]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Orbiting phantoms would occasionally swoop down around the heads of the storm when it is at phase 5.5 (Bombable) or Phase 7 (Hole Open)

It's a reference to war of the worlds, where seagulls would circle around tripods and when the shields were down and they were vulnerable, they would land on the tripods. Basically, it would be Phantoms signifying that the wither storm is vulnerable and able to be attacked

**Comment by Kyleo3345** [comment]
Nice reference using war of the worlds.

**Comment by nonamecrackers2** [comment]
Interesting idea, but this would take a lot of effort for an effect that would be barely appreciated by the majority of players
