### ISSUE TITLE
[Suggestion]: Tainted Snow set

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2129]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

This would go along with #2128 in my reply

Basically just tainted snow layers/blocks, as well as a tainted snow grass block

**Comment by watersofnazareth** [comment]
I don't think I'll add tainted snow, it'd be hard to fit it into the bowels

**Comment by SSgamingYT** [comment]
> I don't think I'll add tainted snow, it'd be hard to fit it into the bowels

It wouldn't entirely have to fit into the bowels (unless you added a mini tainted taiga room in the bowels), it could just be something that the player can make with tainted snow golems and the snow that they make
