### ISSUE TITLE
Changes to the Wither Storm and dead

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#213]
Can you add particles to the tractor beams and add glowing parts to the wither storm in phase 6/7 and also add like a hallway of tentacles to the command block.

**Comment by nonamecrackers2** [comment]
Particles: #14; Emissive textures: #63

The hallway to command block podium is meant to be a break from the chaos of getting into the bowels and to see the command block for the first time; adding a bunch of tentacles that would slap players around would take away both aspects

**Comment by Resuster** [comment]
oh
