### ISSUE TITLE
[Suggestion]: More Withered items ( I listed them in the description ) 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2130]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Withered raw beef: Can be dropped by killing a sickened cow and a sickened mooshroom

Withered poppy and tainted iron ingot: Can be dropped by sickened iron golems

Withered leather: can be dropped by sickened cow and a sickened mooshroom

Withered raw porkchop: can be dropped by sickened pig

Withered ominous banner: can be dropped by pillagers and vindicator ( only if they have the Withered banner on their head )

Withered arrow: can be dropped by sickened skeletons

Withered string: can be dropped by sickened cats and sickened spiders

Withered emaralds: can be dropped by sickened vindicators

Withered Feather: can be dropped by sickened chickens and sickened parrots

Withered Raw chicken: can be dropped by sickened chickens

Withered phantom membrane: can be dropped by sickened phantom's

**Comment by watersofnazareth** [comment]
Well, Sickened mobs aren't really meant to drop food, but once Sheep are added, String will likely also be added

**Comment by Herobrine982950291** [comment]
what will the uses be for all of this?

**Comment by Infinitekaosv3** [comment]
> what will the uses be for all of this?

maybe crackers can come up with that, i just suggested this sense it would make sense for the sickened animals to drop what their normal versions drop

**Comment by nonamecrackers2** [comment]
I don't really see the point in many of these items. A withered poppy would really just be a withered rose, and a lot of these food items wouldn't be edible so they might as well just be the withered flesh. The rest wouldn't have much use, and to justify them we should add something for them but that's currently not on my agenda. Thanks for the suggestion though.

**Comment by BluePineappleGuy** [comment]
withered string sounds like it could have a good use but i can't think of one
