### ISSUE TITLE
[Suggestion]: Immersive crafting

### ISSUE THREAD

**Issue by Xeromite** [nonamecrackers2/crackers-wither-storm-mod#2132]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Make crafting immersive, for example, making formidibomb like in story mode (I know there are already mods adding that, but they dont start the formidibomb timer when crafted)

**Comment by GearsawStudios** [comment]
Unclear, what do you mean by immersive? If it's making it more like Story Mode, then it'll likely be rejected.

**Comment by Xeromite** [comment]
> Unclear, what do you mean by immersive? If it's making it more like Story Mode, then it'll likely be rejected.

Meant what you put the items on a table (not in UI), for example, you take 2 sticks in hand, put it in a row, take 3 wood, put it in a row and you get a pickaxe, well i guess thats a stupid feature

**Comment by SSgamingYT** [comment]
> > Unclear, what do you mean by immersive? If it's making it more like Story Mode, then it'll likely be rejected.
> 
> Meant what you put the items on a table (not in UI), for example, you take 2 sticks in hand, put it in a row, take 3 wood, put it in a row and you get a pickaxe, well i guess thats a stupid feature

there are no plans to pointlessly make features that are non-witherstorm related features anything like story mode.

**Comment by Xeromite** [comment]
> > > Unclear, what do you mean by immersive? If it's making it more like Story Mode, then it'll likely be rejected.
> > 
> > 
> > Meant what you put the items on a table (not in UI), for example, you take 2 sticks in hand, put it in a row, take 3 wood, put it in a row and you get a pickaxe, well i guess thats a stupid feature
> 
> there are no plans to pointlessly make features that are non-witherstorm related features anything like story mode.

If you do watch the moment where jessie crafts the formibidibomb, you will understand what i mean

**Comment by SSgamingYT** [comment]
> > > > Unclear, what do you mean by immersive? If it's making it more like Story Mode, then it'll likely be rejected.
> > > 
> > > 
> > > Meant what you put the items on a table (not in UI), for example, you take 2 sticks in hand, put it in a row, take 3 wood, put it in a row and you get a pickaxe, well i guess thats a stupid feature
> > 
> > 
> > there are no plans to pointlessly make features that are non-witherstorm related features anything like story mode.
> 
> If you do watch the moment where jessie crafts the formibidibomb, you will understand what i mean

Did you just blatantly ignore what I said??? There are _no_ plans to make this an official feature. Instead, stick with Immersive MC, as eventually CWSM will have compatibility with it.

**Comment by Xeromite** [comment]
May take an eternity, devs dont really make any mods compatibilities (even with such small one)

**Comment by SSgamingYT** [comment]
> May take an eternity, devs dont really make any mods compatibilities (even with such small one)

I literally made an issue about this exact thing and it got a response. #2042

**Comment by Xeromite** [comment]
> > May take an eternity, devs dont really make any mods compatibilities (even with such small one)
> 
> I literally made an issue about this exact thing and it got a response. #2042

Alright then

**Comment by nonamecrackers2** [comment]
As people have already mentioned, you can use ImmersiveMC for this
