### ISSUE TITLE
[Bug]: WS transitioning from distant render to in render causes fog to appear when distant fog is off even without shaders

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2135]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.5

### Describe the bug

A bug happened! Similar to #2107 but with no shaders!

### Steps to Reproduce

1. turn off distant fog
2. Wait for WS to transition from distant to in render
3. See error

### Crash Reports/Logs

N/A

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

![image](https://github.com/user-attachments/assets/f710b095-f85f-41a8-a280-e8fa0f3ee729)

**Comment by nonamecrackers2** [comment]
This is because the distant fog is off, but not the normal, vanilla fog. You'll have to find a mod that disables vanilla fog, since disabling it for just the Wither Storm this way is not possible with the limited time scope that I have.

**Comment by Herobrine982950291** [comment]
> This is because the distant fog is off, but not the normal, vanilla fog. You'll have to find a mod that disables vanilla fog, since disabling it for just the Wither Storm this way is not possible with the limited time scope that I have.

So THAT's why the mod isn't for 1.20.3 or up....

**Comment by nonamecrackers2** [comment]
What?

**Comment by Herobrine982950291** [comment]
nothing
forget it

**Comment by BluePineappleGuy** [comment]
> > This is because the distant fog is off, but not the normal, vanilla fog. You'll have to find a mod that disables vanilla fog, since disabling it for just the Wither Storm this way is not possible with the limited time scope that I have.
> 
> So THAT's why the mod isn't for 1.20.3 or up....

no i think crackers is still working on it the fog has nothing to do with this

**Comment by Herobrine982950291** [comment]
> > > This is because the distant fog is off, but not the normal, vanilla fog. You'll have to find a mod that disables vanilla fog, since disabling it for just the Wither Storm this way is not possible with the limited time scope that I have.
> > 
> > 
> > So THAT's why the mod isn't for 1.20.3 or up....
> 
> no i think crackers is still working on it the fog has EVERYTHING to do with this.

! wasn't talking about that.
