### ISSUE TITLE
[Suggestion]: Configurable Head Movement Speed

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2138]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A way to change how fast the heads rotate around (in blocks per second?)

**Comment by TaintedBlock** [comment]
#1780 #1858

**Comment by SSgamingYT** [comment]
> #1780 #1858

Oop

**Comment by SSgamingYT** [comment]
Dupe
