### ISSUE TITLE
[ Suggestion ] Disable command block tools and the crafting recipes in config.

### ISSUE THREAD

**Issue by onyxromero** [nonamecrackers2/crackers-wither-storm-mod#214]
**Description of feature**
With the ability to define custom tools that can work on command blocks via tags in a datapack we can make any tool we want work on the command block. The command block tools are infinite, and it'd add more of a challenge if we could use tools that could break.

**Comment by nonamecrackers2** [comment]
Should be able to remove them using a data pack to remove the recipes, however let me know if it’s not possible.
