### ISSUE TITLE
Wither Storm vanished after i closed my server for the night 

### ISSUE THREAD

**Issue by High-Asian** [nonamecrackers2/crackers-wither-storm-mod#2143]
Me and my buddies were playing with the mod on a server and when we closed it for the night it vanished. We only have client side mods, When we tried to go into creative to summon a new one, it didn't work so idk what happened. But we can spawn via commands.

**Comment by Herobrine982950291** [comment]
Please fill out the template.

**Comment by BluePineappleGuy** [comment]
yeah you need to use the bug report template for this

**Comment by nonamecrackers2** [comment]
Please use the bug report template
