### ISSUE TITLE
[Bug]: Withered Symbiont's bossbar is visible underground

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#2144]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

basically the name of the withered symbiont was able to be seen all the way underground, and this was in Y -58 
![2024-08-19_20 14 54](https://github.com/user-attachments/assets/2745b914-9d0d-423f-911a-1253db86531d)

### Steps to Reproduce

1. Go underground like really far
2. Wait for the WS to spawn the symbiont
3. The WS Spawns the symbiont
4. See Result

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Modpack: Cracker's Wither Storm Performance (CWSM, Configured, Entity Culling, BHMenu, MixinExtras, ImmediatelyFast, FerriteCore, Embeddium, Embeddium Extra, Dynamic FPS, Just Zoom, Cloth Config, Yeetus Experimentus, Konkrete, Oculus, ModernFix, and Just Enough Items)

**Comment by TaintedBlock** [comment]
I'm pretty sure this is intentional so you know it's around

**Comment by witherstormfan87** [comment]
> I'm pretty sure this is intentional so you know it's around

are you sure?

**Comment by TaintedBlock** [comment]
> > I'm pretty sure this is intentional so you know it's around
> 
> are you sure?

Yes, it would be pretty hard to know where it is otherwise. The wither storm's boss bar can be configured to show up underground. It only doesn't for the purpose of it sneaking up on you while you're underground

**Comment by Herobrine982950291** [comment]
"Tentacled Zombo" is not a Withered Symbiont. I think you have the wrong repostitory XD

**Comment by BluePineappleGuy** [comment]
> "Tentacled Zombo" is not a Withered Symbiont. I think you have the wrong repostitory XD

maybe some kind of rename using resource packs

**Comment by TaintedBlock** [comment]
> "Tentacled Zombo" is not a Withered Symbiont. I think you have the wrong repostitory XD

Me when other languages exist

**Comment by Herobrine982950291** [comment]
I was just jokin around, my guys!

**Comment by Xeromite** [comment]
Isnt that just normal?

**Comment by witherstormfan87** [comment]
i made a resource pack 2 change it to the lolcat language its not done yet though

**Comment by BluePineappleGuy** [comment]
> i made a resource pack 2 change it to the lolcat language its not done yet though

once finished you should open a language pull request i think this would be great to be official

**Comment by nonamecrackers2** [comment]
This is intended
