### ISSUE TITLE
[Suggestion]: Make constantblackhole more prominent in later stages

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2147]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

It looks kind of lame in phase 4 and up because the only thing that it actually absorbs quickly are leaves and some flowers, but stuff like planks and cobble are kinda slow (as well as other blocks, like ores)

**Comment by TaintedBlock** [comment]
Lag machine

**Comment by SSgamingYT** [comment]
> Lag machine

It says the option is laggy in the config already 🤷‍♂️

**Comment by Composer-Hu** [comment]
In the previous version it did work on all blocks, but at the moment, only natural blocks can be quickly absorbed and cause a bigger lag than ever before, I think if there is a config can be changed to 4.1 constantblackhole might be good.

**Comment by BluePineappleGuy** [comment]
So essentially, add the legacy constantblackhole option

**Comment by watersofnazareth** [comment]
Setting the value to low will just instantly delete things, you wouldn't be able to place and use stuff around the storm at all, but also this would cause insane lag, I may tweak the values but it's like how it is for a reason
