### ISSUE TITLE
[Suggestion]: Giant clusters in stage 7

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2148]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the storm reaches stage 7, it should have a small chance to grab **Big** clusters made of _only blocks that get grabbed by constant blackhole, excluding leaves and flowers_

**Comment by watersofnazareth** [comment]
The clusters will eventually get a rework and I don't want to add this into constant blackhole

**Comment by SSgamingYT** [comment]
> The clusters will eventually get a rework and I don't want to add this into constant blackhole

It isn't a constant blackhole thing but alr

**Comment by SSgamingYT** [comment]
> The clusters will eventually get a rework and I don't want to add this into constant blackhole

It just uses the blocks that can be grabbed by constant blackhole

**Comment by nonamecrackers2** [comment]
I'm not really sure if this would be needed anyways. What kind of blocks would it even pick up?

**Comment by SSgamingYT** [comment]
> I'm not really sure if this would be needed anyways. What kind of blocks would it even pick up?

it would be able to pick up entire village houses (like churches) as well as ruined portals and giant chunks of woodland mansions

**Comment by nonamecrackers2** [comment]
Yeah this wouldn't really be feasible, scanning for stuff like that could be performance heavy and hard to pull off. The tractor beams are meant to do this anyway with their structure targeting and is more so what they are designed to do now, I don't think the normal clusters should really do this either. I may consider revisiting this in the future but for now I'll leave this closed.

**Comment by BluePineappleGuy** [comment]
> Yeah this wouldn't really be feasible, scanning for stuff like that could be performance heavy and hard to pull off. The tractor beams are meant to do this anyway with their structure targeting and is more so what they are designed to do now, I don't think the normal clusters should really do this either. I may consider revisiting this in the future but for now I'll leave this closed.

i think he means it is capable of doing that due to the size of the cluster, not that it will scan for those specifically

**Comment by SSgamingYT** [comment]
> > Yeah this wouldn't really be feasible, scanning for stuff like that could be performance heavy and hard to pull off. The tractor beams are meant to do this anyway with their structure targeting and is more so what they are designed to do now, I don't think the normal clusters should really do this either. I may consider revisiting this in the future but for now I'll leave this closed.
> 
> i think he means it is capable of doing that due to the size of the cluster, not that it will scan for those specifically

It could use the same cluster grabbing logic as the beams when "only try grabbing tractor tagged" is enabled in misc settings
