### ISSUE TITLE
[Suggestion]: Usable blocks in cluster form

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2149]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Basically, when things such as furnaces, crafting tables, chests, or any other type of container gets grabbed, it would still be interactive.

It could also make certain things like dispensers shoot out the items inside of them while they are pulled up

This allows for:
Crafting the formidibomb while being pulled into the beam (droppable formidibomb?)
Quickly getting important items out of chests and furnaces before they are consumed
Dispensers to spew massive amounts of tnt?

**Comment by SSgamingYT** [comment]
I get the odd feeling that someone already suggested this

**Comment by BluePineappleGuy** [comment]
> I get the odd feeling that someone already suggested this

i do too however i can't find any issue like this, so i guess you're good 👍

**Comment by watersofnazareth** [comment]
I don't think this is possible at least not currently
