### ISSUE TITLE
Client connecting to server issue

### ISSUE THREAD

**Issue by Xofol1** [nonamecrackers2/crackers-wither-storm-mod#215]
**Minecraft version**
The version of Minecraft the mod is running on
1.16.5 forge latest

**Mod version**
The version of the mod you are using
latest

**Describe the bug**
When i try to connect sometimes it crash my client and i get this message :
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Tag witherstormmod:high_immunity used before it was bound
Code de sortie : -1
I am french btw
Also to fix the bug you just have to make a new world before joining the server

**To Reproduce**
1. Make a sever with the mod
2. Try to connect until you get the error
3. See error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.
The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Tag witherstormmod:high_immunity used before it was bound
Code de sortie : -1

**Screenshots**

**Comment by argDoggo** [comment]
exactly the same thing

**Comment by watersofnazareth** [comment]
Do you have a crash log?

**Comment by nonamecrackers2** [comment]
What mods are you using?

**Comment by argDoggo** [comment]
[crash-2022-07-13_21.06.33-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9110721/crash-2022-07-13_21.06.33-client.txt)

here my crash log

ah and im not crashing every time i log on my dedicated server

the only fix i found is for me to CREATE a new solo world+ leave and join my server after
(btw ty for this great mod i love it ty for the hard work)

**Comment by argDoggo** [comment]
the only fix i found is for me to launch a solo game+ leave  and join my server after

**Comment by ShadeAware** [comment]
Getting this same error

**Comment by nonamecrackers2** [comment]
This should hopefully be fixed in the next update, however it's hard to check due to not knowing the mod/combination of mods that would be causing this (as I'm assuming it's due to a compat issue)
