### ISSUE TITLE
[Suggestion]: Droppable Formidibomb 

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2150]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When enabled, allows players to drop the formidibomb in lit form by pressing shift+right click at the air

The Fuse time when dropped would be configurable, but by default is 600 (half the lit fuse time)

**Comment by BluePineappleGuy** [comment]
doesn't this just make flint and steel useless for the f-bomb

**Comment by SSgamingYT** [comment]
> doesn't this just make flint and steel useless for the f-bomb

This, paired with #2149 , allows the convenience of making and dropping the formidibomb _mid air_, or while being pulled into the wither storm by a beam.

**Comment by watersofnazareth** [comment]
This doesn't fit and could potentially get a player killed on accident
