### ISSUE TITLE
[Suggestion]: Enhanced Cluster Breaking Logic

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2151]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Clusters made up entirely of weak blocks, such as smooth stone, dirt, etc should break apart a lot more than a typical breaking cluster

When a cluster is made up of too much of one single material other than leaves, planks, or grass it should break apart just a bit.

If clusters are near explosions, they should break apart and be pushed away from the explosion. This would also apply to tractor beam clusters, meaning sending TNT up there could be a way to get back chests that were nearly absorbed.

And finally, if a cluster has parts that are completely detached from it, they should disconnect from the cluster entity on formation.

There could be a few modes for this; Weak Blocks only, Materials only, Explosions only, and detached only. Some combos could be Weak & Explosions only, Materials and Weak only, and Weak and Detached only. And of course, there's "off" or "on" to toggle the feature entirely.

 (For low end devices, to avoid so much lag from the checking and entities there could be a "performance mode" toggle for it to only apply the breaking logic to 25% of clusters when enabled.)

**Comment by watersofnazareth** [comment]
Already planning a rework of the cluster system

**Comment by BluePineappleGuy** [comment]
> Already planning a rework of the cluster system

how many plans does bro have, this is the 5th time i've seen you close an issue for already being planned

**Comment by nonamecrackers2** [comment]
This is a neat idea but I think it would go under-appreciated by most people. I don't think there would be enough difference to justify an advanced block cluster logic breaking system, when a simple random check to break clusters apart would look similar or even the same to this if players don't look too hard. I appreciate the suggestion though
