### ISSUE TITLE
[Suggestion]: Extended reach for Phlegm blocks placed inside the bowels

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2152]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Basically just makes Phlegm blocks more powerful the closer they are to the command block (when the boss fight starts?)

**Comment by nonamecrackers2** [comment]
I don't entirely see the need for this and don't think this is really necessary to implement
