### ISSUE TITLE
[Suggestion]: wither storm says random stuff in chat

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#2153]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

in config off by default, idk i just wanna see stuff in chat like: your world is yummy. probably wont be added though :(

**Comment by FrozenDragon0** [comment]
This really wouldn't fit the mod at all.

**Comment by witherstormfan87** [comment]
off by default

**Comment by MoistedPotatoes** [comment]
could work for april fools but other than that, nah

**Comment by Infinitekaosv3** [comment]
Omg yes, i would love this feature in the game as a config

**Comment by NinjaSam5399** [comment]
Best idea

**Comment by Luke7381** [comment]
Why should this be added? the wither storm doesn't even talk anyway. Probably as a April fools joke but thats about it

**Comment by nonamecrackers2** [comment]
This wouldn't be something that would fit in with the mod but could be a cool April Fools thing
