### ISSUE TITLE
[Suggestion]: Inadmissibility of the destruction of a Withered Beacon by a Withered Symbiont.

### ISSUE THREAD

**Issue by Saifin87** [nonamecrackers2/crackers-wither-storm-mod#2156]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The fact is that after summoning a Withered Symbiont during a fight with him, he can use an ability that scatters blocks. This ability will scatter the beacon when the Withered Symbiont uses it immediately after the summoning, which causes inconvenience, forcing the player to collect beacon blocks in the area, especially when the player was going to summon several Withered Symbionts in a row. Perhaps some changes should be made to prevent this from happening.
![2024-08-24_18 18 56](https://github.com/user-attachments/assets/bca6fd6c-5455-4151-bd1d-ddb7e87d91d8)

**Comment by nonamecrackers2** [comment]
This is already fixed in the latest version of the mod
