### ISSUE TITLE
[Suggestion]: Tainted Dust acts as a secondary form of Redstone

### ISSUE THREAD

**Issue by MoistedPotatoes** [nonamecrackers2/crackers-wither-storm-mod#2157]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

i think it would be nice to see tainted dust act similar to redstone, maybe acting in a sort of reverse power source, where activated and deactivated power states are swapped, since the withered phlegm block exists as a sort of supper hopper, cwsm could have a lot of potential for redstone

![2024-08-24_13 55 31](https://github.com/user-attachments/assets/6204c2ec-663c-4adf-aee5-d75dc43e0a5c)

**Comment by nonamecrackers2** [comment]
Interesting idea but this is out of scope for what Cracker's Wither Storm Mod intends to do.

**Comment by YassinAlaa** [comment]
> Interesting idea but this is out of scope for what Cracker's Wither Storm Mod intends to do.

I like his idea u can open it for future reference

**Comment by BluePineappleGuy** [comment]
> > Interesting idea but this is out of scope for what Cracker's Wither Storm Mod intends to do.
> 
> I like his idea u can open it for future reference

out of scope means its not what he had in mind for the mod. so he doesn't plan on adding it, someone needs to make an addon instead
