### ISSUE TITLE
witherstorm becomes unbeatble

### ISSUE THREAD

**Issue by natanbratan350** [nonamecrackers2/crackers-wither-storm-mod#2158]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.16.5

### Mod Version

1.0.3

### Mod Loader

Forge

### Mod Loader Version

36.2.39

### Describe the bug

im playing infernal origins and after waiting about 3 hours finaly entering the bowels. hitting the command block and the platform rises yes but never stops and eventualy leaving the arena.

### Steps to Reproduce

i have no clue

### Crash Reports/Logs

was no crashes

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

https://github.com/user-attachments/assets/6444007c-ff49-4c20-9161-beebede8fe4f

### Mod List

the infernal origins modpack in the forge up plus the mod clumps and chat colors

**Comment by TaintedBlock** [comment]
Please play modern versions of the mod. 1.16.5 is extremely outdated.

**Comment by BluePineappleGuy** [comment]
Yeah, 1.16.5 is unsupported now and will not receive updates. This bug will probably not get fixed

**Comment by natanbratan350** [comment]
> Yeah, 1.16.5 is unsupported now and will not receive updates. This bug will probably not get fixed

is there any way to make the command block reapear with a command or something?
its the last thing i needed to do in the mod pack and i dont really want a flying mass of destruction following me everywhere in the world

**Comment by BluePineappleGuy** [comment]
> > Yeah, 1.16.5 is unsupported now and will not receive updates. This bug will probably not get fixed
> 
> is there any way to make the command block reapear with a command or something? its the last thing i needed to do in the mod pack and i dont really want a flying mass of destruction following me everywhere in the world

as far as i know, you're out of luck. you'll probably just have to `/kill` the storm or something like that.
