### ISSUE TITLE
[Suggestion]: Make the storm delete nearby clusters on death

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2159]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the storm dies, it deletes nearby clusters (30 block radius or higher, maybe configurable?) to avoid it's corpse chunks stacking on them and causing a weird structure

**Comment by watersofnazareth** [comment]
Deleting the clusters for no reason makes no sense and would likely confuse people

**Comment by SSgamingYT** [comment]
> Deleting the clusters for no reason makes no sense and would likely confuse people

It would be part of the death sequence (/witherstormmod kill @w) to make the clusters of its flesh that fall out actually hit the ground instead of "landing" in the air
