### ISSUE TITLE
[Suggestion]: Dynamic item pull strength

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2162]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the storm is near an item, the item is pulled in based on how far away it is, similar to a gravitational pull. This could be configurable with four different modes-
Instant (current item pulling),

Gradual (This idea), 

Phase Gradual (Gradual, but the items phase through blocks to get to the storm), 

and Phase Instant (Current item pulling but the items phase through blocks)

The phase modes allow for less server/tick performance issues for people who like playing with high settings but don't want items all over the ground causing lag.

(Could go into the Items Category)

**Comment by watersofnazareth** [comment]
Items aren't meant to go through blocks, which is why there's a check for if the Storm can see an item before it pulls it, adding the ability to go through blocks really just isn't worth it when we already have things for items that help with performance

**Comment by SSgamingYT** [comment]
Problem is when the storm travels fast but leaves a lot of destruction it causes the items to be left behind (same thing happens in big caves that it manages to reach, the items can't be grabbed because of the awkward angle but the storm can still destroy it and make the items build up)

**Comment by SSgamingYT** [comment]
Problem is when the storm travels fast but leaves a lot of destruction it causes the items to be left behind (same thing happens in big caves that it manages to reach, the items can't be grabbed because of the awkward angle but the storm can still destroy it and make the items build up)
