### ISSUE TITLE
[Bug]: Tainted glass and tainted glass pains have a prefered tool

### ISSUE THREAD

**Issue by WitherInSuit** [nonamecrackers2/crackers-wither-storm-mod#2164]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.7

### Describe the bug

Normally, glass doesn't have a preferred tool to mine it faster, but the tainted glass is best mined with a pickaxe

### Steps to Reproduce

1: Mine any tainted glass block with any tool (Not pickaxe)
2: Mine it with a pickaxe, which has a noticeably faster mining speed

### Crash Reports/Logs

None

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM, Embedium, Essentials, JEI, Apple skin, Clumps

**Comment by NinjaSam5399** [comment]
Glass pains??!?! 😱 😱

**Comment by BluePineappleGuy** [comment]
> Glass pains??!?! 😱 😱

when you get cut by glass it does pain

**Comment by watersofnazareth** [comment]
Will be fixed in the next update
