### ISSUE TITLE
[Bug]: Tainted signs don't drop

### ISSUE THREAD

**Issue by WitherInSuit** [nonamecrackers2/crackers-wither-storm-mod#2165]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.7

### Describe the bug

When mining a tainted sign, nothing dropped. It also took very long to mine it even though I was using an axe

### Steps to Reproduce

Mine a tainted sign

### Crash Reports/Logs

None

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM, Embedium, Essentials, JEI, Apple skin, Clumps

**Comment by watersofnazareth** [comment]
Will be fixed in the next update
