### ISSUE TITLE
[Suggestion]: Rotating bowels

### ISSUE THREAD

**Issue by Xeromite** [nonamecrackers2/crackers-wither-storm-mod#2166]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

INSTEAD OF CODING FOR THE ENTIRE BOWELS TO ROTATE, it could be coded to make the player (and the camera) to rotate, making the effect. A lot of mods exist changing that, and they were pretty easy to code (surely this will get rejected aswell)

**Comment by TaintedBlock** [comment]
Me when you don't read guidelines

**Comment by SSgamingYT** [comment]
Wild bro (you are scheduled for execution)

**Comment by juanelgamer456** [comment]
erm, mods, kill this man!

**Comment by BluePineappleGuy** [comment]
duplicate, such solutions have been suggested and denied.

**Comment by cat100times** [comment]
it's not hard just use a gravity mod
