### ISSUE TITLE
[Bug]: Wither storm 1.20.1 server crash

### ISSUE THREAD

**Issue by Kogomre** [nonamecrackers2/crackers-wither-storm-mod#2169]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.2.20

### Describe the bug

The server crashes 5 minutes after mobs from the mod are spawned

### Steps to Reproduce

Spawn many mobs tentacle and etc

### Crash Reports/Logs

Attached as a file

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Mod List:
YungsBetterDungeons-1.20-Forge-4.0.3.jar
Createdeco-2.0.2-1.20.1-forge.jar
scena-forge-1.0.103.jar
Player-animation-lib-forge-1.0.2-rc1+1.20.jar
Botarium-forge-1.20.1-2.3.4.jar
Mcw-windows-2.2.1-mc1.20.1forge.jar
Create_jetpack-forge-4.2.1.jar
ForgeEndertech-1.20.1-11.1.4.0-build.0572.jar
YungsApi-1.20-Forge-4.0.5.jar
MaxHealthFix-Forge-1.20.1-12.0.3.jar
Cabletiers-1.20.1-1.2.2.jar
Universalgrid-1.20.1-1.1.jar
Createdieselgenerators-1.20.1-1.2h.jar
Create-new-age-forge-1.20.1-1.1.2.jar
Balm-forge-1.20.1-7.3.6-all.jar
Swampier_swamps-1.20-4.0.0.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar
Paraglider-forge-20.1.3.jar
cloth-config-forge-11.1.106.jar
Shetiphiancore-forge-1.20.1-1.2.jar
RPG_style_more_weapons_8.0_1.20.1.jar
Supplementaries-1.20-2.8.17.jar
Refinedstorage-1.12.4.jar
athena-forge-1.20.1-3.1.1.jar
BetterCompatibilityChecker-forge-4.0.8+mc1.20.1.jar
Mcw-trapdoors-1.1.3-mc1.20.1forge.jar
Sleep_tight-1.20-1.1.19.jar
Gottagofast-1.20.x-lexforge-2.0.1.jar
Fairylights-7.0.0-1.20.1.jar
Curios-forge-5.9.1+1.20.1.jar
Create_factory-0.4b-1.20.1.jar
Butchersdelight+Foods+beta+1.20.1+1.0.2.jar
ExtraStorage-1.20.1-4.0.7.jar
Worldedit-mod-7.2.15.jar
Butchersdelight+beta+1.20.1+2.0.9.jar
Mcw-roofs-2.3.1-mc1.20.1forge.jar
conditional-mixin-forge-0.6.2.jar
ItemPhysic_FORGE_v1.7.0_mc1.20.1.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
EnhancedAI-2.4.0-mc1.20.1.jar
AdChimneys-1.20.1-10.1.13.0-build.0734.jar
flightlib-forge-2.1.0.jar
JadeAddons-1.20.1-forge-5.2.2.jar
l2library-2.4.16-slim.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
DynamicTrees-1.20.1-1.3.0-BETA11.jar
DynamicTreesPlus-1.20.1-1.2.0-BETA2.jar
Createteleporters2.2-1.20.1.jar
Sliceanddice-forge-3.2.1.jar
YungsBetterJungleTemples-1.20-Forge-2.0.4.jar
Createbigcannons-5.5.0-mc.1.20.1-forge.jar
Jei-1.20.1-forge-15.8.0.18.jar
AttributeFix-Forge-1.20.1-21.0.4.jar
Caelus-forge-3.2.0+1.20.1.jar
Colytra-forge-6.2.2+1.20.1.jar
Fastasyncworldsave-1.20.1-2.0.jar
SereneSeasons-1.20.1-9.0.0.46.jar
Lightmanscurrency-1.20.1-2.2.2.5a.jar
Design_decor-0.2a-1.20.1.jar
ExtraDisks-1.20.1-3.0.2.jar
EdivadLib-1.20.1-2.0.1.jar
puzzlesaccessapi-forge-8.0.7.jar
forge-1.20.1-47.2.20-universal.jar
Log-Begone-Forge-1.20.1-1.0.8.jar
Mcw-paths-1.0.5-1.20.1forge.jar
Tectonic-forge-1.19.3-2.3.5a.jar
server-1.20.1-20230612.114412-srg.jar
Smoothchunk-1.20.1-3.6.jar
Voicechat-forge-1.20.1-2.5.19.jar
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar
Bettercombat-forge-1.8.4+1.20.1.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
ItemProductionLib-1.20.1-1.0.2a-all.jar
AdLods-1.20.1-8.1.2.0-build.0424.jar
spectrelib-forge-0.13.15+1.20.1.jar
kffmod-4.11.0.jar
flywheel-forge-1.20.1-0.6.10-7.jar
Gravestone-forge-1.20.1-1.0.17.jar
Polymorph-forge-0.49.5+1.20.1.jar
Multibeds-forge-1.20.1-1.1.jar
LeaveMyBarsAlone-v8.0.0-1.20.1-Forge.jar
FastFurnace-1.20.1-8.0.1.jar
Oceansdelight-1.0.2-1.20.jar
PuzzlesLib-v8.1.21-1.20.1-Forge.jar
Valkyrienskies-120-2.3.0-beta.5.jar
Cosmeticarmorreworked-1.20.1-v1a.jar
Chunksending-1.20.1-2.8.jar
Fruitsdelight-1.0.8.jar
Rsrequestify-1.20.1-2.3.3.jar
SkyVillages-1.0.3-1.19.2-1.20.x-forge-release.jar
kuma-api-forge-20.1.8+1.20.1.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
Netherportalfix-forge-1.20-13.0.1.jar
AdvancedPeripherals-1.20.1-0.7.38r.jar
Geckolib-forge-1.20.1-4.4.7.jar
Ars_nouveau-1.20.1-4.12.3-all.jar
Recipeessentials-1.20.1-3.5.jar
AdditionalBanners-Forge-1.20.1-14.0.4.jar
Naturalist-forge-4.0.3-1.20.1.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
Connectivity-1.20.1-5.6.jar
Sophisticatedcore-1.20.1-0.6.22.611.jar
InsaneLib-1.13.2-mc1.20.1.jar
HorseExpert-v8.1.1-1.20.1-Forge.jar
Structureessentials-1.20.1-3.4.jar
Eureka-1201-1.3.0-beta.4.jar
ritchiesprojectilelib-2.0.0-dev+mc.1.20.1-forge.jar
Placebo-1.20.1-8.6.2.jar
Jumpoverfences-forge-1.20.1-1.3.1.jar
Citadel-2.5.4-1.20.1.jar
Alexsmobs-1.22.8.jar
Lootintegrations-1.20.1-3.4.jar
Newshieldvariants-merged-1.20.1-1.2.0.jar
mixinextras-forge-0.3.6.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
Sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
create_dragon_lib-1.20.1-1.4.2.jar
Mcw-doors-1.1.1forge-mc1.20.1.jar
Steam_Rails-1.6.4+forge-mc1.20.1.jar
Interiors-0.5.2+mc1.20.1-FORGE.jar
Dummmmmmy-1.20-1.8.14.jar
Twilightforest-1.20.1-4.3.2508-universal.jar
DynamicTreesTheTwilightForest-1.20.1-2.2.0-BETA2.jar
Minecraftdungeonsv1-7.0.2 1.20.1.jar
Dsbg-1.0-1.20.1.jar
ArcaneLanterns-v8.0.0-1.20.1-Forge.jar
Create_connected-0.8.2-mc1.20.1-all.jar
Mcw-bridges-3.0.0-mc1.20.1forge.jar
FarmersDelight-1.20.1-1.2.4.jar
Cuisinedelight-1.1.14.jar
Ends_delight-1.20.1-2.4.jar
Rebornstorage-1.20.1-5.0.7.jar
Customizableelytra-forge-2.1.1+1.20.jar
Jearchaeology-1.20.1-1.0.3.jar
Endrem_forge-5.2.3-R-1.20.X.jar
Chunky-1.3.146.jar
Mcw-fences-1.1.2-mc1.20.1forge.jar
L_Enders_Cataclysm-1.90+-1.20.1.jar
Patchouli-1.20.1-84-FORGE.jar
Suppsquared-1.20-1.1.14.jar
Collective-1.20.1-7.75.jar
Camera-forge-1.20.1-1.0.12.jar
Witherstormmod-1.20.1-4.1-all.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
Createliquidfuel-2.1.1-1.20.1.jar
Twilightdelight-2.0.12.jar
Architectury-9.2.14-forge.jar
Allthetrims-3.4.3-forge+1.20.1.jar
Identity-2.7.1-1.20.1-forge.jar
Cc-tweaked-1.20.1-forge-1.111.0.jar
Cupboard-1.20.1-2.7.jar
Productivebees-1.20.1-12.6.0.jar
The_bumblezone-7.4.13+1.20.1-forge.jar
Monolib-forge-1.20.1-1.0.0.jar
CosmeticArmours - 1.4.0.0 - 1.20.1 - Forge.jar
Toomanyglyphs-1.20.1-2.3.2.12345.jar
Amendments-1.20-1.2.8.jar
Sophisticatedstorage-1.20.1-0.10.25.804.jar
Limitedchunks-1.20.1-3.9.jar
Copycats-2.0.4+mc.1.20.1-forge.jar
productivelib-1.20.1-0.0.4.jar
Platforms-forge-1.20.1-1.1.jar
Tacz-1.20.1-1.0.2-release.jar
Map_atlases-1.20-6.0.7.jar
Waystones-forge-1.20-14.1.4.jar
Mcw-paintings-1.0.5-1.20.1forge.jar
DynamicTreesArsNouveau-1.20.1-1.2.0.jar
Clumps-forge-1.20.1-12.0.0.4.jar
Hiddennames-1.20.1-1.0.3.jar
crackerslib-forge-1.20.1-0.3.2.1.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
Terralith_1.20.x_v2.5.4.jar
DynamicTreesTerralith-1.20.1-1.2.1.jar
Morevanillashields-1.1.0-1.20.1.jar
Moderntrainparts-0.1.7-forge-mc1.20.1-cr0.5.1.f.ja
Create-1.20.1-0.5.1.f.jar
CreateCasing-1.20.1-1.6.1.jar
Create_central_kitchen-1.20.1-for-create-0.5.1.f-1
Clockwork-1.20.1-0.1.16-forge-b3b22e39fe.jar
Trackwork-1.20.1-1.0.1-beta.jar
Extendedgears-2.1.1-1.20.1-0.5.1.f-forge.jar
CutThrough-v8.0.2-1.20.1-Forge.jar
Tfmg-0.9.0d-1.20.1.jar
Elytratrims-forge-3.4.3+1.20.1.jar
Moonlight-1.20-2.12.9-forge.jar
mixinsquared-forge-0.1.2-beta.4.jar
Jade-1.20.1-forge-11.8.0.jar
Another_furniture-forge-1.20.1-3.0.1.jar
CreativeCore_FORGE_v2.11.33_mc1.20.1.jar
Nethersdelight-1.20.1-4.0.jar
PassiveSkillTree-1.20.1-BETA-0.6.13a-all.jar
Justplayerheads-1.20.1-3.3.jar
Create_interactive-1201-forge-1.0.2-beta.1.jar
FastWorkbench-1.20.1-8.0.2.jar
ParCool-1.20.1-3.2.0.1-R.jar
Ars_elemental-1.20.1-0.6.4.1.jar
Immersive_paintings-0.6.7+1.20.1-forge.jar
Statues-1.20.1-0.4.0.5.jar
Miners_delight-1.20.1-1.2.3.jar
Delightful-1.20.1-3.5.9.jar
Ars_instrumentum-1.20.1-4.1.0.jar
Rsinsertexportupgrade-1.20.1-1.3.jar
MEED-1.20.1-4.7.jar
BetterTridents-v8.0.1-1.20.1-Forge.jar
Alexsdelight-1.5.jar
Charmofundying-forge-6.4.5+1.20.1.jar
Refinedstorageaddons-0.10.0.jar
Refinedpolymorph-0.1.1-1.20.1.jar
Chisels-and-bits-forge-1.4.148.jar
Create_enchantment_industry-1.20.1-for-create-0.5.jar
Createaddition-1.20.1-1.2.4d.jar
[crash-2024-08-17_17.30.16-server.txt](https://github.com/user-attachments/files/16790029/crash-2024-08-17_17.30.16-server.txt)

**Comment by watersofnazareth** [comment]
Your server is hitting it's tick limit which is why it's crashing

**Comment by watersofnazareth** [comment]
Closing since this isn't a true crash
