### ISSUE TITLE
[Bug]: Tainted dust is consdered a rare item while tainted dust lamps aren't

### ISSUE THREAD

**Issue by WitherInSuit** [nonamecrackers2/crackers-wither-storm-mod#2172]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.7

### Describe the bug

Tainted dust is rare, but the block made of 4 tainted dust is common

### Steps to Reproduce

look at their names! One is yellow whilst the other is white!

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

CWSM

**Comment by BluePineappleGuy** [comment]
Absolutely unplayable. I cannot open up the mod until this is fixed.

**Comment by watersofnazareth** [comment]
Fixed
