### ISSUE TITLE
The Withered Beacon:

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2173]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Instead of right clicking it with a wither skull to resummon a wither storm , it opens a GUI where u have to put the 3 skulls  in there places (3 soul sand blocks and command block will be already put)
Sth like that
![Screenshot_20240831_002445_Minecraft](https://github.com/user-attachments/assets/b0b0eabc-1205-40f5-a73a-b274a28e1bd2)

**Comment by watersofnazareth** [comment]
The reason the beacon is how it is is for simplicity as well as automation, we won't be changing it's GUI since there's no issue with it currently

**Comment by YassinAlaa** [comment]
> The reason the beacon is how it is is for simplicity as well as automation, we won't be changing it's GUI since there's no issue with it currently

ok whatever😅🙂
