### ISSUE TITLE
Super TNT:

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2174]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Why use a command block book to make a Super TNT?
Copper Takes Time to Oxidize and be oxidized copper
So similarly leave Normal TNT over Magma and it will eventually Magmatize into Super TNT , this way would save command block books and it will be a challenge for ppl but make the Magmatization time for TNT short

like that
![Screenshot_20240831_003600_Minecraft](https://github.com/user-attachments/assets/9a74a3e8-ccca-4f77-861e-abb3acb57815)

**Comment by TaintedBlock** [comment]
What..? Also, presuming you only play bedrock, Crackers does not develop the bedrock port. Therefore this is irrelevant.

**Comment by YassinAlaa** [comment]
> What..? Also, presuming you only play bedrock, Crackers does not develop the bedrock port. Therefore this is irrelevant.

I know but i am not talking about bedrock now, i am talking about the idea itself... (keep in mind that this is my own idea and it isn't in the bedrock port)

**Comment by watersofnazareth** [comment]
This doesn't fit the theme of the mod plus leaving an explosive on magma doesn't sound too intuitive
