### ISSUE TITLE
The Withered Beacon 2:

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2175]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The fight against the wither storm is epic and hard so it should be rewarding and ofc it does it gives u the withered nether star which allows u to craft the withered beacon but why don't u increase its range 
Make it way more than 128blocks 
![Withered_beacon](https://github.com/user-attachments/assets/686d9cf2-f291-4cb5-96ce-8210a4aec4ac)

**Comment by TaintedBlock** [comment]
Each of the support beacons give you effects at an infinite distance depending on if you are in their direction

**Comment by watersofnazareth** [comment]
As tainted said the support beacons stretch infinitely
