### ISSUE TITLE
Effects

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2177]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the witherstorm storm causes u wither sickness, it will cause the nausea too (but not for too long)
 the timing depend on the diffculty

**Comment by watersofnazareth** [comment]
This would be a lot more annoying than anything I doubt someone that's playing through the game would want to have a green tint or screen spinning constantly
