### ISSUE TITLE
Wither Storm disappearing

### ISSUE THREAD

**Issue by LordSilverX** [nonamecrackers2/crackers-wither-storm-mod#218]
So i played with a friend in a Aternos server in 1.16.5, with the latext version of mod, we logged off and come back some hours later, the boss just....disappear with no trace. where we were we can see him but now there's nothing. Did i need to do something ?

**Comment by nonamecrackers2** [comment]
Shouldn't have disappeared. If you do "/witherstormmod chunks get" while in the overworld, what does it say?

**Comment by YenedeyEy** [comment]
This happened to me in singleplayer in 1.18.2. I wrote the command and it says this "Wither Storm mod has 0 chukns out of 0 forced chunk loaded" I just left the nether and it's gone

**Comment by 123justinnn123** [comment]
happened to me to i was about to go inside it i slept and it was gone

**Comment by LordSilverX** [comment]
> Shouldn't have disappeared. If you do "/witherstormmod chunks get" while in the overworld, what does it say?

it do nothing, the wither is gone.

**Comment by nonamecrackers2** [comment]
May be something with aternos however I'll take a look

**Comment by LordSilverX** [comment]
> May be something with aternos however I'll take a look

Thank you, btw you're mod is really cool and if you have free time, you can try to add some "details" to it.
And is there a command to have the Wither Storm grow faster ?

**Comment by nonamecrackers2** [comment]
Unable to reproduce. If you could find a way to reliably reproduce the issue that would be great. You can use the "/witherstormmod evolutionSpeed" command and set it below 1 to make it evolve quicker
