### ISSUE TITLE
[Suggestion]: Tractor Beam Mob Spinning

### ISSUE THREAD

**Issue by RealPenguinMonkey** [nonamecrackers2/crackers-wither-storm-mod#2180]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the Wither Storm picks up a mob, the mob should slowly spin in a random direction. I think this would help make the Wither Storm's Tractor Beams seem like more of a threat!

**Comment by TaintedBlock** [comment]
duplicate of https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1055

**Comment by Herobrine982950291** [comment]
#1055

**Comment by RealPenguinMonkey** [comment]
oh i didnt know lol sorry
