### ISSUE TITLE
Related to wither sickness and tainted blocks...

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2182]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

+ Walking on tainted blocks slows u (just like soul sand) but u can't walk faster by adding an enchantment (like soul speed) so it will be one if the block characteristics 
this will fit the suggestion #2134 
+ Also staying on tainted blocks for a long time gives u wither sickness or elongate the wither sickness time
Thanks for reading❤️😀

**Comment by GearsawStudios** [comment]
Wither sickness already has infinite duration and this would mean that you could get the sickness with no means of curing it post Wither Storm.

**Comment by YassinAlaa** [comment]
> Wither sickness already has infinite duration and this would mean that you could get the sickness with no means of curing it post Wither Storm.

ok😅 i thought it had duration.. ok but it will still add the wither sickness (just if u walk on these blocks for a long time)

**Comment by watersofnazareth** [comment]
This would end up just making the playing experience worse and as Gearsaw said, Wither Sickness lasts infinitely and through death
