### ISSUE TITLE
[Suggestion]: Alternate way to summon the storm in existing worlds (with no cheats) (read desc)

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2184]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Is it possible to spawn the house in existing worlds? I'm doing a Minecraft survival without the mod, and once the mod updates, I will have no idea how to spawn it without the house.

**Comment by TaintedBlock** [comment]
You should ask questions in the discord. But no, there is no way to spawn it unless you're able to make a command block with other mods.

**Comment by Herobrine982950291** [comment]
that's why i'm suggesting it.

**Comment by nonamecrackers2** [comment]
You worded it as a question. While in the 0 ~ 0 chunk, use the place command to spawn the structure. It's only intended for the mod to be played on new worlds with the mod installed so the structure can generate, an alternative way to spawn it will not be added.

**Comment by Herobrine982950291** [comment]
Welp, ig my ENTIRE SURVIVAL WORLD WITHOUT CHEATS is pointless/useless. haha! Wooooooo! Fun!!!!!!!!!!!!!!! *giggle* ugh.

**Comment by TaintedBlock** [comment]
> Welp, ig my ENTIRE SURVIVAL WORLD WITHOUT CHEATS is pointless/useless. haha! Wooooooo! Fun!!!!!!!!!!!!!!! _giggle_ ugh.

..or just install a mod that allows you to craft a command block?

**Comment by BluePineappleGuy** [comment]
> Welp, ig my ENTIRE SURVIVAL WORLD WITHOUT CHEATS is pointless/useless. haha! Wooooooo! Fun!!!!!!!!!!!!!!! _giggle_ ugh.

open to LAN, enable cheats, and create a command block.

**Comment by Herobrine982950291** [comment]
I don't like using Cheats in a survival world, makes me feel like a cheater, and then... someone close to me will call me a noob.

**Comment by pinkygrocket** [comment]
The Wither Storm can be summoned using mob summoning methods from other mods if you're willing to customize your pack (I'm personally using Create Mechanical Spawner). But for out-of-the-box Wither Storm in an existing world, you'll need to use cheats.

**Comment by BluePineappleGuy** [comment]
> I don't like using Cheats in a survival world, makes me feel like a cheater, and then... someone close to me will call me a noob.

You're not a noob if there wasn't another way to do it. Which there isn't, so its fine here. You can even relog after creating the spawn structure so cheats will disable again.

**Comment by Herobrine982950291** [comment]
ok. Thanks for the new tip, User BluePineappleGuy.
