### ISSUE TITLE
Mobs Running?!

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2186]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Like the mobs run from a player when hit, it can also try to run from the wither storm before being sickened
edit : they dont run while i am playing !!!

**Comment by TaintedBlock** [comment]
have you ever played the mod before

**Comment by Infinitekaosv3** [comment]
i can already tell you havent played the mod before

**Comment by Pandaboi25x** [comment]
im pretty sure they have bedrock edition and it prob doesnt have mob running

**Comment by YassinAlaa** [comment]
> i can already tell you havent played the mod before

 Well they don't run!!!!! Is this a bug or what??

**Comment by YassinAlaa** [comment]
> im pretty sure they have bedrock edition and it prob doesnt have mob running

I have java on my lenovo laptop (i dont play much) and Well they don't run!!!!! Is this a bug or what??

**Comment by YassinAlaa** [comment]
> have you ever played the mod before

Well they don't run!!!!! Is this a bug or what??
