### ISSUE TITLE
[Suggestion]: really stupid symbiont spell

### ISSUE THREAD

**Issue by WitherInSuit** [nonamecrackers2/crackers-wither-storm-mod#2187]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

This is going to be really dumb, but instead of the pull spell just requiring the player to walk backwards or shift on a block, what if it was similar to Minecraft story mode, in which a random key would be selected and the player would have to mash that key to escape from the symbionts hold. During this time the players movement abilities would be reduced, and if they don’t escape the grasp, they would be repeatedly attacked by the symbiont until the spell ends or they die.

they let me cook, and I made a stale turkey sandwich with turkey, bread, and nothing else :|

**Comment by TaintedBlock** [comment]
This just sounds really annoying and not fun to go through ngl.

**Comment by GearsawStudios** [comment]
If it wasn’t a good idea, why suggest it?

**Comment by WitherInSuit** [comment]
Idk I thought it would be funny

**Comment by nonamecrackers2** [comment]
This probably wouldn't really fit in with the mod all that much, it's a real time first person game not really a step-by-step point and click story game. Thanks for your suggestion though.
