### ISSUE TITLE
New Sickened Mobs (pls read till the end)

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2189]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

What about adding a sickened version of the MCSM?! This will be really great and exclusive to the mod! like sickened creeder or sickened ender creeper like smth exclusive!! If that is related to the sickened mobs mentioned in the guidelines then i apologise 
Clarification: I dont mean the u put all story mode mobs but put some exclusive mobs to the mod i am not talking about withered symbiont) + these exclusive mobs will only spawn in the bowels
like this for ex
![Creeder](https://github.com/user-attachments/assets/865f4b02-1065-46aa-859e-707104128009)
![IcyEnderCreeper](https://github.com/user-attachments/assets/b5e883f1-16bb-488f-a0cc-298087604ce8)

**Comment by GearsawStudios** [comment]
This breaks both the sickened mob and no story mode rules.

**Comment by TaintedBlock** [comment]
You did not read the guidelines

**Comment by YassinAlaa** [comment]
> You did not read the guidelines

Well i read it read my issue again!! i didn't talk about sickened variants of current mobs i am talkin about smth else 
MCSW didn't have the sickened variants of mobs i mentioned

**Comment by GearsawStudios** [comment]
MCSW themed suggestions are prohibited and the sickened mobs clause states "More sickened mobs (they will be added as they are added)" which means sickened mobs of _any_ type, regardless if they even exist.

**Comment by YassinAlaa** [comment]
> MCSW themed suggestions are prohibited and the sickened mobs clause states "More sickened mobs (they will be added as they are added)" which means sickened mobs of _any_ type, regardless if they even exist.

i didn't know that mobs from MCSM are prohibted to suggest ! i thought only char and items

**Comment by TaintedBlock** [comment]
> > MCSW themed suggestions are prohibited and the sickened mobs clause states "More sickened mobs (they will be added as they are added)" which means sickened mobs of _any_ type, regardless if they even exist.
> 
> i didn't know that mobs from MCSM are prohibted to suggest ! i thought only char and items

You just proved you didn't read the guidelines 😭
