### ISSUE TITLE
Music Discs

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2190]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Idk how aren't there witherstorm themed music discs ? this witherstorm soundtrack is a very good sound for me ! 
Steps to get it:
Just from the bowels¡!

**Comment by watersofnazareth** [comment]
Please check other suggestions before opening one #1383 #1363

**Comment by YassinAlaa** [comment]
> Please check other suggestions before opening one #1383 #1363

Bro how would i know that there are other suggestions and i don't have time to search i just put my suggestion

**Comment by BluePineappleGuy** [comment]
> > Please check other suggestions before opening one #1383 #1363
> 
> Bro how would i know that there are other suggestions and i don't have time to search i just put my suggestion

There's this revolutionary technology known as search, you can use it to find such suggestions.

**Comment by YassinAlaa** [comment]
> > > Please check other suggestions before opening one #1383 #1363
> > 
> > 
> > Bro how would i know that there are other suggestions and i don't have time to search i just put my suggestion
> 
> There's this revolutionary technology known as search, you can use it to find such suggestions.

Well i do NOT have time!!

**Comment by TaintedBlock** [comment]
> > > > Please check other suggestions before opening one #1383 #1363
> > > 
> > > 
> > > Bro how would i know that there are other suggestions and i don't have time to search i just put my suggestion
> > 
> > 
> > There's this revolutionary technology known as search, you can use it to find such suggestions.
> 
> Well i do NOT have time!!

Well when you DO have time. Take the time to do so.
