### ISSUE TITLE
Withered Symbiont:

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2193]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Well i have thought of new powers for the withered symbiont:
+ Wind Charges : In 1.21 the breeze was introduced having the wind charges ability, it would be great if the Withered Symbiont can shoot wind charges at the player
+ Swap Positions : After certain number of attacks by withered symbiont, it is going to summon sickened mobs at his place and swap positions with the player (one of the players if it is multiplayer) making the player interupted willing to defend themselves and fight the sickened mobs [ This swap can be done by either a specific pearl (swap pearl for ex) or an in-game feature that can be disabled by commands ]

there will be other suggestions on improving the withered symbiont

**Comment by watersofnazareth** [comment]
Please don't open multiple issue like this, if you're going to make a suggestion for a single thing please include it in one, also a Wind Charge attack is already planned but we're not porting to 1.21 just yet, and the Swap Position would likely be too disorienting to a player and isn't something I want to look into adding, thank you for the suggestion though

**Comment by YassinAlaa** [comment]
> Please don't open multiple issue like this, if you're going to make a suggestion for a single thing please include it in one, also a Wind Charge attack is already planned but we're not porting to 1.21 just yet, and the Swap Position would likely be too disorienting to a player and isn't something I want to look into adding, thank you for the suggestion though

YW
+I don't think that swap positions is that bad it will be a nice addition to the game btw i didn't know u plan the wind charges one
@Thefuzz1234555
