### ISSUE TITLE
Withered Symbiont 2:

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2194]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Read this #2193 
Feature Request:
Instead of the Symbiont just appearing suddenly, it could be summoned in a more exciting way. For example, one of the Wither Storm's heads could shoot a special flaming skull that explodes when it hits the ground, bringing the Symbiont into the fight. At first, the Symbiont would be invincible for a short time, making the battle more intense and  interesting as it powers up before attacking.

**Comment by GearsawStudios** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/856 Dupe.
