### ISSUE TITLE
Withered Symbiont 3:

### ISSUE THREAD

**Issue by YassinAlaa** [nonamecrackers2/crackers-wither-storm-mod#2195]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Read this #2193 
and this #2194
Feature Request:
+ Potion Throwing: Such as Shulker bullets and Fireballs , the Withered Symbiont is going to spawn different harmful splashing/lingering potions and spin them in a circular orbit. One a time, it’ll shoot these potions at the player 

(Notice that if u tried to use these potions on the withered symbiont , they will strengthen it cuz harmful potion strength hostile mobs)

**Comment by GearsawStudios** [comment]
This already exists minus the mob buffing. Please don’t chain suggestions together and instead make one long one.

**Comment by YassinAlaa** [comment]
> This already exists minus the mob buffing. Please don’t chain suggestions together and instead make one long one.

I thought it's wrong to suggest more than a feature per issue that's why i separated them

**Comment by watersofnazareth** [comment]
This already exists in the mod as the Throwing spell but it doesn't buff Sickened Mobs nor is it planned to as they're already plenty strong enough

**Comment by BluePineappleGuy** [comment]
> > This already exists minus the mob buffing. Please don’t chain suggestions together and instead make one long one.
> 
> I thought it's wrong to suggest more than a feature per issue that's why i separated them

Yeah but don't make them in a series like "Withered symbiont 1, Withered symbiont 2", but instead try "Withered symbiont wind charge" and "Withered symbiont summoning"
