### ISSUE TITLE
[Suggestion]: A little mini game when your making the Formidi-Bomb when You craft it on the surface 

### ISSUE THREAD

**Issue by Theonewhodied** [nonamecrackers2/crackers-wither-storm-mod#2197]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

this is kinda will be similar to story mode and instead of grab gunpowder from the air you got to grab it in your inventory because the gunpowder and the super tnt will be randomly moved around you have to grab it and make it on the crafting table with your mouse

(this is to make it a bit more harder I did send this already not here but the plus resource pack so it just to make it harder)

**Comment by watersofnazareth** [comment]
This would just be too convoluted and out of the scope of the mod sorry
