### ISSUE TITLE
[Bug]: instant chomp lags game for a long time when killing player

### ISSUE THREAD

**Issue by kaboom24** [nonamecrackers2/crackers-wither-storm-mod#2198]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

I turned on instant chomp and whenever I get killed by the instant chomp the game lags for a really long time I can still move but everything is frozen and I cant use items and am stuck in flight since I am using an elytra when this happens (probably happens whether or not you have an elytra on but have not tested) then after a minute or two I finally die (ps elytra is not broken like the rest of my armor when insta-chomped)

### Steps to Reproduce

summon witherstorm
 turn on instant chomp in config
 set witherstorm to phase 4 or above (have not tested with phases 6-7)
 get chomped
 get lagged

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

clumps version 12.0.0.4.jar
just enough items (JEI) version 15.12.2.51.jar
just enough resource (JER) version 1.4.0.247.jar
waystones version 14.1.5.jar
crackers witherstorm plus version CWSPLUS resource pack v5.2.zip

(datapack for cwsplus not installed only resource pack)

**Comment by BluePineappleGuy** [comment]
Server side lag, or world lag, is what you are experiencing. Probably that how instant chomp works is very poorly optimized.

**Comment by nonamecrackers2** [comment]
Are you experiencing lag outside of being chomped? You can use "/forge tps" to check, the TPS should be at 20 and not below. If it's below you may in general be experiencing lag.

**Comment by Yuancheng124** [comment]
The length of the lag seems to be related to the amount of equipment you are wearing with the durability enchantment.

**Comment by Yuancheng124** [comment]
> Are you experiencing lag outside of being chomped? You can use "/forge tps" to check, the TPS should be at 20 and not below. If it's below you may in general be experiencing lag.

The length of the lag seems to be related to the amount of equipment you are wearing with the durability enchantment.

**Comment by nonamecrackers2** [comment]
Yeah I talked with Naza and that seems to be the case, will have to look into this further but overidding the armor check should do the trick.
