### ISSUE TITLE
Wither storm staying alive after boss fight and a kill comannd 

### ISSUE THREAD

**Issue by PijaniRus** [nonamecrackers2/crackers-wither-storm-mod#220]
Minecraft 1.18.2

Mod version 1.18.2

After killing the wither storm in survival it stayed alive and after using the kill command only the side withers died and the middle one is left alive ,after entering the command block fighting arena again there is no command block to be killed leaving the wither storm to follow without the possibility of being killed.

As usual i waited for it to reach phase 7 entered its bowels and destroyed the command block, after exiting i found it was still alive and didn't get killed even after the kill command.

1st picture after leaving boss
![SPAIN BUT WITHOUT THE S1](https://user-images.githubusercontent.com/109321510/179125752-77bdabeb-edfa-4dce-a909-b13be233faa0.png)
2nd picture is me going back to see if i can kill it again
![SPAIN BUT WITHOUT THE S2](https://user-images.githubusercontent.com/109321510/179125766-ab511e94-0b36-4bc6-89a7-81a8cec95874.png)
3rd picture is the middle wither storm staying alive after using kill commands
![AAAAAAAAAAAAAAAAAAAAAAAAAAAA](https://user-images.githubusercontent.com/109321510/179125784-225cecef-64da-4aa5-9d22-2e19f282514c.png)

**Comment by watersofnazareth** [comment]
Is it still moving around?

**Comment by PijaniRus** [comment]
yes its still following me and destroying the environment while killing mobs with its eye beams.

**Comment by watersofnazareth** [comment]
That is bizarre, what other mods are you using?

**Comment by PijaniRus** [comment]
Yea crackers asked me to send him the latest logs but i'm stupid and don't know where to send them on github

**Comment by watersofnazareth** [comment]
You can just drag and drop them into the message box

**Comment by PijaniRus** [comment]
this one or is there private ones?

**Comment by watersofnazareth** [comment]
Just the ones here, I'm unsure of any private thing with GH

**Comment by PijaniRus** [comment]
[latest wither storm mod conflict (maybe).txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9116890/latest.wither.storm.mod.conflict.maybe.txt)

**Comment by PijaniRus** [comment]
I'll put it here i hope it's good and thanks for help.

**Comment by nonamecrackers2** [comment]
What's your mod list?

**Comment by PijaniRus** [comment]
About to send it
![Screenshot (4)](https://user-images.githubusercontent.com/109321510/179128429-3f927f0f-39ea-47f0-8f1f-e5c7da36ef33.png)
Hope this is good
Sorry it took so long.

**Comment by PijaniRus** [comment]
I'm just going to add that after using the formidibomb on it, it Died?? its still there standing upright with its jaws all relaxed like the faking death animation but at least its not following me just to add that in case it is useful

![yay](https://user-images.githubusercontent.com/109321510/179134894-e0f8ca33-a591-42c2-918c-87063b97eb9a.png)

**Comment by nonamecrackers2** [comment]
I’m really not certain on what could be causing this. Can you reproduce this multiple times? If so, try removing max health fix, seems suspicious

**Comment by PijaniRus** [comment]
ok i have started a new world and its currently phase 4 maybe it was a one time thing then i will remove HP fix in a new world

**Comment by PijaniRus** [comment]
Ok so i have replicated it again now im going to make a new world without the max health fix mod

![again](https://user-images.githubusercontent.com/109321510/179416151-3d9d9371-58cd-49f5-82b2-6251419d10ec.png)

![the hell](https://user-images.githubusercontent.com/109321510/179416152-1d1a8374-9b39-4158-a924-43c068668721.png)

Latest log of replication, still have max heath fix mod, all the steps were the same as the first time.
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9128152/latest.log)

**Comment by PijaniRus** [comment]
Kill command showed death animation of side withers but this time they stayed alive

![2022-07-17_18 56 00](https://user-images.githubusercontent.com/109321510/179416510-51905c50-7287-49a2-9160-afd4497b4ea9.png)

![2022-07-17_18 56 02](https://user-images.githubusercontent.com/109321510/179416515-aaa546c7-141f-4674-87b4-dbbd2697974f.png)

![wee](https://user-images.githubusercontent.com/109321510/179416517-1924f7ad-056e-4d41-b997-60da243539d9.png)

**Comment by PijaniRus** [comment]
Formidibomb worked this time and i used it twice to get rid of the command block, so technically its dead but the boss bar is still there if you get close.

![ded](https://user-images.githubusercontent.com/109321510/179416796-5383a5c2-9315-41e8-bbe7-e995c424d94c.png)

![ded2](https://user-images.githubusercontent.com/109321510/179416800-2db9e929-f760-4c27-a7f8-c6b0470f7122.png)

**Comment by nonamecrackers2** [comment]
Wait so did you try without the max health mod? Also does this happen with any other entity?

**Comment by PijaniRus** [comment]
No i didn't yet, now I'm making a world without max health fix and no it seems everything else dies by kill command even the symbiote dies.

I tried to replicate to make sure it wasn't a one time thing so i did it with the mod again just posting everything that happens so not a single detail is missed.

To correct myself i made a new mod pack to make sure the first one isn't bugged or corrupted by any chance, i am using CurseForge

**Comment by PijaniRus** [comment]
Deleted because there is no delete button

**Comment by PijaniRus** [comment]
> Wait so did you try without the max health mod? Also does this happen with any other entity?

I'd like to report that the "Max Health Fix" mod was the problem the wither has been killed and i got the star without any problems.
I'm going to throw a wild guess that the mod somehow regenerated the withers HP or prevented it from dying in some way like it heals the player on gaining HP and entering the world while having increased HP.

Thank you for your patience Crackers and sorry if it made u worry too much.

![yess](https://user-images.githubusercontent.com/109321510/179421480-fbe079d7-3ab8-4bca-a204-cd27e9af230a.png)

![yess2](https://user-images.githubusercontent.com/109321510/179421482-3adb3c35-3a7d-480f-a0b3-c23106ff50af.png)

**Comment by nonamecrackers2** [comment]
Glad you got it figured out. I'll leave this open however because it may be something with my mod if other mobs are being killed.

**Comment by nonamecrackers2** [comment]
Fixed this issue, the fix will be available in the next 1.18/1.19 release
