### ISSUE TITLE
[Suggestion]: Spectator mode view

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2201]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Could be nice to add spectator mode support. Currently, when I look into the Wither Storm's POV, I get this:
![2024-09-08_18 50 46](https://github.com/user-attachments/assets/064ffb03-b448-473b-a3a0-498a34906877)
Maybe make me look through the vision of the middle Wither Storm Head, and add like a purple tint to the vision.

**Comment by watersofnazareth** [comment]
Well technically this is the view of the Wither Storm, the heads are separate to the actual body, and I'm not sure if we'd really be able to reposition the spectator camera

**Comment by Herobrine982950291** [comment]
or maybe add a spectator function for the heads...

**Comment by nonamecrackers2** [comment]
Going to echo what Naza mentioned. Adding proper support for spectator mode is kind of niche and is out of scope for the mod right now.

**Comment by Herobrine982950291** [comment]
I guess we are stuck with goofy ahh speccy mode.
