### ISSUE TITLE
Hola buenas 

### ISSUE THREAD

**Issue by Noajs41** [nonamecrackers2/crackers-wither-storm-mod#2203]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Yo quiero participar en todo

**Comment by Noajs41** [comment]
Holi

**Comment by Noajs41** [comment]
Hola buenas

**Comment by NinjaSam5399** [comment]
Sé que quieres participar, pero solo hablamos inglés. Entonces, ¿puedes utilizar un traductor?

**Comment by NinjaSam5399** [comment]
Idk if I'm minimodding.

**Comment by nonamecrackers2** [comment]
English only please
