### ISSUE TITLE
[Suggestion]: Make the Wither Storm and Withered Symbiont immune to Intimidation from Domestic Innovation

### ISSUE THREAD

**Issue by pinkygrocket** [nonamecrackers2/crackers-wither-storm-mod#2204]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Domestic Innovation is a mod that allows pets to gain special passive or active abilities by wearing enchanted collars. Intimidation is an enchantment that lets pets scare hostile mobs into fleeing, with the distance the mob will flee and frequency increasing with levels. However, there is no blacklist for the effect, making any hostile mob including the Wither Storm and the Withered Symbiont affected by Intimidation, which feels "out of theme" for this mod. I've confirmed this happens with the Withered Symbiont, but it doesn't occur with the Wither Storm.

Relevant issue from Domestic Innovation's repo: [[Suggestion] Add a tag to blacklist certain entities/mobs from being affected by Intimidation #220 ](https://github.com/AlexModGuy/DomesticationInnovation/issues/220)

**Comment by GrandmaPork** [comment]
this is an issue that only domestic innovation needs to solve

**Comment by pinkygrocket** [comment]
I asked cross-mod interactions over on the CWSM server and a moderator told me to file a suggestion report here as well, even though I already put in a suggestion on the Domestic Innovation side.

**Comment by nonamecrackers2** [comment]
I appreciate the report, and yeah in general it's a good idea to report to both ends. Though looking at this issue this would most likely be something that Domestic Innovation would need to fix, since I doubt I would be able to cleanly implement a fix for this myself.
