### ISSUE TITLE
[Suggestion]: Creepers blow off chunks of WS

### ISSUE THREAD

**Issue by Cod1ngGamer** [nonamecrackers2/crackers-wither-storm-mod#2206]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Pretty simple idea, when a creeper is sucked into the wither storm by a tractor beam, there's a chance that it explodes, blowing off small chunks of withered flesh and slightly reducing its "consumedEntities" value. Can be changed or disabled in the config, of course.

**Comment by watersofnazareth** [comment]
Well, funny thing is this will already be a 4.3 feature but won't change ConsumedEntities, so I'm going to give this the labels for 4.3 and close it
