### ISSUE TITLE
[Bug]: Tractor beam wont show when shaders enabled

### ISSUE THREAD

**Issue by Kskdo** [nonamecrackers2/crackers-wither-storm-mod#2210]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

Forge 47.3.5

### Describe the bug

I installed complementary shaders and when i turned it on, the tractor beam disappeared. It still functions, but its not there visually. Like the wither storm is looking at me and i am flying. No visual tractor beam. This isnt just for complementary shader, any shader i turn on makes the tractor beam disappear.

### Steps to Reproduce

Install Optifine
Install any shader
Turn it on
Dont see the tractor beam

### Crash Reports/Logs

It didnt crash

### Is OptiFine installed?

- [X] OptiFine is installed

### Screenhots

![image](https://github.com/user-attachments/assets/6bad2fd3-82bc-4ed0-8f0c-92eb9bc780bf)

### Mod List

CWSM and optifine

**Comment by GearsawStudios** [comment]
Optifine isn't supported.

**Comment by Kskdo** [comment]
oh ok. I will just use oculus then.
