### ISSUE TITLE
[Suggestion]: Block Cluster Interacting With Player

### ISSUE THREAD

**Issue by RealPenguinMonkey** [nonamecrackers2/crackers-wither-storm-mod#2211]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

If a player is on a block cluster that is getting pulled into the Wither Storm, instead of falling through it, it should bring the player with it, and the player has to jump off before getting pulled into the Wither Storm's grasp! Additionally, Block Clusters that are in the tractor beam can damage the player if not avoided! (Using my idea of swimming in the tractor beam!) 
This could be toggled through settings, and I think this would be a great addition to this already amazing mod!

**Comment by Cod1ngGamer** [comment]
This sounds amazing, but would probably require some kind of physics engine, like the one used in create interactive, and might be really laggy when combined with the WS

**Comment by Kskdo** [comment]
I had suggested this before and they said they wont add it.

**Comment by watersofnazareth** [comment]
#150, also, Clusters doing damage to players could be an issue since they go through walls
