### ISSUE TITLE
[Suggestion]: Custom Panorama: 1.21

### ISSUE THREAD

**Issue by Herobrine982950291** [nonamecrackers2/crackers-wither-storm-mod#2212]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

For the panorama, it would be cool to see Tractor beams in the Trial Chambers, or like block clusters. (or something else these are just my ideas)

**Comment by nonamecrackers2** [comment]
This would be something that will be to our discretion once we get to that version
