### ISSUE TITLE
[Suggestion]: New attacks for wither storm (like how it is in the game minecraft story mode) can yall read that

### ISSUE THREAD

**Issue by N0Sn1tching** [nonamecrackers2/crackers-wither-storm-mod#2218]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

(WITHER STORM AI): Can you make it so that wither storm can try to grab you from the nether portal with his tentacles like it would be so immersive. In Minecraft: Story Mode game, wither storm did this and it honestly would be great to have wither storm new attack moves that he can use like an realistic tentacle grabbing, i think this also was on mc story mode game. Like it would just squeeze the player in wither storms tentacle, and like new attack moves would be great generally, like attacks that are in mc story mode game on wither storm. And like more attacks too, i mean attacks that are in the mc story mode game and more :)

would make the mod much more immersive

because it would be so cool

(i just would love to see all the attacks that wither storm could do in the official game minecraft story mode in this mod)

**Comment by TSEG6** [comment]
This will never be added lol (also lol you **totally** read the guidelines)

**Comment by watersofnazareth** [comment]
Well I'm not on my PC and can't link the other github issues currently, this is a duplicate and violates the guidelines, sorry but this isn't going to be added

**Comment by Gubberball** [comment]
Nice job reading the guidelines
