### ISSUE TITLE
[Suggestion]:  Support command block book enchanted for more weapons in the original version

### ISSUE THREAD

**Issue by nmsl123467** [nonamecrackers2/crackers-wither-storm-mod#2219]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

For example netherite weapons, tools and trident.

**Comment by juanelgamer456** [comment]
bro didn't read the guidelines 😔 (he will be terminated)

**Comment by nmsl123467** [comment]
> bro didn't read the guidelines 😔 (he will be terminated)

Ok, this was my oversight, I've decided to close this question now
