### ISSUE TITLE
Wither Storm Segments Duplicating

### ISSUE THREAD

**Issue by SimpleWolf** [nonamecrackers2/crackers-wither-storm-mod#222]
**Minecraft version**
1.18.2

**Mod version**
2.0.1.2

**Describe the bug**
Wither Storm Segments Duplicated after Formidibomb. Server quickly began lagging after.

**To Reproduce**
Unknown, occured after Tier 5 Formidibomb.

**Crash Reports / Logs**
https://pastebin.com/YUau5JE2

Note: Server is Modded.

**Screenshots**
![2022-07-15_18 15 22](https://user-images.githubusercontent.com/30203908/179275079-38ce6faa-078d-4e92-b6b9-bfdf60dadf1d.png)
![2022-07-15_18 20 42](https://user-images.githubusercontent.com/30203908/179275861-c34d876c-de1f-4e0c-ad7b-597ac09f0956.png)

**Comment by nonamecrackers2** [comment]
Could you send over the list of mods?

**Comment by SimpleWolf** [comment]
Architectury API
Carry On
Comforts
Cracker's Wither Storm Mod
Create
Create Curios
CreativeCore
Curios API
Customizable Player Models
Flywheel
Gauges and Switches
GraveStone Mod
Just Enough Items
Mantle
PlayerRevive
Rhino
Sophisticated Backpacks
Sophisticated Core
Tinkers Construct
Torchmaster
GoblinTrader
YUNGAPI
Rubidium
OculusMC

**Comment by antivoid66** [comment]
holy

**Comment by SimpleWolf** [comment]
If anyone's curious, this is what it looks like now. Safe to say that it will dig you out if you stay underground.
(It has also reached Bedrock)
![2022-07-15_20 11 56](https://user-images.githubusercontent.com/30203908/179295205-9eae6bd3-11b2-4b50-9d1a-5eecc5dba740.png)
![2022-07-15_20 12 18](https://user-images.githubusercontent.com/30203908/179295243-060bdda1-506f-48dc-b736-dda47e1a2e0a.png)

**Comment by antivoid66** [comment]
wow i never seen anything like this

**Comment by SimpleWolf** [comment]
Update: There are now FIVE Wither Storm Segment
![2022-07-15_23 14 08](https://user-images.githubusercontent.com/30203908/179318012-905d2dfa-cd6d-42c6-baf1-d1ddd6f704b6.png)
s

**Comment by SimpleWolf** [comment]
Update 2: Killing the Wither again with a Formi will kill the two original Segments and Leave the duplicated ones alive.
![2022-07-15_23 21 31](https://user-images.githubusercontent.com/30203908/179318837-2750dcbb-1841-49b1-b965-fd14476bff50.png)

Also, another Segment appeared beforehand, something ain't right

**Comment by ShadeKage** [comment]
Ive seen this bug before on a youtube video doing this mod on a server, and they didnt have any mods besides this one (heres the vid https://www.youtube.com/watch?v=OI2G5eS_AMo)
Im to guess some heads from the wither storm desync from the main body, and the game spawns in more to replace the old ones, making the originals no longer part of the same body, and thus not be counted as the same
In the vid the issue also did start after the bomb was used, so maybe it going into block form than back out caused the issue? unsure about the true reason
P.S heres the time stamp for the video to the part with the bug being shown!! 46:52

**Comment by nonamecrackers2** [comment]
I understand the reason why it's happening, but not what is causing it, as this issue hasn't happened to me on my server and singleplayer tests/playthroughs. The segment system will probably need a rewrite.

**Comment by BD103** [comment]
I'm a bit late, but I used this command to kill a segment that's duplicated.

```
/kill @e[type=witherstormmod:wither_storm_segment,limit=1]
```

**Comment by watersofnazareth** [comment]
Fixed as of prerelease
