### ISSUE TITLE
[Suggestion]: Add Story Mode Clouds

### ISSUE THREAD

**Issue by SuperAndy135** [nonamecrackers2/crackers-wither-storm-mod#2221]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Add Story Mode clouds, as an addon or a setting, maybe a separate mod

**Comment by TaintedBlock** [comment]
I love when people refuse to read the guidelines!

**Comment by Laikagor** [comment]
read the guidelines
