### ISSUE TITLE
[Suggestion]: Tractor Beam Customization

### ISSUE THREAD

**Issue by Transient-ParadoX** [nonamecrackers2/crackers-wither-storm-mod#2223]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A config option called 'Beam Pull' which allows you to change the force of the Tractor Beam (pull force).

you could also edit this via a command, maybe looking like

/witherstormmod pullforce set <int-value>

or something like that. I feel like it would be cool to be able to change more things about the behaviour of the storm.

**Comment by TaintedBlock** [comment]
Already exist. I believe it's in the "tractor beam" part of the world config

**Comment by nonamecrackers2** [comment]
Yep, it's called "tractorPullSpeedModifier"
