### ISSUE TITLE
[Suggestion]: a world config resetting 

### ISSUE THREAD

**Issue by gamer69w** [nonamecrackers2/crackers-wither-storm-mod#2236]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When using the world config, make it so that it stays as the last customized preference instead of resetting it to the default so i can save time instead of wasting 5 minutes per world

**Comment by TSEG6** [comment]
There's literally a folder in .minecraft called defaultconfigs (or something like that) so just put your wither storm server config in there and it'll carry over to every world you make :)

**Comment by nonamecrackers2** [comment]
> There's literally a folder in .minecraft called defaultconfigs (or something like that) so just put your wither storm server config in there and it'll carry over to every world you make :)

This
