### ISSUE TITLE
[Bug]: Withered Symbiont Wont Take Damage at Half Health if The "Attackable When Not Vulnerable" Config is Enabled

### ISSUE THREAD

**Issue by MoistedPotatoes** [nonamecrackers2/crackers-wither-storm-mod#2237]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

4.2.1

### Describe the bug

the symbiont becomes invulnerable to any damage at half health when "attackable when not vulnerable" is enabled in the server config, im not sure why but it happens

### Steps to Reproduce

1. summon symbiont
2. enable "attackable when not vulnerable" in the server config
3. damage symbiont to half health
4. now when you try to attack it, it wont do any damage

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-10-13_13 01 23](https://github.com/user-attachments/assets/94efc76e-bc97-4b97-a468-7a72b6aecc81)

### Mod List

cwsm and cwsm v sides

**Comment by TaintedBlock** [comment]
This isn't a bug. The symbiont has to use an attack or power down I believe

**Comment by nonamecrackers2** [comment]
Yes, once it powers down and wakes up again you can hit it again
