### ISSUE TITLE
[Suggestion]: separate mod for the command block tools

### ISSUE THREAD

**Issue by Tobsike** [nonamecrackers2/crackers-wither-storm-mod#2238]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Make a separate mod for the command block tools (possibly in a fabric port)

**Comment by TaintedBlock** [comment]
Please add a suggestion name. Also, why would crackers make a separate mod for those??

**Comment by Tobsike** [comment]
Mainly i just want the models and the stats without the wither storm for less lag

**Comment by TaintedBlock** [comment]
> Mainly i just want the models and the stats without the wither storm for less lag

Then just.. don't spawn the wither storm..?

**Comment by pinkygrocket** [comment]
There are plenty of mods that add unbreakable tools and infinity+1 equipment. What separates CWSM's infinity+1 equipment from other mods is their integration into other aspects of the mod. It doesn't make much sense to separate CWSM's equipment from the rest of it.

**Comment by watersofnazareth** [comment]
Not planning on this
