### ISSUE TITLE
[Suggestion]: Ability to upload custom music as Witherstorm's theme

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#2241]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I've seen the original comment about music depending on the phase and I know it won't be possible to do such changes.

So I was thinking if it would be possible for you to allow users to upload their custom music to play during wither's presence.

Or at least an instruction on how to change the music file (I'm a noob at java coding)
I do not want to bother you guys, you've already made the best Minecraft mod I've ever seen.

**Comment by TaintedBlock** [comment]
You can do this with resource packs. Do some research on how to make one

**Comment by pinkygrocket** [comment]
The Minecraft Wiki has good resources on how to get started with resource packs:
* [Resource pack](https://minecraft.wiki/w/Resource_pack)
* [Tutorials/Creating a resource pack](https://minecraft.wiki/w/Tutorials/Creating_a_resource_pack)

**Comment by ghost** [comment]
Thanks 👍
