### ISSUE TITLE
[Bug]: Using the Flint and Steel on a Formidibomb when Quad is installed turns the Formidibomb into primed vanilla TNT

### ISSUE THREAD

**Issue by pinkygrocket** [nonamecrackers2/crackers-wither-storm-mod#2244]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.10

### Describe the bug

Manually lighting a Formidibomb with Flint and Steel spawns primed vanilla TNT, instead of shortening the existing fuse time. This forces the player to wait out the inventory fuse time.

### Steps to Reproduce

1. Place a Formidibomb in your inventory
2. Place the Formidibomb
3. Light it with Flint and Steel

### Crash Reports/Logs

https://mclo.gs/IhZkl9h

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

[modslist.txt](https://github.com/user-attachments/files/17427140/modslist.txt)

**Comment by FrozenDragon0** [comment]
With the amount of mods your using, good chance it's an incompatibility issue with something.

**Comment by pinkygrocket** [comment]
Probably, the pains of packdevving. I'm going to do a little bit of testing this morning; my guess is that it's Elytra Bombing or Forgery.

**Comment by nonamecrackers2** [comment]
Yeah check to see if you can find the mod/combination of mods if possible since that would help out a lot

**Comment by pinkygrocket** [comment]
I tracked it down to [Quad.](https://www.curseforge.com/minecraft/mc-mods/quad) It has a mixin related to TNT that is probably the root of the issue: https://github.com/LieOnLion/Quad/blob/forge%2B1.20.4/src/main/java/io/github/lieonlion/quad/mixin/TntBlockMixin.java

**Comment by nonamecrackers2** [comment]
Thanks! I will investigate this further

**Comment by Billnotic** [comment]
From my limited understanding of modding, it seems like the issue might be here
https://github.com/LieOnLion/Quad/blob/forge%2B1.20.4/src/main/java/io/github/lieonlion/quad/util/QuadUtil.java

AFAIK all Quad does is set the block's LIT state to true, so the issue likely lies with how CWSM handles the formidibomb lit state. I'll try forking quad and seeing if hardcoding a check for the formidibomb and using its different blockstates will fix anything.

**Comment by Billnotic** [comment]
https://discord.com/channels/987817685293355028/1297662936806068304/1297663287680565308

compiled a jar of quad that works with cwsm

**Comment by nonamecrackers2** [comment]
Yeah I forget how the Formidibomb works so I will have to investigate, thank you everyone for pointing out the problem

**Comment by lieonlion** [comment]
@nonamecrackers2 found the issue. It is due to Quad calling the `explode()` function when lighting the tnt, however forge decided to make it just set the block on fire, which calls the `wasExploded()` function in the tnt class, which im guessing the mod overrides the `wasExploded()` function but not `explode()`? I have a fix working and will upload a new version in 24-48 hours.

**Comment by lieonlion** [comment]
I have released a fix to the issue now with version 1.2.9.

[CurseForge](https://www.curseforge.com/minecraft/mc-mods/quad/files/5900857)
[Modrinth](https://modrinth.com/mod/quad/version/1.2.9+1.20.4-Forge)

**Comment by pinkygrocket** [comment]
Working with the latest version of Quad and CWSM installed together. Thanks everyone!

**Comment by nonamecrackers2** [comment]
Awesome!
