### ISSUE TITLE
[Suggestion]: Tainted Saplings

### ISSUE THREAD

**Issue by Dawylan2010** [nonamecrackers2/crackers-wither-storm-mod#2247]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Tainted Saplings that spawn Tainted Trees, maybe even Tainted Apples. That's all.

**Comment by watersofnazareth** [comment]
#1111 But thank you for reminding me to close that issue too

**Comment by Pandaboi25x** [comment]
exploding rn
