### ISSUE TITLE
[Suggestion]: Enchanted Golden Apple Stew

### ISSUE THREAD

**Issue by MoistedPotatoes** [nonamecrackers2/crackers-wither-storm-mod#2248]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

since golden apples have an enchanted counterpart, why not golden apple stew?

what i think enchanted golden apple stew should do:

be able to cure wither sickness much quicker than regular golden apple stew

give the same effects of a enchanted golden apple like golden apples with golden apple stew

crafting recipe:

enchanted golden apple (duh)

withered phlegm block

suspicious stew (regeneration specifically)

tainted mushroom

![enchanted_golden_apple_stew_crafting_recipe](https://github.com/user-attachments/assets/88ab17e2-5450-461b-8544-dd8985f5dd0f)

**Comment by watersofnazareth** [comment]
I like the thought of using Phlegm and this recipe for some reason needing a hopper and chest to be made

**Comment by MoistedPotatoes** [comment]
i mainly used the phlegm block for the slime-like appearance, it should probably be changed to tainted slime blocks if that gets added in evo part 2

**Comment by nonamecrackers2** [comment]
#1198
