### ISSUE TITLE
[Suggestion]: A new setting in the CWSM World options

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2250]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A option where you can make the skulls not break any blocks but only set things on fire ( would work really great with the " Burnt " Mod )
![image](https://github.com/user-attachments/assets/77e63d6b-bd86-46ca-9fef-f86f511e08aa)
![image](https://github.com/user-attachments/assets/e683a8d3-709b-469c-990b-0d85c3d33ae5)
The photos give a example of what the wither storm skulls would do if they only set things on fire instead of breaking blocks

**Comment by TaintedBlock** [comment]
Turning mob griefing off should do the trick

**Comment by Infinitekaosv3** [comment]
> Turning mob griefing off should do the trick

How?

**Comment by TaintedBlock** [comment]
> > Turning mob griefing off should do the trick
> 
> How?

Won't blow up anything but I believe will start a fire

**Comment by Composer-Hu** [comment]
If I recall correctly, WS will not absorb blocks when mob griefing turned off, this may not be what he wants.

**Comment by nonamecrackers2** [comment]
Mob griefing would probably be the best bet here, I don't see how adding a config option for this would be very useful

**Comment by SSgamingYT** [comment]
> Mob griefing would probably be the best bet here, I don't see how adding a config option for this would be very useful

Turning off mob griefing causes the storm to be unable to pick up blocks

**Comment by BluePineappleGuy** [comment]
maybe if it just created a sphere (the radius of which is the same as the
blast radius) and placed fire in every valid place within that sphere, that
could look very cool

also not obtainable of an effect in the mod currently
