### ISSUE TITLE
[Suggestion]: Distant yell sound when Bowels open in the distance

### ISSUE THREAD

**Issue by FatalERROR1234** [nonamecrackers2/crackers-wither-storm-mod#2253]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Hello. I would like to hear a Wither Storm distant yell sound when the Bowels open when faraway. I made this suggestion because I use a texture pack for the mod that makes it accurate to MCSM, and I can't tell whether the Storm is in Phase 7 or 7.5 when looking at it faraway.

**Comment by nonamecrackers2** [comment]
You should be able to see the bowels hole from a distance. Regardless I don't really want to add another distant sound for this, you're meant to be able to see from a distance if it is open or not.

**Comment by FatalERROR1234** [comment]
> You should be able to see the bowels hole from a distance. Regardless I don't really want to add another distant sound for this, you're meant to be able to see from a distance if it is open or not.

but I use a texture pack - LucasDotje's Accurate Story Mode Storm. I can't see the bowels then.

**Comment by FatalERROR1234** [comment]
so sorry
