### ISSUE TITLE
[Suggestion]: Simple Clouds-esk wither storm evolution 

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2255]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Ive noticed how the simple clouds have procedural generation to form, while still maintaining its intended general shape. Would this be usable for cwsm? The wither storm could be procedurally generated similarly to the clouds while keeping its original shape as it evolves to each phase, basically allowing for unique evolution each run of the mod. Also, each block/entity absorbed adds a block to the evolution. Placement of tentacles and such could be done by having them appear at the edge of the body closest to a set point, while still being attached to the body. (But not inside of it) This also allows for evolution "past" phase 7, but of course there could be an lod/limit to the maximum amount that the storm can grow to prevent lag. (Of course, looking at simple clouds, there could be a very large limit on the size of the storm without performance issues)

Note: this evolution is entirely client-side possible. To avoid having to move the heads, the general front shape of the body from phase 4 is maintained, while the back continues to grow. This prevents the need for moving heads around, which would force server-side effects.

**Comment by Arceus-77** [comment]
I like the idea of it getting bigger And BIGGER AND **BIGGER**

**Comment by IndigoAmethyst** [comment]
Honestly this would be very cool to add, however nearly impossible at the same time.

**Comment by SSgamingYT** [comment]
> Honestly this would be very cool to add, however nearly impossible at the same time.

Not exactly, as I explained how it could be possible. Simply just scale the cloud size down, give it it's shape, give it server-client communication (to detect consumed entities), have it grow depending on consumed entities, and bam, you have a procedural wither storm! (This is a very watered down explanation, as I don't know much about coding, but it's a place to start)

**Comment by BluePineappleGuy** [comment]
should probably have a config limit to allow procedural growth past stage
7, with a lag warning

**Comment by nonamecrackers2** [comment]
This is possible but difficult to maintain and support since if we go the compute shader route to generate such a mesh. I prefer having static models since it's less complicated and helps with identifying phases, so I'd rather not go this route. Thanks for the idea though.
