### ISSUE TITLE
[Bug]: The command block book will disappear when it comes into contact with large block clusters

### ISSUE THREAD

**Issue by nmsl123467** [nonamecrackers2/crackers-wither-storm-mod#2260]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.10

### Describe the bug

When I defeated the Wither Symbiont, the command block book that fell happened to be near a block cluster. The moment they came into contact, the command block book disappeared and did not appear in the backpack. The "Command block book automatically put into backpack" option in settings is turned on。

### Steps to Reproduce

1. Spawn wither storm
2. Spawn and defeat the wither symbiont
3. Let the command block book drop and wait for contact with block cluster
4. When the two touch, the command block book disappears

### Crash Reports/Logs

none

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

only CWSM

**Comment by watersofnazareth** [comment]
This will be fixed in the next update
