### ISSUE TITLE
[Suggestion]: the blocks shake before getting picked up 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2261]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Make it so the blocks start to shake before the get picked up in the tractor beam, ( also kinda how it works when the blocks particles  start to appear before getting picked up ) also put a example video to.

https://github.com/user-attachments/assets/c319bb88-fc8a-41b0-9ce5-6536635c89ce

**Comment by SSgamingYT** [comment]
Would be neat to see, but it would be very quick and subtle (small details are everything, please add this)

**Comment by Infinitekaosv3** [comment]
> Would be neat to see, but it would be very quick and subtle (small details are everything, please add this)

Yes I love small details, even tho you dont see it real quick, your still able to see it and gotta be there at the right time
