### ISSUE TITLE
[Suggestion]: Blocks that get picked up in Tractor beam spiral around it 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2264]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Blocks that get picked up in Tractor beam spiral around it 
Example Video: 
https://github.com/user-attachments/assets/738f462e-f1ba-4431-8f24-11ebc5cca495

**Comment by Infinitekaosv3** [comment]
and mobs get picked up as normal

**Comment by SSgamingYT** [comment]
Sadly I made this suggestion before and it was rejected. Who knows, maybe they'll reconsider

**Comment by Infinitekaosv3** [comment]
> Sadly I made this suggestion before and it was rejected. Who knows, maybe they'll reconsider

Oh alright

**Comment by watersofnazareth** [comment]
This would be too much to really look into doing and currently the clusters in the beam are fine
