### ISSUE TITLE
[Bug]: Orange Tractor Beam

### ISSUE THREAD

**Issue by LightningAnimates** [nonamecrackers2/crackers-wither-storm-mod#2266]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

So before this, the beam was purple and normal, but today, it became Orange!

### Steps to Reproduce

I have no idea

### Crash Reports/Logs

It's not a crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Minecraft_ Forge Loading  31 10 2024 12_10_57](https://github.com/user-attachments/assets/3d50a446-0553-4fad-904d-0e40373a25c9)

### Mod List

Only CWS

**Comment by Composer-Hu** [comment]
Just the halloween surprise, not a bug.

**Comment by LightningAnimates** [comment]
Oh
