### ISSUE TITLE
[Suggestion]: Make Sickened Iron golems stronger

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2267]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I spawned in 2 Sickened iron golems and the normal iron golem killed both of them, Also wouldnt the sickened be more stronger then the others?

**Comment by watersofnazareth** [comment]
This is intended as they'd be too overpowered for the player to fight with their increased movement speed, for example, if a tentacle grabs you in the bowels, you don't want to be one shot

**Comment by Infinitekaosv3** [comment]
> This is intended as they'd be too overpowered for the player to fight with their increased movement speed, for example, if a tentacle grabs you in the bowels, you don't want to be one shot

oh alright
