### ISSUE TITLE
[Suggestion]: Purple lightning strikes around the Wither Storm 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2269]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Phase 5 to Phase 7.5 there should be Purple lightning that strikes around the Wither Storm
Example:
https://github.com/user-attachments/assets/8a67c213-e9c4-46a1-9b90-4a2bd06861cd

**Comment by IndigoAmethyst** [comment]
I am guessing you mean Phase 7.5 not 8.5

**Comment by Infinitekaosv3** [comment]
> I am guessing you mean Phase 7.5 not 8.5

Yes sorry, lol

**Comment by watersofnazareth** [comment]
#1791

**Comment by llenderr** [comment]
That a flash glare not lightning

**Comment by nonamecrackers2** [comment]
#696
