### ISSUE TITLE
[Suggestion] Dynamic Music

### ISSUE THREAD

**Issue by Onemario1234** [nonamecrackers2/crackers-wither-storm-mod#227]
The boss music that plays from the Wither Storm should depend on the current phase, alongside your distance from the Wither Storm. Like, only playing the intro when it's getting closer, and playing the intense bits on loop when it's closer.

Dynamic music would also solve the problem with the music suddenly calming down even though you're still near the beast.

**Comment by nonamecrackers2** [comment]
While the dynamic music idea seems interesting, it'll mean splitting up the tracks into various different sections and would take extra work for something I don't think would be very noticeable. I will however add variations of the WS theme to the different major phase sections.

**Comment by Onemario1234** [comment]
Sounds good to me!

**Comment by Anth1121** [comment]
> While the dynamic music idea seems interesting, it'll mean splitting up the tracks into various different sections and would take extra work for something I don't think would be very noticeable. I will however add variations of the WS theme to the different major phase sections.

You can find the wither storm tracks all separated from the original game at khinsider.com. (https://downloads.khinsider.com/game-soundtracks/album/minecraft-story-mode-gamerip-2016)

**Comment by darkheart78** [comment]
bowels theme in bowels and the ramping up part when closer to the command block

**Comment by BluePineappleGuy** [comment]
> bowels theme in bowels and the ramping up part when closer to the command block

or the ramping up part in the bowels when the bossfight is active but not in the arena

**Comment by Steve982950** [comment]
is it true? is nonamecrackers2 gonna add the ''WitherStorm Rises'' as the main music for phases 6-7?

**Comment by BluePineappleGuy** [comment]
> is it true? is nonamecrackers2 gonna add the ''WitherStorm Rises'' as the main music for phases 6-7?

i think WS rises would be better for a theme when close to the dead wither storm to give a sense of foreboding.

**Comment by Steve982950** [comment]
will this issue(and other confirmed issues) be part of a potential 1.20 update?

**Comment by Steve982950** [comment]
> is it true? is nonamecrackers2 gonna add the ''WitherStorm Rises'' as the main music for phases 6-7?

Sorry I meant ''Is NNC2 gonna add the WitherStorm Theme 2 as the main music for phases 6-7?''

**Comment by nonamecrackers2** [comment]
More parts of the theme will be added in the next major release (depending on the phase, not worrying about distance).

**Comment by Herobrine982950291** [comment]
this was confirmed 2 years ago, yet still it's not in the game...

**Comment by BluePineappleGuy** [comment]
> this was confirmed 2 years ago, yet still it's not in the game...

it is, in a way. crackers fixed the music quality (which was potato at the time this issue was made) and added more of the WS theme into the mod.

**Comment by Herobrine982950291** [comment]
oh, great.

**Comment by WitherBean** [comment]
> this was confirmed 2 years ago, yet still it's not in the game...

It's coming in Evolution: 10,000,000

**Comment by Herobrine982950291** [comment]
> > this was confirmed 2 years ago, yet still it's not in the game...
> 
> *"It's coming in Evolution 10,000,000"*

**Comment by Linusintro** [comment]
This could be done in a similar way to [Decayed Reality](https://www.decayed-team.com/decayed-reality), where there is music playing when the Wither Storm is far away or when you hide in a cave. This music is less intense, but it still creates some tension and reminds you of the ongoing danger. For those who don't know, the addon has four of these themes: "Tension Far Blackhole", "Tension Far Cave", "Tension Far Night", "Tension Far Twisted Order".
