### ISSUE TITLE
[Suggestion]: Make the wither storm eat wither roses (item form)

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2271]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Wither roses tend to build up in item form during the early stages of the wither storm, which causes severe lag and in some cases crashes/tps drops.

This could be fixed by either making the wither storm eat wither roses in item form, or making the mobs it kills not drop wither roses at all.

**Comment by watersofnazareth** [comment]
Just remove it from the unappetizing tag?

**Comment by SSgamingYT** [comment]
> Just remove it from the unappetizing tag?

How do I do that?

**Comment by nonamecrackers2** [comment]
You need to make a datapack and override that item tag to remove wither roses. Wither roses are excluded and are dropped because they are used for golden apple stew and can be important.
