### ISSUE TITLE
[Suggestion]: Configurable Small Block grabbing distance

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2273]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The distance of which the wither storm can pull in small clusters (1 block clusters) could be configurable, with the reach being configurable for hunchback, standard, and devourer.

Allows for long range destruction, because who cares about performance

**Comment by watersofnazareth** [comment]
It's a bit too hard coded to allow this easily
