### ISSUE TITLE
[Suggestion]: Advancement: "Formidibomb Time! " 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2275]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Only one player in the entire MC world will get this advancement, you can get this advancement by lighting the Formidibomb Infront of the Wither Storm

**Comment by FatalERROR1234** [comment]
or how about when they craft the bomb itself... rename "F-Bomb" to "It's Formidibomb Time". that could be a good idea.

**Comment by nonamecrackers2** [comment]
This shouldn't be limited to one single person, otherwise other people would be unable to get all the advancements. Otherwise I don't think this is necessary since there are other advancements that fill this part of progression.
