### ISSUE TITLE
[Suggestion]: Make Villagers, Pillagers, Vindicators, Evokers, Hide under structures to prevent getting pulled into the Tractor Beam

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2276]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Sense hiding under a block prevents you from getting pulled into the Tractor beam, what if Villagers, Pillagers, Vindicators, Evokers Hide under blocks as well to not get pulled into the Tractor beam, And make the Witch drink an Invisibility potion to run away from the WS without getting caught

**Comment by SSgamingYT** [comment]
I like this idea, it makes the running away mechanic much more interesting than simply just running off randomly

**Comment by Composer-Hu** [comment]
And the witch?

**Comment by DrMalpracticewastaken** [comment]
> And the witch?

the witch should drink an invisibility potion

**Comment by pinkygrocket** [comment]
I think this feature should have an entity tag to apply this behavior if it gets implemented, e.g. `witherstormmod:runs_for_cover`

**Comment by Infinitekaosv3** [comment]
> > And the witch?
> 
> the witch should drink an invisibility potion

Thank for the Idea! i added that to the github

**Comment by watersofnazareth** [comment]
My only issue with this is it may be laggy, and usually mobs do end up hiding at structures but will run away when it's compromised

**Comment by Infinitekaosv3** [comment]
> My only issue with this is it may be laggy, and usually mobs do end up hiding at structures but will run away when it's compromised

Ohh alright
