### ISSUE TITLE
[Suggestion]: A New item/tool

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2278]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

This new item would allow you to right click on ANY Blocks ( Only blocks the WS can pick up ) and Highlight them, then make that block a targeted block which would make the WS try to grab it. 
Example: My friends base is underground, so I use the tool and right click the blocks above my friends base, then the WS would be able to try and grab those selected blocks 
This also doesnt have to be a survival item either, could only be for creative.

**Comment by SSgamingYT** [comment]
I feel like this could be an amulet staff or an amulet on a stick, maybe something like this in the crafting menu:

Beacon
Amulet
Stick

**Comment by Infinitekaosv3** [comment]
> I feel like this could be an amulet staff or an amulet on a stick, maybe something like this in the crafting menu:
> 
> Beacon Amulet Stick

I do actually like the amulet staff for the item

**Comment by BluePineappleGuy** [comment]
how about its a creative only thing because i don't really see any good
reason to have it in survival mode

**Comment by watersofnazareth** [comment]
While this is a neat idea, there's no practical reason for this to be added
