### ISSUE TITLE
[Suggestion]: 1.19.2- port of newer versions to 1.19.2

### ISSUE THREAD

**Issue by NetherDragon74** [nonamecrackers2/crackers-wither-storm-mod#2279]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I play in pretty much any version that has a cool mod, but right now I found a modpack I play on for 1.19.2, I installed the mod without realizing it was a relatively outdated versions, and although I could just change to 1.20.1, Most mods I currently have installed do not have a 1.20.1 version.

**Comment by SSgamingYT** [comment]
Sadly 1.19.2 updates are now unsupported. There are no plans for backporting, as nonamecrackers2 has made clear on the cf page and this GitHub page

**Comment by watersofnazareth** [comment]
Not worth the time or effort
