### ISSUE TITLE
[Suggestion] Dynamic Weather

### ISSUE THREAD

**Issue by Onemario1234** [nonamecrackers2/crackers-wither-storm-mod#228]
**Description of feature**
A config option that modifies the weather to change dynamically depending on the current Wither Storm Phase.

For example, Phase 0 to Phase 2 have no weather changes. Phase 3 to Phase 5 have permanent rain as long as you're in range. Phases 6 and 7 have a permanent thunderstorm.

The "range" would be the same range that decides when the boss bar and music show up.

**Comment by nonamecrackers2** [comment]
The weather in my opinion masks the Wither Storm with the rest of the sky and brings a less pleasurable viewing experience. Minecraft (to my knowledge) also currently doesn't support locational weather.

**Comment by Onemario1234** [comment]
It doesn't, true. Fair points.
