### ISSUE TITLE
[Suggestion]: Add suspense music and screen getting darker for Wither sickness

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2281]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When you get down to 1 heart due to Wither Sickness, play suspense music at 1:00 left, and make your screen get darker slowly
as you Wither away

**Comment by nonamecrackers2** [comment]
Don't feel this is entirely necessary, especially the music part. Doesn't seem to fit vanilla especially well in my opinion.
