### ISSUE TITLE
[Suggestion]: Items get picked up in tractor Beam

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2282]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When any Item gets inside of a tractor beam, it should get picked up along with the blocks.

**Comment by watersofnazareth** [comment]
Already planned #2000

**Comment by Infinitekaosv3** [comment]
> Already planned #2000

Oh alright👍
