### ISSUE TITLE
[Suggestion]: Pillager and snow golems shoot WS head

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2286]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When Pillagers and Snow Golems get picked up in TB, They could shoot the eye/head like skeletons do

**Comment by watersofnazareth** [comment]
Snow Golems shooting the heads has been implemented in the Dev environment, but Pillagers are a bit more tricky to get working and may never be added
