### ISSUE TITLE
[Suggestion]: "Splash Potion Of Wither Sickness" and "Potion of Wither Sickness"

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2287]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

New item called " Splash Potion Of Wither Sickness " when thrown on a mob they would get the wither sickness
And when a player drinks the potion they would get the sickness

**Comment by Gubberball** [comment]
What would it be brewed with?

**Comment by watersofnazareth** [comment]
Wither Sickness as a potion isn't planned and will likely never be added since the Wither Storm + Command Block is meant to be the source
