### ISSUE TITLE
Suggestion: Make TNT able to stun a wither storm head if the explosion is close enough to the head

### ISSUE THREAD

**Issue by RefrigeraterReal** [nonamecrackers2/crackers-wither-storm-mod#229]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**Comment by nonamecrackers2** [comment]
My only question is how would you be able to ignite and bring the tnt that close to it's head in survival?

**Comment by RefrigeraterReal** [comment]
Maybe make it take longer to ignite while it's in the tractor beam

**Comment by ShadeKage** [comment]
Yea, valid point, just set the fuse timer to be way massive when its in a tractor beam and then set it to 0 once tis close to the head, could act as a even more effective distraction
