### ISSUE TITLE
[Suggestion]: A option to disable the Firework Bundle from disappearing after being used

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2290]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A option to disable the Firework Bundle from disappearing after being used, I only wanted this because Im doing a redstone thingy with them and dont wanna keep replacing them everytime I use the redstone

**Comment by pinkygrocket** [comment]
A CraftTweaker script could do this (listen to RightClickBlockEvent and NeighborNotifyBlockEvent and replace the firework bundle with a firework bundle when the events fire)

**Comment by watersofnazareth** [comment]
It'd be a neat idea to eventually add an upgraded version of the firework launcher, using bowels materials, that doesn't get used and instead uses redstone pulses to fire rockets

**Comment by Infinitekaosv3** [comment]
> It'd be a neat idea to eventually add an upgraded version of the firework launcher, using bowels materials, that doesn't get used and instead uses redstone pulses to fire rockets

Id love that idea

**Comment by nonamecrackers2** [comment]
They disappear because otherwise you could just keep using them over and over again. A config option for this probably wouldn't be more beneficial then the work to add one, so think of it as a redstone engineering challenge to work around.
