### ISSUE TITLE
[Suggestion]: More Game Versions

### ISSUE THREAD

**Issue by niki142009** [nonamecrackers2/crackers-wither-storm-mod#2294]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Plsss more game versions, so for 1.20.2 and so on

**Comment by Composer-Hu** [comment]
Please wait patiently, they're on their way.

**Comment by watersofnazareth** [comment]
Why would we port to 1.20.2..?
1.21 is being worked on but it's taking a while, also please don't make issues like this we'll get to it when when get to it
