### ISSUE TITLE
fabulous graphics bug

### ISSUE THREAD

**Issue by jasongi33** [nonamecrackers2/crackers-wither-storm-mod#230]
**Minecraft version**
1.18.2

**Mod version**
1.18.2

**Describe the bug**
when on fabulous graphics the wither storms tractor beams do not render and if its raining the chunks will be blackish and rain will appear over them making it look odd

**To Reproduce**
1. Go to settings and put graphics on fabulous.
2. summon witherstorm
3. set to phase 3-7

**Screenshots**
![2022-07-16_16 25 35](https://user-images.githubusercontent.com/109427860/179361472-ebd0d557-03dd-48a2-a807-93bf1affc49d.png)
![2022-07-16_16 25 35](https://user-images.githubusercontent.com/109427860/179361497-4cb93205-eab3-4750-a9ec-24f6d04ff8ff.png)

**Comment by jasongi33** [comment]
i just noticed that fabulous graphics breaks more than just the tractor beams rendering it also breaks the cloud effects and the distant renderer i can send a screenshot if needed

**Comment by nonamecrackers2** [comment]
I'm unable to find a proper fix for this. This seems almost like an issue with forge or an issue with how the ordering of rendering works when using fabulous.
