### ISSUE TITLE
[Suggestion]: Wither storm feature when all 3 eye's are broken

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2304]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When all the 3 eyes on the WS are broken, the WS should randomly start moving around and turning around because it cant see, when one of the eye's comes back it turns back around towards the player.

**Comment by nonamecrackers2** [comment]
This would only be for a short period of time, so it wouldn't be a very noticeable effect, especially for the effort to implement this
