### ISSUE TITLE
[Suggestion]: monsters nearby new message when the WS is nearby

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2307]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When you try to sleep a New monsters nearby message pops up when the WS is above you or near you

Message: " You may not rest now, The Wither Storm is nearby "

**Comment by nonamecrackers2** [comment]
#2057
