### ISSUE TITLE
[Suggestion]: New config 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2308]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A config you can turn on to make the Wither storm ignore you and not pick you up or shoot skulls at you **during before phase 4**, to make it look like the WS is more focused on growing then killing

**Comment by TaintedBlock** [comment]
Turn player pick up chance to 0

**Comment by Infinitekaosv3** [comment]
> Turn player pick up chance to 0

doesnt that effect the other phases to?

**Comment by TaintedBlock** [comment]
Ah well, true. But you could always set it back I guess. Or datapack it, lol. It would actually be really easy

**Comment by ShadowmeC3** [comment]
Adding onto this, I think it would be cool for there to be a config for the wither storm to not prioritize you over other mobs. And a config for the wither storm to not know where you are at all times, unless you have the amulet. I think this would be cool for role playing if you don’t want to be the main character all the time lol.

**Comment by TaintedBlock** [comment]
> Adding onto this, I think it would be cool for there to be a config for the wither storm to not prioritize you over other mobs. And a config for the wither storm to not know where you are at all times, unless you have the amulet. I think this would be cool for role playing if you don’t want to be the main character all the time lol.

Setting it's ultimate target to something like 'NONE' or 'RANDOM STROLL' will stop it from following you. And again, changing pickup chances lower or to 0 will cause it to go for mobs rather than players

**Comment by nonamecrackers2** [comment]
This is really specific and niche and I don't think this would see much use by most users to justify adding this.
