### ISSUE TITLE
Game Crashing Upon Joining a Server, but only sometimes.

### ISSUE THREAD

**Issue by TallChest15** [nonamecrackers2/crackers-wither-storm-mod#231]
**Minecraft version**
1.16.5

**Mod version**
1.0.2.4

**Describe the bug**
It crashes, most commonly after a skybox-colored screen with no crosshair. The crash log says the reason is something about wither sickness. This is random, and you CAN still play normally if you're persistent enough to keep trying until it works.

**To Reproduce**
1. Open your game with the mod
2. Join a server with the mod installed
3. If you're unlucky, the game will crash.

**Comment by nonamecrackers2** [comment]
Could you send the crash report?

**Comment by nonamecrackers2** [comment]
Think the issue is related to #240
