### ISSUE TITLE
[Bug]: Fog is green in the Bowels.

### ISSUE THREAD

**Issue by Jouto25** [nonamecrackers2/crackers-wither-storm-mod#2311]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.12

### Describe the bug

I went to have some fun in a playground world, and when I entered the Bowels, the fog color is green. I'm unsure if this is due to a mod I had in my mod list, or something in the mod itself.

### Steps to Reproduce

Go to the Bowels with the mod list mentioned.

### Crash Reports/Logs

https://file.garden/ZxRmhi1I1XGt8AYE/bowelslogs.txt

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot 2024-11-16 220907](https://github.com/user-attachments/assets/7baf9c86-1b3a-4bf4-90c2-8212cda61a78)
![Screenshot 2024-11-16 220922](https://github.com/user-attachments/assets/7dc01f21-651d-49a9-9f37-8fff4a204bb3)

### Mod List

https://files.catbox.moe/jed1ac.7z

  [✔] AchievementOptimizer-1.20.1-1.0.5
  [✔] AdvancementPlaques-1.20.1-forge-1.6.7
  [✔] alexsmobs-1.22.9
  [✔] almanac-1.20.x-forge-1.0.2
  [✔] alternate_current-mc1.20-1.7.0
  [✔] alternategunpowder-1.0.0-1.20.1
  [✔] AmbientEnvironment-forge-1.20.1-11.0.0.1
  [✔] amendments-1.20-1.2.12
  [✔] amethyst-cutting-1.0
  [✔] Amplified_Nether_1.20.x_v1.2.5
  [✔] Animation_Overhaul-forge-1.20.x-1.3.1
  [✔] antiportals-mc1.20.1-1.3
  [✔] appleskin-forge-mc1.20.1-2.5.1
  [✔] architectury-9.2.14-forge
  [✔] ArmorUnlocked-1.20-1.0.2
  [✔] artifacts-forge-9.5.13
  [✔] autohud-6.3.7+1.20.1-forge
  [✔] AxesAreWeapons-1.7.3-forge-1.20.2
  [✔] BadMobs-1.20.1-19.0.4
  [✔] BadOptimizations-2.2.0-1.20.1
  [✔] bendy-lib-forge-4.0.0
  [✔] BetterAdvancements-NeoForge-1.20.1-0.4.2.10
  [✔] bettercombat-forge-1.8.6+1.20.1
  [✔] BetterF3-7.0.2-Forge-1.20.1
  [✔] bettervillage-forge-1.20.1-3.2.0
  [✔] blastingraw-1.20.1-2-forge
  [✔] bygonenether-1.3.2-1.20.x
  [✔] caelus-forge-3.2.0+1.20.1
  [✔] chainmailed-1.3
  [✔] charmofundying-forge-6.5.0+1.20.1
  [✔] citadel-2.6.0-1.20.1
  [✔] cloth-config-11.1.136-forge
  [✔] Clumps-forge-1.20.1-12.0.0.4
  [✔] cobweb-forge-1.20.1-1.0.0
  [✔] collective-1.20.1-7.87
  [✔] comforts-forge-6.4.0+1.20.1
  [✔] connectivity-1.20.1-5.6
  [✔] Controlling-forge-1.20.1-12.0.2
  [✔] corpse-forge-1.20.1-1.0.17
  [✔] corrosivesculk-1.20.1-1.0.1
  [✔] CreativeCore_FORGE_v2.12.22_mc1.20.1
  [✔] cupboard-1.20.1-2.7
  [✔] curios-forge-5.11.0+1.20.1
  [✔] curiouslanterns-1.20.1-1.3.3
  [✔] dungeons-and-taverns-ancient-city-overhaul-1
  [✔] dynamiccrosshair-7.4.4+1.20-forge
  [✔] EasyAnvils-v8.0.2-1.20.1-Forge
  [✔] EasyMagic-v8.0.1-1.20.1-Forge
  [✔] elementus-1.3.0-20.1-beta-03
  [✔] embeddium-0.3.31+mc1.20.1
  [✔] embeddiumplus-1.20.1-v1.2.13
  [✔] emi-1.1.18+1.20.1+forge
  [✔] EnchantingInfuser-v8.0.3-1.20.1-Forge
  [✔] entity_model_features_forge_1.20.1-2.2.6
  [✔] entity_texture_features_forge_1.20.1-6.2.7
  [✔] expandedstorage-10.3.0-beta.5+1.20.1-forge
  [✔] experimentalsettingsdisabler-1.20.1-3.0
  [✔] extrasounds-1.20.1-forge-1.3
  [✔] Fallingleaves-1.20.1-2.1.0
  [✔] ferritecore-6.0.1-forge
  [✔] firstperson-forge-2.4.6-mc1.20.1
  [✔] ForgeConfigScreens-v8.0.2-1.20.1-Forge
  [✔] forgery-3.5.1+1.20
  [✔] fortune_on_netherite_1.1.0_forge_1.20.1
  [✔] geckolib-forge-1.20.1-4.4.9
  [✔] getittogetherdrops-forge-1.20-1.3
  [✔] gpumemleakfix-1.20.1-1.8
  [✔] grindenc-forge-1.20.x-v2.2
  [✔] Hearths v1.0.1 f12-48
  [✔] HopoBetterRuinedPortals-[1.20-1.20.2]-1.3.7
  [✔] Iceberg-1.20.1-forge-1.1.25
  [✔] immersive_weathering-1.20.1-2.0.3-forge
  [✔] ImmersiveUI-FORGE-0.2.2
  [✔] InvMove-1.20-0.8.4-Forge
  [✔] invtweaks-1.20.1-1.1.0
  [✔] ItemBorders-1.20.1-forge-1.2.2
  [✔] ItemPhysicLite_FORGE_v1.6.5_mc1.20.1
  [✔] LeavesBeGone-v8.0.0-1.20.1-Forge
  [✔] leawind_third_person-v2.2.0-beta.4-mc1.20-1.20.1-forge
  [✔] LegendaryTooltips-1.20.1-forge-1.4.5
  [✔] letmedespawn-1.20.x-forge-1.4.4
  [✔] libraryferret-forge-1.20.1-4.0.0
  [✔] lionfishapi-1.9
  [✔] Log-Begone-Forge-1.20.1-1.0.8
  [✔] lucent-1.20.1-1.5.5
  [✔] Medium Ore Veins_ Deluxe 1.2.2.1
  [✔] memoryleakfix-forge-1.17+-1.1.5
  [✔] modelfix-1.15
  [✔] ModifierKeyFix-1.1.0
  [✔] moonlight-1.20-2.13.26-forge
  [✔] moremobvariants-forge+1.20.1-1.3.0.1
  [✔] MouseTweaks-forge-mc1.20.1-2.25.1
  [✔] Necronomicon-Forge-1.6.0+1.20.1
  [✔] noisium-forge-2.3.0+mc1.20-1.20.1
  [✔] notenoughanimations-forge-1.8.1-mc1.20.1
  [✔] nyfsspiders-forge-1.20.1-2.1.1
  [✔] OctoLib-FORGE-0.4.2+1.20.1
  [✔] oculus-mc1.20.1-1.7.0
  [✔] Paxi-1.20-Forge-4.0
  [✔] piseks-craftable-saddle-1.0
  [✔] player-animation-lib-forge-1.0.2-rc1+1.20
  [✔] PresenceFootsteps-1.20.1-1.9.1-beta.1
  [✔] Prism-1.20.1-forge-1.0.5
  [✔] ProPlacer-v8.0.2-1.20.1-Forge
  [✔] PuzzlesLib-v8.1.25-1.20.1-Forge
  [✔] qualitysounds-forge-1.5.0-1.20.1
  [✔] radiantgear-forge-2.1.5+1.20.1
  [✔] radium-mc1.20.1-0.12.4+git.26c9d8e
  [✔] Realistic-Cobwebs-NeoForge-2.1.0-all
  [✔] Reblured-1.20.1-1.3.0
  [✔] recipeessentials-1.20.1-3.6
  [✔] resourcefulconfig-forge-1.20.1-2.1.2
  [✔] sculkhorde-1.20.1-0.9.16
  [✔] Searchables-forge-1.20.1-1.0.3
  [✔] secondchanceforge-1.20-1.5.1
  [✔] separatedleaves-2.5.0-forge-1.20.4
  [✔] SlotCycler-v8.0.1-1.20.1-Forge
  [✔] smoothboot(reloaded)-mc1.20.1-0.0.4
  [✔] smoothchunk-1.20.1-3.6
  [✔] snowundertrees-1.20.1-1.4.6
  [✔] sophisticatedbackpacks-1.20.1-3.20.13.1131
  [✔] sophisticatedcore-1.20.1-0.7.5.773
  [✔] soul-fire-d-forge-1.20.1-4.0.6
  [✔] sound-physics-remastered-forge-1.20.1-1.4.5
  [✔] spyglass_of_curios-forge-1.20.1-1.7.2
  [✔] stepitup-2.0.1-1.20.1-forge
  [✔] structureessentials-1.20.1-3.4
  [✔] StylishEffects-v8.0.2-1.20.1-Forge
  [✔] supplementaries-1.20-3.1.7
  [✔] takesapillage-1.0.3-1.20.1
  [✔] TravelersTitles-1.20-Forge-4.0.2
  [✔] UniversalEnchants-v8.0.0-1.20.1-Forge
  [✔] VanillaTweaks-forge-1.20.1-1.5.71
  [✔] veinmining-forge-1.5.0+1.20.1
  [✔] visuality-forge-2.0.2
  [✔] Windows Keyboard Fixes-forge-1.17-to-atleast-1.20-1.0.1-all
  [✔] witherstormmod-1.20.1-4.2.1-all
  [✔] Xaeros_Minimap_24.6.1_Forge_1.20
  [✔] XaerosWorldMap_1.39.0_Forge_1.20
  [✔] YungsApi-1.20-Forge-4.0.6
  [✔] YungsBetterDesertTemples-1.20-Forge-3.0.3
  [✔] YungsBetterJungleTemples-1.20-Forge-2.0.5
  [✔] YungsBetterMineshafts-1.20-Forge-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Forge-2.0.6
  [✔] YungsBetterOceanMonuments-1.20-Forge-3.0.4

**Comment by TaintedBlock** [comment]
Any resource packs?

**Comment by Jouto25** [comment]
> Any resource packs?

![image](https://github.com/user-attachments/assets/8c2477c1-aee3-4521-a669-d4a5d194c1a1)

**Comment by Composer-Hu** [comment]
I think you can try to disabled this:
![image](https://github.com/user-attachments/assets/9549cf74-a5e9-4a15-afbb-79721a48b8bc)
or disabled or R pack

**Comment by Jouto25** [comment]
> I think you can try to disabled this: ![image](https://private-user-images.githubusercontent.com/127498588/386980655-9549cf74-a5e9-4a15-afbb-79721a48b8bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NjQwNjksIm5iZiI6MTczMTg2Mzc2OSwicGF0aCI6Ii8xMjc0OTg1ODgvMzg2OTgwNjU1LTk1NDljZjc0LWE1ZTktNGExNS1hZmJiLTc5NzIxYTQ4YjhiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxNzE2MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGU5MjRmMDRmNTE4YWNiYWFkZWQyMGFkNzIxZDAzYzVmMTZjZDBmODgxNGU3MDQ1MzZjZWY1MzgxZWIyMjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P_MSt7CooHT90rVYH6rsHn1qz7V7zqGSfqnG27PDbRI) or disabled or R pack

![image](https://github.com/user-attachments/assets/94ceb041-3131-40e7-be64-24aec418f97c)

This is not turned on in my instance.

**Comment by Jouto25** [comment]
Found out the issue- It's **Embeddium++**.

It seems that Embeddium++ causes the fog of the Bowels to just be wacked out. Strangely however, this issue doesn't apply to other Embeddium extensions like Sodium/Embeddium Extras.

**With Embeddium Extras installed, no Embeddium++:**
![image](https://github.com/user-attachments/assets/72202966-b64a-4b0c-919f-184e5b55e867)

**With Embeddium++ installed:**
![image](https://github.com/user-attachments/assets/4f5625eb-aeb9-48b3-ac4e-244e7570a3b4)

And after some digging, this fog issue seemingly also persists in dimensions that are not the Overworld, like the Nether, as shown in this issue: https://github.com/SrRapero720/EmbeddiumPlus/issues/64

So I'll be giving a PSA to not use Embeddium++ until it's updated with the fog fixed. You can use alternatives like [Sodium/Embeddium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras) without any issue from fog colors in the meantime.
