### ISSUE TITLE
[Suggestion]: Villagers ring the bell when the WS is nearby

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2313]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Villagers ring the bell when the WS is nearby

**Comment by FatalERROR1234** [comment]
Lovely suggestion! :)

**Comment by Infinitekaosv3** [comment]
> Lovely suggestion! :)

Thanks!

**Comment by watersofnazareth** [comment]
Unlike raids villagers actively run away from villages when the Wither Storm is coming, so there's no real point in this
