### ISSUE TITLE
[Suggestion]: Villagers emit the sweating/Water particle effect 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2314]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Villagers emit the sweating/Water particle effect while running away from the Wither Storm

**Comment by SSgamingYT** [comment]
Honestly, I don't feel like this fits in the mod very well. Plus the particles can cause lag when there's a lot of villagers nearby

**Comment by Infinitekaosv3** [comment]
> Honestly, I don't feel like this fits in the mod very well. Plus the particles can cause lag when there's a lot of villagers nearby

It kinda does fit in cuz the villagers are worried and running away from the WS

**Comment by SSgamingYT** [comment]
> > Honestly, I don't feel like this fits in the mod very well. Plus the particles can cause lag when there's a lot of villagers nearby
> 
> It kinda does fit in cuz the villagers are worried and running away from the WS

Not really, mobs don't ever actually play effects when running away in vanilla unless they are attacked. This effect would be better off in an extension to fresh animations, rather than something in CWSM or Minecraft in general

**Comment by Infinitekaosv3** [comment]
> > > Honestly, I don't feel like this fits in the mod very well. Plus the particles can cause lag when there's a lot of villagers nearby
> > 
> > 
> > It kinda does fit in cuz the villagers are worried and running away from the WS
> 
> Not really, mobs don't ever actually play effects when running away in vanilla unless they are attacked. This effect would be better off in an extension to fresh animations, rather than something in CWSM or Minecraft in general

villagers make the water effect in raids, they should do the same when running away

**Comment by FatalERROR1234** [comment]
> Honestly, I don't feel like this fits in the mod very well. Plus the particles can cause lag when there's a lot of villagers nearby

It kinda does... In raids, the villagers run from Pillagers/other raiders and they sweat. It could make more sense if the same happens with the storm

**Comment by Infinitekaosv3** [comment]
> > Honestly, I don't feel like this fits in the mod very well. Plus the particles can cause lag when there's a lot of villagers nearby
> 
> It kinda does... In raids, the villagers run from Pillagers/other raiders and they sweat. It could make more sense if the same happens with the storm

Exactly

**Comment by watersofnazareth** [comment]
See #2342
