### ISSUE TITLE
[Suggestion]: Wither storm unable to pick up tainted blocks

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2315]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Make the Wither Storm unable to pick up tainted blocks.

Honestly the WS picking up tainted blocks doesn't make sense cuz it's like drinking your own blood sorta

This could also be a config I guess but I don't know

**Comment by TaintedBlock** [comment]
This doesn't really make sense imo. Blocks are blocks, it's like if the Wither Storm couldn't reabsorb its own mass to gain it back

**Comment by Infinitekaosv3** [comment]
> This doesn't really make sense imo. Blocks are blocks, it's like if the Wither Storm couldn't reabsorb its own mass to gain it back

the tainted blocks are apart of the WS's guts, would you really eat your own guts lol

**Comment by Composer-Hu** [comment]
![image](https://github.com/user-attachments/assets/7bd4ab81-f3cb-40f1-8e6d-69d73be2ad23)
lol

**Comment by Infinitekaosv3** [comment]
> ![image](https://private-user-images.githubusercontent.com/127498588/388180149-7bd4ab81-f3cb-40f1-8e6d-69d73be2ad23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMjE1OTcsIm5iZiI6MTczMjIyMTI5NywicGF0aCI6Ii8xMjc0OTg1ODgvMzg4MTgwMTQ5LTdiZDRhYjgxLWYzY2ItNDBmMS04ZTZkLTY5ZDczYmUyYWQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQyMDM0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTAxMjljNmEyMjIwNjJlN2Y3NDZhNjgwMDBlMDViMDgzNmFiNDllNzkzYjFmZmU5ZmNkNDlhMTEzNTYyZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dv-4CjdW9_WfpPJWlooiM0UCWKnDE5B_T1DBmkO2q_0) lol

not everything is suppose to be in this mod from MCSM, like endermen on wither storm

**Comment by Composer-Hu** [comment]
I don't mean to restore MCSM, just to illustrate that wither storm would not miss anything that it could devour.

**Comment by watersofnazareth** [comment]
The Wither Storm is meant to be indiscriminate towards most block types, it doesn't care that the blocks are tainted or not it just gains mass

**Comment by ScreamingMC** [comment]
Simple. make a datapack with path `...\data\witherstormmod\tags\blocks\wither_storm_block_blacklist.json` and add `#witherstormmod:tainted_blocks` to it if you prefer. no war, no drama, just simple quick datapack. only for you it will apply, others will have like they want.
