### ISSUE TITLE
[Suggestion]: Make rain and snow wrap around the WS

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2318]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Make rain and snow wrap around the WS and get pulled into the WS when the weather is rain/snow

**Comment by kaboom24** [comment]
UH HUH! PLEASE ADD THIS!!!

**Comment by nonamecrackers2** [comment]
Not really feasible to pull off given how rain/snow is rendered. Would be too much work for a barely noticeable effect, sorry
