### ISSUE TITLE
structures from storymode

### ISSUE THREAD

**Issue by jasongi33** [nonamecrackers2/crackers-wither-storm-mod#232]
i think adding structures or parts of them into the mod would be cool as they could contain useful supplies to help fight off or stall the wither storm. these structures would have their own theme of loot 

example of a structure you could find is:
Gabriel's temple
a part or boomtown

some of the special loot you could find is:
part of the amulet (you need 4 to craft the amulet similar to the new music disc) this would add a way to get the amulet without going into creative mode

some kind of schematics for the grapplehook (seen just before the formidibomb is used in storymode) this could be used to grapple onto a player in the tractor beam allowing you to save them or used to grapple onto the ground to save yourself.

i think these structures could spawn each in a different direction one could spawn  in the positive x axis while another could spawn in the negative y axis. these structures could add a bunch of new things while giving the players a place to hold out against the wither storm.

**Comment by nonamecrackers2** [comment]
While these seem like good ideas, I don’t plan on adding anymore structures to the mod. This could be a cool expansion however.
