### ISSUE TITLE
[Bug]: Bowels ambience doesnt play when loading a resource pack

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2321]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Describe the bug

When I loaded a new resource pack, and went back into the game the bowels ambience stopped playing but i could still hear the rumbling and shaking of the bowels

### Steps to Reproduce

1. load a new resource pack
2. press done
3. go back into game

### Crash Reports/Logs

No Crash Logs

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

![image](https://github.com/user-attachments/assets/ab78ad83-f3e1-41f9-8557-a34747a8f86a)

**Comment by TaintedBlock** [comment]
This isn't a bug, this is just what happens when you load or unload anything with resource packs. It happens to most sounds

**Comment by watersofnazareth** [comment]
Not sure if we could logically fix this but it is a vanilla thing

**Comment by Minerdude27272** [comment]
In options, click the purple "W". Then press the refresh sounds button in the top left.

Only do this **if** your sounds are refusing to work or after you apply a resource-pack.

**Comment by watersofnazareth** [comment]
Closing this as it's a vanilla thing and not normally encountered, you should expect audio to stop when reloading the entire game
