### ISSUE TITLE
[Suggestion]: More tainted flesh blocks

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2322]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

More tainted flesh blocks ( I only want these so i can decorate my custom bowels structures )
These blocks could also make it look like there's holes in the bowels.
1. Tainted flesh slab
2. Tainted flesh stairs

**Comment by SSgamingYT** [comment]
This would be pretty useful to make small details ngl, you could probably make the storm's corpse look more detailed with it too or make rounder tunnels in the bowels

**Comment by Infinitekaosv3** [comment]
> This would be pretty useful to make small details ngl, you could probably make the storm's corpse look more detailed with it too or make rounder tunnels in the bowels

yes id love this
