### ISSUE TITLE
[Suggestion]: Tainted ore 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2324]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

This doesnt have to be a tainted ore texture made by minecraft, it could be CWSM's own ore like how CWSM has its own door and glass texture

**Comment by watersofnazareth** [comment]
:clueless:

**Comment by Infinitekaosv3** [comment]
> :clueless:

you know how CWSM has its own tainted door and glass texture, what if CWSM had its own tainted ore texture

**Comment by Infinitekaosv3** [comment]
hopefully that makes more sense

**Comment by watersofnazareth** [comment]
The reason I said clueless is because I already did it lol
