### ISSUE TITLE
[Suggestion]: New config

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2326]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

A config where you can change what time-stamp the WS music should play and start at when the WS encounters you

**Comment by watersofnazareth** [comment]
Please give these proper names, but also this one isn't logically possible with how audio works in Minecraft
