### ISSUE TITLE
[Suggestion]: White terracotta pickup chance 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2328]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When blackhole config is turned on, White terracotta should get picked up as fast as planks and logs do 
![image](https://github.com/user-attachments/assets/fc5c2f99-e63a-4fcb-8701-025922ae3074)

**Comment by TaintedBlock** [comment]
Why white terracotta specifically? Or do you mean just terracotta in general?

**Comment by Infinitekaosv3** [comment]
> Why white terracotta specifically? Or do you mean just terracotta in general?

just white because some village houses have white terracotta and having the white terracotta just floating looks weird imo, thats why i sent that photo

**Comment by Infinitekaosv3** [comment]
> > Why white terracotta specifically? Or do you mean just terracotta in general?
> 
> just white because some village houses have white terracotta and having the white terracotta just floating looks weird imo, thats why i sent that photo

i mean it could be all terracotta blocks

**Comment by watersofnazareth** [comment]
The reason this happens is due to the badlands

**Comment by Infinitekaosv3** [comment]
> The reason this happens is due to the badlands

oh damn, theres no way to make the WS pick up just the village white terracotta?

**Comment by nonamecrackers2** [comment]
No there’s not a really solid way to do that
