### ISSUE TITLE
[Suggestion]: Wither Storm Block pick up blacklist

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2329]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Wither Storm Block blacklist

**Comment by watersofnazareth** [comment]
This has already existed for a very long time 😭

**Comment by Infinitekaosv3** [comment]
> This has already existed for a very long time 😭

i guess i didnt look hard enough lol
