### ISSUE TITLE
Corpses in the bowels.

### ISSUE THREAD

**Issue by Autumnis** [nonamecrackers2/crackers-wither-storm-mod#233]
Random humanoid models, whether they're a withered citizen or withered zombie/skeleton, could spawn in the bowels that act the same as armor stands except without being able to be moved or broken and with a random pose. Maybe random items/armor could be found on these as some loot for going into the bowels for the first time.

**Comment by nonamecrackers2** [comment]
We're working on adding skeletons/zombies that appear randomly in the tainted flesh blocks. We're using #399 to track this currently
