### ISSUE TITLE
[Suggestion]: WS roars can be heard through nether portal

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2330]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

WS roars can be heard through the nether portal while being 5 blocks away from the nether portal while also being in the nether

**Comment by DrMalpracticewastaken** [comment]
chill bro 😭

**Comment by Infinitekaosv3** [comment]
> chill bro 😭

😭😭

**Comment by MoistedPotatoes** [comment]
for portals on the surface this would be a good idea, it would also alert the player that they should NOT go into that portal as on the other side of it, it would not be a pretty sight.

**Comment by Infinitekaosv3** [comment]
> for portals on the surface this would be a good idea, it would also alert the player that they should NOT go into that portal as on the other side of it, it would not be a pretty sight.

why would the WS be in the nether?

**Comment by kaboom24** [comment]
Uh, YES PLEASE!

**Comment by nonamecrackers2** [comment]
I personally like the inability to determine whether or not the Wither Storm is outside a portal or not. This would give this away but is a cool idea
