### ISSUE TITLE
[Suggestion]: all 3 head roar when WS is near player

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2335]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

when the WS is near you/WS boss bar appears, all 3 of the WS heads should roar

**Comment by TaintedBlock** [comment]
What exactly would be the purpose of this besides being kinda loud

**Comment by Infinitekaosv3** [comment]
> What exactly would be the purpose of this besides being kinda loud

its like the WS announcing that hes here, and they could also turn down the roar

**Comment by pinkygrocket** [comment]
I think what Kaosv is suggesting is an entrance sound ala the [Triumvirate from Splatoon 3](https://www.youtube.com/watch?v=lYvqVly1gec) (volume warning). My retort however is that the Wither Storm already announces its presence via being seen in the distance, ambient sounds, and cave-ins, lessening the impact of such an event. Could be cool for resummoning though, given that the default resummon makes the Wither Storm at phase 4 from the getgo

**Comment by watersofnazareth** [comment]
There's no real point to this you rarely ever miss the Wither Storm approaching even underground it's telegraphed pretty well
