### ISSUE TITLE
[Suggestion]: Redstone Config

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2337]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

a config where if the Wither Storm is in a certain range, Redstone will flash off and on  

Example: https://streamable.com/4um5n8

**Comment by Infinitekaosv3** [comment]
https://streamable.com/4um5n8
sorry idk why its a image

**Comment by watersofnazareth** [comment]
I tried to do this but it's way too expensive on performance, so this isn't planned
