### ISSUE TITLE
[Suggestion]: Make Skeletons ride spiders & Baby zombies ride chickens

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2339]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Make Skeletons ride spiders & Baby zombies ride chickens when running away from the Wither Storm

**Comment by TaintedBlock** [comment]
I believe both jockeys are possible. I know I've seen the spider one. Chicken one is a mystery though

**Comment by watersofnazareth** [comment]
While this is possible it wouldn't fit really well and would require a new goal to be injected in them, aka more lag
