### ISSUE TITLE
Wither Storm disappears when i approach beyond it's distance renderer

### ISSUE THREAD

**Issue by Russ1an3mp1re** [nonamecrackers2/crackers-wither-storm-mod#234]
**Minecraft version**
The version of Minecraft the mod is running on is 1.16.5

**Mod version**
1.0.2
**Describe the bug**
When I spawn in the Wither Storm, it becomes invisible but the particles and tractor beam is still visible.

**To Reproduce**
Step to reproduce the behavior:
1. Install the Crucial 2 The Refresh Update modpack and spawn the Wither Storm. For me, it disappears.

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**
![Invisible_Wither-Storm](https://user-images.githubusercontent.com/109440572/179373284-81a64d26-b1c6-4a5a-830c-ded976210e6e.png)

**Comment by nonamecrackers2** [comment]
Does the mod pack include rubidium/magnesium and rubidium extras/magnesium extras? If so you’ll need to disable the entity render distance option.

**Comment by Russ1an3mp1re** [comment]
If you want, I can send you the modpack file.

**Comment by nonamecrackers2** [comment]
First see if it includes the mods I've asked for. If it does go to video options and then disable the setting I've indicated.

**Comment by Russ1an3mp1re** [comment]
it includes magnesium but it only allows me to go down to 50%

**Comment by Stormalisk** [comment]
I had this issue trying it on Medieval Minecraft, turns out it was Snow Real Magic that was causing it.

**Comment by Russ1an3mp1re** [comment]
I actually don't have Snow Real Magic installed

**Comment by nonamecrackers2** [comment]
> it includes magnesium but it only allows me to go down to 50%

There should be a menu in video options that should say "Extra" or something along those lines. In it there should be a setting called "Max Entity Distance." Disable that.

**Comment by Russ1an3mp1re** [comment]
okay

**Comment by nonamecrackers2** [comment]
Has that fixed the issue?
