### ISSUE TITLE
[Suggestion]: Make Tractor beams purple in the distant

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2340]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Make Tractor beams purple instead of white when the WS is far away
![image](https://github.com/user-attachments/assets/7b3b367d-dae5-4803-98b8-58a6a83b9315)

**Comment by DrMalpracticewastaken** [comment]
this wouldnt really look good and also you can disable the distant renderer fog

**Comment by watersofnazareth** [comment]
This works as intended

**Comment by nonamecrackers2** [comment]
I’ve tried this but yeah it does not look good
