### ISSUE TITLE
[Suggestion]: Command block in CWSM tab

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2341]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

Put the command block in the CWSM tab, everytime i wanna summon the wither storm in flat world I'd would have to use the " /give " command

**Comment by DrMalpracticewastaken** [comment]
![image](https://github.com/user-attachments/assets/69e5bacd-3c30-4583-833f-d3703a7f6f7b)

**Comment by DrMalpracticewastaken** [comment]
just use that

**Comment by Infinitekaosv3** [comment]
> ![image](https://private-user-images.githubusercontent.com/187129057/391204516-69e5bacd-3c30-4583-833f-d3703a7f6f7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MzEwMjAsIm5iZiI6MTczMjkzMDcyMCwicGF0aCI6Ii8xODcxMjkwNTcvMzkxMjA0NTE2LTY5ZTViYWNkLTNjMzAtNDU4My04MzNmLWQzNzAzYTdmNmY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQwMTM4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmRkMDQ1N2JlN2Y2NWQ2Yjk4OGMxNGQ1NzkwZGY3MWM3Y2FkYzA1NjBjYWYzNjIyNmNjNTBhNmM0MmNlYWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zHmW1Ou-DJa0Xt70EdKn9opgSscbi0NnVCY7yKZEvmM)

where is that at, also not alot of people know about this feature

**Comment by watersofnazareth** [comment]
This has been talked about before but only ops should be able to access the command block
