### ISSUE TITLE
[Suggestion]: withered beacon connects to normal beacons

### ISSUE THREAD

**Issue by DrMalpracticewastaken** [nonamecrackers2/crackers-wither-storm-mod#2344]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

I'm not saying the normal beacons should replace the support beacons, im just saying they should he able to add more levels to the withered one

Maybe like this (I'm on mobile rn so images are hard)
W=withered beacon, S=Support beacon, B=normal beacon

BSB
SWS
BSB

in that shape

**Comment by SSgamingYT** [comment]
I like the idea

**Comment by kaboom24** [comment]
nah it can already make you 2 shot creepers with fist (using strength) and immune to 80% of damage with resistance on max level so adding more levels would be way too OP (also if it was even slightly stronger resistance would make you immune to 100% of damage)

**Comment by nonamecrackers2** [comment]
Not a huge fan of this, this would require adding more levels to the beacon giving even more stronger and overpowered effects
