### ISSUE TITLE
[Suggestion]: Wither Storm World Config In World Creation Menu

### ISSUE THREAD

**Issue by MoistedPotatoes** [nonamecrackers2/crackers-wither-storm-mod#2345]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

simple, have the wither storm configuration button in the world creation menu like this image
![ws_config_in_worldcreation](https://github.com/user-attachments/assets/e925c3fd-01cd-4f44-8bf2-9d3daeb6f3dc)

**Comment by TaintedBlock** [comment]
But you can already access this in the main main menu before even choosing being in single player or multiplayer.

In options I believe

**Comment by SSgamingYT** [comment]
> But you can already access this in the main main menu before even choosing being in single player or multiplayer.
> 
> In options I believe

You can't access world config unless you are already in a world. Common/Client can be accessed, but not world.

**Comment by SSgamingYT** [comment]
As well as a way to import .toml configs like you are importing world configs

**Comment by nonamecrackers2** [comment]
This was something I tried implementing but ran into issues implementing it given Forge’s config system. May revisit this in the future.
