### ISSUE TITLE
[Suggestion]: Command block cracks when attacked in phase 1-2 with command block weapons

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#2346]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When a command block weapon is used on the wither storm in phase 0-2, it should crack the command block. The storm can heal the lost health, but when the bowels fight starts the command block has the health lost from when you attacked it. 

Scenarios where this is possible:
Creative mode/give commands

Resummoning stage set to 0 in config after killing the storm

**Comment by watersofnazareth** [comment]
Not realistically possible and is so small there's no reason to add it I doubt most people spawning the Wither Storm already have a command block tool and the resummoned wither is usually Phase 4
