### ISSUE TITLE
[SUGGESTION] Reuben Easter Egg Quality of Life Change

### ISSUE THREAD

**Issue by GangiTheBased** [nonamecrackers2/crackers-wither-storm-mod#2347]
Change the requirement to get the Easter Egg:
Instead of naming pig "reuben"
Name the pig "Reuben"
It looks prettier when his name starts with uppercase

**Comment by pinkygrocket** [comment]
Should probably be case-insensitive

**Comment by watersofnazareth** [comment]
Went ahead and fixed this
