### ISSUE TITLE
[Suggestion]: Farlands Reborn Compatibility

### ISSUE THREAD

**Issue by GangiTheBased** [nonamecrackers2/crackers-wither-storm-mod#2348]
### Guidelines

- [x] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The mod called "Farlands Reborn" need to be compatible with cwsm! Imagine going to farlands when wither storm chases you! We need this!

**Comment by TaintedBlock** [comment]
I just searched it up, and it works on 1.20.1

**Comment by TaintedBlock** [comment]
![image](https://github.com/user-attachments/assets/33a362f4-a0cd-4e85-a3c2-f698939e071b)

**Comment by GangiTheBased** [comment]
> I just searched it up, and it works on 1.20.1

But it isn't compatible with CWSM

**Comment by GangiTheBased** [comment]
CWSM breaks the farlands generation

**Comment by GangiTheBased** [comment]
And i know im not the only one because people who say farlands don't appear say they have cwsm downloaded

**Comment by watersofnazareth** [comment]
How would CWSM even break it?

**Comment by GangiTheBased** [comment]
> How would CWSM even break it?

No idea. Maybe bowels? Or smth with code? You guys gotta ask the creator of Farlands Reborn. It def has smth with terrain generation. But im sure cwsm is the one who breaks it.

**Comment by GangiTheBased** [comment]
And im sure because all the reports about farlands not working contains information that all the people for who farlands didn't generate had cwsm installed

**Comment by pinkygrocket** [comment]
Isn't this better suited as a bug report, not a suggestion?

**Comment by nonamecrackers2** [comment]
Please reopen this as a bug report and include the relevant details
