### ISSUE TITLE
[Suggestion]: New Structures

### ISSUE THREAD

**Issue by GangiTheBased** [nonamecrackers2/crackers-wither-storm-mod#2349]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

The mod should generate structures like endercon,boom town, etc. but every structure will always be located on certain location set by dev. Exapmle: Endercon generates at: 1000 0 1000 and Wither Storm now spawns there

**Comment by TaintedBlock** [comment]
G U I D E L I N E S

**Comment by nonamecrackers2** [comment]
Please read the guidelines
