### ISSUE TITLE
[Suggestion]: Tell Wither Storm to ignore specified players entirely

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#2351]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

This is a minor issue but I'd like to be able to run a command or adjust a config to exclude certain players from being chased. Reason being that when I was playing in mp, those who wanted to be in creative mode had to be sure they were near a player. It wasn't a huge issue to switch to spectator mode when observing the wither storm, but would be helpful

**Comment by DrMalpracticewastaken** [comment]
this is good we need this

**Comment by pinkygrocket** [comment]
[bro you already suggested this](https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/2327), don't dupe issues

**Comment by GrandmaPork** [comment]
interesting. i couldnt find it and github opened with the issue half completed. thought i left it half-finished

**Comment by nonamecrackers2** [comment]
Eh no worries there’s so many issues and its hard to find existing ones (even if you happen to make them lol)
