### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SlinkyPoetYT** [nonamecrackers2/crackers-wither-storm-mod#2353]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

I am using the bedrock port wither storm

### Describe the bug

Whenever you light the formidabomb in the bedrock port the wither storm will take it up then look up and then it will try to eat it then it will explode but the wither storm won’t fall apart.
Also when it gets to the stage were it is big it won’t even grow.

### Steps to Reproduce

1. Summon wither storm
2. light formidabomb
3. Wait for it to get sucked up by the wither storm and for it to explode 
4. Watch it NOT fall apart

### Crash Reports/Logs

None

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

NONE

**Comment by watersofnazareth** [comment]
We're not responsible for the bedrock port it's not official to us
