### ISSUE TITLE
[Bug]: Reuben and Nonamecrackers2 Symbiont use Programmer Art Textures

### ISSUE THREAD

**Issue by MoistedPotatoes** [nonamecrackers2/crackers-wither-storm-mod#2354]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.11

### Describe the bug

simple bug, reuben and the nonamecrackers2 symbiont use the original programmer art textures instead of the ones from jappa's 1.14 texture update, so they look a bit outdated compared to the obsidian and pigs

### Steps to Reproduce

1: spawn a pig or symbiont
2: rename the pig to "reuben" or with the symbiont "nonamecrackers2"
3: see that the crackers symbiont has the old obsidian texture, and for reuben, the old pig texture

i made a small resource pack to fix these small errors, if you developers want to use them, they're all yours.

[§5CWSM §d1.14 Styled Mobs §eEaster Egg Mobs.zip](https://github.com/user-attachments/files/18045895/5CWSM.d1.14.Styled.Mobs.eEaster.Egg.Mobs.zip)

### Crash Reports/Logs

no crash reports, they're just using programmer art textures

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-12-06_17 53 57](https://github.com/user-attachments/assets/cb506efc-9bbb-426b-9a25-f3934d40a7a4)
![2024-12-06_17 54 36](https://github.com/user-attachments/assets/cfbc71b0-c93d-4ad7-b4ce-797383d31288)
with programmer art used:
![2024-12-06_17 55 27](https://github.com/user-attachments/assets/8d791c78-c557-42d3-b1ea-af8abd3f6892)
![2024-12-06_17 55 35](https://github.com/user-attachments/assets/71edfc99-d6ad-4560-9053-f54561225ad1)

### Mod List

only a texture issue on cwsm's side so no mod incompatibility

**Comment by TaintedBlock** [comment]
I believe both of these are intentional. This would be too big of a mistake to go unchecked.
Do remember that the nonamecrackers2 Symbiont is a joke easter egg. Not to be consistent with everything else. (Reuben's texture just references MCSM's textures)

**Comment by watersofnazareth** [comment]
Both of these are intentional and not a bug whatsoever, the crackers symbiont is a joke of people thinking the Wither Storm is made of Obsidian so I made the texture intentionally use the old ugly texture
