### ISSUE TITLE
[Bug]: Invisible tranctor beams with Optifine shaders

### ISSUE THREAD

**Issue by Bloc6547** [nonamecrackers2/crackers-wither-storm-mod#2355]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

47.3.11

### Describe the bug

The tractor beams are invisible on every Optifine shader except the "built-in" one.
It doesn't seem like an issue at first, but this mod used to work with optifine shaders, in previous versions I think.
Optifine is used here as a MOD, not a version/client.
(My device cannot handle the Oculus and Rubidium, the shader alternatives)

### Steps to Reproduce

1. Set up Minecraft Forge 1.20.1-forge-47.3.11
2. Add the Witherstorm mod 1.20.1-4.2.1-all.jar
3. Add the Optifine_1.20.1_HD_U_I6.jar
4. Launch the game
5. When you turn on any shader, Wither's tractor beams are invisible.

### Crash Reports/Logs

--this bug does not cause the game to crash, it's just a visual glitch--

### Is OptiFine installed?

- [X] OptiFine is installed

### Mod List

none

**Comment by TaintedBlock** [comment]
use embeddium and oculus. Optifine sucks

**Comment by Infinitekaosv3** [comment]
> My device cannot handle the Oculus and Rubidium, the shader alternatives

"My device cannot handle the Oculus and Rubidium, the shader alternatives"

**Comment by TaintedBlock** [comment]
> > My device cannot handle the Oculus and Rubidium, the shader alternatives
> 
> "My device cannot handle the Oculus and Rubidium, the shader alternatives" said by Bloc6547

Ah, didn't see that. But he said rubidium not Embeddium

**Comment by TaintedBlock** [comment]
Embeddium is better

**Comment by Bloc6547** [comment]
Well, it works now!
Thank you, I didn't really notice the downfall/decline of Optifine over the last few months/years.

_(and thanks to Infinitekaosv3 for noticing the detail I mentioned)_
