### ISSUE TITLE
[Suggestion]: wither storm sight

### ISSUE THREAD

**Issue by kaboom24** [nonamecrackers2/crackers-wither-storm-mod#2357]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

when you left click a mob in spectator mode you can see through its perspective currently when you do that with the wither storm you only see the perspective of the middle head I think you should see all three heads point of view (or at least make it possible to select specific heads)

**Comment by TaintedBlock** [comment]
duplicate #2201

**Comment by kaboom24** [comment]
K
