### ISSUE TITLE
[Bug]: Command block books don't work with smithing tables anymore

### ISSUE THREAD

**Issue by FinnCreeper** [nonamecrackers2/crackers-wither-storm-mod#2358]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.2.1

### Mod Loader

Forge

### Mod Loader Version

1.266.0

### Describe the bug

You are unable to place command block books into smithing tables because of the way smithing tables were changed as of 1.20

### Steps to Reproduce

1. place down smithing a table
2. interact with the smithing table
3. attempt to place a command block book in any of the slots
4. it dosn't work

### Crash Reports/Logs

(there was no crash)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![2024-12-14_14 27 12](https://github.com/user-attachments/assets/375f13a5-25f0-4ff0-80ec-6a80290f6632)
![2024-12-14_14 27 20](https://github.com/user-attachments/assets/98431e31-2e89-4812-a33a-4ac289b0c2b9)

### Mod List

Appleskin
Connected glass
Cracker's wither storm mod
fusion (connected textures)
SuperMartijn642's core lib

**Comment by TaintedBlock** [comment]
You use an anvil on 1.20

**Comment by nonamecrackers2** [comment]
This. This is because of the smithing templates which were added in 1.20.1
