### ISSUE TITLE
Tentacle mobs for underground or inside buildings

### ISSUE THREAD

**Issue by SpaceBear87** [nonamecrackers2/crackers-wither-storm-mod#236]
I've noticed players are relatively safe bellow ground, I believe that once the Storm has reached a stage high enough and is hovering above the player while they are underground, the storm should shoot tentacles bellow ground and have smaller tentacle mobs appearing bellow the ground and in caves, if it is a large cave, perhaps use a larger variant. 

Obviously the tentacles wouldn't actually need to connect to the storm itself, just spawning bellow it and be "sucked back down" if the storm is lured away and thus no longer above the player.

Having a small creeper sized hole bellow the tentacles would imply that they just broke through the ground, rather then just spawning there. (Holes would of course change size depending on the tentacle size (or perhaps even blocks around the tentacle, like ruble it just pushed out of the ground))

(Here is a basic image that I found online, its a pretty similar concept)
![OIP](https://user-images.githubusercontent.com/87466338/179386034-daa57f51-9f74-478c-8c21-0410fc0c0819.jpg)

**Comment by nonamecrackers2** [comment]
I feel this isn’t entirely practical and worth my time, and I can see players becoming frustrated that they can’t even be safe underground and are forced to live in the nether. While surviving in the nether is expected, I want players to be able to have some sense of security underground (despite wither sickness and the prospect that the WS will eventually reach them) in the overworld and is one of the bigger reasons why I probably won’t be adding this. Thanks for the suggestion as always, hope you understand.
