### ISSUE TITLE
Make the tentacles move faster while it accelerates, or make it do a specific sound that alerts you that its going to accelerate.

### ISSUE THREAD

**Issue by ItsZed01** [nonamecrackers2/crackers-wither-storm-mod#237]
So basically, what I was thinking is: When the Wither Storm starts accelerating, the tentacles should start moving faster to indicate that its accelerating. It should also do a louder roar so you can hear that its going to accelerate, (for example when you are inside of caves, etc.) This should the toggle-able. I think you can already imagine what it would look/sound like. This would be really helpful as we usually don't know while we are mining in caves for diamonds, etc.

**Comment by nonamecrackers2** [comment]
While I think the surprise of the sudden chase should remain the same, the subtle indication of the tentacles moving a tad faster would be a good idea.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
