### ISSUE TITLE
LoD for WS

### ISSUE THREAD

**Issue by newbod07** [nonamecrackers2/crackers-wither-storm-mod#238]
I think the Wither Storm from far away should be using the low quality model in depending on how far the player from the Wither storm the Wither storm's model changes it's quality saving memory on computers and you can change it in the settings

**Comment by nonamecrackers2** [comment]
I don’t want to make more models however a feature to swap to the low res ones when at a distance is a good idea

**Comment by newbod07** [comment]
> I don’t want to make more models however a feature to swap to the low res ones when at a dista

**Comment by newbod07** [comment]
thank you so much this Feature could help me not lag as much

**Comment by nonamecrackers2** [comment]
Leave this open for future reference, I’ll close it manually once it’s implemented into the mod :)

**Comment by newbod07** [comment]
I didn't even close it I don't know how it it closed lol

**Comment by nonamecrackers2** [comment]
It's all good

**Comment by newbod07** [comment]
ok

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
