### ISSUE TITLE
WS Tractor Beam dissappearing when you go inside

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#239]
When inside the tractor beams, they go invisible, making it look like you're magically levitating
I don't know if this is intentional or it's like this because of technical limitations but being surrounded by purple light as you're getting sucked would add to the terror factor (Just like MCSM)

**Comment by nonamecrackers2** [comment]
This was already implemented into the 1.18 and 1.19 versions, and won't be backported to 1.16. Sorry.
