### ISSUE TITLE
After the light and shadow load, a storm is generated and crashes

### ISSUE THREAD

**Issue by shiyushui** [nonamecrackers2/crackers-wither-storm-mod#24]
I installed this mod, this mod is good, but after loading the light and shadow with opfine, I generated a storm, and the game suddenly crashed, hoping to solve, thanks.

**Comment by nonamecrackers2** [comment]
#22. Try turning off "Block Cluster Colouring" in the client config.

**Comment by shiyushui** [comment]
thanks

**Comment by nonamecrackers2** [comment]
Np
