### ISSUE TITLE
Wither Sickness Immunity Causing Crashes

### ISSUE THREAD

**Issue by GalenAltaiir** [nonamecrackers2/crackers-wither-storm-mod#240]
**Minecraft Version**
Minecraft 1.16.5

**Mod version**
1.0.2.4

**Describe the bug**
Incompatibility with Ars Arsenal mod. Requires Ars Nouveu as core, the armors from the mod seem to grant a passive protection from a list of negative statuses, based on the error message it seems to also attempt to give player protection from *wither sickness* and this causes the crash.

**To Reproduce**
Standalone
1. Install Ars Nouveu
2. Install Ars Arsenal 
3. Install Wither Storm
4. Put on the armor sets from Ars Arsenal

Our Modpack
1. Install [StinggRaee Modded 3.2.0] (https://www.curseforge.com/minecraft/modpacks/stinggrae-modded/files/3878474)
2. Put on Ars Arsenal Armor Sets (Creative Tab 9/12 top right)

**Crash Reports / Logs**
Crash Log - (https://pastebin.com/cgSYBZXT)

**Screenshots**
https://imgur.com/a/2vkVKOe

We managed to resolve the geckolib issue, but are struggling to find a way to resolve the wither sickness error.

I'm aware that this is an incompatibility issue, and might not be resolved. However, if there's a config / some way we can temporarily fix this without disabling either mods that would be good.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 versions
