### ISSUE TITLE
Maybe add the corrupted beacon from minecraft dungeons as a new weapon, craftable with the wither nether star

### ISSUE THREAD

**Issue by RefrigeraterReal** [nonamecrackers2/crackers-wither-storm-mod#241]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**Comment by nonamecrackers2** [comment]
I don't have any intentions of adding weapons from other Minecraft games into my mod specifically. I'll be adding a beacon special to the mod eventually.
