### ISSUE TITLE
[Symbiont summoning item/structure] Corpse Biome once the Wither Storm is defeated.

### ISSUE THREAD

**Issue by StupidUserNameThin** [nonamecrackers2/crackers-wither-storm-mod#242]
Maybe make a biome when its been killed ( Like when you use the Mega TNT or whatever its called) So that way you could collect the blocks from when you're fighting the command block easier. Maybe make it so that when you are in the biome walking on certain blocks could make you get wither sickness or make the player get the sickness when they enter the biome. (But make it temporary so you dont get stuck with the sickness when you leave the biome ) ALSO, maybe make it so that in the corpse biome, you could summon the symbiont using some sort of item / summoning it in a structure.

**Comment by nonamecrackers2** [comment]
Instead of adding a biome I plan for the wither storm to drop clusters of it’s flesh upon death with a random assortment of tainted blocks. I do like the ability to be able to summon the withered symbiont with an item/structure however.

**Comment by TaintedBlockk** [comment]
YESS PLEASE I was actually thinking of the idea yesterday!

**Comment by myron-obsolete-account** [comment]
> 

for a way to summon a withered symbiont, maybe this would be a cool way to do it:

step one: grab some tainted dust and an infected flesh block
step two: throw them into a brewing stand to make a potion
step three: look for a zombie and right click on him to give him the potion, zombie starts shaking and after 10 or 20 seconds he turns into a withered symbiont (could also work with splash/lingering potions)
warning: if you drink the potion, it will kill you

**Comment by nonamecrackers2** [comment]
The Withered Symbiont will now be resummonable in the next major release, using the withered beacon
