### ISSUE TITLE
If the player sleep, the wither storm gets a speed boost

### ISSUE THREAD

**Issue by StellaBiscuit** [nonamecrackers2/crackers-wither-storm-mod#243]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

When you sleep, you skip the night, I feel like it would be cool to give the wither storm a big speed boost if the player sleep through the night (so it give the impression it moved during the night)

The speed boost would end once it is in a player loaded chunk (so you don't actually see it speed boost like a maniac)  or when the time of the boost runs out

**Comment by nonamecrackers2** [comment]
I feel like this would deter people from sleeping and wouldn’t make for an overly fair experience in the case the WS does catch up to the player. Not only that but the faster the WS moves the more performance takes a hit.
