### ISSUE TITLE
Game crashes when it attempts to create a block cluster that contains Train Tracks from create mod. 

### ISSUE THREAD

**Issue by V0calgiant12** [nonamecrackers2/crackers-wither-storm-mod#244]
**Minecraft version**
1.18.2

**Mod version**
2.0.1.2

**Describe the bug**
The game crashes when the WS attempts to pick up a block cluster that contains Train Tracks from the Create mod. (or rather, fake tracks, assumed from the fact that the crash report states nothing about create:tracks but rather create:fake_tracks which I'm going to assume is the in-world form of the item itself) 

**To Reproduce**
1. Download the Create mod and search "Train" in the creative menu once in a world. (might want to make a new world for this)
2. Place down a lot of the tracks to ensure the WS will try to pickup at least one.
3. Summon in the WS, to speed things up, set it to a form with 3 heads and use a firework to bring its attention to the tracks.
4. Have your game crash because the WS attempted to create a block cluster with the tracks in it.

**Crash Reports / Logs**
[crash-2022-07-17_20.03.05-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9129578/crash-2022-07-17_20.03.05-client.txt)

**My Idea for a fix**
Maybe make a list of blocks that cannot be made into a part of a block cluster or a block that the WS picks up individually at the beginning stages when it is first summoned. So that way, the tracks will not be attempted to be put in a block cluster, bypassing the crash. This could also be configurable so if any other problems arise for other mods, instead of creating a bug report and having you put the block name in the list, you can just make the players do it themselves.

**Comment by StellaBiscuit** [comment]
I have an idea, maybe make the blacklisted block break instead of forming a cluster so the item form can be eaten up without crash

**Comment by ShadeKage** [comment]
Im to believe the reason this happens is create uses flywheel to make the custom curved tracks, and they are technically "fake" tracks, the only thing that makes them work is flywheels plugins, and since this mod doesnt support that, it crashes trying to make something it cant
Setting a failsafe to just break the block causing issues would be the best solution, over having to black list any and all blocks that could cause issues

**Comment by V0calgiant12** [comment]
That is a way better idea than mine was, especially because that means the
destruction will still take place which I like.

**Comment by nonamecrackers2** [comment]
From the crash report it looks almost like a NPE that could be easily avoidable. The tracks must not use the block entity rendering system (instead probably using something with flywheel as someone here already suggested), however this is just speculation.

**Comment by nonamecrackers2** [comment]
Should be fixed in the next 1.18/1.19 release
