### ISSUE TITLE
[“Reuben” pig name along with texture] Reuben "Easter egg" and maybe Tameable?

### ISSUE THREAD

**Issue by ShadeKage** [nonamecrackers2/crackers-wither-storm-mod#245]
**Description of feature**
A Easter egg related to renaming a vanilla pig to Reuben, which will give the renamer an achievement, and (possibly) "tame" it
Hear me out, its long
The tame would act like a wolf in AI, but be unable to made sit, but can be leaded to posts to stop following, it would tame to whoever renamed it, and hostile mobs would try to focus it, such as zombies, spiders, skeletons, and creepers, though to avoid annoyance, they would be unable to explode on the pig.
It will try to run from any hostile mobs, and have mild plot armor, being "unkillable" by it not showing red any visible red damage tick and a load of health, only making a panicked oink noise when avoiding the damage, and a speed boost when it is damaged, but if taken too much damage, plays a custom oink noise from story mode, and give it the black eye texture.
The wither storm wont focus the pig, but when you enter the storm in the final fight, it will follow in with you, at this point, it can lose its plot armor, or maybe more likely, is destined to die after the storm is killed, eitherway, dropping a special 1 pork that cant be eaten, and some fancy name, and acts like a trophy.
If the owner dies in anyway, or gets removed from its owner via being leaded to a post, it panics and start oinking loudly, and tries to go to the nearest player in a sprint, imprinting on the first player it finds
I know it might be hard to truly give it plot armor, especially against lava, maybe you could make it unable to go over lava tiles with no blocks inbetween it and the lava below? Eitherway i want it to be sorta useless, only being good as a distraction for normal mobs, and a buddy to bring along the way
Up to you if multiple should be allowed in a server at once, id say make it a command to choose how many max, if at all above 1

Sorry for the novel! I just had this idea brewin and wanted to get it out, thanks!

**Comment by nonamecrackers2** [comment]
Seems like a pretty cool idea, however it’s not worth my time to add some complicated AI to something the majority of players won’t ever notice. I think renaming a pig too Reuben and having it’s texture change could be a cool addition

**Comment by ShadeKage** [comment]
Thats fine! Its why I sorta separated them, maybe in the future, having the Easter egg is fine enough on its own lol

**Comment by BluePineappleGuy** [comment]
it could just give a baby pig a darker spot on its back

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
