### ISSUE TITLE
How long does it take for phase 7 to start?

### ISSUE THREAD

**Issue by Spiritblossoming** [nonamecrackers2/crackers-wither-storm-mod#246]
I've been waiting for over an hour now and im not sure why but phase 7 never will start, and if I summon a phase 7 wither it never opens a hole.

**Comment by ShadeKage** [comment]
It stops growing at phase 5 or so when first spawned, you need to trigger the bomb on it and then re-awaken it to advance to 6 and 7, its mandatory

**Comment by nonamecrackers2** [comment]
If you never formidibombed it won’t evolve until after it’s blown up. Otherwise patience is key, it can take a while (you can always mess with it’s evolution speed in the server config)
