### ISSUE TITLE
Allow some sort of way to make the wither storm follow a creative mode player

### ISSUE THREAD

**Issue by StellaBiscuit** [nonamecrackers2/crackers-wither-storm-mod#247]
**Description of feature**
Right now, there is no way to make a wither storm move other then survival player (and command obviously)

The thing is, if I wanna try out and also see how it moves and stuff, but don't want to get caught in a beam every 2 second, I can't, since there is no way to make a wither storm follow a player that is in creative or spectator

**Comment by SpaceBear87** [comment]
It should still follow in Creative, it did with me.

**Comment by nonamecrackers2** [comment]
Yes it does follow creative players. In the recent 1.18 update you can set the WS ultimate target to a specific player, info on how in the “For creative users” spoiler on the mod page

**Comment by StellaBiscuit** [comment]
Yeah I am dumb, I just didn't realised that it slows down a lot after it caught you for the first time and though it just didn't move at all
