### ISSUE TITLE
Wither Storm Tentacles entering Nether portals

### ISSUE THREAD

**Issue by N13F** [nonamecrackers2/crackers-wither-storm-mod#248]
If a player enters a nether portal and the Wither Storm is near or above the portal, a Wither storm tentacle will spawn through the portal a few seconds after the player enters the nether. The wither storm tentacle would block the nether portal entrance for the player to fend off against.

If the player is close to the tentacle it would grab them and will slowly bring the player back to the portal and into overworld. 

If the player doesn't successfully fend off the tentacle back,  it would wrap around the portals obsidian frame and will attempt to break it. Once it breaks it will quickly slither back into the portal.

This was inspired from a Minecraft story mode scene where the Wither Storms tentacle appeared through the nether portal and then soon after it breaks the nether portal frame.
![Wither Storm tentacle breaking portal](https://user-images.githubusercontent.com/100981997/179470118-4baf3340-b69f-4d25-8ae4-0da3ec9bb480.png)

![Wither Storm tentacle through portal](https://user-images.githubusercontent.com/100981997/179470244-db5c4cef-eaaa-47e2-b012-d943787a47f8.png)

**Comment by SpaceBear87** [comment]
Definitely! This would absolutely blow someone's mind if they had never seen MC:SM, Imagine how scary and truly alive the Witherstorm would seem if this happened in game. I also think the Witherstorm should have manual attacks too, not just the tractor beam.

**Comment by StellaBiscuit** [comment]
Last issue related to that was closed because it would cause the player to be trapped in the nether and would be super hard to return back

I do feel like this should be added, but the obsidian broken by the tentacle should be dropped so it is easy to rebuild it afterwards (a ghast can always light the portal)
Alternatively, ruined portal, piglins and fortress can provide obisidan easly

**Comment by nonamecrackers2** [comment]
I won’t be doing this as described here: #13
