### ISSUE TITLE
Manual Tentacle attacks and tentacle pickups 

### ISSUE THREAD

**Issue by SpaceBear87** [nonamecrackers2/crackers-wither-storm-mod#249]
Rather then just using the tractor beam as its main weapon, I believe the Witherstorm should have numerous manual attacks, couple of examples:

1. hitting the ground with a tentacle, causing damage or perhaps a crack in the ground. 

2. A wide sweep attack, for when the player is unreachable, like in trees or inside a mountain. Basically what this would do is destroy the blocks that the tentacle hits, then it checks if the blocks above or bellow are attached to anything, if they aren't, they should be sucked into the tractor beam (In the base of trees)  which would make it a lot harder to stay out of sight of the storm.

3. Being able to lob the occasional chunk of terrain or tree at a player, the same chunks it would usually pick up (Or again, a tree)

4. A pick up attack, the tentacle could pick up the player (Or even mobs) and then bring it up to its mouth to eat them. If the player hits the tentacle with a sword or axe enough, it will drop the player. Speaking of which, what if when a mob or player is killed by the storm its blocks are turned black and dismembered then disappear into the storm, similar to the Morph mod:
 
![image](https://user-images.githubusercontent.com/87466338/179474467-7c5faf1d-d91f-47ff-ad03-0de31d5df49e.png)
![image](https://user-images.githubusercontent.com/87466338/179474507-0d5d473b-ea1a-4544-a21f-fd485d811a7d.png)

6. In the final stages of the Storm, non infected Mobs should Migrate away from the storm, not an essential, but it would really set the mood for this mod, especially if they wont attack the player because they are scared.

Sorry this is a lot of ideas, and its kinda off topic from the original idea, but they are all here if you need them I guess.

**Comment by ShadeKage** [comment]
I really do like this idea, my add on to that idea would be to maybe make it so the attacks miss at the start, so when it first starts using the attacks, to try and miss near the player, mostly in the way they're running to, to create the idea that its aiming ahead of the the target, but more to just be scary, imagine running away and you just see stuff being thrown and things crashing down around you, that'd be terrifying, but dying instantly wouldn't be very fun, this might be better just as another way to cause block damage
And the "off topic" mob migration sounds neet as well, just like in the chapter with the bomb

**Comment by nonamecrackers2** [comment]
I talked about tentacles attacking here: #12

I think the tentacle melee attacks and reaching down to the ground etc is a great idea but would require a lot of extra work I’m not willing to put time towards right now. I could do a static animation however I can’t guarantee the tentacle would ever connect to its target, losing the realism. For the side thing you should probably separate that.

**Comment by BluePineappleGuy** [comment]
its a cool idea i like it
