### ISSUE TITLE
Command block armor set idea

### ISSUE THREAD

**Issue by realbluthewolf** [nonamecrackers2/crackers-wither-storm-mod#250]
I know this isn't in story mode but it would be cool if you could add a command block armor along with the tools so we have armor and tools, i know story mode already has 8 armor sets to choose from but come on it's 8 sets, one set for the tools would be good, and maybe an achievement with it when you get the command block armor, again just an idea.

**Comment by antivoid66** [comment]
isnt this too op?

**Comment by realbluthewolf** [comment]
> isnt this too op?

I don't think it would be op because I did so testing with the tools before and they are exactly the same as netherite tools, it's just got a little difference in attack power so the armor would have a different in defence.

**Comment by ShadeKage** [comment]
I believe this would be going a little far, remember that the mod is supposed to be based off of story mode, maybe think lesss about the more coolest sounding armor, and maybe towards the armory from story mode with all those selections, id rather keep it accurate as possible than go and add stuff like that

**Comment by realbluthewolf** [comment]
that could work but it's juat an idea.

**Comment by nonamecrackers2** [comment]
The set would require a lot symbiont boss battles for minimal gain (as yeah it would really only be a bit better than netherite). The current way of getting command block books is to have a wither storm active and the cooldown between symbiont summoning times would cause for a lot of long waiting periods for a set I don’t think would see much use from players.
