### ISSUE TITLE
Get Witherstorm's state Command

### ISSUE THREAD

**Issue by SimpleWolf** [nonamecrackers2/crackers-wither-storm-mod#251]
**Description of feature**
A command that allows an OPed player to get the current status of a selected Witherstorm. The `/data` command does have some useful info, but with all of the extra bits of data it can be difficult to read.

I propose a command along the lines of `/witherstormmod status **[DESIREDSTATUSHERE]** @e[type:witherstormmod:wither_storm,limit=1]` to make this a lot easier to work with.

A list of example statuses that could be returned
- Phase
- Distracted
- UltimateTarget
- consumedEntities

It will also be incredibly useful if this data can be used with the /execute command to return the data for command block shenanigens or mods like KubeJS

**Comment by willzsocial** [comment]
this is actually a very good suggestion!

**Comment by nonamecrackers2** [comment]
You could actually do this via "/data get entity @e[type=witherstormmod:wither_storm,limit=1] Phase" or whatever value. I feel this command would be slightly redundant.
