### ISSUE TITLE
Found a mod incompatibility.

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#252]
**Minecraft version**
1.18.2

**Mod version**
The most recent version, 2.0.1.2

**Describe the bug**
The wither storm is incompatible with the mod Beyond Earth, made by mrscauthd. Summoning the wither storm in any way after traveling to space even once, via the structure or commands, completely breaks the minecraft world. Spawn eggs don't work, commands don't work, you can't go through portals, all mobs including the wither storm stop moving and cannot be harmed, tnt disappears when lit without exploding, and the only way to close minecraft in this state is by using the task manager.

**To Reproduce**
1. Use a rocket from Beyond Earth and travel to another planet or the moon.
2. Summon the wither storm by any means, what dimension you're in doesn't matter.
3. See error

**Crash Reports / Logs**
![2022-07-18_09 12 04](https://user-images.githubusercontent.com/95892349/179519100-675e0bf7-948a-4787-ba75-d28e91fd8abe.png)

Minecraft does not crash with this issue.

**Screenshots**

**Comment by nonamecrackers2** [comment]
If you make a new world, and type "/execute in", what are all the dimensions that pop up?

**Comment by ghost** [comment]
beyond_earth:earth_orbit, beyond_earth:glacio, beyond_earth:glacio_orbit, beyond_earth:mars, beyond_earth:mars_orbit, beyond_earth:mercury, beyond_earth:mercury_orbit, beyond_earth:moon, beyond_earth:moon_orbit, beyond_earth:venus, beyond_earth:venus_orbit, minecraft:overworld, minecraft:the_end, minecraft:the_nether, and witherstormmod:bowels.

**Comment by nonamecrackers2** [comment]
Interesting. I’ll have to investigate further.

**Comment by nonamecrackers2** [comment]
Unable to reproduce. It's normal for the game to lag temporarily when the Wither Storm is spawned, and this may be because of your setup or some other issue I'm not aware of.
