### ISSUE TITLE
0,0 Structure should be different on certain biome

### ISSUE THREAD

**Issue by StellaBiscuit** [nonamecrackers2/crackers-wither-storm-mod#254]
**Description of feature**
![image](https://user-images.githubusercontent.com/53101126/179582226-87f7c6d1-6e69-41b8-8e87-6348328dd813.png)
This doesn't seem right...

I feel like there should have some variation depending of the biome that is at 0,0

**Comment by GrandmaPork** [comment]
I've had it be a small island in the ocean lol

**Comment by nonamecrackers2** [comment]
Closing in favor of #1048
