### ISSUE TITLE
A small idea to counter the tractor beams in a cinematic way

### ISSUE THREAD

**Issue by ShadeKage** [nonamecrackers2/crackers-wither-storm-mod#255]
**Description of feature**
The idea goes as follows
If your grabbed by a beam, and hold a direction on wasd into a solid block, your character will "grab" onto it, its a general instinct to do this usually
Grabbing on freezes your movement and causes you to float there, held on, maybe with a custom animation of you ina  swimming animation with your legs facing the WS, could be useful for multiplayer, add some cinematic moments of teammates saving others, or just make a tenser situation
As it currently stands, you can only get caught behind other blocks to stop the pull, which feels kinda lame but i feel this would be a neet addition, maybe could have mechanics of its own, if you take damage you lose grip, etc
Sorry if i clog up suggestions, i just wanna separate them from one another and they sorta just keep coming up in my head as i go, game development n all that

**Comment by nonamecrackers2** [comment]
While this seems pretty cool not sure how it would fit into the mod, and the feasibility code-wise

**Comment by GrandmaPork** [comment]
here's a mod that allows you to wall hang [https://www.curseforge.com/minecraft/mc-mods/wall-jump]

**Comment by ShadeKage** [comment]
Okay, another idea instead of that, maybe you can fishing rod entities out of the beam? lol

**Comment by nonamecrackers2** [comment]
With how the pulling system works at the moment I don't think the fishing rod idea would work very well. If a mod does what you want however I don't see a need to implement it myself.
