### ISSUE TITLE
Flash from F-Bomb goes over HUD

### ISSUE THREAD

**Issue by SocksyBoi** [nonamecrackers2/crackers-wither-storm-mod#256]
I like the flashbang effect that the Formidibomb gives when it goes off, but I think it should go over the hotbar, cursor, current effects, and things like that when it explodes to make it more immersive.

**Comment by nonamecrackers2** [comment]
It actually does this in the latest 1.18 and 1.19 versions if I’m not mistaken

**Comment by SocksyBoi** [comment]
oh, for some reason it doesn't work for me. ill try to get it working tho!
