### ISSUE TITLE
A configuration issue

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#257]
**Minecraft version**
1.18.2

**Mod version**
The version of the mod you are using

**Describe the bug**
Whenever you make some configurations on the main screen whenever you open a new one and save that one the unsaved configurations on the main screen are unsaved

**To Reproduce**
1. Open configrations
2. just edit anything on the main screen without saving
3. open a new screen then save

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 versions
