### ISSUE TITLE
Tractor beam fadeout

### ISSUE THREAD

**Issue by Swagboi7** [nonamecrackers2/crackers-wither-storm-mod#259]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

The tractor beams should have a fade around the edges since currently, the Wither Storm's tractor beams just abruptly stop, which can look awkward when you're looking at it from a far enough distance.

**Comment by Thefuzz1234555** [comment]
Duplicate #15

**Comment by nonamecrackers2** [comment]
I personally prefer how the tractor beams look now and it'd be hard implementation wise due to my limited knowledge of how the rendering system works.

**Comment by BluePineappleGuy** [comment]
i think maybe the bottoms of the tractor beams in the void should have a gradient to go transparent, because it looks weird when the storm is far away
