### ISSUE TITLE
【Bug】The chromatic aberration effect will make the glowing effect disappear

### ISSUE THREAD

**Issue by zChenX1** [nonamecrackers2/crackers-wither-storm-mod#26]
Items and mobs near the Formidibomb will not render the glow effect, but turning off the chromatic aberration effect in the settings will display the glowing effect.

**Comment by nonamecrackers2** [comment]
Mod list?

**Comment by zChenX1** [comment]
witherstormmod-1.16.5-1.0.2
OptiFine_1.16.5_HD_U_G8
starlight-1.2
jei-1.16.5-7.7.1.152
InventoryProfilesNext-forge-1.16-1.3.6
InventoryHud_[1.16.2-1.16.5].forge-3.4.1
appleskin-forge-mc1.16.x-2.4.0
Xaeros_Minimap_22.8.2_Forge_1.16.5
XaerosWorldMap_1.22.0_Forge_1.16.5

**Comment by nonamecrackers2** [comment]
I have a feeling it may be something with optifine but I can check

**Comment by zChenX1** [comment]
OK，Hope to find out the cause and fix it soon

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update.
