### ISSUE TITLE
Netherite Command Block Tools

### ISSUE THREAD

**Issue by Swagboi7** [nonamecrackers2/crackers-wither-storm-mod#261]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.
Surprised that no one suggested this in the github already. Feels kind of weird to have command block upgrades for diamond tools and not Netherite.

**Comment by Gaboamau** [comment]
I think it's because in MC:SM, in the final battle against the command block, it is seen that the diamond is used for the model of the sword that is used. Also, searching for netherite in the nether is a bit difficult, making you spend more time in the nether than in the overworld with the Wither Storm.

**Comment by Swagboi7** [comment]
It being difficult to find in the Nether and such is why it would obviously be an optional upgrade and not necessary for the final fight.

I'd see getting the netherite versions of the tools as either something to get after defeating the Wither Storm, or a way to play it a little safer in the final fight.

**Comment by ShadeKage** [comment]
I think of it as a choice, either netherite for more damage and lava proof, or the diamond command block version for infininte durability, like the "elytra or chestplate" delema

**Comment by Swagboi7** [comment]
The diamond command block form is also lava proof, and has higher attack damage. There is basically no reason to get Netherite with this mod.

**Comment by myron-obsolete-account** [comment]
there is a mod that adds command block variants for every tool which are enchantable in survival in the way you do it with diamond tools
https://www.curseforge.com/minecraft/mc-mods/more-command-block-tools/

**Comment by nonamecrackers2** [comment]
Considering that an addon mod has done this, there isn't really a need to have it implemented in the mod itself.

**Comment by NinjaSam5399** [comment]
Well if you want command block tools, go here https://www.curseforge.com/minecraft/mc-mods/more-command-block-tools
