### ISSUE TITLE
Witherstorm regenerating during final fight (optinal feature)

### ISSUE THREAD

**Issue by MrIcecream00** [nonamecrackers2/crackers-wither-storm-mod#264]
**Description of feature**
I think it would be cool if you could add an optinal feature that the Witherstorm regenerates during the final fight (if the fight gets interrupted and you take to long to get back in) by consuming entities or blocks. Maybe after 5-10 Minutes the commandblock turns one stage back and the cracks disappear while the tentacles respawn and the heads go passive again.
(sorry for any wrong grammar, English is not my main language)

**Comment by nonamecrackers2** [comment]
Seems interesting, however I don't think the small amount of people that would actually use this feature would justify the work to implement it.
