### ISSUE TITLE
Wither storm should shoot skulls even on phase 4

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#265]
Okay so to make things a bit more harder and intense the wither storm should shoot skulls at the player still aat phase 4-7 or at least use the skulls to stop the player from running or when the player is far enough away from the tractor beams

**Comment by nonamecrackers2** [comment]
I feel this would become more annoying than challenging, being at the brink of escape and then being blown to pieces by a skull and losing all your stuff.
