### ISSUE TITLE
Custom SM Map AI

### ISSUE THREAD

**Issue by willzsocial** [nonamecrackers2/crackers-wither-storm-mod#266]
Make it so if you are playing in the MC:SM Map recreation, the wither storm acts and functions differently. Normally in the building the Wither Storm spawns in the ORIGINAL game, it just floats up, whereas, in the original, it stays down. Also, many things are done differently with the Wither Storm in actual story mode, so it would be pretty cool if you made it like that.
Of course, altering the AI just by what map it is WOULD be very hard, so it’s perfectly fine if you can’t do it. Good job on making this extremely well-made mod, Cracker!

**Comment by nonamecrackers2** [comment]
I don't think the work to do this would be worth it, especially for just a small percentage of users that would actually use the map and notice a small difference in the AI. Glad you like the mod though!
