### ISSUE TITLE
WS breaking Nether Portals

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#267]
Yes I know that the tentacle going through the portal thing was suggested and refused (I would love to see it tbh but it is what it is). 
I think The Storm should still break the open Nether Portals it crosses paths with in the overworld with it's tentacle for the players not to run away to another dimension.

**Comment by nonamecrackers2** [comment]
How would it break them? Possibly the tentacles but again, at the height the WS is at normally it doesn't seem realistic for the tentacles to be able to reach down that far. I also don't feel this feature would see much noticeable use by players.
