### ISSUE TITLE
Blocky tentacles & ws shape

### ISSUE THREAD

**Issue by willzsocial** [nonamecrackers2/crackers-wither-storm-mod#269]
normally in story mode, when ws reaches stage 4 it gets all of it’s tentacles, but the thing is, the tentacles on there are very blocky, they arent just a few blocks that get smaller as the tentacles reaches its end, it looks like this.
![image](https://user-images.githubusercontent.com/109611385/179790562-ca87818d-93cc-4586-8b6a-cab0dc5aaa41.jpeg)
you can see how the tentacles are blocky. for some reason these change in the later stages, however, when the wither storm is out of frame the blocky tentacles just float and go into frame. (i really hope you know what i mean otherwise this would be very awkward)
Also, in the image you can see how the ws’s shape is less taller and has more structure near the left head.

**Comment by nonamecrackers2** [comment]
Tentacles: #169

That image isn't actually an accurate representation of the WS from MCSM. I don't plan on changing the models.
