### ISSUE TITLE
Fix Themes Evolution

### ISSUE THREAD

**Issue by Loverxzc** [nonamecrackers2/crackers-wither-storm-mod#27]
The music in this mod is wrong. How about making triggers per phase. Let's say... during phases 0-3, a theme plays up to an intense theme. And after 3 plays very intense. I think it won't be that difficult.

**Comment by nonamecrackers2** [comment]
It wouldn't be however the music isn't top priority. I'll leave this open so I can review it in the future.

**Comment by nonamecrackers2** [comment]
I'll be using #227 to track this
