### ISSUE TITLE
Spanish translation for the mod

### ISSUE THREAD

**Issue by pox1016** [nonamecrackers2/crackers-wither-storm-mod#270]
Translating the mod into spanish would be great, I can help, my mother tongue is spanish and I have helped translate a Google Play Store game called "Card-Jitsu" (I say the name to give evidence, not to promote), I I would really love to help this mod and I won't ask for anything in return, my discord is pox1016#1304.

**Comment by nonamecrackers2** [comment]
Translations are welcome! Once you're finish make a pull request then I can review it and add it to the mod
