### ISSUE TITLE
Witherstorm does not properly slow down after evolving between the first phases and phase 4

### ISSUE THREAD

**Issue by NRH2007** [nonamecrackers2/crackers-wither-storm-mod#271]
1.18.2

Version 1.18.2 2.0.1.2
Forge 40.1.68

I started a survival minecraft world with the mod and was doing well until i noticed the wither storm was, somehow, faster than me by a large margin. I couldnt get an exact measurment but the mob is going incredibly fast and is impossible to outrun even on stage four when it should be quite slow and sluggish. I tested further and found that a wither storm summoned at phase 4 will move FAR slower than one that evolves to the same phase, which leads me to beleive that for some reason the storm is not properly slowing down during evolutions.
Note: I was using the mod with several other mods, but none appear to add anything i can think of that would cause the issue. Upon testing without the mods mentioned, the same behavior happened.

1: Spawn a witherstorm normally, via the structure
2: Use a command to force it to evolve thanks to absorbed entities such as /witherstormmod consumedEntities set @e[type=witherstormmod:wither_storm,limit=1] 300000 a few times to get it to phase 4
3: Allow the wither storm to chase you some and notice it is moving very quickly
4: Compare to a witherstorm summoned into phase 4 with /summon, which should be far slower.

https://pastebin.com/pDYbVAnd Log of the events.
Also, i apoligize for the fact this does not have labels, im not quite sure how to add them.

**Comment by nonamecrackers2** [comment]
This is actually intended. When the Wither Storm evolves to another phase, it starts to chase the player. The chasing speed is fast due to what I decided on when beta testing the mod several times.

Also don't worry about the labels; I'm the one who assigns them :)

**Comment by NRH2007** [comment]
ah, so after a while it slows down again?

**Comment by nonamecrackers2** [comment]
Yes
