### ISSUE TITLE
More hallways in the wither storm

### ISSUE THREAD

**Issue by wxjk-1** [nonamecrackers2/crackers-wither-storm-mod#272]
It would be cool if there was more ways to go in the wither storm than just strate and more things in the wither storm.

**Comment by SocksyBoi** [comment]
it would be sick, like veins throughout it

**Comment by Asteroid4** [comment]
I like this idea, makes it a bit more believable.

**Comment by nonamecrackers2** [comment]
We're planning on adding a village hallway type to the bowels

**Comment by watersofnazareth** [comment]
I may eventually make more structures for the bowels hallways or arena in the future, I'll keep this open for now

**Comment by NinjaSam5399** [comment]
Or in each room will have something like withered sculk, withered pillager outpost, withered dripstone cave, withered geodes, withered lush cave, and/or custom places.

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2

**Comment by NinjaSam5399** [comment]
There's even more structures coming.
