### ISSUE TITLE
WS Teeth Bug

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#273]
When close to the Storm, you can see the debris ring through the teeth

I saw this happen on 1.16.5 and 1.18.2

![static teeth](https://user-images.githubusercontent.com/109467942/179809950-bf73307b-802d-4b46-9571-6190ac62a3af.JPG)

**Comment by nonamecrackers2** [comment]
This is just due to how the rendering order works, nothing I can really do about it.
