### ISSUE TITLE
[Suggestion] Add means to change what block is used to summon the storm

### ISSUE THREAD

**Issue by Kevadroz** [nonamecrackers2/crackers-wither-storm-mod#274]
**Description of feature**
Requiring an unobtainable, unbreakable block to summon the storm is quite inconvenient for modpacks that don't want you to summon the storm at the beggining of the game, specially if said block is intended to be crafted. (I don't want players placing command blocks accidentally wherever).

Could you add a block tag that dictates what blocks can be used in place of the command block in the summon structure?

**Comment by nonamecrackers2** [comment]
Will be implemented as a tag in the next 1.18./1.19 release
