### ISSUE TITLE
Witherstorm got turned upside down and  gigantic while "spawning" and then slowly shrank 

### ISSUE THREAD

**Issue by MrIcecream00** [nonamecrackers2/crackers-wither-storm-mod#275]
**Minecraft version**
1.18.2

**Mod version**
1.18.2

**Describe the bug**
I don't exactly know what happend, but I believe it is because of the Invulnerability Time which was set to the maximum. As I already said in the topic the Witherstorm got turned upside down and gigantic while "spawning"

**To Reproduce**
1. Go to the mod settings
2. Click on world options
3. Scroll down to Invulnerability Time
4. set it to max

**Screenshots**
![2022-07-19_19 46 50](https://user-images.githubusercontent.com/109606144/179818233-cde303b7-cf37-4e59-b7f4-9dae9280f4b6.png)
![2022-07-19_19 48 57](https://user-images.githubusercontent.com/109606144/179818275-4f893a81-1e7b-4538-904f-22f4aa9d8dfa.png)
![2022-07-19_19 50 31](https://user-images.githubusercontent.com/109606144/179818290-606dc7b9-921c-4a26-8426-21c7bc90aedf.png)
![2022-07-19_19 50 45](https://user-images.githubusercontent.com/109606144/179818322-58a4c159-8df6-42ce-9fc9-efe4b3df3fbc.png)
![2022-07-19_19 50 54](https://user-images.githubusercontent.com/109606144/179818337-422a9544-46e5-479f-97f2-71bfcd0cc4ef.png)

![2022-07-19_19 51 14](https://user-images.githubusercontent.com/109
![2022-07-19_19 51 26](https://user-images.githubusercontent.com/109606144/179818378-60a29bdf-33c6-46e2-9fdf-dbd3ee4ca514.png)
606144/179818360-14ede88c-7ba2-4471-86e8-bb815d037193.png)

After that he spawned normaly

**Comment by MrIcecream00** [comment]
the mini wither is kinda cute ngl

**Comment by MrIcecream00** [comment]
Tried it again with normal and lower Invulnerability Time first time he startet smaller. And with normal time he spawnend normal.
![2022-07-19_20 08 21](https://user-images.githubusercontent.com/109606144/179819718-c6014d95-acdb-44fa-8142-8f22d3527fb3.png)
![2022-07-19_20 06 08](https://user-images.githubusercontent.com/109606144/179819729-bc5cc308-e110-4612-9264-217e9948c314.png)

**Comment by nonamecrackers2** [comment]
That's pretty funny... Did you modify the invulnerability time of the WS at all?

**Comment by MrIcecream00** [comment]
Yes, when he got big and upside down it was set to an high number, when he spawnend normaly it was lower than 200

**Comment by nonamecrackers2** [comment]
Probably a small oversight on my part then yeah

**Comment by MrIcecream00** [comment]
no problem, I think the mod is amazing, I was just kinda shocked when he became gigantic

**Comment by RandomGithubUser32** [comment]
This happens in vanilla with the regular wither. 
/summon wither ~ ~ ~ {Invul:800}        should summon a tiny wither and
/summon wither ~ ~ ~ {Invul:4000}       should summon a giant upside-down wither

**Comment by nonamecrackers2** [comment]
Really? Huh. I'll fix it for my mod though since the invulnerability time can be easily modified.

**Comment by TaintedBlockk** [comment]
Dinner Bone Wither Storm without Dinner Bone name tag lolll

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release
