### ISSUE TITLE
Ivor's Potion

### ISSUE THREAD

**Issue by pox1016** [nonamecrackers2/crackers-wither-storm-mod#276]
In episode one Ivor had a potion to stop the Wither Storm in case it got out of hand (which it ended up doing) it would be great to implement this potion to stop the Wither Storm in its early stages (when the Command Block is exposed), making it give you only the items used to spawn it, this would be useful in case you didn't want it to appear in a certain place and it would be like an emergency option (you could also make it launch with the crossbow to shoot with more precision).

("Killing" the storm this way should **never** give you the Wither Storm Nether Star, it would just be to **prevent it from causing disaster in a place you didn't want**).

And regarding how it could be made, I'm not so sure, but you could get one in the house where the Wither Storm is to generate it (I see this would be the best way).

**Comment by Gaboamau** [comment]
This has already been suggested several times and I think the creator decided not to add the potion to the mod, talking about not wanting it to appear in a certain place, you can use /kill to kill it more easily.

**Comment by Asteroid4** [comment]
Maybe it could be creative only

**Comment by nonamecrackers2** [comment]
I feel this is slightly redundant as the majority of players will probably never use this. While it could give you the materials to spawn it again, command blocks cannot be placed in survival. This feature will probably only see use on custom maps/worlds and in a multiplayer setting.
