### ISSUE TITLE
Wither Storm's Head hitbox is extremely inconsistent and unpredictable

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#277]
**Minecraft version**
1.19.1

**Mod version**
1.19-3.0-beta

**Describe the bug**
When trying to hit a Wither Storm's head to break its eye, its incredibly inconsistent and random, making it extremely hard to tell where it is and when it wants to hit

**To Reproduce**
1. Get a Bow
2. get sucked in the tractor beam
3. attempt to shoot the Wither Storm's Eye
4. eye breaking is extremely random and incredibly hard to predict

**Comment by nonamecrackers2** [comment]
This works as intended, however I plan on possibly changing this in the future.
