### ISSUE TITLE
Wither Storm/Withered Symbiote Resummoning

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#279]
When the wither storm dies, there's no way to get any more command block books. These books are useful for upgrading diamond tools, and there's no way to get more after the wither storm dies. My idea is to either allow you to summon the Wither Storm after killing it, or to summon the Withered Symbiote.

**Comment by DuskNova** [comment]
Agree. But i still have a question, does witherstorm spawn more than 1 withered symbiote in a single phase? I tried to change the cooling time in the config but the second one doesn't appear.

**Comment by RandomGithubUser32** [comment]
Maybe the structure needed to spawn the wither storm appears again after you defeated the wither storm.

**Comment by Anth1121** [comment]
What if you could use the withered nether star to like make a withered beacon, and then use the withered beacon to like make a command block or something.

**Comment by nonamecrackers2** [comment]
I won't be making the Withered Symbiont summonable after the Wither Storm is dead, but I do plan on making the Wither Storm resummonable #481
