### ISSUE TITLE
CRASH REPORT 1.19

### ISSUE THREAD

**Issue by willzsocial** [nonamecrackers2/crackers-wither-storm-mod#281]
1.19
for some reason, upon opening the game with the mod, it crashes with this; 
![image](https://user-images.githubusercontent.com/109611385/179867349-6286e093-690f-4693-835c-6da7a4a66681.png)
and this had one simple solution:
delete optifine, though i'm happy i can use the mod now, i know this is in beta but i suggest you add compatability optifine. thanks!

**Comment by nonamecrackers2** [comment]
Optifine needs to update to the latest forge. This is something I can't feasibly fix.
