### ISSUE TITLE
Make the witherstorm chase nearby mobs

### ISSUE THREAD

**Issue by fre10** [nonamecrackers2/crackers-wither-storm-mod#284]
The Wither Storm should be able to chase mobs if all players are at least 2000/1000 blocks away.
You could also add it's own targeting system for mobs, which have various priorities.

Example : Human / Humanoid mobs, like Villagers and Pillagers, should have highest mob priority, while chickens would have the least.

This would go well with the other suggestion of having mobs run away from it and would make distracting the storm while building that nether portal slightly more easier.

**Comment by nonamecrackers2** [comment]
I feel this will throw the balance I crafted over development and I feel this isn't necessary. The Wither Storm in MC:SM always followed the amulet, which was held always by players.
