### ISSUE TITLE
Slower head movements

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#285]
In Minecraft story mode, the Wither Storm slowly "scans" an area as it picks up mobs and players https://youtu.be/PMD9DMB8s0U?t=328 (All wither storm moments - Minecraft story mode. 50:23)
I think a cool feature to add would be that when a head picks a new target, it slowly moves towards it rather than quickly switching over. I have been playing in 1.18.2 and I've noticed that whenever I am in range and I peak out of my hiding spot, it instantly locks onto me and pulls me up. This speed could be random because in the video linked above, there were moments where people were sprinting away and the beam was barely catching up to them, but there were also moments where it was barely moving at all.
Another great addition would be for the wither storm to switch targets after a mob has been in it's beam for a long enough time, or if it escapes it (for example, a player throwing an ender pearl). This would go well with the slow head turning as any mob trapped in the beam would be pulled along without falling out as the wither storm looks for it's next victim. Also, at 5:55 in the video linked above, Petra is trapped in the beam for about 20 seconds before it gives up and moves on, since Jessie and Gabriel held her down.
Interpret this how you want, but at 12:03, someone on the right side of the screen in the background gets caught by the witherstorm beam and is held in place for a moment before being pulled in.
I understand that MC:SM is filled with inconsistencies but I believe these features would be great additions to the mod.

**Comment by TostOlabilir** [comment]
I also think the head should move slower because when a single head is sucking in a bunch of mobs all at once, after it eats one or two of them it quickly retargets, making most of the mobs fall to their death.

**Comment by GrandmaPork** [comment]
I have noticed that many people have requested a feature where tentacles attack players. If you were to do this, I think it could be done by somehow allowing the wither storm to extend it's reach up to a certain point. Also, while in Gabriel's chamber, the Wither storm was able to smash through the obsidian roof after some time so I think it'd be a fun feature to make it where the wither storm is more aggressive when chasing someone with the amulet.

**Comment by mmiller9196** [comment]
It always seems in this mod that the storm neglects to use its tendrils, so i'm on the "tentacles should attack more" gang

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
