### ISSUE TITLE
Armor Ideas

### ISSUE THREAD

**Issue by OrangeJacketDude** [nonamecrackers2/crackers-wither-storm-mod#286]
I don't know if they're planning to add minecraft story mode armors, but if they do hopefully they have special effects to them.

Here are my ideas for it:
Golden Goliath: Better Weapon Damage, Takes longer to swing weapons, Better Protection, Provides Small Light Radius

Redstone Riot: When worn, can turn on redstone as if you were a Redstone block, being near Redstone gives you better damage and speed and slight health regen, the more Redstone you're near the stronger the buff is.

Ender Defender: 2.5x Defense when fighting Ender Creatures

Swordbreaker: All tools lose durability twice as fast when used against his armor, and cause the weapon to take twice as long to recharge its strike when hitting the armor

Shield of Infinity: Has 3x durability of diamond armor, and a slight increase in protection

Dragonsbane: Falling and hitting the ground, the area you threw the ender pearl and where you land, and an area you shoot with an arrow will spawn a pool of dragons breath that deals damage to other entities that aren't you.

Star Shield: Slight increase in speed, provides minor light, enemies hitting you with their bare hands or a non-enchanted weapon causes them to be lit on fire

Adamantine Impervium: 2x Protection and cannot be harmed by normal arrows

Tim's Armor: Slight increase in protection, strength, weapon recharge, and faster when using a bow or putting an arrow in a crossbow

Golden Apple: Slightly heals you and regens your hunger overtime, impervious to all bad potion effects and wither sickness 

Because armors with effects would be cool and I was bored, honestly I just want new armor to collect with the new weapons in the game so even if it was just better netherite armor I'd mostly be fine with it

**Comment by Gaboamau** [comment]
This was already suggested and I don't think the creator is going to add new armors, since the mod is mainly focused on the Wither Storm fighting and survival, plus it would take a long time to be creating each armor, but if you want armors from the MC: SM, there is already another mod that adds it and although it hardly has everything you mentioned, here is the link:
https://www.curseforge.com/minecraft/mc-mods/mcsa

**Comment by nonamecrackers2** [comment]
^
