### ISSUE TITLE
Wither storm's debris cloud

### ISSUE THREAD

**Issue by Seelk4dooM** [nonamecrackers2/crackers-wither-storm-mod#287]
Make the wither storm debris cloud only appear if its have big brain so it can be more realistic and add a lightning bolt rain effect when the wither storm can be seen in the distance by player.

**Comment by nonamecrackers2** [comment]
I feel interfering with the weather would be troublesome compatibility wise and almost annoying (I personally find rain a bit frustrating). I don't plan on changing the debris cloud and personally prefer the way it is right now.

**Comment by GrandmaPork** [comment]
from my experience, forcing rain and thunder gets annoying *cough cough* engender *cough cough*
