### ISSUE TITLE
Wither Storm Segments

### ISSUE THREAD

**Issue by Seelk4dooM** [nonamecrackers2/crackers-wither-storm-mod#288]
Make wither storm can spawn more segments if gets knocked by another f bomb or gets more debris.

**Comment by Gaboamau** [comment]
I think that two is enough, because in addition to giving the Minecraft server or world more lag, it would not make sense to bombard it every so often to have more segments, since it would create much more destruction and make it impossible to enter the hole.

**Comment by nonamecrackers2** [comment]
^
