### ISSUE TITLE
Higher Quality Debris Ring

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#289]
Higher quality debris ring option for people with good computers/servers (Like a huge cluster of actual blocks orbiting the storm instead of what we have now)

**Comment by Asteroid4** [comment]
I think this could work great!

**Comment by RandomGithubUser32** [comment]
Maybe 3d debris rings?

**Comment by willzsocial** [comment]
mhm!

**Comment by nonamecrackers2** [comment]
While it would look pretty cool, unfortunately I feel this would cause performance issues for people with higher setups. Making the debris rings 3D would cause performance to struggle even further.
