### ISSUE TITLE
Broken Texture for eye

### ISSUE THREAD

**Issue by Loverxzc** [nonamecrackers2/crackers-wither-storm-mod#29]
When a head takes a damage in final battle, It changes texture like this:
![Screenshot_115](https://user-images.githubusercontent.com/105715466/170316035-bb0f02a0-6529-425e-941a-95873456f569.png)

**Comment by Abasthepro** [comment]
Hmm that will be awesome

**Comment by nonamecrackers2** [comment]
Has been implemented
