### ISSUE TITLE
Wither Storm Heads Forcing Player To Die

### ISSUE THREAD

**Issue by Froggovibez** [nonamecrackers2/crackers-wither-storm-mod#290]
**Minecraft version**
1.18.2

**Mod version**
The version of the mod you are using

**Describe the bug**
When a wither storm head pulls you up, another head can start pulling you and the game sometimes wont allow you to shoot it and arrows will go straight through it.

**To Reproduce**
1. Open Up Minecraft
2. Summon the boss
3. Wait until it reaches at least phase 4
4. Go into survival mode
5. Allow the tractor beam to pull you up and shoot it
6. Another head will start pulling you, and you can no longer do anything and will end up dying
If you dont get pulled straight away just try again
**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by nonamecrackers2** [comment]
Someone made an issue about this however I can't find it.

**Comment by ShadeKage** [comment]
Best sorta patch fix for it would be to make it to so when its lets go, the entities in that beam are given a short target immunity from beams

**Comment by RandomGithubUser32** [comment]
I think that it would be better to make it an nbt tag such as "TractorBeamImmune" for players that just got freed from one tractor beam.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release
