### ISSUE TITLE
Option to change background music to story mode music?

### ISSUE THREAD

**Issue by Froggovibez** [nonamecrackers2/crackers-wither-storm-mod#291]
**Description of feature**
Maybe add an option where you can replace the original minecraft music with story mode music in the background? It feels a bit boring just having the boss theme and symbiont theme. It also adds more atmosphere.

**Comment by nonamecrackers2** [comment]
This resource pack should do what you seek: https://www.curseforge.com/minecraft/texture-packs/story-mode-textures
