### ISSUE TITLE
Flesh Block Accuracy

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#292]
After the F-Bomb explosion, the severed parts of The Storm have pinkish flesh blocks around it. In story mode, they glow in the dark and are the same color as the storm's eyes. It would be cool if they were like that in the mod too.

![purpler](https://user-images.githubusercontent.com/109467942/179988354-e8523e07-f7bc-4898-859a-697bb6f7b83b.JPG)

**Comment by nonamecrackers2** [comment]
#63
