### ISSUE TITLE
The Bowels are way too dark

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#293]
The Bowels are too dark to see anything. You have to either light it up or get night vision to see everywhere properly. My suggestion is that either players should get auto-night vision when they enter the bowels (just like getting resistance when falling from the bowels) or the tainted dust and mushrooms should actually emit light like torches.

Also I'm not sure if this counts as an "issue report" or a suggestion. If it's the wrong label, I apologise.

**Comment by Asteroid4** [comment]
What version are you using?

**Comment by TostOlabilir** [comment]
I tried both 1.16.5 and the 1.18.2 versions and found it extremely dark on both of them. Am I doing something wrong?

**Comment by nonamecrackers2** [comment]
I feel night vision and making it brighter removes the moody effect the bowels has. You could always set your brightness to "bright" if you haven't already.
