### ISSUE TITLE
 Immunity on the first phases + tool breaking

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#294]
Since the point of The Storm is NOT to kill it in the first few phases, I think it should be fully invulnerable just like it was on MCSM. Speaking of MCSM, in the first episode Gabriel attacked the command block with a diamond sword and it immediately broke. Something like that could also be added where any tool you attack The Wither just breaks. I doubt anyone who is doing this on survival will even try taking it on on the earlier phases anyway but accuracy to the source material would be neat.

**Comment by nonamecrackers2** [comment]
I don't feel this is entirely necessary (it out-regens any damage it takes) and I don't feel much players would notice this (as you've said). While accuracy is nice, my intent was never to be 1:1, instead to generalize it from MC:SM so anyone could play without knowledge of the game. I also think players would find it a little frustrating seeing their netherite sword smashes to smithereens.

**Comment by juanelgamer456** [comment]
> I don't feel this is entirely necessary (it out-regens any damage it takes) and I don't feel much players would notice this (as you've said). While accuracy is nice, my intent was never to be 1:1, instead to generalize it from MC:SM so anyone could play without knowledge of the game. I also think players would find it a little frustrating seeing their netherite sword smashes to smithereens.

well uuuh im sorry to open this again but...
 https://youtu.be/5eVpk7xV3fU

**Comment by myron-obsolete-account** [comment]
> > I don't feel this is entirely necessary (it out-regens any damage it takes) and I don't feel much players would notice this (as you've said). While accuracy is nice, my intent was never to be 1:1, instead to generalize it from MC:SM so anyone could play without knowledge of the game. I also think players would find it a little frustrating seeing their netherite sword smashes to smithereens.
> 
> well uuuh im sorry to open this again but... https://youtu.be/5eVpk7xV3fU

while the point of the mod basically is to only prepare little to not at all before spawning the storm, this still sucks
I gotta be honest that guy is an... nvm lmao

**Comment by nonamecrackers2** [comment]
I mean if you want to try to defeat the hunchback phases, go ahead. It's not intended but I like allowing people to try things and not fully restrict people to the exact progression of the mod.
