### ISSUE TITLE
temporary Slow Fall/Fall damage immunity upon being freed by the tractor beam

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#295]
**Description of feature**
Some people like me are unable to do a MLG water bucket consistently and it would be nice if you had a breather in order to survive it without instantly dying

**Comment by ShadeKage** [comment]
Or at least a damage reduction, maybe a system that makes it some you'll always land at.. lets say 2 hearts if your above 7 heart, as an example, but i agree with him 100%, but that'd be hard to track most likely

**Comment by Sculkter** [comment]
I’d assume you should be hurt or killed when trying to escape a tractor beam, but it’s understandable. I’d recommend trying to make slow fall pots or use Ender Pearls to escape, or don’t get picked up in the first place!

**Comment by nonamecrackers2** [comment]
I don't want to add a way to prevent fall damage as then the reason to avoid being detected by the Wither Storm would be lost.
