### ISSUE TITLE
Weather manipulation?

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#297]
Since its called the Wither "Storm" and that the blocks spin around it like a tornado, could you maybe make the wither storm control the weather, like in the later stages it would put the whole world in a permanent thunderstorm? This may or may not have been shown in mcsm tho, however there are various thunder sounds that play whenever theres a cutscene that involves the wither storm (example, the cutscene near the end of episode 2

**Comment by willzsocial** [comment]
well, it was in mcsm, and this would be a very good update, so yeah

**Comment by nonamecrackers2** [comment]
I outlined my opinion on this here: #228. While you're suggesting global weather, with the darkened sky feature coming soon I feel this is redundant and would be kind of annoying (atleast in my opinion).
