### ISSUE TITLE
[Customizable entity pickup blacklist] Distant Chase Speed Multiplier + Entity Pickup Blacklist

### ISSUE THREAD

**Issue by BudgieGryphon** [nonamecrackers2/crackers-wither-storm-mod#298]
Distant Chase Speed Multiplier: The Wither Storm's speed will increase by a multiplier of X for every Y number of chunks the target has moved from it. Useful for keeping the pressure up so that fleeing into the Nether to travel thousands of blocks away is only temporarily effective.

Entity Pickup Blacklist: A customizable list of entities that the Wither Storm will not attempt to pick up. Used to provide a temporary solution for mod conflicts in which picking up a certain modded entity crashes the world.

**Comment by nonamecrackers2** [comment]
I feel the chase speed doesn't need to modified, however a customizable blacklist I'll consider.

**Comment by BudgieGryphon** [comment]
Chase speed multiplier would be set at 1 normally, the scenario I can imagine it being useful in is on a server where people have spread out and if one person leads the Wither Storm far away then goes to the Nether the Wither Storm won't take ages to become a threat again for everyone else.

**Comment by nonamecrackers2** [comment]
Entity pick up blacklist will be implemented in the next 1.18./1.19 release
