### ISSUE TITLE
Make the wither storm eat "clusters" of mobs

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#299]
The wither storm seems to only go after 1 mob at a time, making other mobs caught in the beam may eventually fall out of it. Will you change it to where the wither storms target multiple mobs at once, and attempt to keep those mobs in the tractor beam

**Comment by nonamecrackers2** [comment]
I'll be making mobs that aren't targeted specifically by the storm but are being sucked up in the tractor beam automatically get absorbed into the storm when near to implement this feature.

**Comment by Luke7381** [comment]
> I'll be making mobs that aren't targeted specifically by the storm but are being sucked up in the tractor beam automatically get absorbed into the storm when near to implement this feature.

alright

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
