### ISSUE TITLE
Approaches sound

### ISSUE THREAD

**Issue by Loverxzc** [nonamecrackers2/crackers-wither-storm-mod#30]
When the Wither Storm approaches the player, this sound will play:
[The Wither Storm Approaches sound.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/8773096/The.Wither.Storm.Approaches.sound.zip)
.

**Comment by Loverxzc** [comment]
And only if the player catch sight of Wither Storm's silhouette in distation

**Comment by nonamecrackers2** [comment]
I feel like this sound would be too intrusive but could be in combination with music that is played when looking at the WS from a distance. A version of the sound without the WS ambience in the background would be necessary if this feature would come to fruition however.

**Comment by nonamecrackers2** [comment]
Closing as I personally feel this sound wouldn't really fit in.
