### ISSUE TITLE
Withered Symbiont

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#300]
Since the sickened mobs got a texture remake, the withered symbiont should also get a texture remake to look more like the regular sickened zombie.

**Comment by watersofnazareth** [comment]
I could do this but I think the symbiont works how it is, so it's up to Cracker if he wants me to

**Comment by nonamecrackers2** [comment]
I think it's fine, but if @Thefuzz1234555 wants to you could go ahead.
