### ISSUE TITLE
Mod Incompatibility: Danny's Expansion

### ISSUE THREAD

**Issue by YodaDeveloperGames** [nonamecrackers2/crackers-wither-storm-mod#301]
**Minecraft version**
1.16.5

**Mod version**
Cracker's Wither Storm: 1.0.2.4
Danny's Expansion: 1.0.9.1

**Describe the bug**
I added Cracker's Wither Storm to my modpack which included Danny's Expansion and it crashes during world loading/creation (it reaches 100%, then it saves and crashes). The issue persists with only Cracker's Wither Storm and Danny's Expansion.

I'm guessing based on the log that the blindness effect is not able to apply to the Danny's Expansion accessories GUI?? (if the blindness effect exists I haven't even played the Wither Storm mod yet lol)

**To Reproduce**
1. Download Cracker's Wither Storm and Danny's Expansion
2. Launch the game
3. Create a new world
4. Crash :(

**Crash Reports / Logs**
https://pastebin.com/icdsYCry

**Screenshots**

**Comment by nonamecrackers2** [comment]
This was reported before and it almost looks like an issue with Danny's Expansion. I'm not sure how to fix this.
