### ISSUE TITLE
Formidibomb breaks fake death when blowing up exposed command block (1.19 beta)

### ISSUE THREAD

**Issue by bestgamer1012345** [nonamecrackers2/crackers-wither-storm-mod#303]
When I blow the command block up with the Formidibomb in the fake death, it breaks it and when I did it, the wither was shown to be dead but the beams were working for a second and then they went invisible. They still work while it's in this bugged state though, but invisible.

Not sure if this bug is in the 1.18.2 version, haven't tested that version yet.

I'm sure it's a bug because I was able to replicate it multiple times on multiple worlds.

**Comment by nonamecrackers2** [comment]
Similiar to #162, however I'll leave this open.

**Comment by nonamecrackers2** [comment]
Fixed in all versions
