### ISSUE TITLE
When using FTB Quests, Observation quest type, and putting "witherstormmod:wither_storm ~ ~ ~ {Phase:1}", game crashes.

### ISSUE THREAD

**Issue by er1cw05** [nonamecrackers2/crackers-wither-storm-mod#304]
Title doesn't cover full bug.

To put it short, the following error code appears when:
- You use FTB Quests
- You use the "Observation" quest type.
- You set the query to observe as "witherstormmod:wither_storm ~ ~ ~ {Phase:1}"
- You set the tag to "entity_type_tag"
- (Unknown if related) You set the time to "10"

You receive the following crash message after the world saves:
> The game crashed whilst unexpected error
> Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: witherstormmod:wither_storm ~ ~ ~ > {Phase:1}
> Exit Code: -1

Attached is the **full** crash log. If this is just an error with FTB Quests and I need to find an alternative quest mod, just let me know so I can replace it.

The idea was that you'd observe Phase 0 and Phase 1 of the Wither Storm for 10 seconds, however, it's hard to set up the quests for this correctly since there's not many NBT tags for quests. Especially since the only one I have is for "Advanced Entity Kill" and that's for killing an entity with a specific NBT tag, not observing said entity.

[crash-2022-07-20_19.20.11-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9155150/crash-2022-07-20_19.20.11-client.txt)

**Comment by er1cw05** [comment]
Update to the crash issue:

It happened again but I didn't even edit any quests this time and started a new world in creative.

> The game crashed whilst unexpected error
> Error: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: witherstormmod:wither_storm ~ ~ ~ {Phase:1}
> Exit Code: -1

Same error code as last time, no new information from there. I'll try looking in the quest book and deleting said quest if it's there
[crash-2022-07-21_00.35.52-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9156167/crash-2022-07-21_00.35.52-client.txt)
.

**Comment by nonamecrackers2** [comment]
You can't include a character other than a-z0-9/._- as described in the crash report. I'm not sure how FTB quests work but this isn't an issue with the mod.
