### ISSUE TITLE
Withered Symbiont Spawning

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#305]
Currently, the withered symbiont pops out of nowhere when you approach the wither storm at the end of phase 5. Instead, it would be cool if the withered symbiont falls out of the wither storm or a tentacle lowers the withered symbiont to the ground.

**Comment by Asteroid4** [comment]
This is a good idea

**Comment by nonamecrackers2** [comment]
In my opinion I prefer the current system, as you're meant to try to explore around carefully to try to find it.

**Comment by RandomGithubUser32** [comment]
Maybe a spawning animation for the command block boss fight or if it spawns in front of you.
