### ISSUE TITLE
Make Wither storm tentacles just like in mcsm

### ISSUE THREAD

**Issue by witherstormfan87** [nonamecrackers2/crackers-wither-storm-mod#306]
Make wither storm tentacles more blocky. 

1.16.5

**Comment by witherstormfan87** [comment]
![IMG_20220721_090717](https://user-images.githubusercontent.com/108914903/180108061-d676fc50-3302-4f2a-9e4a-c183d005639d.jpg)

**Comment by willzsocial** [comment]
i mean, i suggested this then my issue thing got deleted, so...

**Comment by nonamecrackers2** [comment]
#169
