### ISSUE TITLE
1.12.2 Support

### ISSUE THREAD

**Issue by Seelk4dooM** [nonamecrackers2/crackers-wither-storm-mod#307]
Make a 1.12.2 version please

**Comment by watersofnazareth** [comment]
No

**Comment by Seelk4dooM** [comment]
> No

Why no?

**Comment by willzsocial** [comment]
> > No
> 
> Why no?

cracker CLARIFIED, that he wont be porting to older versions on the curseforge page. please do not ask why as there is no reason provided.
