### ISSUE TITLE
Super TNT and F-Bomb recipe change

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#309]
I know this mod isn't supposed to be a 1:1 replica of story mode but the original recipe for the formidi-bomb in the game is "super tnt in the middle and gunpowder all around". I know that you added blaze powder to make it harder for players to craft such a deadly weapon and I agree with that decision, but since we never see the Super TNT crafting recipe in MCSM, you can just swap the gunpowder in its recipe with blaze powder, and revert the f-bomb recipe to the original. I think it would be a neat addition.

![jesse dont forget](https://user-images.githubusercontent.com/109467942/180193738-2050d01e-b391-4e8d-8363-73cbad819863.jpg)

**Comment by Loverxzc** [comment]
Nether - 😭

**Comment by nonamecrackers2** [comment]
I don't think this change is necessary and will just confuse players.
