### ISSUE TITLE
Safe You're Teammate

### ISSUE THREAD

**Issue by Loverxzc** [nonamecrackers2/crackers-wither-storm-mod#31]
If the player is caught by Tractor Beam, the player can be saved by pressing the button and spammed. So player can even build a pyramid of rescues from players.
![Screenshot_116](https://user-images.githubusercontent.com/105715466/170340210-12c1df30-e412-4a01-868e-23ca35d5c632.png)

**Comment by nonamecrackers2** [comment]
This doesn't fit in with the theme of the mod or with I want the mod to be exactly, and the pyramid of players will be hard to replicate in Minecraft. Thanks for the suggestion though

**Comment by BluePineappleGuy** [comment]
> This doesn't fit in with the theme of the mod or with I want the mod to be exactly, and the pyramid of players will be hard to replicate in Minecraft. Thanks for the suggestion though

there should be some way to grab on to something or someone to delay the beam and give you time to distract it. maybe if grabbing or holding on to some sort of block, it would be 3 times as likely to become a block cluster though, to make it less OP
