### ISSUE TITLE
a usage for amulet

### ISSUE THREAD

**Issue by antivoid66** [nonamecrackers2/crackers-wither-storm-mod#311]
**Description of feature**
the amulet can be used with withered star to create a super beacon

**Comment by darthvader45** [comment]
Kinda wondered why the amulet was a 1.18 exclusive, but eh.  I'll just beat it once in 1.16.5, then move on to 1.18 and test the newer version out.

**Comment by nonamecrackers2** [comment]
Forge dropped support for 1.16.5, and porting features between 1.16.5 and 1.18.2 isn't worth my time

**Comment by darthvader45** [comment]
Ah, that's all right.  Got the 1.18.2 version, so at least I can see it.
