### ISSUE TITLE
wither storm softlock (kind of)

### ISSUE THREAD

**Issue by randomIdIdoT** [nonamecrackers2/crackers-wither-storm-mod#312]
1.18.2

witherstormmod-1.18.2-2.0.1.1.jar

cant kill wither storm the normal way and have to use /kill

**To Reproduce**
1. enter wither storm bowel
2. i try to /kill the command block because i dont want to do all the fighting to kill the witherstorm
3. the game doesn't trigger cutscene and doesnt warp me out of the bowel - i jump out - the wither storm doesnt die and i have to /kill the witherstorm to get rid of him

**Crash Reports / Logs**
none

**Screenshots**
none

(idea how to fix)
set a trigger if the command block dies in any way the game force kills the wither storm and warps me out)

**Comment by Asteroid4** [comment]
/kill-ing the wither storm dosn't work, you need to do it yourself, as the command block being struck with a command block tool triggers some code that is needed for the ending to work.

**Comment by randomIdIdoT** [comment]
i know how the mod works and also with the code/sht but just add if it dies (in any way) it triggers the cutscene (this also fixes things with the mod avaritia (sword of the cosmos that insta kills ANYTHING (it ignores all armor) so just do that - if u react to this message i will close)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release
