### ISSUE TITLE
Withered Symbiont health slider in config

### ISSUE THREAD

**Issue by BudgieGryphon** [nonamecrackers2/crackers-wither-storm-mod#313]
The Withered Symbiont dies pretty quickly to a full netherite player; in solo survival this isn't really an issue but on servers or with other mods it's a bit disappointing. A customization option for its health would be pretty cool for those who want it to be a bit more challenging.

**Comment by snakeybl00** [comment]
i think thats a great suggestion

**Comment by RandomGithubUser32** [comment]
While the Withered Symbiont is targeting a player, another player can hit the Withered Symbiont from behind, making the Withered Symbiont really easy to kill in multiplayer. A way to prevent this from happening would be great.

**Comment by nonamecrackers2** [comment]
Just realized you can actually do this with attributes, so I'll be closing this.
