### ISSUE TITLE
Wither Storm automatically detects Formidibomb and tries to suck it in

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#314]
**Description of feature**
Rn, getting the Wither Storm to get the Formidibomb is kaizo fake difficulty, as you'll likely die in the process. Its incredibly inconsistent to get the Wither to suck it in without yourself dying too

**Comment by Inonedn** [comment]
Demonstration why its unfair, also relates to the fall damage

https://www.youtube.com/watch?v=qmGQvh2KFe0

**Comment by nonamecrackers2** [comment]
Huh, shouldn't target you when near or have a formidibomb. I'll mark this as a bug instead, not intended.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release
