### ISSUE TITLE
Elixir from MCSM

### ISSUE THREAD

**Issue by DonnerMan** [nonamecrackers2/crackers-wither-storm-mod#315]
I would like for the dev(s) to add the Elixir that Ivor had and tried to defeat the Wither Storm with. Perhaps the Enchanted Command Block Book could be used to create this along with other things.
![image](https://user-images.githubusercontent.com/109768736/180324334-19dac965-27b8-4c6a-84ca-f7735b246cc2.png)
(The Elixir)

Apparently it was going to be used to defeat the Wither Storm in it's early ages, only while the command block is exposed. Perhaps this could be crafted and used inside of the Wither Storm?

**Comment by Gaboamau** [comment]
In suggestion number #65, the creator clarified that he was not going to add the elixir.
