### ISSUE TITLE
Sub-Phases

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#316]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

My idea: There would be a sub-phase, so that stats could change, but not initiate a new phase. For example, phase 3.2 could make the wither storm slightly bigger and somewhat raise health.

**Comment by snakeybl00** [comment]
would it be like how in minecraft story mode it gets bigger every time it consumes a block

**Comment by Asteroid4** [comment]
> would it be like how in minecraft story mode it gets bigger every time it consumes a block

i think it would mostly be used to smooth out the transition from phase 3 to 4, but not every block would make it grow.

**Comment by Anth1121** [comment]
Yea. i feel like when it transitions from phase 3 to 4, its just kind of, sudden. Maybe a phase 3.5 could involve the heads summoning off it while it gets big, for example when the storm breaks through the roof in EP1, Only 2 heads are visible and then the 3rd comes out of it from the bottom.

**Comment by myron-obsolete-account** [comment]
similar to #90
