### ISSUE TITLE
hole taking to long

### ISSUE THREAD

**Issue by snakeybl00** [nonamecrackers2/crackers-wither-storm-mod#317]
**Minecraft version**
1.18.2

**Mod version**
newest

**Describe the bug**
the hole is taking to long to spawn i have set the max to one minute if u have command tool wich i do but it is taking so long.

**To Reproduce**
1. change settings to max 1 minute if u have command tool
2. summon the storm
3. set it to phase 7'
4. the hole will take forever to appear

**Comment by nonamecrackers2** [comment]
Are you sure you're using the latest (2.0.1.2?)

**Comment by ribwayy** [comment]
This also happened to me.

**Comment by nonamecrackers2** [comment]
Took a look and there is actually a random (up to 4 minutes) added to the config value, so this is likely what happened.
