### ISSUE TITLE
Wither sickness display

### ISSUE THREAD

**Issue by DiamondWalker** [nonamecrackers2/crackers-wither-storm-mod#319]
There should be some kind of meter or visual effect to tell you how close you are to developing wither sickness. It's a very confusing mechanic. I spent 10 to 30 minutes underground under the storm yet I never got any signs of sickness. I'm still not sure if I was just about to get it or was somehow not being affected.

P.S. It might be a good idea to make wither sickness kill plants and crops. Maybe I'm missing something but it seems like you could make a farm underground, avoid the sickness in the nether while the wither storm keeps the farm chunks loaded, and never go to the surface.

**Comment by nonamecrackers2** [comment]
Wither sickness is meant to be a bit of a mystery and I don't plan on adding a meter. If there was a meter showing how close you were to contracting the disease, I feel players would just be able to avoid it (this may not be the case, just speculation). If more documentation on how wither sickness works in the mod is wanted, I could always do that.
