### ISSUE TITLE
Idea: F-Bomb consumes crafting table

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#322]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

in MC:SM, when the f-bomb is crafted it automatically places down on the ground, replacing the crafting table.

**Comment by Asteroid4** [comment]
It would also automatically ignite
Maybe

**Comment by EnderPlays123** [comment]
> It would also automatically ignite

Maybe

**Comment by nonamecrackers2** [comment]
Changing this now I feel would confuse players more. If the placed version is already in entity form, there would be no way to move it around, and if it would just place the block form I don't see the point as it'll just leave players confused as to why their crafting table broke.
