### ISSUE TITLE
Idea: Block Clusters fall to ground when wither storm dies

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#323]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

the block clusters the wither storm picks up float in the air when the wither storm dies, my idea is to make them become FallingBlocks.

**Comment by snakeybl00** [comment]
already happens

**Comment by Asteroid4** [comment]
no, they start to float in midair when the wither storm dies, my idea is to make them fall to the ground.

**Comment by nonamecrackers2** [comment]
They already do this. You're probably experiencing lag
