### ISSUE TITLE
Bowels is not loaded at all times

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#324]
**Minecraft version**
1.19

**Mod version**
3.0 beta

**Describe the bug**
I was fighting the command block, and dealt the final blow. I fell out of the bowels, but the wither storm kept going. As soon as I got back into the bowels, I won.

**To Reproduce**
1. Summon wither storm in stage 7, wait for the hole to form.
2. Enter the hole, then deal the final blow.
3. Jump out of the bowels, the wither storm will not die until you next enter the bowels.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
Undying wither storm

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19 release
