### ISSUE TITLE
A question in (version:1.16.5)

### ISSUE THREAD

**Issue by DuskNova** [nonamecrackers2/crackers-wither-storm-mod#325]
Does witherstorm spawn more than one withered symbiot in a single phase? I tried to change the cooling time in the config (all of them are changed to 1) but after killing the first one, the second one are still not spawned. (I have waited about 30 min)

**Comment by nonamecrackers2** [comment]
It can yes. Pretty sure if you adjust the cooldown _after_ the WS set it it won't have an affect.
