### ISSUE TITLE
Ability to save configurations

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#328]
I hate having to manually set configurations world by world so how about we can save it in a file and import it this will save tons of time and make it so much easier for speedruns etc

**Comment by nonamecrackers2** [comment]
If you take a copy of the server config file and put it in the "defaultconfigs" file where you instance is, it'll apply the config to all worlds.
![image](https://user-images.githubusercontent.com/105086648/180586260-4d203197-43e1-4c41-95cc-a3d7a918bd20.png)
