### ISSUE TITLE
Wither Tracker

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#330]
**Description of feature**
A new item that can be crafted with a compass and other materials that will allow you to see how many blocks the Wither Storm is away from you. In addition, the item could also track if there is any wither skeletons nearby.

**Comment by nonamecrackers2** [comment]
Interesting, but why wither skeletons as well?

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2 using the amulet
