### ISSUE TITLE
More uses for sickened mob drops

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#331]
Currently, sickened mob drops are only used to craft golden apple stew. I think it would be cool if sickened mob drops could do more things. For example, withered bones could be crafted into sickened bone meal which could reverse the growth of crops and wither leaves and grass blocks away. Withered flesh could inflict wither sickness if a player consumes it and sickened spiders could drop withered spider eyes that could be a potion ingredient for potions of wither sickness or the regular wither effect. I don't know about the sickened creepers though.

**Comment by GrandmaPork** [comment]
Sickened gunpowder could be used as a fuse. Like, burn one end and it slowly travels to the end of the trail. Not much use to it but could be neat. Maybe it could drop a special type of gunpowder used to craft the super tnt or fbomb. This could make it so players can only craft the fbomb once the wither storm has been summoned and stuff

**Comment by RandomGithubUser32** [comment]
Yeah, that sounds cool.

**Comment by RandomGithubUser32** [comment]
The mod already has tainted dust so having sickened creepers drop tainted dust and giving tainted dust more uses could work.

**Comment by nonamecrackers2** [comment]
Withered spider eyes will be added in the next update. Leaving the rest out for now
