### ISSUE TITLE
Sickened Phantom

### ISSUE THREAD

**Issue by IntrovertedGamer** [nonamecrackers2/crackers-wither-storm-mod#332]
Simple enough, a Phantom infected by Wither Sickness that spawns from the Withered Symbiont and Command Block, they inflict the Wither status affect for a few seconds (Not sickness, just the regular wither status affect)
Both boss fights mentioned here only spawn 3 at a time, when killed they drop their membranes like regular Phantoms.

**Comment by RandomGithubUser32** [comment]
The mod already makes phantoms orbit the wither storm so if a phantom orbits the wither storm for a long period of time, it should turn into a sickened phantom.
