### ISSUE TITLE
music overlapping

### ISSUE THREAD

**Issue by jasongi33** [nonamecrackers2/crackers-wither-storm-mod#333]
**Minecraft version**
1.19

**Mod version*
witherstormmod-1.19-3.0-beta.jar

**Describe the bug**
the boss music will sometimes overlap with the normal minecraft music

**To Reproduce**
1. summon witherstorm
2. See error

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release
