### ISSUE TITLE
[Suggestion] Hardcore Mode Storm

### ISSUE THREAD

**Issue by Pakins0** [nonamecrackers2/crackers-wither-storm-mod#334]
This suggestion is about a new setting in the config that turns on Hardcore mode, a much more difficult version of the Witherstorm, to give greater challenges to those that have already completed the mod. Some changes will just be regular config edits, while others may require some new features to be added. Depending on how hard cracker would want this to be, some of these or even all of these features could be added. Along with that, recommended values will be paired when needed.

Some example features that might occur
**Spawning:**
Items can't be picked up until the storm has spawned
Witherstorm spawns in half the time
**Gameplay**
Witherstorm is faster (x2)
If the player sleeps, the witherstorm advances roughly the amount it would in the remaining night
Witherstorm never gets distracted
Witherstorm always prioritizes players
Witherstorm can target invisible/shield up players
Witherstorm block consumption is increased, so hiding underground isn't safe even in early destroyer phases (if its too hard turn down the growth speed to balance)
If a player goes into a tractor beam targeting another mob, the storm will immediately target the player instead.
Formidibomb instantly becomes an entity after crafting
Command block tools are equivalent to their diamond counterparts, except for the ability to kill the block in the end.
Phase 6 already has all 9 heads
Phase 7 has more severed storms (3 or 4)
Withered Symbionts are always in their harder stage (less than 50% hp)
Withered Symbionts have more health (x2 or x2.5)
Witherstorm can still target players fighting a symbiont, but have a rare chance of actually targeting
Wither Sickness takes effect faster. (x2 or x3)
Wither Sickness degrades armor (1 durability every 10 seconds per effect level of the sickness)
Wither Sickness health debuff is more effective (x2)
**Final Boss**
Command block becomes aware of your presence as soon as you enter the main room, and begins a normal phase 1 of the fight
Once damaged, phase 1 will play out again, but with more mobs, (x2 or x3) and the phase 2 symbiont will also spawn
Once damaged again, tentacles will spawn, and there will be more of them (x2) with more health (x1.5).
Once damaged the third time, more heads will spawn (4) and they will have more health (x2)
Once damaged for what should be the final time, the command block will have a sliver of HP and all previous phases will play out at once, and all mobs, tentacles, heads, and the second symbiont must be defeated before the command block can be damaged again.
When the storm is defeated, you will get a a new type of nether star (maybe divine nether star?), the ultimate trophy of the mod.

I know this is a lot to add, but given the fact that once you've beaten the mod once there isn't much reason to play again, giving an extreme challenge like this would definitely add more content to the mod. If all of these changes are too impossible, cracker could only add some of them to make it only slightly more challenging, or add all of them for a near impossible experience.

**Comment by watersofnazareth** [comment]
This would be a hassle to implement and wouldn't make too much sense in the mod, Hardcore minecraft is supposed to be like regular survival
