### ISSUE TITLE
Sickened Creeper Nerf/Are way too powerful

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#335]
**Description of feature**
For some reason, Sickened Creepers do way too much damage, so much that even a decent distance from them can insta kill diamond armor players. In fact, they're stronger than Charged Creepers

**Comment by Sculkter** [comment]
From what I’m aware, sickened creepers are supposed to be that deadly. There are work arounds, so you don’t have to go into physical combat with the creeper. Or just use a shield. That works too.

**Comment by nonamecrackers2** [comment]
Yeah. I'll be leaving the sickened creepers as they are for now.
