### ISSUE TITLE
Tractor Beams can carry entities deep underground out of sight

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#336]
**Minecraft version**
1.19

**Mod version**
latest

**Describe the bug**
When deep underground, Tractor Beams can pick up entities that are usually out of range, resulting them in falling to their deaths when the ceiling is high enough

**To Reproduce**
1. Go underground
2. Summon a wither storm
3. Wither tractor beams can target entities deep underground

**Crash Reports / Logs**
N/A

**Screenshots**
N/A

**Comment by FrozenDragon0** [comment]
This would definitely be a nice fix, as it's quite odd being sucked up by a tractor beam along with other entities despite the fact your deep underground with plenty of blocks above you that should block you from being pulled.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release.
