### ISSUE TITLE
Stuck on top of Wither Storm in early phases

### ISSUE THREAD

**Issue by Tinn04** [nonamecrackers2/crackers-wither-storm-mod#337]
Minecraft version 1.19

Mod version 1.19-3.0-beta

When the boss is in the early phases and uses its tractor beam to pull me I can't seem to ever hit its gazer. Once I get pulled all the way in I just get stuck on top of the Wither Storm forever.

Step one:
Get to the phase where the Wither Storm has one head

Step two:
Get pulled by the tractor beam and attempt to shoot its head multiple times but ultimately failing

Step three:
Once pulled all the way just sit there and enjoy the ride. Eat golden apples to live.
![2022-07-22_20 23 21](https://user-images.githubusercontent.com/69121624/180588778-6fb47a49-6915-41c1-9a4d-2e67c56692ef.png)

**Comment by nonamecrackers2** [comment]
It is possible to hit it however due to the randomness that is the injury system it’s extremely unlikely. It not killing you is probably because of your gear, and the WS bite attacks may need to bypass armour.

**Comment by nonamecrackers2** [comment]
Should be fixed in the next 1.18/1.19 release. Biggest change is just hitting the WS (not even the head itself) will have a possibility of causing a head injury.
