### ISSUE TITLE
Change the textures of command block weapons

### ISSUE THREAD

**Issue by DuskNova** [nonamecrackers2/crackers-wither-storm-mod#338]
I think changing the command block weapons' textures into the storymode ones are cooler. (except the command block sword, it's already the storymode one) 
The command block axe and command block pickaxe in the storymode are so cool !
Pictures of them:
![image](https://user-images.githubusercontent.com/108167233/180589734-846aa68c-c474-4d0a-90c5-67e327d931a6.png)
![image](https://user-images.githubusercontent.com/108167233/180589751-bcf0f516-d0ef-40bd-9c69-90f9b838cd78.png)
![image](https://user-images.githubusercontent.com/108167233/180589762-80d5d04e-c6f2-4b08-8038-3303feabe487.png)
![image](https://user-images.githubusercontent.com/108167233/180589781-6152260d-7171-47e8-b544-5f1be6bb55c4.png)

**Comment by watersofnazareth** [comment]
The textures aren't gonna be changed, I've talked to Cracker about this before

**Comment by DuskNova** [comment]
> The textures aren't gonna be changed, I've talked to Cracker about this before

Oh, I've missed that

**Comment by DuskNova** [comment]
Oh, sry. I've missed that

**Comment by nonamecrackers2** [comment]
Textures aren't changing as they're meant to emulate vanilla minecraft

**Comment by Steve982950** [comment]
This mod ISNT Supposed to be a 1:1 recreation.

If you want new weapon textures, here is the link to the Texture Pack

https://www.curseforge.com/minecraft/texture-packs/lucasdotjes-story-mode-storm
