### ISSUE TITLE
Wither Storm ignores the Formidibomb.

### ISSUE THREAD

**Issue by Smash-Bash** [nonamecrackers2/crackers-wither-storm-mod#34]
I tried many, many times in the latest version (1.0.2) to F-Bomb the Wither Storm, but the boss wouldn't notice it. It would just explode on the ground.

Also to note is that I was trying in both Creative and Survival using Formidibombs obtained from the Creative Inventory and lit with a flint and steel, as at the time, I didn't know how to craft them.

**Comment by nonamecrackers2** [comment]
The wither storm can only be formidibombed at the end of phase 5. Commands to do so are listed under a spoiler on the curse page
