### ISSUE TITLE
Enabling fall damage.

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#340]
When you fall out of the wither storm in the final boss battle, you are given resistance so you don't die of fall damage. I think it would be great to have an option to disable this for players that can mlg water bucket under such conditions. After all, Ruben the pig died of fall damage after falling out of the wither storm.

**Comment by Asteroid4** [comment]
I’d love to be able to mlg every time, but yes, it needs to be a config option.

**Comment by RandomGithubUser32** [comment]
Yeah, it should be an option that is turned off by default.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
