### ISSUE TITLE
Command enchanted items

### ISSUE THREAD

**Issue by SplendidSuperGithub** [nonamecrackers2/crackers-wither-storm-mod#341]
Make the command book enchant, similar to other enchanted books.
(Sorry if I have bad grammar, I’m not good speaking English)

**Comment by nonamecrackers2** [comment]
What would the enchantment be? Regardless that isn’t the purpose of the books and I don’t plan on making them enchantments.

**Comment by RandomGithubUser32** [comment]
I think that they meant for the book to be applied using the anvil instead of the smithing table.

**Comment by nonamecrackers2** [comment]
Ah that makes more sense. Regardless I’ve outlined my opinion on the idea here anyway: #362
