### ISSUE TITLE
Wither storm and piglins

### ISSUE THREAD

**Issue by SplendidSuperGithub** [nonamecrackers2/crackers-wither-storm-mod#342]
This is a issue if you see the Minecraft logic. In Minecraft when the piglin see the wither boss or wither skeletons, they try to kill wither boss or skeletons, piglins and withers are natural enemies. Then piglin, have to tri kill wither storm or withered symbionts and withered mobs.

**Comment by watersofnazareth** [comment]
I believe you already requested this #180

**Comment by nonamecrackers2** [comment]
I dont feel this is necessary, considering the magnitude that is the wither storm
