### ISSUE TITLE
Update the mod in 1.16.5

### ISSUE THREAD

**Issue by DuskNova** [nonamecrackers2/crackers-wither-storm-mod#344]
Could you plz update the mod in 1.16.5? I like the update in 1.18.2 very much but it's too laggy for my PC to run. ( Especially when loading the chunks ) 
Thank you very much.

**Comment by watersofnazareth** [comment]
This won't be done, 1.16.5 will only be getting bug fixes

**Comment by DuskNova** [comment]
Wow, ok then.
