### ISSUE TITLE
[Suggestion] Configurable block cluster pick up rate depending on phase

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#345]
Basically, just making it so depending on the Phase of the Wither Storm it could pick up more blocks like 1-3 just getting slightly faster, then 6-7 much faster

**Comment by nonamecrackers2** [comment]
There’s actually two sliders in the server config to configure the cluster pick up rate for phase, one for phase 0-3 and other for 4-7 (unless you want another slider for phase 6-7?)

**Comment by watersofnazareth** [comment]
What I was meant was more of a per phase pick up rate tho that may be excessive, it just usually feels better when it picks up faster in phases 6-7

**Comment by nonamecrackers2** [comment]
I'll add another slider for phase 6-7, as yeah more sliders would be excessive

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
