### ISSUE TITLE
cant use the witherstorm commends

### ISSUE THREAD

**Issue by Formed16** [nonamecrackers2/crackers-wither-storm-mod#346]
**1.19**

**1.19 forge**

**when i try to use one of the witherstorm commends the "name" of the storm dosent apear**

**Comment by nonamecrackers2** [comment]
Are you on server and if so are you opped? Also make sure you’re typing the command right, /witherstormmod

**Comment by Formed16** [comment]
> Are you on server and if so are you opped? Also make sure you’re typing the command right, /witherstormmod

im on single player world and using the autofill to write it

**Comment by nonamecrackers2** [comment]
Make sure the syntax is right. The correct commands are under the “for creative users” spoiler on the mod page
