### ISSUE TITLE
Sickened Creepers and Spiders can spawn with armor

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#347]
**Minecraft version**
1.19

**Mod version**
Latest

**Describe the bug**
Sickened Creepers and Spiders can drop equippable armor, as well as spawning with it equipped
**To Reproduce**
1. Fight a Withered Symboint
2. Let it summon mobs
3. Spawns Creeper/Spider, armor clinks signify equipment

**Crash Reports / Logs**
N/A

**Screenshots**
N/A

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release.
