### ISSUE TITLE
game lagging tremendously when summoning witherstorm

### ISSUE THREAD

**Issue by DrDestructionTrex** [nonamecrackers2/crackers-wither-storm-mod#349]
when ever i summon the witherstorm now it makes my game lag so much i cant even do /kill. this happened after 3 days of playing with the mod. ive disabled mods to see if they were the issue and they weren't. im using the 1.18.2 witherstorm mod in 1.18.2.

**Comment by TaterKing** [comment]
Is it right when you summon it? or is it like 30 seconds after. And are you using shaders as well?

**Comment by Gaboamau** [comment]
I think this always happens, because this also happens to me and I think the creator said that at the beginning, when the Wither Storm is summoned, the game is delayed for a moment, since they have to load the phases, the dimension, among others things, but in the end the game will be fine for you.

**Comment by nonamecrackers2** [comment]
When the Wither Storm is summoned it locates the bowels arena it'll use which lags the game temporarily. It does crash some players games and I am tracking the issue here: #23
