### ISSUE TITLE
New Options for Formidibomb Explosion

### ISSUE THREAD

**Issue by Smash-Bash** [nonamecrackers2/crackers-wither-storm-mod#35]
Could you please add options to disable the ear-ringing sound and/or the white flash when the Formidibomb explodes?

**Comment by Loverxzc** [comment]
He will have to do animation, and the whole impression is lost

**Comment by Smash-Bash** [comment]
The ear-ringing sound can get quite obnoxious, and I don't want to wait through a white screen so I can destroy my world with F-Bombs in Creative mode.
If you want to keep up the impression, you can make the white screen disable option exclusive to Creative if you want.

**Comment by Loverxzc** [comment]
Just press F1 and turn the volume down

**Comment by nonamecrackers2** [comment]
There is already an option to disable the white screen, and yes a config option to disable the ear ringing has crossed my mind.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next update
