### ISSUE TITLE
Ivor potion 

### ISSUE THREAD

**Issue by Lauchingmiau** [nonamecrackers2/crackers-wither-storm-mod#350]
**Description of feature**
In minecraft Ivor had a potion what could "destroy the creature" (tbh idk what it would do to it). 
You could make a special brewing stand what could be made on 
Smithing table and obsidian or some new material what u can create 
This potion could be made by choise nr.1.(u can use special brewing stand and witner skull or/and nether star (you do you here XD)) nr.2.(you can find it in start house on 0 0 0 cords(or u can just leave a healing potion, like sorry Axel already stole it ;P)) 3. (Ivor trades it waaat Npcs?!?!!?!?(kinda dump i know)) 

Potion effects: 
Choise nr.1 (remember the regeneration u gave for 0 phase wither storm? If you will splash it into it, it will lose it) Nr.2. (Simply kills it no fun D:  .)
Nr.3 (Ivor was wrong and this potion makes wither storm stronger, now it absorbs blocks twice faster) Nr.4 (literally every of my suggestions but it will be random) Nr.5 (wither storm becomes smaller... WAIT oh wow CONGRATULATIONS now u have lil wither storm pet owo)

If used on player 
Choice Nr.1 (gives effect "Redstone saturation" now things what need Redstone to open, near you will work coz u give active Redstone aura(idk if its possible to make in code)) Nr.2 (player dies so be careful while throwing it) Nr.3 (you become the target of the wither storm for some time(yes it stronger whan amulet lure)) 

If used on other mob
Nr.1 (why would you use this potion on {mobs name}, idiot(all text is red btw))

I hope you like idea, thank you for reading my essay and for your time :D

**Comment by Gaboamau** [comment]
In suggestion number https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/65, the creator clarified that he was not going to add the elixir.

**Comment by Lauchingmiau** [comment]
> In suggestion number https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/65, the creator clarified that he was not going to add the elixir.

Tbh i cant find it so i hope you are lying, or atless he will change his mind... edit: found he said its now not his priority, well i guess we will see it after a year sad
