### ISSUE TITLE
Wither Storm accelerating despite criteras not being met

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#351]
**Minecraft version**
1.19

**Mod version**
Latest

**Describe the bug**
Regardless of configs and circumstances, the Wither Storm can accelerate randomly and stay as it is

**To Reproduce**
Difficult to reproduce, but it happens even when evolution phase isn't met

**Comment by nonamecrackers2** [comment]
It can accelerate even without evolving. This is intended
