### ISSUE TITLE
Mob Battle Options

### ISSUE THREAD

**Issue by Swagboi7** [nonamecrackers2/crackers-wither-storm-mod#353]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

The Wither Storm is currently not exactly optimal for mob battles for a few reasons:

- It constantly heals (which I have actually seen be fixed via a datapack)
- It cannot be hit from the outside
- The Command Block is not affected by mob enrager staffs from the mob battle mod for whatever reason

I believe some config options to allow the Wither Storm to be damaged normally and disable its constant regen along with allowing the Command Block to be affected by the mob enrager would be some nice additions to the mod for mob battle enjoyers like myself.

**Comment by RandomGithubUser32** [comment]
This has already been suggested.

**Comment by Swagboi7** [comment]
oh

**Comment by RandomGithubUser32** [comment]
However, your third suggestion is completely new.

**Comment by RandomGithubUser32** [comment]
Here is that suggestion btw
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/137

**Comment by nonamecrackers2** [comment]
If you could make a bug report for the mob enrager staff that would be helpful.
