### ISSUE TITLE
Singular tentacle in phase 2

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#354]
Just like in MCSM, the wither storm should have a singular tentacle above its head in phase 2.

**Comment by nonamecrackers2** [comment]
Someone else suggested this however it was rejected, as I feel having a single tentacle is awkward and it does not make sense to change the model now.

**Comment by RandomGithubUser32** [comment]
Maybe make it so that in phase 3, there is one tentacle on top and two tentacles below the wither storm.

**Comment by GrandmaPork** [comment]
the three tentacles looks more weird tbh. Yeah the first one looks awkward but I think what you currently have is weirder
