### ISSUE TITLE
Sculk interaction?

### ISSUE THREAD

**Issue by BaberahamLincoln** [nonamecrackers2/crackers-wither-storm-mod#355]
What if upon absorbing a certain amount of sculk catalysts (a rather small amount, since most storms will never reach the deep dark) the WS would gain sculk growths on its body?
some of my ideas for what this could do:
wardens would be passive to tentacles, command blocks, symbiont, hostile wither sickness infected mobs, and all other wither storm related mobs?
when the wither storm drops down after being formidi-bombed it could spread sculk onto the land it falls on.
there would be sculk growths inside the bowels of a sculk-infested wither storm, making the final battle more dangerous.
maybe a chance for sculk catalysts to rain from the wither storm, land on the ground, and infest a small area around them?
sculk blocks created by the wither storm could have a hybrid sculk-wither texture

**Comment by nonamecrackers2** [comment]
As I described in another post, I plan on keeping the WS and sculk separate.
