### ISSUE TITLE
Command Tool should break after Command Block defeat.

### ISSUE THREAD

**Issue by GoldInvestor1006** [nonamecrackers2/crackers-wither-storm-mod#356]
After you deal the final blow to the command block, the tool should break. It was confirmed that was what happened to the command block tool in Minecraft: Story Mode.

**Comment by IntrovertedGamer** [comment]
I feel like the symbiont that spawns inside the Witherstorm should at least drop another book then if this feature actually gets added.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
So if you wanna keep the tool then you need 3 books and only fight the wither storm with your non valuable one so if this gets added only the one you used should break

**Comment by nonamecrackers2** [comment]
I feel changing this out of the blue will upset and confuse players, especially with no way to regain the tools.
