### ISSUE TITLE
[1.16.5] [1.0.2.4] "shouldSpawnStartingHouse = false" not working

### ISSUE THREAD

**Issue by Subthy** [nonamecrackers2/crackers-wither-storm-mod#357]
**Minecraft version**
1.16.5

**Mod version**
1.0.2.4

**Describe the bug**
Line in config "shouldSpawnStartingHouse = false" is not working and still spawning the structure

**To Reproduce**
1. Disable "shouldSpawnStartingHouse"
2. Start the world
3. Teleport to 0 0

**Screenshots**

![image](https://user-images.githubusercontent.com/73344257/180642658-81c27aa8-e1a5-45d0-885b-407b9e197665.png)
![image](https://user-images.githubusercontent.com/73344257/180642671-70979531-b1b8-4817-b616-4961af5bef25.png)

**Additional info**
I am using Biomes O Plenty world generation

**Comment by BelgianDev** [comment]
Is this fixed? I'm on 1.18.2 and I want to disable this house

**Comment by Subthy** [comment]
> Is this fixed? I'm on 1.18.2 and I want to disable this house

Nope. I suggest messing with the structure file and making that it spawns empty. That is what I did.

**Comment by nonamecrackers2** [comment]
Was looking into it and there doesn't seem to be anything I can do to fix this. There must be some internal overriding in BOP that's causing the structure to generate, even though /locate shows up empty indicating it is _technically_ disabled.
