### ISSUE TITLE
the wither storm's tentacles should be utilized by the wither storm

### ISSUE THREAD

**Issue by crusherXF** [nonamecrackers2/crackers-wither-storm-mod#359]
in minecraft story mode, the wither storm was seen catching people with its tentacles and even having it go through the nether portal.
So the suggestion is have the wither storm utilize it's tentacles like maybe have it catch players who are in a small area that the wither storm itself can't access or have it even go through the nether portal as an entity that captures you. it might be janky but it is cool.
if this doesn't seem balanced or unfair maybe have an option to disable it?

**Comment by Swagboi7** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/12

**Comment by crusherXF** [comment]
weird I checked all the suggestions and didn't find this, maybe I overlooked it. sorry for requesting the same thing
