### ISSUE TITLE
Cannot Save Replay recording

### ISSUE THREAD

**Issue by KeiBoogie** [nonamecrackers2/crackers-wither-storm-mod#360]
**1.16.5**
The version of Minecraft the mod is running on

**1.0.2.4**
The version of the mod you are using

**Cannot save replay mod file**

**To Reproduce**
1. Download Jei, Jer, Forge 36.2.34, and The Wither Storm Mod
2. Record the entire bossfight
3. Exit out of the world or server and press save replay

**Crash Reports / Logs**
https://paste-bin.xyz/71048

**Comment by KeiBoogie** [comment]
> 

Also, the replay mod version I am using can be found here: https://www.curseforge.com/minecraft/mc-mods/replay-mod-for-forge/files/3548798

**Comment by nonamecrackers2** [comment]
I'm unable to reproduce this issue. Regardless, this appears to be a replay mod issue considering the crash report.
