### ISSUE TITLE
enchanted command block books should be applied using an anvil

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#362]
Since normal enchanted books are applied to an item using an anvil, command block books should be applied using an anvil. This should not be too hard for survival since the starter house already includes an anvil.

**Comment by nonamecrackers2** [comment]
I originally wanted to do this however anvils crafting mechanism was too complicated for me to try to learn how it works and add my recipes into it. Changing it now I don’t feel is very necessary and will probably just confuse players.
