### ISSUE TITLE
Some more post MCSM Episode 4 Stuff? 

### ISSUE THREAD

**Issue by EpikMelonDucky** [nonamecrackers2/crackers-wither-storm-mod#364]
**Description of feature**
Ok, ik noname said he wanted to make it as playable for non MCSM players as possible, I understand. Which is why adding the actual admin npc would be weird, but if there was a giant enderman, giant magma golem, and a prism giant boss, and maybe an npc that spawned it, with a few items from mcsm s2 (The Ocean helmets, maybe gauntlets, The MCSM armor sets, although it'd make it so we'd need the clothing mod I think. Maybe some dimensions, like the white pumpkin dimension, the PAMA dimension, Sky dimension, the dimension under the bedrock (MCSM S2 EP 3 - 4). For structures, maybe the Ocean Temple, Possibly the prison, maybe the sky dimension kingdom, The place where Jesse, and the rest fought the giant magma golem. Some more items could be the Redstone Heart, The eversource, The Flint And Steel, The white pumpkin, more. 

I totally understand how hard this would be to code, so it'd be fine if it couldn't happen,  but it'd be dope.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
Then it would be crackers story mode mod

**Comment by EpikMelonDucky** [comment]
What I mean is to add some bosses, just anything from that, maybe the other things don't need to be added.

**Comment by nonamecrackers2** [comment]
I don’t plan on adding anything else from MCSM to this mod specifically.
