### ISSUE TITLE
Server crash when getting wither sickness

### ISSUE THREAD

**Issue by Weirddudewastaken** [nonamecrackers2/crackers-wither-storm-mod#366]
I am trying to host a server with that mod for my friends and whenever one of us gets wither sickness it just crashes. The forge version is 40.1.68 for 1.18.2 and i am running it on a mohist (forge + bukkit) server with the only plugin being discordSRV. 

Logs have been attached below.

edit: also i cannot apply the wither sickness effect to the player.

[debug.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9181246/debug.log)
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9181247/latest.log)
[crash-2022-07-25_13.53.38-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9181248/crash-2022-07-25_13.53.38-server.txt)
.

**Comment by nonamecrackers2** [comment]
#240

**Comment by nonamecrackers2** [comment]
A temporary fix is to join a single player world before joining the server.
