### ISSUE TITLE
1.18.2 version crashing on world creation

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#368]
1.18.2

If I install the mod with or without optifine it would crash on world creation.

install the mod

launch Minecraft

create world

any kind of world works

game crashes on world creation.

**Comment by nonamecrackers2** [comment]
Crash report is necessary

**Comment by SSgamingYT** [comment]
i run a different launcher but heres the log: https://www.mediafire.com/file/k3tur6etpzbvq28/latest.log/file

**Comment by SSgamingYT** [comment]
it may be linux in general, but ive seen other people without tlauncher and without linux have similar problems.

**Comment by nonamecrackers2** [comment]
Doesn't look like anything is wrong... Maybe you've sent the wrong log? Even if you didn't, looks like generation is happening albeit very slowly, which may be because your setup isn't powerful enough
