### ISSUE TITLE
Game crashes upon world creation (1.18.2)

### ISSUE THREAD

**Issue by PredictableUser** [nonamecrackers2/crackers-wither-storm-mod#369]
Game crashes a few moments after attempting to create a world, it never goes above 0% and attempting to reload the world causes it to crash again.

Exit code message:

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'
Exit Code: -1

List of mods:

feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
jei-1.18.2-9.7.0.209
JustEnoughResources-1.18.1-0.13.1.141
OptiFine_1.18.2_HD_U_H7
repurposed_structures_forge-5.1.14+1.18.2
TravelersTitles-1.18.2-Forge-2.1.1
witherstormmod-1.18.2-2.0.1.2
YungsApi-1.18.2-Forge-2.0.8
YungsBetterDesertTemples-1.18.2-Forge-1.3
YungsBetterDungeons-1.18.2-Forge-2.1.0
YungsBetterMineshafts-1.18.2-Forge-2.2
YungsBetterStrongholds-1.18.2-Forge-2.1.1
YungsBetterWitchHuts-1.18.2-Forge-1.0.1
YungsBridges-1.18.2-Forge-2.1.0
YungsExtras-1.18.2-Forge-2.1.0

**Comment by GrandmaPork** [comment]
Are you sure it's this mod that's causing it? try removing it and trying again if you haven't already

**Comment by PredictableUser** [comment]
> Are you sure it's this mod that's causing it? try removing it and trying again if you haven't already

I have attempted to create the world with only JEI, JER and Optifine included with the mod itself. The game still crashes.

**Comment by PredictableUser** [comment]
> > Are you sure it's this mod that's causing it? try removing it and trying again if you haven't already
> 
> I have attempted to create the world with only JEI, JER and Optifine included with the mod itself. The game still crashes.

I have learned that Optifine appears to be causing this issue. I'm unsure why however.

**Comment by GrandmaPork** [comment]
Yeah Optifine does that. Might be the nbt mod or jer

**Comment by nonamecrackers2** [comment]
Downgrade to the recommended 1.18.2 forge version (40.1.0). Something probably changed  in forge that I haven’t accounted for
