### ISSUE TITLE
Wither Storm Segments Duplicate when chunks are refreshed.

### ISSUE THREAD

**Issue by SimpleWolf** [nonamecrackers2/crackers-wither-storm-mod#370]
**Minecraft version**
1.18.2

**Mod version**
2.0.1.2

**Describe the bug**
Whenever the Chunks the Wither Storm is in are unloaded and reload at Tier 6+, the Wither Storm's Segments will respawn. Every Refresh adds an additional Two Wither Storm Segments.

**To Reproduce**
1. Get Wither Storm to Tier 6
2. Restart the Server or use the command /witherstormmod chunks refresh
3. Witness the Wither Storm Segments duplicate.
4. Watch your server's TPS hit the floor.

**Crash Reports / Logs**
Logs did not show anything relating to the issue.

_I did originally report this bug a while back but this time I found the cause, so go figure_

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release.
