### ISSUE TITLE
Minecraft music and wither storm music combining

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#372]
**Minecraft version**
1.18.2

**Mod version**
The version of the mod you are using

**Describe the bug**
Minecraft music has a tendency to play during a wither storm encounter

**To Reproduce**
1. Turn on music
2. encounter the wither storm for over 10 minutes

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/333

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> #333

💀
