### ISSUE TITLE
Wither storm should pick up formidi bomb in phase 4

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#373]
**Description of feature**
Basically in phase 4 the wither storm can be blown up so honestly the wither storm should pick up the bomb in phase 4

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
I ran out of ideas💀

**Comment by nonamecrackers2** [comment]
This is already implemented
