### ISSUE TITLE
Infinite wither storm duplication

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#374]
**Description of feature**
If we blow up a phase 7 wither storm why can't we get 9 wither storms instead of spawning them myselves 8 severed ones and 1 normal one but eventually there should be some cap or limit so it won't take years to program
Also the wither storms will only dupe if they have 3 heads if they are only 1 headed each blowing them up will do nothing

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
9 wither storms can be phase 9

**Comment by nonamecrackers2** [comment]
Spawning more segments will lower performance and will provide more “fake difficulty” then a fair challenge in my opinion.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> Spawning more segments will lower performance and will provide more “fake difficulty” then a fair challenge in my opinion.

Update: tried this myself by structure blocking one severed one and now I have 11 wither storms in my world
