### ISSUE TITLE
Wither storm edits.

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#375]
1. more faster tentacle movement. with more curve
2. a option in client settings that allows the models to change to look more like the ones in story mode.
3. a option in world settings for length of block clusters to be created
4. larger blocks in the debris clouds (the ones circling the wither storm)
5. blocks to move up to the debris rings to seem like the rings are made of blocks.
6. enderman to attack the wither storm (it would slow it down) have a structure that spawns in a mountain, enderman will frequently spawn to help with this future
7. wither storm debris  
when the wither storm dies instead of disappearing it would fall like when exploded but the blocks from it would become block clusters and fall out of the air leaving dead tainted flesh blocks every where and at least 9 heads and 9-15 tentacles laying down
8. block clusters go to other parts of the wither storm not just to the entity itself.
9. wither storm get larger after phase 7 while still having a hole.
10. unable placing a formidabomb in the wither storm. (it will destroy the whole inside of the witherstorm or crash the game)

i understand that are not aiming for accuracy but some of these things would be cool if they were in.

**Comment by watersofnazareth** [comment]
1, 2 and 4 would be require redoing the models, also #47 
3 needs to be clarified more
5 would be almost impossible without causing way too much lag
6 I doubt more structures will be added #232 as far as endermen attacking #235
7 #184 
8 I don't entirely know what this means I assume you mean absorbing into a random part of the hitbox, could be interesting but also weird
9 Is a possibility #106
10 This would require a stupid amount of effort to happen in survival and is unlikely to happen in a normal non creative playthrough, tho I don't know why you'd Formidibomb the bowels

**Comment by ghost** [comment]
1, 2 and 4, yea redoing the models but having a option in the client settings for each of them
3 being a option for the world settings to configure how large of clusters the wither storm should be able to pick up.
5  would act like block clusters just going up and deleting themselves when they get up there.
6 would be cool
7 would be cool
8 i mean the block clusters not just going to one part of the body.
9 would be cool
10 just get a command block tool and beat another symbiont and craft a f bomb go in the wither storm = dead computer

**Comment by watersofnazareth** [comment]
Think of it more in the aspect of modeling and coding, a lot of that would be incredibly tedious without much effect, mostly the model related stuff

**Comment by ghost** [comment]
yea makes sense

**Comment by nonamecrackers2** [comment]
1. #47 
2. I won't be changing the models any time soon, however a resource pack modelling format could be nice to allow users to make their own models (think Mojang plans on implementing a system to edit entity models via json anyway)
4. I think the debris particles are fine as they are, and making them too big will make them stand out too much and would look awkward
5. Would cause major performance drops
6. I won't be making endermen attack the WS (#235 to make it seem like they are) or add more structures #232 
7. Similiar to #184. Making the debris particles transform to blocks with how the system is written is not possible.
8. Don't think this is necessary. The current system would need some rewrites that I'm not willing to do to make this possible.
9. More phases: #106 #10 
10. I don't deem this as very necessary. If people were getting confused by this then I would of course change this.

Sorry it took long to get back. 3 is a possibility and you should make a separate report for that.

**Comment by GrandmaPork** [comment]
While turning the debris ring into blocks wouldn’t be possible, I think the debris ring should be included with the wither storm corpse
