### ISSUE TITLE
the wither storm figured out how to crash games

### ISSUE THREAD

**Issue by gw6338** [nonamecrackers2/crackers-wither-storm-mod#376]
I'm trying to run the mod on an Aternos server, 1.19, and whenever anyone other than me is in range of the Wither Storm while it's sentient gets instantly kicked from the server due to an error. Upon further inspection, it seems to start kicking people the instant it finishes charging up or whatever and starts to move. Any ideas on what could cause this and how to fix?

**Comment by nonamecrackers2** [comment]
If you have optifine with shaders, disable block cluster colouring in the client config
