### ISSUE TITLE
wither storm is disapearing when im away more than 50 blocks

### ISSUE THREAD

**Issue by wictorias12** [nonamecrackers2/crackers-wither-storm-mod#377]
**Minecraft version**
1.18.2

**Mod version**
[1.18.2-2.0.1.2]

**Describe the bug**
 the wither storm dissapears when im like 50 blocks away from him. it happens when im using better minecraft modpack (forge)  v14. i really wanted to play this modpack with wither storm :(

**Comment by nonamecrackers2** [comment]
If the modpack has rubidium/magnesium extras, there’s a certain setting that needs to be disabled.  I’ve outlined it in the “known compatibility issues” spoiler on the mod page.
