### ISSUE TITLE
The game crashes as soon as I turn on any shaders on any versions and any shaders

### ISSUE THREAD

**Issue by VbifVbif** [nonamecrackers2/crackers-wither-storm-mod#378]
**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by IntrovertedGamer** [comment]
https://youtu.be/8-iH4z6iTvE?t=70

**Comment by nonamecrackers2** [comment]
Yeah, will need to disable block cluster colouring in the client config
