### ISSUE TITLE
1.16.5

### ISSUE THREAD

**Issue by VbifVbif** [nonamecrackers2/crackers-wither-storm-mod#379]
**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
???
