### ISSUE TITLE
1.16.5 1.0.2.4 The game crashes as soon as I turn on any shaders

### ISSUE THREAD

**Issue by VbifVbif** [nonamecrackers2/crackers-wither-storm-mod#380]
**Minecraft version**
1.16.5

**Mod version**
1.0.2.4

**Describe the bug**
The game crashes as soon when I turn on any shaders, I realized through experimentation that the crashes are caused by rendering flying clusters of blocks.

**Crash
[crash-2022-07-26_17.40.44-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9189495/crash-2022-07-26_17.40.44-client.txt)
 Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Comment by nonamecrackers2** [comment]
Turn off block cluster colouring in the client config
