### ISSUE TITLE
First Thing In The World + Respawn Mechanism

### ISSUE THREAD

**Issue by Sleet827** [nonamecrackers2/crackers-wither-storm-mod#381]
**First Thing In The World + Respawn Mechanism**
I was thinking that according to the guide, and generally what happened in Story Mode anyways was that no one is meant to be prepared for the Wither Storm, it is like a natural disaster. So make it so that you can't break or place blocks (basically adventure mode) except wither skeleton skulls so that it is the first thing in the world and they can progress, otherwise they might deck themself with full netherite and beat it faster.

Speaking of which after we do deck ourselves with full netherite we might want to continue challenging it again for fun, so there must be some way to respawn in, probably make a house spawn every 10,000 blocks apart I guess.

**Comment by nonamecrackers2** [comment]
I want the players to be able to play the mod the way they want and don’t want to impose unnecessary restrictions. I do plan on adding a way to respawn the WS.

**Comment by Asteroid4** [comment]
> I want the players to be able to play the mod the way they want and don’t want to impose unnecessary restrictions. I do plan on adding a way to respawn the WS.

Maybe using the withered nether star and command block books to make a placeable command block?
