### ISSUE TITLE
Cant figure out the commands cuz im stoopid

### ISSUE THREAD

**Issue by Funnyeh** [nonamecrackers2/crackers-wither-storm-mod#382]
So basically, I try to modify the phase / entity's consumed, but it keeps asking for the witherstorm number. How do I input the commands correctly? I only have 1 witherstorm spawned.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
/witherstormmod phase set @e[type=witherstormmod:wither_storm,limit=1] 5

**Comment by nonamecrackers2** [comment]
There’s a “for creative users” section on the mod page that outlines all the important commands
