### ISSUE TITLE
Optimization of block clusters

### ISSUE THREAD

**Issue by Supertacoz** [nonamecrackers2/crackers-wither-storm-mod#383]
I have an AMD rx 6600 and driver version 22.7.1. 
during the later phases of the wither storm, it picks up a lot of block chunks, which even looking at them generally causes my fps to go from almost solid 60 to varying 30 to 40 fps. this occurs even if low quality models is enabled. if there is a way you could optimize the textures of the block clusters, it would be greatly appreciated.

**Comment by nonamecrackers2** [comment]
I do have some ideas but they’ll need testing

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release. When the update is available, you'll need to install Flywheel along with CWSM and enable "Block Cluster Instancing" in the client config along with a game restart to see the performance improvements.

**Comment by Supertacoz** [comment]
Thank you!
