### ISSUE TITLE
More contextual music for lesser fights, or to make the transition to silence better

### ISSUE THREAD

**Issue by ShadeKage** [nonamecrackers2/crackers-wither-storm-mod#384]
**Description of feature**
In MSM, the build up to the storm was just as important as the actual fight, as it is in this mod, i feel maybe music such as "action suspense" or other tracks should play if the play is over whelmed by mobs, or maybe when fighting the symbiot, or the sickened mobs in the nether like the other suggestion. In short, more tracks from the game beyond the boss music
**More detail of what I had in mind for context**
"Action suspence": Plays when the player is in the area of at least 5 or so hostile mobs, possibly could base it off of mobs seeing the player - (Loops till there are no mobs within a 32 radius), or is being chased by the storm, but outside the radius where they can be attacked - (Loops till your a safer distance away)
"Spiders!": Plays when fighting the symbiot, would be a neet indicator that the storm is ignoring you too - (Loops till the symbiot is dead and finishes that last loop, or if you leave the area)
"Map Room": Plays once fully after the storm is killed, and possibly in its playing dead phase too and is cut off when it awakens - (Plays once through)
**Optional extra songs**
"Ivor fight": Plays when the player is in the area of at least 5 hostile mobs like the last, or maybe if pvp happens, basically a varient of the fight track, It isnt the **most** fitting, but would make for a nice varient - (Loops till there are no mobs within a 32 radius)
"Cave": Plays if you successfully escape the storm, and leave the "chase" music radius - (plays once through the track)
"Wither Storm Destroyed": Segmented for the command block fight for its several phases, I know its hard to segment music, Ive done it before so I'm puttin this in the optional area (This might be in game already, I actually cant remember)

These could just be located in the options as a separate toggle for them to trigger, or could be as one big "music" setting, eitherway thats up to you, Thanks!

**Comment by nonamecrackers2** [comment]
Action suspense is actually used in the withered symbiont boss battle. Adding more music is not really in my interests and I feel it could be a good mod idea for someone who’d like to add more music. What is there to segment for the “destroyed theme” (as isn’t the majority of it fairly slow paced, which wouldn’t fit in very well for the final boss battle)? Thanks for the suggestion though!

**Comment by ShadeKage** [comment]
YEP, i actually was just testing XD sorry bout that, but still, id like to see it in more lol,
God i feel dumb now

**Comment by nonamecrackers2** [comment]
No worries! I like the adding more music thing but it just isn’t in my interests for the mod.

**Comment by ShadeKage** [comment]
Thats alright, tbh the idea came up when just listening to the sound track and thinkin "this would sound cool in game" lol, but yea its more fitting for a separate mod
