### ISSUE TITLE
Configurations do not save upon World recreation

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#385]
**Minecraft version**
1.18.2

**Mod version**
The version of the mod you are using

**Describe the bug**
Whenever you re-create a world configurations don't save with it
**To Reproduce**
1. Re-create a world with configurations set
2. Go to configurations
3. See error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by nonamecrackers2** [comment]
This is a forge thing and is out of my control. You’d have better luck if you were to report this on the forge GitHub repo.
