### ISSUE TITLE
I can’t figure out the commands

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#386]
This isn’t related to the mod it self, I just can’t figure out the command /witherstormmod cluster

**Comment by nonamecrackers2** [comment]
Taken from the [official discord](https://discord.gg/EbM3BJ9DP2):

>  "it's pretty much like the /fill command. you specify one corner than another, which tells it "all the blocks in between these two corners will be put into a cluster." the next argument is the time it's allowed to exist, i usually use 100. the next argument is NBT. since clusters spawn with gravity by default (causing them to get placed back immediately) put {NoGravity:1b} to disable it. there's no way to make them get absorbed by a wither storm atm."

If you need further assistance with stuff I recommend joining the discord instead of asking for help here :)

**Comment by Asteroid4** [comment]
Thanks!
