### ISSUE TITLE
Command block boss fight hard mode

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#387]
**Description of feature**
Maybe if you hit the command block during the fake death sequence, it deals damage to it, making the command block boss fight lose a phase, but the others become harder.

**Comment by watersofnazareth** [comment]
I don't this would logically make sense in game especially since it immediately gets back up if you hit it with a tool

**Comment by nonamecrackers2** [comment]
> I don't this would logically make sense in game especially since it immediately gets back up if you hit it with a tool

Agreed. I think for difficulty to be added it should be done in a different way anyway.

**Comment by Asteroid4** [comment]
tru
