### ISSUE TITLE
Severe Performance issues despite high-end computer (Likely 1.18 and 1.19)

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#388]
**Minecraft version**
1.19

**Mod version**
Latest

**Describe the bug**
Despite my computer's power and low settings, the mod has severe performance drops in 1.19
Computer Specs:
AMD Ryzen 5 3600 6-Core Processor 3.60 GHz
16.0 RAM

**To Reproduce**
1. Summon a Wither Storm
2. See lag

**Comment by watersofnazareth** [comment]
It's based more so on your GPU rendering the models

**Comment by nonamecrackers2** [comment]
The lag is expected and is unavoidable. I'm actively looking for ways to improve the performance and have done the best I possibly can so far. You can look in the client config and disable some stuff to improve performance.

**Comment by nonamecrackers2** [comment]
I'll leave this issue open however for future reference.

**Comment by nonamecrackers2** [comment]
Will be mostly remedied in the next 1.18/1.19 release via Flywheel.
