### ISSUE TITLE
Fear effect

### ISSUE THREAD

**Issue by Loverxzc** [nonamecrackers2/crackers-wither-storm-mod#39]
When player looks on wither storm, he will have a fear effect like this(its pulsing):
![effect3](https://user-images.githubusercontent.com/105715466/170767247-25f7de19-3bc2-4200-89a9-59a2a4b8ba50.png)
![augh](https://user-images.githubusercontent.com/105715466/170767719-3008c4d0-bfd0-44f3-8e63-df3736207069.png)
without:
![2022-05-27_21 04 41](https://user-images.githubusercontent.com/105715466/170767890-1cc452db-c474-4541-bf93-81f87f7c0870.png)
![2022-05-27_21 03 52](https://user-images.githubusercontent.com/105715466/170767910-77e64f7e-5c2e-4e23-b93e-09f84d71b128.png)

**Comment by Loverxzc** [comment]
The further the less

**Comment by Loverxzc** [comment]
missclick

**Comment by nonamecrackers2** [comment]
I don't feel like this is entirely necessary and may be a bit annoying, atleast for me. I feel like the "fear" players get from looking at the WS doesn't need to be enforced by an overlay.
