### ISSUE TITLE
cant hear the wither storm music?

### ISSUE THREAD

**Issue by minecraft12343** [nonamecrackers2/crackers-wither-storm-mod#390]
I am on 1.18.2 and can't hear the wither storm music. Is it a bug or am i missing something. The boss music is on, music is on. Everything's turned on.

Edit: I'm playing on Forge with optifine 1.18.2

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
This is normal (I think)

**Comment by minecraft12343** [comment]
i dont think it is because i checked /playsound and there's supposed to be music playing.

**Comment by nonamecrackers2** [comment]
If your game stutters it can cause it to cut out. You can reload sounds in the client config or by reloading resource packs. Also check if your jukebox/music disc slider is turned down.
