### ISSUE TITLE
Larger heads for larger phases

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#391]
As seen in story mode, after the main character crafted the f-bomb, the wither storm head that picked Jesse up seemed larger than in this mod. This is also seen in different parts of mcsm. It would be cool if the wither storm heads got a bit larger in phase 5 and phase 7.

**Comment by nonamecrackers2** [comment]
I don't feel enlarging the heads is necessary and will just result in having to do extra work for something I don't think would be very noticeable (enlarging the heads will also mean having to enlarge the head hitboxes, etc.).
