### ISSUE TITLE
Wither storm hitbox cannot shrink

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#392]
**Minecraft version**
1.18.2

**Mod version**
Idk💀

**Describe the bug**
Ok idk if this is out of your control but whenever I use separate mods to shrink the wither storm it shrinks the wither storm but the hitbox stays large

**To Reproduce**
1. Download some mod that allows size changing
2. change the wither storms size
3. see error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
Even if this dosent get patched I should still be glad I can make the wither storm go light speed with that same mod

**Comment by nonamecrackers2** [comment]
Does this happen with vanilla mobs? Also what mod are you using to shrink it?

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> Does this happen with vanilla mobs? Also what mod are you using to shrink it?

Nope I can shrink vanilla mobs hitbox also the mod I'm using is pehkui

**Comment by nonamecrackers2** [comment]
It's probably out of my control however I'll take a look.

**Comment by nonamecrackers2** [comment]
After looking at the code, this issue does appear to be out of my control and pehkui would need to add an edge case for my mod. Changing the code to work with pehkui is not worth the effort and the potential bugs.
