### ISSUE TITLE
Wither Storm "Digs" toward player

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#394]
**Description of feature**
I was able to stay at around y -30 for a while before the wither storm found me, I think the wither storm should be able to dig to the player if they are underground.

**Comment by Asteroid4** [comment]
Basically, the block clusters removed all will be near the player, no new mechanics need to be added.

**Comment by nonamecrackers2** [comment]
I don’t feel all the clusters would need to be near the player, instead just heavily concentrated.

**Comment by Asteroid4** [comment]
It should probably be configurable now that i think of it

**Comment by nonamecrackers2** [comment]
I don't feel the wither storm should dig towards the player as the underground is really one of the only other safe spots in the overworld.

**Comment by BluePineappleGuy** [comment]
> I don't feel the wither storm should dig towards the player as the underground is really one of the only other safe spots in the overworld.

ig it is one of the few safe places, but it kinda nerfs the whole "running from mutant tentacle monster" thing as people just live in deep caves while the storm is active. like M O L E S.
