### ISSUE TITLE
sky darkness

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#395]
just the sky will get darker in phases 4 - 7 when the WS gets close to the player.

**Comment by watersofnazareth** [comment]
This is being added, from the Discord: ![image](https://user-images.githubusercontent.com/28667280/181796208-984929db-6614-443a-8544-72efa31be95a.png)

**Comment by nonamecrackers2** [comment]
Also: #183

**Comment by Cgdihkg** [comment]
> This is being added, from the Discord: ![image](https://user-images.githubusercontent.com/28667280/181796208-984929db-6614-443a-8544-72efa31be95a.png)

So why is it done from discord? Implement this into the mod.

**Comment by nonamecrackers2** [comment]
It will be. This photo was from an dev announcement.

**Comment by Cgdihkg** [comment]
> 

Will it be in the 3.0 release?

**Comment by nonamecrackers2** [comment]
Eventually yes

**Comment by Cgdihkg** [comment]
> Eventually yes

And when will 3.0 be released approximately?
