### ISSUE TITLE
Alternate methods of escaping the wither storm.

### ISSUE THREAD

**Issue by Luviam** [nonamecrackers2/crackers-wither-storm-mod#396]
There should be multiple actually viable ways of escaping the wither storm in it's later phases for a decent amount of time. 
Right now all you can really do is hide in the nether or run away in the nether and build another portal to go back into the overworld.

An Idea: Firework blocks. A block of fireworks that could distract the wither storm longer than normal fireworks, but be somewhat random at the same time. (The wither storm having a random chance to pick it up and destroy it)

I'm not too good for idea's but I hope you could take this into consideration. Also, keep it up with the great mod! You should also consider taking a short break sometime.

-Luviam.

**Comment by ghost** [comment]
i think this is great, better than my idea.

**Comment by TaintedBlockk** [comment]
Or set up a dispenser to distract it for a bit

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
