### ISSUE TITLE
Different progression

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#397]
**Description of feature**
I think that you should have to find the super tnt in a new, rare structure instead of crafting it.

**Comment by Asteroid4** [comment]
Also the symbiote should be made stronger

**Comment by ghost** [comment]
wouldnt that make the symbiot useless?

**Comment by ghost** [comment]
well i have the same idea for different progression.
i had a idea of exploding the wither storm to get inside of it.

**Comment by Asteroid4** [comment]
> wouldnt that make the symbiot useless?

No, to craft the command block tool you need to kill it.

**Comment by ghost** [comment]
yea but then you only need to kill the symbiont once

**Comment by Asteroid4** [comment]
> yea but then you only need to kill the symbiont once

Yea

**Comment by nonamecrackers2** [comment]
I don’t intend on changing the progression, however I could see this as a cool modpack idea.
