### ISSUE TITLE
Wither star spawns inside of storm debris. 

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#398]
i have seen cracker agreeing to a lot of wither storm debris suggestions so i think it would be fair if the wither star would spawn somewhere in the debris so the wither star would be a task to obtain. like the player could dig through the debris to find it finding certain wither blocks for stuff like building. or just removal. (heads and tentacles would be destroyed and drop flesh blocks if the block underneath is destroyed.) or just finding the place where the command block was destroyed and finding the star there.

**Comment by nonamecrackers2** [comment]
While this is cool, the reason why it’s given to the player immediately is to avoid the item despawning for whatever reason.

**Comment by ghost** [comment]
well i mean it would be in like a chest or invis item frame
