### ISSUE TITLE
Make boss music not overlap with default vanilla music

### ISSUE THREAD

**Issue by ShadeKage** [nonamecrackers2/crackers-wither-storm-mod#400]
**Description of feature**
Currently, if Minecrafts vanilla music is playing and the boss music begins, either the symbiots or the storms, they two songs clash and become a ear pain, especially if you like me and re textured the default songs to be story mode songs
And that would need to be implmented is whenever someone enters the radius for boss music, keep trying to execute the command on the player "/stopsound @a[name=PLAYER] minecraft:music.game" silently in the background, as to cancel the default music, theres already a system in place to detect where the play is relative to the bosses, so this shouldnt be too hard, right? Thanks

**Comment by nonamecrackers2** [comment]
#333

**Comment by ShadeKage** [comment]
Sorry for the resubmit

**Comment by nonamecrackers2** [comment]
It's all good
