### ISSUE TITLE
A few suggestions about the bowles

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#404]
For the hole below the command block, you can see bedrock at the bottom if you have night vision or turn on full bright. This can look awkward so it would be nice if it were just void below the hole or have the hole narrow further down. If a player digs up, there will also be a bedrock layer above them so it would be great if you just get teleported out of the wither storm if you try to dig up.

**Comment by nonamecrackers2** [comment]
Implemented as a bedrock replacement in 2.2/3.2
