### ISSUE TITLE
weird bug in flat world

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#405]
**Minecraft version**
1.18.2

**Mod version**
latest

**Describe the bug**
So I have a world with many mods. but it refuses to load without crackers wither storm mod, it says "Errors in currently selected datapacks prevented the world from loading" whenever I press safe mode, it does nothing. When I re added the mod, I kept hearing the wither storm summoning sound looping near 0,0,0, even though nothing was there.

**To Reproduce**
note: im not sure if this will work.
1. make a flat world
3. relaunch forge without the wither storm mod
4. notice it might not load
5. re launch with the mod
6. listen closely, you may hear the wither storm summoning noises near 0,0,0

**Crash Reports / Logs**
here's the pastebin link:https://pastebin.com/cpDRxZPs.

**Screenshots**
none

**Comment by Globalfirestorm10** [comment]
thank you for confirming this was a bug, good to know that the solution worked

**Comment by nonamecrackers2** [comment]
I technically haven't confirmed it yet, sorry. Just marking it as a bug for future reference.

**Comment by Globalfirestorm10** [comment]
Oh, my mistake, I haven't done any actions related to the mod, such as light the f-bomb or even pick up an item

**Comment by Globalfirestorm10** [comment]
to anyone other than cracker and me looking at this, this issue is resolved as a bug with forge, I will leave it open for now

**Comment by nonamecrackers2** [comment]
Yes. I will close this however.
