### ISSUE TITLE
Causes Menu Companions to fail to render entities with the Wither sickness layer

### ISSUE THREAD

**Issue by Kevadroz** [nonamecrackers2/crackers-wither-storm-mod#406]
**Minecraft version**
1.16.5

**Mod version**
1.0.2.4

**Describe the bug**
Any entity that can render the "Wither sickness layer" fails to render at all in the main menu, instead being blacklisted and prevented from being choosen again.

**To Reproduce**
1. Install Menu Companions and Wither Storm in the same instance.
2. Boot the instance to the main menu.
3. The player on the right doesn't appear.
4. There are new entries in menucompanions-client.toml > [Menu Entity] > Entity Blacklist.

**Crash Reports / Logs**
Sadly this mod prevent's these crash reports as a side effect of detecting problematic mobs. The best I have is "Tag witherstormmod:wither_sickness_immune used before it was bound"

**Coment**
Due to the prevention of a crash report I can't be sure what mod it's at fault here, so this may not be a problem of this mod but menu companions.

**Comment by nonamecrackers2** [comment]
Should be fixed in the latest 1.16.5 released
