### ISSUE TITLE
Mod Incompatibility: Another Immersive FX issue

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#407]
ImmersiveFX seems to break how the tractor beam sound effects are placed. When going near a tractor beam you don't hear the sounds around you, you only hear them at certain points inside the tractor beam

**Comment by nonamecrackers2** [comment]
What mod version?

**Comment by Luke7381** [comment]
> What mod version?

Its 1.18.2.

**Comment by nonamecrackers2** [comment]
Disable "Enable Stereo to Mono Conversion" in "sndctrl-client.toml" to fix this problem.
