### ISSUE TITLE
Wither storm shoots skulls while pulling in players

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#409]
**Minecraft version**
1.18.2
**Mod version**
The version of the mod you are using
Idk agian
**Describe the bug**
Basically when the wither storm is tractor beaming a player and then targeting a mob it shoots a wither skull killing the player I acually lost my run to this bug
**To Reproduce**
1. Let the wither storm pull you in
2. wait for it to target a mob
3. it shoots a skull and kills you (see error)

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**
I don't have any screenshots but I have footage of the bug in action
https://youtu.be/iyd6C8L4qkY?t=6107

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
I'm still pretty mad about that I worked hard to run from the wither storm with slowness 4

**Comment by Frask0** [comment]
Am pretty sure this is supposed to happen??? It's meant to increase difficulty, and another reason to not get caught. however, you can still block it with a shield, so it's not that big of a problem.

**Comment by KrukAdrian** [comment]
Frask0 is right, This is suppose to happen.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> Am pretty sure this is supposed to happen??? It's meant to increase difficulty, and another reason to not get caught. however, you can still block it with a shield, so it's not that big of a problem.

No it's not nonamecrackers said in another post of mine about skulls
"I feel this would become more annoying than challenging, being at the brink of escape and then being blown to pieces by a skull and losing all your stuff."
Here's the url for proof
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/265

**Comment by nonamecrackers2** [comment]
This works as intended. Slowness doesn't change how fast it goes, you'd need to go into the server config to modify it. You can actually move slightly in the tractor beams to avoid the skulls, and yes using a shield blocks the skulls.
