### ISSUE TITLE
About the Rundown House at 0, 0

### ISSUE THREAD

**Issue by iWalk809** [nonamecrackers2/crackers-wither-storm-mod#41]
The mod is amazing, but is there any way to change the Wither Storm's wither-like structure spawn location?
it seems too OP because any random new player can already summon the wither unless if grief-prevention plugins are used, and it can't generate on pre-existing worlds if a player has already generated the chunk.

**Comment by nonamecrackers2** [comment]
It is designed to be easily accessible, as you're supposed to play along with the wither storm evolving. If you don't want it to be at 0, 0, you can just disable it's generating in the common config before you generate a world. If you want it on a pre existing world, you'll have to build the structure in creative first. If there's more demand for this in the future I'll reconsider it.
