### ISSUE TITLE
Wither Storm duplicates when joining back a world

### ISSUE THREAD

**Issue by EndTheEnders164** [nonamecrackers2/crackers-wither-storm-mod#410]
The version of Minecraft the mod is running on: 1.18.2

The version of the mod I was using: V2.0.1.2

So, I was setting up a surival world in creative mode for myself, I teleported the Wither Storm to the center of the world with me being about 2,000 blocks away from it. Also the generation type I used was "AMPLIFIED". I left the world, and when I joined back, there were two Wither Storms in the distance! PS: Both Wither Storms were in their fourth phase.

To Reproduce...
1. Make a World.
2. Save and Exit the world.
3. Rejoin the world.
4. Witnedd the Duplication.

**Comment by nonamecrackers2** [comment]
If you go to one of the duplicates, are you able /kill it or do any other command on it?

**Comment by Ulisesrec** [comment]
I had this same problem, i'm playing in a server, and when i turned it off and came back it duplicated (it only happened once though) i think it is in phase 6 or 7? (after it has been formidibombed)
Also It only appear as one (at least It only shows one health bar)
![Captura de pantalla de 2022-08-18 11-45-02](https://user-images.githubusercontent.com/73950698/185365602-d8eae4a9-b9f2-49f3-b21e-9ebbca60e133.png)
version is 1.18.2, Forge 40.1.73

**Comment by EndTheEnders164** [comment]
Well for me this happened when the Wither Storm was in it's fourth phase,
and it was also pretty far away(Around a thousand blocks, any farther it
wouldn't be a rendered entity in my world anymore)

**Comment by EndTheEnders164** [comment]
Yes, I was able to use the /kill command on both of them.

**Comment by Ulisesrec** [comment]
Okay, I also tried to use kill, but what was duplicated for me wasn't the storm, but the segments, there were like 20 of them lol, 15 overlapped on a same place
![Captura de pantalla de 2022-08-18 23-55-23](https://user-images.githubusercontent.com/73950698/185502678-21376aa6-d7bb-494d-9c9e-ca569c9640f4.png)

**Comment by nonamecrackers2** [comment]
@Hac-kDUBS164 Any other mods?

**Comment by nonamecrackers2** [comment]
> I had this same problem, i'm playing in a server, and when i turned it off and came back it duplicated (it only happened once though) i think it is in phase 6 or 7? (after it has been formidibombed) Also It only appear as one (at least It only shows one health bar) ![Captura de pantalla de 2022-08-18 11-45-02](https://user-images.githubusercontent.com/73950698/185365602-d8eae4a9-b9f2-49f3-b21e-9ebbca60e133.png) version is 1.18.2, Forge 40.1.73

This looks like segment duplication #222

**Comment by watersofnazareth** [comment]
Fixed as of prerelease 
#222
