### ISSUE TITLE
Wither storm height config 

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#411]
config for flying flight set where the wither storm would stay at that height and not be able to go over things.
so if the wither storm dug a giant hole it would not be able to go down it or if it was in the hole, over it.
so something like
/witherstormmod flyingheight set @e[type=witherstormmod;wither_storm,limit:1] (height)
or through the config
flying height set: off/on
flying height: (the wither storm will stay at this y level, but if off then this is what is already in the mod)

**Comment by nonamecrackers2** [comment]
What other uses besides what you'd described would this be useful for? I can see problems that would arise from this feature.

**Comment by ghost** [comment]
> What other uses besides what you'd described would this be useful for? I can see problems that would arise from this feature.

say if the player wanted the wither storm to not go so high when block clusters are accidently placed (when the wither storm is interrupted. via explosion or death.

**Comment by nonamecrackers2** [comment]
Either way I don't feel this would see much use and the work wouldn't justify it.
