### ISSUE TITLE
plans to rework the way music works when in proximity of the wither storm (BIBLE TEXT WARNING)

### ISSUE THREAD

**Issue by dgc0312** [nonamecrackers2/crackers-wither-storm-mod#412]
Currently, as far as I can see, there is a single track that has different "stages" of music (slow, fast and the fastest versions) that is just playing on loop. 

 

I think it should be based on proximity & aggro on top of how it works. 

 

In particular, if you are on the "edge" of music trigger, the slow version of the theme should play (drums only), when wither storm comes closer you hear the next stage of the theme, then, when he is at point blank range the next version is playing and finally when he is focused on you (in case you're in the multiplayer) the final most aggressive part of the theme plays. 

 

For example, the first part of the theme should play when you start hearing Wither Storm ambience, then the next one turns on when you can see the boss bar and finally when wither storm gets fully rendered for the player. 

 

On top of that, it would've been really nice if Wither Storm had more stages in its boss fight, instead of current "run from wither and wait till stage 5 -> beat symbiont -> blow the wither up -> run from wither and wait till stage 7 -> get command block tools -> deal the finishing blow". I understand the fight is already more than complicated, but it would've been really nice if it encouraged getting above and beyond around the entire minecraft world to gather tools to defeat wither. 

 

It already partially does that by encouraging to use Nether to find blaze powder to craft Formidibomb, but it would've been really nice if the same requirement was for the End / Stronghold. Just like in Minecraft:Story Mode, you'd have to visit a lot of different places, while fleeing from the almighty wither storm, before taking it down. Maybe a mob like Wither Symbiont would spawn in isolated distant areas in which you have to beat him and get another piece for your victory. 

 

I also love how you used Action Suspense theme during wither symbiont fight and I wish the mod enabled it during some other events while you're away from wither storm. 

 

In addition, it would've great if you found a solution to hiding from wither storm in caves underground. Currently, it's rather easy to avoid wither storm by just going underground. By the time it digs to you, hours would pass as it can't really dig deep down and instead picks the blocks from the upper layers. Maybe Wither Storm could somehow utilize its tentacles or do the same thing normal wither can do when it can't reach you - straight up annihilate blocks that separate you from the Storm. 

 

Same thing for the Nether portals. A lot of my success in avoiding wither storm while gathering resources and tools was just jumping into freshly built nether portal whenever I saw wither storm. It can potentially grab portal blocks or you by tracktor beam, but only if you are on the surface. My first successful defeat of the Wither Storm relied a lot on building a net of underground nether portals and just walking between them in the Nether whenever I needed to go out on the surface as the Wither Storm just flied from one portal to another. However, I could get by without it by just sitting underground and carrying a water bucket with myself to avoid occassional fall damage when the beam grabbed me through the ground. 

 

I understand my feedback might be very subjective and this might not be the direction you want to develop this mod, but I believe that might be helpful. Thanks for developing this mod, I had a lot of fun playing solo with it as I was being pursued by one of the most epic and deadly things in all of the minecraft that isn't just a damage sponge with overbuffed lethality, speed and hp.

**Comment by Aimyx** [comment]
wall 'o' text

**Comment by nonamecrackers2** [comment]
I think how the current music system works is fine and don't find this necessary. And glad you enjoy the mod!
