### ISSUE TITLE
More Growth for the Wither Storm

### ISSUE THREAD

**Issue by BlueToadTide** [nonamecrackers2/crackers-wither-storm-mod#414]
After the Wither storm hits phase 7 and if the bowels are open, if the player does not proceed with killing the wither storm, allow the wither storm to advance into another phase ( create what you think the wither storm would look like ) allow it to continue to grow keep the bowels open through this although make it more difficult the longer the wither storm lives on. The wither storm segments should begin to grow along with the storm and grow similarly to how phase 4 is and continue its growth as wanted. 

I'd also like to say I enjoy the mod very much and appreciate your work.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/10
