### ISSUE TITLE
Bowels don't open

### ISSUE THREAD

**Issue by Begnom** [nonamecrackers2/crackers-wither-storm-mod#415]
i'm trying to beat the wither storm with a friend on a server, but the bowels won't open. I'm waiting for nearly 2 hours now.
Can i open them manually with a command or do i just have to wait for longer?

**Comment by Globalfirestorm10** [comment]
Assuming the storm is on phase 7, use this command to open the bowels: /witherstormmod consumedEntities set @e[type=witherstormmod:wither_storm,limit=1] 3000000

**Comment by nonamecrackers2** [comment]
Have you gone through the formidibomb sequence at all?
