### ISSUE TITLE
Suggestions for the mod

### ISSUE THREAD

**Issue by Crispyixs** [nonamecrackers2/crackers-wither-storm-mod#416]
Endermen get angry at the storm
Inside the bowels the gravity will change on each hit (like the game)
The orders temple as a naturally generating structure (can put the amulet there instead of in the abandond house)
Wither storm ignores you for 10 seconds after shooting it (so you dont get sucked up as soon as you shoot it)
Enchanted Command Block tools actually look like how they look in MCSM
(this has probably already been suggested) Netherite Command block weapons

**Comment by ghost** [comment]
1. been suggested
2. been suggested
3. been suggested (not happening)
4. could do that
5. could do that
6. has been suggested

**Comment by watersofnazareth** [comment]
I really recommend reading through issues
#113
#105
#232
Believe this already is a feature?
#338
#261

**Comment by ShadeKage** [comment]
My man didnt even try to read already suggested stuff XD
Also #4 is 100% NOT already in the game, and if it is, its not 10 seconds, its like 2

**Comment by nonamecrackers2** [comment]
I plan on adding # 4 to fix a bug that was already reported.
