### ISSUE TITLE
Fbomb disappears

### ISSUE THREAD

**Issue by Your0wallet** [nonamecrackers2/crackers-wither-storm-mod#417]
**1.18.2**
The version of Minecraft the mod is running on

**36.2.34 forge**
The version of the mod you are using

**Fbomb disappears when lit**

**To Reproduce**
1 get fbomb
2. light it
3. it disappears

**Comment by watersofnazareth** [comment]
Do you have any other mods?

**Comment by nonamecrackers2** [comment]
> Do you have any other mods?

Yes, seems like a mod compat issue. Also your forge version suggests you're using 1.16 instead of 1.18. I recommend clearing that up.

**Comment by nonamecrackers2** [comment]
Closing due to lack of info
