### ISSUE TITLE
Keeping Wither Sickness after death.

### ISSUE THREAD

**Issue by PPengo** [nonamecrackers2/crackers-wither-storm-mod#420]
Not sure if this was suggested already, but it's really annoying that you can just get rid of wither sickness by dying. I feel like with a config toggle, you should keep wither sickness when you die so you have to cure yourself normally to get rid of it.
I play on a server with my friends, and they die a lot, so I have to use /effect to infect them again with wither sickness. It would be more challenging and you wouldn't be able to just cheese it.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
