### ISSUE TITLE
Wither storm is affected by simulation distance

### ISSUE THREAD

**Issue by MirokaSult** [nonamecrackers2/crackers-wither-storm-mod#422]
**Minecraft version**
1.19

**Mod version**
3.0-beta

**Describe the bug**
Wither storm is being affected by simulation distance when dying.

**To Reproduce**
1. Set simulation distance to 5 chunks.
2. Defeat the Command Block.
3. Watch WS not dying if teleported more that 5 chunks away from it.

**Comment by nonamecrackers2** [comment]
This is technically intended, however I'll try and see if I can change this. When the WS dies it unloads its loaded chunks, causing it to then only be affected by simulation distance.

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.18/1.19 release.
