### ISSUE TITLE
Plot armour

### ISSUE THREAD

**Issue by KrukAdrian** [nonamecrackers2/crackers-wither-storm-mod#423]
The plot armour can only be accessed through creative mode. The wither storm will pick you up very slowly and let you escape from the tractor beam and when you fall it will only deal 1 heart. When you're in the bowels once the sickended mobs spawn it will deal only half a heart.

**Comment by Asteroid4** [comment]
I think this is a good idea, but might not work for the main mod

**Comment by nonamecrackers2** [comment]
Interesting idea, however I don't think this is worth my time for something that not many people will use.
