### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by DiamondWalker** [nonamecrackers2/crackers-wither-storm-mod#425]
-the countdown period should have the health bar slowly fill up, like the normal wither. It keeps it consistent and it'd be helpful to know exactly how long you have before it properly spawns.

-in situations that aren't immediately dangerous (i.e. underground), the music should behave more like vanilla's ambient themes. It's way too intense and repetitive to be playing all the time; it gets really obnoxious (I know you can just disable note block sounds, but then you never hear it at all, and it's really cool to hear once in a while).

-the eyes should have a set amount of health rather than just RNG. Maybe they can gain extra protection for a while if you stun one of them. Maybe they could have an extra health bar that shows up when they lock onto you? Knowing exactly how close you are to escaping could ruin the tension though.

-if the eyes don't have a direct line of sight with you and/or are too far away, the beams should have a weakened effect, giving you a few seconds before they start pulling you. When you're underground, there's a lot of times when the beams randomly snap onto you and you can't do anything but wait until it looks somewhere else.

-wither sickness debuff shouldn't have a timer: it's misleading. At first I thought I could wait in the nether for it to go away on its own.

**Comment by nonamecrackers2** [comment]
I'll have to experiment with 5. but the rest sounds good.

**Comment by nonamecrackers2** [comment]
2 and 3 are already implemented, and will definitely experiment with 1

**Comment by nonamecrackers2** [comment]
The health bar will now slowly fill up in the next major release
