### ISSUE TITLE
Ideas for mod (alot seen from others)

### ISSUE THREAD

**Issue by personmhmyes** [nonamecrackers2/crackers-wither-storm-mod#426]
heres just a couple feature ideas not all are mine

feature 1: sub phases (more in depth)
im sure you know all about the subphases but i will list all of the anyway incase you havent seen one
sub phase 2.5 half of the command block is covered and there is 1-2 very small tenticals 
phase 3.3-4 are just transitioning from phase 3-4
phase 3.3 the witherstorm is a bit bigger the bottom has that pointed bit at the bottom seen on phase 4
phase 3.6 the witherstorm is taller and a second head has a tractor beam and more tenticals or they are bigger
phase 3.9 the last head has a tractore been it almost looks like phase 4 but less tenticals/smaller heads arent as big 
sub-phase 5.5(end) transitioning phase from the start and end to phase 5 because its a big difference
phase 6.5 again transitioning phase
note the phases mentioned should probably be used with consumed entities command not phase

feature 2
phases past phase 7 which links with feature one
the witherstorm can get bigger and harder to kill past phase 7 this can be and option defulted to off
phase 7-9 it just get bigger and the 2 segments grow and the main one can maybe get more heads or split of more segments like engender mods witherstorm
phase 10 the hole gets covered and can only be exposed for a short while once formidi bomb is used and maybe can apply to phases 7-9 as well and maybe another 1-2 phases if you want which can be unkillable or extremely hard to kill and needing the use of a netherite command block tool and taking more hits and way stronger mobs like hit 1 spawns withered mobs hit 2 spawns mobs 3 2 withered symbionts and tenticals and tractor beams activate hit 3 command block absorbs nearby mobs and blocks to shield itself which the player needs to damage enough which it cracks away it isnt full blocks its like the witherstorms appearence hit 4 it shakes so much the player gets launched out side the storm or launched away from the block or get blinded because on hit 5 the command block makes fake command blocks that look a bit distorted and spawn mobs or cast withered symbiont attack and the player must hit them 3 times to break 4 will spawn and while doing so the command block is invincable and building on itself then once 4 fakes have been destroyed you hit the block again and destroy it killing the witherstorm

feature 3
behavior changes
all phases that can shoot flaming skulls should use the skulls to attack outside of tractor beam like mcsm it shoots at jessie alot to kill him so it could to the same in your mod
also if the storm makes a big hole it shouldnt go down into it 
it should just sit at the ground level 
the witherstorm can lower itself to attack using tenticals which can either damage the player of hold them to be killed by the storm
it should also try to absorb mobs instead of killing at least some of them and when the witherstorm gets formidi bombed if it falls on a block that was being picked up it should breaking when the withstorm falls it should check if there is a certain amount of blocks in the x -y x co ordinates e.g. 10 and if there isnt then it breaks them which can be realistic because the witherstorm is gonna be heavy

feature 4
wither sickness
first it shouldnt be cured on death it will just restart from either when you begin withering away (10 hearts) or not fully infected it also should get way worst the longer you have it not reseting on death

feature 5
misc
it would be cool if you can make the witherstorm change its ultimate target from the player to something like a cow using commands
you shouldnt be able to hide in the nether/end the witherstorm can either break the portal spawn a head in the portal and try to suck you through if its close enough or constantly spawn mobs through it

and finally the withered netherstar should have a use like crafting a command block which should be placeable in survival
a recipe for a really powerfull ranged weapon named the Tractor bow using durabilty or a item to make a tractor beam when holding right click pulling mobs killing them and when broken the withered nether star drops it is indestructable and a recovory compass can point to it or something
tenticals should get a graphic change to look blocky

thats all my rambling this all might sound like a complaint which it really isnt and all of these are suggestions so i dont expect many to get in although i hope so 

well hope you have a good day or night and im gonna go sleep now

**Comment by ghost** [comment]
feature 1 would make the wither storm feel more smooth than just changing a totally different shape/size
feature 2 this would make the wither storm feel SO MUCH MORE DANGUARUS. and maybe if the wither storm is not exploded at phase 5 then maybe it just gets bigger and the player would have to make the A-NUKE. when i saw feature 2 i went crazy and made a texture for the A-NUKE. but the wither storm will be so much more dangerous if it had this.
feature 3 the not going into a hole feature could be used with this #411
feature 4 i think it should rather just have the wither sickness maybe fade away slowly
feature 5 for the portal break. i dont know how someone could do this but it might be possible.
well thats all. i dont work for cracker but i just want to compliment your suggestions.

**Comment by personmhmyes** [comment]
what i ment by on death is that if the player dies then the sickness doesnt go away but yes the withersickness should also fade away when the witherstorm dies

**Comment by BlueToadTide** [comment]
I like these ideas

**Comment by nonamecrackers2** [comment]
- Transition phases (notably phase 3 - 4): #316 
- More phases: #10 
- Wither Sickness: #420 
- I don't plan on making the WS able to target things other than players. In the cow scenario, there are tons in close proximity that would cause the WS to barely move around.
- My thoughts on messing with portals: #13 
- I don't plan on making command blocks craftable.
- Tentacle's model: #169 

Sorry for taking so long to get back to this. For feature 3 you should probably make a separate report, as the rest is pretty much duplicate.

**Comment by stormkille** [comment]
what if the evolution part 2 the wither storm can pick up whole trees and the wither storm can pick the player up from the nether to the overworld and the wither storm can drink water blocks it goes in and it can go to phase 9 so phase 7.5 is where the hole on it's head is open, phase 8 the smaller little wither storm get bigger phase 8.5 same thing, phase 9 the wither storm can eat end portal frames and bedrock particles start to spawn and any bedrock from -62 to -60 is eaten and a super f-bomb crafted with 4 f-bombs and 4 tnt and enchanted command block book in the middle and it has 3 times the power and radius. P.S I don't think we need netherite command block tools. P.P.S I love the mod and I killed 10 wither storms so far
