### ISSUE TITLE
New effect

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#427]
**Description of feature**
Basically in the ending of episode 3 and during episode 4 Gabriel forgets things I think this would do good as an effect this will make the player forget things like how to attack build and craft

**Comment by IntrovertedGamer** [comment]
How would you be able to get anything done?

**Comment by nonamecrackers2** [comment]
I feel this would be very intrusive, annoying and frustrating for players. Not being able to not do basic stuff to be able to survive wouldn't be very enjoyable.
