### ISSUE TITLE
Suggestion about the wither storm heads.

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#428]
The two heads in the bowles should face downwards when not activated because right now, it looks a bit awkward. 
Great mod by the way.

**Comment by nonamecrackers2** [comment]
I feel if they were to face downwards 90 degrees it'll awkward instead (as seen in MCSM I believe). Either way I don't feel this is entirely necessary and I prefer the heads as they are.
