### ISSUE TITLE
reproduce mod 

### ISSUE THREAD

**Issue by shiyushui** [nonamecrackers2/crackers-wither-storm-mod#43]
Hello, author. May I reproduce your mod in the UTC forum.https://www.mcutc.com

I won't take your mod for profit
It is a China forum,if you agree,we can download your mod on the Forumt,thank you

**Comment by Loverxzc** [comment]
Did I understand correctly that you want to post the mod on the Chinese forum? If yes, then read the last lines on the mod forum
![Screenshot_126](https://user-images.githubusercontent.com/105715466/170820933-f508622e-e1b4-44c6-9bfc-3bfe62a957db.png)

**Comment by Loverxzc** [comment]
But let the author of the mod give permission or refusal

**Comment by shiyushui** [comment]
yes,I will mark the author

**Comment by shiyushui** [comment]
> 您好，作者。我可以在UTC论坛中重现您的mod。https://www.mcutc.com
> 
> 我不会把你的mod用于盈利这是一个中国论坛，如果你同意，我们可以在论坛下载你的mod，谢谢
