### ISSUE TITLE
Wither storm spawn timer

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#430]
**Description of feature**
I feel like for people who want a little time to set up before the wither storm spawns the wither storm should spawn automatically after a certian time (you can modify this in the configuration settings) so that way people don't need to run all the way back and spawn the wither storm

**Comment by watersofnazareth** [comment]
You can use a scoreboard timer to do this

**Comment by nonamecrackers2** [comment]
Oh yeah you totally could. Found [this](https://gaming.stackexchange.com/questions/274911/how-do-i-delay-a-command). Outdated however there could be some useful information.
