### ISSUE TITLE
Segments Move More Freely

### ISSUE THREAD

**Issue by BlueToadTide** [nonamecrackers2/crackers-wither-storm-mod#432]
I think it would be better if the segments could move more freely then just being next to the wither storm, but the segments would stay in a certain block radius of the storm

**Comment by ghost** [comment]
i think this would work if the segments move around the ultimate target.

**Comment by RandomGithubUser32** [comment]
I think that it would also be cool if the segments can rotate themselves on their own instead of facing the same way as the main wither storm all of the time.

**Comment by nonamecrackers2** [comment]
Closing in favor of #701 as it is more detailed.
