### ISSUE TITLE
Saddle in starting house

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#433]
The starting house should contain a saddle to tame a horse because you can't escape the wither storm in stage 4 by foot.

**Comment by nonamecrackers2** [comment]
It's intended to be extremely fast and I don't plan on adding anything to the house that would give players too much of an advantage. Player's are encouraged to figure out ways to escape on their own and I feel adding a saddle would intrude with this.
