### ISSUE TITLE
Bossbar changes

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#434]
I have an idea. When the wither storm is first spawned, the bossbar says "Wither", but it then changes to "Wither?" before, in phase 4, it changes to "Wither Storm".

**Comment by ghost** [comment]
this is kind of unnecessary and just seems not that useful, is there a way the name will not change but the boss bar. like the colour?

**Comment by nonamecrackers2** [comment]
> this is kind of unnecessary and just seems not that useful

I agree, and I don't think the small amount of people that would notice it would justify the extra work I'd have to do.
