### ISSUE TITLE
Yet another issue with immersiveFX

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#437]
**Minecraft version**
Forge 1.18.2 recommended version
**Mod version**
Latest

**Describe the bug**
In a flat world with immersiveFX,near 0,0,0 the sound the wither storm makes when you just spawned it from that house at 0,0,0 keeps looping, over and over again, even if it's a brand new world

**To Reproduce**
1. Create a flat world with crackers wither storm and immersive FX
2. Go to the ground near 0,0,0
3. Listen closely
4. Find the issue

**Crash Reports / Logs**
No logs

**Comment by watersofnazareth** [comment]
This should probably be opened to Immersive FX's github more so here, https://github.com/Y3Z0N/ImmersiveFX/issues

**Comment by ghost** [comment]
i have had this happen to me.

**Comment by nonamecrackers2** [comment]
Could you send the latest.log after you replicate the issue? I want to see if it says anything.

**Comment by nonamecrackers2** [comment]
Can't reproduce. I have all the incompat settings listed in the "Known incompatibility issues" spoiler on the mod page disabled if that helps. If someone could find a reliable way to reproduce this that would be helpful. Either way I feel this is an issue with Immersive FX, stumped on what could be the cause for you guys.
