### ISSUE TITLE
In game progression guide.

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#438]
It would be great if there was a progression guide when playing the game. This could be a book that is given in the starter house or when a player spawns in. This can also be something in the GUI as well.

**Comment by Nov1st2k10** [comment]
If you're looking for a progression guide, there's some modpacks with a guide book, one I'd recommend is A Withering World

**Comment by ghost** [comment]
well this could work in servers to help friends but i hope cracker doesn't make it too obvious what to do. more like a puzzle

**Comment by RandomGithubUser32** [comment]
That sounds like a great idea. I wrote this suggestion because things such as getting command block books can be hard to figure out for new players.

**Comment by nonamecrackers2** [comment]
Won't be adding an in game progression guide at this moment.
