### ISSUE TITLE
Will you make a fabric port?

### ISSUE THREAD

**Issue by Bloxxify2827** [nonamecrackers2/crackers-wither-storm-mod#439]
I wanted to use fabric mods with this one and realized that there wasn’t one you make crackers.

**Comment by ghost** [comment]
well this be good for fabric servers. i was talking to some people who liked fabric more. that's why I cant get them to play the mod.
this will be interesting for mods like illuminations.

**Comment by Luke7381** [comment]
> well this be good for fabric servers. i was talking to some people who liked fabric more. that's why I cant get them to play the mod. this will be interesting for mods like illuminations.

Really don't understand why users would like fabric more, yeah its more lightweight and simpler but thats really it. Also most of the use of modloaders only comes for the developers using them to make mods, all users do is install the modloader and download the mod.

**Comment by nonamecrackers2** [comment]
I myself don't plan on making a fabric port. I chose forge as that's what I'm comfortable with, and since the mod uses a bunch of forge related api stuff porting is simply not worth my time.
