### ISSUE TITLE
The Game Crash

### ISSUE THREAD

**Issue by Accidey** [nonamecrackers2/crackers-wither-storm-mod#44]
>
[crash-2022-05-29_15.34.58-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/8792868/crash-2022-05-29_15.34.58-client.txt)
The game will crash after the withering storm removes the invincible state.
I hope you don't mind my poor English.

**Comment by Loverxzc** [comment]
Are You from Russia?

**Comment by ntck** [comment]
you have a shader on, turn "Block Cluster Colouring" off in the mods client settings, or turn off internal shaders

**Comment by nonamecrackers2** [comment]
^
