### ISSUE TITLE
A New Phase for the Wither Storm

### ISSUE THREAD

**Issue by Oxide2** [nonamecrackers2/crackers-wither-storm-mod#440]
there should be a phase for the wither storm where once it reaches phase 2, it grows one of the wither storm heads but without a tractor beam.
![latest](https://user-images.githubusercontent.com/110611209/182852729-7a055a89-99f5-48ec-a140-57634a3779c8.jpg)

**Comment by nonamecrackers2** [comment]
Messing with the phases at this moment doesn't make much sense and I personally prefer how they are at the moment.
