### ISSUE TITLE
Wither Storm Corrupting Blocks

### ISSUE THREAD

**Issue by PPengo** [nonamecrackers2/crackers-wither-storm-mod#441]
This would probably be a hard feature to implement, but I thought it'd be cool. So the Wither Storm can corrupt mobs with wither sickness, and monsters can turn extremely corrupted, some zombies turning into symbionts. My idea is that the same mob infecting process can happen to blocks, if the ws is in an area for a while, the blocks in that area will get corrupted (replaced with blocks from the ws mod) and if a big enough spot is there, a tentacle could appear and act as a nuisance to the player. It could kind of act like sculk. Now this would be optional, but in a cave, the tentacles could come out from the walls too, but there are only ground tentacles as far as I know in the mod, so you don't have to implement that. As always, there should be a config option to disable this.

**Comment by Oxide2** [comment]
it should probably be for phase 5, 6, or 7 because it would make more sense.

**Comment by watersofnazareth** [comment]
This could be interesting but at the same time it'd be a lot of effort to implement and likely be very laggy

**Comment by ghost** [comment]
would be good if some wither sickness would fall onto blocks in phase 6 and up.
then the corruption would begin.

**Comment by Luke7381** [comment]
Probably would be good for later stages as it has more power.

**Comment by nonamecrackers2** [comment]
Interesting however would require a lot of effort.

**Comment by GrandmaPork** [comment]
Idk about this happening when it’s alive but it’d be cool if the corpse did this before it was awakened
