### ISSUE TITLE
Weird wither sickness bug

### ISSUE THREAD

**Issue by KrukAdrian** [nonamecrackers2/crackers-wither-storm-mod#444]
**Minecraft version**
1.18.2
**Mod version**
1.18.2
**Describe the bug**
It usually happens in multiplayer worlds and the bug is that mobs have the wither sickness layer on even though they arent sick. This bug happended to me a couple of times and keeps on happening.

**Screenshots**
![Zrzut ekranu (1389)](https://user-images.githubusercontent.com/106917942/182930082-ab474b5b-2c5f-4433-85f8-ea5a108f94f8.png)

**Comment by nonamecrackers2** [comment]
What other mods are you using?

**Comment by KrukAdrian** [comment]
I wasn't using any other mods. It was just the wither storm mod

**Comment by nonamecrackers2** [comment]
Do you have smooth lighting off and/or the fabulous graphics setting enabled?

**Comment by watersofnazareth** [comment]
This was in the testing server, but for me I didn't have this issue, which is odd

**Comment by nonamecrackers2** [comment]
@KrukAdrian if you could figure out a way to reliably reproduce this issue that would be helpful

**Comment by KrukAdrian** [comment]
I just noticed that i had smooth lighting off. I'm trying to figure a out a way to reproduce this issue
