### ISSUE TITLE
Ivor's failsafe potion

### ISSUE THREAD

**Issue by 2resa** [nonamecrackers2/crackers-wither-storm-mod#445]
It would be cool it the failsafe/enchanted potion was in the game and here are my ideas. 

So first is my idea to make it. so you'd need a healing potion (healing potions hurt undead mobs) and weakness potion, some blaze powder and a wither flower or a withered bone/flesh then put it in a crafting table. Then its done and ready to use.

Now the uses for it. 
First if you somehow get it before you summoned the wither storm you could use it on the wither storm when its starting up or in early phases where the command block is exposed to kill or turn it into a normal wither.(obviously you wont get the withered nether star because you didn't kill it at its final stage)

Second you could use it on the withered symbiont to do either 2/3 or 1/3 of the symbionts health depending where you hit him with it. If you hit him on his back with it 2/3 but anywhere else is 1/3.

Third is when you're in the bowels you can use to do 1/4 of the command blocks health (like a command block tool) because if it instant killed it, it would get rid of the fun of the boss fight.

Thanks for reading

**Comment by KrukAdrian** [comment]
This was already a suggestion made by me its in #217
