### ISSUE TITLE
Did my Wither Storm despawn?

### ISSUE THREAD

**Issue by Ohyaboiii** [nonamecrackers2/crackers-wither-storm-mod#446]
This may be an extremely stupid question and I apologize if it is, but I'm worried that there may be some sort of bug with my wither storm. I summoned it at 0x 0z and ran a few hundred blocks to create a nether portal. From there I traveled about 6-8k overworld blocks and made a portal back to the overworld so I could have time to prepare for a battle with it. Then I decided to test something by checking the chunks loaded, and it said 0 chunks out of 0 forced chunks loaded. Does this mean that my Wither Storm is just gone? Or does the Wither Storm just sometimes not load chunks? Any help would be appreciated, thanks!

**Comment by jaredniegas** [comment]
I think mine despawned too. I went too far and it's just gone.

**Comment by nonamecrackers2** [comment]
If you have optifine and this is on a singleplayer world, you need to disable "smooth world" as the setting causes it to unload.
