### ISSUE TITLE
WAY TO MUCH LAG!

### ISSUE THREAD

**Issue by RyanExternal** [nonamecrackers2/crackers-wither-storm-mod#447]
1.19

1.19
witherstorm has more than usual tractor beams, lags the whole server.

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by KrukAdrian** [comment]
The wither storm has usually only 3 tractor beams through phase 4-6. In phase 7 it has 9 tractor beams so what seems to be the problem?

**Comment by Ohyaboiii** [comment]
More details? Do you know how much RAM is allocated to the server in question? Also, if by chance you are using a server from aternos.org, then expect lag, because their servers are free.

**Comment by nonamecrackers2** [comment]
Seems like segment duplication, which is already being tracked here: #222. Also please fill the entirety of the template you were given, and include the mod version instead of repeating the game version.
