### ISSUE TITLE
[Suggestion] Wither Storm Structure Targeting

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#448]
Unsure of this being possible, but it'd be neat if the WS when getting close to a structure generated by the world it would stare directly at it for a while, [2 minutes or so] to rip the structure apart and after that time is up its set to target mobs around that area like normal, that way players [and mobs once fear is added] can escape from it while it tears apart the structure, if more elaboration is needed I can do my best to do so

**Comment by UrMomInFort** [comment]
yeessss this needs to be added

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/87

**Comment by watersofnazareth** [comment]
This isn't the exact same as that one

**Comment by UrMomInFort** [comment]
what

**Comment by RandomGithubUser32** [comment]
Yeah sorry about that

**Comment by nonamecrackers2** [comment]
I feel the Wither Storm's ultimate target should always be a player and it shouldn't target other mobs specifically (it being distracted is it targeting random points nearby; in the future it'll be structures nearby). However this idea could be used in conjunction with #87, with the Wither Storm becoming distracted if it bumps into structures. I'd want to test this idea out however.

**Comment by watersofnazareth** [comment]
To clarify a bit more of what I meant was that if it is in range of  a structure it should try targeting it to rip it apart while it's around that structure, not becoming distracted by it, my wording may have been a lil confusing, but it'd make it so it'd be better at ripping things like villages apart

**Comment by watersofnazareth** [comment]
I don't think it'd need to be distracted by them unless the player is sitting in a loaded chunk with a structure nearby basically same idea as it speeding up in a way

**Comment by nonamecrackers2** [comment]
Ah I see, that could work as well
