### ISSUE TITLE
Starter Structure Location Problem (sea)

### ISSUE THREAD

**Issue by UrMomInFort** [nonamecrackers2/crackers-wither-storm-mod#449]
Most of the times i create a survival, the shed on where the wither's located at is literally on a floating island on the middle of the sea.
What is bad about this is that:
If you try to run from the wither, it wont destroy any blocks because he's not on land, and he'll freeze on the air on the first phase.
There's a way to fix him tho:
If you make the wither see you, he will follow you wherever you go, but at first i had no armor whatsoever and wanted to run from him.
Half an hour later i realized he wasnt even moving, so i had to manually make him follow me to land.
Please adjust the spawn of this structure to be on the nearest terrain near 0  , 0 
Not on the middle of the sea!

(hope you understood any of my wordings as i am not good at this, i can re-post this in a better explained way if you didn't.)

**Comment by nonamecrackers2** [comment]
While it is a little weird there isn't a solid way to ensure it'll generate near non-ocean terrain. Also it does still pull in blocks while over water, and I don't see it freezing being an issue since when it evolves it'll start chasing the player anyway.
