### ISSUE TITLE
Add Ivor Potion

### ISSUE THREAD

**Issue by SaiDGaming** [nonamecrackers2/crackers-wither-storm-mod#450]
Potion that can kill wither storm on first phases of evolution when command block is seeable for player.

**Comment by DonnerMan** [comment]
he already said no

**Comment by SaiDGaming** [comment]
> he already said no

oh, okay then.

**Comment by KrukAdrian** [comment]
Please just check in #217 this has already been suggested

**Comment by SaiDGaming** [comment]
As i see it was suggested before and cancelled
