### ISSUE TITLE
Glowing Symbiont

### ISSUE THREAD

**Issue by IntrovertedGamer** [nonamecrackers2/crackers-wither-storm-mod#451]
Sometimes it's hard to actually find where the withered symbiont is depending on what biome it spawns in, to fix this, the Symbiont will have the glowing effect upon spawning from the witherstorm. (This effect lasts until it engages in combat)

**Comment by Frask0** [comment]
I've had this problem a lot to, and it's pretty annoying, so I think this is a really good idea, as it makes locating a Symbiont in like a Oak Woods Biome easier, and overall make the progression of the mod smoother.

**Comment by RandomGithubUser32** [comment]
He said that the withered symbiont is supposed to be hard to find.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/305

**Comment by IntrovertedGamer** [comment]
Could it still be a config option?

**Comment by RandomGithubUser32** [comment]
I don't know. This is not my decision.

**Comment by nonamecrackers2** [comment]
I don't plan on changing default behavior however I could consider a config option

**Comment by nonamecrackers2** [comment]
I feel like making the symbiont "glow" would be kind of cheap as the intention is to try to hunt around carefully, avoiding the Wither Storm, for the symbiont.
