### ISSUE TITLE
Make curing time quicker

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#452]
When a player is infected with the Wither Sickness, they can make Golden Apple Stew to heal them. Unfortunately, the curing process takes a long time. Maybe shorten the process by 30 seconds? 

Thanks;
Gort

**Comment by BlueToadTide** [comment]
Or add it to the config so that you can change the curing time.

**Comment by Sculkter** [comment]
I’m certain there is already a config to change the time it takes to cure wither sickness. If you scroll to the bottom of world options and click wither sickness, you should find it there!

**Comment by nonamecrackers2** [comment]
Yes there is a config value. I don't currently have any intentions on changing the time it takes to cure.
