### ISSUE TITLE
java.lang.IllegalStateException: wither_sickness_immune used before it was bound

### ISSUE THREAD

**Issue by NoobGamerHD** [nonamecrackers2/crackers-wither-storm-mod#453]
**1.16.5**

**1.0.2.4**

**Describe the bug**
After a while, in a multiplayer server, the player that joins the world (never the host though) will crash and have the message "wither_sickness_immune used before it was bound" in the crash report.

**To Reproduce**
1. Join a server with the mod
2. Play for a while with the storm
3. Crash lol

**Crash Reports / Logs**

[crash-2022-08-06_19.02.59-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9275841/crash-2022-08-06_19.02.59-client.txt)

**Comment by watersofnazareth** [comment]
Join a single player world then the server

**Comment by NoobGamerHD** [comment]
Thanks, i'll try doing that once it happens again, then i'll close this issue.

**Comment by nonamecrackers2** [comment]
This has already been reported: #240

**Comment by NoobGamerHD** [comment]
oh alright, i'll close this then.

**Comment by NoobGamerHD** [comment]
Oh alright then, didn't know,

**Comment by nonamecrackers2** [comment]
All good
