### ISSUE TITLE
More Detailed Phase 6

### ISSUE THREAD

**Issue by BlueToadTide** [nonamecrackers2/crackers-wither-storm-mod#454]
When the F-Bomb goes off the segments fall off around the top of the mass of the wither storm, which it should be next to the main head which would make more sense, like it does in MCSM, this isn't really necessary but it'd be more correct.

**Comment by nonamecrackers2** [comment]
While it would make more sense, I don't feel changing the look of phase 6 would make much sense at this point and it would take a lot of extra work for something I don't think most people would really care about/notice.
