### ISSUE TITLE
Super TNT stunnung the Witherstorm

### ISSUE THREAD

**Issue by MicrowaveTheDum** [nonamecrackers2/crackers-wither-storm-mod#456]
I know this sounds stupid, but maybe make the Super TNT stun the Witherstorm

**Comment by RandomGithubUser32** [comment]
Maybe Super TNT can disable all the heads for a while and slow down the wither storm.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
This would be great considering super tnt is useless right now to the wither storm

**Comment by nonamecrackers2** [comment]
Interesting however I don't think the effort to obtain super tnt would justify this use case (you'd effectively be wasting a command block book)
