### ISSUE TITLE
Animated tentacles

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#457]
I understand that having the tentacles actually attack mobs can be really hard to code so if that does not get added, it would still be awesome if the tentacles moved and curled up. There are many clips of this in Minecraft story mode. There are also some images in [this page.
](https://minecraft.fandom.com/wiki/Minecraft:_Story_Mode#Episode_1:_The_Order_of_the_Stone)

**Comment by nonamecrackers2** [comment]
I've outlined my opinion of the current state of tentacle movement here: #47. The slow moving tentacles have grown on me and I quite prefer them, providing more of menacing feeling and capturing the absolute scale of the beast. Changing how they move isn't on my radar right now, however if more people request this I may revisit this in the future. Thanks

**Comment by RandomGithubUser32** [comment]
I do agree that the tentacles should not move quickly. However, having more curvey tentacles that don't stay in the same position as in minecraft story mode looks pretty cool in my opinion. Great mod as always.
