### ISSUE TITLE
Add More Functionality To The Amulet?

### ISSUE THREAD

**Issue by Birbman13** [nonamecrackers2/crackers-wither-storm-mod#458]
The Amulet is a very cool item in story mode. It lacks much functionality in this mod.
Perhaps players can link the amulet to themselves via some method. Maybe if the player with the amulet pointed it in the direction of someone who linked themselves to it, the amulet would glow like in Story Mode. 
The amulet is very important in the game, so making it unique in the mod could be a great idea too.

I love this mod, it's super well made, and I look forward to seeing the progress in the future!
Thanks!

**Comment by nonamecrackers2** [comment]
Interesting idea, however I fail to see how this could be useful in a survival playthrough.

**Comment by SSgamingYT** [comment]
it could help in case people get lost

**Comment by TaintedBlockk** [comment]
Maybe be able to config the Wither Storm to follow the amulet? And if it gets it will follow the person who last had it and if it gets THAT person it will go after any other player like normal.

**Comment by Joshowa5** [comment]
why not use the amulet with maps like in mcsm where you can to use beams and it will point to the players that are linked to the amulet on the map

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
