### ISSUE TITLE
More withered variants of mobs

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#459]
NEW: Mobs such as pigs, sheeps, cows, villagers, horse etc would have a withered variant of themselves, most if not all will be hostile

OLD: I wanted to see a truly withered land where pigs, chickens, cows and villagers are turned into a withered versions of themselves they will all be hostile to

**Comment by myron-obsolete-account** [comment]
sickened villager seems to exist now 
![image](https://user-images.githubusercontent.com/53058491/218176526-9b66e76e-833b-4c04-88a1-db65eb236d15.png)

**Comment by Resuster** [comment]
reminds me of the parasite mod where it infects everything i like it
