### ISSUE TITLE
Better Phase 1 - 3 Model

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#46]
In phase 1 - 3 the shape of the Wither Storm looks really flat, is it possible to add a bit more mass to the back of it? And in phase 3 the tentacles look weird because they're all pointing to the front and have the same shape, my suggestion would be to remove one of the lower ones and make the top one shorter and point to the sky.

**Comment by nonamecrackers2** [comment]
I personally prefer the tentacles and the models as they are and I don't think it's entirely necessary to change them at the moment.
