### ISSUE TITLE
Make the Withered Nether Star useful

### ISSUE THREAD

**Issue by MicrowaveTheDum** [nonamecrackers2/crackers-wither-storm-mod#460]
Maybe it could be used to craft a Withered Beacon as a weapon like the Corrupted Beacon from Minecraft Dungeons or it could also be used as a base protector.

(Nevermind, it was alr suggested, sorry!)

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/3
