### ISSUE TITLE
Maybe have a different use for the withered nether star other than beacon?

### ISSUE THREAD

**Issue by Bloxxify2827** [nonamecrackers2/crackers-wither-storm-mod#461]
Maybe as another thing you could with the other suggestion for using the withered nether star as a beacon, as you could use it to make another command block with it, with other rare materials, you could use the withered nether star for that too maybe.

**Comment by mmiller9196** [comment]
maybe a tractor beam spyglass?

**Comment by nonamecrackers2** [comment]
I don't plan on making command blocks craftable and will most likely go the beacon route. I do intend to make the WS respawnable.
