### ISSUE TITLE
Wither storm infects nearby terrain when playing dead

### ISSUE THREAD

**Issue by mmiller9196** [nonamecrackers2/crackers-wither-storm-mod#462]
I'd like to have it to where when the wither storm plays dead for the first time, to infect the nearby terrain and make a spreading "tainted biome" (like the corruption/crimson biome from terraria) that's exclusive to wither skeletons and infected mobs, it would be cool to have the wither storm warp the terrain along with its fake death, just to make it even more of a threat that it already is.

**Comment by watersofnazareth** [comment]
I think this strays a bit too far from Vanilla, but having remnants of its fall after it gets back up could be interesting [Blocks and Mobs]

**Comment by mmiller9196** [comment]
that sounds pretty good

**Comment by nonamecrackers2** [comment]
For the amount of time the Wither Storm is seen playing dead, I don't feel an advance terrain infecting system would see much spread, and the amount of work to develop the system wouldn't be justified in that sense. I do plan on adding block remains when the WS dies however.
