### ISSUE TITLE
distant lightning effect

### ISSUE THREAD

**Issue by KorewaMatt** [nonamecrackers2/crackers-wither-storm-mod#463]
I think it would be cool to add the effect of the sky flashing purple near the wither storm like in minecraft story mode

https://user-images.githubusercontent.com/110944967/183778989-bd3963a2-a5fb-4a10-97df-3570cda732ad.mp4

or

https://youtu.be/rAPeV1UP8XY?t=383 6:23 - 6:43

**Comment by watersofnazareth** [comment]
Kind of like a transformer exploding, I kinda like that

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2

**Comment by FatalERROR1234** [comment]
> Implemented in 2.2/3.2

That aged well.
