### ISSUE TITLE
The mcsm potion

### ISSUE THREAD

**Issue by KorewaMatt** [nonamecrackers2/crackers-wither-storm-mod#464]
add a potion to kill wither storm/make it envolve faster if you use it in phase 0 - 1 like minecraft story mode.

I don't see much functionality for it if you have cheats on, but its a way you can kill the wither in early phases or a no-cheat way to make the wither storm evolve faster

1 - let's say that for some reason you regret spawning the wither and you don't want to go through everything  to have to kill it or you dont have acess to commands, just throw the potion at him and he will die (without dropping anything)

2- in minecraft story mode the potion didn't work very well, and in mcsm it evolves to phase 3 much faster than in the mod, so the potion can make it evolve faster if you don't want to activate cheats or can't use commands

example: https://youtu.be/7fYG2vcZlfY?t=129

**Comment by watersofnazareth** [comment]
#350
#276
#450
#445 
#65

**Comment by andywowws** [comment]
actually we don't need that potion,you can use the command /give @p splash_potion{CustomPotionEffects:[{Id:6,Amplifier:29}]}
