### ISSUE TITLE
wither storm not an entity and w settings not working

### ISSUE THREAD

**Issue by HanginWithCoop** [nonamecrackers2/crackers-wither-storm-mod#465]
**1.18.2**
The version of Minecraft the mod is running on

**Mod version**
1.18.2

when i try to change the evelution or evelution speed and get to the section that you type the entity i type in wither_storm when i send the comand it says entity not found\

when i try to change it in the w button eaven as an op on my server it will not let me use the two bottom options

![report 1](https://user-images.githubusercontent.com/110949408/183788787-7da60c64-bbdf-4e4d-afa0-66cb2035cb87.png)
![report 2](https://user-images.githubusercontent.com/110949408/183788802-c6c287c8-86bc-47f0-bb2e-7788facf59a0.png)

**Comment by KorewaMatt** [comment]
try /witherstormmod phase set @e[type=witherstormmod:wither_storm,limit=1] 7 <---- phase number

**Comment by watersofnazareth** [comment]
You can't edit common and world on a server as a client, also the command functions with the @e command, @e[type=witherstormmod:wither_storm,limit=1] like Korewa said
