### ISSUE TITLE
[Suggestion] Wither Storm rotates around the player if the player has stopped moving

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#466]
Basically, if the player is staying in a certain chunk instead of the Wither Storm being entirely motionless it should slowly strafe left and right similar to a skeleton, probably with a config of [Do Strafing/Rotating = True/False]

**Comment by GrandmaPork** [comment]
def include the config. i honestly prefer the wither storm being motionless
