### ISSUE TITLE
Formidibomb immunity.

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#468]
When the hole to the final boss arena opens up, the wither storm should be immune to the forminibomb since when this happens, there is both a command block on the wither storm and also one in the bowles. This can be solved by making the wither storm immune to the formidibomb once the hole to the bowles opens up.  This does not need to be a high priority but it is still very awkward.

**Comment by RandomGithubUser32** [comment]
Not to mention the fact that players can use this to cheese the wither storm to get into the final boss arena more easily.

**Comment by Asteroid4** [comment]
I have an idea. When the wither storm is formidibombed once, it learns to not pick up the bomb. I think It makes a bit more sense this way.

**Comment by Asteroid4** [comment]
Aka it wont work in phases 6 or 7

**Comment by RandomGithubUser32** [comment]
That was what the mod was like at first where the formidibomb could only work on the wither storm at the end of phase 5 but he changed it so that the wither storm can be formidibombed in phases 4-7. Making it possible but more difficult to formidibomb the wither storm again is a pretty good idea.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
