### ISSUE TITLE
Rocket minecart?

### ISSUE THREAD

**Issue by 2resa** [nonamecrackers2/crackers-wither-storm-mod#469]
Don't know how it would work(maybe like a fuse or something?) but having the rocket minecart in the mod sounds fun.
And also having it as just a minecart you could use would be cool so you don't just use it to get into the witherstorm.

**Comment by nonamecrackers2** [comment]
Seems like fun, however it doesn't really fit in with my vision for the mod, and I don't think it would see much use in my opinion.
