### ISSUE TITLE
More tentacle movement

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#47]
The tentacles look awesome but they should move a little bit faster because they feel almost static the way they are right now. Especially the ones inside, in the command block room. They don't look alive

**Comment by nonamecrackers2** [comment]
The tentacles are designed to be slow as it doesnt make sense for a massive tentacle that ways a ton to move really fast in the sky. The rest is down to my personal preference and not really thinking they should move faster. If more people request this I’ll revisit it in the future

**Comment by myron-obsolete-account** [comment]
I cannot agree more to nonamecrackers2, because fast movements for something so large is just unlogical. I mean, take a look at Godzilla or Pacific Rim movies. They made the creatures slow for almost all the time too, since they are so large. Problem solved.

**Comment by BluePineappleGuy** [comment]
i think yes, slow movement, but they should move MORE. like, in story mode, the tentacles were kind of slow, but still active and destructive. currently the tentacles barely move that much. they should change their position more.
