### ISSUE TITLE
3 New feature sugestions

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#470]
1st: It was confirmed that the command block tool in Story Mode was destroyed after landing the last hit on The Command Block. I think that the tool you do the last hit with should break, making it a bit more balanced

2nd: Make it so mobs in a certain radius around the witherstorm that are on the surface and not infected run away from it like in story mode

3rd: Make the Command block tools look exactly like in story mode, a guy in your server made this even with emisive textures. I think he could help

Just a few suggestions I think would make this mod better

**Comment by Sculkter** [comment]
In my opinion, it’s hard enough to get a command block tool. For it to break after destroying the command block? That’s kinda odd.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/356
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/15
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/338
