### ISSUE TITLE
Mobs teleported out of bowels

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#471]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

When the wither storm dies, it should release all the mobs in the bowels, not just the player. That way you don’t lose your dog if he teleports in.

**Comment by KrukAdrian** [comment]
I mean how would this even work? Would they just fall out and live?

**Comment by nonamecrackers2** [comment]
They could have immunity like any other mob that falls out through the hole

**Comment by Asteroid4** [comment]
yeah, thats what i was thinking

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release. Tamed animals will be the only other mobs teleported out alongside the player.
