### ISSUE TITLE
Add this variant [joke]

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#472]
https://user-images.githubusercontent.com/48260861/184024387-d1e6d6f4-5f40-4feb-b130-9a0ed2810721.mp4

https://user-images.githubusercontent.com/48260861/184024537-3314808c-7db9-40d0-a37f-03cb37f0a35e.mp4

https://user-images.githubusercontent.com/48260861/184024626-8d4bdfdc-4ad4-469c-a852-e0957cf0898a.mp4

This is merely a joke suggestion and it isn't canon in anyway but if you somehow considered this i would not only be surprised but thankful.

This would be good for a truly hard mode super boss of the wither storm
It would have these attacks
The main wither storm main head would shoot a giant purple laser out of its mouth. The laser would destroy and kill everything in its path.

Every wither storm head would not only shoot flaming wither skulls but would also constantly shoot purple sphere projectiles that causes explosion on impact but doesn't leave a fire and the explosion radius is smaller

3 purple tornadoes would constantly follow this variant, most blocks and entities will have a chance to get flung into the sky, The tornadoes will also immediately inflict wither sickness

Instead of 2 massive severed wither storms there is 5 wither storms with different sizes
![image](https://user-images.githubusercontent.com/48260861/184026274-3a70805b-4ae6-42b4-82d3-63a96c5591c7.png)
2 spitter minions (the smallest ones)
2 Bulker Minions (the 2 above the spitter minions)
1 bulker minion (the largest one)

This variant of the wither storm will make the sky completely purple and everything will be very dark

Again i know you probaby won't add this but maybe you could get some ideas out from this.

**Comment by watersofnazareth** [comment]
This veers way to far from Vanilla which the mod is trying to replicate

**Comment by KrukAdrian** [comment]
honestly

**Comment by Luke7381** [comment]
> This veers way to far from Vanilla which the mod is trying to replicate

Yes i know thats why i referred to it as a joke suggestion and ive also stated that it isn't canon, I don't expect it to be added. Cracker could potentially get idea out of it tho

**Comment by nonamecrackers2** [comment]
That looks very brutal and is not what I have in mind necessarily for increasing the difficulty, sorry
