### ISSUE TITLE
Block pickup blacklist

### ISSUE THREAD

**Issue by BudgieGryphon** [nonamecrackers2/crackers-wither-storm-mod#473]
Certain modded blocks that are otherwise indestructible(specifically End Remastered's portal blocks) can be picked up by the Wither Storm. A pickup blacklist would help a lot here.

**Comment by nonamecrackers2** [comment]
This will be implemented as a tag that can be overridden with datapacks

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release as a tag
