### ISSUE TITLE
Endermen slowing down the wither storm

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#474]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.
My idea is to have endermen in the tractor beam teleport away, but also start holding a flesh block as they do so. This will cause the wither storm to decrease in speed and consumed entities. Also, when the hole forms, endermen would spawn holding flesh blocks near it.

**Comment by Luke7381** [comment]
Endermen attacking the wither storm had been suggested many times already, im sure it will be added in a future update

**Comment by Asteroid4** [comment]
oh, ok.

**Comment by watersofnazareth** [comment]
#141
