### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by tntpat** [nonamecrackers2/crackers-wither-storm-mod#476]
So I think that when the f-bomb is used on the wither storm, his body is all made of blocks, with no other entitys.
I Think that the amulet should be crafted with stuff from the four people. Like tnt, diamonds, redstone, and emeralds.
And finaly I think there should be a system where enderman pull of flesh from the wither storm, slowing it down and opening the bowels.

**Comment by watersofnazareth** [comment]
This would look very ugly and wouldn't work well
The amulet is a server utility item not meant for crafting
#141

**Comment by nonamecrackers2** [comment]
1. The blocks wouldn't be oriented properly and I could see multiple major issues with this feature, mainly the lag placing all the blocks and how I would convert the model over to blocks to be placed.
2. It is a server utility yes and is not meant to be crafted
