### ISSUE TITLE
witherstorm having more than 3 withers on phase 7?

### ISSUE THREAD

**Issue by RyanExternal** [nonamecrackers2/crackers-wither-storm-mod#477]
minecraft version 1.19

mod version: 1.19

after the formidi bomb is exploded and the wither storm turns into three, after a while 1-2 more tiny withers will appear. also more heads appear on the tiny ones. it lags like hell and is impossible to kill because one step foot outside and a tractor beam sucks you up.

theres no way to fix.

i dont have a crash report anymore.

**Screenshots**![image_2022-08-11_123614380](https://user-images.githubusercontent.com/110662926/184185105-0b30fb86-39ee-4617-b91e-c154fd567a54.png)
![image_2022-08-11_123655190](https://user-images.githubusercontent.com/110662926/184185393-a4ab9a59-1f2e-4bc0-bcb0-d82386c5b2d0.png)

**Comment by watersofnazareth** [comment]
#222
