### ISSUE TITLE
The descriptions of Wither Sickness, Formidibomb, Playing Dead and Withered Symbiont should be above the scrollbar

### ISSUE THREAD

**Issue by pox1016** [nonamecrackers2/crackers-wither-storm-mod#478]
**Minecraft version**
1.16.5 (probably also happens with the other versions)

**Mod version**
1.0.2.4

**Describe the bug**
The descriptions are always superimposed on the scroll bar, but in these options mentioned in the title of the report they are not superimposed and they cause discomfort to read.

**To Reproduce**
Steps to reproduce the bug:
1. Go to 'World Options' of the config of the mod
2. Scroll down to 'Wither Sickness', "Formidibomb", "Playing Dead" and "Withered Sybiont"
4. See the error looking at the descriptions pointing left so that the description appears on the right

**Screenshots**
![image](https://user-images.githubusercontent.com/109612890/184199524-1e287dcf-d75b-494f-b3bb-d9dc135a18a1.png)

**Comment by watersofnazareth** [comment]
I believe this is just a vanilla/forge bug

**Comment by nonamecrackers2** [comment]
Those buttons I actually wrote the code for, however I'm not sure I could get around the rendering order. I'll see what I can do.

**Comment by nonamecrackers2** [comment]
Yeah, looking at the code it appears there isn't a straight forward fix for this issue, sorry.
