### ISSUE TITLE
Solid dead body

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#48]
After killing the phase 6 wither storm with the f bomb and it lies on the floor one can walk on some blocks to the command block. But is it possible to make the rest of the body (of the entity itself that fell down, not the blocks that spawned) solid to walk on, too?
- That's the last suggestion. Really love your work because this is a crazily good mod.

**Comment by nonamecrackers2** [comment]
This is not possible due to Minecraft. Really happy you like the mod though.

**Comment by ScreamingMC** [comment]
It is possible, mods like create do it, already like the contraption entity. It's just very hard, but the effect is fire!
