### ISSUE TITLE
Evolution Progress

### ISSUE THREAD

**Issue by SmoothWolf20** [nonamecrackers2/crackers-wither-storm-mod#487]
Maybe instead of just having the wither storm suddenly change to a different look like from phase 4 to phase 5 when it consumes entities, maybe instead you should slowly add more blocks to it's body as it consumes them, until it gets to the next phase, it also adds a somewhat indicator for how long is left until the storm reaches it's next phase.

An example would be this video 
https://www.youtube.com/watch?v=ayXLA6hLjZQ

**Comment by nonamecrackers2** [comment]
#60
