### ISSUE TITLE
Music and bossbar should only trigger when you can actually see the wither storm nearby

### ISSUE THREAD

**Issue by M0ntherload** [nonamecrackers2/crackers-wither-storm-mod#488]
**Description of feature**
Right now, the music and bossbar only trigger when ws is close, which doesn't make the tension it should if you're in a cave.
But imagine the element of surprise when you finally get out to the surface after a pretty long caving session only to find the wither storm practically at your doorstep. And the bossbar with music would not dissapear if you went back in - only when you leave the area.
Really, if you can figure out how to fix ws tractor beam grabbing through walls (which would add on to the element of surprise, especially if you manage to make tractor beams not render in a scenario where there are blocks inbetween you and ws), you can make this as well.

**Comment by RandomGithubUser32** [comment]
I think this should be a config option because some players would like to know the wither storm is above them when caving.

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
