### ISSUE TITLE
Tentacle get in Nether Portal

### ISSUE THREAD

**Issue by Loverxzc** [nonamecrackers2/crackers-wither-storm-mod#49]
If Wither Storm very close with portal, tentacle enters the portal and doesn't let the player in. You have to hit him 5 times to get him out.

**Comment by nonamecrackers2** [comment]
Doesn't really fit in with what I want for the mod. It'll also spoil the surprise of the WS being on the other side when you come out of the portal.

**Comment by BluePineappleGuy** [comment]
i think it could happen if you try to escape the storm from the overworld
