### ISSUE TITLE
Wither Storm heads would give up when a targetted mob/player in the tractor beam isn't moving toward the mouth after configurable seconds/minutes

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#490]
**Description of feature**
If a player or mob is stuck under a roof or just isn't getting sucked towards the head at all the wither storm head would look for another open target after a configurable time, It kinda sucks just having to accept your fate once the wither storm targets you in any situation

**Comment by watersofnazareth** [comment]
This is going to be fixed

**Comment by nonamecrackers2** [comment]
This is actually kind-of implemented already however the value is hardcoded, so adding a config option or potentially even lowering the value would be good. I'd want to do some testing however.

**Comment by GrandmaPork** [comment]
in mc:sm, the wither storm only tried to pull in mobs for about 20 seconds before giving up

**Comment by nonamecrackers2** [comment]
Will be fixed in the next major release.
