### ISSUE TITLE
Game Crash When Connecting to a server

### ISSUE THREAD

**Issue by FoudreTeam** [nonamecrackers2/crackers-wither-storm-mod#491]
**Minecraft version**
The version of Minecraft the mod is running on
1.16.5 (on a modpack)
**Mod version**
The version of the mod you are using
1.0.2.4
**Describe the bug**
When i'm joining a server I my game crash and I got a error
**To Reproduce**
1. Connect to a server that have the mod
2. Game Crash

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.
https://pastebin.com/Xuy5bq2a
**Screenshots**
![CrashReport](https://user-images.githubusercontent.com/62184516/184464668-37aa7c0a-8313-42cc-a4b6-ae4405c86ec0.PNG)

**Comment by watersofnazareth** [comment]
Join a Singleplayer world then join the server

**Comment by FoudreTeam** [comment]
it's working thank you

**Comment by watersofnazareth** [comment]
You're welcome!
and because I forgot #240
