### ISSUE TITLE
Fishing rods can pull the command block entity

### ISSUE THREAD

**Issue by FriedSpuds** [nonamecrackers2/crackers-wither-storm-mod#492]
**Minecraft version**
1.18.2

**Mod version**
Latest

**Describe the bug**
Fishing Rods are able to pull the command block inside the wither storms bowels 

**To Reproduce**
1. Get a fishing rod
2. Fish the command block
3. See error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**
![2022-08-13_22 10 05](https://user-images.githubusercontent.com/111187807/184498259-55f9f023-d107-4349-9e94-ba8c5c39b1c4.png)
![2022-08-13_22 09 59](https://user-images.githubusercontent.com/111187807/184498286-409fe347-c6eb-4b8f-a868-f88a45693a6e.png)
![2022-08-13_22 09 56](https://user-images.githubusercontent.com/111187807/184498288-1442aa4d-8eb3-49ef-a32b-68bcc98769dc.png)

I even managed to pull it outside of it
![2022-08-13_22 26 40](https://user-images.githubusercontent.com/111187807/184498549-2042f978-3377-46a2-bd09-18a822b19c65.png)
 
also it does this if you attack it while its not in the bowels
![2022-08-13_22 30 22](https://user-images.githubusercontent.com/111187807/184498770-f1959067-12c2-45f2-8a35-322fa701ebf2.png)

 it does not defend its self using its tentacles
![2022-08-13_22 35 04](https://user-images.githubusercontent.com/111187807/184498902-4c0a307e-0d3f-410b-a764-f8cffc88da31.png)

 But Still spawns enemies
 ![2022-08-13_22 34 48](https://user-images.githubusercontent.com/111187807/184498933-8b4d6742-dac8-4052-a8bc-33ffc77dedac.png)

**Comment by ghost** [comment]
same with explosion's

**Comment by ShadeKage** [comment]
Definitely an easily fixable bug, should be fixed in the next update
That sure ain't no fish ive ever seen

**Comment by TaintedBlockk** [comment]
How to bring a Command Block home!
