### ISSUE TITLE
May have the bowels go upside down?

### ISSUE THREAD

**Issue by Bloxxify2827** [nonamecrackers2/crackers-wither-storm-mod#493]
Maybe you could have the bowels go updide down after it is hit for the 3rd time, maybe making a new dimension of it just upside down that tps you after hitting it? I wouldn’t have made this request if there was a gravity mod on forge for the versions of your mod. But there isnt, atlease not that i know of.

**Comment by watersofnazareth** [comment]
#105, please read: #217
