### ISSUE TITLE
Wither Storm model having Solid Collision

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#494]
While searching for mods to try I noticed the existence of a mod called Solid Mobs. This mod allows entities to have a solid collision just like blocks, without awkwardly moving away when being nearby. Why not making the WS have such addition, so physical blocks required to recreate his tentacles when the Command Block is exposed won't be needed anymore? The person behind Solid Mobs said that it's a function that can work on Forge, so I'm sure it could be possible.

**Comment by nonamecrackers2** [comment]
Are you talking about the command block tentacles in the bossfight?

**Comment by GoldenDarius** [comment]
@nonamecrackers2 I am actually talking about the moment where you F-bomb the Wither Storm. It generates tentacles with the flesh blocks and then the command block, and to be honest it kinda looks weird. However if the Wither Storm was a solid entity just like a block, you could walk on it and the blocks would become unnecessary, as you could simply use his tentacles for a walking platform

**Comment by SSgamingYT** [comment]
just make the tentacles have their own animation that allows you to access the block

**Comment by nonamecrackers2** [comment]
In that case, the solid mobs mod doesn't actually make the model solid but instead the hitbox of the entity solid. Since the hitbox does not overlay the model 1:1 this would not work, unless if I was to make a physics solver however I'm not willing to figure that out.

**Comment by BluePineappleGuy** [comment]
i mean you could have smaller hitboxes for the tentacles like you did with the heads, and make it solid when its collapsed (so not to break the beams), so its still somewhat possible
