### ISSUE TITLE
Withered Symbiont rework + aditional ideas

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#496]
The Withered Symbiont honestly feels... off to me.
I think for what it does and for the importance it has, it deserves a glow up. 
First of all, I'd like to highlight how the Symbiont makes zero sense design-wise. It's a being that comes from the inside of the Wither Storm. So why does it look like a zombie with tentacles? I would imagine it looking more wither skeleton-ish, with the face being a combination of a Wither Boss face and the WS face? One eye being purple so the pulling move can be executed with a small tractor beam coming from that eye. Another thing would be for it to have a command block interface onto its cest (that white part with the glowing squares) so the command block particles it sometimes emits actually make sense, as well as the deactivation sound it does when it's stunned. 
The second thing that could be done is certainly having actual Wither Skeletons spawning,  maybe a withered (even more) version of them, looking sick just like the other mobs, after all in Bedrock the Wither can summon Wither skeletons as minions (maybe making the first stages of the wither storm do the attacks it does in BE like dashing could give it a more unique feeling).
Lastly, it would be great if the Symbiont had its own custom themes, which could contain references/motifs of the Wither Storm theme, also many musicians would be interested in making this a thing.

**Comment by nonamecrackers2** [comment]
The Symbiont was actually designed intentionally to be the way that it is. It was originally going to be a "command block golem" however considering that the Wither Storm is the antithesis of creation, the golem didn't make much sense. The Symbiont is an entity (potentially human-like, up to your interpretation) that got trapped in the Wither Storm. It contracted an advanced variant of wither sickness that mutated tentacles and other mass on to it. The Command Block effectively uses the thing as a puppet to do it's bidding (the parasitic nature of it's infection and how it's utilized by the Command Block is the reason why it has the word "Symbiont" in it's name), and has some of the abilities of the block imbued inside of it (the reasoning of why there's the command block aura particles, why it can summon a wide variety of projectiles and mobs, etc.). 

I feel an entity with a half Wither Storm head would like kind of awkward. Changing the look of the Symbiont now as well doesn't make much sense, and I personally have grown to love the Symbiont as it is. I could potentially experiment with it looking like a wither skeleton, however I don't want to mess with the "lore" that is with the Symbiont; who it is, how it got in the WS, why it drops a command block book, etc. There's already #459 and I'll consider adding a sickened wither skeleton. Changing the music as well is not very important and I don't deem it entirely necessary.

Hope you understand my thoughts on the Symbiont. Thanks for the suggestions as always.

**Comment by GoldenDarius** [comment]
@nonamecrackers2 I absolutely understand the reasoning behind the Symbiont's look, and I think the half wither storm head can indeed be avoided, however if it did contract a stronger Wither Sickness, looking decayed and basically withered does make more sense than still being a recognizable humanoid, which is why I think a more wither skeleton look could work. After all the lore of wither skeletons is similar, they were humanoids who turned into skeletons due to the harsh conditions of the Nether upon death. It could still keep some chunks of "flesh" and clothes that belonged to its former humanoid self though.

**Comment by juanelgamer456** [comment]
i know this is old but i just wanted to add that the ws creates the symbiont to "kill the player for it"
i also know this doesnt make too much sense but this is the lore that i been told by tainted
