### ISSUE TITLE
Block clusters system rework

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#497]
Block clusters should increase in size depending on the phase the WS is in. If this is already a thing, then it's barely noticeable. Another issue I have with them is how repetitive they look in terms of shape, as they all have this round and spherical shape, and when you do kill the WS the moment they pile together they form these weird looking towers too, which doesn't help either. My solution to this is adding more variants to the shape clusters can have. The shapes should try and be more squared and extended, since this is Minecraft after all. When the WS dies, the clusters should be pushed away from it before beginning to fall, like if they were pushed back by an explosion, to avoid the formation of those weird towers. Lastly, a more smart way of clusters formation could be related to combination of blocks, so when the WS is targeting a specific area, let's say a structure made of wool, it should pick up as much blocks from there as possible, if not all, to mimic how the WS would get distracted by the wool buildings that everyone was making in Story Mode, and how he'd absorb all of them in no time.

**Comment by watersofnazareth** [comment]
#135

**Comment by nonamecrackers2** [comment]
Block clusters do actually increase in size and I do find it quite noticeable. Variations on cluster shapes is already confirmed. Also making block cluster collection more "smart" would be difficult and I could see some performance issues.
