### ISSUE TITLE
just some details (sorry if someone already asked for this)

### ISSUE THREAD

**Issue by juanelgamer456** [nonamecrackers2/crackers-wither-storm-mod#498]
so i just have some personal issues,
-the craft of the formidibomb should be like mcsm, only gunpowder and no blaze powder
-the aura of particles seems like too much too soon for the phase 4 and 5, it could be smaller or with less rings, aftter that, the phase 6 looks perfect
-i dont like the full resistance for when you fall form the bowels, i think you should just be ready for the fall with a bucke or a potion, or just being lucky
-vanilla mobs should start running from the wither storm instead of attacking the player at some point (i dont think you could make this one actually)
-there should be a potion to use againt the wither at his first phases, of course its not gonna be easy to craft it, but it could work for prevent "pranks" in servers with friends
-no offense to the modders but, the death aniation was kinda dissapointing, the way that the wither storm ends should be more epic that how the ender dragon does

(i dont know anything about programming or making mods so sorry if something is actually hard to make, and sorry again if this was aked for someone else or its not being added for some reason)

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/340
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/15
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/65

**Comment by nonamecrackers2** [comment]
1. Someone already suggested this (can't find it however). It uses blaze powder intentionally to make the bomb more difficult to acquire.
2. I can see how it seems excessive and not accurate to MCSM, however changing the look of the WS now doesn't make much sense and is not in my best interests.
3. #340 
4. #15 
5. #65 
6. I feel the death animation is fine as it is. I'm not sure what I could do to make it more epic and again, changing it is not in my best interests right now.

**Comment by BluePineappleGuy** [comment]
> 1. Someone already suggested this (can't find it however). It uses blaze powder intentionally to make the bomb more difficult to acquire.

what about using blaze powder in the recipie for super tnt instead? wouldn't change progression much, but would make it easier to craft the f-bomb (i always mix up the gunpowder and blaze powder)
