### ISSUE TITLE
Feature Suggestion: Command Block Damage

### ISSUE THREAD

**Issue by BigBillsHell** [nonamecrackers2/crackers-wither-storm-mod#5]
is it possible to add a config option where the mod allows the command block to be damaged using other means instead of just using command tools i.e using other weapons like crossbows, swords and etc? mainly because for some modpacks that want to utilize the fight inside in a different way rather than using Command Tools

if not, is it possible to give some sort of effect to the player that will allow them to damage the command block using other tools/items/weapons inside the Wither Storm?

**Comment by nonamecrackers2** [comment]
It would be possible, however the tools are part of the progression of the mod. If you could destroy the command block with another tool type, players could skip the second Withered Symbiont mini-boss fight. It would ultimately be up to players and modpack creators to come up with a balanced replacement that doesn't screw with progression  _too much_ (however I have no power with what people would do as replacements/other methods, so people could do whatever they wanted).

You can actually make a datapack and override the item tag "command_block_tools" and put whatever item you want in there to be able to attack the command block, however it'll have the side effects of having the command block aura particles around the item.
