### ISSUE TITLE
Dropz Mod Incompatibility 

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#500]
**Minecraft version**
The version of Minecraft the mod is running on
1.18.2
**Mod version**
The version of the mod you are using
Latest version
**Describe the bug**
Wither Storm won't pick up dropped items with the Dropz mod https://www.curseforge.com/minecraft/mc-mods/dropz 
**To Reproduce**
1 Summon the Wither Storm with the Dropz mod installed,
2 Drop any item
3 The Wither Storm won't pick up the item

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by watersofnazareth** [comment]
This is due to Dropz using a different entity/changing the items

**Comment by nonamecrackers2** [comment]
Looking at the code, a separate rigid body physics system is overriding the original velocity and motion calculations. CWSM would need to add an edge case which I am not up to at this given moment.
