### ISSUE TITLE
Can't join LAN-Multiplayer-Server with Witherstorm-Mod installed

### ISSUE THREAD

**Issue by EikAuto** [nonamecrackers2/crackers-wither-storm-mod#502]
Hello everybody,
I can create a LAN-Multiplayer-Server with Witherstorm-Mod installed,
but I can't join the Server from an other PC in LAN and get the the error-message: "InternalException:java.lang.IndexOutOfBoundsException".
Both Minecraft versions in LAN are exactly the same versions, and I have installed only the witherstorm-mod,
maybe you could tell me some troubleshooting :-)

By using the Forge-version 1.18.2 within the Mod-version 1.18.2 I can join the Server but the Mod doesn't work!
By using the Forge-version 1.19.2 within the Mod-version 1.19-3.0-beta I can start the Mod in the Server-World but then I can't join from an other PC in LAN!

Thank you for you time!

**Minecraft version**
1.18.2 - 
1.19.2

**Forge version** 
1.19.2-forge-43.0.8

**Mod version**
1.18.2 - 
1.19 (witherstormmod-1.19-3.0-beta.jar)

**Describe the bug**
By joining a server in LAN where the Witherstorm-Mod is installed (tested serveral mod-versions), I get the following error-message:

"InternalException:java.lang.IndexOutOfBoundsException"

**To Reproduce**
1. Go to Singleplayer and start a new World with Witherstorm-Mod installed, for example in version 1.19
2. Click on "ESC" and start the world in LAN.
3. Get on an other PC in the LAN and try to join the Server.
4. See error "InternalException:java.lang.IndexOutOfBoundsException"

**Comment by nonamecrackers2** [comment]
Anything in the logs?
