### ISSUE TITLE
Two more animations

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#503]
The wither storm should close its eyes when just spawned and open its eyes when its invulnerability period ends. This might look awkward so I get it if this does not get added. I also found a cool death animation on [this page](https://minecraftstorymode.fandom.com/wiki/Wither_Storm?file=Wither_Storm%2527s_defeat_%2528Netflix%2529.png) where the wither storm glows when dying.

**Comment by watersofnazareth** [comment]
The invulnerable state is handled by a texture so you can make a resource pack for this if you wanted, The death animation is similar to the Ender Dragons

**Comment by RandomGithubUser32** [comment]
The death animation similar to that of the ender dragon does not need to be deleted. I am just saying that the wither storm along with the flying debris glowing could look pretty cool with the death animation we currently have.

**Comment by nonamecrackers2** [comment]
Considering that the normal Wither doesn't close it's eyes and that this could be achieved using a resource pack means that this doesn't need to implemented into the mod. The closest thing to a "glow" I could do is make the textures emissive, however that would require re-rendering the entire model twice (I believe, one for non-emissive then the emissive layer is on top) causing more performance drops.

**Comment by RandomGithubUser32** [comment]
Yeah, maybe just a texture change for the death animation and maybe use the already present glow effect. I was never talking about emissive textures.
![2022-08-15_22 29 20](https://user-images.githubusercontent.com/109647302/184785600-9ea321ed-fe75-43eb-b18d-fb0a8cb15f2e.png)
something like this

**Comment by GrandmaPork** [comment]
Aren’t emissive textures limited to those with Optifine? Also, couldn’t that be done with a texture pack?

**Comment by RandomGithubUser32** [comment]
Well, it was a texture pack but it makes the wither storm pink all the time, not only when the wither storm dies. The magenta glowing effect around the wither storm is in vanilla but limited to commands.

**Comment by nonamecrackers2** [comment]
Looks pretty funky, however changing the death animation is not in by best interests as of now.
