### ISSUE TITLE
Issue on VR 

### ISSUE THREAD

**Issue by Bloxxify2827** [nonamecrackers2/crackers-wither-storm-mod#505]
Version: 1.16.5 Vivecraft

Mod version: Crackers wither storm 1.16.5

The bug:
When i go into the bowels of the wither storm (VR) I get an infinite loading screen, no crash, just infinite loading screen

**To Reproduce**
1. Go into Vivecraft with mods allowed in the installation process
2.Insert Crackers wither storm mod into the minecraft directory (1.16.5) 
3. Go into a world and summon the wither storm (Phase 7)
4. Go into the bowels

**Crash Reports / Logs*.
No crash report

No Screenshots

**Comment by nonamecrackers2** [comment]
Does this occur with other dimensions? I feel this is a hardware performance issue.

**Comment by Bloxxify2827** [comment]
> Does this occur with other dimensions? I feel this is a hardware performance issue.

I didnt have any issue going into the nether/end
