### ISSUE TITLE
[Major] Memory Leak caused when a world doesn't have generated structures

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#506]
1.16/1.18/1.19

Any

Game will continuously search for bowels structure in chunks but will never find it till the PC crashes

1. Go to Create New World
2. Click on More World Options
3. Turn off Generated Structures
4. Summon the Wither Storm
5. Memory Leak

**Comment by ThrillOBlade** [comment]
That happened to me when I was testing it on Genshin maps
