### ISSUE TITLE
Wither Storm destructivity buff (For 1.19 and/or 1.18.2)

### ISSUE THREAD

**Issue by ThrillOBlade** [nonamecrackers2/crackers-wither-storm-mod#507]
I would love to see the wither storm getting a buff on it's destructive powers

I do love to admire the wither storm mod, but I wish you to tweak its powers a bit and here is a list that I want you to add and update in the near future:

- Tractor Beam Particles
- Mobs and Entities getting locked within the tractor beam instead of falling out (If they can't move themselves out of it) even when the wither storm moves it's head to another direction
- Wither Storm consuming a cluster amount of mobs instead of just eating 1 at a time as other mobs kept falling out of the tractor beam and I'm not surprised that happened when I tested it out
![image](https://user-images.githubusercontent.com/111252518/184557326-53afdce9-d239-4c27-99ab-2e9652c35401.png)
- If its could be possible you can add these: Blocks Clusters getting bigger when absorbed or sucked up and especially a block cluster or a structure or building gets shattered into single block pieces when getting sucked up through the tractor beam like in story mode
![image](https://user-images.githubusercontent.com/111252518/184557231-2c4a2c23-3ff6-4111-9577-13a4a4ffed48.png)
- Blocks/Block Clusters have a bigger chance of getting sucked up when their in the tractor beam for a while if they haven't gotten picked up by it
- More official sound effects for the wither storm all from here: https://minecraft.fandom.com/wiki/Minecraft_Story_Mode:Wither_Storm#Sounds
- Tentacles that can break through blocks and even obsidian and grab mobs
 
Anyways if you are done reading this, Thank you and have a good day updating and adding these new features

**Comment by watersofnazareth** [comment]
#12
#14
Block Clusters at least for now cause a lot of lag

**Comment by Luke7381** [comment]
Most if not all of these had been requested already

**Comment by nonamecrackers2** [comment]
1. #14 
2. This would take some effort to figure out and I don't think this is entirely necessary
3. #299 
4. I could see a lot of lag from this. With the size of most clusters it picks up I don't feel this is entirely makes sense. It would also take some effort to figure out what pieces should break off. I may reconsider this in the future.
5. This is already in the mod.
6. I may consider more sounds in the future however a different suggestion should be made for this (if this hasn't been suggested yet, not sure).
7. #12
