### ISSUE TITLE
Wither storm showing up on map

### ISSUE THREAD

**Issue by 2resa** [nonamecrackers2/crackers-wither-storm-mod#508]
If the wither storm shows up on maps not only would it be cool it could give you a better estimate of when it will arrive.
The wither storm could show as a point or a cooler option but may be hard to implement it a top down view of the wither storms current phase.

This feature isn't super viable if you spawn him immediately since even a max tier map would be small for the wither storm but if you had prep time and a map room it could help quiet a bit.

**Comment by nonamecrackers2** [comment]
I'm fairly certain map icons don't update dynamically when on a map wall, and as mentioned the max sized tier of map may not be big enough to be useful.
