### ISSUE TITLE
Make the tractor beams pick up dropped items

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#509]
**Description of feature**
I noticed the wither storm never pick up items unless you get extremely close to it so can you make the tractor beams pick up items?

**Comment by ThrillOBlade** [comment]
Oh shit, I actually forgot to add this to my suggestion list on where I was thinking about that lol

**Comment by watersofnazareth** [comment]
This technically falls under #152
