### ISSUE TITLE
Particles for the tractor beam

### ISSUE THREAD

**Issue by pox1016** [nonamecrackers2/crackers-wither-storm-mod#510]
In the MC Story Mode it is seen that the tractor beam of the Wither Storm has particles, adding them would be very cool and would give a very nice detail.
![image](https://user-images.githubusercontent.com/109612890/184567641-028fb731-d555-4354-8426-0bb069cea072.png)

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/14
