### ISSUE TITLE
[Suggestion] Falling Blocks around the Wither Storm get converted into Block Clusters

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#511]
Basically in nearby chunks to the Wither Storm have it so whenever falling blocks are created they get converted into a Block Cluster

**Comment by ghost** [comment]
what if the falling blocks are under ground?

**Comment by watersofnazareth** [comment]
Block Clusters phase through blocks but could probably have a check if they have visibility to the sky
