### ISSUE TITLE
Wither mobs in remains

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#512]
So on the discord, wither storm remains have confirmed. 
so i thought of a danger of the remains of the wither storm. say if the player were to go mining into the wither storm to remove the it.
the player would encounter mobs stuck in there and when the player has mined all the blocks around that mob. it would be free but with a taint of wither sickness.

**Comment by watersofnazareth** [comment]
Given how the mobs in blocks will work I'd say this is probably impossible to do unless the blocks just randomly spawn mobs

**Comment by ghost** [comment]
yes. that would probably work.

**Comment by nonamecrackers2** [comment]
If this was to be implemented I feel this should only work on non-player placed tainted blocks if that's even possible.

**Comment by V0calgiant12** [comment]
> If this was to be implemented I feel this should only work on non-player placed tainted blocks if that's even possible.

Could do it similar to how Mojang did with sculk shriekers. Have a tag that is set to true by naturally spawned blocks, and false when placed by a player.

**Comment by nonamecrackers2** [comment]
Yeah, that's what I was thinking.

**Comment by V0calgiant12** [comment]
is this going to be closed as it is in the game or are you planning on keeping it open incase you decide to make it so that player placed ones don't have them?

**Comment by nonamecrackers2** [comment]
This suggestion is different. It's specifying that tainted blocks should have a chance to spawn a sickened mob.

**Comment by V0calgiant12** [comment]
ohhhh, I thought it meant that there were dead mobs inside the blocks. I feel dumb now.

**Comment by nonamecrackers2** [comment]
Won't be added, especially since theres now mob spawners in the bowels spawning sickened mobs
