### ISSUE TITLE
Buff to the Command Block weapons

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#513]
Compared to Story Mode, the command block tools and weapons feel kind of weak, and I was thinking that maybe they could have a little extra to them. Make so that the Command Block tools deal more damage to "withered" mobs and mobs related to the Wither Storm (heads, tentacles, Symbiont, Withered Monsters and maybe Wither Skeletons and Wither Boss). It could even grant more chances to get Withers to drop their head to facilitate the resummoning of a Wither Storm since it is a planned feature.

**Comment by watersofnazareth** [comment]
There's no need to buff them at all unless you wanted to make the final boss fight easier

**Comment by GoldenDarius** [comment]
It will at least nerf the tentacles a bit as they are quite unfair sometimes when you try to damage them, in fact if you watch Story Mode, Jesse easily cuts a tentacle with his enchanted weapon. Sometimes the fight in the bowels gets too long due to the amount of things happening at the same time. Either way this could easily become something you can use against Wither Bosses and Wither Skeletons too, so it can help respawning the Wither Storm

**Comment by RandomGithubUser32** [comment]
Maybe just the tentacles. Netherite tools are already completely useless in this mod.

**Comment by GoldenDarius** [comment]
That's why they are adding netherite command block tools

**Comment by RandomGithubUser32** [comment]
Yeah sorry about that

**Comment by nonamecrackers2** [comment]
I'm considering netherite variants of the command block tools, however buffing them will make them way too strong and they may overshadow other toolsets added by other mods.

> It will at least nerf the tentacles a bit as they are quite unfair sometimes when you try to damage them, in fact if you watch Story Mode, Jesse easily cuts a tentacle with his enchanted weapon. Sometimes the fight in the bowels gets too long due to the amount of things happening at the same time.

Honestly this would remove some of the difficulty and I personally find the fight a little short as it is right now.
