### ISSUE TITLE
A few suggestions from the curseforge page

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#515]
1: The wither storm rises theme should play when the wither storm rises in phase 6 with the two smaller wither storms. (theeyeofgamingxd)

2: Sickened mobs constantly spawn in the bowles if the player has not broken the command block yet as well as the wither storm sometimes grabs the player when they are fighting the withered symbiont.
(errorsbill)

3: A way to configure how frequently the wither storm shoots out flaming wither skulls.
(ivorfromminecraftstorymod)

4: An option for the wither storm to only follow players with the amulet.
(will_rblxyt)

These suggestions are from other people not me

**Comment by nonamecrackers2** [comment]
While I appreciate bringing in those suggestions, it's up to those people to suggest them here instead.
