### ISSUE TITLE
Wither Storm can show different subphases in distant renderer

### ISSUE THREAD

**Issue by GoldSlimeling91** [nonamecrackers2/crackers-wither-storm-mod#516]
**Minecraft version**
1.19

**Mod version**
3.0 beta

**The Bug**
The Wither Storm, when it has a different evolution speed than 1, can change sizes in the distant renderer when in phases 5 and 6, it seems it only does this when it has subphases in the phase it's in.

**To Reproduce**
1. Set a Wither Storm's evolution speed to 2
2. Set the same storm's phase to 5
3. Let the storm out of your render distance so the distant renderer initiates
4. Witness it change size out of nowhere

**Screenshots**
![2022-08-15_15 24 12](https://user-images.githubusercontent.com/111310936/184703449-e9b21879-9ef4-443d-9ebe-a545430d340f.png)
![2022-08-15_15 24 20](https://user-images.githubusercontent.com/111310936/184703464-48ece6e2-a43a-40cc-b307-04426c55a389.png)

**Comment by TSEG6** [comment]
This also happened to me on a 1.18.2 server.

**Comment by nonamecrackers2** [comment]
Fixed in all versions
