### ISSUE TITLE
Hardcore option for consumed players, longer wither storm "revive" time, a trapped mob model idea

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#517]
Inspired by #123 
Idk how you'd implement this I think a fun (but optional) feature would be to respawn hardcore players after the wither storm dies. Respawned players would be given the weakness and slowness effect for a short time. This would probably have to be a option you have to choose and have a warning because not being in hardcore while using this could cause issues. I think a "Who's Gabriel?" achievement would be a fun easter egg for whoever is respawned.

A small and nice change would be to make the wither storm wait like 10 seconds longer before rising off the ground when awakening from the playing dead phase. I feel like it comes back too fast at the moment. The command block pulling the player towards it could last the same amount of time though. 

I saw somewhere that you had the idea of non-player placed tainted blocks randomly spawn mob models. I think this could also be done by making a specific "trapped" block that does this instead, allowing you to place the trapped mobs wherever needed. Also, if this is even possible, pulling player skins and pasting them onto a model would be a neat edition. Even if the player is alive still.

**Comment by Sculkter** [comment]
This is cool! Perhaps at half health when in the Storm's jaws, it teleports you to a section in side of the Storm! You'd have Blindness and max level Slowness, and when the Storm is blown up, you spawn back in with Wither Sickness! I like your idea!

**Comment by ShadeKage** [comment]
This'd definitely have to be for hardcore servers only, but would be really cool in them, I approve

**Comment by GrandmaPork** [comment]
Trapping people in the bowels wouldn’t be the best idea. I was thinking that their inventory can be saved and they’re put into spectator mode so they can watch since I’d image it would get really boring to be trapped

**Comment by nonamecrackers2** [comment]
I really like the hardcore idea actually. I don't personally feel the reviving cooldown stuff needs reworking and will plan to leave it as is. Also I don't think it would be possible to pull player skins onto block models unfortunately.

**Comment by GrandmaPork** [comment]
This mod is like 8 years old but it uses player names to grab models. I’m not sure if they have to be in the game but maybe you could figure out how to make it work https://youtu.be/d_-qaJOeI1o

**Comment by watersofnazareth** [comment]
I don't believe this needed to be closed as it had the to be confirmed tag, with this one I think it's best if Crackers was to close it if they wanted to

**Comment by GrandmaPork** [comment]
okay i just closed it cuz the other was closed

**Comment by nonamecrackers2** [comment]
As mentioned in the other issue, I'd prefer to not mess with hardcore if possible.
