### ISSUE TITLE
Commands let people with morph mod turn into different phases

### ISSUE THREAD

**Issue by HyperRooky** [nonamecrackers2/crackers-wither-storm-mod#518]
If you can, can you try to make it so if people have the identity mod you can use commands to turn yourself into different phases because I was using the identity mod and I can only be the segments and the phase 0 wither storm

**Comment by watersofnazareth** [comment]
This would be related to the Morph mod not so much CWSM

**Comment by nonamecrackers2** [comment]
Yeah, you'll have to request this feature to them instead. If you could somehow modify the NBT of the entity you're morphing into, you could change the phase.
