### ISSUE TITLE
What am I banned for, excatly?

### ISSUE THREAD

**Issue by M0ntherload** [nonamecrackers2/crackers-wither-storm-mod#519]
I am o3k_#9814. I did not get a ban reason. In the last 30 or so minutes I sent 2 messages with excessive amounts of emojis, I was warned for it and I stopped as requested. Yet I'm banned. There is no other way for me to contact anyone the server, so I am resorting to using github.

**Comment by watersofnazareth** [comment]
You were told to stop, yet you continued, you've already been warned in the past, once by Cracker's himself, and twice by me, if that answers you question

**Comment by watersofnazareth** [comment]
Adding ban evading to this

**Comment by nonamecrackers2** [comment]
Please do not open issues that are completely unrelated to the mod here
