### ISSUE TITLE
Buff Symbiont a bit

### ISSUE THREAD

**Issue by Catlord-3** [nonamecrackers2/crackers-wither-storm-mod#520]
Hey, I love the mod, i just feel that the withered symbiont should be buffed to have a bit more health, as with a smite 5 diamond sword, strength 2, and two crits it is possible to kill it on the first time it runs out of energy. I feel like this should not really be a thing you should be able to do so maybe up the health of the symbiont a little. found this out by stumbling across a smite 5 book in a playthrough

**Comment by Sculkter** [comment]
Lord have mercy, you want the thing buffed? If the Symbiont has the angle on you, a single explosive jump would one-shot you! If anything, I think it's fine the way it is. :]

**Comment by nonamecrackers2** [comment]
You could easily do this with [attributes](https://minecraft.fandom.com/wiki/Attribute). I also feel it's currently fine the way it is and there is a balance to be kept with players that may be more inept with PvP.
