### ISSUE TITLE
Bowels corpse's

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#521]
so on a server. if the game mode is hardcore, a player that is consumed by the wither storm would be placed in the bowels by the wither storm. so when the final fight happens the remaining players who walk in the bowels will see the people who have been consumed.
people who have can still join the game but will have a filter over the skin making it much darker. and all the player can see is the bowels with a purple filter on top much like the texture that shows up when being pulled by a tractor beam.
this will require the people to not be eaten more of when a cluster gets picked up it goes to the body.
so the player would do that and instantly go to the bowels.

**Comment by Bloxxify2827** [comment]
I think this is a really good idea, but it sounds very hard to do.

**Comment by Theoyeah** [comment]
I defenitifly like this idea ! Tho, it would be cool in survival that if you leave the game in the death screen, it would do the same until you **respawn**. A small suggestion too, is that you have some animals tagged/tammed that got eaten by the wither, you could see the corspes of them too, if you manage to Kill the wither with the f bomb or by the command block, then they respawn.

**Comment by nonamecrackers2** [comment]
Are you suggesting that players who die become statues inside the Wither Storm? If so this was already suggested [here](https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/223#:~:text=The%20next%20suggestion%20is,WS%20has%20absorbed%20them.) #223.

The second portion to me seems like it would bypass hardcore and as such the spirit of it, effectively giving players another life.
