### ISSUE TITLE
[Suggestion] Spyglass Advancement

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#522]
I think I mentioned this a while back but forgot to mention it, whenever you inspect the Wither Storm with a Spyglass it should give you an Advancement like "Is It The End?" or "Is It a Wither...?"

**Comment by mmiller9196** [comment]
what about "that's no storm" like a reference to the death star?

**Comment by Sculkter** [comment]
That's no Storm... It's a Wither Storm!

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release
