### ISSUE TITLE
Issues with other mods

### ISSUE THREAD

**Issue by Catlord-3** [nonamecrackers2/crackers-wither-storm-mod#523]
I have been testing the wither storm against some different modded enemies, and i noticed a few issues with it. I am using the 1.16.5 version
1. Certain entities that are immune to normal attacks are immune to the wither storms bite and end up awkwardly levitating in its head while the head looks straight up, stuck on that entity. Maybe changing the damage type to non players to be similar to /kill or the void would work to fix this?
2. Some strong modded enemies have attacks that can actually one hit kill the wither storm even in phases 4-7. i found that rahovart, a boss from lycanites mobs, has an attack that will one shot the wither storm if hit. 
3. Cheese with another mod. Using the Ice and fire mod, which has an item which allows you to turn mobs into stone, the wither storm is also affected by this, as well as almost all mobs from this mod. strangely, the tentacle enemy is not, while all other mobs are. this could allow you to fully stop a late stage witherstorm without having to fight it, or remove the segments from tiers 6 and 7. 
4. certain entities immune to pull that probably shouldn't be. Some entities while clearly being targeted by the wither storm, just will not move from their spot. an example is the previously mentioned rahovart from lycanites mobs, but it isnt the only mob that the storm cannot pick up.

I know these are all not a huge deal and may be up to the other mod makers to fix, but i appreciate you reading and appreciate all the work that went into this mod. I hope you can get these fixed.

**Comment by mmiller9196** [comment]
I don't think he can make the wither storm immune to petrification,
also lycanites mobs has a lot of strong mobs, so maybe just don't play it with the wither storm mod

**Comment by nonamecrackers2** [comment]
1. I could experiment with bypassing invulnerability with the Wither Storm's chomp attacks
2. This is really out of my control. I could hypothetically attempt to fix this, however it'll mean /kill won't work anymore and there'll be a lot of unforeseen consequences I don't really want to deal with.
3. I could probably find a way to prevent this from happening.
4. This is probably due to the implementation of the entity and is something I probably wouldn't be able to fix myself.

**Comment by 48004800** [comment]
> 1. I could experiment with bypassing invulnerability with the Wither Storm's chomp attacks
> 2. This is really out of my control. I could hypothetically attempt to fix this, however it'll mean /kill won't work anymore and there'll be a lot of unforeseen consequences I don't really want to deal with.
> 3. I could probably find a way to prevent this from happening.
> 4. This is probably due to the implementation of the entity and is something I probably wouldn't be able to fix myself.

Since my issue is closed, I don't know if you can see my reply, so I choose to reply to you here.
