### ISSUE TITLE
An alternative way for the Wither Storm to pick up and assimilate entities

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#524]
After reading a certain issue about some entities just awkwardly floating into a Wither Storm jaw, and after experiencing this on my own, I figured that the Wither Storm should have an alternative way to actually assimilate entities. By watching Minecraft: Story Mode, there is a particular scene were mobs and people get assimilated, and it shows how the main head of the Wither Storm pulls them close to its centre where it absorbs blocks, and then looks away as he allows the natural pulling effect the command block has at its middle area do the rest, pulling them inside. Here's a video where it's shown.

https://user-images.githubusercontent.com/75396163/185364016-5d853b9b-fea3-4198-ba59-4e8f497f24cc.mp4

The options here are plentiful: either have a second pulling effect that is faster and doesn't require the Wither Storm to chomp on the entity, but simply pulls it close enough to have it absorbed just like a block cluster, with a chance of a player to be picked up this way (easier to escape but quicker pulling, the player could try to either hit the wither storm's head or float out of there), or maybe have this be a unique way of assimilation for mobs/entities only (like vehicles or special mobs) with a configuration to allow players to be affected too or not.

**Comment by ghost** [comment]
i have put this for my suggestion. #521
but this would be more of a in depth explanation.

**Comment by nonamecrackers2** [comment]
This could actually be a pretty cool idea with mobs that aren't being targeted directly but are instead just being pulled in by the beam. This will allow the already in place chomping system to still do it's thing while adding a cool new way to absorb entities.

**Comment by Aimyx** [comment]
This Would also make entities not fall out of the beam when the WS eats somthing.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
