### ISSUE TITLE
[XP buff for Wither Storm] [Suggestion] Large XP reward for killing Symbiote and defeating the storm

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#526]
**Description of feature**
When you kill the Symbiote, you should be granted a large amount of exp, preferrably 9,000 so you can use it to enchant your gear, since sometimes you don't have enough exp to fully enchant your gear in order to prepare for the final fight.

For the Wither Storm, you should be granted a huge amount of exp for finally killing it, as it is a monumental challenge

**Comment by TheSrBig** [comment]
Good idea!

**Comment by watersofnazareth** [comment]
Not entirely sure about the Symbiont dropping XP as it gives you a really powerful tool

**Comment by nonamecrackers2** [comment]
I think the Wither Storm dropping more XP would be good, however considering that yes you get an awesome weapon from the Symbiont and also fight the thing twice, I don't feel it's XP needs to be buffed.

**Comment by RandomGithubUser32** [comment]
For the wither storm, the amount of XP given should be greater than the amount of XP you get from killing the ender dragon.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release

**Comment by TheSrBig** [comment]
> Se implementará en la próxima versión 1.18./1.19

Perfect
