### ISSUE TITLE
Change the design of the heads when we kill the storm wither

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#527]
When the storm wither dies with the FormidiBomb, it dies raising its heads, I thought it would be a good idea instead of it raising its heads, blinking its laser beam until it melts, and lowering its heads little by little until it reaches the floor and stays with its mouth open as we know it in the mod.

**Comment by nonamecrackers2** [comment]
Little confused; you want the tractor beam (the beam of light) to _melt?_ This wouldn't be possible with how rendering works, however the tractor beams blinking could be interesting, however of not much importance.

**Comment by BluePineappleGuy** [comment]
I like the way the tilt up like that when the formidibomb blows, because it looks like the bomb blasted the heads upward. however, in the bowels, i think they should face down and hang lifeless as they do in story mode

**Comment by TheSrBig** [comment]
> I like the way the tilt up like that when the formidibomb blows, because it looks like the bomb blasted the heads upward. however, in the bowels, i think they should face down and hang lifeless as they do in story mode
 
I also like it when they look up, but what I mean is that when they look up, there is a flicker or flash of the tractor beams, I think I make myself clear.

**Comment by nonamecrackers2** [comment]
Going to be keeping the current animation as of now.
