### ISSUE TITLE
Withered/sickened mobs convert back into normal mobs after wither storm had been defeated.

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#528]
**Description of feature**
With wither sickness being cured after wither storm defeat, this would make sense, its better for it to go slowly than immediately though

**Comment by RandomGithubUser32** [comment]
Maybe slowly and not strait away

**Comment by Globalfirestorm10** [comment]
yeah, it would be better if the process is done over a duration of time, lets says something like 3 Minecraft days (roughly 30 minutes), instead of being converted to regular mobs immediately

**Comment by watersofnazareth** [comment]
#420

**Comment by Luke7381** [comment]
> #420

Yes however it doesn't really state mobs tho.

**Comment by nonamecrackers2** [comment]
Oh you mean the sickened mobs being cured (converted back to normal) when the Wither Storm dies. That should definitely be done to keep parity.

**Comment by Luke7381** [comment]
> parity
Yep the sickened mobs, also the way you mentioned parity reminds me of the evil biomes from terraria

**Comment by nonamecrackers2** [comment]
Just checked and it already does this. Sickened mobs that are summoned by an egg or the /summon command won't be converted since they don't have an original entity to convert back to, and this works as intended.

**Comment by Luke7381** [comment]
> Just checked and it already does this. Sickened mobs that are summoned by an egg or the /summon command won't be converted since they don't have an original entity to convert back to, and this works as intended.

Oh
