### ISSUE TITLE
Wither storm bossbar

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#529]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

I feel not enough is done with the wither storm’s bossbar after phase 3. Maybe during the fight with the command block, the bossbar could show the health of the command block, so anyone outside the storm can tell the health of the block.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
