### ISSUE TITLE
Wither Storm takes fire damage 

### ISSUE THREAD

**Issue by Catlord-3** [nonamecrackers2/crackers-wither-storm-mod#530]
**Minecraft version**
1.16.5

**Mod version**
latest (1.0.2.4)

**Describe the bug**
Wither storm will take fire damage

**To Reproduce**
Start world, summon storm, enchant weapon with fire aspect, see storm take damage from fire. While it does irrelavent damage, i feel it still probably should be fixed.

**Comment by nonamecrackers2** [comment]
> While it does irrelavent damage...

As in the Wither Storm only displays it having fire?

**Comment by Catlord-3** [comment]
No, it does actual damage, it just doesn't do much as it heals it back. Tested and also takes lava damage, this damage can actually be seen to move the health bar if kept submerged. Also, only storms phase 0-3 take fire damage, but 4+ can still show the fire effect.

**Comment by Catlord-3** [comment]
No, it does actual damage, it just doesn't do much as it heals it back

**Comment by nonamecrackers2** [comment]
Ah. I think I fixed this is in newer versions but didn't in 1.16.5

**Comment by nonamecrackers2** [comment]
Fixed in the latest 1.16.5 release
