### ISSUE TITLE
Suggestion regarding the Wither Storm health + first 3 phases

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#531]
The Wither Storm starts with 400 health, basically 200 hearts. To avoid people trying to kill it in normal ways, and also trying to kind of nerf the unnatural fast healing it has, it would be cool if the base health of the WS increased with every entity it consumes. It could even gain different amounts of health depending on what it consumes (items, blocks, players, mobs etc) and if possible, the health increase from block clusters could depend by the size of the cluster itself. The Wither Storm could both heal and increase its max health with every consumed entity, and if the natural healing is nerfed in favor of this (it could have both natural healing and base health increase to lower the chances of it dying by other means to zero) then it could increase the absorbing of blocks until it fully recovers. The fact that stage 4 to 7 only have 1400 health is kind of disappointing, it would be interesting to have the WS have huge amount of health while in those stages due to the block absorption (maybe a max health cap could be set in case it causes memory issues, unsure if it could happen). 

The other suggestion I have is still related to phase 1 to 3. In story mode the WS is seen doing several dash attacks to try and attack Gabriel and the others, similarly to how Bedrock Edition's Withers do. That could easily be an attack that causes the WS to descend while flying, since ironically it has better aim the lower to the ground it is. There should also be a small phase transition between phase 3 and 4, as the transformation is just overwhelming and it feels incomplete, due to the size difference. In Story Mode, just before everyone runs away, the WS is seen having a particular big shape with a lower structure similar to the one it has in phase 4 (I assume that's supposed to be the tail bone of the wither once it absorbed blocks) and it gains a bigger tentacle. 

https://user-images.githubusercontent.com/75396163/185571633-5a40d11e-a940-41e2-adb9-b9a5b332f076.mp4

This could be a phase 3.5 to help players understand that the Wither Storm is about to transform to its large stage 4 form, and maybe it could also have the other two heads starting to turn like the main one with a purple eye and a jaw (but not fully). Here's a fanmade render based on the original model from the game.

![Screenshot_20220819-094134_Discord](https://user-images.githubusercontent.com/75396163/185569143-a139540c-fd67-4fb6-927f-ad83cc14295e.png)

**Comment by nonamecrackers2** [comment]
Think attributes are maxed at a specific value (somewhere in thousands) so growing health may not be possible (I'll have to check again). In between phases for 3-4 has already been suggested: #316 

I probably won't do the strafing since I don't think the effort of working it in with the current AI is very feasible for me at the moment.

**Comment by GoldenDarius** [comment]
I actually just remembered that the Wither Storm from Engender mod actually increased its health by 1every entity it consumed, so I think it is possible. Besides I had this idea when I thought about the sickness decreasing your max health, and telling myself "why not having the exact opposite happening to the Storm"

**Comment by Asteroid4** [comment]
I found this:
"You could have another value - the number of health bars remaining.
When the mob dies, subtract 1 from the remaining bar count and restore it to full health, unless the bar count is reduced to 0.
For example, if an enemy has 2000 health, give it 1000 health and 2 health bars."

**Comment by Asteroid4** [comment]
It might be somewhat buggy at some points, but it would work.

**Comment by nonamecrackers2** [comment]
> Think attributes are maxed at a specific value (somewhere in thousands) so growing health may not be possible (I'll have to check again). In between phases for 3-4 has already been suggested: #316
> 
> I probably won't do the strafing since I don't think the effort of working it in with the current AI is very feasible for me at the moment.

Closing due to these reasons.

Also considering that the Wither Storm isn't intended to be killed via natural means, the amount of health doesn't overly matter as it isn't meant to be attacked directly (unless of course, if you have the config to make it vulnerable to these attacks on, however I still feel an increasing max health isn't very necessary)
