### ISSUE TITLE
Wither Storm's tractor beams start spazzing out when not looking at the Wither Storm directly

### ISSUE THREAD

**Issue by CatalystBrimrose** [nonamecrackers2/crackers-wither-storm-mod#533]
**Minecraft version**
1.18.2
**Mod version**
2.0.1.2

**Describe the bug**
When not looking at the Wither Storm the tractor beams start spazzing out like crazy

**To Reproduce**
1. Go near the Wither Storm
2. look at the tractor beams, not the Wither Storm itself 
3. look at how the beams start spazzing out

**Screenshots**

![2022-08-19_16 39 50](https://user-images.githubusercontent.com/111583739/185643665-5eede8ff-2ed9-4b5a-b61b-2be279f6ae2a.png)

**Comment by watersofnazareth** [comment]
What other mods do you have

**Comment by CatalystBrimrose** [comment]
Here are my other mods: 
![Overwolf_IZ4p1As56u](https://user-images.githubusercontent.com/111583739/185731786-1a500d9a-bc47-42e5-99d0-e55ce647bd72.png)
![Overwolf_jjwZdoTw1i](https://user-images.githubusercontent.com/111583739/185731790-85d2adfa-2c1c-416b-a1ad-84aa1b25d9f9.png)
![Overwolf_MSZTOjCs8V](https://user-images.githubusercontent.com/111583739/185731791-f4f18a5e-1a9e-45f7-bb9a-5d5db5a06e81.png)
![Overwolf_sEJdV8BPmI](https://user-images.githubusercontent.com/111583739/185731792-974dc0f4-4176-485c-86f2-bed77f88f96c.png)
![Overwolf_z6glBwwZwb](https://user-images.githubusercontent.com/111583739/185731793-70642e4a-d26e-4684-83f7-d1ff89123fed.png)
![Overwolf_ZklB2gZhql](https://user-images.githubusercontent.com/111583739/185731794-345482d9-71a9-4106-8153-ea3aee075a26.png)
![Overwolf_87P9RzDNcl](https://user-images.githubusercontent.com/111583739/185731795-c241ac88-36d2-4edc-bb05-7f87bc976e4b.png)
![Overwolf_AbNicBNmo4](https://user-images.githubusercontent.com/111583739/185731797-b71272af-902f-4714-ac53-ed13442b928d.png)
![Overwolf_BdYPIDpZzZ](https://user-images.githubusercontent.com/111583739/185731798-480b0ecf-1ea5-4607-a172-5e856b40b419.png)
![Overwolf_Cfdp59QJMQ](https://user-images.githubusercontent.com/111583739/185731799-b4218bfd-61b3-400b-ae93-1d89ccf1db7b.png)
![Overwolf_cSOYWKGc98](https://user-images.githubusercontent.com/111583739/185731800-beedfec9-998d-4e02-a918-9da9b7c3a6a4.png)
![Overwolf_d8blKaCU9F](https://user-images.githubusercontent.com/111583739/185731802-c3ae7a8c-011f-4518-9d7a-23a8ac881883.png)
![Overwolf_glL2TbLcCL](https://user-images.githubusercontent.com/111583739/185731804-e4c7cad6-42a4-4700-9c9b-0013792460b1.png)

**Comment by watersofnazareth** [comment]
This is caused by Entity Culling

**Comment by CatalystBrimrose** [comment]
Thank you!
