### ISSUE TITLE
mrcrayfishguns doesn't hurt wither storm in the slightest

### ISSUE THREAD

**Issue by mmiller9196** [nonamecrackers2/crackers-wither-storm-mod#534]
I downloaded the mrcrayfishgun mod and the bullets have no affect on the heads, can the head only be hit by arrows or swords?

VERSION 1.18.2

**Comment by Globalfirestorm10** [comment]
This is a mod incompatibility, it will most likely be marked as low priority

**Comment by watersofnazareth** [comment]
If it's Phase 4 or higher it'd be immune to damage and currently heads have a random chance to have their eyes broken, but I will mark this low priority just in case

**Comment by nonamecrackers2** [comment]
If the bullets aren't projectiles they won't be registered by the heads, I'll have to check.
