### ISSUE TITLE
The Wither Storm Is Not Rendering Properly 

### ISSUE THREAD

**Issue by TheDarkPanther** [nonamecrackers2/crackers-wither-storm-mod#535]
**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by Globalfirestorm10** [comment]
Please provide more details, Cracker cannot determine any issues without logs, mod lists, version used, screenshots, etc

**Comment by Globalfirestorm10** [comment]
we cannot determine any issues without logs, mod lists, version used, screenshots, etc

**Comment by watersofnazareth** [comment]
Please fill the report out, I will be closing this for now

**Comment by RandomGithubUser32** [comment]
Maybe they have optifine installed.
