### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by cooldude47980597** [nonamecrackers2/crackers-wither-storm-mod#536]
I formidi bomb killed the wither storm into phase 7 but when it’s dead it’s tractor beams are still active

**Comment by watersofnazareth** [comment]
You'd need to give more details, any screenshots anything?

**Comment by watersofnazareth** [comment]
Tagging as invalid and closing till more info is given

**Comment by cooldude47980597** [comment]
Bruh

**Comment by cooldude47980597** [comment]
It happened on one of my Smp servers

**Comment by nonamecrackers2** [comment]
Please fill out the bug report template you were given
