### ISSUE TITLE
Wither Storm can't pick up certain blocks

### ISSUE THREAD

**Issue by Catlord-3** [nonamecrackers2/crackers-wither-storm-mod#537]
**Minecraft version**
1.16.5
**Mod version**
latest (1.0.2.4)

**Describe the bug**
Wither storm is unable to pick up certain blocks that it should. It cannot pick up end stone, obsidian, crying obsidian, and respawn anchors

**To Reproduce**
summon wither storm in area with only these blocks
observe it not picking up anything (with f3+b you can see it try but fail as if it was bedrock), This is easiest to see in the end, but it cannot pick up these blocks in all dimensions.

**Comment by watersofnazareth** [comment]
This isn't a bug, it doesn't do it in 1.16.5 as it's a new feature

**Comment by Catlord-3** [comment]
Why wouldn't it be able to pick up end stone or obsidian?

**Comment by watersofnazareth** [comment]
Explosion Resistance

**Comment by Catlord-3** [comment]
Shouldn't the storm be able to pick up anything (breakable) to prevent certain structures being pretty much storm proof? Also, end stone isn't very blast resistant, it can be destroyed by a creeper explosion

**Comment by nonamecrackers2** [comment]
This is because the 1.16.5 Wither Storm uses the ender_dragon_immune block tag to check if it can pick up certain blocks, which contains the blocks you mention. The change to use the wither_immune block tag was technically a feature and won't be backported to 1.16.5.
