### ISSUE TITLE
Golden Apple Stew not curing Wither Sickness

### ISSUE THREAD

**Issue by Hyperz6** [nonamecrackers2/crackers-wither-storm-mod#539]
The minecraft version I am running the mod on is 1.18.2 and  I am using Wither Storm mod version 2.0.1.2

It appears that when I drink the golden apple stew in an attempt to cure the Wither sickness disease, I do get the absorption affect and gain all my hearts back and a timer is applied to the Wither Sickness disease indicating when it will end but after a few minutes, the absorption runs out and the timer resets back to infinity and I begin losing hearts again. At first I thought this was maybe due to the Wither Storm immediately giving it back to me because I will still in it's vicinity so I decided to test it in the Nether to make sure. I drank a golden apple stew in an entirely different dimension to see if it would actually cure the sickness and the same results would appear with the wither sickness not being cured at all.

<img width="1016" alt="Screenshot 2022-08-21 001635" src="https://user-images.githubusercontent.com/111641779/185745920-77768c87-98c1-4174-bb47-a6fef4a810ad.png">

- Moments after drinking Golden apple stew, wither sickness effect is back to infinity and I once again begin losing hearts.

**Comment by ghost** [comment]
you have to wait a few minutes. then it would get into effect.

**Comment by Hyperz6** [comment]
Nevermind, there is no issue, I guess it was a bit deceiving at first on the mechanics of it

**Comment by Bloxxify2827** [comment]
#274
