### ISSUE TITLE
[Pull in clusters of mobs] Better tractor beams and command tutorial

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#54]
Can you make the wither storm pull multiple mobs with it's tractor beam? 

One way to do it would be to make multiple "tractor beam" entities that all face the same direction as their head

Also can you give us a tutorial on how to use the /witherstormmod cluster command? It is getting confusing trying to make clusters, it just pulls the chunk below me upwards in the area I selected, then it just sits there.

**Comment by SSgamingYT** [comment]
I need help with the cluster creation command
/witherstormmod cluster create
I did the position and radius, I just dont know how to make it get eaten by a wither storm or become a cluster at all

**Comment by nonamecrackers2** [comment]
This tractor beam was mentioned before (I think I closed it) and I'll need to ponder on it more. When you're using the cluster command, you also need to supply the time the cluster can exist (I usually use 100). There is no way to make the Wither Storm pick up existing clusters as of now.

**Comment by SSgamingYT** [comment]
Oooh okay! Also a quick thing you could do for the command is to add an @e at the end so we could specify the entity it goes to (i. e. The wither storm), then make the limit 1.
Just a thought I don't know if it will work or not

**Comment by SSgamingYT** [comment]
sorry about the weird spammy stuff on the message, I replied through email which for some reason made all of those symbols appear.

**Comment by nonamecrackers2** [comment]
Closing in favour of #67
