### ISSUE TITLE
Breakable command block

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#540]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

my idea is to make the command block that spawns the wither storm a new “survival mode” command block. The only difference between it and the normal command block is that this new command block can be broken with a command block tool, and also can be placed in survival. The gui can still only be used by opped players in creative mode however.

**Comment by Asteroid4** [comment]
If this were added, I think the wither storm in phases 0-3 would drop this new command block as well as a nether star.

**Comment by nonamecrackers2** [comment]
This [mod](https://www.curseforge.com/minecraft/mc-mods/placeable-command-block) does effectively what you're looking for with the only downside of the block not dropping after breaking it. I don't plan on modifying command block properties myself.

**Comment by EnderPlays123** [comment]
Oh, ok.
