### ISSUE TITLE
The other wither storms begin to expand like the central wither storm when there is a long time without killing the wither storm.

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#541]
I have an idea, is that when the wither storm is not killed, after exploding the formidibomb the other parts above the wither storm become bigger when it grabs blocks like the central wither storm.

**Comment by watersofnazareth** [comment]
They do grab blocks?

**Comment by FrozenDragon0** [comment]
> They do grab blocks?

They do, I've seen the segments pick up block clusters.

**Comment by RandomGithubUser32** [comment]
Do you mean having the segments grow as well?
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/389
