### ISSUE TITLE
Game Crashes With Optifine

### ISSUE THREAD

**Issue by L8558** [nonamecrackers2/crackers-wither-storm-mod#543]
Minecraft version: 1.18.2

Forge Version: 40.1.69

Mod version: witherstormmod-1.18.2-2.0.1.2

Game Crashes when loading any world, the bug only occurs while using optifine and It's not present using rubidium & oculus 

Steps to reproduce the bug:
1. Go to 'Single Player'.
2. Open / Create any World.
3. See error

**Crash Reports / Logs**
The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'
Error code: -1

**Comment by Globalfirestorm10** [comment]
Are you using the latest version of 1.18.2 forge? If so, downgrade to 1.18.2 forge version 40.1.57, aka the last known compatible version with optifine

**Comment by watersofnazareth** [comment]
Smooth Worlds needs to be off this is a known issue, it is best to use Rubidium with the mod instead of Optifine
