### ISSUE TITLE
1.18.2 feature port for 1.16.5

### ISSUE THREAD

**Issue by CatalystBrimrose** [nonamecrackers2/crackers-wither-storm-mod#545]
**Description of feature**
It would be cool if some feature that are present on the 1.18.2 version will be ported to the 1.16.5 version, features such as: The ability of the Wither Storm to pick up clusters of mobs, the new stunned head animation and the better beam effect. 
This is beacause i just cant play 1.18.2, its just too laggy and unplayable, so it would be cool to have theese features in the 1.16.5 version.

**Comment by watersofnazareth** [comment]
This will not be done as it is not worth the time or effort
