### ISSUE TITLE
More Config Options

### ISSUE THREAD

**Issue by Catlord-3** [nonamecrackers2/crackers-wither-storm-mod#546]
To allow the storm to be better worked into modpacks, allow for certain stats to be altered in the config menu. Things like command block tool damage, withered mob health and damage, symbiont health and damage, storm projectile damage, and early storm health, so that with mods that introduce very strong tools don't take away from the challenge too much and don't completely outclass command block tools, but also not make the tools and mobs from the mod too overpowered for vanilla Minecraft. I don't know how hard this would be to implement, so I understand if you decide to not implement it because this would take a lot of work that could be better used improving other aspects of the mod, or giving yourself a break (Seriously, this mod is amazing, and you earned it), or for any other reason. Thank you for reading and thank you for this amazing mod!

**Comment by watersofnazareth** [comment]
This can be done with Datapacks

**Comment by nonamecrackers2** [comment]
Most of what you're requesting can be done with the /attribute command. And you're welcome :)
