### ISSUE TITLE
witherstorm ring config

### ISSUE THREAD

**Issue by personmhmyes** [nonamecrackers2/crackers-wither-storm-mod#547]
for phases 4-7 u can use either % or a set amount to limit the number of rings rendered for peformance

**Comment by watersofnazareth** [comment]
The rings don't impact performance that much, and I don't think this is needed

**Comment by nonamecrackers2** [comment]
The rings are 2D objects that have virtually no impact on performance. You can disable the debris rings if you'd like to see for yourself. If you're talking about the debris particles, there are various options to increase performance for those in the client config.
