### ISSUE TITLE
Block Cluster Animation

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#548]
In story mode The block cluster shatter into blocks, however you have turned it down, because it would be to lagy.
but think i have found a way.
what if instead of the block clusters moving straight to the wither storm, the block clusters would have a random animation.
still being one model or entity. say if it had 1-10 animations, it would make the block clusters feel more authentic. while also having them loop until in the wither storm.

**Comment by watersofnazareth** [comment]
#225, however Block Cluster Shattering could be interesting tho I think it's been suggested before too

**Comment by watersofnazareth** [comment]
Accidentally closed

**Comment by nonamecrackers2** [comment]
Performance with block clusters currently would not make this feature very feasible, however as performance is improved I'll revisit this.

**Comment by nonamecrackers2** [comment]
Block clusters will now split in the next major release
