### ISSUE TITLE
formidi bomb not floating up and blowing up wither storm

### ISSUE THREAD

**Issue by grupoo69** [nonamecrackers2/crackers-wither-storm-mod#55]
When I detonate it wither storm does not eat it

**Comment by Loverxzc** [comment]
Perhaps Wither Storm hasn't reached the end of Phase 5 yet.
Phase 5:
![2022-05-07_09](https://user-images.githubusercontent.com/105715466/171430328-768086bd-7186-4f61-8970-6d9b96b12a9c.png)
End Phase 5:
![2022-05-07_09 (1)](https://user-images.githubusercontent.com/105715466/171430389-38545c0d-ba4d-4d35-92fb-4a3a4184d0ca.png)
![2022-05-16_14 09 36](https://user-images.githubusercontent.com/105715466/171430567-aea644ba-f951-4be8-8560-ab3d01a5c519.png)

**Comment by Loverxzc** [comment]
and use flint and steel, If you didn't know
