### ISSUE TITLE
Wither storm phases 6-7 should use "Wither Storm Rises" as the main song

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#550]
This is self explanatory right?

**Comment by ghost** [comment]
its a bit quite quiet for a wither storm tricking the player into being right under it. if any thing a more intense theme.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> its a bit quite quiet for a wither storm tricking the player into being right under it. if any thing a more intense theme.

Yup I feel like there should be diffrent themes for diffrent phases just to fit and make the mod more interesting

**Comment by nonamecrackers2** [comment]
#227
