### ISSUE TITLE
[suggestion] Literally a Wither storm

### ISSUE THREAD

**Issue by Mettod99** [nonamecrackers2/crackers-wither-storm-mod#552]
When wither storm reaches evolution phase 7, the debris rings around it would be so big, they would cover whole sky, creating a new weather event - Withering Storm. 
This storm would last as long, as the WS is alive. That means you can't just skip it by sleeping.
The sky would turn dark, darker than regular storm, but brighter than night. Weird magenta/purple rain would fall, infecting all mobs that are directly exposed to the sky (no blocks between them and the clouds) with wither sickness. Lightning bolts powered by the command block would strike more frequently than in regular storm, maybe they could be more destructive, causing exlposions.
When this weather event starts, the debris rings would disappear to save performance (configurable), and the magenta/purple rain particles could fall "lesser" than in regular rain to save some performance as well.
It would be nice if you could start the Withering storm by using /weather command.
I think this storm would be a perfect demonstration how powerful the Wither Storm got. Now, when is it able to affect whole overworld.

I know this is not in the original MCSM, but still it could be a cool feature.
And also I wanted to thank you for creating this awensome mod, you literally made dreams come true. Full wither storm boss fight, when you can even enter it! That's incredible! You are so talented! 😄 
Oh, and please forgive me for my "english", I am good at reading, not writing 😅

**Comment by Anonsevenseven** [comment]
I actually quite like this concept. If it is confirmed, I'd like to see how it would be implemented.

Edit: Perhaps another phase? Actually, maybe not...

**Comment by GrandmaPork** [comment]
I think this would fit like a phase 8/9. Also, it would have to be a really light sprinkle since rain can be very intrusive

**Comment by Mettod99** [comment]
> I think this would fit like a phase 8/9. Also, it would have to be a really light sprinkle since rain can be very intrusive

It would be like a few drops per second, not a heavy rain. And particles could be disabled in config.

**Comment by ghost** [comment]
i think it would be more of a event other than a whole phase.

**Comment by Globalfirestorm10** [comment]
I hope to see this idea implemented, although I think there should be a config option for it

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
This is pretty cool however it should have a range like you need to be within a certian distance of the wither storm for the storm to occur otherwise the scales would just go straight to insane mode very quick
Also It wont harm mobs teamed with the wither storm via /Team if the wither storm and a mob are on the same team The Storm Won't Hurt The Current Teamed Mob

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> > I think this would fit like a phase 8/9. Also, it would have to be a really light sprinkle since rain can be very intrusive
> 
> It would be like a few drops per second, not a heavy rain. And particles could be disabled in config.

Facts

**Comment by nonamecrackers2** [comment]
Don't feel that a new weather event would fit in with the mod as of now. Also yw for the mod :)
