### ISSUE TITLE
Make the Wither Storm disappear the item you have in hand when you hit it, as in the original series.

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#553]
As in the original series, in the first chapter, when the Wither Storm is in front of Gabriel, Gabriel jumps and hits the Wither Storm with his sword, but when he hits it, it disappears, it would be nice that this is implemented to the Mod, if you think it would be too difficult this option, you should make an option for this, even so I think it should be implemented.

**Comment by ghost** [comment]
the wither storms height will have to be lowered as so for the tentacles.
and would be really hard to implement

**Comment by TheSrBig** [comment]
> la altura de las tormentas marchitas tendrá que reducirse como así para los tentáculos. y sería realmente difícil de implementar

Of course, obviously this would be eliminated when the command block is visibly protected, so to speak, or that it is affecting in the early stages.

**Comment by watersofnazareth** [comment]
#356

**Comment by TheSrBig** [comment]
> #356 But it's not the same, I'm talking about something similar, but not the same, he's talking about the command tool, I'm talking about any item you stick to it wither storm when you see his command block

**Comment by TheSrBig** [comment]
@Thefuzz1234555

**Comment by TheSrBig** [comment]
@Thefuzz1234555

**Comment by nonamecrackers2** [comment]
Regardless making players items disappear would be quite frustrating and I don't entirely feel this feature would sit well with the majority of the player base.
