### ISSUE TITLE
Main wither storm is "dead active" in the formidibomb phase

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#554]
**Minecraft version**
1.18.2

**Mod version**
1.18.2-pre3

**Describe the bug**
The main witherstorm's tractor beam and tentacles are still active in the formibomb state

**To Reproduce**

**Crash Reports / Logs**
no crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/48260861/186799632-816dc239-6e99-4d61-84e4-5c7d9bc55263.png)

**Comment by watersofnazareth** [comment]
Huh that's interesting, do you have any other mods installed?

**Comment by Luke7381** [comment]
> Huh that's interesting, do you have any other mods installed?

Quite a decent amount
Beyond earth
MCA Reborn
Lucky tnt

**Comment by nonamecrackers2** [comment]
If you could provide steps to reliably reproduce this that would be great. May be some desync.

**Comment by Luke7381** [comment]
> If you could provide steps to reliably reproduce this that would be great. May be some desync.
Sorry for late response
There isn't really a specific way of doing it, all i remember is formidibombing the wither storm and this happened
I would like to mention that my computer isn't the best in the world so that could play a factor
Mod list if this could help
Alex Mobs, Better Village, Biomes o plenty, Create, Enchantwithmob, Enchanted Celestials, Minecraft comes alive, lucky tnt, Infernal Mobs and Mob Battle. However i never had this bug in the latest release of 1.18.2 so i dont think its my mods.

**Comment by nonamecrackers2** [comment]
Interesting. I'll have to investigate this further.
