### ISSUE TITLE
Problem With Moving elevators mod

### ISSUE THREAD

**Issue by MechtroYT** [nonamecrackers2/crackers-wither-storm-mod#555]
Minecraft version
1.18.2

Mod version
2.0.1.2
Describe the bug
there is a Cannot get property DirectionProperty Problem with the moving elevator mod 

To Reproduce
it just happends

Crash Reports / Logs
https://pastebin.com/A9WryJnR

Screenshots
it instantly crahes so there are no screenshot

**Comment by ghost** [comment]
sounds like a moving elevators mod problem

**Comment by MechtroYT** [comment]
Ive Reported it Also to them

**Comment by nonamecrackers2** [comment]
Yep, appears to be a moving elevators problem.
