### ISSUE TITLE
Command block tools don't work in enchanting table

### ISSUE THREAD

**Issue by Catlord-3** [nonamecrackers2/crackers-wither-storm-mod#556]
**Minecraft version**
1.16.5 and 1.18.2

**Mod version**
Latest (1.0.2.4 and 2.0.1.2)

**Describe the bug**
Command block tools cannot be enchanted in an enchanting table.

**To Reproduce**
1. Get base command block tool, lapis, and enchantment table
2. Insert command block tool and lapis into table
3. See no options for enchanting show up
 

**Screenshots**
![2022-08-26_00 48 15](https://user-images.githubusercontent.com/69657737/186847465-d3409fe0-ec47-49f8-97ee-7b81a26209e8.png)

**Comment by ghost** [comment]
this is expected. it is not supposed to be enchanted.

**Comment by RandomGithubUser32** [comment]
No, it works with an anvil but not an enchantment table.

**Comment by FrozenDragon0** [comment]
Can confirm this is also an issue on the 1.19 version of the mod, enchantment table will not accept the command block tools at all.
