### ISSUE TITLE
[Bug] Symbiont can be boat cheesed

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#559]
1.16.5/1.18.2/1.19

Any

Symbiont can be cheesed with boats 

1. Place a boat
2. Make Symbiont touch boat
3. Symbiont is now stuck in boat
4. Easily kill Symbiont

**Comment by KrukAdrian** [comment]
Is this suppose to be a bug or a suggestion?

**Comment by FrozenDragon0** [comment]
> Is this suppose to be a bug or a suggestion?

Most likely a bug, I don't see how cheesing the Symbiont in a boat would be considered a suggestion.

**Comment by mmiller9196** [comment]
maybe if the symbiont got placed in a vehicle/mount, it would summon evoker fangs
