### ISSUE TITLE
A couple bugs (All Versions)

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#560]
1. Even if gamerule mobGriefing is set to false, flaming wither skulls can still cause fires.
2. The withered symbiont can sometimes spawn inside of blocks. This causes the withered symbiont not to face the player, resulting in a very easy fight. (Fixed)
3. Punching a dying withered symbiont still causes it to jump.
4. Regular withers attack the command block entity pushing it.
5. When formidibombed in phase 5 (not the end of phase 5) the wither storm skips to phase 6. (Works as intended)
6. The wither storm's tractor beam can still pull in players and mobs that the wither storm should be passive to (players fighting the withered symbiont as well as entities that are in the same [team](https://minecraft.fandom.com/wiki/Commands/team?so=search) as the wither storm).
7. If the phase of the wither storm is set to a number below 0 with a command, the game crashes.
8. When the wither storm's generic.attack.damage is increased with the attribute command, the wither storm does not do more damage.
9. Explosions can push the command block entity.

**Comment by RandomGithubUser32** [comment]
This should be labeled as a bug but I can't label things.

**Comment by watersofnazareth** [comment]
5 Isn't a bug, it was changed because people were getting confused

**Comment by RandomGithubUser32** [comment]
Okay and also 2 seems to be fixed where punching the symbiont draws it closer to the player.

**Comment by nonamecrackers2** [comment]
How are you setting the phase of the Wither Storm to a value below 0? The /data command?

**Comment by RandomGithubUser32** [comment]
Yeah, I usually use /data. It can lock players out of their worlds.
