### ISSUE TITLE
Withered biome

### ISSUE THREAD

**Issue by normalgamerboi** [nonamecrackers2/crackers-wither-storm-mod#562]
When the wither storm dies not much happens huh well you know how we can walk on the body of a blown up wither storm well how about when it dies instead of it disappearing like the ender dragon it falls just like when it's bombed but it falls apart and becomes a huge biome of withered blocks and chunks of the wither storms flesh and in the middle is a command block and you can rebuild the wither storm structure and respawn it (that would be a good idea for the confirmed wither storm resummonable feature your planning on adding) you can choose what to do with this idea

**Comment by watersofnazareth** [comment]
#184 
#481
