### ISSUE TITLE
[Suggestion] Bigger Phases grab smaller blocks by using the Hunchback's pick up rate

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#563]
I've just had this on my mind but I think it'd be cool if/when the WS picks up 1x1 clusters in a bigger Phase it'd use it's old pick up rate so 1x1s would go up towards the storm fast, if it's just 1x1s then it probably wouldn't affect performance much at all

**Comment by ghost** [comment]
This will help with random floating blocks in craters.

**Comment by BluePineappleGuy** [comment]
perhaps in the tractor beam hunchback pickup cluster size and pickup rate can be used for block clusters, and it forms 1-4 based on the size.
