### ISSUE TITLE
Cleaner terrain eating (debris ring eats blocks too)

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#564]
Inspired by #289
Currently when the witherstorm is in an area for an extended period of time, it will leave random floating blocks and clusters. This isn’t that annoying since you’re not really gonna be near it unless you want to fight the withered symbiont. One option I thought of that could help reduce the amount of floating blocks would be to have the debris ring also bring in blocks, but limit it to only one 1x1 at a time. The debris ring would only choose the closest block to it that is also mostly exposed to air or something.

**Comment by nonamecrackers2** [comment]
What do you mean the Wither Storm currently leaves "random floating blocks and clusters"? It doesn't do this? Slightly confused, sorry if I don't understand what you're getting at.

**Comment by GrandmaPork** [comment]
I think a few screenshots would say more than words could. 
Also, I noticed that when I enter the wither storm bowels in a single player world, a lot of clusters that the wither storm was gonna eat were just kinda turned back into normal blocks and left floating in the air (you can sorta see some towers of them in the second picture, my shield is in the way tho)
![2022-08-16_14 04 56](https://user-images.githubusercontent.com/109642282/187328340-8b47ec49-7bdb-4e5e-a6aa-33526c2dc008.png)
![2022-08-16_14 00 45](https://user-images.githubusercontent.com/109642282/187328555-339e1ea7-931b-419e-be11-7805426fe011.png)
Notice the floating "trees" in these next few
![2022-08-14_00 31 47](https://user-images.githubusercontent.com/109642282/187328743-4b7becc9-7acf-4500-adfd-df9be9d31535.png)
![2022-08-14_00 31 39](https://user-images.githubusercontent.com/109642282/187328905-15f676dc-cd34-40ca-8437-171f27bdf648.png)

**Comment by nonamecrackers2** [comment]
Ohh I see what you mean now. It's very doubtful I can make the terrain "cleaner" without impacting performance, and off the top of my head detecting those floating blocks wouldn't be very possible. I honestly kind of like how the terrain is eaten but I can see how those towers get awkward. I'll experiment with both things and see what I can do however.

**Comment by GrandmaPork** [comment]
Towers seem to be made when a player enters the wither storm. Any way to fix this? Like an option that allows the wither storm to eat clusters even when the player is in the bowels?
![2023-03-21_19 03 21](https://user-images.githubusercontent.com/109642282/226762591-d2b7f225-b633-4f28-8fb8-7542e1c9d370.png)
![2023-03-21_18 56 12](https://user-images.githubusercontent.com/109642282/226762602-c1593dd6-b437-4603-8b50-ddc7ca8e71b7.png)

**Comment by nonamecrackers2** [comment]
This is because the WS doesn't save which clusters it's sucking in and can forget them, making them fall

**Comment by GrandmaPork** [comment]
So does the wither storm unload when you enter the bowels? Could that be changed?

**Comment by nonamecrackers2** [comment]
I’m not fully sure if it does but it’s really the only explanation to why the clusters fall. I’m not sure if there could be anything I could do to fix it if that’s the case

**Comment by nonamecrackers2** [comment]
Fixed the clusters falling on world reload, etc. Going to be leaving out the rest however.
