### ISSUE TITLE
Enable/Disable Config for upcoming Progression Guide

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#565]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

There should be a config for the new progression guide, so it can be disabled or enabled for modpack creators to create a custom progression guide, instead of the default one

**Comment by nonamecrackers2** [comment]
Technically the in-game progression guide isn't a confirmed feature yet.

**Comment by nonamecrackers2** [comment]
There are currently no plans for an in-game guide
