### ISSUE TITLE
More Command Block "Weapons"

### ISSUE THREAD

**Issue by Supertacoz** [nonamecrackers2/crackers-wither-storm-mod#566]
I feel that the Bow, Crossbow, and shield are all left out from being able to benefit from command block books. However, I think I have a balanced Idea. 

1. The Command Block Bow and Crossbow: essentially just a bow and crossbow with infinite durability and increased base stats, these would be able to harm the command block inside the witherstorm, however not with their projectiles, still requiring you to go up and physically hit the block with said weapon. 

2. Command Block shield: This one is a bit weirder, as the shield is not really meant to be a weapon. of course this would allow the shield to benefit from unlimited durability, but would just that actually make it worth spending a command block book on it? I don't think it would be. instead, add a couple abilities to it. for example, perhaps make it so if you are simply wearing it in your off hand or main hand, and one of the tentacles that slaps you away from the command block tries to hit you, make it not affect the player so long as the shield is in a hand. or, maybe make whatever hit your shield take a bit of damage? or maybe allow the command block shield to block certain things that are normally not blockable?

**Comment by Bloxxify2827** [comment]
I remember NonameCrackers saying he wants it to stay “Vanilla” but it would be cool to see them if you just want to get OP stuff before killing him off

**Comment by Cgdihkg** [comment]
Лучьше сделать мощные стрелы командного блока

**Comment by ghost** [comment]
You can just cheese the final fight with a bow if this was implemented

**Comment by Supertacoz** [comment]
I specified you would have to go physically hit the command block with the bow itself, but should have mentioned arrows that it fires shouldn't hurt the command block

**Comment by watersofnazareth** [comment]
The only command block related things should be the tools as you'd need a symbiont every time
#250
#263
