### ISSUE TITLE
Very dark purple sky. 

### ISSUE THREAD

**Issue by Cgdihkg** [nonamecrackers2/crackers-wither-storm-mod#567]
Make sure that from the 4 phase of the drying storm, the sky becomes more and more purple, and at the end it becomes dark dark purple. Otherwise, the atmosphere is 0.

**Comment by RandomGithubUser32** [comment]
In minecraft story mode, the wither storm does not seem to darken the sky in phase 4.

**Comment by Cgdihkg** [comment]
> In minecraft story mode, the wither storm does not seem to darken the sky in phase 4.

He has been darkening the sky since the beginning of phase 5. Check out the screenshot on the wiki as he attacks redstonia

**Comment by RandomGithubUser32** [comment]
Yes but not in phase 4.

**Comment by Cgdihkg** [comment]
> Yes

Well, add.

**Comment by nonamecrackers2** [comment]
#183
