### ISSUE TITLE
A few ideas of mine I have came up with.

### ISSUE THREAD

**Issue by bowsth** [nonamecrackers2/crackers-wither-storm-mod#568]
So, the title explains itself basically if there’s an endermen that gets caught within the storms beam, it will get pissed off at the storm and teleport away. (No, you don’t need to make it so it starts trying to rip it apart.) And also, you can use the flesh blocks from the fallen storm to craft tools, such as Withered Pickaxe, sword ect and if you craft it, The Flesh pick can Mine diamonds, and the sword has an attack damage of 14 or 8, and if you re-summon the storm, and defeat it once again, you’ll get an achievement saying “The more the merrier!” Also, you should make it so if there’s a big structure, then the storm will pay attention to that structure and suck it up, and speaking of tall structures, if a structure gets hit by a tentacle from the storm, that part will be destroyed. Apologizes if these ideas don’t fit the mod or are too complicated to code

**Comment by Luke7381** [comment]
Cracker already confirmed that enderman attacking the wither storm probably won't be added due to how model rendering works unfortunately.

**Comment by watersofnazareth** [comment]
#113
The mod is trying to keep a vanilla feel, having new tools strays too far especially since the flesh is, flesh
#87
#12
