### ISSUE TITLE
Hitbox of heads can be broken at times

### ISSUE THREAD

**Issue by Birbman13** [nonamecrackers2/crackers-wither-storm-mod#569]
When being picked up in a tractor beam, the first reaction is to shoot at the head. Sometimes, arrows go straight through the hitbox, and do not cause the beam to release you. The only way to escape, in my experience, is to hope a skull is shot at you, causing the head to take damage and release you. I have a clip of this happening on a stream, so I may send that in, just so you can see what I mean by this

**Comment by Birbman13** [comment]
Here's the clip. I even turned on hitboxes to see where they were. https://clips.twitch.tv/RefinedTalentedAmazonMrDestructoid-2Q_o1wUa77zwnQwK

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/290
