### ISSUE TITLE
Morph

### ISSUE THREAD

**Issue by Loverxzc** [nonamecrackers2/crackers-wither-storm-mod#57]
Player can transform into Wither Storm. He will get abilities, pull the target, follow 1 target, send sickness, tighten certain blocks, **_poop(jk)?_** Can release the target, and other.

**Comment by IntrovertedGamer** [comment]
Are you trying to make this compatible with a Morph Mod or actually make it a feature of the mod itself?

**Comment by Loverxzc** [comment]
Feature in mod

**Comment by nonamecrackers2** [comment]
This doesn't really fit with what I want for the mod, and would be a lot of effort to try to fit in.
