### ISSUE TITLE
Block clusters orbit the wither storm.

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#570]
Just like the debris, it would be cool if there was an option for the block clusters to orbit the wither storm instead of the block clusters flying straight into the wither storm. The block clusters could fly to the debris clouds and orbit the wither storm alongside the rest of the debris for 5-10 seconds before being absorbed by the wither storm. The reason I say that this should be configurable is for lower-end computers that might not be able to handle this.

**Comment by watersofnazareth** [comment]
#289

**Comment by RandomGithubUser32** [comment]
Yeah, but it is a config option and it is not exactly the same.

**Comment by nonamecrackers2** [comment]
I may actually experiment with this, especially since Flywheel has proven to increase performance with block clusters tremendously.
