### ISSUE TITLE
Drop for phases 0-3

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#571]
I know that the wither storm is not supposed to be killed in those phases but it still feels awkward having such a powerful boss like that drop nothing. A normal nether star or a command block could work.

**Comment by watersofnazareth** [comment]
It should probably drop a regular nether star but you're not really meant to kill it in the 0-3 phases

**Comment by RandomGithubUser32** [comment]
Yeah, it just feels awkward having such a powerful boss drop nothing.

**Comment by FrozenDragon0** [comment]
How would you even kill it at the low phases considering it regenerates HP so fast?

**Comment by RandomGithubUser32** [comment]
Smite 5 netherite sword or power V bow with healing arrows. Also, I use strength 255 in creative for testing reasons.

**Comment by FrozenDragon0** [comment]
> Smite 5 netherite sword or power V bow with healing arrows. Also, I use strength 255 in creative for testing reasons.

Ah, now that makes sense. I did kill it once via Health potion with a modified level of 10 just to see what would happen.

**Comment by nonamecrackers2** [comment]
Since those phases are technically supposed to be killed at all, we'll be leaving this suggestion out.
