### ISSUE TITLE
Distant fog suggestion.

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#572]
When the client option distant fog is turned off, the wither storm is not affected by the fog in the distance but when the wither storm enters the player's render's distance, the wither storm is affected by fog. It looks pretty awkward so it would be better if this was changed so that the wither storm is not affected by fog at all if distant fog is turned off.

**Comment by watersofnazareth** [comment]
This is due to the game changing between the distant renderer and regular rendering, and I don't think there is much to fix this

**Comment by RandomGithubUser32** [comment]
I don't know if this is possible to do but the solution would be to make the wither storm completely immune to fog.

**Comment by nonamecrackers2** [comment]
With how rendering works and how fog is setup disabling fog on a per entity basis is not possible without some severe code injection I'm not willing to do.

**Comment by RandomGithubUser32** [comment]
Okay, I get that this is not possible.

**Comment by myron-obsolete-account** [comment]
@RandomGithubUser32 there is a mod called NoFog on curseforge which you can use to remove that fog entirely so it doesnt look weird. in the config settings of the mod (using clothconfig) you only need to disable terrain fog, everything else you can turn back on (when installing the mod it turns off a few other fog types by defaut which you dont need to turn off for the wither storm fog thing to look better)

**Comment by myron-obsolete-account** [comment]
optifine has a similar feature and its a bit easier to use however optifine stops rendering the storm when you dont have the entity base on screen (which is at the bottom of the body) because optifine makes things to entity rendering that we perhaps dont want to happen so NoFog is an alternate solution

**Comment by myron-obsolete-account** [comment]
@RandomGithubUser32 hi uh are you alive or something?
