### ISSUE TITLE
Problems with the Wither Storm and L_Ender's Cataclysm

### ISSUE THREAD

**Issue by 48004800** [nonamecrackers2/crackers-wither-storm-mod#573]
1.19.3.0 Cracker's Wither Storm 
0.20 L_Ender's Cataclysm
https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm
I'm pretty sure it's a hitbox issue.This happens with the Wither Storm in Phase 4 and beyond.
Wither Storm cannot bite enderguards and ender  golems
Wither Storm has an animation that keeps shaking its head, but cannot deal damage to them.

suggestion：
As a couple of additional suggestions, I recommend allowing the Wither Storm to fire huge heads and cause big explosions. Wither Storm's bite should be as powerful as /kill.
You might think my suggestion is inappropriate, but overall it's a good idea to add some cool attacks to this behemoth.

**Comment by nonamecrackers2** [comment]
This is probably due to the entities being invulnerable to the damage the heads deal #523

**Comment by 48004800** [comment]
> This is probably due to the entities being invulnerable to the damage the heads deal #523

This happens with the Wither Storm in Phase 4 and beyond.
Phase 3 Wither Storm can easily kill enderguards and endergolems

**Comment by 48004800** [comment]
> This is probably due to the entities being invulnerable to the damage the heads deal #523

I'm sure the wither storm can damage them, seems to be a hitbox issue

**Comment by 48004800** [comment]
If you have time, you should re-understand my question.
I can be sure that wither storms can damage both entities, occasionally wither storms can bite them but most of the time it doesn't do damage due to hitboxes.

**Comment by nonamecrackers2** [comment]
Interesting. I'll reopen and investigate further.

**Comment by 48004800** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/580#issue-1356901002
