### ISSUE TITLE
Maybe add the armors? (Only Ivors armor in his base)

### ISSUE THREAD

**Issue by Bloxxify2827** [nonamecrackers2/crackers-wither-storm-mod#574]
**Description of feature**
I think it would be cool if you added the armor that you see in ivors lab when you go to the farlands, i thought that they all have the same armor durability and protection, maybe having them all 2 or 3 more armor points than netherite, and able to be enchanted.
![0F0BA446-981F-47FA-A9C6-D20822EE8BF5](https://user-images.githubusercontent.com/110550077/187317000-499b750b-e498-496c-95d3-0eb06be06ac7.png)
![4C50B543-440E-431D-AFD9-D347308D3D98](https://user-images.githubusercontent.com/110550077/187317010-e27ddf6b-9c9b-4b49-af7d-7bb1fb4f493b.jpeg)

**Comment by ghost** [comment]
there is a mod for this.

**Comment by nonamecrackers2** [comment]
#91
