### ISSUE TITLE
Make the "wither_storm_boss_theme.ogg" of higher quality

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#575]
I have seen that the same music that the game uses, I have listened several times the music that brings the mod, and it is heard in my opinion that this in several times saturated, the saturated parts are 0:43 to 1:31 in my opinion, now I also hear that there are parts cut and the cut is noticed when the music is changed, I leave a link to youtube with the music of higher quality (I repeat, in my opinion) of the original authors of the theme https://www. youtube.com/watch?v=3NlkqN3O1MU obviously may be missing things, as at the end it lacks that "sound decreasing" and other things, I also recommend that at the second 0:42 the wither is generated when we invoke it, or you can lengthen the time I do not know, I leave my recommendation and I will be aware of your response, I also leave the SoundCloud of them https://soundcloud.com/wellescreative

**Comment by watersofnazareth** [comment]
Most of the audio files are going to be replaced with higher quality ones that were extracted from MCSM, including the theme which will be longer and less muddy

**Comment by nonamecrackers2** [comment]
Will be implemented in the next 1.18./1.19 release

**Comment by TheSrBig** [comment]
> Will be implemented in the next 1.18./1.19 release

Good
