### ISSUE TITLE
Ring the bells! - New Advancement / Villager behavior

### ISSUE THREAD

**Issue by Mettod99** [nonamecrackers2/crackers-wither-storm-mod#576]
I just thought it would be cool, when the Wither Storm is approaching a village, you would get new "Ring the bells!" or "The storm is coming!" advancement if you just simply ring the village bell.

Or it could be feature when the WS is near to a village, villagers would panic and ring the bell just like in raid.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
