### ISSUE TITLE
Blocks dont appear

### ISSUE THREAD

**Issue by Davoiscoollol302** [nonamecrackers2/crackers-wither-storm-mod#578]
**Minecraft version**
1.16.5

**Mod version**
1.0.2.6

**Describe the bug**
The phase 5-7 on low res model off his blocks disappears in 1.16.5

**To Reproduce**
1. Open minecraft
2. Spawn a wither storm in phase 5-7
3. See him.
4. Thats if

**Crash Reports / Logs**
This dont crash but is annoying

**Screenshots**
![Screenshot_20220821-174453_PojavLauncher_Minecraft_Java_Edition_for_Android](https://user-images.githubusercontent.com/112526862/187570547-c82cdce5-6b22-4a7d-8f71-6c5fab71a630.jpg)

**Comment by Bloxxify2827** [comment]
Maybe cause your on a goddamn android lol

**Comment by Bloxxify2827** [comment]
Wait how did you get forge for pojavlauncher?

**Comment by Bloxxify2827** [comment]
And how did you get a .jar into it?

**Comment by Davoiscoollol302** [comment]
> 
This also happened on pc lol

**Comment by nonamecrackers2** [comment]
#16. This may be a hardware limit or you aren't allocating enough memory to your game. I'm not entirely certain however I'm not sure how I could fix this anyway.
