### ISSUE TITLE
How does wither storm follow player and load chunks

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#579]
*please add "Questions" Tag to this post

Ok so question

How does the wither storm constantly follow the player & load chunks I kinda having a hard time with one of my other mods also while I'm here I mine as well report a bug

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
If you wondering what mods it's for its for murder alpha's revenge
Couldn't release even a beta without following working
Also maybe a dusttale sans mod if I do end up making that

**Comment by nonamecrackers2** [comment]
The chunk loading is a bit complicated, but in a nutshell it constantly ticks for Wither Storms that are alive, then queues chunks to load using the setChunksForced method in ServerLevel. It then copies how the Wither flies and searches for the nearest player out of all that exists in the current world the WS is in. For the bug, I recommend making a new issue to seperate it from this question.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> The chunk loading is a bit complicated, but in a nutshell it constantly ticks for Wither Storms that are alive, then queues chunks to load using the setChunksForced method in ServerLevel. It then copies how the Wither flies and searches for the nearest player out of all that exists in the current world the WS is in. For the bug, I recommend making a new issue to seperate it from this question.

Tysm
