### ISSUE TITLE
Wither storm hitbox issue

### ISSUE THREAD

**Issue by 48004800** [nonamecrackers2/crackers-wither-storm-mod#580]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/573#issue-1354200038
This question is the same as that one

1.19.2
mod:1.19.3.0
forge:43.1.3

I already know that the author plans to strengthen the attack of the wither storm to   kill powerful entities, and I fully agree with this change, but my problem is not related to this change.

Wither Storm will not be able to deal damage to some entities in phase 4 or above due to hitbox issues

![2022-08-31_14 57 27](https://user-images.githubusercontent.com/78255094/187615299-a0b25ad8-9727-43ac-bce5-8db547318365.png)
![2022-08-31_14 57 33](https://user-images.githubusercontent.com/78255094/187615333-da2a55c0-d381-47c8-a366-ca33b112fccf.png)
![2022-08-31_14 57 40](https://user-images.githubusercontent.com/78255094/187615357-53784492-e1db-4e71-8fd7-424c4f406223.png)

Wither Storm can damage these entities in phase 3
![2022-08-31_14 59 37](https://user-images.githubusercontent.com/78255094/187615415-ce6151f6-5797-40bd-a45e-0d50fd364051.png)

**Comment by 48004800** [comment]
The Wither Storm is not invulnerable even in the final stages, maybe you could consider strengthening him and make a command specifically designed to clear the Wither Storm. (The author previously stated that strengthening the wither storm may make /kill ineffective)（This is just a digression）

**Comment by 48004800** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/573#issue-1354200038

**Comment by Catlord-3** [comment]
The storm is also removed in peaceful mode, which I feel like will be what is typically used to remove it, as it's a lot easier to set the difficulty to peaceful than do /kill @e[type=witherstorm], so there should be a way to remove the storm anyways if it is causing major issues, or you just want to clear it, so being immune to /kill would not remove ways of clearing storms without properly killing them (going through command block fight for each storm). I think adding a command to remove the wither storm is a good idea too in case you dont want to set difficulty to peaceful for some reason.

**Comment by 48004800** [comment]
@nonamecrackers2 
I don't know why, but the problem is solved now

**Comment by nonamecrackers2** [comment]
Huh. Alright, let us know if it pops up again and you can reproduce it

**Comment by 48004800** [comment]
> Huh. Alright, let us know if it pops up again and you can reproduce it

This problem has reappeared.
forge:45.0.43 
[citadel-2.3.3-1.19.4](https://www.curseforge.com/minecraft/mc-mods/citadel/files/4473245)
[L_Ender's cataclysm-0.83 -1.19.4 M.F.A fix](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm/files/4494496)
[witherstormmod-1.19.4-3.2.1.3.jar](https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod/files/4468077)

**Comment by nonamecrackers2** [comment]
Really? Alright will have to investigate then
