### ISSUE TITLE
New Injury System - Toughening

### ISSUE THREAD

**Issue by GoldSlimeling91** [nonamecrackers2/crackers-wither-storm-mod#582]
So as of now, the head injury system with the Storm is based purely on a dice roll and if you don't win that dice roll, you die. With this current system of luck based gameplay it can lead to a lot of frustration when you shoot a whole stack of arrows at a head and yet it does nothing to the head you're shooting at, this is my concept on an overhauled injury system.

The Wither Storm's heads could have their own individual health bars and become injured when this health reaches 0, very similar to how the heads found in the bowels work, though there could also be a smaller hitbox where the eye is that takes more damage, much like the Ender Dragon's head. When one of it's heads is injured it will still repair itself like normal, just that the next time you get pulled by that head, it will take more hits than before before becoming injured and having it's tractor beam be disabled.

This new armor the heads gain would be lost over time as the Storm is off in the distance, usually between the encounters and chase sequences. Melee weapons would still deal more damage to the heads than ranged projectiles would and still act as a last resort, but will still eventually be nullified by the armor the heads gain from being attacked too often and it would still inflict a decent bite of your health away even if you injured it and got away from it's clutches.

Overall just removing the luck aspect but still keeping the whole 'try to not be pulled in too much' aspect, that's my take bye bye.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/425
This is not exactly the same though

**Comment by nonamecrackers2** [comment]
Closing since recent changes to how the injury system works doesn't really make this necessary
