### ISSUE TITLE
Flickering Redstone Lights, Beacons, Lanterns, and etc. when Wither Storm is in proximity

### ISSUE THREAD

**Issue by BulbousDrew** [nonamecrackers2/crackers-wither-storm-mod#583]
If a Wither Storm is in proximity to Redstone Lights, Beacons, Lanterns, or other light sources, the light sources flicker. All of this would be toggleable from the config menu, of course.
Ex:
Light Flicker
Redstone Lamp: On/Off
Glowstone: On/Off
Torch: On/Off
Sea Lantern: On/Off
Beacon: On/Off
Lantern: On/Off

Redstone Lamps and Beacons would only flicker when powered.

**Comment by Bloxxify2827** [comment]
I think this would be a good idea, maybe 500 blocks and closer

**Comment by BulbousDrew** [comment]
Yeah, it would add a higher level of immersion if it were to happen farther away

**Comment by watersofnazareth** [comment]
This would cause pretty bad lag for servers, Minecraft's lighting engine is really slow

**Comment by nonamecrackers2** [comment]
> This would cause pretty bad lag for servers, Minecraft's lighting engine is really slow

That and I'm not sure blockstates can support this.

**Comment by TaintedBlockk** [comment]
That would be pretty scary honestly.

**Comment by ShadeKage** [comment]
You could just have the block blink but with no light updates, that'd solve the lag issue

**Comment by nonamecrackers2** [comment]
Closing since this would be very difficult to implement and would be very taxing on performance
