### ISSUE TITLE
Small little aesthetic

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#585]
**Description of feature**
Can a command block be placed in the center of the wither storm model? Theres probably no point to adding this but it would be a small little detail because you know the command block is in the center of it.

**Comment by Bloxxify2827** [comment]
Though this is in the engender mod, it really has no meaning because the wither storm in crackers mod because its supposed to be invincible on the outside

**Comment by Luke7381** [comment]
> Though this is in the engender mod, it really has no meaning because the wither storm in crackers mod because its supposed to be invincible on the outside

Yeah that makes sense, plus the community didn't respond greatly so ill close it.

**Comment by nonamecrackers2** [comment]
Someone already suggested this, however I can't I find it. Considering that you're not meant to see the inside of the WS's mass model, there is no point. Thanks for the suggestion though

**Comment by Luke7381** [comment]
> Someone already suggested this, however I can't I find it. Considering that you're not meant to see the inside of the WS's mass model, there is no point. Thanks for the suggestion though

Yeah i figured.
