### ISSUE TITLE
Tentacle growing animation at the beginning of phase 3

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#587]
**Description of feature**
maybe there could be an animation for when the tentacles grow at the beginning of phase 3

**Comment by watersofnazareth** [comment]
Redoing the animations is a pretty big hassle for something so miniscule

**Comment by Globalfirestorm10** [comment]
> Redoing the animations is a pretty big hassle for something so miniscule

True, but it would be cool to see them grow. Maybe this could be marked as low priority, idk

**Comment by BluePineappleGuy** [comment]
I like the idea of animations when it evolves. i think a similar thing with the heads would be great when evolving into stage 4/7.

**Comment by nonamecrackers2** [comment]
> Redoing the animations is a pretty big hassle for something so miniscule
