### ISSUE TITLE
Make phases 4-7 more immersive

### ISSUE THREAD

**Issue by Birbman13** [nonamecrackers2/crackers-wither-storm-mod#589]
Use lighting changes, world interaction beyond picking up chunks of the world, maybe an actual thunder storm, and other methods of making the fight more immersive. At the moment it feels mostly like getting picked up, shooting the eye, rinse and repeat. 
Some of these ideas I've seen from other suggestions.

**Comment by watersofnazareth** [comment]
#463

**Comment by nonamecrackers2** [comment]
Also #552
