### ISSUE TITLE
[Wither Storm head escaping system rewrite] tractor beam bug

### ISSUE THREAD

**Issue by jarbearO9** [nonamecrackers2/crackers-wither-storm-mod#59]
when i get pulled in but escape by shooting the head, the head that got me targets me until i rejoin the world.

**Comment by jarbearO9** [comment]
Same thing if i hit it with a sword

**Comment by Loverxzc** [comment]
Are you from Russia? Or it seems to me?

**Comment by nonamecrackers2** [comment]
Probably because the variable that keeps track of the cooldown isn't saved, I'm wanting to rewrite this system anyway

**Comment by nonamecrackers2** [comment]
This system has been rewritten for 1.18.2 and won't be backported to 1.16.5
