### ISSUE TITLE
Skip death animation option

### ISSUE THREAD

**Issue by KrukAdrian** [nonamecrackers2/crackers-wither-storm-mod#591]
Make an option so you can skip the death animation of the wither storm when you defeat the command block or use the /kill command.
If this was already suggested, Please tell me

**Comment by watersofnazareth** [comment]
The kill command should be able to kill it without any animation as we saw with the Server when we tried killing it, I think this should be changed

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
