### ISSUE TITLE
Carryon Wither Storm Phase 4-7 Errors

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#592]
**Minecraft version**
1.18.2

**Mod version**
The version of the mod you are using

**Describe the bug**
While Using CarryOn And Picking Up The Wither Storm In Phase 4 & Beyond The Model Renders A Giant Black Blob When You Enter F5 Mode & Fly It Should Acually Model As A Tiny Wither Storm In Your Hand

**To Reproduce**
1. Install CarryOn
2. Pick Up The Wither Storm In Phase 4 And Beyond
3. see error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by watersofnazareth** [comment]
This isn't really a bug that can be fixed by Crackers, this should be opened up to Carry On

**Comment by nonamecrackers2** [comment]
Try reporting to carry on. If you can reproduce this with other mobs than this is definitely a carry on issue.
