### ISSUE TITLE
Wither Sickness overlay can be seen on transparent textures

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#593]
**Minecraft version**
1.18.1.19.2

**Mod version**
Latest

**Describe the bug**
For some entities, mostly modded entities, which have special transparent pixels, can have the texture overlapping on pixels that aren't supposed to be visible

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**
![2022-09-03_11 48 15](https://user-images.githubusercontent.com/36087299/188278234-90f045a5-2cb5-4abe-99b1-b9fca4af196c.png)

**Comment by watersofnazareth** [comment]
This could be possibly fixed by changing the rendering from Wither Sickness to be invisible on pixels that have no color, this could also fix head layer rendering on Zombies and other mobs

**Comment by nonamecrackers2** [comment]
Not entirely sure this is possible however I'll definitely try looking into it.

**Comment by ShadeKage** [comment]
Had this glitch happen with epic fight active while blocking with a shield, you could see through the shield cause or the purple effect, has to do with entity screen priority, same thing that causes Z fighting

**Comment by nonamecrackers2** [comment]
Fixed in 2.2/3.2
