### ISSUE TITLE
Special Potion Of Leaping

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#596]
Like in MCSM there should be a potion of leaping you can find in witch huts that allows you to jump into the bowels of the wither storm

**Comment by GrandmaPork** [comment]
I feel like people would drink this and kill themselves with it before realizing they could use it to get into the bowels

**Comment by TostOlabilir** [comment]
You can just use 
/give @p potion{CustomPotionColor:655104,display:{Name:'[{"text":"Potion of Leaping","italic":false}]'},CustomPotionEffects:[{Id:8,Duration:300,Amplifier:70}]} 1

**Comment by watersofnazareth** [comment]
I don't think this would or should be added as there is already a way to get into the bowels

**Comment by RandomGithubUser32** [comment]
A potion that allows you to jump that high would be too op.

**Comment by nonamecrackers2** [comment]
You could easily do this with commands (as pointed out by @TostOlabilir). I don't feel this is entirely necessary to be implemented by the mod.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> You can just use /give @p potion{CustomPotionColor:655104,display:{Name:'[{"text":"Potion of Leaping","italic":false}]'},CustomPotionEffects:[{Id:8,Duration:300,Amplifier:70}]} 1

Thats the boring way to do it but ok also you can't even get it without cheats
