### ISSUE TITLE
WS Bossbar

### ISSUE THREAD

**Issue by TostOlabilir** [nonamecrackers2/crackers-wither-storm-mod#597]
Option to hide bossbar and the wither storm name in The W settings since it's kinda useless after phase 4. I know most people are cool with the bossbar but having the option is always nice.

**Comment by watersofnazareth** [comment]
#488

**Comment by nonamecrackers2** [comment]
Technically a different feature request so I'll reopen this. I can definitely see how people may want the bossbar hidden. Will have to look into it though,

**Comment by nonamecrackers2** [comment]
Won't be adding a config to disable the bossbar outright
