### ISSUE TITLE
Config to immediately spawn Wither Storm upon world start

### ISSUE THREAD

**Issue by BudgieGryphon** [nonamecrackers2/crackers-wither-storm-mod#599]
For those of us who like pain and suffering, a config option that causes the Wither Storm to spawn when the world is started. Possibly a grace timer before it starts? I know you can just... spawn it manually but not having control over when/if it spawns is fun.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release

**Comment by Laughingcat27** [comment]
would be great if it works on servers, because everytime i play with friends, we agree to not collect any items/make progress before spawning the storm. and you wouldn't guess it, they go around and chop trees anyways, saying it's "just a tree"

**Comment by Aimyx** [comment]
where in the world would the wither storm spawn? 0,0 or somewhere else?

**Comment by nonamecrackers2** [comment]
Wherever the rundown house is
