### ISSUE TITLE
Danny's Expansion mod compatibility issue

### ISSUE THREAD

**Issue by birdyalo** [nonamecrackers2/crackers-wither-storm-mod#6]
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: nonamecrackers2.witherstormmod.client.capability.PlayerScreenBlinder cannot be cast to com.bottomtextdanny.dannys_expansion.core.capabilities.player.DannyEntityCap
Exit Code: -1

[crash-2022-05-10_14.20.08-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/8665095/crash-2022-05-10_14.20.08-client.txt)

**Comment by nonamecrackers2** [comment]
I managed to reproduce the issue, and from the logs it appears to be something with Danny's Expansion, if I'm not mistaken. Unfortunately, I can't look at their source code to see what they've done. You could try asking the mod author to see if it's something they can fix.

**Comment by birdyalo** [comment]
Rip. its fine. Sure, ill ask them.
