### ISSUE TITLE
Wither storm absorbtion (suggestion)

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#60]
I have an idea for the wither storm absorbing blocks!
something that could you could do is make models of the wither storm that grow each time a block is absorbed, for example the wither storm eats a block, it detects when that block is eaten, then it changes stages, but only wither smaller increments like 8 2x2x2 pixel chunks in a random area on the wither storm's back.

 

If you have trouble doing the models, I'll gladly help you make them! I can make the models, and you texture them! (I'm not good with textures)

HOWEVER, I can only model with blockbench, so I will likely take longer with any other modelling source.

 

with bigger chunks, it grows more, so the 3x3x3 block chunks add 216 2x2x2 chunks, etc. like I said, I can help with the models, so no worry.

 

P. S. if you want faster updates on the models (if you need them) you can add me through my discord- Super Shark Gaming#1771 (copy and paste it)

**Comment by nonamecrackers2** [comment]
Creating procedural models with minecraft's entity modelling system would not be feasible, and making models for each time a block or any amount of blocks is absorbed would be a nightmare to create and manage (lots of models)
 
While I appreciate your willingness to help, again this idea isn't very feasible, and the method I have for creating the Wither Storm models actually doesn't use block bench directly. Instead, I build the models with blocks in the game then use a conversion process to transform them into entity models. I've tried building the models using block bench directly before and it got too slow. Thanks for the offer though.

**Comment by SSgamingYT** [comment]
its not procedural models, its growing each time a block touches the storm. its always the same model, just skipping some sub stages when certain amounts of clusters are consumed
