### ISSUE TITLE
Wither Storm AI independent of player movement

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#600]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

Lets say a all of the players log off the server, leaving the wither storm to rampage the world overnight. Currently, it would just stay at spawn no matter what. My idea is to make it stay at spawn until it no longer can pick up blocks, then it picks a direction and goes in it slowly. If it reaches the world border, it turns randomly.

**Comment by TSEG6** [comment]
I feel like it would be better if it just kept wandering around completely randomly after a certain amount of time has passed if there are no players, and only staying in the same location if there's a structure nearby.

**Comment by RandomGithubUser32** [comment]
This would solve the issue of the wither storm not moving at all when all players are in spectator mode.

**Comment by watersofnazareth** [comment]
The WS deloads when players are not on the server

**Comment by RandomGithubUser32** [comment]
Perhaps just have this feature for when the wither storm has nothing to follow.

**Comment by nonamecrackers2** [comment]
This could probably be a new ultimate targeting type.

**Comment by Asteroid4** [comment]
> This could probably be a new ultimate targeting type.

Yea! It could also function as the default if there is no valid ultimate target.

**Comment by CubeGamer647** [comment]
I would like this kind of targeting even if there were players online. I would like to see it just wander around, randomly destroying stuff and targeting things other than players. I don't think this is a feature, but correct me if I'm wrong.

**Comment by BladeLightsteel** [comment]
i feel like you should be able to just have it wander around to like villages and structures, and once it destroys it, it kinda moves on to the next closest one

**Comment by nonamecrackers2** [comment]
Random strolling will be added in the next major release.
