### ISSUE TITLE
The amulet

### ISSUE THREAD

**Issue by Theoyeah** [nonamecrackers2/crackers-wither-storm-mod#601]
I know, there's a demo in discord i think??? But i have an idea...

For the Wither Storm, it would follow the player with the amulet... but in case no one have it, it would go to the nearest person as it should do.  Another scenario is that if a player does have one, but another player is near enough to the WS, the Wither Storm would start chasing him.

Hope it helps you!

**Comment by Globalfirestorm10** [comment]
The amulet is made for multiplayer, and it does exactly what you say, follows the player with it
