### ISSUE TITLE
is it there any way I can check if witherstorm despawned?

### ISSUE THREAD

**Issue by Dvudu** [nonamecrackers2/crackers-wither-storm-mod#602]
I'm worried it may have despawned after my game crashed. I haven't seen it for quite a long time, and although I could just wait for it to get near to me, i'd rather finding out through some command or any other way that doesnt require waiting still, im **really** far away from the last time ive died to it. Im playing in singleplayer with entity distance in 500%, btw.

**Comment by FrozenDragon0** [comment]
What's your coordinates from spawn? The Witherstorm does eventually no longer render if your extremely far out, had this in a world where I was 100k blocks from spawn and couldn't see the storm at all but it was still active.

**Comment by Dvudu** [comment]
Not as far as you were, it was about 6k blocks from the spawn (-5715 35 810), but now im pretty much at the spawn. Yet, I can't see the storm nor have seen it on my way. I do feel like ive been finding mobs sick with the wither disease more often than before, though.

**Comment by Catlord-3** [comment]
You can do/tp @e[type=witherstormmod:wither_storm] @e[type=witherstormmod:wither_storm,limit=1]. If there is a storm it will successfully teleport it to itself and say "teleported wither storm to wither storm". If the storm is despawned or something, it will say "no entity was found"

**Comment by Dvudu** [comment]
Thank you so much!!! It seems like it did despawn, indeed, no entity was found.

**Comment by nonamecrackers2** [comment]
If you're using optifine and this is singleplayer, make sure "Smooth World" is off to prevent this from reoccurring.
