### ISSUE TITLE
Ban Appeal

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#603]
(context, they made # memes slow mode 6 hours long and I got banned for complaining) Hello, Crackers Modded Community, I was Permanently IP banned at 6:03 PM September 1st 2022, Me along with other Members were banned for "Complaining", We were banned with no warning beforehand, and "Complaining" doesn't even break any of the rules, I was banned for "complaining", but all I really did was post memes about "how the server isn't as fun as it once was" I was then banned without even receiving a warning. I would like an unban from the server, I am sorry for all the trouble I might have caused to the server.
(images of the messages in the comments)

**Comment by Nov1st2k10** [comment]
![image](https://user-images.githubusercontent.com/106888663/188338833-4f1f6757-3904-49b7-8160-78e922bef492.png)
![image](https://user-images.githubusercontent.com/106888663/188338844-a2b33d43-ff98-4c15-bda4-25100271b247.png)
![image](https://user-images.githubusercontent.com/106888663/188338862-7220ac95-b2a5-4875-a721-1283b42d56fc.png)
![image](https://user-images.githubusercontent.com/106888663/188338865-4d6dd76c-f179-4d6d-9765-f62ed92224b4.png)

**Comment by Nov1st2k10** [comment]
![Screen Shot 2022-09-04 at 5 14 08 PM 1](https://user-images.githubusercontent.com/106888663/188339080-a8f5e883-edeb-440b-9628-fb7c8f54b3f5.png)

**Comment by watersofnazareth** [comment]
Yeah we were talking about this and I do apologize, it was a harsh punishment but at the time I was the only staff online and the drama was really excessive, I should've just timed you out instead
