### ISSUE TITLE
Withered Symbiont phase 2 buff

### ISSUE THREAD

**Issue by GoldenDarius** [nonamecrackers2/crackers-wither-storm-mod#604]
The Withered Symbiont is a great boss with lots of potential, but as you know by now I think it needs a buff. I decided to rather focus my ideas on phase 2 so it feels more of a challenge, considering the next update we know about.. 

Phase two is honestly too easy. You can cheese it by causing explosions next to the Symbiont, especially with the creepers he summons. Phase two should trigger the exact moment his health reaches half, coded to be unable to go lower than half until phase 2 is triggered maybe, so if an attack should deal enough damage to go beyond half, it won't. Once it hits half health, the Symbiont will roar and wave its arms up, and have invincibility frames for 19 seconds of this small cutscenes, maybe some particles can be added. As it "transforms", it can gain the Wither Boss shield, which allows the Symbiont to be invulnerable to explosions while also tanking damage, losing less health with each hit.
![Wither_with_wither_armor_effect](https://user-images.githubusercontent.com/75396163/188574653-2d7c17a8-d521-4567-baa1-a196923ef1da.gif)

Another idea I had is for the Symbiont to gain a small Command Block interface onto its chest, right during the 19th second of the cutscene for his transformation, which can be useful for a battle mechanic. It can be the only place where the player can use arrows against the Symbiont, and if hit with an arrow the moment the Symbiont is preparing an attack, it will stop the attack and cause the Symbiont to enter in a very short stage of stun, maybe shaking its head in confusion or something. 
![Normal-6738_1080x675](https://user-images.githubusercontent.com/75396163/188575657-430ccb56-c336-4cd1-ae93-a97c9bc24c54.png)

**Comment by GoldenDarius** [comment]
(By the way, I said 19 seconds because that's how long the intro for the theme is)

**Comment by watersofnazareth** [comment]
#520

**Comment by GoldenDarius** [comment]
> #520

I do not think it's related to that at all. It's very generic, and my idea was to target phase 2 specifically and in a detailed way, not just "buff symbiont". This is mostly being done because of the music update too. Since phase 2 is very intense, the actual fight needs to be intense

**Comment by nonamecrackers2** [comment]
Quite like the first idea, I'll try messing around with it in the future.

**Comment by nonamecrackers2** [comment]
The symbiont not going below half-health will be implemented in the next major release.
