### ISSUE TITLE
Segments also should turn into blocks during fake death

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#605]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

My idea is that if a segment fake dies, it also turns into blocks, like the main wither storm. However, these structures would be smaller and have nothing on them.

**Comment by Asteroid4** [comment]
It would be more decorative than anything, so I guess it should be low priority.

**Comment by watersofnazareth** [comment]
Think this was suggested already and it wouldn't work out well, I can't find the issue number though

**Comment by nonamecrackers2** [comment]
There isn't much need for a little platform to be generated (like the "starfish" of the main ws) and I feel it may look awkward. If you meant for the blocks of the model to become actual blocks, then that is not possible.
