### ISSUE TITLE
I suggest making the sky darker 

### ISSUE THREAD

**Issue by Cgdihkg** [nonamecrackers2/crackers-wither-storm-mod#606]
I suggest making the sky darker in phase 4 and above. Why in phase 4? If you noticed, a wither storm darkens the sky in phase 4 in the minecraft story mode. At the very end of episode 1, the storm almost overtook them, the sky darkened slightly and began to blink (I don't think to add blinking, but only darkening).

And i know, what was more suggestion.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/183
