### ISSUE TITLE
Higher level phases for Wither Storm and Severed Wither Storms

### ISSUE THREAD

**Issue by TaintedBlockk** [nonamecrackers2/crackers-wither-storm-mod#608]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**
I think as a feature to add to the Wither Storm for future updates is to make it continue to grow bigger but at a much slower rate. Like to the point where it starts to cover up the hole in its head. For the Severed Storms I feel like they could eventually grow to a good size but does max out to a certain size for the main Storm and the severed ones.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/389
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/10
