### ISSUE TITLE
Player statues idea

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#609]
Here’s an old mod that implements player statues. I could help find similar mods if you think this would be possible and/or would like more ideas https://youtu.be/d_-qaJOeI1o

**Comment by nonamecrackers2** [comment]
Pretty cool, however this has already been suggested [here](https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/223#:~:text=There%20could%20also%20be%20a%20function%20(maybe%20optional)%20for%20a%20player%20model%20to%20be%20spawned%20as%20decoration%20in%20case%20the%20WS%20has%20absorbed%20them) #223
