### ISSUE TITLE
Altered progression

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#610]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

My idea is to make super tnt obtainable from end cities and not be able to be crafted via the command block book.

**Comment by Asteroid4** [comment]
It feel it would give the feeling of searching across the world for a way to destroy the wither storm felt in MCSM.

**Comment by Sculkter** [comment]
Try Explorer's Eve. It's a Wither Storm Modpack adding to the challenge of the Storm. You still craft somethings the same, but alot of the recipes have been revamped.

**Comment by Cgdihkg** [comment]
Как тогда выйти? Только покажется твой палец он сразу темя затянет.

**Comment by nonamecrackers2** [comment]
I don't plan on altering the progression, however there are modpacks such as [Explorer's Eve](https://www.curseforge.com/minecraft/modpacks/explorers-eve) which makes super tnt only obtainable via structures (I believe) which is mainly what you want.
