### ISSUE TITLE
A multiple occurrence crash

### ISSUE THREAD

**Issue by 48004800** [nonamecrackers2/crackers-wither-storm-mod#614]
1.19.2
mod:3.0

[crash-2022-09-10_22.23.28-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9540568/crash-2022-09-10_22.23.28-server.txt)

**Comment by Globalfirestorm10** [comment]
looks like there was an issue rendering a symbiont

**Comment by nonamecrackers2** [comment]
If this is super flat, reload your world. This is a vanilla bug (I believe) in 1.19 that causes dimensions added by data packs/mods to not load on world creation. After reload everything should work fine.
