### ISSUE TITLE
Different types of Symbionts.

### ISSUE THREAD

**Issue by ItsZed01** [nonamecrackers2/crackers-wither-storm-mod#616]
So, what I was thinking is, there should be a variation between the different types of symbionts, for example, there could be 3 of them and it would be a 1 in 3 chance for one of those types to spawn, I guess I can make some quick renders of the different variations. Obviously this isn't the final thing, I just made something really quick since I'm too lazy to texture it..
![symbionts](https://user-images.githubusercontent.com/81433526/189496647-b0cb7843-4089-4970-b306-3228e910008a.png)

**Comment by RandomGithubUser32** [comment]
Do they have different abilities or are those just alternate models?

**Comment by ItsZed01** [comment]
> 

im not sure, its mostly up to crackers, but it would be cool if they had different abilities lol

**Comment by RandomGithubUser32** [comment]
He will probably give them different abilities because this is labeled game-changing.

**Comment by nonamecrackers2** [comment]
I don't feel the symbiont should really have different variations, and I'm not sure what each variation could hold.
