### ISSUE TITLE
Origins (Forge) Phantom Origin

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#617]
**Minecraft version**
1.18.2

**Mod version**
2.1-pre.3

**Describe the bug**
When you are invisible using the phantom origin, the wither storm can still see you, even though other mobs can't.

**To Reproduce**
1. Select Phantom Origin and Summon Wither Storm.
2. Enter phantom mode.
3. Wither Storm can still see you.

**Crash Reports / Logs**
None

**Screenshots**
None

**Comment by Birbman13** [comment]
Normal Mobs can still see you with phantom, so it makes sense that the witherstorm can too

**Comment by nonamecrackers2** [comment]
This would require and edge case since I assume the origin doesn’t use the invisibility effect.

**Comment by Asteroid4** [comment]
> This would require and edge case since I assume the origin doesn’t use the invisibility effect.

Yea, they don't use the invis effect.

**Comment by ShadeKage** [comment]
Maybe he just has good eye sight lol
No but for real this is a REALLY specific issue, unlikely to get changed for to foreseeable future
