### ISSUE TITLE
Mobs in blocks disappear when command block moves them up.

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#618]
**Minecraft version**
1.18.2

**Mod version**
2.1-pre.3

**Describe the bug**
When the command block in the bowels moves upwards, the mobs in the blocks making up the platform vanish.

**To Reproduce**
1. Hit command block in bowels
2. Mobs disappear

**Crash Reports / Logs**
None

**Screenshots**
![2022-09-11_20 25 37](https://user-images.githubusercontent.com/83736854/189555836-ede476e2-0fd8-4111-bc92-6823ab9b9dd2.png)
![2022-09-11_20 25 22](https://user-images.githubusercontent.com/83736854/189555839-475d3d46-e23f-4d47-86f9-7fce4e211373.png)

**Comment by nonamecrackers2** [comment]
Could you possibly attach a screenshot? I think I get what you mean but want to make sure.

**Comment by watersofnazareth** [comment]
I don't think this could easily be fixed because it uses blockstates

**Comment by Asteroid4** [comment]
Updated the original post and added the screenshots.

**Comment by nonamecrackers2** [comment]
Ah yeah. Interesting, will have to investigate.

**Comment by Asteroid4** [comment]
Btw how are the mobs currently being attached to the blocks? Is it using blockstates or is it position-dependent?

**Comment by watersofnazareth** [comment]
Closing this as mob statues are now a separate block

**Comment by myron-obsolete-account** [comment]
> Closing this as mob statues are now a separate block

wait they are? like, going to be in the next update? or already are? never seen them as seperate blocks.

**Comment by nonamecrackers2** [comment]
They’ll be coming in the next update
