### ISSUE TITLE
[Debris amount config option] Billions of blocks spinning around.

### ISSUE THREAD

**Issue by Minecraft1561645** [nonamecrackers2/crackers-wither-storm-mod#620]
![2022-09-11_18 09 46](https://user-images.githubusercontent.com/113301327/189537314-c3335ac8-0ed7-4c28-8ac0-2300c0ce1f64.png)
![2022-09-11_18 11 13](https://user-images.githubusercontent.com/113301327/189537325-7d7844a2-02da-4a4c-b0fb-add49a48f1ea.png)
![2022-09-11_18 12 31](https://user-images.githubusercontent.com/113301327/189537333-642fce79-8554-4ab5-ab7f-e0c74c038c0b.png)
![2022-09-11_18 14 30](https://user-images.githubusercontent.com/113301327/189537342-13231c73-0c41-485f-ac54-a941e30e23e5.png)
![2022-09-11_18 19 56](https://user-images.githubusercontent.com/113301327/189537348-8c5de6d7-6b5d-46a1-a059-2966c3b7945d.png)
![2022-09-11_18 23 26](https://user-images.githubusercontent.com/113301327/189537361-384cbc67-9111-4c9c-a5d0-d527a21ddb49.png)
![2022-09-11_18 48 35](https://user-images.githubusercontent.com/113301327/189537370-f7824b62-f8ea-4f79-ba3e-3e6119831989.png)
![xvcxc](https://user-images.githubusercontent.com/113301327/189537374-5d655791-32cf-4e2d-b077-0d12a55e3452.png)
You will make several times more blocks spin around the wither storm. There are so few of them that it seems that there are practically none. In the screenshots you can see how billions of blocks are spinning around the wither storm.

**Comment by RandomGithubUser32** [comment]
That will be very laggy for low-end devices.

**Comment by Minecraft1561645** [comment]
I have a 2009 processor and a 2016 graphics card. Simply put, outdated products.

But I am sure that there will be a very majority of people who have a 2018-2019 graphics card and a 2018 processor.

**Comment by RandomGithubUser32** [comment]
Maybe a config option for more blocks spinning around the wither storm.

**Comment by nonamecrackers2** [comment]
I could possibly add a config option to specify debris amount however making the default what is shown in the screenshots to me is quite excessive and performant intensive.

**Comment by Globalfirestorm10** [comment]
> ![2022-09-11_18 09 46](https://user-images.githubusercontent.com/113301327/189537314-c3335ac8-0ed7-4c28-8ac0-2300c0ce1f64.png) ![2022-09-11_18 11 13](https://user-images.githubusercontent.com/113301327/189537325-7d7844a2-02da-4a4c-b0fb-add49a48f1ea.png) ![2022-09-11_18 12 31](https://user-images.githubusercontent.com/113301327/189537333-642fce79-8554-4ab5-ab7f-e0c74c038c0b.png) ![2022-09-11_18 14 30](https://user-images.githubusercontent.com/113301327/189537342-13231c73-0c41-485f-ac54-a941e30e23e5.png) ![2022-09-11_18 19 56](https://user-images.githubusercontent.com/113301327/189537348-8c5de6d7-6b5d-46a1-a059-2966c3b7945d.png) ![2022-09-11_18 23 26](https://user-images.githubusercontent.com/113301327/189537361-384cbc67-9111-4c9c-a5d0-d527a21ddb49.png) ![2022-09-11_18 48 35](https://user-images.githubusercontent.com/113301327/189537370-f7824b62-f8ea-4f79-ba3e-3e6119831989.png) ![xvcxc](https://user-images.githubusercontent.com/113301327/189537374-5d655791-32cf-4e2d-b077-0d12a55e3452.png) You will make several times more blocks spin around the wither storm. There are so few of them that it seems that there are practically none. In the screenshots you can see how billions of blocks are spinning around the wither storm.

what the hell did you do to the tentacles

**Comment by Cgdihkg** [comment]
> > ![2022-09-11_18 09 46](https://user-images.githubusercontent.com/113301327/189537314-c3335ac8-0ed7-4c28-8ac0-2300c0ce1f64.png) ![2022-09-11_18 11 13](https://user-images.githubusercontent.com/113301327/189537325-7d7844a2-02da-4a4c-b0fb-add49a48f1ea.png) ![2022-09-11_18 12 31](https://user-images.githubusercontent.com/113301327/189537333-642fce79-8554-4ab5-ab7f-e0c74c038c0b.png) ![2022-09-11_18 14 30](https://user-images.githubusercontent.com/113301327/189537342-13231c73-0c41-485f-ac54-a941e30e23e5.png) ![2022-09-11_18 19 56](https://user-images.githubusercontent.com/113301327/189537348-8c5de6d7-6b5d-46a1-a059-2966c3b7945d.png) ![2022-09-11_18 23 26](https://user-images.githubusercontent.com/113301327/189537361-384cbc67-9111-4c9c-a5d0-d527a21ddb49.png) ![2022-09-11_18 48 35](https://user-images.githubusercontent.com/113301327/189537370-f7824b62-f8ea-4f79-ba3e-3e6119831989.png) ![xvcxc](https://user-images.githubusercontent.com/113301327/189537374-5d655791-32cf-4e2d-b077-0d12a55e3452.png) You will make several times more blocks spin around the wither storm. There are so few of them that it seems that there are practically none. In the screenshots you can see how billions of blocks are spinning around the wither storm.
> 
> what the hell did you do to the tentacles

It's just a lot of wither storms to have a lot of blocks in one position and it turned out like this

**Comment by Globalfirestorm10** [comment]
ah ok
