### ISSUE TITLE
Tentacle attacks 

### ISSUE THREAD

**Issue by Cgdihkg** [nonamecrackers2/crackers-wither-storm-mod#621]
I know this has been suggested many times before. But the author, experiment with the tentacle attack, maybe in some ways it will turn out perfectly? Who knows? I think this is one of the features that should be in fashion. Let the tentacles have three types of attack: 1. Picks you up and carries you to the head that eats, 2. A simple tentacle attack, 3. Squeezes, causing damage. And it will also be possible to fight off the tentacles, as from the head. If you add tentacles to the mod, it will be a full-fledged wither storm. Or at least implement a simple tentacle attack.

**Comment by nonamecrackers2** [comment]
#12
