### ISSUE TITLE
Randomization of how fast entities get pulled in the tractor beam and the speed of flaming skulls

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#624]
There were many scenes in story mode where things in the tractor beam get pulled in at different speeds along with this flaming wither skulls also had different speed when there were fired, here are some examples

During the wither storm chase scene with the horses, if jesse went into the tractor beam he/she would get pulled in very fast
During the introduction of phase 4 in the first episode the tractor beam pulled in people and blocks at a quick rate
During the forest chase scene in episode one the flaming skulls were fired at extreme speeds.
During the part where you crafted the formidbomb the tractor beam pulled jesse and items at a slow rate

Options concept
Max speed of tractor beams.
Max speed of wither skulls.

**Comment by nonamecrackers2** [comment]
Small randomization on how fast the mobs get pulled has been implemented, a config option also has been added for the speed of flaming skulls
