### ISSUE TITLE
Small Hole in Phase 6 Model

### ISSUE THREAD

**Issue by GoldSlimeling91** [nonamecrackers2/crackers-wither-storm-mod#625]
**Minecraft version**
1.19

**Mod version**
3.0 beta

**Describe the bug**
In early Phase 6, the wither storm has a hole in the right side of it's model, this is pretty minor because it is usually not seen in normal gameplay but just wanted to say it's there

**Screenshots**
![2022-09-14_15 48 44](https://user-images.githubusercontent.com/111310936/190250210-bd9d2fc6-2910-4126-9e85-3fc09c18b817.png)
![2022-09-14_15 48 36](https://user-images.githubusercontent.com/111310936/190250222-81f3a743-4fb4-407b-bec0-ca183569b101.png)

**Comment by Asteroid4** [comment]
I noticed it too.

**Comment by Bloxxify2827** [comment]
Crackers called it a “small easter egg” so hes probably going to keep it

**Comment by GoldSlimeling91** [comment]
oh ok

**Comment by BluePineappleGuy** [comment]
Just found this, literally unplayable
