### ISSUE TITLE
You should add witherstorm theme 2

### ISSUE THREAD

**Issue by Hiuui** [nonamecrackers2/crackers-wither-storm-mod#627]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Bloxxify2827** [comment]
Why did you close it

**Comment by TheSrBig** [comment]
what is the theme, upload the link of yt

**Comment by nonamecrackers2** [comment]
#227

**Comment by Hiuui** [comment]
https://www.youtube.com/watch?v=WvZ3hwwRSkY

**Comment by Hiuui** [comment]
Close what

**Comment by Hiuui** [comment]
https://www.youtube.com/watch?v=WvZ3hwwRSkY Watch the vid
