### ISSUE TITLE
Eliminate Crafting Table when crafting the Formidi Bomb

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#628]
good day, I have seen that in the original series, both in the video game and in the netflix version, at the time of craftear the formidibomb with the super tnt, the formidibomb is created but at the time of craftearla eliminates or disappears the crafteo table with which crafteo, I leave a GIF where you see this
![bloggif_63227ee98902f](https://user-images.githubusercontent.com/89810837/190292332-8dc65bf9-ad44-47a5-8e41-abd3aa5dd700.gif)

https://user-images.githubusercontent.com/89810837/190292341-6d728554-e34b-4bd4-bbdc-7a6512da656e.mp4

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/322

**Comment by TheSrBig** [comment]
> Esto se sugirió antes, pero no puedo encontrar esa sugerencia.

I have not seen that, I have checked the others.

**Comment by RandomGithubUser32** [comment]
It is closed btw

**Comment by TheSrBig** [comment]
> Está cerrado btw

and what do you want me to do, let an admin answer me please.

**Comment by TheSrBig** [comment]
ok, but now it is not enceasrio that is placed at the time of craftearse, only that breaks the crafting table and so far, plus you can crafte easily, only 4 planks of wood, I do not think it's a big change, also can not check "nonamecrackers2" that can be confused other people
