### ISSUE TITLE
Aternos Server Commands

### ISSUE THREAD

**Issue by OliversIntention** [nonamecrackers2/crackers-wither-storm-mod#629]
(1.19.2)

I made a server (Aternos) and I op'd myself, but I still cannot configure world commands etc, any help?

**Comment by GrandmaPork** [comment]
If you’re trying to access the config files for this mod then you should talk to your server provider

**Comment by OliversIntention** [comment]
I am the server provider, and I do have access to the server files. I just need to know how to do it.

> If you’re trying to access the config files for this mod then you should talk to your server provider

**Comment by OliversIntention** [comment]
Btw this is Crackers wither storm mod.

**Comment by GrandmaPork** [comment]
Which commands specifically do you want to use? Summon/kill commands and like grow commands?

**Comment by OliversIntention** [comment]
No, I can use that using Operator Commands. There's a list of server owner only options in the settings menu that I am trying to reach. Client Settings are for everyone. Screenshot: https://gyazo.com/68ef42a4067de5e7245087a26e69987d

**Comment by nonamecrackers2** [comment]
You need to go to where your "world" folder is, then "serverconfig" then edit "witherstormmod-server.toml"

**Comment by OliversIntention** [comment]
Thank you very much, this worked.
