### ISSUE TITLE
Purple areas in the Wither Storm in phases 6 and 7

### ISSUE THREAD

**Issue by Gaboamau** [nonamecrackers2/crackers-wither-storm-mod#63]
I've seen that in Minecraft: Story Mode, when the Wither Storm comes back to life after being destroyed by the Formidibomb, the Wither Storm segments, or the Wither Storm itself, in some parts, you can see a bright purple color as if it were the blood of the Wither Storm, as seen in the image. Maybe you can include it in the mod in a future update.

![image](https://user-images.githubusercontent.com/106891155/172038657-d4de0b5a-f6e5-478a-b180-e966efac6328.png)

**Comment by Abasthepro** [comment]
Yeah it's cool

**Comment by KrukAdrian** [comment]
Hope this gets added, cuz this is totally cool

**Comment by Resuster** [comment]
are u gonna add that cracker?

**Comment by myron-obsolete-account** [comment]
appears this is implemented

**Comment by Laughingcat27** [comment]
victory
