### ISSUE TITLE
Tentacles in final boss have infinite range/ fight over who grabs the player

### ISSUE THREAD

**Issue by ShadeKage** [nonamecrackers2/crackers-wither-storm-mod#630]
**Minecraft version**
1.18.2

**Mod version**
2.0.1.2

**Describe the bug**
The tentacles in the final boss seem to have infinite range, or just a really long one, for unknown reasons, this causes several issues such as
- The platform tentacles constantly slapping the nearest player even when they are on the ground, the roof, literally anywhere within the bowels fight area
- In the grabbing phase where the other tentacles try grabbing players, they all try to pick up the player at the same time, causing the player to snap rapidly between them all, causing possible epilepsy issues (similar to if you mass TPed someone around the room with commands)

**To Reproduce**
1. Go to the listed version of game and mod
2. Go into storm bowels
3. Begin the boss fight in survival

**Crash Reports / Logs**
NA, This didnt crash the game 

**Screenshots**
I cant really screenie it due to it all being so quick, I'd look like a normal boss fight image, sorry :/

P.S. Im on discord in the server if you need more info on this bug or other ones ive seen you can message me lol
Shade Kage#8470

**Comment by nonamecrackers2** [comment]
Do you happen to have any other mods?

**Comment by watersofnazareth** [comment]
This is caused by other mods, I can't recall which one though @nonamecrackers2

**Comment by nonamecrackers2** [comment]
Could possibly be some mod that messes with attributes which is the only thing that I can think of that would affect the tentacles.

**Comment by watersofnazareth** [comment]
Must be something that affects their aggro range maybe Farsighted Mobs?

**Comment by nonamecrackers2** [comment]
Possibly. Need more info from OP

**Comment by ShadeKage** [comment]
Oh! if its caused by sight range, then uh.. yea.. I had some other mods, sorry!
I had a mod installed that adds extra sight range to mobs, didn't know thats how the tentacles were coded

**Comment by nonamecrackers2** [comment]
Ah that makes sense.
