### ISSUE TITLE
1.16.5 1.0.2.4 Wither sickness layer glitches with epic fight animations

### ISSUE THREAD

**Issue by Joshowa5** [nonamecrackers2/crackers-wither-storm-mod#633]
**Minecraft version**
1.16.5 but you will probably have the same bug on later versions but i don't rly know because i cant use 1.18+

**Mod version**
1.0.2.4

**Describe the bug**
the wither sickness layer doesn't work properly with epic fight animations

**To Reproduce**
1. install epic fight mod
2. Get infected with a almost fatal disease called "Wither Sickness"

**Screenshots**
![Screen Shot 2022-09-19 at 6 11 26 AM](https://user-images.githubusercontent.com/113861249/190930011-fc6ebe6b-8d0b-4acb-8bd0-4739eb3f8529.png)
![Screen Shot 2022-09-19 at 6 11 10 AM](https://user-images.githubusercontent.com/113861249/190930013-73341a89-f3d7-401f-8334-11a47fec0348.png)
first person:
![2022-09-19_06 10 02](https://user-images.githubusercontent.com/113861249/190930098-21c9dbc2-26f8-468e-99b4-e1b580feabdd.png)

**Comment by Globalfirestorm10** [comment]
known bug, epicfight is shit when it comes to compatibility

**Comment by nonamecrackers2** [comment]
Yeah this does not seem easily fixable. Epic fight's player model modifications don't make it to the wither sickness layer, which effectively re-renders the player model with the wither sickness overlay as the texture. There isn't anything I can really do on my end.

**Comment by guivnf** [comment]
> Yeah this does not seem easily fixable. Epic fight's player model modifications don't make it to the wither sickness layer, which effectively re-renders the player model with the wither sickness overlay as the texture. There isn't anything I can really do on my end.

Actually there is, epic fight makes changes to the player model and it uses a system to translate cube models into triangle ones so it allows for bends. If you want to patch armor models, not sure how the sickened layer is written, but you can in fact fix the vertex groups inside of a program of your choice and export these json models and add in a patch between both mods. Theres a tutorial being worked on on the epic fight wiki, but it's beeing constantly updated and you can learn how to do this in blender pretty easily. I'm the current maintainer of the epic fight mod, and i would gladly help you out in any issues regarding this overlay.

**Comment by nonamecrackers2** [comment]
Alright thanks for reaching out, I'll look into it further
