### ISSUE TITLE
Possible to make clusters make there "shaking" sound before moving toward the wither storm?

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#636]
**Description of feature**
Title.

**Comment by watersofnazareth** [comment]
Been recommended already #121

**Comment by watersofnazareth** [comment]
In fact it's implemented for the next update

**Comment by Luke7381** [comment]
> Been recommended already #121

It doesn't mention that the clusters make a shaking sound before being picked up by the storm.

**Comment by nonamecrackers2** [comment]
I've added the shaking but not the sound

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
