### ISSUE TITLE
More accurate Super TNT texture

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#637]
In minecraft story mode, instead of just having the black letters "TNT", the letters actually "glowed" as if filled with lava. Here is a more accurate texture that I made.

[super_tnt_side.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9639099/super_tnt_side.zip)

**Comment by watersofnazareth** [comment]
I prefer the plain black text in all honesty

**Comment by RandomGithubUser32** [comment]
okay sure

**Comment by RandomGithubUser32** [comment]
okay sure

**Comment by Globalfirestorm10** [comment]
honestly, you should reopen this, i'd love to see the super tnt block glow

**Comment by RandomGithubUser32** [comment]
Okay, I guess that I will reopen this to see what everyone thinks about this.

**Comment by nonamecrackers2** [comment]
You could totally do this with a resourcepack. Would look cool but doesn't need to be changed in the base mod.
