### ISSUE TITLE
3.0

### ISSUE THREAD

**Issue by Cgdihkg** [nonamecrackers2/crackers-wither-storm-mod#638]
When will version 3.0 be released? There have been no updates for at least 2 months.

**Comment by Globalfirestorm10** [comment]
Very soon When it's ready, be patient, Crackers has other stuff in his life to deal with

**Comment by Globalfirestorm10** [comment]
also this isn't a suggestion

**Comment by Luke7381** [comment]
At max its gonna be October, but there is a chance of it being before that.
