### ISSUE TITLE
Bug/inconsistency in Tainted Mushroom

### ISSUE THREAD

**Issue by El-Glider800** [nonamecrackers2/crackers-wither-storm-mod#639]
**Minecraft version**
1.19

**Mod version**
1.19 Minecraft

**Describe the bug**
The player is unable to place the tainted mushroom in to pots, while other mushroom can.

**To Reproduce**
1. Go to 'a pot'
2. Right click on 'pot with tainted mushroom in hand'
3. See error

**Comment by watersofnazareth** [comment]
This is more of a suggestion than a bug

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
