### ISSUE TITLE
Texture glitch with glowing item frame 

### ISSUE THREAD

**Issue by El-Glider800** [nonamecrackers2/crackers-wither-storm-mod#640]
**Minecraft version**
1.19

**Mod version**
1.19 Minecraft

**Describe the bug**
The glowing item frame when placed look like a normal item frame 

**To Reproduce**
1. Go to 'a block'
2. Right click on 'Block with glowing item frame in hand'
3. See error

**Comment by watersofnazareth** [comment]
Could you explain this in more detail?

**Comment by nonamecrackers2** [comment]
Closing until more information is given
