### ISSUE TITLE
Having the Wither's sky effect world wide when Wither Storm is active

### ISSUE THREAD

**Issue by Elizriel** [nonamecrackers2/crackers-wither-storm-mod#642]
When summoning a Wither, weither a normal one or the Wither Storm, there is a sky effect that is used (it basically slightly darkens the horizon).

As of now, it only appears at the same range the Bossbar, but I was wondering if it was possible to make the sky effect appear either world wide or in the entire Wither Storm's distant renderer radius (10000 blocks) while the latter is active and roaming.

**Comment by nonamecrackers2** [comment]
I don't think it should darken the sky globally as it really only happens because the mass of the storm is blocking light from the sun.
