### ISSUE TITLE
Pulling players out of the tractor beam

### ISSUE THREAD

**Issue by Joshowa5** [nonamecrackers2/crackers-wither-storm-mod#643]
**Description of feature**
Add an option to pull players out of the tractor beam (like in mcsm) where you can hold right click and pull them until the witherstorm looks away and it should also randomly pull you while trying to pull other players, it can be a good but hard and dangerous early game alternative to fireworks as your friends might not be able to deal enough damage because they have no armour to keep hitting the storms head with a sword until it lets go and on the hunchback phases its extremely hard to survive once it pulls you, so there would actually be more reasons to actually bring friends to play with you, but this should have a config and should be disabled by default as alot people probably have a different opinion and might want to play the mod without it

**Comment by Joshowa5** [comment]
also why am i having a seizure whilst reading my own suggestion

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/255

**Comment by Joshowa5** [comment]
oh i didnt see that because it was like 4 months ago srry

**Comment by RandomGithubUser32** [comment]
You should try to search for issues instead of scrolling through them.
