### ISSUE TITLE
Floating lights on the storm

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#646]
1.18.2
2.1

the lights that  appear on the storm when blocks are taken off. are just randomly floating all over the storm.
it looks weird asf
![2022-09-26_12 22 03](https://user-images.githubusercontent.com/109059241/192181508-9bc3180a-b378-48bf-a73f-22bf93d2b928.png)
![2022-09-26_12 22 07](https://user-images.githubusercontent.com/109059241/192181512-3476a45f-b463-44fd-a804-901221d17569.png)
![2022-09-26_12 22 15](https://user-images.githubusercontent.com/109059241/192181517-73399452-9e22-4d0d-ab8f-e00b9814cd37.png)
![2022-09-26_12 22 25](https://user-images.githubusercontent.com/109059241/192181521-d88c34a3-2d82-4af9-b610-bd8b8867cb68.png)

**Comment by ghost** [comment]
ignore the clouds

**Comment by nonamecrackers2** [comment]
Is this with flywheel enabled? Also what's your client config set to?

**Comment by ghost** [comment]
yes. the config is set too high.

**Comment by nonamecrackers2** [comment]
Can't reproduce. If you can provide reliable steps to reproduce this that would be helpful.
