### ISSUE TITLE
Block Clusters appearing as completely black

### ISSUE THREAD

**Issue by V0calgiant12** [nonamecrackers2/crackers-wither-storm-mod#647]
**Minecraft version**
1.18.2

**Mod version**
2.1

**Describe the bug**
Block clusters appear to be turning black from the second they are made, with and without Block Cluster Coloring. A reload of the world doesnt fix it, nor does quitting out to

**To Reproduce**
1. Create a new world
2. Summon a witherstorm
3. Bring the storm to stage 4 because it is easier to see.
4. Watch as the block clusters turn completely black from the moment they are created to the moment they are at the storm.

**Screenshots**
![2022-09-25_19 02 43](https://user-images.githubusercontent.com/109500471/192180014-4e8ce4e0-5390-45cb-8404-e954a3bbffed.png)
![2022-09-25_19 02 23](https://user-images.githubusercontent.com/109500471/192180097-7e0c5b74-8c18-4e9d-bed8-cb8fa6dc17e8.png)
![2022-09-25_19 02 33](https://user-images.githubusercontent.com/109500471/192180101-41ff6a39-65c9-49ed-b835-970b50994e36.png)
![2022-09-25_19 02 41](https://user-images.githubusercontent.com/109500471/192180135-da148812-f177-4f51-a342-be1b73494a1d.png)

**Comment by nonamecrackers2** [comment]
What's your modlist and client config configured to?

**Comment by V0calgiant12** [comment]
I did originally notice it in my own modpack, but after words I tested it out with only the mod and it still happened.
But here's my client config:
Render Debris Cloud: On
Render Debris Rings: Off
Render 2D Debris: Off
Render Distant Debris Cloud: On
Render Segment Debris: Off
Lower Debris Resolution with Phases: On
Wither Storm LOD: On
Low Res Models: Off
Render Tractor Beams: On
Render Pulse: On
Distant Renderer: On
Block Cluster Rendering: On
Wither Sickness Layer: On
Play Boss Themes: On
Chromatic Aberration: On
Blinding Effects: On
Camera Shake Effects: On
Distant Fog: On
Block Cluster Rendering: On (but like I said, this has no effect on the bug)
Ear Ringing Effects: On
Render Tractor Beam Overlay: On
Sky Ambience Effects: On
Tractor Beam Particles: On

**Comment by V0calgiant12** [comment]
I made an interesting discovery: when you fly far away from the storm (far enough for the sky to turn completely back to normal), it'll sometimes half fix it, but not fully. as seen in these screenshots that I attached. 
It also seems to appear with proper coloring on alternating sides of the WS (left and right) but which side has it seems to change based on what the WS's rotation is.

![2022-09-26_01 29 55](https://user-images.githubusercontent.com/109500471/192232289-82bbd8a8-ed67-4a60-b769-99d295d2ab37.png)
![2022-09-26_01 30 07](https://user-images.githubusercontent.com/109500471/192232246-7ac82641-dc0d-496d-b4ab-e42b4dc60e5a.png)
![2022-09-26_01 43 13](https://user-images.githubusercontent.com/109500471/192233081-0a2c2f6d-db8c-4965-aedb-845809b717e9.png)

**Comment by nonamecrackers2** [comment]
And this is without Flywheel?

**Comment by V0calgiant12** [comment]
Happens with and without.

**Comment by nonamecrackers2** [comment]
Interesting. I'll have to investigate further.

**Comment by watersofnazareth** [comment]
Optifine maybe?

**Comment by V0calgiant12** [comment]
No optifine. A completely vanilla client with only the WS mod installed. If it helps, I'm on forge 40.61.0 (or whatever version has 61 in it, I can't remember the forge version layout lol)

Besides, I like Sodium/Oculus (a forge port of Sodium) better. (it also doesn't have any compat issues with a lot of mods that have compat issues with Rebuddium)

**Comment by nonamecrackers2** [comment]
Forge version may be why. I’ll have to test it out though

**Comment by V0calgiant12** [comment]
interesting, I restarted my computer as some point and its not doing it anymore. Might have been an issue with my pc. Im gonna ask the other guy that made an issue on this what their specs were so I can compare theirs to mine because that might have been the issue.

**Comment by V0calgiant12** [comment]
it was not the issue, i wonder what caused it, hm.

**Comment by nonamecrackers2** [comment]
I managed to find the problem. It's due to block clusters checking light levels around world origin (0, 0, 0). Since those blocks are usually covered, it returns dark light levels making the clusters pitch black.

**Comment by V0calgiant12** [comment]
ohhhh, interesting, that explains why it stopped happening in a different world

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update.

**Comment by V0calgiant12** [comment]
Sweet
