### ISSUE TITLE
Low resolution models setting doesn't change the wither storm model

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#648]
**Minecraft version**
1.18.2

**Mod version**
2.1

**Describe the bug**
Low resolution models isn't working

**To Reproduce**
1. Go to client settings
2. turn on low resolution models
3. spawn in wither storm phase 4+

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/48260861/192186982-0383822a-980f-4573-a6f5-a9494070a5dd.png)
![image](https://user-images.githubusercontent.com/48260861/192186990-08e05f22-a168-46fa-99be-781c439b2eb5.png)

**Comment by nonamecrackers2** [comment]
If you have flywheel installed this is intended.

**Comment by Asteroid4** [comment]
> If you have flywheel installed this is intended.

Wait, why is that?

**Comment by Luke7381** [comment]
> If you have flywheel installed this is intended.

Why is that intended?

**Comment by nonamecrackers2** [comment]
Since Flywheel increases performance of the model there's no need to use the low resolution ones. If you prefer the low res ones over the main ones stylistically you should make a new issue to request that as a feature.
