### ISSUE TITLE
Going forward 

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#649]
This isn’t a feature but rather a question. Amazing to see what you were able to add in this recent update. I’ve noticed that you’ve marked some feature requests as “game changing” and “unlikely”. When it comes to game changing, will this be something you’re willing to accomplish or just a mark that means it will be too difficult to bother with. With that being said, how should I look at updates in the future. Will they mostly be small bug fixes with a few content updates? Just curious, can’t wait to try the new update out!

**Comment by watersofnazareth** [comment]
Ask this on Discord not github

**Comment by nonamecrackers2** [comment]
For the labels, they're really meant for organization. If you look at the description for "game changing," it's a "[s]uggestion that may change the way players interact and use the mod." It could be a small tweak or feature addition. I use "unlikely" for features I don't really think fit in or are possible.
