### ISSUE TITLE
Amulet with a natural generation

### ISSUE THREAD

**Issue by Howareyoouu** [nonamecrackers2/crackers-wither-storm-mod#651]
**Improvements to the amulet for survival**
I suggest that the amulet instead of being only creative and doesn’t have a use except for multiplayer server that you can find it in the rundown house it’s loot is bad right now and would make a reason for opening chests. When you grab it you are not going to be able to drop it or lose it even after death it works like the wither sickness. It would have the same use as right now for multiplayer and would make you able to get it in survival. If you are playing in single player this would at least serve as a trophy after defeating the wither storm and being able to drop it.

**Comment by watersofnazareth** [comment]
#475
