### ISSUE TITLE
Settings descriptions is broken/overlapping

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#652]
**Minecraft version**
1.18.2
**Mod version**
2.1 (also was in 2.0)
**Describe the bug**
When hovering over most settings it shows some other settings description, its even worse when scrolling down.

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is Flywheel's optimizations active?**
yes, but this doesn't look like something related to flywheel.

**Screenshots**
![image](https://user-images.githubusercontent.com/48260861/192390971-4004f158-5c02-469a-a1f3-8ca7a278e5a7.png)
![image](https://user-images.githubusercontent.com/48260861/192391002-3eec4efd-2ca1-45f8-9808-f5bcd2f12727.png)
![image](https://user-images.githubusercontent.com/48260861/192391034-5fbaa8ec-14fb-4bc1-b9bb-18de28f0676b.png)
![image](https://user-images.githubusercontent.com/48260861/192391166-30385933-a551-44b1-be57-54c38380fb9d.png)
![image](https://user-images.githubusercontent.com/48260861/192391188-33466885-fbc4-4d8f-ae0c-570849944d83.png)
![image](https://user-images.githubusercontent.com/48260861/192391355-45890c0a-46fb-4222-8e22-42cbda112fab.png)
![image](https://user-images.githubusercontent.com/48260861/192391370-8f36e2be-5f56-4933-991c-06eaccc4e004.png)
Supposed to be till show hole
![image](https://user-images.githubusercontent.com/48260861/192391477-4a009eab-3ee6-4fde-8563-c629a39df847.png)
Supposed to be minimum distraction distance
![image](https://user-images.githubusercontent.com/48260861/192391713-c4d859b4-78da-4727-8dce-94dd3cd64015.png)

**Comment by nonamecrackers2** [comment]
Are you using the scrollbar to scroll? This happened to me I believe but I dismissed it since I couldn't properly reproduce it.

**Comment by Luke7381** [comment]
> Are you using the scrollbar to scroll? This happened to me I believe but I dismissed it since I couldn't properly reproduce it.

No i was using scroll wheel.

**Comment by nonamecrackers2** [comment]
Hmm interesting. This may be a bug with MC in general but I'll take a look.

**Comment by nonamecrackers2** [comment]
Managed to find the issue, but not sure on how to fix it. It appears to be an MC bug. For those wanting to reproduce it, going into windowed mode, then the server/client config and using the scrollbar to the very bottom then hovering over a config option produces the problem. Not sure how you've reproduce it via the scroll wheel though.
