### ISSUE TITLE
Camera shaking no longer occurs in bowels

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#653]
**Minecraft version**
1.18.2
**Mod version**
2.1
**Describe the bug**
The camera shaking that used to happen in the bowls no longer occur anymore, and i have camera shaking on.

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is Flywheel's optimizations active?**
yes

**Screenshots**

**Comment by Luke7381** [comment]
Nevermind apparently its due to view bobbing being turned off.

**Comment by nonamecrackers2** [comment]
That would make sense
