### ISSUE TITLE
Spyglass achievement works with more items than it should

### ISSUE THREAD

**Issue by theemeraldsword85** [nonamecrackers2/crackers-wither-storm-mod#654]
**Minecraft version**
1.19.2

**Mod version**
3.1

**Describe the bug**
You can use other items to activate the "Is it the end?" advancement than just spyglasses.

**To Reproduce**
1. Take a look the witherstorm, and use any item that activates with right click. (Bow, shields, potions, trident, etc.)
2. It will give you the advancement... I don't think this was intended!

**Crash Reports / Logs**
It doesn't cause a crash, obviously.

**Is Flywheel's optimizations active?**
I do not have flywheel installed.

**Screenshots**

![2022-09-26_17 13 49](https://user-images.githubusercontent.com/114451543/192404098-c57db939-fb0a-4da7-a67b-703eec4473a5.png)

![2022-09-26_17 29 25](https://user-images.githubusercontent.com/114451543/192404326-8eb00f3b-ad02-451f-abc4-f927edf9d51f.png)

**Comment by FrozenDragon0** [comment]
I've also had this advancement unlock on it's own after I looked at the WS house from around 200 blocks away and yet the storm wasn't even active.

**Comment by nonamecrackers2** [comment]
Fairly certain this is just 1.19 so I'll remove the 1.18 label for now

**Comment by watersofnazareth** [comment]
It does affect 1.18.2

**Comment by RandomGithubUser32** [comment]
Also works with food items and potions

**Comment by theemeraldsword85** [comment]
oops
sorry about that

**Comment by nonamecrackers2** [comment]
Interesting. Thought it would be just 1.19 since I haven’t experienced it at all in my 1.18 testing

**Comment by nonamecrackers2** [comment]
Will be fixed in the next release.
