### ISSUE TITLE
holes in witherstorm model phase 6 allowing the player to see inside the witherstorm

### ISSUE THREAD

**Issue by personmhmyes** [nonamecrackers2/crackers-wither-storm-mod#655]
it is in all versions of the mod and minecraft
when witherstorm is in phase 6 you can see inside of it because of 2 holes 

its is on the right side of it if it was facing directly at you

![delete after this](https://user-images.githubusercontent.com/109728651/192413645-50997277-9a13-45a1-8743-c2e2066e27bb.png)

![image](https://user-images.githubusercontent.com/109728651/192414036-5d850943-5d54-4ecc-b07a-272d3849bb12.png)

**Comment by watersofnazareth** [comment]
#625
