### ISSUE TITLE
Flywheel issue (Mass of the storm not flashing red when taking damage)

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#657]
**Mod version**
1.18 newest release

**Describe the bug**
When the wither storm is set as vulnerable, the mass of the wither storm does not seem to "take" damage. This is probably because the models for the mass of the storm are different. However, the mass of the wither storm does "take" damage when the storm dies.

**To Reproduce**
1. Config the wither storm be able to take damage
2. Shoot the wither storm with a bow (must be in phases 4+)
3. See error

**Is Flywheel's optimizations active?**
Specify if Flywheel is installed and it's compat optimizations are enabled
Yes this only happens when flywheel is enabled

**Screenshots**
![2022-09-27_01 03 29](https://user-images.githubusercontent.com/109647302/192437250-7b25fd32-b735-4c7a-9ef2-bbced449fbe9.png)

**Comment by watersofnazareth** [comment]
This is just due to how Flywheel is rendering the model, I don't think it's actually possible for this to be fixed

**Comment by RandomGithubUser32** [comment]
Okay sure but I am still confused why the mass still renders damage when the wither storm dies but not when the storm takes damage.

**Comment by watersofnazareth** [comment]
Because the death animation isn't using flywheel from what I know

**Comment by nonamecrackers2** [comment]
Yeah, death animation isn't Flywheel optimized by default. As pointed out not sure if I can fix it but I'll take a look.
