### ISSUE TITLE
Spyglass advancement bug

### ISSUE THREAD

**Issue by Mettod99** [nonamecrackers2/crackers-wither-storm-mod#658]
**Minecraft version**
1.19.2

**Mod version**
3.1

**Describe the bug**
Spyglass advancement unlocks when you target the wither storm by bow.

**To Reproduce**
1. Summom the wither storm.
2. Take your bow.
3. Aim the wither storm.

**Screenshots**
![2022-09-27_17 48 29](https://user-images.githubusercontent.com/86322378/192573316-99ea344f-2fd7-4138-9892-926cdddf63cc.png)

**Comment by Mettod99** [comment]
Just realized someone already reported this... whoopsie

**Comment by Globalfirestorm10** [comment]
Close this issue
