### ISSUE TITLE
Config Option for Structure

### ISSUE THREAD

**Issue by SamuelRUM** [nonamecrackers2/crackers-wither-storm-mod#659]
Hello! Really love the mod so far, and I'm trying to create a modpack where the wither storm is the final boss. I have a recipe with crafttweaker for the commandblock itself which requires beating various other bosses and is very expensive.  The only problem I have right now is that I want to gate the boss fight, instead of it being able to be obtained by going to the strucutre.

As such, my future request would be for in the future to add a config option that disables either the structure entirely, or the commandblock in the wither structure itself. That way modpack makers like me can utilize the mod in a distinct way.

**Comment by Globalfirestorm10** [comment]
well, that would kind of defeat the purpose of a "wither storm mod", since the structure contains the summoner for it, but this could be solved via /give or creative

**Comment by SamuelRUM** [comment]
Wait so you are saying you can't summon the storm if it's not on the structure itself?

**Comment by watersofnazareth** [comment]
#41
#170

**Comment by nonamecrackers2** [comment]
1.18.2+ removed the config option due to structure changes that makes it possible to disable structures via datapacks.

**Comment by Globalfirestorm10** [comment]
> Wait so you are saying you can't summon the storm if it's not on the structure itself?

Yes, unless you use /summon or make the summoning structure in creative mode, the summoning platform was the entire reason the house exists

**Comment by SamuelRUM** [comment]
Well, I managed to find a work around by making a quest that summons the wither storm by turning in the craftable command block, apart from the house.  But just to be clear (cause I want to know how it works) does it need the entire structure of the house to summon or just the top platform? how does that work in the program? why can you not register the wither storm structure as just the wither summon shape itself? (Im not trying to be snobby I promise I just want to know 😓).

**Comment by Asteroid4** [comment]
You don't need the house as long as you can place down command blocks. I think he meant only using this mod and vanilla minecraft, its not possible. If you use the mod Placeable Command Blocks, it works for me.
