### ISSUE TITLE
Update to the Spanish language

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#660]
good day, I have tried the update of "The Sky Darkness" and I love it, the only problem I see is the translation, I am a speaker of Spanish Mexico, I live in Mexico and that's why haha, and the translation to that language is terrible, there are words that sometimes I do not see sense because they lack words, you can tell that the guy who translated them, use a translator, I as a speaker of the language is noted, now I practice English, so it would be easy for me to translate several words, as some if they are well translated, now another thing, I have several friends from other countries who speak Spanish-Chile, Argentina and others, and probably update the language of their countries, well, you as administrators decide this, I hope your answer.

**Comment by watersofnazareth** [comment]
The languages are usually all fan-made, so if you wanna take a crack at improving it you're more than welcome to

**Comment by nonamecrackers2** [comment]
Pretty much all of the Spanish translations stem from one single file and are simply placeholders, as said by the translator. Not a Spanish speaker, so not sure if that’s the problem here but if you feel they need to be improve I fully welcome you to update them.

**Comment by TheSrBig** [comment]
Well, each language in escaño has a different name for each block such as "madera, "tablas, "tablones", "vallas", "cercas", and if I want to improve them, where would I send them?

**Comment by TheSrBig** [comment]
> Pretty much all of the Spanish translations stem from one single file and are simply placeholders, as said by the translator. Not a Spanish speaker, so not sure if that’s the problem here but if you feel they need to be improve I fully welcome you to update them.

Well, each language has a different name for each block such as "madera, "tablas, "tablones", "vallas", "cercas", and if I wanted to improve them, where would I send the files?
