### ISSUE TITLE
Physical darkening of the sky

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#662]
When the wither storm darkens the sky, it would be cool if it was not just visual but allowed hostile mobs to not burn in the sun as well as maybe even having the mobs spawn in the day. This is shown in a scene in the day where all sorts of hostile mobs run away from the wither storm.

**Comment by watersofnazareth** [comment]
This would be really weird in game and also wouldn't really be noticeable, you can use mods like mob sunscreen if you want

**Comment by RandomGithubUser32** [comment]
Maybe if mobs spawned during the day as well it would be noticeable.

**Comment by nonamecrackers2** [comment]
I don’t really want to mess with mob spawns at the moment but I could potentially revisit this in the future.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
