### ISSUE TITLE
(1.18.2) wither storm looses its body when exiting the nether when wither storm is nearby

### ISSUE THREAD

**Issue by mmiller9196** [nonamecrackers2/crackers-wither-storm-mod#663]
1.18.2

when I detonated the wither storm, the wither storm lost its body when it reanimated
(edit): this actually happens only when you exit from the nether when the wither storm is nearby, so this is a bug with the nether portal and rendering the wither storm
![2022-09-28_02 11 55_2](https://user-images.githubusercontent.com/110945774/192713149-42cda00e-6ea5-4534-b16c-a92ad4a2f04f.png)

**Comment by Globalfirestorm10** [comment]
Send your mod list here

**Comment by watersofnazareth** [comment]
This is due to Flywheel, not really a bug just reload your chunks

**Comment by mmiller9196** [comment]
> This is due to Flywheel, not really a bug just reload your chunks

Great, thanks
