### ISSUE TITLE
You have to be incredibly close to the Wither Storm for it to function

### ISSUE THREAD

**Issue by aaronhowser1** [nonamecrackers2/crackers-wither-storm-mod#664]
**Minecraft version**
1.18.2

**Mod version**
witherstormmod-1.18.2-2.1

**Describe the bug**
You have to be much closer to the Wither Storm than I would expect for it to work. If you're where the beams are aimed, it's unloaded, and doesn't do anything. For the tier 7, if you're being sucked in by the middle heads, the outer ones are unloaded. This means for it to actually progress the evolution, so it opens the portal, you basically have to be inside it the entire time with enough armor to not be killed.

**To Reproduce**
Be near the Wither Storm, but not extremely

**Is Flywheel's optimizations active?**
Specify if Flywheel is installed and it's compat optimizations are enabled
Flywheel is installed with these configs:
```
#Flywheel compat
	[client."flywheel compat"]
		#DEFAULT=true. Specifies if CWSM compat with Flywheel should be enabled or not. NOTE: disabling will prevent the performance boosts from taking effect. Only disable if facing issues. Reload Type: GAME
		flywheelCompatEnabled = true
		#DEFAULT=false. Specifies if block clusters should be instanced. NOTE: Block biome colors do not work with block clusters (e.x. leaves/grass will be white). Reload Type: GAME
		blockClusterInstancing = false
		#DEFAULT=false. Specifies if the Wither Storm's death animation should be instanced. NOTE: The fade away animation will NOT work with this option enabled. Reload Type: NONE
		witherStormDeathInstancing = false
		#DEFAULT=false. Specifies if the distant renderer should be instanced. NOTE: The distant renderer does not render properly with this option enabled. Reload Type: WORLD
		distantRendererInstancing = false
```

**Screenshots**
![image](https://user-images.githubusercontent.com/15698722/192743997-2bf3ef56-5064-4308-a060-2c5d75dad567.png)
![image](https://user-images.githubusercontent.com/15698722/192744329-8f95ef44-5011-4398-9cea-fcb9299fd130.png)
![image](https://user-images.githubusercontent.com/15698722/192744345-f05a14b0-023b-40ee-a0fb-3d9ef9da171d.png)
![image](https://user-images.githubusercontent.com/15698722/192744548-0d0fcd1a-5e8f-4790-8c9e-4f0f667f2e5e.png)
Above are on a server, below is in single player
![image](https://user-images.githubusercontent.com/15698722/192746147-ac6b6a9e-0447-4a81-bedd-d10fcb434b02.png)
![image](https://user-images.githubusercontent.com/15698722/192746237-6c133d52-5468-4498-96fc-595aadc01bb4.png)

**Comment by aaronhowser1** [comment]
Measured using a waypoint, you have to be around 30 blocks horizontally from the Storm for it to work

**Comment by Globalfirestorm10** [comment]
It works, it's probably just an optifine bug, send your mod list here

**Comment by watersofnazareth** [comment]
Do you have Rubidium Extras

**Comment by nonamecrackers2** [comment]
Yeah, if you rubidium extras you need to disable “max entity distance” or whatever it’s called. This incompatibility is outlined on the mod page.

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/200155404-e666e044-110b-4b60-b01e-65671425acf1.png)
![image](https://user-images.githubusercontent.com/15698722/200155411-5f851df7-8dc9-49d3-a84a-fc94dbb2dcea.png)

**Comment by nonamecrackers2** [comment]
That should work. What other mods do you have that may cause this?
