### ISSUE TITLE
Bedrock is visible inside the wither storm when mining or having night vision on.

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#665]
I and other people have recently found a bug where digging in any direction, you will find bedrock and the wither storm is not supposed to have bedrock inside the wither storm, so instead you put something the teleports you outside the wither storm instead of hitting bedrock inside the wither storm.

**Comment by watersofnazareth** [comment]
This is intentional

**Comment by Asteroid4** [comment]
I think that maybe there should be a block called "Indestructible Tainted Flesh" which replaces this bedrock. I'll make a seperate issue for it tho.

**Comment by NinjaSam5399** [comment]
ok
