### ISSUE TITLE
Indestructible Tainted Flesh

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#667]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

My idea is to make it such that instead of having bedrock in the bowels, there would be indestructible tainted flesh. It is basically bedrock that looks like tainted flesh.

**Comment by TheEyeOfGaming** [comment]
yeah like a tainted bedrock block, would look sick tbh

**Comment by myron-obsolete-account** [comment]
actually a good idea which i also wanted to suggest, because when too many creepers blow up the same spot in the bowels it looks weird to see bedrock there, so indestructible tainted flesh would be better

**Comment by myron-obsolete-account** [comment]
wow i commented and right after nonamecrackers2 added the confirmed tag

i am a wizard

(joking. i dont think i caused crackers to add that tag here.)

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
