### ISSUE TITLE
Standing and moving on block clusters

### ISSUE THREAD

**Issue by bruhicantlogin** [nonamecrackers2/crackers-wither-storm-mod#668]
i wanted so that you could stand and slowly move on block clusters to get away from the tractor beam, its probably unlikely due to the ammount of effort and coding it would probably need, but it seems pretty cool
![image](https://user-images.githubusercontent.com/111668781/192880213-76308b75-4431-4cb8-8482-f520328cd9ad.png)

**Comment by watersofnazareth** [comment]
#150

**Comment by bruhicantlogin** [comment]
> #150

crap i didn't know bout that
