### ISSUE TITLE
the command block sword in story mode was gone when the wither storm was killed so in the mod it will do the same 

### ISSUE THREAD

**Issue by Wither5575** [nonamecrackers2/crackers-wither-storm-mod#669]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by RandomGithubUser32** [comment]
Please read the other suggestions before making one

**Comment by watersofnazareth** [comment]
#356
