### ISSUE TITLE
Low fps still present in later phases with block cluster rendering on.

### ISSUE THREAD

**Issue by Supertacoz** [nonamecrackers2/crackers-wither-storm-mod#670]
Minecraft 1.18.2

mod version 2.1

not necessarily a bug, but rather something that may be out of nomancracker's control. a while ago, I found that I had low fps with block cluster rendering on, and thought it was my graphics card struggaling. now, after testing it with flywheel, i found the fps to be unchanged. I decided to look at my GPU usage, and found it was less than 20% usage. then, I checked cpu usage. that was maxed out. on a ryzen 7 3700x. at least, it was maxed out on a single core/thread. because minecraft is mostly singlethreaded, the primary thread gets pegged when dealing with a lot of block clusters. but, the issue disappears if block cluster rendering is off. I am curious as to why block cluster rendering primarily on the CPU instead of the GPU.

to reproduce: summon the witherstorm in phase 5 or later with block cluster rendering on (with or without flywheel)

log: [2022-08-09-1.log.gz](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9669291/2022-08-09-1.log.gz)

flywheel: active, default configuration.

PC specs in case you were wondering:
Ryzen 7 3700x
32 GB DDR4 3400
Rx 6600

**Comment by nonamecrackers2** [comment]
If you go to the flywheel compat config and enable block cluster instancing following a game restart, you should see a big difference. The only reason the config is off by default is because block colours such as grass appear as white.

**Comment by Supertacoz** [comment]
Apologies, I should've looked into it more.

**Comment by nonamecrackers2** [comment]
No worries!
