### ISSUE TITLE
Tractor beam not picking up Formidi Bomb

### ISSUE THREAD

**Issue by OliversIntention** [nonamecrackers2/crackers-wither-storm-mod#672]
**Minecraft version**
1.19.2 (Essential Mod)

**Mod version**
1.19.2

**Describe the bug**
The Wither Storm (for me) won't pick up the Formidi Bomb anymore, the bomb still works but it looks really weird that the center Wither Head won't tractor beam it up anymore.

**To Reproduce**
1. Spawn Wither Storm
2. Set phase 4-7 (Minus the 7 Hole)
3. Place down F-Bomb and light it
4. Wait, and see the error

**Is Flywheel's optimizations active?**
No,  Flywheel is only 1.18/1.16

**Screenshots**

**Comment by nonamecrackers2** [comment]
Was able to reproduce however I'm not sure what the cause could even be. I feel the Essential mod is messing with something, however since it's closed source I can not determine what exactly.
