### ISSUE TITLE
Story Mode Armor Suggestion

### ISSUE THREAD

**Issue by OliversIntention** [nonamecrackers2/crackers-wither-storm-mod#673]
**Description of feature**
In Minecraft Story Mode, Ivor lets you pick out armor for the Wither Storm battle. I really like these armors and can be a very cool edition to the Mod. They can even have their own crafting recipes (My suggestion is maybe the armor color dyes plus netherite armor [Example of an Ender Defender recipe: https://gyazo.com/f87c26d9374047f3fbc12ddb1a28526f]) dakonblackrose made some cool armor templates for the Minecraft Story Mode Retold addon for bedrock edition.

Also I just wanna say I really like the recent update, gives more realism and I like it :)

**Comment by nonamecrackers2** [comment]
#191 

Also glad you like the update :)
