### ISSUE TITLE
Tractor Beam Rework Suggestion

### ISSUE THREAD

**Issue by OliversIntention** [nonamecrackers2/crackers-wither-storm-mod#674]
**Description of feature**
There's gonna be like 3 suggestions lol.

1. Make the tractor beam smaller. In Minecraft: Story Mode, the tractor beam is only the size of maybe a villager house: https://gyazo.com/3a7110ecee73dab725a84600ec80c378 / And I feel like this should be implemented, because the current one I find too big and bulky.
2. Make the heads move slower. In Story Mode, you have a time to avoid the tractor beam and dodge it. In this mod, it just automatically sucks you up.  (Maybe it can also be a setting on how fast it is)
3. On phase 7, it's very hard to get away from the Wither Storm, and I mean impossible. There's 9 heads and when you destroy one, another one just picks you up, that keeps on going over and over until your back at the first one when it's healed again. I'm suggesting a cooldown on the tractor beam heads (Maybe it can be a world setting? Default being 20 seconds)

I don't expect all of these suggestions to pass, I'm really just throwing idea's out there.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/285

**Comment by nonamecrackers2** [comment]
1. I don't feel this is necessary and I feel the size of them should remain as they are.
2. #285 
3. This has been fixed in the latest 1.18.2/1.19.2 release (2.1+/3.1+)

Also, please don't group suggestions into one issue. It's easier to track that way :)
