### ISSUE TITLE
Middle wither storm in phase 6 looking like phase 5

### ISSUE THREAD

**Issue by KrukAdrian** [nonamecrackers2/crackers-wither-storm-mod#675]
So in the original game when the wither storm fakes its death after it wakes up the middle wither storm looks like phase 5 and not big brain
![Zrzut ekranu (1727)](https://user-images.githubusercontent.com/106917942/193126529-f83ca443-bf27-43e4-a263-606fca19d90e.png)
![Ws middle](https://user-images.githubusercontent.com/106917942/193126681-4218d822-46b3-4baf-a2ca-a880c2845797.png)

**Comment by OliversIntention** [comment]
Making models are hard. He'd have to make an entirely new Wither Storm model so it has the separation blocks (of where the 2 other Wither's were supposed to be), plus, I feel it wouldn't look right.

**Comment by nonamecrackers2** [comment]
Yeah, lot's of model reworking which isn't worth it. Besides, my models are basically the "image" of my mod at this point so changing them doesn't make much sense.

**Comment by Asteroid4** [comment]
Also, In MCSM the size doesn't make much scence, given how massize phase 5.5 is.
