### ISSUE TITLE
Block Clusters Are Black Right as They’re Breaking Off

### ISSUE THREAD

**Issue by ChrisLTheNerd** [nonamecrackers2/crackers-wither-storm-mod#676]
**Minecraft version**
1.19. Forge-43.1.27

**Mod version**
witherstormmod-1.19.2-3.1

**Describe the bug**
Block clusters are sometimes black way before getting absorbed by the Wither Storm. It sometimes doesn't happen after reloading. It happens more often with phase 3 or lower from what I've been able to observe.

**To Reproduce**
1. Get close to block cluster
2. Block clusters will be black when coming off or mid air
3. Get further away and they're back to normal
4. Reloading may also make things go back to normal.

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No and no other mods installed when testing issue

**Screenshots**
Issue happening

https://user-images.githubusercontent.com/50182206/193167825-78782a37-6a73-4d60-9ade-95210df60cb1.mp4

https://user-images.githubusercontent.com/50182206/193170559-c191626a-7210-442c-a849-bdeaca415fe6.mp4

Issue not happening

https://user-images.githubusercontent.com/50182206/193169991-e723dc13-8e63-4548-b54b-c261e7d3b361.mp4

https://user-images.githubusercontent.com/50182206/193171293-73ea40fc-3612-40a8-9d8c-b3482b2868fc.mp4

**Comment by watersofnazareth** [comment]
#647

**Comment by V0calgiant12** [comment]
What were your specs?

**Comment by ChrisLTheNerd** [comment]
I have an Intel core i7-12700k, an EVGA FTW3 RTX 3080 TI, 32GB(2x16GB) of G.Skill Trident Z RGB DDR4-3200 CL14, and a 1TB & 2TB Samsung 970 EVO Plus M.2 NVMe.

**Comment by V0calgiant12** [comment]
okay, yeah, not what i thought it was, because I restarted my pc at some point and it just stopped happening when i opened up the game again. Wonder what caused it since it wasnt anything about hardware or the forge version
