### ISSUE TITLE
The Potion of the Wither

### ISSUE THREAD

**Issue by OliversIntention** [nonamecrackers2/crackers-wither-storm-mod#677]
**Description of feature**
In creative mode, I love playing around with the wither storm mod. Having mobs (try to) run away, tinkering with commands and settings, etc. I feel that their should be a potion (specifically splash potion) of wither sickness. I would love to see a crowd of pigs with Wither Sickness to see how they react to it, just for science ig.

also throwing this at your friends would be funny lol.

**Comment by Bagheera68** [comment]
Give them the effect using commands /effect give @e/@a witherstormmod:wither_sickness

**Comment by RandomGithubUser32** [comment]
regular potion:
/give @p potion{display:{Name:'{"text":"Potion of Wither Sickness","italic":false}'},CustomPotionEffects:[{Id:255b,Amplifier:0b,Duration:19999980}],CustomPotionColor:9569279} 1

splash potion:
/give @p splash_potion{display:{Name:'{"text":"Splash Potion of Wither Sickness","italic":false}'},CustomPotionEffects:[{Id:255b,Amplifier:0b,Duration:19999980}],CustomPotionColor:9569279} 1

lingering potion:
/give @p lingering_potion{display:{Name:'{"text":"Lingering Potion of Wither Sickness","italic":false}'},CustomPotionEffects:[{Id:255b,Amplifier:0b,Duration:19999980}],CustomPotionColor:9569279} 1

**Comment by nonamecrackers2** [comment]
Wither sickness isn't meant to be a potion. You can use these commands or a potion generator online to get a potion however.
