### ISSUE TITLE
Multiplayer not working 

### ISSUE THREAD

**Issue by Bagheera68** [nonamecrackers2/crackers-wither-storm-mod#678]
Minecraft version:
1.19.2

Mod version:
3.1

Im playing multiplayer on lan network. As soon as I summon the wither storm, the server starts kicking my friends out stating that theres some java error.

Fly wheel is active and optifine is not active.

**Comment by Globalfirestorm10** [comment]
Please include a screenshot of the error, the latest.log for the server, and debug.log for the server. Nobody can help you with the current info you have provided

**Comment by Bagheera68** [comment]
![Uploading a3{752a2bf} (250ecd55-7d61-4034-80ca-27fb0f6e244d id=0x7f0a03cc tag=BaseCommentFragment) …]()

**Comment by Bagheera68** [comment]
![20221001_084912.jpg](https://user-images.githubusercontent.com/114000728/193421776-a84dcaab-426a-4850-bf89-4857b6f0d1fb.jpg)
![20221001_084907.jpg](https://user-images.githubusercontent.com/114000728/193421820-f0ec47c7-32f5-4b16-92a4-f9f2614cb5db.jpg)
![20221001_084900.jpg](https://user-images.githubusercontent.com/114000728/193421856-8e926dcc-daef-413e-8cdc-b3c1d2e23ed7.jpg)

**Comment by Bagheera68** [comment]
I meant to post the screenshots but I hadnt taken a picture yet. Tell me if theres anything else. (These are what it says when it kicks my friends out.):

**Comment by Globalfirestorm10** [comment]
Try creating a world, giving yourself wither sickness, then joining

**Comment by Bagheera68** [comment]
How will this help?

**Comment by nonamecrackers2** [comment]
What's your forge version?

**Comment by Bagheera68** [comment]
43.1.30 If theres anything else, feel free to ask.

**Comment by Globalfirestorm10** [comment]
> How will this help?

There is a bug where you can't join a server unless you made a world with CWSM before.

**Comment by Globalfirestorm10** [comment]
also, send the latest.log and debug.log

**Comment by Bagheera68** [comment]
> also, send the latest.log and debug.log

Sorry to ask, but how do you get these?

**Comment by Globalfirestorm10** [comment]
.minecraft->logs-> look for latest.log and debug.log, then send them here

**Comment by Bagheera68** [comment]
[debug.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9725435/debug.log)
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9725444/latest.log)

Just click on them, look at them or do what you need, then delete them.

**Comment by Bagheera68** [comment]
[debug.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9738047/debug.log)
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9738050/latest.log)

**Comment by Bagheera68** [comment]
is there a way to make it where you can view the .log file but not have to download it?

**Comment by nonamecrackers2** [comment]
You could put it on pastebin, however this will work fine

**Comment by Bagheera68** [comment]
Alright, tell me if theres any solutions!

**Comment by nonamecrackers2** [comment]
Does this happen with any other mods by themselves?

**Comment by Bagheera68** [comment]
No

**Comment by nonamecrackers2** [comment]
Oh just wait, meant to post that reply on a different issue, sorry!

**Comment by Bagheera68** [comment]
All good!

**Comment by Bagheera68** [comment]
Tell me if there's any updates on the solution.

**Comment by nonamecrackers2** [comment]
This appears to be a general issue. Mods such as Create and Twilight Forest also have this issue with no resolution. Until a fix is found (either by Forge or myself) you'll have to find another way to play multiplayer than LAN. Sorry!

**Comment by Bagheera68** [comment]
Oh ok

**Comment by Bagheera68** [comment]
Nvm I found a solution; I got a forge server and I'm playing that way. It now works.
