### ISSUE TITLE
Phase 4.5

### ISSUE THREAD

**Issue by Cgdihkg** [nonamecrackers2/crackers-wither-storm-mod#679]
Playing minecraft story mode, I noticed that there is a phase that is more than 4, but less than 5. This phase looks the same as 4, with the exception of tentacles that grow already from the bottom and large tentacles that appear in this fashion at the end of phase 5. If you chose redstonia, then after finishing the episode, there is a wither storm on the screensaver, similar to phase 4, but tentacles grow from the bottom and there are large tentacles. I decided to draw something very fast, but similar.
![Screenshot_20220930_194626_com vblast flipaclip](https://user-images.githubusercontent.com/112248653/193319332-c3c412c5-1534-4202-87c7-d2a6fcc70660.jpg)

**Comment by Globalfirestorm10** [comment]
please send a photo of where you saw this phase in MCSM

**Comment by OliversIntention** [comment]
CG, if you are talking about the phase during the Redstonia scene, that Wither Storm resembles the early phase 5 (where the Wither Symbiont doesn't spawn yet). So, this feature wouldn't be that good. Plus Cracker would have to make an entirely new model.

**Comment by nonamecrackers2** [comment]
Pretty sure that phase was a bug and not actually intended. I find the phase looks awkward anyway and don't personally feel it needs to be added.

**Comment by Cgdihkg** [comment]
> Pretty sure that phase was a bug and not actually intended. I find the phase looks awkward anyway and don't personally feel it needs to be added.

Why is phase awkward? The normal phase. The more phases the better. And add huge tentacles at the beginning of phase 5.

**Comment by Globalfirestorm10** [comment]
> > Pretty sure that phase was a bug and not actually intended. I find the phase looks awkward anyway and don't personally feel it needs to be added.
> 
> 
> 
> Why is phase awkward? The normal phase. The more phases the better. And add huge tentacles at the beginning of phase 5.

Not quite. Crackers made this mod to add the main wither storm phases, not make 20 of them. Plus, like he said, it was an animation glitch, also these models take time, it's not like he could just make a new one within a day
