### ISSUE TITLE
[1.19.2] Eating/Drinking anything triggers "Is it the end?" advancement.

### ISSUE THREAD

**Issue by Baggytrousers27** [nonamecrackers2/crackers-wither-storm-mod#680]
1.19.2 Forge 43.1.32
witherstormmod-1.19.2-3.1

No flywheel

Eat/Drink anything after opening world and the above advancement triggers.

[debug.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9686830/debug.log)

Apologies if this is a duplicate.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/654
