### ISSUE TITLE
Ivor Boss Fight

### ISSUE THREAD

**Issue by IntrovertedGamer** [nonamecrackers2/crackers-wither-storm-mod#685]
So i don't expect this feature to be added soon, but i feel like with enough free time and other minor feature suggestions or bug fixes finished with and out of your way, it could be done. 

I'm sure all of you will have a lot of questions so i'll answer them by the end of the explanation.

Process:

The boss fight takes place in a new structure which is Soren's Fortress, you find Ivor in the room where several bookshelves are present.

To get to the structure in the first place, you have to buy a map to it from a cartographer and make your way there, upon the boss bar appearing and making your way into the room, the fight begins with Ivor pulling out a gold sword to attack.

The Fight and attack patterns:

Ivor remains somewhat untouchable at the start of the fight, as he will dodge projectiles and throw splash potions of harming when you get to close.

Harming Rain:

His first attack is throwing multiple potions of harming in the air that stay up there for a second before it falls down on you, you obviously need to get out of the way before it does so, an extra effect is that he would occasionally throw lingering potions so that the effect will continue in that area for a few seconds. (only applies to this attack) He will do this a couple of times before proceeding onto his next move

Blitz:

Ivor drinks a potion of speed, and rapidly circles around you, you get alerted of where he'll strike for a brief moment before he dashes at you with his sword, he becomes exhausted and starts eating to regain health, giving you some time to score a few hits.

Where are you?:

Ivor splashes himself a potion of invisibilty and dissapears, your best chance at survival would would switching to 3rd person so you can get a good FOV, a potion of harming will appear out of nowhere, floating in the air for a few seconds before being tossed at you, this attack will go on for 15 seconds before Ivor becomes visible again.

Impaling Drop:

Ivor will drink a potion of leaping, jump in the air and drop down on you with his sword in front, he does this 3 times before becoming exhausted and giving you time to hit him, this attack is performed after the previous 3 have been done, not particularly in order, just if he does all of the previous attacks. 

When Ivor is defeated, he doesn't die, but the boss bar dissapears, and he splashes you with a potion of Turtle Master before running away, dropping a command block book on his way out of the room.

Possible Q&A:

What is the point of this boss fight if it gives you the same prize as the Withered Symbiont? 

A: I wanted to give this mod more of an MCSM vibe, where it would let you choose how you wanted the mod to progress, not as a general feature but in this scenario, it would, i also have thought of a planned use for Ivor in the future after the Witherstorm is destroyed, where you could sell him emeralds and other specific items in return for potions of a greater level then what you can get in vanilla, such as speed 5, strength 6, and healing 3.

How could you fight while also running from the witherstorm?

A: The fight kind of works like when you fight the symbiont, the wither storm will not follow you during this fight.

Won't this make Command Block books renewable?

A: My thought of how to solve this would be to make Soren's Fortress like the rundown house, it only spawns once per world and thus, only one fight. 

Where would you find Ivor after the witherstorm is destroyed? 

A: I'm honestly not sure, my best idea is that he would stop by the Rundown House and make his new home there once the main threat is gone.

I guess at this point, i'll adress why i want this, the main thing i love about this mod is the fact it's the first one to make me anxious, because the witherstorm will always be tracking me down no matter how far i run, which would tempt players to avoid it as much as possible, i usually escape through a nether portal, and move 1000 blocks away before going back to the overworld, far away from the witherstorm, however after escaping it, i'm only left one thing i can really do before it comes at that's collecting TNT, to get the final thing i need to craft a formidibomb, i end up having to go confront the witherstorm anyways, don't get me wrong, i love the withered symbiont boss fight, however, i always felt like it was more of a boss that you confront AFTER the witherstorm reaches phase 6, being the last enemy you have get through before you confront the final boss, what i'm saying is that it doesn't feel like something meant to fight mid-game so much as when your geared up with good armor and tools, a side affect of this is like i said before, gives players a choice on how they want to progress through this, some will confront the Witherstorm directly in order to obtain the book while others will take a less risky approach and fight in Soren's Temple to obtain it.

Like i said before, this is a lot to add, so it should probably be put off until you a lot of free time to do it, but i feel like it could be done if you do have it.

**Comment by watersofnazareth** [comment]
No new structures or anything will be added, just the Wither Storm hence the name [Cracker's Wither Storm Mod]

**Comment by Krypton6167** [comment]
man, I feel sorry for this guy he just wrote a whole 5 essays and he just got a "no."

**Comment by nonamecrackers2** [comment]
Seems like an interesting idea, but since this mod is dedicated to the Wither Storm and meant to detach it from MC:SM it won't be added, sorry.
