### ISSUE TITLE
Wither Storm invulnerability on phase 2 

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#686]
The wither storm needs invulnerability when it is born, because the tractor beam is developing when at phase 2 and the tractor beam is not ready to activate, and I also seen this video (sent as clip).
https://youtube.com/watch?v=NU4cPCBVL4o&feature=share&utm_source=EKLEiJECCKjOmKnC5IiRIQ&t=78

**Comment by watersofnazareth** [comment]
Don't think this would even be noticeable

**Comment by KrukAdrian** [comment]
I mean it would be cool for there to be a phase 1.5 when the tractor beam is developing

**Comment by nonamecrackers2** [comment]
Don't feel this is necessary since you can't hurt the wither storm substantially anyways.

**Comment by NinjaSam5399** [comment]
ok
