### ISSUE TITLE
[Suggestion] Secondary Bowels Hallway

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#687]
Basically, just a small change to have the bowels be able to generate a second hallway on the other side of the arena, this would give the player more options to get some of the upcoming resources (Mainly logs and leaves because they'd be rare)

**Comment by V0calgiant12** [comment]
Yeah, that and it is also there in MCSM
![image](https://user-images.githubusercontent.com/109500471/193954398-b365d8ec-9737-45fc-8ad5-70a6295e4134.png)
