### ISSUE TITLE
suggestion: minshaft hallway in the bowels

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#688]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**
so, let's say that the storm sucks up a mineshaft, when you enter the bowels, I think there should be some parts of the mineshaft sticking out, and leading to other parts, but of course, the material such as the wood can be tainted.

**Comment by watersofnazareth** [comment]
I'll consider working on this

**Comment by nonamecrackers2** [comment]
There wouldn't be a way to make the tunnel appear based on whether the WS consumed a mineshaft or not but a tunnel for it can be considered.

**Comment by Globalfirestorm10** [comment]
ok

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2

**Comment by Globalfirestorm10** [comment]
Im aware
