### ISSUE TITLE
Potion that can kill wither in first phases

### ISSUE THREAD

**Issue by Byllfighter** [nonamecrackers2/crackers-wither-storm-mod#691]
![Screenshot_2022-10-02-15-05-02-798_com google android youtube~2](https://user-images.githubusercontent.com/60580992/193453249-f43121e8-e063-4f77-bb8b-97288aeaaf1a.jpg)

It is present in the original game

**Comment by Asteroid4** [comment]
Please check other submissions before posting, cracker has already stated that he won't add this. (#445 )
