### ISSUE TITLE
Wither Storm Health Increase with each phase

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#692]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

Previously, the wither storm stayed at its phase 4 health during phases 5-7, and that was ok when you could not deal damage to it directly, but I feel that the wither storm should have its health increase in the later phases too now that disabling invulnerability is an option.

**Comment by Minecraft1561645** [comment]
Let them have the health that I have indicated.
Phase WIther: 400 health.
Phase 1: 500 health.
Phase 2: 650 health.
Phase 3: 800 heath.
Phase 4+: 1024 health

**Comment by Asteroid4** [comment]
> Let them have the health that I have indicated. Phase WIther: 400 health. Phase 1: 500 health. Phase 2: 650 health. Phase 3: 800 heath. Phase 4+: 1024 health

I was thinking something like:
Phase 0-4:
Unchanged from normal health
Phase 5:
1500 health
Phase 5.5:
2000 health
Phase 6:
1500 health, segments have 250 health
Phase 7:
2000 health, segments have 500 health

**Comment by RandomGithubUser32** [comment]
Because of vanilla limitations, it is impossible to make the wither storm have more than 1024 health.

**Comment by RandomGithubUser32** [comment]
Giving the wither storm different levels of resistance to damage in later phases could work.

**Comment by ghost** [comment]
> Because of vanilla limitations, it is impossible to make the wither storm have more than 1024 health.

Wait, how did the engender mod do it?

**Comment by RandomGithubUser32** [comment]
By vanilla, the maximum amount of health a mob can have is 1024. However, with mods, this can be increased. If nonamecrackers2 could make the wither storm have more health in later phases he definitely would.

**Comment by Asteroid4** [comment]
I just realized that my other issue is basically the same as this one. Oops.
