### ISSUE TITLE
Wither Storm Regeneration Slider

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#693]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

I disabled invincibility for the wither storm on my server, and noticed the regeneration was disabled too. I feel that regeneration should be unlinked from invincibility, and should instead go onto different slider in the config.

**Comment by nonamecrackers2** [comment]
But why? Having invul on but having regeneration disabled doesn't make much sense, as you can't damage the WS and the health will remain constant. You can also have regeneration on but invul disabled, however the WS's health regeneration outpaces damage anyway, which is the main reason why the two are clumped into one config option.
