### ISSUE TITLE
Wither Storm phase increase should automatically increase health.

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#694]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

I think that when the wither storm's health should increase each phase instantly, for instance if phase n's health is x and phase n+1's health is y, the health would increase by y-x instantly.

**Comment by nonamecrackers2** [comment]
#531. Not exactly the same, however similar enough.
