### ISSUE TITLE
Disable automatic segment regeneration, make command for it

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#695]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

My idea is to make it such that a segment, when killed by hand, will not regenerate. However, there should be a command, /witherstormmod segment regenerate (wither storm), that will regenerate segments for a wither storm if it is phase 6 or greater.

**Comment by EnderPlays123** [comment]
Also, should i stop making so many issues at once?

**Comment by watersofnazareth** [comment]
Not sure if this would even really be possible with how the Segments are coded

**Comment by ghost** [comment]
> Not sure if this would even really be possible with how the Segments are coded

ig have 2 variables track if the segments were killed by players, and dont regenerate them if the variables are true.

**Comment by nonamecrackers2** [comment]
Segments are intentionally non-killable and as such this will not be implemented.
