### ISSUE TITLE
Purple lightning strikes when the wither storm is near like in minecraft story mode episode 4

### ISSUE THREAD

**Issue by Helloisnice** [nonamecrackers2/crackers-wither-storm-mod#696]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
#228, #552
