### ISSUE TITLE
Re-sprites of the wither storm tools and (recipes part 1)

### ISSUE THREAD

**Issue by mmiller9196** [nonamecrackers2/crackers-wither-storm-mod#697]
Hello, I have recently been playing the game itself, and looking at the wiki, and the weapons have completely different sprites than the command block tools in game for reference here's the command block shovel (MC:SM) compared to the modded sprite

MC:SM
![image](https://user-images.githubusercontent.com/110945774/193480707-b82c9760-7973-4773-bade-5040ded8808d.png)

CWSM
![image](https://user-images.githubusercontent.com/110945774/193481356-2fed8422-c6ae-4be8-bd24-bec6b7ea0fa3.png)

the same can be said for all the other weapons for MCSM

![image](https://user-images.githubusercontent.com/110945774/193481406-6a5a4ae8-c1da-4030-bb96-a854a78d9d98.png)

I already made a texture pack re-spriting all of the tools to the MC:SM sprites correcting them and I would like to suggest for their implementation here are the resprites I have done based off the MC:SM sprites (BESIDES THE SWORD SINCE IT IS ALREADY ACCURATE!!!)

pickaxe:
![command_block_pickaxe](https://user-images.githubusercontent.com/110945774/193482508-3b45fb0e-5bc8-4612-ab2d-94dcc7d9af04.png)

axe:
![command_block_axe](https://user-images.githubusercontent.com/110945774/193482938-9ab1b582-e79e-4ff7-aec8-bca33a0be258.png)

shovel:
![command_block_shovel](https://user-images.githubusercontent.com/110945774/193483884-0f3ca88d-e596-495b-838c-28dbaf51b408.png)

hoe:
![command_block_hoe](https://user-images.githubusercontent.com/110945774/193490554-2c986a90-50e8-4f14-b06a-26984ce198be.png)

I would also like to recommend different types of smithing recipes and recipes in general (since the weapons didn't look like a diamond weapon at all) but I will continue this suggestion in a different suggestion box.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/338
Great job with the textures though

**Comment by nonamecrackers2** [comment]
Awesome textures though. Highly recommend you post them somewhere online.

**Comment by GrandmaPork** [comment]
Make these into a texture pack please. I would like to use these

**Comment by mmiller9196** [comment]
Ok ill make a texture pack for the weapons

**Comment by mmiller9196** [comment]
ok im just waiting for it to be approved now

**Comment by mmiller9196** [comment]
ok I just posted it in the discord
