### ISSUE TITLE
Re-sprites of the wither storm tools and (recipes part 2)

### ISSUE THREAD

**Issue by mmiller9196** [nonamecrackers2/crackers-wither-storm-mod#698]
since I felt like the tools lack the "diamond part" of the tool, I felt like I could provide a suggestion recipe for the tools I suggested

pickaxe:

Base item: a copper-amethyst combined pickaxe
![image](https://user-images.githubusercontent.com/110945774/193492139-52ef574d-2185-401e-8bcd-76386ee90129.png)

smithing table reaction:
![image](https://user-images.githubusercontent.com/110945774/193492165-acb8cac4-edf5-4bfc-88cd-3b3b42d70d5e.png)

axe:
base item: gold axe

smithing table reaction:
![image](https://user-images.githubusercontent.com/110945774/193492230-39dd17c9-2bdb-4672-a88a-bee88a65be36.png)

shovel:
base item: a tainted cobblestone shovel (obtained by just mining off some tainted cobblestone form the fake death of witherstorm)
![image](https://user-images.githubusercontent.com/110945774/193492444-92ab8210-faf7-4f3d-a6dc-823258e2d0f2.png)

smithing table reaction:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/110945774/193492696-1d4d4102-b543-4c84-8fd2-d2b12d1b1a24.png">

hoe:
base item: a hoe forged with blaze rods and copper
<img width="340" alt="image" src="https://user-images.githubusercontent.com/110945774/193492801-7e352f46-c92b-440f-be1d-0e63ead813a3.png">

smithing table reaction:
![image](https://user-images.githubusercontent.com/110945774/193492880-7a4a5cc2-5f22-4dca-a993-628b1565477f.png)

thats all I have to suggest for now.

**Comment by nonamecrackers2** [comment]
I don't feel the recipes of the tools should be changed however this could totally be a cool datapack in conjunction with your resprites.
