### ISSUE TITLE
Lootr incompatibility 

### ISSUE THREAD

**Issue by SkullDiamond** [nonamecrackers2/crackers-wither-storm-mod#7]
For some reason Lootr dont work whit this mod installed

**Comment by nonamecrackers2** [comment]
Could you provide more information and any logs/crash reports that may be applicable?

**Comment by SkullDiamond** [comment]
Doesnt crash but here is the latest.log I tried only whit lootr and your mod.
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/8666826/latest.log)

**Comment by nonamecrackers2** [comment]
I don't see anything that is wrong? What exactly are you saying doesn't work?

**Comment by SkullDiamond** [comment]
the chest on the world dont spawn as lootr

**Comment by nonamecrackers2** [comment]
Have you verified that this is the case even without the mod installed?

**Comment by SkullDiamond** [comment]
I tried whit only those 2 mods and when I remove Wither Storm mod lootr works
![image](https://user-images.githubusercontent.com/79324102/167961971-7ee5261f-2cb0-47f9-98fd-65733f61283a.png)

**Comment by nonamecrackers2** [comment]
I'll take a look into it

**Comment by nonamecrackers2** [comment]
There will be a config option that will act as a temporary fix in the next update
