### ISSUE TITLE
Wither Storm Mod crashes Realistic Block Physics mod's physics engine 

### ISSUE THREAD

**Issue by ekiplier** [nonamecrackers2/crackers-wither-storm-mod#70]
Playing with both Wither Storm Mod and [Realistic Block Physics ](https://www.curseforge.com/minecraft/mc-mods/realistic-block-physics) mods causes the latter's physics engine to crash.

**Comment by nonamecrackers2** [comment]
I need a crash report to figure out the issue

**Comment by ekiplier** [comment]
The thing is it doesn't crash the actual game, it just makes the RBP mod stop working properly. It's not hard to reproduce, though. Just install both mods, join a world, and see physics not working and some lag.

**Comment by nonamecrackers2** [comment]
Interesting. Could you try turning off "Tick In Containers" under the "Formidibomb" config?

**Comment by ekiplier** [comment]
I just tried it, block physics still don't work. This time it took a bit longer to reproduce though.

**Comment by nonamecrackers2** [comment]
Will have to investigate further then

**Comment by nonamecrackers2** [comment]
Just was testing and noticed the mod was acting normal, and I'm unable to reproduce this issue. Did you have any other mods installed when you encountered this issue?

**Comment by ekiplier** [comment]
Sorry, it wasn't a crash. It was actually just extreme lag

**Comment by nonamecrackers2** [comment]
Ah, got you
