### ISSUE TITLE
[Bug] Block Clusters gradually cause more and more lag

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#700]
1.18.2

2.1

- Description and Easiest way to replicate -
Place one Repeating Command block placing one block continuously, And another replacing that block with a block cluster, strangely if you add the tag {NoGravity: 1b} it clears the lag up, once this lag starts it will affect the Wither Storm's block clusters and gradually get worse, it seems to be some form of a weird leak, and it could possibly be related to collision, generally it takes a while to take effect but once the WS begins picking up huge clusters it happens relatively fast

**Is Flywheel's optimizations active?**
Yes, all are active

**Comment by nonamecrackers2** [comment]
I can't seem to reproduce this. Are you still able to with the latest version of the mod?

**Comment by nonamecrackers2** [comment]
Actually, just realized my attempt to recreate this issue was with Flywheel 0.6.8 (among other changes). Gonna test on 2.1 if the issue is present. If so I may have just fixed it without knowing.

**Comment by nonamecrackers2** [comment]
Yeah still can't reproduce. If this is still an issue let me know.
