### ISSUE TITLE
A new Segment feature - Scouting

### ISSUE THREAD

**Issue by GoldSlimeling91** [nonamecrackers2/crackers-wither-storm-mod#701]
As of now the two smaller wither storms simply sit side by side next to the main wither, just mirroring it's rotation and movement and acting as extra sets of heads. So instead of sitting in one fixed spot locked with the main storm they could potentially scout around the chunks where the main wither is at, seeking out any creatures to absorb.
The two segments will either scout ahead to cover more terrain faster or go back a bit to grab some missed mobs, they will never stray too far from the main storm however and will stay within the radius of the debris rings. The segments are also a decent amount faster than the main storm so they can't fall behind it.
If the storm is chasing it's current target, the segments will always scout ahead for the main wither regardless if they missed mobs in the back.

An example of where the segments could potentially be while patrolling, the segment in the back is beaming mobs the other two missed, while the one in the front is scouting out the terrain ahead.
![2022-10-04_00 29 25](https://user-images.githubusercontent.com/111310936/193734808-6b6666d0-c597-4eef-942a-04006f0b2572.png)

**Comment by Asteroid4** [comment]
I feel that this is a great use of the segments!

**Comment by RandomGithubUser32** [comment]
cool but kind of similar to https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/432

**Comment by nonamecrackers2** [comment]
Quite like this idea actually

**Comment by ChrisLTheNerd** [comment]
That's an awesome idea! It gives the segments an interesting purposes.

**Comment by Globalfirestorm10** [comment]
I like this idea as well, hope to see it implemented within the next few updates

**Comment by TheEyeOfGaming** [comment]
this is a cool idea, hopefully it gets added!

**Comment by Theoyeah** [comment]
It is interesting, but it would be more fitting if the segment would just not go outside the circles

**Comment by NinjaSam5399** [comment]
YAY!

**Comment by Globalfirestorm10** [comment]
> YAY!
> 
> 

?

**Comment by nonamecrackers2** [comment]
Closing since this has been kind of implemented

**Comment by BluePineappleGuy** [comment]
> Closing since this has been kind of implemented

wait what

**Comment by myron-obsolete-account** [comment]
> > Closing since this has been kind of implemented
> 
> wait what

yes I did notice, segments do more freeroaming and all that.

**Comment by nonamecrackers2** [comment]
Yeah they're not as locked anymore, they do more roaming around on there own.
