### ISSUE TITLE
1.19.2 When I put on shaders the tracker beam doesnt show only the particles

### ISSUE THREAD

**Issue by LunchTingz56** [nonamecrackers2/crackers-wither-storm-mod#702]

**Comment by Globalfirestorm10** [comment]
this isn't only 1.19.2, it's all the other versions, and I believe this is normal, you may need to tweak some settings

**Comment by nonamecrackers2** [comment]
Yeah, not much I can do on my end. You'll have to find a shader that works with them. I think the new complimentary one, configured properly, works with the tractor beams.
