### ISSUE TITLE
Segments fall when WS dies

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#703]
In MCSM, you can see that the segments fall to the ground when the wither storm dies. Maybe it would be as blocks, maybe as an entity, but I think it would be cool to implement into this mod.

**Comment by nonamecrackers2** [comment]
This is already implemented

**Comment by ghost** [comment]
It does, but I was thinking it could stay permanently.

**Comment by nonamecrackers2** [comment]
Not very feasible to implement that in a solid way.
