### ISSUE TITLE
Other mobs in block clusters

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#704]
Currently there are only zombies and skeletons that can appear in block clusters, but I think it would be good to have more mobs there. I was thinking that there could be:
- Spiders
- Creepers
- Cows
- Chickens
- Pigs
- Sheep

I understand that that is a lot to add, so maybe mark this as low priority.

**Comment by watersofnazareth** [comment]
I enjoy the idea of having the bowels be dead and barren, with the life drained out of it which is why I chose Skeles/Zombies, but I will consider adding more mobs/statues in general, possibly as a standalone block

**Comment by nonamecrackers2** [comment]
Actually, closing since this does not follow the new guidelines
