### ISSUE TITLE
Got bored and made a Wither Sickness texture

### ISSUE THREAD

**Issue by GoldSlimeling91** [nonamecrackers2/crackers-wither-storm-mod#706]
literally got bored and decided to make another texture for the effect itself and decided to share it, thats it
Texture file
![wither_sickness](https://user-images.githubusercontent.com/111310936/194224159-94ba3b75-60a4-466c-8bb1-ff2cc16cffdc.png)
Resized version
![wither_sickness_big](https://user-images.githubusercontent.com/111310936/194224260-e1b6cb8d-4aad-4c13-b349-6126bbaa0d70.png)

**Comment by bowserjr0** [comment]
can you make a texture pack of it ?

**Comment by V0calgiant12** [comment]
damn, that looks cool!

**Comment by Asteroid4** [comment]
I don't think this should be a github issue, it should go in #creations in the discord server.

**Comment by V0calgiant12** [comment]
> I don't think this should be a github issue, it should go in #creations in the discord server.

Where is the link to the server though?

**Comment by Asteroid4** [comment]
https://discord.gg/GcmwCjdnun

**Comment by V0calgiant12** [comment]
ty

**Comment by nonamecrackers2** [comment]
I like it, however gonna be sticking with the current one. You can easily turn this into a texture pack if you'd like though

**Comment by myron-obsolete-account** [comment]
@GoldSlimeling91 can I use this for a resource pack which I might or might not upload so people can use it? I plan on making a small enhancement respak for CWSM
