### ISSUE TITLE
MCSM Enderman Behaviour

### ISSUE THREAD

**Issue by Atrick21** [nonamecrackers2/crackers-wither-storm-mod#707]
**Description of feature**
Endermen will teleport into the overworld around the end portal if the main end island where the ender dragon is became flooded. Basically like in MCSM, when the main island is flooded, endermen will start spawning around the portal and after a while in the surface of it. When the wither storm arrives then like with previous suggestions, endermen will start spawning with flesh blocks in their hands and eventually the hole will appear. Basically a necessity to bring water buckets to flood the end island in order to defeat the wither storm. This feature gives another challenge to getting rid of the wither storm because currently we only wait after we spawn it, we formidi-bomb it, then we wait again, and it's ready to fight (Of course you still fight the Symbionts though). Endermen will only be able to teleport to the overworld if the end portal at the end is activated, so basically players need to fight the ender dragon first if it isn't open. Endermen could also be able to spawn in large numbers if more end islands are flooded. (All of this could be a configurable setting though)

**Comment by Globalfirestorm10** [comment]
this has already been suggested

**Comment by Globalfirestorm10** [comment]
here's the link to crackers response:https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/656#issuecomment-1261299508

**Comment by Atrick21** [comment]
I don't think the endermen teleporting out of the end in mass numbers when it is flooded has been suggested, but in the message I mentioned that it would accompany previous suggestions in which the endermen are attracted to the wither storm. I already knew that was suggested.

**Comment by ghost** [comment]
1. it would be way too as hard.
2.  why would someone go out of there on way to flood the entire end.  
3. and would be considered a MCSM mod.

**Comment by nonamecrackers2** [comment]
Detecting if the end is flooded isn’t very feasible, and messing with the progression to fit around this isn’t in my best interest right now. Having endermen spawn with tainted blocks has already been suggested before.
