### ISSUE TITLE
2 Things

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#708]
**Description of feature**
1. Wither Storm Heads can turn off there tractor beams at anytime they want
There were points in story mode where the WS heads would turn off there tractor beams, Some could argue that its a animation error but i doubt it as it looks intentional.

Examples: 
1. During episode 1 after Gabriel saves Jesse and Petra from the tractor beam, when Jesse notices the wither storm shooting skulls we see one of the heads not have there tractor beam on
![image](https://user-images.githubusercontent.com/48260861/194684782-9d6b57a3-a299-4359-aa90-bfb374bf9a04.png)
2 Also in episode 1 In Gabriel's temple when Petra attempts to save Gabriel a head suddenly activated its tractor beam pulling her.

In CWSM, i was thinking the heads could have a alternative behavior and shoot skulls more frequently when there tractor beam is off.
I was also thinking the wither storm could just suddenly turn on the tractor beam when a head is locked on a target, kind of like a ambush attack

2. Wither Storm can fly low to the ground when needed and/or wanted
During the forest chase scene the wither storm is shown to be low to ground, this made it easier for it to cause more harm.

**Comment by V0calgiant12** [comment]
I actually really like this idea, though it might be hard for Crackers to implement. I feel like this might have to be the main topic of an update later on rather than the update that is currently being worked on.

**Comment by theemeraldsword85** [comment]
The beam turning off to shoot skulls more rapidly sounds like a pretty good idea. I wonder if it will be added.

**Comment by NinjaSam5399** [comment]
Cracker, can you pls implement this? I really love this Idea.

**Comment by Luke7381** [comment]
Improved my grammar a little, was rushing when i first made this.

**Comment by myron-obsolete-account** [comment]
the tractor beam thing is a neat idea, actually i think i have an idea on what conditions nonamecrackers2 could make for the beams to turn on/off:
when a head found a target it wants to pull and consume, the tractor beam gets activated. else its disabled. if the storm is looking for a target, it sometimes activates the tractor beam to detect if there is something/somebody hidden behind specific blocks (if its a house, the head could shoot a flaming skull to access the victim)

**Comment by nonamecrackers2** [comment]
I think how it currently works as of now is fine and does not need altering
