### ISSUE TITLE
Tainted Dust Block

### ISSUE THREAD

**Issue by Risslerasslw** [nonamecrackers2/crackers-wither-storm-mod#709]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**
In mcsm during the battle withe the command block, while Jesse says he going to go onto the “ledge” you can see a glowing purple block that looks like the red stone powder
![D469B431-3DAF-43B4-8588-975AA2628957](https://user-images.githubusercontent.com/115381746/194733531-267d91cc-9363-49ac-bf1c-05a51530aab6.jpeg)

**Comment by nonamecrackers2** [comment]
I believe @Thefuzz1234555 was working on something similiar.

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
