### ISSUE TITLE
bug with tinted glass

### ISSUE THREAD

**Issue by Gaboamau** [nonamecrackers2/crackers-wither-storm-mod#71]
There is a bug where when looking at the Wither Storm through the tinted glass or tinted glass panel, the Attractor Rays and clouds of the Wither Storm disappear or are not visible.

(without tinted glass)
![image](https://user-images.githubusercontent.com/106891155/172499957-6d0b01be-7160-4f2c-8f0d-7379258b32c4.png)
(with tinted glass)
![image](https://user-images.githubusercontent.com/106891155/172500009-e391569c-6020-4c46-ba26-509b242cc21e.png)
(All types of tinted glass)
![image](https://user-images.githubusercontent.com/106891155/172500572-25a6658f-b398-439b-ac25-dc2bce205eeb.png)

**Comment by nonamecrackers2** [comment]
This is due to the rendering order of things, and there isn't much that I could do to fix this issue
