### ISSUE TITLE
[Starting house cannot generate via commands in other chunks beside 0, 0] Cracked WStorm in a pre-generated server world

### ISSUE THREAD

**Issue by SrChuleta** [nonamecrackers2/crackers-wither-storm-mod#711]
Hi! Im sorry if this is a repeated question but i have been searching but i didnt find the answer. Sorry if my english writting level is bad too, cause im spanish.
Im trying to generate the 0,0 house in a mohist 1.16.5 pre-generated world server, but i dont know if it is posible. If its not, ¿is it possible to generate it via commands or a command_block?

**Comment by Globalfirestorm10** [comment]
if you've already generated the world and it's structures before you added CWSM, then no

**Comment by FrozenDragon0** [comment]
> Hi! Im sorry if this is a repeated question but i have been searching but i didnt find the answer. Sorry if my english writting level is bad too, cause im spanish. Im trying to generate the 0,0 house in a mohist 1.16.5 pre-generated world server, but i dont know if it is posible. If its not, ¿is it possible to generate it via commands or a command_block?

You'll need to build the Witherstorm recipe in creative manually since it's a pregen world.

**Comment by SrChuleta** [comment]
Well i did with just soul sand, but when i place the last skull it just disappears. I´ve researched that there is a datapack that allows you to craft the command block, but is for 1.18 and 1.19 versions only. So nope, it doesnt work.
Another possibility that i thought, was copying the player data (inventory) in a new world generated with CWSM. Is that possible?

**Comment by nonamecrackers2** [comment]
In 1.16.5, no. In 1.19 (and maybe even 1.18.2 I'm not sure) you can generate structures via commands. I recommend upgrading to 1.18+ anyways since it has all the new features, however that is your choice.

> Another possibility that i thought, was copying the player data (inventory) in a new world generated with CWSM. Is that possible?

Yes, just make sure you have the exact same mod list when regenerating a world. I'm not exactly sure how you to copy player data so you'll have to figure that out (think it's just in a folder called "playerdata"). I believe copying the playerdata folder will also cause your position to be transferred as well, so you may spawn inside blocks or in the sky. So beware. Good luck!

**Comment by ISLANDBANE** [comment]
> In 1.16.5, no. In 1.19 (and maybe even 1.18.2 I'm not sure) you can generate structures via commands. I recommend upgrading to 1.18+ anyways since it has all the new features, however that is your choice.
> 
> > Another possibility that i thought, was copying the player data (inventory) in a new world generated with CWSM. Is that possible?
> 
> Yes, just make sure you have the exact same mod list when regenerating a world. I'm not exactly sure how you to copy player data so you'll have to figure that out (think it's just in a folder called "playerdata"). I believe copying the playerdata folder will also cause your position to be transferred as well, so you may spawn inside blocks or in the sky. So beware. Good luck!

It dose t work with the house, though

**Comment by nonamecrackers2** [comment]
Just realized it may be due to how it can only spawn at 0, 0.

**Comment by nonamecrackers2** [comment]
Allowing the structure command to generate the house in other locations instead of the 0, 0 chunk would not be very feasible without some internal code rewriting/bypassing which I am not up to. You can always use the command to generate it at 0, 0 then /clone it somewhere else or use worldedit.
