### ISSUE TITLE
Compatibility With "Essential" Mod

### ISSUE THREAD

**Issue by XLordGaster** [nonamecrackers2/crackers-wither-storm-mod#712]
**The version of Minecraft the mod is running on**
1.16.5 (1.16.5-forge-36.2.33 if we are being really specific)

**Mod version**
witherstormmod-1.16.5-1.0.2.4 (Although any version of CWSM for 1.16.5 has caused the same exact issue)

**Describe the bug**
The mod causes many things to not be rendered. Just having CWSM and the "Essential" mod (the mod that allows easy multiplayer)  makes all particles and all entity models to not render. Everything from your own playermodel to every mob in existence is invisible/not rendered. When you break blocks they just disappear because none of the particles from them breaking are visible.

**To Reproduce**
1. Have the "Essential" mod (link: https://www.curseforge.com/minecraft/mc-mods/essential-mod)
2. Have CWSM
3. Load a world and you won't be able to see any entities or anything other than blocks pretty much.

**Crash Reports / Logs**
Game doesn't crash

**Is Flywheel's optimizations active?**
Flywheel was not used

**Screenshots**
![image](https://user-images.githubusercontent.com/67292840/194947411-92901400-6fd8-4515-8022-e4cd7044ec0a.png)
I'm in third person and holding a lava bucket but it's all not visible.
![image](https://user-images.githubusercontent.com/67292840/194948324-b8ed7e95-cd4b-431c-a10d-4b1d4ec8c498.png)
I'm looking at a horse, which you can see due to a healthbar mod (Torohealth) I have, but you can't see it in the world, and again can't see that I'm holding something because my arm and the spawn egg both don't render.
![image](https://user-images.githubusercontent.com/67292840/194950130-3d6a4c31-0793-4af7-acc4-44c20d1d1045.png)
I'm looking at a giant zombie and once again, can't see it, but I am looking at it because you can see the healthbar in the top left corner. You also can't see the book in my hand even though I'm holding it.

**Comment by nonamecrackers2** [comment]
Does this happen without CWSM?

**Comment by XLordGaster** [comment]
No, this issue doesn't happen without CWSM, I have played with essential for a while now and have had many other mods with no issues. As soon as I added CWSM, this issue presented itself. I even went out of my way to strictly test just CWSM and Essential together and the same issue appeared so I can confirm it is an issue with CWSM and Essential.

**Comment by OliversIntention** [comment]
I would also like to see an Essential mod compatibility.

**Comment by ShadeKage** [comment]
Same here, this mod is very important for several people to be able to play multiplayer without buying a server, I think more than the one person making their modpack would be VERY happy

**Comment by Joshowa5** [comment]
> Does this happen without CWSM?

I do remember playing with this mod without CWSM and I had the same issues but it could have been another mod but I have no idea

**Comment by nonamecrackers2** [comment]
Fixed in the latest 1.16.5 version
