### ISSUE TITLE
Make the command block hittable if all tentacles are killed without killing all the heads.

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#714]
I would love to add this because when you kill all tentacles protecting the command block its no longer protected and can be hitted without having to kill wither storm heads. And also, I want new advancement called "No longer protected" when you kill all the tentacles around the command block first without killing all the heads.

**Comment by nonamecrackers2** [comment]
You can't kill the tentacles surrounding the command block, which is intended. Making them killable is not in my best interests as it would remove the quick thinking aspect of jumping on to the platform and dealing a quick, swift blow.
