### ISSUE TITLE
Any right click animation gives "Is it the end??" Award

### ISSUE THREAD

**Issue by dgc0312** [nonamecrackers2/crackers-wither-storm-mod#716]
**Minecraft version**
1.19.2

**Mod version**
3.1

**Describe the bug**
When you do any action that does an animation with right click (eat throw an arrow etc) it gives you the "Is it the end??" award

**To Reproduce**
1. Get food/shield/bow
2. eat it/use it

![image](https://user-images.githubusercontent.com/107085380/195334693-7cb71602-7355-40c7-81f7-35105da61e2a.png)
![image](https://user-images.githubusercontent.com/107085380/195334800-7f31971d-45bc-4851-a718-db48c0ed7ea7.png)

**Comment by V0calgiant12** [comment]
#654

**Comment by ShadeKage** [comment]
AKA, this has already been reported before by another user, thanks anyways
