### ISSUE TITLE
Add a higher invulnerability to the WS upon respawn

### ISSUE THREAD

**Issue by ShadeKage** [nonamecrackers2/crackers-wither-storm-mod#717]
**Description of feature**
Make it so when you respawn, you are given immunity from being targeted for about a minute or so, and possibly a config to change this amount of time or turn it off fully
Reason: I have seen so many clips online of people getting spawn camped by the storm at spawn, myself included, and i feel this should be something given to avoid this, and with a config people can go back to how it currently is

If this is already a feature that i just didn't notice, then just add the config to adjust how long it lasts for then lol, thanks
**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
This has already been implemented in the latest (2.1 and 3.1) releases, however I'll consider the config option.

**Comment by nonamecrackers2** [comment]
This has been implemented in 3.2/2.2, forgot to close this
