### ISSUE TITLE
Bowels Is Null

### ISSUE THREAD

**Issue by TheNotZen364** [nonamecrackers2/crackers-wither-storm-mod#718]
**Minecraft version**
The version of Minecraft the mod is running on
1.19.2

**Mod version**
The version of the mod you are using
latest

**Describe the bug**
crashing 
**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.
https://pastebin.com/JceKuEE9

**Is Flywheel's optimizations active?**
Specify if Flywheel is installed and it's compat optimizations are enabled

**Screenshots**

(Error crashed with something about bowels is null)

**Comment by TheNotZen364** [comment]
More info this is the crash The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.getCapability(net.minecraftforge.common.capabilities.Capability)" because "bowels" is null

**Comment by TheNotZen364** [comment]
superflat only

**Comment by watersofnazareth** [comment]
https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod#:~:text=Superflat%20worlds%20will%20need%20to%20be%20reloaded%20after%20world%20creation%20to%20make%20sure%20that%20the%20bowels%20is%20loaded%20in%201.19
