### ISSUE TITLE
Spyglass achievement activating despite being nowhere near the witherstorm and not having a spyglass...

### ISSUE THREAD

**Issue by SolemnStag** [nonamecrackers2/crackers-wither-storm-mod#719]
**Minecraft version**

1.19.2

**Mod version**

3.1

**Describe the bug**

When using the mod, despite being nowhere close to the witherstorm and not having a spyglass on your person, the "Is it the end...?" achievement activates.

**To Reproduce**

1. Start up a new world
2. Spawn the witherstorm
3. Leave the witherstorm's vicinity and play for a while
4. The "Is it the end...?" achievement may randomly activate 

**Crash Reports / Logs**

N/A

**Is Flywheel's optimizations active?**

Flywheel is not installed.

**Comment by Globalfirestorm10** [comment]
this is a known bug

**Comment by Globalfirestorm10** [comment]
please close this issue

**Comment by nonamecrackers2** [comment]
#654
