### ISSUE TITLE
A bug with the wither storm head

### ISSUE THREAD

**Issue by KrukAdrian** [nonamecrackers2/crackers-wither-storm-mod#72]
So whenever i get sucked by the head and it tries to kill me, it is pretty hard to hit the head to let you go. Can you somehow make it easier?

**Comment by Loverxzc** [comment]
Just kick eye.

**Comment by nonamecrackers2** [comment]
You should just have to hit the hitbox. There’s also a random chance it may not work, and there is a delay between attempts.
