### ISSUE TITLE
Possible Bug: Wither Storm becomes impossible to outrun through conventional means upon phase change

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#720]
**Minecraft version**
1.18.2/1.19.2
**Mod version**
Latest

**Describe the bug**
When the Wither Storm accelerates, it becomes impossible to properly escape due to how fast it moves, forcing the player to use unorthodox strategies like kiting it in a boat with a shield in the ocean
**To Reproduce**
1. Wait for the phase change
2. Phase Change
3. Wither Storm becomes impossible to outrun
**Crash Reports / Logs**
N/A
**Is Flywheel's optimizations active?**
N/A

**Screenshots**
N/A

**Comment by Luke7381** [comment]
The wither storm im pretty sure is supposed to accelerate when a phase change occurs, in fact there is options in the options menu to change how fast it goes in certain situations.

**Comment by nonamecrackers2** [comment]
> The wither storm im pretty sure is supposed to accelerate when a phase change occurs, in fact there is options in the options menu to change how fast it goes in certain situations.

Correct. If you prefer it to not chase you, or to slow down its speed, the server config option has the options to change it.
