### ISSUE TITLE
Errors caused by withering storm attacking Gladiator

### ISSUE THREAD

**Issue by 48004800** [nonamecrackers2/crackers-wither-storm-mod#721]
https://www.curseforge.com/minecraft/mc-mods/mcdoom
1.19.2
mod:3.1.1
The withering storm could not really kill him. Gladiator's blood volume is empty, but  he didn't die

. You can't find him with the command, nor can the player kill him.
![2022-10-16_11 42 47](https://user-images.githubusercontent.com/78255094/196016868-152afbea-e071-4b66-908c-d4d68a757780.png)

Under normal circumstances, players can kill Gladiator

**Comment by watersofnazareth** [comment]
This should be opened up in https://github.com/AzureDoom/MCDoom/issues I don't think this is related to the Wither Storm

**Comment by 48004800** [comment]
> This should be opened up in https://github.com/AzureDoom/MCDoom/issues I don't think this is related to the Wither Storm

This happens only when the wither storm attacks Gladiator

I don't think it's likely to be the problem of doom
In other cases, Gladiator can be killed normally

**Comment by nonamecrackers2** [comment]
I'll have to look into it, but seems like an MCDoom problem.

**Comment by 48004800** [comment]
> I'll have to look into it, but seems like an MCDoom problem.

https://github.com/AzureDoom/MCDoom/issues/73
This does not seem to be a problem with DOOM MOD

DOOM recreated Gladiator. But the problem still exists

I suggest you set a more powerful attack for the wither Storm（It may solve this problem, and at the same time, it can make the Witherstom more powerful）

**Comment by nonamecrackers2** [comment]
Does not seem solvable on my end. Here's the code snippet that kills entities:

`target.hurt(DamageSource.mobAttack(this).bypassArmor(), Float.MAX_VALUE);`

Based off of the /kill command. Should be compatible with all mobs.
