### ISSUE TITLE
Tainte slime block

### ISSUE THREAD

**Issue by AzaelKurosaki** [nonamecrackers2/crackers-wither-storm-mod#722]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**
i was datamining through the MCSM file and found there is a block texture for a tainted slime block (idk if this image helps)

![obj_blockSlimeWitherA](https://user-images.githubusercontent.com/115914240/196020329-6d6266bb-9344-4e80-afe0-b119211d77b3.png)

**Comment by RandomGithubUser32** [comment]
That might be for the prison slime mob in MCSM. I could be wrong though and it does seem like a good addition to the game.

**Comment by AzaelKurosaki** [comment]
> That might be for the prison slime mob in MCSM. I could be wrong though and it does seem like a good addition to the game.

The texture file says wither storm slime block (or something li that)

**Comment by RandomGithubUser32** [comment]
Ok cool

**Comment by watersofnazareth** [comment]
Probably won't do a actual slime block but I may try doing something with the tainted mushroom

**Comment by TheEyeOfGaming** [comment]
if theres a tainted slime block, there should be a sickened slime with it

**Comment by AzaelKurosaki** [comment]
![obj_blockSlime](https://user-images.githubusercontent.com/115914240/199105780-2e1afb0d-8e73-455f-97f2-26acb1d487b0.png)
found out that it is a slime block

**Comment by nonamecrackers2** [comment]
Slimes in CWSM are wither sickness immune (due to the vast amount of them in super flat worlds), and because of this tainted slime wouldn’t make sense
