### ISSUE TITLE
[Suggestion] Tentacle "coocon" 

### ISSUE THREAD

**Issue by bruhicantlogin** [nonamecrackers2/crackers-wither-storm-mod#723]
So i was watching very funny videos(don't ask me what were they about.) and i suddenly saw this
![image](https://user-images.githubusercontent.com/111668781/196021199-7abd2bb6-1d78-485e-97a8-fbddf3c903ae.png)
so i thought it would be cool that instead of just punching the player away, the tentacles on the insides could grab the player and start piercing him/hitting him like that.

**Comment by Loverxzc** [comment]
😏

**Comment by bruhicantlogin** [comment]
thats sussy my boy

**Comment by watersofnazareth** [comment]
This would end up killing the player cheaply and also give the player a chance to hit the command block again

**Comment by bruhicantlogin** [comment]
ah, ok

**Comment by RandomGithubUser32** [comment]
Maybe the tentacles could hold the player away from the command block and the tentacles could maybe toss the player away after piercing the player 2 times.

**Comment by nonamecrackers2** [comment]
I doubt with the current animation system this would be very feasible. Not only that it also takes away the tension of trying to reach the command block as you won't necessarily be slapped away. If they grab you and start stabbing you repeatedly, I could see this become frustrating to players.
