### ISSUE TITLE
[Suggestion] Pulling players out of the tractor beams

### ISSUE THREAD

**Issue by bruhicantlogin** [nonamecrackers2/crackers-wither-storm-mod#724]
idk if this has already been suggested but i think it would be cool if you could pull players out of the tractor beam to save them.
![image](https://user-images.githubusercontent.com/111668781/196021536-ac2a2ca1-7450-4b36-bb1e-6cabff13cfac.png)
also sorry by posting 2 suggestions real quick, its because i just thought of a better suggestion right after the first one.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/255
