### ISSUE TITLE
[Suggestion] Block cluster variant for blocks and items with uses

### ISSUE THREAD

**Issue by bruhicantlogin** [nonamecrackers2/crackers-wither-storm-mod#725]
instead of just removing items or blocks like crafting tables, maybe what if the crafting table and the item did instead get converted into a type of block cluster that you can still use? like per example, if you get pulled up together with a crafting table, you could move on the tractor beam towards it and use it normally, and for items? you could also move in their direction and pick them up
![image](https://user-images.githubusercontent.com/111668781/196022633-f0a08bfa-fff6-4c0b-86ef-013ee141e94c.png)
![image](https://user-images.githubusercontent.com/111668781/196022667-0a15c75f-3762-45ea-a2d6-3cb0f03b62f4.png)
this isn't on the title but i also think it would be cool if block clusters could damage and pull the player away if they did hit him while he was on top of it and being pulled by the tractor beam.

**Comment by bruhicantlogin** [comment]
also sorry again for making suggestions too quickly.

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/113

**Comment by watersofnazareth** [comment]
This would probably need a lot of things to be rewritten for something that wouldn't even be useful, but as Random said this is a duplicate

**Comment by bruhicantlogin** [comment]
did not know, sorry
