### ISSUE TITLE
Wither storm color customization

### ISSUE THREAD

**Issue by ROBOY6321** [nonamecrackers2/crackers-wither-storm-mod#726]
A way to change the color of wither storm

It will be possible to change the color of the storm and the color of the tractor beams, I wanted it in the mod because I was tired of changing textures in Photoshop and inserting into the mod

(i google translated this because i speak other language im sorry if something wrong there)

**Comment by KrukAdrian** [comment]
So you want a custom color picker for the wither storm and tractor beam beacuse you dont want to edit in photoshop?
I don't think the creator will add that

**Comment by OliversIntention** [comment]
Yeah, sounds like lazy.

**Comment by bruhicantlogin** [comment]
why do you even want to change the colors of the wither storm 💀

**Comment by FrozenDragon0** [comment]
A feature to change the storm's color just because you can't be bothered editing in photoshop?

Sorry but that's just being lazy.

**Comment by ROBOY6321** [comment]
Lazy? i just wanted a faster way to change the color for the wither storm it takes 30 minutes to draw a really good png texture and it's annoying what if i don't want to spend so much time to change the color of the wither storm? why should i spend so much time it will be much easier

**Comment by GrandmaPork** [comment]
There’s no need for this. The work to put in the slider would likely be much more on his end than yours.

**Comment by Globalfirestorm10** [comment]
Seriously? There's no way he's gonna add an entire colour editor just for your laziness

**Comment by watersofnazareth** [comment]
Just make a resourcepack there's really no point in this being added at all it's not worth the time and effort for someone's laziness
