### ISSUE TITLE
Tractor beam color config

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#727]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**
Tractor beam config to change the colors and the particle colors as well, you should be able to change the color using a set number of presets to choose from, or you can enter a hex code

**Comment by GrandmaPork** [comment]
This can be done with a resource pack

**Comment by Nov1st2k10** [comment]
It would be much easier with a config

**Comment by bruhicantlogin** [comment]
why EXACTLY do you want to change the color of the tractor beam 💀

**Comment by Nov1st2k10** [comment]
more color accurate to story mode

**Comment by ROBOY6321** [comment]
i would like that

**Comment by Globalfirestorm10** [comment]
I'd actually like this to be implemented, seems like a nice idea.

**Comment by watersofnazareth** [comment]
From what I know it's currently impossible to change the beam texture but this shouldn't be done through configs, it should be texture based if Crackers does decide to change this

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
