### ISSUE TITLE
Very rare Villages / trees in bowels

### ISSUE THREAD

**Issue by Aimyx** [nonamecrackers2/crackers-wither-storm-mod#728]
**Minecraft version**
1.18.2 / 1.19

**Mod version**
latest

**Describe the bug**
In all the times i defeated the storm, i never ran into the villages / trees that spawn in the bowels and the pillars that appear in the center never shown up either

**To Reproduce**
Keep spawning and entering the ws and there wont be these structures that often.

**Crash Reports / Logs**
no crashes

**Is Flywheel's optimizations active?**
No

**Screenshots**
none

**Comment by HenryDeez** [comment]
This is intended

**Comment by Luke7381** [comment]
You can use datapacks to increase the chances if you want.

**Comment by Aimyx** [comment]
oh.
How do I use a data pack? Because i have absolutely no idea what that is and how to use it.

**Comment by nonamecrackers2** [comment]
https://minecraft.fandom.com/wiki/Data_pack
