### ISSUE TITLE
Tainted gravel

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#729]
I seen this capture it was from minecraft story mode and if you do not want to rework the gravel you could just place the gravel inside the bowel. This new block makes the bowels look much better/

Here's the picture
![image](https://user-images.githubusercontent.com/111523734/196756619-e521873f-ad83-4476-825c-7dbef5e0dacd.png)

**Comment by TheEyeOfGaming** [comment]
nice idea

**Comment by TheEyeOfGaming** [comment]
Nice idea, cracker could use the old gravel texture and make it pink, would look cool in the bowels!

**Comment by NinjaSam5399** [comment]
I would love these.

**Comment by theemeraldsword85** [comment]
I think that's what tainted sand was intended to be

**Comment by watersofnazareth** [comment]
Forgor about this, this'll be in 4.3

https://cdn.discordapp.com/attachments/987821961059123241/1300914457081544724/image.png?ex=67330d40&is=6731bbc0&hm=c4c0821debb48f5e3e59b23a0ee9bc67c7df146d1a3051a9b81bcb1d402f2a4e&
