### ISSUE TITLE
Segment invulnerability rework

### ISSUE THREAD

**Issue by RandomGithubUser32** [nonamecrackers2/crackers-wither-storm-mod#730]
When the wither storm invulnerability option is turned off in the latest version, it feels kind of weird having arrows and other projectiles hit and damage the wither storm but harmlessly bounce off the segments. A solution would be to make the segments "take damage" but not lose any health just like entities with resistance 5 or when a snowball hits an entity.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
