### ISSUE TITLE
Some cool updates

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#731]
1. wither storms bowels would have a more vibrant cave system like a maze. except there would me a straight path to the command block still.
2. with the bowels idea you can find some "withered diamonds" around with these you can make the wither diamond armor set, when max armor, thorns will automatically be put on all armor, when a enemy hits you they will be given the effect withering. also can be turned into withered netherite armor. there would not be a tool set for this.
3. outside of the wither storm bats will spawn in phases 5-7 to show the sky darkening.
4. in the final battle mobs should come through the wall other then just spawning there.

**Comment by GrandmaPork** [comment]
2nd one would work pretty well if it just had more durability actually. Maybe a addon but I think it makes fighting the witherstorm pretty rewarding besides a new beacon

**Comment by Globalfirestorm10** [comment]
1. Crackers wants to keep the bowels barren
2. Probably not gonna happen
3. This would be useless, as the WS would just get distracted by the bats, and the bats would cause more performance issues along with the ton that are still there
4. I like this idea, may be hard to implement though

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/272

**Comment by ghost** [comment]
1. sounds lazy
2. WOULD BE COOL
3. just make the wither storm not attack bats. 
4. cool

**Comment by Globalfirestorm10** [comment]
> 1. sounds lazy
> 
> 2. WOULD BE COOL
> 
> 3. just make the wither storm not attack bats. 
> 
> 4. cool

1. Eh, not entirely, the bowels are supposed to be barren, and devoid of any life, other than the few withered undead mobs. This is the whole point of them

2. True, but Crackers has already rejected this many times

3. Doubt it will happen, as the bats would have to be an entirely new entity the WS doesn't attack, and there's much more that I think cracker can explain

**Comment by nonamecrackers2** [comment]
1. #272 
2. Adding new minerals and armor sets will not be happening.
3. Don't really want to mess with mob spawning as it could have potential unforeseen consequences (bats may clog the mob cap)
4. Would be hard to implement, would also require some animating which is not worth my time.
