### ISSUE TITLE
Command Block Armor

### ISSUE THREAD

**Issue by CappyKid** [nonamecrackers2/crackers-wither-storm-mod#732]
"With the power of the command block books, the most bravest and talented warriors can merge their diamond armor to create a new armor set."
Basically, the Command Block Armor is basically like Netherite Armor except with more knockback resistance. Also, a few bugs in the 1.19.2 update. The Wither Storm won't pick up the Formidibomb in either gamemode. Please fix the bugs whenever you can and maybe consider Command Block Armor.

**Comment by ghost** [comment]
no

**Comment by OliversIntention** [comment]
Useless, unneeded, and not even part of the MCSM series.

**Comment by Globalfirestorm10** [comment]
already suggested, and denied, please close this

**Comment by TheEyeOfGaming** [comment]
very bad idea, never make dumb ideas like this, command block armor would be annoying to obtain and useless

**Comment by CappyKid** [comment]
Yeah you're right. Scrap this idea.

**Comment by nonamecrackers2** [comment]
#321. Also no need to berate the suggestion, provide constructive criticism instead of bringing someone down. Also please separate suggestions from bug reports.
