### ISSUE TITLE
Sickened Spiders Compatible with Nyf`s Spiders mod

### ISSUE THREAD

**Issue by TheEyeOfGaming** [nonamecrackers2/crackers-wither-storm-mod#735]
**Description of feature**
Make the sickened spiders able to climb and stuff with this mod that is a 1.19 port of spiders 2.0
https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders
Would be cool for the sickened spiders with this mod, when in the bowels they all climb towards you when you build towards the command block.
**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Aimyx** [comment]
One word. yes.

**Comment by Globalfirestorm10** [comment]
This would probably be done by allowing the game to look for the animation overhaul for spiders, but there would still be incompatiblilites

**Comment by nonamecrackers2** [comment]
May not be possible but will have to look into it.

**Comment by nonamecrackers2** [comment]
Implemented in 2.2.1/3.2.1
