### ISSUE TITLE
F-bomb exploding witherstorm but leaving a massive crater

### ISSUE THREAD

**Issue by Bagheera68** [nonamecrackers2/crackers-wither-storm-mod#736]
The version of Minecraft the mod is running on 1.19.2, Its a bug report.

The mod version is 3.1.1

When you use the f-bomb, the tractor beam does not pick up the f- bomb and it still blows up the witherstorm also leaving behind a massive crater.

Flywheel is not active

**Comment by TheEyeOfGaming** [comment]
nice idea

**Comment by GrandmaPork** [comment]
This an idea or a bug report

**Comment by Bagheera68** [comment]
Oh sry its a bug report

**Comment by Bagheera68** [comment]
Oh sry its abut report

**Comment by Bagheera68** [comment]
Ill include images when I can.

**Comment by CappyKid** [comment]
Yeah that happened to me too

**Comment by Bagheera68** [comment]
I just wonder if its fixable

**Comment by GoldSlimeling91** [comment]
The wither storm doesnt even pick up the bomb is whats happening here, thats why it leaves the crater behind

**Comment by ChrisLTheNerd** [comment]
That was fixed for 1.19.2 in the latest version of the mod which is [witherstormmod-1.19.2-3.1.1]  4 days ago. I played it and I can confirm it.

**Comment by Bagheera68** [comment]
Im playing 3.1.1 and its still happening

**Comment by Globalfirestorm10** [comment]
this is intentional

**Comment by Bagheera68** [comment]
So the wither storm isnt suppost to pick it up anymore?

**Comment by ChrisLTheNerd** [comment]
Yeah, it's supposed to still pick it up. It just still leaves a crater if it's too close to the ground

**Comment by nonamecrackers2** [comment]
It is supposed to pick it up and this is an issue with the Essentials mod, if you have it.

**Comment by Bagheera68** [comment]
I dont have the essentials mod.
Tell me if theres something I can do.

**Comment by nonamecrackers2** [comment]
If you could send screenshots or even a video of you picking it up that would be extremely helpful

**Comment by Globalfirestorm10** [comment]
> So the wither storm isnt suppost to pick it up anymore?

Sorry, I was talking about the crater

**Comment by Bagheera68** [comment]
![2022-10-25_19 39 01](https://user-images.githubusercontent.com/114000728/197908086-66863e0c-5539-45e0-946c-cf15275d870a.png)
![2022-10-25_19 39 07](https://user-images.githubusercontent.com/114000728/197908103-eede937b-11a0-4a87-8c77-e7458a5372f3.png)
![2022-10-25_19 39 08](https://user-images.githubusercontent.com/114000728/197908115-b3c8f459-1b0b-4c51-9b9a-ffbc1707e52a.png)
![2022-10-25_19 39 17](https://user-images.githubusercontent.com/114000728/197908130-2a6592c3-d8e7-4327-b668-1a493e18c454.png)

**Comment by Bagheera68** [comment]
> Sorry, I was talking about the crater

All good.

**Comment by Bagheera68** [comment]
Tell me if theres a solution.

**Comment by nonamecrackers2** [comment]
Will do. This behavior is really peculiar.

**Comment by Bagheera68** [comment]
Ok

**Comment by ChrisLTheNerd** [comment]
> That was fixed for 1.19.2 in the latest version of the mod which is [witherstormmod-1.19.2-3.1.1] 4 days ago. I played it and I can confirm it.

Well I was wrong, it seems I have the same issue and I just probably mistook it for the 1.18.2 version. It's only picking up the F-bomb in 1.18.2 and just leaving it on the ground in 1.19.2.
![2022-11-01_14 39 59](https://user-images.githubusercontent.com/50182206/199312564-14b1bd90-b25e-487e-aef3-28fd11309e0f.png)
![2022-11-01_14 40 03](https://user-images.githubusercontent.com/50182206/199312505-5d946ddf-6a2a-4add-b288-5e0555fde010.png)
![2022-11-01_14 45 41](https://user-images.githubusercontent.com/50182206/199313908-85ba1b85-4c20-4673-8ae8-a7164cc24a3b.png)

**Comment by OliversIntention** [comment]
happened to me too, 1.19.2 with no essentials mod

**Comment by Bagheera68** [comment]
Yeah so this is a clearly common bug, good we reported it!

**Comment by Krypton6167** [comment]
I find something even more strange, when I am in survival and the wither storm picks me up with its tractor beam, as soon as I set off the bomb it goes away than I light up 64 fireworks and they STILL ignore me!

**Comment by Krypton6167** [comment]
So I guess the witherstorm is smart and doesn't pick it up, huh?

**Comment by Globalfirestorm10** [comment]
> I find something even more strange, when I am in survival and the wither storm picks me up with its tractor beam, as soon as I set off the bomb it goes away than I light up 64 fireworks and they STILL ignore me!

Fireworks are supposed to distract the wither storm, that's a feature

**Comment by Globalfirestorm10** [comment]
> So I guess the witherstorm is smart and doesn't pick it up, huh?

no, this is a bug

**Comment by Bagheera68** [comment]
Any updates?

**Comment by myron-obsolete-account** [comment]
This issue has the most comments here wow

**Comment by nonamecrackers2** [comment]
Fixed in 3.2

**Comment by myron-obsolete-account** [comment]
> Fixed in 3.2

🧀
