### ISSUE TITLE
Make a Withered Variants of these Mobs (Withered Creepers, Withered Zombies, Withered Skeletons, and Withered Spiders) have a Different Spawn Eggs Color.

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#737]
Rather than a confusing spawn eggs, and having a same color for withered creepers, withered zombies, withered skeletons, and withered spiders. You should redesign the color of these mob so it does not look so same quality.

**Comment by ghost** [comment]
no too hard.

**Comment by nonamecrackers2** [comment]
#459

**Comment by NinjaSam5399** [comment]
ok
