### ISSUE TITLE
Purple Debris Around the Wither Storm.

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#738]
When I watched minecraft story mode season 1, I discovered a purple debris flying around like debris flying around the wither storm. But also, the purple debris is only at phase 6. but then it disappears at phase 7.

Here is the picture I found:
![image](https://user-images.githubusercontent.com/111523734/197243089-2ad37e73-dea0-4787-9912-613cd2e0b1a3.png)

**Comment by RandomGithubUser32** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/63

**Comment by Luke7381** [comment]
It isn't really debris more like "wounds", and also this had been suggested already.

**Comment by NinjaSam5399** [comment]
oh

**Comment by NinjaSam5399** [comment]
but it was flying around the wither storm.

**Comment by Aimyx** [comment]
it was resucking them in, to recuperate

**Comment by NinjaSam5399** [comment]
yup

**Comment by bruhicantlogin** [comment]
im pretty sure those are particles from the tractor beam

**Comment by NinjaSam5399** [comment]
they are not from the tractor beams

**Comment by Resuster** [comment]
btw those are particles not debris
