### ISSUE TITLE
Config Option for attacking the command block with any weapon

### ISSUE THREAD

**Issue by anIceyGirl** [nonamecrackers2/crackers-wither-storm-mod#739]
**Description of feature**
Pretty self-explanatory, hopefully. A config option that allows you to attack the command block with any weapon, or perhaps a specific set of weapons?

**Comment by nonamecrackers2** [comment]
You can do this already via the command block tools tag. You'll need to make a datapack to override it, put in your own items, and then it should work. The only issue is that the command block particles will spawn around your item when dropped.
