### ISSUE TITLE
ultimateTarget "None" command not working

### ISSUE THREAD

**Issue by OliversIntention** [nonamecrackers2/crackers-wither-storm-mod#740]
**Minecraft version**
1.18.2 Forge 40.1.73

**Mod version**
Latest Version of 1.18.2

**Describe the bug**
When setting the ultimateTarget to "None," instead of it sitting in place and not rotating, it continues to follow me.

**To Reproduce**
1. Wither Storm phase (1-3 Maybe) 4-7
2. Do ultimateTarget command and set it to "none"
3. See error

**Crash Reports / Logs**
None, but here are screenshots of the World Settings: 
https://gyazo.com/63b4cfcf38d191baa08324565ae7db58
https://gyazo.com/df1c4811e3323ff309932e78b337b72b
https://gyazo.com/78ec893934209181f84be000dd274888
https://gyazo.com/a471f81d7493fe802577e2584954fb1b
https://gyazo.com/9f8b063bb604a7d90cf6aabe21f2def6

**Is Flywheel's optimizations active?**
Flywheel Setting screenshots: https://gyazo.com/8ff1ecd81aaa643ff8547b197ee67531

**Screenshots**
lol i did it already

**Comment by nonamecrackers2** [comment]
Ahh sorry guess I probably mentioned the wrong setting to set. You have to set the "Ultimate Target Type" in the server config to "NONE" instead of using the command. Sorry for the confusion, that would be why it's not working :P
