### ISSUE TITLE
/witherstormmod Head

### ISSUE THREAD

**Issue by ISLANDBANE** [nonamecrackers2/crackers-wither-storm-mod#742]
/witherstormmod head command.
You can deactivate heads, reactivate them
And they are marked as 1 2 3
In phase 7 it’s 9
Could potentially be a useful command for creative users****
****THERE MAY BE A FEW ISSUES HOWEVER****
p.s it could be amazing to see this in the game

**Comment by KrukAdrian** [comment]
why did you cclose this

**Comment by ISLANDBANE** [comment]
> why did you cclose this

I did not? No idea why it did

**Comment by nonamecrackers2** [comment]
You could use the /data command to bring them back. You'll have to set their health back (/data set entity @e[type=witherstormmod:wither_storm_head,limit=1,sort=nearest] Health set value <number>) and then modify the tag that controls their "hurt" state (can't remember the exact name).

**Comment by ISLANDBANE** [comment]
> You could use the /data command to bring them back. You'll have to set their health back (/data set entity @e[type=witherstormmod:wither_storm_head,limit=1,sort=nearest] Health set value ) and then modify the tag that controls their "hurt" state (can't remember the exact name).

Yes but I meant like deactivating for certain times or stuff like that…

**Comment by nonamecrackers2** [comment]
Just do the above but set the "hurt" state to true
