### ISSUE TITLE
wither storm end dimension bowels crash

### ISSUE THREAD

**Issue by mmiller9196** [nonamecrackers2/crackers-wither-storm-mod#743]
1.18.2

wither storm crashes when bowels open up in the end dimension

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.getCapability(net.minecraftforge.common.capabilities.Capability)" because "bowels" is null

**Comment by nonamecrackers2** [comment]
If you type "/execute in", what dimensions pop up? Can you also provide the entire crash report?

**Comment by watersofnazareth** [comment]
Isn't this the crash related to flat worlds

**Comment by Globalfirestorm10** [comment]
Yeah

**Comment by nonamecrackers2** [comment]
Closing until further information is given
