### ISSUE TITLE
WitherStorm Glows in Dark

### ISSUE THREAD

**Issue by TheEyeOfGaming** [nonamecrackers2/crackers-wither-storm-mod#744]
**Description of feature**
In Mcsm when the witherstorm is at Phase 4, he glows a light blue
![image](https://user-images.githubusercontent.com/114343289/197812104-1b475e6a-aac0-4bb0-bdd9-32313f529029.png)
adding that the witherstorm makes a light blue glow around his body makes him easier to see at night, and make him not look invisible with the only thing you see are its tractorbeams.

**Comment by Globalfirestorm10** [comment]
I actually really like this suggestion

**Comment by ghost** [comment]
this would allow for seeing the wither storm better at night other then 3 purple lasers coming from no where

**Comment by ROBOY6321** [comment]
yes please i want this

**Comment by nonamecrackers2** [comment]
#145. Not the same colors but same idea.
