### ISSUE TITLE
Spyglass Achievement When the Witherstorm isnt summoned

### ISSUE THREAD

**Issue by TheEyeOfGaming** [nonamecrackers2/crackers-wither-storm-mod#745]
**Minecraft version**
1.19.2

**Mod version**
Latest

**Describe the bug**
When you look into the spyglass when the witherstorm isnt summoned yet, it gives you the achievement regardless.

**Screenshots**

![2022-10-25_19 16 12](https://user-images.githubusercontent.com/114343289/197828929-9a391c81-0cb6-4cd8-aaa6-4bc1d3fd5d93.png)

The achievement should be granted when the witherstorm is summoned and then you look throught the spyglass.

**Comment by Globalfirestorm10** [comment]
This is a known bug, but i'm pretty sure it was resolved already, are you using the latest update?

**Comment by TheEyeOfGaming** [comment]
yes the latest 1.19.2 update

**Comment by nonamecrackers2** [comment]
This has been fixed.

**Comment by nonamecrackers2** [comment]
Can you please specify which mod version you're using exactly?

**Comment by TheEyeOfGaming** [comment]
1.19.2 version 3.1.1, it still does the bug where it gives the "is it the end" achievement when using the spyglass, even though the witherstorm isnt summoned yet

**Comment by rafaelkai** [comment]
Can confirm this still happens on the latest version.

**Comment by nonamecrackers2** [comment]
Fixed in 3.2
