### ISSUE TITLE
Ivors potion

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#746]
please add ivors potion from mcsm, make sure that it can only kill a wither storm if it hits the command block, and so in phase 3+, you can't kill it with the potion, to craft it should take a potion of healing in the middle, and then gold around it. the reason its a potion of healing is because, obviously, only potions of healing can do damage to a wither storm, not harming potions. anyway, hope ya add this in.

**Comment by ghost** [comment]
#217

**Comment by watersofnazareth** [comment]
Just gonna say, use the search function of github
#445 #450 #276 #350 #464 #315 #175 #65 #66 #691

**Comment by Krypton6167** [comment]
sorry guys didn't know he wasn't gonna add it.
