### ISSUE TITLE
obsidian witherstorm

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#747]
in Minecraft story mode you can see the wither storm made out of obsidian, you can clearly see this here:
https://www.youtube.com/watch?v=cdfxxxZfbSM&t=120s
maybe make it made out of obsidian with the texture.

**Comment by watersofnazareth** [comment]
This isn't actually correct, this is the only occurrence of this happening in the game and I will not be changing the texture for it

**Comment by ghost** [comment]
change it yourself. texture packs

**Comment by KrukAdrian** [comment]
I can make a texture pack

**Comment by KrukAdrian** [comment]
[Wither storm Obsidian Texture.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9893590/Wither.storm.Obsidian.Texture.zip)
I have made it

**Comment by KrukAdrian** [comment]
[Wither storm obsidian.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9893635/Wither.storm.obsidian.zip)
I have made it

**Comment by ROBOY6321** [comment]
> [Wither storm obsidian.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/9893635/Wither.storm.obsidian.zip) I have made it

thank you :Dd;s;dd;;dd; :skull: i really needded it
