### ISSUE TITLE
exp drop

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#748]
when the wither storm dies it should drop a ton of exp, it should drop about as much exp as the ender dragon in phases 0-3. but in phase 4+, it drops a boatload of exp when it dies.

**Comment by FrozenDragon0** [comment]
I'm pretty sure this has already been added into the recent update, if not then it's already been suggested.

**Comment by ROBOY6321** [comment]
isnt is that already in game?

**Comment by Krypton6167** [comment]
oh, it is, sorry.
