### ISSUE TITLE
new death animation.

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#749]
so, I know this is Netflix only, but I think it'd be a nice tweak. in Minecraft story mode, specifically HERE: https://www.youtube.com/watch?v=dv1lK47IgBk&t=2125s before the wither dies it should light up pink, and then explode, I just think the aspect looks cool.

**Comment by ghost** [comment]
no too bright. goofy. like the current one more.

**Comment by ROBOY6321** [comment]
i like this

**Comment by Globalfirestorm10** [comment]
I think the current death animation is better than this

**Comment by nonamecrackers2** [comment]
Believe this was already suggested before however I can't find it. Changing the death animation is not priority and isn't in my best interests as of now, and I feel making it light up and glow would be extremely difficult to do right from a code standpoint. Hope you understand.

**Comment by V0calgiant12** [comment]
Could do it the same way you did the overlay texture for Wither Sickness, except have the fade in happen really fast and change the overlay to be just pure white. The only problem I see with this method is the flywheel compatibility model and how the overlay would work for that, if at all.
