### ISSUE TITLE
New death animations for phase 0-3 

### ISSUE THREAD

**Issue by KrukAdrian** [nonamecrackers2/crackers-wither-storm-mod#75]
Im thinking that the wither storm could maybe have a better death animation for phase 0-3 cause it is killable in those phases. So it could be a death animation like phase 7 or something else.

**Comment by nonamecrackers2** [comment]
It's not designed to be killable in the smaller phases, and I don't want to add anything special to it's death or else people will try to defeat it, which is not intended.
