### ISSUE TITLE
Wither storm music bug

### ISSUE THREAD

**Issue by ROBOY6321** [nonamecrackers2/crackers-wither-storm-mod#752]
**Minecraft version**
This happens on any version

**Mod version**
latest

**Describe the bug**
This happens randomly when near wither storm also i have giant freeze before this happens

**To Reproduce**
must have slow computer

**Crash Reports / Logs**
i didnt looked in

**Is Flywheel's optimizations active?**
nop

**Screenshots**
nop

omg you found secret message:
:skull:

**Comment by Globalfirestorm10** [comment]
There is little to no info about this "bug", please tell us more

**Comment by ROBOY6321** [comment]
this is happens on higher stages if i have alot of lag more chance of sounds gone

**Comment by ROBOY6321** [comment]
also this happend on both slow computers i tried it on good computer it works perfectly fine

**Comment by nonamecrackers2** [comment]
Go to the client config menu and press the "refresh sounds" button in the top left corner.

**Comment by ROBOY6321** [comment]
> Go to the client config menu and press the "refresh sounds" button in the top left corner.
then it happens again :skull:

**Comment by nonamecrackers2** [comment]
That is most likely due to your hardware, causing Minecraft to freeze periodically causing sounds to cut out.
