### ISSUE TITLE
Yellow tractor beam

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#754]
1.19.2 - The sky darkens

so for some reason, the tractor beams seem to turn yellow instead of purple, bug, or feature?
**Is Flywheel's optimizations active?**
No

**Screenshots**
![2022-10-31](https://user-images.githubusercontent.com/116845536/199084232-2264b04b-f4d7-432b-ba20-5f091206a94e.png)

**Comment by TheEyeOfGaming** [comment]
thats odd

**Comment by Krypton6167** [comment]
I know, and honestly, I'm not sure not having flywheel causes the problem, I tried looking at the wither storm optimization but for some reason, it just doesn't work.

**Comment by V0calgiant12** [comment]
It's for Halloween, if you set your computer's date 1 day ahead/behind it goes back to normal

**Comment by KrukAdrian** [comment]
WAIT ITS FOR HALLOWEEN?

**Comment by Krypton6167** [comment]
oh, nice

**Comment by nonamecrackers2** [comment]
> WAIT ITS FOR HALLOWEEN?

Yep :)

**Comment by OliversIntention** [comment]
does it change for christmas

**Comment by Asteroid4** [comment]
> does it change for christmas

if not, plz add it. Alternating red/green beams ftw!
