### ISSUE TITLE
The Better Bowels/The Bowels Update.

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#755]
I find out that there are just planks, and I wish I could have this to craft stairs, planks, slabs, and boats. I also love to add withered trees, including wood, logs, and leaves. And I also want to have a village houses get withered instead of being very clean and fine. And finally I would really want to add pillager outpost inside the bowels.

**Comment by V0calgiant12** [comment]
the wood is already being added in the next update, however I think an outpost would be cool.

**Comment by BluePineappleGuy** [comment]
i think that the bowels structure should turn instead of the player, to make it similar to story mode

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
