### ISSUE TITLE
Spawned Wither Storm 20,000 blocks away/ crashed when it reached 10,000 blocks away when player is at 0 0

### ISSUE THREAD

**Issue by xroblox33** [nonamecrackers2/crackers-wither-storm-mod#756]
**Minecraft version**
The version of Minecraft the mod is running on 1.19.2

**Mod version**
The version of the mod you are using witherstormmod-1.19.2-3.1.1

**Describe the bug**
A clear and concise description of what the bug is. Spawned in a wither storm 20,000 blocks away then killed myself and wait for the monster to come to 0 0 were I built a large village for it to destory but when the wither reached 10000 blocks from 0 0 it crashed with no crash report

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is Flywheel's optimizations active?**
Specify if Flywheel is installed and it's compat optimizations are enabled

**Screenshots**
![Capture](https://user-images.githubusercontent.com/117233015/199354232-67c3fdb1-535d-4aa9-93c7-22a7c13a5f7e.PNG)

**Comment by xroblox33** [comment]
Not sure what happened, When I came back onto my world, The wither storm disappeared... That really disappointed me when it disappeared...

**Comment by Globalfirestorm10** [comment]
send the latest.log please, as this is needed (also if the latest.log was updated, find the old one)

**Comment by xroblox33** [comment]
I'm very new to this file stuff but the game crashed without a crash report witch was weird, The crashed never happened since, So I don't think this will be a problem anyway since probably the crash happens when your farther than 10,000 blocks from the wither.

**Comment by Globalfirestorm10** [comment]
A latest.log isnt a crash report, please send it from that time, go to .minecraft->logs-> and then find the log from the time it crashed

**Comment by nonamecrackers2** [comment]
Closing until more information is given.
