### ISSUE TITLE
Chaotic Wither Storm and faster growing speed

### ISSUE THREAD

**Issue by EndTheEnders164** [nonamecrackers2/crackers-wither-storm-mod#757]
The Wither Storm in this mod, even though it's pretty accurate and REALLY cool, I feel like the Wither Storm could be more chaotic like the original Wither boss. The Engender Mod has done this with the Wither Storm as well. And if the Engender Mod did it, so can this mod. I would also reccomend that the Wither Storm could also grow a little faster, by like, 25% or 50%. That's really all, and thanks for making this mod. I almost always wanted to make and fight the Wither Storm in Minecraft, ever since I first played Minecraft: Story Mode. This is the most accurate Wither Storm mod yet, and I am glad you made it.
See you around.

--Dimitrius Films

**Comment by Luke7381** [comment]
Having more chaos/destructivity had been suggested at some point

**Comment by EndTheEnders164** [comment]
Oh... Did Cracker confirm making this part of the mod?

**Comment by watersofnazareth** [comment]
Use the configs, this is a thing already

**Comment by NinjaSam5399** [comment]
Well its going to be too hard and its already in the config.

**Comment by EndTheEnders164** [comment]
> Well its going to be too hard and its already in the config.

I CAN'T BELIEVE I MISSED THAT LMAO💀
