### ISSUE TITLE
Configuration for how fast the tractor beams pull mobs

### ISSUE THREAD

**Issue by LyxiaSix** [nonamecrackers2/crackers-wither-storm-mod#759]
a new setting to configure how powerful/weak the pull of the wither storm's tractor beams would be pretty cool.

**Comment by Luke7381** [comment]
I actually suggested this at #624

**Comment by ROBOY6321** [comment]
kinda useless

**Comment by Loverxzc** [comment]
> вроде бесполезно

for maps?
