### ISSUE TITLE
(1.18.2) Worlds don’t load when using Distant Horizons

### ISSUE THREAD

**Issue by Swagboi7** [nonamecrackers2/crackers-wither-storm-mod#76]
Progress just stays at 100% and eventually gives you an error that acts as if you were on a server. (Server took too long to load)

**Comment by Swagboi7** [comment]
After some messing around, it turns out Distant Horizons itself is straight up broken with (I’m guessing) the latest version of Forge. This problem happens even when DH is by itself. Sorry.

**Comment by nonamecrackers2** [comment]
Ah ok. It's all good.
