### ISSUE TITLE
Alternative way to summon wither storm

### ISSUE THREAD

**Issue by ROBOY6321** [nonamecrackers2/crackers-wither-storm-mod#760]
**Description of feature**
You can summon wither storm by giving it a command block
you can get it from dungeons fishing etc
so you can get ready for wither storm instead of spawning it when you dont even have anything
small feature but i think its cool

:skull:

**Comment by watersofnazareth** [comment]
This would fall under #481

**Comment by ROBOY6321** [comment]
so quick

**Comment by ROBOY6321** [comment]
bruh
