### ISSUE TITLE
Players darkens when getting sucked up

### ISSUE THREAD

**Issue by Theoyeah** [nonamecrackers2/crackers-wither-storm-mod#762]
In Minecraft Story Mode (Netflix) when we can see Jesse unleash the formidibomb, he starts to get darken, we can also see that when the WS evolves to stage 4 in Chapter 1

I think it would be cool to see that in the mod too

**Comment by Theoyeah** [comment]
dang i just remembered this issue existed

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release

**Comment by Theoyeah** [comment]
Wowie !!!!
