### ISSUE TITLE
Models of Witherstorm are very unoptimized

### ISSUE THREAD

**Issue by User198263321** [nonamecrackers2/crackers-wither-storm-mod#764]
Mod: 3.1.1 1.19.2
Forge: 43.1.47

Hey, I was playing your mod and noticed that the Witherstorm models are very unoptimized and have many unused rendered faces that can be removed. Would you mind temporarily linking me the models so I can see if I can fix or improve them? No credits for me optimizing models if I do. This is on all stages of the Witherstorm. There are too much issues to screenshot all of them. I took one of the teeth because it is easy to see. Also, the large block segments that they pick up are not culled. Every block in it is rendered with all faces.

![image](https://user-images.githubusercontent.com/53535277/200127813-ed902b3b-fd6e-4165-a4fe-b08fa7fb1dce.png)

**Comment by Globalfirestorm10** [comment]
Do you have optifine, occulus, rubidium, essentials mod, or flywheel installed?

**Comment by User198263321** [comment]
> Do you have optifine, occulus, rubidium, essentials mod, or flywheel installed?

This doesn't matter but yes, I do for rubidium and flywheel. Doesn't change models.

**Comment by Globalfirestorm10** [comment]
true, but I'm talking about the texture glitches (i.e, the teeth), these are caused by flywheel optimization and rubidium

**Comment by User198263321** [comment]
> true, but I'm talking about the texture glitches (i.e, the teeth), these are caused by flywheel optimization and rubidium

Not a glitch. That's Z-fighting. 2 faces in the same location that overlap each other. Also, issue happens even when those mods are disabled.

**Comment by Globalfirestorm10** [comment]
I stand corrected

**Comment by Aimyx** [comment]
culling on the clusters is one of my favorite ideas, its probably half the reason they are so laggy.

**Comment by nonamecrackers2** [comment]
Culling was already attempted and implemented but was removed due to minimal performance gains (only around a 5 FPS difference). The issue is that each frame, the game iterates through all the faces and sends them to the graphics card for rendering each frame. Flywheel uploads the model data only once, causing significant performance boosts. This process is simplified but gets the point across. Thanks for offering though!

**Comment by User198263321** [comment]
> Culling was already attempted and implemented but was removed due to minimal performance gains (only around a 5 FPS difference). The issue is that each frame, the game iterates through all the faces and sends them to the graphics card for rendering each frame. Flywheel uploads the model data only once, causing significant performance boosts. This process is simplified but gets the point across. Thanks for offering though!

It definitely can vary depending on how fast or how low ticks you set for witherstorms to pick up block segments.
