### ISSUE TITLE
QOL ideas for world with multiple Witherstorms summoned or active

### ISSUE THREAD

**Issue by User198263321** [nonamecrackers2/crackers-wither-storm-mod#765]
Mod: 3.1.1 1.19.2
Forge: 43.1.47

When I have a Witherstorm summoned, I need to stay in creative for mobs to spawn and when I have multiple in final forms, they stay in the same spot and never move but they still rotate to me and follow even though I have pickup chance to 0 and prefer players off. I don't even have the amulet. Letting them kill me doesn't end me as target. They still target me. "Fixed" by setting target to none, but then they just stay still and never wander even with distraction settings on. Here are my ideas:

1. Option for Witherstorms to ignore players as the final target but still affected by (2.)
2. Configurable distance for summoned Witherstorms staying in a player's general area (so they don't completely wander off)
3. Final target can be set to random (so each summoned 'storm can spread out and not stay in the exact same location)
(Issue example: I take a time lapse of them destroying a world but they stay in the same spot as long as I don't move. Keeping them in general player distance means they don't just completely leave out of render distance if prior )
![image](https://user-images.githubusercontent.com/53535277/200132462-911b426d-11b5-4b07-a1dd-c5ed58c6e403.png)
Witherstorms are very close together.

#Issue? Final form doesn't seem to listen to distraction settings.
*Another option to check if land mobs are on the ground along with a seprate option to check if flying mobs are stuck in another 'storm's trackor bream. If checking for mobs in a beam won't slow the game down more than checking if they are on the ground, then just have one option to check if they are in a beam or not. This option is only applied when there are more than 1 'storm active in the world. This would prevent the 'storms from fighting over 1 mob
*option to have storms seperate or not merge themselves together to make it look like there is only one.

**Comment by User198263321** [comment]
Maybe some or all of this can be in a separate menu button that is "More than 1 Wither Storm Options"
![image](https://user-images.githubusercontent.com/53535277/200132785-0ce007a6-6084-47c8-8e8b-4a5dba594b12.png)

**Comment by nonamecrackers2** [comment]
> #Issue? Final form doesn't seem to listen to distraction settings.

I recommend making a separate issue for this. Also what distraction settings does it seem to ignore specifically?

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release (random strolling, that is)
