### ISSUE TITLE
Mob spawn cap options depending on how much Witherstorms are active (options can be disabled back to default behavior)

### ISSUE THREAD

**Issue by User198263321** [nonamecrackers2/crackers-wither-storm-mod#766]
Mod: 3.1.1 1.19.2
Forge: 43.1.47

I can't seem to find a mod that easily allows me to manage the spawn cap of mobs for 1.19.2 and I think it would make sense for this mod. Another cool thing could be an option that treats the Witherstorm as a player or in this case, letting the storm's presence spawn mobs around the 'storm itself (includes options to dynamically increase the mob cap depending on how many 'storms are spawned). This would also be helpful when spectating the world since the 'storms in this case can spawn mobs when the player can't since they are spectating.

This could be a separate tab of options called "Mob Spawn Options"
![image](https://user-images.githubusercontent.com/53535277/200133277-d0ef9d31-89ff-4d65-8a61-a9beadc9727e.png)

**Comment by nonamecrackers2** [comment]
I don't think it would be very feasible to make the Wither Storm influence mob spawns. Also building in mob spawn controlling into this mod might be a bit out of scope, you'll probably want to wait for a mod to be released that is dedicated to spawn control anyway.

**Comment by GrandmaPork** [comment]
If someone were to make this possible, I’d like to know
