### ISSUE TITLE
Reloading world causes block segments/clusters to form back into solid sections under the storm, raising it's height.

### ISSUE THREAD

**Issue by User198263321** [nonamecrackers2/crackers-wither-storm-mod#767]
Mod: 3.1.1 1.19.2
Forge: 43.1.47

Currently, when you reload a world, the block segments despawn where they were and form back to the world. However, they stay still and don't fall (at least some of them don't). I think that they should fall to the ground instead, forming mountains or function like sand until the reach the ground. I would like this change since the witherstorm won't just fly even higher since the blocks are there or be a pain to clean up since you need to tower to them. Hear me out:

![image](https://user-images.githubusercontent.com/53535277/200134188-4f7aeaca-bddf-4b74-907b-3250ff356d53.png)

When a world spawns with floating sand, the floating sand stays floating unless it gets updated by a neighboring block
When a world spawns with solid blocks, they stay floating unless broken, **placed**, or moved by a piston.
The Witherstorm doesn't break or place those blocks, it **removes them** from the world in order to absorb them, this behavior is not possible any other way in the game unless you use something like a piston; however, the piston stops after it extends or retracts, therefore, it makes the block solid again. Since the blocks are floating, it would only make sense if they fell since they were never placed or stopped in the first place. The only way they stop is when they are absorbed into the storm, which is a moving entity.

Or maybe this is bugged and this whole issue is an unintentional side effect.

**Comment by Globalfirestorm10** [comment]
already reported

**Comment by User198263321** [comment]
> already reported

What issue?

**Comment by Globalfirestorm10** [comment]
Nevermind, mixed up your issues with a different report

**Comment by nonamecrackers2** [comment]
Are the clusters not forming back to into blocks when they fall? If so that's unintended.

**Comment by User198263321** [comment]
> Are the clusters not forming back to into blocks when they fall? If so that's unintended.

Yes, they appear to just kind of spawn or accumulate on world reload. Block cluster pickup speed is maxed out though.

**Comment by nonamecrackers2** [comment]
Weird. Looks almost like they get stuck in the water possibly. I’ll mark this as a bug instead

**Comment by FrozenDragon0** [comment]
The water can be a bit annoying at times when the clusters are reverted back into blocks. Although not as annoying as Lava, if you let the storm dig down far enough or sucks up a lava lake and then you relog it just creates a mess of flowing lava which can be very annoying to clean up.

**Comment by Globalfirestorm10** [comment]
> The water can be a bit annoying at times when the clusters are reverted back into blocks. Although not as annoying as Lava, if you let the storm dig down far enough or sucks up a lava lake and then you relog it just creates a mess of flowing lava which can be very annoying to clean up.

I agree, but to be fair, you aren't really supposed to clean up the WS's path of destruction and mess, and if you are,it would take days to do so

**Comment by watersofnazareth** [comment]
#690 Didn't know this was a duplicate
