### ISSUE TITLE
Disable Bossbar in Config

### ISSUE THREAD

**Issue by SimpleWolf** [nonamecrackers2/crackers-wither-storm-mod#768]
**Description of feature**
Title says all pretty much. When playing with sound mods the distinct rumbling gets muffled underground, meaning that it's actually possible for a player to not realise the Wither Storm is right above them until they see the beast as they walk outside. However, the bossbar does make that surprise a bit difficult since it appears when the Wither Storm comes into range, having a config to disable that would be quite nice.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Aimyx** [comment]
Yes, exactly what I wanted, but  I think several people already requested this.

**Comment by nonamecrackers2** [comment]
We won't be adding a config to disable it outright however the new "smart bossbar" feature in 2.2/3.2 is probably what you want.
