### ISSUE TITLE
command block animations.

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#769]
Okay, so, hear me out, when you hit the command block in the bowels, it should light up a light purple and spew particles around it, like its energy is being released in an explosion, example:
https://www.youtube.com/watch?v=MAREvo6I7H4&t=452s
and no, this isn't specifically to make the mod more like Minecraft story mode, I just feel it makes the scenario feel a little more cinematic.

**Comment by OliversIntention** [comment]
i like it

**Comment by Aimyx** [comment]
me like

**Comment by nonamecrackers2** [comment]
The command block will now spew it's orange glow and extra particles will hit in the next major release
