### ISSUE TITLE
The game stopped working when I was testing the latest version of the mod (2.0-beta) for minecraft 1.18.2

### ISSUE THREAD

**Issue by Gaboamau** [nonamecrackers2/crackers-wither-storm-mod#77]
While testing the mod on a creative world to see if it worked, while the Wither Storm was at the end of phase 6 before moving on to phase 7, the game crashed and gave me this message:

The game crashed whilst ticking entity
Error: java.lang.StackOverflowError: Ticking entity
Error code: -1

Here is the full bug report:

[crash-2022-06-11_22.43.07-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/8885295/crash-2022-06-11_22.43.07-server.txt)

And if you ask for the list of mods, I only had the Wither Storm mod installed.

**Comment by nonamecrackers2** [comment]
Should be fixed in the next upcoming update
