### ISSUE TITLE
More wither segments

### ISSUE THREAD

**Issue by Krypton6167** [nonamecrackers2/crackers-wither-storm-mod#771]
**Description of feature**
"It seems the worst has happened... and more wither segments have appeared!"
possibly having more wither storm segments, maybe for more phases like phase 8 might be cool, and referencing to #701 they could all be scouting for prey, this, might be annoying and I understand if you won't add it, but I like having the wither storm be more destructive as it happens in Minecraft: story mode. and having some predictions for future phases would be cool.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Globalfirestorm10** [comment]
I believe this was suggested already, and was turned down

**Comment by MEMEBOyt** [comment]
I honestly wouldn't be a fan of that. I prefer the wither storm being accurate to story mode.

**Comment by Globalfirestorm10** [comment]
Same here, I don't like this idea

**Comment by nonamecrackers2** [comment]
More segments would cause more lag and some unintended side effects, especially considering how the current system is designed to only support two segments. Adding more could also bring back segment duplication.
