### ISSUE TITLE
An idea for skipping the night whilst the wither storm is active.

### ISSUE THREAD

**Issue by Terraver** [nonamecrackers2/crackers-wither-storm-mod#772]
Maybe when the player sleeps at night, the Wither Storm's ConsumedEntities jumps up a couple hundred to a couple thousand and skips into the next stages?

Would be cool to see the Wither Storm progress as days pass by.

**Comment by ROBOY6321** [comment]
that would be cool i wanted suggest that long ago

**Comment by Loverxzc** [comment]
disbalanced idea

**Comment by OliversIntention** [comment]
not sure how this is disbalanced,  I like this idea.

**Comment by TheEyeOfGaming** [comment]
maybe instead of the consumed entities idea, what if when the player sleeps the witherstorm goes 5x faster since the witherstorm is following you, and sleeping at night would give the witherstorm a advantage and get closer to you

**Comment by OliversIntention** [comment]
I was also thinking of this idea too ^^^ perhaps both? maybe only one though, since it would be disbalanced.

**Comment by Aimyx** [comment]
I like this, cool idea, but what about the destruction, would it be more or less, because if the wither storm is going fast, not many block clusters get sucked in, and if it is close, and you slept through the whole night, while the ws was growing, wouldn't it cause more destruction, witch would cause more lag?

**Comment by Terraver** [comment]
> I like this, cool idea, but what about the destruction, would it be more or less, because if the wither storm is going fast, not many block clusters get sucked in, and if it is close, and you slept through the whole night, while the ws was growing, wouldn't it cause more destruction, witch would cause more lag?

I was thinking the destruction would be more, but to make this more balanced, the Wither Storm wouldn't be too close to the player and killing them right off the bat, instead, 200-600 blocks away. Plus, the amount of blocks destroyed by the wither storm would be added to the ConsumedEntities rule to reduce lag. Say, if the Wither Storm is at Phase 3 with 1000 blocks in the ConsumedEntities rule, you sleep the night, the Wither Storm is around 486 blocks away, with the wither storm having more than 3000 blocks in the ConsumedEntities rule.

**Comment by nonamecrackers2** [comment]
This could mess with progression too much and I'd rather have other, more purpose built methods to speed up evolution

**Comment by GrandmaPork** [comment]
I believe there is a mod that speeds up ticks when you sleep. Try that out because it might give you the results you want
