### ISSUE TITLE
Early Stages target humanoid mobs

### ISSUE THREAD

**Issue by ourpleman** [nonamecrackers2/crackers-wither-storm-mod#773]
Make it so that the Wither Storm will target humanoid mobs (Villagers, Zombies, Skeletons, basicly any mob that stands on two legs) instead of animals. Its annoying when you want the Wither Storm to attack a village, but it just attacks random fish instead.

**Comment by OliversIntention** [comment]
It targets its nearest mob, just like a stage 4-7 tractor beam head. And I believe if you're in survival mode, it'll just come straight to you.

**Comment by Globalfirestorm10** [comment]
> It targets its nearest mob, just like a stage 4-7 tractor beam head. And I believe if you're in survival mode, it'll just come straight to you.

you're correct about survival mode, and it will always target the nearest mob, unless changed in the config

**Comment by nonamecrackers2** [comment]
The Wither Storm now prefers to target mobs with larger hitboxes in the latest release
