### ISSUE TITLE
Entity Type Tag to control what can/can't be picked up by tractor beams

### ISSUE THREAD

**Issue by notWaterGuy12** [nonamecrackers2/crackers-wither-storm-mod#774]
An entity tag for what can/can't be picked up would be very helpful for pack devs that want to fine-tune the fighting experience. Just as an example, they could add the player to the "can't be picked up" tag so they can fight anything spawning around the storm.

**Comment by Globalfirestorm10** [comment]
there are settings for the WS to ignore the player in the config iirc, but other than that, there is no blacklist, I think a blacklist should be included

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
