### ISSUE TITLE
Better Cluster Physics

### ISSUE THREAD

**Issue by VeryKitty03** [nonamecrackers2/crackers-wither-storm-mod#775]
Maybe a cool addition to block clusters would be that they could be collidable and go up in only tractor beams, while going the same speed as a entity or player that is getting beamed to their doom.

**Comment by ghost** [comment]
That would be way too hard to implement since they are a entities.

**Comment by Globalfirestorm10** [comment]
not quite, This has been suggested in https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/150 already
