### ISSUE TITLE
"bowels is null" glitch

### ISSUE THREAD

**Issue by MoistedPotatoes** [nonamecrackers2/crackers-wither-storm-mod#776]
1.19.2

witherstormmod-1.19.2-3.1.1

the glitch happens not too long after you summon the witherstorm, it seems, and it only happens on the world once.

**To Reproduce**
1. Go to minecraft
2. create new world
3. summon the witherstorm and wait.
4. See the crash report

the crash report: The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.getCapability(net.minecraftforge.common.capabilities.Capability)" because "bowels" is null

![Screenshot (1190)](https://user-images.githubusercontent.com/107385480/201557179-36f13707-501b-4c73-862b-5be975c0fde0.png)

**Comment by Globalfirestorm10** [comment]
known bug with flat worlds and end dimension, please close this issue

**Comment by nonamecrackers2** [comment]
This an issue with 1.19+ that is out of my control. As already noticed, reloading the world does fix the issue.
