### ISSUE TITLE
Reanimation of the tentacles

### ISSUE THREAD

**Issue by EndTheEnders164** [nonamecrackers2/crackers-wither-storm-mod#777]
I feel like the tentacles on the Wither Storm are moving a little slowly... Maybe you could reanimate the tentacles to be faster and more chaotic? Thanks!
PS: About my previous suggestion, I realised that the Config Options for this mod exist, and someone pointed it out as well.

--Dimitrius Films

**Comment by ghost** [comment]
n o. it would make the game buggy and would feel out of place from the current Minecraft worlds. like most mobs animations are slow.

**Comment by KrukAdrian** [comment]
I think this was already suggested

**Comment by nonamecrackers2** [comment]
This was already suggested, and the response was no due to personal preference and how I find that upping the speed would make the movement of them too unrealistic.
