### ISSUE TITLE
Amulet use

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#779]
Make it so on the setting you can set the amulet to see special players location if possible somehow

**Comment by nonamecrackers2** [comment]
What do you mean by “special players?” You’ll have to be more specific.

**Comment by Abasthepro** [comment]
> What do you mean by “special players?” You’ll have to be more specific.

Like the host can select what player can be shown in the amulet

**Comment by Globalfirestorm10** [comment]
> > What do you mean by “special players?” You’ll have to be more specific.
> 
> 
> 
> Like the host can select what player can be shown in the amulet
> 
> 

shown? What do you mean by that?

**Comment by Abasthepro** [comment]
> What do you mean by “special players?” You’ll have to be more specific.

**Comment by GrandmaPork** [comment]
I think he means it could be used as a compass to find a player

**Comment by Abasthepro** [comment]
> What do you mean by “special players?” You’ll have to be more specific.

Like this https://youtu.be/0VxjuylHsIA

**Comment by GrandmaPork** [comment]
i'd reopen this

**Comment by Globalfirestorm10** [comment]
> > What do you mean by “special players?” You’ll have to be more specific.
> 
> Like this https://youtu.be/0VxjuylHsIA

oh, that might be hard to implement, especially if the player is very far away from you, idk, ask cracker

**Comment by Abasthepro** [comment]
> > > What do you mean by “special players?” You’ll have to be more specific.
> > 
> > 
> > Like this https://youtu.be/0VxjuylHsIA
> 
> oh, that might be hard to implement, especially if the player is very far away from you, idk, ask cracker

Cracker may be able to code it if he got enough experience

**Comment by GrandmaPork** [comment]
One issue I have with this is that it wouldn’t be very practical. Unless in a pre-made and well planned out map for this to really be useful and even then, the witherstorm would just tear this apart. What I recommend is going to journey map and/or xaero’s minimap mod and see if they can add some sort of compatibility for this. OR this could be some sort of “after the storm” thing you can make

**Comment by Globalfirestorm10** [comment]
> One issue I have with this is that it wouldn’t be very practical. Unless in a pre-made and well planned out map for this to really be useful and even then, the witherstorm would just tear this apart. What I recommend is going to journey map and/or xaero’s minimap mod and see if they can add some sort of compatibility for this. OR this could be some sort of “after the storm” thing you can make

Or perhaps the amulet could do something similar to Xaero's Minimap and make a waypoint with the distance to that player (i.e, it marks player 1 as 150m away, which is 150 blocks)

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
