### ISSUE TITLE
Wither storm idea

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#780]
Make it so when the wither storm is in 4 and above phase and it is in a building it absorbed the blocks around it instead of glitches into it

**Comment by nonamecrackers2** [comment]
There isn’t much cases of the Wither Storm being stuck in buildings, unless if it was manually teleported into one. This feature wouldn’t really be worth my time, and could cause a lot of lag if it tries to create and render a lot of surrounding block clusters at once.
