### ISSUE TITLE
Wither storm teeth

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#781]
Make the wither storm teeth a little yellowish

**Comment by watersofnazareth** [comment]
This would be a meaningless change and you should be able to do it yourself through the texture files

**Comment by KrukAdrian** [comment]
I think hes mentioning how the teeth turn yellow after the wither storm's fake death.

**Comment by Abasthepro** [comment]
Yeah

**Comment by nonamecrackers2** [comment]
I personally prefer the white color regardless. Feel free to make resource packs though
