### ISSUE TITLE
Crashing Major!

### ISSUE THREAD

**Issue by justfigure** [nonamecrackers2/crackers-wither-storm-mod#782]
**Minecraft version**
The version of Minecraft the mod is running on 1.19.2

**Mod version**
The version of the mod you are using [witherstormmod-1.19.2-3.1.1]

**Describe the bug**
A clear and concise description of what the bug is. I was just making the wither storm phase 5 then I fordibombed it sorry don't know item name then I Wanted to Revive it so I switched to survival right on it and it crashed so I restarted my computer because when my game crashes I can't reopen Minecraft launcher then I reopened the world and it crashed again 

**To Reproduce**
I had more than 20~ mods I think anyways I don't think it's conflict with other mods
**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.
https://pastebin.com/SkuXmzsW
**Is Flywheel's optimizations active?**
Specify if Flywheel is installed and it's compat optimizations are enabled
no there wasn't any version for 1.19.2 for Flywheel at least that I could find
**Screenshots**
The Game Crashes and doesn't show anything the whole task crashes!

**Comment by justfigure** [comment]
Gonna create another world but I need to look a bit deeper or find the solution that's when I will Close this Crashing Major!

**Comment by justfigure** [comment]
Please someone help with this problem...

**Comment by justfigure** [comment]
[DEATH IS INCOMING AND FAST.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10052602/DEATH.IS.INCOMING.AND.FAST.zip)
Here's the world file

**Comment by justfigure** [comment]
obviously extract it

**Comment by justfigure** [comment]
Then put it in C:\Users\0wdga\AppData\Roaming\.minecraft\saves

**Comment by justfigure** [comment]
The 0wdga Will be Different of Course just go to .minecraft\saves

**Comment by justfigure** [comment]
12 hours to wait E

**Comment by justfigure** [comment]
Pin this tab for now in my browser so I can see what happens in comments of this issue

**Comment by watersofnazareth** [comment]
What's your mod list and latest.log, your world file won't help

**Comment by justfigure** [comment]
here it is 
[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10053217/latest.log)

**Comment by justfigure** [comment]
You haven't even checked the paste bin link? It also has the latest log with all the text.

**Comment by justfigure** [comment]
bruh I installed so many mods it's 155 Megabytes...

**Comment by justfigure** [comment]
Way above the 25 Megabyte limit.

**Comment by justfigure** [comment]
I guess the mod list is f**ked

**Comment by justfigure** [comment]
Gonna delete these pointless zip files.

**Comment by justfigure** [comment]
I just wanted to play f**kin minecraft with mods and it wanted to f**kin crash

**Comment by justfigure** [comment]
And thought Cracker's Wither Storm Mod will be a fun addition, just I think Cracker's Wither Storm mod is the root of the problem that's why I'm even here.

**Comment by justfigure** [comment]
Gonna close browser for now if you comment it will be a little while till I see your message time for me right now is 7:53p.m Might see your message tomorrow. goodbye probably for now.

**Comment by justfigure** [comment]
god I installed so many f**kin mods...

**Comment by justfigure** [comment]
Found the issue It's a poorly made port to 1.19.2 here it is https://www.curseforge.com/minecraft/mc-mods/nightmareesm
