### ISSUE TITLE
the attractor beam should attract blocks

### ISSUE THREAD

**Issue by BrunoGoldbergFerro** [nonamecrackers2/crackers-wither-storm-mod#783]
Attractor beam should attract blocks like in story mode

**Comment by V0calgiant12** [comment]
Do you mean the beam should pick up blocks? Because it already does that, just not constantly. It'll pickup blocks via tractor beams sometimes

**Comment by nonamecrackers2** [comment]
Please elaborate

**Comment by nonamecrackers2** [comment]
Closing until more information is given
