### ISSUE TITLE
/witherstormmod Command update - Subject: Wither Symbiont Power down/up

### ISSUE THREAD

**Issue by justfigure** [nonamecrackers2/crackers-wither-storm-mod#784]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**
Make a Command for /witherstormmod charge/decharge or some other word with same meaning to make a Wither Symbiont power down or back up along at the end of the command after @e[type=witherstormmod:wither_symbiont,limit=1] timer/secs if you still don't know which feature I'm mentioning let me explain it's when a Wither Symbiont Uses Spells Untill it Summons Mobs Which it Then Powers down so The Player can Attack it in the Back. Please add this nonamecrackers/dev team. idk if dev team even exists...

**Comment by justfigure** [comment]
This is just using a feature already in mod for commands and so... Just a feature needed for /witherstormmod.

**Comment by nonamecrackers2** [comment]
You should be able to do this with commands, something like `/data modify entity @e[type=witherstormmod:withered_symbiont,limit=1,sort=nearest] Stage set value 2` should work to set the symbiont to it's "vulnerable" state
