### ISSUE TITLE
Crying obsidian

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#785]
Add crying obsidian as a floating ring and on the sides of the wither storm after he faked death it's not that big of a thing idk if it's worth it but just for the texture

**Comment by nonamecrackers2** [comment]
I don’t feel crying obsidian is very fitting and doesn’t make much sense. The debris is meant to represent any block absorbed, and adding blocks that are left in their normal state in the debris ring isn’t really worth my time, so I feel the debris ring should also be left alone.
