### ISSUE TITLE
Tractor beam should assist/increase the chances of clusters getting sucked up to the witherstorms body

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#787]
The tractor beam should be able to assist/increase the chances if clusters and blocks getting sucked up to the witherstorms body I know the clusters are designed to go for the witherstorms body but I'm saying the tractor beam should increase the chance if that

**Comment by watersofnazareth** [comment]
They do? What is it you mean exactly?

**Comment by Abasthepro** [comment]
> They do? What is it you mean exactly?

I mean even if they do you should be able to edit the chances/assist in the settings

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
