### ISSUE TITLE
alternate theme for hunchback stages

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#789]
I noticed there is another theme for the wither storm that can be found [here](https://www.youtube.com/watch?v=3NlkqN3O1MU&list=PLk1sle6PCaD25UMPaxlaR3qI0uddeTvwK&index=11). i think it would be perfect for the hunchback stages (1-3) as they dont quite fit with the default theme.

**Comment by nonamecrackers2** [comment]
That version is the more bass-y version of the one currently in the game, and I feel that it would be more appropriate for the later phases than the the hunchback ones. Regardless, the video you linked is pretty much identical to what is already in the mod and there wouldn't really be a noticeable difference.
