### ISSUE TITLE
make wither storm easier to see at night

### ISSUE THREAD

**Issue by MFNmodding** [nonamecrackers2/crackers-wither-storm-mod#791]
The wither storm is hard to see during the night, which hinders your ability to know how far away it is. my suggestion is to add a colored outline(possibly purple or blue) to the wither storm's distant renderer during the night. that's my entire suggestion.

**Comment by OliversIntention** [comment]
purple outline would be best. also a good idea to add purple lightning (as seen at the start of episode 4)

**Comment by MFNmodding** [comment]
that's what i'm saying, at the moment it's ever so slightly darker than the night sky if you zoom in on it. but not everyone has spyglasses or zoom mods.

**Comment by nonamecrackers2** [comment]
This was attempted during development but didn't work overly well. I will be willing to look into it now however.

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
