### ISSUE TITLE
The tractor beam should be more purplish

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#793]
The tractor beam should not be so pink like in the mod I know I could install a pack but I'm just saying so it looks more canon or more like the wither storm in mcsm

**Comment by GrandmaPork** [comment]
The cwsm wither storm isn’t meant to be a 1 to 1 replica of the story mode wither storm

**Comment by Abasthepro** [comment]
> The cwsm wither storm isn’t meant to be a 1 to 1 replica of the story mode wither storm

I didn't say make the whole mod like mcsm's wither storm I just said make the tractor beam a little more purplish

**Comment by nonamecrackers2** [comment]
I personally prefer the pink color and don't find it necessary to change it to be more purplish.
