### ISSUE TITLE
Improve the attack of the tractor beam in the first phases

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#794]
In this suggestion I have found a problem that is quite common in the first phases of the wither storm (0-3) that when the wither attracts a mob with its tractor beam, it is seen that it attracts it, but it is not seen that it attracts it from the beam, but that it attracts it by magical forces haha, and to solve this it would be very simple, that the wither would tilt something like the video that I will present later, or that the wither does not approach as you will see in the 2 video

Wither from bedrock leans when attacking, you could use this animation or create a similar one.

https://user-images.githubusercontent.com/89810837/205461577-c51ec40e-b842-4efe-bac6-79827b489868.mp4

problem of the tractor beam in the storm wither

https://user-images.githubusercontent.com/89810837/205461834-ed9d8155-e5ae-42f9-a724-064714cd2d62.mp4

we can see that the wither storm of minecraft story mode also leans a little bit, probably this animation can be used as well.

https://user-images.githubusercontent.com/89810837/205462090-c13f5bdf-bd74-4061-8d1d-2325c382cd1d.mp4

**Comment by NinjaSam5399** [comment]
Your second video is glitched out.

**Comment by NinjaSam5399** [comment]
And every time I watch it my entire app turns out to turns black a bit.

**Comment by TheSrBig** [comment]
it must be your device, because I see it perfectly fine.

**Comment by nonamecrackers2** [comment]
Should have been implemented in the latest release
