### ISSUE TITLE
Wither Storm Possession

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#796]
### FEATURE SUGGESTION

****

_I don't know if this will be used by many people if it was added to the mod, or if you even know how to add this, but it would be cool to have this as a feature._

So my idea is to be able to control/possess the Wither Storm like you used to be able to do it with almost any mob using the Morph Mod.

**Extra stuff/ideas to make it better or something:**
**1** - if you turn your head, the entire storm rotates into that direction the player is looking at with the rotationSpeed set in the configs + the horizontal head rotation is limited to let's say 160° so the head can't turn inside the body, which would look stupid.
**2** - right-click (or whatever key is being used) to shoot a flaming wither skull with a cooldown of 100 ticks
**3** - using WASD to fly with the speed from the slowFlyingSpeed config and with CRTL being hold to accelerate with the speed from the targetStationaryFlyingSpeed config
**4** - the middle head only is being controlled while the other 2 heads behave normally
**5** - might be more difficult to do this one but if there are multiple players, one Wither Storm could be controlled by up to 3 players (one for each head), the middle head still being the one that manages flying movements
**6** - if a possessed Wither Storm gets F-bombed, the screen for the player that controls the storm turns white and then fades to black until the storm revives, then the back screen disappears
**7** - if a possessed Wither Storm gets command-block-damaged from the bowels, the screen of the player that controls the storm gets a damage overlay effect (ideas: blur flash, red flash, purple flash, small cracks that get bigger for each hit)
**8** - if a possessed Wither Storm dies, the screen of the player that controls it slowly turns black until the storm is completely dead. If the storm's gone, the player that controlled it gets killed too (maybe with keepInventory being on so you don't lose all your stuff you had).
**9** - if a possessed Wither Storm head gets damaged, a big crack could appear on the players screen who is controlling the said head which disappears when the tractor beam reactivates
**10** - similar to Xaero's Minimap Mod's _latest death waypoint_ feature, there could be a little dot with the name of the player below it on the screen to show where the ultimate target of the Wither Storm is (and the dot temporarily disappears if the player uses a shield/invisibility potion to hide from the storm)

****

the command for this could be **/witherstormmod control [selector]** or **/witherstormmod possess [selector]** or anything you'd like to choose
and the command to stop controlling a storm could be **/witherstormmod exit [selector]**

as I said you might don't know how to do all of this and I also think it's a pretty unneccessary feature and a waste of time to make this but would be neat to have it to prank other people, or just to have the feeling to be powerful

feel free to add the _unlikely_ label

****

_(I tried to make the storm controllable by constantly teleporting a Wither Storm to me using command blocks, but it didn't work well because I couldn't see anything in first person and in destroyer phases it makes no sense trying to go in 3rd person mode because the storm is too big to be able to see anything.)_

**Comment by Aimyx** [comment]
I want this, but its just unnecessary, as the mod is about going against the storm. not being one. and the code for this. OOHH the code.

**Comment by Globalfirestorm10** [comment]
yeah, that would probably be hard to implement, especially with all the mechanics the WS has

**Comment by nonamecrackers2** [comment]
This has been suggested multiple times, and I don't feel this would fit with the scope and intent of the mod. This could however be a sick addon if one should ever come to fruition.
