### ISSUE TITLE
Enchanted Command Armor

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#798]
**Description of feature**
If there are command tools, then why not make armor from a command book?

**FEATURE** **REQUEST**
### **I think we should add Enchanted Command Armor. it will have a regeneration effect for up to 8 minutes if you are low on health. Well, goodbye.**

**Comment by FrozenDragon0** [comment]
I believe this was already suggested before and was denied, really no need for command block armor as it'd take a bit to even get it in the first place.

**Comment by ghost** [comment]
Well, yes, though...

**Comment by Globalfirestorm10** [comment]
It's already been suggested as said before, you should close this down now

**Comment by nonamecrackers2** [comment]
#250
