### ISSUE TITLE
 Wither storm is not dead

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#799]
**Minecraft version**
Forge 1.16.5

**Mod version**
1.0.2.4

**Describe the bug**
This happened after I killed the command block with a command, I immediately got out of the wither storm he did not die, when I entered his stomach there was no command block.
THIS IS 100% a bug.

**Screenshots**

![2022-12-10_18 14 17](https://user-images.githubusercontent.com/119749553/206865312-75daf8f0-8f81-4435-8e41-f8d4e700c965.png)

**Comment by Globalfirestorm10** [comment]
you should've just killed the ws via command, not the command block lol

**Comment by octoling328** [comment]
try use the /kill command to force kill the storm?

**Comment by Globalfirestorm10** [comment]
> try use the /kill command to force kill the storm?

yeah, that would've worked instead of killing the command block, you should've used /kill @E[type=witherstormmod:witherstorm] instead

**Comment by ghost** [comment]
**Thanks**

**Comment by octoling328** [comment]
Sooooooo it's fixed?

**Comment by ghost** [comment]
It seems not

**Comment by octoling328** [comment]
What happened now?

**Comment by Globalfirestorm10** [comment]
> What happened now?

I just told him the proper command for killing the wither storm, that's all

**Comment by Globalfirestorm10** [comment]
> Sooooooo it's fixed?

No, it isn't fixed yet, probably will be in a future update. Also, I think this is more of an enhancement/missing feature than a bug, but of course ill leave that up to cracker himself

**Comment by nonamecrackers2** [comment]
/kill on the command block doesn't actually activate the proper death sequence which kills the wither storm. This has been remedied in newer versions however not yet in 1.16.5

**Comment by ghost** [comment]
will it be fixed?)

**Comment by nonamecrackers2** [comment]
Yes, it’s fixed in my dev environment and will be available in the next bug fix release
