### ISSUE TITLE
Wither Storm Dissapears When Updating From 1.16.5 To 1.18.2 

### ISSUE THREAD

**Issue by MoistedPotatoes** [nonamecrackers2/crackers-wither-storm-mod#80]
For Some Reason The Wither Storm, Withered Symbiont, And Sickened Mobs Dissapears When Updating Your Version And The Mod To 1.18.2, But This Is Not The Case With Blocks And Items In Item Frames However.

**Comment by nonamecrackers2** [comment]
Nothing in the mod changed drastically that would cause this to happen. May be something with minecraft restructuring how entities are stored. Nothing I can really do, sorry.
