### ISSUE TITLE
Punishment for Sleeping

### ISSUE THREAD

**Issue by Jackmo2207** [nonamecrackers2/crackers-wither-storm-mod#801]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**
I think there should be a way for the mod to punish players who sleep to skip the night, to encourage taking a risk and either continuing running at nighttime to stay ahead of the wither storm, or sleeping to avoid the mobs but having the wither storm get closer. Basically, the way I imagine this working is, it uses the wither storm's slow flying speed and calculates how many blocks the wither storm would travel in the 10 minutes you're skipping via sleep, then teleport it that many blocks towards the player. So if it was 1000 blocks away and I slept, I'd wake up and see it 100 blocks away for example. It's accurate to story mode too, because in episode 2 you choose between sleeping or setting out to Soren's base at night to stay ahead and if you sleep the wither storm catches you.

**Comment by TheEyeOfGaming** [comment]
good idea!

**Comment by nonamecrackers2** [comment]
#243
