### ISSUE TITLE
Wither Storm Resummoning Mechanic

### ISSUE THREAD

**Issue by MrCoolz123456** [nonamecrackers2/crackers-wither-storm-mod#802]
**Description of feature**
I thought of a cool system that was inspired by the Minecraft Dungeons's orb of dominance, where the final boss was defeated but it's shards were still active. So after you defeat the Wither Storm, shards of the command block will appear around the world.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by ERCEpic** [comment]
This seems like a cool idea, but would player have a reasonable idea of where the shards are? Maybe you could get maps from villages showing where the shards are.

**Comment by MrCoolz123456** [comment]
That would be a good idea. Maybe with the wandering trader or a special structure that contains a map.

**Comment by GrandmaPork** [comment]
I think that the shards should be indestructible even to cactus, and should be within a small radius of where the witherstorm dies. This allows the player to easily find and resummon the witherstorm if they want but also prevents one troll from doing it if at least one shard is missing.
The command block can be a “cracked” or “unstable” one that breaks after like 5-10 seconds in case a player places it by mistake. Then it splits into shards again and they’re dropped on the ground.

**Comment by GrandmaPork** [comment]
If a shard is deleted via void or cactus then it should be assumed it was done on purpose. Just make shards immune to fire lava and explosions (maybe a config for cactus and what not).
And a config that adds the shard to a villager trade in case one was destroyed by mistake. Allows the players to not use cheats and to simply change a config value to get one back

**Comment by nonamecrackers2** [comment]
This doesn't really fit in with my idea for making the Wither Storm resummonable, and I'd prefer to keep the command block uncraftable (as I assume you'd use the shards to craft the block? Not sure how the orb of dominance works as I'm not a dungeons player).
