### ISSUE TITLE
Crash on server Join 1.16.5

### ISSUE THREAD

**Issue by Wojtek-Bear** [nonamecrackers2/crackers-wither-storm-mod#803]
Minecraft version
Forge 1.16.5 36.2.39

Mod version
1.0.2.4

Describe the bug
I'm trying to start a server with friends and it crashes to desktop.
[crash-2022-12-20_13.05.05-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10271742/crash-2022-12-20_13.05.05-client.txt)

**Comment by nonamecrackers2** [comment]
#240
