### ISSUE TITLE
mod crashes when prehistoric fauna mod is installed

### ISSUE THREAD

**Issue by octoling328** [nonamecrackers2/crackers-wither-storm-mod#804]
**Minecraft version**
1.16.5 forge 36.2.39

**Mod version**
[witherstormmod-1.16.5-1.0.2.4.jar]

**Describe the bug**
when you are playing the game with the mod installed, if unlucky enough the game will crash 

**To Reproduce**
1. install the mod
2. play the game as usual until the game freezes
3. See crash

**Crash Reports / Logs**
https://discordbot.matyrobbrt.com/fpreview/?url=https://cdn.discordapp.com/attachments/750505199415590942/1054732463903088650/crash-2022-12-20_19.38.14-server.txt

**Is Flywheel's optimizations active?**
no

attached files:
[crash-2022-12-20_19.38.14-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10277912/crash-2022-12-20_19.38.14-server.txt)

suspected reason(pls read screenshot)
![Screenshot 2022-12-21 at 21 22 36](https://user-images.githubusercontent.com/101700669/208915592-463a9e73-dcad-4ee8-86eb-74f8969fdce5.png)

(P.S. removing either prehistoric or wither storm mod fixes the issue but I don't want it)

**Comment by nonamecrackers2** [comment]
Try disabling the formidibomb "Tick in Containers" config option in the server config menu. This feature has been causing lots of issues and has been removed in newer versions, so I recommend disabling it. Let me know if that works.

**Comment by octoling328** [comment]
I fixed it, thanks!

(p.s. the world becomes unplayable even though I fixed it, entities will move with lag and drinking potions will give you an infinite time limit(even I had 60fps ), regenerating the world helps the problem so always make a backup of your worlds and make sure to you set the "Tick in Containers"  to false from the server config and reload minecraft so this won't happen)

**Comment by nonamecrackers2** [comment]
Sounds good!
