### ISSUE TITLE
Problems with graphics!

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#805]
**Minecraft version**
 Forge 1.18.2

**Mod version**
2.1.1

**Describe the bug**
### in general, I have a weak computer and I decided to download mods to create my own mod pack. I opened Minecraft and set the Wither Storm graphics to low. I said that I have a weak PC, when I turned on low graphics, I slowed down a bit and nothing changed after that! When I flew away from the Wither Storm, everything was fine! 
This happened on version 1.18.2

****To Reproduce**
1. Go to 'Client Options'
2. Click on 'Preset:Low'
3.. See error**

**Is Flywheel's optimizations active?**
Yes there is optimization

**Screenshots**
When I flew off the graphics were low
![2022-12-23_16 21 40](https://user-images.githubusercontent.com/119749553/209343740-982f510b-4997-489c-b59f-a5c83652bcd2.png)
When I flew up to Wither Storm, the graphics became medium or high
![2022-12-23_16 21 10](https://user-images.githubusercontent.com/119749553/209343763-a8de5876-e6a5-440f-ad23-dbce55e521e7.png)

_**Is it  just me or does anyone else have it too?**

**Comment by ghost** [comment]
Am I the only one?

**Comment by Globalfirestorm10** [comment]
what do you mean by "graphics"? Everything looks normal to me

**Comment by ghost** [comment]
### On the first screenshot, everything seems to be ok.
but when I fly up to the wither storm, then its graphics become medium or high

**Comment by Globalfirestorm10** [comment]
There's nothing wrong with this, this is a feature that works as intended

**Comment by Globalfirestorm10** [comment]
If you're referring to the storm's appearance being obscured/fogged up when you fly away from it, than this is normal, it's just the distant renderer

**Comment by nonamecrackers2** [comment]
If you fly away from the storm to activate the distant renderer, and look away from the storm, does performance improve?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
But when I get close to Wither Storm, its graphics look better than what I have in the client config options.

**Comment by Globalfirestorm10** [comment]
This is because of the distant renderer fogging up the appearance of the WS, making it easier to render. Correct me if i'm wrong cracker, but isn't this normal?

**Comment by nonamecrackers2** [comment]
I originally misinterpreted this report. The reason why your “low” client config preset isn’t working when near the storm is due to flywheel, which improves rendering performance for the default WS models and so the low res models do not need to be applied.
