### ISSUE TITLE
Ruined house spawning in dimensions from other mods (for example: The Abyss) + a suggestion

### ISSUE THREAD

**Issue by The-Goat-HUN** [nonamecrackers2/crackers-wither-storm-mod#806]
A fix could be to make the ruined house configurable and blacklist it from dimensions, possibly even disable it completely so that we can create our own means to summon the Wither Storm (e.g.: a quest that will summon it).

Game version: 1.18.2

**Comment by nonamecrackers2** [comment]
This can be done via data packs. It isn’t very straightforward however, so I plan on releasing a data pack that disabled it, etc.

**Comment by GrandmaPork** [comment]
1.18.2 abyss was discontinued, I don’t recommend using it

**Comment by The-Goat-HUN** [comment]
You can't even use it.

GrandmaPork ***@***.***> ezt írta (időpont: 2023. jan. 11.,
Sze 5:20):
