### ISSUE TITLE
Advancements can be skipped

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#807]
**Minecraft version**
1.19.2

**Mod version**
latest

**Describe the bug**
Sometimes, the advancements for Formidibomb and onward are skipped entirely

**Crash Reports / Logs**

**Comment by nonamecrackers2** [comment]
Which advancement is not be awarded?

**Comment by nonamecrackers2** [comment]
Closing until more information is given

**Comment by myron-obsolete-account** [comment]
@Inonedn hi. Mind giving out more information? Thanks.

**Comment by LocalWaterCreeper911911** [comment]
> @Inonedn hi. Mind giving out more information? Thanks.

@Inonedn is dead, forget about him

**Comment by BluePineappleGuy** [comment]
> Which advancement is not be awarded?

i think he means 'the strong grow weak' and 'the weakened arise stronger'
