### ISSUE TITLE
Two new abilities for the Wither Symbiote

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#808]
**Description of feature**
Introducing 2 new Wither Symbiote abilities.
1) From 5 to 10 dynamites spawn and the player needs to run away from these TNTs.

2) The wither symbiote throws a potion at the player that benefits or annoys them during combat.

### AGAIN THIS IS JUST A SUGGESTION, THE AUTHOR OF THE MOD CANNOT ADD IT! IT IS UNCLEAR HOW IT WILL BE IMPLEMENTED
**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Globalfirestorm10** [comment]
I like this idea, however, the potion idea seems a bit out of place for this, perhaps there could be a chance where one of the arrows is tipped with an effect (i.e, a 1 in 5 chance for the arrow attack to contain a wither tipped arrow)

**Comment by ghost** [comment]
yep

**Comment by BluePineappleGuy** [comment]
> I like this idea, however, the potion idea seems a bit out of place for this, perhaps there could be a chance where one of the arrows is tipped with an effect (i.e, a 1 in 5 chance for the arrow attack to contain a wither tipped arrow)

i dont think the potions would feel out of place, but it throwing them would kinda remind me of the mcsm ivor fight
