### ISSUE TITLE
Common config option for the structure at 0,0 spawning

### ISSUE THREAD

**Issue by th3impasta** [nonamecrackers2/crackers-wither-storm-mod#809]
**Description of feature**
A config option for the structure spawning in the common config so i can gate the wither storm behind other mods in a modpack i'm working on

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
There is no config option as this can be done with data packs. As mentioned in another post I do plan on making a pack that can disable the structure, which you may be able to utilize for your use case.

**Comment by th3impasta** [comment]
that's a shame, i dont like using datapacks as they are hard to integrate
