### ISSUE TITLE
in 1.18.2 looks like the wither structure is not generated at x0 z0

### ISSUE THREAD

**Issue by Jukabofy** [nonamecrackers2/crackers-wither-storm-mod#81]
It is not solved in the last version

**Comment by nonamecrackers2** [comment]
What biome is 0 0 in, and the Y level of the highest block at that point?

**Comment by Gaboamau** [comment]
This is happening to me but only when I change the types of worlds, for example in superflat worlds, the house does not appear in the coordinates x:0 and z:0, and in single biome worlds, sometimes they do not work either, for example in the badlands biome does not appear.

**Comment by nonamecrackers2** [comment]
Ah. Due to the tag used to determine where it can generate. It uses the mineshaft one as mineshafts can generate in any biome, must not be allowed in badlands (probably because there’s a separate mineshaft structure for the badlands, could be wrong)

**Comment by Jukabofy** [comment]
![2022-06-13_15 34 49](https://user-images.githubusercontent.com/87483832/173441859-2e2c9a3b-5f3f-4e52-b658-d11d2be27df7.png)


> Ah. Due to the tag used to determine where it can generate. It uses the mineshaft one as mineshafts can generate in any biome, must not be allowed in badlands (probably because there’s a separate mineshaft structure for the badlands, could be wrong)

I don't think, maybe is something else

**Comment by Jukabofy** [comment]
In the fisrt screenshot above this commentary, it didn't geenrate for some reason, after reorganizing my custom modpack, looks like is working agai
![2022-06-13_16 15 59](https://user-images.githubusercontent.com/87483832/173460672-d4886619-8b9c-49e1-b0ff-48106ae144ae.png)
n
