### ISSUE TITLE
Command Block Book getting destroyed

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#810]
**Minecraft version**
1.19.2

**Mod version**
Latest

**Describe the bug**
the command block book can be sucked in by the wither storm and/or get destroyed by a creeper

**Comment by V0calgiant12** [comment]
It doesnt happen in the early stages, funnily enough, but once it gets to stage 4, it doesnt care what the item is, it just sucks it in anyway. Im like 60% sure its a bug, but it might not be, at least for wither roses. But im on bord with the wither storm not sucking in vital and rare items needed to progress such as the F-bomb and cmd block book/tools.

**Comment by nonamecrackers2** [comment]
It shouldn't pick up command block books. I'll have to investigate

**Comment by V0calgiant12** [comment]
So, did some testing in game, and it seems to have not been picked up, the command block books and tools I mean. I was testing it on 1.19.2 on forge 43.2.1 with next to no other mods installed. and the others mods installed were only client side too so there is that. so, I have no idea how you got the book to be sucked in by the storm, however, they will be destroyed by explosions. And on a kind of unrelated note, the F-bomb does get sucked in which should, in my opinion, change as it is a vital part of progression and if it is lost, you have to do everything all over again.

**Comment by nonamecrackers2** [comment]
The command block book doesn't get sucked in, however it can be blown up, which is technically intentional however I'll leave this open for future reference.

**Comment by Inonedn** [comment]
It is incredibly easy for the command book to be destroyed by a creeper due to how beefed up and spammed they are
