### ISSUE TITLE
Game crashing upon getting near the wither storm (1.18.2 Server)

### ISSUE THREAD

**Issue by idek-but-GB** [nonamecrackers2/crackers-wither-storm-mod#812]
Whenever I get near the wither storm, my game crashes. This is on a 1.18.2 forge server and i seem to be the only one who crashes. 
The exit code is 1 and the crash report is attached, as well as the log for when I was on the server before crashing. The reason I didn't crash to begin with was because I was away from the storm. The mods installed on the server and client are: Wildfire's gender mod, architectury (client only), custom skin loader, flywheel, simple log in, simple voice chat and the wither storm mod itself. All the mod files are the same ones that are being used by the server and everyone else playing. Through console on the server, the reason it says for me disconnecting is simply 'disconnected'. When checking the logs, AverageGB is me (which is why it ends as soon as I get teleported). Please help. Thanks
[hs_err_pid328.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10309262/hs_err_pid328.log)
[2022-12-27-3.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10309266/2022-12-27-3.log)

**Comment by idek-but-GB** [comment]
Closing, I managed to fix the issue by removing flywheel

**Comment by Globalfirestorm10** [comment]
I've checked both logs, nothing seems wrong in these logs, perhaps you uploaded the wrong ones? Most of the logs just contain some chat messages and processes from the server
