### ISSUE TITLE
Head Glitch?

### ISSUE THREAD

**Issue by Faknocker** [nonamecrackers2/crackers-wither-storm-mod#813]
here is a video of the issue https://streamable.com/t7sssw

**Comment by nonamecrackers2** [comment]
This looks like a rubididum extras issue. I recommend going to the mod incompatibility section (under magnesium extras) in the mod page as it outlines the issue it looks like your having. Also, please fill out the entire form and also provide a list of your mods.

**Comment by Faknocker** [comment]
figured out what was causing it the mod called entity culling
