### ISSUE TITLE
phase 1 witherstorm corpse after destroying the command block

### ISSUE THREAD

**Issue by Realfoxy985** [nonamecrackers2/crackers-wither-storm-mod#814]
I think having a corpse of the regular wither after you destroy the command block would be a good idea because technically the wither storms skin is technically a case protecting the phase 0 wither storm so it would make sense for a phase 0 corpse to fall out of the sky once destroying the command block

**Comment by nonamecrackers2** [comment]
This doesn't really make much sense in my opinion, and also isn't very necessary. Also as the Wither Storm evolves, the phase 0 body amalgamates into the big black mass that is the later phases.
