### ISSUE TITLE
placeable mob statues

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#816]
What im thinking of is when a mob statue is mined it gets added to your inventory and you can place it anywhere you want  (only 1 can be held)

**Comment by GearsawStudios** [comment]
Why should this be in the mod? The mod is a Wither Storm mod so I'm unsure what this adds to it besides that it's kind of cool.

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2

**Comment by Pandaboi25x** [comment]
> Implemented in 2.2/3.2

tysm!
