### ISSUE TITLE
Small Visual F-Bomb-Corpse-Structure Improvements?

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#818]
**Description of feature**
So since the bones and the Command Block which are located on top of the structure were pretty much inside the Wither Storm, it would look quite better if there were some tainted planks/stone/sand/cobblestone blocks (and maybe even some tainted dust?) around the command block and tentacles, to make it look like the F-Bomb ripped the body open so the Command Block could get exposed.

I did something similar like that in a gigantic Wither Storm corpse I built myself:
![2022-12-31_21 16 37](https://user-images.githubusercontent.com/53058491/210154899-499b5b1c-8571-4cfa-92b3-2b9380b7fd85.png)

**Comment by myron-obsolete-account** [comment]
Here's one design that I thought would look good.
![2023-01-02_13 21 21](https://user-images.githubusercontent.com/53058491/210230668-89989c7b-99df-4be9-b951-71eabfa37f6f.png)

**Comment by myron-obsolete-account** [comment]
oh yeah and heres a video for uh better visuality i guess like you can see how it looks like what i built

https://www.youtube.com/watch?v=jkSvGGBTLTo

**Comment by bruhicantlogin** [comment]
that first one was epic honestly

**Comment by myron-obsolete-account** [comment]
yeah well I tried my best with the bones but thanks

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
