### ISSUE TITLE
"jeb_" Easter Egg

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#821]
**Description of feature**
Okay listen this is really silly and unneccessary but when you name a Wither Storm "jeb_" it's tractor beams could start flashing in rainbow colors like the sheep's wool does.

(also I'm sorry for opening like 5 suggestion issues in one day and I swear this is the last one for now)

**Comment by ERCEpic** [comment]
Yes

**Comment by ghost** [comment]
yes

**Comment by TheSrBig** [comment]
yes

**Comment by NinjaSam5399** [comment]
Pls add it

**Comment by Aimyx** [comment]
yes

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
