### ISSUE TITLE
Relocation of Wither Storm segment holes on main body

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#823]
**Description of feature**
So currently the phase 6 body looks like this:
![oldphase6](https://user-images.githubusercontent.com/53058491/210170797-cb0c026d-6a47-465a-ad7d-78486f9306f9.png)
It is physically impossible for the heads to move up there to then get split up into extra bodies, so i thought it would make more sense if the holes were on the bottom like this:
![newphase6](https://user-images.githubusercontent.com/53058491/210170814-d70d7603-6fcc-49ce-b278-05cc9ef73825.png)
That way it would look better and make more sense.

(sorry for the goofy drawings, I wanted to make them quick and not waste too much time on them)

As seen in MCSM, the segment holes are also located on the bottom sides (you can notice the blood-like areas):
![28ab7a028ec4e22ea073a6b2d9c4ce27](https://user-images.githubusercontent.com/53058491/210170918-2e86f0e8-ca02-4769-bf1a-95b394994023.jpg)

**Comment by OliversIntention** [comment]
i like this suggestion, it makes more sense

**Comment by myron-obsolete-account** [comment]
thanks + i agree

**Comment by nonamecrackers2** [comment]
Changing the models takes a lot of work and is not in my best interest as of now. Well yes, it doesn't make much sense, changing it isn't a priority and isn't necessary.

**Comment by myron-obsolete-account** [comment]
hey how about I change the models so you dont have to do it? im just offering that because i'd really like to have it changed but its your mod so you have to decide
(you may also need to send the end-of-phase-5-body model so i can make changes to it)

**Comment by nonamecrackers2** [comment]
I appreciate the willingness to contribute, however I will have to decline, sorry.

**Comment by myron-obsolete-account** [comment]
aw man okay
