### ISSUE TITLE
Idea for a new structure in the bowel

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#824]
Since we have a village in the bowels, I think you should add a pillager outpost so the bowels won't have only one structure. It should be easy, just use /place structure. If it does not work, you could build the pillager outpost yourself. If you can't fit the pillager outpost in the bowels, then you can bury the pillager outpost fully or only a bit or mostly buried, Or do it by chance.

**Comment by ghost** [comment]
**a good idea, but it would be better not to have an pillager outpost, but a forest mansion, since it is larger and will fit into the abyss of a storm.**

**Comment by NinjaSam5399** [comment]
The mansion will mostly take over the bowels so its best to have a pillager outpost.

**Comment by bruhicantlogin** [comment]
mansion could be just small pieces of it, and the rest being literally in the model mass of the wither storm

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2

**Comment by NinjaSam5399** [comment]
Thanks
