### ISSUE TITLE
Spawn egg color

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#825]
**Description of feature**
**I have an idea.
I think it is necessary to update the textures of the items, (i.e.) the textures of the blocks have been updated, why not for the items?
I know very well that my post will not be accepted, but if the author and artist accept it, it will be really cool!
:D**

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by watersofnazareth** [comment]
I believe the items are fine, but Spawn Eggs will be changed to be more distinct

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
