### ISSUE TITLE
Wither Storm attracting items which are located in a closed room

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#826]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
Dropped items getting attracted by the Wither Storm while being in a cave.

**To Reproduce**
1. Summon Wither Storm
2. Set phase to 4 or above (optional but recommended so the item pickup radius is bigger than from the hunchback phases)
3. Go to cave or other place which has pretty much no way out
4. Drop some items or mine some blocks
5. See Wither Storm attracting them

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No.

**Screenshots**
No, but a video instead
https://user-images.githubusercontent.com/53058491/210185551-5d5137ee-818e-4255-990c-cf6dc052ce5d.mp4

_someone call the cops, the wither storm is commiting a crime!_

**Comment by watersofnazareth** [comment]
This is technically working as intended, but it may be possible to make a check to see if items have a certain amount of blocks above them?

**Comment by nonamecrackers2** [comment]
The wither storm must be really close to the ground in this. I'll leave this open however low priority.

**Comment by myron-obsolete-account** [comment]
oh yeah I set the flying height to 25 because it's more satisfying seeing the storm lower to the ground, so that may be the cause of the issue

**Comment by nonamecrackers2** [comment]
Will be fixed in the upcoming 1.19.4/1.20.1 release

**Comment by MoRoN222** [comment]
Hey cracker I updated the translations can you check it out please https://github.com/nonamecrackers2/crackers-wither-storm-mod/pull/786
