### ISSUE TITLE
wither storm shaking when in powder snow

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#827]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
<s>Wither Storm Segment is shaking like the Heads are shaking when harmed after the wither storm has been blown up</s>
wither storm shaking when in powder snow

**To Reproduce**
1. F bomb the wither storm (i did it with a command, if that information is important)
2. wait for it to split and drop
3. see segment shaking _after landing in powder snow_

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No.

**Screenshots**
video:

https://user-images.githubusercontent.com/53058491/210230086-51ba50b4-099d-41c4-934d-44bef1b6966d.mp4

**Comment by myron-obsolete-account** [comment]
oh wait nevermind the segment landed in powder snow, but im gonna leave this open because the wither storm shouldnt be taking freezing damage/shaking when in powder snow, maybe you can fix that, nonamecrackers?

**Comment by Globalfirestorm10** [comment]
Aren't the segments pretty much invulnerable to damage? I doubt the segments are taking any damage

**Comment by nonamecrackers2** [comment]
Yeah they aren't taking damage but they shouldn't be shaking... That's really funny to see though

**Comment by myron-obsolete-account** [comment]
hey can someone give that poor wither storm segment a scarf? that dude's freezing to death!

**Comment by Globalfirestorm10** [comment]
> hey can someone give that poor wither storm segment a scarf? that dude's freezing to death!

Good luck finding or making one big enough for that ONE segment XD

**Comment by Globalfirestorm10** [comment]
> Yeah they aren't taking damage but they shouldn't be shaking... That's really funny to see though

True

**Comment by nonamecrackers2** [comment]
Will be fixed in 2.2.1/3.2.1

**Comment by Globalfirestorm10** [comment]
honestly, you should've kept this in as a funny easter egg, but ok
