### ISSUE TITLE
Two suggestions in one

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#828]
**Description of feature**
Perhaps in the bowels, there could be liquid taint leaking from the ceiling, similar to water leaking from a cave roof. I also think there should be small pools of liquid taint that you can harvest (via something like a bottle or bucket) and use to craft/make tainted blocks from regular blocks. While this may seem like a stupid idea, I think it would be great for builders (and people who would like to see some more ambience in the bowels). The taint leaking doesn't have to be complex either, if water is above a cave in normal minecraft,there is particles that show it leaks through, you can simply just copy that, apply the same logic to the bowels, and just make them purple instead.

**Comment by Aimyx** [comment]
or just make the water purple, and have it spawn on the ceiling

**Comment by Globalfirestorm10** [comment]
Wait, why'd the "to be confirmed" label get removed?

**Comment by nonamecrackers2** [comment]
The entire label has been removed from all the issues, was unnecessary as features get worked on in secret and I never change them to "confirmed" once they're in development.

**Comment by Globalfirestorm10** [comment]
fair enough, thanks for explaining. That aside, what is your opinion on this feature request?

**Comment by nonamecrackers2** [comment]
Not sure yet

**Comment by Globalfirestorm10** [comment]
fair enough

**Comment by nonamecrackers2** [comment]
Considering you can now craft the tainted blocks with the withered beacon, I don't think this is very necessarily/worth my time to implement

**Comment by BluePineappleGuy** [comment]
i mean, some sort of withering liquid could be nice for traps and stuff, as there isn't any common counteract to wither+wither sickness.
