### ISSUE TITLE
Wither storm teleporting

### ISSUE THREAD

**Issue by TaterKing** [nonamecrackers2/crackers-wither-storm-mod#83]
I'm using a Minecraft story mode map first of all. I try too summon the witherstorm using the summon command (/summon witherstormmod:wither_storm ~ ~ ~) and then it just disappears I don't know why so if you could lemme know that would be cool.

**Comment by Jukabofy** [comment]
Peaceful mode?

**Comment by TaterKing** [comment]
yes......... pls help my dumb brain

**Comment by TaterKing** [comment]
thanks
