### ISSUE TITLE
Config Setting for Distant Renderer

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#830]
**Description of feature**
So I recently installed a mod which disables fog so I could clearly see the Wither Storm in the distance.
![Java-runtime-gamma 2023 01 02 - 15 18 18 06 (1)](https://user-images.githubusercontent.com/53058491/210606500-46144234-86a6-4fed-ad5a-e1c2fa0dca01.png)
Now it looks kind of weird to me when the tractor beams are white, so could you maybe make a new setting to keep the color of the tractor beams pink when the storm is far away?

For anyone asking: the mod is called NoFog and it's NOT OptiFine.

**Comment by ghost** [comment]
### _I think the author will notice this but say that it should be like that. (THIS IS A SUGGESTATION AND MAYBE EVERYTHING IS DIFFERENT)_

**Comment by watersofnazareth** [comment]
This is just due to a Minecraft limitation I'm pretty sure, honestly the mod relies on fog for impact

**Comment by watersofnazareth** [comment]
> ### _I think the author will notice this but say that it should be like that. (THIS IS A SUGGESTATION AND MAYBE EVERYTHING IS DIFFERENT)_

Wh...?

**Comment by myron-obsolete-account** [comment]
> This is just due to a Minecraft limitation I'm pretty sure, honestly the mod relies on fog for impact

I don't think the white color is from Minecraft limitations, however it is not that big of a problem that they are white and if there is no way to change that if it's from Minecraft.

**Comment by V0calgiant12** [comment]
Can't you just turn off the distant render fog and it becomes normal again?

**Comment by myron-obsolete-account** [comment]
> Can't you just turn off the distant render fog and it becomes normal again?

what exactly do you mean by that

**Comment by myron-obsolete-account** [comment]
the fog is a minecraft thing and i got a mod to disable the fog. the tractor beam colors are probably programmed to become white when the wither storm is far away, so i asked if there could be an option to keep the tractor beams pink when the storm is far away from the player

**Comment by watersofnazareth** [comment]
You can turn off distant fog in the client settings btw

**Comment by V0calgiant12** [comment]
Exactly what I was saying above

**Comment by myron-obsolete-account** [comment]
oh i didnt notice there was a setting for that bro im so stupid thank you
