### ISSUE TITLE
Just one question.

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#831]
Is it okay if I made a mod that adds a way to make a command block in survival mode + place it so you can resummon the Wither Storm? I actually made that mod for this mod to be able to resummon the Wither Storm.

If you, nonamecrackers2, already have planned an idea on how to resummon the Wither Storm then I will delete the mod I made because then it would be useless (but that's fine)

**Comment by Jackmo2207** [comment]
There's a mod for this already so yes (but it's planned to be added to the main mod)

**Comment by watersofnazareth** [comment]
A way to resummon is planned but you're fine to make a mod about that if you want, tho some already exist, for now I will close this issue, hope that answers your question

**Comment by myron-obsolete-account** [comment]
okay thank you
