### ISSUE TITLE
Wither Storm Segment getting pushed around by Alex's Mobs' Rhinoceros

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#833]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
Wither Storm Segment getting pushed around by Alex's Mobs' Rhinoceros.

**To Reproduce**
1. F-Bomb the Wither Storm
2. it's hard to make the segment land exactly on the rhinoceros, but I think using [the mob battle mod](https://www.curseforge.com/minecraft/mc-mods/mob-battle-mod) will have a similar result (make the rhinoceros attack the segment)
3. watch the segment getting bullied :(

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No.

**Video:**
https://user-images.githubusercontent.com/53058491/210805305-59176746-7316-4497-9447-2375b371a516.mp4

---

_btw nonamecrackers2 if you read this I asked a question in closed issue #823 could you please answer to that thanks_

**Comment by TheEyeOfGaming** [comment]
thats a very funny bug LOL

**Comment by ghost** [comment]
dude the video is not working
https://user-images.githubusercontent.com/119749553/210806410-e582e100-a376-4bac-8f4d-70f819196b38.png
### changed: it seems to be there but it is not shown on GitHub

**Comment by myron-obsolete-account** [comment]
> dude the video is not working https://user-images.githubusercontent.com/119749553/210806410-e582e100-a376-4bac-8f4d-70f819196b38.png
> ### changed: it seems to be there but it is not shown on GitHub

what are you trying to tell me

**Comment by watersofnazareth** [comment]
Like the bug with Create this is pretty much a edge case with Alex's Mobs, you can report it to them instead of here as we can't do too much about this
