### ISSUE TITLE
Visual Tractor Beam Issue

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#834]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
When looking at the tractor beams from the wither storm at a specific angle it kind of... breaks? please look at the video

**To Reproduce**
1. summon wither storm
2. slowly move around wither storm's tractor beams
3. see sometimes the layering messes up or a spot gets darker or whatever happens there

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No

**video::**
https://user-images.githubusercontent.com/53058491/210814878-45ead9c2-81f1-4eac-a815-bdf6b5d3d414.mp4

**Comment by watersofnazareth** [comment]
This is just how Minecraft's rendering handles translucent textures
