### ISSUE TITLE
Create Mod can do anything with Wither Storm Mod Entities

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#835]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
Create 0.5.0g contraptions can push around segments and the command block

**To Reproduce**
1. get create and build anything that moves (trains probably work too)
2. teleport a segment, activate contraption and watch the chaos

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No

**Videos:**
https://user-images.githubusercontent.com/53058491/210815726-483e55b4-7f5c-405b-b53e-2eb86a5e4039.mp4

**Comment by watersofnazareth** [comment]
We can't really do anything about this as it's not a actual bug and it's on the create side, plus this isn't something that would happen without you *really* trying to do it
