### ISSUE TITLE
Compatible with distant horizons

### ISSUE THREAD

**Issue by Bagheera68** [nonamecrackers2/crackers-wither-storm-mod#837]
I know you can run it with distant horizons, but what if you made it where it looks right with distant horizons like the wither storm is in the distance destroying stuff while it comes to you. I know this isnt a high probability, but it would be cool.

**Comment by GrandmaPork** [comment]
Seeing distant block clusters?

**Comment by TheEyeOfGaming** [comment]
would be cool, but not sure if its possible

**Comment by watersofnazareth** [comment]
This would have to be opened up with Distant Horizons
