### ISSUE TITLE
Ender Dragon being the Wither Storm's "Moon"

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#838]
**Description of feature**
If the player somehow manages to bring the Wither Storm to the End (or uses cheats to do that) the Ender Dragon could be starting to orbit the Wither Storm when the storm is at phase 4 or above. Imagine looking up and seeing the dragon and the storm being best friends 🗿

**Comment by ERCEpic** [comment]
I think that would be cool

**Comment by nonamecrackers2** [comment]
It isn’t possible to bring the wither storm through dimensions, and this feature would take a lot of time to develop with barely anybody noticing, sorry.
