### ISSUE TITLE
More Tainted Blocks

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#839]
**Description of feature**
So first of all, instead of using foilage coloring, it would be better to actually have tainted leaves, tainted grass and tainted grass blocks, so you can place them in your home in the overworld without the color being biome-defaulted.
Next, how about a whole tainted wood system? Like, having tainted wooden logs which can be used for planks, which you can use to make stairs, slabs, fences etc. to make a tainted house, for example, would be insanely cool. It would also look better for the structures in the bowels.

And how about you could convert a tainted flesh block into 9 tainted flesh clumps (which you can turn back into a block) and when you try to eat one of the tainted flesh clumps, you get infected with the Wither Sickness, no matter if theres an active Wither Storm in the world or not (the effect could maybe only last like 10 minutes).

And most importantly, tainted water which sickens anyone/-thing that swims in it would be cool too.

_(tainted dirt would be not so interesting but nice for designing)_

**Comment by watersofnazareth** [comment]
More tainted blocks will be added into the next update, it's been discussed in the Discord server a bit and have been added by yours truly

**Comment by NinjaSam5399** [comment]
I would like tainted dirt.

**Comment by Aimyx** [comment]
Oh boy, here i go making a tainted dirt hut again!

**Comment by myron-obsolete-account** [comment]
Imagine a whole minecraft world but the blocks are swapped with their tainted versions. Imagine the villages duh

**Comment by nonamecrackers2** [comment]
Implemented in 2.2/3.2
