### ISSUE TITLE
[Rotation Speed Config Option] A couple suggestions

### ISSUE THREAD

**Issue by ShirakiShio** [nonamecrackers2/crackers-wither-storm-mod#84]
- Adding a rotation speed slider, which enables you to determine the speed at which the Witherstorm will turn towards you if you are behind it or similar, would be a pretty handy thing.

- The cyan glow it gave off at night (notably in S1E1, when it approached the forest.)

- The purple sky the final phase created(?) in S1E4, towards the end.

- It would be super cool if you could establish properly looping track sections for each phase. (not each but the major ones, hunchback, destroyer, split)

- When carrying an enchanted weapon (enchanted via. command block book), the game will play the 'fighting' part of the witherstorm theme once it has reached phase 7.

**Comment by nonamecrackers2** [comment]
The rotation speed slider will be added. The other's will need further processing.

**Comment by nonamecrackers2** [comment]
Different themes will be used for different major parts of the WS evolution (using a different suggestion to track this), including the purple sky, etc.
