### ISSUE TITLE
New Wither Storm Death Sound

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#840]
I decided to spend some time on making a new death sound for the Wither Storm. I tried to keep it as similar to the current death sound as possible, while still making noticeable changes. I listed some mainly noticeable audio features and things that are different here:
- It now sounds more like the storm is ripping apart and dropping _many_ block clusters to the ground (in the old sound there were only around 6 thuds 'n' thumps, now there are 14)
- The sound is a bit longer than before (22.5 seconds)
- The sound doesn't end so suddenly, I added a bit of a fade-out and moved audio parts around to make it sound more "realistic"
- Added a bit of echo effects
- You can literally _feel_ the Wither Storm's death

For those who want to listen to it without downloading it:

https://user-images.githubusercontent.com/53058491/211169953-d9e514e4-307d-439b-9cd2-ad09aaed3522.mp4

File:
[wither_storm_death.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10367148/wither_storm_death.zip)

**Comment by ERCEpic** [comment]
I like it!

**Comment by myron-obsolete-account** [comment]
thank you!

**Comment by OliversIntention** [comment]
i like this

**Comment by nonamecrackers2** [comment]
Gonna leave the sound as it is, but feel free to make a resource pack using your new sound :)
