### ISSUE TITLE
Lower The Defaut Flying Height

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#841]
**Description of feature**
As stated in the title, the flying height should be a bit lower by default. Most of the time in MCSM the Wither Storm is lower to the ground, and the current default flying height in CWSM is a bit too high. Looks weird I guess. A flying height of 25 would be too low, so I think about 50 blocks above the ground as default would be perfect huh?

And yes we can turn down the flying height everytime we make a new world but it starts to get annoying and having it set automatically is like a dream coming true.

**Comment by GrandmaPork** [comment]
Adjust the configs for one world, then set it in the “defaultconfigs” folder

**Comment by myron-obsolete-account** [comment]
ight thanks
