### ISSUE TITLE
Evolution Attribute Modifier at lowest possible breaks

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#842]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
When I move the slider all way to the left (value 0.01), and then open the mod's config using Create's config menu the value actually goes a little bit lower (0.009999999776482582) + I didn't notice that the evolution speed got faster in-game because that value is an invalid value.
![image](https://user-images.githubusercontent.com/53058491/211205145-4b4ffb5c-57ac-42bf-bdd6-8c21e072014a.png)

**To Reproduce**
1. Get Create
2. Make new world and set evolution attribute modifier to lowest
3. Save config settings
4. Type command `/create config`
5. Open witherstormmod's config through Create's config menu (click "access configs of other mods" then scroll to find the witherstormmod and click the double arrow button, go to server config and scroll down until you can find the evolution attribute modifier config)
6. See that the value is... weird.

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No.

**Screenshots**
No, not really.

**Comment by watersofnazareth** [comment]
This is just the closest approximation of the decimal representation of 0.01, basically funny coding does this nothing can be done about this it's just how 0.01 is read, this has no affect on the game and it's not invalid because it's not set to 0, very basic explanation but this can't be fixed

**Comment by myron-obsolete-account** [comment]
alright
