### ISSUE TITLE
[UNFIXABLE] Bowels is null also occurs on amplified worlds.

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#843]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
The bowels is null crash also happens on amplified worlds. I think every world generation type (except default) isn't loading modded dimensions on world creation :( 

I think you should warn people on the CurseForge page about that

**To Reproduce**
1. Make new world
2. Set generation type to amplified
3. Summon WS

**Crash Reports / Logs**
bowels is null

**Is Flywheel's optimizations active?**
No.

**Screenshots**
N/A

**Comment by watersofnazareth** [comment]
Reload the world after creating it

**Comment by myron-obsolete-account** [comment]
yeah i know that i just wanted to let the developer(s) know it doesnt only happen on superflat worlds

**Comment by watersofnazareth** [comment]
#614

**Comment by myron-obsolete-account** [comment]
> #614

I am aware of reloading the world being a solution bruh
