### ISSUE TITLE
Bowels open after dragon was killed

### ISSUE THREAD

**Issue by MirokaSult** [nonamecrackers2/crackers-wither-storm-mod#844]
I know something similar but overcomplicated was already suggested, but I think it would be pretty cool to just make so that bowels open only after you kill the ender dragon, it will add an immersion that endermen are leaving end and interacting with the WS.

**Comment by myron-obsolete-account** [comment]
Wouldn't make much sense in my opinion + I don't think all players who want to suffer from the Wither Storm also want to beat the game, just to be able to kill the Wither Storm afterwards. Also there are already a lot of Endermen spawning in the overworld anyways so you can get that feeling that they harm the WS to open the hole without having to beat the dragon first.

Also, why would the Endermen leave the end just because the Ender Dragon is dead? Just a side thought.

**Comment by ghost** [comment]
**### + let's be honest. In the original, the endermen left the ender world due to the fact that the main characters of the game Minecraft Story Mode
flooded Ender's world with water. And they had nowhere to go, and they went to the ordinary world.**

**Comment by MirokaSult** [comment]
> Wouldn't make much sense in my opinion + I don't think all players who want to suffer from the Wither Storm also want to beat the game, just to be able to kill the Wither Storm afterwards. Also there are already a lot of Endermen spawning in the overworld anyways so you can get that feeling that they harm the WS to open the hole without having to beat the dragon first.
> 
> Also, why would the Endermen leave the end just because the Ender Dragon is dead? Just a side thought.

Developer can always make this a toggleable feature. I know it wouldn't make much sense but after using a formidibomb on the WS you have almost nothing to do but just run and wait, so this will add an additional challenge.

**Comment by MirokaSult** [comment]
> **### + let's be honest. In the original, the endermen left the ender world due to the fact that the main characters of the game Minecraft Story Mode flooded Ender's world with water. And they had nowhere to go, and they went to the ordinary world.**

The thing with flooding the end island was already suggested, but checking if the whole island was flooded is very hard to code if not impossible.

**Comment by ghost** [comment]
well, yes

> > **### + let's be honest. In the original, the endermen left the ender world due to the fact that the main characters of the game Minecraft Story Mode flooded Ender's world with water. And they had nowhere to go, and they went to the ordinary world.**
> 
> The thing with flooding the end island was already suggested, but checking if the whole island was flooded is very hard to code if not impossible.

**Comment by myron-obsolete-account** [comment]
> The thing with flooding the end island was already suggested, but checking if the whole island was flooded is very hard to code if not impossible.

Also there are still millions of other End islands around the main island so it would be insane to fill the entire End with water.

**Comment by watersofnazareth** [comment]
I don't think this would interact with the goal of the mod very well, the mod isn't supposed to be exactly like MCSM and this would ruin the progression of players as the mod encourages you to explore a lot more

**Comment by nonamecrackers2** [comment]
> I don't think this would interact with the goal of the mod very well, the mod isn't supposed to be exactly like MCSM and this would ruin the progression of players as the mod encourages you to explore a lot more

This would also be far better suited for something like a modpack.
