### ISSUE TITLE
[Stop targeting mobs if they’re not moving closer to the storm] Wither Storm gives up on tractor beaming player

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#845]
In the case someone ender pearls behind lots of ground while in tractor beam, they are now caught between the ground and wither storm until the block clusters get absorbed. I think the wither storm should give up on tractor beaming a player after either a configurable amount of time, or if the player is stationary for again, a configurable amount of time.

**Comment by nonamecrackers2** [comment]
This is already implemented but this gave me an idea on how I could further improve the already in place system, so I’ll leave this open

**Comment by GrandmaPork** [comment]
Interesting. I have never noticed this.

**Comment by nonamecrackers2** [comment]
Yeah the time it takes is quite long, which is probably why

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
