### ISSUE TITLE
Hardcore option

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#846]
An optional hardcore feature: the wither storm remembers who it has directly killed (not by fall damage or wither skulls) and “resummons” them after each fake or real death. (Maybe even a chance that they aren’t resummoned until final death) a summoned player could be set from spectator back into survival where they are placed inside of a chunk of tainted flesh. They would be given various 2-3 minute effects like blindness, slowness, mining fatigue, and wither sickness (which obviously isn’t temporary). They’d either have to dig themselves out or something similar

**Comment by V0calgiant12** [comment]
Well, withersickness wouldn't make sense and would be unfair because
1. Wither Sickness dissipates when the storm dies
2. There would be no way to cure if other players don't have the withered stuff needed for a stew

**Comment by GrandmaPork** [comment]
There would likely be leftovers but if not then yeah the players could only get the effect if it’s just a fake death

**Comment by nonamecrackers2** [comment]
I already mentioned in another suggestion mentioning messing with hardcore, and I said no as I don’t have an interest in changing the core mechanic behind the game mode, and I don’t feel like adding development intensive features that I believe the majority of the player base wouldn’t use.

**Comment by GrandmaPork** [comment]
Apparently I already suggested this in #517
