### ISSUE TITLE
A warning for getting the F-bomb or spawning a symbiont in too early 

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#847]
I think there should be a warning for those new to the mod (mostly content makers) when they pull a Formidibomb or command block book out of creative too early. Even if the symbiont is spawned in any stage besides the ones it should.
This could be disabled for testing but I think it might be useful

**Comment by V0calgiant12** [comment]
Yes, this should definitely be a thing. Maybe it could be in the form of lore text on the item or in chat after it checks for the correct conditions

**Comment by nonamecrackers2** [comment]
I’d rather not send intruding chat messages but instead prevent this via gameplay, as in preventing the Wither Storm from being F-Bombed at phase 4.

**Comment by GrandmaPork** [comment]
What about a tooltip like "Not ready" in red
