### ISSUE TITLE
Having more segments if enough force?

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#848]
**Description of feature**
I doubt this would be added due to the mod already having issues with FPS but would be interesting
Could there be a optional feature where if the wither storm gains enough mass in its final stage and that if you were to throw another f-bomb it would make more segments. This didn't happen in story mode but it would make sense for it to happen.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by Globalfirestorm10** [comment]
isn't this just segment duplication but intentional?

**Comment by myron-obsolete-account** [comment]
duplication of #771

as nonamecrackers2 said, if more segments are being added, it would bring back segment duplication which was a glitch where wither storm segments would duplicate in a world, which caused people to get confused why there is still a "wither storm" in the world when they defeated it, and in another youtube video i saw that there were about 20 segments stacked at one place

**Comment by Luke7381** [comment]
> duplication of #771
> 
> as nonamecrackers2 said, if more segments are being added, it would bring back segment duplication which was a glitch where wither storm segments would duplicate in a world, which caused people to get confused why there is still a "wither storm" in the world when they defeated it, and in another youtube video i saw that there were about 20 segments stacked at one place

I forgot this was suggested already. I figured crackers probably won't accept this one.
