### ISSUE TITLE
Texture-Based Tractor Beams

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#849]
**Description of feature**
I think giving the tractor beams a texture would be better, and here are 3 main reasons why:
- color customization (if people want to make color themes, they could change the beam's color to, let's say green, too)
- the beams would _probably_ be visible with almost any shader
- might fix #795

You could just put the color in the texture, and when the texture gets used it just changes the opacity of it so you can still see through it.

**Comment by nonamecrackers2** [comment]
You’ll be able to change the color of the tractor beams in an upcoming update, and I doubt having them texture based would fix the visual glitch.
