### ISSUE TITLE
New models of the wither storm

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#85]
Since it has been some time since launching the mod I suggest editing the models like adding glowing purple areas, new tentacles, and add particals to the tracktor beam and if these are hard to do you don't have to add all of them at the same time and make the wither storm look better if this is hard to do it's just a suggestion the wither storm is cool with this model I'm just suggesting for new models

**Comment by nonamecrackers2** [comment]
I think the models are fine as they are. Making new models which achieve the same product currently available except slightly different wouldn't make much sense. Particles for the tractor beams have already been suggested.
