### ISSUE TITLE
Gamerule mobGriefing on false doesn't prevent dying WS from dropping block clusters

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#850]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
When I set the gamerule mobGriefing to false, the Wither Storm still drops block clusters when dying. In my opinion this should be disabled when the gamerule is set to false, since the WS is technically griefing the terrain which is located below it, using it's block clusters to replace blocks.

**To Reproduce**
1. set the gamerule mobGriefing to false
2. kill any Wither Storm at or above phase 5+
3. See error

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No.

**Video**

https://user-images.githubusercontent.com/53058491/212144240-299e5c83-43b0-4d4d-9184-100037ecf282.mp4

(sorry for the low quality/bitrate, I had to export the video like that so it doesn't get too big)

**Comment by nonamecrackers2** [comment]
Will be fixed in the next 1.19.4/1.20.1 release

**Comment by myron-obsolete-account** [comment]
thank's you are a real W
