### ISSUE TITLE
Solution for OptiFine/Shader rendering problems found!

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#851]
This is not a bug report, neither a feature request, but I just want to announce that I have found a solution for rendering issues when using OptiFine/shaders.

To fix the general entity-not-rendering-when-looking-away you need [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium/files/4024781) (Sodium for Forge) instead of OptiFine, it also tries to optimize the game while not actually changing entity rendering stuff (might need to disable entity culling in video settings > performance to always make the WS show up, not sure though)
For shaders you need [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus/files/4299147) which is a Forge ver. of Iris. It only works if you use Rubidium and the tractor beams are completely visible when using shaders this way!

**BLOCK CLUSTER COLORING DOES NOT NEED TO BE TURNED OFF!**

(screenshot from far away)
![2023-01-13_15 27 22](https://user-images.githubusercontent.com/53058491/212344534-5dab49b9-240c-4852-9369-dd4d59ae1667.png)

(a close-up screenshot)
![2023-01-13_15 31 40](https://user-images.githubusercontent.com/53058491/212344648-21062892-de95-49dd-9944-416b33638e21.png)

I don't know if many people already know this solution, but I think the majority of CWSM-fans doesn't know this, so you're welcome.

_As a side note, this way of using shaders somehow also fixes issue #795_

**Comment by V0calgiant12** [comment]
The block cluster coloring needing to be turned off depends on the shader.

**Comment by myron-obsolete-account** [comment]
i dont think so because with optifine + complementary sh. it crashed when block cluster coloring was on but with rubidium x oculus and complementary sh. + block cluster coloring on doesnt crash the game

however you may be right with your statement

**Comment by nonamecrackers2** [comment]
Closing since this isn’t a suggestion or bug report.
