### ISSUE TITLE
Command Block entity emissive texture layer

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#852]
**Description of feature**
It would be nice if you could add an emissive texture layer to the command block entity to make it look better generally and/or with shaders

Command Block with shaders looks like this, notice that the areas where these "light bulbs" are lighting up
![2023-01-13_19 19 09](https://user-images.githubusercontent.com/53058491/212391557-4dc3b74e-cc2a-4d75-aa7d-1b1d87fbc56e.png)

How the entity looks like with shaders
![2023-01-13_19 23 15](https://user-images.githubusercontent.com/53058491/212392223-64809b62-a1e4-49cf-b3cf-5b19f6aed4da.png)

Side-by-side comparison, block - entity
![2023-01-13_19 23 29](https://user-images.githubusercontent.com/53058491/212392268-a929e2b4-e77f-4f2f-aad0-e2f9d003a491.png)

**Comment by nonamecrackers2** [comment]
The command block entity just uses the existing command block model and texture, so the emissive texture should just work. Explicit support with shader mods for the command block entity to render the emissive texture when shaders are enabled is a compatibility layer I do not want to implement, instead they would have to do something about this.
