### ISSUE TITLE
Tentacle Angle Change

### ISSUE THREAD

**Issue by GoldInvestor1006** [nonamecrackers2/crackers-wither-storm-mod#853]
This is more of a personal preference, and I know you aren't interested in changing the models at the moment, but it never felt quite right to me to have the tentacles of the main storm in later phases facing upwards. I would prefer downwards or sideways (or a mix) but do what you will with them.

I have a (poorly drawn) mockup of what it could look like. (yes i made it in paint 3d)
![WitherStormMockup](https://user-images.githubusercontent.com/31906108/212446084-3aae387d-0f8b-4678-b812-e488485e53d1.png)

**Comment by TheEyeOfGaming** [comment]
tbh in my preferece is that the 2 giant tentacles get removed when they split into 3 Witherstorms and then soon regrow them when they evolve more

**Comment by nonamecrackers2** [comment]
Yes, as you said I currently don't really have a big enough reason to change the models up, nor is it in my best interest.
