### ISSUE TITLE
in minecraft story mode at night the wither storm can be seen to glow in the dark now i know this makes no sense but look at this pic

### ISSUE THREAD

**Issue by Wither5575** [nonamecrackers2/crackers-wither-storm-mod#855]
**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested. List of commonly suggested features: https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**ONLY ONE FEATURE REQUEST PER ISSUE**
![image](https://user-images.githubusercontent.com/114622205/212487622-bd335eb2-fa0f-414b-98ed-8d4dda0b1f3f.png)

**Comment by nonamecrackers2** [comment]
#744 https://youtu.be/CqFPhL6ZDro?t=28

**Comment by Wither5575** [comment]
i did not see that my bad
