### ISSUE TITLE
A new way of how the Withered Symbiont Spawns

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#856]
**Description of feature**
Instead of the Symbiont just popping up like annoying YouTube ads, one of the WS-heads could shoot a flaming soul wither skull, which on impact with the floor causes an explosion and summons the Symbiont. But thats not it, the Symbiont should be in a invulnerable state (so you can't even harm it's back scratch) for like 10 seconds and after that it gets active. It's like the Symbiont has to gain power first before it can act.

[I actually designed a few textures and sounds for this (click to download .zip)](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10418663/new_symbiont_spawn_idea.zip)

Flaming Soul Wither Skull texture preview:
![2023-01-14_20 04 11](https://user-images.githubusercontent.com/53058491/212492451-01f0617c-3b79-4d52-a688-1c1f0405a522.png)

Invulnerable Withered Symbiont texture preview:
![2023-01-14_20 04 18](https://user-images.githubusercontent.com/53058491/212492471-a9debb52-e159-4be9-ac40-3271b3871034.png)

Ditto but back:
![2023-01-14_20 04 20](https://user-images.githubusercontent.com/53058491/212492481-fad1cb09-b29f-4de0-82da-f3287f1e36cb.png)

**Comment by TheEyeOfGaming** [comment]
thats a sick idea! wonder if cracker will like the idea

**Comment by myron-obsolete-account** [comment]
I actually wanted to suggest this 2 weeks ago but then thought "nah crackers probably wont accept this" but now I did it anyways so let's see what hes gonna say

**Comment by ghost** [comment]
> На самом деле я хотел предложить это 2 недели назад, но потом подумал: "Нет, крекеры, вероятно, не примут это", но теперь я все равно это сделал, так что давайте посмотрим, что он скажет

Yup

**Comment by nonamecrackers2** [comment]
I feel the skull idea doesn’t really emphasize and fit in with the command blocks ability to spawn mobs from thin air, which is consistently used throughout the final battle.

**Comment by YassinAlaa** [comment]
> I feel the skull idea doesn’t really emphasize and fit in with the command blocks ability to spawn mobs from thin air, which is consistently used throughout the final battle.

Ummm ur right but this animation looks great + the texture he made looks so sick🔥 
I wish u add it
