### ISSUE TITLE
Command Block Bow(/Crossbow?)

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#857]
**Description of feature**
Crafting + Usage Idea:
Smithing Table --> Bow + Enchanted Command Block Book = Command Block Bow

If you have arrows, it shoots the arrows as command block arrows, which can harm the Command Block entity in the final boss fight or trigger the WS to revive, so you don't have to go near it with a melee command block weapon. The arrows could also spawn the command block particles around them like dropped command block items do.

Maybe you could even do the same thing with a Crossbow.

**Comment by Jackmo2207** [comment]
This would break the final boss and make it extremely easy

**Comment by myron-obsolete-account** [comment]
actually a fair point
