### ISSUE TITLE
Wither Storm can't kill specific mobs

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#858]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
The heads of the WS can't kill these flying things (watch the video below)

**To Reproduce**
1. Get Alex's Mobs
2. Spawn WS in End
3. Spawn some "Spectres"

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No.

**Video**
(ignore the watermark I had to use some crappy video compressor)

https://user-images.githubusercontent.com/53058491/212500735-71be974d-2bda-4263-a9e7-bebead22f6d3.mp4

**Comment by watersofnazareth** [comment]
It's because they're immune to the Wither Storm trying to kill them, see #721, don't know why this issue happens because the Wither Storm's bite is pretty much exactly like the kill command
