### ISSUE TITLE
Water can move the command block on a exploded wither storm (at least on 1.18.2)

### ISSUE THREAD

**Issue by NEFFLEAFF** [nonamecrackers2/crackers-wither-storm-mod#86]

**Comment by Abasthepro** [comment]
What why if the wither storm is playing dead how do you want the command block to move when its on water and its a heavy block btw I'd rather say no

**Comment by NEFFLEAFF** [comment]
This is not a suggestion, it's a bug

**Comment by Abasthepro** [comment]
> 

Uhh OK nvm i guess at least type issue but nvm

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update

**Comment by nonamecrackers2** [comment]
Actually going to reopen this as I think 1.16.5 is affected as well

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update
