### ISSUE TITLE
Symbiont beacon

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#862]
Withered symbiont can be very difficult to find mid-battle. Especially if you die and try to find him + your gear.
I propose a beacon similar to what the end gateway portals have where it’s temporary but allows you to find it. Maybe like something from hocus pocus until you get close enough to see it.
Alternatively you can just use the glowing effect, maybe add a config option for the withered symbiont to always have the glow effect

**Comment by watersofnazareth** [comment]
#451
