### ISSUE TITLE
Alternative way to render tractor beam

### ISSUE THREAD

**Issue by TheGubBit** [nonamecrackers2/crackers-wither-storm-mod#863]
**Description of feature**
I thought about this for only a little bit, but a way to render the tractor beam, is to get the height from sea level, to the eye, then get tangent length, and do this for each corner of the eye to then create the tractor beam box. It could cause lag due to all the calculations, however I think rendering it like this would be awesome.

As of right now, I have used it twice, when programming a limit to a camera's height, and for creating random lightning.
So far it has worked great, no lag or anything, and on top of that, I used Roblox Studio.
On top of that Minecraft has optimized versions of sinus, cosinus and tangent, so it dosen't lag as much when calculating.

- Gullible Gulibiesating Gulleast#3749

**Comment by myron-obsolete-account** [comment]
I think this might fix the issue that the tractor beams are off-place when the WS has been resized using Pehkui. Didn't want to create an issue report for that tho because it's not that bad actually.

**Comment by Aimyx** [comment]
Yeah, this would be cool to see.

**Comment by BluePineappleGuy** [comment]
would maybe fix the seeing tractor beam deep underground issue

**Comment by nonamecrackers2** [comment]
I feel this method would be extremely performance intensive and may not work very well, however I have another idea on how to limit the tractor beams from appearing when underground

**Comment by BluePineappleGuy** [comment]
> I feel this method would be extremely performance intensive and may not work very well, however I have another idea on how to limit the tractor beams from appearing when underground

👀

**Comment by LocalWaterCreeper911911** [comment]
> I feel this method would be extremely performance intensive and may not work very well, however I have another idea on how to limit the tractor beams from appearing when underground

👀
