### ISSUE TITLE
"Is it the end?" achivement bug

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#867]
So as i was playing i wanted to use the spyglass and look at the sun for no god damn reason and then i got the achivement "Is it the end?" and the wither storm wasnt even spawned in yet *i would send the vid but github wont let me so sorry*

**Mod version**
The version of the mod you are using
1.19.2

**Is Flywheel's optimizations active?**
Yes

**Comment by V0calgiant12** [comment]
This is a known issue and has already been reported at #745

**Comment by nonamecrackers2** [comment]
#745
