### ISSUE TITLE
NoAI:1 should disable roaring

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#869]
**Description of feature**
It would be nice if you could make the heads stop roaring when the storm's AI is turned off with commands, because I want to make a short video for a custom desktop wallpaper but the heads mouths opening all the time is kind of annoying.

**Comment by myron-obsolete-account** [comment]
Okay I can't find a way to create a perfect looped GIF with the tentacle movements but I'll leave this open because the idea is still good I think.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
