### ISSUE TITLE
New form of distraction for the Wither Storm

### ISSUE THREAD

**Issue by Gaboamau** [nonamecrackers2/crackers-wither-storm-mod#87]
I thought of another way for the Wither Storm to be distracted (in addition to the one it already has) that could be interesting to implement in the Mod, like in MC:SM, the Wither Storm likes to consume structures, so what you could implement is that when the Wither Storm comes into contact with a naturally generated structure such as a village, the Wither Storm will distract itself for a few minutes by consuming that village, giving us time to escape and when those minutes are up, the Wither Storm will start chasing us again. This could also work with other structures like mansions or temples and the bigger the structure the longer it will stay distracted.

Although I think this might be difficult to implement, I still like the mod as it is, and I hope you continue to work on this very unique project.

**Comment by nonamecrackers2** [comment]
Instead, I could probably take the current distraction system and instead make it go to nearby structures (as previously it would just go to a random position nearby)

**Comment by GrandmaPork** [comment]
I think the taller the structure, the higher the priority

**Comment by watersofnazareth** [comment]
Implemented as of the Prereleases
