### ISSUE TITLE
Falling Segments when CMD-Block's health is at 16

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#871]
**Description of feature**
The Command Block doesn't have enough power anymore to hold 2 extra Wither Storms up in the air, and it needs its power for itself to defend itself against the player, who's trying to destroy it.

May not be so noticeable, however there is already that feature where the segments struggle when trying to hold themselves up in the air (they sometimes fall a few blocks and slowly move up again) so why not making the segments fall and die early? Would make kind of sense I guess.

**Comment by nonamecrackers2** [comment]
I don’t feel this is necessary and I honestly prefer the current system as it is. Killing them off early would also make the final death animation lose some of its jazz
