### ISSUE TITLE
Something inbetween the main storm and segments (I can't find the right word for it)

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#872]
**Description of feature**
I think it would look insanely better if there was something like this

![this](https://user-images.githubusercontent.com/53058491/213670478-04c5e988-d49b-4d79-a5ca-a05a03cfed04.png)

between the main WS and the segments, as if the command block controls the segments seperately and tells them what to do (which basically is the case, but a bit more of a visualization of it would be nice I guess)

It's like the CMD-Block is sending out it's power to the segments and it kinda also makes it look like the main storm holds the segments up in the air. This could be a toggleable option, off by default, as it's just a visual detail.

I thought of something that kind of looks like a mixture of these 3 things:

- Guardian's attack beam
- That visualized wind that appears around the player when he uses a trident while it's raining
   ![image](https://user-images.githubusercontent.com/53058491/213672311-a953953a-9f8d-42b9-b647-ac591cf00d2d.png)
- The healing beam that ender crystals shoot to the Ender Dragon

**Comment by NinjaSam5399** [comment]
That looks very cool.

**Comment by TheEyeOfGaming** [comment]
cool idea

**Comment by myron-obsolete-account** [comment]
I didn't expect you to actually "accept" this feature request, because I thought that it's actually kind of unneccessary.

**Comment by SmoothWolf20** [comment]
I very much like this.

**Comment by nonamecrackers2** [comment]
I don't feel this would fit in the mod very well personally and may look quite out of place
