### ISSUE TITLE
Make Sickened Creepers drop tainted dust like normal creepers drop normal gunpowder

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#873]
It is unclear if tainted dust is supposed to be like redstone or like gunpowder but I think its just both, especially because you can't use it like redstone

**Comment by nonamecrackers2** [comment]
Tainted dust is really just a block light decoration and I don’t think sickened creepers should drop it

**Comment by GrandmaPork** [comment]
I see it more as tainted redstone dust than tainted gunpowder. A redstone use would be really cool tho. Maybe it has a longer circuit length
