### ISSUE TITLE
Roaring without shooting skull

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#874]
**Description of feature**
The WS should roar without shooting a flaming skull because it just doesnt really make sense i think like look they shoot skulls all the time but dont roar a single time without shooting a skull xd

**Comment by V0calgiant12** [comment]
#689

**Comment by myron-obsolete-account** [comment]
My bad.

**Comment by V0calgiant12** [comment]
All good
