### ISSUE TITLE
Wither Storm is not coming after me

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#875]
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
I was riding my horse for 20 minutes straight and the WS I had on my back didn't move his ass just one inch. I think it is "distracted" (feature) but it shouldn't be "distracted" this long (bug), right?

**To Reproduce**
1. Summon storm
2. gtfo
3. get as far away as you can
4. See error (may not always be reproduceable)

**Crash Reports / Logs**
N/A

**Is Flywheel's optimizations active?**
No.

**Screenshots**
N/A

**Comment by myron-obsolete-account** [comment]
Oh yeah of course! While I was away, writing this report, the WS decided to fly towards me again!
But is it normal that it's distracted that long? The time he was distracted was like 30 minutes.

**Comment by Jackmo2207** [comment]
I think it's distracted for about 25 minutes yeah

**Comment by V0calgiant12** [comment]
Yeah, that's completely normal

**Comment by myron-obsolete-account** [comment]
Just checked the configs and you're right, thanks. I'm going to lower the value and override the default server config file with that so it stays on my set value for every new world I make.
