### ISSUE TITLE
Wither Storm's Body doesn't rotate with player's head movements when constantly teleporting storm to player

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#876]
I don't really think it is a bug, and I am kinda requesting a feature with this issue. Could you change some stuff that when someone teleports the storm with specified rotation, the body rotates that way too? Would be cool for if you want to play as the WS using a repeating CMD-Block which teleports the storm to a player all the time.

**Comment by nonamecrackers2** [comment]
Change the `YBodyRot` nbt tag to change its rotation.

**Comment by myron-obsolete-account** [comment]
Oh thank you.

**Comment by myron-obsolete-account** [comment]
bro i had so much fun messing with the XBodyRot nbt tag sorry but you have to see this @nonamecrackers2 

https://user-images.githubusercontent.com/53058491/213804739-d255335d-31c6-4128-8453-13c39e1fc247.mp4

**Comment by myron-obsolete-account** [comment]
okay yeah uh how do i make the body rotate to wherever i look to (on Y axis)? i already did the very basic thing using `execute at Slebbey run tp @e[type=witherstormmod:wither_storm,limit=1] ~ ~25 ~ ~ ~` in a repeating command block but now i might need a little help i guess

**Comment by myron-obsolete-account** [comment]
ok the body now rotates to whereever i look, is it possible to make the body rotate _slowly_ or is it only possible to rotate it that fast?

**Comment by nonamecrackers2** [comment]
I believe that you can only make it snap to your head, you could try scoreboard garbage however I'm not sure how you'd do that.

I also raise you this https://streamable.com/2g5gki#

**Comment by myron-obsolete-account** [comment]
> I also raise you this https://streamable.com/2g5gki#

Made my day
