### ISSUE TITLE
Storm wither doesn't open her head portal

### ISSUE THREAD

**Issue by ELJOKER900** [nonamecrackers2/crackers-wither-storm-mod#877]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
When I generate the storm wither it doesn't play that music, I found the button to play it but when the command block after that this effect speeds up when it slows down the command block (that start music) minecraft stops and crashes

**To Reproduce**
1.create a new world with 1.19.2
2.spawn the storm wither
3.enable boss themes
4.wait
and that's it

**Crash Reports / Logs**
[crash-2023-01-21_12.04.18-server.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10472025/crash-2023-01-21_12.04.18-server.txt)

**Is Flywheel's optimizations active?**
I don't know, maybe it's not that, but maybe I'll put it in the crash text

**Screenshots**
I don't know why I will put this in the image if by saying that it crashes you already know what it is

**Comment by ELJOKER900** [comment]
Hello everyone, it's me again and I want to tell you that this is not a bug since I have discovered that if you activate the music while it is generated it crashes, but if you activate it before it does not crash, the same is something else.

**Comment by ELJOKER900** [comment]
I'm sorry again, it's a bug, why does it crash when the song starts

**Comment by Globalfirestorm10** [comment]
Are you on a flat or amplified world? This seems to be a "bowels is null" crash, which is very common on these world types

**Comment by myron-obsolete-account** [comment]
any other world type than default wont load modded dimensions on world creation, see #843 

if that doesnt seem to be the issue then i dont know what it is

**Comment by myron-obsolete-account** [comment]
oh yeah this is from your crash report/log
`java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerLevel.getCapability(net.minecraftforge.common.capabilities.Capability)" because "bowels" is null`
"because bowels is null" is a known issue, fixed by reloading the world you are playing on, so please close this issue as this is a duplicate of #614 and #718

**Comment by ELJOKER900** [comment]
oh , is the normal world

**Comment by ELJOKER900** [comment]
oh ok

**Comment by ELJOKER900** [comment]
but how to i close this issue?

**Comment by myron-obsolete-account** [comment]
@ELJOKER900 
![image](https://user-images.githubusercontent.com/53058491/213878441-48a639cb-7329-401a-be84-aa41b896d391.png)

**Comment by ELJOKER900** [comment]
thanks

**Comment by ELJOKER900** [comment]
but here are other bug

**Comment by myron-obsolete-account** [comment]
the portal thats btw actually just a hole, opens after 6 minutes (configurable) when the player has a command block tool, and the hole only appears when the storm is at phase 7

**Comment by ELJOKER900** [comment]
oh

**Comment by ELJOKER900** [comment]
ok
