### ISSUE TITLE
Tainted Plants

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#878]
The bowels only have 2 plants, mushroom, and grass (coming soon). but still not enough for the bowel. So I think you should add more. You could add cactus (touch them and it will damage you and causes you to  get/worsen your  wither sickness), tainted flowers, tainted berries (It has wither sickness so it would worsen/cause you to have sickness), and tainted shrubs. I also have another good idea, I think you should add tainted saplings too.

**Comment by myron-obsolete-account** [comment]
#839 duplicate, please close

**Comment by myron-obsolete-account** [comment]
Oh wait I missread it as "planks" sorry. I'm not sure if more plants will be added however I think it would be good enough if we get tainted logs and leaves as seperate blocks and use them as plants.

**Comment by NinjaSam5399** [comment]
Can you add this Cracker?

**Comment by nonamecrackers2** [comment]
This would be down to @Thefuzz1234555 as they're the one doing the new blocks

**Comment by watersofnazareth** [comment]
Not gonna be adding saplings, maybe shrubs/cacti, I may also make a tainted dirt/grass block, for now I'm pretty content on the current blocks
