### ISSUE TITLE
Option to make the Storm freeroam

### ISSUE THREAD

**Issue by Isoknight** [nonamecrackers2/crackers-wither-storm-mod#879]
It would be nice if there was a setting to make the Wither Storm move by itself instead of having to follow a player. I think it could result in an interesting playthrough, maybe making it a bit eerie finding the destruction caused by the Storm while it threatens the world.
This might not be that useful in survival playthroughs depending on what the player thinks would be better, but it could most likely be useful for people that want to watch it cause destruction without having to guide it all the time.

**Comment by myron-obsolete-account** [comment]
It does get distracted sometimes for a timespan of about 25 minutes (configurable) so you have long enough time to get away from it. Also I think I've read in some issue that there will be a feature implemented where it goes to places like villages (basically structures with people) but I'm not sure.

**Comment by Isoknight** [comment]
I mean like the Storm does it's own thing, instead of hunting the player down

**Comment by myron-obsolete-account** [comment]
It kind of does already?

**Comment by Isoknight** [comment]
Sort of, but what I mean is that it could roam by itself instead of following a player.

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release.
