### ISSUE TITLE
Wither storm aggressive

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#88]
When the wither storm is in his destroyer form he is slow and doesn't fire that much wither skulls at the player so what I'm suggesting is to make the wither storm fly faster who the player is far and he shots wither skulls aggressively

**Comment by nonamecrackers2** [comment]
The wither storm has a fairly thought out chasing sequence that will determine if the wither storm should chase the player or slowly follow it. When the wither storm evolves, or depending on how far away you are and how often you move will determine when the wither storm should chase you. As for the skulls, they are mostly replaced by the flaming wither skulls which I feel shoot at an appropriate rate.
