### ISSUE TITLE
Small idea for the bowels fight

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#880]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

Here's my idea: Y'know the mod statues in the bowels that are in the flesh? What if there were tainted stone statue versions of them? These statue versions would be things like skeletons, zombies, and maybe even symbionts. maybe on one of these stages, they could activate (being shown by their eyes suddenly glowing with a similar look to the symbiont), and they would step down from their podium, then come at you slowly with their weapon. If this makes it much harder, perhaps it could be a config option? I also have another idea in case this one gets rejected as well

**Comment by watersofnazareth** [comment]
Statues are going to be added but I don't know about making them activate, having them as decoration is their main purpose

**Comment by Globalfirestorm10** [comment]
![image](https://user-images.githubusercontent.com/102924027/214461310-90499e3e-24cf-4721-abfc-cf3017b5d490.png)
i'm referring to something like this, but with tainted stone or some other material to fit the bowels, and like I said, sickened mobs with weapons as well. It'd be cool tbh

**Comment by Globalfirestorm10** [comment]
Any updates on whether this suggestion is good or not?

**Comment by nonamecrackers2** [comment]
I feel these statues wouldn’t really fit in with the mod and would seem out of place for players, at least for me.

**Comment by Globalfirestorm10** [comment]
> I feel these statues wouldn’t really fit in with the mod and would seem out of place for players, at least for me.

Fair enough
