### ISSUE TITLE
 Add movement animations to players when they are being grabbed by tractor beams

### ISSUE THREAD

**Issue by pox1016** [nonamecrackers2/crackers-wither-storm-mod#884]
I think this would be super cool because if now the wither storm grabs you the current animation is like walking, it would add more emotion when the player changes the point of view when he is being grabbed by a tractor beam, I think it could even be done animations face down same as in the original game (this would involve adding a feature for the player's point of view to rotate as well).
![image](https://user-images.githubusercontent.com/109612890/214679653-886266fd-cc31-4f89-be60-3416ac21b97a.png)
![image](https://user-images.githubusercontent.com/109612890/214679835-d8c54cf1-640b-43f7-829f-3e2ce8dc6b4d.png)

**Comment by V0calgiant12** [comment]
If this does get added (which, personally, I have my doubts) I would recommend using the player animator mod because it allows for keyframe animations which, to my very small knowledge, might make it easier to implement. (Also keyframes looks smoother overall)

**Comment by GrandmaPork** [comment]
He’d have to limit it for players but I would love to see this done with mobs

**Comment by Globalfirestorm10** [comment]
if there was animations, they'd probably have to be simplistic, but even regular animations are very unlikely

**Comment by GrandmaPork** [comment]
For players, I think it should in positions like Petra and maybe Gabriel. It’d be cool if animals just spin around

**Comment by nonamecrackers2** [comment]
Modifying player animations is not in my interests for this mod.

**Comment by KrukAdrian** [comment]
> Modifying player animations is not in my interests for this mod.

welp thats sad
