### ISSUE TITLE
crash issue

### ISSUE THREAD

**Issue by AzaelKurosaki** [nonamecrackers2/crackers-wither-storm-mod#885]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.2

**Mod version**
witherstormmod-1.19.2-3.1.1.jar

**Describe the bug**
The mod crashes my minecraft.

**To Reproduce**
1. install dungeons/structure mods'
2. run minmecraft and create a world'
3. install Cracker's Wither Storm Mod'
4. create a new world
5. see crash

**Crash Reports / Logs**

[crash-2023-01-28_12.47.34-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10528029/crash-2023-01-28_12.47.34-client.txt)

**Is Flywheel's optimizations active?**

yes

**Screenshots**
![Captura de pantalla_20230128_123811](https://user-images.githubusercontent.com/115914240/215285074-ebf58fd9-be1a-4d74-bb8a-96be6243852f.png)
this is without the mod
![Captura de pantalla_20230128_123237](https://user-images.githubusercontent.com/115914240/215285077-abc30af4-27c9-45f3-a5d6-74b3ec0421d6.png)
this is with the mod

**Comment by Globalfirestorm10** [comment]
try giving yourself wither sickness on the server, then removing it

**Comment by AzaelKurosaki** [comment]
> try giving yourself wither sickness on the server, then removing it
the game crashes before the world even loads

**Comment by AzaelKurosaki** [comment]
here it is the modlist in question
[modlist.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10528326/modlist.txt)

**Comment by myron-obsolete-account** [comment]
this happens to occur when having forge ver. 43.2.4 installed since I am now experiencing the same issue after updating forge. it worked just fine with 43.2.2, and I'm not sure if it works with 43.2.3 too.

**Comment by myron-obsolete-account** [comment]
there may be a compatibility issue with CWSM 3.1.1 and forge 43.2.4, can't think of any other cause

**Comment by Globalfirestorm10** [comment]
I can't think of any mod incompatibilities other than oculus and rubidium, but those only have head rendering issues with the WS, not a fatal issue.

Try downgrading to forge version 43.2.0 for 1.19.2

**Comment by myron-obsolete-account** [comment]
43.2.2 should be enough downgrading actually

**Comment by nonamecrackers2** [comment]
Use the recommended 1.19 build, the latest includes a breaking change

**Comment by Globalfirestorm10** [comment]
> Use the recommended 1.19 build, the latest includes a breaking change

What about the most recent issue? Does the same factor for 1.19.2 apply to 1.18.2?

**Comment by nonamecrackers2** [comment]
Marking as 1.18.2 as this issue is present in that version as well

**Comment by nonamecrackers2** [comment]
Fixed in 2.2/3.2
