### ISSUE TITLE
Fabric for CWSM (read description)

### ISSUE THREAD

**Issue by Theoyeah** [nonamecrackers2/crackers-wither-storm-mod#887]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
BEFORE, I KNOW THAT THIS WAS NOT POSSIBLE BEFORE AS SOME STUFF IS MISSING IN FABRIC

I was scrolling trough Curseforge and i saw a new mod (Went public in Mid-december and as 7.1 millions downloads as i am wrinting this). It was a thing that added the entire API of Forge to Fabric, and is still updated. As i remember i saw you (crackers) saying that you can't add your mod because some stuff on the API was innexistent.
![image](https://user-images.githubusercontent.com/97792861/215317187-b0139992-e22c-4d28-ae33-ea67424a2081.png)

I would kind of like seing it being ported to fabric, at least for sometimes. Because i would like to use Replay Mod and Sodium to do cool stuff.

Tho i understand if it isn't possible or you don't want to.

Hope you understand (;.

**Comment by myron-obsolete-account** [comment]
why closed

**Comment by woodgoldtwo** [comment]
> _**Please read the guidelines before submitting:**_ #217
> 
> **Description of feature** BEFORE, I KNOW THAT THIS WAS NOT POSSIBLE BEFORE AS SOME STUFF IS MISSING IN FABRIC
> 
> I was scrolling trough Curseforge and i saw a new mod (Went public in Mid-december and as 7.1 millions downloads as i am wrinting this). It was a thing that added the entire API of Forge to Fabric, and is still updated. As i remember i saw you (crackers) saying that you can't add your mod because some stuff on the API was innexistent. ![image](https://user-images.githubusercontent.com/97792861/215317187-b0139992-e22c-4d28-ae33-ea67424a2081.png)
> 
> I would kind of like seing it being ported to fabric, at least for sometimes. Because i would like to use Replay Mod and Sodium to do cool stuff.
> 
> Tho i understand if it isn't possible or you don't want to.
> 
> Hope you understand (;.

That mod is a port of the Forge **CONFIG** API, not the entire Forge API

**Comment by Felix14-v2** [comment]
> That mod is a port of the Forge **CONFIG** API, not the entire Forge API

What about [Fabricated Forge API](https://github.com/FeltMC/Fabricated-Forge-API) ? @nonamecrackers2
