### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#89]
Question: are you working on the wither storm texture like some glowing purple areas and stuff like That?

**Comment by nonamecrackers2** [comment]
Due to how rendering works, adding glowing areas to the Wither Storm would cause more fps lag.

**Comment by Abasthepro** [comment]
> Due to how rendering works, adding glowing areas to the Wither Storm would cause more fps lag.

OK them just make them purple they don't need to be glowing or anything
