### ISSUE TITLE
Player doesn't teleport into bowels when in elytra animation

### ISSUE THREAD

**Issue by MEMEBOyt** [nonamecrackers2/crackers-wither-storm-mod#892]
When I use fireworks to launch myself into the bowels with my elytra, I don't teleport inside but if i'm not in the elytra animation, I teleport just fine. I'm using 1.18.2. I'm sorry I explained this kinda bad.

**Comment by watersofnazareth** [comment]
This may be intentional to stop the player from dying when entering the bowels

**Comment by nonamecrackers2** [comment]
It should work, I’ll have to investigate
