### ISSUE TITLE
Suggestion to Enhance the "Camping" Experience against the Wither Storm

### ISSUE THREAD

**Issue by TheSrBig** [nonamecrackers2/crackers-wither-storm-mod#893]
Dear Developers,

I would like to propose an additional feature for the "Cracker's Wither Storm" mod in Minecraft. When a player "camps" in a mine, the Wither Storm should remove blocks in an area around the player, creating an additional challenge for its capture. Additionally, each time the blocks are removed, the Wither Storm should gradually descend, increasing the tension and excitement during the hunt.

I believe this feature would add an extra element of strategy and challenge for players who are looking to "camp" against the Wither Storm, making the experience even more thrilling and satisfying.

Thank you in advance for your consideration, and I hope to see this feature in a future update of the mod.

**Comment by Globalfirestorm10** [comment]
> Dear Developers,
> 
> 
> 
> I would like to propose an additional feature for the "Cracker's Wither Storm" mod in Minecraft. When a player "camps" in a mine, the Wither Storm should remove blocks in an area around the player, creating an additional challenge for its capture. Additionally, each time the blocks are removed, the Wither Storm should gradually descend, increasing the tension and excitement during the hunt.
> 
> 
> 
> I believe this feature would add an extra element of strategy and challenge for players who are looking to "camp" against the Wither Storm, making the experience even more thrilling and satisfying.
> 
> 
> 
> Thank you in advance for your consideration, and I hope to see this feature in a future update of the mod.

Nice idea, I like it

**Comment by Aimyx** [comment]
It would make players not just wait around for the ws to be distracted, its always a looming threat.

**Comment by TheSrBig** [comment]
> It would make players not just wait around for the ws to be distracted, its always a looming threat.

I did not understand your question
