### ISSUE TITLE
Real time simulated blockS

### ISSUE THREAD

**Issue by SplendidSuperGithub** [nonamecrackers2/crackers-wither-storm-mod#895]
The wither storm is not maked by block is, a entity, the block can be broken and touched and he it can’t be touched or broken, like entities, without physics, so my idea is change this, have real time simulated blocks, a wither storm maked by blocks, with physics, blocks that can be broken by player, touched, broken by creeper or endermans, all the things a block have. Probably you will say but is too complicated code block who can move in real time, but being block, so https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies, I thinks mod core will help

**Comment by nonamecrackers2** [comment]
This is extremely difficult to implement and will require severe rewrites with almost no gameplay benefits, sorry.

**Comment by SplendidSuperGithub** [comment]
> This is extremely difficult to implement and will require severe rewrites with almost no gameplay benefits, sorry.

Well about probably will help to don’t have a new dimension what is inside wither storm, have blocks what is the wither storm, Can mine the wither storm and have tentacles who can broke blocks and take you, probably all of this things can help the mod, about fps there a mods to boost fps. I think will be better add not too complicated using Valkyrien skies
