### ISSUE TITLE
Crashing apon world creation

### ISSUE THREAD

**Issue by Nuclear4Hurricane** [nonamecrackers2/crackers-wither-storm-mod#896]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is Flywheel's optimizations active?**
Specify if Flywheel is installed and it's compat optimizations are enabled

**Screenshots**

**Comment by Nuclear4Hurricane** [comment]
[crash-2023-02-03_12.10.12-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10581099/crash-2023-02-03_12.10.12-client.txt)

**Comment by Nuclear4Hurricane** [comment]
1.19.2

**Comment by V0calgiant12** [comment]
Forge incompatibility with the mod, known issue (#885 ), use Forge 43.2.3 or lower until the next update for the mod

**Comment by myron-obsolete-account** [comment]
um if this is a duplicate why is this not closed

**Comment by nonamecrackers2** [comment]
#885 Also please fill out the report next time
