### ISSUE TITLE
Bowels change when near a biome/structure

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#899]
I think it would be cool and more *realistic* when the ws was near a village and the bowels will generate to village bowels *if possible make an option to disable this feature in game* i know it may take hard/long coding but it will be very cool lookin at the end 

*:jess:*

**Comment by Globalfirestorm10** [comment]
iirc, crackers said he wouldn't do this, as there's no way to make that change if it has consumed (or been near) a structure such as a village

**Comment by Pandaboi25x** [comment]
> iirc, crackers said he wouldn't do this, as there's no way to make that change if it has consumed (or been near) a structure such as a village

Oh damn thats kinda sad

**Comment by Pandaboi25x** [comment]
Gonna close this now since i now know crackers wont be doing this

**Comment by nonamecrackers2** [comment]
This wouldn’t be possible regardless, since bowels structures are pre generated when the wither storm summons and there isn’t a way to dynamically change structures after they’ve been generated
