### ISSUE TITLE
Transforming animation between phase 3 and 4

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#90]
Future idea:When the wither storm Is in his 3rd phase when he get to  the 4th phase it immediately go giant if you can add an animation or a phase between 3 and 4

**Comment by Asteroid4** [comment]
It always felt sudden when it transformed, maybe at a certain consumedEntites amount, it gets bigger, then again and again until it reaches stage 4

**Comment by BluePineappleGuy** [comment]
maybe the debris can cover swirl around more packed in the shape of stage 4, then it transforms and the debris spaces out again as 3 heads grow from the storm, and tentacles pop out.
