### ISSUE TITLE
Command Block Upside Down

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#903]
Please Make The Final Battle With The Command Block (The Last Hit) Upside Down

**Comment by nonamecrackers2** [comment]
#105

Please stop opening duplicates. Also, please read the guidelines #217

**Comment by myron-obsolete-account** [comment]
It starts to get annoying imo. Also why can't people search for terms like "upside down" in the search bar and find issues with the same topic before just smacking in a new suggestion? Lazy or what?
