### ISSUE TITLE
After Formidi Bomb

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#905]
When You Blow Up The Wither Storm It Can Release Some Of The Mobs It Killed

**Comment by myron-obsolete-account** [comment]
I don't think this is neccessary + I think this is already a feature.

**Comment by nonamecrackers2** [comment]
#123

**Comment by LucasDotje** [comment]
How Is It Possible That Someone Asked That Already?

**Comment by myron-obsolete-account** [comment]
> How Is It Possible That Someone Asked That Already?

Maybe because other people wanted the same feature?
