### ISSUE TITLE
Please Make This Option

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#906]
Please Make It A Option That The Wither Storm Can Only Suck Up Things In The Tractor Beam

**Comment by myron-obsolete-account** [comment]
what?

**Comment by nonamecrackers2** [comment]
Disable mobGriefing then? That should work for what you want.

**Comment by LucasDotje** [comment]
I Meant The Block Clusters

**Comment by myron-obsolete-account** [comment]
> I Meant The Block Clusters

You can disable block cluster pickup by setting the gamerule mobGriefing to false as nonamecrackers2 already said

**Comment by LucasDotje** [comment]
I Mean That The Block Clusters Only Can Be Picked Up In The Tractor Beam

**Comment by myron-obsolete-account** [comment]
> I Mean That The Block Clusters Only Can Be Picked Up In The Tractor Beam

I don't think that's neccessary enough to be a feature

**Comment by nonamecrackers2** [comment]
I don't seem much of a point personally for this.
