### ISSUE TITLE
Wither Storm Skull Config 

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#908]
A Wither Storm Skull Config To Make The Explosions Bigger

**Comment by myron-obsolete-account** [comment]
aren't the explosions already big enough

**Comment by BluePineappleGuy** [comment]
> aren't the explosions already big enough

you can never have too much explosions :)

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
