### ISSUE TITLE
New armor for the player

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#91]
Future idea: the players need some new armor because the wither storm is so strong

**Comment by nonamecrackers2** [comment]
I think the Wither Storm is perfectly beatable with normal armor and enough preparation. There is also not much room to fit in the armor into the progression as well. If you'd like armor, there's a mod called Minecraft: Story Mode Armors which add the armors from MCSM.

**Comment by Steve982950** [comment]
1: there are mods for this
2: NOT SUPPOSED TOO BE 1:1 ACCURATE
