### ISSUE TITLE
Creepers doing self-defense when being tractorbeamed

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#910]
**Description of feature**
Creepers could explode infront of a head's eye to damage it when being tractorbeamed, as "self defense" or something (duh creepers still die when they blow up but then they atleast do like uhh idk try to scare the wither storm?)

You could also add that the WS avoids creepers for like 10 minutes after the incident happened since uhh yeah idk.

**Comment by NinjaSam5399** [comment]
bruh

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
