### ISSUE TITLE
Cheesing the symbiont with a creeper

### ISSUE THREAD

**Issue by Bloxxify1520** [nonamecrackers2/crackers-wither-storm-mod#911]
**Minecraft version**
1.19.2

**Mod version**
1.19

**Describe the bug**
The symbiont it supposed to be a hard boss, but there is a pretty easy way to get him to 1-2 hits instantly with one thing. Whenever you hit him first or twice be usually summons a wave of mobs, one of them is the sickened creeper. If you get him close enough to the symbionts weak point, it will deal BIG amounts of damage to him.

**To Reproduce**
1. Go to a world
2. Get symbiont spawn egg
3. Wait for him to summon mob wave
4. Get sickened creeper close to him and make him explode
5. See error

**Crash Reports / Logs**
no crashes

**Is Flywheel's optimizations active?**
No

**Screenshots**
none currently available

**Comment by Bloxxify1520** [comment]
Basically, in one of my servers the people knew this trick and kind of farmed books.

**Comment by nonamecrackers2** [comment]
This isn't necessarily a bug however I'll mark it as a suggestion

**Comment by nonamecrackers2** [comment]
Added blast resistance to the Symbiont in 2.2/3.2
