### ISSUE TITLE
Summoning totem not working in 1.16.5

### ISSUE THREAD

**Issue by Zer0reZ83** [nonamecrackers2/crackers-wither-storm-mod#912]
The summoning totem is not working in 1.16.5 for me with these mods : 

- bygonenether
- catalogue
- configured
- curios forge
- dynamic surroundings
- enhanced celestials
- faithfull backrooms
- faithfull backroom addon
- geckolib forge
- InsaneLib
- lycanitesmobs
- optifine
- Progressive Bosses
- Spartan weaponry
- The graveyard
- The legend of Herobrine
- total darkness
- voidtotem

All of these mods are in their most recent version for 1.16.5

Any ideas how to fix it ?

**Comment by V0calgiant12** [comment]
Are you using the one at the ruined house? Or are you using one you made on the ground?

**Comment by myron-obsolete-account** [comment]
You are probably one of those people who forgot to remove grass or snow from the sides of the structure because with these little blocks being there it wont spawn the WS successfully.

**Comment by nonamecrackers2** [comment]
> You are probably one of those people who forgot to remove grass or snow from the sides of the structure because with these little blocks being there it wont spawn the WS successfully.

Try this and see, if not it's most likely bygone nether as I believe they replace the soul sand blocks with their own variation.

**Comment by Isoknight** [comment]
If I remember correctly, Bygone Nether makes the Wither a crafting table recipe instead of a physical build, which would break the Wither Storm's totem.
