### ISSUE TITLE
Mod doenst work with Danny Expansion 

### ISSUE THREAD

**Issue by TenerPVPs** [nonamecrackers2/crackers-wither-storm-mod#913]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.16.5

**Mod version**
1.16.5-1.0.2.4

**Describe the bug**
Bassicaly it crashed when i try create the world

**To Reproduce**
Just use with Danny Expansion mod https://www.curseforge.com/minecraft/mc-mods/dannys-expansion and try create a map

**Crash Reports / Logs**
[message (1).txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10726290/message.1.txt)

**Is Flywheel's optimizations active?**
Iam not using flywheels

**Screenshots**
Doenst have just crashes

**Comment by nonamecrackers2** [comment]
#6

**Comment by nonamecrackers2** [comment]
This has apparently been an issue for ages 💀
