### ISSUE TITLE
Config option to disallow spawning the storm until the ended dragon has been defeated.

### ISSUE THREAD

**Issue by AmberMaid** [nonamecrackers2/crackers-wither-storm-mod#914]
A config to prevent players from spawning the wither storm until either the ended dragon or wither has been defeated.

**Comment by GrandmaPork** [comment]
What for? The main fun of this is starting a world of fresh and surviving that

**Comment by Globalfirestorm10** [comment]
This was already suggested, please close this

**Comment by MoRoN222** [comment]
Who would want that honestly

**Comment by MoRoN222** [comment]
and even if you don't want to play in survival, would still be pretty evil if you want to stress test your PC or test features etc.
game: "BEAT THE DRAGON FIRST"

**Comment by GrandmaPork** [comment]
Remember guys, kids leave suggestions here too

**Comment by nonamecrackers2** [comment]
Guys, please stop berating people.

**Comment by Globalfirestorm10** [comment]
I wasn't? I was giving my general opinion on the idea, and my justification for it, you can do whatever you want ig 🤷‍♂️

**Comment by myron-obsolete-account** [comment]
-_-

**Comment by myron-obsolete-account** [comment]
This has the same energy as "having opinions is forbidden"

**Comment by GrandmaPork** [comment]
You guys were being too much. Remember that kids make suggestions here too so even if you don’t understand why a suggestion is made, you don’t need to call it outright stupid

**Comment by nonamecrackers2** [comment]
You can have your opinions, just be respectful about it

**Comment by myron-obsolete-account** [comment]
Oh my god I am so terribly sorry mister cracker the second without a name !!!

**Comment by Globalfirestorm10** [comment]
> You can have your opinions, just be respectful about it

fair enough, my apologies

**Comment by Globalfirestorm10** [comment]
> Oh my god I am so terribly sorry mister cracker the second without a name !!!

Just move on, no need to start a fight over a suggestion.

**Comment by nonamecrackers2** [comment]
After some more consideration decided that this could be something done with a custom modpack/datapack
