### ISSUE TITLE
Wither Vaccine (better version of the golden apple stew)

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#917]
A wither vaccine that makes you immune to wither sickness for an hour, less or even longer (time for the immune can be changed in the settings) could prove useful if a player is in a cave  :) 

the crafting recipe would look like this: Empty Vaccine
![the](https://user-images.githubusercontent.com/121638798/219416968-a746ea24-b179-4780-b486-a4ddfd088e3a.png)
1st version of the wither vaccine:
![h](https://user-images.githubusercontent.com/121638798/219417103-fdff27e9-7f1a-4f3b-97b0-aee7d01c23cb.png)
2nd version of the wither vaccine (1st version is better ngl)
![no way](https://user-images.githubusercontent.com/121638798/219417202-51797882-dedc-46c2-ace0-847bf6043cb6.png)
i didnt try making the vaccine okay?

*i will not respond to any comments only to a admin/owner comment!!1!!!1*

yes i did it in mcreator :jess:

**Comment by nonamecrackers2** [comment]
I don’t really feel this fits in with the mod, especially considering with peoples stances on vaccines on a whole and would prefer to leave it out. I’m also curious to why you’d use the cure item that completely removes the sickness in the vaccine that only removes it for an hour.

**Comment by myron-obsolete-account** [comment]
Hi crackers!

**Comment by myron-obsolete-account** [comment]
Sorry if you are being annoyed by this but when do you think will the update be out. Next few weeks? 1 or 2 months? maybe in a billion years?

**Comment by myron-obsolete-account** [comment]
...I regret asking, this feels cringe, I want die.

**Comment by Pandaboi25x** [comment]
> I don’t really feel this fits in with the mod, especially considering with peoples stances on vaccines on a whole and would prefer to leave it out. I’m also curious to why you’d use the cure item that completely removes the sickness in the vaccine that only removes it for an hour.

i do not even know lol i just thought a vaccine would be cool but i just got so many ideas with that i didnt think twice

**Comment by V0calgiant12** [comment]
> ...I regret asking, this feels cringe, I want die.

Me whenever I ask anyone anything:

**Comment by TheEyeOfGaming** [comment]
we could name it an Elixir instead, then we finally have a reason for it to be in the game, as a way to atleast be able to be resistant to the wither sickness and not have the trouble to make more golden apple stews.

**Comment by myron-obsolete-account** [comment]
> > ...I regret asking, this feels cringe, I want die.
> 
> Me whenever I ask anyone anything:

I feel this

**Comment by myron-obsolete-account** [comment]
> we could name it an Elixir instead, then we finally have a reason for it to be in the game, as a way to atleast be able to be resistant to the wither sickness and not have the trouble to make more golden apple stews.

Well... he technically said no to an exilir that stops the WS in early phases which isn't supposed to happen, but... an exilir that heals you? Well idk

**Comment by nonamecrackers2** [comment]
> Sorry if you are being annoyed by this but when do you think will the update be out. Next few weeks? 1 or 2 months? maybe in a billion years?

This isn't really an appropriate place to ask this, but you'll have to wait and see for when it comes out.
