### ISSUE TITLE
When the formidi bomb is crafted it takes the crafting table with it and explode in seconds

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#92]
Is mcsm when jesse crafted the f bomb the crafting table turned into the f bomb and exploded in a seconds so I'm saying make the f bomb when crafted it takes the crafting table and explode is seconds after it was crafted (if it was from the creative menu it goes to the inventory and doesn't explode until the player placed it.

**Comment by nonamecrackers2** [comment]
This wouldn't give players much time to escape otherwise from the massive explosion, and for the Wither Storm to pick it up.
