### ISSUE TITLE
Remove 2 Big tentacles at Phase 6 and Regrow them back when they got 9 heads

### ISSUE THREAD

**Issue by TheEyeOfGaming** [nonamecrackers2/crackers-wither-storm-mod#923]
**Description of feature**
You should remove the 2 Big Tentacles after the witherstorm gets formidibombed so that it looks similar to the Witherstorm in MCSM while retaining Crackers Witherstorm Look, and make it when it gets 9 heads that the 2 Big Tentacles regrow back.
You could also make it a Config Option to make the tentacles disappear when formidibombed and regrow when it gets 9 heads.
Phase 6 after formidibomb:
![image](https://user-images.githubusercontent.com/114343289/219653691-9a832124-bf76-4c03-9735-549977826518.png)
Phase 6 After it gets 9 heads and the 2 main tentacles Grow back:
![image](https://user-images.githubusercontent.com/114343289/219654054-d45704d7-2eea-4bb8-b527-c057fb1ca0fe.png)
These images i found on the internet cuz i dont know how to put screenshots on github but you get my point.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by myron-obsolete-account** [comment]
I like this idea, would kind of look weird without them but would kinda make sense too, after such a big strong blast of an F-Bomb. May I add that it would be cool too that the tentacles convert into tainted flesh blocks and stay on the ground, as if they have been cut off? Just a side idea.

**Comment by Globalfirestorm10** [comment]
IIRC, crackers said he wouldn't make any changes to the body and tentacle models for now, but id recommend you just wait and see for what he has to say

**Comment by nonamecrackers2** [comment]
Gonna keep the tentacles attached. Don't really feel like messing with the look of the existing phases too much.
