### ISSUE TITLE
Symbiont sometimes WONT spawn in latest version 1.19.2

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#926]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on

**Mod version**
The version of the mod you are using

**Describe the bug**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is Flywheel's optimizations active?**
Specify if Flywheel is installed and it's compat optimizations are enabled

**Screenshots**

**Comment by myron-obsolete-account** [comment]
did you just not fill out the bug report forum

**Comment by myron-obsolete-account** [comment]
without any information nobody will be able to help you

**Comment by myron-obsolete-account** [comment]
@humzahre ***clears throat***

I'm gonna try to help you despite you given no information about the issue. The symbiont may take very long, up to half an hour I think, to spawn, so you need patience. If that's not the case you may have conflicting mods.

**Comment by Globalfirestorm10** [comment]
> _**Please check the guidelines before submitting:**_ #217
> 
> **Minecraft version** The version of Minecraft the mod is running on
> 
> **Mod version** The version of the mod you are using
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Crash Reports / Logs** Crash reports / logs hosted on pastebin, gist, etc.
> 
> **Is Flywheel's optimizations active?** Specify if Flywheel is installed and it's compat optimizations are enabled
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.

Sir, please fill out the template we gave you, we cannot help you without a mod list, descriptions, etc

**Comment by myron-obsolete-account** [comment]
what did I just say lmao

**Comment by humzahre** [comment]
IT NEVER SPAWNED I HAVE WAITED FOR AN HOUR

**Comment by myron-obsolete-account** [comment]
jeez calm down

**Comment by myron-obsolete-account** [comment]
you still didn't fill out the template tho

**Comment by myron-obsolete-account** [comment]
wait @humzahre did you perhaps disable the gamerule mobGriefing

**Comment by myron-obsolete-account** [comment]
@humzahre cmon atleast tell us which minecraft version and which mod version you use

**Comment by myron-obsolete-account** [comment]
yeah I think they disabled mobGriefing. I tested something similar about the Symbiont dropping (spawning) a Command Block Book item on death but it didn't do it when the gamerule mobGriefing was turned off. Might be because the Symbiont itself "spawns" the item, and that counts as mobGriefing. Same with the Wither Storm trying to spawn the Symbiont.

**Comment by nonamecrackers2** [comment]
Please fill out the bug report

**Comment by myron-obsolete-account** [comment]
it's too late now

**Comment by Globalfirestorm10** [comment]
> IT NEVER SPAWNED I HAVE WAITED FOR AN HOUR

Kid, calm down. We've told you several times to fill out the bug report, please do so, or your issue will remain unsolved.It's not that hard, just reproduce the issue (if you don't have it already), and make sure you don't have mobgriefing disabled

**Comment by humzahre** [comment]
i DONT KNOW How to fill out the bug report. i am new

**Comment by Globalfirestorm10** [comment]
when you create an issue, you can edit the bug report. It's that simple, I fail to understand how you don't know this
