### ISSUE TITLE
Bedrock Edition?

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#927]
**Description of feature**
There are people in the comments of your videos asking for/about bedrock edition ports and I want to make sure if it will or won't happen.

**Comment by NinjaSam5399** [comment]
There are already a Bedrock Version.

**Comment by myron-obsolete-account** [comment]
I mean like an official port by nonamecrackers2 himself

Also for clarification (before i accidentally start a war here) i dont want a bedrock port because i dont even play bedrock duh

**Comment by Globalfirestorm10** [comment]
IIRC, crackers said he wouldn't be doing that

**Comment by myron-obsolete-account** [comment]
thats what I thought he said somewhere too but I want a confirmation so I can go back to the comment sections and tell 'em it won't happen

**Comment by nonamecrackers2** [comment]
Yeah I won't be making a bedrock version, there isn't a proper modding API in bedrock to begin with.

**Comment by myron-obsolete-account** [comment]
Splendid.
