### ISSUE TITLE
Requesting Deeper Bowels Pit Due To Visible Floor

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#929]
**Description of feature**
If you really pay attention and look down while falling, you can see the bedrock for a little bit before you get teleported back outside. And I don't think something like indestructible tainted flesh blocks (#667 - confirmed) will make it look better. I might be late, as the depth may have already been increased, since the bowels have already got their upgrade, but if not, please do it.
![image](https://user-images.githubusercontent.com/53058491/219899390-182e75e6-e382-4571-8cb8-f8256bbc803d.png)

**Comment by GrandmaPork** [comment]
That or fill the bottom with black concrete or something so we can’t see the bedrock

**Comment by myron-obsolete-account** [comment]
Well, it would be quite better if it would go deeper, because if it was something very dark e.g. you said black concrete, you would still see something different when the thick fog goes away, so a deeper hole would keep the fog visible, since it basically moves with the player. Making the fog even thicker would slowly start to look ugly so a deeper pit would be better instead.

**Comment by GrandmaPork** [comment]
I mean yeah but it would probably be better for performance to not raise the height limit

**Comment by nonamecrackers2** [comment]
Should be a lot better in 2.2/3.2 thanks to hardened flesh. Extending the bowels isn't overly necessary since the fog from the top covers the bottom anyway.
