### ISSUE TITLE
When getting picked up by the tracktor beam you can break the eye do the tracktor beam turns off

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#93]
Future idea:when the wither storm is in his 4 phase and above when getting picked up by the wither storm you can hit the eye to break it so the tracktor beam turns off but it's hard because you have to be close to the head and the texture of the eye goes like the mcsm wither storm eye when jesse hits it with the sword

**Comment by Loverxzc** [comment]
Already in the mod

**Comment by Abasthepro** [comment]
> 

Bruh fr? Haven't you played the mod or what or you mean there is a suggestion it's not in the mod

**Comment by Abasthepro** [comment]
> Already in the mod

Only If you mean in the final boss arean when the wither storm tracktor beam picks you up and you start hitting the wither storm but no I'm talking about both and a texture by both I mean the wither storm in his phase 4 and above and the eye texture changes to broke

**Comment by dgc0312** [comment]
I think that would not be possible since the final boss the heads are an entity and the wither storm are 1 entity only (the heads are attached to the entity) not like in engenders mod where the wither storm head was an entity and the body another and the tentacle another one etc

**Comment by Abasthepro** [comment]
> I think that would not be possible since the final boss the heads are an entity and the wither storm are 1 entity only (the heads are attached to the entity) not like in engenders mod where the wither storm head was an entity and the body another and the tentacle another one etc

Why is everyone this dumb BRUH when the wither storm is in his 4 phase and above he gets a complete different body and heads when I was playing the mod the wither storm was in phase 4 or 5 idk one of the heads turned a 180 i was like bruh and if the wither storm is one entity hoe can all 3 heads move different directions and they have their own hit box and you literally hit them BRUH

**Comment by nonamecrackers2** [comment]
The Wither Storm is one separate entity, everything is combined and not separated into different parts. Each head has their own AI, and this idea could be possible. No need to be rude @Abasthepro

**Comment by Abasthepro** [comment]
> The Wither Storm is one separate entity, everything is combined and not separated into different parts. Each head has their own AI, and this idea could be possible. No need to be rude @Abasthepro

Ok I'm sorry to you and everyone I just want everyone to get the idea

**Comment by nonamecrackers2** [comment]
This will be implemented in the next 1.18.2 update

**Comment by Abasthepro** [comment]
> This will be implemented in the next 1.18.2 update

YES!!! THANKS 👍👍👍👍
