### ISSUE TITLE
The music doesn't play when I summon the wither storm

### ISSUE THREAD

**Issue by Mochitoq** [nonamecrackers2/crackers-wither-storm-mod#930]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
When I place the wither skeleton skull and the wither storm is summoned, the music is not heard, I already tried refreshing the sounds but it doesn't work

**Comment by myron-obsolete-account** [comment]
Did you, first of all, enable the music?

**Comment by Mochitoq** [comment]
> Did you, first of all, enable the music?

If you mean turn up the volume of the music, yes I did

**Comment by myron-obsolete-account** [comment]
No I mean enable the music.

**Comment by Mochitoq** [comment]
> No I mean enable the music.

but how do i activate it?

**Comment by myron-obsolete-account** [comment]
config

**Comment by myron-obsolete-account** [comment]
<kbd>Esc</kbd> > Options... > W > Client Options > Play Boss Themes

toggle that.
and don't forget to save.

**Comment by myron-obsolete-account** [comment]
`h   a   v   e          f   u   n          p   l   a   y   i   n   g   .`

**Comment by Globalfirestorm10** [comment]
assuming this worked for you, you might wanna close the issue

**Comment by Mochitoq** [comment]
> `h a v e f u n p l a y i n g .`

Thank you :D

**Comment by Nukegd** [comment]
> Esc > Options... > W > Client Options > Play Boss Themes
> 
> toggle that. and don't forget to save.

I also did it, but I still don't have music playing, and I even reloaded the sounds.
