### ISSUE TITLE
[Suggestion] Config for not-glowing teeth

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#931]
**Suggestion**
Can you add a config option to disable teeth glow? Would be cool.

---

~~**Minecraft version**~~
~~1.19.2~~

~~**Mod version**~~
~~3.1.1~~

~~**Describe the bug**~~
~~When I hit the Command Block inside of the Wither Storm and then go outside, I noticed that the teeth and eyes of the WS start to blink.~~

~~**To Reproduce**~~
~~Steps to reproduce the behavior:~~
~~1. Enter Bowels~~
~~2. Damage Command Block~~
~~3. Get out of Bowels~~
~~4. See error~~
~~Note: If blinking does not occur after first time damaging the Command Block, you may have to hit it a second time. I felt like it was that way when I played but maybe I just didn't pay attention.~~

~~**Crash Reports / Logs**~~
~~N/A~~

~~**Is Flywheel's optimizations active?**~~
~~No.~~

~~**Screenshots**~~
~~N/A - Video~~

~~https://user-images.githubusercontent.com/53058491/219956703-e2d26fe9-eddf-4666-b35f-f2d1f4f7f22d.mp4~~

**Comment by Bloxxify1520** [comment]
Its an intended effect to make it look like the sto has been weakened.

**Comment by myron-obsolete-account** [comment]
Ok but I have a different question.

Why do the teeth glow in the first place? Can teeth even glow? Isn't there a different way to visualize them? whatttt??

**Comment by nonamecrackers2** [comment]
They glow for parity reasons with MC:SM. I don't feel a config option for this is very necessary.

**Comment by MoRoN222** [comment]
That one fancy girl in school be like "omg I want glowing teeth they would look so cool" like ew what
