### ISSUE TITLE
Wither Storm not evolving

### ISSUE THREAD

**Issue by Resuster** [nonamecrackers2/crackers-wither-storm-mod#934]
*
So, i was playing some wither storm survival for 40-50 minutes i think and i thought the wither storm would reach phase 4 by now but it didnt. so i turned on cheats and went to look at it and it was still at phase 0 for some reason. literally i was playing for 50 minutes and the wither storm hasnt evolved at all. i even searched the config to see if anything was wrong but it was normal. hopefully u can fix this in the next update

**Comment by Resuster** [comment]
ok so as i was keep looking at it, it evolved to phase 1. not sure if this was a bug or lag.

**Comment by myron-obsolete-account** [comment]
I would keep this open as it seems strange that it didn't evolve after almost an hour. What version were you playing on if I may ask?

**Comment by Resuster** [comment]
> I would keep this open as it seems strange that it didn't evolve after almost an hour. What version were you playing on if I may ask?

1.18.2

**Comment by Resuster** [comment]
i was at 1K blocks and when i went to check on it it didnt evolve but when i stayed for time it evolved to phase 1
i think cuz of the lag thats why i closed it

**Comment by V0calgiant12** [comment]
Did you have any other mods installed?

**Comment by nonamecrackers2** [comment]
Reminder if you have optifine to disable "smooth world", as this could possibly be the culprit

**Comment by Resuster** [comment]
okay
