### ISSUE TITLE
3.2 Update file missing language provider javafml:44, found 43

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#935]
**Minecraft version**
1.19.2

**Mod version**
3.2

**Describe the bug**
When I try to load Minecraft it ends up with a screen which looks like the screenshot below.

**To Reproduce**
1. Load witherstormmod 3.2 on Forge 1.19.2 43.2.4
2. See error

**Crash Reports / Logs**
[crash-2023-02-22_17.43.47-fml.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10806323/crash-2023-02-22_17.43.47-fml.txt)

**Is Flywheel's optimizations active?**
No.

**Screenshots**
![2023-02-22_17 44 05](https://user-images.githubusercontent.com/53058491/220697796-1262983d-9679-4225-a888-d93439abffb7.png)

**Comment by nonamecrackers2** [comment]
3.2 requires 1.19.3, and doesn't support 1.19.2, sorry.

**Comment by myron-obsolete-account** [comment]
![image](https://user-images.githubusercontent.com/53058491/220701380-572271f1-ee98-4d18-aaf0-7d8377e0039e.png)
urgh now I gotta find all of my current mods in 1.19.3, and most of them are probably not updated yet

**Comment by MoRoN222** [comment]
gah my internet connection delayed everything why

**Comment by myron-obsolete-account** [comment]
> 3.2 requires 1.19.3, and doesn't support 1.19.2, sorry.

well thats sad
