### ISSUE TITLE
Green clusters...?

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#937]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3

**Mod version**
1.19.3

**To Reproduce**
1. Go to 'cwsm 1.19.3'
2.'place the beacons'
3.'let the resummon begin'
4. destroy the withered beacon so that it stops the resummon 
5. and yea you now have floating green clusters

**Is Flywheel's optimizations active?**
no

**Screenshots**
![image](https://user-images.githubusercontent.com/121638798/220727328-6b2943bc-044b-4ef5-8d9e-7abca066db99.png)

**Comment by Asteroid4** [comment]
I encountered this while summoning multiple wither storms, i think it has something to do with the purple in the clusters inverting.

**Comment by NinjaSam5399** [comment]
me too

**Comment by nonamecrackers2** [comment]
Will be fixed in 2.2.1/3.2.1

**Comment by Pandaboi25x** [comment]
funni green clusters gone
