### ISSUE TITLE
another beacon bug (please dont fix this today take a break)

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#938]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3

**Mod version**
1.19.3

**Describe the bug**
another beacon bug 

**To Reproduce**
1. Go to 'cwsm 1.19.3'
2. place 2 lapis beacons and place a withered beacon
3. 'place a random beacon (could be diamond or emerald)'
4. See that the diamond beacon is confused

**Is Flywheel's optimizations active?**
no

**Screenshots**
![image](https://user-images.githubusercontent.com/121638798/220736002-2a74ece2-5d38-466d-9828-5bd46bd7a67b.png)

**Comment by nonamecrackers2** [comment]
Will be fixed in 2.2.1/3.2.1
