### ISSUE TITLE
When the wither storm picks players up the cant escape only ef they had ender pearl or elytra and fire works so i suggest spamming jump to escape 

### ISSUE THREAD

**Issue by Abasthepro** [nonamecrackers2/crackers-wither-storm-mod#94]
Future idea:When the wither storm picks players up the cant escape only ef they had ender pearl or elytra and fire works so i suggest spamming jump to escape

**Comment by nonamecrackers2** [comment]
Just normal fireworks work, no need for an elytra. You can also hit the heads with melee attacks as well. Ultimately, you're supposed to try to avoid the Wither Storm picking you up instead of getting picked up. Good preparation could save you most of the time.
