### ISSUE TITLE
[Crash] Sickened Creeper doesn't extend vannilla class, and crashes with Epic Fight patcher

### ISSUE THREAD

**Issue by guivnf** [nonamecrackers2/crackers-wither-storm-mod#940]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2

**Mod version**
any

**Describe the bug**
Creepers don't extend the vanilla creeper class

**To Reproduce**
So epic fight heavily rely on mods extending vanilla classes of each entity to apply presets. Wither Storm mod doesn't seem to extend the vanilla class of the creeper entity, and thus epic fight inst' able to properly define what the sickened creeper entity is and thus has issues with it and can cause a crash. This should be a simple fix as it would only require you to do a simple change on the sickened creeper class.

**Crash Reports / Logs**
https://mclo.gs/1LqkrLV

**Screenshots**
No screenshots can be provided as this error hapens when a datapack patcher from efm is applied on a world with a creeper entity that is loaded. You can try using this datapack on a world with an already existing sickened creeper entity that is loaded and you'll see the crash.
[witherstorm_patch.zip](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10807778/witherstorm_patch.zip)

**Comment by nonamecrackers2** [comment]
All the sickened mobs are actually extensions of a base ``AbstractSickenedEntity`` class that contains base logic shared across all the sickened mobs, for converting to and from sickened/non-sickened versions. Right now moving this class to an interface would take a lot of rewriting (which would allow me to extend the Creeper class) so I'll have to look into further sometime in the near future. Thanks for reaching out though.

**Comment by nonamecrackers2** [comment]
Sickened mobs have been rewritten in 2.2.1/3.2.1 to be interfaced based, and each mob now extends their respective mob class (e.x. SickenedCreeper now extends Creeper). Hopefully this will allow compat with Epic Fight.
