### ISSUE TITLE
Worlds crashing when mod loads

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#941]
Mods: only cws

Mod version: any 1.18.2 future or later versions not yet tested

Problem: when I launch minecraft and attempt to join a world with the mod it immediately crashes
The only thing I had done was load a copy of Eystreem's scary survival on my installation with the mod

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
I would recommend using a virtual machiene before doing this or it will wreck your entire installation of the mod

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
Here's the world for testing: https://www.mediafire.com/file/dxk18q4djh9qf1h/world+that+broke+my+entire+minecraft+.zip/file

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
Also before you ask about my pc I just got a new one and it breaks on that too

**Comment by Globalfirestorm10** [comment]
> Mods: only cws
> 
> 
> 
> Mod version: any 1.18.2 future or later versions not yet tested
> 
> 
> 
> Problem: when I launch minecraft and attempt to join a world with the mod it immediately crashes
> 
> The only thing I had done was load a copy of Eystreem's scary survival on my installation with the mod

Sir, please share the crash report

**Comment by nonamecrackers2** [comment]
Yeah, please send the crash report

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
Ok
Give me a moment

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
The game crashed whilst unexpected error Error: java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module

minecraft@1.18.2 of loader 'TRANSFORMER @106d77da)

Exit Code: -1

Also I'm a girl but I really don't care when people misgender me so it's okay

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> The game crashed whilst unexpected error Error: java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module
> 
> minecraft@1.18.2 of loader 'TRANSFORMER @106d77da)
> 
> Exit Code: -1
> 
> Also I'm a girl but I really don't care when people misgender me so it's okay

I got a diffrent crash report when reattempting boot up so here:
The game crashed whilst unexpected error Error: java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.18.2 of loader 'TRANSFORMER @57f847af)

Exit Code: -1

**Comment by Globalfirestorm10** [comment]
please send the full crash report file from that time. If you do not know how, go to .minecraft (if you are on windows, press windows+r, and type in %appdata%, then hit enter. If you are on mac. Click on Go, hit option, find "library", then find .minecraft). From there, go to the "crash reports" folder, then find the crash report from that time

**Comment by nonamecrackers2** [comment]
What version of the mod are you using?

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
Ok good news, when I updated to 2.2 it fixed everything I can load Eystreem's SSS so it's all fixed

However I was using 2.1.1 when the crashes happened

**Comment by nonamecrackers2** [comment]
Ah yeah, the bug you're describing has been fixed in the newest version.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> Ah yeah, the bug you're describing has been fixed in the newest version.

Thank you
Now I can finally make Super TNT Pyrimads Agian
