### ISSUE TITLE
Future withered mobs stats ideas

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#943]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Withered Pig: Moves at the same walking speed as a player, deals 2 hearts, 20 Health

Withered Cow: Moves slightly slower than the withered pig, deals 4 hearts, 25 Health

Withered Chicken: Moves faster than the player walk speed but still out runnable, deals 1 heart, has 15 Health

Withered Sheep: Just as fast as the withered pig, deals 3 hearts, has 30 HP

Withered Witch: Moves as fast as the Withered Cow, Has 40 Health, Throws potions more frequently and harmful status effects inflicted are stronger (ex: posion II, slowness II etc), Withered Witches would also regen 9 health instead of 4 when using a regen potion.

Withered Slime: Jumps farther distances, Large slimes has 30 health, medium slimes has 21 health and small slimes have 10 health. Large slimes deal 8 hearts, medium deals 4 hearts and small slimes deal 2 hearts.

**Comment by NinjaSam5399** [comment]
Good idea

**Comment by Globalfirestorm10** [comment]
another idea is that tainted slimes leave little blobs of itself behind sometimes which you can get stuck in (just apply the soul sand logic to that ig). Other than that, I like the idea

**Comment by nonamecrackers2** [comment]
Closing since the stats will be decided on our discretion as mobs are added
