### ISSUE TITLE
General color customization instead of just the tractor beams

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#945]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217
Maybe instead of only the tractor beam changing color, maybe include other things such as the tractor beam overlay, the wither storms eyes, the glowing effect during night, wither sickness texture, maybe even the fog in the bowels?

**Comment by GrandmaPork** [comment]
I haven’t played with the new tractor beams yet but this seems like how it should be. I don’t care for the wither sickness texture or the fog, cuz then people are gonna be asking for the blocks to be adjusted as well, but it’d only make sense if the eyes, beam overlay, and the glow matched the tractor beam

**Comment by nonamecrackers2** [comment]
Most of things mentioned must be changed via resource packs, however the glow isn't and could use a config option

**Comment by nonamecrackers2** [comment]
Will be possible in the next update via resource packs
