### ISSUE TITLE
Blockage still has normal oak logs

### ISSUE THREAD

**Issue by Dashdestroyer82** [nonamecrackers2/crackers-wither-storm-mod#946]
small lil oversight with the blockage room, and that is there are logs that were not tainted
![2023-02-22_15 09 46](https://user-images.githubusercontent.com/126129803/220807631-30300a8e-9a92-4432-abd8-7ec0e5ddb53a.png)
just a small thing (you better fix my thing or else an F-Bomb will be in your mailbox)

**Comment by nonamecrackers2** [comment]
Will be fixed in 2.2.1/3.2.1
