### ISSUE TITLE
Make the mod more fun. (for people who already played)

### ISSUE THREAD

**Issue by ghost** [nonamecrackers2/crackers-wither-storm-mod#947]
Alr its been a while since I have seen a update on this mod. but with all mods, there is a life cycle.
the mod sees the the daylight and everyone wants a bit of it. everyone has a turn of playing it.  with their friends or by them selves. and whenever I open the mod. I dont care. I just close the game and do something else.
but after a while the mod tends to start being boring. when people have already made content off the mod and there is nothing else left to do. this is a midlife crisis for the mod. I know I sound like a idiot. but no large youtuber has made a video on the mod in a while so I want to address it. right now you need to make the mod more fun, in general or the mods going in the ground and will be considered as a underrated artefact. 

point is this mod is boring right now. no youtubers. no people to play with.
this mod  is just not fun anymore. cause everyone beat it, and not much building to do when the wither storm destroys it.
the best thing to do is to listen to many ideas and put them in the mod. dont shoot them down if they are possible, put it in.
what's the point of suggestions if they are going to be shot down. have the mod reach out to a wider variety of people.
this isn't a Minecraft mod. this is a business, and the mods going to go in the ground without more people working on the mod. more help equals less time spent on the mod.

just make the mod fun again. even for the people who played it already.
ps I'm not saying its not fun. its just not fun for the people who already played the mod hundreds of times.

NOT ABOUT THE DISCORD SERVER. ABOUT THE MOD

**Comment by AzaelKurosaki** [comment]
cry about it (you were banned for a reason)

**Comment by GrandmaPork** [comment]
I don’t think you understand what you’re asking for.
It’s practically an insult to submit this as a suggestion. 
I am not Cracker but I can imagine a LOT of work had gone in to developing this mod, and it just can’t be worth it to spend the time implementing every little feature that may be possible, regardless of how impactful it may be. If people lose interest in it because they beat it once then so be it. This game has a lot of replay ability to it and Cracker just released a huge update regarding features.

**Comment by Bloxxify1520** [comment]
Dude, You got banned from the server and your mad about it so you shit on it. I have about 5 images of you commenting on his videos saying “also ban naza”. Just leave him alone if your mad, nobody cares.

**Comment by ghost** [comment]
its NOT ABOUT THE DISCORD SERER ON GOD

**Comment by myron-obsolete-account** [comment]
why are you making this suggestion? Have you not seen that 2.2/3.2 already released? Is that not enough? Then you are a real bruh moment person

**Comment by Isoknight** [comment]
Here we see a person that doesn't understand how developing works in their natural habitat

**Comment by nonamecrackers2** [comment]
I'd love to keep this mod fresh for everyone however it's extremely hard to do that the way the mod is designed. You go through a very straight forward linear progression, from running away from the WS, gearing up, getting a formidibomb, blowing it up, running away again, gearing up, and then entering and defeating it. While worlds players try to replay on may have different seeds and different world generation, the experience is effectively the same, so it's understandable people don't want to replay it. It doesn't have much going for it replay-value wise and that was expected.

Cracker's Wither Storm Mod is also meant to a "break" from normal Minecraft, providing a fun challenge and something new to do with your favorite block game, not to replace it entirely. "Hey, I'm sick of playing survival let's try out something new." "Hey, there's this new mod called 'Cracker's Wither Storm Mod', want to try it?" "Sure!" ...Then they play it once and probably won't play it again for a while. I don't expect people to be replaying it over and over again. I find this the case with most mods or just mods in general.

Now of course, why are features such as a resummonable Wither Storm present in updates. I do want to provide new content to people who do definitely want to keep playing it. However, I'm not going to scrounge around trying to shove in every possible suggestion just to try to keep everyone playing, becoming a mad-hungry developer who's only in it for the fame and glory. New updates will come when they come, with features I believe will fit the mod best, to bring some replayability for those who do want it. However your suggestion makes it seem like I (or any other developer in fact) should be wasting their time trying to keep something relevant, which just in reality, isn't feasible or realistic for any project. Sorry if I misinterpreted your post.

CWSM still reaches upwards of 3K downloads a day, and I don't feel the mod is in a "mid-life crisis" or becoming an "underrated artifact" any time soon. Mod development is also a passion, not a "business." I appreciate your concerns however.

P.S. CWSM was just recently updated. Also, try out some modpacks using CWSM, such as FTB Inferno and Explorer's Eve, which put different twists on my mod.

**Comment by Globalfirestorm10** [comment]
> Alr its been a while since I have seen a update on this mod. but with all mods, there is a life cycle. the mod sees the the daylight and everyone wants a bit of it. everyone has a turn of playing it. with their friends or by them selves. and whenever I open the mod. I dont care. I just close the game and do something else. but after a while the mod tends to start being boring. when people have already made content off the mod and there is nothing else left to do. this is a midlife crisis for the mod. I know I sound like a idiot. but no large youtuber has made a video on the mod in a while so I want to address it. right now you need to make the mod more fun, in general or the mods going in the ground and will be considered as a underrated artefact.
> 
> point is this mod is boring right now. no youtubers. no people to play with. this mod is just not fun anymore. cause everyone beat it, and not much building to do when the wither storm destroys it. the best thing to do is to listen to many ideas and put them in the mod. dont shoot them down if they are possible, put it in. what's the point of suggestions if they are going to be shot down. have the mod reach out to a wider variety of people. this isn't a Minecraft mod. this is a business, and the mods going to go in the ground without more people working on the mod. more help equals less time spent on the mod.
> 
> just make the mod fun again. even for the people who played it already. ps I'm not saying its not fun. its just not fun for the people who already played the mod hundreds of times.
> 
> NOT ABOUT THE DISCORD SERVER. ABOUT THE MOD

Que te Cojan Mil Cabras. I think everyone has had enough of your rants now. Just leave the community alone

**Comment by Globalfirestorm10** [comment]
> I'd love to keep this mod fresh for everyone however it's extremely hard to do that the way the mod is designed. You go through a very straight forward linear progression, from running away from the WS, gearing up, getting a formidibomb, blowing it up, running away again, gearing up, and then entering and defeating it. While worlds players try to replay on may have different seeds and different world generation, the experience is effectively the same, so it's understandable people don't want to replay it. It doesn't have much going for it replay-value wise and that was expected.
> 
> Cracker's Wither Storm Mod is also meant to a "break" from normal Minecraft, providing a fun challenge and something new to do with your favorite block game, not to replace it entirely. "Hey, I'm sick of playing survival let's try out something new." "Hey, there's this new mod called 'Cracker's Wither Storm Mod', want to try it?" "Sure!" ...Then they play it once and probably won't play it again for a while. I don't expect people to be replaying it over and over again. I find this the case with most mods or just mods in general.
> 
> Now of course, why are features such as a resummonable Wither Storm present in updates. I do want to provide new content to people who do definitely want to keep playing it. However, I'm not going to scrounge around trying to shove in every possible suggestion just to try to keep everyone playing, becoming a mad-hungry developer who's only in it for the fame and glory. New updates will come when they come, with features I believe will fit the mod best, to bring some replayability for those who do want it. However your suggestion makes it seem like I (or any other developer in fact) should be wasting their time trying to keep something relevant, which just in reality, isn't feasible or realistic for any project. Sorry if I misinterpreted your post.
> 
> CWSM still reaches upwards of 3K downloads a day, and I don't feel the mod is in a "mid-life crisis" or becoming an "underrated artifact" any time soon. Mod development is also a passion, not a "business." I appreciate your concerns however.
> 
> P.S. CWSM was just recently updated. Also, try out some mudpacks using CWSM, such as FTB Inferno and Explorer's Eve, which put different twists on my mod.

ah yes, I love mudpacks
