### ISSUE TITLE
Idea for beam colors on servers.

### ISSUE THREAD

**Issue by V0calgiant12** [nonamecrackers2/crackers-wither-storm-mod#948]
**Description of feature**
So with how it is now, there is no way to change the beam colors with datapacks or with commands at all. However, I have an idea, it'll be this sort of opt in/opt out kind of thing. 
Here's the run down:

New client config option: "Server beam colors" this is a toggle on/off option that when true would make you "opted in" for your tractor beam color to be changed to whatever the server tractor beam color is, and to add onto this, there would be a similar option toggle in the server config ("Universal Tractor Beam Color") that would basically determine if there should be a custom color for those who are opted in for it. And, like the client one, there would be 3 rgb sliders/options that would replace the client tractor beam color for those who want it and if the "Universal Tractor Beam Color" is true.

What I think the defaults should be:
"Server Beam Colors": true
"Universal Beam Colors": false
Rgb: same as client default

If you add this, feel free to change the names if you think of better ones, I'm bad at names.

**Comment by nonamecrackers2** [comment]
Closing since this can be done with server resource packs now
