### ISSUE TITLE
Witherstorm causes abnormal RAM usage on server(s)

### ISSUE THREAD

**Issue by ShirakiShio** [nonamecrackers2/crackers-wither-storm-mod#95]
Recently the RAM usage has gradually increased on our Nitrado server, we already have the most expensive RAM plan and it still doesn't appear to be enough. It's peak was 9.2 gigabytes. We have a 8GB plan. It keeps lagging behind so we can't get anything done.

Is there a specific reason for this? Is it a bug? Or should we just switch service, if so, which one? We need one that is based in central europ or preferrably Germany.

If you require info, let me know.

**Comment by nonamecrackers2** [comment]
It may be a memory leak. What version are you using? Do you keep the server running at all times? I'm not sure of a specific reason why.

**Comment by ShirakiShio** [comment]
Which version are you referring to? The game's is 1.16.5, the mod's is the latest for 1.16.5 and forge's is 36.2.35.

The time it hit peak it was only running for about 2-3 hours. I rarely let the server run overnight, 99% of the time it's only running when we are actually playing.

**Comment by nonamecrackers2** [comment]
Sorry should have elaborated, what you gave is fine. I'll need to investigate, never had this happen (or at least that I was aware of).

**Comment by ShirakiShio** [comment]
![image](https://user-images.githubusercontent.com/48332495/173955608-19676a8b-68a9-4fc0-9dd4-d1385ee42b0e.png)
I started it up for a moment to check, here's the RAM usage after a few minutes, for reference.

**Comment by nonamecrackers2** [comment]
Does your provider provide any java diagnostic tools?

**Comment by ShirakiShio** [comment]
It doesn't seem like it, unfortunately.

**Comment by nonamecrackers2** [comment]
If you do "/forge entity list", what entity type is there the most of?

**Comment by ShirakiShio** [comment]
I'll send the list later, after letting the server run for a bit. Don't want it to catch up on us while we're offline.

**Comment by nonamecrackers2** [comment]
Sure

**Comment by ShirakiShio** [comment]
![image](https://user-images.githubusercontent.com/48332495/174037220-b2d1fc22-4f84-489d-b0d6-23649cd330f9.png)
RAM usage is at 9.1 gigs at the time of this screenshot

**Comment by nonamecrackers2** [comment]
If you scroll up, there should be more to that list.

**Comment by ShirakiShio** [comment]
![image](https://user-images.githubusercontent.com/48332495/174091206-b48ac4e2-640a-4b9a-bfbe-2b5dd5ff863d.png)
RAM usage is currently at 9.8gigs

**Comment by nonamecrackers2** [comment]
Try killing all the items using "/kill @e[type=item]" (make sure there isn't anything important laying on the ground)

**Comment by ShirakiShio** [comment]
Changed nothing, it's still gradually going up.

**Comment by nonamecrackers2** [comment]
Weird. On my server, it'll usually go up to 2 gbs and then garbage collection does its thing and it drops back down. Yours doesnt seem to be doing that.

**Comment by ShirakiShio** [comment]
Oddly enough it hasn't been lagging (much) anymore despite the RAM being sky high

**Comment by nonamecrackers2** [comment]
Interesting. It may just be with your server then. I'll keep this open to see if I can reproduce in the future.

**Comment by ShirakiShio** [comment]
I resolved the lag issue by slowing down the Witherstorm, turns out it's speed was causing issues as it was going so fast it was loading a bunch of chunks rapidly. Speed was like 200 blocks in 10 seconds. Because it was 80k blocks away from the target.

**Comment by nonamecrackers2** [comment]
Oh wow, yeah that could cause it.
