### ISSUE TITLE
Wither Storm stops following players if they are 78,000 orso blocks away.

### ISSUE THREAD

**Issue by FrozenDragon0** [nonamecrackers2/crackers-wither-storm-mod#950]
**Minecraft version**
1.19.3

**Mod version**
1.19.3-3.2

**Describe the bug**
When at a very far distance from the storm it'll stop moving towards you entirely and be in a stand still until you go back into it's moving radius.

**To Reproduce**
1. Summon the storm normally either at the house at 0,0 or summon it with commands, preferably at phase 4 or higher targeting the player.
2. Teleport yourself to around 78,000 blocks away from 0,0 with the storm still being within 0,0's proximity.
3. Notice that in the amulet item the storm's distance stops moving entirely unless you walk back into it's tracking distance or you walk further out increasing your distance away from the storm.

**Is Flywheel's optimizations active?**
Flywheel isn't installed.

**Screenshots**
Can't really say too much with screenshots.

Side-note, I'm not 100% sure if this is a bug or if it's a intended feature for the storm to stop moving towards you if your very far out but I figured I'd report it anyway. 
Only way I could notice this was with the amulet as 78,000 blocks away is very far to the point of the storm not even being visible with the distant renderer.

**Comment by FrozenDragon0** [comment]
@nonamecrackers2 I believe this bug also affects 1.18.2 aswell.

**Comment by FrozenDragon0** [comment]
Just tested on 1.18.2 and it seems that this is a 1.19.3 exclusive problem.

**Comment by nonamecrackers2** [comment]
Can't reproduce. What's your mod list? And does this bug occur on a singleplayer world and/or on a server?

**Comment by FrozenDragon0** [comment]
> Can't reproduce. What's your mod list? And does this bug occur on a singleplayer world and/or on a server?

After some testing, looks like Optifine is the culprit for this. Given Optifine being closed source I'm guessing this issue isn't fixable?

**Comment by nonamecrackers2** [comment]
Yeah this wouldn't be then, I wouldn't even know where to start looking
