### ISSUE TITLE
a question about the ban on discord

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#951]
I know it's not really a bug report, for crackers mod, but why did me and 2FA( Aka Nate) get banned?. We didn't break server rules. We got automatically banned (i had carl blocked so I do not see a reason why I got a ban. Please respond -Pandaboi

**Comment by FrozenDragon0** [comment]
You've been unbanned, Carl-bot had a malfunction and autobanned both you and 2FA falsely for whatever reason.

**Comment by Thefuzz1234555** [comment]
Yea for some reason Carl had a fit I revoked the ban

**Comment by Pandaboi25x** [comment]
> You've been unbanned, Carl-bot had a malfunction and autobanned both you and 2FA falsely for whatever reason.

yea apperantly sending a message within a minute counts as 4 fucking strikes 👍

**Comment by MoRoN222** [comment]
Man that turtle do be vibin'

**Comment by Pandaboi25x** [comment]
> Man that turtle do be vibin'

:skull:
