### ISSUE TITLE
When i kill the Wither Storm, the Torso instantly disappears

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#952]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**1.19.3**
The version of Minecraft the mod is running on

**3.2**
The version of the mod you are using

**I /kill the Wither storm but the torso of the wither storm instantly disappears,leaving the tentacles and the heads floating.**

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is Flywheel's optimizations active?**
Specify if Flywheel is installed and it's compat optimizations are enabled

![CWSM Bug](https://user-images.githubusercontent.com/125754458/220937784-77f338f9-4798-4327-8523-59bbeef16b76.png)

**Comment by humzahre** [comment]
please fix this in a potential new update

**Comment by myron-obsolete-account** [comment]
Wow you managed to partially fill out the template! Anyway, this is a known issue and has already been reported (#939) so please close this as this is a duplicate.

**Comment by Globalfirestorm10** [comment]
whyd you open and close this 6 times?

**Comment by humzahre** [comment]
sorry i was confused

**Comment by myron-obsolete-account** [comment]
why reopenhhhhhhh

**Comment by humzahre** [comment]
i thought that was a bad idea to close it and that nonamecrackers2 wouldn't fix it and ignore it

**Comment by Globalfirestorm10** [comment]
Well no, this is a duplicate issue, so hes aware of it

**Comment by myron-obsolete-account** [comment]
Yeah he responded to the first issue that states the same problem. Don't worry he has seen it, responded to it, and 99%-ly will fix it.

**Comment by humzahre** [comment]
ok hopefully :|

**Comment by humzahre** [comment]
1.

**Comment by myron-obsolete-account** [comment]
2.
