### ISSUE TITLE
When I reload the world, the Amulet is inactive until i get close to the wither storm.

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#953]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**1.19.3**
The version of Minecraft the mod is running on

**3.2**
The version of the mod you are using

**When I reload the world, the Amulet doesn't pulsate until i get close to the storm. In the Tooltip it says ''Wither Storm: Couldn't find nearby''

**To Reproduce**

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Flywheel isnt enabled**
Specify if Flywheel is installed and it's compat optimizations are enabled

**Screenshots**
![CWSM Bug 2](https://user-images.githubusercontent.com/125754458/220941738-36c03248-3b60-4573-9d1f-4f3e786c8c6a.png)

**Comment by nonamecrackers2** [comment]
If you're more than 1K blocks away from the storm, it won't pulse when you look at it.

**Comment by humzahre** [comment]
i had to LOAD IN the Wither Storm by getting close to it

**Comment by humzahre** [comment]
By the way when I look at the Tooltips, it says ''Wither Storm: Couldn't find nearby''

**Comment by humzahre** [comment]
please fix it

**Comment by nonamecrackers2** [comment]
Yeah, if you reload and if you're farther than 1K blocks you'll have to get close to it for it to be detected, this is intentional
