### ISSUE TITLE
spinning amulet inside the withered beacon

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#954]
it would be very cool to see the amulet spinning inside the withered beacon (there could also be a config to change the speed of the spinning amulet
![image](https://user-images.githubusercontent.com/121638798/220985053-4a4acb11-9c7e-4fd3-827c-daf15d32876d.png)
image so that you would know what i mean and what amulet where how
oh and a question why is there no "to be confirmed" label? because i see only misc and idk if somethin gon get confirmed or not

:jess:

**Comment by watersofnazareth** [comment]
I don't think this would be a good idea, the beacon is already pretty well animated by itself, I'll let Cracker's give his opinion on this but I don't like the idea of the amulet spinning

**Comment by Pandaboi25x** [comment]
> I don't think this would be a good idea, the beacon is already pretty well animated by itself, I'll let Cracker's give his opinion on this but I don't like the idea of the amulet spinning

oh well even if it doesnt it was worth trying

**Comment by nonamecrackers2** [comment]
It could be interesting to see it spin but would require some work, I'll have to think on it

**Comment by nonamecrackers2** [comment]
I think we're gonna roll with keeping the amulet stationary. The amulet is already baked into the withered beacon model and I don't really think removing it to make it spin in the block entity renderer is something that would be worth the effort to do.

**Comment by Pandaboi25x** [comment]
> I think we're gonna roll with keeping the amulet stationary. The amulet is already baked into the withered beacon model and I don't really think removing it to make it spin in the block entity renderer is something that would be worth the effort to do.

its fine i was thinking about closing this because i imagined how it would look like
