### ISSUE TITLE
Upon reloading the world, the wither storm unloads and only one segment is loaded in

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#955]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**1.19.3**
The version of Minecraft the mod is running on

**3.2**
The version of the mod you are using

**When i reload the world, the wither storm and the right segment unloads. The left segment is showing only. **

**To Reproduce**
1. teleport away from WS
2. Reload the world and the WS segment will show

**No crashes**
Crash reports / logs hosted on pastebin, gist, etc.

**No Flywheel**
Specify if Flywheel is installed and it's compat optimizations are enabled

**Screenshots**
![CWSM Bug 3](https://user-images.githubusercontent.com/125754458/221008709-2064673d-6967-465b-bc3e-2448a8aa02e7.png)

**Comment by V0calgiant12** [comment]
Do you have any other mods installed?

**Comment by humzahre** [comment]
no

**Comment by humzahre** [comment]
only CWSM

**Comment by humzahre** [comment]
yes i have WorldEdit and CWSM

**Comment by V0calgiant12** [comment]
Hmm, yeah, I was playing last night as well and one of the segments unloaded for me, might have something to do with graphic settings?

**Comment by nonamecrackers2** [comment]
Do you have optifine installed?

**Comment by V0calgiant12** [comment]
Nope, and mine didn't happen when I left and rejoined, I just flew away in creative and a segment unloaded. It might have to do with using fast graphics and/or chunks not loading because I was on my phone when it happened  (not bedrock edition btw, using pojav launcher)

**Comment by humzahre** [comment]
no optifine

**Comment by humzahre** [comment]
btw it was also facing the wrong direction. It wasnt distracted

**Comment by nonamecrackers2** [comment]
Does the other Wither Storm load back in when you go to it's original position? Also is this singleplayer or multiplayer?

**Comment by humzahre** [comment]
im in singleplayer

**Comment by nonamecrackers2** [comment]
> Does the other Wither Storm load back in when you go to it's original position?

And what about this?

**Comment by V0calgiant12** [comment]
For me it did load back in, and then the distant render appeared again

**Comment by humzahre** [comment]
when i got close to WS, when the bossbar appeared, it fixed

**Comment by nonamecrackers2** [comment]
Weird, for some reason it just stops chunk loading. Do you have optifine installed?

**Comment by V0calgiant12** [comment]
You... Already asked the question, I mean, to be fair, it must be really hard to keep track of what questions you've already asked for what issues because there's so many of them. But no, neither of us have optifine, as we answered before.

**Comment by nonamecrackers2** [comment]
Yeah lol sorry, there is a lot to keep track of. I will have to investigate, thank you

**Comment by nonamecrackers2** [comment]
Unable to reproduce. This may be down to hardware, considering @V0calgiant12 said they were using their phone to play the mod when the bug occurred.
