### ISSUE TITLE
full WS soundtrack

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#956]
the in-game WS soundtrack doesn't contain the full wither storm theme found here: https://www.youtube.com/watch?v=WvZ3hwwRSkY
my idea is that the full theme should be implemented as the soundtrack. 

also maybe the early part of WS destroyed should be played as an ambient music in the bowels?

**Comment by myron-obsolete-account** [comment]
You can make a resourcepack to change the music.

**Comment by nonamecrackers2** [comment]
Didn't pick this out earlier: #227

**Comment by BluePineappleGuy** [comment]
> Didn't pick this out earlier: #227

?
that one's saying dynamic music (music depends on situation), i'm saying up until 8:05 should play as the theme instead of getting cut off at 4:01

**Comment by nonamecrackers2** [comment]
Ah my bad, sorry about that

**Comment by nonamecrackers2** [comment]
More parts of the theme will be added in the next major release.
