### ISSUE TITLE
Command block tools upgrade

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#957]
Base stats of the command block tools could be lowered to diamond level, but every attack runs a weaker version of a random command. For example, it could use the /tp command to randomly teleport an enemy, or the /attribute command to change the enemy's base stats for a few seconds.

**Comment by Asteroid4** [comment]
My reason for this is to make command block books more valuable, which incentives respawning the storm.

**Comment by watersofnazareth** [comment]
This would make the tools too powerful, they are fine as is and this change isn't necessary as the tools are pretty decently balanced as is

**Comment by nonamecrackers2** [comment]
I agree
