### ISSUE TITLE
Place a Shrieker in the Deep Dark Maze Section in Bowel

### ISSUE THREAD

**Issue by WorldSpinAround** [nonamecrackers2/crackers-wither-storm-mod#958]
I understand a Warden in the Bowels would be overkill, but at the very least, add a deactivated Shrieker (simply place one from creative).

They bring the perfect amount of fear in your heart, when you think the Wither Storm by itself couldn't make the situation any worse. Just hearing one Shrieker would freak you out, as you fear a Warden might arrive.

Sure enough, no Wardens. But for new players, this could be fun!

--------------------------------
Now,
If the issue for the Warden is that it follows you outside the Maze, then perhaps make the entrance and exit 2 blocks tall, or 2,5 blocks tall.
You have 4 chances upon encountering an Activated Shrieker.

**Comment by myron-obsolete-account** [comment]
Sickened Warden would be sick tho.

**Comment by Globalfirestorm10** [comment]
If there was a sickened warden, it should be a secret boss of sorts tbh

**Comment by watersofnazareth** [comment]
We agreed that we wouldn't have the Warden summonable in the maze due to concerns for the players, but non functional shreikers may be added

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release
