### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#96]
I know this isn't much of a suggestion for the actual mod but in general, but it would be cool for there to be a Discord server for news and other things relating to the mod or other projects and also bug reports like in this Github issue tracker.

Also it'd likely be a good idea to have some kind of verification if a server was made due to people being spammy or immature in Minecraft mod Discord servers and not reading FAQs

**Comment by nonamecrackers2** [comment]
I may consider it in the future. Running a discord server is something I don't have the resources for at the moment.
