### ISSUE TITLE
Different way of resummoning the wither storm.

### ISSUE THREAD

**Issue by illucc** [nonamecrackers2/crackers-wither-storm-mod#960]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Instead of beacons summoning a big wither storm(i forgor stage numbers) It should instead make a "hologram" of the command block and when a normal wither is brought near it then they both would fuse together.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by BluePineappleGuy** [comment]
or it could just spawn a command block and then you can use the summoning totem to resummon the storm

**Comment by nonamecrackers2** [comment]
We'll be keeping the resummoning system as it is for now
