### ISSUE TITLE
3.2 for 1.19.2?

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#962]
**Description of feature**
I have so many other cool mods installed alongside your mod and most of them aren't updated for 1.19.3, so could you maybe please port the latest update a little bit back to 1.19.2? That would be nice.

**Comment by Globalfirestorm10** [comment]
iirc, he said there was a forge incompatibility that he needed to workaround

**Comment by myron-obsolete-account** [comment]
there indeed is an incompatibility as I couldn't play it in 1.19.2 :(

**Comment by V0calgiant12** [comment]
There's a major difference between the two versions internally, so, like he said in the discord, it just wasn't worth the effort and would have made the update take longer.

Also, you can't play the 1.19.2 version on the latest version of forge, you have to use version 44.2.3 or lower

**Comment by watersofnazareth** [comment]
1.19.3 will not be backported to 1.19.2

**Comment by myron-obsolete-account** [comment]
> 1.19.3 will not be backported to 1.19.2

but why

**Comment by nonamecrackers2** [comment]
There's some big code changes between 1.19.3 and 1.19.2, and it would take a lot of extra time to port them over and I don't think it would be worth my time

**Comment by myron-obsolete-account** [comment]
😞
