### ISSUE TITLE
Different color of the tractor beam screen effect depending on the color

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#963]
(I don't know how to explain it well). So, depending on the tractor beam color, the tractor beam screen effects would be that specific color of the tractor beam. For example, you change the tractor beam to blue and the screen effect would turn blue too if you are inside a tractor beam instead of purple tractor beam screen effects on blue tractor beam. My explanation might be bad.

**Comment by myron-obsolete-account** [comment]
I have an idea for this. Grass and water textures are black and white to then gain their unique color depending on in what biome they are. Maybe this could be used for the tractor beam overlay? Depending on what color it's set to, the, then white, overlay gets recolored to the respective tractor beam color. Should work I guess.

**Comment by NinjaSam5399** [comment]
ok

**Comment by myron-obsolete-account** [comment]
> ok

based

**Comment by watersofnazareth** [comment]
You can make a resource pack to do this, it's not really worth the time and effort to do this especially since this is handled by a texture that can be easily edited

**Comment by NinjaSam5399** [comment]
Ok Thanks
