### ISSUE TITLE
Blocks turn green after destroying the withered beacon when its spawning the wither storm.

### ISSUE THREAD

**Issue by KrukAdrian** [nonamecrackers2/crackers-wither-storm-mod#964]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2

**Mod version**
1.18.2

**Describe the bug**
Basically once the withered beacon is activated it sucks up all the blocks but when its destroyed the blocks fly away and turn green.

**To Reproduce**
When the withered beacon is destroyed make them fall
![Zrzut ekranu (2315)](https://user-images.githubusercontent.com/106917942/221282550-9a4a99df-f219-4626-a3ea-aac34466b7b4.png)

**Screenshots**

**Comment by Pandaboi25x** [comment]
#937  this already had been an issue lol

**Comment by myron-obsolete-account** [comment]
aha another duplicate

**Comment by myron-obsolete-account** [comment]
ngl I should become a contributor so I can close issues that are a duplicate (kidding)

**Comment by KrukAdrian** [comment]
bruh.... i was literally checking if another issue like  this has been posted. Its weird when I make a duplicate i feel ashamed

**Comment by myron-obsolete-account** [comment]
Don't feel ashamed, duh.

**Comment by nonamecrackers2** [comment]
> bruh.... i was literally checking if another issue like this has been posted. Its weird when I make a duplicate i feel ashamed

It's alright, happens to everyone

**Comment by NinjaSam5399** [comment]
Are you going to fix it cracker?
