### ISSUE TITLE
New spawning mechanics for sickened mobs

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#965]
Some of the sickened mob blocks in the walls would climb out of the walls and turn into normal sickened mobs, and that could be how the command block spawns mobs when it is hit.

**Comment by Asteroid4** [comment]
There would need to a be a lot more sickened mobs in the walls for this to work though

**Comment by Pandaboi25x** [comment]
#933 this was actually already suggested

**Comment by Asteroid4** [comment]
Oh.


So should I close it?

**Comment by Globalfirestorm10** [comment]
Yeah
