### ISSUE TITLE
WS semi-invisible during death

### ISSUE THREAD

**Issue by TeaCupsTeaPots** [nonamecrackers2/crackers-wither-storm-mod#966]
**Minecraft version**
1.19.3 (forge 44.1.17)

**Mod version**
1.19.3-3.2

**Describe the bug**
During the wither storm's death animation (real death, not playing dead), the main body of the wither storm and the main body of it's segments disappear, leaving only the tentacles and heads.
Issue happens whether I am using optifine or not (I've tested both).

**To Reproduce**
1. Kill the wither storm at phase seven via either commands or in the bowels (I've tested both).
2. Watch it's death animation and the body is invisible.

**Is Flywheel's optimizations active?**
Flywheel is not installed.

**Screenshots**
![2023-02-25_10 54 22](https://user-images.githubusercontent.com/102552124/221353140-bf77ca93-42f6-4998-8877-d864ba4257bf.png)
![2023-02-25_10 54 27](https://user-images.githubusercontent.com/102552124/221353145-684e4900-3b66-42f4-a13c-992888fec668.png)

**Comment by myron-obsolete-account** [comment]
Man so many people reporting that issue duh

**Comment by Globalfirestorm10** [comment]
> 
> 
> **Minecraft version**
> 
> 1.19.3 (forge 44.1.17)
> 
> 
> 
> **Mod version**
> 
> 1.19.3-3.2
> 
> 
> 
> **Describe the bug**
> 
> During the wither storm's death animation (real death, not playing dead), the main body of the wither storm and the main body of it's segments disappear, leaving only the tentacles and heads.
> 
> Issue happens whether I am using optifine or not (I've tested both).
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Kill the wither storm at phase seven via either commands or in the bowels (I've tested both).
> 
> 2. Watch it's death animation and the body is invisible.
> 
> 
> 
> **Is Flywheel's optimizations active?**
> 
> Flywheel is not installed.
> 
> 
> 
> **Screenshots**
> 
> ![2023-02-25_10 54 22](https://user-images.githubusercontent.com/102552124/221353140-bf77ca93-42f6-4998-8877-d864ba4257bf.png)
> 
> ![2023-02-25_10 54 27](https://user-images.githubusercontent.com/102552124/221353145-684e4900-3b66-42f4-a13c-992888fec668.png)
> 
> 
> 
> 

This is a duplicate, it's a known issue already, so please close this
