### ISSUE TITLE
⚠️𝗖𝗥𝗔𝗦𝗛⚠️𝘞𝘪𝘵𝘩𝘦𝘳𝘴𝘵𝘰𝘳𝘮 𝘔𝘰𝘥 𝘤𝘢𝘶𝘴𝘦𝘴 𝘮𝘺 𝘨𝘢𝘮𝘦 𝘵𝘰 𝘤𝘳𝘢𝘴𝘩 𝘰𝘯 𝘸𝘰𝘳𝘭𝘥 𝘫𝘰𝘪𝘯!

### ISSUE THREAD

**Issue by User4716** [nonamecrackers2/crackers-wither-storm-mod#967]
**Cracker's Wither Storm Mod** (witherstormmod-1.19.2-3.1.1.jar) crashes my game when I join a world.

**I use Forge 43.2.4 - 1.19.2**
**Mod version: 3.1.1**

Flywheel is installed
Oculus is not installed
Iris & Oculus Flywheel Compat is not installed
ㅤ

**My game crashes when I try to join a world and it says "Joining world..."**
![2023-02-25_14 52 03](https://user-images.githubusercontent.com/97033682/221357937-a7eb20a9-f339-4193-ad3e-60d961c0cbbe.png)

**Here is the latest.log**
**[latest.log](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10831193/latest.log)**
**And crash.log**
**[crash-2023-02-25_14.51.51-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10831199/crash-2023-02-25_14.51.51-client.txt)**
ㅤ

**Below is the important part of the crash report. But please check the log files above to get full logs.**

> **-- Head --**
> Thread: Render thread
> **Stacktrace:**
> at nonamecrackers2.witherstormmod.common.event.WitherSicknessEvents.onWorldTick(WitherSicknessEvents.java:36) ~[witherstormmod-1.19.2-3.1.1.jar%23449!/:1.19.2-3.1.1] {re:classloading}
> at nonamecrackers2.witherstormmod.common.event.__WitherSicknessEvents_onWorldTick_LevelTickEvent.invoke(.dynamic) ~[witherstormmod-1.19.2-3.1.1.jar%23449!/:1.19.2-3.1.1] {re:classloading,pl:eventbus:B}
> at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
> at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
> at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
> at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:815) ~[forge-1.19.2-43.2.4-universal.jar%23466!/:?] {re:classloading}

ㅤ
> **-- Affected level --**
> **Details:**
> All players: 1 total; [LocalPlayer['MyMcUsername'/145, l='ClientLevel', x=-8.50, y=85.00, z=-3.50]]
> Chunk stats: 1024, 418
> Level dimension: minecraft:overworld
> Level spawn location: World: (0,76,0), Section: (at 0,12,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
> Level time: 49 game time, 49 day time
> Server brand: forge
> Server type: Integrated singleplayer server

ㅤ
> **Stacktrace:**
> at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23461!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:dogslie.mixins.json:ClientLevelMixin,pl:mixin:APP:witherstormmod.mixins.json:MixinClientLevel,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:waterdripsound.mixins.json:client.MixinClientWorld,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}

> at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2280) ~[client-1.19.2-20220805.130853-srg.jar%23461!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:dynmus-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:plasmovoice-common.mixins.json:MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}

> at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23461!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:dynmus-common.mixins.json:MinecraftClientMixin,pl:mixin:APP:entity_texture_features-common.mixins.json:reloading.MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:cgm.mixins.json:client.MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:plasmovoice-common.mixins.json:MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}

> at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23461!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
> at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23461!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
> at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?] {}
> at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
> at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
> at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
> at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
> at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
> at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
> at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
> at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

**Please can someone help me with this, I am not sure how to fix this..**

**Comment by myron-obsolete-account** [comment]
Why is there some weird font text in the title

**Comment by Globalfirestorm10** [comment]
This is a known bug, for now, use the recommended 1.19.2 version, please close this

**Comment by watersofnazareth** [comment]
1.19.2 will not be updated, if you want to avoid this issue please update to 1.19.3

**Comment by myron-obsolete-account** [comment]
> 1.19.2 will not be updated, if you want to avoid this issue please update to 1.19.3

bruh they said they used 3.1.1 not 3.2 🤦‍♂️

**Comment by nonamecrackers2** [comment]
As others said, use the recommended 1.19.2 forge version or use 3.2

**Comment by User4716** [comment]
So does this mean that I need to use 1.19.3 in order to play with this mod? It shouldn't be like that..

**Comment by User4716** [comment]
I guess I just have to wait until all my mods update to 1.19.3 or maybe 1.19.4 in the future..

The owner of this mod, nonamecrackers2 said: **"There's some big code changes between 1.19.3 and 1.19.2, and it would take a lot of extra time to port them over and I don't think it would be worth my time"**

>_https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/962_

**Comment by Globalfirestorm10** [comment]
> So does this mean that I need to use 1.19.3 in order to play with this mod? It shouldn't be like that..

If you want the latest features, yeah. If you absolutely want to stay on 1.19.2, use the recommended forge version
