### ISSUE TITLE
Question: Requirements for resummoning the Wither Storm

### ISSUE THREAD

**Issue by anonymoususer923847** [nonamecrackers2/crackers-wither-storm-mod#969]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

In the trailer for the new update, it can be seen that the Wither Storm is resummoned with five beacons with all pyramid layers (presumably one main withered beacon and four supporting ones of different colors). When playing, can I resummon the storm with (1) one full withered beacon pyramid, (2) one partial pyramid (with only one or two mineral layers), or (3) by placing the withered beacon DIRECTLY on a grass block and right-click three wither skeleton skulls?

**Comment by myron-obsolete-account** [comment]
You only need a Withered Beacon and 3 Wither Skeleton Skulls, nothing else.

**Comment by anonymoususer923847** [comment]
You mean I can place the sole Withered Beacon (no pyramids) and put the skulls in and the WS will be summoned?

**Comment by myron-obsolete-account** [comment]
Yeah. I suggest you get the fuck out of the area before the beast kills you though.

**Comment by anonymoususer923847** [comment]
Is it true, Cracker?

**Comment by myron-obsolete-account** [comment]
> Is it true, Cracker?

https://user-images.githubusercontent.com/53058491/221625529-de92594a-aada-4f00-8f23-43d8edf8ae30.mp4

**Comment by anonymoususer923847** [comment]
Thx

**Comment by nonamecrackers2** [comment]
Yeah, you can resume on the WS with only the main beacon, doesn’t have to be activated
