### ISSUE TITLE
storm doesn't fully render with shaders on

### ISSUE THREAD

**Issue by angrybird12186** [nonamecrackers2/crackers-wither-storm-mod#972]
minecraft version: 1.19.3
mod version: newest version
bug description: when shaders are turned on, only the storm's heads and tentacles render
Steps to reproduce the behavior: play the mod with optifine and use shaders (i used complementary shaders and bsl)
**Is OptiFine installed?**
yes

**Screenshots**
![image_2023-02-27_112136339](https://user-images.githubusercontent.com/116077325/221550958-5c1ce750-b293-420f-b444-67072ea1eceb.png)

**Comment by Globalfirestorm10** [comment]
this happens also not only happens with optifine itself, but with every single shader.

**Comment by myron-obsolete-account** [comment]
boi that storm looking funny yo

**Comment by nonamecrackers2** [comment]
#939

**Comment by myron-obsolete-account** [comment]
> #939

I think that only happens when the Wither Storm dies, this issue might be different.

**Comment by myron-obsolete-account** [comment]
@nonamecrackers2 hi it's me again sorry but please reopen this this is a different issue because this one doesnt happen on death its something different aswell as issue #1030 duh

**Comment by nonamecrackers2** [comment]
Guess you're technically right, was going to use #939 to encompass all of the related body "unloading" issues however it would be best to seperate them.

**Comment by nonamecrackers2** [comment]
> @nonamecrackers2 hi it's me again sorry but please reopen this this is a different issue because this one doesnt happen on death its something different aswell as issue #1030 duh

Thanks for catching that, there's a lot of suggestions and I usually quickly read most of them, missing some key details, including your original comment about it being different.

**Comment by Globalfirestorm10** [comment]
I noticed that this issue is not present with oculus and rubidium, however the body unloading and the tentacles whitening happens in the death animation

**Comment by nonamecrackers2** [comment]
> I noticed that this issue is not present with oculus and rubidium, however the body unloading and the tentacles whitening happens in the death animation

As a replacement for optifine?

**Comment by Globalfirestorm10** [comment]
Yes, I used oculus and rubidium as a replacement for optifine

**Comment by nonamecrackers2** [comment]
Managed to figure out it's due to optifine (tested only in 1.18.2 so far) and a patch will be implemented as a work around to fix this issue

**Comment by Globalfirestorm10** [comment]
Both 1.19.3 and 1.18.2 have this issue, I can confirm. I'm glad to see that you will find a patch a for this issue

**Comment by nonamecrackers2** [comment]
Yeah, just haven't gotten to 1.19 yet

**Comment by nonamecrackers2** [comment]
Will be fixed in 2.2.1/3.2.1
