### ISSUE TITLE
Game continues to crash

### ISSUE THREAD

**Issue by OskarSl66** [nonamecrackers2/crackers-wither-storm-mod#973]
**Mod version**
1.19.2/witherstormmod-1.19.2-3.1.1.jar

**Describe the bug**
The Bug Is I want to Play this on A singleplayer world creative and the game crashes and the error says as follows:
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.19.2 of loader 'TRANSFORMER' @7f2d31af)

**To Reproduce**
1. Go to ''

**Crash Reports / Logs**
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.19.2 of loader 'TRANSFORMER' @280d4882)

**Is OptiFine installed?**
yes and no

**Comment by Globalfirestorm10** [comment]
> **Mod version**
> 
> 1.19.2/witherstormmod-1.19.2-3.1.1.jar
> 
> 
> 
> **Describe the bug**
> 
> The Bug Is I want to Play this on A singleplayer world creative and the game crashes and the error says as follows:
> 
> The game crashed whilst unexpected error
> 
> Error: java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.19.2 of loader 'TRANSFORMER' @7f2d31af)
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Go to ''
> 
> 2. Click on '....'
> 
> 3. Scroll down to '....'
> 
> 4. See error
> 
> 
> 
> **Crash Reports / Logs**
> 
> The game crashed whilst unexpected error
> 
> Error: java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.19.2 of loader 'TRANSFORMER' @280d4882)
> 
> 
> 
> **Is OptiFine installed?**
> 
> yes and no
> 
> 


1. Is optifine installed or not? Specify
2. Next time, please fill out the template properly
3. Attach the crash report.txt file, as nobody can help you without it

**Comment by myron-obsolete-account** [comment]
This bug has been fixed in the latest version, please close this.

**Comment by Oshen09** [comment]
This bug might be fixed in the new 1.19.3 and 1.18.2 versions, but I've been having the same problem in my 1.19.2 world, as the most recent patch to the mod has not been released to that version.

**Comment by nonamecrackers2** [comment]
1.19.2 has been updated to fix this crash issue

**Comment by myron-obsolete-account** [comment]
omg real

**Comment by myron-obsolete-account** [comment]
yo can we do 3.1.1.1.1

**Comment by Linksapprentice** [comment]
I'm getting this error in a 1.16.5 version as well

**Comment by nonamecrackers2** [comment]
> I'm getting this error in a 1.16.5 version as well

You should not be getting this same error. I recommend opening a new issue and attaching your crash report/log
