### ISSUE TITLE
Command for generating a rundown house in a dimension

### ISSUE THREAD

**Issue by Globalfirestorm10** [nonamecrackers2/crackers-wither-storm-mod#974]
Description of feature
Describe what you want in the mod. Make sure this was not already suggested.

ONLY ONE FEATURE REQUEST PER ISSUE

Basically, you could add a command to generate the rundown house in a dimension. Simple enough, right? You just make a command, and make it so that the nbt structure spawns in from the players location. This would help solve the issue of people complaining that they want to beat the ender dragon then summon the WS. However, if possible, perhaps the materials could vary depending on which dimension the house is generated in ("dimension" as in the nether or end, not modded ones ofc, as that would probably be too difficult).

**Comment by Globalfirestorm10** [comment]
That aside, you've done a great job with this mod, but I have a question: what inspired you to make such a mod?

**Comment by myron-obsolete-account** [comment]
> Description of feature Describe what you want in the mod. Make sure this was not already suggested.
> 
> ONLY ONE FEATURE REQUEST PER ISSUE
> 
> Basically, you could add a command to generate the rundown house in a dimension. Simple enough, right? You just make a command, and make it so that the nbt structure spawns in from the players location. This would help solve the issue of people complaining that they want to beat the ender dragon then summon the WS. However, if possible, perhaps the materials could vary depending on which dimension the house is generated in ("dimension" as in the nether or end, not modded ones ofc, as that would probably be too difficult).

I think you can place the structure using the /place command

**Comment by FrozenDragon0** [comment]
The only real dimension the storm would work in outside the overworld is the End, the Nether's ceiling causes the storm to not function properly.

**Comment by nonamecrackers2** [comment]
> That aside, you've done a great job with this mod, but I have a question: what inspired you to make such a mod?

Replaying Minecraft story mode again on my old iPad mini

**Comment by Globalfirestorm10** [comment]
> > That aside, you've done a great job with this mod, but I have a question: what inspired you to make such a mod?
> 
> 
> 
> Replaying Minecraft story mode again on my old iPad mini

Interesting

**Comment by myron-obsolete-account** [comment]
> > That aside, you've done a great job with this mod, but I have a question: what inspired you to make such a mod?
> 
> Replaying Minecraft story mode again on my old iPad mini

Netflix huh?

**Comment by nonamecrackers2** [comment]
No, I have the actual game on the thing

**Comment by nonamecrackers2** [comment]
Datapacks could be used to change the dimension the platform spawns in. Also the /place command exists in 1.19 however I'm not entirely sure if it can place the structure in different dimensions

**Comment by Globalfirestorm10** [comment]
Got it, thanks
