### ISSUE TITLE
Wither Storm sending withered mobs through nether portal

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#975]
Right now, all the wither storm does when you go through a nether portal is wait until you leave that portal. It makes more sense for the wither storm to send waves of withered mobs through until you go back to the overworld.

**Comment by watersofnazareth** [comment]
I am actually experimenting with making fleeing mobs go into portals, but this specific feature has been suggested #343

**Comment by Asteroid4** [comment]
of course my specific search terms dont match #343

**Comment by Asteroid4** [comment]
> I am actually experimenting with making fleeing mobs go into portals

I'm interested to see how that develops though.
