### ISSUE TITLE
Direct Command Block Control of withered mobs.

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#976]
During the command block fight, the command block could gain direct control of withered mobs, causing the mob to emit command block particles, and making it significantly stronger. For balancing purposes, I think this feature should only be enabled when the wither storm was spawned with a wither storm beacon.

**Comment by Asteroid4** [comment]
I just realized now, that’s literally the lore behind the withered symbiont

**Comment by nonamecrackers2** [comment]
I personally don't feel the command block should take direct control over the withered mobs, as mentioned this is effectively what has been done with the Withered Symbiont
