### ISSUE TITLE
podium flip

### ISSUE THREAD

**Issue by BluePineappleGuy** [nonamecrackers2/crackers-wither-storm-mod#977]
So things like the bowels flipping during the fight is impossible, but what about a podium flip? this would not require so many blocks to be moved at once and would not require any dependencies either. but the idea would require upside down tentacles for the ones on the podium, so maybe it would be considered low priority.

**Comment by nonamecrackers2** [comment]
#105

**Comment by nonamecrackers2** [comment]
Sorry kind of just liked scanned over it, reopening

**Comment by nonamecrackers2** [comment]
This would require some work I'm currently not willing to do, such as some drastic code changes to allow for seamless flipping (instead of it just "jumping" 180 degrees which I'd rather avoid doing)
