### ISSUE TITLE
Withered beacon fusion crafting

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#978]
Here’s an idea:

if you click on the withered beacon or a withered support beacon with an item, it will add that item to the beacon, and it will float on top of the beacon. If you place the items in a certain way, they will combine into an entity or an item.

Example:
Command block book in the center plus one zombie skull plus 2 tainted flesh plus one tainted bone resummons a symbiote.

**Comment by Asteroid4** [comment]
Somewhat like Draconic Evolution’s fusion crafting.

**Comment by Asteroid4** [comment]
Forgot to mention, you can add your own recipes with data packs or something

**Comment by Globalfirestorm10** [comment]
> Forgot to mention, you can add your own recipes with data packs or something 

Or with mods like craftweaker

**Comment by Asteroid4** [comment]
> > Forgot to mention, you can add your own recipes with data packs or something
> 
> Or with mods like craftweaker

yea

Also, im guessing this should be low priority

**Comment by Globalfirestorm10** [comment]
I agree, as again, you can do this with datapacks or mods

**Comment by BluePineappleGuy** [comment]
wait is this getting added because it got closed as COMPLETED

**Comment by nonamecrackers2** [comment]
Will be implemented in the next major release

**Comment by angrybird12186** [comment]
are all of the combinations written anywhere? i only know about the reuben one and i've been trying to find more for about 20 minutes now
![image_2023-09-12_132501842](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/116077325/c03032e0-3d4b-4c4b-82ac-9ddbbe32395d)

**Comment by myron-obsolete-account** [comment]
> are all of the combinations written anywhere? i only know about the reuben one and i've been trying to find more for about 20 minutes now ![image_2023-09-12_132501842](https://user-images.githubusercontent.com/116077325/267327106-c03032e0-3d4b-4c4b-82ac-9ddbbe32395d.png)

you can use JEI to view the recipes

**Comment by angrybird12186** [comment]
the beacons don't have crafting table gui. you just place items on them by right clicking, so i don't think it would work
edit: it worked. ty

**Comment by myron-obsolete-account** [comment]
> the beacons don't have crafting table gui. you just place items on them by right clicking, so i don't think it would work

bro
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/53058491/470ede70-c5ff-4e56-8d4f-f4e3b5aa10ca)

edit: didn't see your edit lmao
