### ISSUE TITLE
MAJOR BUG: Sometimes the Witherstorm unloads while players are in the nether.

### ISSUE THREAD

**Issue by Pakins0** [nonamecrackers2/crackers-wither-storm-mod#98]
Playing 1.16.5 Version (This has happened twice)
When I exit the nether the witherstorm cannot be seen
No chunks are forceloaded like they should be around the storm
/kill @e[type=witherstormmod:wither_storm] does nothing
Another one has to be spawned in order to work
One time I did this the witherstorm was still alive it just unloaded but I can't confirm that for the second time

**Comment by nonamecrackers2** [comment]
Are you using the latest 1.16.5 version of the mod?

**Comment by Pakins0** [comment]
Yes

**Comment by nonamecrackers2** [comment]
Will have to investigate then

**Comment by nonamecrackers2** [comment]
Were you using OptiFine? If so, "Smooth World" probably was the culprit. Also, has this issue occured mutliple times?

**Comment by nonamecrackers2** [comment]
Closing until this issue can be reliably reproduced.
