### ISSUE TITLE
Less smart boss bar

### ISSUE THREAD

**Issue by HeyItsZer0** [nonamecrackers2/crackers-wither-storm-mod#980]
So with the new Smart boss bar feature the music almost never reaches past the drone at the start, since it- in my experience- keeps getting reset if I run behind a tree or any slightest obstruction. Not the biggest of issues, but it does get a little irritating. Maybe it'd be possible to make it less sensitive to obstructions or at least put a toggle in the config to switch between the smart boss bar and the regular one?

**Comment by Asteroid4** [comment]
Theres already an option for disabling the smart bossbar, but I think it would be good if there had to be at least 10 or so blocks between you and the storm for the bossbar and music to go away.

**Comment by HeyItsZer0** [comment]
Ah, we found it. My bad, the LAN world's host was just blind as hell and couldn't find it in the config. Thanks.
