### ISSUE TITLE
Witherstorm don't catch formidbomb

### ISSUE THREAD

**Issue by KowiNaz** [nonamecrackers2/crackers-wither-storm-mod#981]
**Minecraft version**
1.18.3 and 1.19.2-3

**Mod version**
2.2

Witherstorm don't catch formidbomb. How to set it on?

**Comment by myron-obsolete-account** [comment]
wheres the rest of the bug report template? steps to reproduce? screenshots or videos?

**Comment by nonamecrackers2** [comment]
Use flint and steel to light it
