### ISSUE TITLE
The button introduction of the mod option does not translate the key name

### ISSUE THREAD

**Issue by zChenX1** [nonamecrackers2/crackers-wither-storm-mod#982]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3 Forge 44.1.20

**Mod version**
3.2

**Describe the bug**
The description of the button in the mod settings inside the "W" button does not have a localized key name

**To Reproduce**

1. Select a different language
2. Click on the in-game purple 'W' setting screen
3. Click any option button
4. The title of the option button is translated normally, but the floating text is not translated and the original en_us.json does not have a localized key name

**Crash Reports / Logs**
no

**Is OptiFine installed?**
Not Installed Optifine.

**Screenshots**
![R 7RR%G7@5W T%}J(UR`KA5](https://user-images.githubusercontent.com/94461675/222453094-3a33b7dc-9c59-496a-b25d-91dd196cb3d6.png)
Maybe not quite complete, but the description in English is enough to prove the problem

**Comment by myron-obsolete-account** [comment]
This is known and not even an issue, the description of config options are not able to be translated and are always english on default.

**Comment by nonamecrackers2** [comment]
This is just how forge configs work, the descriptions cannot be translatable due to how they’re written to a file but I’m sure we could add localization keys in the lang for when rendering them in the menu.

**Comment by Composer-Hu** [comment]
这是没办法汉化的，我改过汉化文件。看不懂的可以问我们，你可以关闭这个话题

**Comment by myron-obsolete-account** [comment]
> 这是没办法汉化的，我改过汉化文件。看不懂的可以问我们，你可以关闭这个话题

uhhhh what
