### ISSUE TITLE
Some little issue of the Guide document.

### ISSUE THREAD

**Issue by anonymoususer923847** [nonamecrackers2/crackers-wither-storm-mod#983]
To nonamecrackers2,
I know this isn't an issue with the mod itself, but it seems like the Guide itself is somewhat outdated (does not reflect the new updates). Is this intentional, or did you forgot it?
Btw,
CONGRATS ON 1M DOWNLOADS!

**Comment by Pandaboi25x** [comment]
it will be updated the devs kinda forgot about it lol

**Comment by nonamecrackers2** [comment]
Yeah I do have the intention of updating it.
