### ISSUE TITLE
Withered Symbionts tainted attack texture thing + a new attack for the symbiont

### ISSUE THREAD

**Issue by Pandaboi25x** [nonamecrackers2/crackers-wither-storm-mod#984]
The withered symbionts have those funny attacks right i decided to make my own textured attacks for him 
here is what i made:
tainted arrow: it could work like a potion arrow like if you hit somebody with it they would get wither sickness (minecraft)
![image](https://user-images.githubusercontent.com/121638798/222509028-18acc7c7-b983-4733-a5df-7ea695425f38.png)
tainted thing that he spawns 
![image](https://user-images.githubusercontent.com/121638798/222509110-b5937b07-e240-4a85-b740-2eafc52e72c8.png)
this thing that makes you fly: it looks bad sorry
![image](https://user-images.githubusercontent.com/121638798/222509209-3b654172-3fc5-4857-92df-7e7ed6e1a9ba.png)
fire charger thing:
![image](https://user-images.githubusercontent.com/121638798/222509260-8e022246-37eb-4357-bce8-c7bbf7f2c699.png)

and uh the last thing is fanmade tainted trident:
![image](https://user-images.githubusercontent.com/121638798/222509314-7f4790fb-e7a1-494a-8744-fa15814cc57d.png)
there is a small chance you can get it pretty much like the arrow attack but harder

**Comment by TheEyeOfGaming** [comment]
tbh i prefer it not having new attack textures, cuz it then would look more like as if the Symbiont uses the Command Block Books power to summon stuff like how you can summon stuff from a command block

**Comment by Pandaboi25x** [comment]
> tbh i prefer it not having new attack textures, cuz it then would look more like as if the Symbiont uses the Command Block Books power to summon stuff like how you can summon stuff from a command block

hmmm true true tho im letting crackers opinion on this

**Comment by myron-obsolete-account** [comment]
I personally like this but just as a tip you could smoothen the purple parts out a bit so it has like a "transition" between the normal texture and the purple parts.
P.S.: the things that come out of the ground are called evoker fangs, or in this case just fangs. and the flying things are called shulker pellets. 🍷🗿

Edit: you could also make the border of the fireball texture purple too, would look better I guess?

**Comment by Pandaboi25x** [comment]
> I personally like this but just as a tip you could smoothen the purple parts out a bit so it has like a "transition" between the normal texture and the purple parts. P.S.: the things that come out of the ground are called evoker fangs, or in this case just fangs. and the flying things are called shulker pellets. 🍷🗿
> 
> Edit: you could also make the border of the fireball texture purple too, would look better I guess?

yeaa im not changing it no more💀

**Comment by Resuster** [comment]
Perhaps a purple fire for the fire charge?

**Comment by nonamecrackers2** [comment]
Gonna keep the vanilla textures since it implies more that the symbiont is manifesting these objects using command block power. Also I think a barrage of tridents would be a little bit too overpowered

**Comment by Resuster** [comment]
Fine with me

**Comment by Pandaboi25x** [comment]
darn 😔 oh well
