### ISSUE TITLE
Spawning the wither storm crashes your game

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#986]
I tried spawning the wither storm during a test run and it crashed my minecraft
From there on everything began breaking (I'll list it I'm order)
After attempting to load back on the world it got stuck at 100% and I needed to restart

After attempting to spawn the wither storm (agian) it stopped spawning no matter if I broke all skulls and replaced them

After reading an item name it just gave me a server closed screen and brought me to the server list

The first problem happened agian but this time i couldn't restart without task manager (game probably froze)

From this point on I posted this bug report

While I was passively walking it crashed out of nowhere and my pc started performing badly (never done This before since this is the new pc)
After this I got sick of it and made a new world

(I'll edit this when something else occurs)

I joined the world and spawning the wither storm worked, I guess this glitch happens randomly?
Version of mod: 2.2
Minecraft version: 1.18.2

**Comment by Bloxxify1520** [comment]
Whats your PC specs?

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> Whats your PC specs?

I would expect my old pc to do this but for reference
Rtx 3070
Also java edition is optimized badly so don't be too surprised if this happens to you

Not using optifine or any shades either

**Comment by Globalfirestorm10** [comment]
Hey there, mind sending off the crash report? We just need it to assist you with your issue

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
I suppose this is a random glitch because it completely stopped now

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
> Hey there, mind sending off the crash report? We just need it to assist you with your issue

Extremely sorry but at the time I had too many crashes enabled and it stopped happening ever since that one time meaning I couldn't catch the crash report
Although if this ever happens agian I'll get the crash report
