### ISSUE TITLE
Wither storm theme not playing

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#987]
Ever since I updated to 2.2 the wither storm theme stopped playing when I spawned in the wither storm

Minecraft version: 1.18.2

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment]
After scrolling to find what's causing another glitch I found that it's an option so

**Comment by nonamecrackers2** [comment]
Yeah, the option was changed and got defaulted back to false
