### ISSUE TITLE
Wither Storm body dissapearing

### ISSUE THREAD

**Issue by Stanislav228Bebrochka** [nonamecrackers2/crackers-wither-storm-mod#989]
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.19.3

**Mod version**
3.2

**Describe the bug**
When wither storm destroying his body instantly dissapearing, only tentacles and heads have "desroying animation" but his body have few pixels left.

**To Reproduce**

**Crash Reports / Logs**
No crashes.

**Is OptiFine installed?**
No

**Screenshots**
![2023-03-02](https://user-images.githubusercontent.com/126867385/222765267-d615911e-983e-4314-8612-734472290059.png)

**Comment by Stanislav228Bebrochka** [comment]
I'm sorry for the particle effect, but it's still clear in the screenshot that his body is gone, and the heads and tentacles remain.

**Comment by TeaCupsTeaPots** [comment]
this is a duplicate

**Comment by Stanislav228Bebrochka** [comment]
Oh okay…

**Comment by nonamecrackers2** [comment]
#939
