### ISSUE TITLE
[Idea] Make Wither Storm bossbar reflect Command Block bossbar

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#990]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
Describe what you want in the mod. Make sure this was not already suggested.

**ONLY ONE FEATURE REQUEST PER ISSUE**

that’s the whole idea, when the command block is hit the wither storm gets damaged for 1/4 max health, and it can no longer regen. It would be an interesting way to reflect the command block’s bossbar in the overworld.

**Comment by Globalfirestorm10** [comment]
You know what you could do? As soon as the command block takes damage, then the storm can take that set amount of damage as well

**Comment by Asteroid4** [comment]
> You know what you could do? As soon as the command block takes damage, then the storm can take that set amount of damage as well

Yea! And it will flash red when it does.

**Comment by Asteroid4** [comment]
i just realized this is literally an old issue i made like a year ago (#529)

**Comment by Globalfirestorm10** [comment]
These are both similar, but im not sure if this should count as a duplicate or not

**Comment by nonamecrackers2** [comment]
Yeah, since it's pretty much the same idea I'll close this in favor for the old one. Good catch
