### ISSUE TITLE
When I try to download latest version it gives me the old one

### ISSUE THREAD

**Issue by AdmiralPotatoCat** [nonamecrackers2/crackers-wither-storm-mod#991]

**Comment by myron-obsolete-account** [comment]
This... is not enough information. How are we supposed to help you?

**Comment by Globalfirestorm10** [comment]
> 
> 
> 
> 
> 1.19.2
> 
> The version of Minecraft the mod is running on
> 
> 
> 
> 3.1.1.1
> 
> The version of the mod I am using
> 
> 

As moron said, we cannot help you, as you've given us squat.please provide more info, such as screenshots, descriptions, etc

**Comment by V0calgiant12** [comment]
Okay, I'm going to try to make sense of the info given, you're trying to download the latest version of the mod, which is on 1.19.3 and 1.18.2 ONLY, but you have not been informed of this and think that the latest 1.19.2 version of the mod has the new update, however, it doesn't. So you're going to have to either update to 1.19.3 or downgrade to 1.18.2

**Comment by nonamecrackers2** [comment]
The 1.19.2 version is no longer supported, the update only exists on 1.19.3 and 1.18.2. 1.19.2 was updated to fix a critical crash issue. Reasoning to why 1.19.2 won't be updated with the new features:

![image](https://user-images.githubusercontent.com/105086648/222931344-871fe623-c875-4242-abcf-575e8af03aee.png)
