### ISSUE TITLE
Wither Spread

### ISSUE THREAD

**Issue by Aimyx** [nonamecrackers2/crackers-wither-storm-mod#992]
***Please read the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Description of feature**
If The wither storm in kept in a general area for an extended period of time, random blocks should be turned into withered variants, opening up some farming possibilities for it. This would show the wither storm's "withering effect" to more than just the bowels and entities.

**ONLY ONE FEATURE REQUEST PER ISSUE**

**Comment by nonamecrackers2** [comment]
#936

**Comment by MoRoN222** [comment]
> #411

uhm thats not the same suggestion...

**Comment by nonamecrackers2** [comment]
Meant to put 441, thanks for catching that

**Comment by MoRoN222** [comment]
> Meant to put 441, thanks for catching that

Oh ok. You're welcome I guess?
