### ISSUE TITLE
Destroying nether portals

### ISSUE THREAD

**Issue by AdmiralPotatoCat** [nonamecrackers2/crackers-wither-storm-mod#993]
If a wither storm sees you enter a portal, it will go to the portal and destroy it with tentacles
However when your in the nether you can find the order of the stone railway travel system thing which will allow you to escape if the wither storm destroys your nether portal whilst you have no blocks of obsidian

**Comment by myron-obsolete-account** [comment]
Duplicate of #49 and #267 please close this.

**Comment by FrozenDragon0** [comment]
This has already been suggested and was denied, also duplicates of the mentioned issues above by MoRoN222.

**Comment by AdmiralPotatoCat** [comment]
oh srry didn't realise

**Comment by myron-obsolete-account** [comment]
It's fine

**Comment by myron-obsolete-account** [comment]
We do be dealing with duplicates every day duh this feels like a job
