### ISSUE TITLE
Withered/Sickened Sun

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#994]
**Description of feature**
Okay so the Wither Storm literally spreads it's withering effect everywhere, right? Now how about this: let's say, the Wither Storm emits another kind of withering effect that goes to outer space and affects other objects such as stars and different planets. The sun is made out of gas. Nothing but flamin' hot che- I mean gas. The withering effects the WS emits could sicken the sun, which then turns purple-ish instead of yellow. It actually blends in very well with the dark sky effect when the WS is at its last phases.
![2023-03-05_18 01 37](https://user-images.githubusercontent.com/53058491/222975078-84d6d0aa-3651-4137-a862-c1a181d39f69.png)

When the sun turns into its withered state, a loud otherworldly rumbling sound could play, which is basically sounds that the sun emits, that travel through space 'n' time and eventually hit on earth.
The sun then emits a light that, as stated above, is now purple-ish instead of yellow. So of course the moon is affected by the lighting of it.
![2023-03-05_18 01 31](https://user-images.githubusercontent.com/53058491/222975178-96c379e3-744b-41b8-a6b3-32619705db57.png)

The sky darkening effect could then be applied to everywhere on the world, since the sun is less bright and sickened. Poor sun :(

Oh and I forgot to say that the sun sickening process could begin when the WS is at phase 7.

TEXTURES:
![sun](https://user-images.githubusercontent.com/53058491/222975295-77911079-5d4e-40de-a74f-5c8f0c0a0cad.png)
![moon_phases](https://user-images.githubusercontent.com/53058491/222975296-1cd4bd47-d541-41e8-ac14-4075ce2b4034.png)

**Comment by Globalfirestorm10** [comment]
I like this idea, I think you overcomplicated it though

**Comment by myron-obsolete-account** [comment]
wdym

**Comment by Bloxxify1520** [comment]
I think you perfectly described this, and i love the idea

**Comment by Globalfirestorm10** [comment]
> wdym

nvm

**Comment by Globalfirestorm10** [comment]
Also correct me if im wrong, but doesn't the skies "darkening" effect take place in stage 6?

**Comment by myron-obsolete-account** [comment]
> Also correct me if im wrong, but doesn't the skies "darkening" effect take place in stage 6?

I think so yeah.

> I think you perfectly described this, and i love the idea

Thanks.

---

I also forgot to add that the darkened sun effect could last for lets say 5 more minutes after the WS dies because it still takes some time for the sun to calm down and get that withered effect off of it, since the WS doesn't continiously force a withering effect to it anymore.

**Comment by GrandmaPork** [comment]
The sun is unbelievably far away. It’d be better if the sky darkening effect just tinted the atmosphere to make the sun appear purple (that’d be the lore explanation, cracker can just add the purple sun and moon to the sky darkening effect)

**Comment by BluePineappleGuy** [comment]
it would be cool after the storm exploded the sky brightened slowly and the withered sun went away

**Comment by myron-obsolete-account** [comment]
> it would be cool after the storm exploded the sky brightened slowly and the withered sun went away

thats what my idea was, kind of

**Comment by NinjaSam5399** [comment]
Pls Confirm it, its cool!

**Comment by Globalfirestorm10** [comment]
Have some patience, crackers needs time to decide whether this would be feasible (and if this would fit in with the mod).

**Comment by nonamecrackers2** [comment]
I think this is an interesting idea but I don't feel it would really fit in with the mod. It could totally be an interesting modpack/addon idea to the mod though

**Comment by myron-obsolete-account** [comment]
:(

**Comment by NinjaSam5399** [comment]
NOOOOOOOOOOOO!!
