### ISSUE TITLE
Putting a locked Amulet into crafting table outputs locked Amulet

### ISSUE THREAD

**Issue by myron-obsolete-account** [nonamecrackers2/crackers-wither-storm-mod#995]
**Minecraft version**
1.19.3

**Mod version**
3.2

**Describe the bug**
When I put a locked amulet in a crafting table, it outputs a locked amulet. Intended?

**To Reproduce**
1. Lock amulet in crafting table
2. Try to unlock it in crafting table
3. See error

**Crash Reports / Logs**
N/A

**Is OptiFine installed?**
No.

**Screenshots**
N/A

**Comment by myron-obsolete-account** [comment]
What does "needs confirming" mean btw

**Comment by nonamecrackers2** [comment]
Bugs that need confirming

**Comment by myron-obsolete-account** [comment]
> Bugs that need confirming

Yah I saw that description too but like what do you mean by confirming? Confirming that the bug actually exists or what?

**Comment by nonamecrackers2** [comment]
It’s for myself to keep track of which bugs I need to try to replicate

**Comment by myron-obsolete-account** [comment]
Ah ok.

**Comment by nonamecrackers2** [comment]
Will be fixed in 2.2.1/3.2.1
