### ISSUE TITLE
[Idea] Make F-Bomb requirement configurable.

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#996]
Basically, if a new configuration option, "Require F-Bomb to open hole in head", is set to false, the phase 5.5 wither storm will grow as big as a phase 7 storm on its own, but it wont split into 3. Then, the hole in the wither storm head will appear.

**Comment by myron-obsolete-account** [comment]
I like the idea of the WS keep growing.

**Comment by Globalfirestorm10** [comment]
I like this idea, but the question is, how exactly could the player get to the bowels in this phase?

**Comment by Globalfirestorm10** [comment]
Tbh, the hole in it's head wouldn't really make much sense, as there's no identifiable cause for it. However, I have an alternative idea (sort of): The command block starts to become semi-unstable due to the sheer size of the storms body, so it takes internal damage (sort of like an implosion, but obviously not as catastrophic) causing some chunks of the storms' body to fall out. Then, eventually, a path to the bowels is created as a result of these chunks falling out

**Comment by myron-obsolete-account** [comment]
> Tbh, the hole in it's head wouldn't really make much sense, as there's no identifiable cause for it. However, I have an alternative idea (sort of): The command block starts to become semi-unstable due to the sheer size of the storms body, so it takes internal damage (sort of like an implosion, but obviously not as catastrophic) causing some chunks of the storms' body to fall out. Then, eventually, a path to the bowels is created as a result of these chunks falling out

which could also explain why the bowels look like a frickin' maze

**Comment by Globalfirestorm10** [comment]
Yeah, the same I guess goes for the normal phase 6 and 7, the only difference being that the instability and imposions/body breaking is because of the fbomb explosion (and the fact that there are now three separate storms to control, which as i'd imagine, the command block was not made for)

**Comment by Honey-Programming** [comment]
Here is my suggestion: When the Wither Storm grows out of late phase 5, the top get really big. Like REALLY big. The command block cannot handle all this mass and sucks in the surrounding tainted flesh in the bowels to keep it alive. Eventually, it sucks in the front part of the Wither Storm leaving a hole. If you don't enter the bowels and destroy the command block, the Wither Storm will start losing all of it's mass. Once it gets small enough, the command block restabilizes and a sound is played, like the one where the command block in MCSM reactivates. Then the Wither Storm starts growing again, and the cycle repeats. (Unless you blow it up with the formidi-bomb)

**Comment by Honey-Programming** [comment]
The same thing will happen with the phase 7, but now the command block is strong enough to hold even that much mass.

**Comment by nonamecrackers2** [comment]
Considering that the player already has to fight the symbiont twice to get the tools to defeat the command block, fighting the symbiont for a third to just open the hole seems very tedious and boring. This could be something that could be done with datapacks potentially however
