### ISSUE TITLE
[Idea] Give the wither storm segments their own bossbars.

### ISSUE THREAD

**Issue by Asteroid4** [nonamecrackers2/crackers-wither-storm-mod#997]
Title

**Comment by Jackmo2207** [comment]
This would be pointless clutter, you could argue that the main one doesn't even need a bossbar

**Comment by Bloxxify1520** [comment]
> This would be pointless clutter, you could argue that the main one doesn't even need a bossbar

Well, if you have the setting to directly hit the storm its useful

**Comment by Asteroid4** [comment]
Ive thought about it a bit, and i dont think having 3 bossbars would be particularly useful. Not gonna close it incase cracker likes the idea, but i don't really like it.

**Comment by nonamecrackers2** [comment]
The segments don’t need bossbars since the main Wither Storm is meant to encompass both itself and its segments. Having their own boss are would also cause clutter
