### ISSUE TITLE
Alternate "Classic style" bowels

### ISSUE THREAD

**Issue by GoldInvestor1006** [nonamecrackers2/crackers-wither-storm-mod#999]
Simply put, an alternate version of the bowels that resembles the original bowels concept. The bowels in the current version of the mod would stay put for the regular wither storm, but maybe potential alternate versions (chain or repeating) could use this modified layout.

Though if making an alternate version of bowels isn't worth the effort, then consider just bringing back the old tainted dust generation that looked really cool in the original game due to the idea that the command block is a huge power source.

However, I mainly just wanted to share these mockups I have made.
![2023-03-06_23 28 18](https://user-images.githubusercontent.com/31906108/223327690-78bfefa6-8be2-4e55-8d55-82df3e96e19d.png)
![2023-03-06_23 28 32](https://user-images.githubusercontent.com/31906108/223328558-7c4c3291-6e9b-4b22-8cb2-ade03d1dfcd3.png)
![2023-03-06_23 49 01](https://user-images.githubusercontent.com/31906108/223327709-758d9a83-3715-4990-a2ab-f760321ca0fe.png)
![2023-03-06_23 40 14](https://user-images.githubusercontent.com/31906108/223327704-418c8d81-8a46-4ecc-b040-f4afb0a95970.png)

**Comment by nonamecrackers2** [comment]
This could be something that can be done via datapacks/a custom modpack.
